insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"BEL002",
"Mesopotamian religion",
"Sumerian, Akkadian, Babylonian and Assyrian religion",
"belief-tradition",
"People",
"F1.9a",
"WA-MES;WA-IRN;WA-LEV",
"-3500",
"100",
"c.; temple cults to the Parthian period",
"Mesopotamian temples commissioned cult statues, votive figures, foundation deposits and incantation bowls and ran large workshops.",
"stone and copper-alloy votive figures; clay tablets; foundation pegs",
"votive statues; foundation pegs; incantation texts",
"ritual and belief;rule and display;record and writing",
"Assyriologists",
"household cults; the temple-dependent labourers; neighbouring religions",
"sacred",
"Met Open Access (CC0);Cuneiform Digital Library Initiative;Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL003",
"Greco-Roman religion",
"Greek and Roman polytheism",
"belief-tradition",
"People",
"F1.11",
"EU-GRR;AF-EGY;WA-LEV;WA-ANA",
"-800",
"400",
"c.; imperial bans in 390s",
"Greek and Roman cults paid for temples, cult statues, votive offerings and sacrificial equipment, sustaining sculptors, bronze-casters and potters.",
"marble and bronze sculpture; terracotta votives; temple building",
"cult statues; votives; altars; temples",
"ritual and belief;rule and display",
"classicists; ancient authors",
"mystery cults and local deities; enslaved temple workers; Christian destruction and reuse",
"sacred",
"Met Open Access (CC0);Getty Museum Open Content (public-domain images);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL004",
"Norse religion",
"Old Norse religion; heathen Scandinavia",
"belief-tradition",
"People",
"F1.11",
"EU-SCA;EU-BLC",
"200",
"1100",
"c.; conversion 10th–11th c.",
"Norse religion shaped picture stones, amulets such as Thor's hammers, ship burials and carved ornament.",
"stone carving; silver casting; woodcarving",
"picture stones; hammer amulets; ship burials",
"ritual and belief;rule and display",
"historians; Snorri Sturluson (13th c. Christian writer)",
"Sámi religion alongside; enslaved people in burials; modern nationalist misuse",
"funerary;sacred",
"Wikimedia Commons;SMK Denmark (public domain);Nationalmuseum Sweden (public domain)",
"R3",
"F1.16",
"medium",
"Watch for far-right appropriation of symbols.",
"canon_beliefs.csv"
],
[
"BEL005",
"Zoroastrianism",
"Mazdayasna; Parsi and Irani faith",
"belief-tradition",
"People",
"F1.9a;F1.9",
"WA-IRN;AS-CEN;AS-SAS",
"-1000",
"",
"c.; origins debated; continues",
"Zoroastrian practice built fire temples and towers of silence and, among Parsis in India, patronised embroidered gara saris and silver ritual vessels.",
"fire-temple building; silverwork; silk embroidery",
"fire altars; ritual vessels; gara saris",
"ritual and belief;clothing and adornment",
"the community; Iranologists",
"Irani Zoroastrians under persecution; converts' descendants; funerary practice",
"sacred;funerary;living-community",
"Met Open Access (CC0);Wikimedia Commons;community-published site",
"R2",
"F1.16",
"medium",
"Date of Zarathustra debated (c. 1500–500 BCE).",
"canon_beliefs.csv"
],
[
"BEL006",
"Manichaeism",
"Religion of Light",
"belief-tradition",
"People",
"F1.9a;F1.12a;F1.8",
"WA-MES;WA-IRN;AS-CEN;AS-CHN",
"240",
"1600",
"c.; Mani's preaching from 240; last traces in south China c. 16th c.",
"Manichaeans used richly illuminated books and painting as teaching, including silk paintings from Turfan and south China.",
"manuscript illumination; silk painting",
"illuminated fragments; hanging scrolls",
"ritual and belief;record and writing",
"historians; Turfan finds",
"a persecuted faith known mostly from its enemies' texts",
"sacred",
"Wikimedia Commons;International Dunhuang Programme (link out; check terms)",
"R2",
"F1.16",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL007",
"Judaism",
"Jewish religious tradition",
"belief-tradition",
"People",
"F1.9a;F1.11;F1.6;F1.10;THEME",
"GL",
"-1000",
"",
"c.; continues",
"Jewish practice commissions Torah scrolls, ritual silver (Torah ornaments, Hanukkah lamps), synagogue buildings and illuminated Haggadot, often from Jewish and non-Jewish makers alike.",
"scribal writing on parchment; silversmithing; embroidery; illumination",
"Torah scrolls; rimonim; Haggadot; ketubbot",
"ritual and belief;record and writing",
"the community; historians",
"makers barred from guilds in many places; Beta Israel, Yemeni and other non-European traditions; objects looted 1933–45",
"sacred;living-community;conflict-looting",
"Met Open Access (CC0);British Library digitised collections (public-domain items);NYPL Digital Collections (public-domain items);Wikimedia Commons",
"R1",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL008",
"Coptic Orthodox Christianity",
"Coptic Church",
"belief-tradition",
"People",
"F1.6",
"AF-EGY;AF-NUB",
"300",
"",
"c.; continues",
"Coptic monasteries and churches commissioned icons, textiles, carved wood and manuscripts, including the well-known Coptic tapestry-woven tunic fragments.",
"tapestry weaving in wool and linen; icon painting; woodcarving",
"textiles; icons; manuscripts",
"ritual and belief;clothing and adornment;record and writing",
"the Church; historians",
"the dead whose burial textiles fill museums; Muslim makers of church fittings",
"sacred;funerary;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Brooklyn Museum (CC BY where marked);Wikimedia Commons",
"R2",
"F1.16;F1.18",
"high",
"Many \"Coptic textiles\" come from graves.",
"canon_beliefs.csv"
],
[
"BEL009",
"Ethiopian Orthodox Tewahedo Christianity",
"Tewahedo Church",
"belief-tradition",
"People",
"F1.6",
"AF-HRN",
"330",
"",
"c.; Aksumite conversion; continues",
"The Ethiopian church sustains parchment manuscripts, painted icons and diptychs, processional crosses and rock-hewn churches.",
"parchment making; tempera painting; metal casting; rock-cutting",
"manuscripts; icons; crosses; tabots",
"ritual and belief;record and writing;rule and display",
"the Church; historians",
"Muslim and Beta Israel neighbours; tabots that must not be seen by laypeople",
"sacred;living-community;conflict-looting",
"Walters Art Museum (CC0);Met Open Access (CC0);British Library digitised collections (public-domain items);Wikimedia Commons",
"R1",
"F1.16;F1.24",
"high",
"Tabots are never displayed; some taken at Maqdala (1868) have been returned by churches (e.g. Edinburgh 2002); verify others.",
"canon_beliefs.csv"
],
[
"BEL010",
"Eastern Orthodox Christianity (Byzantine rite)",
"Orthodox Church",
"belief-tradition",
"People",
"F1.11;F1.9a",
"EU-BYZ;EU-EER;WA-ANA;WA-LEV;WA-CAU",
"330",
"",
"c.; continues",
"Orthodox practice centres on icons, iconostases, mosaics, frescoes and embroidered liturgical textiles, and its Iconoclast controversy (726–843) fought over images.",
"icon painting in tempera; mosaic; fresco; gold embroidery",
"icons; iconostases; epitaphioi",
"ritual and belief;rule and display",
"the Church; historians",
"Iconoclasts' losses; non-Orthodox subjects; icons taken as war booty",
"sacred;living-community",
"Met Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R1",
"F1.16;F1.14",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL011",
"Latin (Roman) Catholic Christianity",
"Catholic Church; Western Church",
"belief-tradition",
"People",
"F1.11;F1.7;THEME",
"GL",
"300",
"",
"c.; continues",
"Catholic patronage commissioned cathedrals, altarpieces, reliquaries, vestments and devotional prints and, through missions, colonial church art worldwide.",
"stained glass; panel painting; goldsmithing; embroidery; printing",
"altarpieces; reliquaries; vestments; santos",
"ritual and belief;rule and display;record and writing",
"the Church; historians",
"Indigenous and African makers of mission art; Reformation destruction; objects taken from colonised peoples by missionaries",
"sacred;living-community",
"Met Open Access (CC0);Rijksmuseum (CC0);National Gallery of Art Washington (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.17",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL012",
"Protestant Christianities",
"Lutheran, Reformed, Anglican and others",
"belief-tradition",
"People",
"F1.11;F1.7;F1.6;F1.12;THEME",
"GL",
"1517",
"",
"continues",
"Protestant reform destroyed many images (iconoclasm) while promoting printed Bibles, hymnals and plain meeting houses, and missions spread print and dress codes.",
"printing; engraving; plain carpentry",
"Bibles; catechisms; meeting houses",
"ritual and belief;record and writing",
"historians",
"Catholic makers whose work was destroyed; missionised peoples told to abandon their images",
"sacred",
"Rijksmuseum (CC0);Library of Congress (public-domain items);Wikimedia Commons",
"R2",
"F1.16;F1.28",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL013",
"Shakers",
"United Society of Believers in Christ's Second Appearing",
"belief-tradition",
"People",
"F1.7",
"AM-EWD",
"1774",
"",
"continues (very small community)",
"The Shakers made plain furniture, oval boxes and tools whose simplicity later influenced modern designers.",
"joinery; bentwood boxes; broom making",
"chairs; oval boxes; tools",
"ritual and belief;shelter;tools",
"the Shakers themselves; design historians",
"the women who led the society; its celibate community's survival",
"living-community",
"Met Open Access (CC0);Smithsonian Open Access (CC0 items);Library of Congress (public-domain items)",
"R2",
"F1.20;F1.29",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL014",
"Armenian Apostolic Christianity",
"Armenian Church",
"belief-tradition",
"People",
"F1.9a",
"WA-CAU;WA-ANA;WA-IRN",
"301",
"",
"c.; conversion c. 301; continues",
"The Armenian church produced carved khachkar cross-stones, stone churches and illuminated gospels, many destroyed in and after 1915.",
"stone carving; manuscript illumination",
"khachkars; gospels; churches",
"ritual and belief;record and writing",
"the Church; historians",
"makers killed or displaced in the genocide; khachkars destroyed at Julfa (1998–2006)",
"sacred;conflict-looting;living-community",
"Walters Art Museum (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.19a;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL015",
"West Syriac Christianity",
"Syriac Orthodox Church; Jacobite",
"belief-tradition",
"People",
"F1.9a",
"WA-LEV;WA-MES;WA-ANA;AS-SAS",
"500",
"",
"c.; continues",
"Syriac-speaking churches produced illuminated gospels such as the Rabbula Gospels (586) and monasteries such as Deir al-Za'faran.",
"manuscript illumination; stone building",
"gospels; monasteries",
"ritual and belief;record and writing",
"the Church; historians",
"Syriac Christians displaced in 1915 (Sayfo) and since 2003",
"sacred;living-community",
"Wikimedia Commons;British Library digitised collections (public-domain items)",
"R3",
"F1.16",
"medium",
"Rabbula Gospels' confession attribution debated.",
"canon_beliefs.csv"
],
[
"BEL016",
"Church of the East",
"Assyrian Church; \"Nestorian\" (exonym)",
"belief-tradition",
"People",
"F1.9a;F1.12a;F1.8;F1.9",
"WA-MES;WA-IRN;AS-CEN;AS-CHN;AS-SAS",
"410",
"",
"c.; continues as Assyrian Church of the East",
"The Church of the East spread from Mesopotamia to China, leaving the Xi'an stele (781), Turfan paintings and Kerala copper plates.",
"stone inscription; wall painting",
"Xi'an stele; crosses; manuscripts",
"ritual and belief;record and writing",
"the Church; historians",
"\"Nestorian\" is a label by opponents; Syriac Christians of Kerala",
"sacred;living-community",
"Wikimedia Commons",
"R2",
"F1.13",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL017",
"Sunni Islam",
"Ahl al-Sunna",
"belief-tradition",
"People",
"F1.10;THEME",
"GL",
"632",
"",
"continues",
"Sunni practice commissions mosques, minbars, Qur'an manuscripts, calligraphy and endowed (waqf) complexes across the Islamic world.",
"calligraphy; manuscript illumination; architecture; tilework",
"Qur'ans; mosque lamps; minbars",
"ritual and belief;record and writing;rule and display",
"scholars; the community",
"non-Muslim makers of mosque fittings; figurative traditions; diverse regional practice",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons;Qatar Digital Library",
"R1",
"F1.16;F1.28",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL018",
"Shiʻi Islam",
"Twelver, Ismaili and Zaydi traditions",
"belief-tradition",
"People",
"F1.10",
"WA-IRN;WA-MES;WA-ARB;AS-SAS;AF-EGY",
"680",
"",
"c.; continues",
"Shiʻi practice commissioned shrines such as Mashhad and Karbala, Muharram standards (alams) and ta'ziyeh passion-play material.",
"metal standards; tilework; mirror mosaic; textile banners",
"alams; shrine fittings; banners",
"ritual and belief;rule and display",
"scholars; the community",
"Ismaili and Zaydi traditions often subsumed; South Asian Muharram arts",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL019",
"Ibadi Islam",
"Ibadiyya",
"belief-tradition",
"People",
"F1.10",
"WA-ARB;AF-MAG;AF-SWA",
"700",
"",
"c.; continues",
"Ibadi communities in Oman and the M'zab valley built austere mosques and settlements later admired by modernist architects.",
"mudbrick and lime building",
"M'zab towns; mosques",
"ritual and belief;shelter",
"the community; historians",
"M'zab women's weaving; Omani craft",
"living-community",
"Wikimedia Commons",
"R3",
"F1.20;F1.29",
"medium",
"Le Corbusier's interest in M'zab is widely reported.",
"canon_beliefs.csv"
],
[
"BEL020",
"Sufi orders",
"tariqas (Chishti, Mevlevi, Qadiri, Tijani and others)",
"belief-tradition",
"People",
"F1.10;THEME",
"GL",
"900",
"",
"c.; continues",
"Sufi orders commissioned shrines, lodges and devotional objects, from Mevlevi dress and instruments to Mouride portraits in Senegal and Chishti shrine textiles.",
"shrine building; calligraphy; textiles; music",
"shrines; begging bowls (kashkul); banners; portraits",
"ritual and belief;play and music;clothing and adornment",
"members; scholars",
"women and non-elite devotees; suppression in Turkey (1925) and elsewhere",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.17",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL021",
"Theravada Buddhism",
"Southern Buddhism",
"belief-tradition",
"People",
"F1.9",
"AS-SAS;AS-MSE",
"-250",
"",
"c.; continues",
"Theravada communities in Sri Lanka and mainland Southeast Asia commission stupas, Buddha images, palm-leaf manuscripts and merit-making textiles.",
"bronze casting; lacquer and gilding; palm-leaf writing; brick stupas",
"Buddha images; manuscripts; banners",
"ritual and belief;record and writing",
"the sangha; scholars",
"women's merit-weaving; images removed from temples to collections",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL022",
"Mahayana Buddhism",
"Great Vehicle Buddhism",
"belief-tradition",
"People",
"F1.8;F1.9;F1.12a",
"AS-CHN;AS-KOR;AS-JPN;AS-CEN;AS-SAS;AS-MSE",
"100",
"",
"c.; continues",
"Mahayana practice drove cave temples, bronze and wood bodhisattvas, sutra copying and woodblock printing, including the earliest dated printed book (868).",
"woodblock printing; bronze and wood sculpture; sutra copying; cave carving",
"sutras; bodhisattvas; cave temples",
"ritual and belief;record and writing",
"the sangha; scholars",
"lay women patrons; the removal of cave murals and heads to foreign collections",
"sacred;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);National Museum of Korea e-museum (KOGL Type 1);ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R1",
"F1.5;F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL023",
"Vajrayana Buddhism",
"Tantric Buddhism; Tibetan Buddhism",
"belief-tradition",
"People",
"F1.9;F1.8;F1.12a",
"AS-HIM;AS-CHN;AS-CEN;AS-NTH;AS-ISE",
"700",
"",
"c.; continues",
"Vajrayana monasteries commission thangka paintings, gilt-copper images, sand mandalas and ritual implements following precise iconometric rules.",
"thangka painting; gilt-copper casting; appliqué; sand mandala",
"thangkas; images; vajras; mandalas",
"ritual and belief;rule and display",
"the lamas; scholars",
"Newar artists who made much of it; objects sold after 1959; initiation-restricted images",
"sacred;living-community;conflict-looting",
"Met Open Access (CC0);Himalayan Art Resources (link out);Rijksmuseum (CC0);Wikimedia Commons",
"R1",
"F1.16;F1.26",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL024",
"Chan and Zen Buddhism",
"Chan; Seon; Zen",
"belief-tradition",
"People",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"600",
"",
"c.; continues",
"Chan and Zen monasteries shaped ink painting, calligraphy, dry gardens and tea practice.",
"ink painting; calligraphy; garden making; tea ceramics",
"ink paintings; tea bowls; gardens",
"ritual and belief;play and music",
"the monasteries; scholars; D. T. Suzuki's Western framing",
"the Western \"Zen aesthetic\" simplification; lay and commercial makers",
"sacred",
"ColBase Japan (Japan Government Standard Terms);Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.15;F1.20",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL025",
"Shaiva traditions",
"Shaivism",
"belief-tradition",
"People",
"F1.9",
"AS-SAS;AS-HIM;AS-MSE;AS-ISE",
"200",
"",
"c.; continues",
"Shaiva devotion commissioned lingas, temples and processional bronzes such as the Chola Nataraja.",
"lost-wax bronze; granite carving",
"Natarajas; lingas; temples",
"ritual and belief;rule and display",
"devotees; scholars",
"temple servants and dancers; stolen temple images in Western museums",
"sacred;conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL026",
"Vaishnava traditions",
"Vaishnavism",
"belief-tradition",
"People",
"F1.9",
"AS-SAS;AS-MSE;AS-ISE",
"200",
"",
"c.; continues",
"Vaishnava devotion produced Krishna paintings, pichhvai temple hangings and Jagannath imagery.",
"opaque watercolour; temple cloth painting",
"pichhvais; paintings; images",
"ritual and belief;play and music",
"devotees; scholars",
"temple painters of Nathdwara; lower-caste devotees",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL027",
"Shakta traditions",
"Shaktism; Goddess worship",
"belief-tradition",
"People",
"F1.9",
"AS-SAS;AS-HIM",
"500",
"",
"c.; continues",
"Goddess worship shaped Durga festival images of clay made each year and temples to Kali and the Mahavidyas.",
"unfired clay modelling; painting",
"Durga images; temples",
"ritual and belief",
"devotees; scholars",
"Kumartuli image-makers (Kolkata); tantric practice",
"sacred;living-community",
"Wikimedia Commons;Met Open Access (CC0)",
"R3",
"F1.16;F1.22a",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL028",
"Jainism",
"Jain Dharma",
"belief-tradition",
"People",
"F1.9",
"AS-SAS",
"-500",
"",
"c.; continues",
"Jain merchants funded marble temples such as Dilwara and Ranakpur and illustrated Kalpasutra manuscripts.",
"marble carving; manuscript painting; cloth paintings",
"temples; Kalpasutras; pata",
"ritual and belief;record and writing",
"the community; scholars",
"temple carvers; Digambara and Svetambara difference",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.17",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL029",
"Sikhism",
"Sikhi",
"belief-tradition",
"People",
"F1.9",
"AS-SAS",
"1500",
"",
"c.; continues",
"Sikh practice centres on the Guru Granth Sahib, gurdwaras such as the Harmandir Sahib, and arms and dress of the Khalsa.",
"manuscript copying; gilding; weaponry",
"scriptures; gurdwaras; turbans; arms",
"ritual and belief;clothing and adornment",
"the community",
"objects taken 1849; Sikh women's roles",
"sacred;living-community;conflict-looting",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL030",
"Daoism",
"Daojiao",
"belief-tradition",
"People",
"F1.8",
"AS-CHN",
"142",
"",
"c.; organised Daoism from 142; continues",
"Daoist institutions commissioned ritual paintings, robes, talismans and temple images.",
"embroidery; painting; woodblock",
"robes; paintings; talismans",
"ritual and belief",
"priests; scholars",
"local cults; women practitioners",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL031",
"Confucian ritual",
"Ru; Confucian ritual practice",
"belief-tradition",
"People",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN;AS-MSE",
"-500",
"",
"c.; continues",
"Confucian ritual fixed ancestor-hall furniture, ritual bronzes and ceramics, and Korea's Jongmyo royal rites.",
"ritual vessels; lacquer",
"ancestral tablets; ritual vessels",
"ritual and belief;rule and display",
"scholars; states",
"women's labour in ancestral rites; non-elite practice",
"ancestral",
"National Museum of Korea e-museum (KOGL Type 1);Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16",
"medium",
"Treated as ritual practice, not a church.",
"canon_beliefs.csv"
],
[
"BEL032",
"Shinto",
"Kami worship",
"belief-tradition",
"People",
"F1.8",
"AS-JPN",
"700",
"",
"c.; continues",
"Shinto shrines rebuild Ise every 20 years and commission mirrors, swords and festival floats.",
"cypress carpentry; metalwork; float making",
"shrines; mirrors; floats",
"ritual and belief;rule and display",
"priests; scholars; the Meiji state (State Shinto)",
"the Meiji separation of Buddhism; local kami; Ainu and Ryukyu",
"sacred;living-community",
"ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R2",
"F1.16;F1.22a",
"high",
"Ise rebuilding is a case for repair and renewal.",
"canon_beliefs.csv"
],
[
"BEL033",
"Bon",
"Bön; Yungdrung Bon",
"belief-tradition",
"People",
"F1.9",
"AS-HIM",
"1000",
"",
"c.; organised Bon; continues",
"Bon monasteries produce thangkas, images and ritual objects parallel to Buddhist ones.",
"painting; casting",
"thangkas; images",
"ritual and belief",
"the Bon community; scholars",
"pre-Buddhist religion confused with organised Bon",
"sacred;living-community",
"Himalayan Art Resources (link out);Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL034",
"Korean shamanism",
"Muism; mudang practice",
"belief-tradition",
"People",
"F1.8",
"AS-KOR",
"1000",
"",
"c.; continues",
"Korean mudang (shamans) use painted deity portraits, costumes, fans and paper decorations in gut rituals.",
"painting; paper craft; costume",
"musindo paintings; fans; costumes",
"ritual and belief;play and music",
"practitioners; folklorists",
"women practitioners as makers; suppression under Joseon, colonial and modern states",
"sacred;living-community",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons",
"R3",
"F1.16;F1.29",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL035",
"Chinese popular religion",
"folk religion; shenism",
"belief-tradition",
"People",
"F1.8",
"AS-CHN;AS-ISE;AS-MSE",
"500",
"",
"c.; continues",
"Popular religion drives paper offerings burned for the dead, temple images, door gods and New Year prints.",
"paper craft; woodblock printing; temple carving",
"paper offerings; door gods; nianhua",
"ritual and belief;food and storage",
"practitioners; ethnographers",
"diaspora temples; paper-offering makers",
"funerary;living-community",
"Wikimedia Commons;National Palace Museum Taipei Open Data",
"R3",
"F1.16;F1.29",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL036",
"Shamanic traditions of Siberia and the steppe",
"Siberian shamanism; Tengrism (steppe revival term)",
"belief-tradition",
"People",
"F1.12a",
"AS-NTH;AS-CEN;AM-ARC",
"1000",
"",
"c.; long histories, documented from 17th c.; continue and revive after 1991",
"Siberian and steppe practitioners (Evenki, Sakha, Buryat, Tuvan and others) make frame drums, costumes hung with iron pendants and spirit figures that are also regular targets of collecting.",
"frame-drum making; skin sewing; iron pendant forging; carved spirit figures",
"drums; costumes; spirit figures",
"ritual and belief;play and music;care and access",
"anthropologists; the Evenki word šaman borrowed via Russian into a general term",
"the term's flattening of distinct peoples' practices; Soviet persecution and confiscations; objects held in St Petersburg and elsewhere",
"sacred;Indigenous-community;conflict-looting",
"Wikimedia Commons",
"R3",
"F1.16;F1.24",
"medium",
"Term \"shamanism\" is an outsiders' generalisation; use each people's own terms where possible.",
"canon_beliefs.csv"
],
[
"BEL037",
"Mesoamerican religion",
"Mesoamerican ritual traditions",
"belief-tradition",
"People",
"F1.7",
"AM-MES;AM-CAM",
"-1200",
"1550",
"c.; Olmec period to conquest; many practices continue in syncretic forms",
"Mesoamerican ritual shaped codices of the 260-day calendar, ball courts, incense burners, offerings of jade and feathers, and bloodletting implements.",
"screenfold painting; jade carving; featherwork; ceramic incense burners",
"codices; offerings; ball-game gear",
"ritual and belief;record and writing;play and music",
"scholars; colonial friars (Sahagún, Landa)",
"Indigenous present-day practitioners; destruction of codices by missionaries (Maní 1562)",
"sacred;Indigenous-community",
"Met Open Access (CC0);LACMA (public-domain images);Wikimedia Commons",
"R1",
"F1.16;F1.28;F1.30",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL038",
"Andean religion (huacas)",
"huaca worship; Andean ritual traditions",
"belief-tradition",
"People",
"F1.7",
"AM-AND",
"-3000",
"",
"c.; continues in syncretic forms",
"Andean ritual made offerings of cloth, spondylus shell, miniature figures and keros to huacas (sacred places and beings) and ancestors.",
"tapestry offerings; spondylus working; metal miniatures",
"offering textiles; figurines; keros",
"ritual and belief;exchange and value",
"scholars; colonial \"extirpation of idolatries\" records",
"the huacas themselves as persons; present Quechua and Aymara practice",
"sacred;funerary;Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL039",
"Pueblo religion (katsina)",
"Hopi and Zuni katsina practice",
"belief-tradition",
"People",
"F1.7",
"AM-WST",
"1300",
"",
"c.; continues",
"Hopi and Zuni carvers make katsina figures (tihu) and masks, the latter ceremonial and not for sale or display.",
"cottonwood root carving; painting",
"tihu figures; masks",
"ritual and belief",
"the Hopi and Zuni; anthropologists",
"masks sold at auction against tribal objection; carvers as named artists",
"sacred;Indigenous-community;living-community",
"community-published site",
"R2",
"F1.16;F1.24;F1.26",
"high",
"Do not display masks.",
"canon_beliefs.csv"
],
[
"BEL040",
"Ghost Dance",
"Nanissáanah",
"belief-tradition",
"People",
"F1.7",
"AM-WST",
"1889",
"1891",
"c.; revival 1889–91",
"Ghost Dance followers painted muslin and hide shirts and dresses, some taken from the dead at Wounded Knee (1890).",
"painting on muslin and hide",
"shirts; dresses",
"ritual and belief;clothing and adornment",
"Wovoka's followers; James Mooney",
"the Wounded Knee dead; Lakota requests for return",
"sacred;funerary;conflict-looting;Indigenous-community",
"Smithsonian Open Access (CC0 items)",
"R3",
"F1.24;F1.19a",
"high",
"Glasgow returned a Ghost Dance shirt in 1999.",
"canon_beliefs.csv"
],
[
"BEL041",
"Native American Church",
"peyote religion",
"belief-tradition",
"People",
"F1.7",
"AM-WST;AM-EWD",
"1918",
"",
"incorporated 1918; continues",
"Native American Church members make beaded ritual fans, gourd rattles and staffs for peyote meetings.",
"beadwork (gourd stitch); featherwork",
"fans; rattles; staffs",
"ritual and belief;play and music",
"members; the US courts",
"ritual use protected only from 1994; sacred content",
"sacred;Indigenous-community",
"Smithsonian Open Access (CC0 items)",
"R3",
"F1.16",
"medium",
"",
"canon_beliefs.csv"
],
[
"BEL042",
"Yorùbá religion",
"Òrìṣà worship; Ifá divination; diaspora branches include Lucumí (Santería/Regla de Ocha) in Cuba",
"belief-tradition",
"People",
"F1.6;F1.7",
"AF-GUI;AM-CAR;AM-LAT",
"1000",
"",
"c.; continues in West Africa and the Americas",
"Òrìṣà shrines and Ifá diviners commission carved divination trays and bowls, beaded crowns, twin figures (ère ìbejì) and shrine sculpture.",
"wood carving; beadwork; brass",
"Ifá trays; ère ìbejì; beaded crowns",
"ritual and belief;rule and display",
"practitioners; scholars",
"named carvers (e.g. Olowe of Ise); diaspora practitioners",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R1",
"F1.16;F1.26",
"high",
"Ifá is on UNESCO's intangible heritage list (2008).",
"canon_beliefs.csv"
],
[
"BEL043",
"Vodun (Fon, Ewe and Gbe-speaking peoples)",
"Vodún; Vodoun",
"belief-tradition",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"c.; older roots; continues in Benin, Togo and Ghana",
"Vodun practice sustains shrines, bocio empowered figures, appliqué and metal emblems for deities, some of which also served the Dahomey court.",
"wood carving; assemblage with cord and cloth; iron and brass forging",
"bocio; shrine objects; asen altars",
"ritual and belief;care and access;rule and display",
"practitioners; scholars (Blier)",
"practitioners' own names for objects; objects removed as \"fetishes\"; Vodun's link to the Atlantic trade framed without people",
"sacred;living-community;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.24",
"high",
"Benin's national Vodun day (10 January) since 1996.",
"canon_beliefs.csv"
],
[
"BEL044",
"Akan religion",
"Akan traditional religion",
"belief-tradition",
"People",
"F1.6",
"AF-GUI",
"1500",
"",
"c.; continues",
"Akan religious practice includes shrines to abosom, akuaba figures carried for fertility, and terracotta memorial heads made by women potters.",
"wood carving; terracotta modelling; brass casting",
"akuaba; memorial heads (nsodie); shrine vessels",
"ritual and belief;care and access",
"practitioners; scholars",
"women potters of memorial heads; Christian and Muslim Akan; objects dug from burial sites for the art market",
"sacred;funerary;living-community;conflict-looting",
"Met Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R2",
"F1.16;F1.18;F1.24",
"high",
"Memorial heads are often looted from graves.",
"canon_beliefs.csv"
],
[
"BEL045",
"Kongo religion and minkisi",
"Kongo cosmology",
"belief-tradition",
"People",
"F1.6;F1.7",
"AF-CEN;AM-CAR;AM-LAT",
"1400",
"",
"c.; continues; carried to the Americas",
"Kongo ritual specialists (nganga) assembled minkisi, including nail-driven nkisi nkondi, and Kongo grave decoration travelled to the Americas with enslaved people.",
"wood carving; assemblage with medicines; nailing; grave decoration",
"minkisi; nkondi; grave goods",
"ritual and belief;care and access;rule and display",
"practitioners; scholars (MacGaffey, Thompson)",
"nganga as named makers; \"fetish\" framing; people whose knowledge crossed the Atlantic in slavery",
"sacred;living-community;conflict-looting;human-flow",
"Met Open Access (CC0);AfricaMuseum Tervuren collection search (link out);Wikimedia Commons",
"R1",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL046",
"Candomblé",
"Candomblé Ketu, Jeje and Angola nations",
"belief-tradition",
"People",
"F1.7",
"AM-LAT",
"1830",
"",
"c.; earliest terreiros in Bahia in the 19th c.; continues",
"Candomblé houses make beaded necklaces (fios de conta), ritual dress, metal tools and altars for the orixás, inkices and voduns.",
"glass beadwork; embroidery and lace; forged and cut metal",
"necklaces; ritual dress; ferramentas",
"ritual and belief;clothing and adornment",
"practitioners (povo de santo); scholars",
"women priestesses (mães-de-santo) as leaders and makers; police seizures (Rio objects transferred to Museu da República in 2020)",
"sacred;living-community;conflict-looting",
"Wikimedia Commons;community-published site",
"R2",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL047",
"Haitian Vodou",
"Vodou; Vodun (Haiti)",
"belief-tradition",
"People",
"F1.7",
"AM-CAR",
"1700",
"",
"c.; continues",
"Haitian Vodou artists sew sequinned drapo (flags) for the lwa, cut oil-drum iron sculpture and draw vèvè ground designs.",
"sequin and bead embroidery; cut steel drums; cornmeal drawing",
"drapo; metal sculpture; vèvè",
"ritual and belief;play and music",
"practitioners; scholars",
"the anti-superstition campaigns (1941–42) that destroyed objects; Hollywood stereotypes",
"sacred;living-community",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R2",
"F1.16;F1.29",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL048",
"Rastafari",
"Rastafari movement",
"belief-tradition",
"People",
"F1.7;F1.6",
"AM-CAR;AF-HRN",
"1930",
"",
"continues",
"Rastafari shaped Jamaican dress (crocheted tams), wood carving and reggae record-sleeve art in red, gold and green.",
"crochet; wood carving; graphic design",
"tams; carvings; record sleeves",
"ritual and belief;clothing and adornment;play and music",
"members; scholars",
"women in the movement; persecution such as the Coral Gardens incident (1963); commercial use of its colours",
"living-community",
"Wikimedia Commons",
"R3",
"F1.21;F1.4",
"medium",
"\"Rastafarianism\" is an outsider term.",
"canon_beliefs.csv"
],
[
"BEL049",
"Malagasy ancestral religion",
"razana practice; famadihana",
"belief-tradition",
"People",
"F1.6",
"AF-MAD",
"1500",
"",
"c.; continues",
"Malagasy ancestor practice wraps the dead in silk lamba mena during famadihana reburials, and in the south carved aloalo posts mark Mahafaly tombs.",
"silk weaving; wood carving; tomb building",
"lamba mena; aloalo; tombs",
"ritual and belief;clothing and adornment",
"practitioners; anthropologists",
"Christian Malagasy; aloalo removed from tombs for sale",
"funerary;sacred;living-community;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.18",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL050",
"Aboriginal Dreaming",
"the Dreaming; Jukurrpa (Warlpiri); Tjukurpa (Anangu); many other language terms",
"belief-tradition",
"People",
"F1.12",
"OC-AUS",
"-50000",
"",
"deep time, as the communities describe it; continues",
"Aboriginal law and story are expressed through rock art, body and ground designs, bark and acrylic painting and ceremonial objects, with rules about who may make and see them.",
"ochre painting; bark painting; acrylic painting; fibre",
"rock art; paintings; ceremonial objects",
"ritual and belief;record and writing;rule and display",
"Aboriginal communities themselves; \"Dreaming/Dreamtime\" was coined by outsiders (Spencer and Gillen, Stanner)",
"restricted and secret-sacred knowledge; distinct language groups flattened into one term; communities' own words",
"Indigenous-community;sacred",
"Museums Victoria Collections (CC BY or public domain where marked);community-published site",
"R1",
"F1.16;F1.24;F1.26",
"medium",
"Use each community's own term; restricted objects never displayed.",
"canon_beliefs.csv"
],
[
"BEL051",
"Māori customary and spiritual practice",
"tikanga Māori; tapu and noa",
"belief-tradition",
"People",
"F1.12",
"OC-POL",
"1300",
"",
"c.; since settlement of Aotearoa; continues",
"Tikanga governs how whakairo (carving), raranga (weaving) and tā moko are made and how taonga (treasured objects) are cared for, including their return.",
"wood carving; flax weaving; tattooing; greenstone working",
"taonga; wharenui; cloaks; hei-tiki",
"ritual and belief;clothing and adornment;rule and display",
"Māori; iwi and hapū themselves",
"iwi as peoples not states; distinct iwi practices; toi moko (preserved heads) repatriation",
"Indigenous-community;sacred;ancestral",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked);community-published site",
"R2",
"F1.16;F1.24;F1.26",
"high",
"Not a \"religion\" in the church sense: customary law and practice.",
"canon_beliefs.csv"
],
[
"BEL052",
"Hawaiian religion",
"ʻaikapu; Hawaiian akua worship",
"belief-tradition",
"People",
"F1.12",
"OC-POL",
"1000",
"1819",
"c.; kapu system abolished 1819; practices revived since 1970s",
"Hawaiian religion commissioned carved temple images (kiʻi), feathered god images (akua hulu manu) and heiau.",
"wood carving; featherwork on basketry; stone platform building",
"kiʻi; feathered images; heiau",
"ritual and belief;rule and display",
"practitioners; historians (Kamakau, Malo)",
"images burned in 1819; present Hawaiian practitioners; objects in Western museums",
"sacred;Indigenous-community;conflict-looting",
"community-published site;Smithsonian Open Access (CC0 items)",
"R2",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL053",
"Sámi religion",
"noaidi practice",
"belief-tradition",
"People",
"F1.11",
"EU-SCA",
"500",
"",
"c.; suppressed from 17th c.; revived",
"Sámi noaidi used painted frame drums, many confiscated by Lutheran authorities, one of which was returned from Denmark in 2023.",
"frame drums with alder-bark paint; carving",
"drums; sieidi stones",
"ritual and belief;play and music",
"Sámi; missionaries' records",
"Sámi across four states; the drums' owners (e.g. Bendix Ivarsen's drum taken 1691)",
"sacred;Indigenous-community;conflict-looting",
"Finna.fi (CC BY where marked);Wikimedia Commons",
"R2",
"F1.16;F1.24",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL054",
"Baháʼí Faith",
"Bahá'í",
"belief-tradition",
"People",
"F1.10;THEME",
"WA-IRN;WA-LEV;GL",
"1863",
"",
"continues",
"The Baháʼí Faith commissions terraced gardens and nine-sided temples such as the Lotus Temple in Delhi (1986).",
"reinforced concrete; marble cladding; garden design",
"houses of worship; gardens",
"ritual and belief;shelter",
"the community",
"persecution in Iran; local architects",
"living-community;sacred",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_beliefs.csv"
],
[
"BEL055",
"Malagan (New Ireland)",
"malanggan; malangan",
"belief-tradition",
"People",
"F1.12",
"OC-MEL",
"1800",
"",
"c.; documented from the 19th c., older roots; continues",
"Malagan ceremonies in New Ireland commission carved and painted figures and friezes to honour the dead, made to be displayed once and then left to decay or, from the colonial period, sold, which is why museums hold so many.",
"wood carving; painting with ochres and lime; fibre",
"malagan figures; friezes; masks",
"ritual and belief;rule and display",
"New Ireland communities; anthropologists (Küchler)",
"carvers' rights to specific designs (owned as intellectual property); objects meant to decay; communities' present practice",
"funerary;sacred;Indigenous-community;living-community",
"Met Open Access (CC0);Auckland Museum Collections Online (CC BY where marked);Wikimedia Commons",
"R2",
"F1.16;F1.24;F1.22a",
"high",
"A ceremonial complex rather than a religion; design rights are transmitted and owned.",
"canon_beliefs.csv"
],
[
"CIV001",
"Egyptian",
"Ancient Egypt; Pharaonic Egypt; Kemet (self-name, 'the black land')",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-EGY",
"-3100",
"-30",
"c. 3100 BCE (unification) to 30 BCE (Roman annexation); Predynastic before and Roman/Coptic continuities after",
"A state-organised craft system in stone, faience, linen, papyrus and metal whose workshops, tools and named workers are unusually well documented.",
"stone carving; faience; linen weaving; papyrus making; copper-bronze casting; gilding; mud brick",
"statues; stelae; coffins; faience vessels; jewellery; papyri; linen; furniture",
"ritual and belief;rule and display;record and writing;clothing and adornment;shelter",
"Greek and Roman writers; Egyptology from Champollion (1822) on; museums; national heritage bodies",
"Nubian neighbours (and the Kushite 25th Dynasty, often cast as 'foreign'); Libyan/Amazigh and Levantine residents and captives; forced and conscripted labour; the non-elite village makers (e.g. Deir el-Medina workers named individually); Predynastic, Coptic and Islamic Egypt; present-day Egyptians, whose connection is often cut by 'Egyptomania' framing",
"funerary;sacred;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);British Museum collection online (link out);Wikimedia Commons;PeriodO",
"R2",
"F1.3;F1.5;F1.24",
"high",
"Existing in project. Much museum material is from burials: default-exclude human remains and flag funerary objects.",
"canon_civilisations.csv"
],
[
"CIV002",
"Nubian / Kushite",
"Kush; Kerma, Napatan and Meroitic Kush; Ta-Seti",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-NUB;AF-EGY",
"-2500",
"350",
"c. 2500 BCE (Kerma) to c. 350 CE (end of Meroë); Christian Nubian kingdoms follow",
"Nubian workshops produced Kerma polished pottery, Meroitic painted ceramics, gold work and a pyramid-building tradition distinct from Egypt's.",
"black-topped and polished pottery; goldsmithing; iron smelting (Meroë); sandstone carving; faience",
"pottery; jewellery; pyramids; offering tables; inscriptions in Meroitic script",
"rule and display;ritual and belief;clothing and adornment;exchange and value;record and writing",
"Egyptian texts (as 'Kush'); George Reisner and 20th-century Egyptology; Sudanese archaeology; museums",
"Treated as Egypt's periphery rather than a centre; C-Group, Pan-Grave and Medjay pastoralists; Christian Nubian kingdoms (Nobadia, Makuria, Alwa); present-day Nubians displaced by the Aswan High Dam (1960s); Meroitic as a still largely untranslated language",
"funerary;living-community;conflict-looting",
"Met Open Access (CC0);British Museum collection online (link out);Wikimedia Commons;open-access excavation reports;PeriodO",
"R2",
"F1.3;F1.5;F1.24",
"high",
"Members: ARC Kerma, A-Group, C-Group, Pan-Grave, X-Group. Boston MFA holds Reisner material but images are not open.",
"canon_civilisations.csv"
],
[
"CIV003",
"Aksumite",
"Axumite; Kingdom of Aksum",
"civilisation-as-commonly-named",
"Composite",
"F1.6;F1.9a",
"AF-HRN;WA-ARB",
"50",
"940",
"c. 1st–10th century CE; conversion to Christianity 4th century",
"Aksum minted gold, silver and bronze coins, raised monolithic stelae and wrote in Ge'ez, trading across the Red Sea.",
"monolith quarrying and carving; coin minting; stone architecture; ivory",
"stelae; coins; inscriptions; pottery; church architecture",
"rule and display;exchange and value;record and writing;ritual and belief",
"Greek and Roman sources (Periplus); European travellers; Ethiopian national history; UNESCO (Aksum, 1980)",
"The pre-Aksumite D'mt period and South Arabian links; pastoralists and the Beja; enslaved people traded across the Red Sea; Ethiopian Orthodox communities for whom the sites remain sacred; later Zagwe and Solomonic periods",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"F1.3;F1.13",
"high",
"Stelae at Aksum are living sacred landscape; the Aksum obelisk was taken to Rome 1937 and returned 2005 (restitution case).",
"canon_civilisations.csv"
],
[
"CIV004",
"Swahili",
"Swahili coast; Swahili city-states; Waswahili",
"civilisation-as-commonly-named",
"Composite",
"F1.6;F1.10",
"AF-SWA;AF-MAD",
"800",
"",
"c. 8th century CE to present; stone towns flourish c. 1000–1500",
"Coral-stone towns, carved doors, textiles and imported ceramics show African coastal makers working within Indian Ocean trade.",
"coral-stone and lime building; wood carving; weaving; bead-making; iron working",
"carved doors; mosques and tombs; pillar tombs; textiles; coins; beads",
"shelter;exchange and value;ritual and belief;rule and display;transport",
"Colonial historiography (often as 'Arab' or 'Persian' colonies); later African archaeology (Chittick, Horton, Chami); Swahili communities",
"The inland peoples who supplied ivory, gold and grain; enslaved people traded through the coast; the colonial framing that denied African authorship; present-day Swahili-speaking communities of Kenya, Tanzania, Mozambique and Comoros",
"living-community;human-flow",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection online (link out);open-access excavation reports;UNESCO World Heritage listing (link out)",
"R2",
"F1.3;F1.13",
"high",
"Existing in project. Slave trade must be shown as people with content note.",
"canon_civilisations.csv"
],
[
"CIV005",
"Great Zimbabwe",
"Zimbabwe culture; Dzimba-dza-mabwe",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-SOU",
"1100",
"1450",
"c. 1100–1450 CE at the main site; wider Zimbabwe tradition c. 1200–1800",
"Dry-stone walling without mortar, soapstone carving and gold trade connected southern African makers to the Indian Ocean.",
"dry-stone walling; soapstone carving; gold working; iron smelting; cattle husbandry",
"enclosure walls; soapstone birds; gold beads; imported glass and ceramics",
"rule and display;shelter;exchange and value;ritual and belief",
"Shona oral tradition; colonial writers who denied African authorship (Rhodesian 'Phoenician/Sheba' myth); Gertrude Caton-Thompson (1929) and later African archaeology; UNESCO (1986)",
"The broader Zimbabwe tradition sites (Khami, Danangombe, Naletale); the Mapungubwe predecessors; farming commoners outside the enclosures; the Shona descendant communities; the colonial denial itself",
"sacred;living-community;conflict-looting",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R2",
"F1.3;F1.24",
"high",
"Soapstone birds were removed in the 1890s; most returned from South Africa (1981, 2003). Check which remain abroad.",
"canon_civilisations.csv"
],
[
"CIV006",
"Nok",
"Nok culture",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-GUI",
"-1500",
"1",
"c. 1500 BCE–1 CE for settlement; terracottas from c. 900 BCE",
"Nok communities made some of the earliest large fired-clay sculpture in sub-Saharan Africa and smelted iron.",
"terracotta modelling and firing; iron smelting; grinding stones",
"terracotta figures; pottery; iron tools",
"ritual and belief;tools;food and storage",
"Bernard Fagg (1940s); popular media and the art market ('Nok civilisation')",
"The name implies a state: evidence shows dispersed farming communities, not a kingdom; neighbouring contemporaries; the looting that destroyed contexts; present-day communities of central Nigeria",
"conflict-looting;living-community",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.24",
"high",
"FLAG: 'civilisation' is misleading; routes to ARC Nok (existing). Terracottas heavily looted and faked; avoid market-sourced images.",
"canon_civilisations.csv"
],
[
"CIV007",
"Ghana / Wagadu",
"Ghana Empire; Wagadou (Soninke name)",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-SAH",
"300",
"1240",
"c. 4th? to 13th century CE; known from Arabic writers from the 8th century",
"Wagadu controlled gold and salt routes across the Sahara, linking Sahelian smiths and weavers to North African markets.",
"gold trade; iron working; weaving; mud-brick architecture",
"gold; beads; pottery; architecture at Koumbi Saleh",
"exchange and value;rule and display;transport",
"Arabic geographers (al-Bakri, 1068); Soninke oral tradition; French colonial scholarship",
"Unrelated to the territory of present-day Ghana; the Soninke name Wagadu; enslaved people traded across the Sahara; Sahelian peoples outside the court; debated identification of Koumbi Saleh as capital",
"living-community;human-flow",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.13;F1.29",
"medium",
"Start date poorly known; verify range. Few free object images.",
"canon_civilisations.csv"
],
[
"CIV008",
"Mali",
"Mali Empire; Manden Kurufaba",
"civilisation-as-commonly-named",
"Composite",
"F1.6;F1.10",
"AF-SAH",
"1235",
"1600",
"c. 1235 (Sunjata) to decline c. 1600",
"Mali's courts and cities supported earthen mosque building, manuscript culture and gold-based trade across the Sahel.",
"earthen architecture; manuscript copying; gold trade; weaving; iron smithing",
"mosques; manuscripts; textiles; terracottas (Inland Niger Delta)",
"exchange and value;record and writing;ritual and belief;rule and display",
"Griots' oral history (Sunjata epic); Arabic sources (Ibn Battuta, al-Umari); European maps (Catalan Atlas, 1375)",
"The griot and smith (nyamakala) castes as makers and historians; non-Mande peoples; enslaved labour; Timbuktu's scholarly networks as distinct from the state; present-day Mande communities",
"living-community;human-flow",
"Wikimedia Commons;Gallica / BnF (public-domain items);open-access excavation reports",
"R3",
"F1.3;F1.28;F1.29",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV009",
"Songhay",
"Songhai Empire",
"civilisation-as-commonly-named",
"Composite",
"F1.6;F1.10",
"AF-SAH",
"1430",
"1591",
"c. 1430s to Moroccan invasion 1591",
"Songhay rule at Gao and Timbuktu sustained scholarly manuscript production and Saharan trade.",
"manuscript copying; earthen architecture; river transport",
"manuscripts; mosques; tomb of the Askia",
"record and writing;exchange and value;ritual and belief;transport",
"Timbuktu chronicles (Tarikh al-Sudan, Tarikh al-Fattash); French colonial scholarship",
"Earlier Songhay history at Gao; the enslaved and servile workers; Tuareg, Fulani and Bozo neighbours; present-day Songhay communities",
"living-community;human-flow",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3;F1.28",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV010",
"Kanem-Bornu",
"Kanem Empire; Bornu Empire; Sefuwa dynasty",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-SAH;AF-CEN",
"700",
"1893",
"c. 8th–9th century (Kanem) to 1893; Bornu phase from the late 14th century",
"A long-lived Sahelian state around Lake Chad whose courts used fired-brick palaces, Arabic manuscripts, quilted cavalry armour and trans-Saharan trade goods.",
"fired-brick building; manuscript copying; quilted cotton armour; leatherwork; horse breeding",
"manuscripts; brick palace ruins (e.g. Gambaru); quilted armour; horse equipment",
"rule and display;exchange and value;war;transport;record and writing",
"Arabic chronicles (e.g. Ahmad ibn Furtu, 16th c.); European travellers (Heinrich Barth, 1850s); historians",
"The Sao and other Lake Chad peoples it conquered; enslaved people traded north across the Sahara; Kanuri and neighbouring present-day communities; Buduma and Kotoko island and river peoples",
"human-flow;living-community",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.13",
"medium",
"Few free object images; mainly a search label.",
"canon_civilisations.csv"
],
[
"CIV011",
"Ife",
"Ile-Ife; Ife art",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-GUI",
"1000",
"1500",
"c. 11th–15th century for the classic sculpture; settlement older and city continuing",
"Ife casters and potters made naturalistic heads in copper alloy and terracotta and produced glass beads locally.",
"lost-wax casting (copper, brass); terracotta; glass bead making; stone carving",
"heads; figures; glass beads; potsherd pavements",
"ritual and belief;rule and display;clothing and adornment",
"Leo Frobenius (1910), who attributed the works to outsiders; later Nigerian and British archaeology; museums",
"Frobenius's 'Atlantis' attribution; the Yoruba living tradition and the Ooni of Ife; glass-bead workers; other Yoruba centres",
"sacred;living-community;conflict-looting",
"Wikimedia Commons;British Museum collection online (link out);open-access excavation reports",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV012",
"Benin",
"Benin Kingdom; Edo Kingdom; 'Benin Bronzes'",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-GUI",
"1180",
"",
"c. 12th century to present (kingdom conquered 1897; Oba restored 1914)",
"Royal guilds (e.g. Igun Eronmwon casters) produced cast plaques, heads and ivory carving recording court history.",
"lost-wax brass casting; ivory carving; wood carving; coral beadwork",
"plaques; commemorative heads; carved tusks; regalia",
"rule and display;ritual and belief;record and writing",
"The Edo court; European traders and the 1897 British punitive expedition; museums worldwide",
"Not the Republic of Benin; the 1897 looting and killing; the named guilds as makers; the living court and Edo people; debates over restitution",
"conflict-looting;sacred;living-community",
"Wikimedia Commons;British Museum collection online (link out);open-access excavation reports",
"R2",
"F1.3;F1.24;F1.17",
"high",
"Restitution in progress; use only restitution-cleared or community-published images; Digital Benin (link out).",
"canon_civilisations.csv"
],
[
"CIV013",
"Kongo",
"Kingdom of Kongo",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-CEN",
"1390",
"1914",
"c. 1390 to formal end 1914",
"Kongo makers produced raffia textiles, ivory and Christian-Kongo metalwork, and power figures (minkisi).",
"raffia weaving; brass casting; wood carving; ivory carving",
"raffia cloth; crucifixes; minkisi; ivory horns",
"ritual and belief;rule and display;clothing and adornment;exchange and value",
"Portuguese sources from 1483; Kongo elites' own letters; historians",
"The Atlantic slave trade that drew people from and through Kongo; neighbouring Loango, Ngoyo and Kakongo; minkisi as sacred objects; the present-day Bakongo",
"sacred;human-flow;conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;Smithsonian Open Access (CC0)",
"R3",
"F1.3;F1.16;F1.23",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV014",
"Mapungubwe",
"Mapungubwe Kingdom",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-SOU",
"1075",
"1220",
"c. 1075–1220 CE (with K2 before)",
"Mapungubwe's elite used gold foil, glass beads and ivory, an early sign of class-based settlement in southern Africa.",
"gold foil; glass beads (imported and reworked); ivory; iron",
"gold rhinoceros; beads; pottery",
"rule and display;exchange and value;ritual and belief",
"University of Pretoria excavations (1933 on); South African state; UNESCO (2003)",
"Burials excavated without consent; the later Great Zimbabwe; Venda, Sotho and Shona descendant communities; apartheid-era suppression of the site's story",
"funerary;ancestral;living-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3;F1.24",
"high",
"Human remains reburied 2007. Funerary material default-excluded. Routes to ARC Mapungubwe.",
"canon_civilisations.csv"
],
[
"CIV015",
"Carthaginian / Punic",
"Carthage; Punic",
"civilisation-as-commonly-named",
"Composite",
"F1.6;F1.11",
"AF-MAG;EU-GRR;EU-IBE",
"-814",
"-146",
"traditional foundation 814 BCE to Roman destruction 146 BCE",
"Carthaginian workshops made glass, masks, ivory and purple dye across the western Mediterranean.",
"glass (core-formed); murex dye; terracotta; metal; shipbuilding",
"masks; stelae; amulets; glass beads",
"exchange and value;ritual and belief;transport",
"Greek and Roman writers (often hostile); French colonial archaeology; Tunisian heritage",
"Imazighen (Berbers) of the hinterland; the enslaved and mercenaries; Roman propaganda about child sacrifice (debated); later Roman Carthage",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection online (link out)",
"R3",
"F1.3",
"high",
"Sub-label of CIV Phoenician; tophet material is funerary.",
"canon_civilisations.csv"
],
[
"CIV016",
"Garamantian",
"Garamantes",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-MAG;AF-SAH",
"-500",
"700",
"c. 500 BCE–700 CE",
"The Garamantes built underground irrigation channels (foggaras) and towns in the Fezzan and traded across the Sahara.",
"foggara irrigation; mud-brick building; glass and textile trade",
"pyramid tombs; imported glass; textiles",
"food and storage;exchange and value;shelter",
"Herodotus; Roman writers; David Mattingly's Fezzan Project",
"Enslaved labour possibly used for irrigation; neighbouring Saharan pastoralists; present-day Libyan communities",
"funerary;human-flow",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.13",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV017",
"Ethiopian (Abyssinian)",
"Abyssinian; Solomonic Ethiopia",
"civilisation-as-commonly-named",
"Composite",
"F1.6",
"AF-HRN",
"1270",
"1974",
"Solomonic dynasty 1270–1974; label also stretched back to Aksum",
"Ethiopian scriptoria produced illuminated Ge'ez manuscripts and icons, and rock-hewn churches (Lalibela).",
"parchment manuscripts; painting; rock-cut architecture; metal processional crosses",
"manuscripts; icons; crosses; churches",
"ritual and belief;record and writing;rule and display",
"European travellers and orientalists; Ethiopian imperial ideology",
"Oromo, Somali, Afar and other peoples incorporated by conquest; Beta Israel and Muslim communities; the Zagwe; the looting of Maqdala (1868)",
"sacred;conflict-looting;living-community",
"Met Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons;British Museum collection online (link out)",
"R3",
"F1.3;F1.24",
"medium",
"'Abyssinian' is an exonym; many manuscripts from Maqdala 1868; restitution claims live.",
"canon_civilisations.csv"
],
[
"CIV018",
"Maya",
"Classic Maya; Mayan civilisation",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"-1000",
"1697",
"c. 1000 BCE (Preclassic) to 1697 (fall of Nojpetén); Maya peoples continue today",
"Maya scribes, painters, sculptors and potters produced a fully readable script, painted ceramics, stucco and carved monuments.",
"limestone carving; stucco; polychrome ceramics; jade working; bark-paper codices; weaving",
"stelae; painted vessels; codices; jade; huipil textiles",
"record and writing;rule and display;ritual and belief;clothing and adornment",
"Spanish colonial writers; 19th-century explorers (Stephens and Catherwood); Mayanists; Maya communities today",
"Over 30 living Maya-language communities; the 'collapse' narrative that erases continuity; non-elite farmers; codices burned by Spanish clergy (1562); looted grave goods",
"Indigenous-community;funerary;conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Yale University Art Gallery (public-domain images);LACMA (public-domain images);Wikimedia Commons",
"R2",
"F1.3;F1.5;F1.24",
"high",
"Existing in project.",
"canon_civilisations.csv"
],
[
"CIV019",
"Olmec",
"Olmeca",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"-1600",
"-400",
"c. 1600–400 BCE (San Lorenzo, La Venta)",
"Olmec workshops carved colossal basalt heads and small jade and greenstone figures that circulated widely.",
"basalt carving; jade working; ceramic",
"colossal heads; altars; jade celts and masks; figurines",
"rule and display;ritual and belief",
"Named from the Nahuatl 'rubber people' by 20th-century archaeologists; called a 'mother culture' (contested)",
"The self-name is unknown; contemporaneous Gulf and Pacific-coast peoples framed as 'derivative'; the mother-vs-sister culture debate",
"Indigenous-community;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Yale University Art Gallery (public-domain images);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Routes to ARC Olmec and HOR Olmec horizon.",
"canon_civilisations.csv"
],
[
"CIV020",
"Aztec / Mexica",
"Aztec Empire; Triple Alliance; Mexica",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"1325",
"1521",
"Tenochtitlan founded c. 1325; Spanish conquest 1521",
"Mexica specialist crafts (featherwork, goldwork, stone sculpture) were organised by guilds and tribute.",
"featherwork; lost-wax gold casting; stone sculpture; codex painting; chinampa agriculture",
"feather shields and headdresses; codices; stone sculpture; mosaic masks",
"rule and display;ritual and belief;record and writing;exchange and value;war",
"'Aztec' popularised by 19th-century writers (Clavijero, Humboldt, Prescott); Mexican national history",
"Tlaxcaltecs and other allies and enemies; the Triple Alliance partners Texcoco and Tlacopan; tribute-paying peoples; Nahua people today",
"Indigenous-community;sacred;conflict-looting;living-community",
"Met Open Access (CC0);Wikimedia Commons;Library of Congress (public-domain items)",
"R3",
"F1.3;F1.17",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV021",
"Andean",
"Andean civilisation; pre-Hispanic Andes",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"-3000",
"1532",
"c. 3000 BCE (Caral) to 1532 (Spanish invasion)",
"Andean makers developed record-keeping in cords (khipu), fine textiles, metallurgy and earthwork across 5,000 years.",
"camelid and cotton weaving; metallurgy; khipu knotting; adobe; terracing",
"textiles; khipu; ceramics; metalwork",
"record and writing;clothing and adornment;rule and display;food and storage;exchange and value",
"Archaeologists (Julio C. Tello, Max Uhle); Peruvian national history; museums",
"Amazonian neighbours; coastal fisherfolk; Quechua and Aymara communities today; the Spanish-colonial and republican continuations",
"Indigenous-community;funerary;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Yale University Art Gallery (public-domain images);Wikimedia Commons",
"R2",
"F1.3;F1.5;F1.18",
"high",
"Existing in project. Members: CIV Caral, Chavín, Moche, Nazca, Tiwanaku, Wari, Chimú, Inca; HOR Early/Middle/Late Horizon.",
"canon_civilisations.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
