insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"CIV022",
"Inca",
"Tawantinsuyu; Inka",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"1438",
"1572",
"c. 1438 (conventional) to 1572",
"The Inca state organised tapestry weaving, fitted-stone architecture, road-building and khipu accounting.",
"fitted masonry; qompi tapestry; khipu; metalwork; road engineering",
"tunics; khipu; aryballos jars; road network; qeros",
"rule and display;record and writing;transport;clothing and adornment",
"Spanish chroniclers; Garcilaso de la Vega; Peruvian national history",
"The conquered peoples of Tawantinsuyu; acllakuna (chosen women) as weavers; mit'a labour; Quechua communities today",
"Indigenous-community;living-community;sacred",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.18;F1.23",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV023",
"Mississippian",
"Mississippian culture",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-EWD",
"800",
"1600",
"c. 800–1600 CE",
"Mississippian towns built earthen platform mounds and made shell gorgets, copper plates and effigy pottery.",
"earthwork; shell engraving; copper repoussé; ceramics",
"platform mounds; gorgets; copper plates; effigy pottery",
"rule and display;ritual and belief;shelter",
"20th-century American archaeology",
"The many nations descended from Mississippian peoples (e.g. Muscogee, Chickasaw, Choctaw, Osage); ancestral burials looted; Cahokia as one of many centres",
"Indigenous-community;funerary;sacred;ancestral",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.24",
"high",
"Routes to ARC Mississippian; NAGPRA applies.",
"canon_civilisations.csv"
],
[
"CIV024",
"Ancestral Puebloan",
"Anasazi (deprecated)",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-WST",
"-1500",
"1600",
"Basketmaker II from c. 1500 BCE in some chronologies; Pueblo peoples continue today",
"Ancestral Puebloans built masonry great houses and cliff dwellings and made painted pottery and baskets.",
"masonry; coiled and painted pottery; basketry; turquoise",
"great houses; cliff dwellings; black-on-white pottery; baskets",
"shelter;food and storage;ritual and belief",
"Archaeologists; 'Anasazi' was a Navajo-derived term replaced at Pueblo request",
"The living Pueblo nations (Hopi, Zuni, Rio Grande Pueblos); Navajo and other neighbours; the looting of Mesa Verde and Chaco in the 19th century",
"Indigenous-community;ancestral;sacred;funerary;living-community",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.26",
"high",
"Routes to ARC Ancestral Puebloan and HOR Chaco.",
"canon_civilisations.csv"
],
[
"CIV025",
"Mound Builders",
"'Mound Builder' myth",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-EWD",
"-3500",
"1600",
"label applied to earthwork builders from the Archaic to the Mississippian",
"The label hid Indigenous authorship of the earthworks it described.",
"earthwork",
"mounds; earthworks",
"ritual and belief;shelter",
"19th-century European-American writers who attributed earthworks to a lost non-Indigenous race",
"Indigenous authorship; the removal policies the myth supported; the specific cultures (Watson Brake, Poverty Point, Adena, Hopewell, Mississippian)",
"Indigenous-community;ancestral;funerary",
"Smithsonian Open Access (CC0);Library of Congress (public-domain items);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Kept as a search label so the card can explain the myth; not a real grouping.",
"canon_civilisations.csv"
],
[
"CIV026",
"Teotihuacan",
"Teotihuacano",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"-100",
"550",
"c. 100 BCE–550 CE",
"Teotihuacan planned a gridded city with apartment compounds, mural painting and mass-produced ceramics.",
"talud-tablero architecture; mural painting; obsidian working; mould-made ceramics",
"masks; murals; figurines; incense burners",
"shelter;ritual and belief;rule and display;exchange and value",
"Named by later Nahua speakers; archaeologists",
"The city's self-name unknown; multi-ethnic neighbourhoods (Zapotec, Maya); present-day local communities",
"Indigenous-community;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.5",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV027",
"Toltec",
"Toltecs",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"900",
"1150",
"c. 900–1150 CE (Tula)",
"Tula's workshops made columnar warrior statues and chacmools; later Mexica called fine craft 'toltecayotl'.",
"basalt sculpture; relief carving; ceramics",
"atlantean columns; chacmools; relief panels",
"rule and display;war;ritual and belief",
"Mexica tradition; colonial chroniclers; archaeologists",
"The Mexica myth-making that idealised them; neighbours at Chichén Itzá; the name used as a synonym for 'skilled artisan'",
"Indigenous-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV028",
"Zapotec",
"Bë'enzaa (self-name)",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"-500",
"1521",
"c. 500 BCE (Monte Albán) to 1521; Zapotec people continue",
"Zapotec scribes carved early Mesoamerican inscriptions and potters made effigy urns.",
"stone carving; ceramics; weaving",
"effigy urns; carved stones; tombs",
"record and writing;ritual and belief;rule and display",
"Nahuatl exonym; Mexican archaeology",
"Living Zapotec communities; Mixtec neighbours; the looting of Monte Albán tombs",
"Indigenous-community;funerary;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Routes to ARC Monte Albán (Zapotec).",
"canon_civilisations.csv"
],
[
"CIV029",
"Mixtec",
"Ñuu Savi (self-name)",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"900",
"1521",
"Postclassic kingdoms c. 900–1521; earlier roots; Mixtec people continue",
"Mixtec painters produced screenfold codices and goldsmiths cast fine jewellery.",
"codex painting on deerskin; lost-wax gold casting; turquoise mosaic",
"codices; gold jewellery; polychrome ceramics",
"record and writing;rule and display;clothing and adornment",
"Nahuatl exonym; Mexican archaeology",
"Living Ñuu Savi communities; the codices held abroad",
"Indigenous-community;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.28",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV030",
"Taíno",
"Taino; Arawak (older)",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-CAR",
"1000",
"1550",
"c. 1000–1550 as the name for Greater Antillean chiefdoms; roots c. 600 CE",
"Taíno makers carved wooden duhos, stone zemis and three-pointers.",
"wood carving; stone carving; cotton weaving; shell inlay",
"duhos; zemis; three-pointers",
"ritual and belief;rule and display",
"European chroniclers (Pané, Las Casas); 20th-century archaeology (Rouse)",
"The 'extinction' myth; living Taíno and descendant communities; Lucayan, Ciboney and others",
"Indigenous-community;sacred;living-community",
"Met Open Access (CC0);Smithsonian Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.26",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV031",
"Caral / Norte Chico",
"Caral-Supe",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"-3000",
"-1800",
"c. 3000–1800 BCE",
"Caral-Supe communities built monumental platforms and sunken plazas and used cotton for nets and textiles.",
"stone and earth platforms; cotton textile; shicra bags",
"platform mounds; flutes; textiles; khipu-like strings",
"ritual and belief;food and storage",
"Ruth Shady (1990s); UNESCO (2009)",
"Contemporary coastal fishing villages; the 'first civilisation' claim",
"Indigenous-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3;F1.5",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV032",
"Chavín",
"Chavín de Huántar",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"-900",
"-200",
"c. 900–200 BCE",
"Chavín temple sculpture and portable objects spread a shared imagery across the Andes.",
"stone carving; metalwork; textile painting; ceramics",
"tenoned heads; carved slabs; gold",
"ritual and belief;rule and display",
"Julio C. Tello (1919); UNESCO (1985)",
"The label implies an empire; Chavín de Huántar was a temple centre whose imagery spread; contemporaneous coastal cultures (Cupisnique, Paracas); present-day Quechua communities of the Conchucos valley",
"Indigenous-community;sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Routes to HOR Early Horizon.",
"canon_civilisations.csv"
],
[
"CIV033",
"Moche",
"Mochica",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"100",
"800",
"c. 100–800 CE on Peru's north coast",
"Moche potters and metalworkers made mould-made portrait and scene vessels and gilded copper regalia for elite burials.",
"mould-made ceramics; fineline painting; gilding and depletion gilding; adobe; weaving",
"stirrup-spout vessels; portrait heads; ear ornaments; murals",
"rule and display;ritual and belief;clothing and adornment",
"Max Uhle and Rafael Larco Hoyle (early 20th c.); Peruvian archaeology (Sipán, 1987)",
"Probably several polities rather than one state; the potters and metalworkers as named workshops; looted burials sold abroad; present-day north-coast communities",
"Indigenous-community;funerary;conflict-looting",
"Met Open Access (CC0);Art Institute of Chicago (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"Sipán tombs discovered after looting (1987). Routes to ARC Moche.",
"canon_civilisations.csv"
],
[
"CIV034",
"Nazca",
"Nasca",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"-100",
"800",
"c. 100 BCE–800 CE on Peru's south coast",
"Nasca potters painted polychrome slip vessels and communities made the geoglyphs and underground aqueducts (puquios).",
"polychrome slip painting; camelid and cotton weaving; geoglyph clearing; puquio engineering",
"polychrome vessels; textiles; geoglyphs; trophy heads",
"ritual and belief;food and storage;clothing and adornment",
"Max Uhle (early 20th c.); Maria Reiche's geoglyph work; UNESCO (1994)",
"The 'alien' pseudo-archaeology around the lines; the Paracas predecessors; water engineers and farmers; present-day Nazca and Palpa communities",
"Indigenous-community;funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Routes to ARC Nasca.",
"canon_civilisations.csv"
],
[
"CIV035",
"Tiwanaku",
"Tiahuanaco; Tiwanacu",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"500",
"1000",
"as a state c. 500–1000 CE; settlement from c. 110 CE",
"Tiwanaku workshops cut fitted andesite and sandstone blocks and made tapestry, keros and snuff trays across the southern Andes.",
"fitted masonry with metal cramps; tapestry weaving; polychrome ceramics; raised-field farming",
"monoliths; Gateway of the Sun; keros; tunics; snuff trays",
"rule and display;ritual and belief;food and storage",
"Archaeologists (Posnansky, Ponce Sanginés, Kolata); Bolivian national history; UNESCO (2000)",
"Aymara communities for whom the site is ancestral; colonies and allies around Titicaca; the 19th–20th-century quarrying and nationalist uses of the site",
"Indigenous-community;sacred;ancestral",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3",
"high",
"Member of HOR Middle Horizon (existing).",
"canon_civilisations.csv"
],
[
"CIV036",
"Wari",
"Huari",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"600",
"1000",
"c. 600–1000 CE",
"Wari state workshops produced standardised tapestry tunics and planned administrative compounds across the Peruvian highlands.",
"interlocking tapestry; planned architecture; polychrome ceramics; khipu (wrapped)",
"tapestry tunics; ceramics; architectural compounds",
"rule and display;clothing and adornment;record and writing",
"Archaeologists (20th c.)",
"Communities under Wari control; the weavers, probably specialists; looted burials at Wari and on the coast",
"Indigenous-community;funerary;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.18",
"high",
"Member of HOR Middle Horizon (existing).",
"canon_civilisations.csv"
],
[
"CIV037",
"Chimú",
"Chimor; Kingdom of Chimor",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AND",
"900",
"1470",
"c. 900–1470 CE (Inca conquest)",
"Chimú workshops at Chan Chan made hammered gold and silver, featherwork and textiles in quantity for a court economy.",
"sheet-metal work; adobe friezes; feathered textiles; blackware ceramics",
"adobe friezes; gold and silver vessels; featherwork; blackware",
"rule and display;exchange and value;clothing and adornment",
"Spanish chroniclers; archaeologists; UNESCO (Chan Chan, 1986)",
"Artisans deported to Cuzco after the Inca conquest; the Sicán/Lambayeque predecessors; present-day north-coast communities",
"Indigenous-community;funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3;F1.23",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV038",
"Marajoara",
"Marajoara culture; Marajó",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AMZ",
"400",
"1400",
"c. 400–1400 CE on Marajó Island",
"Marajoara potters made painted and modelled funerary urns and ceramic pubic covers (tangas) on raised earth mounds.",
"excised and painted ceramics; mound building",
"funerary urns; tangas; figurines",
"ritual and belief;clothing and adornment;shelter",
"Brazilian and US archaeology (Meggers and Evans; Anna Roosevelt; Denise Schaan)",
"The idea that Amazonia could not support complex societies; the living peoples of Marajó; looting for the tourist and collector market",
"Indigenous-community;funerary;conflict-looting",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3",
"high",
"Routes to ARC Marajoara.",
"canon_civilisations.csv"
],
[
"CIV039",
"Amazonian 'garden cities'",
"Amazonian 'lost cities'; Upano; Casarabe; Upper Xingu",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-AMZ",
"-500",
"1650",
"c. 500 BCE (Upano) to c. 1650 CE (Upper Xingu); several distinct cases",
"Amazonian settlements built causeways, mounds, ditches and anthropogenic dark earths (terra preta), managing forest as a made landscape.",
"earthworks; causeways; terra preta soil making; ceramics",
"platform mounds; causeways; ditched villages; ceramics",
"shelter;food and storage;transport",
"Archaeologists using lidar (2020s); media ('lost city')",
"The 'lost' framing that ignores living Indigenous peoples (e.g. Kuikuro in the Xingu); the distinct cases lumped together; forest management as making",
"Indigenous-community;living-community",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.3;F1.5;F1.22",
"medium",
"Composite search label; routes to ARC Upano, Casarabe, Upper Xingu, Acre geoglyphs.",
"canon_civilisations.csv"
],
[
"CIV040",
"Muisca",
"Chibcha; Muisca Confederation",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-CAM;AM-AND",
"600",
"1600",
"c. 600–1600 CE in the Colombian eastern highlands",
"Muisca goldsmiths cast tumbaga votive figures (tunjos) and were the source of the El Dorado story.",
"lost-wax tumbaga casting; cotton weaving; salt production",
"tunjos; Muisca raft; textiles",
"ritual and belief;exchange and value;rule and display",
"Spanish chroniclers; Colombian national history; Museo del Oro",
"The El Dorado myth and draining of Lake Guatavita; Muisca communities recognised today; neighbouring Guane and Lache",
"Indigenous-community;sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV041",
"Purépecha / Tarascan",
"Tarascan state; P'urhépecha",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"1350",
"1530",
"c. 1350–1530 CE",
"Purépecha metalworkers were leading Mesoamerican makers of copper and bronze tools and bells.",
"copper and bronze smelting; featherwork; lacquer",
"copper tools; bells; ornaments; yácatas",
"tools;rule and display;ritual and belief",
"Spanish chroniclers (Relación de Michoacán); 'Tarascan' is a colonial exonym",
"P'urhépecha people today; the West Mexican shaft-tomb predecessors",
"Indigenous-community;living-community",
"Wikimedia Commons",
"R3",
"F1.3",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV042",
"Mesoamerican",
"Mesoamerica",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-MES",
"-2000",
"1521",
"c. 2000 BCE–1521 CE as a culture-area label",
"A culture-area label for societies sharing calendars, ballgames, maize farming, codex writing and similar crafts.",
"stone carving; ceramics; bark-paper; featherwork; jade",
"codices; ballcourts; calendars; stelae",
"record and writing;ritual and belief;play and music",
"Paul Kirchhoff (1943)",
"Northern (Aridamerican) and Isthmo-Colombian neighbours; the diversity of languages; living Indigenous peoples of Mexico and Central America",
"Indigenous-community;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.30",
"high",
"Culture-area label; routes to CIV Olmec, Maya, Zapotec, Teotihuacan, Toltec, Mixtec, Aztec.",
"canon_civilisations.csv"
],
[
"CIV043",
"Pre-Columbian",
"precolumbian civilisations; Pre-Hispanic",
"civilisation-as-commonly-named",
"Composite",
"F1.7",
"AM-ARC;AM-NWC;AM-WST;AM-EWD;AM-MES;AM-CAM;AM-CAR;AM-AND;AM-AMZ",
"-15000",
"1492",
"everything in the Americas before 1492 CE",
"An umbrella label that defines thousands of years of American making by the arrival of Europeans.",
"various",
"various",
"",
"European and Euro-American periodisation; art market and museums",
"Continuities after 1492 and living Indigenous nations; the diversity it flattens; that 1492 means nothing in much of the Americas for decades after",
"Indigenous-community;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Smithsonian Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.30",
"high",
"Umbrella label for F1.3 and F1.30 teaching.",
"canon_civilisations.csv"
],
[
"CIV044",
"Chinese",
"Chinese civilisation; Zhonghua",
"civilisation-as-commonly-named",
"Composite",
"F1.8",
"AS-CHN",
"-2000",
"",
"label applied from Neolithic cultures (c. 7000 BCE) or Erlitou (c. 1900 BCE) to the present",
"Chinese workshops developed bronze piece-mould casting, silk, lacquer, paper, printing and high-fired porcelain, often at industrial scale.",
"piece-mould casting; sericulture; lacquer; papermaking; woodblock printing; porcelain",
"bronze vessels; silk; porcelain; books; lacquerware",
"record and writing;rule and display;ritual and belief;exchange and value;clothing and adornment",
"Chinese historiography (dynastic histories); European sinology; the PRC's 'five thousand years' narrative; museums",
"Non-Han peoples (Tibetan, Uyghur, Mongol, Yi, Zhuang and many more); regional Neolithic cultures made into a single origin story; conscripted and enslaved labour; Taiwanese and diaspora histories",
"living-community;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);National Palace Museum Taipei Open Data;Smithsonian Open Access (CC0);Wikimedia Commons",
"R2",
"F1.3;F1.5;F1.14",
"high",
"Existing in project.",
"canon_civilisations.csv"
],
[
"CIV045",
"Japanese",
"Nihon; Japanese civilisation (Huntington)",
"civilisation-as-commonly-named",
"Composite",
"F1.8",
"AS-JPN",
"-14000",
"",
"label stretched from Jōmon (c. 14,000 BCE) to the present",
"Japanese makers developed early pottery, lacquer, sword-making, woodblock printing and textile dyeing traditions.",
"pottery; lacquer; steel forging; woodblock printing; dyeing; carpentry",
"Jōmon vessels; lacquerware; swords; prints; textiles",
"ritual and belief;rule and display;record and writing;clothing and adornment",
"National historiography (Meiji era); Samuel Huntington (1996); museums",
"The Ainu and Ryukyuan peoples; Korean and Chinese makers who moved to Japan; burakumin leather and other stigmatised crafts",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);ColBase, Japan NICH (check per-image terms);Wikimedia Commons",
"R3",
"F1.3",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV046",
"Korean",
"Korean civilisation",
"civilisation-as-commonly-named",
"Composite",
"F1.8",
"AS-KOR",
"-1500",
"",
"label applied from Mumun (c. 1500 BCE) or earlier to the present",
"Korean makers developed celadon and buncheong ceramics, early metal movable type and a phonetic script (Hangeul).",
"celadon; buncheong; metal movable type; lacquer with mother-of-pearl; paper",
"celadon vessels; printed books; crowns; lacquer boxes",
"record and writing;rule and display;ritual and belief",
"Korean national historiography; museums",
"The multi-polity past (Three Kingdoms, Gaya, Balhae); potters taken to Japan in the 1590s; North Korean heritage",
"living-community",
"National Museum of Korea e-museum (KOGL Type 1);Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV047",
"Tibetan",
"Tibetan civilisation; Bod",
"civilisation-as-commonly-named",
"Composite",
"F1.9;F1.8",
"AS-HIM;AS-CHN",
"600",
"",
"Tibetan Empire from c. 7th century CE; label stretched to earlier prehistory",
"Tibetan makers developed thangka painting, metal image casting, woodblock printing of scripture and wool textiles.",
"thangka painting; metal casting; woodblock printing; wool weaving",
"thangkas; statues; ritual objects; books",
"ritual and belief;record and writing;clothing and adornment",
"Tibetan histories; Western Tibetology (e.g. R. A. Stein, 'Tibetan Civilization', 1962)",
"Himalayan neighbours (Ladakh, Bhutan, Nepal); Bon traditions; Zhang Zhung; Tibetans in exile; sacred objects in museums",
"sacred;living-community;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.16",
"medium",
"Politically contested; be careful with terminology.",
"canon_civilisations.csv"
],
[
"CIV048",
"Indus Valley",
"Harappan civilisation; Indus civilisation; Sindhu–Sarasvati civilisation (contested)",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-SAS",
"-3300",
"-1300",
"c. 3300–1300 BCE incl. Early, Mature (c. 2600–1900 BCE) and Late Harappan",
"Planned brick cities with drains, standard weights and seals show regional-scale craft production without identified palaces or royal tombs.",
"fired brick; carnelian bead drilling; steatite seal carving; faience; copper-bronze; cotton",
"stamp seals; carnelian beads; weights; painted pottery; bangles",
"record and writing;exchange and value;clothing and adornment;shelter",
"John Marshall and the Archaeological Survey of India (1924); 'Harappan' after the type site; South Asian archaeology; museums",
"Contemporaneous non-urban farmers and pastoralists; craft workers; no known self-name (the script is undeciphered); present-day communities of Sindh, Punjab, Gujarat and Haryana; the Late Harappan transformation framed as 'collapse'; links with Magan, Dilmun and Mesopotamia (Meluhha)",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;open-access excavation reports;PeriodO",
"R2",
"F1.3;F1.5;F1.13",
"high",
"Existing in project. 'Sarasvati' naming is politically contested. Routes to ARC Early, Mature and Late Harappan.",
"canon_civilisations.csv"
],
[
"CIV049",
"Vedic",
"Vedic period; Vedic Aryan (contested)",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-SAS",
"-1500",
"-500",
"c. 1500–500 BCE; dates depend on textual chronology",
"Known mostly from orally transmitted ritual texts that describe chariots, fire altars and metalwork; archaeological correlates are debated.",
"oral transmission; fire-altar building; metalwork; chariotry",
"altars; texts (later written)",
"ritual and belief;record and writing",
"19th-century European philology (Max Müller); Indian nationalist and Hindutva historiography",
"The non-Vedic populations of South Asia; the archaeological record (PGW, OCP) that does not map neatly onto texts; Dravidian, Munda and other language communities",
"sacred",
"Wikimedia Commons",
"R3",
"F1.3;F1.29",
"medium",
"Highly contested; the card should say so.",
"canon_civilisations.csv"
],
[
"CIV050",
"Khmer",
"Angkorian; Khmer Empire",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-MSE",
"802",
"1431",
"c. 802–1431 CE (Angkor)",
"Khmer builders and sculptors made sandstone temples, bronzes and a hydraulic city at Angkor.",
"sandstone carving; laterite; bronze casting; hydraulic engineering; stoneware",
"temples; statues; bronzes; stoneware",
"ritual and belief;rule and display;shelter",
"French colonial scholarship (EFEO); Cambodian national history; UNESCO (1992)",
"Post-Angkorian Cambodia; forced and temple labour; looting during conflict; living Khmer Buddhist practice at the temples",
"sacred;conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"Many looted sculptures being returned; check provenance.",
"canon_civilisations.csv"
],
[
"CIV051",
"Cham (Champa)",
"Champa; Cham civilisation",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-MSE",
"200",
"1832",
"c. 2nd century CE to annexation 1832",
"Cham builders made brick temple towers and sandstone sculpture along the central Vietnamese coast, at sites such as Mỹ Sơn.",
"fired-brick architecture; sandstone carving; bronze; ceramics",
"temple towers; sculpture; inscriptions",
"ritual and belief;rule and display;record and writing",
"French colonial scholarship (EFEO); Musée Guimet; UNESCO (Mỹ Sơn, 1999)",
"Champa was several polities, not one; living Cham communities (Hindu and Muslim) in Vietnam and Cambodia; the Sa Huỳnh predecessors; war damage to Mỹ Sơn (1969)",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV052",
"Pyu",
"Pyu city-states; Tircul",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-MSE",
"-200",
"1050",
"c. 200 BCE–1050 CE",
"Pyu communities built walled brick cities, cast silver coins and made Buddhist reliquaries and burial urns.",
"fired brick; silver coin minting; urn burial; gold and silver repoussé",
"coins; funerary urns; stupas; reliquaries",
"ritual and belief;exchange and value;rule and display",
"Chinese sources ('Piao'); Burmese archaeology; UNESCO (Pyu Ancient Cities, 2014)",
"Mon and other neighbours; the Bagan successors; living Buddhist uses of the sites",
"funerary;sacred;living-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.3;F1.5",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV053",
"Gandharan",
"Gandhara; Gandhara civilisation; Graeco-Buddhist (older)",
"civilisation-as-commonly-named",
"Composite",
"F1.9;F1.12a",
"AS-SAS;AS-CEN",
"-100",
"500",
"c. 1st century BCE to 5th century CE for the sculpture; region named much earlier",
"Gandharan workshops carved Buddhist images and narrative reliefs in grey schist and stucco for monasteries.",
"schist carving; stucco modelling; gilding",
"Buddha and bodhisattva images; narrative reliefs; reliquaries",
"ritual and belief",
"19th-century British colonial scholarship; the art market ('Graeco-Buddhist')",
"The over-emphasis on 'Greek influence' at the expense of local and Kushan makers; monastic communities; looting and faking in the modern market; present-day Pakistan and Afghanistan",
"sacred;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Art Institute of Chicago (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.2;F1.24",
"high",
"Heavily looted and faked; strict provenance check.",
"canon_civilisations.csv"
],
[
"CIV054",
"Indianised states of Southeast Asia",
"Hindu-Buddhist Southeast Asia; 'Greater India' (colonial-era)",
"civilisation-as-commonly-named",
"Composite",
"F1.9",
"AS-MSE;AS-ISE",
"100",
"1500",
"c. 1st–15th century CE",
"A label for Southeast Asian polities that adopted Sanskrit, Hindu and Buddhist forms while developing their own temple and bronze traditions.",
"stone temple building; bronze casting; inscriptions",
"temples; statues; inscriptions",
"ritual and belief;rule and display;record and writing",
"George Coedès ('Les États hindouisés', 1944); 'Greater India' Society (1920s)",
"Local agency in selecting and transforming Indian forms; Austronesian and Mon-Khmer foundations; non-state peoples of highlands and islands",
"sacred",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.2",
"high",
"Label critiqued as diffusionist; card explains the critique.",
"canon_civilisations.csv"
],
[
"CIV055",
"Mesopotamian",
"Ancient Mesopotamia; 'Cradle of civilisation'",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-MES",
"-3500",
"-539",
"c. 3500 BCE (Uruk) to 539 BCE (Persian conquest of Babylon)",
"Mesopotamian scribes and craft workers developed cuneiform, cylinder seals, and industrial-scale textile and pottery workshops.",
"clay tablets; cylinder-seal carving; mud brick; wool textile; copper-bronze",
"tablets; cylinder seals; ziggurats; statues",
"record and writing;rule and display;ritual and belief;exchange and value",
"Greek name ('between the rivers'); 19th-century European Assyriology; museums",
"Hill peoples, pastoralists and deportees; women weavers in temple and palace workshops; present-day Iraqis, Assyrians, Mandaeans and Yazidis; looting during wars (2003 on)",
"conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);British Museum collection online (link out);Wikimedia Commons;Penn Museum online collection (link out);Open Context (CC BY)",
"R2",
"F1.3;F1.5;F1.24",
"high",
"Umbrella; routes to Sumerian, Babylonian, Assyrian, ARC Uruk, Ubaid.",
"canon_civilisations.csv"
],
[
"CIV056",
"Sumerian",
"Sumer",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-MES",
"-3500",
"-2000",
"c. 3500–2000 BCE",
"Sumerian city workshops produced early writing, inlaid lyres, cylinder seals and standardised pottery.",
"cuneiform; shell and lapis inlay; metalwork; bevelled-rim bowls",
"tablets; lyres; statues; seals",
"record and writing;ritual and belief;play and music;rule and display",
"Akkadian name for the land; 19th-century Assyriology (Oppert)",
"Akkadian speakers who lived alongside them; labour recorded in ration lists; the Royal Tombs of Ur as burials",
"funerary;conflict-looting",
"Met Open Access (CC0);Penn Museum online collection (link out);British Museum collection online (link out);Wikimedia Commons",
"R3",
"F1.3;F1.5",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV057",
"Babylonian",
"Babylonia",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-MES",
"-1900",
"-539",
"c. 1900–539 BCE (Old to Neo-Babylonian)",
"Babylonian scribes and brickmakers produced law codes, astronomical records and glazed-brick architecture.",
"glazed brick; cuneiform; astronomy",
"Ishtar Gate; tablets; boundary stones",
"record and writing;rule and display;ritual and belief",
"Biblical and Greek sources; Assyriology",
"Kassite, Amorite and Chaldean dynasties; deportees (e.g. Judaeans) and their crafts; non-elite brickmakers and temple dependants; the Ishtar Gate's removal to Berlin",
"conflict-looting",
"Met Open Access (CC0);British Museum collection online (link out);Wikimedia Commons",
"R3",
"F1.3",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV058",
"Assyrian",
"Assyria",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-MES",
"-2000",
"-609",
"c. 2000–609 BCE (Old to Neo-Assyrian)",
"Assyrian palace workshops carved stone reliefs and ivories and organised deported craftworkers.",
"relief carving; ivory; glazed brick",
"palace reliefs; lamassu; ivories",
"rule and display;war;record and writing",
"Biblical sources; 19th-century excavators (Layard, Botta); museums",
"Present-day Assyrian people, who use the name for themselves; deported craftworkers; the 2015 destruction at Nimrud",
"conflict-looting;living-community",
"Met Open Access (CC0);British Museum collection online (link out);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"Living community uses the name.",
"canon_civilisations.csv"
],
[
"CIV059",
"Elamite",
"Elam",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-IRN",
"-3200",
"-539",
"c. 3200–539 BCE",
"Elamite workshops made bitumen compound vessels, bronze casting and glazed brick in southwestern Iran.",
"bitumen compound; bronze casting; glazed brick",
"statues; vessels; tablets",
"rule and display;ritual and belief;record and writing",
"Mesopotamian texts; French archaeology at Susa",
"Highland Anshan and the Proto-Elamite phase; that Elam was a shifting federation rather than one state; the mass removal of Susa finds to Paris under French concession; Iranian communities today",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV060",
"Dilmun",
"Tilmun",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-ARB",
"-2200",
"-500",
"c. 2200–500 BCE; name used in texts from late 4th millennium BCE",
"Dilmun, centred on Bahrain, was a Gulf trading hub known for stamp seals and tens of thousands of burial mounds.",
"stamp-seal carving; copper trade; tumulus building",
"stamp seals; burial mounds; pottery",
"exchange and value;ritual and belief;transport",
"Mesopotamian texts; Danish expeditions (P. V. Glob, Geoffrey Bibby, 1950s); UNESCO (2019)",
"The name is Mesopotamian; Gulf peoples; the burial mounds are graves; present-day Bahrainis",
"funerary",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV061",
"Magan",
"Makkan",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-ARB",
"-2600",
"-1800",
"c. 2600–1800 BCE; archaeologically Umm an-Nar and Wadi Suq",
"Magan (Oman peninsula) supplied copper and diorite to Mesopotamia and made soft-stone vessels.",
"copper smelting; soft-stone carving; tomb building",
"copper ingots; soft-stone vessels; tombs",
"exchange and value;tools;ritual and belief",
"Mesopotamian texts; archaeologists",
"Magan is a Mesopotamian name, not a self-name; the Hafit, Umm an-Nar and Wadi Suq communities of the UAE and Oman; copper miners and smelters; present-day Emirati and Omani communities",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.13",
"medium",
"Routes to ARC Umm an-Nar.",
"canon_civilisations.csv"
],
[
"CIV062",
"Phoenician",
"Phoenicia; Canaanite (self-description); Punic (western)",
"civilisation-as-commonly-named",
"Composite",
"F1.9a;F1.11;F1.6",
"WA-LEV;EU-GRR;AF-MAG;EU-IBE",
"-1500",
"-300",
"c. 1500–300 BCE; conventionally from c. 1200 BCE for the Iron Age city-states",
"Phoenician city-state workshops made murex purple dye, glass, carved ivory and metal bowls, and spread an alphabet used around the Mediterranean.",
"murex dye; core-formed and blown glass; ivory carving; metal bowls; shipbuilding",
"inscriptions; ivories; glass; metal bowls; amphorae",
"record and writing;exchange and value;transport;clothing and adornment",
"Greek writers ('Phoinikes'); 19th-century scholarship; Lebanese national history",
"The name is Greek, the people called themselves by city (Tyrians, Sidonians) or Canaanites; enslaved rowers and traded people; the peoples they settled among in North Africa and Iberia; dye workers",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection online (link out)",
"R3",
"F1.3;F1.13;F1.5",
"high",
"Routes to CIV Carthaginian / Punic.",
"canon_civilisations.csv"
],
[
"CIV063",
"Hittite",
"Hatti; Hittite Empire",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-ANA",
"-1650",
"-1180",
"c. 1650–1180 BCE",
"Hittite scribes kept cuneiform archives at Hattusa and workshops made rock reliefs, metal vessels and animal-shaped rhyta.",
"cuneiform on clay; rock-relief carving; silver and gold vessels; iron (limited)",
"tablets; rock reliefs; rhyta; seals",
"record and writing;rule and display;ritual and belief",
"Biblical name applied by 19th-century scholars; Hugo Winckler's excavations (1906); decipherment by Bedřich Hrozný (1915)",
"Hattians and Hurrians whose cultures the state absorbed; Luwian speakers; deported populations; the Neo-Hittite successor states",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3",
"high",
"The self-designation was 'land of Hatti'; 'Hittite' is a borrowed biblical term.",
"canon_civilisations.csv"
],
[
"CIV064",
"Urartian",
"Urartu; Kingdom of Van; Biainili (self-name)",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-CAU;WA-ANA;WA-IRN",
"-860",
"-590",
"c. 860–590 BCE",
"Urartian workshops made bronze belts, shields and cauldrons and built fortresses with irrigation works around Lake Van.",
"bronze casting and repoussé; stone fortress building; irrigation",
"bronze belts; shields; cauldron attachments; inscriptions",
"war;rule and display;ritual and belief",
"Assyrian texts ('Urartu'); 19th–20th-century archaeology (Russian, Turkish, Armenian)",
"Contested national claims (Armenian, Turkish, Kurdish); looted bronzes on the market; the peoples conquered and deported",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.24",
"high",
"Many Urartian bronzes are unprovenanced.",
"canon_civilisations.csv"
],
[
"CIV065",
"Nabataean",
"Nabataeans; Nabataean Kingdom",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-ARB;WA-LEV",
"-300",
"106",
"c. 4th century BCE to Roman annexation 106 CE",
"Nabataeans carved tomb façades at Petra and Hegra, built water-harvesting systems and made eggshell-thin painted pottery.",
"rock-cut architecture; water harvesting; fine painted ceramics; incense trade",
"tomb façades; inscriptions; painted bowls",
"ritual and belief;exchange and value;transport;shelter",
"Greek and Roman writers; European travellers (Burckhardt, 1812); Jordanian and Saudi heritage bodies; UNESCO",
"Bedouin communities displaced from Petra (1985); the pastoralists and caravan workers; the tombs as graves",
"funerary;living-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV066",
"Sabaean",
"Saba; Sheba; Ancient South Arabian",
"civilisation-as-commonly-named",
"Composite",
"F1.9a;F1.6",
"WA-ARB;AF-HRN",
"-1000",
"275",
"c. early 1st millennium BCE to Himyarite conquest c. 275 CE",
"Sabaean builders constructed the Marib dam and temples and carved alabaster votive figures and inscriptions in the South Arabian script.",
"dam engineering; ashlar masonry; alabaster carving; bronze casting",
"inscriptions; alabaster statues; incense burners",
"ritual and belief;food and storage;record and writing;exchange and value",
"Biblical and Qur'anic tradition ('Sheba'); European epigraphers; Yemeni heritage",
"Qatabanian, Hadrami, Minaean and Himyarite neighbours; the conflict-driven destruction and looting in Yemen; the legend overshadowing evidence",
"conflict-looting",
"Met Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"medium",
"Yemen looting ongoing; strict provenance.",
"canon_civilisations.csv"
],
[
"CIV067",
"Persian",
"Iranian; Achaemenid-Sasanian; Persia",
"civilisation-as-commonly-named",
"Composite",
"F1.9a;F1.10",
"WA-IRN;AS-CEN",
"-550",
"",
"Achaemenid 550 BCE onward; the label is stretched through Islamic and modern Iran",
"Persian courts commissioned multi-ethnic workforces for palaces, metalwork, textiles, carpets and book arts.",
"stone relief; silver-gilt; silk weaving; carpet knotting; manuscript painting",
"reliefs; silver plates; carpets; manuscripts",
"rule and display;ritual and belief;record and writing;clothing and adornment",
"Greek writers ('Persis'); European orientalism; Iranian national history",
"The workforce named in the Persepolis Fortification Tablets (Ionians, Egyptians, Babylonians); non-Persian peoples of Iran (Kurds, Baluch, Azeris, Arabs); Elamite foundations",
"conflict-looting;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.23",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV068",
"Hellenistic",
"Hellenistic world",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.9a;F1.12a",
"EU-GRR;WA-LEV;WA-MES;WA-IRN;AF-EGY;AS-CEN",
"-323",
"-31",
"323 BCE (Alexander's death) to 31 BCE",
"A label for the Greek-speaking kingdoms from Egypt to Bactria whose workshops mixed Greek and local forms.",
"marble and bronze sculpture; glass; coinage; mosaic",
"statues; coins; mosaics; glass",
"rule and display;exchange and value;ritual and belief",
"Johann Gustav Droysen (1830s)",
"The local majorities (Egyptians, Babylonians, Bactrians); enslaved workers; the label's Greek-centred view",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.2",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV069",
"Jiroft",
"Jiroft culture; Halil Rud civilisation",
"civilisation-as-commonly-named",
"Composite",
"F1.9a",
"WA-IRN",
"-3000",
"-2000",
"c. 3rd millennium BCE",
"Carved chlorite vessels in an 'intercultural style' were made in southeastern Iran and traded to Mesopotamia and the Gulf.",
"chlorite carving; inlay",
"carved chlorite vessels; weights",
"exchange and value;ritual and belief",
"Yousef Majidzadeh (2000s) after looting exposed the cemeteries",
"The looting that preceded excavation; forgeries; neighbouring Helmand and Oxus",
"conflict-looting;funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.24",
"medium",
"Known largely through looted material; 'civilisation' claim contested.",
"canon_civilisations.csv"
],
[
"CIV070",
"Helmand",
"Helmand civilisation; Shahr-i Sokhta",
"civilisation-as-commonly-named",
"Composite",
"F1.9a;F1.9",
"WA-IRN;AS-SAS",
"-3200",
"-2100",
"c. 3200–2100 BCE",
"Shahr-i Sokhta was a craft town working lapis lazuli, carnelian and textiles between Iran, Central Asia and the Indus.",
"bead making; weaving; pottery",
"beads; textiles; pottery",
"exchange and value;clothing and adornment",
"Italian (IsMEO) and Iranian archaeologists; UNESCO (2014)",
"Neighbours in the Indus and Oxus; burials",
"funerary",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"F1.3;F1.13",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV071",
"Greek and Roman",
"Classical civilisation; Classical antiquity; Graeco-Roman",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.6;F1.9a",
"EU-GRR;EU-BYZ;EU-WCE;EU-IBE;EU-BLC;AF-MAG;AF-EGY;WA-LEV;WA-ANA",
"-800",
"476",
"c. 800 BCE to 476 CE (conventional end in the West)",
"A combined label for Greek and Roman making: marble and bronze sculpture, painted pottery, glass, concrete, coinage and mosaic.",
"marble carving; bronze casting; painted pottery; glassblowing; concrete; mosaic",
"statues; vases; coins; mosaics; glass",
"rule and display;ritual and belief;exchange and value;shelter;play and music",
"Renaissance humanists; 18th–19th-century European classicism (Winckelmann); school curricula",
"Enslaved makers, who produced much of it; the non-Greek, non-Roman peoples of the Mediterranean; the painted colour lost to white-marble ideals; Byzantium; the use of the label to define 'Western civilisation'",
"human-flow;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Art Institute of Chicago (CC0);Wikimedia Commons;Europeana (filter by rights)",
"R2",
"F1.3;F1.2;F1.14;F1.23",
"high",
"Existing in project. Routes to CIV Greek and Roman sub-labels, Etruscan, Hellenistic.",
"canon_civilisations.csv"
],
[
"CIV072",
"Ancient Greek",
"Hellenic; Greece",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-800",
"-146",
"c. 800 BCE to 146 BCE (Roman conquest)",
"Greek city workshops made painted pottery, bronze and marble sculpture and coinage.",
"black- and red-figure pottery; bronze casting; marble carving",
"vases; statues; coins; temples",
"ritual and belief;rule and display;exchange and value;play and music",
"Renaissance and 19th-century classicism",
"Enslaved workers; women's textile production; non-Greek neighbours (Thracians, Scythians)",
"human-flow",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.3",
"high",
"Sub-label of existing 'Greek and Roman'; may merge.",
"canon_civilisations.csv"
],
[
"CIV073",
"Roman",
"Ancient Rome; Roman Empire",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.6;F1.9a",
"EU-GRR;EU-WCE;EU-IBE;EU-BLC;AF-MAG;AF-EGY;WA-LEV;WA-ANA",
"-753",
"476",
"traditional 753 BCE to 476 CE (West); East continues as Byzantine",
"Roman workshops made glass, concrete, mosaics, coinage and portraits at empire-wide scale.",
"glassblowing; concrete; mosaic; bronze casting",
"portraits; mosaics; glass; coins",
"rule and display;shelter;exchange and value;war",
"Renaissance and European classicism; national histories",
"Enslaved and freed workers who ran many workshops; provincial makers from Britain to Egypt credited only as 'Roman'; conquered peoples (Gauls, Dacians, Judaeans, Britons); the Eastern empire's continuation as Byzantium",
"human-flow",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Portable Antiquities Scheme (CC BY);Wikimedia Commons",
"R3",
"F1.3;F1.23",
"high",
"Sub-label of existing 'Greek and Roman'; may merge.",
"canon_civilisations.csv"
],
[
"CIV074",
"Minoan",
"Minoan Crete",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-3100",
"-1100",
"c. 3100–1100 BCE; palatial period c. 1950–1450 BCE",
"Cretan palace workshops made fresco, faience, carved stone vessels, seals and fine pottery (Kamares ware).",
"fresco; faience; stone-vessel carving; seal engraving; wheel-made pottery",
"frescoes; faience figures; seals; Kamares ware; Linear A tablets",
"ritual and belief;rule and display;record and writing;exchange and value",
"Arthur Evans (1900s), after the mythical King Minos",
"The self-name is unknown (Linear A undeciphered); Evans's heavy reconstructions at Knossos; non-palatial villages; forgeries of 'Minoan' goddesses",
"none",
"Met Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.14;F1.28a",
"high",
"Good case for F1.28a (reconstruction) and F1.14 (forgery).",
"canon_civilisations.csv"
],
[
"CIV075",
"Mycenaean",
"Mycenaean Greece; Late Helladic",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-1750",
"-1050",
"c. 1750–1050 BCE",
"Mycenaean palaces kept Linear B records of textile, perfume and bronze production by named workers.",
"Linear B; gold repoussé; bronze; fresco; textile",
"gold masks; tablets; weapons; stirrup jars",
"record and writing;rule and display;war;ritual and belief",
"Heinrich Schliemann (1876), after Mycenae",
"Workers listed in the tablets (many women textile workers, some probably unfree); neighbours in Anatolia and the Levant; the shaft graves as burials",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.23",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV076",
"Cycladic",
"Cycladic culture",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-3200",
"-2000",
"Early Cycladic c. 3200–2000 BCE; later Cycladic to c. 1100 BCE",
"Cycladic islanders carved marble figurines and vessels, many later modified to fit modernist taste.",
"marble carving; emery abrasion; painting (lost)",
"figurines; vessels",
"ritual and belief",
"Archaeologists; the 20th-century art market",
"Looting for collectors (most figures unprovenanced); lost paint; forgeries",
"funerary;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.2;F1.24",
"high",
"Most figures without context; good F1.24 case.",
"canon_civilisations.csv"
],
[
"CIV077",
"Etruscan",
"Etruria; Rasenna (self-name)",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-900",
"-27",
"c. 900 BCE (Villanovan) to 1st century BCE (absorbed by Rome)",
"Etruscan workshops produced bronze mirrors and statues, gold granulation, bucchero and painted tombs.",
"bronze casting and engraving; granulation; bucchero; tomb painting",
"mirrors; bucchero; sarcophagi; tomb paintings",
"ritual and belief;clothing and adornment;rule and display",
"Roman writers; Renaissance and 18th-century 'Etruscheria'",
"Most evidence comes from tombs; looting (tombaroli); the Villanovan roots; Italic neighbours",
"funerary;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV078",
"Byzantine",
"Eastern Roman Empire; Romaioi (self-name)",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.9a;F1.6",
"EU-BYZ;WA-ANA;WA-LEV;AF-EGY",
"330",
"1453",
"330 (Constantinople) to 1453",
"Byzantine workshops made mosaics, icons, silk, enamel and ivory for church and court.",
"mosaic; icon painting; cloisonné enamel; silk weaving; ivory carving",
"icons; mosaics; silks; enamels",
"ritual and belief;rule and display;clothing and adornment",
"Hieronymus Wolf (1557) coined 'Byzantine'; Enlightenment writers (Gibbon)",
"They called themselves Romans; Armenian, Slavic, Syriac and Coptic makers; enslaved people; the 1204 looting",
"sacred;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV079",
"Celtic",
"Celts; Keltoi; 'Celtic art'",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-WCE;EU-BLC;EU-IBE;EU-EER",
"-800",
"800",
"label stretched from Hallstatt (c. 800 BCE) through La Tène to early medieval Ireland and Britain",
"Iron Age and early medieval metalworkers made curvilinear La Tène ornament on weapons, torcs and mirrors, later echoed in Insular manuscripts.",
"bronze and gold smithing; enamel; repoussé; manuscript illumination",
"torcs; shields; mirrors; brooches; manuscripts",
"clothing and adornment;war;rule and display;ritual and belief",
"Greek and Roman writers ('Keltoi', 'Galli'); 18th-century antiquarians (Edward Lhuyd's language work); 19th-century nationalism and the Celtic Revival",
"The many unrelated peoples it lumps together; that ancient 'Celts' in Britain and Ireland are not so named in ancient sources; Iberian Celtiberians; the gap between language, art style and people; Romantic and nationalist inventions",
"none",
"Met Open Access (CC0);Portable Antiquities Scheme (CC BY);British Museum collection online (link out);Wikimedia Commons;Europeana (filter by rights)",
"R3",
"F1.3;F1.15",
"high",
"Routes to ARC Hallstatt and La Tène.",
"canon_civilisations.csv"
],
[
"CIV080",
"Norse / Viking",
"Viking Age; Vikings; Norse",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.7",
"EU-SCA;EU-BLC;EU-EER;AM-ARC",
"793",
"1066",
"Viking Age conventionally 793–1066; Norse Greenland to c. 1450",
"Norse shipwrights, smiths and carvers made clinker-built ships, pattern-welded swords, and carved wood and runestones.",
"clinker shipbuilding; pattern welding; wood carving; textile weaving; runic inscription",
"ships; swords; brooches; runestones; textiles",
"transport;war;clothing and adornment;record and writing;ritual and belief",
"Medieval chroniclers ('vikingr' = raider); 19th-century Scandinavian nationalism; popular media",
"The enslaved people (thralls) captured and traded; Sámi neighbours and trading partners; the farmers and women weavers who made the sails; Rus' and Islamic-world partners; far-right appropriation of Norse symbols",
"human-flow;funerary",
"Swedish History Museum (CC BY);National Museum of Denmark (CC BY-SA);DM;Portable Antiquities Scheme (CC BY);Wikimedia Commons;Europeana (filter by rights)",
"R3",
"F1.3;F1.13;F1.18",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV081",
"Thracian",
"Thracians",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-BYZ;EU-GRR",
"-1000",
"46",
"c. 1st millennium BCE to Roman annexation 46 CE",
"Thracian goldsmiths made gold and silver vessels and regalia, found mostly in tumulus burials.",
"gold and silver repoussé; tomb building; horse gear",
"rhyta; phialae; helmets; tomb paintings",
"rule and display;ritual and belief;clothing and adornment",
"Greek writers; Bulgarian national archaeology",
"Thracians were many tribes, not one; most finds come from burials; looting of tumuli in Bulgaria",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;Europeana (filter by rights)",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV082",
"Nuragic",
"Nuragic civilisation; Nuraghi",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-GRR",
"-1800",
"-238",
"c. 1800 BCE to Roman conquest 238 BCE",
"Sardinian communities built stone towers (nuraghi) and cast bronze figurines (bronzetti).",
"dry-stone tower building; bronze casting",
"nuraghi; bronzetti; well temples",
"shelter;ritual and belief;war",
"Sardinian and Italian archaeology (Giovanni Lilliu); UNESCO (Su Nuraxi, 1997)",
"The label implies a unified state; Phoenician and Punic neighbours; present-day Sardinians",
"none",
"Wikimedia Commons;Europeana (filter by rights);UNESCO World Heritage listing (link out)",
"R3",
"F1.3",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV083",
"Old Europe",
"Old European culture (Gimbutas)",
"civilisation-as-commonly-named",
"Composite",
"F1.11",
"EU-BYZ;EU-EER",
"-6500",
"-3500",
"c. 6500–3500 BCE (Neolithic and Copper Age southeastern Europe)",
"A label for Neolithic Balkan and Carpathian farming societies known for figurines, painted pottery and early copper and gold.",
"painted pottery; clay figurines; copper and gold working",
"figurines; painted pots; copper tools",
"ritual and belief;food and storage;clothing and adornment",
"Marija Gimbutas (1970s), with a contested 'goddess' interpretation",
"The diversity of cultures (Vinča, Cucuteni–Trypillia, Varna, Karanovo); the contested gender narrative; later populations",
"none",
"Wikimedia Commons;Europeana (filter by rights)",
"R3",
"F1.3;F1.16",
"high",
"Routes to ARC Vinča (existing), Cucuteni–Trypillia, Varna.",
"canon_civilisations.csv"
],
[
"CIV084",
"Moorish",
"Moors; Al-Andalus (partly)",
"civilisation-as-commonly-named",
"Composite",
"F1.11;F1.6;F1.10",
"EU-IBE;AF-MAG",
"711",
"1614",
"711 to the final expulsions of Moriscos 1609–1614",
"The label covers Andalusi and Maghribi workshops that made lustreware, carved ivory, silks, stucco and tilework.",
"lustreware; ivory carving; silk weaving; stucco; zellij tilework",
"pyxides; silks; lustre dishes; tiles",
"rule and display;ritual and belief;clothing and adornment",
"Medieval Christian chroniclers ('Mauri'); Romantic travellers; Spanish and Moroccan heritage",
"It flattens Arabs, Imazighen, Muslims, converts, Jews and Mozarabs into one term with racialised overtones; Mudéjar and Morisco makers under Christian rule; the expelled",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.2",
"high",
"Routes to CIV Islamic; label to explain, not endorse.",
"canon_civilisations.csv"
],
[
"CIV085",
"Western",
"Western civilisation; 'the West'",
"civilisation-as-commonly-named",
"Composite",
"THEME;F1.11",
"EU-WCE;EU-GRR;EU-BLC;EU-IBE;GL",
"-800",
"",
"a modern label claiming a line from Greece and Rome to modern Europe and North America",
"A curriculum label that organised much of museum and design-history teaching around European making.",
"",
"",
"",
"19th–20th-century European and US universities ('Western Civ' courses, from c. 1919 in the US); Samuel Huntington (1996)",
"Everything outside Europe and its settler colonies; the Islamic, Byzantine and African roots it borrows from; the colonised and enslaved whose labour and objects built its museums",
"none",
"Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"Search label; card explains the label.",
"canon_civilisations.csv"
],
[
"CIV086",
"Islamic",
"Islamic world; Islamic art",
"civilisation-as-commonly-named",
"Composite",
"F1.10",
"WA-ARB;WA-LEV;WA-MES;WA-IRN;WA-ANA;AF-EGY;AF-MAG;AF-SAH;AF-SWA;EU-IBE;AS-CEN;AS-SAS;AS-ISE;AS-CHN",
"622",
"",
"622 (hijra) to present",
"A label for the makers of many societies whose shared features include Arabic script, calligraphy, geometric ornament, glazed ceramics, carpets and metalwork.",
"calligraphy; lustreware; inlaid metal; carpet knotting; paper",
"Qur'ans; carpets; tiles; inlaid brass",
"record and writing;ritual and belief;rule and display;clothing and adornment;exchange and value",
"European art history and museums ('Islamic art' departments, 19th c.)",
"Non-Muslim makers (Christians, Jews, Zoroastrians) within Islamic societies; enslaved workers; regional traditions (West African, Southeast Asian, Chinese Muslim) often left out; present-day Muslim communities",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R2",
"F1.3;F1.13;F1.15",
"high",
"Existing in project.",
"canon_civilisations.csv"
],
[
"CIV087",
"Scythian",
"Scythians; Saka",
"civilisation-as-commonly-named",
"Composite",
"F1.12a;F1.11",
"AS-CEN;EU-EER;WA-CAU",
"-900",
"-200",
"c. 9th–3rd century BCE",
"Scythian and related steppe peoples made gold 'animal style' ornaments, horse gear and felt, preserved mainly in kurgan burials.",
"gold casting and repoussé; felt making; horse equipment",
"plaques; pectorals; bridle ornaments; felt hangings",
"clothing and adornment;rule and display;transport;war",
"Herodotus; Russian imperial collecting (Peter I's Siberian collection); Soviet archaeology",
"The many different peoples grouped under one name; most finds come from graves; Greek goldsmiths who made some pieces; looting",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_civilisations.csv"
],
[
"CIV088",
"Sogdian",
"Sogdiana; Sogdians",
"civilisation-as-commonly-named",
"Composite",
"F1.12a;F1.8",
"AS-CEN;AS-CHN",
"-500",
"1000",
"c. 6th century BCE to c. 10th century CE",
"Sogdian merchants and makers produced silver vessels, wall paintings and silks and carried goods across the Silk Road.",
"silverwork; wall painting; silk weaving",
"silver vessels; murals; funerary couches",
"exchange and value;rule and display;ritual and belief",
"Greek and Persian sources; Chinese records; 20th-century archaeology (Panjikent, Afrasiab)",
"Sogdian diaspora communities in China, whose funerary couches mix traditions; the plural identities of merchants; enslaved people traded on the same routes; the Arab conquest and later Islamic Sogdiana",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.13",
"medium",
"",
"canon_civilisations.csv"
],
[
"CIV089",
"Oxus",
"Oxus civilisation; BMAC; Bactria–Margiana",
"civilisation-as-commonly-named",
"Composite",
"F1.12a",
"AS-CEN",
"-2250",
"-1700",
"c. 2250–1700 BCE",
"Oxus (BMAC) settlements made compartmented seals and composite stone 'princess' figures.",
"soft-stone carving; metal casting",
"seals; composite figurines",
"ritual and belief;rule and display",
"Viktor Sarianidi (1970s); French archaeology (Henri-Paul Francfort)",
"The large number of looted and faked 'Bactrian' objects on the market; neighbouring Andronovo and Namazga communities; present-day Turkmen, Uzbek and Afghan communities",
"conflict-looting;funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.24",
"medium",
"Routes to ARC Bactria–Margiana Archaeological Complex.",
"canon_civilisations.csv"
],
[
"CIV090",
"Polynesian",
"Polynesia",
"civilisation-as-commonly-named",
"Composite",
"F1.12",
"OC-POL",
"-900",
"",
"Lapita arrival c. 900 BCE (Tonga, Samoa) to present",
"Polynesian makers built voyaging canoes, barkcloth, carved wood and stone, and navigation without instruments.",
"canoe building; barkcloth (tapa); wood and stone carving; featherwork",
"canoes; tapa; carvings; feather cloaks",
"transport;clothing and adornment;ritual and belief;rule and display",
"Jules Dumont d'Urville (1831); European voyagers",
"Living Polynesian nations (Māori, Hawaiian, Samoan, Tongan, Tahitian and others) and their own names and histories; the European racial ranking that set Polynesia above Melanesia; Micronesian and Melanesian neighbours; taonga taken to museums",
"Indigenous-community;sacred;ancestral;living-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY);Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_civilisations.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
