insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"CIV091",
"Lapita",
"Lapita culture; Lapita cultural complex",
"civilisation-as-commonly-named",
"Composite",
"F1.12",
"OC-MEL;OC-POL",
"-1350",
"-500",
"c. 1350–500 BCE from the Bismarck Archipelago to Tonga and Samoa",
"Lapita potters stamped intricate dentate designs on pottery as their communities voyaged into Remote Oceania for the first time.",
"dentate-stamped pottery; obsidian exchange; shell ornament; canoe voyaging",
"dentate-stamped pots; shell rings; obsidian tools",
"food and storage;ritual and belief;transport;exchange and value",
"Archaeologists, after the Lapita site in New Caledonia (excavated 1952)",
"Not a civilisation or state; the earlier Papuan-speaking peoples of Near Oceania; descendant Pacific communities who hold the designs in tattoo and tapa",
"Indigenous-community;ancestral",
"Wikimedia Commons;open-access excavation reports;Auckland Museum Collections Online (CC BY)",
"R3",
"F1.3",
"high",
"FLAG: rarely called a civilisation; label kept because searched. Routes to ARC Lapita (existing) and HOR Lapita horizon.",
"canon_civilisations.csv"
],
[
"CIV092",
"Rapa Nui",
"Easter Island civilisation",
"civilisation-as-commonly-named",
"Composite",
"F1.12",
"OC-POL",
"1150",
"",
"settlement c. 1150–1250 CE to present",
"Rapa Nui carvers quarried and moved nearly a thousand moai and made rongorongo tablets and wood carvings.",
"volcanic tuff carving; wood carving; rongorongo incision",
"moai; rongorongo tablets; wood figures",
"ritual and belief;record and writing;rule and display",
"European voyagers (Roggeveen, 1722); Jared Diamond's 'collapse' account (2005) and its critics",
"The 'ecocide' myth, contested by evidence that slave raids (1862) and introduced disease caused the population crash; the living Rapa Nui people; moai held abroad (e.g. Hoa Hakananai'a) and return requests",
"Indigenous-community;sacred;ancestral;living-community;human-flow",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3;F1.24;F1.22",
"high",
"Good F1.3 case: no 'rise and fall' unless evidence supports it.",
"canon_civilisations.csv"
],
[
"CIV093",
"Aboriginal and Torres Strait Islander",
"'oldest continuous culture/civilisation'",
"civilisation-as-commonly-named",
"Composite",
"F1.12",
"OC-AUS",
"-63000",
"",
"occupation of Australia from at least c. 65,000–50,000 years ago (debated) to present",
"Aboriginal and Torres Strait Islander makers have developed rock art, ground-edge axes, fibre work, eel-trap aquaculture and painting over tens of thousands of years.",
"rock painting and engraving; ground-edge stone; fibre weaving; bark painting; aquaculture",
"rock art; stone tools; fibre bags; bark paintings; shields",
"ritual and belief;tools;food and storage;clothing and adornment;record and writing",
"Popular media and government campaigns ('oldest continuous culture'); Aboriginal organisations",
"More than 250 language groups with their own names and laws; Torres Strait Islanders as distinct; that the phrase can freeze living cultures in the past; stolen objects and remains held in museums",
"Indigenous-community;sacred;ancestral;living-community",
"Museums Victoria Collections (CC BY / public domain);Wikimedia Commons;community-published site",
"R3",
"F1.3;F1.26;F1.24",
"high",
"Date: Madjedbebe claim c. 65,000 BP is debated; 'civilisation' is not a self-description; community consultation required.",
"canon_civilisations.csv"
],
[
"COM001",
"Copts",
"Coptic Christians; Aigyptios/Qibt (origin of the name)",
"community",
"People",
"F1.6",
"AF-EGY;AF-NUB",
"300",
"",
"c. 300 CE (Christian Egypt) to present; community continuity longer",
"Coptic weavers, scribes, icon painters and builders are credited with late antique tapestry textiles, bookbinding and icon painting, and the community still makes icons and church textiles.",
"tapestry weave;linen and wool;parchment;icon painting;bookbinding",
"textile;manuscript;icon;liturgical object",
"clothing and adornment; ritual and belief; record and writing",
"the community; ethnographic and museum usage",
"'Coptic' in museums often labels all late antique Egyptian textiles regardless of the maker's faith; it also covers Egyptian Coptic Catholic and Protestant communities",
"living-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons; Coptic Museum Cairo (view)",
"R2",
"F1.16;F1.18",
"high",
"links: BEL008; MKR012; STY083. Museum 'Coptic textile' label is a period label, not a community attribution; say so.",
"canon_communities.csv"
],
[
"COM002",
"Nubians",
"Nobiin- and Kenzi/Mattokki-speakers; Fadicca; Dongolawi; Barabra (dated exonym)",
"community",
"People",
"F1.6",
"AF-EGY;AF-NUB",
"-2500",
"",
"ancestral Nubian cultures from c. 2500 BCE; present communities displaced by Aswan dams 1902–1971",
"Nubian communities are known for painted and decorated house façades, basketry and beadwork, and many were resettled when the Aswan dams flooded their villages.",
"mud-brick building;painted plaster;basketry;beadwork;palm fibre",
"house façade;basket;plate cover;jewellery",
"shelter; clothing and adornment; food and storage; ritual and belief",
"the community; ethnographic and museum usage",
"Nobiin, Kenzi and Dongolawi speakers and Sudanese and Egyptian Nubians; ancient 'Nubia' labels in museums merge Kerma, Kush and medieval kingdoms with the living people",
"living-community; Indigenous-community; human-flow",
"Wikimedia Commons; Met Open Access (CC0); British Museum collection online (view; licence per image); Nubian Museum Aswan (view)",
"R2",
"F1.22;F1.24",
"medium",
"links: CIV002; OCC230; POL004. Dam resettlement is forced displacement; human-flow applied. Indigenous self-identification varies; verify.",
"canon_communities.csv"
],
[
"COM003",
"Siwi",
"Isiwan; Siwans (exonym)",
"community",
"People",
"F1.6",
"AF-EGY;AF-MAG",
"1200",
"",
"oasis town Shali founded c. 1203 by tradition; oasis older",
"The Amazigh community of Siwa oasis is known for kershef salt-mud building, silver jewellery and dense embroidery on wedding dresses and shawls.",
"kershef (salt-mud) building;silver;embroidery;palm fibre basketry",
"wedding dress;shawl;necklace (aghraw);basket",
"shelter; clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Siwi households and clans; tourist 'Siwa embroidery' markets merge commercial copies with community work",
"living-community; Indigenous-community",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R3",
"F1.18",
"medium",
"Shali date traditional; endonym Isiwan verified.",
"canon_communities.csv"
],
[
"COM004",
"Sinai Bedouin",
"Bedu of Sinai; Tarabin, Muzeina, Jebeliya and other tribes",
"community",
"People",
"F1.6;F1.10",
"AF-EGY;WA-LEV",
"1500",
"",
"tribal presence attested in Ottoman period; earlier roots",
"Sinai Bedouin women embroider cross-stitch dresses, face veils and bags whose colours signal tribe and marital status.",
"cross-stitch embroidery;goat-hair weaving;beadwork;coins",
"dress;face veil;camel bag;tent",
"shelter; clothing and adornment; transport; exchange and value",
"the community; ethnographic and museum usage",
"separate tribes (Tarabin, Muzeina, Jebeliya and others) with distinct styles; 'Bedouin' as a museum label joins Sinai with Naqab, Jordanian and Arabian groups",
"living-community",
"Wikimedia Commons; British Museum collection online (view; licence per image); Met Open Access (CC0)",
"R3",
"F1.18",
"medium",
"Start date is a placeholder; verify.",
"canon_communities.csv"
],
[
"COM005",
"Beja",
"Bidhaawyeet-speakers; Bishari, Hadendowa, Amarar, Beni-Amer",
"community",
"People",
"F1.6",
"AF-NUB;AF-EGY;AF-HRN",
"-500",
"",
"Blemmyes of classical sources are often identified as ancestors; approximate",
"Beja communities are known for silver and leather work, carved wooden combs and camel-herding equipment.",
"leatherwork;silver;wood carving;mat weaving",
"comb;shield;sword sheath;mat tent",
"shelter; clothing and adornment; transport; war",
"the community; ethnographic and museum usage",
"Hadendowa, Bishari, Amarar and Beni-Amer (the last speaking Tigre) under one name; the colonial 'Fuzzy-Wuzzy' caricature",
"living-community; Indigenous-community",
"British Museum collection online (view; licence per image); Pitt Rivers Museum collections online (view); Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"Blemmyes link is contested; endonym to verify. Rejected exonym 'Fuzzy-Wuzzy' deliberately not in other_names as a name.",
"canon_communities.csv"
],
[
"COM006",
"Jieng",
"Dinka (exonym)",
"community",
"People",
"F1.6",
"AF-NUB",
"1000",
"",
"approximate; cattle-herding ancestors older",
"Jieng communities make beaded corsets, carved headrests and cattle-related objects whose colours mark age and status.",
"glass beadwork;wood carving;ash and hide work",
"beaded corset;headrest;pipe;cattle bell",
"clothing and adornment; rule and display; food and storage",
"the community; ethnographic and museum usage",
"many sections (Rek, Agar, Bor and others); museum 'Nilotic' labels merge them with Naath and others",
"living-community; Indigenous-community",
"British Museum collection online (view; licence per image); Pitt Rivers Museum collections online (view); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Beaded corset dating and sectional variation to verify.",
"canon_communities.csv"
],
[
"COM007",
"Naath",
"Nuer (exonym)",
"community",
"People",
"F1.6",
"AF-NUB;AF-HRN",
"1000",
"",
"approximate",
"Naath communities make carved headrests, beadwork and cattle-horn objects, and body scarification marks initiation.",
"horn shaping;wood carving;beadwork",
"headrest;bracelet;cattle-horn training",
"clothing and adornment; ritual and belief; food and storage",
"the community; ethnographic and museum usage",
"eastern and western Naath; Evans-Pritchard's 1940 ethnography shaped the outside picture",
"living-community; Indigenous-community",
"Pitt Rivers Museum collections online (view); British Museum collection online (view; licence per image); Internet Archive (public-domain ethnographies; read critically)",
"R3",
"F1.3",
"medium",
"links: none. Pitt Rivers holds Evans-Pritchard photographs (view).",
"canon_communities.csv"
],
[
"COM008",
"Nuba peoples",
"Nuba (collective name for many Kordofan hill communities)",
"community",
"People",
"F1.6",
"AF-NUB",
"1000",
"",
"approximate",
"The many Nuba Mountains communities are known for body painting, pottery and wrestling regalia; outside photography made some groups famous without consent.",
"body painting;ochre;pottery;basketry",
"body painting;wrestling bracelet;pot",
"clothing and adornment; play and music; ritual and belief",
"the community; ethnographic and museum usage",
"over fifty language communities (Moro, Otoro, Kao, Nyaro and others) flattened by one name; the Riefenstahl photographs",
"living-community; Indigenous-community",
"Pitt Rivers Museum collections online (view); Wikimedia Commons",
"R3",
"F1.26;F1.2",
"medium",
"Name is a collective, not one endonym; say so.",
"canon_communities.csv"
],
[
"COM009",
"Fur",
"For; Fora",
"community",
"People",
"F1.6",
"AF-NUB;AF-SAH",
"1600",
"",
"Keira sultanate c. 1650–1916; community older",
"Fur communities are known for pottery, leather and basketry, and the Darfur sultanate's court used imported cloth and armour.",
"pottery;leatherwork;basketry",
"pot;saddle;basket",
"food and storage; transport; rule and display",
"the community; ethnographic and museum usage",
"Darfur's many other peoples; the sultanate label",
"living-community; Indigenous-community; conflict-looting",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R3",
"F1.19a",
"low",
"Sultanate dates to verify; conflict since 2003 affects heritage.",
"canon_communities.csv"
],
[
"COM010",
"Imazighen",
"Amazigh (sing.); Berber (rejected exonym for many)",
"community",
"People",
"F1.6;F1.10",
"AF-MAG;AF-SAH;AF-EGY",
"-1000",
"",
"Libyco-Berber inscriptions from 1st millennium BCE; approximate",
"Amazigh communities across North Africa make flat-woven and knotted rugs, silver jewellery, painted pottery and Tifinagh-inscribed objects, much of it by women.",
"flat-weaving;pile knotting;silver casting and enamel;handmade pottery;Tifinagh",
"rug;fibula;necklace;pot;wedding textile",
"shelter; clothing and adornment; rule and display; record and writing",
"the community; ethnographic and museum usage",
"Kabyle, Rifian, Shilha, Mozabite, Chaoui, Siwi and Kel Tamasheq among others; 'Berber rug' markets that erase named weavers",
"living-community; Indigenous-community",
"Met Open Access (CC0); British Museum collection online (view; licence per image); musée du quai Branly collections online (view); Wikimedia Commons; Europeana",
"R1",
"F1.18;F1.2;F1.26",
"high",
"'Berber' is widely used but rejected by many; recorded as contested. links: PRA011; PRA012; MKR014.",
"canon_communities.csv"
],
[
"COM011",
"Iqbayliyen",
"Kabyles (exonym form); Leqbayel",
"community",
"People",
"F1.6",
"AF-MAG",
"1000",
"",
"approximate",
"Kabyle women make hand-built painted pottery and men and women make enamelled silver jewellery associated with Ath Yenni.",
"hand-built pottery;cloisonné enamel on silver;weaving",
"pot;lamp;fibula;brooch",
"clothing and adornment; food and storage; rule and display",
"the community; ethnographic and museum usage",
"village confederations; French colonial ethnography that made 'Kabyle art' a category",
"living-community; Indigenous-community",
"musée du quai Branly collections online (view); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.18;F1.3",
"high",
"links: Imazighen row.",
"canon_communities.csv"
],
[
"COM012",
"Ishelḥiyen",
"Chleuh (French rendering of the self-name); Shilha-speakers; Soussi",
"community",
"People",
"F1.6",
"AF-MAG",
"1000",
"",
"approximate",
"Shilha-speaking communities of the Souss and Anti-Atlas are associated with silver jewellery centres such as Tiznit and with granary (agadir) building.",
"silver;enamel;rammed earth;stone",
"necklace;fibula;agadir granary",
"shelter; clothing and adornment; food and storage",
"the community; ethnographic and museum usage",
"Jewish silversmiths who made much 'Berber' silver before emigration; tribal diversity",
"living-community; Indigenous-community",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.23",
"medium",
"Endonym išelḥiyen verified (also written Ishelhien); links: Moroccan Jewish communities row.",
"canon_communities.csv"
],
[
"COM013",
"Ait Mzab",
"Mozabites (exonym)",
"community",
"People",
"F1.6;F1.10",
"AF-MAG",
"1000",
"",
"M'zab towns founded 11th c.; approximate",
"The Ibadi community of the M'zab valley built the five walled towns of Ghardaïa and weaves rugs with distinctive geometric designs.",
"plaster and stone building;wool weaving",
"town;mosque;rug",
"shelter; ritual and belief",
"the community; ethnographic and museum usage",
"women weavers; the Ibadi religious framing",
"living-community; Indigenous-community",
"Wikimedia Commons; UNESCO ICH pages (text; status to verify)",
"R3",
"F1.16",
"medium",
"links: BEL019. UNESCO status of M'zab valley to verify.",
"canon_communities.csv"
],
[
"COM014",
"Sahrawi",
"Saharawi; Ahl as-Sahel",
"community",
"People",
"F1.6",
"AF-MAG;AF-SAH",
"1600",
"",
"Hassaniya-speaking tribal formation from c. 16th c.; approximate",
"Sahrawi women make leather cushions and bags and the large woven khaima tent, and refugee camps sustain these crafts.",
"leatherwork;goat-hair tent weaving;dyed cloth (melhfa)",
"tent;leather bag;cushion",
"shelter; clothing and adornment; transport",
"the community; ethnographic and museum usage",
"tribes and refugee and non-refugee populations; disputed territory",
"living-community; Indigenous-community; human-flow",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"Displacement since 1975 is central to the community's present; human-flow applied.",
"canon_communities.csv"
],
[
"COM015",
"Moroccan Jewish communities",
"Maghrebi Jews; Toshavim and Megorashim",
"community",
"People",
"F1.6;F1.10",
"AF-MAG",
"-100",
"",
"presence from antiquity; most emigrated 1948–1970s",
"Jewish silversmiths, embroiderers and bookmakers were central to Moroccan jewellery and textile production until emigration, and a community of about 1,000 remains in Morocco.",
"silversmithing;gold embroidery;enamel",
"jewellery;wedding dress (keswa kbira);Torah case",
"clothing and adornment; ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"Indigenous (toshavim) and Iberian-origin (megorashim) Jews; Amazigh clients whose 'Berber' jewellery Jews made",
"living-community",
"Met Open Access (CC0); Wikimedia Commons; Israel Museum (view)",
"R3",
"F1.23;F1.2",
"medium",
"links: OCC051. Start date approximate.",
"canon_communities.csv"
],
[
"COM016",
"Kel Tamasheq",
"Tuareg (exonym); Kel Tamajaq; Kel Tamahaq",
"community",
"People",
"F1.6",
"AF-SAH;AF-MAG",
"500",
"",
"approximate; Tifinagh script older",
"Kel Tamasheq smiths (inaden) make silver crosses, leather bags, saddles and locks, and women make tents and leatherwork.",
"silver casting;lost-wax;leather dyeing;Tifinagh",
"cross pendant;camel saddle;leather bag;tent",
"shelter; clothing and adornment; transport; record and writing",
"the community; ethnographic and museum usage",
"confederations (Kel Aïr, Kel Ahaggar, Kel Adagh and others) and the inaden caste of smiths",
"living-community; Indigenous-community; conflict-looting",
"Met Open Access (CC0); British Museum collection online (view; licence per image); musée du quai Branly collections online (view); Wikimedia Commons",
"R2",
"F1.23;F1.19a",
"high",
"links: MKR009; PRA014. Endonym varies by dialect.",
"canon_communities.csv"
],
[
"COM017",
"Bamanan",
"Bamana; Bambara (exonym)",
"community",
"People",
"F1.6",
"AF-SAH",
"1600",
"",
"Ségou state c. 1712–1861; community older",
"Bamanan communities make bogolan mud cloth, ci wara headcrests and Jo and Kore society figures, and bogolan is now also a design industry.",
"mud-dye;wood carving;iron forging",
"bogolan cloth;ci wara headcrest;figure",
"clothing and adornment; ritual and belief; play and music",
"the community; ethnographic and museum usage",
"blacksmith (numu) and other nyamakala castes; Mande neighbours merged in museum labels",
"living-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Art Institute of Chicago (CC0 images); British Museum collection online (view; licence per image); Wikimedia Commons",
"R1",
"F1.18;F1.2;F1.16",
"high",
"links: MKR007; MKR008; PRA004. Many society objects are sacred.",
"canon_communities.csv"
],
[
"COM018",
"Dogon",
"Dogon (self-used)",
"community",
"People",
"F1.6",
"AF-SAH",
"1400",
"",
"arrival on Bandiagara escarpment c. 15th c. by tradition",
"Dogon communities are known for carved granary doors, masks for dama rites and cliff villages, and museums often mislabel Tellem objects as Dogon.",
"wood carving;iron;mud building;indigo",
"mask;granary door;figure;toguna",
"shelter; ritual and belief; food and storage",
"the community; ethnographic and museum usage",
"the Tellem and other earlier escarpment peoples; many language varieties; Griaule's contested ethnography",
"living-community; sacred; conflict-looting",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); musée du quai Branly collections online (view); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.3;F1.24",
"high",
"Griaule-era claims (Sirius) contested; theft from escarpment sites documented; conflict-looting applied.",
"canon_communities.csv"
],
[
"COM019",
"Senufo",
"Siena; Syénambélé (Senambele); Senoufo (French); Senara (one subgroup)",
"community",
"People",
"F1.6",
"AF-SAH;AF-GUI",
"1600",
"",
"approximate",
"Senufo communities are known for Poro society masks and figures, carved by specialist sculptor groups, and for Korhogo painted cloth.",
"wood carving;brass casting;mud painting on cloth",
"mask;rhythm pounder;bird figure;Korhogo cloth",
"ritual and belief; play and music; clothing and adornment",
"the community; ethnographic and museum usage",
"Kulebele carvers and Fonombele smiths; Supyire and other language groups",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16;F1.23",
"high",
"links: PRA027. The name Senufo is of external origin and subgroups use their own names; no single endonym, so the widely used name is kept (endonym to verify).",
"canon_communities.csv"
],
[
"COM020",
"Bwa",
"Bwaba",
"community",
"People",
"F1.6",
"AF-SAH",
"1600",
"",
"approximate",
"Bwa communities make large painted plank masks and leaf masks for the Do cult; their neighbours are often credited with them.",
"wood carving;earth pigment;leaf",
"plank mask;leaf mask",
"ritual and belief; play and music",
"the community; ethnographic and museum usage",
"Nuna, Winiama and Mossi neighbours whose masks are merged with Bwa ones",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_communities.csv"
],
[
"COM021",
"Moose",
"Mossi (exonym form)",
"community",
"People",
"F1.6",
"AF-SAH",
"1400",
"",
"kingdoms from c. 15th c.",
"Moose communities make carved wooden masks and dolls, weave strip cloth and cast brass, some in Ouagadougou workshops.",
"wood carving;narrow-strip weaving;brass casting",
"mask;doll (biiga);strip cloth",
"ritual and belief; play and music; clothing and adornment",
"the community; ethnographic and museum usage",
"Nyonyose (earlier peoples) who carry the masks; Nakomse rulers",
"living-community",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R3",
"",
"medium",
"links: POL038.",
"canon_communities.csv"
],
[
"COM022",
"Fulɓe",
"Fulani (Hausa-derived exonym); Peul (French); Fula",
"community",
"People",
"F1.6",
"AF-SAH;AF-GUI",
"1000",
"",
"approximate",
"Fulɓe herders and women artisans make engraved calabashes, gold and amber jewellery and khasa wool blankets woven by specialists.",
"calabash engraving;gold hammering;wool weaving",
"calabash;earring;khasa blanket;hat",
"clothing and adornment; food and storage; exchange and value",
"the community; ethnographic and museum usage",
"Wodaabe and settled Fulɓe; weaver castes (maabuɓe) in Mali",
"living-community",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_communities.csv"
],
[
"COM023",
"Wolof",
"Wolof",
"community",
"People",
"F1.6",
"AF-SAH",
"1300",
"",
"Jolof state from c. 14th c.",
"Wolof communities are associated with gold filigree jewellery, fabric wrapping, sous-verre glass painting and dress fashion in Dakar.",
"gold filigree;reverse glass painting;dyed cloth",
"jewellery;glass painting;boubou",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"caste groups of smiths (tëgg) and griots",
"living-community",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R3",
"F1.21",
"medium",
"links: STY092 Souwere.",
"canon_communities.csv"
],
[
"COM024",
"Hausawa",
"Hausa",
"community",
"People",
"F1.6",
"AF-SAH",
"1000",
"",
"Hausa city-states from c. 11th c.",
"Hausa dyers, embroiderers and builders are known for indigo pits, embroidered robes and plastered relief architecture.",
"indigo dyeing;hand embroidery;mud plaster relief",
"riga robe;dyed cloth;decorated house",
"shelter; clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Fulɓe ruling class after 1804; Kano dyers' guilds",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.18",
"high",
"links: POL032; MKR006.",
"canon_communities.csv"
],
[
"COM025",
"Bozo",
"Sorogo; Bozo",
"community",
"People",
"F1.6",
"AF-SAH",
"1000",
"",
"approximate",
"Bozo fisher communities build boats and are associated with masonry guilds (barey ton) at Djenné.",
"boat-building;earth masonry;net making",
"pirogue;mosque plaster;net",
"shelter; transport; food and storage",
"the community; ethnographic and museum usage",
"Marka and Songhay masons merged in the Djenné story",
"living-community",
"Wikimedia Commons; UNESCO ICH pages (text; status to verify)",
"R3",
"F1.28a",
"medium",
"links: PRA017. Mason-guild attribution to verify.",
"canon_communities.csv"
],
[
"COM026",
"Kassena",
"Kasena; Gurunsi (collective exonym)",
"community",
"People",
"F1.6",
"AF-SAH;AF-GUI",
"1500",
"",
"approximate",
"Kassena women paint geometric designs on the walls of compounds such as those at Tiébélé.",
"earth plaster;mineral pigment;burnishing",
"painted house",
"shelter; ritual and belief",
"the community; ethnographic and museum usage",
"Nankani and other Gurunsi groups",
"living-community",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_communities.csv"
],
[
"COM027",
"Yorùbá",
"Yoruba; Anago; Lucumí (Cuba, diaspora); Nagô (Brazil, diaspora)",
"community",
"People",
"F1.6",
"AF-GUI;AM-CAR;AM-LAT",
"1000",
"",
"Ife from c. 1000 CE; the collective name spread in the 19th c.",
"Yorùbá carvers, casters, weavers and dyers make ère ìbejì figures, Gẹ̀lẹ̀dẹ́ masks, beaded crowns, aṣọ òkè and adìrẹ cloth, and named masters such as Olowe of Ise are credited.",
"wood carving;beadwork;indigo resist dye;strip weaving;brass casting",
"twin figure;mask;beaded crown;veranda post;adire cloth",
"ritual and belief; rule and display; clothing and adornment; play and music",
"the community; ethnographic and museum usage",
"Ekiti, Ọ̀yọ́, Ìjẹ̀bú, Ẹ̀gbá and other sub-groups; diaspora communities; named carvers credited only as 'Yoruba'",
"living-community; sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Art Institute of Chicago (CC0 images); British Museum collection online (view; licence per image); Wikimedia Commons",
"R1",
"F1.26;F1.16;F1.18",
"high",
"links: BEL042; STY085; PRA003; PRA005; SCH014.",
"canon_communities.csv"
],
[
"COM028",
"Edo",
"Bini; Benin (exonym for the kingdom)",
"community",
"People",
"F1.6",
"AF-GUI",
"1200",
"",
"kingdom from c. 13th c.",
"Edo guilds in Benin City cast brass heads and plaques and carve ivory for the Oba's court, and the Igun Eronmwon guild still casts.",
"lost-wax brass casting;ivory carving;coral beadwork",
"commemorative head;plaque;tusk;altar",
"rule and display; ritual and belief",
"the community; ethnographic and museum usage",
"guild members (Igun Eronmwon, Igbesanmwan) credited only as 'Benin'; Esan and other peoples of the kingdom",
"living-community; sacred; conflict-looting",
"Digital Benin (digitalbenin.org); Met Open Access (CC0); British Museum collection online (view; licence per image); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R1",
"F1.24;F1.26",
"high",
"links: CIV012; DYN038; MKR001; MKR002; OCC175; STY086; PRA019.",
"canon_communities.csv"
],
[
"COM029",
"Ndi Igbo",
"Igbo",
"community",
"People",
"F1.6",
"AF-GUI",
"850",
"",
"Igbo-Ukwu c. 9th–10th c.; approximate",
"Igbo communities make ikenga shrine figures, mbari clay houses, uli body and wall painting and masks, and Nsukka artists drew on uli.",
"wood carving;clay modelling;uli painting;bronze casting",
"ikenga;mbari house;mask;uli drawing",
"ritual and belief; rule and display; clothing and adornment",
"the community; ethnographic and museum usage",
"many autonomous towns; Igbo-Ukwu as a separate archaeological site; Biafra war losses",
"living-community; sacred; conflict-looting",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R2",
"F1.16;F1.20",
"high",
"links: ARC034; STY084; SCH015.",
"canon_communities.csv"
],
[
"COM030",
"Asantefoɔ",
"Asante; Ashanti (older exonym form)",
"community",
"People",
"F1.6",
"AF-GUI",
"1680",
"",
"Asante state c. 1680s–1901; community ongoing",
"Asante weavers, goldsmiths and carvers make kente, gold regalia, goldweights and stools, and regalia looted in 1874 are now partly on loan back.",
"strip weaving;lost-wax gold casting;wood carving;adinkra stamping",
"kente;stool;gold ornament;goldweight",
"rule and display; exchange and value; clothing and adornment",
"the community; ethnographic and museum usage",
"other Akan peoples (Fante, Akuapem, Bono) whose work is labelled Asante; Ewe kente weavers",
"living-community; sacred; conflict-looting",
"Manhyia Palace Museum (view); Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.24;F1.18",
"high",
"links: POL029; DYN039; MKR003; PRA002; PRA020; STY088; OCC155; OCC292.",
"canon_communities.csv"
],
[
"COM031",
"Fon",
"Fɔngbe-speakers",
"community",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"Dahomey c. 1600–1894",
"Fon artists make appliqué hangings and iron and brass sculpture, forms developed in the Dahomey court workshops, and the Yemadje family workshops in Abomey continue.",
"appliqué;iron forging;brass casting",
"appliqué hanging;asen altar;bocio figure;throne",
"rule and display; ritual and belief",
"the community; ethnographic and museum usage",
"Yoruba and other captive artisans at Abomey; enslaved people sold through Ouidah",
"living-community; sacred; human-flow; conflict-looting",
"musée du quai Branly collections online (view); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.24;F1.23",
"high",
"links: POL030; BEL043; MKR005; OCC171. Dahomey's slave trade is central: human-flow.",
"canon_communities.csv"
],
[
"COM032",
"Ewe",
"Eʋe",
"community",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"approximate",
"Ewe weavers make strip-woven kete cloth, and Ewe communities make Vodun shrine objects.",
"strip weaving;wood carving",
"kete cloth;shrine figure",
"clothing and adornment; ritual and belief",
"the community; ethnographic and museum usage",
"Ewe in Ghana and Togo; kente attributed only to Asante",
"living-community; sacred",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.18",
"high",
"links: BEL043; PRA002.",
"canon_communities.csv"
],
[
"COM033",
"Ga",
"Ga-Dangme (with Dangme)",
"community",
"People",
"F1.6",
"AF-GUI",
"1500",
"",
"approximate",
"Ga carpenters in Teshie make figurative coffins (abebuu adekai) for funerals, now also for galleries.",
"wood carving;paint",
"figurative coffin",
"ritual and belief",
"the community; ethnographic and museum usage",
"named workshops such as Kane Kwei's; Dangme",
"living-community; funerary",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: STY179.",
"canon_communities.csv"
],
[
"COM034",
"Fante",
"Mfantse",
"community",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"approximate",
"Fante asafo military companies commission appliqué and patchwork flags from specialist flag-makers and build cement posuban shrines.",
"appliqué;cement sculpture",
"flag;posuban shrine",
"rule and display; war",
"the community; ethnographic and museum usage",
"individual companies and named flag-makers credited only as 'Fante'; other Akan coastal groups",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"",
"high",
"links: STY180.",
"canon_communities.csv"
],
[
"COM035",
"Krobo",
"Klo",
"community",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"approximate",
"Krobo bead makers recycle glass into powder-glass beads for dipo initiation and trade.",
"powder-glass bead firing",
"bead",
"clothing and adornment; ritual and belief; exchange and value",
"the community; ethnographic and museum usage",
"Dangme neighbours; imported beads",
"living-community",
"Wikimedia Commons",
"R3",
"",
"high",
"links: PRA018.",
"canon_communities.csv"
],
[
"COM036",
"Baule",
"Baoulé",
"community",
"People",
"F1.6",
"AF-GUI",
"1700",
"",
"migration from Asante area c. 18th c. by tradition",
"Baule carvers make portrait masks, spirit-spouse figures and gold ornaments, and some figures are named to individual sculptors in recent research.",
"wood carving;gold casting;weaving",
"portrait mask;spirit-spouse figure;gold pendant",
"ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"Guro and Yohure neighbours; named carvers such as Owie Kimou",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Cleveland Museum of Art Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.26",
"high",
"",
"canon_communities.csv"
],
[
"COM037",
"Dan",
"Dan (self-used); Gio (exonym in Liberia)",
"community",
"People",
"F1.6",
"AF-GUI",
"1600",
"",
"approximate",
"Dan carvers make face masks and large spoons for honoured hosts, and named carvers such as Zlan are credited.",
"wood carving",
"mask;feast ladle (wakemia)",
"ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"We (Guéré) and Mano neighbours; named carvers",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Cleveland Museum of Art Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.26",
"high",
"",
"canon_communities.csv"
],
[
"COM038",
"Mende",
"Mɛnde",
"community",
"People",
"F1.6",
"AF-GUI",
"1500",
"",
"approximate",
"Mende carvers make helmet masks worn by women of the Sande society, one of the few masks African women wear.",
"wood carving;blackened finish",
"sowei helmet mask",
"ritual and belief; clothing and adornment",
"the community; ethnographic and museum usage",
"Temne, Gola and Vai Sande/Bondo societies; male carvers of female masks",
"living-community; sacred",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.16;F1.18",
"high",
"links: GAP sowei row in blindmap.",
"canon_communities.csv"
],
[
"COM039",
"Ijaw",
"Izon; Ijo; Kalabari (subgroup)",
"community",
"People",
"F1.6",
"AF-GUI",
"1400",
"",
"approximate",
"Kalabari women cut threads from imported cloth to make pelete bite, and Ijaw carvers make water-spirit masks and ancestral screens.",
"cut-thread cloth;wood carving",
"pelete bite cloth;mask;ancestral screen",
"clothing and adornment; ritual and belief",
"the community; ethnographic and museum usage",
"Kalabari, Nembe, Okrika and other Ijaw polities",
"living-community; sacred; ancestral",
"British Museum collection online (view; licence per image); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_communities.csv"
],
[
"COM040",
"Ejagham",
"Ekoi (exonym)",
"community",
"People",
"F1.6",
"AF-GUI;AF-CEN",
"1600",
"",
"approximate",
"Ejagham carvers make skin-covered headdresses and use nsibidi signs, a graphic system shared across the Cross River.",
"skin-covered carving;nsibidi",
"skin-covered headdress;cloth",
"ritual and belief; record and writing",
"the community; ethnographic and museum usage",
"Efik and Ekpe society members across groups",
"living-community; sacred",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.5",
"medium",
"nsibidi as writing is debated; F1.5 link.",
"canon_communities.csv"
],
[
"COM041",
"Sapi",
"Sapes (Portuguese usage); ancestors of Temne and Bullom",
"community",
"People",
"F1.6",
"AF-GUI",
"1450",
"1600",
"historical; c. 1490–1550 ivory production",
"Sapi carvers are credited with ivory saltcellars and oliphants carved for Portuguese buyers.",
"ivory carving",
"saltcellar;oliphant;spoon",
"exchange and value; rule and display",
"the community; ethnographic and museum usage",
"Temne and Bullom descendants",
"none",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.2;F1.13",
"medium",
"links: STY087. Historical grouping; descendants living.",
"canon_communities.csv"
],
[
"COM042",
"Kuba peoples",
"Bakuba (Luba-derived exonym); Bushoong and some 18 subgroups",
"community",
"People",
"F1.6",
"AF-CEN",
"1600",
"",
"kingdom from c. 17th c.",
"Kuba men weave raffia and women embroider cut-pile and appliqué panels, and carvers make ndop portrait figures and masks.",
"raffia weaving;cut-pile embroidery;appliqué;wood carving",
"raffia skirt;cut-pile panel;ndop figure;mask;cup",
"clothing and adornment; rule and display; ritual and belief",
"the community; ethnographic and museum usage",
"Bushoong, Kete, Ngeende and other subgroups; women embroiderers",
"living-community; sacred",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R1",
"F1.18;F1.15",
"high",
"links: POL022; STY089; PRA006; TEC125.",
"canon_communities.csv"
],
[
"COM043",
"Baluba",
"Luba",
"community",
"People",
"F1.6",
"AF-CEN",
"1500",
"",
"kingdom c. 1585–1889",
"Luba sculptors make stools and staffs with female figures and lukasa memory boards used by the Mbudye society.",
"wood carving;beadwork;iron",
"caryatid stool;lukasa memory board;staff",
"rule and display; record and writing; ritual and belief",
"the community; ethnographic and museum usage",
"Shankadi, Hemba and other Luba-related groups; Buli-style carvers",
"living-community; sacred",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R2",
"F1.5;F1.16",
"high",
"links: POL023.",
"canon_communities.csv"
],
[
"COM044",
"Chokwe",
"Tshokwe; Kioko (older form)",
"community",
"People",
"F1.6",
"AF-CEN;AF-SOU",
"1600",
"",
"approximate",
"Chokwe carvers make chief's chairs, mwana pwo masks and the Chibinda Ilunga hunter figure, and Chokwe sand drawings (sona) are studied by mathematicians.",
"wood carving;brass tacks;sand drawing",
"chair;mwana pwo mask;figure;sona",
"rule and display; ritual and belief; play and music",
"the community; ethnographic and museum usage",
"Lunda and Luvale neighbours; Makishi shared across groups",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.26;F1.15",
"high",
"links: PRA028; AP 173.",
"canon_communities.csv"
],
[
"COM045",
"Bakongo",
"Kongo",
"community",
"People",
"F1.6",
"AF-CEN;AM-CAR;AM-LAT",
"1390",
"",
"kingdom from c. 1390; diaspora via Atlantic slave trade",
"Kongo communities make minkisi power figures, prestige textiles and Christian crucifixes, and Kongo ideas shaped making in the Americas.",
"wood carving;iron nails;raffia weaving;brass casting",
"nkisi;crucifix;raffia cloth;grave marker",
"ritual and belief; rule and display; clothing and adornment",
"the community; ethnographic and museum usage",
"Vili, Yombe, Woyo and other Kongo subgroups; enslaved Kongo people in the Americas",
"living-community; sacred; human-flow",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Art Institute of Chicago (CC0 images); Wikimedia Commons; Wereldmuseum / NMVW collections online (view; licence per item)",
"R1",
"F1.16;F1.24",
"high",
"links: CIV013; POL020; BEL045; PLC054.",
"canon_communities.csv"
],
[
"COM046",
"Fang",
"Ekang; Pahouin (exonym)",
"community",
"People",
"F1.6",
"AF-CEN",
"1700",
"",
"approximate",
"Fang communities in Gabon, Cameroon and Equatorial Guinea keep carving and masking traditions, while most byeri guardian figures made for ancestor reliquaries left the region in the colonial era.",
"wood carving;oil patina",
"byeri figure;ngil mask",
"ritual and belief",
"the community; ethnographic and museum usage",
"Ntumu, Okak, Betsi and other subgroups; Kota and Punu neighbours",
"living-community; sacred; ancestral",
"Met Open Access (CC0); musée du quai Branly collections online (view); Wikimedia Commons",
"R2",
"F1.24;F1.2",
"high",
"links: STY062.",
"canon_communities.csv"
],
[
"COM047",
"Basongye",
"Songye",
"community",
"People",
"F1.6",
"AF-CEN",
"1500",
"",
"approximate",
"Songye carvers make mankishi power figures and kifwebe striated masks.",
"wood carving;iron;animal materials",
"nkishi figure;kifwebe mask",
"ritual and belief",
"the community; ethnographic and museum usage",
"Luba neighbours; nganga specialists",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_communities.csv"
],
[
"COM048",
"Mangbetu",
"Mangbetu",
"community",
"People",
"F1.6",
"AF-CEN",
"1800",
"",
"kingdom 19th c.",
"Mangbetu makers are known for anthropomorphic pottery, harps and ivory, much of it made in the early 20th c. for Belgian and other collectors, and this work shaped outside ideas of Congo art.",
"pottery;wood carving;ivory",
"anthropomorphic jar;harp;knife",
"rule and display; play and music",
"the community; ethnographic and museum usage",
"Zande and other makers; objects made for the colonial market",
"living-community",
"Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R3",
"F1.2",
"medium",
"links: POL024.",
"canon_communities.csv"
],
[
"COM049",
"Grassfields peoples",
"Bamiléké (exonym for a group of chiefdoms); Bamum; Bafut; Kom",
"community",
"People",
"F1.6",
"AF-CEN",
"1400",
"",
"approximate",
"Grassfields chiefdoms make beaded thrones, masks, carved house posts and ndop cloth.",
"beadwork;wood carving;resist dye",
"beaded throne;elephant mask;house post;ndop cloth",
"rule and display; ritual and belief; clothing and adornment",
"the community; ethnographic and museum usage",
"over 100 chiefdoms each named for itself; 'Bamileke' is a colonial collective",
"living-community; sacred; conflict-looting",
"Met Open Access (CC0); British Museum collection online (view; licence per image); musée du quai Branly collections online (view); Wikimedia Commons",
"R2",
"F1.26",
"high",
"links: MKR004; POL025; AP 178. Afo-A-Kom return (1973) link: OCC row to verify.",
"canon_communities.csv"
],
[
"COM050",
"Balega",
"Lega",
"community",
"People",
"F1.6",
"AF-CEN",
"1600",
"",
"approximate",
"Lega members of the Bwami society own small ivory and wooden figures and masks tied to rank.",
"ivory carving;wood carving",
"figure;mask;spoon",
"ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"Bembe and other neighbours",
"living-community; sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_communities.csv"
],
[
"COM051",
"Bapende",
"Pende",
"community",
"People",
"F1.6",
"AF-CEN",
"1600",
"",
"approximate",
"Pende carvers make mbuya village masks and small ivory ikhoko pendants, and Pende masquerades continue.",
"wood carving;ivory",
"mask;pendant",
"ritual and belief; play and music",
"the community; ethnographic and museum usage",
"Kwilu and Kasai Pende; Chokwe and Yaka neighbours",
"living-community; sacred",
"Met Open Access (CC0); Art Institute of Chicago (CC0 images); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_communities.csv"
],
[
"COM052",
"Mbuti",
"BaMbuti; 'Pygmy' (rejected exonym)",
"community",
"People",
"F1.6",
"AF-CEN",
"1000",
"",
"approximate",
"Mbuti women paint barkcloth with freehand patterns in the Ituri forest, work now shown as painting.",
"barkcloth beating;gardenia and charcoal painting",
"painted barkcloth",
"clothing and adornment; play and music",
"the community; ethnographic and museum usage",
"Efe, Asua and other forest peoples; Lese and Bila farmer neighbours who trade the cloth",
"living-community; Indigenous-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"'Pygmy' marked as rejected exonym.",
"canon_communities.csv"
],
[
"COM053",
"Amhara",
"Amara",
"community",
"People",
"F1.6",
"AF-HRN",
"1270",
"",
"Solomonic dynasty from 1270; community older",
"Amhara communities are associated with Orthodox church painting, parchment manuscripts, processional crosses and handwoven cotton (shemma).",
"parchment;egg-tempera painting;brass casting;cotton weaving",
"manuscript;icon;processional cross;netela shawl",
"ritual and belief; record and writing; clothing and adornment",
"the community; ethnographic and museum usage",
"Tigrayans and Agaw who share the church tradition; weavers (often low-status) and smiths",
"living-community; sacred; conflict-looting",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wellcome Collection (CC BY); Wikimedia Commons",
"R2",
"F1.16;F1.24",
"high",
"links: BEL009; MKR011; PRA008; OCC Maqdala 1868 (see OCC register); PLC069.",
"canon_communities.csv"
],
[
"COM054",
"Tigrinya-speaking peoples",
"Tegaru (Tigray); Bihera Tigrinya (Eritrea)",
"community",
"People",
"F1.6",
"AF-HRN",
"-800",
"",
"Aksumite and earlier roots; approximate",
"Tigrinya-speakers in Tigray and Eritrea maintain rock-hewn churches, church painting, basketry and weaving.",
"rock-cutting;basketry;weaving;painting",
"church;basket;icon",
"ritual and belief; shelter; food and storage",
"the community; ethnographic and museum usage",
"Tigray and Eritrean communities as separate political identities; Tigre speakers",
"living-community; sacred; conflict-looting",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R3",
"F1.16;F1.19a",
"medium",
"links: PLC064; PLC065. Endonyms to verify; war damage since 2020.",
"canon_communities.csv"
],
[
"COM055",
"Soomaali",
"Somali",
"community",
"People",
"F1.6;F1.10",
"AF-HRN;AF-SWA",
"900",
"",
"approximate",
"Somali communities make portable aqal houses, carved headrests and wooden vessels, woven mats and silver jewellery.",
"mat weaving;wood carving;leather;silver",
"aqal house;headrest;milk vessel;mat",
"shelter; food and storage; clothing and adornment",
"the community; ethnographic and museum usage",
"clan families; Somali Bantu (Jareer), once enslaved; Benadir weavers",
"living-community; human-flow",
"British Museum collection online (view; licence per image); Wikimedia Commons; Pitt Rivers Museum collections online (view)",
"R3",
"F1.29",
"high",
"human-flow for Somali Bantu history.",
"canon_communities.csv"
],
[
"COM056",
"Oromo",
"Oromo; 'Galla' (rejected exonym)",
"community",
"People",
"F1.6",
"AF-HRN",
"1500",
"",
"expansion 16th c.; approximate",
"Oromo communities make carved headrests, milk containers, gourds and the gadaa-related staff and regalia.",
"wood carving;leather;gourd;beadwork",
"headrest;milk container;gourd;staff",
"food and storage; rule and display; ritual and belief",
"the community; ethnographic and museum usage",
"Borana, Tulama, Arsi and other branches",
"living-community; Indigenous-community",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"",
"high",
"'Galla' marked rejected.",
"canon_communities.csv"
],
[
"COM057",
"'Afar",
"Afar; Danakil (exonym)",
"community",
"People",
"F1.6",
"AF-HRN",
"1000",
"",
"approximate",
"Afar pastoralists build portable mat houses (ari) and make daggers (jile) and leatherwork.",
"mat weaving;leather;iron",
"ari house;jile dagger",
"shelter; war",
"the community; ethnographic and museum usage",
"sultanates and clans",
"living-community; Indigenous-community",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_communities.csv"
],
[
"COM058",
"Harari",
"Gēy Usuach (Gey Usu, \"people of the city\")",
"community",
"People",
"F1.6;F1.10",
"AF-HRN",
"1000",
"",
"Harar walled city 16th c.; approximate",
"Harari women make coiled baskets hung on the walls of the gey gar house and embroider dress.",
"coiled basketry;embroidery;bookbinding",
"basket;wall display;manuscript",
"food and storage; rule and display; record and writing",
"the community; ethnographic and museum usage",
"Oromo and Somali makers in Harar",
"living-community",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Endonym verified: Gēy Usuach.",
"canon_communities.csv"
],
[
"COM059",
"Konso",
"Xonsita (self-name); language Afaa Xonso",
"community",
"People",
"F1.6",
"AF-HRN",
"1500",
"",
"approximate",
"Konso communities build walled terraced towns and carve waka memorial figures, many of which have been stolen for the art market; Ethiopian customs impounded more than 200 from 1996.",
"dry-stone terracing;wood carving",
"waka figure;terrace;town wall",
"shelter; ritual and belief",
"the community; ethnographic and museum usage",
"clans and towns",
"living-community; Indigenous-community; funerary; conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"medium",
"Endonym Xonsita verified (single t). Seized waka are kept at the Konso Museum; individual returns from abroad still to verify.",
"canon_communities.csv"
],
[
"COM060",
"Beta Israel",
"'Falasha' (rejected exonym)",
"community",
"People",
"F1.6",
"AF-HRN",
"1300",
"",
"approximate",
"Beta Israel potters and smiths make clay figures and ironwork, forms that shifted towards sale, and most of the community has lived in Israel since the 1980s–1990s.",
"pottery;ironwork;weaving",
"clay figure;pot;tool",
"ritual and belief; tools",
"the community; ethnographic and museum usage",
"relocated community; Falash Mura",
"living-community",
"Wikimedia Commons",
"R3",
"F1.2",
"medium",
"Pottery for tourists shifted forms; verify.",
"canon_communities.csv"
],
[
"COM061",
"Waswahili",
"Swahili",
"community",
"People",
"F1.6;F1.10",
"AF-SWA;AF-MAD",
"800",
"",
"coast towns from c. 8th c.",
"Swahili craftspeople build coral-stone houses and dhows and carve doors, chairs and Lamu furniture.",
"coral stone;lime;wood carving;dhow building",
"carved door;chair;dhow;siwa horn",
"shelter; transport; rule and display",
"the community; ethnographic and museum usage",
"Bajuni, Mijikenda and enslaved workers on the coast; Arab and Indian-labelled makers",
"living-community; human-flow",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: CIV004; POL010; MKR015; STY091; NET012; PRA023.",
"canon_communities.csv"
],
[
"COM062",
"Maasai",
"Il-Maa-speakers; Maasai",
"community",
"People",
"F1.6",
"AF-SWA",
"1500",
"",
"approximate",
"Maasai women make glass-bead collars and ornaments whose colours mark age and status, and Maasai names are used on non-Maasai products.",
"glass beadwork;hide;iron",
"beaded collar;earring;shield",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Samburu, Il Chamus and other Maa speakers; brands that use the Maasai name (Maasai IP Initiative)",
"living-community; Indigenous-community",
"British Museum collection online (view; licence per image); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.2;F1.21",
"high",
"links: PRA030. Maasai Intellectual Property Initiative is real; verify its status.",
"canon_communities.csv"
],
[
"COM063",
"Mijikenda",
"nine Mijikenda peoples (Giriama and others)",
"community",
"People",
"F1.6",
"AF-SWA",
"1600",
"",
"approximate",
"Mijikenda communities carve vigango memorial posts for Gohu society elders, and stolen posts have been returned from US museums.",
"wood carving",
"kigango post",
"ritual and belief",
"the community; ethnographic and museum usage",
"nine separate peoples; carvers",
"living-community; sacred; funerary; conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"Returns from US museums (2014–) to verify dates.",
"canon_communities.csv"
],
[
"COM064",
"Agĩkũyũ",
"Kikuyu",
"community",
"People",
"F1.6",
"AF-SWA",
"1500",
"",
"approximate",
"Kikuyu women weave sisal kiondo bags, a form now mass-produced for export.",
"sisal twining;dyeing",
"kiondo bag",
"food and storage; transport",
"the community; ethnographic and museum usage",
"weavers of other groups (Kamba) also make kiondo",
"living-community",
"Wikimedia Commons",
"R3",
"F1.21",
"medium",
"",
"canon_communities.csv"
],
[
"COM065",
"Akamba",
"Kamba",
"community",
"People",
"F1.6",
"AF-SWA",
"1700",
"",
"approximate",
"Kamba carvers have run a large export carving industry since the early 20th c. and remain known for woodcarving.",
"wood carving",
"figure;bowl",
"exchange and value",
"the community; ethnographic and museum usage",
"workshop labour",
"living-community",
"Wikimedia Commons",
"R3",
"F1.2",
"high",
"links: STY178.",
"canon_communities.csv"
],
[
"COM066",
"Wamakonde",
"Makonde",
"community",
"People",
"F1.6",
"AF-SWA;AF-SOU",
"1800",
"",
"approximate",
"Makonde carvers make lipiko masks and blackwood sculpture, including the shetani style made for sale.",
"wood carving;blackwood",
"lipiko mask;ujamaa sculpture",
"ritual and belief; exchange and value",
"the community; ethnographic and museum usage",
"Mozambican and Tanzanian Makonde; Mwera neighbours",
"living-community; sacred",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.2",
"high",
"links: STY177; PRA031.",
"canon_communities.csv"
],
[
"COM067",
"Baganda",
"Ganda",
"community",
"People",
"F1.6",
"AF-SWA",
"1300",
"",
"Buganda kingdom c. 14th c.",
"Baganda barkcloth makers beat Ficus bark into lubugo cloth for mourning, royal and ceremonial use.",
"barkcloth beating",
"barkcloth;basket;drum",
"clothing and adornment; ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"barkcloth makers of other kingdoms",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons; UNESCO ICH pages (text; status to verify)",
"R2",
"F1.18",
"high",
"links: POL012; PRA001; PLC081.",
"canon_communities.csv"
],
[
"COM068",
"Bahaya",
"Haya",
"community",
"People",
"F1.6",
"AF-SWA",
"-500",
"",
"Early Iron Age smelting in Buhaya (Kagera) dated to the mid to later 1st millennium BCE (steel-making c. 2,300–2,000 years ago); precise dates debated",
"Haya elders in Kagera, north-west Tanzania, rebuilt and fired bloomery furnaces for archaeologist Peter Schmidt in the 1970s, a case of living knowledge meeting archaeology, and Haya communities hold this smelting history in oral tradition.",
"bloomery smelting;barkcloth",
"furnace;iron bloom",
"tools",
"the community; ethnographic and museum usage",
"the smelters themselves named only as 'informants'",
"living-community",
"Wikimedia Commons; Internet Archive (public-domain ethnographies; read critically)",
"R3",
"F1.28a;F1.5",
"medium",
"Dates contested; the Atlas logic names the Haya as an example.",
"canon_communities.csv"
],
[
"COM069",
"Hadzabe",
"Hadza",
"community",
"People",
"F1.6",
"AF-SWA",
"-10000",
"",
"deep regional presence; approximate",
"Hadzabe hunter-gatherers make bows, poisoned arrows and beadwork, and are much studied.",
"bow making;arrow poison;beadwork",
"bow;arrow;necklace",
"tools; food and storage",
"the community; ethnographic and museum usage",
"their own framing over researchers'",
"living-community; Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.26",
"medium",
"Start date approximate only.",
"canon_communities.csv"
],
[
"COM070",
"amaZulu",
"Zulu",
"community",
"People",
"F1.6",
"AF-SOU",
"1816",
"",
"kingdom 1816–1879; community older",
"Zulu women make beadwork with colour codes and communal ceramics (ukhamba), and men carve headrests and weave.",
"glass beadwork;hand-built pottery;wood carving;wire weaving",
"bead panel;beer pot;headrest;telephone-wire basket",
"clothing and adornment; food and storage; rule and display",
"the community; ethnographic and museum usage",
"Nguni neighbours; kingdom as polity versus people",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.18",
"high",
"links: POL017; PRA015.",
"canon_communities.csv"
],
[
"COM071",
"amaNdebele",
"Ndebele (South African)",
"community",
"People",
"F1.6",
"AF-SOU",
"1600",
"",
"approximate",
"Ndebele women paint homesteads and make beaded aprons and neck rings, and Esther Mahlangu took the painting to cars and canvases.",
"wall painting;beadwork",
"painted house;beaded apron;neck ring",
"shelter; clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Zimbabwean Ndebele (a different people); individual painters",
"living-community",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R2",
"F1.18;F1.21",
"high",
"links: STY090; PRA016.",
"canon_communities.csv"
],
[
"COM072",
"Vatsonga",
"Tsonga; Shangaan",
"community",
"People",
"F1.6",
"AF-SOU",
"1600",
"",
"approximate",
"Tsonga carvers make headrests and staffs, and women make beadwork and xibelani skirts.",
"wood carving;beadwork;cloth gathering",
"headrest;staff;xibelani skirt",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Shangaan and Ronga distinctions",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_communities.csv"
],
[
"COM073",
"Basotho",
"Sotho",
"community",
"People",
"F1.6",
"AF-SOU",
"1820",
"",
"nation formed under Moshoeshoe I from c. 1820s",
"Basotho weave the conical mokorotlo hat and wear the Basotho blanket, a woollen blanket made in England and South Africa.",
"grass weaving;wool blanket design",
"mokorotlo hat;Basotho blanket",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"English mills that made the blankets; litema wall painting by women",
"living-community",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R3",
"F1.2;F1.21",
"high",
"",
"canon_communities.csv"
],
[
"COM074",
"amaXhosa",
"Xhosa",
"community",
"People",
"F1.6",
"AF-SOU",
"1600",
"",
"approximate",
"Xhosa women make beadwork and ochre-dyed dress, and tobacco pipes are a noted form.",
"beadwork;ochre dye;wood carving",
"beadwork;pipe;dress",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Mfengu, Thembu and Mpondo",
"living-community",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_communities.csv"
],
[
"COM075",
"San",
"Ju|'hoan, !Xun, ǂKhomani and others; Basarwa (Botswana usage); 'Bushmen' (rejected exonym for many; some use it)",
"community",
"People",
"F1.6",
"AF-SOU",
"-20000",
"",
"ancestral rock art over many millennia; approximate",
"San ancestors made rock paintings and ostrich-eggshell beads, and present San artists work in collectives such as Kuru.",
"rock painting;ostrich-eggshell beads;printmaking",
"rock art;bead;print",
"ritual and belief; clothing and adornment",
"the community; ethnographic and museum usage",
"many separate peoples and languages; Khoekhoe; rock art as 'ancestral' not 'prehistoric'",
"living-community; Indigenous-community; ancestral",
"Wikimedia Commons; British Museum collection online (view; licence per image)",
"R2",
"F1.26;F1.3",
"high",
"Rock art may be ancestral; handle with community.",
"canon_communities.csv"
],
[
"COM076",
"Khoekhoen",
"Nama; Damara (neighbours); 'Hottentot' (rejected exonym)",
"community",
"People",
"F1.6",
"AF-SOU",
"-2000",
"",
"herding from c. 2000 years ago; approximate",
"Nama women make patchwork dresses and the portable matjieshuis mat house.",
"mat weaving;patchwork",
"mat house;dress",
"shelter; clothing and adornment",
"the community; ethnographic and museum usage",
"Nama, Korana, Griqua",
"living-community; Indigenous-community; human-flow",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Genocide of 1904–1908 (Nama); human-flow.",
"canon_communities.csv"
],
[
"COM077",
"Ovaherero",
"Herero",
"community",
"People",
"F1.6",
"AF-SOU",
"1600",
"",
"approximate",
"Herero women make and wear long dresses adopted from late-19th-century German missionary fashion, now in bright prints, with the otjikaiva headdress shaped like cattle horns.",
"sewing;cloth",
"dress;otjikaiva headdress",
"clothing and adornment; rule and display",
"the community; ethnographic and museum usage",
"Mbanderu; genocide survivors",
"living-community; human-flow",
"Wikimedia Commons",
"R3",
"F1.2;F1.19a",
"high",
"Genocide 1904–1908; objects and remains in German collections.",
"canon_communities.csv"
],
[
"COM078",
"Merina",
"Merina",
"community",
"People",
"F1.6",
"AF-MAD",
"1500",
"",
"kingdom c. 16th–1897",
"Merina weavers make lamba akotifahana silk cloths, including burial shrouds (lamba mena).",
"silk weaving;natural dye",
"lamba;burial shroud",
"clothing and adornment; ritual and belief; rule and display",
"the community; ethnographic and museum usage",
"enslaved andevo weavers; Betsileo weavers",
"living-community; funerary; human-flow",
"Met Open Access (CC0); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.18",
"high",
"links: POL018; MKR016; PRA021; BEL049.",
"canon_communities.csv"
],
[
"COM079",
"Zafimaniry",
"Zafimaniry",
"community",
"People",
"F1.6",
"AF-MAD",
"1800",
"",
"approximate",
"Zafimaniry carvers join wooden houses without nails and carve geometric patterns into them.",
"wood joinery;carving",
"house;door;shutter",
"shelter",
"the community; ethnographic and museum usage",
"Betsileo neighbours",
"living-community; Indigenous-community",
"UNESCO ICH pages (text; status to verify); Wikimedia Commons",
"R2",
"",
"high",
"links: STY174; PLC097; PRA022.",
"canon_communities.csv"
],
[
"COM080",
"Sakalava",
"Sakalava",
"community",
"People",
"F1.6",
"AF-MAD",
"1600",
"",
"kingdoms from c. 17th c.",
"Sakalava carvers make figures for royal tombs, and Sakalava communities keep royal relic (dady) rites.",
"wood carving",
"tomb figure",
"ritual and belief",
"the community; ethnographic and museum usage",
"Boina and Menabe kingdoms; Vezo and Mahafaly neighbours",
"living-community; sacred; funerary",
"musée du quai Branly collections online (view); Wikimedia Commons",
"R3",
"",
"medium",
"links: POL019; STY175.",
"canon_communities.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
