insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"COM284",
"Yapese",
"Yap islanders",
"community",
"People",
"F1.12",
"OC-MIC",
"1000",
"",
"approximate",
"Yapese voyagers quarried rai stone disks on Palau and brought them home as valuables, and rai are still exchanged in marriages, inheritance and other important transactions.",
"stone quarrying;canoe transport",
"rai stone;canoe",
"exchange and value; transport",
"the community; ethnographic and museum usage",
"Palauan quarry land; outer islands",
"living-community; Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: PLC407.",
"canon_communities.csv"
],
[
"COM285",
"Nukuoro",
"Nukuoro islanders",
"community",
"People",
"F1.12",
"OC-MIC;OC-POL",
"1300",
"",
"Polynesian outlier; approximate",
"Nukuoro islanders carve and weave today, and the stylised tino figures of their ancestors are now mostly in museums.",
"wood carving",
"tino figure",
"ritual and belief",
"the community; ethnographic and museum usage",
"Kapingamarangi relatives",
"living-community; Indigenous-community; sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"AP 217.",
"canon_communities.csv"
],
[
"COM286",
"I-Kiribati",
"Kiribati people",
"community",
"People",
"F1.12",
"OC-MIC",
"-500",
"",
"approximate",
"I-Kiribati make coconut-fibre armour with shark-tooth weapons, pandanus mats and canoes.",
"coconut-fibre knotting;shark-tooth hafting;pandanus weaving",
"armour;sword;mat",
"war; clothing and adornment; transport",
"the community; ethnographic and museum usage",
"Banaba (Ocean Island) people displaced by phosphate mining",
"living-community; Indigenous-community; human-flow",
"British Museum collection online (view; licence per image); Wikimedia Commons",
"R3",
"F1.22",
"high",
"Banaban relocation to Rabi: human-flow.",
"canon_communities.csv"
],
[
"COM287",
"Pohnpeians",
"Mehn Pohnpei",
"community",
"People",
"F1.12",
"OC-MIC",
"1000",
"",
"Nan Madol built c. 1180–1628 CE",
"Pohnpeian ancestors built Nan Madol from basalt columns, and makers today weave and brew sakau.",
"basalt stacking;weaving",
"Nan Madol;mat",
"shelter; ritual and belief",
"the community; ethnographic and museum usage",
"Saudeleur rulers versus labourers",
"living-community; Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.28a",
"medium",
"links: PLC405; POL088. Endonym to verify.",
"canon_communities.csv"
],
[
"COM288",
"Māori",
"Tangata whenua; iwi and hapū",
"community",
"People",
"F1.12",
"OC-POL",
"1250",
"",
"settlement c. 1250–1300 CE",
"Māori makers carve whakairo, weave kākahu cloaks and practise tā moko, and iwi govern taonga held in museums.",
"wood and pounamu carving;harakeke weaving;tā moko",
"wharenui;kākahu;hei tiki;waka",
"ritual and belief; rule and display; clothing and adornment",
"the community; ethnographic and museum usage",
"iwi and hapū as the owning groups; Moriori",
"living-community; Indigenous-community; sacred; ancestral",
"Te Papa Collections Online (some CC BY); Auckland Museum Collections Online (many CC BY); Wikimedia Commons",
"R1",
"F1.24;F1.26",
"high",
"links: BEL051; PRA204; PRA205; PRA206; SCH044; INS085; EVT025; MOV103.",
"canon_communities.csv"
],
[
"COM289",
"Kānaka Maoli",
"Native Hawaiians; Kanaka ʻŌiwi",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"settlement c. 1000–1200 CE",
"Kānaka Maoli make kapa, feather cloaks (ʻahu ʻula) and wood images, and revived voyaging with Hōkūleʻa (1976).",
"kapa beating;featherwork;wood carving",
"kapa;ʻahu ʻula;kiʻi;waʻa",
"clothing and adornment; rule and display; ritual and belief; transport",
"the community; ethnographic and museum usage",
"island and aliʻi distinctions; diaspora",
"living-community; Indigenous-community; sacred",
"Bishop Museum (view); Wikimedia Commons",
"R1",
"F1.24;F1.13",
"high",
"links: BEL052; POL083; PRA201; MOV102; PLC415.",
"canon_communities.csv"
],
[
"COM290",
"Tagata Sāmoa",
"Samoans",
"community",
"People",
"F1.12",
"OC-POL",
"-800",
"",
"settlement c. 800 BCE",
"Samoans weave ʻie tōga fine mats, practise tatau with hand tools, and build fale.",
"pandanus weaving;tatau;timber fale building",
"ʻie tōga;pe'a;fale",
"exchange and value; clothing and adornment; shelter",
"the community; ethnographic and museum usage",
"American Samoa; tufuga families",
"living-community; Indigenous-community",
"Te Papa Collections Online (some CC BY); Auckland Museum Collections Online (many CC BY); Wikimedia Commons",
"R2",
"F1.18",
"high",
"links: POL086; MKR089; PRA202; PRA207.",
"canon_communities.csv"
],
[
"COM291",
"Kakai Tonga",
"Tongans",
"community",
"People",
"F1.12",
"OC-POL",
"-800",
"",
"settlement c. 800 BCE",
"Tongan women make ngatu barkcloth in kautaha groups and weave kie mats.",
"barkcloth;pandanus weaving",
"ngatu;kie",
"exchange and value; rule and display; clothing and adornment",
"the community; ethnographic and museum usage",
"diaspora in Aotearoa and USA",
"living-community; Indigenous-community",
"Te Papa Collections Online (some CC BY); Auckland Museum Collections Online (many CC BY); Wikimedia Commons",
"R2",
"F1.18",
"high",
"links: POL084; POL085; MKR088; PRA199. Kakai Tonga (\"Tongan people\") in use, e.g. Waikato thesis title \"Kakai Tonga 'i Okalani\".",
"canon_communities.csv"
],
[
"COM292",
"Rapanui",
"Rapa Nui people",
"community",
"People",
"F1.12",
"OC-POL",
"1200",
"",
"settlement c. 1200 CE; approximate",
"Rapanui ancestors carved moai at Rano Raraku and kohau rongorongo tablets, and the community seeks return of Hoa Hakananai'a.",
"volcanic tuff carving;wood carving;rongorongo",
"moai;moai kavakava;rongorongo tablet",
"ritual and belief; record and writing",
"the community; ethnographic and museum usage",
"population collapse from 1860s slave raids; Chilean state",
"living-community; Indigenous-community; sacred; ancestral; human-flow",
"Museo Antropológico P. Sebastián Englert (view); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: CIV092; OCC148; PLC412; PLC413. 1862 slave raids: human-flow.",
"canon_communities.csv"
],
[
"COM293",
"Mā'ohi",
"Tahitians; Mā'ohi of French Polynesia",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"approximate",
"Mā'ohi make tapa, featherwork and tattoo, revived after mission-era bans.",
"barkcloth;featherwork;tattoo",
"tapa;to'o figure;mourner's costume",
"ritual and belief; clothing and adornment",
"the community; ethnographic and museum usage",
"Society, Austral and Tuamotu islanders",
"living-community; Indigenous-community; sacred",
"Te Fare Iamanaha Musée de Tahiti et des Îles (view); British Museum collection online (view; licence per image); Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: POL087; OCC120.",
"canon_communities.csv"
],
[
"COM294",
"Kūki 'Āirani",
"Cook Islands Māori",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"approximate",
"Cook Islands makers sew tivaevae quilts and carved staff gods, many destroyed or taken by missionaries.",
"appliqué quilting;wood carving",
"tivaevae;staff god",
"ritual and belief; clothing and adornment",
"the community; ethnographic and museum usage",
"Rarotongan, Aitutaki and other islands",
"living-community; Indigenous-community; sacred",
"British Museum collection online (view; licence per image); Auckland Museum Collections Online (many CC BY); Wikimedia Commons",
"R2",
"F1.18;F1.24",
"high",
"AP 216.",
"canon_communities.csv"
],
[
"COM295",
"Niuē",
"Niueans",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"approximate",
"Niuean makers produced painted hiapo barkcloth in the 19th c. and weave today.",
"barkcloth painting;weaving",
"hiapo;hat",
"clothing and adornment",
"the community; ethnographic and museum usage",
"diaspora majority in Aotearoa",
"living-community; Indigenous-community",
"Te Papa Collections Online (some CC BY); Auckland Museum Collections Online (many CC BY); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"AP 219.",
"canon_communities.csv"
],
[
"COM296",
"Mangarevans",
"Mangareva islanders",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"approximate",
"Mangarevans make carving and pearl-shell work today, and most older god figures were destroyed in the 1830s mission era.",
"wood carving",
"figure",
"ritual and belief",
"the community; ethnographic and museum usage",
"Gambier islanders",
"living-community; Indigenous-community; sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.24",
"medium",
"",
"canon_communities.csv"
],
[
"COM297",
"ʻEnana",
"Marquesans; ʻEnata (South Marquesan)",
"community",
"People",
"F1.12",
"OC-POL",
"1000",
"",
"approximate",
"Marquesan carvers make tiki, u'u clubs and bowls, and tattoo is revived.",
"wood and stone carving;tattoo",
"tiki;u'u club;bowl",
"ritual and belief; war",
"the community; ethnographic and museum usage",
"northern (Enana) and southern (Enata) groups",
"living-community; Indigenous-community; sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.24",
"medium",
"",
"canon_communities.csv"
],
[
"COM298",
"Yörük",
"Yuruk; Türkmen of Anatolia",
"community",
"People",
"F1.10",
"WA-ANA",
"1100",
"",
"Oghuz arrival in Anatolia from 11th c.",
"Yörük women weave kilims, goat-hair tent panels and storage bags, and some families still migrate seasonally.",
"flat weaving;goat-hair weaving;natural dye",
"kilim;tent;çuval bag",
"shelter; transport; food and storage",
"the community; ethnographic and museum usage",
"settled descendants; village weavers labelled 'Yörük' by dealers",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_communities.csv"
],
[
"COM299",
"Pontic Greeks",
"Pontians; Rum of the Pontus",
"community",
"People",
"F1.11",
"WA-ANA;EU-GRR",
"-700",
"",
"Greek presence from c. 7th c. BCE; exchange of populations 1923",
"Pontic Greek makers are associated with silver church work and the kemenche lyre, carried to Greece after the 1923 population exchange.",
"silverwork;instrument making",
"kemenche;church silver",
"play and music; ritual and belief",
"the community; ethnographic and museum usage",
"Turkish-speaking Greek Orthodox (Karamanlides); deaths of 1916–1923",
"living-community; human-flow",
"Europeana; Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"Population exchange and deportations: human-flow.",
"canon_communities.csv"
],
[
"COM300",
"Buryaad",
"Buryats",
"community",
"People",
"F1.12a",
"AS-NTH;AS-CEN",
"1600",
"",
"approximate",
"Buryat silversmiths make jewellery and saddle fittings, and monastery artists paint and cast Buddhist images.",
"silver;appliqué;casting",
"jewellery;thangka;saddle",
"clothing and adornment; ritual and belief; transport",
"the community; ethnographic and museum usage",
"Western (shamanic) and Eastern (Buddhist) Buryats",
"living-community; Indigenous-community; sacred",
"Himalayan Art Resources (view); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_communities.csv"
],
[
"ARC001",
"Lomekwian",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SWA",
"-3300000",
"-3300000",
"c. 3.3 million years ago; single site complex (Lomekwi 3, West Turkana)",
"The oldest known knapped stone tools, made before the genus Homo is securely attested.",
"stone knapping (anvil and passive-hammer techniques)",
"cores; flakes; anvils",
"tools",
"Sonia Harmand et al. (2015)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.5",
"medium",
"Stone-tool industry, not a people or society. Single-site evidence; some researchers question the dating and context.",
"canon_cultures_horizons.csv"
],
[
"ARC002",
"Oldowan",
"Mode 1",
"archaeological-culture",
"People",
"F1.6;F1.9a",
"AF-HRN;AF-SWA;AF-SOU;WA-CAU;GL",
"-2600000",
"-1000000",
"c. 2.6 million to c. 1 million years ago (persists alongside Acheulean)",
"Simple flaked cores and sharp flakes made by early hominins for butchery and plant processing.",
"hard-hammer percussion; stone selection",
"choppers; flakes; hammerstones",
"tools;food and storage",
"Louis and Mary Leakey, after Olduvai Gorge (Tanzania)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Smithsonian Open Access (CC0)",
"R3",
"F1.5",
"high",
"Stone-tool industry, not a people or society. Also at Dmanisi (Georgia).",
"canon_cultures_horizons.csv"
],
[
"ARC003",
"Acheulean",
"Acheulian; Mode 2",
"archaeological-culture",
"People",
"F1.6;F1.9a;F1.9;F1.11",
"AF-HRN;AF-SWA;AF-SOU;AF-MAG;WA-LEV;AS-SAS;EU-WCE;EU-IBE;GL",
"-1760000",
"-130000",
"c. 1.76 million to c. 130,000 years ago; varies by region",
"Hominins shaped symmetrical handaxes, a sign of planned, standardised tool-making sustained for over a million years.",
"bifacial flaking; soft-hammer thinning",
"handaxes; cleavers; picks",
"tools",
"Gabriel de Mortillet, after Saint-Acheul (France)",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports;British Museum collection online (link out);Portable Antiquities Scheme (CC BY)",
"R2",
"F1.5",
"high",
"Stone-tool industry, not a people or society. Earliest dates from Kokiselei (Kenya).",
"canon_cultures_horizons.csv"
],
[
"ARC004",
"Middle Stone Age",
"MSA",
"archaeological-culture",
"People",
"F1.6",
"AF-HRN;AF-SWA;AF-SOU;AF-MAG;AF-CEN;AF-GUI;AF-SAH",
"-300000",
"-30000",
"c. 300,000–30,000 years ago; regional end dates vary",
"Early Homo sapiens made prepared-core points, ochre pigments and shell beads, the earliest evidence of symbolic adornment.",
"prepared-core (Levallois) knapping; hafting with adhesives; ochre processing; shell perforation",
"points; blades; ochre pieces; shell beads",
"tools;clothing and adornment;ritual and belief",
"A. J. H. Goodwin and C. van Riet Lowe (1929)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5;F1.30",
"high",
"Stone-tool industry, not a people or society. Broad African period-industry; also used for Jebel Irhoud (Morocco, c. 300 ka).",
"canon_cultures_horizons.csv"
],
[
"ARC005",
"Aterian",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-MAG;AF-SAH",
"-145000",
"-29000",
"c. 145,000–29,000 years ago (dates vary widely)",
"North African MSA toolmakers made tanged points for hafting and some of the earliest shell beads.",
"tang shaping; hafting; shell perforation",
"tanged points; scrapers; Nassarius beads",
"tools;clothing and adornment",
"Named after Bir el-Ater (Algeria) by French prehistorians",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Stone-tool industry, not a people or society.",
"canon_cultures_horizons.csv"
],
[
"ARC006",
"Nubian Complex",
"Nubian Levallois",
"archaeological-culture",
"People",
"F1.6;F1.9a",
"AF-NUB;WA-ARB",
"-130000",
"-70000",
"c. 130,000–70,000 years ago in Nubia and Dhofar (Oman)",
"A distinctive Levallois point method found in Nubia and in southern Arabia, used to trace early human movements out of Africa.",
"Nubian Levallois core preparation",
"points; cores",
"tools",
"Anthony Marks and Philip Van Peer; applied to Arabia by Jeffrey Rose et al. (2011)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Stone-tool industry, not a people or society. Arabian attribution debated.",
"canon_cultures_horizons.csv"
],
[
"ARC007",
"Still Bay",
"Stillbay",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"-77000",
"-70000",
"c. 77,000–70,000 years ago",
"Southern African makers pressure-flaked bifacial points, sometimes heat-treating silcrete, alongside engraved ochre at Blombos Cave.",
"heat treatment; pressure flaking; ochre engraving",
"bifacial points; engraved ochre; shell beads",
"tools;clothing and adornment;ritual and belief",
"Named after Still Bay (South Africa); Goodwin and van Riet Lowe (1929)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5",
"high",
"Stone-tool industry, not a people or society.",
"canon_cultures_horizons.csv"
],
[
"ARC008",
"Howiesons Poort",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"-66000",
"-59000",
"c. 66,000–59,000 years ago",
"Makers produced backed blades for composite tools and engraved ostrich eggshell water containers with repeated patterns.",
"backed-blade production; composite hafting; eggshell engraving",
"backed blades; engraved ostrich eggshell",
"tools;food and storage;ritual and belief",
"Named after Howiesons Poort shelter (South Africa)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.15",
"high",
"Stone-tool industry, not a people or society.",
"canon_cultures_horizons.csv"
],
[
"ARC009",
"Later Stone Age",
"LSA",
"archaeological-culture",
"People",
"F1.6",
"AF-HRN;AF-SWA;AF-SOU;AF-CEN;AF-GUI",
"-50000",
"1900",
"from c. 50,000–40,000 years ago; forager toolkits persist into recent centuries",
"Microlithic toolkits, ostrich-eggshell beads and rock art made by African foragers over tens of thousands of years.",
"microlith production; bead making; rock painting",
"microliths; eggshell beads; bone points",
"tools;clothing and adornment;ritual and belief",
"A. J. H. Goodwin and C. van Riet Lowe (1929)",
"",
"Indigenous-community;living-community",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.30",
"medium",
"Stone-tool industry, not a people or society. Descendant forager communities (e.g. San) are living.",
"canon_cultures_horizons.csv"
],
[
"ARC010",
"Iberomaurusian",
"Oranian",
"archaeological-culture",
"People",
"F1.6",
"AF-MAG",
"-23000",
"-9500",
"c. 23,000–9500 BCE (calibrated ranges vary)",
"North African foragers made bladelet tools and buried their dead in large cemeteries, with evidence of tooth avulsion.",
"bladelet production; bone tools; ochre",
"bladelets; bone points; burials",
"tools;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Known largely from cemeteries (Taforalt, Afalou).",
"canon_cultures_horizons.csv"
],
[
"ARC011",
"Capsian",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-MAG",
"-10000",
"-6000",
"c. 10,000–6000 BCE",
"Capsian foragers of Tunisia and Algeria left snail-shell middens, engraved ostrich eggshell and decorated stones.",
"microlith production; eggshell engraving",
"microliths; engraved eggshell; escargotières",
"tools;food and storage;ritual and belief",
"Jacques de Morgan, after Gafsa (Latin Capsa)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC012",
"Kiffian",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"-8000",
"-6000",
"c. 8000–6000 BCE (Gobero, Niger)",
"Early Holocene 'Green Sahara' fisher-hunters made bone harpoons and wavy-line pottery by now-dry lakes.",
"bone harpoon making; pottery",
"harpoons; pottery; burials",
"food and storage;tools",
"Paul Sereno and Elena Garcea (2008)",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"medium",
"Known mostly from the Gobero cemetery.",
"canon_cultures_horizons.csv"
],
[
"ARC013",
"Faiyum A",
"Fayum Neolithic",
"archaeological-culture",
"People",
"F1.6",
"AF-EGY",
"-5200",
"-4000",
"c. 5200–4000 BCE",
"Early Egyptian farmers stored grain in basket-lined pits and made linen and pottery by Lake Qarun.",
"basketry; pottery; linen; grain storage",
"baskets; pottery; sickles",
"food and storage;clothing and adornment",
"Gertrude Caton-Thompson and Elinor Gardner (1920s)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC014",
"Badarian",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-EGY",
"-4400",
"-4000",
"c. 4400–4000 BCE",
"Upper Egyptian communities made thin rippled pottery, ivory combs and cosmetic palettes, known mostly from graves.",
"rippled black-topped pottery; ivory carving; stone palettes",
"pottery; palettes; figurines; beads",
"food and storage;clothing and adornment;ritual and belief",
"Guy Brunton and Gertrude Caton-Thompson, after el-Badari",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC015",
"Naqada",
"Naqada I–III; Amratian; Gerzean",
"archaeological-culture",
"People",
"F1.6",
"AF-EGY",
"-4000",
"-3000",
"c. 4000–3000 BCE",
"Predynastic Egyptian workshops made painted pottery, flint knives, stone vessels and ceremonial palettes before unification.",
"ripple-flaked flint; stone-vessel drilling; painted pottery; copper",
"decorated pottery; palettes; knives; stone vessels",
"ritual and belief;rule and display;food and storage",
"Flinders Petrie (1890s), after Naqada",
"",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC016",
"Khartoum Mesolithic",
"Early Khartoum",
"archaeological-culture",
"People",
"F1.6",
"AF-NUB",
"-8000",
"-5000",
"c. 8000–5000 BCE",
"Nile foragers made some of Africa's earliest pottery, decorated with wavy lines, and bone harpoons.",
"early pottery (wavy-line, dotted wavy-line); bone working",
"pottery; harpoons",
"food and storage;tools",
"A. J. Arkell (1940s)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC017",
"A-Group",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-NUB",
"-3800",
"-2900",
"c. 3800–2900 BCE",
"Lower Nubian communities made eggshell-thin painted pottery and traded with Predynastic Egypt.",
"fine painted pottery; trade",
"pottery; palettes; imported goods",
"food and storage;exchange and value",
"George Reisner (1907–09)",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"Known mainly from cemeteries; the 'A-Group' letter labels are Reisner's.",
"canon_cultures_horizons.csv"
],
[
"ARC018",
"C-Group",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-NUB",
"-2400",
"-1550",
"c. 2400–1550 BCE",
"Lower Nubian cattle-herders made incised black pottery and stone grave superstructures.",
"incised pottery; herding",
"bowls; figurines; stelae",
"food and storage;ritual and belief",
"George Reisner",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC019",
"Kerma",
"Kerma culture",
"archaeological-culture",
"People",
"F1.6",
"AF-NUB",
"-2500",
"-1500",
"c. 2500–1500 BCE",
"Kerma potters made black-topped beakers of extraordinary thinness and the city had monumental mud-brick deffufa.",
"black-topped fine pottery; mud-brick monumental building; faience; mica ornament",
"beakers; deffufa; beds; faience",
"food and storage;ritual and belief;rule and display",
"George Reisner (1913–16); Charles Bonnet",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"Royal tumuli included human sacrifice; handle remains carefully.",
"canon_cultures_horizons.csv"
],
[
"ARC020",
"X-Group",
"Ballana culture; Post-Meroitic",
"archaeological-culture",
"People",
"F1.6",
"AF-NUB",
"350",
"600",
"c. 350–600 CE",
"Post-Meroitic rulers at Ballana and Qustul were buried with silver crowns, horse gear and imported goods.",
"silver working; wheel-made pottery",
"crowns; horse trappings; pottery",
"rule and display;ritual and belief",
"George Reisner; Walter Emery",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC021",
"D'mt / pre-Aksumite",
"Da'amat",
"archaeological-culture",
"People",
"F1.6",
"AF-HRN",
"-800",
"-400",
"c. 800–400 BCE",
"Highland Ethiopian and Eritrean communities built temples such as Yeha in South Arabian style.",
"ashlar masonry; stone carving; inscriptions",
"temples; incense burners; inscriptions",
"ritual and belief;record and writing",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Degree of South Arabian migration vs local agency is debated.",
"canon_cultures_horizons.csv"
],
[
"ARC022",
"Savanna Pastoral Neolithic",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SWA",
"-3000",
"700",
"c. 3000 BCE–700 CE",
"East African herders made stone bowls and obsidian tools and moved cattle, sheep and goats across the Rift Valley.",
"obsidian knapping; stone bowls; pottery",
"stone bowls; obsidian tools",
"food and storage;tools",
"archaeologists",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"Many sites are burial cairns.",
"canon_cultures_horizons.csv"
],
[
"ARC023",
"Urewe",
"Dimple-based ware",
"archaeological-culture",
"People",
"F1.6",
"AF-SWA;AF-CEN",
"-600",
"500",
"c. 600 BCE–500 CE",
"Early Iron Age Great Lakes communities smelted iron and made distinctive dimple-based pottery.",
"iron smelting; pottery",
"pottery; furnaces",
"tools;food and storage",
"Mary Leakey (1948), after Urewe (Kenya)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"medium",
"Often linked to Bantu-speaking expansions; link language to material with care.",
"canon_cultures_horizons.csv"
],
[
"ARC024",
"Triangular Incised Ware",
"TIW; Tana tradition",
"archaeological-culture",
"People",
"F1.6",
"AF-SWA",
"600",
"1000",
"c. 7th–10th century CE",
"Early coastal pottery ancestral to Swahili towns, showing their African roots.",
"pottery",
"pottery",
"food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Also called Tana tradition; ties to CIV Swahili.",
"canon_cultures_horizons.csv"
],
[
"ARC025",
"Engaruka",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SWA",
"1400",
"1700",
"c. 15th–18th century",
"Farmers in northern Tanzania built stone-walled terraces and irrigation channels.",
"stone terracing; irrigation",
"terraces; channels; house platforms",
"food and storage;shelter",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC026",
"Tichitt tradition",
"Dhar Tichitt",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"-2200",
"-200",
"c. 2200–200 BCE (Mauritania)",
"Agro-pastoralists built dry-stone walled villages along the Tichitt–Walata escarpments, among the earliest in West Africa.",
"dry-stone building; pearl-millet cultivation; pottery",
"walled compounds; pottery; grinding stones",
"shelter;food and storage",
"Patrick Munson (1970s); Kevin MacDonald",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC027",
"Kintampo",
"Kintampo complex",
"archaeological-culture",
"People",
"F1.6",
"AF-GUI",
"-2500",
"-1400",
"c. 2500–1400 BCE (Ghana)",
"Early farming communities made grooved stone 'rasps' (possibly for pottery), clay figurines and ground-stone axes.",
"ground stone; pottery; daub houses",
"stone rasps; axes; pottery",
"food and storage;tools",
"Oliver Davies (1960s)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC028",
"Nok",
"Nok culture",
"archaeological-culture",
"People",
"F1.6",
"AF-GUI",
"-1500",
"1",
"c. 1500 BCE–1 CE; terracottas from c. 900 BCE (Goethe University chronology)",
"Farming communities in central Nigeria made large fired-clay figures and smelted iron.",
"terracotta modelling and firing; iron smelting",
"terracotta figures; pottery; iron tools; grinding stones",
"ritual and belief;tools;food and storage",
"Bernard Fagg (1940s), after the village of Nok",
"",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R1",
"F1.24;F1.5",
"high",
"Existing in project. Terracottas heavily looted and faked; use only excavated or pre-1970 documented pieces.",
"canon_cultures_horizons.csv"
],
[
"ARC029",
"Gajiganna",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"-1800",
"-800",
"c. 1800–800 BCE (Lake Chad basin, Nigeria)",
"Herders and later farmers settled the Lake Chad firki plains, making impressed pottery.",
"pottery; pearl millet cultivation",
"pottery; bone tools",
"food and storage",
"Frankfurt Lake Chad project (Peter Breunig, 1990s)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC030",
"Sao",
"Sao civilisation",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH;AF-CEN",
"-600",
"1600",
"c. 6th century BCE to 16th century CE (dates debated)",
"Communities south of Lake Chad made terracotta figures, bronze ornaments and large burial jars.",
"terracotta; lost-wax copper-alloy casting; pottery",
"figurines; burial jars; ornaments",
"ritual and belief;clothing and adornment",
"Kotoko and Kanuri oral tradition; Jean-Paul Lebeuf's excavations (1930s–)",
"",
"funerary;living-community",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"'Sao' is a name from oral tradition for earlier peoples; Kotoko communities claim descent.",
"canon_cultures_horizons.csv"
],
[
"ARC031",
"Djenné-Djenno",
"Jenne-jeno",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"-250",
"1400",
"c. 250 BCE–1400 CE",
"An early West African city without a citadel, with iron working, pottery and trade in the Inland Niger Delta.",
"iron smelting; pottery; mud-brick; copper import",
"pottery; iron tools; burial urns",
"shelter;exchange and value;tools",
"Susan and Roderick McIntosh (1977 on)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC032",
"Inland Niger Delta terracottas",
"Djenné terracottas",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"1100",
"1600",
"c. 12th–16th century",
"Makers in the Inland Niger Delta modelled seated and kneeling clay figures, later looted in large numbers.",
"terracotta modelling",
"figures",
"ritual and belief",
"archaeologists",
"",
"conflict-looting;sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.24",
"medium",
"Mali restricted export (1970s); much looting; strict provenance. F1.24 case.",
"canon_cultures_horizons.csv"
],
[
"ARC033",
"Bura",
"Bura-Asinda-Sikka",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"200",
"1300",
"c. 3rd–13th century CE (Niger, Burkina Faso)",
"A burial tradition with terracotta heads and figures set on funerary jars.",
"terracotta; iron",
"jars; heads; figures",
"ritual and belief",
"Boubé Gado (1975 on)",
"",
"funerary;conflict-looting",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC034",
"Igbo-Ukwu",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-GUI",
"800",
"1000",
"c. 9th–10th century CE",
"Makers cast highly detailed leaded-bronze vessels and ornaments using local ores and imported glass beads.",
"lost-wax casting of leaded bronze; beadwork",
"vessels; ornaments; beads",
"ritual and belief;rule and display;clothing and adornment",
"Thurstan Shaw (1959–64)",
"",
"funerary;sacred;living-community",
"Wikimedia Commons;open-access excavation reports;British Museum collection online (link out)",
"R2",
"F1.5",
"high",
"Includes a burial chamber and a shrine repository; Igbo living community.",
"canon_cultures_horizons.csv"
],
[
"ARC035",
"Senegambian stone circles",
"Senegambian megaliths",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"-300",
"1600",
"c. 3rd century BCE–16th century CE",
"Communities quarried and set laterite pillars in over a thousand circles.",
"laterite quarrying; iron tools",
"stone circles; burial goods",
"ritual and belief",
"archaeologists; UNESCO (2006)",
"",
"funerary",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC036",
"Tellem",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SAH",
"1000",
"1500",
"c. 11th–15th century (Bandiagara)",
"Tellem people buried their dead in cliff caves with textiles, headrests and wooden figures.",
"cotton weaving; wood carving",
"textiles; headrests; figures",
"ritual and belief;clothing and adornment",
"Dogon oral tradition; Dutch excavations (Utrecht, 1960s)",
"",
"funerary;sacred;conflict-looting",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Earliest cotton textiles in West Africa; cave burials.",
"canon_cultures_horizons.csv"
],
[
"ARC037",
"Sapi",
"Sapi-Portuguese ivories; nomoli",
"archaeological-culture",
"People",
"F1.6",
"AF-GUI",
"1400",
"1600",
"c. 15th–16th century (Sierra Leone coast)",
"Sapi carvers made ivory salt cellars and horns for Portuguese buyers, and steatite figures (nomoli).",
"ivory carving; steatite carving",
"salt cellars; oliphants; nomoli; pomdo",
"exchange and value;ritual and belief",
"European art history; 'Sapi' from Portuguese sources",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection online (link out)",
"R3",
"F1.2;F1.17",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC038",
"Kisalian",
"Classic Kisalian; Upemba Depression",
"archaeological-culture",
"People",
"F1.6",
"AF-CEN",
"900",
"1300",
"c. 10th–13th century CE (Classic Kisalian)",
"Cemeteries at Sanga and Katoto contain copper crosses (currency), ironwork and pottery, foreshadowing the Luba state.",
"copper casting; iron smithing; pottery",
"copper crosses; ornaments; pottery",
"exchange and value;ritual and belief",
"Jacques Nenquin; Pierre de Maret",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC039",
"Lydenburg",
"Lydenburg Heads",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"500",
"700",
"c. 500–700 CE",
"Early farmers in Mpumalanga made seven hollow terracotta heads, the earliest known in southern Africa.",
"terracotta",
"heads; pottery",
"ritual and belief",
"Found by Ludwig von Bezing (1957); archaeologists",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC040",
"Mapungubwe",
"K2–Mapungubwe",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"1000",
"1290",
"K2 c. 1000–1220; Mapungubwe hilltop c. 1220–1290",
"Early southern African class society with gold foil and imported glass beads.",
"gold foil; bead making; ivory",
"gold rhinoceros; beads; pottery",
"rule and display;exchange and value",
"archaeologists",
"",
"funerary;ancestral;living-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"high",
"Routes from CIV Mapungubwe; reburied remains.",
"canon_cultures_horizons.csv"
],
[
"ARC041",
"Zimbabwe tradition",
"Great Zimbabwe culture",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"1200",
"1800",
"c. 1200–1800",
"Dry-stone walled centres across Zimbabwe, Botswana and Mozambique, including Great Zimbabwe and Khami.",
"dry-stone walling; gold; soapstone",
"enclosures; soapstone; beads",
"rule and display;shelter",
"archaeologists",
"",
"sacred;living-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"high",
"Routes from CIV Great Zimbabwe.",
"canon_cultures_horizons.csv"
],
[
"ARC042",
"Bokoni",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-SOU",
"1500",
"1820",
"c. 1500–1820 (Mpumalanga)",
"Farming communities built stone-walled homesteads, terraces and roads over a large landscape.",
"dry-stone walling; terracing",
"homesteads; terraces; roads",
"shelter;food and storage;transport",
"Peter Delius and colleagues (2000s)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC043",
"Dembeni phase",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-MAD",
"800",
"1000",
"c. 9th–10th century CE (Mayotte and the Comoros)",
"Early Comorian villages worked and traded chlorite-schist vessels, local pottery and imported Near Eastern and Chinese ceramics, linking Madagascar to the Swahili coast.",
"chlorite-schist carving; pottery; shell bead making",
"chlorite-schist vessels; pottery; beads",
"exchange and value;food and storage;clothing and adornment",
"Henry Wright and colleagues (1980s–90s)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"Named after the Dembeni site on Mayotte.",
"canon_cultures_horizons.csv"
],
[
"ARC044",
"Mahilaka",
"",
"archaeological-culture",
"People",
"F1.6",
"AF-MAD",
"900",
"1500",
"c. 10th–15th century CE (northwest Madagascar)",
"A walled port town where makers worked chlorite-schist, iron and glass beads for Indian Ocean trade.",
"chlorite-schist carving; iron smelting; coral and stone building",
"chlorite-schist vessels; iron; town walls",
"exchange and value;shelter;tools",
"Chantal Radimilahy (1990s)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"Site-based grouping; Malagasy and Swahili links.",
"canon_cultures_horizons.csv"
],
[
"ARC045",
"Rasikajy",
"Vohémar; Iharana",
"archaeological-culture",
"People",
"F1.6",
"AF-MAD",
"1200",
"1600",
"c. 13th–16th century CE (northeast Madagascar)",
"Islamised trading communities buried their dead with Chinese celadon, glass, chlorite-schist vessels and iron, showing Madagascar's place in Indian Ocean exchange.",
"chlorite-schist carving; iron; imported ceramics",
"chlorite-schist vessels; celadon; mirrors; beads",
"ritual and belief;exchange and value",
"French colonial excavators (early 20th c.); Pierre Vérin",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.13;F1.24",
"medium",
"Known almost entirely from cemeteries; many grave goods removed in colonial period.",
"canon_cultures_horizons.csv"
],
[
"ARC046",
"Mousterian",
"Mode 3 (Europe/West Asia)",
"archaeological-culture",
"People",
"F1.11;F1.9a;F1.12a",
"EU-WCE;EU-IBE;WA-LEV;WA-CAU;WA-IRN;AS-CEN",
"-160000",
"-40000",
"c. 160,000–40,000 years ago",
"Neanderthals (and in the Levant also Homo sapiens) made prepared-core flake tools, hafted with birch-tar and bitumen adhesives.",
"Levallois knapping; adhesive making (birch tar, bitumen)",
"scrapers; points; flakes",
"tools",
"Gabriel de Mortillet, after Le Moustier (France)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Portable Antiquities Scheme (CC BY);Europeana (filter by rights)",
"R3",
"",
"high",
"Stone-tool industry, not a people or society.",
"canon_cultures_horizons.csv"
],
[
"ARC047",
"Natufian",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-LEV",
"-13000",
"-9500",
"c. 13,000–9500 BCE",
"Sedentary foragers built round houses, carved bone and stone, used sickles on wild cereals and made bead headdresses.",
"ground stone; bone carving; dentalium shell beadwork; sickle blades",
"mortars; sickles; figurines; bead ornaments",
"food and storage;clothing and adornment;shelter;ritual and belief",
"Dorothy Garrod (1928), after Wadi an-Natuf",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R2",
"F1.5",
"high",
"Burials include adorned individuals; handle remains carefully.",
"canon_cultures_horizons.csv"
],
[
"ARC048",
"Pre-Pottery Neolithic A",
"PPNA",
"archaeological-culture",
"People",
"F1.9a",
"WA-LEV;WA-ANA;WA-MES",
"-10000",
"-8800",
"c. 10,000–8800 BCE",
"Early cultivators built round houses, the Jericho tower and storage buildings.",
"stone architecture; ground stone; early cultivation",
"towers; granaries; axes",
"shelter;food and storage",
"Kathleen Kenyon (Jericho, 1950s)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC049",
"Pre-Pottery Neolithic B",
"PPNB",
"archaeological-culture",
"People",
"F1.9a",
"WA-LEV;WA-ANA;WA-MES",
"-8800",
"-6500",
"c. 8800–6500 BCE",
"Farming villages made lime plaster, plastered skulls and large statues, and traded obsidian.",
"lime plaster; naviform blade cores; obsidian exchange",
"plastered skulls; plaster statues ('Ain Ghazal); blades",
"shelter;ritual and belief;exchange and value",
"Kathleen Kenyon",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5",
"high",
"Plastered skulls are human remains: default-exclude from display.",
"canon_cultures_horizons.csv"
],
[
"ARC050",
"Taş Tepeler",
"Göbekli Tepe–Karahan Tepe group",
"archaeological-culture",
"People",
"F1.9a",
"WA-ANA",
"-9600",
"-8000",
"c. 9600–8000 BCE",
"Hunter-gatherer and early farming communities carved T-shaped pillars and animal reliefs in communal buildings.",
"limestone quarrying and carving; relief",
"T-pillars; sculptures; enclosures",
"ritual and belief;shelter",
"Şanlıurfa Neolithic research project (2020s); Klaus Schmidt (Göbekli Tepe, 1995 on)",
"",
"none",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"F1.16",
"medium",
"Name is a recent regional grouping; Göbekli Tepe itself is PPNA/PPNB.",
"canon_cultures_horizons.csv"
],
[
"ARC051",
"Central Anatolian Neolithic (Çatalhöyük)",
"Çatalhöyük",
"archaeological-culture",
"People",
"F1.9a",
"WA-ANA",
"-7100",
"-5950",
"c. 7100–5950 BCE",
"Densely packed houses with wall paintings, plaster reliefs, figurines and obsidian mirrors.",
"mud-brick; wall painting; obsidian polishing; clay figurines",
"paintings; figurines; mirrors",
"shelter;ritual and belief",
"James Mellaart (1960s); Ian Hodder (1993–2017)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Open Context (CC BY);UNESCO World Heritage listing (link out)",
"R2",
"F1.5;F1.14",
"high",
"Open Context holds Çatalhöyük data. Mellaart's later drawings include fabrications; flag.",
"canon_cultures_horizons.csv"
],
[
"ARC052",
"Halaf",
"Halafian",
"archaeological-culture",
"People",
"F1.9a",
"WA-MES;WA-ANA",
"-6100",
"-5100",
"c. 6100–5100 BCE",
"Makers of finely painted polychrome pottery and stamp seals across northern Mesopotamia.",
"polychrome pottery; stamp seals",
"pottery; seals; figurines",
"food and storage;record and writing;ritual and belief",
"Max von Oppenheim, after Tell Halaf",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC053",
"Ubaid",
"Ubaid period",
"archaeological-culture",
"People",
"F1.9a",
"WA-MES;WA-ARB;WA-IRN",
"-6500",
"-3800",
"c. 6500–3800 BCE",
"Ubaid communities made painted pottery, clay sickles and temples; their pottery reached the Gulf.",
"painted pottery; mud-brick; clay sickles",
"pottery; figurines; sickles",
"food and storage;ritual and belief;shelter",
"Named after Tell al-'Ubaid (H. R. Hall and Leonard Woolley, 1919–)",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC054",
"Uruk",
"Uruk period",
"archaeological-culture",
"People",
"F1.9a",
"WA-MES",
"-4000",
"-3100",
"c. 4000–3100 BCE",
"Uruk workshops mass-produced bevelled-rim bowls and developed cylinder seals and proto-cuneiform.",
"mould-made pottery; cylinder seals; accounting tokens",
"bowls; seals; tablets; Warka Vase",
"record and writing;food and storage;rule and display",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC055",
"Ghassulian",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-LEV",
"-4400",
"-3500",
"c. 4400–3500 BCE",
"Chalcolithic Levantine makers cast arsenical copper by lost-wax process (Nahal Mishmar hoard) and painted wall frescoes.",
"lost-wax copper casting; ivory carving; wall painting",
"maceheads; standards; ossuaries",
"ritual and belief;rule and display",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC056",
"Proto-Elamite",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-IRN",
"-3100",
"-2700",
"c. 3100–2700 BCE",
"Proto-Elamite tablets and seals show an administrative writing system across the Iranian plateau.",
"clay tablets; seals",
"tablets; seals",
"record and writing",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC057",
"Marlik",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-IRN",
"-1400",
"-1000",
"c. 14th–11th century BCE (Gilan, northern Iran)",
"A cemetery of elite tombs with repoussé gold and silver beakers, bronze weapons and zoomorphic pottery.",
"gold and silver repoussé; bronze casting; burnished pottery",
"gold beakers; zoomorphic vessels; weapons",
"rule and display;ritual and belief;war",
"Ezat Negahban (excavated 1961–62)",
"",
"funerary;conflict-looting",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Known almost entirely from tombs; 'Amlash' market pieces are often looted or fake.",
"canon_cultures_horizons.csv"
],
[
"ARC058",
"Luristan bronzes",
"Luristan",
"archaeological-culture",
"People",
"F1.9a",
"WA-IRN",
"-1000",
"-650",
"c. 1000–650 BCE (Iron Age western Iran)",
"Metalworkers of the Zagros cast bronze horse-bits, finials and weapons with animal imagery.",
"bronze casting",
"horse-bits; standard finials; axes; pins",
"transport;ritual and belief;war",
"archaeologists",
"",
"funerary;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.24",
"medium",
"Most on the market were looted from graves from the 1920s; many fakes. F1.24 case.",
"canon_cultures_horizons.csv"
],
[
"ARC059",
"Arabian Neolithic",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-ARB",
"-6000",
"-3500",
"c. 6000–3500 BCE",
"Herders and fishers across Arabia made fine bifacial arrowheads, shell ornaments and stone structures.",
"bifacial flaking; shell working",
"arrowheads; shell beads; cairns",
"tools;clothing and adornment;food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Broad regional label; many local variants.",
"canon_cultures_horizons.csv"
],
[
"ARC060",
"Hafit",
"Hafit period",
"archaeological-culture",
"People",
"F1.9a",
"WA-ARB",
"-3200",
"-2600",
"c. 3200–2600 BCE",
"Early Bronze Age communities in the UAE and Oman built beehive stone tombs on ridges and imported Jemdet Nasr pottery.",
"dry-stone tomb building; pottery import; copper",
"beehive tombs; pottery; beads",
"ritual and belief;exchange and value",
"Danish expedition (1959) at Jebel Hafit; later Emirati and Omani archaeology",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"F1.13",
"high",
"Part of the Al Ain UNESCO site (2011).",
"canon_cultures_horizons.csv"
],
[
"ARC061",
"Umm an-Nar",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-ARB",
"-2600",
"-2000",
"c. 2600–2000 BCE",
"Umm an-Nar communities smelted copper, built stone towers and communal round tombs, and traded with Mesopotamia and the Indus.",
"copper smelting; ashlar stone tombs; soft-stone vessels; date cultivation",
"circular tombs; towers; soft-stone vessels; copper ingots",
"exchange and value;ritual and belief;food and storage;tools",
"Danish expedition (P. V. Glob, 1959), after Umm an-Nar island (Abu Dhabi)",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R2",
"F1.13",
"high",
"Archaeological correlate of 'Magan'.",
"canon_cultures_horizons.csv"
],
[
"ARC062",
"Wadi Suq",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-ARB",
"-2000",
"-1600",
"c. 2000–1600 BCE",
"Middle Bronze Age Oman peninsula communities with long collective tombs and new soft-stone vessel styles.",
"soft-stone carving; copper; tomb building",
"tombs; vessels; weapons",
"ritual and belief;tools",
"archaeologists",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC063",
"Dadanite–Lihyanite",
"Dedan; Lihyan",
"archaeological-culture",
"People",
"F1.9a",
"WA-ARB",
"-800",
"-100",
"c. 8th–1st century BCE? (al-'Ula oasis)",
"Oasis kingdoms at al-'Ula carved colossal statues and inscriptions in Dadanitic script.",
"sandstone carving; inscriptions",
"statues; inscriptions; tombs",
"rule and display;record and writing;ritual and belief",
"epigraphers; Saudi archaeology (AlUla)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Chronology debated.",
"canon_cultures_horizons.csv"
],
[
"ARC064",
"Shulaveri–Shomu",
"Shulaveri-Shomutepe",
"archaeological-culture",
"People",
"F1.9a",
"WA-CAU",
"-6000",
"-4000",
"c. 6000–4000 BCE",
"Early farmers in Georgia, Armenia and Azerbaijan built round mud-brick houses; early grape wine residues come from their pots.",
"mud-brick; pottery; obsidian; viticulture",
"pottery; obsidian tools",
"food and storage;shelter",
"archaeologists",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC065",
"Maykop",
"Maikop",
"archaeological-culture",
"People",
"F1.9a;F1.11",
"WA-CAU;EU-EER",
"-3700",
"-3000",
"c. 3700–3000 BCE",
"North Caucasus kurgan burials with gold and silver vessels and bulls, and early arsenical bronze.",
"gold and silver working; arsenical bronze; kurgans",
"vessels; bulls; weapons",
"rule and display;ritual and belief",
"Nikolai Veselovsky (1897), after the Maykop kurgan",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC066",
"Kura–Araxes",
"Early Transcaucasian",
"archaeological-culture",
"People",
"F1.9a",
"WA-CAU;WA-ANA;WA-IRN;WA-LEV",
"-3500",
"-2000",
"c. 3500–2000 BCE",
"Makers of hand-burnished black-and-red pottery and hearths spread from the Caucasus to the Levant.",
"burnished pottery; metallurgy",
"pottery; hearths",
"food and storage;shelter",
"archaeologists",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"high",
"Levantine variant called Khirbet Kerak ware.",
"canon_cultures_horizons.csv"
],
[
"ARC067",
"Trialeti",
"Trialeti–Vanadzor",
"archaeological-culture",
"People",
"F1.9a",
"WA-CAU",
"-2200",
"-1500",
"c. 2200–1500 BCE",
"Middle Bronze Age kurgans in Georgia with gold goblets and silver vessels.",
"gold granulation; silver",
"goblets; vessels",
"rule and display;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC068",
"Colchian",
"Colchis; Colchian culture",
"archaeological-culture",
"People",
"F1.9a",
"WA-CAU",
"-1700",
"-600",
"c. 1700–600 BCE (western Georgia); later Colchis continues into Classical period",
"Western Georgian smiths cast bronze axes, hoes and figurines and worked early iron; the region's gold fed the Greek Golden Fleece story.",
"bronze casting; iron working; gold working",
"axes; hoes; figurines; ornaments",
"tools;clothing and adornment;ritual and belief",
"Georgian and Soviet archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Distinguish Bronze Age Colchian culture from Classical-era Colchis (Vani).",
"canon_cultures_horizons.csv"
],
[
"ARC069",
"Koban",
"",
"archaeological-culture",
"People",
"F1.9a",
"WA-CAU",
"-1100",
"-400",
"c. 1100–400 BCE",
"North Caucasus smiths made engraved bronze axes and belt buckles.",
"bronze casting and engraving; iron",
"axes; belt buckles; pins",
"war;clothing and adornment",
"Rudolf Virchow and others, after Koban (North Ossetia)",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC070",
"Aurignacian",
"",
"archaeological-culture",
"People",
"F1.11;F1.9a",
"EU-WCE;EU-IBE;EU-EER;EU-BYZ;WA-LEV",
"-43000",
"-33000",
"c. 43,000–33,000 BCE (calibrated ranges vary)",
"Early Homo sapiens in Europe made blade tools, carved ivory figurines, bone flutes and painted Chauvet Cave.",
"blade knapping; ivory carving; bone-flute making; cave painting",
"figurines (Hohlenstein-Stadel); flutes; beads; blades",
"tools;ritual and belief;play and music;clothing and adornment",
"Henri Breuil and Émile Cartailhac (early 1900s), after Aurignac (France)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R2",
"F1.5;F1.16",
"high",
"Stone-tool industry (with associated art), not a people.",
"canon_cultures_horizons.csv"
],
[
"ARC071",
"Gravettian",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-EER;EU-IBE;EU-BYZ",
"-33000",
"-21000",
"c. 33,000–21,000 BCE",
"Gravettian makers fired clay figurines (Dolní Věstonice), carved 'Venus' figures and built mammoth-bone dwellings.",
"fired clay; ivory and stone carving; mammoth-bone construction; textile impressions",
"figurines; beads; backed points",
"tools;ritual and belief;shelter;clothing and adornment",
"Named after La Gravette (France)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R2",
"F1.5;F1.18",
"high",
"Stone-tool industry (with associated art), not a people. Earliest known fired-clay objects.",
"canon_cultures_horizons.csv"
],
[
"ARC072",
"Solutrean",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-IBE",
"-22000",
"-17000",
"c. 22,000–17,000 BCE",
"Solutrean knappers made thin leaf-shaped points by pressure flaking and heat treatment.",
"pressure flaking; heat treatment",
"laurel-leaf points; bone needles",
"tools",
"Gabriel de Mortillet, after Solutré (France)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"Stone-tool industry (with associated art), not a people. 'Solutrean hypothesis' for American origins is rejected.",
"canon_cultures_horizons.csv"
],
[
"ARC073",
"Magdalenian",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-IBE",
"-17000",
"-12000",
"c. 17,000–12,000 BCE",
"Magdalenian makers carved spear-throwers and harpoons in antler and painted Lascaux and Altamira.",
"antler carving; cave painting and engraving; eyed-needle sewing",
"spear-throwers; harpoons; engraved plaques; cave art",
"tools;ritual and belief;clothing and adornment",
"Gabriel de Mortillet, after La Madeleine (France)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R2",
"F1.16",
"high",
"Stone-tool industry (with associated art), not a people.",
"canon_cultures_horizons.csv"
],
[
"ARC074",
"Maglemosian",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-SCA;EU-BLC;EU-WCE",
"-9000",
"-6400",
"c. 9000–6400 BCE",
"Mesolithic foragers of the North European Plain made bone and antler harpoons, amber carvings and dugout canoes.",
"bone and antler working; amber carving; dugout canoe making",
"harpoons; amber figures; axes",
"tools;transport;ritual and belief",
"Named after Maglemose bog (Denmark)",
"",
"none",
"National Museum of Denmark (CC BY-SA);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC075",
"Ertebølle",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-SCA;EU-WCE",
"-5300",
"-3950",
"c. 5300–3950 BCE",
"Coastal foragers of southern Scandinavia made pottery, paddles and shell middens before adopting farming.",
"pointed-base pottery; wooden paddles; fish traps",
"pots; lamps; paddles; weirs",
"food and storage;transport",
"Named after Ertebølle shell midden (Denmark)",
"",
"none",
"National Museum of Denmark (CC BY-SA);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC076",
"Lepenski Vir",
"Iron Gates Mesolithic",
"archaeological-culture",
"People",
"F1.11",
"EU-BYZ",
"-9500",
"-5500",
"c. 9500–5500 BCE",
"Danube Gorges foragers built trapezoidal houses and carved sandstone boulder sculptures with fish-like faces.",
"sandstone carving; lime-plaster floors",
"boulder sculptures; houses; burials",
"ritual and belief;shelter",
"Dragoslav Srejović (1965–70)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC077",
"Starčevo–Körös–Criș",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-BYZ;EU-EER",
"-6200",
"-5200",
"c. 6200–5200 BCE",
"Early farming communities of the Balkans and Carpathian Basin made pottery and figurines.",
"pottery; farming",
"pottery; figurines",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC078",
"Cardial Ware",
"Impressed Ware; Cardial–Epicardial",
"archaeological-culture",
"People",
"F1.11;F1.6",
"EU-IBE;EU-GRR;AF-MAG",
"-5500",
"-4500",
"c. 5500–4500 BCE",
"Early Mediterranean farmers decorated pots with cockle-shell (Cardium) impressions as farming spread by sea.",
"shell-impressed pottery",
"pottery",
"food and storage",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC079",
"Linear Pottery",
"LBK; Linearbandkeramik",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-EER",
"-5500",
"-4500",
"c. 5500–4500 BCE",
"First farmers of central Europe built timber longhouses and made band-decorated pottery.",
"timber longhouse construction; pottery; polished stone adzes",
"longhouses; pottery; adzes",
"shelter;food and storage;tools",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC080",
"Vinča",
"Vinča culture",
"archaeological-culture",
"People",
"F1.11",
"EU-BYZ",
"-5400",
"-4500",
"c. 5400–4500 BCE",
"Vinča communities in the central Balkans made abundant clay figurines and some of the earliest copper smelting in Europe.",
"pottery; figurine making; copper smelting",
"figurines; pottery; copper tools",
"ritual and belief;food and storage;tools",
"Miloje Vasić (excavations from 1908)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R1",
"F1.5",
"high",
"Existing in project. 'Vinča symbols' are not proven writing.",
"canon_cultures_horizons.csv"
],
[
"ARC081",
"Varna culture",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-BYZ",
"-4600",
"-4200",
"c. 4600–4200 BCE",
"The Varna cemetery holds the world's oldest large assemblage of worked gold, alongside copper and Spondylus shell.",
"gold working; copper; Spondylus shell working",
"gold ornaments; sceptres; bracelets",
"rule and display;ritual and belief;clothing and adornment",
"Found 1972; Ivan Ivanov",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC082",
"Cucuteni–Trypillia",
"Tripolye; Cucuteni",
"archaeological-culture",
"People",
"F1.11",
"EU-EER;EU-BYZ",
"-5500",
"-2750",
"c. 5500–2750 BCE",
"Makers of painted spiral pottery who built very large settlements (mega-sites) in Ukraine and Moldova.",
"painted pottery; clay house building",
"pottery; figurines; house models",
"food and storage;shelter;ritual and belief",
"Named after Cucuteni (Romania, 1884) and Trypillia (Ukraine; Vikentiy Khvoyka, 1890s)",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R2",
"F1.5",
"high",
"Ukrainian heritage at risk from war.",
"canon_cultures_horizons.csv"
],
[
"ARC083",
"Funnelbeaker",
"TRB; Trichterbecherkultur",
"archaeological-culture",
"People",
"F1.11",
"EU-SCA;EU-WCE;EU-EER",
"-4300",
"-2800",
"c. 4300–2800 BCE",
"Northern European farmers built megalithic tombs and made funnel-necked pottery and flint axes.",
"megalith building; pottery; flint axes",
"dolmens; passage graves; beakers; axes",
"ritual and belief;food and storage;tools",
"archaeologists",
"",
"funerary",
"National Museum of Denmark (CC BY-SA);Swedish History Museum (CC BY);Wikimedia Commons;Europeana (filter by rights)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC084",
"Maltese Temple culture",
"Temple period",
"archaeological-culture",
"People",
"F1.11",
"EU-GRR",
"-3600",
"-2500",
"c. 3600–2500 BCE",
"Maltese communities built megalithic temples and the Ħal Saflieni Hypogeum with carved figures.",
"megalithic building; stone carving",
"temples; figures; hypogeum",
"ritual and belief;shelter",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC085",
"Grooved Ware",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-BLC",
"-3200",
"-2500",
"c. 3200–2500 BCE",
"British Neolithic flat-based pottery linked to henges and Orkney settlements like Skara Brae.",
"pottery; stone furniture",
"pottery; carved stone balls",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Archaeology Data Service (open reports);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC086",
"Comb Ceramic",
"Pit–Comb Ware",
"archaeological-culture",
"People",
"F1.11",
"EU-SCA;EU-EER",
"-4200",
"-2000",
"c. 4200–2000 BCE",
"Forager potters of northeastern Europe decorated pots with comb impressions and carved elk-head figures.",
"comb-impressed pottery; amber and flint",
"pottery; figurines; amber",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Finna / Finnish Heritage Agency (CC BY);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC087",
"Yamnaya",
"Pit Grave culture",
"archaeological-culture",
"People",
"F1.11;F1.12a",
"EU-EER;AS-CEN",
"-3300",
"-2600",
"c. 3300–2600 BCE",
"Pontic–Caspian steppe herders used wagons and built kurgans; ancient DNA links them to later European populations.",
"wagon building; kurgan construction; copper working",
"wagons; kurgans; pottery",
"transport;ritual and belief",
"Vasily Gorodtsov (1901)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"Ancient DNA has made the name a proxy for 'Indo-European' migration; treat carefully.",
"canon_cultures_horizons.csv"
],
[
"ARC088",
"Corded Ware",
"Battle Axe culture",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-EER;EU-SCA",
"-3000",
"-2350",
"c. 3000–2350 BCE",
"Makers of cord-impressed beakers and stone battle axes, known largely from single graves.",
"pottery; stone axes",
"beakers; battle axes",
"food and storage;war",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;Europeana (filter by rights);National Museum of Denmark (CC BY-SA)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
