insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"ARC089",
"Únětice",
"Aunjetitz",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-EER",
"-2300",
"-1600",
"c. 2300–1600 BCE",
"Central European Early Bronze Age metalworkers who made ingot torcs, daggers and the Nebra sky disc.",
"bronze casting; gold inlay",
"Nebra sky disc; ingots; daggers",
"rule and display;ritual and belief;exchange and value",
"Čeněk Rýzner (1879), after Únětice near Prague",
"",
"none",
"Wikimedia Commons;open-access excavation reports;Europeana (filter by rights)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC090",
"El Argar",
"Argaric",
"archaeological-culture",
"People",
"F1.11",
"EU-IBE",
"-2200",
"-1550",
"c. 2200–1550 BCE",
"Southeastern Iberian hilltop towns with bronze and silver work and burials under houses.",
"bronze; silver; pottery",
"diadems; weapons; pottery",
"rule and display;war;ritual and belief",
"Louis and Henri Siret (1880s)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC091",
"Nordic Bronze Age",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-SCA",
"-1700",
"-500",
"c. 1700–500 BCE",
"Scandinavian bronze-casters made lurs, the Trundholm sun chariot and oak-coffin burials with preserved textiles.",
"bronze casting; wool textiles; rock carving",
"lurs; sun chariot; textiles",
"ritual and belief;play and music;clothing and adornment",
"archaeologists",
"",
"funerary",
"National Museum of Denmark (CC BY-SA);Swedish History Museum (CC BY);Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC092",
"Urnfield",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-EER;EU-BYZ",
"-1300",
"-750",
"c. 1300–750 BCE",
"Central European communities cremated their dead and made sheet-bronze vessels and armour.",
"sheet-bronze; cremation",
"urns; helmets; buckets",
"ritual and belief;war",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;Europeana (filter by rights)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC093",
"Villanovan",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-GRR",
"-900",
"-700",
"c. 900–700 BCE (earliest Iron Age phase of Etruria and parts of northern Italy)",
"Villanovan communities cremated their dead in biconical and hut-shaped urns and made bronze helmets and fibulae, forerunners of Etruscan crafts.",
"bronze sheet work; impasto pottery; cremation",
"hut urns; biconical urns; crested helmets; fibulae",
"ritual and belief;war;clothing and adornment",
"Giovanni Gozzadini (1850s), after Villanova near Bologna",
"",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;Europeana (filter by rights)",
"R3",
"",
"high",
"Routes to CIV Etruscan.",
"canon_cultures_horizons.csv"
],
[
"ARC094",
"Hallstatt",
"Hallstatt culture (C–D)",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-BYZ",
"-800",
"-450",
"Hallstatt C–D c. 800–450 BCE (Hallstatt A–B overlap the Urnfield period)",
"Salt miners and elite households in central Europe used iron, imported Greek and Etruscan vessels and made patterned wool twills, preserved in the Hallstatt salt mines.",
"salt mining; iron smithing; twill weaving; sheet-bronze",
"swords; situlae; textiles; wagon burials",
"rule and display;clothing and adornment;exchange and value;ritual and belief",
"Named after Hallstatt (Austria; cemetery excavated from 1846 by Johann Georg Ramsauer); Hallstatt/La Tène division by Hans Hildebrand (1870s)",
"",
"funerary",
"Wikimedia Commons;Europeana (filter by rights);open-access excavation reports",
"R2",
"F1.18",
"high",
"Routes from CIV Celtic.",
"canon_cultures_horizons.csv"
],
[
"ARC095",
"La Tène",
"",
"archaeological-culture",
"People",
"F1.11",
"EU-WCE;EU-BLC;EU-IBE;EU-BYZ",
"-450",
"-1",
"c. 450 BCE to Roman conquest (1st century BCE); later in Ireland",
"Iron Age metalworkers made curvilinear ornament on torcs, scabbards, shields and mirrors that became the basis of 'Celtic art'.",
"repoussé; enamel; iron smithing; wheel-thrown pottery",
"torcs; shields; scabbards; mirrors; coins",
"clothing and adornment;war;rule and display;exchange and value",
"Named after La Tène (Lake Neuchâtel, Switzerland; finds from 1857)",
"",
"none",
"Met Open Access (CC0);Portable Antiquities Scheme (CC BY);British Museum collection online (link out);Wikimedia Commons;Europeana (filter by rights)",
"R2",
"F1.15",
"high",
"Routes from CIV Celtic.",
"canon_cultures_horizons.csv"
],
[
"ARC096",
"Talaiotic",
"Talayotic",
"archaeological-culture",
"People",
"F1.11",
"EU-IBE;EU-GRR",
"-1000",
"-123",
"c. 1000 BCE to Roman conquest of the Balearics (123 BCE)",
"Balearic islanders built cyclopean stone towers (talaiots) and T-shaped taula sanctuaries.",
"dry-stone megalithic building; bronze",
"talaiots; taulas; navetas; bronze figures",
"shelter;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R3",
"",
"medium",
"Menorca Talayotic sites UNESCO (2023).",
"canon_cultures_horizons.csv"
],
[
"ARC097",
"Castro culture",
"Cultura castreña",
"archaeological-culture",
"People",
"F1.11",
"EU-IBE",
"-900",
"100",
"c. 9th century BCE to Romanisation (1st century CE)",
"Hillfort communities of northwest Iberia built round stone houses and made gold torcs and carved stone warriors.",
"stone building; gold working",
"hillforts (castros); torcs; warrior statues",
"shelter;clothing and adornment;rule and display",
"archaeologists",
"",
"none",
"Wikimedia Commons;Europeana (filter by rights);open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC098",
"Djeitun",
"Jeitun",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN",
"-6200",
"-4500",
"c. 6200–4500 BCE (southern Turkmenistan)",
"The earliest farming villages of Central Asia, with mud-brick houses and painted pottery.",
"mud-brick; pottery; cereal farming",
"houses; pottery; figurines",
"shelter;food and storage",
"Vadim Masson (Soviet archaeology)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC099",
"Botai",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN",
"-3700",
"-3100",
"c. 3700–3100 BCE (northern Kazakhstan)",
"Botai settlements hold early evidence of horse use, including possible bit wear and mare's-milk residues in pots.",
"horse husbandry (debated); pottery; bone tools",
"pottery; bone tools; pit houses",
"transport;food and storage;shelter",
"Viktor Zaibert (1980s)",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Botai horses were ancestors of Przewalski's horses, not modern domestic horses (aDNA, 2018).",
"canon_cultures_horizons.csv"
],
[
"ARC100",
"Afanasievo",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN;AS-NTH",
"-3300",
"-2500",
"c. 3300–2500 BCE (Altai, Minusinsk)",
"Early herders of the Altai and Minusinsk basin with copper objects and kurgan burials, genetically related to Yamnaya.",
"copper working; pottery; herding",
"pottery; copper ornaments; kurgans",
"food and storage;ritual and belief",
"Sergei Teploukhov (1920s), after Afanasyeva Gora",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC101",
"Okunevo",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH",
"-2500",
"-1800",
"c. 2500–1800 BCE (Minusinsk basin)",
"Okunevo communities carved stone stelae with faces and rayed designs.",
"stone carving; copper-bronze",
"stelae; figurines",
"ritual and belief",
"archaeologists",
"",
"funerary;sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC102",
"Sintashta",
"Sintashta–Petrovka",
"archaeological-culture",
"People",
"F1.12a;F1.11",
"AS-CEN;EU-EER",
"-2100",
"-1800",
"c. 2100–1800 BCE (southern Urals)",
"Fortified settlements with bronze metallurgy, where some of the earliest spoked-wheel chariots were buried.",
"bronze metallurgy; spoked-wheel chariot building",
"chariots; weapons; fortified settlements",
"transport;war;tools",
"archaeologists",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R2",
"F1.19a",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC103",
"Andronovo",
"Andronovo horizon; Andronovo culture-historical community",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN;AS-NTH",
"-2000",
"-1150",
"c. 2000–1150 BCE",
"Bronze Age herders across the Kazakh steppe with timber houses, tin-bronze and geometric pottery.",
"tin-bronze metallurgy; timber-framed houses; pottery",
"pottery; bronze tools; ornaments",
"tools;food and storage;shelter",
"Sergei Teploukhov (1920s), after Andronovo village",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"high",
"Often called a horizon or 'community' of related cultures (Alakul, Fedorovo).",
"canon_cultures_horizons.csv"
],
[
"ARC104",
"Bactria–Margiana Archaeological Complex",
"BMAC; Oxus civilisation",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN",
"-2250",
"-1700",
"c. 2250–1700 BCE",
"Walled oasis towns (Gonur Depe) with compartmented seals, composite stone figures and metalwork.",
"soft-stone carving; metal casting; mud-brick",
"seals; figurines; vessels",
"ritual and belief;rule and display;shelter",
"Viktor Sarianidi (1976)",
"",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.24",
"high",
"Routes from CIV Oxus; many 'Bactrian' objects on the market are looted or fake.",
"canon_cultures_horizons.csv"
],
[
"ARC105",
"Saka",
"Sakas; Issyk kurgan",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN",
"-900",
"-100",
"c. 9th–1st century BCE",
"Saka metalworkers in Kazakhstan and the Tian Shan made gold 'animal style' ornaments, including the Issyk 'Golden Man' costume.",
"gold casting and appliqué; felt",
"costume plaques; headdresses; cauldrons",
"clothing and adornment;rule and display;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Closely related to Scythians; routes from CIV Scythian.",
"canon_cultures_horizons.csv"
],
[
"ARC106",
"Xiaohe",
"Xiaohe–Gumugou; Tarim Basin mummies",
"archaeological-culture",
"People",
"F1.12a;F1.8",
"AS-CEN;AS-CHN",
"-2000",
"-1500",
"c. 2000–1500 BCE (Tarim Basin)",
"Desert burials preserved felt, woven wool, baskets and early kefir cheese.",
"wool weaving; felting; basketry",
"textiles; baskets; wooden posts",
"clothing and adornment;food and storage;ritual and belief",
"archaeologists",
"",
"funerary;sacred",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"medium",
"Preserved human bodies; default-exclude. Politically sensitive in Xinjiang.",
"canon_cultures_horizons.csv"
],
[
"ARC107",
"Deer stone–khirigsuur complex",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-CEN;AS-NTH",
"-1300",
"-700",
"c. 1300–700 BCE (Mongolia, Tuva)",
"Late Bronze Age herders carved deer stones and built large stone mounds (khirigsuurs) with horse offerings.",
"stone carving; mound building",
"deer stones; khirigsuurs",
"ritual and belief",
"archaeologists",
"",
"sacred;funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC108",
"Pazyryk",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH;AS-CEN",
"-500",
"-200",
"c. 6th–3rd century BCE (Altai)",
"Frozen Altai tombs preserved felt hangings, a knotted pile carpet, tattooed skin, saddles and wooden carvings.",
"felt appliqué; pile-carpet knotting; wood carving; tattooing",
"Pazyryk carpet; felt hangings; saddles; headdresses",
"clothing and adornment;ritual and belief;transport;rule and display",
"Sergei Rudenko (1929; 1947–49)",
"",
"funerary;ancestral;living-community",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.18;F1.24",
"high",
"Altai communities protest the removal of the Ukok 'princess' (1993); oldest known pile carpet (Hermitage).",
"canon_cultures_horizons.csv"
],
[
"ARC109",
"Tagar",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH",
"-800",
"-100",
"c. 8th–1st century BCE (Minusinsk)",
"Iron Age herders of southern Siberia cast bronze animal-style knives and built large kurgans.",
"bronze casting; kurgan building",
"knives; plaques; kurgans",
"ritual and belief;tools",
"archaeologists",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC110",
"Tashtyk",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH",
"-100",
"400",
"c. 1st century BCE–4th century CE (Minusinsk)",
"Tashtyk communities of southern Siberia made painted plaster funerary masks and dolls holding cremated remains.",
"plaster moulding and painting; textiles; wood carving",
"funerary masks; burial dolls; textiles",
"ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC111",
"Xiongnu",
"",
"archaeological-culture",
"People",
"F1.12a;F1.8",
"AS-CEN;AS-CHN;AS-NTH",
"-209",
"100",
"c. 209 BCE–1st century CE (political confederation); archaeological culture to c. 2nd century",
"Xiongnu elite tombs held Chinese silks, Greco-Bactrian textiles and steppe metalwork, showing a nomadic empire at the centre of exchange.",
"gold and bronze belt plaques; felt; imported silk",
"belt plaques; textiles; lacquer",
"rule and display;exchange and value;clothing and adornment",
"Chinese historical sources (Sima Qian); Mongolian and Russian archaeology (Noin-Ula, 1924)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC112",
"Mal'ta–Buret'",
"",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH",
"-22000",
"-19000",
"c. 24,000–21,000 years ago (Lake Baikal region)",
"Upper Palaeolithic hunters carved mammoth-ivory figurines and birds and built semi-subterranean houses.",
"ivory carving; bone working",
"figurines; plaques; beads",
"ritual and belief;clothing and adornment",
"Mikhail Gerasimov (1928)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"A Mal'ta child genome (2013) links Siberians and Native Americans.",
"canon_cultures_horizons.csv"
],
[
"ARC113",
"Kitoi",
"Baikal Early Neolithic",
"archaeological-culture",
"People",
"F1.12a",
"AS-NTH",
"-6000",
"-5000",
"c. 6000–5000 BCE",
"Hunter-gatherer cemeteries by Lake Baikal with fishing gear, ochre and nephrite rings.",
"nephrite working; bone and antler tools",
"fish lures; nephrite rings",
"food and storage;clothing and adornment",
"archaeologists",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC114",
"Okhotsk culture",
"",
"archaeological-culture",
"People",
"F1.12a;F1.8",
"AS-NTH;AS-JPN",
"500",
"1200",
"c. 5th–12th century CE (Sakhalin, Hokkaido, Kurils)",
"Maritime hunters of the Okhotsk Sea carved ivory and bone and kept bear-skull shrines in their houses.",
"bone and ivory carving; sea-mammal hunting",
"figurines; harpoons; pottery",
"food and storage;ritual and belief",
"archaeologists",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Links with later Ainu bear ritual debated.",
"canon_cultures_horizons.csv"
],
[
"ARC115",
"Xinglongwa",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-6200",
"-5400",
"c. 6200–5400 BCE (Inner Mongolia, Liaoning)",
"Planned villages of pit houses with some of the earliest carved jade (slit rings) in China.",
"jade working; pit-house construction; pottery",
"jade slit rings; pottery; houses",
"clothing and adornment;shelter;food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC116",
"Peiligang",
"Peiligang–Jiahu",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-7000",
"-5000",
"c. 7000–5000 BCE (Henan)",
"Early millet and rice farmers; the Jiahu site preserved bone flutes and early fermented-drink residues.",
"pottery; bone-flute making; tortoise-shell rattles",
"flutes; pottery; grinding slabs",
"food and storage;play and music;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.4",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC117",
"Hemudu",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-5000",
"-4500",
"c. 5000–4500 BCE (Zhejiang)",
"Waterlogged rice-farming villages with pile-built houses using mortise-and-tenon joinery and carved bone and ivory.",
"mortise-and-tenon carpentry; bone spades; lacquer (early)",
"stilt houses; bone tools; lacquered bowl",
"shelter;food and storage;tools",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC118",
"Yangshao",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-5000",
"-3000",
"c. 5000–3000 BCE (Yellow River)",
"Millet-farming villages made red painted pottery, some with fish and human-face motifs.",
"painted pottery; pit houses",
"painted basins; jars",
"food and storage;ritual and belief",
"Johan Gunnar Andersson (1921), after Yangshao village",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC119",
"Majiayao",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-3300",
"-2000",
"c. 3300–2000 BCE (Gansu, Qinghai)",
"Potters made spiral-painted jars and one of the earliest bronze knives in China.",
"painted pottery; copper-bronze casting",
"painted jars; knife",
"food and storage;tools",
"J. G. Andersson (1920s)",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC120",
"Dawenkou",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-4100",
"-2600",
"c. 4100–2600 BCE (Shandong)",
"Burials with pottery, jade and ivory show growing social ranking; some pots bear early signs.",
"pottery; jade; ivory carving",
"pottery; jades; tall-stemmed cups",
"food and storage;rule and display;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC121",
"Hongshan",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-4700",
"-2900",
"c. 4700–2900 BCE (Liaoning, Inner Mongolia)",
"Hongshan makers carved jade 'pig-dragons' and hooked cloud pendants and built stone cairns and a 'goddess temple' at Niuheliang.",
"jade carving; stone cairn building; clay sculpture",
"jade pig-dragons; cloud pendants; figures",
"ritual and belief;clothing and adornment",
"Named after Hongshanhou (Chifeng); Japanese excavations 1930s",
"",
"funerary;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"",
"high",
"Jades are mostly from burials; many fakes on the market.",
"canon_cultures_horizons.csv"
],
[
"ARC122",
"Liangzhu",
"Liangzhu civilisation",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-3300",
"-2300",
"c. 3300–2300 BCE (Lake Tai)",
"Liangzhu jade workers carved cong and bi with fine incised masks, and the city had walls and a large dam system.",
"jade carving with abrasives; earth dam engineering; lacquer",
"cong; bi; axes; dams",
"ritual and belief;rule and display;food and storage",
"Shi Xingeng (1936); UNESCO (2019)",
"",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC123",
"Longshan",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-3000",
"-1900",
"c. 3000–1900 BCE (lower and middle Yellow River)",
"Longshan potters threw eggshell-thin black cups on a fast wheel; walled towns such as Taosi appear.",
"fast-wheel pottery; rammed earth; jade",
"eggshell cups; walled towns; jades",
"food and storage;rule and display;shelter",
"Excavations at Chengziya (1930); Li Ji and others",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"",
"high",
"Distinct from HOR Longshan horizon (K. C. Chang).",
"canon_cultures_horizons.csv"
],
[
"ARC124",
"Shimao",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-2300",
"-1800",
"c. 2300–1800 BCE (Shaanxi)",
"A stone-walled city with carved stone reliefs and jades set into walls.",
"stone masonry; relief carving; jade",
"walls; reliefs",
"shelter;rule and display;ritual and belief",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Some human sacrifice at gates; care with remains.",
"canon_cultures_horizons.csv"
],
[
"ARC125",
"Erlitou",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-1900",
"-1500",
"c. 1900–1500 BCE (Henan)",
"Erlitou foundries made the first piece-mould cast bronze vessels in China; its palace complex is linked by some to the Xia.",
"piece-mould bronze casting; turquoise mosaic",
"jue; turquoise dragon; plaques",
"rule and display;ritual and belief",
"Xu Xusheng (1959)",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5",
"high",
"Xia identification is debated.",
"canon_cultures_horizons.csv"
],
[
"ARC126",
"Erligang",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-1600",
"-1400",
"c. 1600–1400 BCE",
"Early Shang bronze workshops spread standardised vessels across a broad region.",
"piece-mould casting",
"ding; jue",
"rule and display;ritual and belief",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC127",
"Sanxingdui",
"Sanxingdui civilisation",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-1700",
"-1150",
"c. 1700–1150 BCE; sacrificial pits c. 1200–1100 BCE",
"Sichuan bronze-casters made large masks, a bronze tree and a standing figure unlike Shang work.",
"bronze casting; gold foil; jade",
"masks; heads; tree; gold mask",
"ritual and belief;rule and display",
"Pits found 1986; new pits 2020–22",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"Sacrificial pits (objects deliberately buried).",
"canon_cultures_horizons.csv"
],
[
"ARC128",
"Jinsha",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-CHN",
"-1200",
"-500",
"c. 1200–500 BCE (Chengdu plain)",
"Successor centre to Sanxingdui whose makers cut the gold 'sun and immortal birds' foil disc and worked ivory, jade and bronze.",
"gold foil cutting; jade carving; ivory; bronze casting",
"gold sun-bird disc; jade cong; ivory tusks; bronze figures",
"ritual and belief;rule and display",
"Found 2001 during construction in Chengdu",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Sun-bird motif is China's official cultural heritage logo.",
"canon_cultures_horizons.csv"
],
[
"ARC129",
"Dian",
"Dian kingdom",
"archaeological-culture",
"People",
"F1.8;F1.9",
"AS-CHN;AS-MSE",
"-400",
"100",
"c. 4th century BCE–1st century CE (Lake Dian, Yunnan)",
"Dian bronze-casters made cowrie containers topped with miniature scenes of weaving, ritual and warfare, and bronze drums.",
"lost-wax and piece-mould bronze casting; gilding",
"cowrie containers; drums; weapons; buckles",
"rule and display;ritual and belief;exchange and value;clothing and adornment",
"Excavations at Shizhaishan (1955–)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.18",
"medium",
"Scenes show women weaving on backstrap looms (F1.18).",
"canon_cultures_horizons.csv"
],
[
"ARC130",
"Chulmun",
"Jeulmun; comb-pattern pottery",
"archaeological-culture",
"People",
"F1.8",
"AS-KOR",
"-8000",
"-1500",
"c. 8000–1500 BCE",
"Korean Neolithic foragers and early cultivators made comb-pattern pottery.",
"comb-incised pottery; ground stone",
"pottery; net sinkers; shell middens",
"food and storage;tools",
"archaeologists",
"",
"none",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC131",
"Mumun",
"Plain pottery period",
"archaeological-culture",
"People",
"F1.8",
"AS-KOR",
"-1500",
"-300",
"c. 1500–300 BCE",
"Rice-farming villages made undecorated pottery, polished red jars and stone daggers, and began bronze use.",
"plain and red-burnished pottery; polished stone daggers; bronze (later)",
"pottery; stone daggers; mandolin-shaped daggers",
"food and storage;war;ritual and belief",
"archaeologists",
"",
"none",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC132",
"Korean dolmen tradition",
"Gochang, Hwasun and Ganghwa dolmens",
"archaeological-culture",
"People",
"F1.8",
"AS-KOR",
"-1000",
"-300",
"c. 1st millennium BCE (Mumun)",
"Communities raised thousands of stone dolmens, the densest concentration in the world.",
"megalith quarrying and raising",
"dolmens; grave goods",
"ritual and belief",
"archaeologists; UNESCO (2000)",
"",
"funerary",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC133",
"Jōmon",
"Jomon",
"archaeological-culture",
"People",
"F1.8",
"AS-JPN",
"-14000",
"-300",
"c. 14,000–300 BCE; end dates vary regionally (Yayoi began earlier in Kyushu)",
"Jōmon foragers made some of the world's earliest pottery, cord-marked and later flame-rimmed, plus lacquer and clay dogū figures.",
"cord-marked pottery; lacquer; clay figurine making",
"flame-style pots; dogū; lacquered combs",
"food and storage;ritual and belief;clothing and adornment",
"From Edward S. Morse's 'cord-marked' pottery (1877)",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);ColBase, Japan NICH (check per-image terms);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R2",
"F1.5",
"high",
"Northern Jōmon sites UNESCO (2021). Ainu are living descendants in the north.",
"canon_cultures_horizons.csv"
],
[
"ARC134",
"Yayoi",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-JPN",
"-900",
"250",
"c. 900 BCE–250 CE (AMS revision of older c. 300 BCE start)",
"Wet-rice farmers, arriving from the Korean peninsula and mixing with Jōmon people, made bronze bells (dōtaku) and wheel-finished pottery.",
"paddy rice farming; bronze casting; iron; weaving",
"dōtaku; pottery; mirrors",
"food and storage;ritual and belief;clothing and adornment",
"After Yayoi-chō, Tokyo (pottery found 1884)",
"",
"none",
"Met Open Access (CC0);ColBase, Japan NICH (check per-image terms);Wikimedia Commons",
"R2",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC135",
"Kofun",
"Kofun period",
"archaeological-culture",
"People",
"F1.8",
"AS-JPN",
"250",
"538",
"c. 250–538 CE (to 710 in some schemes)",
"Elite keyhole-shaped tombs were ringed by clay haniwa figures of people, horses and houses.",
"tomb building; haniwa terracotta; Sue stoneware",
"haniwa; mirrors; armour; Sue ware",
"ritual and belief;rule and display;war",
"archaeologists",
"",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);ColBase, Japan NICH (check per-image terms);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R2",
"",
"high",
"Imperial tombs are sacred and closed to excavation (Imperial Household Agency).",
"canon_cultures_horizons.csv"
],
[
"ARC136",
"Satsumon",
"",
"archaeological-culture",
"People",
"F1.8",
"AS-JPN",
"700",
"1200",
"c. 7th–13th century CE (Hokkaido)",
"Hokkaido communities made scratched-pattern pottery and are considered ancestral to Ainu culture.",
"brushed pottery; iron import",
"pottery; houses",
"food and storage;shelter",
"archaeologists",
"",
"Indigenous-community;ancestral",
"ColBase, Japan NICH (check per-image terms);open-access excavation reports",
"R3",
"",
"medium",
"Ainu are a living Indigenous people, recognised 2019.",
"canon_cultures_horizons.csv"
],
[
"ARC137",
"Mehrgarh (Neolithic)",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-7000",
"-2600",
"c. 7000–2600 BCE (Balochistan)",
"One of South Asia's earliest farming villages, with mud-brick storage, early cotton and the earliest known drilled teeth.",
"mud-brick; bead drilling; pottery",
"beads; figurines; pottery",
"food and storage;clothing and adornment;shelter;care and access",
"Jean-François Jarrige (1974–)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC138",
"Early Harappan",
"Regionalisation era; Ravi, Kot Diji",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-3300",
"-2600",
"c. 3300–2600 BCE",
"Walled towns with painted pottery before the integration of the Mature Harappan phase.",
"pottery; mud-brick",
"pottery; figurines",
"food and storage;shelter",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"Member of CIV Indus Valley.",
"canon_cultures_horizons.csv"
],
[
"ARC139",
"Mature Harappan",
"Integration era",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-2600",
"-1900",
"c. 2600–1900 BCE",
"Planned brick cities (Mohenjo-daro, Harappa, Dholavira) with seals, weights and long-drilled carnelian beads.",
"fired brick; carnelian drilling; steatite seals; faience",
"seals; beads; weights; figurines",
"record and writing;exchange and value;clothing and adornment;shelter",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R1",
"F1.5",
"high",
"Member of CIV Indus Valley.",
"canon_cultures_horizons.csv"
],
[
"ARC140",
"Late Harappan",
"Localisation era; Posturban Harappan",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-1900",
"-1300",
"c. 1900–1300 BCE",
"Regional successor phases (e.g. Jhukar, Rangpur, Cemetery H) in which large cities shrank but bead-making, pottery and farming continued and shifted east and south.",
"pottery; beadwork; faience; copper",
"regional pottery styles; beads",
"food and storage;clothing and adornment",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.3",
"high",
"Member of CIV Indus Valley; avoid 'collapse' framing.",
"canon_cultures_horizons.csv"
],
[
"ARC141",
"Ochre Coloured Pottery",
"OCP; OCP–Copper Hoard culture",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-2000",
"-1500",
"c. 2000–1500 BCE (Ganga–Yamuna Doab)",
"Upper Ganges communities made ochre-washed pottery and are associated with copper hoards; burials at Sinauli held wooden carts sheathed in copper.",
"ochre-slipped pottery; copper casting; copper sheathing",
"pottery; copper harpoons; anthropomorphic figures; carts",
"tools;ritual and belief;transport",
"B. B. Lal (1950s) and later Archaeological Survey of India (Sinauli, 2018)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Sinauli 'chariot' interpretation debated.",
"canon_cultures_horizons.csv"
],
[
"ARC142",
"Painted Grey Ware",
"PGW",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-1200",
"-600",
"c. 1200–600 BCE (western Ganga plain)",
"Iron Age farming communities made fine wheel-thrown grey pottery painted in black and began iron working in the Ganga plain.",
"fine grey pottery; iron smithing; glass beads",
"bowls; dishes; iron tools",
"food and storage;tools",
"B. B. Lal (Hastinapura excavations, 1950–52)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Often linked to later Vedic texts and Mahabharata sites; that link is contested.",
"canon_cultures_horizons.csv"
],
[
"ARC143",
"Northern Black Polished Ware",
"NBPW",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-700",
"-200",
"c. 700–200 BCE",
"A glossy, metallic-looking black pottery used in the early historic cities of the Ganga plain, including under the Mauryas.",
"high-gloss pottery firing",
"dishes; bowls",
"food and storage;rule and display;exchange and value",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Luxury ware; linked with second urbanisation.",
"canon_cultures_horizons.csv"
],
[
"ARC144",
"Deccan Chalcolithic",
"Malwa; Jorwe; Savalda",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-2000",
"-700",
"c. 2000–700 BCE (Maharashtra, Madhya Pradesh)",
"Farming villages of the Deccan made painted pottery and copper tools; Inamgaon and Daimabad yielded bronze sculptures (date debated).",
"painted pottery; copper working",
"painted pottery; urn burials; copper axes",
"food and storage;tools;ritual and belief",
"H. D. Sankalia and Deccan College (1950s–80s)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"Groups several named cultures; Daimabad bronzes' date contested.",
"canon_cultures_horizons.csv"
],
[
"ARC145",
"Southern Neolithic",
"Ashmound tradition",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-3000",
"-1200",
"c. 3000–1200 BCE (Karnataka, Andhra Pradesh)",
"Herders and farmers of the southern Deccan burned cattle dung into large ash mounds and made ground-stone axes and rock art.",
"ground stone; dung burning; rock painting and bruising",
"ashmounds; axes; rock art",
"food and storage;tools;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC146",
"Megalithic South India",
"Iron Age South India; megalithic burials",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-1200",
"300",
"c. 1200 BCE–300 CE",
"Iron Age communities built stone-circle and cist burials with black-and-red ware, iron tools and carnelian beads.",
"iron smithing; black-and-red ware; bead drilling; stone setting",
"cists; urns; iron weapons; beads",
"ritual and belief;tools;war",
"archaeologists",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"Includes Adichanallur urn cemetery.",
"canon_cultures_horizons.csv"
],
[
"ARC147",
"Gandhara Grave culture",
"Swat protohistoric graves",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-1600",
"-500",
"c. 1600–500 BCE (Swat, Dir)",
"Cemeteries in the Swat valley with grey pottery and copper, linked by genetics to later South Asian populations.",
"grey pottery; copper",
"pottery; pins; graves",
"ritual and belief",
"Italian Archaeological Mission (IsMEO) and Ahmad Hasan Dani (1960s)",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC148",
"Balangoda culture",
"Sri Lankan Mesolithic",
"archaeological-culture",
"People",
"F1.9",
"AS-SAS",
"-38000",
"-1000",
"from c. 38,000 years ago (Batadomba-lena, Fa-Hien) to the Holocene",
"Sri Lankan rainforest foragers made geometric microliths and bone tools at a very early date.",
"microlith production; bone tools",
"microliths; bone points; beads",
"tools;food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Stone-tool industry. Vedda people are a living community.",
"canon_cultures_horizons.csv"
],
[
"ARC149",
"Burzahom (Kashmir Neolithic)",
"Northern Neolithic",
"archaeological-culture",
"People",
"F1.9",
"AS-HIM;AS-SAS",
"-3000",
"-1500",
"c. 3000–1500 BCE",
"Kashmir valley farmers dug pit houses, made harvesting knives and bone tools, and carved a hunting scene on stone.",
"pit-dwelling construction; bone tools; ground-stone knives",
"harvesters; bone awls; engraved slab",
"shelter;food and storage;tools",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC150",
"Karuo",
"Kharro",
"archaeological-culture",
"People",
"F1.9",
"AS-HIM",
"-3300",
"-2000",
"c. 3300–2000 BCE (Chamdo, eastern Tibet)",
"Early farming villages of eastern Tibet with millet, stone houses, painted pottery and shell ornaments.",
"stone house building; pottery; ground stone",
"pottery; ornaments; axes",
"shelter;food and storage;clothing and adornment",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC151",
"Qugong",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-HIM",
"-1400",
"-1100",
"early phase at the type site re-dated to c. 1400–1300 cal BCE by 2024 re-excavation (earlier estimates c. 2000–1500 or 1750–1100 BCE); end approximate (Lhasa)",
"A Neolithic settlement near Lhasa whose potters made polished, incised and stamped round-based wares.",
"burnished pottery; incised and stamped decoration",
"pottery; tools",
"food and storage;tools",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"low",
"Copper/metal claim removed: not reported in the 2024 re-excavation (Neolithic assemblage); restore only with a source.",
"canon_cultures_horizons.csv"
],
[
"ARC152",
"Mustang cave tombs",
"Chokhopani; Mebrak; Samdzong",
"archaeological-culture",
"People",
"F1.9",
"AS-HIM",
"-1000",
"650",
"c. 1000 BCE–650 CE (Upper Mustang, Nepal)",
"Cliff-cut cave burials with wooden coffins, a gold-and-silver funerary mask, textiles and beads.",
"wood coffin making; gold and silver repoussé; weaving",
"coffins; masks; beads",
"ritual and belief",
"archaeologists",
"",
"funerary;sacred",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC153",
"Hoabinhian",
"",
"archaeological-culture",
"People",
"F1.9;F1.8",
"AS-MSE;AS-ISE;AS-CHN",
"-12000",
"-3000",
"c. 12,000–3000 BCE (earlier in some sites)",
"Forager toolkit of unifacially flaked cobbles (sumatraliths) used across mainland Southeast Asia and Sumatra.",
"unifacial cobble flaking",
"sumatraliths; grinding stones",
"tools;food and storage",
"Madeleine Colani (1920s), after Hòa Bình province (Vietnam)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"high",
"Stone-tool industry.",
"canon_cultures_horizons.csv"
],
[
"ARC154",
"Phùng Nguyên",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"-2000",
"-1500",
"c. 2000–1500 BCE (Red River delta)",
"Neolithic to early Bronze Age villages with incised pottery and jade.",
"pottery; stone; early bronze",
"pottery; ornaments",
"food and storage;clothing and adornment",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC155",
"Ban Chiang",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"-2100",
"200",
"c. 2100 BCE–200 CE; start of bronze working debated (c. 1500–1000 BCE)",
"Northeast Thai villagers buried their dead with red-on-buff painted pottery, bronze bracelets and later iron, a key case for independent Southeast Asian metallurgy.",
"painted pottery; bronze casting; iron",
"painted jars; bronze bracelets; rollers",
"ritual and belief;clothing and adornment;food and storage",
"Found 1966; Thai Fine Arts Department and University of Pennsylvania (Chester Gorman, Pisit Charoenwongsa)",
"",
"funerary;conflict-looting",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R2",
"F1.5;F1.24",
"high",
"Heavily looted in the 1960s–70s; US federal investigation (2008) led to returns to Thailand. F1.24 case.",
"canon_cultures_horizons.csv"
],
[
"ARC156",
"Đông Sơn",
"Dong Son",
"archaeological-culture",
"People",
"F1.9;F1.8",
"AS-MSE;AS-CHN;AS-ISE",
"-1000",
"100",
"c. 1000 BCE–1st century CE (Red River valley), drums traded later",
"Đông Sơn bronze-casters made large decorated kettle drums that were carried across Island Southeast Asia.",
"lost-wax and piece-mould bronze casting",
"bronze drums; situlae; daggers",
"rule and display;ritual and belief;play and music;exchange and value",
"After Đông Sơn village (Thanh Hóa), excavated 1924–; EFEO (Victor Goloubew)",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13;F1.4",
"high",
"Drums reach Indonesia (Heger type I).",
"canon_cultures_horizons.csv"
],
[
"ARC157",
"Sa Huỳnh",
"Sa Huynh",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"-1000",
"200",
"c. 1000 BCE–200 CE (central and southern Vietnam)",
"Coastal communities buried their dead in large jars with nephrite lingling-o earrings and glass and carnelian beads.",
"jar burial; nephrite and glass bead working; iron",
"burial jars; lingling-o; beads",
"ritual and belief;clothing and adornment;exchange and value",
"Finds from 1909; French archaeologists (Madeleine Colani)",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"Taiwanese nephrite in Sa Huỳnh ornaments shows long-distance exchange.",
"canon_cultures_horizons.csv"
],
[
"ARC158",
"Plain of Jars",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"-500",
"500",
"c. 500 BCE–500 CE (dates debated; some jars placed earlier)",
"Communities in Laos quarried and set over two thousand stone jars used in mortuary ritual.",
"stone quarrying and carving",
"stone jars; discs",
"ritual and belief",
"Madeleine Colani (1935); UNESCO (2019)",
"",
"funerary;conflict-looting",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R3",
"",
"medium",
"Unexploded ordnance from the 1964–73 bombing still at sites (F1.19a).",
"canon_cultures_horizons.csv"
],
[
"ARC159",
"Óc Eo",
"Funan (archaeological)",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"100",
"650",
"c. 1st–7th century CE (Mekong delta)",
"A canal-linked port where makers worked gold, glass beads and tin, trading with India, China and Rome.",
"gold working; glass bead making; canal engineering",
"beads; seals; gold plaques; Roman coins",
"exchange and value;clothing and adornment;transport",
"Louis Malleret (1944)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"medium",
"Links to the Chinese-recorded polity 'Funan'.",
"canon_cultures_horizons.csv"
],
[
"ARC160",
"Dvaravati",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-MSE",
"600",
"1000",
"c. 6th–11th century CE (central Thailand)",
"Mon-speaking Buddhist communities made stucco and terracotta sculpture, dharmachakra wheels and moated towns.",
"stucco; terracotta; stone carving",
"Buddha images; dharmachakras; stucco reliefs",
"ritual and belief",
"Art historians and archaeologists (from coins inscribed 'Dvaravati')",
"",
"sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"Art-historical as much as archaeological grouping.",
"canon_cultures_horizons.csv"
],
[
"ARC161",
"Dapenkeng",
"Tapenkeng",
"archaeological-culture",
"People",
"F1.9;F1.8",
"AS-ISE;AS-CHN",
"-3500",
"-2500",
"c. 3500–2500 BCE (Taiwan)",
"Earliest Neolithic of Taiwan with cord-marked pottery, often linked to the beginnings of Austronesian dispersal.",
"cord-marked pottery; ground stone; bark-cloth beaters",
"pottery; adzes; beaters",
"food and storage;tools;clothing and adornment",
"Kwang-chih Chang (1960s)",
"",
"Indigenous-community",
"open-access excavation reports",
"R3",
"",
"medium",
"Taiwanese Indigenous peoples are living descendants.",
"canon_cultures_horizons.csv"
],
[
"ARC162",
"Beinan",
"Peinan",
"archaeological-culture",
"People",
"F1.9;F1.8",
"AS-ISE",
"-3300",
"-300",
"c. 3300–300 BCE (east Taiwan; main phase c. 1500–800 BCE)",
"A large slate-slab settlement and cemetery with nephrite earrings (including lingling-o and human-animal jades).",
"slate slab construction; nephrite carving",
"slate coffins; jade earrings; pottery",
"ritual and belief;clothing and adornment;shelter",
"Found 1980 during railway construction",
"",
"funerary;Indigenous-community",
"open-access excavation reports;Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC163",
"Toalean",
"",
"archaeological-culture",
"People",
"F1.9",
"AS-ISE",
"-6000",
"500",
"c. 8000–1500 years ago (southwest Sulawesi)",
"Sulawesi foragers made small serrated 'Maros points' and backed microliths.",
"pressure flaking; microliths",
"Maros points; microliths",
"tools",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"",
"medium",
"Stone-tool industry; a Toalean genome published 2021.",
"canon_cultures_horizons.csv"
],
[
"ARC164",
"Arctic Small Tool tradition",
"ASTt; Denbigh Flint Complex (Alaska)",
"archaeological-culture",
"People",
"F1.7;F1.12a",
"AM-ARC;AS-NTH",
"-2500",
"-800",
"c. 2500–800 BCE",
"Palaeo-Inuit (Palaeo-Eskimo) peoples spread from Alaska to Greenland with finely made microblades, burins and bow technology.",
"microblade and burin production; bow and arrow",
"microblades; burins; harpoon heads",
"tools;food and storage",
"William Irving (1957)",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0);National Museum of Denmark (CC BY-SA);open-access excavation reports",
"R3",
"",
"high",
"'Palaeo-Eskimo' is being replaced by 'Palaeo-Inuit' in some usage; check preferred term.",
"canon_cultures_horizons.csv"
],
[
"ARC165",
"Saqqaq",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-ARC",
"-2500",
"-800",
"c. 2500–800 BCE (west Greenland)",
"Early Greenlanders made stone and bone tools and sewn skin clothing; a Saqqaq hair sample gave the first ancient human genome (2010).",
"stone knapping; bone and wood working; skin sewing",
"tools; harpoons; clothing fragments",
"tools;clothing and adornment;food and storage",
"archaeologists",
"",
"Indigenous-community;ancestral",
"National Museum of Denmark (CC BY-SA);open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC166",
"Dorset",
"Tuniit (in Inuit oral history)",
"archaeological-culture",
"People",
"F1.7",
"AM-ARC",
"-500",
"1400",
"c. 500 BCE–1400 CE (dates vary regionally)",
"Dorset carvers made small ivory, antler and wood figures of bears, people and masks.",
"ivory and antler carving; soapstone lamps; snow knife",
"figurines; masks; soapstone lamps",
"ritual and belief;shelter;food and storage",
"Diamond Jenness (1925), after Cape Dorset (Kinngait)",
"",
"Indigenous-community;sacred",
"Smithsonian Open Access (CC0);National Museum of Denmark (CC BY-SA);Wikimedia Commons;open-access excavation reports",
"R2",
"",
"high",
"Inuit oral histories name them Tuniit.",
"canon_cultures_horizons.csv"
],
[
"ARC167",
"Old Bering Sea",
"OBS",
"archaeological-culture",
"People",
"F1.7;F1.12a",
"AM-ARC;AS-NTH",
"-200",
"500",
"c. 200 BCE–500 CE (Bering Strait)",
"Maritime hunters carved walrus-ivory harpoon parts and 'winged objects' with curvilinear engraving.",
"walrus-ivory carving and engraving",
"winged objects; harpoon heads; figures",
"tools;ritual and belief;food and storage",
"Henry B. Collins (1920s–30s)",
"",
"Indigenous-community;funerary;conflict-looting",
"Smithsonian Open Access (CC0);Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"Ivories mined from sites for the market; St Lawrence Island context.",
"canon_cultures_horizons.csv"
],
[
"ARC168",
"Ipiutak",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-ARC",
"1",
"800",
"c. 1st–8th century CE (Point Hope, Alaska)",
"A large settlement and cemetery with elaborate ivory carvings, openwork and inset eyes placed with the dead.",
"ivory carving; openwork; jet and ivory inlay",
"masks; openwork carvings; chains",
"ritual and belief",
"Helge Larsen, Froelich Rainey and Louis Giddings (1939–41)",
"",
"Indigenous-community;funerary;sacred",
"Smithsonian Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC169",
"Thule",
"Thule culture; Neo-Inuit",
"archaeological-culture",
"People",
"F1.7",
"AM-ARC",
"1000",
"1600",
"c. 1000–1600 CE (spread from Alaska to Greenland c. 1200–1300)",
"Ancestors of the Inuit spread across the Arctic with whale-bone houses, umiaks, dog sleds and toggling harpoons.",
"whalebone construction; skin boat building; sled making; ivory carving",
"harpoons; ulus; combs; snow goggles",
"shelter;transport;food and storage;clothing and adornment",
"Therkel Mathiassen (Fifth Thule Expedition, 1920s)",
"",
"Indigenous-community;ancestral;living-community",
"Smithsonian Open Access (CC0);National Museum of Denmark (CC BY-SA);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.26",
"high",
"Living Inuit communities; Inuit-led interpretation preferred.",
"canon_cultures_horizons.csv"
],
[
"ARC170",
"Marpole",
"Marpole phase",
"archaeological-culture",
"People",
"F1.7",
"AM-NWC",
"-500",
"500",
"c. 500 BCE–500 CE (Fraser delta, Salish Sea)",
"Coast Salish ancestral communities carved stone bowls, antler and wood and built plank houses.",
"stone bowl carving; antler carving; plank house construction",
"seated-figure bowls; antler combs; ornaments",
"ritual and belief;shelter;food and storage",
"archaeologists",
"",
"Indigenous-community;ancestral;funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"Marpole village site (c̓əsnaʔəm) is a Musqueam sacred place.",
"canon_cultures_horizons.csv"
],
[
"ARC171",
"Locarno Beach",
"Locarno Beach phase",
"archaeological-culture",
"People",
"F1.7",
"AM-NWC",
"-1500",
"-500",
"c. 1500–500 BCE (Salish Sea)",
"Ancestral Coast Salish communities made ground-slate knives, labrets and carved antler before the Marpole phase.",
"ground-slate working; antler carving; labret making",
"slate knives; labrets; antler carvings",
"tools;clothing and adornment;food and storage",
"Charles Borden (1950s), after Locarno Beach, Vancouver",
"",
"Indigenous-community;ancestral",
"open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC172",
"Clovis",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-WST;AM-EWD;AM-MES",
"-11100",
"-10800",
"c. 13,050–12,750 cal BP",
"Clovis knappers made fluted spear points traded over long distances across North America.",
"fluting; overshot flaking; caching",
"fluted points; bifaces; caches",
"tools;food and storage",
"Named after Clovis, New Mexico (Blackwater Draw, 1930s)",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"Stone-tool tradition; 'Clovis first' has been disproven.",
"canon_cultures_horizons.csv"
],
[
"ARC173",
"Western Stemmed Tradition",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-WST",
"-12000",
"-8000",
"c. 14,000–10,000 BP; some dates as early as 16,000 BP (Cooper's Ferry)",
"Stemmed points in the Great Basin and Plateau, possibly as old as or older than Clovis.",
"stemmed point knapping",
"stemmed points; crescents",
"tools",
"archaeologists",
"",
"Indigenous-community",
"open-access excavation reports",
"R3",
"",
"medium",
"Stone-tool tradition.",
"canon_cultures_horizons.csv"
],
[
"ARC174",
"Hohokam",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-WST",
"450",
"1450",
"c. 450–1450 CE (Sonoran Desert)",
"Hohokam farmers dug hundreds of kilometres of irrigation canals, made red-on-buff pottery, ball courts and acid-etched shell.",
"canal engineering; red-on-buff pottery; shell etching",
"canals; pottery; etched shell; ball courts",
"food and storage;clothing and adornment;play and music",
"Harold Gladwin and Emil Haury (1930s); term from O'odham",
"",
"Indigenous-community;ancestral",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"O'odham peoples are descendants; the name's translation is debated.",
"canon_cultures_horizons.csv"
],
[
"ARC175",
"Mogollon",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-WST",
"200",
"1450",
"c. 200–1450 CE (Arizona, New Mexico, Chihuahua)",
"Mogollon villagers built pit houses and later pueblos and made brown and painted pottery.",
"pit house construction; pottery",
"pottery; houses",
"shelter;food and storage",
"Emil Haury (1936)",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0);open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC176",
"Mimbres",
"Mimbres Mogollon",
"archaeological-culture",
"People",
"F1.7",
"AM-WST",
"1000",
"1130",
"Classic Mimbres c. 1000–1130 CE",
"Mimbres potters painted black-on-white bowls with figures and patterns, many placed over faces in burials with a hole 'killed' through them.",
"painted pottery",
"figurative bowls",
"ritual and belief;food and storage",
"archaeologists",
"",
"Indigenous-community;funerary;conflict-looting",
"Smithsonian Open Access (CC0);open-access excavation reports",
"R2",
"F1.24;F1.18",
"high",
"Bowls largely looted from graves; NAGPRA; display with care.",
"canon_cultures_horizons.csv"
],
[
"ARC177",
"Ancestral Puebloan",
"Anasazi (deprecated); Basketmaker; Pueblo I–IV",
"archaeological-culture",
"People",
"F1.7",
"AM-WST",
"-1500",
"1600",
"Basketmaker II from c. 1500 BCE in some chronologies; Pueblo IV to c. 1600",
"Builders of masonry great houses (Chaco) and cliff dwellings (Mesa Verde) who made coiled baskets, turkey-feather blankets and painted pottery.",
"masonry; coiled basketry; black-on-white pottery; turkey-feather weaving",
"great houses; pottery; baskets; sandals",
"shelter;food and storage;clothing and adornment",
"archaeologists",
"",
"Indigenous-community;ancestral;sacred;funerary;living-community",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R2",
"",
"high",
"Routes from CIV Ancestral Puebloan.",
"canon_cultures_horizons.csv"
],
[
"ARC178",
"Casas Grandes",
"Paquimé",
"archaeological-culture",
"People",
"F1.7",
"AM-WST;AM-MES",
"1200",
"1450",
"c. 1200–1450 CE (Chihuahua)",
"Paquimé bred scarlet macaws, made polychrome effigy pottery and built multi-storey adobe compounds.",
"adobe building; polychrome pottery; macaw breeding",
"effigy jars; macaw pens; shell ornaments",
"shelter;ritual and belief;exchange and value",
"Charles Di Peso (1958–61)",
"",
"Indigenous-community",
"Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC179",
"Maritime Archaic",
"Red Paint People",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD;AM-ARC",
"-7000",
"-1000",
"c. 7000–1000 BCE (Labrador to Maine)",
"Coastal hunters made ground-slate tools and buried their dead with red ochre (Port au Choix).",
"ground slate; red ochre; bone carving",
"slate points; gouges; effigies",
"tools;ritual and belief",
"archaeologists",
"",
"Indigenous-community;funerary",
"Smithsonian Open Access (CC0);open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC180",
"Old Copper complex",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD",
"-4000",
"-1000",
"c. 4000–1000 BCE (earliest perhaps c. 7000 BCE) (western Great Lakes)",
"Among the world's earliest metalworkers, cold-hammering and annealing native copper into tools.",
"cold-hammering; annealing native copper",
"points; awls; knives",
"tools",
"archaeologists",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0);open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC181",
"Poverty Point",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD",
"-1700",
"-1100",
"c. 1700–1100 BCE (Louisiana)",
"Hunter-gatherers built monumental concentric earthen ridges and mounds and made baked clay cooking objects.",
"earthwork; baked clay objects; stone bead making",
"ridges; mounds; clay cooking balls; beads",
"shelter;ritual and belief;food and storage",
"archaeologists",
"",
"Indigenous-community;ancestral",
"Wikimedia Commons;UNESCO World Heritage listing (link out);open-access excavation reports",
"R2",
"F1.5",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC182",
"Adena",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD",
"-800",
"1",
"c. 800 BCE–1 CE (Ohio valley)",
"Adena communities built burial mounds and carved stone tablets and pipes.",
"mound building; stone carving; copper",
"tablets; tubular pipes; mounds",
"ritual and belief",
"After the Adena estate (Chillicothe, Ohio), excavated 1901",
"",
"Indigenous-community;funerary;ancestral",
"Smithsonian Open Access (CC0);open-access excavation reports",
"R3",
"",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC183",
"Hopewell",
"Ohio Hopewell",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD",
"-100",
"500",
"c. 100 BCE–500 CE",
"Hopewell makers built geometric earthworks and made mica cut-outs, copper plates and platform pipes from far-traded materials.",
"earthwork; mica cutting; copper hammering; pipe carving",
"platform pipes; mica hands; copper birds",
"ritual and belief;exchange and value;rule and display",
"Warren K. Moorehead (1891), after Mordecai Hopewell's farm",
"",
"Indigenous-community;funerary;ancestral",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R2",
"",
"high",
"See HOR Hopewell Interaction Sphere; Hopewell Ceremonial Earthworks UNESCO (2023).",
"canon_cultures_horizons.csv"
],
[
"ARC184",
"Mississippian",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-EWD",
"800",
"1600",
"c. 800–1600 CE",
"Towns (Cahokia, Moundville, Etowah) with platform mounds, engraved shell gorgets, copper plates and effigy pottery.",
"earthwork; shell engraving; copper repoussé; shell-tempered pottery",
"gorgets; copper plates; effigy vessels",
"rule and display;ritual and belief;shelter",
"archaeologists",
"",
"Indigenous-community;funerary;sacred;ancestral",
"Smithsonian Open Access (CC0);Wikimedia Commons;open-access excavation reports;UNESCO World Heritage listing (link out)",
"R2",
"",
"high",
"Routes from CIV Mississippian.",
"canon_cultures_horizons.csv"
],
[
"ARC185",
"Olmec",
"Olmec culture",
"archaeological-culture",
"People",
"F1.7",
"AM-MES",
"-1600",
"-400",
"c. 1600–400 BCE (San Lorenzo c. 1400–1000; La Venta c. 1000–400 BCE)",
"Gulf Coast makers carved colossal basalt heads, jade figures and celts, and buried massive serpentine offerings.",
"basalt carving and transport; jade and serpentine working; ceramic figurines",
"colossal heads; altars; jade masks; celts",
"rule and display;ritual and belief",
"Marshall Saville and George Vaillant (1920s); Matthew Stirling (1938–46)",
"",
"Indigenous-community;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Yale University Art Gallery (public-domain images);Wikimedia Commons",
"R2",
"",
"high",
"Routes from CIV Olmec; see HOR Olmec horizon.",
"canon_cultures_horizons.csv"
],
[
"ARC186",
"Tlatilco",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-MES",
"-1250",
"-800",
"c. 1250–800 BCE (Basin of Mexico)",
"A village cemetery with hundreds of burials holding hand-modelled 'pretty lady' figurines and Olmec-style vessels.",
"hand-modelled figurines; pottery",
"figurines; masks; vessels",
"ritual and belief;clothing and adornment",
"Found by brickmakers (1936); Miguel Covarrubias",
"",
"funerary;Indigenous-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC187",
"Monte Albán (Zapotec)",
"Monte Albán I–V",
"archaeological-culture",
"People",
"F1.7",
"AM-MES",
"-500",
"800",
"c. 500 BCE–800 CE (Valley of Oaxaca)",
"The Zapotec hilltop capital with carved 'Danzantes' slabs, painted tombs and ceramic effigy urns.",
"stone relief carving; tomb painting; ceramic urn modelling",
"Danzantes; effigy urns; tombs",
"rule and display;ritual and belief;record and writing",
"Alfonso Caso (1931 on)",
"",
"Indigenous-community;funerary",
"Met Open Access (CC0);Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"high",
"Routes from CIV Zapotec; Tomb 7's goldwork is later Mixtec reuse.",
"canon_cultures_horizons.csv"
],
[
"ARC188",
"West Mexican shaft tomb tradition",
"Teuchitlán tradition",
"archaeological-culture",
"People",
"F1.7",
"AM-MES",
"-300",
"400",
"c. 300 BCE–400 CE (Jalisco, Nayarit, Colima)",
"Hollow ceramic figures of people, dogs and village scenes were placed in deep shaft-and-chamber tombs.",
"hollow ceramic modelling; burnished slip",
"figures; dogs; house models",
"ritual and belief;clothing and adornment",
"archaeologists",
"",
"funerary;conflict-looting;Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);LACMA (public-domain images);Wikimedia Commons",
"R2",
"F1.24",
"high",
"Almost all known from looted tombs; many fakes. F1.24 case.",
"canon_cultures_horizons.csv"
],
[
"ARC189",
"Classic Veracruz",
"",
"archaeological-culture",
"People",
"F1.7",
"AM-MES",
"100",
"1000",
"c. 100–1000 CE (Gulf Coast; El Tajín)",
"Gulf Coast makers carved stone ballgame yokes, hachas and palmas and made smiling-face ceramic figures.",
"stone carving; ceramic modelling",
"yokes; hachas; palmas; smiling figures",
"play and music;ritual and belief",
"archaeologists",
"",
"Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_cultures_horizons.csv"
],
[
"ARC190",
"Gran Coclé",
"Coclé; Sitio Conte",
"archaeological-culture",
"People",
"F1.7",
"AM-CAM",
"200",
"1500",
"c. 200–1500 CE; Sitio Conte burials c. 700–1000",
"Panamanian makers produced polychrome pottery and cast and hammered gold, found in chiefly burials.",
"polychrome pottery; lost-wax gold casting; depletion gilding",
"polychrome plates; gold plaques; ear rods",
"rule and display;ritual and belief;clothing and adornment",
"Samuel Lothrop (Harvard, 1930s); Penn Museum",
"",
"funerary;Indigenous-community",
"Penn Museum online collection (link out);Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_cultures_horizons.csv"
],
[
"ARC191",
"Diquís",
"Diquís stone spheres",
"archaeological-culture",
"People",
"F1.7",
"AM-CAM",
"300",
"1500",
"c. 300–1500 CE (southern Costa Rica)",
"Communities carved hundreds of near-perfect stone spheres and cast gold ornaments.",
"stone sphere shaping; gold casting",
"spheres; gold pendants",
"ritual and belief;rule and display",
"archaeologists",
"",
"Indigenous-community",
"Wikimedia Commons;UNESCO World Heritage listing (link out)",
"R3",
"",
"medium",
"UNESCO (2014).",
"canon_cultures_horizons.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
