insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"DYN045",
"Chandela dynasty",
"Chandelas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"831",
"1315",
"c.",
"The Chandelas built the sandstone temples of Khajuraho with dense figural sculpture around 950–1050.",
"sandstone carving",
"temples; sculptures",
"rule and display;ritual and belief",
"historians",
"sculptors' guilds; colonial prudishness in interpretation",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN046",
"Chaulukya (Solanki) dynasty",
"Solankis of Gujarat",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"940",
"1244",
"",
"The Solanki court built the Modhera Sun Temple (1026) and Queen Udayamati's stepwell Rani ki Vav.",
"sandstone carving; stepwell building",
"Modhera; Rani ki Vav",
"rule and display;ritual and belief;food and storage",
"historians",
"Jain merchant patrons; Somnath raid",
"sacred",
"Wikimedia Commons",
"R2",
"",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN047",
"Hoysala dynasty",
"Hoysalas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1000",
"1346",
"c.",
"Hoysala temples at Belur, Halebidu and Somanathapura were carved in soapstone by sculptors who signed their work.",
"chloritic schist carving",
"temples; bracket figures",
"rule and display;ritual and belief",
"historians; signed sculptors' inscriptions",
"women dancers depicted; Delhi Sultanate sack",
"sacred",
"Wikimedia Commons",
"R1",
"F1.26;F1.23",
"high",
"Signed works (e.g. Mallitamma) make Hoysala a case for F1.26.",
"canon_dynasties.csv"
],
[
"DYN048",
"Eastern Ganga dynasty",
"Eastern Gangas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1078",
"1434",
"",
"Eastern Ganga kings built the Jagannath temple at Puri and the Konark Sun Temple (c. 1250).",
"sandstone and chlorite carving",
"Konark; Puri",
"rule and display;ritual and belief",
"historians",
"temple workers; Odia present communities",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN049",
"Kakatiya dynasty",
"Kakatiyas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1163",
"1323",
"c.",
"The Kakatiyas built the Warangal gateways and the Ramappa temple (1213) with lightweight bricks.",
"stone carving; floating bricks",
"Ramappa; Warangal gateways",
"rule and display;ritual and belief",
"historians",
"the Koh-i-Noor's claimed origin",
"sacred",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN050",
"Sena dynasty",
"Senas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1070",
"1230",
"c.",
"The Senas continued Bengal's black-stone sculpture for Hindu cults after the Palas.",
"black stone carving",
"images",
"ritual and belief;rule and display",
"historians",
"Buddhist institutions in decline",
"sacred",
"Wikimedia Commons;Met Open Access (CC0)",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN051",
"Khalji dynasty",
"Khaljis",
"dynasty",
"People",
"F1.10;F1.9",
"AS-SAS",
"1290",
"1320",
"",
"Alauddin Khalji built the Alai Darwaza (1311) with true arches and red sandstone and marble inlay.",
"red sandstone; marble inlay",
"Alai Darwaza",
"rule and display;ritual and belief",
"historians",
"raided southern kingdoms; Mongol captives",
"none",
"Wikimedia Commons",
"R3",
"",
"high",
"Link: Delhi Sultanate (POL).",
"canon_dynasties.csv"
],
[
"DYN052",
"Tughluq dynasty",
"Tughlaqs",
"dynasty",
"People",
"F1.10;F1.9",
"AS-SAS",
"1320",
"1414",
"",
"Firoz Shah Tughluq moved Ashokan pillars to Delhi and his predecessors built the sloping walls of Tughlaqabad.",
"rubble masonry; transport of monoliths",
"Tughlaqabad; relocated pillars",
"rule and display;ritual and belief",
"historians",
"populations moved to Daulatabad; enslaved labour",
"none",
"Wikimedia Commons",
"R2",
"F1.14;F1.24",
"high",
"Pillar relocation is a reuse case.",
"canon_dynasties.csv"
],
[
"DYN053",
"Adil Shahi dynasty",
"Adil Shahis of Bijapur",
"dynasty",
"People",
"F1.10;F1.9",
"AS-SAS",
"1490",
"1686",
"",
"The Adil Shahis built the Gol Gumbaz and Ibrahim II patronised a distinctive Bijapur painting.",
"dome construction; painting",
"Gol Gumbaz; paintings",
"rule and display;ritual and belief",
"historians",
"Habshi (African) nobles and soldiers; Mughal conquest",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN054",
"Qutb Shahi dynasty",
"Qutb Shahis of Golconda",
"dynasty",
"People",
"F1.10;F1.9",
"AS-SAS",
"1518",
"1687",
"",
"The Qutb Shahis built the Charminar (1591) and ruled the diamond and painted-cotton trade of Masulipatnam.",
"diamond cutting; kalamkari",
"Charminar; chintz",
"rule and display;exchange and value",
"historians",
"diamond miners; weavers",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN055",
"Nayaka dynasty of Madurai",
"Madurai Nayakas",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1529",
"1736",
"",
"The Madurai Nayakas enlarged the Meenakshi temple with towering gopurams and pillared halls.",
"granite; painted stucco",
"gopurams; halls",
"rule and display;ritual and belief",
"historians",
"temple servants; Tamil Muslim traders",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN056",
"Wodeyar dynasty",
"Wadiyars of Mysore",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1399",
"1950",
"traditional start",
"The Wodeyars patronised Mysore painting and the Dasara festival and built the Mysore Palace (1912).",
"gesso painting; palace building",
"paintings; palace",
"rule and display;ritual and belief",
"historians",
"artisans of palace workshops",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"Link: Kingdom of Mysore (POL).",
"canon_dynasties.csv"
],
[
"DYN057",
"Sisodia dynasty of Mewar",
"Sisodias; Maharanas of Udaipur",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1326",
"1947",
"c.",
"The Sisodias kept a court painting workshop at Udaipur producing large festival paintings.",
"opaque watercolour painting",
"paintings; palaces",
"rule and display;ritual and belief",
"historians",
"named and unnamed court painters; Bhil communities",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN058",
"Kachhwaha dynasty",
"Kachhwahas of Amber and Jaipur",
"dynasty",
"People",
"F1.9",
"AS-SAS",
"1128",
"1949",
"c.",
"Jai Singh II founded Jaipur (1727) with astronomical instruments (Jantar Mantar) and a painting workshop.",
"masonry instruments; painting",
"Jantar Mantar; Jaipur",
"rule and display;tools",
"historians",
"artisan communities settled by caste-based quarters in Jaipur; Mina communities displaced from Amber",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN059",
"Malla dynasty (Nepal)",
"Mallas of Kathmandu Valley",
"dynasty",
"People",
"F1.9",
"AS-HIM",
"1200",
"1769",
"",
"The Malla kings of Kathmandu, Patan and Bhaktapur commissioned Newar copper casting, woodcarving and Durbar Square temples.",
"lost-wax copper casting; woodcarving; brick",
"temples; images; struts",
"rule and display;ritual and belief",
"historians",
"Newar artisan castes (Shakya, Tamrakar); Gorkha conquest",
"sacred",
"Met Open Access (CC0);Himalayan Art Resources (link out);Wikimedia Commons",
"R2",
"F1.16;F1.23",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN060",
"Namgyal dynasty (Ladakh)",
"Namgyals",
"dynasty",
"People",
"F1.9",
"AS-HIM",
"1460",
"1842",
"c.",
"The Namgyal kings built Leh Palace and supported Hemis monastery.",
"mud-brick; painting",
"palace; monasteries",
"rule and display;ritual and belief",
"historians",
"Balti and Muslim neighbours",
"sacred",
"Wikimedia Commons;Himalayan Art Resources (link out)",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN061",
"Sailendra dynasty",
"Shailendras",
"dynasty",
"People",
"F1.9",
"AS-ISE",
"750",
"850",
"c.",
"The Sailendra kings sponsored Borobudur in Central Java, the largest Buddhist monument, carved with 2,672 relief panels.",
"andesite carving",
"Borobudur",
"ritual and belief;rule and display",
"historians",
"corvée labourers and carvers; the Sanjaya line and Hindu contemporaries; heads removed from Borobudur Buddhas for collections",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"Link: Mataram (POL).",
"canon_dynasties.csv"
],
[
"DYN062",
"Trần dynasty",
"Tran",
"dynasty",
"People",
"F1.8;F1.9",
"AS-MSE",
"1225",
"1400",
"",
"The Trần court repelled Mongol invasions and patronised the Trúc Lâm Zen school and ceramics.",
"stoneware; woodcarving",
"ceramics; temples",
"rule and display;ritual and belief",
"historians",
"Cham neighbours",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"Link: Đại Việt (POL).",
"canon_dynasties.csv"
],
[
"DYN063",
"Later Lê dynasty",
"Lê",
"dynasty",
"People",
"F1.8;F1.9",
"AS-MSE",
"1428",
"1789",
"",
"The Lê period saw Chu Đậu blue-and-white exports and doctoral stelae at the Temple of Literature.",
"stoneware; stone stelae",
"ceramics; stelae",
"rule and display;record and writing",
"historians",
"Cham; Mạc usurpers",
"none",
"Wikimedia Commons",
"R3",
"F1.28",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN064",
"Nguyễn dynasty",
"Nguyen",
"dynasty",
"People",
"F1.8;F1.9",
"AS-MSE",
"1802",
"1945",
"",
"The Nguyễn built the Huế citadel and tombs and ordered \"Bleu de Huế\" porcelain from China.",
"masonry; porcelain orders; lacquer",
"citadel; tombs",
"rule and display;ritual and belief",
"historians",
"French protectorate after 1883",
"funerary",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN065",
"Konbaung dynasty",
"Alaungpaya dynasty",
"dynasty",
"People",
"F1.9",
"AS-MSE",
"1752",
"1885",
"",
"The Konbaung court built Mandalay and its regalia was taken by Britain in 1885.",
"silverwork; kalaga embroidery; lacquer",
"regalia; silver",
"rule and display",
"historians",
"regalia partly returned 1964",
"conflict-looting",
"Wikimedia Commons;V&A collections search (link out)",
"R2",
"F1.24",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN066",
"Chakri dynasty",
"Rattanakosin",
"dynasty",
"People",
"F1.9",
"AS-MSE",
"1782",
"",
"continues",
"The Chakri kings built Bangkok's Grand Palace and dress the Emerald Buddha seasonally.",
"gilding; mother-of-pearl inlay",
"Grand Palace; costumes",
"rule and display;ritual and belief",
"historians",
"Lao and Khmer war captives settled as labour; the Emerald Buddha taken from Vientiane in 1779; artisans of the royal craft departments",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN067",
"Imperial house of Japan",
"Yamato dynasty; Kōshitsu",
"dynasty",
"People",
"F1.8",
"AS-JPN",
"550",
"",
"c.; historically attested from about the 6th century; continues",
"The imperial house's Shōsōin repository has preserved 8th-century objects since 756, and from 1890 the Imperial Household named master craftspeople as Imperial Household Artists.",
"repository conservation; lacquer; textiles; metalwork",
"Shōsōin treasures; commissioned crafts",
"rule and display;ritual and belief",
"historians; Imperial Household Agency",
"restricted access to imperial tombs (kofun) for archaeology; commoner makers",
"sacred;funerary",
"ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R2",
"F1.17;F1.24",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN068",
"Fujiwara regents",
"Fujiwara Hokke; sekkan regents",
"dynasty",
"People",
"F1.8",
"AS-JPN",
"858",
"1068",
"c.; regency peak",
"Fujiwara no Yorimichi built the Byōdōin Phoenix Hall (1053) and commissioned the sculptor Jōchō's joined-wood Amida.",
"joined-wood sculpture (yosegi-zukuri); lacquer; gold leaf",
"Byōdōin; Amida image",
"rule and display;ritual and belief",
"historians; court diaries",
"estate cultivators who funded the court; Jōchō's workshop assistants",
"sacred",
"ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R2",
"",
"high",
"Link: Heian court (POL).",
"canon_dynasties.csv"
],
[
"DYN069",
"Ashikaga shoguns",
"Ashikaga",
"dynasty",
"People",
"F1.8",
"AS-JPN",
"1336",
"1573",
"",
"The Ashikaga shoguns built Kinkaku-ji and Ginkaku-ji and ranked imported Chinese objects (karamono) with the help of connoisseurs such as Nōami.",
"ink painting; lacquer; tea wares",
"pavilions; scrolls; tea bowls",
"rule and display;ritual and belief",
"historians; the Kundaikan sōchōki connoisseurship manual",
"dōbōshū attendants (often of low status) who shaped taste; Chinese and Korean makers",
"none",
"ColBase Japan (Japan Government Standard Terms);Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.15;F1.17",
"high",
"Link: Muromachi shogunate (POL).",
"canon_dynasties.csv"
],
[
"DYN070",
"Toyotomi",
"Toyotomi Hideyoshi and heir",
"dynasty",
"People",
"F1.8",
"AS-JPN;AS-KOR",
"1585",
"1615",
"",
"Hideyoshi built a portable golden tea room and his invasions of Korea (1592–98) took Korean potters to Japan, founding new kilns.",
"gold leaf; tea ceramics",
"golden tea room; Osaka castle",
"rule and display;war;ritual and belief",
"historians",
"abducted Korean potters; Korean casualties; tea master Sen no Rikyū (ordered to die 1591)",
"conflict-looting",
"ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R2",
"F1.19a;F1.23",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN071",
"Tokugawa shoguns",
"Tokugawa",
"dynasty",
"People",
"F1.8",
"AS-JPN",
"1603",
"1868",
"",
"The Tokugawa shoguns built the Nikkō Tōshōgū mausoleum and retained Kanō-school painters as official artists, setting a court taste copied by daimyo.",
"lacquer; polychrome carving; painting on screens",
"Tōshōgū; screens; lacquer trousseaux",
"rule and display;ritual and belief",
"historians",
"carpenters, carvers and painters; daimyo made to fund construction; townspeople's own art market (ukiyo-e)",
"sacred",
"ColBase Japan (Japan Government Standard Terms);Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.17",
"high",
"Link: Tokugawa Japan (POL).",
"canon_dynasties.csv"
],
[
"DYN072",
"Maeda clan of Kaga",
"Kaga domain",
"dynasty",
"People",
"F1.8",
"AS-JPN",
"1583",
"1871",
"c.",
"The Maeda lords of Kaga ran a domain craft workshop (saikusho) and fostered Kaga maki-e, Kutani porcelain and dyeing.",
"maki-e lacquer; porcelain; yūzen dyeing",
"lacquer; Kutani ware",
"rule and display;exchange and value",
"historians",
"domain artisans and commoner workshops; later Kutani revival makers",
"living-community",
"ColBase Japan (Japan Government Standard Terms);Wikimedia Commons",
"R3",
"F1.17;F1.29",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN073",
"Nabeshima clan of Saga",
"Saga domain",
"dynasty",
"People",
"F1.8",
"AS-JPN;AS-KOR",
"1607",
"1871",
"c.",
"The Nabeshima brought Korean potters after the 1590s invasions, whose discovery of porcelain clay near Arita began Japanese porcelain, and ran the Ōkawachi kilns for Nabeshima ware.",
"porcelain; overglaze enamel",
"Arita; Nabeshima ware",
"rule and display;exchange and value",
"historians",
"Korean potters (e.g. Yi Sam-pyeong/Ri Sanpei)",
"none",
"ColBase Japan (Japan Government Standard Terms);Rijksmuseum (CC0);Met Open Access (CC0)",
"R1",
"F1.14;F1.23;F1.13",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN074",
"Chinggisid lineage",
"Borjigin; Golden Lineage",
"dynasty",
"People",
"F1.12a;F1.13",
"AS-CEN;AS-CHN;WA-IRN;EU-EER;AS-NTH",
"1206",
"1847",
"c.; last Chinggisid khans in the Kazakh steppe",
"Descent from Chinggis Khan legitimised khans from the Yuan and Ilkhanate to Crimea and the Kazakh hordes, and so shaped who could commission court art for six centuries.",
"cloth-of-gold; paiza; seals",
"seals; robes",
"rule and display",
"historians",
"non-Chinggisid rulers who had to rule through puppet khans (Timur)",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"",
"medium",
"Links: Mongol Empire, Yuan, Ilkhanate (POL).",
"canon_dynasties.csv"
],
[
"DYN075",
"Shaybanid dynasty",
"Abulkhairids",
"dynasty",
"People",
"F1.10;F1.12a",
"AS-CEN",
"1500",
"1599",
"",
"The Shaybanids ruled Bukhara and Samarkand, patronising madrasas and a Bukhara school of manuscript painting.",
"tile mosaic; manuscript painting",
"Mir-i Arab madrasa; manuscripts",
"rule and display;ritual and belief",
"historians",
"Herat painters taken to Bukhara; Persian captives",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN076",
"Julio-Claudian dynasty",
"Julio-Claudians",
"dynasty",
"People",
"F1.11",
"EU-GRR;EU-WCE;AF-EGY;WA-LEV",
"-27",
"68",
"",
"Augustus and his successors fixed an official classicising style in the Ara Pacis, standard portrait types copied across the empire, and court cameos such as the Gemma Augustea.",
"marble relief; portrait copying; cameo cutting; cast glass",
"Ara Pacis; portrait busts; cameos",
"rule and display;ritual and belief",
"historians; Suetonius and Tacitus",
"enslaved and freed workshop labour; provincial copyists; conquered Egypt's treasury",
"none",
"Met Open Access (CC0);Getty Museum Open Content (public-domain images);Wikimedia Commons",
"R2",
"F1.14",
"high",
"Link: Rome (POL).",
"canon_dynasties.csv"
],
[
"DYN077",
"Macedonian dynasty (Byzantine)",
"Macedonians",
"dynasty",
"People",
"F1.11",
"EU-BYZ;WA-ANA",
"867",
"1056",
"",
"Macedonian emperors presided over a revival of classical models in manuscripts such as the Paris Psalter and in carved ivory triptychs and caskets.",
"ivory carving; manuscript illumination; cloisonné enamel",
"Paris Psalter; ivory triptychs; enamels",
"rule and display;ritual and belief",
"historians; the term \"Macedonian Renaissance\" is modern",
"Bulgarians conquered by Basil II; imperial silk workers",
"sacred",
"Met Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN078",
"Palaiologan dynasty",
"Palaiologoi",
"dynasty",
"People",
"F1.11",
"EU-BYZ;WA-ANA",
"1259",
"1453",
"",
"Under the Palaiologoi the statesman Theodore Metochites funded the Chora church mosaics and frescoes (1315–21), and micro-mosaic icons were made in Constantinople.",
"mosaic; fresco; micromosaic icons",
"Chora; Mystras churches; icons",
"ritual and belief;rule and display",
"historians",
"a shrinking empire's peasants; Latin and Ottoman neighbours",
"sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN079",
"Merovingian dynasty",
"Merovingians",
"dynasty",
"People",
"F1.11",
"EU-WCE",
"481",
"751",
"c.",
"Merovingian rulers wore gold and garnet cloisonné, like the bees from Childeric's grave, found in 1653 and mostly stolen from Paris in 1831.",
"garnet cloisonné; gold",
"fibulae; buckles; bees",
"rule and display;clothing and adornment",
"historians; Gregory of Tours",
"Gallo-Roman makers; the stolen grave goods",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.24",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN080",
"Ottonian dynasty",
"Ottonians; Liudolfings",
"dynasty",
"People",
"F1.11",
"EU-WCE",
"919",
"1024",
"",
"Ottonian emperors and bishops commissioned illuminated manuscripts at Reichenau and cast bronze doors such as Bernward's at Hildesheim (1015).",
"bronze casting; manuscript illumination; goldsmithing",
"Hildesheim doors; gospel books; crosses",
"ritual and belief;rule and display",
"historians",
"monastic scribes and painters; Slavic peoples east of the Elbe",
"sacred",
"Wikimedia Commons;Europeana",
"R2",
"",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN081",
"Hohenstaufen dynasty",
"Staufer",
"dynasty",
"People",
"F1.11",
"EU-WCE;EU-GRR",
"1138",
"1254",
"",
"Frederick II built Castel del Monte, struck gold augustales in a Roman manner and wrote a treatise on falconry.",
"gold coinage; castle building; manuscript illustration",
"augustales; castles; falconry treatise",
"rule and display;tools",
"historians",
"Muslims deported to Lucera; Italian communes",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN082",
"Hauteville dynasty",
"Norman kings of Sicily",
"dynasty",
"People",
"F1.11;F1.10",
"EU-GRR;AF-MAG",
"1072",
"1194",
"Norman siege of Palermo 1071, city taken January 1072; kingdom from 1130",
"Roger II's Palermo combined Byzantine mosaics, a painted muqarnas ceiling in the Fatimid manner and a silk coronation mantle with an Arabic inscription (1133–34).",
"mosaic; painted muqarnas; silk and pearl embroidery",
"Cappella Palatina; coronation mantle",
"rule and display;ritual and belief;clothing and adornment",
"historians",
"Muslim and Greek makers who were later expelled or assimilated",
"none",
"Wikimedia Commons",
"R1",
"F1.13;F1.14",
"high",
"Mantle now in Vienna (imperial treasury).",
"canon_dynasties.csv"
],
[
"DYN083",
"Capetian dynasty",
"Capetians (direct line)",
"dynasty",
"People",
"F1.11",
"EU-WCE",
"987",
"1328",
"",
"Louis IX built the Sainte-Chapelle for relics, and Paris craft statutes were compiled in Étienne Boileau's Livre des métiers (c. 1268).",
"stained glass; goldsmithing; guild statutes",
"Sainte-Chapelle; reliquaries; statutes",
"rule and display;ritual and belief;record and writing",
"historians",
"Jews expelled 1306; women in trades (some guilds were women's)",
"sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.17;F1.28",
"high",
"Link: Kingdom of France (POL).",
"canon_dynasties.csv"
],
[
"DYN084",
"Valois dynasty",
"Valois",
"dynasty",
"People",
"F1.11",
"EU-WCE",
"1328",
"1589",
"",
"Valois kings and princes commissioned books of hours such as the Très Riches Heures and Francis I's Fontainebleau with Italian artists.",
"manuscript illumination; painted enamel; stucco",
"books of hours; Fontainebleau; enamels",
"rule and display;ritual and belief",
"historians",
"Huguenot artisans; peasant costs of war",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"",
"high",
"Valois-Burgundy is under Burgundian State (POL).",
"canon_dynasties.csv"
],
[
"DYN085",
"Bourbon dynasty",
"Bourbons",
"dynasty",
"People",
"F1.11",
"EU-WCE;EU-IBE;EU-GRR",
"1589",
"1830",
"France 1589–1792 and 1814–30; branches in Spain and Naples",
"Louis XIV's Versailles was furnished by the Gobelins manufactory, and Louis XV made Sèvres a royal porcelain works.",
"tapestry; soft-paste porcelain; marquetry",
"Versailles furnishings; Sèvres; tapestries",
"rule and display",
"historians",
"enslaved people in French colonies; workers at royal manufactures",
"human-flow",
"Met Open Access (CC0);Getty Museum Open Content (public-domain images);Wikimedia Commons",
"R2",
"F1.17",
"high",
"Link: Kingdom of France (POL).",
"canon_dynasties.csv"
],
[
"DYN086",
"Tudor dynasty",
"Tudors",
"dynasty",
"People",
"F1.11",
"EU-BLC",
"1485",
"1603",
"",
"Henry VIII's Dissolution of the Monasteries (1536–41) destroyed and dispersed religious art while Holbein painted the court.",
"portrait painting; tapestry; goldsmithing",
"portraits; tapestries",
"rule and display;ritual and belief",
"historians",
"monastic makers and communities; Catholic and Irish subjects",
"sacred",
"Wikimedia Commons;National Gallery of Art Washington (CC0)",
"R1",
"F1.16;F1.24",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN087",
"Habsburg dynasty",
"House of Habsburg",
"dynasty",
"People",
"F1.11;F1.13",
"EU-WCE;EU-IBE;AM-LAT",
"1273",
"1918",
"",
"Habsburg Kunstkammern such as Ambras and Rudolf II's Prague collected objects from across the empire, including the feather headdress in Vienna associated with Moctezuma.",
"Kunstkammer collecting; tapestry; armour",
"Kunstkammer objects; featherwork; armour",
"rule and display",
"historians",
"colonised peoples whose objects were collected; Mexico's request for the headdress",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R1",
"F1.24",
"high",
"Link: Spanish Empire (POL).",
"canon_dynasties.csv"
],
[
"DYN088",
"Medici",
"House of Medici",
"dynasty",
"People",
"F1.11",
"EU-GRR",
"1434",
"1737",
"as patrons from Cosimo il Vecchio; grand dukes from 1569",
"The Medici commissioned art, founded a pietre dure workshop (1588) and, through Anna Maria Luisa's 1737 Family Pact, kept their collections in Florence.",
"pietre dure; bronze casting; painting; early porcelain",
"collections; pietre dure tables; Medici porcelain",
"rule and display;exchange and value",
"historians; Vasari",
"artisans and guild workers; women patrons",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R1",
"F1.17;F1.24",
"high",
"Link: Republic of Florence (POL).",
"canon_dynasties.csv"
],
[
"DYN089",
"Gonzaga",
"House of Gonzaga",
"dynasty",
"People",
"F1.11",
"EU-GRR",
"1328",
"1708",
"",
"The Gonzaga of Mantua commissioned Mantegna's Camera degli Sposi and sold much of their collection to Charles I of England in 1627–28.",
"fresco; collecting",
"Camera degli Sposi; collection",
"rule and display",
"historians",
"Isabella d'Este's role as patron",
"none",
"Wikimedia Commons",
"R3",
"F1.24",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN090",
"Wettin dynasty (Albertine Saxony)",
"Wettins",
"dynasty",
"People",
"F1.11",
"EU-WCE",
"1485",
"1918",
"",
"Augustus the Strong founded Meissen, Europe's first hard-paste porcelain works (1710), and the Green Vault treasury.",
"hard-paste porcelain; goldsmithing",
"Meissen; Green Vault objects",
"rule and display;exchange and value",
"historians",
"Böttger and Tschirnhaus's workers; Chinese and Japanese models copied",
"none",
"Rijksmuseum (CC0);Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN091",
"Romanov dynasty",
"Romanovs",
"dynasty",
"People",
"F1.11",
"EU-EER;AS-NTH",
"1613",
"1917",
"",
"The Romanovs patronised the Imperial Porcelain Factory (1744) and ordered Fabergé eggs as Easter gifts.",
"porcelain; guilloché enamel; goldsmithing",
"Fabergé eggs; porcelain",
"rule and display;ritual and belief",
"historians",
"serfs; Siberian fur tributaries",
"none",
"Wikimedia Commons",
"R2",
"",
"high",
"Link: Russian Empire (POL).",
"canon_dynasties.csv"
],
[
"DYN092",
"Jagiellonian dynasty",
"Jagiellons",
"dynasty",
"People",
"F1.11",
"EU-EER;EU-WCE",
"1386",
"1572",
"",
"Sigismund II Augustus commissioned Flemish tapestries for Wawel, which were evacuated in 1939 and returned from Canada in 1961.",
"tapestry",
"Wawel tapestries; Sigismund Chapel",
"rule and display",
"historians",
"Flemish weavers; Lithuanian and Ruthenian subjects",
"none",
"Wikimedia Commons",
"R2",
"F1.19a",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN093",
"Nemanjić dynasty",
"Nemanjići",
"dynasty",
"People",
"F1.11",
"EU-BYZ",
"1166",
"1371",
"",
"The Nemanjić rulers founded monasteries with frescoes such as Studenica, Mileševa and Sopoćani.",
"fresco; stone building",
"monasteries; frescoes",
"ritual and belief;rule and display",
"historians",
"peasants; Greek painters employed",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_dynasties.csv"
],
[
"DYN094",
"Hohenzollern dynasty",
"Hohenzollerns",
"dynasty",
"People",
"F1.11",
"EU-WCE;EU-EER",
"1415",
"1918",
"",
"Frederick II made the Berlin porcelain works royal (KPM, 1763), and Prussia's 1813 \"gold for iron\" campaign swapped jewellery for cast-iron pieces.",
"porcelain; cast-iron jewellery",
"KPM porcelain; iron jewellery",
"rule and display;clothing and adornment",
"historians",
"Polish subjects; industrial workers",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_dynasties.csv"
],
[
"DYN095",
"Kalākaua dynasty",
"Hale o Kalākaua",
"dynasty",
"People",
"F1.12",
"OC-POL",
"1874",
"1893",
"Kalākaua r. 1874–91; Liliʻuokalani 1891–93",
"King Kalākaua revived hula at court, had the Kumulipo chant published and built ʻIolani Palace before the 1893 overthrow.",
"featherwork; building; printing",
"ʻIolani Palace; regalia; chants",
"rule and display;play and music;ritual and belief",
"historians; Hawaiian sources",
"Native Hawaiian commoners; US annexation",
"Indigenous-community;sacred",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R2",
"F1.29",
"medium",
"Link: Hawaiian Kingdom (POL).",
"canon_dynasties.csv"
],
[
"DYN096",
"Inca royal lineages (panaqa)",
"panaka; royal ayllu",
"dynasty",
"People",
"F1.7",
"AM-AND",
"1400",
"1572",
"c.; to the fall of Vilcabamba",
"Each Inca ruler's descendants formed a panaqa that kept his preserved body, estates and fine cloth, so dynastic memory was held in objects and khipu rather than written chronicles.",
"cumbi cloth; khipu; gold and silver images",
"royal estates; textiles; khipu",
"rule and display;ritual and belief;record and writing",
"colonial chroniclers (Betanzos, Sarmiento); historians",
"non-royal ayllus; the preserved bodies destroyed or hidden by Spanish officials",
"funerary;sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16;F1.28",
"medium",
"Link: Inca (Tawantinsuyu) (POL).",
"canon_dynasties.csv"
],
[
"DYN097",
"Tilantongo royal lineage",
"Mixtec dynasty of Tilantongo; lineage of Lord Eight Deer Jaguar Claw",
"dynasty",
"People",
"F1.7",
"AM-MES",
"940",
"1520",
"c.; genealogies in the codices begin in the 10th century",
"Mixtec painters recorded the Tilantongo rulers' genealogies, marriages and conquests in screenfold codices such as the Zouche-Nuttall.",
"deerskin screenfold painting; gesso and mineral pigments",
"codices; genealogies",
"rule and display;record and writing",
"the codices themselves; scholars (Caso; Jansen and Pérez Jiménez)",
"commoners and allied ñuu; present Ñuu Savi communities who read the codices today",
"living-community",
"Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.26;F1.28",
"medium",
"Link: Mixtec kingdoms (POL).",
"canon_dynasties.csv"
],
[
"OCC001",
"Fall of Ur (c. 2004 BCE)",
"Elamite sack of Ur; Lament for Ur",
"event",
"Time",
"F1.9a",
"WA-MES;WA-IRN",
"-2004",
"-2004",
"approx.; Middle Chronology",
"Elamite and Shimashki forces sacked Ur and ended the Ur III state and its large textile and craft workshops, an event mourned in the Sumerian city laments.",
"weaving;temple building",
"tablet;temple",
"war;ritual and belief",
"Assyriologists (Lament for Ur, ETCSL)",
"the dependent workers of the Ur III workshops",
"conflict-looting",
"Cuneiform Digital Library Initiative (link-out); public-domain primary texts",
"R3",
"F1.19a;F1.28",
"high",
"links: POL094; INS092; PRD034.",
"canon_events.csv"
],
[
"OCC002",
"Thera eruption (c. 1600 BCE)",
"Minoan eruption of Santorini",
"event",
"Time",
"F1.11",
"EU-GRR",
"-1620",
"-1600",
"date debated: radiocarbon c. 1600 BCE vs archaeological c. 1500 BCE",
"The eruption buried the town of Akrotiri on Thera in ash, preserving painted walls, storage jars and multi-storey houses.",
"fresco;pottery;building",
"wall painting;storage jar",
"shelter;food and storage",
"volcanologists; Aegean archaeologists",
"the people who left before the eruption, whose fate is unknown",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.28;F1.22",
"medium",
"links: CIV074; POL115. Link to Minoan decline is debated.",
"canon_events.csv"
],
[
"OCC003",
"Uluburun shipwreck (c. 1320 BCE)",
"Uluburun wreck",
"event",
"Time",
"F1.9a;F1.13",
"WA-ANA;WA-LEV;EU-GRR",
"-1320",
"-1300",
"approx.; excavated 1984–1994",
"A ship that sank off southern Anatolia carried copper and tin ingots, glass ingots, ivory, ebony and jewellery, a snapshot of Late Bronze Age trade in raw materials.",
"copper and tin ingots;glass ingots;ivory",
"oxhide ingot;glass ingot;jewellery",
"exchange and value;transport",
"nautical archaeologists (Institute of Nautical Archaeology)",
"the crew, whose origin is still debated",
"none",
"open-access excavation reports; Wikimedia Commons",
"R2",
"F1.13;F1.22",
"high",
"links: NET020; NET026; INV026.",
"canon_events.csv"
],
[
"OCC004",
"Late Bronze Age collapse (c. 1200–1150 BCE)",
"Bronze Age collapse; \"Sea Peoples\" crisis",
"event",
"Time",
"F1.9a;F1.11;F1.6",
"WA-LEV;WA-ANA;EU-GRR;AF-EGY",
"-1200",
"-1150",
"approx.",
"Palaces from Mycenae to Hattusa and Ugarit fell, ending palace workshops and long-distance trade in copper, tin and glass, and writing stopped in Greece.",
"palace crafts;trade in ingots",
"tablet;palace",
"war;exchange and value",
"historians and archaeologists",
"the non-palatial communities that carried on",
"conflict-looting",
"open-access excavation reports; Wikimedia Commons",
"R2",
"F1.19a;F1.3",
"high",
"links: POL100; POL101; POL116; NET020. Causes debated (drought, earthquakes, raiders, system collapse).",
"canon_events.csv"
],
[
"OCC005",
"Elamite seizure of Babylonian monuments (c. 1158 BCE)",
"Shutruk-Nahhunte's raid on Sippar and other cities",
"event",
"Time",
"F1.9a",
"WA-MES;WA-IRN",
"-1158",
"-1155",
"approx.; campaign dates debated",
"The Elamite king Shutruk-Nahhunte carried Mesopotamian stelae, including the Code of Hammurabi and the Victory Stele of Naram-Sin, to Susa and re-inscribed some of them, an early recorded case of taking made monuments as trophies.",
"stone carving;inscription",
"stele;statue",
"rule and display;war",
"Assyriologists and Elamologists from Susa excavations (French mission, 1898 on)",
"the craftsmen who carved and re-carved the stelae",
"conflict-looting",
"Cuneiform Digital Library Initiative (link-out); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.24;F1.19a",
"high",
"links: POL098; CIV059; TXT038. Stelae found at Susa by de Morgan's mission 1898–1902 and now in the Louvre.",
"canon_events.csv"
],
[
"OCC006",
"Neo-Assyrian mass deportations (8th–7th c. BCE)",
"Assyrian deportations",
"event",
"Time",
"F1.9a",
"WA-MES;WA-LEV;WA-ANA",
"-745",
"-627",
"approx.; from Tiglath-pileser III to Ashurbanipal",
"Assyrian kings moved hundreds of thousands of conquered people, often skilled craftsmen, to build and furnish their cities.",
"ivory carving;building;metalwork",
"ivory furniture fitting;relief",
"war;rule and display",
"Assyriologists (royal inscriptions and reliefs)",
"the deportees, shown only as captives in the reliefs",
"human-flow;conflict-looting",
"Cuneiform Digital Library Initiative (link-out); Met Open Access (CC0)",
"R2",
"F1.23;F1.13",
"high",
"links: POL096; STY169. Numbers in royal inscriptions are propaganda.",
"canon_events.csv"
],
[
"OCC007",
"Fall of Nineveh (612 BCE)",
"destruction of Nineveh",
"event",
"Time",
"F1.9a",
"WA-MES",
"-612",
"-612",
"612 BCE",
"The sack of Nineveh by Babylonian and Median forces ended the Assyrian palace workshops, while fire baked clay tablets of the palace libraries and left carved wall reliefs buried until the 19th century.",
"relief carving;clay tablets",
"palace relief;tablet",
"record and writing;rule and display;war",
"Assyriologists (Babylonian Chronicle)",
"deported craft workers of the Assyrian empire",
"conflict-looting",
"Cuneiform Digital Library Initiative (link-out); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a;F1.28",
"high",
"links: POL096; POL097. Relief removal to London in the 1840s–50s (Layard) is a later F1.24 story.",
"canon_events.csv"
],
[
"OCC008",
"Cyrus Cylinder and the return of cult statues (539 BCE)",
"Cyrus Cylinder",
"event",
"Time",
"F1.9a",
"WA-MES;WA-IRN",
"-539",
"-539",
"539 BCE",
"After taking Babylon, Cyrus declared that he returned cult statues to their temples and resettled their peoples, a royal claim often read as an early \"restitution\".",
"cylinder inscription;cult statue",
"cylinder;cult statue",
"ritual and belief;rule and display",
"Achaemenid propaganda; Assyriologists",
"the Babylonian priests who wrote it and the modern myths of \"the first human-rights charter\"",
"sacred",
"Cuneiform Digital Library Initiative (link-out); Wikimedia Commons",
"R3",
"F1.24;F1.3",
"high",
"links: POL105; POL097.",
"canon_events.csv"
],
[
"OCC009",
"Twelve Tables funerary limits (c. 450 BCE)",
"Law of the Twelve Tables, Table X",
"event",
"Time",
"F1.11",
"EU-GRR",
"-451",
"-450",
"approx.; text survives only in later quotations",
"The early Roman law code capped funeral display, including numbers of mourning cloths and a ban on burying gold except gold bound to teeth.",
"goldwork;textile",
"shroud;dental gold",
"ritual and belief;rule and display",
"Roman state; reconstructed by modern philologists from Cicero and others",
"non-elite funerals, which left few records",
"funerary",
"public-domain primary texts; Wikisource",
"R3",
"F1.17;F1.16",
"high",
"Cicero, De legibus 2.23–24 preserves the clauses.",
"canon_events.csv"
],
[
"OCC010",
"Sack of Persepolis (330 BCE)",
"burning of Persepolis",
"event",
"Time",
"F1.9a",
"WA-IRN",
"-330",
"-330",
"330 BCE",
"Alexander's army looted the Achaemenid treasury and burned the palace complex, dispersing metalwork and ending the royal building workshops.",
"stone relief;metalwork",
"column capital;relief;vessel",
"rule and display;war",
"historians (Diodorus, Plutarch, Arrian); archaeologists (Oriental Institute excavations 1931–39)",
"the multi-ethnic workforce named in the Persepolis Fortification Tablets",
"conflict-looting",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.19a;F1.24",
"high",
"links: POL105; STY095.",
"canon_events.csv"
],
[
"OCC011",
"Qin standardisation (221 BCE)",
"unification of script, weights, measures and axles",
"event",
"Time",
"F1.8",
"AS-CHN",
"-221",
"-210",
"from 221 BCE",
"After unifying China, the Qin state standardised script, coinage, weights, measures and axle widths, and stamped standard vessels with the edict.",
"bronze casting;inscription",
"standard weight;measuring vessel;coin",
"exchange and value;record and writing;rule and display",
"Qin state; historians (Sima Qian)",
"the regional scripts and measures it replaced",
"none",
"Met Open Access (CC0); Chinese Text Project (link-out); Wikimedia Commons",
"R2",
"F1.5;F1.17",
"high",
"links: POL159; INS019.",
"canon_events.csv"
],
[
"OCC012",
"Lex Oppia (215 BCE)",
"Oppian Law",
"event",
"Time",
"F1.11",
"EU-GRR",
"-215",
"-195",
"passed 215 BCE; repealed 195 BCE",
"A Roman sumptuary law passed during the Second Punic War limited women to half an ounce of gold and banned multi-coloured dress, so its repeal debate records how dress and jewellery signalled rank.",
"goldwork;dyeing",
"jewellery;garment",
"clothing and adornment;rule and display",
"Roman state; Livy (Book 34)",
"the women who protested for its repeal, known mainly through Livy",
"none",
"public-domain primary texts; Wikisource",
"R3",
"F1.17",
"high",
"Livy 34.1–8 gives the repeal debate (Cato vs Valerius).",
"canon_events.csv"
],
[
"OCC013",
"Sack of Corinth (146 BCE)",
"destruction of Corinth by Lucius Mummius",
"event",
"Time",
"F1.11",
"EU-GRR",
"-146",
"-146",
"146 BCE",
"Roman troops sacked Corinth and shipped Greek statues and bronzes to Italy, feeding a Roman market for Greek art and copies.",
"bronze casting;marble sculpture",
"statue;bronze vessel",
"rule and display;war",
"historians (Polybius, Pausanias, Pliny)",
"enslaved Corinthians sold after the sack",
"conflict-looting;human-flow",
"Met Open Access (CC0); Wikimedia Commons; public-domain primary texts",
"R3",
"F1.19a;F1.14;F1.24",
"high",
"links: POL120. \"Corinthian bronze\" as a luxury label in Pliny.",
"canon_events.csv"
],
[
"OCC014",
"Zhang Qian's missions to the Western Regions (138–126 BCE)",
"Zhang Qian's embassy",
"event",
"Time",
"F1.8;F1.12a;F1.13",
"AS-CHN;AS-CEN",
"-138",
"-115",
"first mission c. 138–126 BCE; second c. 119–115 BCE",
"Han envoy Zhang Qian's journeys to Central Asia are traditionally taken as opening Han contact with the Western Regions and their horses, glass and metalwork.",
"silk;horse breeding",
"silk;horse figure",
"exchange and value;transport",
"Han historians (Sima Qian)",
"the steppe and oasis peoples already trading",
"none",
"Chinese Text Project (link-out); Met Open Access (CC0)",
"R3",
"F1.13",
"high",
"links: NET001; NET003; POL160.",
"canon_events.csv"
],
[
"OCC015",
"Han salt and iron monopolies (117 BCE)",
"Debate on Salt and Iron (81 BCE)",
"event",
"Time",
"F1.8",
"AS-CHN",
"-117",
"-81",
"monopolies from c. 117 BCE; debate 81 BCE",
"Emperor Wu put salt making and iron casting under state monopoly, and a court debate in 81 BCE argued over the quality and price of state-made tools.",
"iron casting;salt boiling",
"iron tool;salt pan",
"tools;food and storage",
"Han state; Huan Kuan's Yantie lun",
"the conscript and convict labour in state foundries",
"human-flow",
"Chinese Text Project (link-out)",
"R3",
"F1.17;F1.19",
"high",
"links: POL160; INV089.",
"canon_events.csv"
],
[
"OCC016",
"Siege of Jerusalem (70 CE)",
"destruction of the Second Temple",
"event",
"Time",
"F1.9a",
"WA-LEV",
"70",
"70",
"70 CE",
"Roman forces destroyed the Second Temple and carried its menorah and vessels to Rome, where the Arch of Titus shows them in procession.",
"goldwork;relief carving",
"menorah;relief",
"ritual and belief;war",
"historians (Josephus); Roman monuments",
"captives enslaved after the siege",
"conflict-looting;sacred;human-flow",
"Wikimedia Commons; public-domain primary texts",
"R2",
"F1.19a;F1.24",
"high",
"links: BEL007; POL120.",
"canon_events.csv"
],
[
"OCC017",
"Eruption of Vesuvius (79 CE)",
"destruction of Pompeii and Herculaneum",
"event",
"Time",
"F1.11",
"EU-GRR",
"79",
"79",
"79 CE; month debated (August or October)",
"Ash and pyroclastic flows buried Pompeii and Herculaneum, preserving workshops, bakeries, fulleries and painted rooms whose later excavation shaped knowledge of Roman making.",
"fresco;bronze;glass;fulling",
"wall painting;furniture;tools",
"shelter;food and storage;tools",
"volcanologists; historians (Pliny the Younger's letters)",
"enslaved workers of the towns, prominent among the dead",
"funerary;human-flow",
"Wikimedia Commons; Met Open Access (CC0); public-domain primary texts",
"R2",
"F1.28",
"high",
"links: STY006; TXT002. Excavation event listed separately (OCC097).",
"canon_events.csv"
],
[
"OCC018",
"Shapur I's Roman captives (260)",
"captivity of Valerian",
"event",
"Time",
"F1.9a;F1.11",
"WA-IRN;EU-GRR",
"260",
"260",
"260 CE",
"After capturing the emperor Valerian, Shapur I settled Roman prisoners in Iran, where they are credited with building dams and bridges such as the Band-e Kaisar at Shushtar.",
"masonry;hydraulic engineering",
"bridge;dam",
"war;food and storage",
"Sasanian inscriptions (Shapur's Res Gestae); historians",
"the captives' own names and lives",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.23",
"medium",
"links: POL107. Engineering attribution is traditional.",
"canon_events.csv"
],
[
"OCC019",
"Edict on Maximum Prices (301 CE)",
"Diocletian's Price Edict",
"event",
"Time",
"F1.11",
"EU-GRR;WA-ANA;AF-EGY",
"301",
"301",
"301 CE",
"Diocletian's edict fixed prices for goods and wages across the empire, listing rates for purple dye, silk, textiles and the day-pay of builders, carpenters and painters.",
"purple dyeing;weaving;carpentry;painting",
"textile;dye",
"exchange and value;rule and display",
"Roman state; epigraphers (inscription fragments)",
"makers paid by piece or in kind",
"none",
"public-domain primary texts; Wikimedia Commons; open-access excavation reports",
"R2",
"F1.17;F1.23",
"high",
"Known from inscribed copies, mostly in the eastern provinces.",
"canon_events.csv"
],
[
"OCC020",
"Sack of Rome (410)",
"Visigothic sack of Rome",
"event",
"Time",
"F1.11",
"EU-GRR",
"410",
"410",
"24–27 August 410",
"Alaric's Visigoths looted Rome for three days, a shock that became a founding story for \"the fall of Rome\" and for Late Antique hoarding of silver.",
"silverwork;hoarding",
"silver plate;coin hoard",
"war;exchange and value",
"historians (Orosius, Augustine's City of God)",
"the non-elite Romans and the Goths' own motives",
"conflict-looting",
"public-domain primary texts; Wikimedia Commons",
"R3",
"F1.19a;F1.3",
"high",
"links: POL120. The \"fall\" narrative is contested (see PRD064).",
"canon_events.csv"
],
[
"OCC021",
"Buddhism reaches the Yamato court (538 or 552)",
"gift of a Buddha image from Baekje",
"event",
"Time",
"F1.8",
"AS-JPN;AS-KOR",
"538",
"552",
"538 or 552, sources differ",
"Baekje's gift of a gilt-bronze Buddha and sutras to the Yamato court is the traditional start of Buddhism in Japan, followed by Baekje temple builders, tile makers and image makers.",
"gilt bronze;roof tile;temple carpentry",
"Buddhist image;roof tile",
"ritual and belief;shelter",
"Japanese chronicles (Nihon shoki; Gangōji engi)",
"the Korean craftsmen who built Asuka-dera",
"sacred",
"ColBase (Japan Government Standard Terms); KOGL Type 1 images on Wikimedia Commons",
"R2",
"F1.13;F1.16",
"high",
"links: POL173; POL178; BEL022.",
"canon_events.csv"
],
[
"OCC022",
"Teotihuacan burning (c. 550)",
"destruction of central Teotihuacan",
"event",
"Time",
"F1.7",
"AM-MES",
"550",
"650",
"approx.; dating debated",
"The civic and ritual centre of Teotihuacan was burned and its images smashed, ending the city's role as Mesoamerica's largest craft centre.",
"obsidian working;mural painting;pottery",
"mural;figurine;obsidian blade",
"ritual and belief;rule and display",
"archaeologists",
"the causes, still unknown (internal revolt or attack)",
"sacred",
"INAH Mediateca (link-out); Met Open Access (CC0)",
"R3",
"F1.19a",
"medium",
"links: POL044; CIV026.",
"canon_events.csv"
],
[
"OCC023",
"Silkworms reach Byzantium (c. 552)",
"smuggling of silkworm eggs",
"event",
"Time",
"F1.11;F1.13",
"EU-BYZ;AS-CEN",
"552",
"553",
"approx.; story told by Procopius",
"Procopius tells of monks bringing silkworm eggs from Central Asia to Justinian, the traditional start of Byzantine sericulture.",
"sericulture;silk weaving",
"silk textile",
"clothing and adornment;exchange and value",
"historians (Procopius, Theophanes of Byzantium)",
"Sogdian and Persian silk producers",
"none",
"public-domain primary texts",
"R3",
"F1.14;F1.13",
"medium",
"links: NET001; DIA001. A story, not a documented transfer; versions differ on who carried the eggs.",
"canon_events.csv"
],
[
"OCC024",
"Tang robe-colour rules (630)",
"Zhenguan dress regulations",
"event",
"Time",
"F1.8",
"AS-CHN",
"630",
"630",
"edict of the 8th month, Zhenguan 4 (630); revised later in the Tang",
"An edict of 630 assigned robe colours to official ranks, purple for the third rank and above, crimson for the fourth and fifth, green for the sixth and seventh and blue for the eighth and ninth, making dyed cloth a visible mark of rank.",
"dyeing;silk weaving",
"official robe",
"clothing and adornment;rule and display",
"Tang state; historians (Old and New Tang Histories)",
"commoners and dyers",
"none",
"Chinese Text Project (link-out); Met Open Access (CC0)",
"R3",
"F1.17",
"high",
"Colour ladder quoted from the Zhenguan 4 edict in a Later Tang memorial (932); rules changed several times.",
"canon_events.csv"
],
[
"OCC025",
"Coinage reform of ʿAbd al-Malik (696–697)",
"Arabisation of coinage",
"event",
"Time",
"F1.10",
"WA-LEV;WA-MES",
"696",
"697",
"AH 77",
"The Umayyad caliph replaced Byzantine- and Sasanian-style coins with gold and silver coins bearing only Arabic inscriptions, setting a lasting epigraphic design for Islamic coinage.",
"die cutting;minting",
"dinar;dirham",
"exchange and value;rule and display",
"historians and numismatists",
"the Byzantine- and Sasanian-trained mint workers whose designs it replaced",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.5;F1.17",
"high",
"links: DYN009. Nomisma for coin types.",
"canon_events.csv"
],
[
"OCC026",
"Byzantine Iconoclasm (726–843)",
"Iconoclast controversy",
"event",
"Time",
"F1.11",
"EU-BYZ;WA-ANA",
"726",
"843",
"two phases, c. 726/730–787 and 815–843",
"Imperial bans on religious figural images led to destroyed or replaced icons and mosaics, and the 843 restoration fixed rules for icon painting that lasted.",
"icon painting;mosaic",
"icon;mosaic",
"ritual and belief",
"Byzantine church and state; historians",
"iconophile monks' and women's roles, known from partisan sources",
"sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.16;F1.3",
"high",
"links: BEL010; POL121. Sources are almost all from the victorious side.",
"canon_events.csv"
],
[
"OCC027",
"Huichang persecution of Buddhism (845)",
"Great Anti-Buddhist Persecution",
"event",
"Time",
"F1.8",
"AS-CHN",
"842",
"846",
"peak 845",
"Tang orders closed thousands of monasteries and melted bronze images and bells for coinage, destroying much Buddhist metalwork.",
"bronze casting;melting",
"Buddhist statue;bell",
"ritual and belief;exchange and value",
"historians; Ennin's diary",
"monks and nuns returned to lay life",
"sacred;conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); public-domain primary texts",
"R3",
"F1.16;F1.19a",
"high",
"links: BEL022; POL162.",
"canon_events.csv"
],
[
"OCC028",
"End of embassies to Tang (894)",
"suspension of kentōshi",
"event",
"Time",
"F1.8",
"AS-JPN;AS-CHN",
"894",
"894",
"894",
"Japan's court stopped sending envoys to Tang China, a date later used to mark a turn to kokufū (\"national style\") court art.",
"calligraphy;painting",
"kana manuscript;yamato-e",
"rule and display",
"Japanese historiography",
"continued private trade with China and Korea",
"none",
"ColBase (Japan Government Standard Terms); Japan Search",
"R3",
"F1.3",
"high",
"links: STY145; PRD121. The \"isolation\" reading is now questioned.",
"canon_events.csv"
],
[
"OCC029",
"Book of the Eparch (c. 912)",
"To eparchikon biblion",
"event",
"Time",
"F1.11",
"EU-BYZ",
"911",
"912",
"approx.; attributed to Leo VI",
"The Byzantine prefect's rulebook regulated Constantinople's guilds, including silk dealers and dyers, and barred export of reserved imperial silks.",
"silk weaving;purple dyeing",
"silk textile",
"clothing and adornment;exchange and value",
"Byzantine state",
"workers outside the guilds",
"none",
"public-domain primary texts",
"R3",
"F1.17",
"high",
"links: TXT009; POL121. Event row for the edict; the text is TXT009.",
"canon_events.csv"
],
[
"OCC030",
"Somnath raid (1026)",
"Mahmud of Ghazni's raid on Somnath",
"event",
"Time",
"F1.9;F1.10",
"AS-SAS",
"1026",
"1026",
"January 1026",
"Mahmud of Ghazni sacked the Somnath temple in Gujarat and carried off its treasure, an event later retold in competing nationalist histories.",
"stone carving;goldwork",
"temple;cult image",
"ritual and belief;war",
"Persian chroniclers; colonial and nationalist historians",
"how the temple and town recovered, which later sources obscure",
"sacred;conflict-looting",
"public-domain primary texts; Indian Culture portal (per-owner licence)",
"R3",
"F1.3;F1.19a",
"medium",
"links: DYN014. See Romila Thapar, Somanatha (2004), on the event's later uses.",
"canon_events.csv"
],
[
"OCC031",
"Fatimid treasury looting (1067–1069)",
"al-Shidda al-ʿUzma (the Great Calamity)",
"event",
"Time",
"F1.10",
"AF-EGY",
"1067",
"1069",
"approx.",
"Unpaid troops looted the Fatimid palace treasuries in Cairo, dispersing rock crystal, textiles, books and metalwork across the Mediterranean.",
"rock-crystal carving;tiraz weaving;bookbinding",
"rock-crystal ewer;tiraz textile;manuscript",
"rule and display;exchange and value",
"historians (al-Maqrizi, drawing on earlier inventories)",
"the palace craftsmen who made the objects",
"conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.24",
"medium",
"links: POL041; STY101. Many Fatimid rock crystals now in European church treasuries.",
"canon_events.csv"
],
[
"OCC032",
"Jingkang incident (1127)",
"fall of Kaifeng",
"event",
"Time",
"F1.8",
"AS-CHN",
"1127",
"1127",
"1126–1127",
"Jurchen Jin forces took Kaifeng, capturing two Song emperors, the imperial collections and many artisans, and the Song court re-formed in the south.",
"ceramics;painting;bronze",
"Ru ware;painting;ritual bronze",
"war;rule and display",
"historians",
"artisans and palace women taken north",
"conflict-looting;human-flow",
"National Palace Museum Taipei Open Data (CC BY 4.0); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.19a;F1.24",
"high",
"links: POL166; SCH034. Ru ware production ends with the Northern Song.",
"canon_events.csv"
],
[
"OCC033",
"Destruction of Nalanda (c. 1193–1200)",
"sack of Nalanda",
"event",
"Time",
"F1.9",
"AS-SAS",
"1193",
"1200",
"approx.; date and attackers debated",
"Nalanda and other monastic centres in Bihar were destroyed around 1200, ending workshops for Pala-style bronzes and palm-leaf manuscripts in the region.",
"bronze casting;palm-leaf manuscript",
"bronze image;manuscript",
"ritual and belief;record and writing",
"Persian chronicles; historians",
"the monks and craftsmen who moved to Nepal and Tibet",
"sacred;conflict-looting;human-flow",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"links: POL191; STY119. Attribution to Bakhtiyar Khalji is common but debated.",
"canon_events.csv"
],
[
"OCC034",
"Sack of Constantinople (1204)",
"Fourth Crusade",
"event",
"Time",
"F1.11",
"EU-BYZ",
"1204",
"1204",
"April 1204",
"Crusaders looted Constantinople and carried relics, reliquaries, enamels and the bronze horses to Venice, filling western treasuries with Byzantine work.",
"enamel;bronze casting;goldwork",
"reliquary;icon;horses of San Marco",
"ritual and belief;war",
"historians (Villehardouin, Niketas Choniates)",
"the Byzantine makers whose work was melted down",
"conflict-looting;sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.24;F1.19a",
"high",
"links: POL121; POL131; DYN077.",
"canon_events.csv"
],
[
"OCC035",
"Mongol deportations of artisans (1219–1260s)",
"artisan households under the Mongols",
"event",
"Time",
"F1.12a;F1.13;F1.8",
"AS-CEN;WA-IRN;AS-CHN",
"1219",
"1270",
"approx.",
"Mongol armies spared and relocated skilled craftsmen from conquered Central Asian and Iranian cities to workshops in Mongolia and China, mixing textile and metal traditions.",
"weaving;nasij;metalwork",
"cloth of gold;robe",
"clothing and adornment;war",
"historians (Juvayni, Rashid al-Din); Yuan registers",
"the named individuals behind \"artisan households\"",
"human-flow",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.23",
"medium",
"links: POL233; DYN074; NET001. Numbers in chronicles are unreliable.",
"canon_events.csv"
],
[
"OCC036",
"Sack of Baghdad (1258)",
"Mongol conquest of Baghdad",
"event",
"Time",
"F1.10",
"WA-MES",
"1258",
"1258",
"February 1258",
"Hülegü's army sacked Baghdad and ended the Abbasid caliphate, destroying libraries and scattering craftsmen, though some later worked for the Ilkhans.",
"bookmaking;paper;metalwork",
"manuscript",
"record and writing;war",
"historians",
"continuities in Baghdad's crafts after 1258",
"conflict-looting",
"Digital Library of the Middle East; Met Open Access (CC0)",
"R2",
"F1.19a",
"high",
"links: DYN010; POL234; STY103. Scale of library loss is often exaggerated.",
"canon_events.csv"
],
[
"OCC037",
"Mansa Musa's hajj (1324)",
"pilgrimage of Mansa Musa",
"event",
"Time",
"F1.6;F1.10",
"AF-SAH;AF-EGY",
"1324",
"1325",
"1324–1325",
"Mali's ruler travelled to Mecca through Cairo with large amounts of gold and brought back the Andalusi poet al-Sahili, whom Ibn Khaldun credits with an audience hall in Mali and later tradition with mosques at Timbuktu and Gao.",
"gold trade;earthen building",
"mosque;gold",
"exchange and value;ritual and belief",
"Arabic chroniclers (al-Umari); historians",
"the enslaved people in the caravan",
"human-flow",
"collection search link-out only",
"R2",
"F1.13",
"medium",
"links: POL036; CIV008; NET010. Architectural attributions to al-Sahili beyond the audience hall are weakly supported.",
"canon_events.csv"
],
[
"OCC038",
"Black Death (1347–1351)",
"Great Mortality",
"event",
"Time",
"F1.11;F1.10;F1.13",
"EU-WCE;EU-BLC;EU-IBE;WA-LEV;AF-EGY;AF-MAG",
"1347",
"1351",
"main wave; recurrences to the 18th century",
"Plague killed perhaps a third to a half of the population in affected areas, raising wages for surviving craft workers and prompting labour laws.",
"building;weaving",
"none specific",
"care and access",
"historians",
"non-European losses, less studied",
"funerary",
"public-domain primary texts; Wellcome Collection",
"R2",
"F1.19a;F1.23",
"high",
"Mortality estimates vary widely.",
"canon_events.csv"
],
[
"OCC039",
"Statute concerning Diet and Apparel (1363)",
"English sumptuary law of 1363",
"event",
"Time",
"F1.11",
"EU-BLC",
"1363",
"1604",
"1363; later Acts of Apparel (1533 etc.) repealed 1604",
"English law set which cloths, furs and prices each rank could wear, one of a series of sumptuary acts that shaped the cloth trade.",
"wool;fur;silk",
"garment",
"clothing and adornment;rule and display",
"English crown and Parliament",
"the tailors and furriers who adapted to the rules",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC040",
"Ming sumptuary regulations (from 1368)",
"Hongwu dress and house rules",
"event",
"Time",
"F1.8",
"AS-CHN",
"1368",
"1644",
"approx.; rules reissued and widely broken",
"Early Ming law restricted dragon and phoenix motifs, certain colours and gold embroidery to the court and set house sizes and decoration by rank.",
"embroidery;silk weaving;timber building",
"dragon robe;mandarin square",
"clothing and adornment;rule and display;shelter",
"Ming state; historians",
"merchants who ignored the rules as Ming commerce grew",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data (CC BY 4.0)",
"R3",
"F1.17",
"medium",
"links: POL168. Rank badges (buzi) as members.",
"canon_events.csv"
],
[
"OCC041",
"Ming maritime ban (1371–1567)",
"haijin",
"event",
"Time",
"F1.8;F1.13",
"AS-CHN",
"1371",
"1567",
"1371; relaxed 1567 (Yuegang opened)",
"The Ming ban on private sea trade pushed porcelain and silk exports into tribute missions and smuggling until its relaxation in 1567.",
"porcelain;silk",
"blue-and-white porcelain",
"exchange and value;transport",
"Ming state; historians",
"coastal traders labelled \"pirates\" (wokou)",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Rijksmuseum (CC0/PDM)",
"R2",
"F1.13",
"high",
"links: NET054; NET008; DIA007. Qing had a separate ban (see Great Clearance).",
"canon_events.csv"
],
[
"OCC042",
"Timur's deportation of artisans (1398–1402)",
"craftsmen taken to Samarkand",
"event",
"Time",
"F1.12a;F1.10;F1.9",
"AS-CEN;WA-LEV;AS-SAS;WA-ANA",
"1398",
"1405",
"Delhi 1398; Damascus 1401; Anatolia 1402",
"Timur forcibly moved builders, weavers, glass and metal workers from Delhi, Damascus and elsewhere to build and furnish Samarkand, as Clavijo saw in 1404.",
"tilework;weaving;glass;metalwork",
"tile;textile",
"shelter;rule and display",
"historians; Clavijo's Embajada",
"the deported makers and their home cities",
"human-flow;conflict-looting",
"public-domain primary texts; Archnet (link-out)",
"R2",
"F1.13;F1.23",
"high",
"links: POL235; STY106; TXT036.",
"canon_events.csv"
],
[
"OCC043",
"Zheng He's voyages (1405–1433)",
"Ming treasure fleets",
"event",
"Time",
"F1.8;F1.13;F1.9;F1.6;F1.10",
"AS-CHN;AS-ISE;AS-SAS;WA-ARB;AF-SWA",
"1405",
"1433",
"seven voyages",
"Seven Ming fleets carried porcelain, silk and gifts to Southeast Asia, India, Arabia and East Africa, recorded in the Liujiagang and Changle inscriptions.",
"shipbuilding;porcelain;silk",
"treasure ship;porcelain;giraffe painting",
"transport;exchange and value;rule and display",
"Ming records; Ma Huan's Yingya shenglan",
"the crews and the societies visited",
"none",
"Chinese Text Project (link-out); Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: TXT089; TXT090; NET005. Ship sizes in later sources are disputed.",
"canon_events.csv"
],
[
"OCC044",
"Ming occupation of Đại Việt (1407–1427)",
"fourth Chinese domination",
"event",
"Time",
"F1.9;F1.8",
"AS-MSE",
"1407",
"1427",
"1407–1427",
"Ming armies removed books and took Vietnamese craftsmen to China, among them Nguyễn An, later credited with building work in Beijing.",
"building;printing",
"book;palace architecture",
"war;record and writing",
"Vietnamese and Chinese historians",
"the craftsmen named only collectively",
"human-flow;conflict-looting",
"public-domain primary texts",
"R3",
"F1.13;F1.23",
"medium",
"links: POL215. Nguyễn An's role in the Forbidden City to verify.",
"canon_events.csv"
],
[
"OCC045",
"Hunminjeongeum promulgated (1446)",
"creation of Hangul",
"event",
"Time",
"F1.8",
"AS-KOR",
"1443",
"1446",
"created 1443; promulgated 1446",
"King Sejong's court issued a designed alphabet for Korean, with the Haerye explaining letter shapes from the organs of speech.",
"woodblock printing;type design",
"book;type",
"record and writing",
"Joseon court; Korean historiography",
"the scribes and scholars who worked on it",
"none",
"KOGL Type 1 images on Wikimedia Commons; Kyujanggak / Uigwe (link-out)",
"R2",
"F1.5",
"high",
"links: TXT107; POL177.",
"canon_events.csv"
],
[
"OCC046",
"Fall of Constantinople (1453)",
"Ottoman conquest of Constantinople",
"event",
"Time",
"F1.11;F1.10",
"EU-BYZ;WA-ANA",
"1453",
"1453",
"29 May 1453",
"Ottoman conquest ended the Byzantine state; Greek scholars and makers moved west while Mehmed II rebuilt the city with new court workshops.",
"building;manuscript;icon painting",
"manuscript;icon",
"war;rule and display",
"historians",
"the city's people and continuities under Ottoman rule",
"conflict-looting;human-flow",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a;F1.13",
"high",
"links: POL121; INS041; INS042.",
"canon_events.csv"
],
[
"OCC047",
"Ōnin War (1467–1477)",
"Ōnin no ran",
"event",
"Time",
"F1.8",
"AS-JPN",
"1467",
"1477",
"1467–1477",
"Fighting destroyed much of Kyoto; returning weavers settled near the old Western Army camp, which gave the Nishijin weaving district its name.",
"silk weaving",
"brocade;kimono",
"clothing and adornment;war",
"Japanese historiography",
"non-elite Kyoto residents",
"conflict-looting",
"ColBase (Japan Government Standard Terms); Japan Search",
"R3",
"F1.19a",
"high",
"links: POL182; PRD124.",
"canon_events.csv"
],
[
"OCC048",
"Venetian Patent Statute (1474)",
"Parte Veneziana",
"event",
"Time",
"F1.11",
"EU-WCE",
"1474",
"1474",
"19 March 1474",
"Venice granted ten-year exclusive rights to makers of new and useful devices, an early general patent law.",
"glassmaking;machines",
"device",
"tools;exchange and value",
"Venetian Senate; historians of patents",
"guild members excluded from rights",
"none",
"public-domain primary texts",
"R3",
"F1.14",
"high",
"links: POL131.",
"canon_events.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
