insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OCC049",
"Gyeongguk daejeon (1485)",
"Grand Code for State Administration",
"event",
"Time",
"F1.8",
"AS-KOR",
"1485",
"1485",
"completed 1485",
"Joseon's law code registered government artisans by craft in the capital and provinces and set dress and household rules by rank.",
"registered artisans",
"none specific",
"rule and display",
"Joseon state",
"artisans outside the registers",
"none",
"Kyujanggak / Uigwe (link-out)",
"R3",
"F1.17",
"medium",
"Artisan numbers to verify.",
"canon_events.csv"
],
[
"OCC050",
"Portuguese brass in Benin (from c. 1485)",
"manilla trade",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI;EU-WCE",
"1485",
"1600",
"approx.",
"Portuguese traders brought brass manillas to Benin, and metal analysis links many Benin brasses to manillas made in the Rhineland.",
"brass casting;metal analysis",
"manilla;plaque",
"exchange and value",
"historians; archaeometrists",
"enslaved people traded in the same exchanges",
"human-flow",
"Digital Benin (each lender's licence)",
"R3",
"F1.13",
"medium",
"links: DYN038; POL026. Isotope study published 2023.",
"canon_events.csv"
],
[
"OCC051",
"Alhambra Decree (1492)",
"expulsion of the Jews from Spain",
"event",
"Time",
"F1.11;F1.10",
"EU-IBE",
"1492",
"1492",
"31 March 1492",
"Spain's order expelling Jews scattered Sephardic silversmiths, weavers and printers to North Africa, the Ottoman empire and elsewhere.",
"silverwork;weaving;printing",
"ritual silver;textile",
"ritual and belief;exchange and value",
"Spanish crown; historians",
"those who converted and stayed",
"human-flow;sacred",
"public-domain primary texts; Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: BEL007; POL135.",
"canon_events.csv"
],
[
"OCC052",
"Columbus's first voyage and the Columbian exchange (1492)",
"Columbian exchange",
"event",
"Time",
"F1.7;F1.11;F1.13",
"AM-CAR;EU-IBE;GL",
"1492",
"1600",
"1492; exchange unfolds over the 16th century",
"Columbus's landfall in the Caribbean began transfers of crops, animals, materials, diseases and people that remade making in the Americas and beyond.",
"cochineal;silver;cacao;tobacco",
"none specific",
"exchange and value;transport",
"historians (Alfred Crosby, 1972)",
"Taíno and other Indigenous peoples first affected",
"human-flow;Indigenous-community",
"public-domain primary texts; Library of Congress (per-item rights; many public domain); Wikimedia Commons",
"R1",
"F1.13;F1.22",
"high",
"links: CIV030; NET034; POL055.",
"canon_events.csv"
],
[
"OCC053",
"Vasco da Gama reaches Calicut (1498)",
"opening of the Cape route",
"event",
"Time",
"F1.11;F1.9;F1.13",
"EU-IBE;AS-SAS;AF-SWA",
"1497",
"1499",
"voyage 1497–1499",
"The Portuguese sea route round Africa to India began direct European trade in Indian textiles and spices.",
"cotton textile;spice",
"chintz;pepper",
"exchange and value;transport",
"historians",
"the Gujarati and Arab pilots and traders already on the route",
"conflict-looting",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: NET033; POL136; DIA006.",
"canon_events.csv"
],
[
"OCC054",
"Portuguese sack of Kilwa and Mombasa (1505)",
"Almeida's attacks on the Swahili coast",
"event",
"Time",
"F1.6;F1.13",
"AF-SWA",
"1505",
"1505",
"1505",
"Portuguese forces under Francisco de Almeida sacked Kilwa and Mombasa, disrupting the Swahili coast's gold and cloth trade.",
"stone building;cloth trade",
"coral-stone architecture",
"war;exchange and value",
"historians; Portuguese chronicles",
"Swahili accounts such as the Kilwa Chronicle",
"conflict-looting",
"public-domain primary texts; Zamani Project (link-out)",
"R3",
"F1.19a;F1.13",
"high",
"links: POL009; NET011; TXT048.",
"canon_events.csv"
],
[
"OCC055",
"Ottoman deportation of artisans from Tabriz and Cairo (1514–1517)",
"sürgün of craftsmen",
"event",
"Time",
"F1.10",
"WA-IRN;AF-EGY;WA-ANA",
"1514",
"1517",
"Tabriz 1514; Cairo 1517",
"After taking Tabriz and Cairo, Selim I moved painters, tile makers, weavers and other craftsmen to Istanbul, feeding the court workshops.",
"tilework;painting;weaving",
"tile;manuscript;textile",
"rule and display",
"historians; Ottoman court registers",
"the deported makers' names outside payroll registers",
"human-flow;conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.17",
"high",
"links: INS041; INS042; POL042; POL236.",
"canon_events.csv"
],
[
"OCC056",
"Epidemics in the Americas (from 1518)",
"smallpox and cocoliztli epidemics",
"event",
"Time",
"F1.7",
"AM-CAR;AM-MES;AM-AND;GL",
"1518",
"1600",
"smallpox from 1518–1520; cocoliztli 1545 and 1576",
"Introduced epidemics killed a large share of Indigenous people, destroying workshops and passing on fewer makers' skills.",
"none specific",
"none specific",
"care and access",
"historians; demographers; geneticists",
"the survivors who kept crafts going",
"funerary;Indigenous-community",
"public-domain primary texts; INAH Mediateca (link-out)",
"R2",
"F1.19a;F1.23",
"high",
"links: CIV043. Population estimates debated.",
"canon_events.csv"
],
[
"OCC057",
"Fall of Tenochtitlan (1521)",
"Spanish conquest of the Mexica capital",
"event",
"Time",
"F1.7",
"AM-MES",
"1519",
"1521",
"campaign 1519–1521; city fell 13 August 1521",
"The Spanish-led conquest, with Indigenous allies, destroyed Tenochtitlan, and most Mexica goldwork was melted into bars, so few pieces survive.",
"goldwork;featherwork;melting",
"gold ornament;feather headdress;codex",
"war;ritual and belief;exchange and value",
"historians; Spanish and Nahua sources (Florentine Codex)",
"the Tlaxcalan and other Indigenous allies; Mexica survivors",
"conflict-looting;sacred;Indigenous-community",
"INAH Mediateca (link-out); Wikimedia Commons; public-domain primary texts",
"R1",
"F1.19a;F1.24",
"high",
"links: POL051; POL052; CIV020; TXT109; TXT114. Surviving featherwork (e.g. Vienna headdress) is a restitution case.",
"canon_events.csv"
],
[
"OCC058",
"Ransom of Atahualpa (1532–1533)",
"Cajamarca treasure",
"event",
"Time",
"F1.7",
"AM-AND",
"1532",
"1533",
"1532–1533",
"Inca gold and silver collected to ransom Atahualpa at Cajamarca were melted down by the Spanish, erasing most imperial metalwork.",
"goldwork;silverwork;melting",
"metal vessel;figurine",
"war;exchange and value",
"Spanish chroniclers; historians",
"the Andean smiths who made the pieces",
"conflict-looting;sacred;Indigenous-community",
"public-domain primary texts; Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a;F1.24",
"high",
"links: POL061; CIV022.",
"canon_events.csv"
],
[
"OCC059",
"Dissolution of the Monasteries (1536–1541)",
"Suppression of the Monasteries",
"event",
"Time",
"F1.11",
"EU-BLC",
"1536",
"1541",
"1536–1541",
"Henry VIII's closure of English and Welsh monasteries led to stripped lead, melted plate, broken shrines and scattered libraries.",
"lead;goldsmithing;bookbinding",
"shrine;plate;manuscript",
"ritual and belief;rule and display",
"English crown; historians",
"lay workers dependent on monasteries",
"sacred;conflict-looting",
"British Library public-domain images (Flickr Commons); Wikimedia Commons; Yale Center for British Art (public-domain images)",
"R2",
"F1.16;F1.19a",
"high",
"links: BEL011; BEL012.",
"canon_events.csv"
],
[
"OCC060",
"New Laws of the Indies (1542)",
"Leyes Nuevas",
"event",
"Time",
"F1.7;F1.11",
"AM-LAT",
"1542",
"1542",
"1542; partly revoked 1545",
"Spanish law sought to end Indigenous enslavement and phase out the encomienda, changing how Indigenous labour for building and craft was demanded.",
"forced labour",
"none specific",
"rule and display",
"Spanish crown; historians",
"Indigenous and African people still coerced after the laws",
"human-flow;Indigenous-community",
"public-domain primary texts",
"R3",
"F1.23",
"high",
"links: POL069; POL070.",
"canon_events.csv"
],
[
"OCC061",
"Portuguese reach Tanegashima (1543)",
"arrival of the matchlock in Japan",
"event",
"Time",
"F1.8;F1.13",
"AS-JPN",
"1543",
"1543",
"1543 (some accounts 1542)",
"Portuguese traders brought matchlock guns to Tanegashima, and Japanese smiths are credited with copying them within a few years.",
"gunsmithing;ironwork",
"matchlock gun",
"war;tools",
"Japanese chronicle (Teppōki); historians",
"Chinese traders who carried the Portuguese",
"none",
"ColBase (Japan Government Standard Terms); Japan Search",
"R2",
"F1.14;F1.19a",
"high",
"links: INV166.",
"canon_events.csv"
],
[
"OCC062",
"Silver found at Potosí (1545)",
"Cerro Rico de Potosí",
"event",
"Time",
"F1.7;F1.13",
"AM-AND",
"1545",
"1545",
"1545",
"The silver mountain of Potosí became the largest silver source of its time, feeding mints, colonial silverwork and global trade.",
"silver mining;amalgamation;minting",
"coin;silverwork",
"exchange and value",
"historians",
"Andean mitayos and enslaved Africans who worked the mines",
"human-flow;Indigenous-community",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.22;F1.23",
"high",
"links: INS008; NET036; POL070.",
"canon_events.csv"
],
[
"OCC063",
"Maní auto-da-fé (1562)",
"burning of Maya books at Maní",
"event",
"Time",
"F1.7",
"AM-MES",
"1562",
"1562",
"July 1562",
"Franciscan friar Diego de Landa burned Maya books and images at Maní, so only four Maya codices are known to survive.",
"bark paper;painting",
"codex;image",
"record and writing;ritual and belief",
"Landa's Relación; historians",
"Maya scribes and the knowledge in the books",
"sacred;conflict-looting;Indigenous-community",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.24;F1.28",
"high",
"links: TXT115; TXT116; TXT117; BEL037.",
"canon_events.csv"
],
[
"OCC064",
"Council of Trent decree on images (1563)",
"Decree on the invocation of saints and sacred images",
"event",
"Time",
"F1.11",
"EU-WCE;EU-IBE",
"1563",
"1563",
"December 1563",
"The Catholic Church's decree on images asked that religious art be clear, decorous and approved by bishops, shaping Counter-Reformation art in Europe and its colonies.",
"painting;sculpture",
"altarpiece;devotional image",
"ritual and belief",
"Council of Trent",
"Indigenous and colonial makers who adapted the rules",
"sacred",
"public-domain primary texts",
"R3",
"F1.16",
"high",
"links: BEL011; STY022.",
"canon_events.csv"
],
[
"OCC065",
"Statute of Artificers (1563)",
"Statute of Apprentices",
"event",
"Time",
"F1.11",
"EU-BLC",
"1563",
"1814",
"1563; apprenticeship clauses repealed 1814",
"English law made a seven-year apprenticeship compulsory in many trades and let justices set wages, framing craft training for 250 years.",
"apprenticeship",
"none specific",
"tools",
"English Parliament",
"women's household craft work, outside the statute",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC066",
"Battle of Talikota and sack of Vijayanagara (1565)",
"fall of Hampi",
"event",
"Time",
"F1.9",
"AS-SAS",
"1565",
"1565",
"1565",
"After defeat by a coalition of Deccan sultanates, Vijayanagara's capital at Hampi was looted and abandoned, ending its temple and palace workshops.",
"stone carving;building",
"temple;palace",
"war;ritual and belief",
"historians",
"continuities in later Nayaka courts",
"conflict-looting;sacred",
"Wikimedia Commons; Indian Culture portal (per-owner licence)",
"R3",
"F1.19a",
"high",
"links: POL196; DYN053; DYN055.",
"canon_events.csv"
],
[
"OCC067",
"Urdaneta's return route (1565)",
"tornaviaje",
"event",
"Time",
"F1.9;F1.7;F1.13",
"AS-ISE;AM-LAT",
"1565",
"1565",
"1565",
"Andrés de Urdaneta found a return route across the Pacific, making the Manila–Acapulco galleon run possible.",
"navigation;shipbuilding",
"galleon",
"transport;exchange and value",
"historians",
"Filipino and Chinese sailors and shipbuilders",
"human-flow",
"public-domain primary texts",
"R3",
"F1.13",
"high",
"links: INS040; NET036. Event only; the trade itself is INS040/NET036.",
"canon_events.csv"
],
[
"OCC068",
"Beeldenstorm (1566)",
"Iconoclastic Fury",
"event",
"Time",
"F1.11",
"EU-BLC",
"1566",
"1566",
"August–October 1566",
"Protestant crowds stripped and smashed images in hundreds of Low Countries churches.",
"sculpture;stained glass;painting",
"altarpiece;statue",
"ritual and belief",
"historians",
"Catholic makers and later restorers",
"sacred;conflict-looting",
"Rijksmuseum (CC0/PDM); Wikimedia Commons",
"R2",
"F1.16;F1.19a",
"high",
"links: BEL012; POL129.",
"canon_events.csv"
],
[
"OCC069",
"Potosí mita reorganised (1573)",
"Toledo's mita",
"event",
"Time",
"F1.7",
"AM-AND",
"1573",
"1812",
"1573; abolished 1812",
"Viceroy Francisco de Toledo imposed rotating forced labour drafts on Andean communities for the Potosí mines and mills.",
"forced labour;silver refining",
"none specific",
"exchange and value",
"Spanish viceroyalty; historians",
"the mitayos and their families",
"human-flow;Indigenous-community",
"public-domain primary texts",
"R2",
"F1.23;F1.22",
"high",
"links: POL070; INS008.",
"canon_events.csv"
],
[
"OCC070",
"Sword hunt (1588)",
"katanagari",
"event",
"Time",
"F1.8",
"AS-JPN",
"1588",
"1588",
"1588",
"Toyotomi Hideyoshi ordered farmers to give up swords and guns, fixing a line between armed samurai and unarmed commoners.",
"swordsmithing;melting",
"sword",
"war;rule and display",
"Japanese state; historians",
"farmers who hid weapons",
"none",
"ColBase (Japan Government Standard Terms); Japan Search",
"R3",
"F1.19a",
"high",
"links: DYN070. Hideyoshi claimed the metal would be used for a Great Buddha.",
"canon_events.csv"
],
[
"OCC071",
"Imjin War (1592–1598)",
"Japanese invasions of Korea; \"pottery wars\"",
"event",
"Time",
"F1.8",
"AS-KOR;AS-JPN",
"1592",
"1598",
"1592–1598",
"Japanese invasions devastated Korea, and many Korean potters were taken to Japan, where they are credited with founding kilns such as those at Arita and Satsuma.",
"ceramics;porcelain;kiln building",
"tea bowl;porcelain",
"war;food and storage",
"Korean and Japanese historiography",
"the captives who could not return",
"human-flow;conflict-looting",
"KOGL Type 1 images on Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R1",
"F1.13;F1.19a;F1.23",
"high",
"links: DIA012; DYN070; DYN073; POL177.",
"canon_events.csv"
],
[
"OCC072",
"Capture of the carracks São Jacinto and Santa Catarina (1602–1603)",
"kraak porcelain auctions",
"event",
"Time",
"F1.11;F1.8;F1.13",
"EU-BLC;AS-CHN;AS-ISE",
"1602",
"1604",
"1602 and 1603; Amsterdam sale 1604",
"Dutch capture and auction of two Portuguese carracks put large lots of Chinese blue-and-white porcelain on the Amsterdam market, launching the \"kraak\" fashion.",
"porcelain",
"kraak porcelain",
"exchange and value;food and storage",
"historians",
"the Jingdezhen potters",
"conflict-looting",
"Rijksmuseum (CC0/PDM); Met Open Access (CC0)",
"R2",
"F1.13;F1.14",
"high",
"links: INS038; NET054.",
"canon_events.csv"
],
[
"OCC073",
"Deportation of Armenians from Julfa (1604–1605)",
"forced migration to New Julfa",
"event",
"Time",
"F1.10;F1.13",
"WA-CAU;WA-IRN",
"1604",
"1605",
"1604–1605",
"Shah ʿAbbas forcibly moved the Armenians of Julfa to Isfahan, where New Julfa merchants and craftsmen ran a silk and textile network.",
"silk trade;painting",
"textile;illuminated manuscript",
"exchange and value",
"historians",
"those who died in the march",
"human-flow",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: DIA002; INS046; POL236.",
"canon_events.csv"
],
[
"OCC074",
"Expulsion of the Moriscos (1609–1614)",
"expulsión de los moriscos",
"event",
"Time",
"F1.11;F1.10",
"EU-IBE;AF-MAG",
"1609",
"1614",
"1609–1614",
"Spain expelled about 300,000 Moriscos, losing silk, pottery and building crafts that moved to North Africa.",
"silk weaving;lustreware;plasterwork",
"textile;pottery",
"clothing and adornment",
"Spanish crown; historians",
"Moriscos who stayed hidden",
"human-flow",
"public-domain primary texts; Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: STY015; POL153; POL154.",
"canon_events.csv"
],
[
"OCC075",
"Extirpation of idolatry in Peru (1609–1660s)",
"extirpación de idolatrías",
"event",
"Time",
"F1.7",
"AM-AND",
"1609",
"1670",
"campaigns c. 1609–1660s",
"Church campaigns in the Andes seized and burned huacas, mallquis and ritual objects.",
"burning;textile;stone",
"huaca;ritual object",
"ritual and belief",
"Catholic church; historians",
"Andean communities who hid huacas",
"sacred;ancestral;Indigenous-community",
"public-domain primary texts",
"R3",
"F1.16;F1.24",
"high",
"links: BEL038.",
"canon_events.csv"
],
[
"OCC076",
"Statute of Monopolies (1624)",
"English patent statute",
"event",
"Time",
"F1.11",
"EU-BLC",
"1624",
"1624",
"1624",
"English law ended most royal monopolies but kept patents for new inventions, the basis of later patent law.",
"invention",
"patent",
"exchange and value;tools",
"English Parliament",
"inventors without means to petition",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC077",
"Sakoku edicts (1633–1639)",
"maritime restrictions",
"event",
"Time",
"F1.8",
"AS-JPN",
"1633",
"1639",
"1633–1639; restrictions eased from 1853",
"Tokugawa edicts limited foreign trade to Dutch and Chinese ships at Nagasaki and set the terms of Japan's porcelain and textile exports.",
"porcelain;lacquer;silk",
"export porcelain;lacquer",
"exchange and value",
"Tokugawa shogunate; historians (term sakoku coined 1801)",
"Ryukyu, Tsushima and Ainu trade",
"none",
"ColBase (Japan Government Standard Terms); Rijksmuseum (CC0/PDM)",
"R2",
"F1.13",
"high",
"links: INS025; POL183; DYN071. \"Closed country\" label is contested.",
"canon_events.csv"
],
[
"OCC078",
"Queue order (1645)",
"tifa yifu",
"event",
"Time",
"F1.8",
"AS-CHN",
"1645",
"1911",
"1645; ended 1911–12",
"The Qing required Han men to shave the forehead, wear the queue and adopt Manchu-style dress, changing tailoring and hair work across China.",
"tailoring;hairdressing",
"queue;robe",
"clothing and adornment;rule and display",
"Qing state",
"women, who were largely exempt",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data (CC BY 4.0)",
"R3",
"F1.17",
"high",
"links: POL169.",
"canon_events.csv"
],
[
"OCC079",
"Navigation Acts (1651–1660)",
"English Navigation Acts",
"event",
"Time",
"F1.11;F1.13",
"EU-BLC;AM-LAT;GL",
"1651",
"1849",
"1651; 1660; repealed 1849",
"English law required colonial trade to use English ships, shaping what colonies could make and sell.",
"shipbuilding;trade",
"none specific",
"exchange and value;transport",
"English Parliament",
"colonial makers barred from some trades",
"human-flow",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R2",
"F1.13",
"high",
"links: POL137. Enumerated goods included sugar and tobacco produced by enslaved people.",
"canon_events.csv"
],
[
"OCC080",
"VOC's first large order for Japanese porcelain (1659)",
"Arita export porcelain",
"event",
"Time",
"F1.8;F1.11;F1.13",
"AS-JPN;EU-BLC",
"1659",
"1659",
"1659",
"With Chinese supply disrupted, the VOC placed a large order at Arita, beginning Japanese export porcelain for Europe.",
"porcelain",
"Imari;Kakiemon",
"exchange and value;food and storage",
"historians of ceramics",
"the Arita potters, many of Korean descent",
"none",
"Rijksmuseum (CC0/PDM); Met Open Access (CC0); ColBase (Japan Government Standard Terms)",
"R3",
"F1.13;F1.14",
"medium",
"links: INS038; DIA012. Small purchases from the 1650s (4,149 pieces ordered 1656); the 1659 order was for 64,866 pieces.",
"canon_events.csv"
],
[
"OCC081",
"Great Clearance (1661–1683)",
"coastal evacuation",
"event",
"Time",
"F1.8",
"AS-CHN",
"1661",
"1683",
"1661; lifted 1683–84",
"The Qing forced coastal people inland to cut off Zheng forces on Taiwan, disrupting coastal kilns, salt works and trade.",
"salt making;porcelain trade",
"none specific",
"war;exchange and value",
"Qing state; historians",
"the displaced coastal people",
"human-flow",
"public-domain primary texts",
"R3",
"F1.19a",
"high",
"links: POL169.",
"canon_events.csv"
],
[
"OCC082",
"Burial in Woollen Acts (1666–1680)",
"Burying in Woollen Acts",
"event",
"Time",
"F1.11",
"EU-BLC",
"1666",
"1814",
"1666, 1678, 1680; repealed 1814",
"English law required the dead to be buried in woollen shrouds, to support the wool trade.",
"wool;weaving",
"shroud",
"clothing and adornment;ritual and belief",
"English Parliament",
"linen weavers and importers, and families fined for using linen",
"funerary",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC083",
"Great Fire of London (1666)",
"Rebuilding Act 1667",
"event",
"Time",
"F1.11",
"EU-BLC",
"1666",
"1667",
"September 1666; Rebuilding Act 1667",
"After the fire, London rebuilt in brick and stone under the Rebuilding Act, with Wren's churches and new building rules.",
"brick;stone;building regulation",
"church;house",
"shelter",
"historians; London authorities",
"the displaced poor",
"none",
"Yale Center for British Art (public-domain images); British Library public-domain images (Flickr Commons)",
"R2",
"F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC084",
"Royal edict founding the Gobelins manufactory (1667)",
"Manufacture royale des meubles de la Couronne",
"event",
"Time",
"F1.11",
"EU-WCE",
"1667",
"1667",
"1662 purchase; 1667 edict",
"Louis XIV's edict made the Gobelins a royal manufactory under Le Brun for tapestry, furniture and metalwork.",
"tapestry weaving;cabinetmaking",
"tapestry;furniture",
"rule and display",
"French crown",
"Flemish weavers and other migrant workers",
"none",
"Met Open Access (CC0); Getty Museum Open Content (CC0); Paris Musées (Open Content)",
"R2",
"F1.17",
"high",
"links: DYN085; POL126.",
"canon_events.csv"
],
[
"OCC085",
"Pueblo Revolt (1680)",
"Popé's Revolt",
"event",
"Time",
"F1.7",
"AM-WST",
"1680",
"1692",
"1680; Spanish return 1692",
"Pueblo peoples expelled Spanish colonists from New Mexico and destroyed mission churches, restoring kiva practice for a time.",
"adobe building;ritual objects",
"mission church;katsina",
"ritual and belief;war",
"Pueblo peoples; historians",
"Pueblo views of the event",
"sacred;Indigenous-community",
"Library of Congress (per-item rights; many public domain); US National Archives Catalog",
"R3",
"F1.19a;F1.16",
"high",
"links: ARC177; BEL039.",
"canon_events.csv"
],
[
"OCC086",
"Tenna sumptuary edicts (1683)",
"Tenna sumptuary laws",
"event",
"Time",
"F1.8",
"AS-JPN",
"1683",
"1683",
"1683",
"Shogunal edicts banned townspeople from wearing gold brocade, embroidery and full tie-dye (sō-kanoko), a ban often linked to the rise of yūzen paste-resist dyeing.",
"shibori;embroidery;yūzen dyeing",
"kosode",
"clothing and adornment;rule and display",
"Tokugawa shogunate",
"dyers and weavers who adapted",
"none",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R3",
"F1.17;F1.18",
"medium",
"Link to yūzen's rise is a common but debated claim.",
"canon_events.csv"
],
[
"OCC087",
"Revocation of the Edict of Nantes (1685)",
"Edict of Fontainebleau",
"event",
"Time",
"F1.11",
"EU-WCE",
"1685",
"1685",
"October 1685",
"The revocation drove Huguenot silk weavers, silversmiths and watchmakers out of France to England, the Netherlands and Prussia.",
"silk weaving;silversmithing;watchmaking",
"silk;silver",
"clothing and adornment;exchange and value",
"French crown; historians",
"those who converted and stayed",
"human-flow",
"public-domain primary texts; Yale Center for British Art (public-domain images)",
"R3",
"F1.13",
"high",
"links: DIA010.",
"canon_events.csv"
],
[
"OCC088",
"French ban on printed calicoes (1686–1759)",
"prohibition des toiles peintes",
"event",
"Time",
"F1.11",
"EU-WCE",
"1686",
"1759",
"1686; lifted 1759",
"France banned import, making and wearing of printed cottons to protect silk and wool, while smuggling and illicit printing continued.",
"cotton printing;mordant dyeing",
"indienne",
"clothing and adornment",
"French crown",
"smugglers and illicit printers",
"none",
"Paris Musées (Open Content); Met Open Access (CC0)",
"R2",
"F1.14;F1.18",
"high",
"links: NET055.",
"canon_events.csv"
],
[
"OCC089",
"Minas Gerais gold rush (1690s)",
"ciclo do ouro",
"event",
"Time",
"F1.7",
"AM-LAT",
"1693",
"1780",
"approx.",
"Gold finds in Minas Gerais drew miners and enslaved Africans, funding gilded Baroque churches.",
"gold mining;gilding",
"church interior",
"exchange and value;ritual and belief",
"historians",
"enslaved African miners and craftsmen",
"human-flow",
"BNDigital (Biblioteca Nacional do Brasil); Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"links: POL072; DIA008.",
"canon_events.csv"
],
[
"OCC090",
"Calico Act (1700)",
"An Act for the more effectual employing the poor...",
"event",
"Time",
"F1.11;F1.9;F1.13",
"EU-BLC;AS-SAS",
"1700",
"1774",
"passed 1700, in force 1701; superseded 1721; repealed 1774",
"English law banned imports of printed, painted or dyed calicoes from Persia, China and the East Indies, protecting wool and silk and encouraging printing on imported plain cloth in England.",
"cotton printing;mordant dyeing;woodblock printing",
"chintz;palampore",
"clothing and adornment;exchange and value",
"English Parliament",
"Indian dyers and printers who lost a market",
"none",
"Met Open Access (CC0); Yale Center for British Art (public-domain images); Wikimedia Commons",
"R1",
"F1.14;F1.18;F1.13",
"high",
"links: NET055; INS030. Pair with OCC093.",
"canon_events.csv"
],
[
"OCC091",
"Coke smelting at Coalbrookdale (1709)",
"Abraham Darby's coke-fired furnace",
"event",
"Time",
"F1.11",
"EU-BLC",
"1709",
"1709",
"1709",
"Abraham Darby smelted iron with coke instead of charcoal, which later made cheap cast iron pots, rails and bridges possible.",
"coke smelting;iron casting",
"cast-iron pot;bridge",
"tools;food and storage",
"historians of industry",
"colliers and ironworkers",
"none",
"Science Museum Group Collection (link-out); Yale Center for British Art (public-domain images)",
"R2",
"F1.19",
"high",
"links: INV089.",
"canon_events.csv"
],
[
"OCC092",
"Statute of Anne (1710)",
"Copyright Act 1710",
"event",
"Time",
"F1.11",
"EU-BLC",
"1710",
"1710",
"1710",
"The first British copyright statute gave authors rather than printers a limited term of rights in books.",
"printing;bookmaking",
"book",
"record and writing;exchange and value",
"British Parliament",
"printers, engravers and designers, not covered until later acts",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R2",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC093",
"Calico Act (1721)",
"7 Geo. I c. 7",
"event",
"Time",
"F1.11;F1.9;F1.13",
"EU-BLC;AS-SAS",
"1721",
"1774",
"passed 1721, in force 1722; repealed 1774 (Manchester Act)",
"English law banned the wearing and household use of most printed calicoes, while fustians and muslins stayed legal, steering the growth of British cotton manufacture.",
"cotton printing;fustian",
"chintz;fustian",
"clothing and adornment",
"English Parliament; wool and silk weavers' protests",
"Indian cloth producers",
"none",
"Met Open Access (CC0); Yale Center for British Art (public-domain images); Wikimedia Commons",
"R2",
"F1.14;F1.18",
"high",
"links: NET055. Spitalfields weavers attacked calico-wearers in 1719–20.",
"canon_events.csv"
],
[
"OCC094",
"Afghan sack of Isfahan (1722)",
"siege of Isfahan",
"event",
"Time",
"F1.10",
"WA-IRN",
"1722",
"1722",
"March–October 1722",
"The siege and fall of Isfahan to Afghan forces ended Safavid court patronage of carpets, textiles and painting.",
"carpet weaving;painting",
"carpet;manuscript",
"war;rule and display",
"historians",
"the people who starved during the siege",
"conflict-looting",
"Met Open Access (CC0)",
"R3",
"F1.19a",
"high",
"links: POL236; SCH021.",
"canon_events.csv"
],
[
"OCC095",
"İbrahim Müteferrika's press (1727)",
"first Ottoman Turkish printing press using Arabic type",
"event",
"Time",
"F1.10",
"WA-ANA",
"1727",
"1742",
"licensed 1727; about 17 titles printed to 1742",
"A licence from the sultan let İbrahim Müteferrika print books in Ottoman Turkish with movable Arabic type in Istanbul.",
"typefounding;printing;engraving",
"printed book;map",
"record and writing",
"Ottoman state; historians",
"Jewish, Armenian and Greek printers active in Istanbul earlier",
"none",
"Wikimedia Commons; Digital Library of the Middle East",
"R2",
"F1.5",
"high",
"links: INV043. The claimed earlier Ottoman \"print ban\" is debated.",
"canon_events.csv"
],
[
"OCC096",
"Engraving Copyright Act (1735)",
"Hogarth's Act",
"event",
"Time",
"F1.11",
"EU-BLC",
"1735",
"1735",
"1735",
"After campaigning by Hogarth and others, British law gave engravers copyright in their designs.",
"engraving;printmaking",
"print",
"record and writing;exchange and value",
"British Parliament",
"engravers working from others' designs, less protected",
"none",
"Yale Center for British Art (public-domain images); official text of the law (government legislation site; link-out)",
"R3",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC097",
"Herculaneum and Pompeii excavations (1738–1748)",
"Bourbon excavations",
"event",
"Time",
"F1.11",
"EU-GRR",
"1738",
"1860",
"Herculaneum from 1738; Pompeii from 1748",
"Royal excavations recovered Roman furniture, bronzes and wall paintings, whose publication fed Neoclassical design.",
"fresco;bronze;excavation",
"wall painting;tripod;furniture",
"rule and display",
"Bourbon court of Naples; archaeologists",
"the diggers and the damage done",
"funerary",
"Wikimedia Commons; public-domain primary texts; Met Open Access (CC0)",
"R2",
"F1.2;F1.28",
"high",
"links: STY026. See OCC017.",
"canon_events.csv"
],
[
"OCC098",
"Nader Shah's sack of Delhi (1739)",
"capture of the Peacock Throne",
"event",
"Time",
"F1.9;F1.10",
"AS-SAS;WA-IRN",
"1739",
"1739",
"March 1739",
"Nader Shah looted Delhi and took the Mughal treasury, including the Peacock Throne and major gems, to Iran.",
"goldsmithing;gem setting",
"throne;gem",
"rule and display;war",
"historians",
"the people killed in the massacre",
"conflict-looting",
"public-domain primary texts; Wikimedia Commons",
"R3",
"F1.19a;F1.24",
"high",
"links: POL197.",
"canon_events.csv"
],
[
"OCC099",
"Lisbon earthquake (1755)",
"Great Lisbon earthquake",
"event",
"Time",
"F1.11",
"EU-IBE",
"1755",
"1755",
"1 November 1755",
"After the earthquake and fire, Lisbon was rebuilt with the Pombaline timber cage (gaiola) for quake resistance and standard building parts.",
"timber frame;azulejo;building standardisation",
"gaiola;azulejo",
"shelter",
"historians; engineers",
"the poor displaced by the new plan",
"none",
"Wikimedia Commons; Europeana (per-item rights)",
"R2",
"F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC100",
"Battle of Plassey (1757)",
"East India Company rule in Bengal",
"event",
"Time",
"F1.9",
"AS-SAS",
"1757",
"1757",
"June 1757",
"The Company's victory gave it control over Bengal's revenue and weaving districts, where it forced weavers into fixed contracts.",
"handloom weaving;muslin",
"muslin;calico",
"exchange and value;war",
"historians",
"the weavers, spinners and dyers",
"human-flow",
"British Library public-domain images (Flickr Commons); Yale Center for British Art (public-domain images)",
"R2",
"F1.13;F1.23",
"high",
"links: INS030; POL200. \"Coerced weavers\" follows Company records; degree debated.",
"canon_events.csv"
],
[
"OCC101",
"Spinning jenny (c. 1764)",
"Hargreaves's jenny",
"event",
"Time",
"F1.11",
"EU-BLC",
"1764",
"1770",
"approx.; patent 1770",
"James Hargreaves's multi-spindle wheel let one spinner work many threads, moving spinning from single wheels to machines.",
"spinning",
"spinning jenny",
"clothing and adornment;tools",
"historians of industry",
"women hand-spinners who lost work",
"none",
"Science Museum Group Collection (link-out); Wikimedia Commons",
"R2",
"F1.19;F1.18",
"high",
"",
"canon_events.csv"
],
[
"OCC102",
"Konbaung sack of Ayutthaya (1767)",
"fall of Ayutthaya",
"event",
"Time",
"F1.9",
"AS-MSE",
"1767",
"1767",
"April 1767",
"Burmese forces destroyed Ayutthaya and took artisans, dancers and scholars to Burma.",
"lacquer;bronze;building",
"temple;image",
"war;ritual and belief",
"Thai and Burmese chronicles; historians",
"the deported artisans",
"human-flow;conflict-looting;sacred",
"Wikimedia Commons",
"R3",
"F1.19a;F1.13",
"high",
"links: DYN065; POL213.",
"canon_events.csv"
],
[
"OCC103",
"Cook's voyages (1768–1779)",
"Endeavour, Resolution and Discovery voyages",
"event",
"Time",
"F1.12;F1.13",
"OC-POL;OC-AUS;OC-MEL;AM-NWC",
"1768",
"1780",
"three voyages 1768–1780",
"Collections made on Cook's voyages sent Pacific barkcloth, featherwork and carvings to European museums, often without clear consent.",
"collecting;barkcloth;featherwork",
"barkcloth;feather cloak;carving",
"rule and display",
"British Admiralty; historians",
"Pacific makers and exchange partners",
"Indigenous-community;conflict-looting",
"Te Papa Collections Online (per-item; taonga restricted); Wikimedia Commons; collection search link-out only",
"R2",
"F1.24;F1.13",
"high",
"links: TXT125; CIV090.",
"canon_events.csv"
],
[
"OCC104",
"Water frame and Cromford Mill (1769–1771)",
"Arkwright's water frame",
"event",
"Time",
"F1.11",
"EU-BLC",
"1769",
"1771",
"patent 1769; mill 1771",
"Richard Arkwright's water-powered spinning frame and mill at Cromford set the model of the factory with shifts and child workers.",
"water power;spinning;factory",
"water frame",
"clothing and adornment;tools",
"historians of industry",
"child workers and the inventors Arkwright borrowed from",
"none",
"Science Museum Group Collection (link-out); Yale Center for British Art (public-domain images)",
"R2",
"F1.19;F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC105",
"Siku quanshu and the literary inquisition (1772–1782)",
"Complete Library of the Four Treasuries",
"event",
"Time",
"F1.8",
"AS-CHN",
"1772",
"1782",
"1772–1782",
"The Qianlong emperor's great manuscript compilation also led to the banning and burning of thousands of titles judged hostile.",
"manuscript copying;bookbinding",
"book",
"record and writing;rule and display",
"Qing state",
"the many copyists",
"none",
"Chinese Text Project (link-out); National Palace Museum Taipei Open Data (CC BY 4.0)",
"R3",
"F1.24;F1.28",
"high",
"links: POL169.",
"canon_events.csv"
],
[
"OCC106",
"Túpac Amaru II rebellion and ban on Inca dress (1780–1781)",
"Great Rebellion",
"event",
"Time",
"F1.7",
"AM-AND",
"1780",
"1781",
"rebellion 1780–81; bans 1781",
"After the rebellion, Spanish officials banned Inca noble dress, portraits of Inca kings and other emblems of Inca descent.",
"tapestry weaving;painting",
"unku;portrait",
"clothing and adornment;rule and display",
"Spanish colonial authorities; historians",
"Andean nobles who hid their textiles",
"Indigenous-community",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.24;F1.17",
"high",
"links: STY066; SCH004. Orders issued by Visitador Areche.",
"canon_events.csv"
],
[
"OCC107",
"Calico Printers' Act (1787)",
"Designing and Printing of Linens Act",
"event",
"Time",
"F1.11",
"EU-BLC",
"1787",
"1787",
"1787",
"British law gave textile print designers two months' copyright, the first design right for patterns.",
"cotton printing;pattern design",
"printed textile",
"clothing and adornment",
"British Parliament",
"designers in pattern shops",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.14;F1.18",
"high",
"",
"canon_events.csv"
],
[
"OCC108",
"Wedgwood anti-slavery medallion (1787)",
"\"Am I Not a Man and a Brother?\"",
"event",
"Time",
"F1.11;F1.13",
"EU-BLC",
"1787",
"1787",
"1787",
"Josiah Wedgwood's factory produced a jasperware medallion of a kneeling enslaved man for the abolition campaign, an early mass-made campaign object.",
"jasperware;moulding",
"medallion",
"rule and display",
"abolitionists (Society for Effecting the Abolition of the Slave Trade)",
"the self-image of enslaved people",
"human-flow",
"Met Open Access (CC0); Smithsonian Open Access (CC0 where designated); Wikimedia Commons",
"R2",
"F1.21;F1.17",
"high",
"links: NET035. Designer attributed to Henry Webber or William Hackwood.",
"canon_events.csv"
],
[
"OCC109",
"Brookes slave ship diagram (1788)",
"Description of a Slave Ship",
"event",
"Time",
"F1.11;F1.13",
"EU-BLC;AM-CAR;AF-GUI",
"1788",
"1789",
"1788 Plymouth; 1789 London version",
"An abolitionist print showed enslaved Africans packed into the ship Brookes and was reproduced widely.",
"engraving;printing",
"broadside",
"record and writing",
"abolitionists (Plymouth and London committees)",
"the voices of enslaved people",
"human-flow",
"Library of Congress (per-item rights; many public domain); British Library public-domain images (Flickr Commons)",
"R2",
"F1.21;F1.28",
"high",
"links: NET035; SV.",
"canon_events.csv"
],
[
"OCC110",
"US Patent Act (1790)",
"Patent Act of 1790",
"event",
"Time",
"F1.7",
"AM-EWD",
"1790",
"1790",
"April 1790",
"The first US federal patent law set up examined patents for useful inventions.",
"invention",
"patent model",
"tools;exchange and value",
"US Congress",
"enslaved inventors, who could not hold patents",
"human-flow",
"US National Archives Catalog; Smithsonian Open Access (CC0 where designated)",
"R3",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC111",
"Abolition of guilds in France (1791)",
"Allarde decree; Le Chapelier Law",
"event",
"Time",
"F1.11",
"EU-WCE",
"1791",
"1791",
"March and June 1791",
"Revolutionary laws abolished the craft guilds and banned workers' combinations, opening trades to anyone with a licence.",
"none specific",
"none specific",
"tools",
"French National Assembly",
"journeymen's associations (compagnonnage)",
"none",
"public-domain primary texts",
"R3",
"F1.17;F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC112",
"Cotton gin (1793)",
"Whitney's cotton gin",
"event",
"Time",
"F1.7",
"AM-EWD",
"1793",
"1794",
"built 1793; patent 1794",
"The cotton gin made short-staple cotton profitable to clean, driving the expansion of slavery in the US South and raw cotton for mills.",
"ginning",
"cotton gin;raw cotton",
"clothing and adornment;tools",
"historians",
"the enslaved people who grew and picked cotton; earlier gins",
"human-flow",
"Smithsonian Open Access (CC0 where designated); US National Archives Catalog",
"R2",
"F1.19;F1.23",
"high",
"links: NET056.",
"canon_events.csv"
],
[
"OCC113",
"Opening of the Louvre (1793)",
"Muséum central des arts",
"event",
"Time",
"F1.11",
"EU-WCE",
"1793",
"1793",
"10 August 1793",
"The revolutionary state opened royal and church collections to the public, the model for national museums fed later by conquest.",
"display",
"painting;sculpture",
"rule and display",
"French revolutionary state",
"the confiscated owners and later the looted",
"conflict-looting",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC114",
"Napoleonic art seizures (1796–1815)",
"Treaty of Tolentino confiscations",
"event",
"Time",
"F1.11",
"EU-WCE;EU-GRR",
"1796",
"1815",
"1796–1815",
"French armies took paintings, sculpture and manuscripts from Italy, the Low Countries and elsewhere to Paris under treaty terms.",
"display",
"painting;sculpture;manuscript",
"rule and display;war",
"French state; historians",
"the places stripped of works",
"conflict-looting",
"public-domain primary texts; Wikimedia Commons",
"R2",
"F1.24;F1.19a",
"high",
"Many works were returned in 1815, with Antonio Canova negotiating for the Papal States.",
"canon_events.csv"
],
[
"OCC115",
"French campaign in Egypt (1798–1801)",
"Description de l'Égypte",
"event",
"Time",
"F1.6;F1.11",
"AF-EGY",
"1798",
"1829",
"campaign 1798–1801; publication 1809–1829",
"Napoleon's scholars surveyed Egypt and published the Description de l'Égypte, which fed the Egyptian Revival.",
"engraving;survey",
"plate volume",
"record and writing",
"French state; savants",
"Egyptian scholars and workers",
"conflict-looting",
"Internet Archive (public-domain texts); Wikimedia Commons",
"R2",
"F1.2;F1.28",
"high",
"links: STY028.",
"canon_events.csv"
],
[
"OCC116",
"Siege of Seringapatam (1799)",
"fall of Srirangapatna",
"event",
"Time",
"F1.9",
"AS-SAS",
"1799",
"1799",
"May 1799",
"British forces killed Tipu Sultan and looted his palace, sending arms, textiles and Tipu's Tiger to Britain.",
"arms making;woodcarving",
"Tipu's Tiger;sword;tent",
"war;rule and display",
"British army; historians",
"Mysore's makers and courts",
"conflict-looting",
"Wikimedia Commons; Yale Center for British Art (public-domain images)",
"R2",
"F1.24;F1.19a",
"high",
"links: POL199.",
"canon_events.csv"
],
[
"OCC117",
"Capitulation of Alexandria and the Rosetta Stone (1801)",
"Article 16 transfer",
"event",
"Time",
"F1.6;F1.11",
"AF-EGY;EU-BLC",
"1801",
"1802",
"1801; arrived London 1802",
"Under the French surrender in Egypt, antiquities including the Rosetta Stone passed to Britain.",
"stone carving",
"stele",
"record and writing",
"British and French states",
"Egyptian claims to the stone",
"conflict-looting",
"Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: INS051.",
"canon_events.csv"
],
[
"OCC118",
"Elgin's removal of the Parthenon sculptures (1801–1812)",
"Parthenon marbles",
"event",
"Time",
"F1.11",
"EU-GRR;EU-BLC",
"1801",
"1816",
"removed 1801–1812; bought by Parliament 1816",
"Lord Elgin's agents removed about half the surviving Parthenon sculptures to Britain, and Greece's return request (formal since 1983) is still unresolved.",
"marble carving",
"frieze;metope;pediment figure",
"ritual and belief;rule and display",
"British Parliament; Greek state",
"the Ottoman-era Athenian view",
"conflict-looting",
"Wikimedia Commons; public-domain primary texts",
"R1",
"F1.24",
"high",
"links: INS051; POL117. Legality of Elgin's firman disputed.",
"canon_events.csv"
],
[
"OCC119",
"Luddite machine-breaking (1811–1816)",
"Luddites",
"event",
"Time",
"F1.11",
"EU-BLC",
"1811",
"1816",
"1811–1816; Frame Breaking Act 1812",
"Textile workers smashed stocking frames and shearing machines that cut wages or skill, and Parliament made frame-breaking a capital crime.",
"framework knitting;cloth finishing",
"stocking frame",
"clothing and adornment;tools",
"historians; Parliament",
"the workers' own aims beyond \"anti-machine\"",
"none",
"British Library public-domain images (Flickr Commons); public-domain primary texts",
"R2",
"F1.19;F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC120",
"Iconoclasm in the Society and Austral Islands (1815–1820s)",
"burning of \"idols\"",
"event",
"Time",
"F1.12",
"OC-POL",
"1815",
"1825",
"approx.",
"After conversions, islanders under missionary influence burned or gave up god images, some sent to London as trophies of conversion.",
"woodcarving;sennit",
"god image;toʻo",
"ritual and belief",
"London Missionary Society; historians",
"Islanders' own reasons for conversion",
"sacred;Indigenous-community",
"collection search link-out only",
"R3",
"F1.16;F1.24",
"medium",
"links: POL087. Rurutu islanders gave up A'a and other figures to LMS missionaries on Ra'iatea in August 1821; A'a reached London in 1822.",
"canon_events.csv"
],
[
"OCC121",
"French Artistic Mission to Brazil (1816)",
"Missão Artística Francesa",
"event",
"Time",
"F1.7;F1.11",
"AM-LAT",
"1816",
"1826",
"1816; Academy opened 1826",
"French artists invited to Rio de Janeiro founded academic art teaching in Brazil.",
"painting;architecture;engraving",
"painting;print",
"rule and display",
"Portuguese crown in Brazil; historians",
"Afro-Brazilian craftsmen already working in Rio",
"none",
"BNDigital (Biblioteca Nacional do Brasil); Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL072.",
"canon_events.csv"
],
[
"OCC122",
"Abolition of the kapu system (1819)",
"ʻAi Noa",
"event",
"Time",
"F1.12",
"OC-POL",
"1819",
"1819",
"1819",
"After Kamehameha I's death, rulers ended the kapu system and many heiau images were destroyed or hidden.",
"woodcarving;featherwork",
"kiʻi;feather image",
"ritual and belief",
"Hawaiian rulers (Liholiho, Kaʻahumanu); historians",
"Hawaiians who kept images",
"sacred;Indigenous-community",
"Smithsonian Open Access (CC0 where designated); Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: BEL052; POL083.",
"canon_events.csv"
],
[
"OCC123",
"Clothing law of Mahmud II (1829)",
"introduction of the fez",
"event",
"Time",
"F1.10",
"WA-ANA;EU-BYZ",
"1829",
"1829",
"1829",
"Ottoman law replaced turbans with the fez for officials, spreading fez-making and European tailoring.",
"felting;tailoring",
"fez;frock coat",
"clothing and adornment;rule and display",
"Ottoman state",
"women's dress, not covered",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC124",
"Cultivation System (1830–1870)",
"Cultuurstelsel",
"event",
"Time",
"F1.9;F1.11",
"AS-ISE",
"1830",
"1870",
"1830; phased out from 1870",
"The Dutch forced Javanese villages to grow indigo, sugar and coffee for export.",
"indigo;sugar",
"dye;sugar",
"exchange and value",
"Dutch colonial state; historians",
"the Javanese villagers",
"human-flow",
"Rijksmuseum (CC0/PDM); Tropenmuseum images on Wikimedia Commons (CC BY-SA)",
"R3",
"F1.23;F1.22",
"high",
"links: POL223.",
"canon_events.csv"
],
[
"OCC125",
"Indian Removal Act and the Trail of Tears (1830–1839)",
"forced removals",
"event",
"Time",
"F1.7",
"AM-EWD",
"1830",
"1839",
"Act 1830; removals to 1839",
"US removal of Cherokee, Muscogee, Choctaw, Chickasaw and Seminole peoples tore makers from lands and materials.",
"basketry;pottery",
"basket;pottery",
"shelter;care and access",
"US Congress; historians",
"those who resisted or hid",
"human-flow;Indigenous-community",
"US National Archives Catalog; Library of Congress (per-item rights; many public domain)",
"R3",
"F1.19a",
"high",
"links: POL065.",
"canon_events.csv"
],
[
"OCC126",
"Slavery Abolition Act (1833)",
"abolition in British colonies",
"event",
"Time",
"F1.11;F1.7;F1.6",
"EU-BLC;AM-CAR;AF-SOU",
"1833",
"1838",
"passed 1833; in force 1834; \"apprenticeship\" to 1838",
"British law ended slavery in most colonies, paid compensation to enslavers and brought in indentured labour.",
"none specific",
"none specific",
"rule and display",
"British Parliament",
"the formerly enslaved, who got nothing",
"human-flow",
"official text of the law (government legislation site; link-out); SlaveVoyages (historical data public domain)",
"R3",
"F1.23",
"high",
"links: DIA009.",
"canon_events.csv"
],
[
"OCC127",
"First Opium War and Treaty of Nanjing (1839–1842)",
"First Anglo-Chinese War",
"event",
"Time",
"F1.8;F1.11",
"AS-CHN",
"1839",
"1842",
"1839–1842",
"The war opened five treaty ports and ceded Hong Kong, reorganising the old Canton trade in export painting, porcelain and silk.",
"export painting;porcelain",
"export painting",
"war;exchange and value",
"historians",
"Chinese opium users and traders",
"conflict-looting",
"public-domain primary texts; Rijksmuseum (CC0/PDM)",
"R2",
"F1.13;F1.19a",
"high",
"links: INS021; POL169.",
"canon_events.csv"
],
[
"OCC128",
"Treaty of Waitangi (1840)",
"Te Tiriti o Waitangi",
"event",
"Time",
"F1.12",
"OC-POL",
"1840",
"1840",
"6 February 1840",
"The treaty between the British Crown and Māori chiefs guaranteed Māori authority over their taonga, the basis for later claims over carvings, designs and knowledge.",
"none specific",
"taonga",
"rule and display",
"British Crown; Māori rangatira; Waitangi Tribunal (from 1975)",
"the differences between the English and Māori texts",
"Indigenous-community",
"DigitalNZ; Te Papa Collections Online (per-item; taonga restricted)",
"R2",
"F1.24;F1.26",
"high",
"links: POL091; OCC255.",
"canon_events.csv"
],
[
"OCC129",
"Tenpō reforms (1841–1843)",
"Tenpō no kaikaku",
"event",
"Time",
"F1.8",
"AS-JPN",
"1841",
"1843",
"1841–1843",
"Shogunal reforms banned luxury and restricted prints of kabuki actors and courtesans, pushing ukiyo-e artists to new subjects.",
"woodblock printing",
"ukiyo-e print",
"clothing and adornment;record and writing",
"Tokugawa shogunate (Mizuno Tadakuni)",
"censored publishers",
"none",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0); Art Institute of Chicago (CC0 public-domain works)",
"R2",
"F1.17",
"high",
"links: STY148.",
"canon_events.csv"
],
[
"OCC130",
"Irish Famine and crochet relief (1845–1852)",
"Great Hunger",
"event",
"Time",
"F1.11",
"EU-BLC",
"1845",
"1852",
"1845–1852",
"During the famine, schemes taught women crochet and lace so they could earn, the start of \"Irish crochet\".",
"crochet;lacemaking",
"crochet lace",
"clothing and adornment",
"historians",
"the women makers",
"human-flow",
"collection search link-out only",
"R3",
"F1.18;F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC131",
"Fortune's tea smuggling (1848–1851)",
"transfer of tea plants to India",
"event",
"Time",
"F1.8;F1.9;F1.13",
"AS-CHN;AS-SAS",
"1848",
"1851",
"1848–1851",
"Robert Fortune took tea plants, seeds and workers from China to India for the East India Company.",
"tea processing",
"tea",
"food and storage",
"historians",
"the Chinese workers who went",
"none",
"Wellcome Collection; British Library public-domain images (Flickr Commons)",
"R3",
"F1.14;F1.13",
"high",
"links: NET059.",
"canon_events.csv"
],
[
"OCC132",
"Treaty of Lahore and the Koh-i-Noor (1849)",
"Koh-i-Noor diamond",
"event",
"Time",
"F1.9",
"AS-SAS",
"1849",
"1852",
"1849; recut 1852",
"The Koh-i-Noor passed to Queen Victoria under the Treaty of Lahore and was recut in 1852.",
"gem cutting",
"diamond",
"rule and display",
"British state",
"India, Pakistan and Afghanistan's claims",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: POL198.",
"canon_events.csv"
],
[
"OCC133",
"Perry expeditions and the opening of Japan (1853–1858)",
"Treaty of Kanagawa (1854); Harris Treaty (1858)",
"event",
"Time",
"F1.8;F1.7",
"AS-JPN",
"1853",
"1858",
"Perry's visits 1853 and 1854; commercial treaty 1858",
"US naval pressure forced Japan to open ports, and the export of lacquer, ceramics, fans and prints that followed fed Japonisme in Europe and America.",
"lacquer;ceramics;woodblock printing",
"print;fan;lacquerware",
"exchange and value;transport",
"US and Tokugawa states; historians",
"Japanese merchants and makers who shaped the export trade",
"none",
"Library of Congress (per-item rights; many public domain); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.13;F1.2",
"high",
"links: STY030; POL183; INS025.",
"canon_events.csv"
],
[
"OCC134",
"Bessemer process (1856)",
"Bessemer converter",
"event",
"Time",
"F1.11",
"EU-BLC",
"1856",
"1856",
"announced 1856",
"Henry Bessemer's converter blew air through molten pig iron to make cheap steel in bulk, used for rails, ships and later building frames.",
"steelmaking;converter",
"rail;beam;ship plate",
"shelter;transport;tools",
"historians of technology",
"William Kelly's parallel US work and older Asian crucible and co-fusion steels",
"none",
"Science Museum Group Collection (link-out); Wikimedia Commons",
"R2",
"F1.19",
"high",
"links: INV090.",
"canon_events.csv"
],
[
"OCC135",
"Perkin's mauve (1856)",
"mauveine",
"event",
"Time",
"F1.11",
"EU-BLC",
"1856",
"1857",
"discovered 1856; factory 1857",
"William Perkin's aniline dye, found while trying to make quinine, began the coal-tar dye industry that displaced plant and insect dyes and the dyers who worked with them.",
"synthetic dye;coal tar",
"dyed silk;dyed wool",
"clothing and adornment",
"historians of chemistry",
"natural-dye growers and dyers worldwide",
"none",
"Science Museum Group Collection (link-out); Met Open Access (CC0); Wikimedia Commons",
"R1",
"F1.19;F1.18",
"high",
"Pair with alizarin (1868–69) and indigo (1897) rows.",
"canon_events.csv"
],
[
"OCC136",
"Indian uprising and the looting of Delhi and Lucknow (1857–1858)",
"1857 rebellion",
"event",
"Time",
"F1.9",
"AS-SAS",
"1857",
"1858",
"1857–1858",
"After retaking Delhi and Lucknow, British troops looted palaces and houses, and Mughal manuscripts, jewels and arms entered British collections.",
"goldsmithing;manuscript painting;arms making",
"manuscript;jewellery;arms",
"war;rule and display",
"historians",
"the many Indians killed in reprisals",
"conflict-looting",
"British Library public-domain images (Flickr Commons); Wikimedia Commons",
"R2",
"F1.24;F1.19a",
"high",
"links: POL197; POL201.",
"canon_events.csv"
],
[
"OCC137",
"Indigo revolt (1859–1860)",
"Nil Bidroho",
"event",
"Time",
"F1.9",
"AS-SAS",
"1859",
"1860",
"1859–1860",
"Bengal peasants refused to grow indigo under European planters' coercive contracts, and the protest weakened the Bengal indigo system before synthetic indigo ended it.",
"indigo cultivation;dye processing",
"indigo cake",
"clothing and adornment",
"historians; the play Nil Darpan (1860)",
"the peasants, especially women, in planters' records",
"human-flow",
"British Library public-domain images (Flickr Commons)",
"R3",
"F1.23;F1.18",
"high",
"links: OCC176.",
"canon_events.csv"
],
[
"OCC138",
"Looting of the Summer Palace (1860)",
"Yuanmingyuan looting and burning",
"event",
"Time",
"F1.8;F1.11",
"AS-CHN",
"1860",
"1860",
"October 1860",
"British and French troops looted and then burned the Yuanmingyuan in Beijing, and its enamels, jades, porcelain and bronze zodiac heads went to European collections and markets.",
"cloisonné;jade carving;porcelain;bronze casting",
"cloisonné;jade;zodiac head",
"rule and display;war",
"historians",
"Chinese palace staff and craftsmen; China's continuing claims",
"conflict-looting",
"Wikimedia Commons; public-domain primary texts",
"R1",
"F1.24;F1.19a",
"high",
"links: POL169. Context: Second Opium War (1856–1860).",
"canon_events.csv"
],
[
"OCC139",
"Cotton famine (1861–1865)",
"Lancashire cotton famine",
"event",
"Time",
"F1.11;F1.7;F1.9;F1.6",
"EU-BLC;AM-EWD;AS-SAS;AF-EGY",
"1861",
"1865",
"1861–1865",
"The US Civil War cut raw cotton to Lancashire mills, throwing mill workers out of work and pushing cotton growing in India and Egypt.",
"cotton spinning;cotton cultivation",
"cotton cloth",
"clothing and adornment",
"historians",
"the enslaved growers whose labour supplied the pre-war mills",
"human-flow",
"British Library public-domain images (Flickr Commons); Library of Congress (per-item rights; many public domain)",
"R2",
"F1.19;F1.13",
"high",
"links: NET056.",
"canon_events.csv"
],
[
"OCC140",
"Blackbirding in the Pacific (1863–1904)",
"Pacific labour trade",
"event",
"Time",
"F1.12",
"OC-MEL;OC-AUS;OC-POL",
"1863",
"1904",
"1863–1904",
"Recruiters took Islanders, often by deception or force, to work on Queensland and Fijian plantations, taking makers out of their communities.",
"plantation labour",
"none specific",
"care and access",
"historians; Pacific Islander descendants",
"the Islanders' own accounts",
"human-flow",
"Trove (link-out); Wikimedia Commons",
"R3",
"F1.23",
"high",
"Deportations under the Pacific Island Labourers Act 1901 ended it.",
"canon_events.csv"
],
[
"OCC141",
"Long Walk of the Navajo (1864–1868)",
"Bosque Redondo",
"event",
"Time",
"F1.7",
"AM-WST",
"1864",
"1868",
"1864–1868",
"US forced removal of the Navajo to Bosque Redondo led weavers to use commercial yarns and trade goods, and later reservation trading posts reshaped Navajo weaving for the market.",
"weaving;commercial yarn",
"blanket;rug",
"clothing and adornment",
"US state; Diné historians",
"those who died on the walk",
"human-flow;Indigenous-community",
"US National Archives Catalog; Smithsonian Open Access (CC0 where designated)",
"R3",
"F1.18",
"high",
"links: STY078; INS013.",
"canon_events.csv"
],
[
"OCC142",
"Jiangnan Arsenal (1865)",
"Jiangnan Machine Manufacturing Bureau",
"event",
"Time",
"F1.8",
"AS-CHN",
"1865",
"1865",
"1865",
"The Qing Self-Strengthening movement set up an arsenal in Shanghai to make guns and steamships, with a translation bureau for Western technical books.",
"machining;shipbuilding;translation",
"rifle;steamship;technical book",
"war;tools",
"Qing state (Zeng Guofan, Li Hongzhang)",
"the Chinese workers and foreign technicians",
"none",
"public-domain primary texts",
"R3",
"F1.19",
"high",
"links: POL169.",
"canon_events.csv"
],
[
"OCC143",
"Return of the Oegyujanggak uigwe (2011)",
"Uigwe return",
"event",
"Time",
"F1.8;F1.11",
"AS-KOR;EU-WCE",
"1866",
"2011",
"taken 1866; returned 2011 as renewable loan",
"French troops took Joseon royal protocol books from Ganghwa Island in 1866, and France returned 297 volumes to Korea on renewable loan in 2011.",
"manuscript illustration;bookbinding",
"uigwe",
"record and writing;rule and display",
"French and Korean states",
"other Korean objects still abroad",
"conflict-looting",
"Kyujanggak / Uigwe (link-out)",
"R3",
"F1.24",
"high",
"links: TXT106. Number of volumes to verify.",
"canon_events.csv"
],
[
"OCC144",
"Exposition Universelle (Paris 1867)",
"1867 Exposition",
"event",
"Time",
"F1.11;F1.8",
"EU-WCE;AS-JPN",
"1867",
"1867",
"April–November 1867",
"Japan took part officially for the first time, with Satsuma exhibiting separately, and the displays fed French Japonisme.",
"display",
"ceramics;lacquer;print",
"rule and display",
"French state; exhibitors",
"the Japanese makers named only by region",
"none",
"Paris Musées (Open Content); Wikimedia Commons",
"R3",
"F1.15",
"high",
"links: STY030.",
"canon_events.csv"
],
[
"OCC145",
"Removal of Te Hau ki Tūranga (1867)",
"Te Hau ki Tūranga wharenui",
"event",
"Time",
"F1.12",
"OC-POL",
"1867",
"1867",
"1867",
"The Crown removed the carved meeting house Te Hau ki Tūranga, made under Raharuhi Rukupō in 1842, from Manutūke to Wellington, where it is now at Te Papa.",
"carving;kōwhaiwhai painting",
"wharenui",
"shelter;ritual and belief",
"New Zealand government; historians",
"Rongowhakaata, the house's people",
"sacred;conflict-looting;Indigenous-community",
"Te Papa Collections Online (per-item; taonga restricted)",
"R3",
"F1.24",
"medium",
"Ownership recognised in the Rongowhakaata settlement; details to verify.",
"canon_events.csv"
],
[
"OCC146",
"Alizarin synthesis (1868–1869)",
"synthetic madder",
"event",
"Time",
"F1.11",
"EU-WCE;EU-BLC",
"1868",
"1869",
"synthesis 1868; commercial 1869",
"Graebe and Liebermann's synthesis of alizarin replaced madder root, and madder growing in France and the Netherlands collapsed within a few years.",
"synthetic dye",
"Turkey red cloth",
"clothing and adornment",
"historians of chemistry",
"madder growers and Turkey-red dyers",
"none",
"Science Museum Group Collection (link-out)",
"R2",
"F1.19;F1.18",
"high",
"",
"canon_events.csv"
],
[
"OCC147",
"Maqdala (1868)",
"British expedition to Abyssinia",
"event",
"Time",
"F1.6;F1.11",
"AF-HRN",
"1868",
"1868",
"April 1868",
"After defeating Emperor Tewodros II, British troops looted Maqdala and took manuscripts, crosses, crowns and tabots to Britain.",
"manuscript;metalwork;woodcarving",
"manuscript;processional cross;tabot",
"ritual and belief;war",
"British state",
"the Ethiopian clergy and makers",
"sacred;conflict-looting",
"British Library public-domain images (Flickr Commons); Wikimedia Commons",
"R1",
"F1.24;F1.19a",
"high",
"links: POL007; OCC265.",
"canon_events.csv"
],
[
"OCC148",
"Removal of Hoa Hakananai'a (1868)",
"Rapa Nui moai in London",
"event",
"Time",
"F1.12",
"OC-POL",
"1868",
"1868",
"1868; Rapa Nui request 2018",
"Crew of HMS Topaze took the moai Hoa Hakananai'a from Rapa Nui; a Rapa Nui delegation asked for its return in 2018.",
"basalt carving",
"moai",
"ritual and belief",
"British navy; British Museum",
"the Rapa Nui, who have asked for it back",
"sacred;ancestral;Indigenous-community",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: CIV092.",
"canon_events.csv"
],
[
"OCC149",
"Separation of Shinto and Buddhism (1868)",
"shinbutsu bunri; haibutsu kishaku",
"event",
"Time",
"F1.8",
"AS-JPN",
"1868",
"1874",
"orders 1868; anti-Buddhist violence to c. 1874",
"Meiji orders to separate Shinto from Buddhism set off the destruction and sale of Buddhist images and temple treasures, many of which went abroad.",
"sculpture;metalwork",
"Buddhist image;temple furnishing",
"ritual and belief",
"Meiji state",
"the temples and villages that lost their images",
"sacred;conflict-looting",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.16;F1.24",
"high",
"links: BEL032; BEL022.",
"canon_events.csv"
],
[
"OCC150",
"Burning of the royal sampy (1869)",
"sampy",
"event",
"Time",
"F1.6",
"AF-MAD",
"1869",
"1869",
"September 1869",
"After Queen Ranavalona II's conversion, the royal sampy (talismans of the Merina monarchy) were burned.",
"wood;cloth;beads",
"sampy",
"ritual and belief",
"Merina state",
"Malagasy people who kept ancestral practice",
"sacred;Indigenous-community",
"collection search link-out only",
"R3",
"F1.16",
"high",
"links: POL018; BEL049.",
"canon_events.csv"
],
[
"OCC151",
"Ottoman antiquities regulations (1869–1884)",
"Asar-ı Atika Nizamnamesi",
"event",
"Time",
"F1.10",
"WA-ANA;WA-MES;WA-LEV",
"1869",
"1884",
"1869; 1874; 1884",
"Ottoman antiquities regulations, tightened in 1884 under Osman Hamdi Bey, made finds state property and banned export.",
"excavation",
"antiquity",
"rule and display",
"Ottoman state",
"local finders; the empire's non-Turkish peoples",
"none",
"public-domain primary texts",
"R3",
"F1.24",
"high",
"links: INS047.",
"canon_events.csv"
],
[
"OCC152",
"Suez Canal (1869)",
"opening of the Suez Canal",
"event",
"Time",
"F1.6;F1.13",
"AF-EGY",
"1869",
"1869",
"November 1869",
"The canal cut the sea route between Europe and Asia, speeding trade in raw materials and manufactured goods.",
"civil engineering",
"ship",
"transport;exchange and value",
"historians",
"the Egyptian corvée workers who dug it",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_events.csv"
],
[
"OCC153",
"Ban on Ainu tattooing and earrings (1871)",
"Kaitakushi prohibition",
"event",
"Time",
"F1.8",
"AS-JPN",
"1871",
"1871",
"1871; reissued 1876",
"Japan's Hokkaido Development Commission banned Ainu women's tattooing and men's earrings as part of assimilation.",
"tattooing;metalwork",
"earring",
"clothing and adornment",
"Meiji state",
"Ainu, whose practices continued in secret",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.17",
"medium",
"",
"canon_events.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
