insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OCC154",
"Meiji dress and hair reforms (1871–1872)",
"dampatsurei (1871); court dress decree (1872)",
"event",
"Time",
"F1.8",
"AS-JPN",
"1871",
"1872",
"1871–1872",
"Meiji edicts allowed men to cut the topknot and made Western-style dress official court and uniform wear, creating demand for tailoring and hats.",
"tailoring;millinery",
"uniform;frock coat",
"clothing and adornment;rule and display",
"Meiji state",
"women, who kept kimono longer",
"none",
"NDL Digital Collections (public-domain items); ColBase (Japan Government Standard Terms)",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC155",
"Sagrenti War and the looting of Kumasi (1874)",
"Third Anglo-Asante War",
"event",
"Time",
"F1.6",
"AF-GUI",
"1874",
"1874",
"February 1874",
"British troops looted Kumasi and took Asante gold regalia, some auctioned in London.",
"goldsmithing;casting",
"regalia",
"rule and display;war",
"British state",
"Asante goldsmiths and court",
"conflict-looting",
"Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: POL029; OCC292.",
"canon_events.csv"
],
[
"OCC156",
"Haitōrei (1876)",
"Sword Abolition Edict",
"event",
"Time",
"F1.8",
"AS-JPN",
"1876",
"1876",
"March 1876",
"The ban on wearing swords in public ended demand for new swords, and sword-fitting makers turned to export metalwork.",
"swordsmithing;metal inlay",
"sword;tsuba;export metalwork",
"war;clothing and adornment",
"Meiji state",
"the smiths who left the trade",
"none",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.19;F1.13",
"high",
"",
"canon_events.csv"
],
[
"OCC157",
"Wickham's rubber seeds (1876)",
"transfer of Hevea seeds",
"event",
"Time",
"F1.7;F1.9;F1.13",
"AM-AMZ;AS-ISE;AS-MSE",
"1876",
"1876",
"1876",
"Henry Wickham took about 70,000 Hevea seeds from Brazil to Kew, and seedlings started rubber plantations in Southeast Asia.",
"rubber tapping",
"rubber",
"tools",
"historians",
"Indigenous knowledge of rubber",
"none",
"Wellcome Collection",
"R3",
"F1.14",
"high",
"links: INV033.",
"canon_events.csv"
],
[
"OCC158",
"Ancient Monuments Protection Act (1882)",
"UK Ancient Monuments Act",
"event",
"Time",
"F1.11",
"EU-BLC",
"1882",
"1882",
"1882",
"Britain's first heritage law listed prehistoric monuments for state guardianship, with Augustus Pitt-Rivers as first inspector.",
"conservation",
"monument",
"rule and display",
"British Parliament",
"sites not on the schedule",
"none",
"official text of the law (government legislation site; link-out); public-domain primary texts",
"R3",
"F1.24",
"high",
"links: INS053.",
"canon_events.csv"
],
[
"OCC159",
"Code of Indian Offenses (1883)",
"Religious Crimes Code",
"event",
"Time",
"F1.7",
"AM-WST;AM-EWD",
"1883",
"1934",
"1883; enforcement ended 1934",
"US rules banned Native American ceremonies, including dances and giveaways, pushing ritual making underground.",
"regalia making",
"regalia",
"ritual and belief",
"US Department of the Interior",
"the communities who kept ceremonies",
"sacred;Indigenous-community",
"US National Archives Catalog",
"R3",
"F1.16",
"high",
"links: POL078.",
"canon_events.csv"
],
[
"OCC160",
"Krakatoa eruption (1883)",
"Krakatau",
"event",
"Time",
"F1.9;F1.13",
"AS-ISE;GL",
"1883",
"1883",
"August 1883",
"News of the eruption spread worldwide by telegraph within days, and its ash coloured sunsets painted and reported far away.",
"none specific",
"none specific",
"record and writing",
"volcanologists; historians",
"the tens of thousands killed by tsunamis in Java and Sumatra",
"none",
"Wikimedia Commons; British Library public-domain images (Flickr Commons)",
"R3",
"F1.22;F1.21",
"medium",
"Link to specific paintings (e.g. Munch) is speculative; keep it general.",
"canon_events.csv"
],
[
"OCC161",
"Paris Convention (1883)",
"Paris Convention for the Protection of Industrial Property",
"event",
"Time",
"F1.13;THEME",
"GL",
"1883",
"1883",
"signed 1883; in force 1884",
"The first international treaty on patents, trademarks and industrial designs let makers claim protection across member states.",
"patent;trademark;design registration",
"patent;trademark",
"exchange and value",
"signatory states",
"colonised makers with no standing",
"none",
"UNESCO/UN instrument texts (link-out); public-domain primary texts",
"R2",
"F1.14",
"high",
"WIPO now administers it.",
"canon_events.csv"
],
[
"OCC162",
"Berlin Conference (1884–1885)",
"Congo Conference",
"event",
"Time",
"F1.6;F1.11",
"GL",
"1884",
"1885",
"November 1884–February 1885",
"European powers set rules for claiming African territory, the framework for colonial extraction of rubber, ivory and craft.",
"none specific",
"none specific",
"rule and display",
"European states",
"all African states, which were absent",
"none",
"public-domain primary texts",
"R2",
"F1.3",
"high",
"links: POL139; POL140.",
"canon_events.csv"
],
[
"OCC163",
"Potlatch ban (1884–1951)",
"Indian Act amendment",
"event",
"Time",
"F1.7",
"AM-NWC",
"1884",
"1951",
"passed 1884, in force 1885; removed 1951",
"Canadian law banned the potlatch, criminalising ceremonies where masks, coppers and regalia were made and given.",
"carving;copper working",
"mask;copper;regalia",
"ritual and belief;exchange and value",
"Canadian government",
"Kwakwakaʼwakw and other nations who continued in secret",
"sacred;Indigenous-community",
"collection search link-out only",
"R2",
"F1.16;F1.24",
"high",
"links: STY076; POL079.",
"canon_events.csv"
],
[
"OCC164",
"Third Anglo-Burmese War and the Mandalay regalia (1885)",
"fall of Mandalay",
"event",
"Time",
"F1.9",
"AS-MSE",
"1885",
"1964",
"1885; part returned 1964",
"British forces deposed King Thibaw and took the Mandalay regalia, part of which the V&A returned to Burma in 1964.",
"goldsmithing;gem setting",
"regalia",
"rule and display",
"British state",
"Burmese court makers",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: DYN065.",
"canon_events.csv"
],
[
"OCC165",
"Berne Convention (1886)",
"Berne Convention for the Protection of Literary and Artistic Works",
"event",
"Time",
"F1.13;THEME",
"GL",
"1886",
"1886",
"1886",
"The treaty extended copyright to authors and artists across member states without registration.",
"printing;illustration",
"book;print",
"record and writing",
"signatory states",
"oral and collective traditions",
"none",
"UNESCO/UN instrument texts (link-out); public-domain primary texts",
"R2",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC166",
"Hall–Héroult process (1886)",
"electrolytic aluminium",
"event",
"Time",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1886",
"1886",
"1886",
"Independent discovery of electrolytic smelting made aluminium cheap enough for household goods and aircraft.",
"electrolysis;aluminium",
"pan;aircraft",
"tools;transport",
"historians",
"bauxite miners",
"none",
"Science Museum Group Collection (link-out)",
"R2",
"F1.19;F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC167",
"Merchandise Marks Act (1887)",
"\"Made in Germany\"",
"event",
"Time",
"F1.11",
"EU-BLC;EU-WCE",
"1887",
"1887",
"1887",
"British law required foreign goods to be marked with their origin, and \"Made in Germany\" became a mark of quality.",
"marking",
"label",
"exchange and value",
"British Parliament",
"makers inside Britain who copied",
"none",
"official text of the law (government legislation site; link-out)",
"R3",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC168",
"Lei Áurea (1888)",
"Golden Law",
"event",
"Time",
"F1.7",
"AM-LAT",
"1888",
"1888",
"13 May 1888",
"Brazil abolished slavery, the last country in the Americas to do so, ending the legal basis of enslaved labour in its plantations, mines and craft workshops.",
"none specific",
"none specific",
"rule and display",
"Brazilian state",
"those freed without land or pay",
"human-flow",
"BNDigital (Biblioteca Nacional do Brasil)",
"R3",
"F1.23",
"high",
"links: DIA008.",
"canon_events.csv"
],
[
"OCC169",
"Removal and return of the Great Zimbabwe birds (1889–2026)",
"soapstone birds",
"event",
"Time",
"F1.6",
"AF-SOU",
"1889",
"2026",
"removed from 1889; four returned from South Africa 1981; pedestal from Germany (loan agreed 2000, public 2003); last bird returned from South Africa 15 April 2026",
"Soapstone birds taken from Great Zimbabwe from 1889 came back in stages, from South Africa in 1981, from Germany in 2003 and, last, from Cecil Rhodes's former house Groote Schuur in 2026, and the bird is Zimbabwe's national emblem.",
"soapstone carving",
"bird carving",
"ritual and belief",
"Zimbabwean state; historians",
"the site damaged by colonial digging",
"sacred;conflict-looting",
"Zamani Project (link-out)",
"R3",
"F1.24",
"high",
"links: POL015; CIV005. 2026 handover also returned ancestral human remains.",
"canon_events.csv"
],
[
"OCC170",
"Imperial Household Artists (1890)",
"Teishitsu Gigeiin",
"event",
"Time",
"F1.8",
"AS-JPN",
"1890",
"1944",
"1890–1944",
"The Meiji court appointed leading artists and craftsmen as Imperial Household Artists, backing metalwork, lacquer and ceramics.",
"metalwork;lacquer;cloisonné",
"lacquer;cloisonné",
"rule and display",
"Meiji state",
"workshop assistants",
"none",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R3",
"F1.17",
"high",
"links: INS028.",
"canon_events.csv"
],
[
"OCC171",
"French conquest of Abomey (1892)",
"Dahomey war",
"event",
"Time",
"F1.6",
"AF-GUI",
"1892",
"1892",
"1892",
"French troops took the royal statues, thrones and doors of Abomey to Paris.",
"brass casting;woodcarving",
"statue;throne;door",
"rule and display;war",
"French state",
"Fon court artists",
"conflict-looting;sacred",
"Paris Musées (Open Content); collection search link-out only",
"R2",
"F1.24",
"high",
"links: POL030. 26 objects returned 2021 (see OCC286).",
"canon_events.csv"
],
[
"OCC172",
"Lombok expedition (1894)",
"Lombok treasure",
"event",
"Time",
"F1.9",
"AS-ISE",
"1894",
"1894",
"1894",
"Dutch forces looted the Cakranegara palace on Lombok, taking gold and jewellery.",
"goldsmithing",
"jewellery;kris",
"rule and display;war",
"Dutch state",
"Balinese and Sasak people",
"conflict-looting",
"Rijksmuseum (CC0/PDM); Tropenmuseum images on Wikimedia Commons (CC BY-SA)",
"R3",
"F1.24",
"high",
"links: POL223.",
"canon_events.csv"
],
[
"OCC173",
"Danballyeong (1895)",
"haircut ordinance",
"event",
"Time",
"F1.8",
"AS-KOR",
"1895",
"1895",
"1895",
"A Korean ordinance ordered men to cut the topknot, provoking protest and undermining the market for the horsehair hats (gat) and headbands worn with it.",
"hairdressing",
"topknot",
"clothing and adornment",
"Joseon state",
"women, who were not covered, and the protesters who resisted",
"none",
"KOGL Type 1 images on Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL177.",
"canon_events.csv"
],
[
"OCC174",
"Ancient Shrines and Temples Preservation Law (1897)",
"Koshaji hozonhō",
"event",
"Time",
"F1.8",
"AS-JPN",
"1897",
"1897",
"1897",
"Japan's first national heritage law funded temple repairs and created \"national treasures\".",
"conservation",
"temple;sculpture",
"rule and display",
"Meiji state",
"non-temple craft",
"sacred",
"ColBase (Japan Government Standard Terms)",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC175",
"Benin punitive expedition (1897)",
"Sack of Benin City",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI",
"1897",
"1897",
"February 1897",
"British forces looted Benin City, taking thousands of brass plaques, heads and ivories, many sold to fund the expedition.",
"brass casting;ivory carving",
"plaque;commemorative head;tusk",
"rule and display;war",
"British state",
"the Edo people, the Benin court's own records of the objects, and the guild casters who made them",
"conflict-looting;sacred;ancestral",
"Digital Benin (each lender's licence); Wikimedia Commons",
"R1",
"F1.24;F1.19a",
"high",
"links: CIV012; DYN038; POL026; INS082.",
"canon_events.csv"
],
[
"OCC176",
"Synthetic indigo (1897)",
"BASF indigo",
"event",
"Time",
"F1.11;F1.9",
"EU-WCE;AS-SAS",
"1897",
"1897",
"1897",
"BASF's synthetic indigo undercut plant indigo within two decades, collapsing indigo planting in Bengal and Bihar and changing dyers' supplies worldwide.",
"synthetic dye",
"indigo",
"clothing and adornment",
"historians",
"indigo cultivators",
"none",
"Science Museum Group Collection (link-out)",
"R2",
"F1.19;F1.18",
"high",
"",
"canon_events.csv"
],
[
"OCC177",
"Boxer war and looting of Beijing (1900)",
"Eight-Nation Alliance",
"event",
"Time",
"F1.8",
"AS-CHN",
"1900",
"1901",
"1900–1901",
"Foreign troops looted Beijing's palaces, and fire at the Hanlin Academy destroyed volumes of the Yongle Encyclopedia.",
"manuscript;porcelain",
"manuscript;porcelain",
"war",
"historians",
"Chinese Christians and Boxers killed",
"conflict-looting",
"Library of Congress (per-item rights; many public domain); Wikimedia Commons",
"R2",
"F1.24;F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC178",
"Dunhuang Library Cave opened (1900–1908)",
"Mogao Cave 17",
"event",
"Time",
"F1.8;F1.12a",
"AS-CHN;AS-CEN",
"1900",
"1908",
"found 1900; Stein 1907; Pelliot 1908",
"Wang Yuanlu found the sealed library cave, and Stein and Pelliot bought thousands of manuscripts, paintings and prints for London and Paris.",
"manuscript;woodblock printing;silk painting",
"manuscript;Diamond Sutra;banner",
"record and writing;ritual and belief",
"explorers; historians",
"Wang Yuanlu's position",
"sacred;conflict-looting",
"International Dunhuang Programme (link-out; non-commercial); British Library public-domain images (Flickr Commons)",
"R2",
"F1.24;F1.28",
"high",
"links: INV039.",
"canon_events.csv"
],
[
"OCC179",
"Phosphate mining on Banaba (1900–1979)",
"Ocean Island mining",
"event",
"Time",
"F1.12",
"OC-MIC",
"1900",
"1979",
"1900–1979; Banabans moved to Rabi, Fiji, 1945",
"Phosphate mining for Australian and New Zealand fertiliser stripped Banaba's land, and most Banabans were relocated to Rabi Island in Fiji.",
"phosphate mining",
"fertiliser",
"food and storage",
"historians; Banaban community",
"the Banabans' claims, still pursued",
"human-flow;Indigenous-community",
"collection search link-out only",
"R3",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC180",
"Younghusband expedition (1903–1904)",
"British invasion of Tibet",
"event",
"Time",
"F1.9",
"AS-HIM",
"1903",
"1904",
"1903–1904",
"British troops looted Tibetan monasteries during the invasion, sending manuscripts, thangkas and ritual objects to British collections.",
"manuscript;thangka painting;metalwork",
"manuscript;thangka;ritual object",
"war;ritual and belief",
"British state; historians",
"the Tibetans killed at Chumik Shenko",
"conflict-looting;sacred",
"British Library public-domain images (Flickr Commons)",
"R3",
"F1.24",
"high",
"links: POL205.",
"canon_events.csv"
],
[
"OCC181",
"Antiquities Act (1906)",
"US Antiquities Act",
"event",
"Time",
"F1.7",
"AM-WST",
"1906",
"1906",
"June 1906",
"US law protected archaeological sites on federal land and required permits to dig, partly to stop pot hunting in the Southwest.",
"excavation",
"pottery;site",
"rule and display",
"US Congress",
"Native nations, whose ancestors' sites were placed under federal control",
"Indigenous-community",
"US National Archives Catalog",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC182",
"Bali puputan (1906–1908)",
"Badung and Klungkung puputan",
"event",
"Time",
"F1.9",
"AS-ISE",
"1906",
"1908",
"Badung 1906; Klungkung 1908",
"Dutch attacks on the Balinese courts ended in ritual mass suicides, and court objects were taken to the Netherlands.",
"kris making;goldsmithing",
"kris;regalia",
"rule and display;war",
"Dutch state; historians",
"the Balinese court and people",
"conflict-looting",
"Tropenmuseum images on Wikimedia Commons (CC BY-SA); Rijksmuseum (CC0/PDM)",
"R3",
"F1.24",
"high",
"links: POL222.",
"canon_events.csv"
],
[
"OCC183",
"Putumayo atrocities (1907–1912)",
"Casement report",
"event",
"Time",
"F1.7",
"AM-AMZ",
"1907",
"1912",
"exposed 1907–1912",
"The Peruvian Amazon Company forced Indigenous people to collect rubber through torture and killing, exposed in Roger Casement's 1912 report.",
"rubber tapping",
"rubber",
"exchange and value",
"historians; Roger Casement",
"the Indigenous peoples themselves",
"human-flow;Indigenous-community",
"public-domain primary texts",
"R3",
"F1.22;F1.23",
"high",
"links: NET060; PRD210.",
"canon_events.csv"
],
[
"OCC184",
"Xinhai Revolution and the end of Qing dress (1911–1912)",
"Xinhai Revolution",
"event",
"Time",
"F1.8",
"AS-CHN",
"1911",
"1912",
"1911–1912",
"The fall of the Qing ended the queue and court robe system, and new dress such as the Zhongshan suit followed.",
"tailoring",
"Zhongshan suit;qipao",
"clothing and adornment",
"historians",
"women and rural people",
"none",
"Library of Congress (per-item rights; many public domain)",
"R3",
"F1.17",
"high",
"links: OCC078.",
"canon_events.csv"
],
[
"OCC185",
"Export of the Nefertiti bust (1913)",
"Nefertiti bust",
"event",
"Time",
"F1.6;F1.11",
"AF-EGY;EU-WCE",
"1912",
"1913",
"found 1912; to Germany 1913",
"The bust from the Amarna workshop of Thutmose went to Germany under a division of finds, and Egypt has asked for its return.",
"limestone;painting",
"bust",
"rule and display",
"German excavators (Borchardt)",
"Egyptian claims",
"conflict-looting",
"Staatliche Museen zu Berlin (SMB-digital); Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: STY082.",
"canon_events.csv"
],
[
"OCC186",
"Moving assembly line at Highland Park (1913)",
"Ford assembly line",
"event",
"Time",
"F1.7",
"AM-EWD",
"1913",
"1913",
"1913",
"Ford's moving assembly line at Highland Park cut the time to build a Model T and became the model for mass production.",
"assembly line;interchangeable parts",
"car",
"transport",
"historians",
"the immigrant workers who faced high turnover",
"none",
"Smithsonian Open Access (CC0 where designated); Library of Congress (per-item rights; many public domain)",
"R2",
"F1.19",
"high",
"links: INS065.",
"canon_events.csv"
],
[
"OCC187",
"Werkbund debate (1914)",
"Muthesius–van de Velde debate",
"event",
"Time",
"F1.11",
"EU-WCE",
"1914",
"1914",
"July 1914",
"At the Werkbund meeting in Cologne, Hermann Muthesius argued for standard types and Henry van de Velde for the artist's freedom.",
"standardisation",
"furniture;product",
"tools",
"Deutscher Werkbund",
"the workers who made the products",
"none",
"public-domain primary texts",
"R3",
"F1.20;F1.19",
"high",
"links: MOV011.",
"canon_events.csv"
],
[
"OCC188",
"Armenian genocide (1915–1923)",
"Medz Yeghern",
"event",
"Time",
"F1.10;F1.11",
"WA-ANA;WA-CAU",
"1915",
"1923",
"1915–1923",
"Ottoman deportations and massacres destroyed Armenian communities of weavers, silversmiths and potters; survivors carried crafts to Jerusalem, Aleppo, Beirut and beyond.",
"carpet weaving;silversmithing;ceramics",
"carpet;silverwork;tile",
"clothing and adornment",
"historians",
"the victims and their unrecorded work",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.19a;F1.13",
"high",
"Armenian potters from Kütahya in Jerusalem (from 1919).",
"canon_events.csv"
],
[
"OCC189",
"Dazzle camouflage (1917)",
"razzle dazzle",
"event",
"Time",
"F1.11",
"EU-BLC;GL",
"1917",
"1918",
"1917–1918",
"Artists led by Norman Wilkinson painted Allied ships in broken, high-contrast patterns meant to confuse enemy range-finding, turning painters and women's design teams to war work.",
"paint;pattern design;scale models",
"ship;model",
"war;transport",
"British Admiralty; historians",
"the women art students who drew most of the schemes",
"none",
"Wikimedia Commons; Internet Archive (public-domain texts)",
"R3",
"F1.19a;F1.20",
"high",
"Effectiveness was never proven.",
"canon_events.csv"
],
[
"OCC190",
"Radium dial painters (1917–1928)",
"\"Radium Girls\"",
"event",
"Time",
"F1.7",
"AM-EWD",
"1917",
"1928",
"work from 1917; key lawsuit settled 1928",
"Women painting watch dials with radium paint were told to point brushes with their lips and later sickened, and their lawsuits helped establish occupational-disease law.",
"radium paint;dial painting",
"watch dial",
"tools",
"historians; the workers' lawsuits",
"the many unnamed workers who died before any case",
"none",
"Library of Congress (per-item rights; many public domain); US National Archives Catalog",
"R3",
"F1.23;F1.22",
"high",
"US Radium Corporation (Orange, New Jersey); Radium Dial Company (Ottawa, Illinois).",
"canon_events.csv"
],
[
"OCC191",
"Propaganda porcelain (1918)",
"State Porcelain Factory, Petrograd",
"event",
"Time",
"F1.11",
"EU-EER",
"1918",
"1930",
"from 1918",
"The nationalised Imperial Porcelain Factory decorated blank imperial plates with revolutionary slogans and Suprematist designs.",
"overglaze painting;porcelain",
"plate;cup",
"food and storage;rule and display",
"Soviet state; artists (Chekhonin, Suetin, Chashnik)",
"the factory painters who executed designs",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.20;F1.19",
"high",
"links: MOV017; POL151.",
"canon_events.csv"
],
[
"OCC192",
"Boycott of foreign cloth (1920–1922)",
"Non-cooperation movement; khadi campaign",
"event",
"Time",
"F1.9",
"AS-SAS",
"1920",
"1922",
"1920–1922; bonfire in Bombay July 1921",
"Gandhi's non-cooperation campaign urged Indians to burn foreign cloth and spin and wear khadi, making hand-spinning a political act.",
"hand-spinning;handloom weaving",
"khadi;charkha",
"clothing and adornment;rule and display",
"Indian National Congress; Gandhi",
"the Indian mill workers and traders hurt by the boycott",
"none",
"Indian Culture portal (per-owner licence); Wikimedia Commons",
"R1",
"F1.18;F1.17",
"high",
"links: MOV081; POL201. See also OCC197.",
"canon_events.csv"
],
[
"OCC193",
"Exposición de Artes Populares (1921)",
"Mexican popular arts exhibition, centenary of independence",
"event",
"Time",
"F1.7",
"AM-MES;AM-LAT",
"1921",
"1921",
"September 1921",
"An exhibition in Mexico City organised by Dr Atl, Roberto Montenegro and Jorge Enciso presented Indigenous and rural crafts as national art.",
"lacquer;pottery;weaving",
"lacquer;pottery;textile",
"rule and display",
"Mexican state; artists",
"the named makers, rarely credited",
"Indigenous-community",
"INAH Mediateca (link-out); collection search link-out only",
"R3",
"F1.15;F1.29",
"high",
"links: POL076; SCH006; MOV056.",
"canon_events.csv"
],
[
"OCC194",
"Seizure of the Village Island potlatch (1921)",
"Cranmer potlatch",
"event",
"Time",
"F1.7",
"AM-NWC",
"1921",
"1980",
"seized 1921–22; returns from 1979–80",
"Police seized masks and regalia after Dan Cranmer's potlatch; returned pieces went to the U'mista Cultural Centre (1980) and Nuyumbalees.",
"carving;painting",
"mask;copper;regalia",
"ritual and belief",
"Canadian government; the ʼNamgis and Kwakwakaʼwakw",
"those pieces still held elsewhere",
"sacred;Indigenous-community",
"collection search link-out only",
"R2",
"F1.24;F1.16",
"high",
"links: OCC163.",
"canon_events.csv"
],
[
"OCC195",
"Discovery of Tutankhamun's tomb (1922)",
"KV62",
"event",
"Time",
"F1.6",
"AF-EGY",
"1922",
"1932",
"found 1922; clearance to 1932",
"Howard Carter's find set off a craze for Egyptian motifs in Art Deco design, and Egypt kept the whole contents rather than dividing them with excavators.",
"goldsmithing;cabinetmaking;faience",
"funerary mask;furniture;jewellery",
"ritual and belief;rule and display",
"Egyptian Antiquities Service; Carter and Carnarvon",
"the Egyptian workmen who did the digging",
"funerary;sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.2;F1.24",
"high",
"links: STY028; STY042; DYN004.",
"canon_events.csv"
],
[
"OCC196",
"Greek–Turkish population exchange (1923)",
"Convention of Lausanne exchange",
"event",
"Time",
"F1.11;F1.10",
"EU-BYZ;WA-ANA",
"1923",
"1923",
"1923",
"About 1.6 million people were forcibly exchanged, moving potters, weavers and carpet makers between Anatolia and Greece.",
"carpet weaving;pottery;silversmithing",
"carpet;pottery",
"clothing and adornment",
"Greek and Turkish states; League of Nations",
"the Karamanli Turkish-speaking Orthodox and Greek-speaking Muslims",
"human-flow",
"Wikimedia Commons; Europeana (per-item rights)",
"R3",
"F1.13",
"high",
"links: POL152.",
"canon_events.csv"
],
[
"OCC197",
"All-India Spinners' Association (1925)",
"Akhil Bharat Charkha Sangh",
"event",
"Time",
"F1.9",
"AS-SAS",
"1925",
"1925",
"1925",
"The association organised hand-spinners and weavers across India to produce, certify and sell khadi, paying spinners by the hank.",
"hand-spinning;handloom weaving",
"khadi",
"clothing and adornment",
"Gandhi and the Congress",
"the women spinners paid by the hank",
"none",
"Indian Culture portal (per-owner licence)",
"R3",
"F1.18;F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC198",
"Hat Law (1925)",
"Şapka Kanunu",
"event",
"Time",
"F1.10",
"WA-ANA",
"1925",
"1925",
"November 1925",
"The Turkish Republic banned the fez and required brimmed hats for men, shifting headwear making.",
"felt;millinery",
"hat;fez",
"clothing and adornment;rule and display",
"Turkish Republic",
"women and rural people",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL152.",
"canon_events.csv"
],
[
"OCC199",
"Hujum (1927)",
"Soviet unveiling campaign",
"event",
"Time",
"F1.12a",
"AS-CEN",
"1927",
"1927",
"launched March 1927",
"The Soviet campaign in Uzbekistan had women burn the paranji and chachvon veils in public.",
"weaving;horsehair",
"paranji;chachvon",
"clothing and adornment",
"Soviet state",
"the women killed in reprisals",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC200",
"Uniform Dress Law and unveiling in Iran (1928–1936)",
"Kashf-e hijab",
"event",
"Time",
"F1.10",
"WA-IRN",
"1928",
"1936",
"1928; 1936",
"Reza Shah's laws required Western dress and the Pahlavi hat for men and banned the chador in public.",
"tailoring;millinery",
"Pahlavi hat;chador",
"clothing and adornment",
"Iranian state",
"women who stopped leaving home",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: DYN023.",
"canon_events.csv"
],
[
"OCC201",
"Collapse of Gulf pearling (1929–1950s)",
"end of the pearl-diving economy",
"event",
"Time",
"F1.10",
"WA-ARB",
"1929",
"1955",
"approx.",
"The Depression and Japanese cultured pearls collapsed the Gulf pearl trade, and oil work replaced diving, boat building and pearl dealing.",
"pearl diving;dhow building",
"pearl;dhow",
"exchange and value",
"historians",
"the indebted and enslaved divers",
"human-flow",
"Qatar Digital Library (link-out)",
"R3",
"F1.22;F1.23",
"high",
"Mikimoto's cultured-pearl methods (from 1890s) in notes only.",
"canon_events.csv"
],
[
"OCC202",
"Kazakh famine and forced sedentarisation (1930–1933)",
"Asharshylyk",
"event",
"Time",
"F1.12a",
"AS-CEN",
"1930",
"1933",
"1930–1933",
"Soviet collectivisation and forced settlement killed about 1.5 million Kazakhs and broke the herding life around which felt, yurt and leather making were organised.",
"felt making;yurt building;leatherwork",
"yurt;felt",
"shelter",
"historians",
"the dead and those who fled to China",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.19a",
"high",
"Death toll estimates vary.",
"canon_events.csv"
],
[
"OCC203",
"Salt March (1930)",
"Dandi March",
"event",
"Time",
"F1.9",
"AS-SAS",
"1930",
"1930",
"March–April 1930",
"Gandhi's march to Dandi to make salt from seawater broke the British salt monopoly in public and made a simple act of making into protest.",
"salt making",
"salt",
"food and storage",
"historians; Indian National Congress",
"the salt workers of the coast",
"none",
"Indian Culture portal (per-owner licence); Wikimedia Commons",
"R3",
"F1.17",
"high",
"",
"canon_events.csv"
],
[
"OCC204",
"Mission Dakar–Djibouti (1931–1933)",
"French ethnographic mission",
"event",
"Time",
"F1.6;F1.11",
"AF-SAH;AF-HRN;AF-GUI",
"1931",
"1933",
"1931–1933",
"Marcel Griaule's mission crossed Africa collecting about 3,500 objects for Paris, some taken by pressure or theft as Michel Leiris recorded.",
"collecting",
"mask;boli;manuscript;painting",
"ritual and belief",
"French state; Musée d'Ethnographie du Trocadéro",
"the owners and communities",
"conflict-looting;sacred",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: INS054. Object count to verify.",
"canon_events.csv"
],
[
"OCC205",
"Closure of the Bauhaus (1933)",
"Bauhaus dissolution",
"event",
"Time",
"F1.11",
"EU-WCE",
"1932",
"1933",
"Dessau closed 1932; Berlin dissolved July 1933",
"Under Nazi pressure the Bauhaus closed, and its teachers and students carried its methods to the US, Britain, Palestine and elsewhere.",
"design teaching",
"furniture;textile;typography",
"tools",
"historians; Bauhaus masters",
"the women weavers and students who did not emigrate",
"human-flow",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.20;F1.13",
"high",
"links: INS057; DIA011.",
"canon_events.csv"
],
[
"OCC206",
"Soviet decree on artistic organisations (1932)",
"On the Reconstruction of Literary and Artistic Organisations",
"event",
"Time",
"F1.11;F1.12a",
"EU-EER;AS-CEN",
"1932",
"1932",
"23 April 1932",
"The Communist Party dissolved independent art groups and set up single state unions, clearing the way for Socialist Realism as the rule for art and design.",
"none specific",
"poster;painting",
"rule and display",
"Communist Party of the Soviet Union",
"the avant-garde groups dissolved",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: STY045; MOV019; POL151.",
"canon_events.csv"
],
[
"OCC207",
"Evacuation of the Palace Museum collections (1933–1949)",
"southward removal of the Forbidden City treasures",
"event",
"Time",
"F1.8",
"AS-CHN",
"1933",
"1949",
"1933–1949",
"Facing Japanese invasion, staff moved nearly 20,000 crates of the imperial collection south and west, and part went to Taiwan in 1948–49.",
"packing;conservation",
"porcelain;painting;bronze",
"rule and display",
"Palace Museum staff; Nationalist government",
"the staff and porters who moved the crates",
"conflict-looting",
"National Palace Museum Taipei Open Data (CC BY 4.0)",
"R2",
"F1.24;F1.19a",
"high",
"links: INS022; POL169.",
"canon_events.csv"
],
[
"OCC208",
"Reich Chamber of Culture (1933)",
"Reichskulturkammer",
"event",
"Time",
"F1.11",
"EU-WCE",
"1933",
"1945",
"September 1933",
"Nazi law required artists, craftspeople, designers and publishers to join a state chamber, which excluded Jewish and politically unwanted makers from working.",
"none specific",
"none specific",
"rule and display",
"Nazi state (Goebbels)",
"the excluded makers, many later murdered",
"human-flow",
"collection search link-out only",
"R3",
"F1.19a;F1.23",
"high",
"links: POL150.",
"canon_events.csv"
],
[
"OCC209",
"Machine Art (MoMA 1934)",
"Machine Art exhibition",
"event",
"Time",
"F1.7",
"AM-EWD",
"1934",
"1934",
"March–April 1934",
"Philip Johnson's exhibition presented propellers, springs and kitchenware as art, framing industrial products as design for museums.",
"machining;display",
"propeller;bearing;kitchenware",
"rule and display;tools",
"Museum of Modern Art",
"the factory workers who made the objects",
"none",
"collection search link-out only",
"R3",
"F1.15;F1.19",
"high",
"links: INS081; MOV024.",
"canon_events.csv"
],
[
"OCC210",
"International Exhibition of Chinese Art (1935–1936)",
"Burlington House Chinese exhibition",
"event",
"Time",
"F1.11;F1.8",
"EU-BLC;AS-CHN",
"1935",
"1936",
"November 1935–March 1936",
"Loans from the Palace Museum shown at the Royal Academy in London shaped Western canons of Chinese art.",
"display",
"porcelain;painting;bronze",
"rule and display",
"Royal Academy; Chinese government",
"objects not selected, and the collectors' agendas",
"none",
"collection search link-out only",
"R3",
"F1.15;F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC211",
"Iraq Antiquities Law (1936)",
"Law No. 59 of 1936",
"event",
"Time",
"F1.9a;F1.10",
"WA-MES",
"1936",
"1936",
"1936",
"Iraq's law ended the easy division of finds with foreign excavators and kept more antiquities in the country.",
"excavation",
"antiquity",
"rule and display",
"Iraqi state (Sati' al-Husri)",
"local diggers and dealers who lost income",
"none",
"Cuneiform Digital Library Initiative (link-out)",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC212",
"\"Degenerate Art\" confiscations and exhibition (1937)",
"Entartete Kunst",
"event",
"Time",
"F1.11",
"EU-WCE",
"1937",
"1941",
"confiscations 1937; exhibition Munich July 1937, touring to 1941",
"The Nazi state seized about 20,000 modern works from German museums, mocked some in a touring exhibition, and sold or burned others.",
"painting;sculpture;print",
"painting;sculpture",
"rule and display",
"Nazi state",
"the artists persecuted, many Jewish",
"conflict-looting",
"collection search link-out only",
"R2",
"F1.24;F1.19a",
"high",
"links: POL150.",
"canon_events.csv"
],
[
"OCC213",
"Axum obelisk taken and returned (1937–2005)",
"Obelisk of Axum",
"event",
"Time",
"F1.6;F1.11",
"AF-HRN",
"1937",
"2005",
"taken 1937; returned 2005; re-erected 2008",
"Fascist Italy shipped an Aksumite stele to Rome, and after decades of requests it was returned to Ethiopia.",
"stone carving",
"stele",
"ritual and belief;rule and display",
"Italian and Ethiopian states",
"Aksum's residents",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: POL006; CIV003.",
"canon_events.csv"
],
[
"OCC214",
"Mongolian purges and destruction of monasteries (1937–1939)",
"Stalinist repression in Mongolia",
"event",
"Time",
"F1.12a",
"AS-CEN",
"1937",
"1939",
"1937–1939",
"Purges killed thousands of lamas and destroyed most Buddhist monasteries with their images and workshops.",
"sculpture;appliqué;painting",
"image;thangka",
"ritual and belief",
"Mongolian People's Republic; historians",
"the monks killed",
"sacred;conflict-looting",
"collection search link-out only",
"R3",
"F1.16;F1.19a",
"high",
"links: SCH045.",
"canon_events.csv"
],
[
"OCC215",
"Paris Exposition (1937)",
"Exposition Internationale des Arts et Techniques",
"event",
"Time",
"F1.11",
"EU-WCE",
"1937",
"1937",
"1937",
"The fair set the Soviet and Nazi pavilions face to face and showed Picasso's Guernica in the Spanish Republic's pavilion.",
"exhibition",
"pavilion;painting",
"rule and display",
"French state",
"the colonial pavilions",
"none",
"Paris Musées (Open Content); Wikimedia Commons",
"R3",
"F1.15;F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC216",
"Einsatzstab Reichsleiter Rosenberg looting (1940–1945)",
"ERR",
"event",
"Time",
"F1.11",
"EU-WCE;EU-EER",
"1940",
"1945",
"1940–1945",
"The Nazi agency seized art, books, furniture and ritual objects from Jewish collectors and occupied countries, many never recovered.",
"none specific",
"painting;furniture;book;Judaica",
"rule and display;war",
"Nazi state",
"victims whose property is still unidentified",
"conflict-looting",
"collection search link-out only",
"R2",
"F1.24",
"high",
"links: OCC261.",
"canon_events.csv"
],
[
"OCC217",
"Utility Furniture Scheme (1942)",
"Utility furniture",
"event",
"Time",
"F1.11",
"EU-BLC",
"1942",
"1952",
"1942–1952",
"British wartime rules allowed only approved designs of furniture, overseen by a panel including Gordon Russell.",
"cabinetmaking;rationing",
"furniture",
"shelter",
"British Board of Trade",
"the furniture makers restricted",
"none",
"Wikimedia Commons",
"R3",
"F1.19a;F1.22a",
"high",
"",
"canon_events.csv"
],
[
"OCC218",
"Yan'an Talks on Literature and Art (1942)",
"Yan'an Forum",
"event",
"Time",
"F1.8",
"AS-CHN",
"1942",
"1942",
"May 1942",
"Mao's talks told artists to serve workers, peasants and soldiers, framing art and craft policy in the PRC.",
"woodcut;painting",
"woodcut;poster",
"rule and display",
"Mao Zedong; Chinese Communist Party",
"artists who disagreed and were purged",
"none",
"collection search link-out only",
"R3",
"F1.20",
"high",
"links: MOV090; POL171.",
"canon_events.csv"
],
[
"OCC219",
"Rebuilding of Warsaw (1945–1960s)",
"reconstruction of Warsaw Old Town",
"event",
"Time",
"F1.11",
"EU-EER",
"1945",
"1965",
"1945–1960s",
"After the city was destroyed, Poles rebuilt Warsaw's Old Town using pre-war surveys and Bellotto's paintings, making reconstruction an act of national identity.",
"masonry;painting;reconstruction",
"building",
"shelter",
"Polish state; historians",
"the residents moved out",
"none",
"Wikimedia Commons",
"R3",
"F1.28a",
"high",
"Historic Centre of Warsaw, World Heritage 1980 (verified).",
"canon_events.csv"
],
[
"OCC220",
"Bikini Atoll nuclear tests (1946–1958)",
"Operation Crossroads",
"event",
"Time",
"F1.12;F1.7",
"OC-MIC",
"1946",
"1958",
"1946–1958",
"US nuclear testing moved Bikini islanders from their atoll, and the \"bikini\" swimsuit took its name days after the first tests.",
"none specific",
"swimsuit",
"care and access",
"US state",
"Bikini islanders",
"human-flow;Indigenous-community",
"US National Archives Catalog",
"R3",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC221",
"Partition of India (1947)",
"Partition",
"event",
"Time",
"F1.9",
"AS-SAS",
"1947",
"1947",
"August 1947",
"Partition displaced millions, including artisans and weavers, and refugee craftspeople restarted work in India and Pakistan.",
"weaving;embroidery",
"phulkari",
"clothing and adornment",
"historians",
"women survivors",
"human-flow",
"Indian Culture portal (per-owner licence)",
"R2",
"F1.13;F1.19a",
"high",
"links: POL202.",
"canon_events.csv"
],
[
"OCC222",
"Hōryū-ji Kondō fire and the Law for the Protection of Cultural Properties (1949–1950)",
"Bunkazai hogohō",
"event",
"Time",
"F1.8",
"AS-JPN",
"1949",
"1950",
"fire January 1949; law May 1950",
"A fire damaged the 7th-century wall paintings of Hōryū-ji's Golden Hall, and the next year Japan passed a law protecting tangible and intangible cultural properties.",
"wall painting;conservation",
"wall painting;temple",
"ritual and belief;care and access",
"Japanese state",
"makers of works not designated",
"sacred",
"ColBase (Japan Government Standard Terms); Japan Search",
"R2",
"F1.24;F1.29",
"high",
"links: INS028 (Living National Treasures follow from the 1950 law, system from 1955).",
"canon_events.csv"
],
[
"OCC223",
"Hague Convention (1954)",
"Convention for the Protection of Cultural Property in the Event of Armed Conflict",
"event",
"Time",
"F1.13;THEME",
"GL",
"1954",
"1954",
"1954; Second Protocol 1999",
"The first global treaty on protecting cultural property in war set up the blue shield emblem.",
"none specific",
"monument;collection",
"war;care and access",
"UNESCO member states",
"non-state armed groups and intangible heritage",
"conflict-looting",
"UNESCO/UN instrument texts (link-out)",
"R2",
"F1.24;F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC224",
"Khrushchev's decree against architectural \"excesses\" (1955)",
"On the elimination of excesses in design and construction",
"event",
"Time",
"F1.11;F1.12a",
"EU-EER;AS-CEN",
"1955",
"1955",
"November 1955",
"The decree condemned Stalinist ornament and pushed standard prefabricated housing, the start of the khrushchyovka.",
"prefabricated concrete;standard design",
"apartment block",
"shelter",
"Soviet state",
"the ornamental craftsmen who lost work",
"none",
"Wikimedia Commons",
"R3",
"F1.20;F1.19",
"high",
"links: STY046; STY158.",
"canon_events.csv"
],
[
"OCC225",
"First container ship voyage (1956)",
"Ideal X",
"event",
"Time",
"F1.7;F1.13",
"AM-EWD;GL",
"1956",
"1956",
"April 1956",
"Malcom McLean's converted tanker carried 58 containers from Newark to Houston, the start of container shipping.",
"standard container;crane",
"shipping container",
"transport;exchange and value",
"historians",
"dockworkers who lost jobs",
"none",
"Library of Congress (per-item rights; many public domain)",
"R2",
"F1.13;F1.21",
"high",
"links: NET062.",
"canon_events.csv"
],
[
"OCC226",
"Minamata disease recognised (1956)",
"Minamata",
"event",
"Time",
"F1.8",
"AS-JPN",
"1956",
"1968",
"recognised 1956; state admits cause 1968",
"Mercury waste from Chisso's acetaldehyde plant poisoned fishing communities, a founding case of industrial pollution.",
"chemical industry;mercury",
"none specific",
"care and access",
"Japanese state; victims' groups",
"victims not certified",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"links: OCC276.",
"canon_events.csv"
],
[
"OCC227",
"Backyard furnaces of the Great Leap Forward (1958–1960)",
"Great Leap Forward",
"event",
"Time",
"F1.8",
"AS-CHN",
"1958",
"1960",
"1958–1960",
"Millions were told to make steel in small furnaces, melting pots and tools into poor iron while famine followed.",
"iron smelting;melting",
"furnace;iron",
"tools",
"Chinese Communist Party",
"the tens of millions who died in the famine",
"none",
"collection search link-out only",
"R3",
"F1.19;F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC228",
"Igloo tag and the first Kinngait print collection (1958–1959)",
"Cape Dorset prints",
"event",
"Time",
"F1.7",
"AM-ARC",
"1958",
"1959",
"igloo tag 1958; first annual print collection 1959",
"Canada introduced an igloo tag to certify Inuit-made art, and the first annual Kinngait print collection launched Inuit printmaking.",
"stonecut;stencil;soapstone carving",
"print;carving",
"exchange and value",
"Canadian state; West Baffin Eskimo Co-operative",
"Inuit makers who did not choose the market framing",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.14;F1.17",
"high",
"links: STY173; POL079. Igloo tag created 1958 (Government of Canada); managed by the Inuit Art Foundation since 2017.",
"canon_events.csv"
],
[
"OCC229",
"Tibetan exile and carpet weaving in Nepal (1959–1960s)",
"Tibetan refugee carpet industry",
"event",
"Time",
"F1.9",
"AS-HIM",
"1959",
"1970",
"from 1959",
"Tibetan refugees set up carpet workshops in Nepal with Swiss aid, which grew into a major export industry.",
"knotting;carpet weaving",
"Tibetan carpet",
"shelter;exchange and value",
"historians; aid agencies",
"child labour in the industry",
"human-flow",
"collection search link-out only",
"R3",
"F1.13;F1.18",
"high",
"links: POL205.",
"canon_events.csv"
],
[
"OCC230",
"Aswan High Dam and the Nubian campaign (1960–1980)",
"International Campaign to Save the Monuments of Nubia",
"event",
"Time",
"F1.6",
"AF-EGY;AF-NUB",
"1960",
"1980",
"1960–1980",
"The dam flooded Nubia, relocating temples such as Abu Simbel and displacing Nubians and their painted house tradition.",
"stone cutting;relocation",
"temple",
"ritual and belief;shelter",
"UNESCO; Egyptian and Sudanese states",
"the displaced Nubians",
"human-flow",
"UNESCO World Heritage List data (link-out); Wikimedia Commons",
"R2",
"F1.24;F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC231",
"Shrinking of the Aral Sea (from 1960)",
"Aral Sea disaster",
"event",
"Time",
"F1.12a",
"AS-CEN",
"1960",
"2010",
"from the 1960s",
"Soviet irrigation for cotton drained the Aral Sea, ruining fishing and leaving salt and dust over Karakalpakstan.",
"cotton irrigation",
"cotton",
"clothing and adornment;food and storage",
"Soviet planners; environmental historians",
"the Karakalpak fishing communities",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"links: PRD173.",
"canon_events.csv"
],
[
"OCC232",
"Cultural Heritage Protection Act (Korea, 1962)",
"Munhwajae boho beop",
"event",
"Time",
"F1.8",
"AS-KOR",
"1962",
"1962",
"1962",
"South Korea's law set up the system of designated intangible cultural properties and their holders.",
"safeguarding",
"none specific",
"care and access",
"South Korean state",
"makers not designated",
"none",
"Korean national e-museum (KOGL Type 1 items only)",
"R3",
"F1.29",
"high",
"",
"canon_events.csv"
],
[
"OCC233",
"Sketchpad (1963)",
"Ivan Sutherland's Sketchpad",
"event",
"Time",
"F1.7",
"AM-EWD",
"1963",
"1963",
"1963",
"Ivan Sutherland's program let users draw on a screen with a light pen, a founding step for CAD.",
"computer graphics",
"drawing",
"tools",
"historians of computing",
"other early CAD work in industry",
"none",
"collection search link-out only",
"R3",
"F1.21",
"high",
"",
"canon_events.csv"
],
[
"OCC234",
"Yirrkala bark petitions (1963)",
"Yolŋu bark petitions",
"event",
"Time",
"F1.12",
"OC-AUS",
"1963",
"1963",
"August 1963",
"Yolŋu leaders sent the Australian Parliament petitions typed on paper framed by painted bark, making bark painting a legal document.",
"bark painting",
"petition",
"record and writing",
"Yolŋu clans",
"non-Yolŋu voices",
"Indigenous-community",
"collection search link-out only",
"R2",
"F1.28",
"high",
"links: STY156.",
"canon_events.csv"
],
[
"OCC235",
"Border Industrialization Program (1965)",
"maquiladoras",
"event",
"Time",
"F1.7",
"AM-LAT",
"1965",
"1965",
"1965",
"Mexico let foreign firms set up assembly plants on the US border, starting the maquiladora industry.",
"assembly",
"garment;electronics",
"exchange and value",
"Mexican state",
"the mostly women workers in the assembly plants",
"none",
"collection search link-out only",
"R3",
"F1.21;F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC236",
"Destroy the Four Olds (1966–1976)",
"Cultural Revolution campaign against the \"Four Olds\"",
"event",
"Time",
"F1.8",
"AS-CHN",
"1966",
"1976",
"campaign from August 1966; Cultural Revolution to 1976",
"Red Guards smashed temple images, burned books and paintings and seized private collections as \"old\" culture, while many craft workshops were closed or turned to political goods.",
"none specific",
"temple image;book;painting",
"ritual and belief;rule and display",
"Chinese Communist Party; historians",
"the artists and owners persecuted, and the objects hidden by ordinary people",
"sacred;conflict-looting",
"collection search link-out only",
"R3",
"F1.19a;F1.24",
"high",
"links: POL171.",
"canon_events.csv"
],
[
"OCC237",
"Mexico 1968 Olympics design programme",
"México 68",
"event",
"Time",
"F1.7",
"AM-MES",
"1968",
"1968",
"1968",
"Lance Wyman, Eduardo Terrazas and Pedro Ramírez Vázquez created a graphic identity drawing on Wixárika (Huichol) yarn art and Op Art, applied from stamps to pavements.",
"graphic design;signage",
"logo;pictogram;poster",
"rule and display",
"Olympic organising committee",
"the students killed at Tlatelolco days before the Games; the Wixárika makers of the source art",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.20;F1.2",
"high",
"links: EVT021.",
"canon_events.csv"
],
[
"OCC238",
"Whole Earth Catalog (1968–1972)",
"Whole Earth Catalog",
"event",
"Time",
"F1.7",
"AM-WST",
"1968",
"1972",
"regular issues 1968–1972",
"Stewart Brand's catalogue reviewed tools, books and techniques for self-reliant making and fed the later maker and personal-computer cultures.",
"printing;tool reviewing",
"catalogue",
"tools",
"Stewart Brand",
"the Indigenous and rural techniques it borrowed from",
"none",
"collection search link-out only",
"R3",
"F1.21",
"high",
"links: MOV049; MOV046.",
"canon_events.csv"
],
[
"OCC239",
"UNESCO 1970 Convention",
"Convention on the Means of Prohibiting and Preventing the Illicit Import, Export and Transfer of Ownership of Cultural Property",
"event",
"Time",
"F1.13;THEME",
"GL",
"1970",
"1970",
"adopted November 1970; in force 1972",
"The convention asked states to control export and import of cultural property, and 1970 became the date museums use to judge whether an acquisition is legitimate.",
"provenance research",
"antiquity",
"rule and display",
"UNESCO member states",
"objects taken before 1970, including most colonial collections",
"conflict-looting",
"UNESCO/UN instrument texts (link-out)",
"R1",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC240",
"Aboriginal flag (1971)",
"Australian Aboriginal Flag",
"event",
"Time",
"F1.12",
"OC-AUS",
"1971",
"2022",
"first flown July 1971; copyright transferred to the Commonwealth 2022",
"Luritja artist Harold Thomas designed the flag; after years of licensing disputes over its use on clothing, he transferred copyright to the Australian government in 2022.",
"textile printing;graphic design",
"flag;garment",
"rule and display",
"Harold Thomas; Federal Court of Australia (1997 authorship ruling)",
"other Aboriginal flags and Torres Strait Islander symbols",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.14;F1.26",
"high",
"Flag works still in copyright; link out only.",
"canon_events.csv"
],
[
"OCC241",
"Panguna mine (1972–1989)",
"Bougainville copper mine",
"event",
"Time",
"F1.12",
"OC-MEL",
"1972",
"1989",
"opened 1972; closed 1989",
"The open-pit copper mine on Bougainville polluted rivers and helped spark a civil war that closed it.",
"copper mining",
"copper concentrate",
"exchange and value",
"historians; Bougainvilleans",
"the landowning clans",
"conflict-looting;Indigenous-community",
"collection search link-out only",
"R3",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC242",
"World Heritage Convention (1972)",
"Convention Concerning the Protection of the World Cultural and Natural Heritage",
"event",
"Time",
"F1.13;THEME",
"GL",
"1972",
"1972",
"adopted November 1972; in force 1975",
"The convention created the World Heritage List, which directs tourism and conservation money to listed sites and, with them, to craft repair and souvenir trades.",
"conservation;restoration",
"monument;site",
"care and access",
"UNESCO member states",
"sites that states do not nominate, and people living at listed sites",
"none",
"UNESCO/UN instrument texts (link-out); UNESCO World Heritage List data (link-out)",
"R2",
"F1.24;F1.3",
"high",
"links: INS075.",
"canon_events.csv"
],
[
"OCC243",
"CITES (1973)",
"Convention on International Trade in Endangered Species of Wild Fauna and Flora",
"event",
"Time",
"F1.13;THEME",
"GL",
"1973",
"1975",
"signed March 1973; in force 1975",
"The treaty controls trade in listed species, changing what makers can legally use for ivory, tortoiseshell, coral, feathers, skins and rare timbers.",
"ivory;tortoiseshell;coral;rosewood",
"carving;jewellery;instrument",
"exchange and value",
"signatory states",
"craft communities who depended on the trade",
"none",
"UNESCO/UN instrument texts (link-out)",
"R2",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC244",
"Multi Fibre Arrangement (1974–2004)",
"MFA",
"event",
"Time",
"F1.13;THEME",
"GL",
"1974",
"2004",
"in force 1974; quotas phased out by 1 January 2005",
"Quotas on textile and clothing imports spread garment making to many new countries; their end in 2005 concentrated it in China, Bangladesh and a few others.",
"garment making;sewing",
"garment",
"clothing and adornment",
"GATT and WTO member states",
"garment workers in countries that lost orders after 2005",
"none",
"collection search link-out only",
"R3",
"F1.21;F1.23",
"high",
"links: EVT032.",
"canon_events.csv"
],
[
"OCC245",
"Khmer Rouge regime (1975–1979)",
"Democratic Kampuchea",
"event",
"Time",
"F1.9",
"AS-MSE",
"1975",
"1979",
"April 1975–January 1979",
"The regime killed a large share of Cambodia's artists, dancers, musicians and craftspeople and banned religion, so weaving, silverwork and court dance were rebuilt afterwards from few survivors.",
"silk weaving;silversmithing",
"textile;silverware",
"ritual and belief;play and music",
"historians; survivors' testimony",
"the victims and survivors who rebuilt the crafts",
"human-flow;conflict-looting",
"collection search link-out only",
"R3",
"F1.19a",
"high",
"Forced labour in communes: human-flow.",
"canon_events.csv"
],
[
"OCC246",
"American Indian Religious Freedom Act (1978)",
"AIRFA",
"event",
"Time",
"F1.7",
"AM-WST;AM-EWD",
"1978",
"1978",
"August 1978",
"US law declared a policy of protecting Native American religious practice, including access to sacred sites and use of eagle feathers and other sacred materials.",
"featherwork;regalia making",
"regalia;ceremonial object",
"ritual and belief",
"US Congress",
"tribes without federal recognition; the Act's lack of enforcement",
"sacred;Indigenous-community",
"US National Archives Catalog",
"R3",
"F1.16",
"high",
"",
"canon_events.csv"
],
[
"OCC247",
"Ahmedabad Declaration (1979)",
"Ahmedabad Declaration on Industrial Design for Development",
"event",
"Time",
"F1.9;F1.13",
"AS-SAS;GL",
"1979",
"1979",
"January 1979",
"A UNIDO–ICSID meeting at NID Ahmedabad called for design suited to the needs of developing countries rather than copied from industrial nations.",
"design policy",
"none specific",
"tools",
"UNIDO; ICSID; National Institute of Design",
"craftspeople, invited as subjects rather than authors",
"none",
"collection search link-out only",
"R3",
"F1.20",
"high",
"links: INS033.",
"canon_events.csv"
],
[
"OCC248",
"Shenzhen Special Economic Zone (1980)",
"Shenzhen SEZ",
"event",
"Time",
"F1.8",
"AS-CHN",
"1980",
"1980",
"August 1980",
"China's first special economic zones, led by Shenzhen, drew foreign firms and migrant workers and grew into a centre of electronics manufacture.",
"assembly;electronics manufacture",
"electronics;toy;garment",
"exchange and value",
"Chinese state",
"migrant workers, many young women, on factory dormitory regimes",
"none",
"collection search link-out only",
"R3",
"F1.21;F1.23",
"high",
"links: INS069.",
"canon_events.csv"
],
[
"OCC249",
"Egypt's Law 117 (1983)",
"Law on the Protection of Antiquities (No. 117 of 1983)",
"event",
"Time",
"F1.6",
"AF-EGY",
"1983",
"1983",
"1983; amended 2010",
"Egypt's law made all antiquities public property, ended the legal antiquities trade and banned export.",
"none specific",
"antiquity",
"rule and display",
"Egyptian state",
"local communities who once sold finds",
"none",
"official text of the law (government legislation site; link-out)",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC250",
"Stereolithography patent (1984–1986)",
"3D printing",
"event",
"Time",
"F1.7",
"AM-WST",
"1984",
"1986",
"filed 1984; granted 1986",
"Chuck Hull's patent on building objects layer by layer from UV-cured resin began commercial 3D printing.",
"stereolithography;3D printing",
"prototype",
"tools",
"historians of technology",
"earlier Japanese and French layer-printing proposals",
"none",
"collection search link-out only",
"R3",
"F1.21",
"high",
"links: INS078; MOV049.",
"canon_events.csv"
],
[
"OCC251",
"Desktop publishing (1985)",
"Macintosh, LaserWriter and PageMaker",
"event",
"Time",
"F1.7",
"AM-WST",
"1985",
"1985",
"1985",
"The Apple LaserWriter, PostScript and Aldus PageMaker let designers set pages on personal computers, displacing much professional typesetting.",
"digital typesetting;PostScript",
"page layout;typeface",
"record and writing",
"historians of design",
"typesetters and compositors who lost work",
"none",
"collection search link-out only",
"R3",
"F1.21",
"high",
"links: MOV033.",
"canon_events.csv"
],
[
"OCC252",
"CITES ivory trade ban (1989)",
"African elephant ivory trade ban",
"event",
"Time",
"F1.13;F1.6",
"GL;AF-SWA;AF-SOU",
"1989",
"1990",
"agreed October 1989; in force January 1990",
"Moving the African elephant to CITES Appendix I ended most legal international ivory trade, closing carving workshops from Hong Kong to Japan.",
"ivory carving",
"carving;seal;netsuke",
"exchange and value",
"CITES parties",
"African communities living with elephants",
"none",
"UNESCO/UN instrument texts (link-out)",
"R3",
"F1.22",
"high",
"Later one-off sales (1999, 2008) complicate the story.",
"canon_events.csv"
],
[
"OCC253",
"Indian Arts and Crafts Act (1990)",
"IACA 1990",
"event",
"Time",
"F1.7",
"AM-WST;AM-EWD",
"1990",
"1990",
"November 1990",
"US law made it a crime to market goods falsely as made by Native Americans, strengthening the 1935 Act that created the Indian Arts and Crafts Board.",
"none specific",
"jewellery;pottery;beadwork",
"exchange and value",
"US Congress",
"Native artists who are not enrolled members of a recognised tribe",
"Indigenous-community",
"US National Archives Catalog",
"R2",
"F1.14",
"high",
"links: INS014. 1935 Act is covered by INS014.",
"canon_events.csv"
],
[
"OCC254",
"NAGPRA (1990)",
"Native American Graves Protection and Repatriation Act",
"event",
"Time",
"F1.7",
"AM-WST;AM-EWD;AM-NWC;AM-ARC",
"1990",
"1990",
"November 1990",
"US law required federally funded museums to inventory and return Native American human remains, funerary objects, sacred objects and objects of cultural patrimony to tribes.",
"none specific",
"sacred object;funerary object",
"ritual and belief",
"US Congress",
"tribes without federal recognition; Native Hawaiian claims handled differently",
"sacred;funerary;Indigenous-community",
"US National Archives Catalog",
"R1",
"F1.24",
"high",
"links: POL078.",
"canon_events.csv"
],
[
"OCC255",
"WAI 262 claim (1991–2011)",
"Ko Aotearoa Tēnei report",
"event",
"Time",
"F1.12",
"OC-POL",
"1991",
"2011",
"lodged 1991; report 2011",
"Māori claimants asked the Waitangi Tribunal about control of taonga works, mātauranga and native flora and fauna, and its 2011 report proposed protection for taonga works.",
"none specific",
"taonga",
"care and access",
"Waitangi Tribunal; claimant iwi",
"iwi not party to the claim",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.14;F1.26",
"high",
"",
"canon_events.csv"
],
[
"OCC256",
"Destruction and rebuilding of the Mostar bridge (1993–2004)",
"Stari Most",
"event",
"Time",
"F1.11",
"EU-BYZ",
"1993",
"2004",
"destroyed November 1993; reopened 2004",
"The Ottoman bridge of 1566 was shelled down in the Bosnian war and rebuilt with stone from the original quarries and Ottoman methods.",
"stone masonry;quarrying",
"bridge",
"transport",
"historians; reconstruction team",
"the divided communities on either bank",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.28a;F1.19a",
"high",
"Old Bridge Area of the Old City of Mostar, World Heritage 2005 (verified).",
"canon_events.csv"
],
[
"OCC257",
"Mataatua Declaration (1993)",
"Mataatua Declaration on Cultural and Intellectual Property Rights of Indigenous Peoples",
"event",
"Time",
"F1.12;F1.13",
"OC-POL;GL",
"1993",
"1993",
"June 1993",
"A conference hosted by the nine tribes of Mataatua in Aotearoa asserted Indigenous peoples' rights to define and control their cultural and intellectual property.",
"none specific",
"none specific",
"care and access",
"Indigenous delegates from 14 countries",
"peoples not represented",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.14;F1.26",
"high",
"",
"canon_events.csv"
],
[
"OCC258",
"Carpets case (1994)",
"Milpurrurru v Indofurn; Bulun Bulun v R & T Textiles (1998)",
"event",
"Time",
"F1.12",
"OC-AUS",
"1994",
"1998",
"1994; related case 1998",
"Australian courts ruled that carpets made in Vietnam copying Aboriginal artists' paintings infringed copyright and caused cultural harm, and a 1998 case recognised community interests in an artist's work.",
"carpet weaving;screen printing",
"carpet;printed fabric",
"exchange and value",
"Federal Court of Australia; the artists' estates",
"communities whose designs had no single named author",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.14;F1.26",
"high",
"",
"canon_events.csv"
],
[
"OCC259",
"TRIPS Agreement (1994)",
"Agreement on Trade-Related Aspects of Intellectual Property Rights",
"event",
"Time",
"F1.13;THEME",
"GL",
"1994",
"1995",
"signed April 1994; in force 1995",
"The WTO agreement set minimum patent, copyright, design and trademark rules for all members and protected geographical indications such as regional textiles and foods.",
"none specific",
"none specific",
"exchange and value",
"WTO member states",
"traditional and collective knowledge, not covered",
"none",
"collection search link-out only",
"R3",
"F1.14",
"high",
"",
"canon_events.csv"
],
[
"OCC260",
"UNIDROIT Convention (1995)",
"Convention on Stolen or Illegally Exported Cultural Objects",
"event",
"Time",
"F1.13;THEME",
"GL",
"1995",
"1995",
"June 1995",
"The convention requires the return of stolen cultural objects even from buyers who acted in good faith, tightening the 1970 rules.",
"none specific",
"antiquity",
"rule and display",
"UNIDROIT member states",
"objects in states that have not signed",
"conflict-looting",
"collection search link-out only",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC261",
"Washington Principles (1998)",
"Washington Conference Principles on Nazi-Confiscated Art",
"event",
"Time",
"F1.13;THEME",
"GL",
"1998",
"1998",
"December 1998",
"Forty-four governments agreed non-binding principles to identify Nazi-looted art and reach \"just and fair solutions\" with heirs.",
"provenance research",
"painting;decorative arts",
"rule and display",
"44 governments at the Washington Conference",
"states that did not sign and the non-binding nature of the principles",
"conflict-looting",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC216.",
"canon_events.csv"
],
[
"OCC262",
"Geographical Indications of Goods Act (India, 1999)",
"GI Act",
"event",
"Time",
"F1.9",
"AS-SAS",
"1999",
"2003",
"passed 1999; in force 2003",
"India's law lets regional crafts and foods register geographical indications, and many handloom and craft names have since been registered.",
"handloom weaving;registration",
"sari;textile;tea",
"exchange and value",
"Indian state",
"makers outside the registered area and power-loom copies",
"none",
"collection search link-out only",
"R3",
"F1.14",
"high",
"Darjeeling tea was the first registration (2004); to verify.",
"canon_events.csv"
],
[
"OCC263",
"Destruction of the Bamiyan Buddhas (2001)",
"Bamiyan Buddhas",
"event",
"Time",
"F1.12a;F1.9",
"AS-CEN",
"2001",
"2001",
"March 2001",
"The Taliban blew up the two giant rock-cut Buddhas of Bamiyan, and the same year smashed statues in the Kabul Museum.",
"rock carving;clay and plaster modelling",
"colossal statue;cave painting",
"ritual and belief",
"historians",
"the Hazara residents of the valley",
"sacred;conflict-looting",
"Wikimedia Commons",
"R2",
"F1.19a;F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC264",
"Creative Commons licences (2002)",
"CC licences 1.0",
"event",
"Time",
"F1.13;THEME",
"GL",
"2002",
"2002",
"December 2002",
"Creative Commons released free standard licences that let makers share work on stated terms, later used by many open-access museum programmes.",
"licensing",
"none specific",
"record and writing",
"Creative Commons (Lawrence Lessig and others)",
"communities whose knowledge sits outside copyright",
"none",
"collection search link-out only",
"R3",
"F1.14;F1.21",
"high",
"",
"canon_events.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
