insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OCC265",
"Returns of Maqdala objects (2002–2023)",
"Maqdala returns",
"event",
"Time",
"F1.6;F1.11",
"AF-HRN;EU-BLC",
"2002",
"2023",
"January 2002; September 2021; 24 September 2023",
"Returns of Maqdala loot to Ethiopia include a tabot from St John's Episcopal Church, Edinburgh (2002), objects bought and returned by the Scheherazade Foundation (2021) and a tabot bought by a private individual and handed over in London in September 2023.",
"none specific",
"tabot;manuscript;cross",
"ritual and belief",
"a church, a foundation, private holders and the Ethiopian state",
"the objects still in national collections",
"sacred;conflict-looting",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC147. Verified: Edinburgh tabot Jan 2002; Scheherazade Foundation Sept 2021; tabot bought by Jacopo Gnisci, handed over at Battersea 24 Sept 2023.",
"canon_events.csv"
],
[
"OCC266",
"Karanga Aotearoa Repatriation Programme (2003)",
"Te Papa repatriation programme",
"event",
"Time",
"F1.12",
"OC-POL",
"2003",
"2003",
"mandated 2003",
"Te Papa leads the New Zealand government's programme to bring home Māori and Moriori ancestral remains from overseas institutions.",
"none specific",
"none specific",
"ritual and belief",
"New Zealand government; Te Papa",
"ancestors still held abroad",
"ancestral;funerary;Indigenous-community",
"Te Papa Collections Online (per-item; taonga restricted)",
"R3",
"F1.24",
"high",
"links: INS087.",
"canon_events.csv"
],
[
"OCC267",
"Kimberley Process (2003)",
"Kimberley Process Certification Scheme",
"event",
"Time",
"F1.13;F1.6",
"GL;AF-CEN;AF-GUI",
"2003",
"2003",
"launched 2003",
"Governments and the diamond industry set up certificates to keep rough diamonds from conflict zones out of trade.",
"certification",
"rough diamond",
"exchange and value",
"states and the diamond industry",
"artisanal miners and abuses outside its definition of \"conflict\"",
"none",
"collection search link-out only",
"R3",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC268",
"Looting of the Iraq Museum (2003)",
"Baghdad museum looting",
"event",
"Time",
"F1.9a;F1.10",
"WA-MES",
"2003",
"2003",
"April 2003",
"After the US-led invasion, looters took thousands of objects from the Iraq Museum while site looting spread across southern Iraq.",
"none specific",
"cylinder seal;statue;vase",
"rule and display",
"historians; museum staff",
"the staff who protected storerooms",
"conflict-looting",
"collection search link-out only",
"R2",
"F1.24;F1.19a",
"high",
"Numbers and recoveries to verify.",
"canon_events.csv"
],
[
"OCC269",
"UN Declaration on the Rights of Indigenous Peoples (2007)",
"UNDRIP",
"event",
"Time",
"F1.13;THEME",
"GL",
"2007",
"2007",
"September 2007",
"The declaration affirms Indigenous peoples' rights to their cultural heritage, traditional knowledge and repatriation of ceremonial objects and remains (Articles 11, 12 and 31).",
"none specific",
"none specific",
"care and access",
"UN General Assembly",
"the four states that first voted against (later endorsed)",
"Indigenous-community",
"UNESCO/UN instrument texts (link-out)",
"R3",
"F1.24;F1.26",
"high",
"",
"canon_events.csv"
],
[
"OCC270",
"Dodd–Frank Section 1502 (2010)",
"conflict minerals rule",
"event",
"Time",
"F1.7;F1.6",
"AM-EWD;AF-CEN",
"2010",
"2010",
"July 2010",
"US law required listed companies to report tin, tantalum, tungsten and gold from Congo and neighbouring countries, reaching into electronics and jewellery supply chains.",
"mining;due diligence",
"electronics;jewellery",
"exchange and value",
"US Congress",
"artisanal miners who lost buyers",
"none",
"collection search link-out only",
"R3",
"F1.22",
"high",
"",
"canon_events.csv"
],
[
"OCC271",
"French law on the return of toi moko (2010)",
"Loi du 18 mai 2010",
"event",
"Time",
"F1.11;F1.12",
"EU-WCE;OC-POL",
"2010",
"2012",
"law 2010; return 2012",
"A French law allowed museums to return preserved tattooed Māori heads (toi moko), and 20 were handed to Te Papa in 2012.",
"none specific",
"toi moko",
"ritual and belief",
"French Parliament",
"ancestors held in countries without such laws",
"ancestral;funerary;Indigenous-community",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC266. Numbers to verify.",
"canon_events.csv"
],
[
"OCC272",
"Aleppo souk fire (2012)",
"al-Madina souq fire",
"event",
"Time",
"F1.10",
"WA-LEV",
"2012",
"2012",
"September 2012",
"Fighting set the covered markets of Aleppo's old city on fire, destroying shops and workshops of soap, textiles and metalwork.",
"soap making;textile trade",
"market",
"exchange and value",
"historians",
"merchants and makers displaced by the war",
"conflict-looting",
"collection search link-out only",
"R3",
"F1.19a",
"high",
"",
"canon_events.csv"
],
[
"OCC273",
"Destruction of Timbuktu mausoleums and manuscripts (2012–2013)",
"Timbuktu",
"event",
"Time",
"F1.6;F1.10",
"AF-SAH",
"2012",
"2013",
"2012–2013",
"Armed groups destroyed Sufi saints' mausoleums and burned manuscripts in Timbuktu, while residents smuggled most manuscripts to Bamako.",
"earthen building;manuscript copying",
"mausoleum;manuscript",
"ritual and belief;record and writing",
"historians; Malian state",
"the families and librarians who saved the manuscripts",
"sacred;conflict-looting",
"British Library Endangered Archives Programme; collection search link-out only",
"R2",
"F1.24;F1.19a",
"high",
"links: TXT054. Mausoleums rebuilt by local masons 2014–15.",
"canon_events.csv"
],
[
"OCC274",
"Garment factory fires in Karachi and Dhaka (2012)",
"Ali Enterprises fire; Tazreen Fashions fire",
"event",
"Time",
"F1.9;F1.13",
"AS-SAS",
"2012",
"2012",
"Karachi September 2012; Dhaka November 2012",
"Fires at the Ali Enterprises factory in Karachi and Tazreen Fashions near Dhaka killed hundreds of garment workers behind locked exits.",
"garment making",
"garment",
"clothing and adornment",
"labour groups; historians",
"the brands buying from both factories",
"none",
"collection search link-out only",
"R3",
"F1.23",
"high",
"links: EVT032; EVT031.",
"canon_events.csv"
],
[
"OCC275",
"Bangladesh Accord (2013)",
"Accord on Fire and Building Safety in Bangladesh",
"event",
"Time",
"F1.9;F1.13",
"AS-SAS",
"2013",
"2013",
"May 2013",
"After Rana Plaza, brands and trade unions signed a binding agreement for factory safety inspections in Bangladesh.",
"factory inspection",
"garment",
"clothing and adornment",
"brands and global trade unions",
"workers in factories outside the Accord",
"none",
"collection search link-out only",
"R3",
"F1.23",
"high",
"links: EVT032.",
"canon_events.csv"
],
[
"OCC276",
"Minamata Convention (2013)",
"Minamata Convention on Mercury",
"event",
"Time",
"F1.13;THEME",
"GL",
"2013",
"2017",
"signed October 2013; in force 2017",
"The treaty limits mercury in products and industry and targets its use in artisanal gold mining, also constraining fire-gilding.",
"mercury;amalgamation;gilding",
"none specific",
"care and access",
"UN member states",
"artisanal miners without alternatives",
"none",
"UNESCO/UN instrument texts (link-out)",
"R3",
"F1.22",
"high",
"links: OCC226.",
"canon_events.csv"
],
[
"OCC277",
"Destruction at Palmyra (2015)",
"Palmyra",
"event",
"Time",
"F1.9a;F1.10",
"WA-LEV",
"2015",
"2017",
"2015–2017",
"Islamic State blew up the temples of Baalshamin and Bel and killed the antiquities scholar Khaled al-Asaad.",
"stone carving",
"temple;funerary bust",
"ritual and belief",
"historians; heritage agencies",
"the residents of Tadmur",
"conflict-looting;funerary",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: POL114.",
"canon_events.csv"
],
[
"OCC278",
"Gorkha earthquake (2015)",
"Nepal earthquake",
"event",
"Time",
"F1.9",
"AS-HIM",
"2015",
"2015",
"25 April 2015",
"The earthquake toppled temples in the Kathmandu Valley's Durbar squares, which Newar carpenters and masons rebuilt with traditional methods.",
"woodcarving;brick masonry",
"temple;strut",
"ritual and belief",
"historians; Nepal's Department of Archaeology",
"rural villages rebuilt with less support",
"sacred",
"collection search link-out only",
"R3",
"F1.28a",
"high",
"links: SCH032; DYN059.",
"canon_events.csv"
],
[
"OCC279",
"ISIS destruction in Mosul and Nimrud (2015)",
"Mosul Museum; Nimrud",
"event",
"Time",
"F1.9a;F1.10",
"WA-MES",
"2015",
"2015",
"February–April 2015",
"Islamic State filmed the smashing of statues in the Mosul Museum and blew up parts of the Assyrian palace at Nimrud, while also selling looted antiquities.",
"stone carving",
"statue;lamassu;relief",
"rule and display",
"historians; heritage agencies",
"Iraqi staff and residents who hid objects",
"conflict-looting",
"collection search link-out only",
"R2",
"F1.24;F1.19a",
"high",
"links: POL096.",
"canon_events.csv"
],
[
"OCC280",
"Al Mahdi conviction at the ICC (2016)",
"Prosecutor v. Ahmad Al Faqi Al Mahdi",
"event",
"Time",
"F1.6",
"AF-SAH",
"2016",
"2017",
"verdict September 2016; reparations order 2017",
"The International Criminal Court convicted a man for directing attacks on Timbuktu's mausoleums, its first case centred on cultural destruction.",
"none specific",
"mausoleum",
"ritual and belief",
"International Criminal Court",
"other perpetrators",
"conflict-looting;sacred",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC273.",
"canon_events.csv"
],
[
"OCC281",
"National Museum of Brazil fire (2018)",
"Museu Nacional fire",
"event",
"Time",
"F1.7",
"AM-LAT",
"2018",
"2018",
"2 September 2018",
"Fire destroyed most of Brazil's National Museum in Rio, including Indigenous collections and recordings of languages.",
"none specific",
"featherwork;pottery;recording",
"rule and display",
"historians; museum staff",
"the Indigenous communities whose objects were lost",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC282",
"Sarr–Savoy report (2018)",
"The Restitution of African Cultural Heritage: Toward a New Relational Ethics",
"event",
"Time",
"F1.6;F1.11",
"EU-WCE;AF-GUI;AF-SAH;AF-CEN",
"2018",
"2018",
"November 2018",
"Felwine Sarr and Bénédicte Savoy recommended the return of African objects taken to France in the colonial period without proven consent.",
"provenance research",
"none specific",
"rule and display",
"Felwine Sarr; Bénédicte Savoy",
"museums outside France and objects acquired after independence",
"conflict-looting",
"collection search link-out only",
"R1",
"F1.24",
"high",
"Commissioned after Macron's Ouagadougou speech (28 November 2017).",
"canon_events.csv"
],
[
"OCC283",
"Ainu Promotion Act (2019)",
"Act Promoting Measures to Realise a Society in Which the Pride of the Ainu People Is Respected",
"event",
"Time",
"F1.8",
"AS-JPN",
"2019",
"2019",
"April 2019",
"Japanese law recognised the Ainu as an Indigenous people and funded culture programmes, including the Upopoy national museum.",
"none specific",
"none specific",
"care and access",
"Japanese state",
"Ainu calls for land and fishing rights",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.29",
"high",
"links: OCC153.",
"canon_events.csv"
],
[
"OCC284",
"Notre-Dame fire (2019)",
"Notre-Dame de Paris fire",
"event",
"Time",
"F1.11",
"EU-WCE",
"2019",
"2024",
"fire 15 April 2019; reopened December 2024",
"Fire destroyed the cathedral's timber roof and spire, which were rebuilt with oak and hand-hewing methods like the medieval ones.",
"timber framing;hand-hewing;lead roofing",
"roof;spire",
"ritual and belief",
"French state; restoration team",
"the workers exposed to lead",
"sacred",
"collection search link-out only",
"R3",
"F1.28a",
"high",
"",
"canon_events.csv"
],
[
"OCC285",
"COVID-19 pandemic (2020–2023)",
"COVID-19",
"event",
"Time",
"F1.13;THEME",
"GL",
"2020",
"2023",
"WHO emergency 2020–2023",
"The pandemic stopped factories and shipping, cancelled garment orders and saw home sewers and makerspaces produce masks and face shields.",
"sewing;3D printing",
"mask;face shield",
"care and access",
"WHO; historians",
"garment workers left unpaid when orders were cancelled",
"none",
"collection search link-out only",
"R3",
"F1.22;F1.22a",
"high",
"",
"canon_events.csv"
],
[
"OCC286",
"French restitution law (2020)",
"Loi du 24 décembre 2020",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI;AF-SAH",
"2020",
"2021",
"law December 2020; Benin return November 2021",
"A French law allowed 26 objects from the royal treasures of Abomey to go to Benin and a sabre attributed to El Hadj Umar Tall to go to Senegal.",
"brass casting;woodcarving",
"statue;throne;sabre",
"rule and display",
"French Parliament",
"other objects that need a new law each time",
"conflict-looting",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC171.",
"canon_events.csv"
],
[
"OCC287",
"Benin bronze returns by UK universities (2021)",
"Aberdeen head; Okukor",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI;EU-BLC",
"2021",
"2021",
"October 2021",
"The University of Aberdeen returned a Benin head and Jesus College, Cambridge returned the cockerel Okukor, the first UK institutional returns.",
"brass casting",
"commemorative head;cockerel",
"rule and display",
"the universities; Nigerian authorities",
"objects in national museums bound by law",
"conflict-looting;ancestral",
"Digital Benin (each lender's licence)",
"R3",
"F1.24",
"high",
"",
"canon_events.csv"
],
[
"OCC288",
"Uyghur Forced Labor Prevention Act (2021)",
"UFLPA",
"event",
"Time",
"F1.7;F1.8",
"AS-CEN;AS-CHN",
"2021",
"2022",
"signed December 2021; in force June 2022",
"US law presumes goods made wholly or partly in Xinjiang involve forced labour and bars their import unless proven otherwise, reaching cotton, garments and solar parts.",
"cotton;garment making",
"garment;solar panel",
"clothing and adornment",
"US Congress",
"Uyghur workers themselves, who are rarely heard",
"human-flow",
"collection search link-out only",
"R3",
"F1.23",
"high",
"",
"canon_events.csv"
],
[
"OCC289",
"German transfer of Benin bronzes (2022)",
"Benin bronzes returned by Germany",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI;EU-WCE",
"2022",
"2022",
"agreement July 2022; first handover December 2022",
"Germany transferred ownership of Benin objects in its public museums to Nigeria and handed over the first 20 in Abuja.",
"brass casting;ivory carving",
"plaque;commemorative head",
"rule and display",
"German and Nigerian governments",
"the Benin court's own claims, raised later",
"conflict-looting;ancestral",
"Digital Benin (each lender's licence)",
"R2",
"F1.24",
"high",
"links: INS082; DYN038. Count of first handover to verify. A 2023 Nigerian presidential notice vested returned objects in the Oba of Benin.",
"canon_events.csv"
],
[
"OCC290",
"Smithsonian and Horniman Benin returns (2022)",
"Benin returns",
"event",
"Time",
"F1.6;F1.7;F1.11",
"AF-GUI;AM-EWD;EU-BLC",
"2022",
"2022",
"2022",
"The Smithsonian transferred 29 Benin objects to Nigeria and London's Horniman Museum 72, among the first transfers of ownership by national museums outside Germany.",
"brass casting",
"commemorative head;plaque",
"rule and display",
"museum trustees; Nigerian National Commission for Museums and Monuments",
"objects in museums barred by law from returning",
"conflict-looting;ancestral",
"Digital Benin (each lender's licence)",
"R3",
"F1.24",
"high",
"Counts to verify.",
"canon_events.csv"
],
[
"OCC291",
"Dutch returns to Indonesia and Sri Lanka (2023)",
"Dutch restitution of colonial collections",
"event",
"Time",
"F1.9;F1.11",
"AS-ISE;AS-SAS",
"2023",
"2023",
"July 2023",
"The Netherlands returned 478 objects, including part of the Lombok treasure and Singhasari statues to Indonesia and a jewelled cannon to Sri Lanka.",
"goldsmithing;stone carving",
"jewellery;statue;cannon",
"rule and display",
"Dutch government; Colonial Collections Committee",
"claims from other former colonies",
"conflict-looting",
"Rijksmuseum (CC0/PDM)",
"R3",
"F1.24",
"high",
"links: OCC172. Counts to verify.",
"canon_events.csv"
],
[
"OCC292",
"Asante gold loans to Kumasi (2024)",
"Asante gold regalia loan",
"event",
"Time",
"F1.6;F1.11",
"AF-GUI;EU-BLC",
"2024",
"2024",
"loans announced January 2024; display opened 1 May 2024",
"The V&A (17 objects) and British Museum (15) lent 32 Asante gold and regalia objects, many taken in the wars of 1874 and 1895-96, to the Manhyia Palace Museum in Kumasi for three years, extendable by three.",
"goldsmithing;casting",
"regalia;soul washer's disc",
"rule and display",
"the museums and the Asantehene",
"the question of ownership, left open by a loan",
"conflict-looting",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: OCC155; POL029.",
"canon_events.csv"
],
[
"OCC293",
"EU Right to Repair Directive (2024)",
"Directive on common rules promoting the repair of goods",
"event",
"Time",
"F1.11",
"EU-WCE;EU-EER;EU-IBE;EU-SCA",
"2024",
"2024",
"adopted 2024",
"The EU obliged manufacturers of some appliances to offer repair at reasonable prices and to supply parts.",
"repair;spare parts",
"appliance",
"tools",
"European Union",
"repairers outside the EU",
"none",
"collection search link-out only",
"R3",
"F1.22a",
"high",
"",
"canon_events.csv"
],
[
"OCC294",
"Revised NAGPRA regulations (2024)",
"NAGPRA final rule",
"event",
"Time",
"F1.7",
"AM-WST;AM-EWD;AM-NWC",
"2024",
"2024",
"in force January 2024",
"New US rules required museums to get consent from tribes before displaying or researching covered items, and many closed displays.",
"none specific",
"sacred object;funerary object",
"ritual and belief",
"US Department of the Interior",
"tribes without federal recognition",
"sacred;funerary;Indigenous-community",
"collection search link-out only",
"R3",
"F1.24;F1.26",
"high",
"links: OCC254.",
"canon_events.csv"
],
[
"INV001",
"writing (Mesopotamia)",
"proto-cuneiform",
"first-known",
"Things",
"F1.9a;THEME",
"WA-MES",
"-3300",
"",
"c. 3400–3200 BCE, Uruk IV–III",
"First known writing: proto-cuneiform tablets from Uruk record goods, rations and labour.",
"clay tablets; reed stylus",
"Uruk IV–III tablets",
"record and writing;exchange and value",
"Assyriologists and archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5;F1.28",
"high",
"Claim: earliest with Egypt, within about a century; competing: Egypt (Abydos U-j, medium). Roots in clay tokens proposed (Schmandt-Besserat, debated).",
"canon_firsts.csv"
],
[
"INV002",
"writing (Egypt)",
"hieroglyphs; U-j labels",
"first-known",
"Things",
"F1.6;THEME",
"AF-EGY",
"-3250",
"",
"c. 3320–3150 BCE (Abydos tomb U-j)",
"First known Egyptian writing: bone and ivory labels from tomb U-j at Abydos with signs read by some as phonetic.",
"bone and ivory labels; ink on pots",
"Abydos U-j labels",
"record and writing;rule and display",
"Egyptologists (German Archaeological Institute excavations)",
"",
"funerary",
"Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5",
"medium",
"Contested: independent invention vs stimulus diffusion from Mesopotamia; U-j readings (Dreyer) debated (confidence medium).",
"canon_firsts.csv"
],
[
"INV003",
"writing (China)",
"oracle-bone script",
"first-known",
"Things",
"F1.8;THEME",
"AS-CHN",
"-1250",
"",
"c. 1250 BCE (reign of Wu Ding)",
"First known Chinese writing: a fully developed script on Shang oracle bones and bronzes at Anyang.",
"bone; turtle plastron; bronze",
"oracle bones",
"record and writing;ritual and belief",
"palaeographers and archaeologists",
"",
"sacred",
"Wikimedia Commons",
"R1",
"F1.5",
"high",
"Earlier Neolithic signs (Jiahu, Dawenkou) are not accepted as writing by most (low); script maturity implies an undocumented earlier stage.",
"canon_firsts.csv"
],
[
"INV004",
"writing (Mesoamerica)",
"Olmec, Zapotec, Epi-Olmec and Maya scripts",
"first-known",
"Things",
"F1.7;THEME",
"AM-MES",
"-900",
"",
"Cascajal Block c. 900 BCE (contested); Zapotec c. 600–400 BCE; Maya c. 300 BCE (San Bartolo)",
"First known writing of the Americas, invented independently in Mesoamerica.",
"stone; paint on plaster",
"Cascajal Block; San José Mogote Monument 3; San Bartolo texts",
"record and writing;rule and display",
"epigraphers and archaeologists",
"",
"none",
"Wikimedia Commons",
"R1",
"F1.5",
"medium",
"Cascajal Block (low: context and date questioned); Monument 3 date debated (medium); San Bartolo c. 300 BCE (high).",
"canon_firsts.csv"
],
[
"INV005",
"khipu as a recording system",
"quipu",
"first-known",
"Things",
"F1.7;THEME",
"AM-AND",
"600",
"",
"Wari khipus c. 600–1000 CE (secure); Caral c. 2500 BCE claim (low)",
"A debated case: knotted cords as an independent recording system that may or may not encode language.",
"cotton; camelid fibre; knotting",
"Wari khipus; Inka khipus",
"record and writing",
"archaeologists; Andean communities",
"",
"Indigenous-community",
"Wikimedia Commons",
"R1",
"F1.5;F1.3",
"medium",
"Caral \"khipu\" announced by Ruth Shady is not securely published (low); whether khipu is writing is open.",
"canon_firsts.csv"
],
[
"INV006",
"Indus script",
"Harappan script",
"first-known",
"Things",
"F1.9;THEME",
"AS-SAS",
"-2600",
"",
"Mature c. 2600–1900 BCE; early signs c. 3300 BCE at Harappa",
"First known sign system of South Asia, on seals, tablets and pots; undeciphered.",
"steatite seals; tablets",
"Indus seals",
"record and writing;exchange and value",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"Whether it writes language is disputed (Farmer, Sproat and Witzel 2004 said no; most disagree).",
"canon_firsts.csv"
],
[
"INV007",
"alphabet",
"Proto-Sinaitic",
"first-known",
"Things",
"F1.6;F1.9a",
"AF-EGY;WA-LEV",
"-1850",
"",
"c. 1900–1700 BCE (Wadi el-Hol; Serabit el-Khadim)",
"First known alphabet: signs adapted from Egyptian hieroglyphs by Semitic-speaking workers.",
"rock inscriptions; stone",
"Wadi el-Hol inscriptions; Serabit el-Khadim inscriptions",
"record and writing",
"epigraphers",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.23",
"medium",
"Date range 1900–1500 BCE debated; made by workers and miners, not scribes (F1.23).",
"canon_firsts.csv"
],
[
"INV008",
"rongorongo",
"kohau rongorongo",
"first-known",
"Things",
"F1.12",
"OC-POL",
"",
"",
"Tablet D (Échancrée) is on wood felled c. 1493–1509 CE (Ferrara et al. 2024); tablets O, Q and three Rome tablets are on 18th–19th-century wood",
"A possible independent invention of writing on Rapa Nui; undeciphered.",
"wood carving",
"rongorongo tablets",
"record and writing",
"scholars; Rapa Nui community",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.5;F1.3",
"low",
"Invention before or after European contact (Roggeveen 1722; Spanish visit 1770) is debated; old wood could be driftwood kept for years before carving.",
"canon_firsts.csv"
],
[
"INV009",
"zero as numeral",
"zero",
"first-known",
"Things",
"THEME",
"AM-MES;AS-SAS;WA-MES",
"-36",
"",
"Long Count zero by 36 BCE (Chiapa de Corzo Stela 2); Babylonian placeholder c. 300 BCE; Indian zero (Gwalior) 876 CE",
"Zero was invented more than once, as placeholder and as number.",
"inscriptions; manuscripts",
"Long Count stelae; Gwalior inscription; Bakhshali manuscript",
"record and writing",
"historians of mathematics",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.30",
"medium",
"Bakhshali manuscript radiocarbon spread (3rd–10th c.) disputed.",
"canon_firsts.csv"
],
[
"INV010",
"counting tokens",
"tokens",
"first-known",
"Things",
"F1.9a",
"WA-MES;WA-LEV;WA-IRN",
"-8000",
"",
"c. 8000 BCE",
"First known clay tokens used for counting goods; a proposed ancestor of writing.",
"clay",
"tokens; bullae",
"record and writing;exchange and value",
"D. Schmandt-Besserat; archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.3",
"medium",
"Token-to-writing thesis (Schmandt-Besserat) contested.",
"canon_firsts.csv"
],
[
"INV011",
"tally marks",
"Lebombo bone; Ishango bone",
"first-known",
"Things",
"F1.6",
"AF-SOU;AF-CEN",
"-42000",
"",
"Lebombo c. 44,000–43,000 BP; Ishango c. 20,000 BP",
"Among the earliest proposed counting records: notched bones from southern and central Africa.",
"baboon fibula; bone",
"Lebombo bone; Ishango bone",
"record and writing",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"low",
"Interpretations as calendars or arithmetic contested.",
"canon_firsts.csv"
],
[
"INV012",
"map (earliest known)",
"Babylonian Map of the World",
"first-known",
"Things",
"THEME",
"WA-MES;AS-CHN",
"-600",
"",
"Babylonian Map of the World c. 600 BCE; Nippur city plan c. 1500 BCE; Mawangdui maps 168 BCE",
"First known surviving world map, on a clay tablet; China's earliest topographic maps on silk follow.",
"clay; silk",
"Imago Mundi tablet; Nippur plan; Mawangdui maps",
"record and writing;rule and display",
"historians of cartography",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.3;F1.28",
"medium",
"Older \"maps\" (Pavlov, Çatalhöyük mural) are contested (low).",
"canon_firsts.csv"
],
[
"INV013",
"portolan chart",
"Carta Pisana",
"first-known",
"Things",
"F1.11",
"EU-WCE;EU-IBE",
"1275",
"",
"c. 1275",
"First known surviving sea chart with rhumb lines.",
"vellum; ink",
"Carta Pisana",
"record and writing;transport",
"historians of cartography",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.13",
"medium",
"Date debated (late 13th century).",
"canon_firsts.csv"
],
[
"INV014",
"astrolabe",
"asturlab",
"first-known",
"Things",
"F1.10;F1.11",
"WA-MES;WA-IRN;EU-GRR",
"927",
"",
"Oldest surviving by Nastulus 927–8; theory Hellenistic",
"Earliest known surviving astrolabe, made in the Abbasid world from Greek theory.",
"brass; engraving",
"Nastulus astrolabe",
"tools;record and writing",
"historians of science",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.13",
"medium",
"Hellenistic invention likely (Hipparchus/Ptolemy); no earlier survivals.",
"canon_firsts.csv"
],
[
"INV015",
"water clock",
"clepsydra",
"first-known",
"Things",
"F1.6",
"AF-EGY",
"-1400",
"",
"Karnak clepsydra, reign of Amenhotep III c. 1400 BCE",
"First known surviving water clock.",
"alabaster; calibrated scales",
"Karnak clepsydra",
"record and writing;tools",
"Egyptologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.30",
"high",
"Babylonian water clocks may be as old.",
"canon_firsts.csv"
],
[
"INV016",
"sundial",
"shadow clock",
"first-known",
"Things",
"F1.6",
"AF-EGY",
"-1500",
"",
"c. 1500 BCE",
"First known shadow clocks.",
"stone",
"Egyptian shadow clocks",
"record and writing;tools",
"Egyptologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.30",
"medium",
"",
"canon_firsts.csv"
],
[
"INV017",
"mechanical clock (escapement)",
"Su Song clock tower",
"first-known",
"Things",
"F1.8;THEME",
"AS-CHN",
"1088",
"",
"Su Song 1088; Yi Xing's water-driven escapement 725",
"First known astronomical clock tower with an escapement, water-driven.",
"water wheel; escapement; gears",
"Su Song's clock tower (Kaifeng)",
"record and writing;tools",
"historians of technology (J. Needham)",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.30",
"high",
"European weight-driven verge clocks c. 1270–1300 are a separate invention (see next row).",
"canon_firsts.csv"
],
[
"INV018",
"mechanical clock (weight-driven)",
"verge and foliot",
"first-known",
"Things",
"F1.11",
"EU-WCE;EU-BLC",
"1280",
"",
"c. 1270–1300",
"First known weight-driven mechanical clocks with verge escapement.",
"iron; weights; verge escapement",
"Salisbury Cathedral clock (c. 1386); Wells clock",
"record and writing;tools",
"historians of technology",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.30",
"medium",
"Exact first date unknown; textual evidence c. 1270s–1280s.",
"canon_firsts.csv"
],
[
"INV019",
"geared computing device",
"Antikythera mechanism",
"first-known",
"Things",
"F1.11",
"EU-GRR",
"-150",
"",
"c. 150–100 BCE (dates debated to c. 200 BCE)",
"First known geared calculator, modelling the heavens.",
"bronze gears",
"Antikythera mechanism",
"tools;record and writing",
"archaeologists and historians of science",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_firsts.csv"
],
[
"INV020",
"pottery (South China)",
"Xianrendong pottery",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"-18000",
"",
"c. 20,000–19,000 cal BP",
"First known pottery vessels, made by hunter-gatherers long before farming.",
"fired clay",
"Xianrendong sherds; Yuchanyan sherds",
"food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"Wu et al. 2012; Yuchanyan c. 18,000 BP.",
"canon_firsts.csv"
],
[
"INV021",
"pottery (Japan and Amur)",
"Incipient Jōmon; Osipovka",
"first-known",
"Things",
"F1.8;F1.12a",
"AS-JPN;AS-NTH",
"-14500",
"",
"Odai Yamamoto I c. 16,500 cal BP (debated); Amur c. 16,000–15,000 BP",
"Early hunter-gatherer pottery in Japan and the Russian Far East, possibly independent of South China.",
"fired clay; cord marking",
"Incipient Jōmon; Osipovka pottery",
"food and storage",
"archaeologists",
"",
"none",
"ColBase (Japan Government Standard Terms); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"Relation to China debated.",
"canon_firsts.csv"
],
[
"INV022",
"pottery (Sahara)",
"Ounjougou pottery",
"first-known",
"Things",
"F1.6",
"AF-SAH",
"-9400",
"",
"c. 9400 BCE, Ounjougou (Mali)",
"First known pottery in Africa, made by hunter-gatherers in the green Sahara; independent invention.",
"fired clay; roulette decoration",
"Ounjougou sherds",
"food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R2",
"F1.5",
"high",
"Huysecom et al. 2009.",
"canon_firsts.csv"
],
[
"INV023",
"pottery (Amazonia)",
"Taperinha pottery",
"first-known",
"Things",
"F1.7",
"AM-AMZ",
"-5000",
"",
"c. 7,000–6,000 BP (Taperinha); San Jacinto (Colombia) and Valdivia (Ecuador) c. 4th millennium BCE",
"Among the earliest pottery in the Americas, made by fisher-foragers of the lower Amazon.",
"shell-tempered clay",
"Taperinha sherds",
"food and storage",
"archaeologists",
"",
"Indigenous-community",
"open-access excavation reports",
"R2",
"F1.5",
"medium",
"Dates (Roosevelt 1991) debated.",
"canon_firsts.csv"
],
[
"INV024",
"pottery (Southwest Asia)",
"Neolithic pottery",
"first-known",
"Things",
"F1.9a",
"WA-ANA;WA-LEV;WA-MES",
"-7000",
"",
"c. 7000 BCE",
"Pottery arrives after farming in Southwest Asia, reversing the East Asian order.",
"fired clay",
"",
"food and storage",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.3",
"medium",
"Teaches that the \"Neolithic package\" is regional.",
"canon_firsts.csv"
],
[
"INV025",
"fired clay figurines",
"Dolní Věstonice figurines",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"-27000",
"",
"c. 29,000–25,000 BP",
"First known fired-clay objects, made before any pottery vessel.",
"loess clay; firing",
"Venus of Dolní Věstonice",
"ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_firsts.csv"
],
[
"INV026",
"glass",
"glass beads; core-formed vessels",
"first-known",
"Things",
"F1.9a;F1.6",
"WA-MES;AF-EGY",
"-2500",
"",
"Glass beads c. 2500 BCE (Mesopotamia); core-formed vessels c. 1500 BCE",
"First known true glass, as beads, then vessels.",
"silica; soda; lime; colourants",
"Mesopotamian glass beads; Amarna glass",
"clothing and adornment;food and storage",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.5",
"medium",
"Faience and glazes older.",
"canon_firsts.csv"
],
[
"INV027",
"glassblowing",
"blown glass",
"first-known",
"Things",
"F1.9a;F1.11",
"WA-LEV",
"-50",
"",
"c. 1st century BCE (Jerusalem finds)",
"First known blown glass, which made glass cheap and common.",
"blowpipe; soda glass",
"Jewish Quarter (Jerusalem) waste; Roman blown glass",
"food and storage;exchange and value",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19",
"medium",
"",
"canon_firsts.csv"
],
[
"INV028",
"primary glass in West Africa",
"Ile-Ife glass",
"first-known",
"Things",
"F1.6",
"AF-GUI",
"1000",
"",
"c. 11th–15th century (Igbo Olokun)",
"First known glass made from raw materials in sub-Saharan Africa, a distinct high-lime high-alumina glass.",
"local sand; glass furnaces",
"Ife glass beads",
"clothing and adornment;exchange and value",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R2",
"F1.5",
"medium",
"Babalola et al. 2017–2018.",
"canon_firsts.csv"
],
[
"INV029",
"synthetic pigment",
"Egyptian blue",
"first-known",
"Things",
"F1.6",
"AF-EGY",
"-3200",
"",
"c. 3200 BCE",
"First known synthetic pigment, a calcium copper silicate.",
"silica; copper; lime; natron; firing",
"painted objects; pigment cakes",
"clothing and adornment;ritual and belief",
"archaeologists; conservation scientists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.28a",
"medium",
"",
"canon_firsts.csv"
],
[
"INV030",
"lacquer",
"Kuahuqiao lacquered bow",
"first-known",
"Things",
"F1.8",
"AS-CHN;AS-JPN",
"-6000",
"",
"Kuahuqiao lacquered bow c. 8,000 BP; Kakinoshima B (Hokkaido) lacquered threads from a burial dated c. 9,000 cal BP on soil samples, contested; burial context suggests c. 8,000–7,000 BP",
"First known lacquer use, recorded on a bow in China; a competing Japanese claim is older but contested.",
"urushi sap",
"Kuahuqiao bow; Kakinoshima lacquered fibre",
"tools;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"Kakinoshima dating challenged (low); Kuahuqiao medium.",
"canon_firsts.csv"
],
[
"INV031",
"porcelain",
"true porcelain (China)",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"580",
"",
"Sui–Tang white porcelain c. 6th–7th century; Eastern Han proto-porcelain",
"First known true porcelain, high-fired white ware from northern China.",
"kaolin; high firing",
"Xing ware; Ding ware",
"food and storage;exchange and value",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R2",
"F1.5;F1.14",
"medium",
"Definition of \"porcelain\" varies; some date it to the Eastern Han.",
"canon_firsts.csv"
],
[
"INV032",
"hard-paste porcelain (Europe)",
"Meissen",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"1708",
"",
"1708–1710, Dresden/Meissen (Tschirnhaus, Böttger)",
"European reinvention of hard-paste porcelain after centuries of imports.",
"kaolin; feldspar; high firing",
"Meissen porcelain",
"food and storage;rule and display",
"historians",
"",
"none",
"Met Open Access (CC0); Rijksmuseum (CC0); Wikimedia Commons",
"R2",
"F1.14;F1.17",
"high",
"A recurrence by imitation, not independent (F1.14).",
"canon_firsts.csv"
],
[
"INV033",
"rubber processing",
"Mesoamerican rubber",
"first-known",
"Things",
"F1.7",
"AM-MES",
"-1600",
"",
"Rubber balls at El Manatí c. 1600 BCE; processing described by Hosler et al. 1999",
"First known processed rubber: latex mixed with morning-glory juice to make bouncing balls, sandals and bands.",
"latex; Ipomoea juice",
"El Manatí balls",
"play and music;clothing and adornment",
"archaeologists; materials scientists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5;F1.14",
"high",
"Goodyear's vulcanisation (1844) is a later recurrence.",
"canon_firsts.csv"
],
[
"INV034",
"vulcanised rubber",
"vulcanisation",
"first-known",
"Things",
"THEME",
"GL",
"1844",
"",
"Goodyear patent 1844; Hancock 1843",
"Industrial recurrence of stabilised rubber by heating with sulphur.",
"rubber; sulphur; heat",
"tyres; waterproofs",
"clothing and adornment;transport",
"historians of technology",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.5;F1.22",
"high",
"Goodyear/Hancock priority dispute.",
"canon_firsts.csv"
],
[
"INV035",
"plastic (semi-synthetic and synthetic)",
"Parkesine; Bakelite",
"first-known",
"Things",
"THEME",
"EU-BLC;GL",
"1862",
"",
"Parkesine 1862; Bakelite (first fully synthetic) 1907",
"First known plastics, moulded from cellulose and later from phenol-formaldehyde.",
"cellulose nitrate; phenol-formaldehyde",
"Parkesine objects; Bakelite radios",
"exchange and value;tools",
"historians of technology",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.19;F1.22",
"high",
"",
"canon_firsts.csv"
],
[
"INV036",
"paper",
"Chinese paper",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"-150",
"",
"Western Han fragments (e.g. Fangmatan) 2nd century BCE; Cai Lun credited 105 CE",
"First known paper, made from plant fibre pulp.",
"hemp; bark; mould",
"Fangmatan map fragment; Xuanquanzhi fragments",
"record and writing",
"archaeologists; historians",
"",
"none",
"Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"The Cai Lun story is a tradition; archaeology shows earlier paper (F1.3).",
"canon_firsts.csv"
],
[
"INV037",
"paper outside China",
"Baghdad paper mill",
"first-known",
"Things",
"F1.10",
"WA-MES;AS-CEN",
"794",
"",
"Baghdad mill c. 794; Samarkand earlier by tradition",
"First known paper production outside China, in the Abbasid world.",
"linen rag; hemp",
"Abbasid manuscripts on paper",
"record and writing",
"historians",
"",
"none",
"Qatar Digital Library (open licence); Wikimedia Commons",
"R2",
"F1.13",
"medium",
"The Talas (751) prisoners story is a legend.",
"canon_firsts.csv"
],
[
"INV038",
"bark paper",
"amate",
"first-known",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Beaters from the early 1st millennium CE or earlier",
"An independent bark-paper tradition in Mesoamerica, beaten rather than pulped.",
"Ficus bark; stone beaters",
"amate; codices",
"record and writing;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"Not \"paper\" in the Chinese pulp sense; beater dating uncertain.",
"canon_firsts.csv"
],
[
"INV039",
"woodblock printing (dated)",
"Diamond Sutra",
"first-known",
"Things",
"F1.8;F1.9",
"AS-CHN;AS-KOR;AS-JPN",
"868",
"",
"Diamond Sutra 868 (earliest dated printed book); Bulguksa dharani before 751 (undated); Hyakumantō Darani 764–770",
"First known dated printed book, and earlier undated prints in Korea and Japan.",
"woodblock; paper; ink",
"Diamond Sutra; Mugujeonggwang dharani; Hyakumantō Darani",
"record and writing;ritual and belief",
"historians of the book",
"",
"sacred",
"Wikimedia Commons",
"R1",
"F1.5",
"high",
"Korean dharani dating debated (before 751).",
"canon_firsts.csv"
],
[
"INV040",
"block printing in the Islamic world",
"tarsh",
"first-known",
"Things",
"F1.10",
"AF-EGY",
"900",
"",
"c. 10th century Egypt",
"First known printing in the Islamic world: block-printed amulets.",
"blocks; paper",
"tarsh amulets",
"record and writing;ritual and belief",
"historians of the book",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.13;F1.16",
"medium",
"",
"canon_firsts.csv"
],
[
"INV041",
"movable type (ceramic)",
"Bi Sheng type",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"1040",
"",
"c. 1040 (described by Shen Kuo 1088)",
"First known movable type, of fired clay.",
"fired clay type",
"",
"record and writing",
"historians",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"high",
"No surviving books from Bi Sheng.",
"canon_firsts.csv"
],
[
"INV042",
"movable metal type",
"Jikji",
"first-known",
"Things",
"F1.8",
"AS-KOR",
"1377",
"",
"Jikji 1377 (earliest extant); earlier metal-type books recorded c. 1230s",
"Earliest surviving book printed with movable metal type.",
"cast bronze type",
"Jikji (BnF)",
"record and writing;ritual and belief",
"historians; UNESCO Memory of the World",
"",
"none",
"Wikimedia Commons; e-museum Korea (KOGL Type 1)",
"R1",
"F1.5;F1.24",
"high",
"Jikji is in Paris (BnF); return requested by Korea.",
"canon_firsts.csv"
],
[
"INV043",
"printing press",
"Gutenberg press",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"1450",
"",
"c. 1450 Mainz",
"First known printing press with cast movable type and oil ink in Europe.",
"screw press; type metal; oil ink",
"Gutenberg Bible",
"record and writing",
"historians of the book",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items)",
"R1",
"F1.5;F1.14",
"high",
"A recurrence; no proven transfer from East Asia.",
"canon_firsts.csv"
],
[
"INV044",
"lithography",
"lithography",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"1796",
"",
"1796–1798, Alois Senefelder",
"First planographic printing, from limestone.",
"limestone; grease; water",
"lithographs; posters",
"record and writing",
"historians",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_firsts.csv"
],
[
"INV045",
"photography (Niépce)",
"heliography",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"1826",
"",
"c. 1826–27",
"First known surviving camera photograph.",
"bitumen on pewter",
"View from the Window at Le Gras",
"record and writing",
"historians of photography",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.3",
"high",
"Daguerre (1839) and Talbot (1839–41) made practical processes.",
"canon_firsts.csv"
],
[
"INV046",
"photography (Hércules Florence)",
"photographie",
"first-known",
"Things",
"F1.7",
"AM-LAT",
"1833",
"",
"1833, Campinas (Brazil)",
"An independent invention of photographic printing in Brazil, named \"photographie\" by its maker.",
"silver nitrate; paper",
"Florence's printed labels",
"record and writing",
"Boris Kossoy; historians",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.3",
"medium",
"Recognised by B. Kossoy (1970s); a case of who gets written in (F1.3).",
"canon_firsts.csv"
],
[
"INV047",
"electric telegraph",
"telegraph",
"first-known",
"Things",
"F1.11;THEME",
"EU-BLC;GL",
"1837",
"",
"Cooke and Wheatstone 1837; Morse 1837–1844; Chappe optical 1794",
"First practical electric telegraphs.",
"wire; batteries; code",
"Cooke–Wheatstone telegraph; Morse key",
"record and writing",
"historians of technology",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.19;F1.13",
"high",
"Multiple claimants.",
"canon_firsts.csv"
],
[
"INV048",
"sound recording",
"phonautograph; phonograph",
"first-known",
"Things",
"THEME",
"EU-WCE;GL",
"1857",
"",
"Scott de Martinville phonautograph 1857; Edison phonograph 1877 (playback)",
"First known recording of sound, then playback.",
"soot on paper; tinfoil",
"phonautograms; tinfoil phonograph",
"play and music;record and writing",
"historians",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items)",
"R3",
"F1.4",
"high",
"",
"canon_firsts.csv"
],
[
"INV049",
"motion picture",
"cinématographe",
"first-known",
"Things",
"THEME",
"EU-WCE;GL",
"1888",
"",
"Le Prince 1888; Edison Kinetoscope 1891–93; Lumière 1895",
"First known moving-picture films and public screenings.",
"film stock; cameras",
"Roundhay Garden Scene; Lumière films",
"play and music;record and writing",
"film historians",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items)",
"R3",
"F1.4",
"high",
"Contested firsts by definition.",
"canon_firsts.csv"
],
[
"INV050",
"programmable computer",
"computer",
"first-known",
"Things",
"THEME",
"GL",
"1941",
"",
"Zuse Z3 1941; Colossus 1943–44; ENIAC 1945; Babbage's Analytical Engine designed 1837",
"First working programmable computers.",
"relays; valves",
"Z3; Colossus; ENIAC",
"record and writing;tools",
"historians of computing",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19;F1.23",
"medium",
"\"First\" depends on definition; women programmers of ENIAC obscured (F1.23).",
"canon_firsts.csv"
],
[
"INV051",
"World Wide Web",
"web",
"first-known",
"Things",
"THEME",
"EU-WCE;GL",
"1989",
"",
"Proposed 1989; first website 1991 (CERN)",
"First hypertext system on the internet, by Tim Berners-Lee at CERN.",
"HTML; HTTP; servers",
"info.cern.ch",
"record and writing;exchange and value",
"CERN; historians",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.21",
"high",
"",
"canon_firsts.csv"
],
[
"INV052",
"video game",
"Tennis for Two; Spacewar!",
"first-known",
"Things",
"THEME",
"GL",
"1958",
"",
"Tennis for Two 1958; Spacewar! 1962",
"First known interactive video games.",
"oscilloscope; computers",
"Tennis for Two; Spacewar!",
"play and music",
"game historians",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"medium",
"Earlier claims (1947 cathode-ray amusement device) exist.",
"canon_firsts.csv"
],
[
"INV053",
"farming (Fertile Crescent)",
"cereal domestication",
"first-known",
"Things",
"F1.9a",
"WA-LEV;WA-MES;WA-ANA;WA-IRN",
"-9500",
"",
"Cultivation c. 9500 BCE; domestic forms c. 8500 BCE",
"First known domestication of wheat, barley, lentil and pea.",
"—",
"einkorn; emmer; barley",
"food and storage",
"archaeobotanists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5",
"high",
"Multi-centre protracted model vs core area.",
"canon_firsts.csv"
],
[
"INV054",
"farming (China)",
"rice and millet domestication",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"-7000",
"",
"Millet c. 8000–6000 BCE (north); rice domestication c. 7000–5000 BCE (Yangtze)",
"Independent domestication of rice and millets.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"Shangshan rice use c. 9000 BCE claimed.",
"canon_firsts.csv"
],
[
"INV055",
"farming (New Guinea)",
"Kuk Swamp",
"first-known",
"Things",
"F1.12",
"OC-MEL",
"-5000",
"",
"Cultivation by c. 7000–4500 BCE",
"Independent agriculture of taro, banana and yam with drainage ditches.",
"ditches; mounds",
"",
"food and storage",
"archaeologists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.5;F1.3",
"medium",
"Kuk is a World Heritage site; counters the idea that farming came from outside.",
"canon_firsts.csv"
],
[
"INV056",
"farming (Mesoamerica)",
"squash and maize",
"first-known",
"Things",
"F1.7",
"AM-MES",
"-8000",
"",
"Squash c. 8000 BCE (Guilá Naquitz); maize c. 7000 BCE (Balsas, Xihuatoxtla)",
"Independent domestication of squash, then maize from teosinte.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV057",
"farming (Andes and Amazonia)",
"potato, manioc, squash",
"first-known",
"Things",
"F1.7",
"AM-AND;AM-AMZ",
"-8000",
"",
"Squash c. 8000 BCE (Ñanchoc); manioc c. 8000 BCE; potato c. 6000 BCE",
"Independent domestication of potato, quinoa, manioc, squash, peanut and cotton.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV058",
"farming (Eastern North America)",
"Eastern Agricultural Complex",
"first-known",
"Things",
"F1.7",
"AM-EWD",
"-3000",
"",
"c. 3000–2000 BCE",
"Independent domestication of squash, sunflower, sumpweed and goosefoot.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_firsts.csv"
],
[
"INV059",
"farming (Sahel and West Africa)",
"pearl millet and sorghum",
"first-known",
"Things",
"F1.6",
"AF-SAH;AF-NUB",
"-2500",
"",
"Pearl millet c. 2500 BCE (Mali); sorghum c. 3000 BCE (eastern Sudan)",
"Independent domestication of pearl millet, sorghum, African rice and yams.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV060",
"farming (Ethiopian highlands)",
"teff and enset",
"first-known",
"Things",
"F1.6",
"AF-HRN",
"",
"",
"Dates uncertain",
"Domestication of teff, enset and noog in the Ethiopian highlands.",
"—",
"",
"food and storage",
"archaeobotanists",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"Poor archaeobotanical record.",
"canon_firsts.csv"
],
[
"INV061",
"farming (South Asia)",
"Mehrgarh",
"first-known",
"Things",
"F1.9",
"AS-SAS",
"-7000",
"",
"c. 7000 BCE",
"Early farming with barley and locally domesticated zebu cattle.",
"—",
"",
"food and storage",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV062",
"aquaculture",
"Budj Bim eel traps",
"first-known",
"Things",
"F1.12",
"OC-AUS",
"-4600",
"",
"Oldest dated channel c. 6,600 years ago",
"Among the earliest known aquaculture: Gunditjmara channels and weirs for kooyang.",
"basalt channels; woven traps",
"eel traps",
"food and storage;tools",
"Gunditjmara people; archaeologists",
"",
"Indigenous-community",
"community-published site; Wikimedia Commons",
"R1",
"F1.5;F1.3",
"medium",
"Dating reported for one channel; ancient Chinese carp culture is a later recurrence.",
"canon_firsts.csv"
],
[
"INV063",
"bread",
"Shubayqa flatbread",
"first-known",
"Things",
"F1.9a",
"WA-LEV",
"-12400",
"",
"c. 14,400 BP (Natufian, Jordan)",
"First known bread, baked by hunter-gatherers before farming.",
"wild cereals; club-rush tubers",
"charred crumbs",
"food and storage",
"archaeobotanists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"F1.5",
"medium",
"Arranz-Otaegui et al. 2018.",
"canon_firsts.csv"
],
[
"INV064",
"beer and fermented drink",
"Raqefet; Jiahu",
"first-known",
"Things",
"THEME",
"WA-LEV;AS-CHN",
"-11000",
"",
"Raqefet Cave c. 13,000 BP (contested); Jiahu mixed drink c. 7000 BCE",
"First known fermented drinks, from the Natufian Levant and Neolithic China.",
"cereals; rice; honey; fruit",
"residues",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"Raqefet claim debated (low); Jiahu residue study (McGovern 2004, medium).",
"canon_firsts.csv"
],
[
"INV065",
"wine",
"Georgian Neolithic wine",
"first-known",
"Things",
"F1.9a;F1.11",
"WA-CAU",
"-6000",
"",
"c. 6000 BCE (Gadachrili Gora, Shulaveris Gora)",
"First known grape wine, in jars in southern Georgia.",
"grapes; clay jars",
"residues in jars",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5;F1.29",
"medium",
"McGovern et al. 2017; links to qvevri practice.",
"canon_firsts.csv"
],
[
"INV066",
"cheese",
"Kuyavian cheese sieves",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"-5200",
"",
"c. 5200 BCE (Kuyavia, Poland)",
"First known cheese-making, from milk residues in perforated pots.",
"milk; perforated pots",
"sieves",
"food and storage",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"Salque et al. 2013.",
"canon_firsts.csv"
],
[
"INV067",
"cacao use",
"Mayo-Chinchipe cacao",
"first-known",
"Things",
"F1.7",
"AM-AMZ;AM-AND",
"-3300",
"",
"c. 5,300 BP (Santa Ana-La Florida, Ecuador)",
"First known cacao use, in the upper Amazon rather than Mesoamerica.",
"cacao; ceramic vessels",
"residues in pots",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.3",
"medium",
"Zarrillo et al. 2018 revised the Mesoamerican-first view.",
"canon_firsts.csv"
],
[
"INV068",
"coffee drinking",
"Yemeni coffee",
"first-known",
"Things",
"F1.10",
"WA-ARB",
"1450",
"",
"Mid-15th century Sufi circles in Yemen",
"First credible evidence of coffee as a drink.",
"roasting; brewing",
"",
"food and storage;ritual and belief",
"historians",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"Ethiopian goatherd legend is later folklore.",
"canon_firsts.csv"
],
[
"INV069",
"nixtamalisation",
"nixtamal",
"first-known",
"Things",
"F1.7",
"AM-MES",
"-1500",
"",
"c. 1500–1200 BCE (approximate)",
"Treating maize with lime, which made it nutritionally complete; a Mesoamerican invention.",
"maize; lime",
"",
"food and storage",
"archaeologists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"Earliest evidence poorly dated.",
"canon_firsts.csv"
],
[
"INV070",
"dog domestication",
"dog",
"first-known",
"Things",
"THEME",
"GL",
"-13000",
"",
"Bonn-Oberkassel c. 14,200 BP; earlier claims contested",
"First domesticated animal, from wolves, among hunter-gatherers.",
"—",
"",
"tools;transport",
"geneticists and archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"Place (Europe, Siberia, East Asia) debated.",
"canon_firsts.csv"
],
[
"INV071",
"horse domestication at Botai (revised)",
"Botai horses",
"first-known",
"Things",
"F1.12a",
"AS-CEN",
"-3500",
"",
"c. 3500 BCE",
"A changed first: Botai horses were long taught as the first domesticated or ridden horses; genomics (2018) show they are ancestors of Przewalski's horses, not of modern domestic horses.",
"—",
"harnessing debate; milk residues",
"transport;food and storage",
"archaeologists and geneticists",
"",
"none",
"Wikimedia Commons",
"R1",
"F1.3;F1.5",
"medium",
"Outram et al. 2009 (bit wear, milk) vs Gaunitz et al. 2018; Botai herding still argued.",
"canon_firsts.csv"
],
[
"INV072",
"horse domestication (DOM2)",
"modern domestic horse",
"first-known",
"Things",
"F1.12a",
"AS-CEN;EU-EER",
"-2200",
"",
"c. 2200 BCE, lower Volga–Don",
"First known ancestors of modern domestic horses, spreading fast with spoked-wheel chariots.",
"—",
"",
"transport;war",
"geneticists",
"",
"none",
"Wikimedia Commons",
"R1",
"F1.3;F1.5",
"high",
"Librado et al. 2021; Yamnaya riding claim (Trautmann et al. 2023) contested.",
"canon_firsts.csv"
],
[
"INV073",
"dromedary domestication",
"dromedary",
"first-known",
"Things",
"F1.10;F1.9a",
"WA-ARB",
"-1000",
"",
"Late 2nd–early 1st millennium BCE",
"First domesticated dromedaries in Arabia, which opened desert caravan trade.",
"—",
"",
"transport",
"archaeozoologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"Dates debated; UAE sites (e.g. Tell Abraq, Mleiha) relevant.",
"canon_firsts.csv"
],
[
"INV074",
"llama and alpaca domestication",
"camelid domestication",
"first-known",
"Things",
"F1.7",
"AM-AND",
"-4000",
"",
"c. 6000–4000 BCE (approximate)",
"Domestication of camelids in the Andes for fibre, meat and carrying.",
"—",
"",
"transport;clothing and adornment",
"archaeozoologists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.5",
"low",
"",
"canon_firsts.csv"
],
[
"INV075",
"native copper working",
"Çayönü copper",
"first-known",
"Things",
"F1.9a",
"WA-ANA;WA-MES",
"-8200",
"",
"Çayönü c. 8200 BCE; Shanidar pendant c. 8700 BCE (approximate)",
"First known metal working: cold-hammered and annealed native copper.",
"native copper; hammering; annealing",
"beads; awls; pendant",
"clothing and adornment;tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV076",
"copper smelting (Balkans)",
"Belovode",
"first-known",
"Things",
"F1.11",
"EU-BYZ",
"-5000",
"",
"c. 5000 BCE (Belovode, Serbia)",
"First known copper smelting from ore.",
"malachite; furnace; slag",
"slag; copper droplets",
"tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5",
"medium",
"Radivojević et al. 2010; competes with Iran.",
"canon_firsts.csv"
],
[
"INV077",
"copper smelting (Iran)",
"Tal-i Iblis",
"first-known",
"Things",
"F1.9a",
"WA-IRN",
"-4800",
"",
"c. 5th millennium BCE",
"Early crucible smelting of copper on the Iranian plateau.",
"crucibles; copper ore",
"crucibles; slag",
"tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"Dating vs Belovode close; Anatolian claims too.",
"canon_firsts.csv"
],
[
"INV078",
"gold working",
"Varna gold",
"first-known",
"Things",
"F1.11",
"EU-BYZ",
"-4600",
"",
"c. 4600–4200 BCE",
"First known large hoard of worked gold, from a cemetery at Varna.",
"gold; hammering; casting",
"Varna grave goods",
"clothing and adornment;rule and display",
"archaeologists",
"",
"funerary",
"Wikimedia Commons",
"R2",
"F1.5;F1.17",
"high",
"",
"canon_firsts.csv"
],
[
"INV079",
"lost-wax casting",
"Mehrgarh amulet; Nahal Mishmar",
"first-known",
"Things",
"F1.9;F1.9a",
"AS-SAS;WA-LEV",
"-4500",
"",
"Mehrgarh wheel-shaped amulet c. 4500–3600 BCE; Nahal Mishmar hoard c. 3700 BCE",
"First known lost-wax castings.",
"copper; wax model; clay mould",
"Mehrgarh amulet; Nahal Mishmar objects",
"tools;ritual and belief",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"Thoury et al. 2016.",
"canon_firsts.csv"
],
[
"INV080",
"tin bronze",
"Pločnik foil",
"first-known",
"Things",
"F1.11",
"EU-BYZ",
"-4650",
"",
"c. 4650 BCE (Pločnik, Serbia); regular tin bronze c. 3000 BCE",
"First known tin-bronze object.",
"copper; tin ore",
"foil",
"tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"Radivojević et al. 2013; single find.",
"canon_firsts.csv"
],
[
"INV081",
"metallurgy (Andes)",
"Jiskairumoko gold",
"first-known",
"Things",
"F1.7",
"AM-AND",
"-2000",
"",
"c. 2000 BCE (Jiskairumoko, Peru)",
"Independent start of metallurgy in the Andes with hammered gold foil.",
"gold; hammering",
"gold beads",
"clothing and adornment",
"archaeologists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"Aldenderfer et al. 2008.",
"canon_firsts.csv"
],
[
"INV082",
"native copper (Great Lakes)",
"Old Copper Complex",
"first-known",
"Things",
"F1.7",
"AM-EWD",
"-7500",
"",
"c. 9,500–7,000 BP (recent redating)",
"Among the world's earliest metal working: Great Lakes peoples hammered native copper into tools.",
"native copper; cold hammering; annealing",
"points; awls; knives",
"tools",
"archaeologists",
"",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.5;F1.3",
"medium",
"Pompeani et al. 2021 dating.",
"canon_firsts.csv"
],
[
"INV083",
"metallurgy (West Mexico)",
"Tarascan metallurgy",
"first-known",
"Things",
"F1.7",
"AM-MES",
"650",
"",
"c. 600–800 CE",
"Metallurgy in West Mexico, probably introduced by sea from South America.",
"copper; bronze; lost-wax",
"bells; tweezers",
"clothing and adornment;ritual and belief",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"Hosler's maritime-contact thesis.",
"canon_firsts.csv"
],
[
"INV084",
"platinum working",
"La Tolita platinum",
"first-known",
"Things",
"F1.7",
"AM-AND",
"-100",
"",
"c. 1st century BCE–1st century CE (approximate)",
"First known working of platinum, sintered with gold by La Tolita-Tumaco metalworkers.",
"platinum grains; gold; sintering",
"nose rings; ornaments",
"clothing and adornment",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_firsts.csv"
],
[
"INV085",
"meteoric iron",
"Gerzeh beads",
"first-known",
"Things",
"F1.6",
"AF-EGY",
"-3200",
"",
"c. 3200 BCE",
"First known iron objects, hammered from meteorites.",
"meteoric iron; hammering",
"Gerzeh beads; Tutankhamun's dagger",
"clothing and adornment",
"archaeometallurgists",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_firsts.csv"
],
[
"INV086",
"iron smelting (Anatolia)",
"Hittite-era iron",
"first-known",
"Things",
"F1.9a",
"WA-ANA",
"-2000",
"",
"Early smelted iron c. 2000 BCE (Kaman-Kalehöyük); common after c. 1200 BCE",
"First known smelted iron.",
"bloomery furnace",
"blades",
"tools;war",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"\"Hittite monopoly\" story is outdated.",
"canon_firsts.csv"
],
[
"INV087",
"iron smelting (sub-Saharan Africa)",
"Nok and Taruga iron",
"first-known",
"Things",
"F1.6",
"AF-GUI;AF-SAH",
"-800",
"",
"Nok furnaces (incl. Taruga) mostly mid-1st millennium BCE; Taruga dates spread c. 800 BCE–50 CE; Great Lakes c. 1st millennium BCE",
"Early iron smelting in West and East Africa, likely independent.",
"bloomery furnaces; bellows",
"slag; tools",
"tools;war",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5;F1.3",
"medium",
"Independence from North Africa debated; dates vary by site.",
"canon_firsts.csv"
],
[
"INV088",
"iron smelting (early African claims)",
"Lejja; Termit",
"first-known",
"Things",
"F1.6",
"AF-GUI;AF-SAH",
"-2000",
"",
"Lejja c. 2000 BCE and Termit c. 1500 BCE claimed",
"Contested claims for much earlier iron smelting in Nigeria and Niger.",
"slag blocks",
"slag",
"tools",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.3",
"low",
"Radiocarbon on charcoal contested; teach as disputed.",
"canon_firsts.csv"
],
[
"INV089",
"cast iron",
"Chinese cast iron",
"first-known",
"Things",
"F1.8",
"AS-CHN",
"-500",
"",
"c. 5th century BCE",
"First known cast iron, poured into moulds.",
"blast furnace; moulds",
"tools; cooking vessels",
"tools;food and storage",
"historians of technology",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5;F1.19",
"medium",
"Some date it to the 8th century BCE.",
"canon_firsts.csv"
],
[
"INV090",
"crucible steel",
"wootz",
"first-known",
"Things",
"F1.9",
"AS-SAS",
"-300",
"",
"c. 3rd century BCE (South India, Sri Lanka)",
"Early high-carbon crucible steel, later forged into \"Damascus\" blades.",
"crucibles; iron; carbon",
"ingots; blades",
"war;tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"low",
"Dates and sites debated.",
"canon_firsts.csv"
],
[
"INV091",
"zinc distillation",
"Zawar zinc",
"first-known",
"Things",
"F1.9",
"AS-SAS",
"1000",
"",
"earliest zinc-smelting ash at Zawar dated 840±110 CE; industrial scale from the 11th–12th c.",
"First known industrial zinc production by distillation.",
"retorts; zinc ore",
"retorts",
"tools",
"archaeometallurgists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"medium",
"Checked (Craddock et al.; Gurjar et al. 2001): zinc mining at Zawar from c. 5th c. BCE, metallic zinc by distillation from c. 9th c. CE.",
"canon_firsts.csv"
],
[
"INV092",
"string",
"Abri du Maras cord",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"-50000",
"",
"c. 41,000–52,000 BP",
"First known twisted cord, made by Neanderthals.",
"plant fibre; twisting",
"cord fragment",
"tools",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.18",
"medium",
"Hardy et al. 2020.",
"canon_firsts.csv"
],
[
"INV093",
"spun fibre",
"Dzudzuana flax",
"first-known",
"Things",
"F1.9a;F1.11",
"WA-CAU",
"-28000",
"",
"c. 30,000 BP",
"Among the earliest spun and dyed plant fibres.",
"wild flax; twisting",
"fibres",
"clothing and adornment",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Kvavadze et al. 2009; fibres could be natural.",
"canon_firsts.csv"
],
[
"INV094",
"woven textile impressions",
"Pavlov textiles",
"first-known",
"Things",
"F1.11",
"EU-WCE",
"-25000",
"",
"c. 27,000–25,000 BP",
"First known evidence of woven textiles, as impressions in fired clay.",
"plant fibre weaving",
"impressions",
"clothing and adornment",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Adovasio, Soffer and colleagues.",
"canon_firsts.csv"
],
[
"INV095",
"twined textiles (Americas)",
"Guitarrero Cave",
"first-known",
"Things",
"F1.7",
"AM-AND",
"-10000",
"",
"c. 12,000–10,000 BP",
"First known textiles of the Americas.",
"plant fibre; twining",
"twined fragments",
"clothing and adornment",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Jolie et al. 2011.",
"canon_firsts.csv"
],
[
"INV096",
"linen textiles",
"Nahal Hemar",
"first-known",
"Things",
"F1.9a",
"WA-LEV",
"-6500",
"",
"c. 6500 BCE",
"Early surviving linen textiles, made mostly without a loom.",
"flax; twining; netting",
"Nahal Hemar textiles",
"clothing and adornment;ritual and belief",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_firsts.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
