insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"INS020",
"Qing Imperial Household workshops (Zaobanchu)",
"Palace workshops",
"institution",
"People",
"F1.8",
"AS-CHN",
"1693",
"1924",
"approx.",
"Court workshops made enamel, glass, jade, clocks and lacquer, with Jesuit and Chinese craftsmen working together.",
"painted enamel;glass;jade carving",
"snuff bottle;clock;cloisonne",
"rule and display",
"Qing court archives",
"the named artisans in archives",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Met Open Access (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.13;F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS021",
"Canton Thirteen Factories",
"Cohong system;Canton system",
"institution",
"People",
"F1.8;F1.13",
"AS-CHN",
"1757",
"1842",
"approx.",
"Foreign trade was limited to Canton, where export painters and porcelain decorators made goods to European order.",
"export painting;porcelain decoration",
"export painting;armorial porcelain",
"exchange and value",
"Qing state; East India companies",
"the export painters and workshop labour",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Yale Center for British Art (public domain);collection search link-out only (works in copyright)",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS022",
"National Palace Museum (Taipei)",
"NPM",
"institution",
"People",
"F1.8",
"AS-CHN",
"1965",
"",
"approx.",
"The museum holds imperial collections shipped from mainland China in 1948-49.",
"collection;open data",
"palace object",
"rule and display",
"Republic of China",
"the contested ownership",
"none",
"National Palace Museum Taipei Open Data (check per-item terms)",
"R3",
"F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS023",
"China Academy of Art",
"National Academy of Art Hangzhou",
"institution",
"People",
"F1.8",
"AS-CHN",
"1928",
"",
"approx.",
"Founded by Cai Yuanpei and Lin Fengmian, it joined Chinese and Western art teaching.",
"painting;design",
"artwork",
"care and access",
"founders",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR038",
"Bunwon royal kilns (Gwangju)",
"Saongwon Bunwon",
"maker-community",
"People",
"F1.8",
"AS-KOR",
"1467",
"1883",
"approx.",
"Royal kilns made white porcelain for the Joseon court with conscripted potters.",
"white porcelain",
"jar;bowl",
"food and storage;ritual and belief",
"Joseon state",
"the conscripted potters",
"none",
"e-Museum Korea (KOGL Type 1 items);Met Open Access (CC0)",
"R3",
"F1.23",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS024",
"Dohwaseo",
"Bureau of Painting",
"institution",
"People",
"F1.8",
"AS-KOR",
"1392",
"1894",
"approx.",
"The Joseon court painting bureau trained painters for records and documentary painting.",
"ink and colour",
"uigwe;portrait",
"record and writing;rule and display",
"Joseon state",
"the painters' low status",
"none",
"e-Museum Korea (KOGL Type 1 items);collection search link-out only (works in copyright)",
"R3",
"F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR039",
"Korean potters taken to Japan (Imjin War)",
"Korean potters in Japan",
"maker-community",
"People",
"F1.8",
"AS-KOR;AS-JPN",
"1592",
"1700",
"approx.",
"Japanese lords took Korean potters during the 1592-98 invasions, founding kilns such as Arita, Satsuma and Hagi.",
"porcelain;stoneware;climbing kiln",
"bowl;porcelain",
"food and storage",
"historians",
"the potters taken by force",
"human-flow",
"e-Museum Korea (KOGL Type 1 items);collection search link-out only (works in copyright)",
"R2",
"F1.13;F1.19a;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR040",
"Arita kilns",
"Imari ware kilns;Hizen porcelain",
"maker-community",
"People",
"F1.8;F1.13",
"AS-JPN",
"1616",
"",
"approx.; living",
"Kilns at Arita, begun by Korean potters such as Yi Sam-pyeong, made Japan's first porcelain and supplied the VOC export trade shipped from Imari.",
"porcelain;underglaze blue;overglaze enamel (Kakiemon)",
"dish;vase;export ware",
"food and storage;exchange and value",
"historians; the Nabeshima domain",
"the Korean potters brought by force",
"human-flow;living-community",
"Rijksmuseum (CC0);Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR041",
"Raku family",
"Raku lineage",
"maker-community",
"People",
"F1.8",
"AS-JPN",
"1570",
"",
"approx.; living, 16th generation",
"From Chojiro, working with Sen no Rikyu, a single family has hand-built and fired low-temperature tea bowls for over 400 years.",
"hand-built earthenware;raku firing",
"tea bowl",
"food and storage;ritual and belief",
"the family and the tea schools",
"the tile-making origins of the family",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.29",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR042",
"Nishijin weavers",
"Nishijin-ori",
"maker-community",
"People",
"F1.8",
"AS-JPN",
"1467",
"",
"approx.; district named after the Onin War western camp; living",
"Kyoto weavers use drawlooms (and Jacquard looms, brought back from Lyon c.1873) for brocade obi and kimono.",
"drawloom;Jacquard loom;brocade",
"obi;kimono;priest's robe",
"clothing and adornment",
"historians; Nishijin guilds",
"home-based outworkers",
"living-community",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR043",
"Ukiyo-e publishers (hanmoto)",
"Hanmoto;Edo publishers",
"maker-community",
"People",
"F1.8",
"AS-JPN",
"1680",
"1900",
"approx.",
"Publishers such as Tsutaya Juzaburo commissioned designers and hired carvers and printers, controlling what prints were made and sold.",
"publishing;woodblock production;censorship seals",
"print;illustrated book",
"exchange and value;record and writing",
"historians",
"the carvers (horishi) and printers (surishi)",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Art Institute of Chicago (CC0);National Diet Library Digital Collections (public-domain items)",
"R2",
"F1.17;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS025",
"Dejima",
"Deshima",
"institution",
"People",
"F1.8;F1.13",
"AS-JPN",
"1641",
"1859",
"approx.",
"The VOC's artificial-island trading post in Nagasaki was Japan's main channel for European books, instruments and the porcelain trade.",
"trade;translation (rangaku)",
"porcelain;book;scientific instrument",
"exchange and value",
"Tokugawa shogunate; VOC",
"the Japanese interpreters and enslaved Asian servants of the Dutch",
"human-flow",
"Rijksmuseum (CC0);National Diet Library Digital Collections (public-domain items)",
"R3",
"F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS026",
"Tokyo School of Fine Arts",
"Tokyo Bijutsu Gakko",
"institution",
"People",
"F1.8",
"AS-JPN",
"1887",
"",
"approx.; now Tokyo University of the Arts",
"The Meiji state's art school, led early by Okakura Kakuzo, taught Nihonga, sculpture, lacquer and metalwork, and trained many Chinese and Korean artists.",
"painting;lacquer;metal casting",
"artwork",
"care and access",
"Meiji state; Okakura Kakuzo and Fenollosa",
"its role in colonial art education in Korea and Taiwan",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS027",
"Japan Folk Crafts Museum",
"Nihon Mingeikan",
"institution",
"People",
"F1.8",
"AS-JPN",
"1936",
"",
"approx.",
"Yanagi Soetsu's museum made a collection the argument of the Mingei movement.",
"collecting;display",
"ceramic;textile;furniture",
"rule and display",
"Yanagi Soetsu and Mingei members",
"the makers of the anonymous objects; Korean objects acquired under colonial rule",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.24;F1.29",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS028",
"Living National Treasures (Japan)",
"Holders of Important Intangible Cultural Properties",
"institution",
"People",
"F1.8",
"AS-JPN",
"1955",
"",
"approx.",
"The state names individual master craftspeople and funds their teaching, a model copied by Korea and UNESCO.",
"certification;apprenticeship funding",
"ceramics;textile;lacquer",
"care and access",
"Japanese state (1950 Law for Protection of Cultural Properties)",
"craftspeople working outside certified lineages",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS029",
"Toyota Production System",
"Lean production",
"institution",
"People",
"F1.8;F1.13",
"AS-JPN",
"1950",
"",
"approx.",
"Toyota's just-in-time and kanban methods reorganised factory production worldwide.",
"just-in-time;kanban;continuous improvement",
"car",
"transport;tools",
"Taiichi Ohno; Toyota",
"supplier workers who absorb the risk",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR044",
"Mughal karkhanas",
"Imperial workshops",
"maker-community",
"People",
"F1.9;F1.10",
"AS-SAS",
"1556",
"1857",
"approx.",
"Imperial workshops gathered weavers, jewellers, armourers and painters under court supervision, described in the Ain-i-Akbari.",
"weaving;enamel;jade carving;painting",
"textile;dagger;manuscript;carpet",
"rule and display;war",
"Abu'l Fazl (Ain-i-Akbari, c.1590)",
"the workers, rarely named",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);collection search link-out only (works in copyright)",
"R1",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR045",
"Kashmir shawl workshops",
"Kani shawl karkhanas",
"maker-community",
"People",
"F1.9;F1.10",
"AS-SAS;AS-HIM",
"1600",
"1880",
"approx.",
"Weavers made twill-tapestry shawls from pashmina fibre whose boteh pattern was copied by Paisley and Lyon mills.",
"twill tapestry;pashmina;talim (coded design)",
"shawl",
"clothing and adornment;exchange and value",
"historians",
"the weavers under heavy taxes and debt; Ladakhi and Tibetan herders",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.14;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR046",
"Banaras weavers",
"Banarasi weavers",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1600",
"",
"approx.; living",
"Mostly Muslim Ansari weaver families make silk brocade saris with zari, now under pressure from power looms.",
"brocade;zari;Jacquard",
"sari",
"clothing and adornment",
"historians; weaver communities",
"the weavers' debt to traders",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR047",
"Dhaka muslin weavers",
"Dhakai muslin",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1600",
"1850",
"approx.",
"Weavers made extremely fine muslin from local cotton; British competition and colonial policy destroyed the trade.",
"fine hand-spinning;weaving",
"muslin",
"clothing and adornment;exchange and value",
"historians",
"the spinners, often women",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.19;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR048",
"Salvi patola weavers (Patan)",
"Patan patola",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1600",
"",
"approx.; living",
"The Salvi family weaves silk double ikat, where both warp and weft are resist-dyed before weaving.",
"double ikat;silk",
"patola",
"clothing and adornment;ritual and belief",
"the family",
"patola copied in Indonesia where it was prized",
"living-community",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR049",
"Kalamkari workshops",
"Machilipatnam and Srikalahasti",
"maker-community",
"People",
"F1.9;F1.13",
"AS-SAS",
"1600",
"",
"approx.; living",
"Painters and block printers made mordant-dyed chintz exported by Dutch and English companies across the world.",
"mordant dyeing;kalam pen;block printing",
"chintz;palampore",
"clothing and adornment;shelter",
"historians",
"the dyers' names; European imitation",
"living-community",
"Met Open Access (CC0);Rijksmuseum (CC0)",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR050",
"Channapatna toymakers",
"Channapatna",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1790",
"",
"approx.; tradition links it to Tipu Sultan; living",
"Turners make lathe-turned wooden toys coloured with lac, a craft recently recast as safe, natural design.",
"lathe-turning;lac colour",
"toy",
"play and music",
"historians; craft agencies",
"the legend's reliability",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR051",
"Swamimalai sthapatis",
"Swamimalai bronze casters",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1600",
"",
"approx.; living",
"Family lineages cast bronze images by lost-wax following shilpa texts, continuing the Chola tradition.",
"lost-wax casting;clay moulding",
"processional image",
"ritual and belief",
"the families; historians",
"artisans outside hereditary lineages",
"sacred;living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.16;F1.29",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR052",
"Vishwakarma communities",
"Vishwakarma",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1000",
"",
"approx.; living",
"Hereditary communities of smiths, carpenters, stone carvers and metalworkers claim descent from the divine architect Vishwakarma.",
"metalwork;carpentry;stone carving",
"tool;temple;image",
"tools;shelter",
"the communities; anthropologists",
"the caste hierarchy placed on them",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.23",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR053",
"Patua communities (Bengal)",
"Chitrakar",
"maker-community",
"People",
"F1.9",
"AS-SAS",
"1700",
"",
"approx.; living",
"Scroll painters sing and paint narrative scrolls, now about news and health as well as myth.",
"scroll painting;song",
"scroll",
"record and writing;ritual and belief",
"the communities",
"the mixed Hindu-Muslim identity of patuas",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.4",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS030",
"English East India Company",
"EIC",
"institution",
"People",
"F1.9;F1.11;F1.13",
"AS-SAS;EU-BLC;AS-CHN",
"1600",
"1874",
"approx.",
"The company traded Indian textiles, ran commissioned painting and took over India's revenue, reshaping textile production.",
"trade;procurement;taxation",
"textile;tea;porcelain",
"exchange and value;rule and display",
"British crown charter",
"the weavers it controlled; enslaved people in its territories",
"human-flow",
"Yale Center for British Art (public domain);collection search link-out only (works in copyright)",
"R2",
"F1.13;F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS031",
"Government art schools in colonial India",
"Madras 1850; Calcutta 1854; Bombay (JJ) 1857; Lahore (Mayo) 1875",
"institution",
"People",
"F1.9",
"AS-SAS",
"1850",
"",
"approx.",
"Colonial art schools taught drawing and 'improved' crafts; Lockwood Kipling ran the Mayo School in Lahore.",
"drawing;craft training",
"craft;drawing",
"care and access",
"colonial state",
"the craft teachers from hereditary communities",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS032",
"Kala Bhavana",
"Santiniketan art school",
"institution",
"People",
"F1.9",
"AS-SAS",
"1919",
"",
"approx.",
"Rabindranath Tagore's art school at Visva-Bharati joined painting, mural and craft.",
"mural;printmaking;craft",
"artwork",
"care and access",
"Tagore; Nandalal Bose",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS033",
"National Institute of Design (Ahmedabad)",
"NID",
"institution",
"People",
"F1.9",
"AS-SAS",
"1961",
"",
"approx.",
"India's first design school followed Charles and Ray Eames's India Report (1958).",
"design education",
"product;textile;graphics",
"care and access",
"Government of India; Gira and Gautam Sarabhai",
"the craftspeople it studied",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS034",
"All India Handicrafts Board",
"AIHB",
"institution",
"People",
"F1.9",
"AS-SAS",
"1952",
"2000",
"approx.",
"Kamaladevi Chattopadhyay's board funded, marketed and documented crafts after independence.",
"policy;marketing",
"craft",
"exchange and value",
"Government of India",
"craftspeople's own voice in policy",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS035",
"Self Employed Women's Association",
"SEWA",
"institution",
"People",
"F1.9",
"AS-SAS",
"1972",
"",
"approx.",
"A union of women workers in the informal economy, including embroiderers, organises and markets craft.",
"cooperative",
"craft",
"exchange and value",
"Ela Bhatt",
"",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS036",
"Aarong",
"BRAC Aarong",
"institution",
"People",
"F1.9",
"AS-SAS",
"1978",
"",
"approx.",
"BRAC's retail chain buys craft from rural producers in Bangladesh.",
"retail;cooperative",
"textile;craft",
"exchange and value",
"BRAC",
"",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS037",
"Derge Parkhang",
"Derge printing house",
"institution",
"People",
"F1.9",
"AS-HIM",
"1729",
"",
"approx.; living",
"The woodblock printing house at Derge carves and prints Tibetan Buddhist texts by hand.",
"woodblock carving;hand printing",
"book;block",
"record and writing;ritual and belief",
"Derge kings; monks",
"",
"sacred;living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.28;F1.5",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR054",
"Javanese and Indo-European batik workshops",
"Batik Belanda;batik pesisir",
"maker-community",
"People",
"F1.9",
"AS-ISE",
"1840",
"1940",
"approx.",
"Workshops on Java's north coast, many run by Indo-European and Chinese-Indonesian women (e.g. Eliza van Zuylen), made batik for Dutch and local markets.",
"batik;canting;cap (block)",
"sarong;cloth",
"clothing and adornment",
"historians",
"the women who drew and dyed the cloth",
"none",
"Rijksmuseum (CC0);Tropenmuseum/Wereldmuseum photos on Wikimedia Commons (CC BY-SA);Met Open Access (CC0)",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS038",
"Dutch East India Company",
"VOC",
"institution",
"People",
"F1.9;F1.11;F1.13",
"AS-ISE;EU-BLC;AF-SOU",
"1602",
"1799",
"approx.",
"The VOC shipped porcelain, textiles and spices, ordered goods to design, and held enslaved people in its colonies.",
"trade;procurement",
"porcelain;textile",
"exchange and value",
"Dutch state charter",
"enslaved people and Banda Islanders killed in 1621",
"human-flow",
"Rijksmuseum (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.13;F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS039",
"Ecole des Beaux-Arts de l'Indochine",
"EBAI",
"institution",
"People",
"F1.9",
"AS-MSE",
"1925",
"1945",
"approx.",
"The Hanoi art school under Victor Tardieu and Nam Son taught lacquer and silk painting as modern art.",
"lacquer;silk painting",
"painting",
"care and access",
"French colonial state",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS040",
"Manila galleon trade",
"Galeon de Manila",
"institution",
"People",
"F1.9;F1.7;F1.13",
"AS-ISE;AM-LAT",
"1565",
"1815",
"approx.",
"Galleons carried Chinese silk and porcelain to Acapulco for silver, moving craft goods and people across the Pacific.",
"trade",
"silk;porcelain;biombo",
"exchange and value;transport",
"Spanish crown",
"Asian enslaved people and sailors",
"human-flow",
"collection search link-out only (works in copyright)",
"R2",
"F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR055",
"Tiraz workshops",
"Dar al-Tiraz",
"maker-community",
"People",
"F1.10",
"AF-EGY;WA-MES;EU-IBE",
"700",
"1300",
"approx.",
"State workshops wove textiles with inscribed bands naming the ruler, used as robes of honour.",
"tapestry weave;embroidery;inscription",
"tiraz band;robe",
"rule and display;clothing and adornment",
"historians",
"the weavers",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR056",
"Kashan lustre potters",
"Abu Tahir family",
"maker-community",
"People",
"F1.10",
"WA-IRN",
"1180",
"1340",
"approx.",
"A family of potters in Kashan signed lustre tiles and wrote a treatise (Abu'l Qasim, 1301).",
"lustre;fritware",
"tile;bowl",
"ritual and belief",
"historians",
"the potters beyond the signing family",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.26;F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR057",
"Iznik potteries",
"Iznik",
"maker-community",
"People",
"F1.10",
"WA-ANA",
"1480",
"1700",
"approx.",
"Potters at Iznik made fritware tiles and vessels painted to designs sent from the Ottoman court studio, a centre-and-workshop system.",
"fritware;underglaze painting",
"tile;dish",
"shelter",
"historians",
"the potters",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS041",
"Ehl-i hiref",
"Community of the Talented",
"institution",
"People",
"F1.10",
"WA-ANA",
"1450",
"1800",
"approx.",
"The Ottoman court corps of artisans kept pay registers (from 1526) listing members, many recruited by devshirme or captured.",
"register;court workshop",
"object",
"rule and display",
"Ottoman court",
"captured and recruited artisans",
"human-flow",
"collection search link-out only (works in copyright)",
"R2",
"F1.17;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS042",
"Nakkashane",
"Ottoman court design studio",
"institution",
"People",
"F1.10",
"WA-ANA",
"1450",
"1800",
"approx.",
"The court design studio made patterns used by tile, textile and book makers.",
"design;pattern",
"pattern",
"rule and display",
"Ottoman court",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.15",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS043",
"Kitabkhana",
"Royal library-workshop",
"institution",
"People",
"F1.10;F1.12a",
"WA-IRN;AS-CEN",
"1400",
"1700",
"approx.",
"Timurid and Safavid courts ran library-workshops of calligraphers, painters, gilders and binders.",
"calligraphy;book painting;binding",
"manuscript",
"record and writing",
"courts",
"the gilders and binders",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS044",
"Waqf",
"Pious endowment",
"institution",
"People",
"F1.10",
"WA-MES;AF-EGY;WA-ANA;AS-SAS",
"700",
"",
"approx.; living",
"Endowments funded mosques, schools and fountains and paid for craft upkeep.",
"endowment deed",
"building",
"ritual and belief",
"Islamic law",
"",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.17",
"high",
"Existing project node; reconcile ID.",
"canon_makers_institutions.csv"
],
[
"INS045",
"Karimi merchants",
"Karimi",
"institution",
"People",
"F1.10;F1.13",
"AF-EGY;WA-ARB",
"1100",
"1450",
"approx.",
"A group of spice merchants linked Egypt, Yemen and India, moving goods and materials.",
"trade",
"spice",
"exchange and value",
"historians",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.13",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS046",
"New Julfa Armenian merchants",
"Julfa",
"institution",
"People",
"F1.10;F1.13",
"WA-IRN;WA-CAU",
"1605",
"1750",
"approx.",
"Armenians forcibly moved to Isfahan built a trade network in silk and textiles from London to Manila.",
"trade",
"silk",
"exchange and value",
"historians (Sebouh Aslanian)",
"the forced deportation of 1604-05",
"human-flow",
"collection search link-out only (works in copyright)",
"R3",
"F1.13",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR058",
"Al Sadu Weaving Cooperative",
"Sadu House",
"maker-community",
"People",
"F1.10",
"WA-ARB",
"1978",
"",
"Al Sadu Project begun 1978 as a private initiative; Sadu House opened 1980; became the Al Sadu Weaving Cooperative Society, owned by the weavers, in 1991",
"Bedouin women's sadu weaving, used for tents and camel gear, was organised as a cooperative and museum in Kuwait City to keep the skill alive.",
"warp-faced weaving;sheep and camel wool",
"tent divider;cushion",
"shelter",
"founders (a group of Kuwaitis; honorary president Sheikha Altaf Salem Al-Ali Al-Sabah)",
"",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS047",
"Istanbul Archaeology Museums",
"Imperial Museum",
"institution",
"People",
"F1.10",
"WA-ANA",
"1891",
"",
"approx.; building 1891; collection from 1869",
"Osman Hamdi Bey built an Ottoman museum and antiquities law (1884) to keep finds in the empire.",
"collection;antiquities law",
"object",
"rule and display",
"Ottoman state",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR059",
"Byzantine imperial silk workshops",
"Constantinople gynaecea",
"maker-community",
"People",
"F1.11",
"EU-BYZ",
"550",
"1204",
"approx.",
"State workshops in Constantinople made silks whose export was restricted, used as diplomatic gifts across Europe.",
"drawloom silk;purple dye",
"silk textile;vestment",
"rule and display;ritual and belief",
"Byzantine state (Book of the Eparch)",
"the women and enslaved workers in the workshops",
"human-flow",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.13;F1.18",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR060",
"Monastic scriptoria (Latin Europe)",
"Scriptorium",
"maker-community",
"People",
"F1.11",
"EU-WCE;EU-BLC;EU-IBE",
"500",
"1250",
"approx.",
"Monks and nuns copied, decorated and bound books, keeping the tools and recipes of manuscript making.",
"parchment;ink making;illumination;binding",
"manuscript;charter",
"record and writing;ritual and belief",
"religious houses; historians",
"nuns' scriptoria and lay professional scribes",
"sacred",
"British Library digitised manuscripts (public-domain items);Walters Art Museum (CC0);Getty Open Content;Europeana",
"R2",
"F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR061",
"Masons' lodges (Bauhutte)",
"Cathedral building lodges",
"maker-community",
"People",
"F1.11",
"EU-WCE;EU-BLC",
"1200",
"1731",
"approx.; Regensburg ordinances 1459; Strasbourg lodge dissolved in 1731 imperial ban",
"Lodges of masons kept geometric design knowledge, training and marks for building cathedrals.",
"geometric template;ashlar dressing;mason's mark",
"cathedral;tracery;drawing",
"shelter;ritual and belief",
"the lodges' own ordinances",
"labourers and quarry workers outside the lodge",
"none",
"Wikimedia Commons;Europeana",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR062",
"London livery companies",
"City of London guilds",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1150",
"",
"approx.; living as charities",
"Craft guilds (goldsmiths, weavers, stationers) set standards such as the hallmark and controlled apprenticeship in London.",
"hallmarking;apprenticeship;assay",
"silver;book;cloth",
"exchange and value;tools",
"the companies' own charters",
"women, 'foreigners' and non-members barred from trade",
"none",
"Yale Center for British Art (public domain);collection search link-out only (works in copyright)",
"R2",
"F1.17;F1.14",
"high",
"Goldsmiths' Company hallmarking from 1300 statute.",
"canon_makers_institutions.csv"
],
[
"MKR063",
"Florentine craft guilds (Arti)",
"Arte della Lana;Arte di Calimala;Arte della Seta",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1182",
"1770",
"approx.; guilds abolished 1770",
"Guilds of wool, cloth finishing and silk ran Florence's economy and funded buildings and art (Orsanmichele, the Baptistery doors).",
"wool manufacture;dyeing;silk weaving",
"cloth;public sculpture;building",
"exchange and value;rule and display",
"the guilds' statutes",
"the ciompi (wool carders) excluded, who revolted in 1378",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.17;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR064",
"Guild of Saint Luke (Antwerp)",
"Sint-Lucasgilde",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1382",
"1795",
"approx.",
"The guild of painters, sculptors and printers regulated workshops and the art market in Antwerp.",
"guild regulation;open market",
"painting;print",
"exchange and value",
"guild records",
"women and immigrant painters limited by rules",
"none",
"Rijksmuseum (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.21",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR065",
"Murano glassmakers",
"Venetian glass furnaces",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1291",
"",
"approx.; living",
"Venice moved glass furnaces to Murano and kept trade secrets, forbidding glassmakers to leave.",
"glassblowing;cristallo;lattimo",
"goblet;mirror;bead",
"food and storage;exchange and value",
"Venetian state",
"the bead makers (often women) and the trade beads used in Africa",
"living-community",
"Met Open Access (CC0);Rijksmuseum (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR066",
"Nuremberg craft system",
"Nuremberg sworn crafts",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1300",
"1800",
"approx.",
"The city council, not guilds, regulated crafts such as brass casting, scientific instruments and toys that sold across Europe.",
"brass casting;instrument making;woodcut",
"instrument;brass basin;print",
"tools;exchange and value",
"city council; historians",
"the women and journeymen in households",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.17",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS048",
"Venetian Arsenal",
"Arsenale di Venezia",
"institution",
"People",
"F1.11",
"EU-WCE",
"1104",
"1797",
"approx.",
"The state shipyard built galleys in standardised parts on a production line, an early mass-production system.",
"standard components;assembly",
"galley",
"transport;war",
"Venetian state",
"the arsenalotti workers",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR067",
"Plantin Press",
"Officina Plantiniana",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1555",
"1876",
"approx.",
"Christophe Plantin's press in Antwerp printed books in many languages with type and tools that survive in the museum.",
"letterpress;type founding;engraving",
"book;map",
"record and writing",
"the firm; Museum Plantin-Moretus",
"the compositors and pressmen",
"none",
"Rijksmuseum (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR068",
"Gobelins Manufactory",
"Manufacture royale des meubles de la Couronne",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1662",
"",
"approx.; living state manufactory",
"Colbert's royal manufactory made tapestries and furniture to glorify Louis XIV, a state design programme.",
"high-warp tapestry;marquetry",
"tapestry;furniture",
"rule and display",
"French state (Colbert, Le Brun)",
"the Flemish weavers recruited",
"none",
"Paris Musees (CC0);Met Open Access (CC0);Getty Open Content",
"R2",
"F1.17;F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR069",
"Meissen porcelain manufactory",
"Meissen",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1710",
"",
"approx.; living",
"The first European hard-paste porcelain factory copied Asian models and founded European porcelain.",
"hard-paste porcelain;overglaze enamel",
"figure;tableware",
"food and storage;rule and display",
"Saxon court; Bottger and Tschirnhaus",
"the Asian porcelain it copied",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR070",
"Sevres porcelain manufactory",
"Manufacture nationale de Sevres",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1740",
"",
"approx.; Vincennes 1740, Sevres 1756; living",
"The royal porcelain factory made soft-paste and later hard-paste luxury porcelain, and its design studio set French taste.",
"soft-paste porcelain;ground colours;gilding",
"vase;tableware",
"rule and display",
"French crown",
"the painters and gilders",
"none",
"Met Open Access (CC0);Paris Musees (CC0);Getty Open Content",
"R2",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR071",
"Delft potteries",
"Delftware makers",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1600",
"1800",
"approx.; one factory still active",
"Delft potters made tin-glazed earthenware imitating Chinese porcelain when imports fell, a case of substitution by copying.",
"tin glaze;cobalt painting",
"tile;plate;tulip vase",
"food and storage;shelter",
"historians",
"the Chinese export porcelain it copied",
"none",
"Rijksmuseum (CC0);Met Open Access (CC0)",
"R2",
"F1.14",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR072",
"Wedgwood (Etruria works)",
"Josiah Wedgwood and Sons",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1759",
"",
"approx.; Etruria works 1769",
"Wedgwood divided pottery work into specialised tasks and used pattern books and showrooms for the new consumer market.",
"creamware;jasperware;division of labour",
"tableware;vase;medallion",
"food and storage;exchange and value",
"the firm; historians",
"the child and women workers; the anti-slavery medallion's framing of the enslaved",
"human-flow",
"Met Open Access (CC0);Yale Center for British Art (public domain);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R1",
"F1.19;F1.21",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR073",
"Coalbrookdale ironworks",
"Coalbrookdale",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1709",
"",
"approx.",
"Abraham Darby smelted iron with coke, and the works cast the Iron Bridge (1779).",
"coke smelting;iron casting",
"iron bridge;cooking pot",
"tools;shelter",
"historians",
"the miners and ironworkers",
"none",
"Yale Center for British Art (public domain);Wikimedia Commons",
"R2",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR074",
"Cromford Mill",
"Arkwright's mill",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1771",
"",
"approx.",
"Richard Arkwright's water-powered cotton mill set the factory system.",
"water frame;factory",
"cotton yarn",
"clothing and adornment",
"historians",
"children workers; enslaved cotton growers",
"human-flow",
"Yale Center for British Art (public domain);Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR075",
"Lyon silk weavers (canuts)",
"Canuts",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1600",
"1900",
"approx.",
"Lyon silk weavers used drawlooms and, from 1804, the Jacquard loom, and revolted in 1831 and 1834.",
"Jacquard loom;silk",
"silk",
"clothing and adornment",
"historians",
"the weavers' poverty",
"none",
"Met Open Access (CC0);Paris Musees (CC0)",
"R2",
"F1.19;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS049",
"Accademia delle Arti del Disegno",
"Florence Academy of Design",
"institution",
"People",
"F1.11",
"EU-WCE",
"1563",
"",
"approx.",
"Vasari's academy separated artists from guild craftsmen, a founding step in the art/craft divide.",
"drawing (disegno);lectures",
"drawing",
"care and access",
"Giorgio Vasari; Cosimo I de' Medici",
"the craftsmen left in the guilds",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.3;F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS050",
"Ecole des Beaux-Arts",
"Beaux-Arts de Paris",
"institution",
"People",
"F1.11;F1.13",
"EU-WCE",
"1817",
"",
"approx.; roots in the 1648 Academie",
"The school's atelier and competition system (Prix de Rome) trained architects from the Americas to Asia.",
"atelier teaching;competition",
"drawing;building design",
"care and access",
"French state",
"women (admitted 1897)",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS051",
"British Museum",
"BM",
"institution",
"People",
"F1.11",
"EU-BLC",
"1753",
"",
"approx.",
"A 'universal museum' whose collection grew with empire; it organised world history by its own classifications.",
"collecting;classification;display",
"object",
"rule and display",
"Act of Parliament",
"source communities requesting return (Benin, Parthenon, others)",
"conflict-looting",
"collection search link-out only (works in copyright)",
"R2",
"F1.3;F1.24",
"high",
"Collection images are CC BY-NC-SA; link out only.",
"canon_makers_institutions.csv"
],
[
"INS052",
"South Kensington Museum",
"Victoria and Albert Museum",
"institution",
"People",
"F1.11",
"EU-BLC",
"1852",
"",
"approx.; renamed V&A 1899",
"Set up after the Great Exhibition to train designers and educate taste with examples of 'good' and 'false' design.",
"collecting;casts;electrotype copies",
"object;cast;copy",
"rule and display;care and access",
"Henry Cole and the Department of Practical Art",
"the Indian and other makers of collected objects",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.15;F1.19;F1.24",
"high",
"V&A images are not open-licensed; link out.",
"canon_makers_institutions.csv"
],
[
"INS053",
"Pitt Rivers Museum",
"Pitt Rivers",
"institution",
"People",
"F1.11",
"EU-BLC",
"1884",
"",
"approx.",
"Its typological display arranged objects by type to argue for evolution, a way of ranking makers.",
"typological display",
"object",
"rule and display",
"Augustus Pitt Rivers",
"source communities; ancestral remains now withdrawn",
"conflict-looting;ancestral",
"collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS054",
"Musee d'Ethnographie du Trocadero",
"Trocadero",
"institution",
"People",
"F1.11",
"EU-WCE",
"1878",
"1937",
"approx.",
"The Paris ethnographic museum, founded after the 1878 fair, was where Picasso and others saw African objects.",
"collecting;display",
"object",
"rule and display",
"French state",
"the colonised makers",
"conflict-looting",
"collection search link-out only (works in copyright)",
"R3",
"F1.2;F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR076",
"Morris and Co.",
"Morris, Marshall, Faulkner and Co.",
"maker-community",
"People",
"F1.11",
"EU-BLC",
"1861",
"1940",
"approx.",
"The firm made stained glass, wallpaper, textiles and furniture, with women doing much of the embroidery and weaving.",
"woodblock printing;natural dyeing;tapestry;stained glass",
"wallpaper;textile;chair",
"shelter",
"the firm; William Morris",
"May Morris and women embroiderers",
"none",
"Met Open Access (CC0);Yale Center for British Art (public domain);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.18;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS055",
"Arts and Crafts Exhibition Society",
"ACES",
"institution",
"People",
"F1.11",
"EU-BLC",
"1887",
"",
"approx.",
"Its exhibitions named the movement and credited individual makers, not only firms.",
"exhibition",
"craft",
"rule and display",
"Walter Crane and founders",
"",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR077",
"Wiener Werkstatte",
"Vienna Workshops",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1903",
"1932",
"approx.",
"A cooperative of craftspeople produced metal, furniture, fashion and textiles; many designers were women.",
"metalwork;textile printing;bookbinding",
"tea service;textile;fashion",
"food and storage;clothing and adornment",
"Josef Hoffmann, Koloman Moser, Fritz Waerndorfer",
"the women designers, called 'Wiener Weiberkunst' by critics",
"none",
"MAK Vienna Sammlung Online (open-licence items; check);Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.18;F1.26",
"high",
"Kept here, not as movement.",
"canon_makers_institutions.csv"
],
[
"MKR078",
"Darmstadt Artists' Colony",
"Mathildenhohe",
"maker-community",
"People",
"F1.11",
"EU-WCE",
"1899",
"1914",
"approx.",
"The Grand Duke of Hesse built houses and studios for designers who made total artworks.",
"architecture;furniture",
"house;furniture",
"shelter",
"Grand Duke Ernst Ludwig",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR079",
"Abramtsevo artists' colony",
"Abramtsevo",
"maker-community",
"People",
"F1.11",
"EU-EER",
"1870",
"1900",
"approx.",
"Savva and Elizaveta Mamontov's estate workshops revived Russian majolica and woodcarving, a model for later craft colonies.",
"majolica;woodcarving",
"tile;furniture",
"shelter",
"Savva and Elizaveta Mamontov",
"the peasant carvers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"INS056",
"Royal College of Art",
"Government School of Design",
"institution",
"People",
"F1.11",
"EU-BLC",
"1837",
"",
"approx.; RCA from 1896",
"Britain's state design school was set up to improve industrial design against French competition.",
"design training",
"design",
"care and access",
"British government",
"the industrial workers it meant to supply",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.19;F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS057",
"Bauhaus",
"Staatliches Bauhaus",
"institution",
"People",
"F1.11;F1.13",
"EU-WCE",
"1919",
"1933",
"approx.; Weimar, Dessau, Berlin",
"The school joined craft workshops and art under one programme, with a preliminary course (Vorkurs) that spread worldwide through emigres.",
"workshop teaching;preliminary course;weaving;metal",
"lamp;chair;textile;typeface",
"shelter;care and access",
"Walter Gropius and masters",
"women channelled into the weaving workshop (Anni Albers, Gunta Stolzl); the craft masters (Werkmeister)",
"none",
"Cooper Hewitt Open Access (CC0 metadata; images where PD);collection search link-out only (works in copyright);Wikimedia Commons",
"R1",
"F1.18;F1.20;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS058",
"Vkhutemas",
"Higher Art and Technical Studios",
"institution",
"People",
"F1.11",
"EU-EER",
"1920",
"1930",
"approx.",
"The Moscow state school taught a shared basic course and trained designers for industry, parallel to the Bauhaus.",
"basic course;textile;metalwork;woodwork",
"textile;furniture;poster",
"care and access",
"Soviet state; teachers (Rodchenko, Popova, Ladovsky)",
"the students' later repression under Stalin",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS059",
"Black Mountain College",
"BMC",
"institution",
"People",
"F1.7",
"AM-EWD",
"1933",
"1957",
"approx.",
"An experimental college in North Carolina where Josef and Anni Albers taught weaving and design by experiment.",
"weaving;design;performance",
"textile;building",
"care and access",
"founders",
"Black students admitted only from 1944 under segregation",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS060",
"Ulm School of Design",
"Hochschule fur Gestaltung Ulm",
"institution",
"People",
"F1.11",
"EU-WCE",
"1953",
"1968",
"approx.",
"Ulm taught systematic, scientific design and worked with Braun and Lufthansa on product and identity systems.",
"systems design;semiotics;modular design",
"radio;corporate identity",
"tools;care and access",
"Inge Aicher-Scholl, Otl Aicher, Max Bill",
"the anti-Nazi Scholl family memory behind it",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS061",
"Council of Industrial Design",
"Design Council",
"institution",
"People",
"F1.11",
"EU-BLC",
"1944",
"",
"approx.",
"A UK state body promoted good design through exhibitions (Britain Can Make It, 1946) and a 'Design Index'.",
"selection;exhibition",
"product",
"care and access",
"British government",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS062",
"Gebruder Thonet",
"Thonet",
"institution",
"People",
"F1.11",
"EU-WCE",
"1849",
"",
"approx.; chair no.14, 1859",
"Thonet's bentwood chair no.14 was shipped flat in parts and made in millions.",
"steam-bent beech;flat-pack",
"chair",
"shelter",
"the firm",
"the factory workers in Moravia",
"none",
"Met Open Access (CC0);MAK Vienna Sammlung Online (open-licence items; check);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS063",
"Singer Manufacturing Company",
"Singer",
"institution",
"People",
"F1.7;F1.13",
"AM-EWD;GL",
"1851",
"",
"approx.",
"Singer mass-produced sewing machines and sold them on instalments, changing home and garment work worldwide.",
"interchangeable parts;hire purchase",
"sewing machine",
"clothing and adornment;tools",
"the company",
"home sewers and garment workers",
"none",
"Smithsonian Open Access (CC0);Library of Congress (public-domain items)",
"R2",
"F1.18;F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS064",
"AEG",
"Allgemeine Elektricitats-Gesellschaft",
"institution",
"People",
"F1.11",
"EU-WCE",
"1883",
"",
"approx.; Behrens from 1907",
"Peter Behrens designed AEG's products, factory and graphics, an early corporate identity.",
"industrial design;corporate identity",
"kettle;fan;factory",
"food and storage;tools",
"the company; Peter Behrens",
"",
"none",
"MAK Vienna Sammlung Online (open-licence items; check);collection search link-out only (works in copyright)",
"R3",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS065",
"Ford Motor Company",
"Ford;Fordism",
"institution",
"People",
"F1.7",
"AM-EWD",
"1903",
"",
"approx.; moving assembly line 1913",
"The moving assembly line at Highland Park set the production regime called Fordism.",
"moving assembly line;standardised parts",
"Model T",
"transport",
"the company",
"the de-skilled and immigrant workers; rubber workers at Fordlandia",
"none",
"Library of Congress (public-domain items);Smithsonian Open Access (CC0)",
"R1",
"F1.19;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS066",
"Olivetti",
"Olivetti",
"institution",
"People",
"F1.11",
"EU-WCE",
"1908",
"",
"approx.",
"Olivetti linked design, architecture and social welfare, working with designers such as Sottsass and Bellini.",
"industrial design;corporate identity",
"typewriter;computer",
"record and writing",
"the company; Adriano Olivetti",
"",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS067",
"Braun (design department)",
"Braun",
"institution",
"People",
"F1.11",
"EU-WCE",
"1955",
"",
"approx.",
"Dieter Rams and Ulm teachers gave Braun products a consistent design language.",
"injection moulding",
"radio;shaver",
"tools;play and music",
"the company; Dieter Rams",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS068",
"IKEA",
"IKEA",
"institution",
"People",
"F1.11;F1.13",
"EU-SCA;GL",
"1943",
"",
"approx.",
"Flat-pack, self-assembled furniture made modern design cheap and global.",
"flat-pack;self-assembly",
"furniture",
"shelter",
"the company",
"forestry impacts; supplier workers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.22",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS069",
"Foxconn",
"Hon Hai Precision Industry",
"institution",
"People",
"F1.8;F1.13",
"AS-CHN;GL",
"1974",
"",
"approx.",
"Contract manufacturing assembles most of the world's electronics for other brands.",
"contract manufacturing",
"smartphone",
"tools",
"the company",
"the workers and the 2010 suicides",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.23;F1.21",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS070",
"Metre Convention (BIPM)",
"International Bureau of Weights and Measures",
"institution",
"People",
"F1.13",
"GL",
"1875",
"",
"approx.",
"An international treaty set common units that makers and manufacturers use.",
"standardisation",
"metre bar;kilogram",
"exchange and value;tools",
"signatory states",
"local measures replaced",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.19;F1.30",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS071",
"DIN",
"Deutsches Institut fur Normung",
"institution",
"People",
"F1.11",
"EU-WCE",
"1917",
"",
"approx.",
"The German standards body's DIN 476 (1922) set the A-series paper sizes later adopted worldwide as ISO 216.",
"standardisation",
"paper size;screw thread",
"record and writing;tools",
"German industry",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.19",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS072",
"ISO",
"International Organization for Standardization",
"institution",
"People",
"F1.13",
"GL",
"1947",
"",
"approx.",
"International standards (e.g. ISO 668 shipping containers, ISO 216 paper) fix the dimensions of made things.",
"standardisation",
"container;paper",
"tools;transport",
"national standards bodies",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.19;F1.13",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS073",
"Unicode Consortium",
"Unicode",
"institution",
"People",
"F1.13",
"GL",
"1991",
"",
"approx.",
"Encodes the world's scripts, deciding which writing systems work on digital devices.",
"character encoding",
"typeface;script",
"record and writing",
"member companies",
"scripts not yet encoded",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.28",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS074",
"World Crafts Council",
"WCC",
"institution",
"People",
"F1.13",
"GL",
"1964",
"",
"approx.",
"An international body linking craft councils, co-founded with Kamaladevi Chattopadhyay, that set craft on the development agenda.",
"network;conference",
"craft",
"exchange and value;care and access",
"founders (Aileen Osborn Webb, Kamaladevi Chattopadhyay)",
"craftspeople without national councils",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS075",
"UNESCO intangible heritage lists",
"Convention for the Safeguarding of the Intangible Cultural Heritage",
"institution",
"People",
"F1.13",
"GL",
"2003",
"",
"approx.",
"Lists of living practices, including many crafts, shape which traditions are recognised, funded and marketed.",
"listing;safeguarding plans",
"craft;practice",
"care and access",
"UNESCO member states",
"practices states do not nominate; minority groups within states",
"living-community",
"collection search link-out only (works in copyright)",
"R2",
"F1.29;F1.3",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS076",
"World Fair Trade Organization",
"WFTO;formerly IFAT",
"institution",
"People",
"F1.13",
"GL",
"1989",
"",
"approx.",
"A federation of fair trade organisations, many selling craft, sets standards for producer pay and conditions.",
"certification;cooperative marketing",
"craft;textile",
"exchange and value",
"member organisations",
"producers outside the certified network",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.23",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS077",
"Etsy",
"Etsy",
"institution",
"People",
"F1.13",
"GL",
"2005",
"",
"approx.",
"A platform for handmade and vintage goods that turned craft into small online businesses, then admitted outsourced production.",
"online marketplace;search ranking",
"craft;print-on-demand goods",
"exchange and value",
"the company",
"sellers' dependence on platform rules",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.17",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS078",
"Fab Lab network",
"Fab Foundation",
"institution",
"People",
"F1.13",
"GL",
"2001",
"",
"approx.; first Fab Lab at MIT Center for Bits and Atoms",
"A worldwide network of digital fabrication labs shares tools, training and open designs.",
"laser cutting;3D printing;CNC milling",
"prototype;tool",
"tools",
"MIT; Neil Gershenfeld",
"unequal access in lower-income regions",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS079",
"CIAM",
"International Congresses of Modern Architecture",
"institution",
"People",
"F1.11;F1.13",
"EU-WCE;GL",
"1928",
"1959",
"approx.",
"The congresses set modernist planning doctrine (the Athens Charter) applied to post-war and colonial cities.",
"planning doctrine",
"city plan;housing",
"shelter",
"the members (Le Corbusier, Giedion)",
"colonial planning in Africa and Asia; residents",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS080",
"Smithsonian Institution",
"Smithsonian",
"institution",
"People",
"F1.7",
"AM-EWD",
"1846",
"",
"approx.",
"The US national museum and research complex built collections of Native American, African and design objects and now releases images CC0.",
"collecting;classification;open access",
"object",
"rule and display",
"US Congress",
"Native nations whose objects and remains were taken (repatriation under NAGPRA)",
"conflict-looting;ancestral",
"Smithsonian Open Access (CC0)",
"R2",
"F1.24;F1.3",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS081",
"Museum of Modern Art",
"MoMA",
"institution",
"People",
"F1.7",
"AM-EWD",
"1929",
"",
"approx.",
"MoMA's exhibitions and design collection defined what counted as 'modern design' worldwide.",
"curating;design collection",
"chair;poster;product",
"rule and display",
"founders; Alfred Barr; Philip Johnson",
"design outside Europe and North America",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.3;F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS082",
"Benin Dialogue Group",
"Benin Dialogue Group",
"institution",
"People",
"F1.6;F1.11",
"AF-GUI;EU-WCE",
"2010",
"",
"approx.",
"European museums, Nigeria and the Benin court negotiate the return and display of Benin objects.",
"negotiation",
"commemorative head;plaque",
"rule and display",
"members",
"disagreements over who should receive returned objects",
"conflict-looting",
"collection search link-out only (works in copyright)",
"R3",
"F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS083",
"Musee des Civilisations noires",
"MCN",
"institution",
"People",
"F1.6",
"AF-SAH",
"2018",
"",
"approx.",
"A Dakar museum, first proposed by Senghor in 1966, built to show Black civilisations worldwide and to receive restitutions.",
"collecting;display",
"object",
"rule and display",
"Senegalese state",
"",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.24",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS084",
"WPA Federal Art Project",
"Index of American Design",
"institution",
"People",
"F1.7",
"AM-EWD",
"1935",
"1943",
"approx.",
"The New Deal programme employed artists, including over 18,000 watercolour records of American craft objects in the Index of American Design.",
"documentation;watercolour",
"watercolour record;poster",
"record and writing",
"US government",
"Native and Black craft excluded from the Index's scope",
"none",
"National Gallery of Art Washington Open Access (CC0);Library of Congress (public-domain items)",
"R2",
"F1.28;F1.29",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR080",
"Papunya Tula Artists",
"Papunya Tula",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1972",
"",
"approx.",
"An Aboriginal-owned company formed by Western Desert painters to market their work and manage cultural rules on what can be shown.",
"acrylic painting;dotting",
"painting",
"ritual and belief;exchange and value",
"the artists (company founded 1972)",
"the sacred content controlled by senior men and women",
"sacred;Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R2",
"F1.16;F1.17;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR081",
"Ernabella Arts",
"Ernabella",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1948",
"",
"approx.; one of the oldest Aboriginal art centres",
"Anangu women at a Presbyterian mission began with craft (walka designs, rugs), later batik and ceramics.",
"batik;ceramics;weaving",
"rug;batik;pot",
"clothing and adornment;exchange and value",
"the artists; mission founders",
"the mission context",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR082",
"Hermannsburg Potters",
"Hermannsburg Potters",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1990",
"",
"approx.",
"Western Arrernte women make hand-built terracotta pots with modelled lids showing Country and stories.",
"hand-built terracotta;underglaze painting",
"pot",
"food and storage;record and writing",
"the potters",
"",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR083",
"Tiwi Design",
"Tiwi Design",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1969",
"",
"approx.",
"Tiwi artists on Bathurst Island make screen-printed textiles, carvings and paintings drawing on pukumani designs.",
"screen printing;carving",
"textile;carved pole",
"clothing and adornment;ritual and belief",
"the artists",
"",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR084",
"Buku-Larrnggay Mulka Centre",
"Yirrkala art centre",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1976",
"",
"approx.",
"The Yolngu art centre at Yirrkala runs bark painting, larrakitj and printmaking, and a media archive.",
"bark painting;printmaking;hollow log",
"bark painting;larrakitj;print",
"ritual and belief;record and writing",
"the Yolngu community",
"",
"sacred;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.16;F1.26",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR085",
"Utopia batik and painting",
"Utopia Women's Batik Group",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1977",
"",
"approx.",
"Anmatyerre and Alyawarr women at Utopia made batik, then painting (Emily Kame Kngwarreye).",
"batik;acrylic painting",
"silk batik;painting",
"clothing and adornment;ritual and belief",
"the artists; CAAMA",
"the women's authorship under market pressure",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR086",
"Warmun Art Centre",
"Warmun",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1998",
"",
"approx.",
"The Gija art centre supports ochre painting in the tradition of Rover Thomas and Queenie McKenzie.",
"natural ochre painting",
"painting",
"ritual and belief",
"the Gija community",
"",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"",
"medium",
"",
"canon_makers_institutions.csv"
],
[
"MKR087",
"Tjanpi Desert Weavers",
"Tjanpi",
"maker-community",
"People",
"F1.12",
"OC-AUS",
"1995",
"",
"approx.",
"Women from Central and Western Desert communities weave fibre sculpture and baskets from grass.",
"coiled fibre;grass weaving",
"basket;fibre sculpture",
"food and storage;ritual and belief",
"NPY Women's Council and the weavers",
"",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.18",
"high",
"",
"canon_makers_institutions.csv"
],
[
"INS085",
"Maori Arts and Crafts Institute",
"Te Puia;Rotorua School of Maori Arts",
"institution",
"People",
"F1.12",
"OC-POL",
"1963",
"",
"approx.; predecessor school 1926 under Apirana Ngata",
"A Rotorua school trains carvers and weavers under customary masters, continuing a 1926 revival school.",
"whakairo carving;raranga weaving",
"carving;meeting house panel",
"ritual and belief;shelter",
"New Zealand government; Ngata",
"the tourism context",
"ancestral;Indigenous-community",
"Te Papa Collections Online (CC BY items);community-published site (link-out)",
"R2",
"F1.29",
"high",
"",
"canon_makers_institutions.csv"
],
[
"MKR088",
"Tongan kautaha",
"Women's tapa groups",
"maker-community",
"People",
"F1.12",
"OC-POL",
"1800",
"",
"approx.; living",
"Groups of women make ngatu (tapa) together, beating and pasting mulberry bark cloth and rubbing designs from kupesi boards.",
"bark cloth beating;pasting;stencilling",
"ngatu",
"clothing and adornment;exchange and value",
"the women's groups",
"",
"living-community",
"Te Papa Collections Online (CC BY items);Auckland Museum Collections Online (CC BY items);community-published site (link-out)",
"R3",
"F1.18",
"medium",
"",
"canon_makers_institutions.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
