insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"STY038",
"Glasgow Style",
"Glasgow School (design)",
"style",
"Ideas",
"F1.11",
"EU-BLC",
"1890",
"1920",
"approx.",
"Mackintosh, Margaret and Frances Macdonald and Herbert MacNair made a linear style across furniture, metal and textile.",
"stencilling;beaten metal;gesso",
"chair;tea room interior;poster",
"shelter;rule and display",
"historians",
"Margaret Macdonald's share of joint work; the Glasgow Girls",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY039",
"Nieuwe Kunst",
"Dutch Art Nouveau",
"style",
"Ideas",
"F1.11;F1.9;F1.13",
"EU-BLC;AS-ISE",
"1892",
"1904",
"approx.",
"Dutch designers adopted Javanese batik techniques and motifs brought through colonial rule.",
"batik;book design;ceramics",
"book cover;textile;ceramic",
"record and writing;clothing and adornment",
"historians",
"Javanese batik makers whose technique was taken up",
"none",
"Rijksmuseum (CC0);Tropenmuseum/Wereldmuseum photos on Wikimedia Commons (CC BY-SA);Wikimedia Commons",
"R3",
"F1.2;F1.14;F1.18",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV010",
"Ecole de Nancy",
"Alliance provinciale des industries d'art",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1901",
"1914",
"approx.",
"Galle, Daum and Majorelle organised glass, furniture and craft firms around a shared naturalist programme.",
"cameo glass;marquetry;pate de verre",
"vase;cabinet;lamp",
"shelter;rule and display",
"the members (founded 1901)",
"factory glassworkers behind signed pieces",
"none",
"Met Open Access (CC0);Paris Musees (CC0);Wikimedia Commons",
"R3",
"F1.17",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY040",
"National Romanticism (Nordic)",
"Nationalromantik",
"style",
"Ideas",
"F1.11",
"EU-SCA",
"1880",
"1915",
"approx.",
"Architects and craft societies used folk building and textile traditions to express national identity.",
"timber;granite;folk weaving",
"house;museum;tapestry",
"shelter;rule and display",
"historians",
"Sami makers used as symbols but excluded",
"none",
"Finna.fi (CC BY items);DigitaltMuseum Norway/Sweden (CC BY items);Nationalmuseum Sweden (public domain via Wikimedia Commons);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY041",
"Zakopane style",
"Styl zakopianski",
"style",
"Ideas",
"F1.11",
"EU-EER",
"1890",
"1914",
"approx.",
"Stanislaw Witkiewicz turned Goral highland carpentry into a national architectural style.",
"log construction;carving",
"villa;chapel;furniture",
"shelter",
"Stanislaw Witkiewicz and followers",
"Goral carpenters who built it",
"none",
"Wikimedia Commons;Europeana",
"R3",
"F1.29",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV011",
"Deutscher Werkbund",
"German Werkbund",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1907",
"1934",
"approx.; refounded 1950",
"Designers, industrialists and craftspeople organised to raise the quality of German industrial goods, and argued openly over standardisation (Typisierung) versus individual artistry.",
"industrial design;standardisation;exhibition",
"appliance;furniture;housing estate;poster",
"shelter;tools",
"the members (Muthesius, Behrens, Naumann)",
"workers in the factories; the export and colonial ambitions behind it",
"none",
"MAK Vienna Sammlung Online (open-licence items; check);Wikimedia Commons;Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R1",
"F1.19;F1.20",
"high",
"Institution-like; kept here as movement. Weissenhof 1927 in makers file as event.",
"canon_movements_styles_schools.csv"
],
[
"MOV012",
"Cubism",
"Cubisme",
"movement",
"Ideas",
"F1.11",
"EU-WCE;EU-IBE",
"1907",
"1925",
"approx.",
"Fragmented, collaged objects changed graphic and product form and brought African and Oceanic sculpture into Western studios.",
"collage;papier colle;oil",
"painting;collage;sculpture",
"rule and display",
"critics (Louis Vauxcelles) and the painters",
"the African and Oceanic makers whose works were studied as 'art negre'",
"none",
"Met Open Access (CC0);National Gallery of Art Washington Open Access (CC0);Wikimedia Commons",
"R3",
"F1.2",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV013",
"Italian Futurism",
"Futurismo",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1909",
"1944",
"approx.",
"Manifestos covered cooking, typography, fashion and architecture, treating speed and machine production as the model for all making.",
"parole in liberta typography;photodynamism;stage design",
"manifesto;poster;building design",
"record and writing;transport",
"F. T. Marinetti and members (1909 manifesto)",
"its links to Fascism; women futurists",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV014",
"Dada",
"Dadaism",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1916",
"1924",
"approx.",
"Dada's readymades and photomontage questioned authorship and the value of hand-making, using mass-produced objects as art.",
"photomontage;readymade;collage",
"magazine;assemblage",
"record and writing",
"the members",
"women Dadaists (Hannah Hoch, Baroness Elsa)",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.14;F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV015",
"Surrealism",
"Surrealisme",
"movement",
"Ideas",
"F1.11;F1.6;F1.7;F1.13",
"EU-WCE;AF-EGY;AM-MES;AM-CAR",
"1924",
"1966",
"approx.; Breton manifesto 1924",
"Surrealists used automatism, found objects and collected Oceanic and Indigenous American objects.",
"automatism;assemblage;photography",
"painting;object;magazine",
"ritual and belief",
"Andre Breton (1924 manifesto) and members",
"collected Indigenous objects and their makers; women surrealists",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.2",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV016",
"New Typography",
"Die neue Typographie",
"movement",
"Ideas",
"F1.11",
"EU-WCE;EU-EER",
"1923",
"1935",
"approx.",
"Asymmetric sans-serif layouts and standard paper sizes (DIN) remade commercial printing.",
"sans-serif type;asymmetric layout;photomontage",
"poster;letterhead;book",
"record and writing",
"Jan Tschichold (1925 special issue; 1928 book) and circle",
"compositors and printers who executed layouts; women designers in the circle",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD);Wikimedia Commons",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV017",
"Suprematism",
"Suprematizm",
"movement",
"Ideas",
"F1.11",
"EU-EER",
"1915",
"1925",
"approx.; launched at 0.10 exhibition 1915",
"Malevich's non-objective forms were applied to porcelain, textiles and architecture models (arkhitektony).",
"geometric abstraction;porcelain painting",
"painting;teapot;architectural model",
"rule and display",
"Kazimir Malevich and followers",
"women in the group (Rozanova, Popova, Ekster)",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV018",
"UNOVIS",
"Champions of the New Art",
"movement",
"Ideas",
"F1.11",
"EU-EER",
"1919",
"1922",
"approx.; Vitebsk",
"A teaching collective in Vitebsk that designed signage, trams and ration cards collectively, signing as a group.",
"lithography;collective authorship",
"poster;book;banner",
"record and writing",
"the members (Malevich, Lissitzky, Chashnik)",
"Jewish Vitebsk craft culture it grew from",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.26",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV019",
"Constructivism",
"Russian Constructivism",
"movement",
"Ideas",
"F1.11",
"EU-EER",
"1921",
"1932",
"approx.",
"Artists recast themselves as constructors of useful things: textiles, workers' clothing, kiosks, posters.",
"photomontage;textile printing;construction",
"poster;textile;workers' club;kiosk",
"clothing and adornment;record and writing;shelter",
"the members (Rodchenko, Stepanova, Popova, Tatlin)",
"textile-factory workers who printed the designs",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R1",
"F1.19;F1.20",
"high",
"Pair with Vkhutemas (makers file).",
"canon_movements_styles_schools.csv"
],
[
"MOV020",
"De Stijl",
"Neo-Plasticism",
"movement",
"Ideas",
"F1.11",
"EU-BLC",
"1917",
"1931",
"approx.",
"Primary colours and orthogonal forms were applied across painting, furniture, typography and houses.",
"primary colour;orthogonal composition",
"chair;house;magazine",
"shelter;record and writing",
"the members (Van Doesburg, Mondrian, Rietveld)",
"the joiners who made Rietveld's furniture",
"none",
"Rijksmuseum (CC0);collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY042",
"Art Deco",
"Style moderne;Art Deco",
"style",
"Ideas",
"F1.11;F1.7;F1.13",
"EU-WCE;AM-EWD;AM-LAT;AF-MAG;AS-SAS;AS-CHN;OC-POL",
"1920",
"1940",
"approx.; named in the 1960s after the 1925 Paris exposition",
"A geometric luxury style ran from ocean liners to cinemas and was adopted by local builders from Mumbai to Shanghai to Napier.",
"lacquer;shagreen;chrome;terrazzo;concrete",
"cinema;liner interior;jewellery;furniture",
"rule and display;shelter;transport",
"historians (Bevis Hillier, 1968)",
"colonial materials and labour (ivory, ebony, Indochinese lacquer workers)",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata; images where PD);Wikimedia Commons",
"R2",
"F1.15;F1.19",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY043",
"Streamline Moderne",
"Streamline design",
"style",
"Ideas",
"F1.7;F1.11",
"AM-EWD;AM-WST",
"1930",
"1945",
"approx.",
"Industrial designers applied aerodynamic forms to static goods to boost Depression-era sales.",
"pressed steel;Bakelite;chrome",
"toaster;train;radio",
"transport;food and storage",
"historians; industrial designers (Loewy, Dreyfuss, Bel Geddes)",
"the workers on the assembly lines; consumers who could not afford the goods",
"none",
"Cooper Hewitt Open Access (CC0 metadata; images where PD);Library of Congress (public-domain items);Wikimedia Commons",
"R2",
"F1.19;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY044",
"International Style (architecture)",
"Modern Movement",
"style",
"Ideas",
"F1.11;F1.7;F1.13",
"GL",
"1920",
"1970",
"approx.",
"Steel, glass and reinforced concrete with free plans were promoted as a universal building method.",
"reinforced concrete;steel frame;curtain wall",
"villa;housing estate;office tower",
"shelter",
"Henry-Russell Hitchcock and Philip Johnson (MoMA 1932)",
"local and vernacular builders; climate difference",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons;Library of Congress (public-domain items)",
"R2",
"F1.3;F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV021",
"Italian Rationalism",
"Razionalismo",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1926",
"1943",
"approx.",
"Gruppo 7 applied modern construction to Italian building, entangled with Fascist state patronage.",
"reinforced concrete;glass block",
"party house;school",
"shelter;rule and display",
"the members (Gruppo 7)",
"its role in Fascist and colonial building (Libya, Eritrea)",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY045",
"Socialist Realism",
"Sotsrealizm",
"style",
"Ideas",
"F1.11;F1.8;F1.12a",
"EU-EER;AS-CHN;AS-KOR;AS-CEN",
"1932",
"1991",
"approx.; official from 1934",
"A state doctrine governed painting, sculpture, posters and ceramics across the Soviet sphere and China.",
"oil;propaganda poster;monumental sculpture",
"poster;statue;porcelain",
"rule and display",
"Soviet state and Union of Artists (1932-34)",
"suppressed artists; national craft traditions reframed",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20;F1.19a",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY046",
"Stalinist architecture",
"Stalinist Empire style",
"style",
"Ideas",
"F1.11;F1.12a",
"EU-EER;AS-CEN;WA-CAU",
"1933",
"1955",
"approx.",
"Monumental classical buildings used craft ornament and prison labour on major projects.",
"steel frame with stone cladding;ornamental plaster",
"tower;metro station;palace of culture",
"shelter;rule and display",
"historians",
"Gulag labour on some works",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV022",
"Isotype",
"International System of Typographic Picture Education",
"movement",
"Ideas",
"F1.11",
"EU-WCE;EU-BLC",
"1925",
"1971",
"approx.; Vienna method from 1925, Isotype name 1935",
"Otto Neurath, Marie Neurath and Gerd Arntz built a standard pictogram system, a team method of turning data into images.",
"pictogram;linocut;statistical chart",
"chart;book;pictogram",
"record and writing;care and access",
"the members",
"Marie Neurath's role as 'transformer', long overlooked",
"none",
"Internet Archive (public-domain scans);collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH003",
"Polish School of Posters",
"Polska Szkola Plakatu",
"school",
"Ideas",
"F1.11",
"EU-EER",
"1950",
"1980",
"approx.",
"State film and theatre posters became an arena for painterly, personal graphic design.",
"lithography;screen printing;hand lettering",
"film poster;theatre poster",
"rule and display;play and music",
"critics and historians",
"the state censorship that framed it; printers",
"none",
"Library of Congress (public-domain items);collection search link-out only (works in copyright)",
"R3",
"F1.4",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY047",
"Swiss Style",
"International Typographic Style",
"style",
"Ideas",
"F1.11;F1.13",
"EU-WCE;GL",
"1950",
"1980",
"approx.",
"Grid systems, sans-serif type and objective photography became the default of corporate and public-sector design.",
"grid;sans-serif type;photography",
"poster;signage system;corporate identity",
"record and writing;care and access",
"historians; practitioners (Muller-Brockmann, Ruder)",
"local and non-Latin scripts that its grids handled poorly",
"none",
"Cooper Hewitt Open Access (CC0 metadata; images where PD);collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV023",
"Garden City movement",
"Garden city",
"movement",
"Ideas",
"F1.11;F1.13",
"EU-BLC;GL",
"1898",
"1940",
"approx.",
"Ebenezer Howard's plan organised housing, industry and green space as a planned whole.",
"town planning;cottage building",
"garden city;estate",
"shelter",
"Ebenezer Howard (1898) and members",
"colonial garden cities (e.g. in Africa) built on segregation",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY048",
"Scandinavian Modern",
"Scandinavian design",
"style",
"Ideas",
"F1.11;F1.13",
"EU-SCA",
"1930",
"1970",
"approx.; label fixed by US touring exhibition Design in Scandinavia (1954-57)",
"Nordic furniture, glass and textile firms sold humane modern design as a national export brand.",
"bent plywood;teak;glassblowing;printed textile",
"chair;glass;textile",
"shelter;food and storage",
"the 1954-57 touring exhibition and marketers",
"Sami design; the factory workers",
"none",
"Nationalmuseum Sweden (public domain via Wikimedia Commons);DigitaltMuseum Norway/Sweden (CC BY items);Finna.fi (CC BY items);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.20;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY049",
"Mid-century modern",
"Mid-century modern design",
"style",
"Ideas",
"F1.7;F1.11",
"AM-EWD;AM-WST",
"1945",
"1970",
"approx.; term by Cara Greenberg (1984)",
"Moulded plywood, fibreglass and wire furniture reached mass markets after war-time material research.",
"moulded plywood;fibreglass;wire",
"chair;house;appliance",
"shelter",
"Cara Greenberg (1984) and the design market",
"military research that produced the materials; factory workers",
"none",
"Cooper Hewitt Open Access (CC0 metadata; images where PD);Library of Congress (public-domain items);collection search link-out only (works in copyright)",
"R3",
"F1.19a;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV024",
"Good Design",
"Good Design exhibitions",
"movement",
"Ideas",
"F1.7;F1.11",
"AM-EWD",
"1950",
"1955",
"approx.",
"MoMA and the Chicago Merchandise Mart selected everyday products as 'good', making the museum a buyer's guide.",
"curatorial selection",
"appliance;furniture;kitchenware",
"food and storage",
"Edgar Kaufmann Jr. (MoMA)",
"products outside middle-class markets",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.24",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV025",
"Gute Form",
"Good Form",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1949",
"1970",
"approx.",
"Max Bill and the Swiss Werkbund defined honest, durable product form; the ideology shaped Ulm and Braun.",
"product design;standardisation",
"appliance;furniture",
"tools;food and storage",
"Max Bill and Swiss Werkbund",
"critics of consumer taste it dismissed",
"none",
"Cooper Hewitt Open Access (CC0 metadata; images where PD);collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY050",
"Brutalism",
"New Brutalism",
"style",
"Ideas",
"F1.11;F1.13",
"EU-BLC;EU-WCE;EU-EER;AM-LAT;AS-SAS;GL",
"1950",
"1980",
"approx.; term Alison and Peter Smithson (1953), Reyner Banham (1955)",
"Exposed, board-marked concrete showed the traces of how buildings were made.",
"beton brut;board-marked concrete",
"housing estate;university;church",
"shelter",
"the Smithsons and Reyner Banham",
"construction workers; later tenants",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV026",
"Metabolism",
"Metaboreizumu",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"1960",
"1975",
"approx.; manifesto at World Design Conference Tokyo 1960",
"Japanese architects proposed buildings of replaceable capsules and megastructures growing like organisms.",
"prefabrication;capsule;megastructure",
"capsule tower;city plan",
"shelter",
"the members (Kikutake, Kurokawa, Maki, Otaka)",
"the post-war construction labour",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV027",
"Archigram",
"Archigram group",
"movement",
"Ideas",
"F1.11",
"EU-BLC",
"1961",
"1974",
"approx.",
"A London group used comic-strip drawings to propose plug-in, walking and instant cities.",
"collage;drawing",
"magazine;speculative project",
"shelter",
"the members",
"the people who would live in the proposed cities",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV028",
"Italian Radical Design",
"Radical Design;Anti-design",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1966",
"1976",
"approx.",
"Groups such as Archizoom, Superstudio and UFO used objects and speculative projects to critique consumer design.",
"speculative drawing;photocollage;polyurethane",
"lamp;sofa;speculative city",
"shelter",
"Germano Celant (1966 term 'architettura radicale'); the members",
"the artisans and small manufacturers who realised the prototypes",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV029",
"Memphis Group",
"Memphis",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1981",
"1988",
"approx.",
"Ettore Sottsass's group used plastic laminate and bold pattern to reject tasteful modern furniture.",
"plastic laminate;terrazzo pattern",
"bookcase;lamp;ceramics",
"shelter",
"the members",
"the manufacturers and laminate makers",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.20;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY051",
"Postmodernism (architecture and design)",
"Postmodern design",
"style",
"Ideas",
"F1.7;F1.11",
"AM-EWD;EU-WCE;AS-JPN",
"1966",
"1995",
"approx.; Venturi (1966), Jencks (1977)",
"Designers returned ornament, historical quotation and humour to buildings and goods.",
"decorative laminate;applied ornament",
"building;teapot;chair",
"shelter",
"Robert Venturi; Charles Jencks",
"Denise Scott Brown's shared authorship",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R2",
"F1.20;F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY052",
"Deconstructivism",
"Deconstructivist architecture",
"style",
"Ideas",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1988",
"2005",
"approx.",
"Computer-aided fragmented forms were grouped by a museum show rather than by the architects.",
"CAD;steel;titanium cladding",
"museum;concert hall",
"shelter",
"Philip Johnson and Mark Wigley (MoMA 1988)",
"the engineers and fabricators who made the forms buildable",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.15",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY053",
"Critical Regionalism",
"Critical regionalism",
"style",
"Ideas",
"F1.13",
"GL",
"1981",
"",
"approx.",
"A theory that architecture should use local climate, light and craft within modern means.",
"local materials;climate response",
"house;public building",
"shelter",
"Alexander Tzonis and Liane Lefaivre (1981); Kenneth Frampton (1983)",
"vernacular builders cited as sources",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY054",
"Neo-vernacular",
"Neo-vernacular architecture",
"style",
"Ideas",
"F1.6;F1.9;F1.13",
"AF-EGY;AS-SAS;GL",
"1945",
"",
"approx.; Hassan Fathy's New Gourna from 1945",
"Architects such as Hassan Fathy and Laurie Baker revived mud-brick vaults and local building crafts against imported concrete.",
"mud brick;Nubian vault;brick jali",
"village;house;school",
"shelter",
"historians; the architects' own writings",
"the Nubian masons whose method Fathy adopted; residents who rejected New Gourna",
"none",
"Archnet (link-out);collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20;F1.29",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY055",
"Tropical Modernism",
"Tropical Architecture",
"style",
"Ideas",
"F1.6;F1.9;F1.13",
"AF-GUI;AS-SAS;AS-ISE;GL",
"1945",
"1975",
"approx.",
"Modern architecture adapted to heat and rain with brise-soleil and cross-ventilation, taught through colonial schools and later reworked by Geoffrey Bawa and West African architects.",
"brise-soleil;cross-ventilation;local timber",
"university;house;hotel",
"shelter",
"Maxwell Fry and Jane Drew (1956 book); Architectural Association Tropical department",
"the African and Asian architects (e.g. Victor Adegbite, Minnette de Silva) who took it beyond its colonial origins",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY056",
"Chandigarh modernism",
"Chandigarh architecture",
"style",
"Ideas",
"F1.9",
"AS-SAS",
"1951",
"1965",
"approx.",
"Le Corbusier, Pierre Jeanneret, Jane Drew, Maxwell Fry and an Indian team designed a city down to its furniture, made by local joiners.",
"reinforced concrete;teak and cane furniture",
"capitol building;chair;house",
"shelter",
"historians",
"Indian architects (e.g. Aditya Prakash, Eulie Chowdhury) and workers; later furniture looting from the city",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.20;F1.24",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY057",
"Parametricism",
"Parametric design",
"style",
"Ideas",
"F1.13",
"GL",
"2008",
"",
"approx.",
"A computational design approach in which form is generated by scripted parameters.",
"parametric modelling;CNC fabrication",
"building;product",
"shelter",
"Patrik Schumacher (2008)",
"fabrication workers; the programmers of the tools",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV030",
"Droog",
"Droog Design",
"movement",
"Ideas",
"F1.11",
"EU-BLC",
"1993",
"",
"approx.",
"A Dutch collective showed re-used and conceptual objects, making the idea behind making the product.",
"reuse;found objects",
"lamp;chair",
"shelter",
"the founders (Renny Ramakers, Gijs Bakker)",
"the craftspeople and small producers who made the pieces",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV031",
"Critical design",
"Critical design",
"movement",
"Ideas",
"F1.11",
"EU-BLC",
"1999",
"",
"approx.",
"Anthony Dunne and Fiona Raby used prototypes to question technology's social effects.",
"prototype;scenario",
"object;film",
"rule and display",
"Anthony Dunne (Hertzian Tales, 1999) and Fiona Raby",
"those without access to the gallery setting",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV032",
"Speculative design",
"Speculative and critical design",
"movement",
"Ideas",
"F1.11;F1.13",
"EU-BLC;GL",
"2013",
"",
"approx.",
"Designers make props and scenarios from possible futures so that people can debate technology before it arrives.",
"prototype;scenario;film",
"object;film",
"rule and display",
"Dunne and Raby (Speculative Everything, 2013)",
"critics note its northern, middle-class viewpoint",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV033",
"New Wave typography",
"Swiss Punk;New Wave graphic design",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-WCE;AM-WST;AM-EWD",
"1970",
"1990",
"approx.",
"Wolfgang Weingart, April Greiman and Cranbrook students broke the Swiss grid, some by early Macintosh.",
"layered type;photocopy;early digital layout",
"poster;magazine",
"record and writing",
"historians; the practitioners",
"the typesetters and printers displaced by desktop tools",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV034",
"Punk DIY graphics",
"Punk design",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-BLC;AM-EWD",
"1976",
"1985",
"approx.",
"Fanzines, sleeves and flyers were made by photocopier and cut-up, an anti-professional mode of making.",
"photocopy;collage;cut-up lettering",
"fanzine;record sleeve;flyer",
"play and music;record and writing",
"the participants; later historians",
"women and queer makers central to zine culture",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV035",
"Net art",
"net.art",
"movement",
"Ideas",
"F1.11;F1.13",
"EU-EER;EU-WCE;GL",
"1994",
"2000",
"approx.",
"Artists used the web browser, HTML and email as their material, making work that existed only on the network.",
"HTML;browser;email",
"website",
"record and writing",
"the participants (term via Vuk Cosic, 1995)",
"artists outside Europe and North America with less internet access",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY058",
"Web 1.0 vernacular",
"Digital folklore;GeoCities style",
"style",
"Ideas",
"F1.13",
"GL",
"1994",
"2009",
"approx.; GeoCities closed 2009",
"Amateur home pages with animated GIFs and tiled backgrounds were a mass vernacular design practice.",
"HTML;animated GIF;tiled background",
"home page",
"record and writing;play and music",
"Olia Lialina and Dragan Espenschied (Digital Folklore, 2009)",
"the anonymous page makers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY059",
"Flat design",
"Flat UI",
"style",
"Ideas",
"F1.13",
"GL",
"2010",
"",
"approx.; Windows Metro 2010, iOS 7 2013",
"Platform makers removed simulated texture for flat colour and type, standardising app interfaces.",
"vector graphics;type",
"app interface;icon",
"tools",
"designers and platform companies",
"users who relied on visual cues for accessibility",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY060",
"Material Design",
"Material Design",
"style",
"Ideas",
"F1.13",
"GL",
"2014",
"",
"approx.",
"Google's published system set rules for layered cards and motion, a corporate style adopted by many makers.",
"design system;component library",
"app interface",
"tools",
"Google (2014)",
"the many local interface conventions it overrode",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV036",
"Generative and computer art",
"Computer art",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1965",
"",
"approx.; first exhibitions 1965 (Nees, Nake, Noll)",
"Programmers used plotters and code to make images, founding algorithmic making.",
"pen plotter;algorithm",
"plotter drawing;print",
"record and writing",
"the practitioners; 1968 Cybernetic Serendipity exhibition",
"women pioneers (Vera Molnar, Lillian Schwartz)",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV037",
"New Tendencies",
"Nove tendencije",
"movement",
"Ideas",
"F1.11",
"EU-BYZ;EU-WCE",
"1961",
"1973",
"approx.",
"Zagreb exhibitions linked kinetic, op and computer art across Cold War blocs.",
"kinetic object;computer graphics",
"object;print",
"rule and display",
"the organisers (Galerija suvremene umjetnosti, Zagreb)",
"the Yugoslav context of non-alignment that made the exchange possible",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV038",
"Kinetic art",
"Kinetic art",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-WCE;AM-LAT",
"1955",
"1975",
"approx.; Le Mouvement exhibition 1955",
"Artists including many Venezuelans and Argentines (Soto, Cruz-Diez, Le Parc) made motion and perception the medium.",
"motors;optics;perspex",
"sculpture;environment",
"play and music",
"the participants and Galerie Denise Rene",
"Latin American artists often credited to Paris",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV039",
"Pop Art",
"Pop",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-BLC;AM-EWD",
"1955",
"1975",
"approx.; term via Lawrence Alloway",
"Artists adopted commercial printing, packaging and screen printing as art methods.",
"screen printing;collage",
"print;painting",
"exchange and value",
"Independent Group; Lawrence Alloway",
"commercial illustrators and printers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV040",
"Arte Povera",
"Poor art",
"movement",
"Ideas",
"F1.11",
"EU-WCE",
"1967",
"1972",
"approx.",
"Artists used soil, felt, rags and scrap to reject industrial polish, treating humble materials and processes as the work.",
"found materials;organic materials",
"installation",
"rule and display",
"Germano Celant (1967)",
"the southern Italian rural economies it romanticised",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV041",
"Studio pottery",
"Studio ceramics",
"movement",
"Ideas",
"F1.11;F1.8;F1.13",
"EU-BLC;AS-JPN;GL",
"1920",
"",
"approx.; Leach Pottery at St Ives 1920",
"Bernard Leach and Hamada Shoji modelled the potter as designer and maker in one, based on East Asian and English slipware sources.",
"wheel throwing;stoneware;climbing kiln",
"bowl;jar;tea bowl",
"food and storage",
"the members; Bernard Leach's A Potter's Book (1940)",
"the Korean and Japanese potters whose methods it drew on; Leach Pottery employees",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.2;F1.14",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV042",
"Studio craft movement",
"American studio craft",
"movement",
"Ideas",
"F1.7;F1.11",
"AM-EWD;AM-WST;EU-BLC",
"1945",
"",
"approx.",
"Craftspeople trained in universities built careers as individual makers in clay, fibre, wood and metal.",
"wheel throwing;furniture making;weaving;metalsmithing",
"vessel;furniture;jewellery",
"food and storage;shelter;clothing and adornment",
"historians; American Craft Council",
"Black and Indigenous craftspeople outside the university system",
"none",
"Smithsonian Open Access (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.17",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV043",
"Studio glass movement",
"Studio glass",
"movement",
"Ideas",
"F1.7;F1.11",
"AM-EWD;EU-EER",
"1962",
"",
"approx.; Toledo Museum workshops 1962",
"Small furnaces and low-melting glass let individual artists blow glass outside the factory, moving glass from industry into studio craft.",
"small furnace;glassblowing;lampworking",
"vessel;sculpture",
"rule and display",
"Harvey Littleton and Dominick Labino; participants",
"Czech glass artists who developed it in parallel",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata; images where PD)",
"R3",
"",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV044",
"Fiber art",
"New Tapestry;Art fabric",
"movement",
"Ideas",
"F1.11;F1.7",
"EU-WCE;EU-EER;AM-EWD",
"1962",
"1995",
"approx.; Lausanne Tapestry Biennials 1962-1995",
"Weavers (many women, including Magdalena Abakanowicz and Sheila Hicks) made off-loom textile sculpture recognised as art.",
"off-loom weaving;knotting;sisal",
"wall hanging;sculpture",
"rule and display",
"the participants; Lausanne Biennials",
"non-Western textile traditions they drew on",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.18",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV045",
"Craftivism",
"Craftivism",
"movement",
"Ideas",
"F1.11;F1.7;F1.13",
"GL",
"2003",
"",
"approx.; term Betsy Greer (2003)",
"Knitting, stitching and embroidery were used as public protest, making slow handwork into a form of political speech.",
"knitting;cross-stitch;embroidery",
"banner;knitted object",
"rule and display;clothing and adornment",
"Betsy Greer and participants",
"earlier protest textiles (arpilleras, suffrage banners)",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV046",
"Appropriate technology",
"Intermediate technology",
"movement",
"Ideas",
"F1.11;F1.13",
"GL",
"1966",
"",
"approx.; ITDG founded 1966",
"E. F. Schumacher's followers designed small, repairable tools built with local skills.",
"small-scale tools;local manufacture",
"hand pump;stove;tool",
"tools;food and storage",
"E. F. Schumacher (Small is Beautiful, 1973) and ITDG (now Practical Action)",
"the users who adapted designs; critiques of top-down transfer",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22;F1.22a",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV047",
"Universal design",
"Inclusive design;Design for All",
"movement",
"Ideas",
"F1.7;F1.11",
"AM-EWD;EU-BLC",
"1985",
"",
"approx.; term Ronald Mace",
"Disability activists and designers set the goal of goods and buildings usable by everyone.",
"ergonomics;accessibility standards",
"kerb cut;tool handle;building",
"care and access",
"Ronald Mace and the Center for Universal Design",
"disabled activists whose campaigns preceded it",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22a",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV048",
"Participatory design",
"Cooperative design;Scandinavian design tradition (IT)",
"movement",
"Ideas",
"F1.11",
"EU-SCA",
"1970",
"",
"approx.; UTOPIA project 1981-85",
"Trade unions and researchers involved workers in designing their own tools.",
"workshops;prototyping",
"software;workplace tool",
"tools",
"the participants (Norwegian and Swedish projects)",
"workers outside unionised Scandinavian workplaces",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.23",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV049",
"Open-source hardware and maker movement",
"Maker movement",
"movement",
"Ideas",
"F1.13",
"GL",
"2005",
"",
"approx.; Make magazine and RepRap 2005",
"Shared digital files and cheap fabrication tools allowed distributed making.",
"3D printing;microcontroller;laser cutting",
"3D print;electronics kit",
"tools",
"participants; Make magazine",
"the maker traditions it rebranded; unequal access",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV050",
"Sustainable design",
"Eco-design;Ecological design",
"movement",
"Ideas",
"F1.13",
"GL",
"1971",
"",
"approx.; Papanek (Design for the Real World, 1971)",
"Designers took responsibility for materials, energy and waste across a product's life.",
"life-cycle assessment;renewable materials",
"product;building",
"tools;shelter",
"Victor Papanek and later practitioners",
"Indigenous and vernacular sustainable practices",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV051",
"Circular design",
"Circular economy design;Cradle to Cradle",
"movement",
"Ideas",
"F1.13",
"GL",
"2002",
"",
"approx.; McDonough and Braungart (2002); Ellen MacArthur Foundation (2010)",
"Designing for repair, reuse and material recovery treats waste as design failure.",
"design for disassembly;material passport",
"product;packaging",
"tools;food and storage",
"McDonough and Braungart; Ellen MacArthur Foundation",
"informal recyclers and repair economies it builds on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22;F1.22a",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV052",
"Decolonising design",
"Decolonial design",
"movement",
"Ideas",
"F1.13",
"GL",
"2016",
"",
"approx.; Decolonising Design group 2016",
"Designers and scholars challenge the Western canon and assumptions of design practice and teaching.",
"research;pedagogy",
"curriculum;project",
"care and access",
"the Decolonising Design group and others",
"varies by context; it names what others leave out",
"none",
"collection search link-out only (works in copyright);community-published site (link-out)",
"R3",
"F1.3;F1.20",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY061",
"Biodesign",
"Biodesign",
"style",
"Ideas",
"F1.13",
"GL",
"2012",
"",
"approx.",
"Designers grow materials with fungi, bacteria and algae, treating living organisms as collaborators in making.",
"mycelium;bacterial cellulose",
"packaging;textile;brick",
"tools",
"William Myers (2012 book) and practitioners",
"earlier vernacular uses of living materials (e.g. fermentation, living root bridges)",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV053",
"Afrofuturism",
"Afrofuturism",
"movement",
"Ideas",
"F1.13;F1.7;F1.6",
"GL;AM-EWD",
"1993",
"",
"approx.; term Mark Dery (1993); roots in Sun Ra and earlier",
"African diaspora artists and designers imagine Black futures through fashion, graphics and music.",
"costume;graphic design;sound",
"album cover;costume;film",
"clothing and adornment;play and music",
"Mark Dery named it; practitioners define it (Sun Ra, Octavia Butler)",
"African continental futurisms",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV054",
"Indigenous Futurism",
"Indigenous Futurisms",
"movement",
"Ideas",
"F1.13;F1.7;F1.12",
"GL;AM-WST;OC-AUS;OC-POL",
"2012",
"",
"approx.; term Grace Dillon (2012)",
"Indigenous artists use speculative and technological forms to assert continuity and sovereignty.",
"digital media;beadwork;costume",
"artwork;game;film",
"ritual and belief;play and music",
"Grace Dillon (2012) and practitioners",
"the specific nations the umbrella term can flatten",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.20",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV055",
"Gulf Futurism",
"Gulf Futurism",
"movement",
"Ideas",
"F1.10",
"WA-ARB",
"2012",
"",
"approx.",
"Artists describe the hyper-modern cities, malls and consumer landscapes of the Gulf as a subject and aesthetic.",
"video;digital image",
"video;music",
"rule and display",
"Sophia Al-Maria and Fatima Al Qadiri (2012)",
"migrant labour that builds the cities",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22;F1.23",
"medium",
"Term originated as an artists' framing, not a mass movement.",
"canon_movements_styles_schools.csv"
],
[
"STY062",
"Primitivism",
"Modernist primitivism",
"style",
"Ideas",
"F1.11;F1.6;F1.12",
"EU-WCE;AF-CEN;AF-GUI;OC-MEL",
"1900",
"1940",
"approx.; debated at MoMA 1984",
"European modernists took African and Oceanic objects as sources, often without knowing their makers or uses.",
"appropriation;collecting",
"painting;sculpture",
"ritual and belief",
"MoMA (Primitivism in 20th Century Art, 1984) and its critics",
"the named African and Oceanic makers and their communities",
"sacred",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R1",
"F1.2;F1.3;F1.24",
"high",
"Lesson on reference and appropriation.",
"canon_movements_styles_schools.csv"
],
[
"STY063",
"Olmec style",
"Olmec horizon style",
"style",
"Ideas",
"F1.7",
"AM-MES",
"-1200",
"-400",
"approx.",
"Jade, greenstone and basalt carving in a shared style spread across Mesoamerica, raising the question of whether a style equals a people.",
"jade carving;basalt carving;ceramic",
"colossal head;jade celt;figurine",
"ritual and belief;rule and display",
"archaeologists (Olmec named in 1920s-40s from Aztec term)",
"the name is Aztec, not theirs; regional makers elsewhere who shared it",
"sacred;Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.3;F1.16",
"medium",
"Style vs culture debate (mother culture vs sister cultures).",
"canon_movements_styles_schools.csv"
],
[
"STY064",
"Chavin style",
"Early Horizon",
"style",
"Ideas",
"F1.7",
"AM-AND",
"-900",
"-200",
"approx.",
"A shared religious style carried by textiles, gold and ceramics unified Andean imagery across regions.",
"stone relief;goldworking;painted textile",
"stone relief;gold ornament;stirrup-spout vessel",
"ritual and belief",
"Julio C. Tello (1919); John Rowe's horizon scheme",
"local communities that adopted it on their own terms",
"sacred;Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.30",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY065",
"Middle Horizon style (Wari and Tiwanaku)",
"Wari-Tiwanaku",
"style",
"Ideas",
"F1.7",
"AM-AND",
"600",
"1000",
"approx.",
"Tapestry tunics with standardised, compressed designs point to state-run weaving and design rules.",
"tapestry weaving;camelid fibre;cotton",
"tapestry tunic;kero cup",
"clothing and adornment;rule and display",
"Max Uhle; John Rowe (horizon scheme)",
"the weavers themselves",
"Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.18;F1.30",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY066",
"Inca imperial style",
"Late Horizon style;tocapu",
"style",
"Ideas",
"F1.7",
"AM-AND",
"1438",
"1533",
"approx.",
"State workshops standardised cloth (tocapu), stone masonry and ceramic forms across the empire.",
"interlocking tapestry;ashlar masonry;standard aryballos",
"tunic;aryballo;wall",
"clothing and adornment;rule and display",
"John Rowe; archaeologists",
"the conquered peoples whose labour made it (see aqllakuna in makers file)",
"Indigenous-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY067",
"Mixteca-Puebla style",
"Postclassic International Style",
"style",
"Ideas",
"F1.7",
"AM-MES",
"1200",
"1520",
"approx.",
"A shared pictorial code in codices, pottery and turquoise mosaic crossed Mesoamerican polities.",
"painted codex;polychrome ceramic;turquoise mosaic",
"codex;polychrome vessel;mosaic mask",
"record and writing;ritual and belief",
"George Vaillant (1941); later 'International Style' (Robertson)",
"the named Mixtec painters in codices",
"sacred;Indigenous-community",
"Wikimedia Commons;Library of Congress (public-domain items);Met Open Access (CC0)",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY068",
"Puuc style",
"Puuc architecture",
"style",
"Ideas",
"F1.7",
"AM-MES",
"600",
"1000",
"approx.",
"Maya builders used mass-produced veneer stones for mosaic facades, a modular system.",
"veneer masonry;stone mosaic",
"palace;temple facade",
"shelter;rule and display",
"archaeologists (after Puuc hills)",
"the labourers who quarried and cut veneer stones",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY069",
"Southeastern Ceremonial Complex",
"Mississippian Ideological Interaction Sphere",
"style",
"Ideas",
"F1.7",
"AM-EWD",
"1100",
"1450",
"approx.",
"Shared imagery on shell gorgets and copper plates linked Mississippian towns.",
"shell engraving;copper repousse",
"gorget;copper plate",
"ritual and belief",
"Antonio Waring and Preston Holder (1945)",
"descendant nations' own understanding",
"sacred;Indigenous-community",
"Smithsonian Open Access (CC0);community-published site (link-out)",
"R3",
"F1.16",
"medium",
"Restrict display; consult descendant communities.",
"canon_movements_styles_schools.csv"
],
[
"STY070",
"Marajoara style",
"Marajoara ceramics",
"style",
"Ideas",
"F1.7",
"AM-AMZ",
"400",
"1400",
"approx.",
"Mound-building societies of Marajo Island made large painted and incised burial urns.",
"incised and painted ceramic",
"burial urn;tanga",
"ritual and belief",
"archaeologists (Meggers and Evans; Roosevelt)",
"present-day Amazonian peoples",
"funerary;Indigenous-community",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.16",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY071",
"Shipibo-Konibo kene",
"Kene design",
"style",
"Ideas",
"F1.7",
"AM-AMZ",
"1600",
"",
"approx.; living tradition, antiquity unknown",
"Women's geometric designs link textiles, ceramics and body painting and are protected as cultural heritage.",
"embroidery;painting;ceramics",
"textile;vessel",
"clothing and adornment;ritual and belief",
"the Shipibo-Konibo, especially women makers; Peru's heritage declaration (2008)",
"commercial copying",
"Indigenous-community;living-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"medium",
"Dating uncertain; use community sources.",
"canon_movements_styles_schools.csv"
],
[
"STY072",
"Tequitqui",
"Indo-Christian art",
"style",
"Ideas",
"F1.7",
"AM-LAT",
"1530",
"1600",
"approx.",
"Indigenous sculptors in New Spain carved Christian images with Native technique and motifs.",
"stone relief;featherwork",
"atrial cross;portal",
"ritual and belief",
"Jose Moreno Villa (1942)",
"the Nahua carvers and their meaning-making",
"sacred",
"Wikimedia Commons",
"R3",
"F1.2;F1.14",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH004",
"Cuzco School",
"Escuela cuzquena",
"school",
"Ideas",
"F1.7",
"AM-AND;AM-LAT",
"1650",
"1800",
"approx.; Indigenous painters split from the guild in 1688",
"Andean painters mass-produced gold-patterned devotional paintings for export across South America.",
"oil on canvas;brocateado gold",
"devotional painting",
"ritual and belief",
"art historians",
"named Indigenous painters such as Diego Quispe Tito; workshop apprentices",
"sacred",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.17;F1.23",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH005",
"Quito School",
"Escuela quitena",
"school",
"Ideas",
"F1.7",
"AM-AND;AM-LAT",
"1600",
"1800",
"approx.",
"Workshops in Quito exported polychrome sculpture with encarnado finishes across the Spanish empire.",
"polychrome wood;encarnado;estofado",
"devotional sculpture",
"ritual and belief",
"art historians",
"Indigenous and mestizo artisans",
"sacred",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.19",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY073",
"Andean Baroque",
"Arte mestizo;Mestizo Baroque",
"style",
"Ideas",
"F1.7",
"AM-AND",
"1650",
"1780",
"approx.",
"Indigenous stone carvers filled church facades with local flora, fauna and figures.",
"stone carving",
"church facade",
"ritual and belief",
"Angel Guido and later historians",
"the carvers themselves",
"sacred",
"Wikimedia Commons",
"R3",
"F1.2",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY074",
"Earthquake Baroque",
"Philippine Baroque churches",
"style",
"Ideas",
"F1.9",
"AS-ISE",
"1600",
"1800",
"approx.",
"Filipino builders under Spanish friars adapted Baroque churches with heavy buttresses against earthquakes.",
"coral stone;brick;buttress",
"church;bell tower",
"ritual and belief;shelter",
"Alicia Coseteng (1972)",
"forced labour (polo y servicio)",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.22",
"medium",
"Term usually attributed to Alicia Coseteng (Spanish Churches in the Philippines, 1972); Pál Kelemen had used \"earthquake baroque\" for Latin America; forced labour (polo y servicio) flagged as human-flow.",
"canon_movements_styles_schools.csv"
],
[
"SCH006",
"Best Maugard method",
"Metodo Best Maugard",
"school",
"Ideas",
"F1.7",
"AM-LAT",
"1923",
"1930",
"approx.",
"A drawing method built on seven motifs from Mexican Indigenous and folk art was taught in state schools.",
"drawing method;ornament",
"drawing manual",
"care and access",
"Adolfo Best Maugard (1923)",
"the Indigenous makers of the source motifs",
"none",
"Internet Archive (public-domain scans);collection search link-out only (works in copyright)",
"R3",
"F1.15",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV056",
"Mexican Muralism",
"Muralismo mexicano",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1920",
"1970",
"approx.",
"State-funded murals by Rivera, Orozco, Siqueiros and others made public walls a medium of political history, with collective workshops and new paints.",
"fresco;pyroxylin;public mural",
"mural",
"rule and display;record and writing",
"the members and Mexican state (Vasconcelos)",
"women muralists; the plasterers and assistants",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R1",
"F1.17;F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV057",
"Estridentismo",
"Stridentism",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1921",
"1927",
"approx.",
"Mexico's avant-garde linked poetry, woodcut and graphic design with the city and radio.",
"woodcut;magazine design",
"magazine;poster",
"record and writing",
"Manuel Maples Arce and members",
"women associated with the group; Indigenous Mexico outside the city",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV058",
"Indigenismo (Peru)",
"Peruvian Indigenism",
"movement",
"Ideas",
"F1.7",
"AM-AND;AM-LAT",
"1920",
"1950",
"approx.",
"Painters around Jose Sabogal took Andean crafts and people as subjects of national art.",
"oil;woodcut",
"painting;print",
"rule and display",
"the members",
"Quechua and Aymara artists themselves",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.2",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV059",
"Brazilian Modernismo",
"Modernismo brasileiro",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1922",
"1945",
"approx.; launched at Semana de Arte Moderna 1922",
"Brazilian artists and designers set out to build a national modern art from local, Indigenous and Afro-Brazilian sources.",
"painting;design",
"painting;book",
"rule and display",
"the members",
"Indigenous and Afro-Brazilian makers treated as sources",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV060",
"Antropofagia",
"Anthropophagic movement",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1928",
"1930",
"approx.; Oswald de Andrade's manifesto 1928",
"It declared that Brazil should 'devour' foreign culture and transform it, a theory of copying.",
"manifesto;painting",
"painting;manifesto",
"rule and display",
"Oswald de Andrade and Tarsila do Amaral",
"the Tupi peoples whose ritual was used as metaphor",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.2;F1.14",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY075",
"Brazilian modern architecture",
"Escola Carioca",
"style",
"Ideas",
"F1.7",
"AM-LAT",
"1936",
"1965",
"approx.",
"Lucio Costa, Oscar Niemeyer and Roberto Burle Marx joined concrete modernism with azulejo tile and tropical planting.",
"reinforced concrete;azulejo;brise-soleil",
"ministry;house;capital city",
"shelter",
"historians",
"construction workers (candangos) who built Brasilia",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV061",
"Arte Concreto-Invencion",
"Asociacion Arte Concreto-Invencion",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1945",
"1955",
"approx.",
"Buenos Aires artists made shaped canvases and objects that rejected illusion, linking art to design and industry.",
"shaped canvas;geometric abstraction",
"painting;object",
"rule and display",
"the members (Tomas Maldonado and others)",
"women members such as Lidy Prati",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV062",
"Madi",
"Movimiento Madi",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1946",
"1955",
"approx.",
"Buenos Aires artists made irregular, articulated and movable objects, treating the frame and the object itself as open to change.",
"shaped frame;articulated object",
"object;painting",
"play and music",
"the members (Gyula Kosice, Carmelo Arden Quin)",
"women members such as Diyi Laan",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH007",
"Taller Torres-Garcia",
"Universalismo Constructivo",
"school",
"Ideas",
"F1.7",
"AM-LAT",
"1934",
"1962",
"approx.",
"Joaquin Torres-Garcia's workshop in Montevideo trained artists and artisans in a grid-based symbolic art with Andean references.",
"constructive grid;wood carving;mural",
"painting;toy;mural",
"rule and display",
"Joaquin Torres-Garcia (Universalismo Constructivo, 1944)",
"Andean sources it drew on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV063",
"Brazilian Concrete art",
"Grupo Ruptura;Grupo Frente",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1952",
"1959",
"approx.",
"Sao Paulo and Rio groups built rational, geometric art tied to graphic and industrial design.",
"geometric abstraction;industrial paint",
"painting;poster",
"record and writing",
"the members (Ruptura manifesto 1952)",
"women artists such as Judith Lauand and Lygia Pape",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV064",
"Neo-Concretism",
"Neoconcretismo",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1959",
"1961",
"approx.",
"Lygia Clark, Lygia Pape and Helio Oiticica made objects to be handled and worn.",
"participatory object;hinged metal",
"bicho;parangole",
"play and music",
"the members (Neo-Concrete Manifesto, 1959)",
"popular and Afro-Brazilian sources in the favelas that Oiticica drew on",
"none",
"collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV065",
"Tropicalia",
"Tropicalismo",
"movement",
"Ideas",
"F1.7",
"AM-LAT",
"1967",
"1969",
"approx.",
"Music, design and art mixed mass culture with Brazilian popular forms under dictatorship.",
"installation;album design",
"album cover;installation",
"play and music",
"the participants; Helio Oiticica's installation title (1967)",
"the Afro-Brazilian musicians and makers whose forms it quoted",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.4",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV066",
"Saint-Soleil",
"Saint Soleil",
"movement",
"Ideas",
"F1.7",
"AM-CAR",
"1972",
"1978",
"approx.",
"Haitian peasant artists, with Maud Robart and Jean-Claude Garoute, made painting and sculpture drawing on Vodou.",
"painting;sculpture",
"painting;sculpture",
"ritual and belief",
"the members; Andre Malraux wrote about them (1975)",
"the peasant artists' own authorship after outside attention",
"sacred;living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.16",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV067",
"Caribbean Artists Movement",
"CAM",
"movement",
"Ideas",
"F1.7;F1.11",
"AM-CAR;EU-BLC",
"1966",
"1972",
"approx.",
"Caribbean writers and artists in London developed a Caribbean aesthetic in exhibitions and publishing, outside metropolitan institutions.",
"painting;publishing",
"painting;publication",
"record and writing",
"the members (Kamau Brathwaite, John La Rose, Andrew Salkey)",
"artists who stayed in the Caribbean",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV068",
"Chicano art movement",
"Chicano Movement art",
"movement",
"Ideas",
"F1.7",
"AM-WST",
"1965",
"1985",
"approx.",
"Silkscreen poster workshops and community murals gave Mexican American communities their own public imagery.",
"screen printing;mural",
"poster;mural",
"rule and display;record and writing",
"the participants",
"women artists (e.g. Judith Baca, Yolanda Lopez)",
"none",
"Smithsonian Open Access (CC0);Library of Congress (public-domain items);collection search link-out only (works in copyright)",
"R2",
"F1.17",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV069",
"Harlem Renaissance",
"New Negro Movement",
"movement",
"Ideas",
"F1.7",
"AM-EWD",
"1918",
"1937",
"approx.",
"Black artists and designers (Aaron Douglas, Augusta Savage) made illustration and sculpture that drew on African forms.",
"illustration;sculpture;book design",
"magazine cover;sculpture;book",
"record and writing;rule and display",
"the members; Alain Locke (The New Negro, 1925)",
"women artists and craftspeople; its reliance on white patrons",
"none",
"Library of Congress (public-domain items);NYPL Digital Collections (public-domain items);Smithsonian Open Access (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV070",
"Black Arts Movement",
"BAM",
"movement",
"Ideas",
"F1.7",
"AM-EWD;AM-WST",
"1965",
"1975",
"approx.",
"Black artists built community-controlled presses, theatres and workshops, making the means of production part of the art.",
"printmaking;publishing",
"poster;book;mural",
"record and writing",
"the members (Amiri Baraka, Larry Neal)",
"women artists and the internal debates on gender",
"none",
"Library of Congress (public-domain items);collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV071",
"AfriCOBRA",
"African Commune of Bad Relevant Artists",
"movement",
"Ideas",
"F1.7",
"AM-EWD",
"1968",
"",
"approx.",
"A Chicago collective set a shared visual programme ('Kool-Aid colours', lettering) and made cheap prints for Black communities.",
"screen printing;lettering",
"print",
"record and writing",
"the members (Jeff Donaldson and others)",
"artists outside Chicago; women members' later careers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY076",
"Northwest Coast formline",
"Formline design",
"style",
"Ideas",
"F1.7",
"AM-NWC",
"1700",
"",
"approx.; much older; living tradition",
"A design system of ovoids and U-forms governs carving, painting and weaving.",
"formline;red cedar carving;Chilkat weaving",
"mask;bentwood box;totem pole;Chilkat blanket",
"ritual and belief;rule and display;food and storage",
"Bill Holm named the principles (1965); defined in practice by Haida, Tlingit, Tsimshian and other artists",
"the name is an outsider's analytic term; many carved objects removed by collectors",
"sacred;Indigenous-community;ancestral",
"Smithsonian Open Access (CC0);community-published site (link-out);collection search link-out only (works in copyright)",
"R2",
"F1.3;F1.26",
"high",
"Antiquity far older than 1700; rights held by nations and families.",
"canon_movements_styles_schools.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
