insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"SCH040",
"Kano school",
"Kanoha",
"school",
"Ideas",
"F1.8",
"AS-JPN",
"1480",
"1868",
"approx.",
"A hereditary workshop trained painters by copying model books (funpon) for screens and castles.",
"ink;gold leaf;model books",
"folding screen;sliding door",
"rule and display",
"the Kano family; historians",
"the workshop assistants; women",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);ColBase Japan (check per-item terms);Wikimedia Commons",
"R1",
"F1.17;F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH041",
"Tosa school",
"Tosaha",
"school",
"Ideas",
"F1.8",
"AS-JPN",
"1400",
"1868",
"approx.",
"A hereditary court painting lineage kept Yamato-e practice and supplied the imperial court for centuries.",
"mineral pigment",
"handscroll;album",
"rule and display",
"the Tosa family",
"workshop assistants and women of the family",
"none",
"Met Open Access (CC0);ColBase Japan (check per-item terms);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY147",
"Rinpa",
"Rimpa",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1600",
"",
"approx.; term 20th c.",
"Artists linked not by teaching but by emulation across a century made designs in gold, lacquer and textile.",
"gold leaf;tarashikomi;lacquer",
"screen;fan;kosode",
"rule and display",
"later historians",
"Hon'ami Koetsu's craft network; textile makers",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY148",
"Ukiyo-e",
"Pictures of the floating world",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1660",
"1900",
"approx.",
"Publishers, designers, block-carvers and printers made cheap colour prints as a team.",
"woodblock printing;colour registration",
"print;book",
"record and writing;play and music",
"historians",
"the carvers and printers",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Art Institute of Chicago (CC0);Cleveland Museum of Art Open Access (CC0);National Diet Library Digital Collections (public-domain items)",
"R1",
"F1.17;F1.21;F1.23",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY149",
"Nanga",
"Bunjinga",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1720",
"1900",
"approx.",
"Japanese painters learned Chinese literati painting largely from imported printed manuals such as the Mustard Seed Garden, painting from books rather than teachers.",
"ink",
"scroll",
"record and writing",
"historians",
"the professional painters they looked down on",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY150",
"Chanoyu aesthetics (wabi)",
"Wabi-sabi;tea aesthetics",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1480",
"",
"approx.; wabi-sabi as a pair is a modern term",
"Tea masters valued plain, irregular vessels, changing which objects were prized.",
"raku;stoneware;bamboo",
"tea bowl;tea caddy",
"food and storage;ritual and belief",
"tea masters (Murata Juko, Sen no Rikyu); later writers",
"the potters",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R1",
"F1.3;F1.22a",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY151",
"Sukiya-zukuri",
"Sukiya style",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1580",
"",
"approx.",
"Residential architecture drew on the tea house, using unfinished natural materials and irregular joinery as refinement.",
"timber;clay",
"tea house",
"shelter",
"historians",
"the carpenters (daiku) who developed the joinery",
"none",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY152",
"Giyofu architecture",
"Pseudo-Western architecture",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1860",
"1890",
"approx.",
"Japanese carpenters built Western-looking buildings with Japanese techniques.",
"timber;plaster",
"school",
"shelter",
"historians",
"the master carpenters",
"none",
"Wikimedia Commons",
"R3",
"F1.14",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY153",
"Imperial Crown Style",
"Teikan yoshiki",
"style",
"Ideas",
"F1.8",
"AS-JPN",
"1930",
"1945",
"approx.",
"Reinforced-concrete public buildings were topped with Japanese-style roofs to express nationalism in the 1930s.",
"reinforced concrete",
"museum",
"rule and display",
"historians",
"its use in colonial buildings in Korea and Taiwan",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV093",
"Nihonga",
"Japanese-style painting",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"1887",
"",
"approx.",
"Okakura Kakuzo and Ernest Fenollosa defined 'Japanese' painting, using mineral pigments on silk, as a modern category against Western oil painting.",
"mineral pigment;silk",
"painting",
"rule and display",
"Okakura Kakuzo; Ernest Fenollosa",
"the pre-Meiji schools it absorbed and renamed",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.3",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV094",
"Shin-hanga",
"New prints",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"1915",
"1960",
"approx.",
"Publisher Watanabe Shozaburo revived the ukiyo-e team of designer, carver and printer to make prints for export.",
"woodblock",
"print",
"exchange and value",
"Watanabe Shozaburo",
"the carvers and printers who made the prints",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV095",
"Sosaku-hanga",
"Creative prints",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"1904",
"1960",
"approx.",
"Artists carved and printed their own blocks, rejecting the publisher's division of labour for single-author making.",
"woodblock",
"print",
"record and writing",
"the members",
"the professional carvers whose skill set the standard",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV096",
"Mingei",
"Folk craft movement",
"movement",
"Ideas",
"F1.8;F1.13",
"AS-JPN;AS-KOR",
"1926",
"",
"approx.; manifesto 1926",
"Yanagi Soetsu, Hamada Shoji and Kawai Kanjiro championed anonymous everyday crafts.",
"hand production",
"ceramics;textile",
"food and storage;clothing and adornment",
"the members",
"the anonymous makers; Korean craftspeople",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R1",
"F1.3;F1.29",
"high",
"Existing project node; reconcile ID.",
"canon_movements_styles_schools.csv"
],
[
"MOV097",
"Gutai",
"Gutai Art Association",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"1954",
"1972",
"approx.",
"Artists in Osaka and Ashiya used bodies and materials such as mud, paper and paint in performative making.",
"performance;mud",
"painting",
"rule and display",
"the members (Yoshihara Jiro)",
"women members (e.g. Tanaka Atsuko) long under-credited",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV098",
"Mono-ha",
"School of Things",
"movement",
"Ideas",
"F1.8",
"AS-JPN;AS-KOR",
"1968",
"1975",
"approx.",
"Artists placed raw stone, wood, steel and glass in relation to one another, letting materials rather than making carry the work.",
"stone;steel",
"installation",
"rule and display",
"the members (Lee Ufan)",
"Korean members such as Lee Ufan in Japan-centred accounts",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV099",
"Superflat",
"Superflat",
"movement",
"Ideas",
"F1.8",
"AS-JPN",
"2000",
"",
"approx.",
"Takashi Murakami joined anime, commercial goods and Japanese painting, running a studio organised like a production company.",
"studio production",
"painting",
"play and music",
"Takashi Murakami",
"the studio assistants who make the works",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY154",
"Lapita style",
"Lapita decorative system",
"style",
"Ideas",
"F1.12",
"OC-MEL;OC-POL",
"-1500",
"-500",
"approx.",
"Dentate-stamped pottery traces the first settlement of Remote Oceania by seafarers and is used to map that migration.",
"dentate stamping;earthenware",
"pot",
"food and storage",
"archaeologists (type site 1952)",
"descendant Pacific communities",
"Indigenous-community",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13;F1.30",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY155",
"Arnhem Land x-ray style",
"X-ray art",
"style",
"Ideas",
"F1.12",
"OC-AUS",
"-2000",
"",
"approx.",
"Painters on rock and bark show the internal organs and bones of animals and people, a long-lived tradition still practised.",
"ochre;bark",
"rock art;bark painting",
"ritual and belief",
"archaeologists",
"the clan-specific knowledge behind the images",
"sacred;Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.16",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY156",
"Yirrkala bark painting",
"Yolngu bark painting",
"style",
"Ideas",
"F1.12",
"OC-AUS",
"1935",
"",
"approx.",
"Yolngu painters made bark paintings for exchange and for the 1963 Bark Petitions.",
"ochre on bark",
"bark painting",
"ritual and belief",
"Yolngu artists",
"community control",
"sacred;Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R2",
"F1.16;F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH042",
"Hermannsburg School",
"Arrernte watercolour",
"school",
"Ideas",
"F1.12",
"OC-AUS",
"1936",
"",
"approx.",
"Albert Namatjira and other Western Arrernte painters made watercolour landscapes of their Country, a practice continued by family members today.",
"watercolour",
"landscape",
"rule and display",
"artists; Rex Battarbee",
"the legal restrictions on Namatjira's citizenship and the copyright loss after his death",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R2",
"F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV100",
"Western Desert painting movement",
"Papunya Tula",
"movement",
"Ideas",
"F1.12",
"OC-AUS",
"1971",
"",
"approx.",
"Papunya men began painting ancestral designs in acrylic on board in 1971, founding a painting movement run through community art centres.",
"acrylic;dot",
"painting",
"ritual and belief",
"the artists; Geoffrey Bardon",
"the sacred designs that had to be withdrawn from public display after 1972 disputes",
"sacred;Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R1",
"F1.16;F1.26",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY157",
"East Kimberley painting",
"Warmun painting",
"style",
"Ideas",
"F1.12",
"OC-AUS",
"1975",
"",
"approx.",
"Gija artists at Warmun, following Rover Thomas and the Gurirr Gurirr ceremony, painted natural ochre on canvas.",
"ochre",
"painting",
"ritual and belief",
"Gija artists",
"restricted ceremonial knowledge",
"Indigenous-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV101",
"proppaNOW",
"proppaNOW",
"movement",
"Ideas",
"F1.12",
"OC-AUS",
"2003",
"",
"approx.",
"A Brisbane collective of urban Aboriginal artists makes work that refuses the market expectation of 'traditional' desert style.",
"mixed media",
"artwork",
"rule and display",
"the members",
"remote community artists whose market position it critiques",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV102",
"Hawaiian Renaissance",
"Hawaiian Renaissance",
"movement",
"Ideas",
"F1.12",
"OC-POL",
"1970",
"1990",
"approx.",
"Hawaiians revived voyaging-canoe building (Hokule'a, 1975), hula, kapa making and language as a cultural and political movement.",
"canoe building",
"canoe",
"transport",
"the participants",
"the makers who kept practices alive before the revival",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.29",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV103",
"Contemporary Maori art movement",
"Maori modernism",
"movement",
"Ideas",
"F1.12",
"OC-POL",
"1950",
"",
"approx.",
"Maori artists (e.g. Paratene Matchitt, Arnold Wilson, Sandy Adsett) joined customary forms with modern painting and sculpture.",
"painting;carving",
"painting",
"rule and display",
"artists",
"iwi-based carvers and weavers working within customary practice",
"Indigenous-community",
"Te Papa Collections Online (CC BY items);community-published site (link-out)",
"R3",
"F1.20",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV104",
"Pacific Sisters",
"Pacific Sisters collective",
"movement",
"Ideas",
"F1.12",
"OC-POL",
"1992",
"",
"approx.",
"A collective of Pacific Island and Maori women in Auckland combined fashion, performance and customary materials.",
"fashion",
"garment",
"clothing and adornment",
"the members",
"Pacific makers outside the diaspora",
"Indigenous-community",
"Te Papa Collections Online (CC BY items);community-published site (link-out)",
"R3",
"F1.18",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV105",
"Sami Artist Group",
"Maze Group",
"movement",
"Ideas",
"F1.11",
"EU-SCA",
"1978",
"1983",
"approx.",
"Sami artists in Masi, Norway, formed a group that made Sami identity visible in contemporary art and duodji.",
"painting",
"painting",
"rule and display",
"the members",
"Sami makers in Sweden, Finland and Russia",
"Indigenous-community",
"DigitaltMuseum Norway/Sweden (CC BY items);community-published site (link-out)",
"R3",
"F1.20",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY158",
"Soviet Modernism",
"Soviet modernist architecture",
"style",
"Ideas",
"F1.11;F1.12a",
"EU-EER;AS-CEN;WA-CAU",
"1955",
"1991",
"approx.",
"Soviet architects built prefabricated panel housing and modernist public buildings with large mosaics, including in Central Asia and the Caucasus.",
"prefabricated panel;mosaic",
"housing",
"shelter",
"historians",
"local artists who made the mosaics; residents",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY159",
"Viking art styles (Oseberg to Ringerike)",
"Oseberg/Broa, Borre, Jelling, Mammen, Ringerike styles",
"style",
"Ideas",
"F1.11",
"EU-SCA;EU-BLC;EU-EER",
"775",
"1050",
"approx.; Oseberg c.775-875, Borre c.850-975, Jelling c.900-975, Mammen c.950-1025, Ringerike c.990-1050",
"A sequence of animal-ornament styles on wood, metal and stone lets archaeologists date Viking Age finds from Ireland to Russia.",
"wood carving;metal casting;filigree;silver inlay;stone carving",
"ship fittings;brooch;harness mount;runestone",
"clothing and adornment;transport;rule and display;ritual and belief",
"20th c. archaeologists naming type sites (e.g. Wilson and Klindt-Jensen, 1966)",
"the makers (smiths and carvers); women's textiles from the same graves; Sami and Slavic neighbours",
"funerary",
"Wikimedia Commons;DigitaltMuseum Norway/Sweden (CC BY items);Met Open Access (CC0)",
"R2",
"F1.3;F1.30",
"high",
"Urnes has its own row. Many finds are grave goods.",
"canon_movements_styles_schools.csv"
],
[
"STY160",
"Hindu temple styles (Nagara, Dravida, Vesara)",
"Nagara;Dravida;Vesara",
"style",
"Ideas",
"F1.9",
"AS-SAS;AS-MSE;AS-ISE",
"500",
"",
"approx.; living tradition",
"South Indian building texts name three temple types, defined mainly by plan shape (square, polygonal, round or apsidal), which later writers mapped onto north, south and the Deccan and still use to classify temples.",
"stone masonry;corbelled tower;proportional grid (vastu)",
"temple;shrine;gateway (gopuram)",
"ritual and belief;shelter",
"Sanskrit architectural treatises (shilpa and vastu texts); later historians",
"regional and village temple traditions that do not fit the three types; the masons' guild knowledge",
"sacred;living-community",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.16;F1.28",
"high",
"Checked: in the agamas and Manasara, Vesara means a round or apsidal (or square-below, round-above) form; its modern use for Deccan \"hybrid\" temples is contested (Adam Hardy prefers \"Karnata Dravida\"; George Michell avoids the term).",
"canon_movements_styles_schools.csv"
],
[
"SCH043",
"Rajasthani (Rajput) painting schools",
"Mewar, Bundi-Kota, Kishangarh, Bikaner, Marwar schools",
"school",
"Ideas",
"F1.9",
"AS-SAS",
"1600",
"1900",
"approx.",
"Court workshops in Rajput kingdoms made illustrated texts, court records and portraits, each with local conventions; many painters were Muslim families working for Hindu courts.",
"opaque watercolour;burnishing;gold",
"manuscript page;court painting;portrait",
"record and writing;rule and display;ritual and belief",
"art historians (court-based classification)",
"the painter families who moved between courts, making court labels misleading",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.26",
"high",
"Classification by court is challenged by family-lineage research (see Pandit Seu row).",
"canon_movements_styles_schools.csv"
],
[
"STY161",
"Lahore and Karachi modernism",
"Pakistani modernism",
"style",
"Ideas",
"F1.9",
"AS-SAS",
"1947",
"1980",
"approx.",
"Artists in Lahore and Karachi built a modern art after Partition, including calligraphic painting (Sadequain, Hanif Ramay) and teaching at the Mayo School/NCA.",
"oil;calligraphy;mural",
"painting;mural",
"record and writing;rule and display",
"historians; groups such as the Lahore Art Circle (1952)",
"women artists (e.g. Zubeida Agha, Anna Molka Ahmed) who led it; regional craft traditions",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"medium",
"Project's own umbrella label, not a historical group name. Checked: Lahore Art Circle founded 1952 (Shakir Ali, Anwar Jalal Shemza, Ahmed Parvez and others); Mayo School became the National College of Arts in 1958.",
"canon_movements_styles_schools.csv"
],
[
"STY162",
"Sepik River art styles",
"Middle Sepik styles",
"style",
"Ideas",
"F1.12",
"OC-MEL",
"1800",
"",
"approx.; much older; living",
"Carvers and painters of Sepik villages make house posts, masks and gable paintings in village-specific styles, heavily collected in the colonial period.",
"wood carving;clay overmodelling;painting on sago spathe",
"mask;hook figure;men's house gable",
"ritual and belief;shelter",
"anthropologists and collectors; Sepik communities",
"village-level distinctions the regional label flattens; objects removed by collecting expeditions",
"sacred;Indigenous-community;living-community",
"Met Open Access (CC0);Auckland Museum Collections Online (CC BY items);collection search link-out only (works in copyright)",
"R3",
"F1.24",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY163",
"Asmat carving",
"Asmat art",
"style",
"Ideas",
"F1.12",
"OC-MEL;AS-ISE",
"1900",
"",
"approx.; living",
"Asmat carvers make ancestor poles (bis), shields and canoes; collecting and missionary markets reshaped the practice.",
"wood carving;pigment",
"bis pole;shield;canoe prow",
"ritual and belief;war;transport",
"Asmat carvers; missionaries and collectors (e.g. 1961 Rockefeller expedition)",
"the political situation in West Papua",
"sacred;ancestral;Indigenous-community",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.24",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH044",
"Ngati Tarawhai carving school",
"Te Arawa carvers",
"school",
"Ideas",
"F1.12",
"OC-POL",
"1850",
"1930",
"approx.",
"A lineage of Te Arawa carvers (e.g. Wero Taroi, Tene Waitere) carved meeting houses and also for colonial tourism and museums.",
"wood carving;paua inlay",
"meeting house;panel",
"ritual and belief;shelter",
"Ngati Tarawhai; historians (Roger Neich)",
"the tourism and museum commissions that moved carvings overseas",
"ancestral;Indigenous-community",
"Te Papa Collections Online (CC BY items);Auckland Museum Collections Online (CC BY items);community-published site (link-out)",
"R3",
"F1.26;F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"MOV106",
"Torres Strait Islander printmaking",
"Torres Strait linocut movement",
"movement",
"Ideas",
"F1.12",
"OC-AUS;OC-MEL",
"1990",
"",
"approx.",
"Islander artists (e.g. Dennis Nona, Alick Tipoti) turned carving and mask designs into large linocuts, a new medium for old designs.",
"linocut;etching",
"print",
"ritual and belief;record and writing",
"the artists; Cairns TAFE teaching programme",
"Islanders outside the printmaking market",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.26",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH045",
"Zanabazar school",
"Zanabazar sculpture",
"school",
"Ideas",
"F1.12a;F1.9",
"AS-CEN;AS-HIM",
"1650",
"1723",
"approx.; lifetime of Zanabazar and followers",
"The first Bogd Gegeen of Mongolia led a workshop of gilt-bronze casting, setting a Mongolian Buddhist sculpture style.",
"lost-wax casting;fire gilding",
"Buddhist image",
"ritual and belief",
"Mongolian tradition; historians",
"Newar and Tibetan sources; workshop members",
"sacred",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.13",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY164",
"Kucha (Kizil) painting style",
"Kizil cave painting",
"style",
"Ideas",
"F1.12a;F1.9",
"AS-CEN;AS-CHN",
"300",
"700",
"approx.",
"Cave murals at Kizil show a Central Asian Buddhist painting workshop tradition between India, Iran and China.",
"mineral pigment on clay plaster",
"cave mural",
"ritual and belief",
"art historians; German Turfan expeditions named styles",
"mural sections cut out and removed to Berlin",
"sacred;conflict-looting",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.13;F1.24",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY165",
"Suzani regional styles",
"Suzani",
"style",
"Ideas",
"F1.12a;F1.10",
"AS-CEN",
"1750",
"",
"approx.; living",
"Women embroidered dowry hangings in regional styles (Bukhara, Samarkand, Nurata, Shakhrisabz) that collectors named by city.",
"silk embroidery;chain stitch;couching",
"wall hanging;bedcover",
"shelter;ritual and belief",
"dealers and collectors (city names); the embroiderers",
"the women makers; collector naming by city",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);collection search link-out only (works in copyright)",
"R2",
"F1.18;F1.3",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY166",
"Turkmen carpet gol tradition",
"Turkmen rugs",
"style",
"Ideas",
"F1.12a;F1.10",
"AS-CEN",
"1700",
"",
"approx.",
"Turkmen weavers used gol medallions that dealers and scholars read as signatures of particular groups (Tekke, Yomut, Salor).",
"knotted pile;wool;natural dye",
"carpet;tent band;bag",
"shelter;transport;food and storage",
"dealers and rug scholars",
"women weavers; the uncertainty of tribal attribution",
"living-community",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.18",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY167",
"Caucasian rug regional styles",
"Kazak, Shirvan, Karabagh rugs",
"style",
"Ideas",
"F1.12a;F1.9a",
"WA-CAU",
"1800",
"",
"approx.",
"Village weavers across the Caucasus made rugs that the Western trade classified by region names.",
"knotted pile;flatweave",
"rug",
"shelter",
"dealers and collectors",
"Armenian, Azerbaijani and other makers' own names; women weavers",
"living-community",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.18",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH046",
"Cilician Armenian illumination",
"Cilician school",
"school",
"Ideas",
"F1.9a;F1.11",
"WA-ANA;WA-CAU",
"1150",
"1375",
"approx.",
"Manuscript painters such as T'oros Roslin worked in the Armenian kingdom of Cilicia, linking Byzantine, Latin and Mongol-era art.",
"parchment;gold;illumination",
"gospel book",
"ritual and belief;record and writing",
"historians",
"scribes' colophons name makers often left out of accounts",
"sacred",
"Walters Art Museum (CC0);Getty Open Content;Wikimedia Commons",
"R3",
"F1.28",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY168",
"Urartian metalwork style",
"Urartian art",
"style",
"Ideas",
"F1.9a",
"WA-CAU;WA-ANA",
"-850",
"-590",
"approx.",
"Bronze workshops of Urartu made cauldrons, shields and belts in a court style.",
"bronze casting;repousse",
"cauldron;belt;shield",
"war;rule and display",
"archaeologists",
"looted findspots",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.24",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY169",
"Phoenician and North Syrian ivory style",
"Syro-Phoenician ivories",
"style",
"Ideas",
"F1.9a",
"WA-LEV;WA-MES",
"-900",
"-700",
"approx.",
"Carved ivory furniture panels were traded and taken as tribute, many found at Nimrud.",
"ivory carving;gold leaf;glass inlay",
"furniture panel",
"rule and display;exchange and value",
"archaeologists",
"the carvers; the elephants and trade",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY170",
"Nabataean style",
"Nabataean art",
"style",
"Ideas",
"F1.9a",
"WA-ARB;WA-LEV",
"-300",
"106",
"approx.",
"Rock-cut facades at Petra and Hegra and thin painted pottery show a trading kingdom's building and ceramic workshops.",
"rock-cut architecture;eggshell-thin pottery",
"tomb facade;bowl",
"ritual and belief;food and storage",
"archaeologists",
"the caravan traders and workers; the Arabian peoples outside the kingdom",
"funerary",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY171",
"Al-Qatt Al-Asiri",
"Asiri wall painting",
"style",
"Ideas",
"F1.10",
"WA-ARB",
"1800",
"",
"approx.; living",
"Women of Asir paint geometric designs on house interiors, recorded by UNESCO (2017).",
"wall painting;pigment",
"interior wall",
"shelter",
"the women painters; UNESCO",
"the women painters' names",
"living-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY172",
"Najdi architecture",
"Najdi mud-brick architecture",
"style",
"Ideas",
"F1.10",
"WA-ARB",
"1700",
"",
"approx.",
"Builders in central Arabia used mud brick with triangular openings and painted doors, a style later revived in Riyadh.",
"mud brick;palm timber",
"house;palace;door",
"shelter",
"historians",
"the builders",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY173",
"Inuit carving (post-war)",
"Inuit sculpture",
"style",
"Ideas",
"F1.7",
"AM-ARC",
"1948",
"",
"approx.",
"Inuit carvers made stone sculpture for a southern market promoted by James Houston and the Canadian state.",
"soapstone carving;serpentine",
"sculpture",
"exchange and value",
"James Houston and Canadian Handicrafts Guild; Inuit carvers",
"pre-contact carving; the state's role in shaping style",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.21",
"high",
"",
"canon_movements_styles_schools.csv"
],
[
"STY174",
"Zafimaniry woodcraft",
"Zafimaniry carving",
"style",
"Ideas",
"F1.6",
"AF-MAD",
"1700",
"",
"approx.; living",
"Zafimaniry carvers cover houses and furniture with geometric patterns, recorded by UNESCO (2003/2008).",
"wood carving",
"house;furniture",
"shelter",
"Zafimaniry makers; UNESCO",
"forest loss that now limits wood",
"living-community",
"community-published site (link-out);collection search link-out only (works in copyright)",
"R3",
"F1.22;F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY175",
"Aloalo sculpture",
"Mahafaly and Sakalava funerary posts",
"style",
"Ideas",
"F1.6",
"AF-MAD",
"1800",
"",
"approx.",
"Carvers make funerary posts with figures for tombs in southern and western Madagascar.",
"wood carving",
"funerary post",
"ritual and belief",
"Mahafaly and Sakalava carvers; historians",
"posts taken for museums",
"funerary;ancestral",
"collection search link-out only (works in copyright)",
"R3",
"F1.16;F1.24",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY176",
"Kusiwa",
"Wajapi body painting",
"style",
"Ideas",
"F1.7",
"AM-AMZ",
"1900",
"",
"approx.; living",
"Wajapi designs painted on the body with urucum and genipap were recorded by UNESCO (2003/2008).",
"body painting",
"body design",
"clothing and adornment;ritual and belief",
"the Wajapi; UNESCO",
"the designs' meaning",
"Indigenous-community;living-community",
"community-published site (link-out)",
"R3",
"F1.29",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY177",
"Makonde modern carving",
"Shetani style",
"style",
"Ideas",
"F1.6",
"AF-SWA",
"1950",
"",
"approx.",
"Makonde carvers in Tanzania and Mozambique made ebony figures such as Shetani and Ujamaa, for a tourist and art market.",
"ebony carving",
"sculpture",
"ritual and belief;exchange and value",
"carvers; dealers",
"the carvers' names under market labels",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY178",
"Kamba carving",
"Akamba carving",
"style",
"Ideas",
"F1.6",
"AF-SWA",
"1920",
"",
"approx.",
"Kamba carvers after Mutisya Munge made figures for colonial and tourist markets, often in cooperatives.",
"wood carving",
"figure",
"exchange and value",
"carvers; historians",
"market labels over individual carvers",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"SCH047",
"Shona stone sculpture",
"Zimbabwean stone sculpture;Workshop School",
"school",
"Ideas",
"F1.6",
"AF-SOU",
"1957",
"",
"approx.; Frank McEwen's Workshop School from 1957",
"Sculptors at the National Gallery workshop and Tengenenge made serpentine sculpture for international markets.",
"stone carving",
"sculpture",
"ritual and belief;exchange and value",
"Frank McEwen; the sculptors",
"the 'Shona' label, since not all artists were Shona",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY179",
"Ga figurative coffins",
"Abebuu adekai",
"style",
"Ideas",
"F1.6",
"AF-GUI",
"1950",
"",
"approx.",
"Ga carpenters build coffins shaped like objects of the dead person's life.",
"carpentry;paint",
"coffin",
"ritual and belief",
"Ga carpenters (e.g. Seth Kane Kwei workshop)",
"the funeral context behind gallery display",
"funerary",
"collection search link-out only (works in copyright)",
"R3",
"F1.16",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"STY180",
"Fante asafo flags",
"Asafo flags",
"style",
"Ideas",
"F1.6",
"AF-GUI",
"1850",
"",
"approx.",
"Fante militia companies commissioned applique flags with proverbs and Union Jack cantons.",
"applique;cotton",
"flag",
"war;rule and display",
"Fante asafo companies; historians",
"the flag makers",
"none",
"collection search link-out only (works in copyright);Met Open Access (CC0)",
"R3",
"F1.19a",
"medium",
"",
"canon_movements_styles_schools.csv"
],
[
"NET001",
"Silk Roads",
"Silk Road; Seidenstraße; overland Silk Routes",
"network",
"Connections",
"F1.13;F1.8;F1.12a;F1.10;F1.9a;F1.11",
"AS-CHN;AS-CEN;WA-IRN;WA-LEV;AS-SAS;EU-GRR;EU-BYZ",
"-130",
"1450",
"conventional start with Han envoy Zhang Qian's missions c.138–126 BCE; steppe exchange far older; decline after c.1450 debated",
"Relay routes across Eurasia carried silk, paper-making, glass, metalwork, textile patterns, pigments and travelling craftspeople between China, Central Asia, Iran, South Asia and the Mediterranean.",
"sericulture; paper-making; glassblowing; weaving; metalwork",
"silk textiles; glass vessels; silver vessels; paper; ceramics; manuscripts",
"exchange and value;transport",
"Ferdinand von Richthofen (term Seidenstraße, 1877); historians; UNESCO (Chang'an–Tianshan corridor, 2014)",
"The name privileges silk and the two ends; it leaves out steppe herders, oasis makers, non-silk goods, and the relay character of most exchange.",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); International Dunhuang Programme (link out); Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Staatliche Museen zu Berlin SMB-digital (CC BY-SA where marked)",
"R1",
"F1.13;F1.14;F1.3",
"high",
"Umbrella node: members include steppe route, oasis route, Tea Horse Road and Sogdian diaspora.",
"canon_networks.csv"
],
[
"NET002",
"Steppe route",
"Eurasian steppe corridor; Steppe Road",
"network",
"Connections",
"F1.13;F1.12a",
"AS-CEN;AS-NTH;EU-EER;AS-CHN;WA-CAU",
"-2000",
"",
"east–west movement of horses, chariots and metallurgy from the 3rd–2nd millennium BCE; Mongol-era (13th–14th c.) peak; ongoing in altered form",
"Mobile pastoralists moved horse gear, chariot technology, bronze metallurgy, felt and gold animal-style ornament across the grasslands from Hungary to Mongolia.",
"felt making; bronze casting; gold working; horse tack",
"felt; gold plaques; bronze knives; chariots; saddles",
"transport;exchange and value;war",
"archaeologists; historians of Central Eurasia",
"Framing as 'route' can hide that herders were makers and patrons, not only carriers.",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports; Europeana",
"R2",
"F1.13",
"high",
"Much evidence is from kurgan burials (funerary sensitivity).",
"canon_networks.csv"
],
[
"NET003",
"Oasis route (Tarim Basin)",
"northern and southern Silk Roads around the Taklamakan",
"network",
"Connections",
"F1.13;F1.8;F1.12a",
"AS-CHN;AS-CEN",
"-130",
"1000",
"Han to late first millennium CE; approximate",
"Oasis cities such as Dunhuang, Turfan, Kucha, Khotan and Kashgar were workshops and relay points for silk, jade, wall painting, manuscripts and Buddhist image-making.",
"wall painting; silk weaving; jade working; manuscript copying",
"murals; manuscripts; textiles; jade",
"exchange and value;record and writing;ritual and belief",
"historians; archaeologists (Stein, Pelliot and later)",
"The early-20th-c. removals of Dunhuang and Turfan material to European and Japanese collections are part of this history.",
"sacred;conflict-looting",
"International Dunhuang Programme (link out); Met Open Access (CC0); Wikimedia Commons; Staatliche Museen zu Berlin SMB-digital (CC BY-SA where marked)",
"R2",
"F1.13;F1.24",
"high",
"Dunhuang Library Cave removals (1907–) relevant to F1.24.",
"canon_networks.csv"
],
[
"NET004",
"Tea Horse Road",
"Chamadao; Ancient Tea Horse Road; Southern Silk Road (partly)",
"network",
"Connections",
"F1.13;F1.8;F1.9",
"AS-CHN;AS-HIM",
"1000",
"1950",
"Song-dynasty tea-for-horses trade formalised 11th c.; Tang origins claimed; porterage into the 20th c.",
"Mule caravans and human porters carried compressed brick tea from Yunnan and Sichuan to Tibet in exchange for horses, wool and medicinal goods.",
"tea compressing; caravan packing; porterage",
"brick tea; tea caddies; saddlery",
"exchange and value;food and storage;transport",
"Chinese historians (term popularised 1990s)",
"Porters' labour (many carried loads over 100 kg) is rarely centred.",
"living-community",
"Wikimedia Commons; open-access journal articles",
"R3",
"F1.13;F1.23",
"medium",
"Term 'Chamagudao' dates from 1990s scholarship.",
"canon_networks.csv"
],
[
"NET005",
"Indian Ocean world",
"Indian Ocean trade; Maritime Silk Road (western)",
"network",
"Connections",
"F1.13;F1.6;F1.9;F1.10;F1.9a",
"AF-SWA;AF-HRN;AF-MAD;WA-ARB;AS-SAS;AS-ISE;AS-MSE;AS-CHN",
"-2500",
"",
"from Harappan–Gulf contact c.2500 BCE; monsoon sailing documented by 1st c. CE; ongoing",
"Monsoon-timed sailing linked textile, bead, ceramic and metal makers from East Africa to China, spreading cotton cloth, glass beads, stoneware and shipbuilding know-how.",
"monsoon sailing; sewn-plank boats; cotton weaving; bead making",
"beads; cotton textiles; stoneware jars; porcelain; ivory",
"exchange and value;transport",
"historians (e.g. K.N. Chaudhuri; Abdul Sheriff); archaeologists",
"Enslaved people moved through the same circuits; coastal and island makers are often reduced to entrepôts.",
"human-flow",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); British Museum EMKP (CC); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.13;F1.23",
"high",
"Umbrella node; sub-circuits Arabian Sea, Bay of Bengal, South China Sea.",
"canon_networks.csv"
],
[
"NET006",
"Arabian Sea circuit",
"Erythraean Sea trade",
"network",
"Connections",
"F1.13;F1.9;F1.10;F1.6",
"WA-ARB;AS-SAS;AF-HRN;AF-SWA;AF-EGY",
"-2500",
"",
"Harappan–Gulf phase c.2500 BCE; Periplus of the Erythraean Sea 1st c. CE; ongoing",
"The western Indian Ocean circuit moved Gujarati and Malabar textiles, pepper, beads, incense and Chinese ceramics between India, Arabia, the Red Sea and East Africa.",
"dhow building; cotton weaving; bead making",
"textiles; pepper jars; beads; amphorae",
"exchange and value;transport",
"historians; the Periplus (1st c. CE Greek text)",
"",
"none",
"Wikimedia Commons; Internet Archive (public-domain texts); open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET007",
"Bay of Bengal circuit",
"Bay of Bengal trade",
"network",
"Connections",
"F1.13;F1.9",
"AS-SAS;AS-MSE;AS-ISE",
"-400",
"",
"Khao Sam Kaeo and Arikamedu evidence from 4th–1st c. BCE; ongoing",
"Exchange between eastern India, Sri Lanka and Southeast Asia carried glass and stone beads, rouletted ware, Buddhist and Hindu image-making and textile patterns.",
"drawn glass beads; stone bead drilling; cotton painting",
"Indo-Pacific beads; rouletted ware; bronze images; textiles",
"exchange and value;ritual and belief;transport",
"historians (e.g. Sunil Amrith); archaeologists",
"South Asian craftspeople working in Southeast Asian ports.",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons; open-access journal articles",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET008",
"South China Sea circuit",
"Nanyang trade",
"network",
"Connections",
"F1.13;F1.8;F1.9",
"AS-CHN;AS-MSE;AS-ISE",
"-500",
"",
"first millennium BCE (jade, bronze drums); intensive from 9th c.; ongoing",
"Exchange between southern China, Vietnam, the Philippines and the Malay world carried jade, bronze drums, stoneware, porcelain, forest products and shipbuilding traditions.",
"lashed-lug boat building; stoneware firing",
"stoneware jars; porcelain; bronze drums",
"exchange and value;transport",
"historians; maritime archaeologists",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons; open-access excavation reports",
"R3",
"F1.13",
"high",
"Overlaps Maritime Jade Road and Nanhai route.",
"canon_networks.csv"
],
[
"NET009",
"Nanhai route",
"South Sea route; Maritime Silk Road (Chinese side)",
"network",
"Connections",
"F1.13;F1.8;F1.9",
"AS-CHN;AS-MSE;AS-ISE;AS-SAS",
"-200",
"1500",
"Han references; Song–Yuan peak at Guangzhou and Quanzhou",
"Chinese ports shipped stoneware, porcelain, silk and iron to the south and west; wrecks such as Belitung (c.830) and Nanhai One (12th c.) preserve whole cargoes.",
"kiln mass production; packing in storage jars",
"Changsha bowls; celadon; iron bars; silk",
"exchange and value;transport",
"Chinese historical texts; historians; UNESCO (Quanzhou, 2021)",
"",
"conflict-looting",
"Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out); open-access journal articles",
"R2",
"F1.13;F1.24",
"high",
"Belitung cargo recovery (commercial salvage) raised ethical debate — check framing.",
"canon_networks.csv"
],
[
"NET010",
"Trans-Saharan trade",
"caravan trade; salt–gold trade",
"network",
"Connections",
"F1.13;F1.6;F1.10",
"AF-MAG;AF-SAH;AF-EGY;AF-GUI",
"300",
"1900",
"camel caravans from c.3rd–4th c. CE; earlier Garamantian links; decline late 19th c.",
"Camel caravans exchanged West African gold, salt, copper, glass, textiles and books, and carried Maghribi and Sahelian styles of building, leatherwork and manuscript making.",
"leatherwork; copper alloy casting; manuscript copying; salt cutting",
"gold; salt slabs; Tuareg leatherwork; manuscripts; beads",
"exchange and value;transport;record and writing",
"historians; Arabic geographers (al-Bakri, Ibn Battuta)",
"Enslaved people were moved across the Sahara; Tuareg and Sahelian makers.",
"human-flow",
"Met Open Access (CC0); Wikimedia Commons; British Museum EMKP (CC); open-access excavation reports",
"R1",
"F1.13;F1.23",
"high",
"Timbuktu manuscripts: some digitised open (check licences).",
"canon_networks.csv"
],
[
"NET011",
"Kilwa gold route",
"Sofala gold trade; Zimbabwe Plateau–Kilwa trade",
"network",
"Connections",
"F1.13;F1.6",
"AF-SOU;AF-SWA;AF-MAD",
"1100",
"1500",
"Mapungubwe and Great Zimbabwe periods; approximate",
"Gold from the Zimbabwe Plateau passed through Sofala to Kilwa, financing coral-stone building and coinage and bringing Chinese porcelain and Indian beads inland.",
"gold mining; coral-stone masonry; coin striking",
"gold; Kilwa coins; glass beads; porcelain sherds",
"exchange and value;rule and display",
"historians; archaeologists",
"Local miners and Shona-speaking makers are often subordinated to coastal narratives.",
"none",
"Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out); open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET012",
"Swahili dhow trade",
"monsoon dhow trade; mtepe and jahazi trade",
"network",
"Connections",
"F1.13;F1.6;F1.10",
"AF-SWA;WA-ARB;AS-SAS;AF-MAD",
"800",
"",
"from c.8th c.; ongoing on a small scale (Lamu, Zanzibar)",
"Monsoon dhows moved mangrove poles, ivory, textiles, carved doors and ceramics between the East African coast, Arabia and India, and carried boat-building skills.",
"sewn and nailed plank boats; coral-stone building; wood carving",
"dhows; carved doors; textiles; mangrove poles",
"transport;exchange and value",
"historians; Swahili communities",
"19th-c. trafficking of enslaved people through Zanzibar.",
"human-flow;living-community",
"Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out); open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET013",
"Cowrie shell currency network",
"cowrie money; Maldivian cowries",
"network",
"Connections",
"F1.13;F1.6;F1.9;F1.8",
"AF-GUI;AF-SAH;AS-SAS;AF-MAD;AS-CHN",
"-1200",
"1900",
"cowries in Shang China c.1200 BCE; Maldivian cowries to Bengal and West Africa to 19th c.",
"Maldivian Monetaria moneta shells served as money from Bengal to West Africa, shipped as ballast by European companies and used to buy enslaved people.",
"shell harvesting; stringing",
"cowrie strings; cowrie-covered regalia",
"exchange and value;clothing and adornment;ritual and belief",
"historians (Hogendorn and Johnson, 'The Shell Money of the Slave Trade', 1986)",
"",
"human-flow",
"Met Open Access (CC0); British Museum EMKP (CC); Wikimedia Commons",
"R3",
"F1.13;F1.23",
"high",
"",
"canon_networks.csv"
],
[
"NET014",
"Ivory trade",
"elephant ivory trade",
"network",
"Connections",
"F1.13;F1.6;F1.11;F1.8",
"AF-SWA;AF-CEN;AF-GUI;AS-SAS;AS-CHN;EU-WCE",
"-2000",
"1989",
"multiple eras; ancient Egyptian and Aegean trade; 19th-c. caravan trade most documented; CITES ban 1989",
"Elephant ivory moved from Africa and South Asia to carvers in China, India, Europe and the Mediterranean; 19th-c. demand for piano keys and billiard balls drove caravan trade.",
"ivory carving; turning",
"carvings; piano keys; combs; oliphants",
"exchange and value;rule and display;play and music",
"historians; conservation bodies",
"Enslaved porters carried tusks in 19th-c. East and Central Africa; looted Benin ivories (1897).",
"human-flow;conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R3",
"F1.13;F1.22;F1.24",
"high",
"",
"canon_networks.csv"
],
[
"NET015",
"European glass trade-bead circulation",
"trade beads; Venetian trade beads",
"network",
"Connections",
"F1.13;F1.6;F1.7",
"EU-WCE;AF-GUI;AF-CEN;AF-SWA;AM-EWD;AM-WST;AM-NWC",
"1480",
"1900",
"Venetian, Bohemian and Dutch beads exported from late 15th c.",
"Venetian, Bohemian and Dutch glass beads were exchanged in Africa and the Americas, where makers reworked them into regalia and beadwork.",
"drawn glass beads; lampwork; beadwork",
"chevron beads; seed beads; beaded regalia",
"exchange and value;clothing and adornment",
"historians; bead researchers",
"Beads were among goods exchanged for enslaved Africans.",
"human-flow",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.13;F1.14",
"high",
"",
"canon_networks.csv"
],
[
"NET016",
"Dilmun–Magan–Meluhha trade",
"Gulf trade; Harappan–Mesopotamian trade",
"network",
"Connections",
"F1.13;F1.9a;F1.9",
"WA-MES;WA-ARB;AS-SAS;WA-IRN",
"-2600",
"-1700",
"Akkadian texts name Dilmun (Bahrain), Magan (Oman) and Meluhha (Indus region)",
"Maritime trade brought Magan copper, Indus carnelian beads and seals, and timber to Mesopotamia, recorded in cuneiform and seen in Ur's royal tombs.",
"copper smelting; carnelian bead drilling; seal carving",
"etched carnelian beads; Gulf seals; copper ingots",
"exchange and value;transport",
"Assyriologists; archaeologists",
"Identification of Meluhha with the Indus region is a scholarly consensus, not a self-name.",
"none",
"Met Open Access (CC0); Cuneiform Digital Library Initiative (link out); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET017",
"Old Assyrian trade (Aššur–Kaneš)",
"Kültepe trade; Old Assyrian merchant colonies",
"network",
"Connections",
"F1.13;F1.9a",
"WA-MES;WA-ANA",
"-1950",
"-1750",
"Kültepe (Kaneš) level II and Ib",
"Assyrian merchant families shipped tin and textiles by donkey caravan to Anatolia for silver and gold, documented in some 23,000 cuneiform letters.",
"donkey caravans; textile weaving (women in Aššur); tin trade",
"tablets; textiles; tin",
"exchange and value;record and writing",
"Assyriologists (letters from Kültepe)",
"Assyrian women who wove textiles for export and wrote letters.",
"none",
"Cuneiform Digital Library Initiative (link out); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13;F1.18;F1.28",
"high",
"",
"canon_networks.csv"
],
[
"NET018",
"Lapis lazuli route",
"Badakhshan lapis trade",
"network",
"Connections",
"F1.13;F1.9a;F1.12a;F1.6",
"AS-CEN;WA-IRN;WA-MES;AF-EGY;AS-SAS",
"-4000",
"-1000",
"lapis in Mehrgarh earlier; Mesopotamian and Egyptian use from 4th millennium BCE",
"Lapis lazuli from Sar-i Sang in Badakhshan reached Mesopotamia, Egypt and the Indus, where it was carved into beads, inlays and seals.",
"lapidary; inlay",
"beads; inlays; cylinder seals; amulets",
"exchange and value;clothing and adornment;rule and display",
"archaeologists (provenance studies)",
"",
"funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"high",
"Ur royal cemetery material is funerary.",
"canon_networks.csv"
],
[
"NET019",
"Anatolian obsidian network",
"Cappadocian obsidian exchange",
"network",
"Connections",
"F1.13;F1.9a",
"WA-ANA;WA-LEV;WA-MES",
"-12000",
"-5000",
"Epipalaeolithic to Chalcolithic; approximate",
"Obsidian from Göllü Dağ and Nenezi Dağ in Cappadocia travelled to the Levant and Cyprus as blades, cores and mirrors (Çatalhöyük).",
"pressure blade making; grinding and polishing",
"blades; mirrors; cores",
"tools;exchange and value",
"archaeologists (obsidian sourcing, Renfrew, Dixon and Cann 1960s)",
"",
"none",
"open-access excavation reports; Wikimedia Commons; Open Context (CC BY)",
"R3",
"F1.13",
"high",
"Aegean Melos obsidian (Franchthi, c.11th millennium BCE) is a parallel network.",
"canon_networks.csv"
],
[
"NET020",
"Late Bronze Age Eastern Mediterranean exchange",
"Uluburun-era trade; Amarna-age exchange",
"network",
"Connections",
"F1.13;F1.11;F1.9a;F1.6",
"EU-GRR;WA-LEV;WA-ANA;AF-EGY;AF-NUB",
"-1700",
"-1100",
"'Bronze Age' as defined for the Aegean and Near East",
"Palace and merchant trade moved copper oxhide ingots, tin, glass ingots, ebony, ivory and textiles between Egypt, Cyprus, the Levant, Anatolia and the Aegean, as shown by the Uluburun wreck.",
"oxhide ingot casting; glass ingot making",
"ingots; glass; jewellery; ivory",
"exchange and value;rule and display",
"archaeologists; Amarna letters",
"Nubian gold and ebony producers.",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET021",
"Phoenician network",
"Phoenician trade and colonies",
"network",
"Connections",
"F1.13;F1.11;F1.9a;F1.6",
"WA-LEV;EU-GRR;EU-IBE;AF-MAG",
"-1100",
"-146",
"Iron Age; to fall of Carthage 146 BCE",
"Phoenician cities and colonies carried purple-dyed cloth, carved ivory, metal bowls, glass and the alphabet across the Mediterranean to Iberia and North Africa.",
"purple dyeing; ivory carving; core-formed glass; metal chasing",
"ivories; metal bowls; glass; purple cloth",
"exchange and value;record and writing",
"Greek authors; historians",
"'Phoenician' is a Greek name; the people called themselves by city (e.g. Tyrians).",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports; Europeana",
"R2",
"F1.13;F1.5",
"high",
"",
"canon_networks.csv"
],
[
"NET022",
"Roman Mediterranean trade",
"Mare Nostrum trade",
"network",
"Connections",
"F1.13;F1.11;F1.6;F1.9a",
"EU-GRR;EU-IBE;EU-WCE;AF-EGY;AF-MAG;WA-LEV",
"-200",
"500",
"approximate",
"Roman shipping standardised amphorae, terra sigillata, marble, glass and grain across the Mediterranean and linked it to the Red Sea and India.",
"terra sigillata moulding; glassblowing; marble quarrying",
"amphorae; terra sigillata; glass; marble",
"exchange and value;food and storage;transport",
"historians; archaeologists",
"Enslaved workers produced and moved much of this trade.",
"human-flow",
"Met Open Access (CC0); Wikimedia Commons; Europeana; open-access excavation reports",
"R2",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET023",
"Medieval Mediterranean trade",
"Mediterranean trade 700–1500",
"network",
"Connections",
"F1.13;F1.11;F1.10",
"EU-GRR;EU-BYZ;EU-IBE;AF-MAG;AF-EGY;WA-LEV",
"700",
"1500",
"approximate",
"Islamic, Byzantine and Italian traders moved silks, lustreware, paper, glass, alum and sugar between the Levant, Egypt, the Maghrib, Iberia and Italy.",
"lustreware; silk weaving; paper-making",
"lustreware; silks; paper; rock crystal",
"exchange and value",
"historians (e.g. S.D. Goitein; Olivia Remie Constable)",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons; Cambridge Digital Library Taylor-Schechter Genizah (link out)",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET024",
"Venetian and Genoese trade networks",
"Venetian and Genoese colonial trade",
"network",
"Connections",
"F1.13;F1.11",
"EU-GRR;EU-BYZ;WA-ANA;EU-EER;WA-LEV",
"1082",
"1797",
"Byzantine privileges for Venice 1082; Venice falls 1797; Genoese colonies to 15th–16th c.",
"Venetian and Genoese colonies from Crete to Caffa moved silks, alum, spices and glass, and supported Murano glass and Italian silk weaving.",
"glass making; silk weaving; shipbuilding (Arsenale)",
"glass; silks; ships",
"exchange and value;transport",
"historians",
"Genoese trafficking of enslaved people via Caffa and Black Sea ports.",
"human-flow",
"Met Open Access (CC0); Rijksmuseum (public-domain images); Wikimedia Commons; Europeana",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET025",
"Amber Road",
"Baltic amber route",
"network",
"Connections",
"F1.13;F1.11",
"EU-SCA;EU-WCE;EU-EER;EU-GRR",
"-1600",
"400",
"Baltic amber in Mycenaean graves from c.1600 BCE; Roman Aquileia trade",
"Baltic amber moved south to Mycenaean Greece, Etruria and Roman Aquileia, where it was carved into beads, pendants and figures.",
"amber carving; bead drilling",
"beads; pendants; carved figures",
"exchange and value;clothing and adornment",
"archaeologists; historians",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; Europeana",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET026",
"Bronze Age tin routes",
"tin trade",
"network",
"Connections",
"F1.13;F1.11;F1.9a;F1.12a",
"EU-BLC;EU-WCE;EU-IBE;AS-CEN;WA-ANA;WA-MES",
"-2500",
"-500",
"approximate; sources and routes debated",
"Tin, needed for tin bronze, travelled long distances from sources such as Cornwall, the Erzgebirge, Iberia and Central Asia.",
"tin smelting; alloying",
"tin ingots",
"exchange and value",
"archaeometallurgists",
"Sources of Near Eastern tin remain debated.",
"none",
"open-access excavation reports; open-access journal articles; Wikimedia Commons",
"R3",
"F1.13;F1.5",
"medium",
"Check current isotope-provenance literature.",
"canon_networks.csv"
],
[
"NET027",
"Varangian route",
"route from the Varangians to the Greeks",
"network",
"Connections",
"F1.13;F1.11",
"EU-SCA;EU-EER;EU-BYZ",
"800",
"1100",
"approximate",
"Scandinavian traders moved along the Dnieper to Constantinople, exchanging furs, wax and enslaved people for silk, silver and glass.",
"boat portage; silver working",
"silks; beads; weights",
"exchange and value;transport",
"Rus' Primary Chronicle; historians",
"Slavic, Finnic and Baltic peoples along the rivers.",
"human-flow",
"Wikimedia Commons; Europeana; open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET028",
"Volga trade route",
"Volga route",
"network",
"Connections",
"F1.13;F1.11;F1.10",
"EU-SCA;EU-EER;WA-IRN;AS-CEN",
"750",
"1050",
"approximate",
"Islamic silver dirhams flowed north via the Volga for furs, wax and enslaved people, filling Scandinavian and Baltic hoards.",
"silver working; bead trade",
"dirhams; hoards; beads",
"exchange and value",
"historians; numismatists; Ibn Fadlan (921–22)",
"Volga Bulgars and Khazars as intermediaries.",
"human-flow",
"Wikimedia Commons; Europeana; open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET029",
"Hanseatic League",
"Hansa",
"network",
"Connections",
"F1.13;F1.11",
"EU-WCE;EU-SCA;EU-BLC;EU-EER",
"1159",
"1669",
"Lübeck refounded 1159; last Hanseatic diet 1669",
"A league of merchant towns ran kontore in Bergen, London, Bruges and Novgorod, moving stockfish, furs, wax, cloth and amber in cog ships.",
"cog building; brick Gothic building",
"cogs; cloth; stockfish",
"exchange and value;transport",
"member towns; historians",
"",
"none",
"Wikimedia Commons; Europeana",
"R3",
"F1.13;F1.17",
"high",
"",
"canon_networks.csv"
],
[
"NET030",
"Grand Trunk Road",
"Uttarapatha; Sadak-e-Azam; Shah Rah-e-Azam",
"network",
"Connections",
"F1.13;F1.9;F1.12a",
"AS-SAS;AS-CEN",
"-300",
"",
"Mauryan route; rebuilt by Sher Shah Suri 1540s; ongoing",
"A trunk road from Bengal to Kabul carried goods, armies and craftspeople and was punctuated by serais, kos minars and wells.",
"road building; serai construction",
"kos minars; serais",
"transport;exchange and value",
"historians; the Mughal and British states",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET031",
"Incense routes",
"Incense Road; frankincense trail",
"network",
"Connections",
"F1.13;F1.9a;F1.6",
"WA-ARB;WA-LEV;AF-HRN",
"-700",
"200",
"approximate",
"Caravans carried frankincense and myrrh from South Arabia and the Horn to the Mediterranean, funding Nabataean building at Petra and in the Negev.",
"resin harvesting; caravan trade",
"incense burners; resin",
"ritual and belief;exchange and value",
"historians; UNESCO (Incense Route – Desert Cities in the Negev, 2005)",
"Harvesters in Dhofar and Somaliland.",
"none",
"Met Open Access (CC0); Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R3",
"F1.13;F1.16",
"high",
"",
"canon_networks.csv"
],
[
"NET032",
"Red Sea network",
"Red Sea trade",
"network",
"Connections",
"F1.13;F1.6;F1.9a;F1.10",
"AF-EGY;AF-HRN;AF-NUB;WA-ARB",
"-2600",
"",
"Egyptian harbour at Wadi al-Jarf c.2600 BCE; Punt voyages; Berenike and Aksum; ongoing",
"Red Sea harbours linked Egypt, Aksum and Arabia to the Indian Ocean, carrying incense, ivory, glass, textiles and pepper.",
"boat building; glass trade",
"papyri; amphorae; Aksumite coins",
"transport;exchange and value",
"archaeologists; historians",
"",
"none",
"Wikimedia Commons; open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
],
[
"NET033",
"Cape Route and the East India companies",
"Carreira da Índia; VOC; English East India Company",
"network",
"Connections",
"F1.13;F1.11;F1.9;F1.8;F1.6",
"EU-BLC;EU-IBE;AF-SOU;AS-SAS;AS-ISE;AS-CHN;AS-JPN",
"1498",
"1874",
"da Gama 1498; VOC 1602–1799; English EIC to 1874",
"Chartered companies shipped Asian textiles, porcelain, lacquer and spices to Europe and commissioned designs for European taste.",
"pattern commissioning; export production",
"chintz; export porcelain; lacquer",
"exchange and value",
"historians; company archives",
"Company slave trading (e.g. VOC to the Cape) and colonial coercion.",
"human-flow;conflict-looting",
"Rijksmuseum (public-domain images); Met Open Access (CC0); Wikimedia Commons; British Library (public-domain digitised items)",
"R2",
"F1.13;F1.17;F1.14",
"high",
"",
"canon_networks.csv"
],
[
"NET034",
"Atlantic world trade",
"Columbian exchange; Atlantic system",
"network",
"Connections",
"F1.13;F1.7;F1.11;F1.6",
"EU-IBE;EU-BLC;AF-GUI;AF-CEN;AM-CAR;AM-LAT;AM-EWD",
"1492",
"1900",
"approximate",
"Atlantic shipping moved plants, animals, metals, dyes and manufactured goods between Europe, Africa and the Americas, reshaping materials available to makers on all three continents.",
"silver mining; dye production; plantation processing",
"silver; cochineal; textiles; ceramics",
"exchange and value;transport",
"historians (Alfred Crosby, 'The Columbian Exchange', 1972)",
"Indigenous dispossession and forced labour; enslaved Africans (see separate node).",
"human-flow",
"Met Open Access (CC0); Library of Congress (public-domain items); NYPL Digital Collections (public-domain items); Wikimedia Commons; Rijksmuseum (public-domain images)",
"R2",
"F1.13;F1.22",
"high",
"",
"canon_networks.csv"
],
[
"NET035",
"Transatlantic trafficking of enslaved Africans",
"transatlantic slave trade; triangular trade; Middle Passage",
"network",
"Connections",
"F1.13;F1.6;F1.7;F1.11",
"AF-GUI;AF-CEN;AF-SOU;AF-SWA;AF-MAD;AM-CAR;AM-LAT;AM-EWD;EU-BLC;EU-IBE",
"1525",
"1867",
"first direct Africa–Americas voyage c.1525; last documented voyage 1866–67",
"About 12.5 million African people were forcibly embarked; their knowledge of rice cultivation, indigo, ironworking, textiles, building and music shaped making across the Americas.",
"rice cultivation; indigo processing; ironwork; basketry",
"—",
"exchange and value",
"historians; SlaveVoyages database",
"People are shown as people, never as goods; content note required.",
"human-flow",
"SlaveVoyages database (free; link out); Enslaved.org (free; link out); Library of Congress (public-domain items); NYPL Digital Collections (public-domain items)",
"R1",
"F1.13;F1.23;F1.3",
"high",
"Show as movement of people with content note; figures from SlaveVoyages estimates.",
"canon_networks.csv"
],
[
"NET036",
"Manila galleon trade",
"Manila–Acapulco galleons; Nao de China",
"network",
"Connections",
"F1.13;F1.7;F1.8;F1.9",
"AS-ISE;AS-CHN;AM-LAT;AM-MES;EU-IBE",
"1565",
"1815",
"first return voyage 1565; last galleon 1815",
"Galleons carried Mexican and Peruvian silver to Manila and Chinese silk, porcelain, lacquer and ivory to Acapulco, prompting enconchado painting, Puebla talavera and biombos.",
"silver minting; export porcelain; enconchado",
"biombos; talavera; ivory santos; mantones",
"exchange and value;transport",
"historians",
"Enslaved and indentured Asians ('chinos') carried to New Spain.",
"human-flow",
"Met Open Access (CC0); LACMA (public-domain images); Wikimedia Commons; Rijksmuseum (public-domain images)",
"R1",
"F1.13;F1.14",
"high",
"",
"canon_networks.csv"
],
[
"NET037",
"Mesoamerican obsidian network",
"obsidian exchange Mesoamerica",
"network",
"Connections",
"F1.13;F1.7",
"AM-MES;AM-CAM",
"-1500",
"1521",
"Formative to Spanish conquest; approximate",
"Obsidian from sources such as Pachuca, El Chayal and Ixtepeque moved as cores and prismatic blades, supporting workshops at Teotihuacan and across the Maya region.",
"prismatic blade pressure technique; source quarrying",
"prismatic blades; eccentrics; mirrors",
"tools;exchange and value;ritual and belief",
"archaeologists (XRF sourcing)",
"",
"none",
"open-access excavation reports; Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_networks.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
