insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OBT048",
"feather cloak",
"ʻahu ʻula; kahu huruhuru",
"object-type",
"Things",
"F1.12;F1.7",
"OC-POL;AM-AND",
"",
"",
"Hawaiian cloaks documented from the 18th century; Andean feather textiles c. 600–1500 CE",
"A garment of thousands of tied feathers that displays chiefly rank.",
"olonā netting; bird feathers; cotton",
"Hawaiian ʻahu ʻula; Māori kahu huruhuru; Wari feathered panels",
"clothing and adornment;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons; community-published site",
"R2",
"F1.24;F1.17",
"high",
"The Kalaniʻōpuʻu cloak returned from Te Papa to Hawaiʻi in 2016.",
"canon_object_types.csv"
],
[
"OBT049",
"beadwork",
"beaded regalia",
"object-type",
"Things",
"THEME",
"AF-SOU;AF-SWA;AM-WST;AM-EWD;AS-ISE",
"",
"",
"Beads c. 100,000 years old; glass-bead embroidery mostly 19th–20th century",
"Garments and objects covered in threaded beads whose colours and patterns carry messages.",
"glass seed beads; shell; sinew; thread",
"Zulu beadwork (ucu); Maasai collars; Plains beaded moccasins; Métis floral beadwork",
"clothing and adornment;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;living-community",
"Smithsonian Open Access (CC0); Met Open Access (CC0); Wikimedia Commons; community-published site",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT050",
"glass trade bead",
"trade beads; chevron beads",
"object-type",
"Things",
"F1.13",
"EU-WCE;AF-GUI;AF-SAH;AM-EWD;AS-SAS",
"1490",
"",
"Venetian chevron beads from the late 15th century; Indo-Pacific drawn beads far earlier",
"Glass beads made in Venice, Bohemia, India and West Africa that circulated as value across continents.",
"drawn glass; lampwork; powder glass",
"Venetian rosetta beads; Indo-Pacific beads; Krobo powder-glass beads",
"clothing and adornment;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"human-flow",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13;F1.23",
"high",
"Tied to the Atlantic trade: show people, not goods, with a content note.",
"canon_object_types.csv"
],
[
"OBT051",
"lip plug",
"labret; lip plate; lip disc",
"object-type",
"Things",
"F1.7;F1.6",
"AM-MES;AM-NWC;AM-AMZ;AF-HRN;AM-ARC",
"",
"",
"Ancient in several regions; dates vary",
"An ornament worn in a pierced lip that marks age, rank or identity.",
"obsidian; gold; wood; stone; clay",
"Mexica gold labrets; Tlingit labrets; Mursi lip plates; Kayapó lip discs",
"clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;living-community",
"Met Open Access (CC0); Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.2",
"high",
"Tourist photography of Mursi women is exploitative; avoid.",
"canon_object_types.csv"
],
[
"OBT052",
"torc",
"torque",
"object-type",
"Things",
"F1.11",
"EU-WCE;EU-BLC;AS-CEN",
"-800",
"",
"Iron Age c. 8th–1st century BCE",
"A rigid neck ring of twisted metal worn by Iron Age elites.",
"gold; electrum; silver; twisting",
"Snettisham torcs; Broighter torc; Vix torc",
"clothing and adornment;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Europeana (per-item licence)",
"R3",
"F1.15",
"high",
"",
"canon_object_types.csv"
],
[
"OBT053",
"fibula",
"brooch; safety-pin brooch",
"object-type",
"Things",
"F1.11",
"EU-GRR;EU-WCE;EU-BLC;EU-SCA;EU-BYZ",
"-1300",
"",
"Bronze Age c. 14th century BCE onward",
"A pin-and-spring brooch that fastened cloaks and signalled regional identity.",
"bronze; silver; gold; garnet cloisonné",
"Praeneste fibula; Anglo-Saxon square-headed brooch; Viking tortoise brooch",
"clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; Europeana (per-item licence)",
"R3",
"F1.15",
"high",
"Many come from graves.",
"canon_object_types.csv"
],
[
"OBT054",
"kundan jewellery",
"kundan; jadau",
"object-type",
"Things",
"F1.9;F1.10",
"AS-SAS",
"1550",
"",
"Associated with Mughal and Rajput courts, 16th–17th century",
"Jewellery setting stones in highly refined gold foil, often backed with enamel (meenakari).",
"gold foil; uncut gems; enamel",
"Mughal jadau; Rajasthani kundan",
"clothing and adornment;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; community-published site",
"R3",
"F1.17",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT055",
"ear spool",
"ear flare",
"object-type",
"Things",
"F1.7",
"AM-AND;AM-MES",
"",
"",
"Moche and Maya elites c. 100–800 CE; start approximate",
"Discs worn in stretched earlobes that carried inlaid images of rank.",
"gold; turquoise; shell; jade",
"Moche ear ornaments (Sipán); Maya jade ear flares",
"clothing and adornment;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.15",
"high",
"Many from tombs.",
"canon_object_types.csv"
],
[
"OBT056",
"mirror",
"bronze mirror; obsidian mirror",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-JPN;AM-MES;AF-EGY;WA-ANA",
"-6000",
"",
"Çatalhöyük obsidian mirrors c. 6000 BCE",
"A polished surface for seeing oneself, also used in divination and burial.",
"obsidian; bronze; iron-ore mosaic; silvered glass",
"Çatalhöyük obsidian mirror; Han TLV mirror; Olmec iron-ore mirror; Venetian glass mirror",
"clothing and adornment;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"The Yata no Kagami itself is sacred and never shown.",
"canon_object_types.csv"
],
[
"OBT057",
"comb",
"hair comb; duafe",
"object-type",
"Things",
"THEME",
"AF-GUI;AF-EGY;EU-SCA;GL",
"-3500",
"",
"Predynastic Egyptian combs c. 3500 BCE",
"A tool for grooming and styling hair that is also a carved gift and badge of identity.",
"wood; ivory; bone; horn; plastic",
"Akan duafe; Viking antler comb; Predynastic Egyptian comb; Afro pick",
"clothing and adornment;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; Europeana (per-item licence)",
"R2",
"F1.20",
"high",
"The 1970s Afro pick is a political object.",
"canon_object_types.csv"
],
[
"OBT058",
"woven palm hat",
"toquilla hat; sombrero vueltiao; pinta'o",
"object-type",
"Things",
"F1.7",
"AM-AND;AM-CAM;AM-LAT",
"",
"",
"Toquilla hats from the 17th century; vueltiao antiquity uncertain",
"Hats plaited or braided from palm and cane fibres, among them the misnamed \"Panama\" hat made in Ecuador.",
"toquilla palm; caña flecha; plaiting",
"Ecuadorian toquilla hat; Colombian sombrero vueltiao; Panamanian pinta'o",
"clothing and adornment;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT059",
"moccasin",
"makizin",
"object-type",
"Things",
"F1.7",
"AM-EWD;AM-WST;AM-ARC",
"",
"",
"Pre-contact",
"A soft shoe of tanned hide, often decorated with quill or bead work.",
"smoked hide; porcupine quill; glass beads",
"Anishinaabe makizin; Lakota beaded moccasins",
"clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Smithsonian NMAI (link out; consult community); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT060",
"leather shoe",
"shoe",
"object-type",
"Things",
"THEME",
"WA-CAU;GL",
"-3500",
"",
"Areni-1 shoe c. 3500 BCE",
"A shaped foot covering of hide, from one-piece shoes to lasted factory footwear.",
"cowhide; lacing; lasts; rubber soles",
"Areni-1 shoe; Ötzi's shoes; Egyptian sandal; sneaker",
"clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT061",
"trousers",
"pants",
"object-type",
"Things",
"F1.12a;THEME",
"AS-CEN;GL",
"-1200",
"",
"Yanghai trousers c. 13th–10th century BCE are the earliest known",
"A two-legged garment developed by horse-riding peoples of the steppe.",
"wool; twill and tapestry weave",
"Yanghai trousers; Scythian trousers",
"clothing and adornment;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT062",
"denim jeans",
"blue jeans",
"object-type",
"Things",
"THEME",
"GL",
"1873",
"",
"Levi Strauss and Jacob Davis rivet patent 1873",
"Work trousers of indigo twill reinforced with copper rivets that became a global consumer garment.",
"cotton denim; indigo; rivets",
"Levi's 501; Japanese selvedge denim",
"clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Smithsonian Open Access (CC0)",
"R3",
"F1.21;F1.22;F1.23",
"high",
"Cotton growing and finishing labour (F1.23).",
"canon_object_types.csv"
],
[
"OBT063",
"T-shirt",
"tee",
"object-type",
"Things",
"THEME",
"GL",
"1900",
"",
"Undershirt of the early 20th century",
"A knitted cotton top that carries print, slogans and brands at mass scale.",
"cotton jersey; screen printing",
"slogan T-shirt; band T-shirt",
"clothing and adornment;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21;F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT064",
"Gulf men's dress",
"kandura; thawb; dishdasha; ghutra; bisht",
"object-type",
"Things",
"F1.10",
"WA-ARB",
"",
"",
"Modern forms 20th century; bisht older",
"A long white robe worn with a head cloth and, for occasions, a gold-edged bisht cloak.",
"cotton; camel and goat wool; zari edging",
"Emirati kandura; Saudi thawb; bisht",
"clothing and adornment;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Qatar Digital Library (open licence)",
"R3",
"F1.21",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT065",
"cosmetic palette",
"palette",
"object-type",
"Things",
"F1.6",
"AF-EGY;AF-NUB",
"-4000",
"",
"Predynastic c. 4000–3100 BCE",
"A stone slab for grinding eye paint that became a vehicle for royal imagery.",
"greywacke; siltstone; malachite; galena",
"Narmer Palette; Battlefield Palette; animal-shaped palettes",
"clothing and adornment;rule and display;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; British Museum collection online (link out)",
"R2",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT066",
"kohl container",
"mukhula; surmedani",
"object-type",
"Things",
"F1.6;F1.10;F1.9",
"AF-EGY;WA-ARB;AS-SAS;AF-MAG",
"-2000",
"",
"Egyptian kohl pots from the Middle Kingdom",
"A small pot or tube with applicator holding eye cosmetic valued also as protection for the eyes.",
"faience; glass; silver; wood; galena",
"Egyptian kohl tubes; Arabian silver mukhula; Indian surmedani",
"clothing and adornment;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT067",
"tattooing tools",
"tattoo comb; uhi; au",
"object-type",
"Things",
"F1.12;THEME",
"OC-POL;AF-EGY;GL",
"-3300",
"",
"Tattoos on Ötzi c. 3250 BCE; Polynesian bone combs from c. 2,700 years ago",
"Combs, needles and pigment for marking skin, among them Polynesian bone combs tapped with a mallet.",
"bone; turtle shell; soot pigment; mallet",
"Samoan au; Māori uhi; Tongan tattoo combs",
"clothing and adornment;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons; community-published site",
"R3",
"F1.16",
"medium",
"Tā moko and tatau are living and protected; community consent needed.",
"canon_object_types.csv"
],
[
"OBT068",
"amphora",
"amphorae; Canaanite jar",
"object-type",
"Things",
"F1.11;F1.13",
"EU-GRR;WA-LEV",
"-1500",
"",
"Canaanite jars c. 1500 BCE; Greek and Roman amphorae to c. 7th century CE",
"A two-handled transport jar for wine, oil and fish sauce whose stamps and shapes let archaeologists trace trade.",
"terracotta; stamps; pitch lining",
"Canaanite jar; Dressel 1; Dressel 20; Panathenaic amphora",
"food and storage;exchange and value;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R2",
"F1.13",
"high",
"Panathenaic amphorae were prizes.",
"canon_object_types.csv"
],
[
"OBT069",
"qvevri",
"kvevri",
"object-type",
"Things",
"F1.9a;F1.11",
"WA-CAU",
"-6000",
"",
"Wine residues in jars at Gadachrili Gora c. 6000 BCE; the qvevri form is ancient and living",
"An egg-shaped clay vessel buried in the ground for fermenting and ageing wine.",
"coiled clay; beeswax lining; burial in earth",
"Kakhetian qvevri",
"food and storage;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R1",
"F1.29",
"high",
"See practice row for Georgian qvevri wine-making (UNESCO 2013).",
"canon_object_types.csv"
],
[
"OBT070",
"celadon bowl",
"celadon; qingci",
"object-type",
"Things",
"F1.8;F1.13",
"AS-CHN;AS-KOR;AS-MSE",
"200",
"",
"Eastern Han proto-celadon; Yue and Longquan wares; Goryeo celadon 12th century",
"A stoneware bowl glazed green by iron in a reducing kiln and traded from Japan to East Africa.",
"stoneware; iron-bearing glaze; reduction firing; dragon kiln",
"Yue ware; Longquan bowls; Goryeo inlaid celadon; Sawankhalok ware",
"food and storage;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; e-museum Korea (KOGL Type 1); Wikimedia Commons",
"R2",
"F1.13;F1.14",
"high",
"Sherds reach the Swahili coast and Great Zimbabwe.",
"canon_object_types.csv"
],
[
"OBT071",
"blue-and-white jar",
"qinghua",
"object-type",
"Things",
"F1.8;F1.10;F1.13",
"AS-CHN;WA-IRN;WA-ANA;EU-BLC;AS-JPN",
"1320",
"",
"Jingdezhen c. 1320s–30s using cobalt from Iran",
"Porcelain painted in cobalt under the glaze, made in China for Islamic, European and Asian markets and copied in each.",
"kaolin porcelain; cobalt oxide; underglaze painting",
"Jingdezhen Yuan jars; Iznik ware; Delftware; Arita ware",
"food and storage;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Rijksmuseum (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R1",
"F1.13;F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT072",
"calabash",
"gourd vessel; igba; ipu",
"object-type",
"Things",
"F1.6;F1.7;F1.12",
"AF-SAH;AF-GUI;AF-SOU;AM-MES;OC-POL",
"",
"",
"Bottle gourd domesticated very early in Asia and the Americas",
"A dried gourd used as bowl, bottle, float, rattle and resonator, often pyro-engraved.",
"Lagenaria gourd; pyro-engraving; carving",
"Fulani engraved calabash; Hawaiian ipu; Yoruba igba",
"food and storage;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT073",
"olla",
"water jar",
"object-type",
"Things",
"F1.7",
"AM-WST;AM-MES;AM-LAT",
"",
"",
"Ancient; dates vary",
"A porous earthenware jar that cools water and stores grain.",
"coiled clay; slip; open firing",
"Acoma olla; Zuni water jar; Mata Ortiz jar",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;living-community",
"Smithsonian Open Access (CC0); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT074",
"stirrup-spout vessel",
"stirrup-spout bottle",
"object-type",
"Things",
"F1.7",
"AM-AND",
"-1500",
"",
"Cupisnique c. 1500 BCE; Moche c. 100–800 CE; Chimú later",
"A bottle with a hollow looped handle-spout that Andean potters moulded into portraits, animals and scenes.",
"mould-made earthenware; slip painting",
"Moche portrait vessels; Chimú blackware; Cupisnique bottles",
"food and storage;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; Art Institute of Chicago (CC0)",
"R2",
"F1.16;F1.24",
"medium",
"Many looted from graves.",
"canon_object_types.csv"
],
[
"OBT075",
"kero",
"qiru; qero",
"object-type",
"Things",
"F1.7",
"AM-AND",
"600",
"",
"Wari and Tiwanaku c. 600–1000 CE; Inka and colonial painted keros",
"A drinking cup for chicha made in pairs and shared in toasts that sealed alliances.",
"wood; ceramic; gold; mopa-mopa resin inlay",
"Tiwanaku ceramic kero; Inka wooden kero; colonial painted keros",
"food and storage;ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT076",
"pithos",
"pithoi",
"object-type",
"Things",
"F1.11",
"EU-GRR",
"-1800",
"",
"Minoan pithoi from c. 1800 BCE",
"A large storage jar for grain, oil and wine used in palace magazines and houses.",
"coiled terracotta; rope-pattern decoration",
"Knossos magazine pithoi",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT077",
"grinding stone",
"quern; saddle quern; rotary quern",
"object-type",
"Things",
"THEME",
"GL",
"-30000",
"",
"Seed grinding at Cuddie Springs (Australia) and Upper Palaeolithic Europe c. 30,000 BP",
"A pair of stones for grinding seed and grain into flour.",
"basalt; sandstone; granite",
"saddle quern; rotary quern; Aboriginal seed grindstone",
"food and storage;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.18;F1.23",
"medium",
"Women's grinding labour is often invisible in displays.",
"canon_object_types.csv"
],
[
"OBT078",
"metate and mano",
"metlatl",
"object-type",
"Things",
"F1.7",
"AM-MES;AM-CAM",
"",
"",
"Ancient; tied to maize processing",
"A three-legged grinding slab and hand stone for maize dough.",
"basalt; carving",
"Costa Rican ceremonial metates; Mexica metate",
"food and storage;tools;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT079",
"mortar and pestle",
"usu; kine; odo",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A hollow vessel and pounder for hulling grain, crushing spice and preparing medicine.",
"wood; stone; bronze",
"West African wooden mortar; Japanese usu; Thai krok",
"food and storage;tools;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT080",
"wok",
"guo",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-MSE",
"",
"",
"Origins uncertain",
"A round-bottomed pan for fast stir-frying over high heat.",
"cast iron; hand-hammered carbon steel",
"Cantonese wok; hand-hammered wok",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.22a",
"low",
"Early dating claims (Han) need checking.",
"canon_object_types.csv"
],
[
"OBT081",
"tagine",
"tajine",
"object-type",
"Things",
"F1.6;F1.10",
"AF-MAG",
"",
"",
"Origins uncertain",
"An earthenware dish with a conical lid that returns steam to slow-cooked food.",
"earthenware; glaze",
"Safi tagine; unglazed Amazigh tagine",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"low",
"",
"canon_object_types.csv"
],
[
"OBT082",
"tea bowl",
"chawan",
"object-type",
"Things",
"F1.8",
"AS-JPN;AS-CHN;AS-KOR",
"1000",
"",
"Jian ware of the Song c. 11th–13th century; Japanese raku from the 16th century",
"A bowl for whisked tea whose valued irregularities became a theory of making.",
"stoneware; tenmoku glaze; raku firing",
"Jian tea bowl; Ido chawan (Korean); Raku chawan",
"food and storage;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"ColBase (Japan Government Standard Terms); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R1",
"F1.14;F1.2",
"high",
"Korean Ido bowls were everyday rice bowls re-valued in Japan (F1.2).",
"canon_object_types.csv"
],
[
"OBT083",
"chopsticks",
"kuaizi; hashi; jeotgarak",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-JPN;AS-KOR;AS-MSE",
"",
"",
"Bronze chopsticks reported from Shang Yinxu; dating needs checking",
"A pair of sticks for cooking and eating used across East Asia.",
"bamboo; lacquered wood; metal; plastic",
"Korean metal jeotgarak; lacquered hashi",
"food and storage;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT084",
"granary",
"grain store; raised granary",
"object-type",
"Things",
"THEME",
"AF-SAH;AS-ISE;AF-SOU",
"",
"",
"Ancient",
"A raised or sealed store for grain protected from damp, pests and theft.",
"mud; thatch; timber; basketry",
"Dogon granaries; Minangkabau rangkiang; Zulu isiphala",
"food and storage;shelter",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"Check local terms before publishing.",
"canon_object_types.csv"
],
[
"OBT085",
"basket",
"coiled basket; twined basket",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Very ancient; survives rarely",
"A container woven from plant fibre, the most widespread and least preserved of vessels.",
"coiling; twining; plaiting; grass; willow; palm",
"Pomo baskets; Rwandan agaseke; Gullah sweetgrass baskets; Japanese bamboo baskets",
"food and storage;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community;Indigenous-community",
"Smithsonian Open Access (CC0); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT086",
"bentwood box",
"kerfed box",
"object-type",
"Things",
"F1.7",
"AM-NWC",
"",
"",
"Pre-contact",
"A box made from one cedar plank steamed and bent at kerfed corners, used for storage, cooking and burial.",
"red cedar; steam bending; kerfing; painting",
"Haida bentwood chest; Tlingit box",
"food and storage;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons; community-published site",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT087",
"coffee pot",
"dallah; jebena; cezve",
"object-type",
"Things",
"F1.10;F1.6",
"WA-ARB;AF-HRN;WA-ANA",
"1500",
"",
"Coffee drinking from 15th-century Yemen; pot forms later",
"Pots for brewing and serving coffee that carry hospitality from Yemen to the Gulf, Ethiopia and Anatolia.",
"brass; copper; clay",
"Gulf dallah; Ethiopian jebena; Ottoman cezve",
"food and storage;ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; UNESCO ICH lists (link out; per-item photo licence)",
"R2",
"F1.13",
"medium",
"UNESCO: Arabic coffee (2015); Turkish coffee (2013).",
"canon_object_types.csv"
],
[
"OBT088",
"samovar",
"samovar",
"object-type",
"Things",
"F1.11;F1.12a",
"EU-EER;WA-IRN;AS-CEN",
"1740",
"",
"Tula manufacture from the 18th century",
"A heated urn for boiling water for tea at the centre of household hospitality.",
"brass; copper; charcoal chimney",
"Tula samovar; Iranian samovar",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT089",
"clay oven",
"tannur; tandoor; tonir",
"object-type",
"Things",
"THEME",
"WA-MES;AS-SAS;WA-CAU;AS-CEN;WA-ARB",
"",
"",
"Ancient; clay ovens at Mesopotamian and Harappan sites",
"A cylindrical clay oven in which flatbread is slapped against the hot wall.",
"clay; straw temper; charcoal",
"tandoor; tonir; tannour",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; UNESCO ICH lists (link out; per-item photo licence)",
"R3",
"F1.18",
"medium",
"Links to lavash and flatbread practice rows.",
"canon_object_types.csv"
],
[
"OBT090",
"earth oven",
"umu; hāngī; lovo; imu",
"object-type",
"Things",
"F1.12",
"OC-POL;OC-MEL",
"",
"",
"Ancient",
"A pit of heated stones for steaming food under leaves and earth.",
"volcanic stones; banana leaves; earth",
"Samoan umu; Māori hāngī; Fijian lovo",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT091",
"kava bowl",
"tanoa; ʻumete; kumete",
"object-type",
"Things",
"F1.12",
"OC-POL;OC-MEL",
"",
"",
"Pre-contact",
"A multi-legged wooden bowl for preparing kava at ceremonies.",
"vesi or ifilele wood; sennit",
"Fijian tanoa; Samoan ʻumete; Tongan kumete",
"food and storage;ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT092",
"beer pot",
"ukhamba",
"object-type",
"Things",
"F1.6",
"AF-SOU",
"",
"",
"Ancient and living",
"A burnished earthenware pot for serving sorghum beer.",
"coiled clay; burnishing; smoke firing",
"Zulu ukhamba; Venda pots",
"food and storage;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT093",
"martaban jar",
"dragon jar; tempayan; tajau",
"object-type",
"Things",
"F1.13;F1.9",
"AS-MSE;AS-ISE;AS-CHN",
"1300",
"",
"Trade jars c. 13th–19th century",
"Large glazed stoneware jars made in China and mainland Southeast Asia that became heirlooms in Borneo and the Philippines.",
"stoneware; brown glaze; applied dragons",
"Martaban jars; Dayak heirloom jars (tajau)",
"food and storage;exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT094",
"tin can",
"canister",
"object-type",
"Things",
"THEME",
"GL",
"1810",
"",
"Durand patent 1810; Donkin factory 1813",
"A sealed metal container that let food be stored for years and moved across oceans and wars.",
"tinplate; soldering; seaming",
"Donkin can; Campbell's soup can; ring-pull can",
"food and storage;war;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.19;F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT095",
"refrigerator",
"fridge",
"object-type",
"Things",
"THEME",
"GL",
"1913",
"",
"Domestic electric refrigerators from the 1910s",
"A cooled cabinet that reorganised shopping, kitchens and supply chains.",
"compressor; refrigerant; enamelled steel",
"Domelre (1913); GE Monitor Top",
"food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.21;F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT096",
"packaging",
"packet; container; wrapper",
"object-type",
"Things",
"THEME",
"GL",
"1850",
"",
"Printed branded packaging from the 19th century",
"Printed containers that carry goods, brand and instructions, now a central waste problem.",
"paperboard; tinplate; plastic; aluminium; print",
"Huntley and Palmers biscuit tin; Tetra Pak; PET bottle",
"food and storage;exchange and value;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.21;F1.22",
"high",
"",
"canon_object_types.csv"
],
[
"OBT097",
"bronze ritual vessel",
"ding; gui; zun",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-1700",
"",
"Erlitou and Erligang c. 1700–1300 BCE; Shang and Zhou",
"Cast bronze vessels for food and wine offerings to ancestors, some bearing long inscriptions.",
"piece-mould bronze casting; inscriptions",
"Houmuwu ding; Mao Gong ding; Shang gu",
"food and storage;ritual and belief;rule and display;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary;ancestral",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; Art Institute of Chicago (CC0); Wikimedia Commons",
"R1",
"F1.16;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT098",
"fish trap",
"weir; eel trap; kooyang trap; ngunnhu",
"object-type",
"Things",
"THEME",
"OC-AUS;AF-SWA;AS-MSE;EU-SCA",
"-4600",
"",
"Budj Bim channels dated to c. 6,600 years ago",
"Channels, weirs and woven traps that catch and hold fish.",
"stone channels; woven basketry; wooden stakes",
"Budj Bim eel traps; Brewarrina fish traps (Ngunnhu); Swahili fence traps",
"food and storage;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.22",
"medium",
"Link to Budj Bim practice row.",
"canon_object_types.csv"
],
[
"OBT099",
"hand axe",
"biface; Acheulean hand axe",
"object-type",
"Things",
"THEME",
"AF-SWA;AF-HRN;GL",
"-1760000",
"",
"Kokiselei (Kenya) c. 1.76 million years ago",
"A symmetrical, bifacially flaked stone tool made for over a million years across Africa and Eurasia.",
"flint; quartzite; obsidian; knapping",
"Kokiselei bifaces; Olorgesailie; Boxgrove",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports; Met Open Access (CC0)",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT100",
"obsidian blade",
"prismatic blade",
"object-type",
"Things",
"THEME",
"AM-MES;WA-ANA;OC-MEL",
"",
"",
"Varies",
"Razor-sharp blades pressure-flaked from obsidian cores and traded over long distances.",
"obsidian; pressure flaking",
"Teotihuacan prismatic blades; Çatalhöyük blades; Talasea (New Britain) obsidian",
"tools;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT101",
"adze",
"toki; koʻi; elbow adze",
"object-type",
"Things",
"THEME",
"OC-POL;OC-MEL;AM-NWC;GL",
"",
"",
"Ancient",
"A blade set at right angles to its handle for shaping wood, key to canoe and house building.",
"basalt; pounamu; iron; hafting",
"Hawaiian koʻi; Māori toki; NWC elbow adze",
"tools;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); Wikimedia Commons",
"R2",
"F1.29",
"high",
"Ceremonial toki poutangata are regalia.",
"canon_object_types.csv"
],
[
"OBT102",
"ground-stone axe",
"edge-ground axe; polished axe",
"object-type",
"Things",
"THEME",
"OC-AUS;EU-WCE;EU-BLC",
"-44000",
"",
"Edge-ground axes in northern Australia c. 44,000–49,000 BP",
"An axe whose edge is ground and polished rather than only flaked.",
"basalt; jadeitite; greenstone; grinding",
"Carpenter's Gap axe fragment; Alpine jadeitite axes; Langdale axes",
"tools;exchange and value;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT103",
"eyed needle",
"bone needle",
"object-type",
"Things",
"THEME",
"AS-NTH;EU-WCE;AS-CHN",
"-40000",
"",
"Strashnaya Cave c. 44–49 ka; a Denisova Cave claim of c. 50 ka rests on one radiocarbon date; many c. 40,000–20,000 BP",
"A pointed tool with an eye that allowed fitted, layered clothing.",
"bone; ivory; bronze; steel",
"Denisova needle; Solutrean needles; Xiaogushan needles",
"tools;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT104",
"spindle and whorl",
"drop spindle; takli; pushka",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Whorls from the Neolithic; dates vary",
"A stick weighted by a whorl for twisting fibre into thread, the most persistent tool of textile labour.",
"wood; clay whorls; stone",
"Andean pushka; Anatolian spindle whorls; Indian takli",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.18;F1.23",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT105",
"backstrap loom",
"body-tensioned loom",
"object-type",
"Things",
"THEME",
"AM-MES;AM-AND;AS-MSE;AS-ISE;OC-MIC",
"",
"",
"Ancient; independent in the Americas and Asia",
"A loom tensioned by the weaver's body, portable and capable of complex warp patterns.",
"sticks; backstrap; warp",
"Maya backstrap loom; Andean backstrap loom; Atayal loom (Taiwan)",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;living-community",
"Smithsonian Open Access (CC0); Met Open Access (CC0); Wikimedia Commons",
"R1",
"F1.18;F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT106",
"warp-weighted loom",
"upright loom",
"object-type",
"Things",
"F1.11",
"EU-WCE;EU-GRR;EU-SCA;WA-ANA",
"-6000",
"",
"Loom weights from Neolithic Anatolia and Europe; start approximate",
"An upright loom whose warps are tensioned by hanging clay or stone weights.",
"loom weights; timber frame",
"Greek warp-weighted loom; Norse vertical loom",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT107",
"treadle loom",
"pit loom; frame loom",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-SAS;AF-SAH;EU-WCE",
"",
"",
"China by the Han; Europe by the 11th century; West African narrow loom",
"A frame loom whose sheds are opened by foot pedals, freeing the hands to throw the shuttle.",
"heddles; treadles; shuttle",
"Indian pit loom; West African narrow-strip loom; European treadle loom",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.18;F1.19",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT108",
"drawloom",
"figure-harness loom",
"object-type",
"Things",
"F1.8;F1.10;F1.13",
"AS-CHN;WA-IRN;EU-WCE",
"-150",
"",
"Laoguanshan pattern-loom models c. 2nd century BCE",
"A loom with a harness raised by a draw-boy that repeats complex figured patterns.",
"harness; pattern cords; silk",
"Han pattern loom; Yunjin brocade loom; Lyon drawloom",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R2",
"F1.13;F1.19",
"medium",
"Whether the Laoguanshan models count as drawlooms is debated.",
"canon_object_types.csv"
],
[
"OBT109",
"Jacquard loom",
"Jacquard mechanism",
"object-type",
"Things",
"F1.11",
"EU-WCE",
"1804",
"",
"Joseph-Marie Jacquard, Lyon, 1804",
"A loom mechanism controlled by punched cards, a precursor of programmed machines.",
"punched cards; hooks; silk",
"woven silk portrait of Jacquard; Spitalfields and Lyon Jacquard silks",
"tools;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT110",
"potter's wheel",
"tournette; kick wheel",
"object-type",
"Things",
"THEME",
"WA-MES;AS-CHN;AS-SAS;GL",
"-4500",
"",
"Slow wheel (tournette) in Ubaid Mesopotamia; fast wheel later",
"A turning platform on which clay is shaped, first slowly and then at speed.",
"stone or wood wheel; pivot; kick or stick drive",
"Ubaid tournette; Longshan wheel-made ware; Japanese kick wheel",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT111",
"bellows",
"bag bellows; bowl bellows; piston bellows",
"object-type",
"Things",
"THEME",
"AF-SAH;AF-GUI;AS-CHN;AS-ISE",
"",
"",
"Ancient",
"A device that drives air into furnaces and forges, essential to smelting.",
"goatskin; clay tuyères; wood; bamboo",
"African bowl bellows; Malay piston bellows; Chinese box bellows",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT112",
"ard",
"scratch plough; maresha",
"object-type",
"Things",
"THEME",
"WA-MES;AF-HRN;AS-SAS;EU-WCE",
"-4000",
"",
"Ard marks and depictions from the 4th millennium BCE",
"A plough that scratches the soil, pulled by oxen, reshaping farming and labour.",
"wood; iron share; yoke",
"Ethiopian maresha; Mesopotamian seeder plough; Døstrup ard",
"tools;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT113",
"digging stick",
"chakitaqlla; ʻōʻō",
"object-type",
"Things",
"THEME",
"OC-POL;AM-AND;AF-SOU;OC-AUS",
"",
"",
"Ancient",
"A pointed stick for digging roots and planting, in the Andes fitted with a foot rest.",
"hardwood; bored stone weight; foot rest",
"Andean chakitaqlla; San digging stick with bored stone",
"tools;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT114",
"fishhook",
"makau; matau",
"object-type",
"Things",
"F1.12;THEME",
"OC-POL;AS-JPN;OC-MEL;AM-NWC",
"-21000",
"",
"Sakitari Cave (Okinawa) shell hooks c. 23,000 BP",
"Hooks carved from shell, bone, stone and wood matched to species and waters.",
"shell; bone; pearl shell; wood",
"Sakitari hooks; Hawaiian makau; Māori matau; NWC halibut hook",
"tools;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT115",
"toggling harpoon",
"unaaq",
"object-type",
"Things",
"F1.7",
"AM-ARC;AS-NTH",
"",
"",
"Palaeo-Inuit and Thule; ancient",
"A harpoon head that turns sideways in the animal, used for seals and whales.",
"ivory; antler; slate; sinew",
"Thule harpoon heads; Yupik harpoons",
"tools;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT116",
"ulu",
"woman's knife",
"object-type",
"Things",
"F1.7",
"AM-ARC",
"",
"",
"Ancient",
"A crescent knife used by Inuit women to cut skin, food and snow.",
"slate; steel; bone or wood handle",
"Inuit ulu; Yupik uluaq",
"tools;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT117",
"kiln",
"dragon kiln; anagama; noborigama",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-KOR;AS-JPN;WA-MES",
"",
"",
"Kilns from the 6th millennium BCE; dragon kilns by the Warring States",
"A chamber for firing clay; East Asian climbing kilns reached the heat for stoneware and porcelain.",
"brick; clay; wood fuel",
"Longquan dragon kilns; Jingdezhen egg-shaped kiln; Korean onggi kiln",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.19",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT118",
"crucible",
"crucible",
"object-type",
"Things",
"THEME",
"WA-IRN;AS-SAS;AF-SAH;GL",
"-5000",
"",
"Tal-i Iblis crucibles c. 5th millennium BCE",
"A heat-proof vessel for melting metal or glass.",
"refractory clay; graphite",
"Tal-i Iblis crucibles; South Asian crucible-steel crucibles",
"tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT119",
"boomerang",
"kylie; returning boomerang",
"object-type",
"Things",
"F1.12",
"OC-AUS",
"-8000",
"",
"Wyrie Swamp examples c. 10,000 BP; an older mammoth-ivory object from Obłazowa Cave (Poland)",
"A curved throwing stick for hunting, digging, music and fighting; only some return.",
"mulga; hardwood; incised decoration",
"Wyrie Swamp boomerangs; clapping boomerangs",
"tools;war;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.29;F1.2",
"medium",
"Souvenir boomerangs are an appropriation case (F1.2).",
"canon_object_types.csv"
],
[
"OBT120",
"sewing machine",
"lockstitch machine",
"object-type",
"Things",
"THEME",
"GL",
"1846",
"",
"Howe 1846; Singer 1851",
"A machine that sews lockstitch, spreading factory garment work and home dressmaking.",
"cast iron; needle; shuttle",
"Singer treadle; Butterfly (China); Usha (India)",
"tools;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Smithsonian Open Access (CC0); Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19;F1.23",
"high",
"",
"canon_object_types.csv"
],
[
"OBT121",
"typewriter",
"typewriter",
"object-type",
"Things",
"THEME",
"GL",
"1874",
"",
"Sholes and Glidden 1874",
"A machine for typing text that reorganised office labour and writing systems.",
"steel; keys; type bars",
"Sholes and Glidden; Olivetti Lettera 22; Chinese typewriter (Double Pigeon)",
"record and writing;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0); Smithsonian Open Access (CC0)",
"R2",
"F1.19;F1.23",
"high",
"",
"canon_object_types.csv"
],
[
"OBT122",
"machete",
"cutlass; panga; bolo",
"object-type",
"Things",
"THEME",
"AM-CAR;AM-LAT;AF-GUI;AS-ISE",
"",
"",
"Colonial era; industrial production 19th century",
"A long knife for clearing growth and cutting cane, made in industrial quantities.",
"steel; wood",
"Collins machete; Filipino bolo; panga",
"tools;war",
"museum and archaeological typology; makers' own terms where known",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23",
"medium",
"Plantation labour context.",
"canon_object_types.csv"
],
[
"OBT123",
"clay tablet",
"tablet",
"object-type",
"Things",
"F1.9a",
"WA-MES;WA-IRN;WA-ANA;WA-LEV",
"-3300",
"",
"Uruk proto-cuneiform c. 3300 BCE",
"A tablet of clay impressed with a stylus that carried accounts, letters, laws and literature for three millennia.",
"clay; reed stylus; firing (sometimes)",
"Uruk proto-cuneiform tablets; Amarna letters; Old Babylonian school tablets",
"record and writing;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.5;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT124",
"counting token and bulla",
"token; bulla",
"object-type",
"Things",
"F1.9a",
"WA-MES;WA-IRN;WA-LEV",
"-8000",
"",
"Tokens from c. 8000 BCE; sealed bullae c. 3500 BCE",
"Small clay shapes that counted goods, later sealed in clay envelopes; a proposed route to writing.",
"clay; impression",
"Susa bullae; Uruk tokens",
"record and writing;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.5;F1.3",
"medium",
"Schmandt-Besserat's token-to-writing thesis is debated.",
"canon_object_types.csv"
],
[
"OBT125",
"cylinder seal",
"cylinder seal",
"object-type",
"Things",
"F1.9a",
"WA-MES;WA-IRN;WA-LEV;WA-ANA",
"-3500",
"",
"Uruk period c. 3500 BCE to Achaemenid times",
"A carved stone cylinder rolled on clay to mark ownership and authority with a repeatable image.",
"stone; lapis lazuli; carving; drill",
"Uruk seals; Akkadian seals; Achaemenid seals",
"record and writing;rule and display;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R1",
"F1.14;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT126",
"stamp seal",
"Indus seal; Dilmun seal",
"object-type",
"Things",
"F1.9a;F1.9",
"WA-ANA;WA-MES;AS-SAS;WA-ARB",
"-6000",
"",
"Near Eastern stamp seals c. 6th millennium BCE; Indus seals c. 2600–1900 BCE; Dilmun seals c. 2000 BCE",
"A carved stamp pressed into clay or sealing to mark goods and authority.",
"steatite; stone; clay",
"Indus unicorn seals; Dilmun seals (Bahrain, Failaka); Halaf stamp seals",
"record and writing;exchange and value;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.13;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT127",
"papyrus scroll",
"papyrus",
"object-type",
"Things",
"F1.6",
"AF-EGY",
"-2560",
"",
"Wadi al-Jarf papyri c. 2560 BCE are the oldest inscribed",
"A roll of sheets laminated from papyrus pith, the writing support of Egypt and the Mediterranean.",
"Cyperus papyrus; carbon ink; reed pen",
"Diary of Merer; Book of the Dead of Hunefer; Oxyrhynchus papyri",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT128",
"palm-leaf manuscript",
"olai; lontar",
"object-type",
"Things",
"F1.9",
"AS-SAS;AS-MSE;AS-ISE;AS-HIM",
"",
"",
"Oldest surviving c. 9th–12th century; use far older",
"Leaves of talipot or palmyra palm incised or inked and strung between boards.",
"palm leaf; stylus incision; lamp black; boards",
"Tamil olai; Balinese lontar; Nepalese Buddhist manuscripts",
"record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons; Library of Congress (PD items); community-published site",
"R2",
"F1.28",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT129",
"bark-paper screenfold book",
"amate codex; huun",
"object-type",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Pre-Hispanic; surviving codices c. 13th–16th century",
"A long strip of bark paper or deer hide coated with lime gesso, painted and folded like a screen.",
"amate bark paper; deerskin; lime gesso; mineral and organic pigments",
"Dresden Codex; Codex Borgia; Codex Zouche-Nuttall; Codex Mendoza (colonial)",
"record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons; Wikidata",
"R1",
"F1.28;F1.24",
"high",
"Most surviving codices are in European collections.",
"canon_object_types.csv"
],
[
"OBT130",
"bamboo and wooden slips",
"jiandu",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-400",
"",
"Warring States to Jin, c. 5th century BCE–4th century CE",
"Strips of bamboo or wood written with brush and ink and bound with cord into rolls.",
"bamboo; wood; ink; cord",
"Guodian slips; Shuihudi Qin slips; Juyan Han slips",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.28;F1.24",
"high",
"Many looted slips circulate on the market; check provenance.",
"canon_object_types.csv"
],
[
"OBT131",
"handscroll",
"juan; emaki",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-JPN;AS-KOR",
"",
"",
"Han onward",
"A horizontal scroll unrolled section by section, carrying text and continuous painting.",
"silk; paper; mounting",
"Admonitions Scroll; Along the River During the Qingming Festival; Genji Monogatari Emaki",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"National Palace Museum Taipei Open Data; ColBase (Japan Government Standard Terms); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT132",
"codex",
"bound book",
"object-type",
"Things",
"F1.11;F1.10;F1.6",
"EU-GRR;EU-BYZ;AF-HRN;WA-LEV",
"100",
"",
"Roman codices 1st–2nd century CE; dominant by the 4th century",
"Pages bound at one edge, which replaced the scroll in the Mediterranean and Islamic worlds.",
"parchment; papyrus; paper; sewing; boards",
"Codex Sinaiticus; Garima Gospels; Blue Qur'an",
"record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons; Qatar Digital Library (open licence); Walters Art Museum (CC0)",
"R1",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT133",
"printed book",
"printed book",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-KOR;EU-WCE;GL",
"868",
"",
"Diamond Sutra 868 CE is the earliest dated printed book",
"A book produced by printing, first from woodblocks in East Asia and later from movable type everywhere.",
"woodblock; movable type; paper; ink",
"Diamond Sutra; Jikji; Gutenberg Bible; Nuremberg Chronicle",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Library of Congress (PD items); Wikimedia Commons; Europeana (per-item licence); Internet Archive (PD scans)",
"R1",
"F1.5;F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT134",
"newspaper",
"gazette",
"object-type",
"Things",
"THEME",
"GL",
"1605",
"",
"Relation (Strasbourg) 1605 often called the first; Chinese court gazettes (dibao) earlier",
"A periodical of news printed on cheap paper for a paying public.",
"newsprint; rotary press; halftone",
"Relation; Peking Gazette; al-Waqa'i' al-Misriyya",
"record and writing;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Library of Congress (PD items); Wikimedia Commons; Internet Archive (PD scans)",
"R2",
"F1.21;F1.28",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT135",
"poster",
"affiche",
"object-type",
"Things",
"THEME",
"GL",
"1866",
"",
"Colour lithographic posters from the 1860s",
"A printed sheet for public walls that carries advertising, politics and events.",
"lithography; screen print; offset",
"Chéret posters; Soviet constructivist posters; OSPAAAL posters",
"record and writing;rule and display;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Library of Congress (PD items); Wikimedia Commons; Europeana (per-item licence)",
"R2",
"F1.20;F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT136",
"screen",
"display",
"object-type",
"Things",
"THEME",
"GL",
"1930",
"",
"Television screens from the 1930s; LCD and OLED later",
"A lit surface displaying changing text and images, now the main surface of reading.",
"cathode-ray tube; LCD; OLED; glass",
"television set; computer monitor; phone screen",
"record and writing;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT137",
"smartphone",
"mobile phone",
"object-type",
"Things",
"THEME",
"GL",
"2007",
"",
"iPhone (2007) widely taken as the start; earlier smartphones from 1994 (IBM Simon)",
"A pocket computer and screen whose materials are mined, assembled and discarded across the globe.",
"lithium; cobalt; rare earths; glass; software",
"IBM Simon; iPhone; Android phones",
"record and writing;exchange and value;care and access;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.21;F1.22;F1.23",
"high",
"Cobalt and coltan mining (DRC) and assembly labour belong in F1.22–F1.23; accessibility features belong in care and access.",
"canon_object_types.csv"
],
[
"OBT138",
"personal computer",
"microcomputer",
"object-type",
"Things",
"THEME",
"GL",
"1965",
"",
"Olivetti Programma 101 (1965); microcomputers 1970s",
"A general-purpose programmable machine that became a design, writing and play tool.",
"silicon chips; plastics; screens",
"Olivetti Programma 101; Apple II; IBM PC; Macintosh",
"record and writing;tools;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Smithsonian Open Access (CC0)",
"R2",
"F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT139",
"khipu",
"quipu",
"object-type",
"Things",
"F1.7",
"AM-AND",
"600",
"",
"Wari khipus c. 600–1000 CE; Inka khipus to the 16th century; kept in some communities into the 20th century",
"Knotted cords of cotton or camelid fibre recording numbers and possibly narrative.",
"cotton; camelid fibre; knotting; dyes",
"Inka khipus; Wari khipus; Rapaz patrimonial khipus",
"record and writing;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R1",
"F1.5;F1.28;F1.29",
"high",
"Whether khipu encode language is debated.",
"canon_object_types.csv"
],
[
"OBT140",
"tally stick",
"tally; split tally",
"object-type",
"Things",
"THEME",
"EU-BLC;AF-SOU;AF-CEN;GL",
"-42000",
"",
"Lebombo bone c. 44,000–43,000 BP (interpretation contested); English Exchequer tallies to 1826",
"A notched stick or bone recording a count or debt, split so each party holds half.",
"hazel; bone; notching",
"Lebombo bone; Ishango bone; English Exchequer tallies",
"record and writing;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R2",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT141",
"stick chart",
"mattang; meddo; rebbelib",
"object-type",
"Things",
"F1.12",
"OC-MIC",
"",
"",
"Documented from the late 19th century; practice older",
"A frame of sticks and shells modelling ocean swells around atolls, memorised before a voyage.",
"coconut midrib; pandanus; shells; lashing",
"mattang; meddo; rebbelib",
"record and writing;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; Smithsonian Open Access (CC0); community-published site",
"R1",
"F1.29",
"high",
"Marshall Islands; teaching and memory tools, not carried at sea.",
"canon_object_types.csv"
],
[
"OBT142",
"map",
"chart",
"object-type",
"Things",
"THEME",
"GL",
"-1500",
"",
"Nippur city plan on a clay tablet c. 1500–1300 BCE; Babylonian Map of the World c. 600 BCE; Mawangdui maps 168 BCE; older candidates contested",
"A drawn model of territory, route or cosmos that serves travel, rule and belief.",
"clay; silk; paper; print",
"Babylonian Map of the World; Mawangdui maps; Tabula Rogeriana; Kangnido",
"record and writing;rule and display;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Library of Congress (PD items); Wikimedia Commons; Qatar Digital Library (open licence); Europeana (per-item licence)",
"R1",
"F1.13;F1.3",
"high",
"",
"canon_object_types.csv"
],
[
"OBT143",
"portolan chart",
"portolan",
"object-type",
"Things",
"F1.11;F1.10",
"EU-IBE;EU-GRR;AF-MAG",
"1275",
"",
"Carta Pisana c. 1275",
"A sea chart on vellum laid out with rhumb lines and names of coastal places.",
"vellum; ink; rhumb lines",
"Carta Pisana; Catalan Atlas; Piri Reis map",
"record and writing;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items); Europeana (per-item licence)",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT144",
"astrolabe",
"asturlab",
"object-type",
"Things",
"F1.10;F1.11",
"WA-IRN;WA-MES;EU-IBE;AF-MAG",
"927",
"",
"Oldest surviving by Nastulus, 927–8 CE; Greek theory earlier",
"A brass model of the sky for telling time, finding prayer direction and surveying.",
"brass; engraving; plates",
"Nastulus astrolabe; Toledo astrolabes; Safavid astrolabes; mariner's astrolabe",
"tools;record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0); Science Museum Group collection (link out; data CC0)",
"R1",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT145",
"sundial",
"shadow clock; gnomon",
"object-type",
"Things",
"THEME",
"AF-EGY;EU-GRR;AS-KOR;AS-SAS",
"-1500",
"",
"Egyptian shadow clocks c. 1500 BCE",
"A device reading time from a shadow.",
"stone; bronze",
"Egyptian shadow clock; Korean angbu ilgu; Jantar Mantar Samrat Yantra",
"record and writing;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; e-museum Korea (KOGL Type 1)",
"R2",
"F1.30",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT146",
"clock",
"mechanical clock",
"object-type",
"Things",
"THEME",
"AS-CHN;EU-WCE;GL",
"1088",
"",
"Su Song's astronomical clock tower 1088; European weight-driven clocks c. 1300",
"A machine that divides time mechanically.",
"escapement; gears; weights; springs",
"Su Song clock tower; Salisbury Cathedral clock; Japanese wadokei",
"record and writing;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.30;F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT147",
"inscribed stela",
"stele",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Varies",
"A standing stone carrying text and image made to last in public.",
"stone carving",
"Code of Hammurabi; Maya stelae; Xi'an Stele; Rosetta Stone",
"record and writing;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT148",
"oracle bone",
"jiaguwen",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-1250",
"",
"Late Shang c. 1250–1046 BCE",
"Ox scapulae and turtle plastrons heated to crack for divination and inscribed with the questions.",
"bone; turtle shell; heat; incision",
"Anyang oracle bones",
"record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT149",
"lukasa",
"memory board",
"object-type",
"Things",
"F1.6",
"AF-CEN",
"",
"",
"Collected 19th–20th century; practice older",
"A hand-held board studded with beads and shells used by Luba Mbudye experts to recall history.",
"wood; beads; shells",
"Luba lukasa",
"record and writing;ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); British Museum collection online (link out); Wikimedia Commons",
"R2",
"F1.29;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT150",
"winter count",
"waniyetu wowapi",
"object-type",
"Things",
"F1.7",
"AM-WST",
"",
"",
"Documented 18th–20th century",
"A hide or cloth painted year by year with one pictograph per winter.",
"bison hide; muslin; paint",
"Lone Dog winter count; Battiste Good winter count",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Library of Congress (PD items); Wikimedia Commons",
"R2",
"F1.29;F1.30",
"high",
"",
"canon_object_types.csv"
],
[
"OBT151",
"rongorongo tablet",
"kohau rongorongo",
"object-type",
"Things",
"F1.12",
"OC-POL",
"",
"",
"One tablet (Échancrée) is on wood felled c. 1493–1509 CE (Ferrara et al. 2024); other dated tablets are on 18th–19th-century wood",
"Wooden tablets from Rapa Nui carved with glyphs, undeciphered.",
"toromiro and other woods; shark tooth or obsidian carving",
"Mamari tablet; Santiago staff",
"record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;ancestral",
"Wikimedia Commons",
"R2",
"F1.5;F1.3",
"medium",
"Whether rongorongo was invented before European contact is debated.",
"canon_object_types.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
