insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OBT152",
"birch-bark scroll",
"wiigwaasabakoon",
"object-type",
"Things",
"F1.7",
"AM-EWD",
"",
"",
"Documented over centuries",
"Birch bark incised with pictographs recording ceremony, migration and song.",
"birch bark; incision",
"Anishinaabe Midewiwin scrolls",
"record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site",
"R3",
"F1.29",
"high",
"Sacred; exclude from display by default.",
"canon_object_types.csv"
],
[
"OBT153",
"brush and inkstone",
"four treasures of the study; wenfang sibao",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"",
"",
"Brush writing evident by the Warring States",
"The brush, ink stick, inkstone and paper that make East Asian calligraphy.",
"animal hair; pine soot; stone; paper",
"Duan inkstones; Huizhou ink sticks; Xuan paper",
"record and writing;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"National Palace Museum Taipei Open Data; ColBase (Japan Government Standard Terms); e-museum Korea (KOGL Type 1); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT154",
"reed pen and pen box",
"qalam; qalamdan; divit",
"object-type",
"Things",
"F1.10",
"WA-IRN;WA-ANA;AF-EGY;WA-MES",
"",
"",
"Reed pen ancient; Islamic calligraphers' toolkit medieval onward",
"The cut reed pen, ink pot and pen box of Arabic, Persian and Ottoman calligraphy.",
"reed; iron-gall and carbon ink; brass; papier-mâché",
"qalamdan; Mamluk inkwell; Ottoman divit",
"record and writing;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT155",
"abacus",
"suanpan; soroban; counting board",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-JPN;EU-GRR",
"",
"",
"Counting boards ancient; suanpan by the Ming",
"A frame or board with beads or counters for calculation.",
"wood; beads",
"Salamis tablet; suanpan; soroban",
"record and writing;exchange and value;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT156",
"globe",
"terrestrial globe; celestial globe",
"object-type",
"Things",
"THEME",
"EU-WCE;WA-IRN",
"1492",
"",
"Behaim's Erdapfel 1492 (oldest surviving terrestrial globe); Islamic celestial globes earlier",
"A spherical model of the earth or heavens.",
"papier-mâché; printed gores; cast brass",
"Behaim Erdapfel; Islamic celestial globes",
"record and writing;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT157",
"coin",
"coinage",
"object-type",
"Things",
"THEME",
"WA-ANA;AS-CHN;AS-SAS;GL",
"-630",
"",
"Lydian electrum c. 630–600 BCE; Chinese and Indian coinages c. 6th–5th century BCE",
"A standardised piece of metal struck or cast with the mark of an issuer.",
"electrum; silver; bronze casting; die striking",
"Lydian electrum; Athenian owl; Chinese ban liang; Umayyad dinar; Aksumite gold",
"exchange and value;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R1",
"F1.5;F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT158",
"cowrie shell money",
"cowries",
"object-type",
"Things",
"F1.13",
"AF-MAD;AF-GUI;AF-SAH;AS-CHN;AS-SAS",
"",
"",
"Cowries used in Shang China and South Asia; Maldivian cowries in West Africa by the 14th century",
"Maldivian shells used as small currency from China to West Africa, shipped in bulk in the Atlantic trade.",
"Monetaria moneta shells; stringing",
"Maldivian cowries; Yoruba cowrie strings",
"exchange and value;clothing and adornment;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"human-flow",
"Wikimedia Commons; British Museum collection online (link out)",
"R2",
"F1.13",
"high",
"Maldives filed under AF-MAD (Indian Ocean islands).",
"canon_object_types.csv"
],
[
"OBT159",
"manilla",
"manila",
"object-type",
"Things",
"F1.13",
"AF-GUI;EU-WCE;EU-IBE",
"1500",
"",
"Portuguese trade 15th–16th century; legal tender in Nigeria until 1949",
"A horseshoe-shaped brass or copper ring made in Europe as currency for West African trade.",
"brass; copper; casting",
"Birmingham manillas; Portuguese manillas",
"exchange and value;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"human-flow",
"Wikimedia Commons; British Museum collection online (link out)",
"R2",
"F1.13;F1.23",
"high",
"Tied to the Atlantic slave trade; Benin brass-casting used manilla metal.",
"canon_object_types.csv"
],
[
"OBT160",
"Katanga cross",
"handa; croisette",
"object-type",
"Things",
"F1.6",
"AF-CEN;AF-SOU",
"1000",
"",
"c. 10th century onward (Upemba depression, Sanga)",
"A cast copper ingot in X-shape used as currency and grave good in the Copperbelt.",
"copper; open-mould casting",
"Katanga crosses",
"exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT161",
"tabu shell money",
"tabu; tambu; diwara",
"object-type",
"Things",
"F1.12",
"OC-MEL",
"",
"",
"Pre-contact; still used alongside the kina",
"Strings of small Nassa shells counted in fathoms, used by the Tolai of New Britain for exchange and mortuary rites.",
"Nassa shells; cane; stringing",
"Tolai tabu coils (loloi)",
"exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community;Indigenous-community",
"Wikimedia Commons; Auckland Museum Collections Online (per-item)",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT162",
"Rai stone",
"fei; stone money",
"object-type",
"Things",
"F1.12",
"OC-MIC",
"",
"",
"Quarried on Palau and carried to Yap; many large stones 19th century",
"Large carved limestone discs whose ownership passes by agreement without the stone moving.",
"aragonite limestone; quarrying; canoe transport",
"Yap stone money",
"exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community;Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.3",
"high",
"",
"canon_object_types.csv"
],
[
"OBT163",
"wampum",
"wampum belt",
"object-type",
"Things",
"F1.7",
"AM-EWD",
"",
"",
"Shell beads pre-contact; belts documented from the 17th century",
"Beads drilled from quahog and whelk shell woven into belts that record agreements; colonists also used beads as currency.",
"quahog shell; whelk shell; drilling; weaving",
"Two Row Wampum; Hiawatha Belt",
"exchange and value;record and writing;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"Smithsonian NMAI (link out; consult community); community-published site",
"R2",
"F1.29;F1.24",
"high",
"Haudenosaunee position: belts are records and agreements, not money; follow community guidance.",
"canon_object_types.csv"
],
[
"OBT164",
"goldweight",
"mrammuo; abrammuo",
"object-type",
"Things",
"F1.6",
"AF-GUI",
"1400",
"",
"c. 15th–19th century",
"Small cast brass figures and geometric weights used to weigh gold dust against a standard.",
"brass; lost-wax casting",
"Akan goldweights; proverb weights",
"exchange and value;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); British Museum collection online (link out); Wikimedia Commons",
"R1",
"F1.13;F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT165",
"Indus weights",
"chert cubes",
"object-type",
"Things",
"F1.9",
"AS-SAS",
"-2600",
"",
"Mature Harappan c. 2600–1900 BCE",
"Cubical chert weights following a binary then decimal ratio used across the Indus cities.",
"chert; grinding",
"Harappan weights; Mohenjo-daro weights",
"exchange and value;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT166",
"balance scale",
"scales; steelyard",
"object-type",
"Things",
"THEME",
"GL",
"-3000",
"",
"Egyptian and Mesopotamian balances by the 3rd millennium BCE; start approximate",
"A beam balance for weighing goods and gold and, in Egyptian imagery, the heart.",
"bronze; wood; weights",
"Egyptian balance; Akan gold scales; Roman steelyard",
"exchange and value;tools;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT167",
"cloth money",
"textile currency",
"object-type",
"Things",
"THEME",
"AF-CEN;AS-CHN;EU-SCA;AF-SAH",
"",
"",
"Many periods",
"Woven cloth used as a store and measure of value.",
"raffia; silk; wool; cotton strips",
"Kuba raffia squares; Chinese silk bolts; Icelandic vaðmál; Sahelian cotton strips",
"exchange and value;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT168",
"paper money",
"banknote; jiaozi",
"object-type",
"Things",
"F1.8;THEME",
"AS-CHN;EU-SCA;GL",
"1024",
"",
"Official jiaozi 1024; Stockholms Banco notes 1661",
"Printed notes promising value, first issued by the Song state.",
"paper; woodblock; copper plate; security printing",
"jiaozi; Da Ming Tongxing Baochao; Stockholms Banco notes",
"exchange and value;record and writing;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.14",
"high",
"Counterfeiting is an F1.14 thread.",
"canon_object_types.csv"
],
[
"OBT169",
"knife and spade money",
"daobi; bubi",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-600",
"",
"Zhou, c. 7th–3rd century BCE",
"Bronze currency cast in the shape of tools.",
"bronze casting",
"Qi knife money; spade money",
"exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT170",
"salt bar",
"amole",
"object-type",
"Things",
"F1.6",
"AF-HRN;AF-SAH",
"",
"",
"Documented from the medieval period; used into the 20th century",
"Carved bars of rock salt used as currency in Ethiopia and the Sahara.",
"rock salt",
"Afar amole; Taoudenni salt slabs",
"exchange and value;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT171",
"feather money",
"tevau",
"object-type",
"Things",
"F1.12",
"OC-MEL",
"",
"",
"Documented 19th–20th century",
"Coils of red honeyeater feathers glued to fibre, used as bridewealth in Santa Cruz (Solomon Islands).",
"scarlet honeyeater feathers; fibre",
"Santa Cruz tevau",
"exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; Auckland Museum Collections Online (per-item)",
"R3",
"F1.29",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT172",
"kula valuable",
"mwali; soulava; bagi",
"object-type",
"Things",
"F1.12",
"OC-MEL",
"",
"",
"Kula described by Malinowski 1922; older",
"Shell armshells and necklaces passed around the Massim islands in ceremonial exchange.",
"Conus shell; Spondylus shell; decoration",
"mwali armshells; soulava necklaces",
"exchange and value;ritual and belief;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community;Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.3;F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT173",
"copper",
"tináa; tl'aqwa",
"object-type",
"Things",
"F1.7",
"AM-NWC",
"",
"",
"Native copper pre-contact; sheet-copper coppers 19th century",
"A shield-shaped copper plaque whose value rose with each transfer at a potlatch.",
"copper sheet; engraving; paint",
"Kwakwakaʼwakw coppers; Haida coppers",
"exchange and value;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site; Wikimedia Commons",
"R3",
"F1.24;F1.29",
"high",
"Confiscations under the Canadian potlatch ban (1884–1951).",
"canon_object_types.csv"
],
[
"OBT174",
"oxhide ingot",
"ingot",
"object-type",
"Things",
"F1.13",
"EU-GRR;WA-LEV",
"-1600",
"",
"Late Bronze Age c. 16th–11th century BCE",
"A standardised copper ingot shaped like a stretched hide, traded across the Mediterranean from Cyprus.",
"copper; casting",
"Uluburun ingots; Cape Gelidonya ingots",
"exchange and value;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13;F1.22",
"high",
"",
"canon_object_types.csv"
],
[
"OBT175",
"Maria Theresa thaler",
"MTT",
"object-type",
"Things",
"F1.13",
"AF-HRN;WA-ARB;EU-WCE",
"1741",
"",
"First issued 1741; frozen 1780 date restruck to the present",
"A silver coin minted in Austria that became a currency of the Red Sea, Arabia and East Africa for two centuries.",
"silver; die striking",
"Maria Theresa thaler (1780-dated restrikes)",
"exchange and value;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13;F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT176",
"Kissi penny",
"kilindi",
"object-type",
"Things",
"F1.6",
"AF-GUI",
"",
"",
"19th–20th century",
"Twisted iron rods used as currency and grave offerings in Sierra Leone, Liberia and Guinea.",
"iron; forging",
"Kissi pennies",
"exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT177",
"fine mat",
"ʻie tōga",
"object-type",
"Things",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; living",
"Finely plaited pandanus mats that are the highest-value gifts at Samoan ceremonies.",
"pandanus; fine plaiting",
"ʻie tōga",
"exchange and value;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community;Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT178",
"payment card",
"credit card",
"object-type",
"Things",
"THEME",
"GL",
"1950",
"",
"Diners Club 1950; magnetic stripe 1960s",
"A plastic card that turned credit into an object carried in the pocket.",
"PVC; magnetic stripe; chip",
"Diners Club card; BankAmericard",
"exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT179",
"prayer beads",
"misbaha; subha; mala; rosary; juzu",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Hindu and Buddhist malas old; Islamic subha by the early Islamic centuries; rosary medieval",
"Strings of counted beads for prayer and recitation.",
"seeds; wood; glass; amber; stone",
"misbaha; japa mala; rosary; juzu",
"ritual and belief;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT180",
"reliquary",
"relic casket; stupa reliquary",
"object-type",
"Things",
"THEME",
"EU-WCE;EU-BYZ;AS-SAS;AS-CHN",
"",
"",
"Buddhist relic deposits from c. 3rd century BCE; Christian reliquaries from the 4th century",
"A container made to hold and honour relics.",
"gold; silver; rock crystal; enamel",
"Bimaran casket; Sainte-Foy (Conques); Famen Temple reliquaries",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons; Europeana (per-item licence)",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT181",
"mask",
"mask",
"object-type",
"Things",
"THEME",
"GL",
"-7000",
"",
"Nahal Hemar stone masks c. 7000 BCE",
"A face covering that transforms the wearer or represents a being in performance, ritual or burial.",
"wood; fibre; metal; paper; gold",
"Dan masks; Noh masks; Yup'ik masks; Tutankhamun's mask; Chokwe mwana pwo",
"ritual and belief;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community;funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16;F1.24;F1.4",
"high",
"Many masks are sacred; display only where the community publishes.",
"canon_object_types.csv"
],
[
"OBT182",
"incense burner",
"mabkhara; censer; thurible; boshanlu",
"object-type",
"Things",
"THEME",
"WA-ARB;AS-CHN;EU-BYZ;GL",
"",
"",
"South Arabian burners 1st millennium BCE; Han boshanlu",
"A vessel for burning resin or wood to scent spaces, bodies and prayers.",
"clay; bronze; brass; frankincense; oud",
"South Arabian cuboid burners; Han boshanlu; Emirati mabkhara; Byzantine censer",
"ritual and belief;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT183",
"Qur'an stand",
"rahla; rahle",
"object-type",
"Things",
"F1.10",
"WA-IRN;WA-ANA;AS-SAS",
"1300",
"",
"Surviving from the 14th century",
"A folding X-shaped stand cut from one board to hold the Qur'an.",
"walnut; carving; lacquer; inlay",
"Ilkhanid rahla (Met); Ottoman rahle",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT184",
"prayer rug",
"sajjada; namazlık",
"object-type",
"Things",
"F1.10",
"WA-ANA;WA-IRN;AS-CEN;AS-SAS",
"",
"",
"Surviving from the 15th–16th century",
"A small carpet with a niche design laid toward Mecca for prayer.",
"wool; silk; knotting",
"Ottoman prayer rugs; Mughal prayer rug",
"ritual and belief;shelter",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT185",
"thangka",
"thangka",
"object-type",
"Things",
"F1.8;F1.9",
"AS-HIM",
"1000",
"",
"c. 11th century onward",
"A painted or appliqué scroll used in Buddhist meditation and teaching.",
"cotton; mineral pigments; silk mounts",
"Regong thangka; Tibetan appliqué thangka",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;living-community",
"Met Open Access (CC0); Wikimedia Commons; community-published site",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT186",
"prayer wheel",
"mani khorlo",
"object-type",
"Things",
"F1.9;F1.8",
"AS-HIM",
"",
"",
"Medieval origin uncertain",
"A cylinder filled with printed mantras, turned by hand, water or wind.",
"copper; printed paper; wood",
"hand prayer wheel; water prayer wheel",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT187",
"icon",
"eikon",
"object-type",
"Things",
"F1.11;F1.6",
"EU-BYZ;AF-HRN;EU-EER",
"550",
"",
"Sinai encaustic icons 6th century",
"A painted image of holy persons venerated in Orthodox and Ethiopian churches.",
"tempera; encaustic; wood panel; gold leaf",
"Sinai Christ Pantocrator; Rublev's Trinity; Ethiopian diptychs",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT188",
"ex-voto",
"votive offering; milagro; tama",
"object-type",
"Things",
"THEME",
"EU-GRR;AM-LAT;EU-WCE",
"",
"",
"Ancient",
"An object offered in fulfilment of a vow, often shaped as a healed body part.",
"terracotta; tin; wax; paint",
"Etruscan anatomical votives; Mexican retablo ex-votos; milagros",
"ritual and belief;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16;F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT189",
"amulet",
"talisman; hirz; ta'wiz",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A small object worn for protection or luck.",
"faience; silver; stone; paper",
"wedjat eye; hamsa; ta'wiz; Thai phra khruang",
"ritual and belief;clothing and adornment;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT190",
"talismanic shirt",
"jama; tılsımlı gömlek",
"object-type",
"Things",
"F1.10;F1.6",
"WA-ANA;AS-SAS;AF-SAH;AF-GUI",
"1500",
"",
"Ottoman and Mughal c. 15th–17th century; West African versions later",
"A shirt inscribed with Qur'anic verses and magic squares worn for protection in battle or illness.",
"cotton; ink; gilding; leather amulets",
"Ottoman talismanic shirts; Asante batakari kese",
"ritual and belief;war;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT191",
"power figure",
"nkisi; nkondi",
"object-type",
"Things",
"F1.6",
"AF-CEN",
"",
"",
"Collected 19th–early 20th century",
"A carved figure activated by a ritual specialist (nganga) with substances, nails and blades to heal, protect and seal oaths.",
"wood; iron nails; medicine packs; mirrors",
"Kongo nkisi nkondi; Songye nkisi",
"ritual and belief;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); British Museum collection online (link out); Wikimedia Commons",
"R2",
"F1.24;F1.16",
"high",
"Many taken under colonial violence; restitution case.",
"canon_object_types.csv"
],
[
"OBT192",
"tjurunga",
"churinga",
"object-type",
"Things",
"F1.12",
"OC-AUS",
"",
"",
"Ancient",
"Sacred objects of Arrernte and other Central Australian peoples, restricted by law and custom.",
"stone; wood; incision",
"",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site",
"R3",
"F1.24",
"high",
"Exclude all images; many have been repatriated. Card should explain restriction only.",
"canon_object_types.csv"
],
[
"OBT193",
"ancestor board",
"gope; kwoi; hohao",
"object-type",
"Things",
"F1.12",
"OC-MEL",
"",
"",
"Collected 19th–20th century",
"Carved boards of the Papuan Gulf that hold ancestral or protective spirits.",
"wood; pigment",
"Papuan Gulf gope boards",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;ancestral",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.24",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT194",
"jade cong and bi",
"cong; bi",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-3300",
"",
"Liangzhu c. 3300–2300 BCE",
"Worked jade tubes and discs placed in burials, their meaning still debated.",
"nephrite; abrasive sawing and drilling",
"Liangzhu cong; Liangzhu bi",
"ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R2",
"F1.3",
"high",
"",
"canon_object_types.csv"
],
[
"OBT195",
"bronze bell",
"bianzhong; dōtaku; beomjong",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-JPN;AS-KOR;EU-WCE",
"-1200",
"",
"Shang bells; Zeng bell set 433 BCE; Yayoi dōtaku",
"A cast bell whose sound calls, marks time or honours.",
"bronze casting; tuning",
"Marquis Yi of Zeng bianzhong; Yayoi dōtaku; Divine Bell of King Seongdeok",
"ritual and belief;play and music;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); e-museum Korea (KOGL Type 1); ColBase (Japan Government Standard Terms); Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT196",
"coffin",
"sarcophagus; coffin",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A container for the dead made to protect and present them.",
"wood; stone; cartonnage; paint",
"Egyptian anthropoid coffins; Roman sarcophagi; Ghanaian figurative coffins (abebuu adekai)",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"Human remains excluded from display.",
"canon_object_types.csv"
],
[
"OBT197",
"shabti",
"ushabti",
"object-type",
"Things",
"F1.6",
"AF-EGY;AF-NUB",
"-2000",
"",
"Middle Kingdom onward",
"A small figure placed in the tomb to work for the dead in the afterlife.",
"faience; wood; stone",
"Seti I shabtis; Taharqa's shabtis (Nuri)",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.23",
"high",
"Labour imagined for the dead: an F1.23 hook.",
"canon_object_types.csv"
],
[
"OBT198",
"divination tray",
"opon Ifá; tablero de Ifá",
"object-type",
"Things",
"F1.6;F1.7",
"AF-GUI;AM-CAR;AM-LAT",
"",
"",
"Collected from the 17th century; Ifá far older",
"A carved tray on which Ifá priests mark signs in powder to consult the oracle.",
"wood; carving; iyerosun powder",
"Yoruba opon Ifá; Cuban tablero de Ifá",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16;F1.13",
"high",
"UNESCO lists the Ifá divination system (2008).",
"canon_object_types.csv"
],
[
"OBT199",
"ceremonial pipe",
"calumet; chanunpa",
"object-type",
"Things",
"F1.7",
"AM-WST;AM-EWD",
"",
"",
"Pre-contact",
"A pipe of pipestone with a long stem used in prayer and treaty-making.",
"catlinite; wood; quills",
"Lakota chanunpa; Hopewell platform pipes",
"ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site",
"R3",
"F1.24",
"high",
"Sacred; exclude from display.",
"canon_object_types.csv"
],
[
"OBT200",
"katsina figure",
"tihu; kachina doll",
"object-type",
"Things",
"F1.7",
"AM-WST",
"",
"",
"Documented 19th century; practice older",
"Carved cottonwood figures given to Hopi children to teach about katsinam.",
"cottonwood root; paint",
"Hopi tihu",
"ritual and belief;play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site",
"R3",
"F1.2;F1.24",
"high",
"Hopi ask that katsinam not be shown; commercial copies are an F1.2 case.",
"canon_object_types.csv"
],
[
"OBT201",
"processional bronze image",
"utsava murti",
"object-type",
"Things",
"F1.9",
"AS-SAS",
"900",
"",
"Chola c. 9th–13th century",
"A lost-wax cast deity image carried in temple processions.",
"copper alloy; lost-wax casting",
"Chola Nataraja; Somaskanda",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R1",
"F1.24;F1.16",
"high",
"Many looted; recent repatriations (e.g. the Subhash Kapoor cases).",
"canon_object_types.csv"
],
[
"OBT202",
"Hanukkah lamp",
"hanukkiah",
"object-type",
"Things",
"F1.10;F1.11",
"AF-MAG;EU-WCE;GL",
"",
"",
"Surviving from the medieval period",
"An eight-branched lamp lit over the festival of Hanukkah.",
"brass; silver; clay",
"North African brass hanukkiot; European silver hanukkiot",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT203",
"cross-stone",
"khachkar",
"object-type",
"Things",
"F1.9a;F1.11",
"WA-CAU",
"800",
"",
"9th century onward",
"A carved stone stele with a cross and interlace set up for prayer and memory.",
"tuff; carving",
"Goshavank khachkar; Noratus cemetery khachkars",
"ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_object_types.csv"
],
[
"OBT204",
"crown",
"diadem; adé",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A head ornament made to show sovereignty.",
"gold; gems; beads; feathers",
"Silla gold crowns; Yoruba beaded crown (adé); Holy Crown of Hungary",
"rule and display;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;funerary",
"e-museum Korea (KOGL Type 1); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.17",
"high",
"Yoruba beaded crowns are sacred.",
"canon_object_types.csv"
],
[
"OBT205",
"staff of office",
"linguist staff; okyeame poma; sceptre",
"object-type",
"Things",
"THEME",
"AF-GUI;GL",
"",
"",
"Varies",
"A staff carried to show delegated authority, often topped with an image of a proverb.",
"wood; gold leaf; silver",
"Akan okyeame poma; Egyptian was-sceptre; parliamentary mace",
"rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.17;F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT206",
"state umbrella",
"chattra; royal parasol",
"object-type",
"Things",
"THEME",
"AS-SAS;AS-MSE;AF-GUI",
"",
"",
"Ancient",
"An umbrella held over a ruler or sacred image as a sign of rank.",
"textile; wood; gold",
"Asante state umbrellas; Thai nine-tiered umbrella",
"rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT207",
"seal of state",
"imperial seal; eobo",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-KOR;GL",
"",
"",
"Varies",
"A seal whose impression makes a document an act of state.",
"jade; gold; silver",
"Heirloom Seal of the Realm (lost); Korean royal seals (eobo); Great Seal of the Realm",
"rule and display;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"e-museum Korea (KOGL Type 1); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R2",
"F1.17",
"high",
"",
"canon_object_types.csv"
],
[
"OBT208",
"flag",
"flag",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient standards; national flags 18th–20th century",
"A cloth carrying the colours of a group, state or cause.",
"textile; dye; appliqué",
"Fante asafo flags; Japanese hinomaru; national flags",
"rule and display;war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items)",
"R2",
"F1.20",
"high",
"",
"canon_object_types.csv"
],
[
"OBT209",
"banner",
"standard; ʿalam; drapo",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A shaped standard carried in procession and battle.",
"textile; metal finial; sequins",
"Shiʿi ʿalam; Chinese battle banners; Haitian Vodou drapo",
"rule and display;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.16",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT210",
"heraldic sign",
"coat of arms; mon; tamga",
"object-type",
"Things",
"THEME",
"EU-WCE;AS-JPN;AS-CEN",
"1130",
"",
"European heraldry c. 1130s–1150s; Japanese mon; steppe tamga older",
"A system of signs identifying lineages and holders of office.",
"paint; embroidery; enamel",
"Japanese kamon; European coats of arms; Kazakh tamga",
"rule and display;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R2",
"F1.21",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT211",
"logo",
"trademark; brand mark",
"object-type",
"Things",
"THEME",
"GL",
"1876",
"",
"Bass red triangle, first UK registered trademark 1876; earlier makers' marks",
"A mark identifying a maker or company, descended from makers' marks and seals.",
"print; digital",
"Bass red triangle; Coca-Cola script; Nike swoosh",
"rule and display;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.21;F1.14",
"high",
"",
"canon_object_types.csv"
],
[
"OBT212",
"brass plaque",
"Benin plaques; Benin Bronzes",
"object-type",
"Things",
"F1.6",
"AF-GUI",
"1500",
"",
"c. 16th–17th century",
"Cast brass plaques depicting the court of Benin that clad palace pillars.",
"leaded brass; lost-wax casting",
"Benin plaques; commemorative heads",
"rule and display;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"conflict-looting;sacred",
"Wikimedia Commons; British Museum collection online (link out)",
"R1",
"F1.24",
"high",
"Looted 1897; restitution ongoing; Digital Benin for records.",
"canon_object_types.csv"
],
[
"OBT213",
"carved door",
"palace door",
"object-type",
"Things",
"F1.6",
"AF-GUI;AF-SWA",
"",
"",
"19th–20th century",
"Doors carved in relief for palaces and houses, showing court life and encounters.",
"wood; relief carving; brass studs",
"Olowe of Ise doors; Zanzibar carved doors",
"rule and display;shelter",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; British Museum collection online (link out)",
"R2",
"F1.26",
"high",
"Olowe of Ise is a named maker (F1.26).",
"canon_object_types.csv"
],
[
"OBT214",
"obelisk and stele",
"obelisk; hawelt",
"object-type",
"Things",
"THEME",
"AF-EGY;AF-HRN",
"-2400",
"",
"Old Kingdom obelisks; Aksum stelae c. 3rd–4th century CE",
"A tall monolith raised as royal or funerary monument.",
"granite; basalt; quarrying",
"Aksum stelae; Lateran obelisk",
"rule and display;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"The Aksum stele taken to Rome in 1937 was returned in 2005.",
"canon_object_types.csv"
],
[
"OBT215",
"mace",
"macehead",
"object-type",
"Things",
"THEME",
"AF-EGY;EU-BLC;GL",
"-3500",
"",
"Predynastic Egypt",
"A club turned into a symbol of authority.",
"stone; silver; gilding",
"Scorpion Macehead; House of Commons mace",
"rule and display;war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT216",
"medal and order",
"decoration",
"object-type",
"Things",
"THEME",
"GL",
"1438",
"",
"Renaissance cast medals from c. 1438 (Pisanello)",
"Small struck or cast pieces awarded to mark service and allegiance.",
"bronze; silver; enamel; ribbon",
"Pisanello medals; campaign medals",
"rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT217",
"passport",
"travel document",
"object-type",
"Things",
"THEME",
"GL",
"1920",
"",
"League of Nations passport standard 1920",
"A booklet identifying a person to the state and controlling movement.",
"security paper; print; biometric chip",
"League of Nations-format passport; Nansen passport",
"rule and display;record and writing;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT218",
"uniform",
"uniform",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Standardised military uniforms from the 17th century",
"Standardised dress that makes people legible as members of an army, school or company.",
"wool; khaki; print",
"British khaki; Mao suit; school uniforms",
"rule and display;clothing and adornment;war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT219",
"shop sign",
"signage",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient; enamel signs 19th century; neon 20th century",
"Signs that name and advertise shops and services in public space.",
"wood; enamel; neon; LED; hand painting",
"Hong Kong neon signs; Ghanaian barbershop signs",
"rule and display;exchange and value;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21;F1.29",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT220",
"feather headdress",
"war bonnet; penacho",
"object-type",
"Things",
"F1.7",
"AM-WST;AM-AMZ;AM-MES",
"",
"",
"Varies",
"Headdresses of feathers earned or inherited as signs of honour.",
"eagle feathers; quetzal and macaw feathers; quills",
"Plains war bonnet; the Vienna penacho; Kayapó krokrokti",
"rule and display;clothing and adornment",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;Indigenous-community",
"community-published site",
"R3",
"F1.2;F1.24",
"high",
"Vienna penacho restitution debate; fashion appropriation of war bonnets (F1.2).",
"canon_object_types.csv"
],
[
"OBT221",
"sword",
"sword",
"object-type",
"Things",
"THEME",
"GL",
"-3300",
"",
"Arslantepe arsenical-copper swords c. 3300 BCE",
"A long blade forged or cast for fighting and display.",
"bronze; iron; crucible steel; pattern welding",
"Arslantepe swords; Japanese katana; Tuareg takouba; Ethiopian shotel; Ulfberht swords",
"war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R2",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT222",
"kris",
"keris",
"object-type",
"Things",
"F1.9",
"AS-ISE;AS-MSE",
"",
"",
"c. 14th century onward",
"An asymmetric pattern-welded dagger regarded as having spiritual power.",
"pattern-welded iron and nickel (pamor); wood hilt",
"Javanese keris; Balinese keris",
"war;ritual and belief;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred;living-community",
"Rijksmuseum (CC0); Met Open Access (CC0); Wikimedia Commons; UNESCO ICH lists (link out; per-item photo licence)",
"R2",
"F1.16",
"high",
"UNESCO Indonesian Kris (2008).",
"canon_object_types.csv"
],
[
"OBT223",
"spear",
"spear; iklwa",
"object-type",
"Things",
"THEME",
"GL",
"-300000",
"",
"Schöningen spears c. 300,000 BP (earlier estimates to 400,000)",
"A shafted pointed weapon; the oldest surviving are wooden throwing spears.",
"wood; stone; iron",
"Schöningen spears; Zulu iklwa",
"war;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT224",
"composite bow",
"recurve bow",
"object-type",
"Things",
"F1.12a",
"AS-CEN;AS-NTH;WA-ANA;AS-KOR",
"-2000",
"",
"Steppe and Near East by the 2nd millennium BCE; approximate",
"A bow laminated from horn, wood and sinew, powerful enough for use from horseback.",
"horn; wood; sinew; hide glue",
"Scythian bow; Mongol bow; Ottoman bow; Korean gakgung",
"war;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; e-museum Korea (KOGL Type 1)",
"R2",
"F1.19a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT225",
"crossbow",
"nu",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"-500",
"",
"Bronze trigger mechanisms from the Warring States",
"A bow mounted on a stock and released by a mechanical trigger.",
"wood; bronze trigger",
"Qin crossbow triggers",
"war;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT226",
"spear-thrower",
"atlatl; woomera",
"object-type",
"Things",
"THEME",
"AM-MES;OC-AUS;EU-WCE",
"-17000",
"",
"Upper Palaeolithic Europe c. 17,000 BP",
"A lever that throws a dart or spear further and harder.",
"wood; antler; stone",
"Mexica atlatl; Aboriginal woomera; Magdalenian propulseur",
"war;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT227",
"shield",
"shield",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A handheld defence often painted with identity.",
"hide; wood; wickerwork; bronze",
"Zulu isihlangu; Aboriginal parrying shield; Asmat shields; Greek hoplon",
"war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT228",
"armour",
"armor; mail; lamellar",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"Body protection of plates, scales, rings or quilting.",
"iron; leather; lacquer; quilted cotton; mail",
"Japanese ō-yoroi; Mamluk mail; Mexica ichcahuipilli; European plate armour",
"war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT229",
"helmet",
"helmet",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"Head protection that also shows rank.",
"bronze; iron; leather",
"Sutton Hoo helmet; Corinthian helmet; Japanese kabuto",
"war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT230",
"obsidian-edged club",
"macuahuitl",
"object-type",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Postclassic; described in 16th-century sources",
"A wooden club set with obsidian blades.",
"wood; obsidian",
"macuahuitl",
"war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"No original survives (the last known was destroyed in a Madrid fire in 1884).",
"canon_object_types.csv"
],
[
"OBT231",
"hand club",
"patu; mere; ula",
"object-type",
"Things",
"F1.12",
"OC-POL;OC-MEL",
"",
"",
"Pre-contact",
"Clubs of stone, bone or wood, some treasured as heirlooms.",
"pounamu; whalebone; hardwood",
"Māori mere pounamu; Fijian ula; Tongan ʻakau",
"war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"ancestral;Indigenous-community",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); Wikimedia Commons",
"R3",
"F1.24",
"high",
"",
"canon_object_types.csv"
],
[
"OBT232",
"firearm",
"gun; matchlock; musket",
"object-type",
"Things",
"THEME",
"GL",
"1288",
"",
"Heilongjiang hand cannon c. 1288",
"A weapon firing projectiles by gunpowder.",
"iron; bronze; wood",
"Heilongjiang hand cannon; Tanegashima matchlock; Brown Bess",
"war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT233",
"cannon",
"bombard",
"object-type",
"Things",
"THEME",
"GL",
"1300",
"",
"China and the Islamic world 13th–14th century",
"A large gun that remade fortification and naval war.",
"bronze; cast iron",
"Great Turkish Bombard (Dardanelles gun); Tsar Cannon",
"war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT234",
"gas mask",
"respirator",
"object-type",
"Things",
"THEME",
"GL",
"1915",
"",
"First World War",
"A mask filtering poison gas, later a civil-defence object.",
"rubber; charcoal filter",
"British PH helmet; Soviet GP-5",
"war;care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R3",
"F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT235",
"throwing knife",
"kpinga; shongo",
"object-type",
"Things",
"F1.6",
"AF-CEN",
"",
"",
"Collected 19th century",
"Multi-bladed iron weapons also used as currency and emblems.",
"forged iron",
"Zande kpinga; Kuba shongo",
"war;exchange and value;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.19a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT236",
"senet",
"senet",
"object-type",
"Things",
"F1.6",
"AF-EGY",
"-3100",
"",
"c. 3100 BCE onward",
"A board game of thirty squares later linked to the soul's journey.",
"wood; faience; ivory",
"Tutankhamun's senet boxes",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT237",
"mancala",
"oware; bao; ayo",
"object-type",
"Things",
"THEME",
"AF-GUI;AF-SWA;AF-HRN;AS-SAS;AM-CAR",
"",
"",
"Ancient; dates uncertain",
"Count-and-capture games played with seeds in pits, spread by trade and the diaspora.",
"wood; seeds; holes in the ground",
"Akan oware; Swahili bao; Yoruba ayo; Caribbean warri",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.4;F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT238",
"go",
"weiqi; baduk",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"-500",
"",
"Mentioned in texts of c. 4th century BCE",
"A territory game of black and white stones on a grid.",
"wood board; slate and shell stones",
"goban; baduk board",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT239",
"chess",
"chaturanga; shatranj; xiangqi",
"object-type",
"Things",
"THEME",
"AS-SAS;WA-IRN;EU-WCE;AS-CHN",
"600",
"",
"Chaturanga c. 6th century CE",
"A war game that changed form as it travelled from India through Iran to Europe and Asia.",
"ivory; wood; bone",
"Lewis chessmen; Charlemagne chessmen; shatranj pieces",
"play and music;war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT240",
"patolli",
"patolli",
"object-type",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Postclassic",
"A race game played with beans on a cross-shaped board, often for high stakes.",
"painted mat; marked beans",
"Codex Magliabechiano patolli scene",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT241",
"Royal Game of Ur",
"Game of Twenty Squares",
"object-type",
"Things",
"F1.9a",
"WA-MES;WA-LEV;AF-EGY",
"-2600",
"",
"Royal Cemetery of Ur c. 2600 BCE",
"A race game of twenty squares played across the Near East for three millennia.",
"shell; lapis lazuli; red limestone; wood",
"Ur boards; tablet of rules (c. 177 BCE)",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons; British Museum collection online (link out)",
"R2",
"F1.4;F1.28",
"high",
"",
"canon_object_types.csv"
],
[
"OBT242",
"backgammon",
"nard; tables; tavla",
"object-type",
"Things",
"THEME",
"WA-IRN;GL",
"",
"",
"Nard described in a Sasanian text; older boards claimed",
"A race game with dice for two players.",
"wood; dice",
"nard boards; tavla",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT243",
"chaupar",
"pachisi; chaupar",
"object-type",
"Things",
"F1.9",
"AS-SAS",
"",
"",
"Mughal period and earlier",
"A cross-shaped race game played with cowries.",
"cloth board; cowries",
"chaupar cloth; Ludo (patented 1896)",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.14",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT244",
"dice and knucklebones",
"astragali",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"Tools of chance used in games and divination.",
"bone; ivory; clay",
"astragali; Indus dice; Roman dice",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT245",
"playing cards",
"cards; karuta; ganjifa",
"object-type",
"Things",
"F1.8;THEME",
"AS-CHN;EU-WCE;WA-IRN",
"900",
"",
"Tang c. 9th century; Mamluk cards; Europe 1370s",
"Printed or painted cards for games that travelled from China to Europe through the Islamic world.",
"paper; woodblock; stencil",
"Mamluk cards; Japanese karuta; Indian ganjifa",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT246",
"doll",
"doll",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A figure made for children's play, teaching or ceremony.",
"cloth; wood; clay; plastic",
"Hina dolls; Barbie; rag dolls",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R3",
"F1.21",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT247",
"wheeled toy",
"wheeled figurine",
"object-type",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Veracruz c. 1st millennium CE",
"Clay animal figures on axles and wheels, showing wheels known but not used for transport.",
"clay; axles",
"Veracruz wheeled animals",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT248",
"kite",
"layang-layang; wau; fengzheng",
"object-type",
"Things",
"THEME",
"AS-CHN;AS-ISE;OC-POL",
"",
"",
"Ancient; dates uncertain",
"A tethered flying frame used for play, signalling and fishing.",
"bamboo; paper; silk; leaves",
"Malay wau; Chinese kites; Polynesian manu",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"low",
"",
"canon_object_types.csv"
],
[
"OBT249",
"rubber ball and ballgame yoke",
"ulli ball",
"object-type",
"Things",
"F1.7",
"AM-MES",
"-1600",
"",
"El Manatí balls c. 1600 BCE",
"Solid rubber balls and hip protectors for the Mesoamerican ballgame.",
"latex; morning-glory juice; carved stone yokes",
"El Manatí balls; stone yokes and hachas",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT250",
"spinning top",
"trompo; gasing",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A spinning toy made from wood, clay or metal.",
"wood; clay",
"Malaysian gasing; trompo",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"low",
"",
"canon_object_types.csv"
],
[
"OBT251",
"kora",
"kora",
"object-type",
"Things",
"F1.6",
"AF-SAH;AF-GUI",
"",
"",
"Documented 18th–19th century",
"A 21-string harp-lute of calabash and hide played by jeli (griots).",
"calabash; cowhide; hardwood neck; strings",
"Mande kora",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT252",
"mbira",
"likembe; kalimba",
"object-type",
"Things",
"F1.6",
"AF-SOU;AF-CEN",
"",
"",
"Lamellophones old in Africa; iron keys",
"A lamellophone of iron keys on a board or box, often in a gourd resonator.",
"forged iron keys; wood; gourd",
"Shona mbira dzavadzimu; likembe",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R2",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT253",
"talking drum",
"dùndún; atumpan",
"object-type",
"Things",
"F1.6",
"AF-GUI",
"",
"",
"Ancient",
"Drums that reproduce tonal speech to send messages and praise.",
"wood; hide; tension cords",
"Yoruba dùndún; Akan atumpan",
"play and music;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.4;F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT254",
"gamelan",
"gamelan",
"object-type",
"Things",
"F1.9",
"AS-ISE",
"800",
"",
"Instruments depicted at Borobudur c. 9th century",
"An ensemble of tuned bronze gongs and metallophones made and played as one set.",
"forged tin-bronze; carved wood",
"Javanese gamelan; Balinese gamelan gong kebyar",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Rijksmuseum (CC0); UNESCO ICH lists (link out; per-item photo licence)",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT255",
"sitar",
"sitar",
"object-type",
"Things",
"F1.9;F1.10",
"AS-SAS",
"1700",
"",
"18th century",
"A long-necked lute with sympathetic strings.",
"tun wood; gourd; steel strings",
"Hindustani sitar",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT256",
"oud",
"ʿud; barbat",
"object-type",
"Things",
"F1.10;F1.9a",
"WA-IRN;WA-MES;WA-ANA;AF-EGY",
"",
"",
"Barbat in Sasanian Iran; oud medieval onward",
"A short-necked fretless lute, ancestor of the European lute.",
"wood staves; gut or nylon strings",
"Iraqi oud; Syrian oud",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT257",
"pipa",
"pipa; biwa",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-JPN",
"",
"",
"Han–Tang",
"A pear-shaped lute that reached China from Central Asia.",
"wood; silk strings",
"Shōsōin biwa; Chinese pipa",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; ColBase (Japan Government Standard Terms)",
"R3",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT258",
"qin",
"guqin",
"object-type",
"Things",
"F1.8",
"AS-CHN",
"",
"",
"Warring States onward",
"A seven-string zither of scholars.",
"paulownia; lacquer; silk strings",
"Tang guqin",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; National Palace Museum Taipei Open Data; UNESCO ICH lists (link out; per-item photo licence)",
"R3",
"F1.4",
"high",
"UNESCO Guqin and its music (2008).",
"canon_object_types.csv"
],
[
"OBT259",
"didjeridu",
"yidaki; mago",
"object-type",
"Things",
"F1.12",
"OC-AUS",
"",
"",
"Arnhem Land rock art suggests some antiquity",
"A wind instrument of termite-hollowed eucalyptus from northern Australia.",
"eucalyptus; beeswax mouthpiece; ochre",
"Yolŋu yidaki",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community;sacred",
"Wikimedia Commons; community-published site",
"R3",
"F1.2",
"medium",
"Some communities restrict who may play; souvenir copies are an F1.2 case.",
"canon_object_types.csv"
],
[
"OBT260",
"conch trumpet",
"pū; shankha; horagai; pututu",
"object-type",
"Things",
"THEME",
"OC-POL;AS-SAS;AM-AND;AS-JPN",
"-900",
"",
"Chavín conches c. 900 BCE; Marsoulas conch (France) c. 18,000 BP",
"A sea shell blown as a horn.",
"conch shell",
"Chavín pututus; Hawaiian pū; shankha; Japanese horagai",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT261",
"panpipes",
"siku; antara",
"object-type",
"Things",
"THEME",
"AM-AND;OC-MEL;EU-GRR",
"",
"",
"Ancient",
"Pipes of graduated length bound in rows.",
"cane; clay",
"Andean siku; Solomon Islands panpipes",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT262",
"slit drum",
"garamut; teponaztli",
"object-type",
"Things",
"THEME",
"OC-MEL;AM-MES;AF-CEN",
"",
"",
"Varies",
"A hollowed log with a slit that sounds when struck.",
"wood carving",
"Vanuatu standing slit drums; Mexica teponaztli; Central African slit gong",
"play and music;record and writing;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT263",
"bone flute",
"flute",
"object-type",
"Things",
"THEME",
"EU-WCE;AS-CHN",
"-40000",
"",
"Geißenklösterle and Hohle Fels c. 40,000 BP; Jiahu c. 7000 BCE",
"Pipes of bird bone or ivory with finger holes.",
"vulture bone; crane bone; mammoth ivory",
"Hohle Fels flute; Jiahu flutes",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT264",
"lyre",
"lyre; krar; begena",
"object-type",
"Things",
"THEME",
"WA-MES;EU-GRR;AF-HRN",
"-2500",
"",
"Ur lyres c. 2500 BCE",
"A stringed instrument with a yoke held on two arms.",
"wood; shell; lapis lazuli; gut",
"Ur bull lyre; kithara; Ethiopian krar and begena",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT265",
"arched harp",
"ennanga; saung",
"object-type",
"Things",
"THEME",
"AF-EGY;AF-CEN;AF-SWA;AS-MSE",
"",
"",
"Egypt 3rd millennium BCE; Burmese saung",
"A harp whose neck curves out of the resonator.",
"wood; hide; strings",
"Zande harp; Mangbetu harp; Burmese saung",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT266",
"horsehead fiddle",
"morin khuur",
"object-type",
"Things",
"F1.12a",
"AS-CEN",
"",
"",
"Older fiddle traditions; standard modern form 20th century",
"A two-string bowed fiddle crowned with a horse head.",
"wood; horsehair; skin",
"Mongol morin khuur",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; UNESCO ICH lists (link out; per-item photo licence)",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT267",
"steelpan",
"pan",
"object-type",
"Things",
"F1.7",
"AM-CAR",
"1935",
"",
"Trinidad c. 1930s–40s",
"A tuned percussion instrument hammered from oil drums.",
"oil-drum steel; hammering; tempering",
"tenor pan",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R2",
"F1.4;F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT268",
"balafon",
"balafon; bala",
"object-type",
"Things",
"F1.6",
"AF-SAH;AF-GUI",
"",
"",
"Sosso Bala tradition dates to the 13th century",
"A frame xylophone with gourd resonators.",
"wood keys; gourds; membranes",
"Sosso Bala; Senufo balafon",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT269",
"shadow puppet",
"wayang kulit; Karagöz; sbek",
"object-type",
"Things",
"THEME",
"AS-ISE;AS-MSE;WA-ANA;AS-CHN",
"",
"",
"Varies",
"Pierced and painted leather figures cast as shadows on a screen.",
"buffalo hide; horn; paint",
"wayang kulit; Karagöz; Sbek Thom",
"play and music;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Rijksmuseum (CC0); Wikimedia Commons; UNESCO ICH lists (link out; per-item photo licence)",
"R2",
"F1.4",
"high",
"",
"canon_object_types.csv"
],
[
"OBT270",
"sound recording disc",
"gramophone record",
"object-type",
"Things",
"THEME",
"GL",
"1887",
"",
"Berliner 1887",
"A disc storing sound that made music a commodity.",
"shellac; vinyl",
"78 rpm disc; LP",
"play and music;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Library of Congress (PD items)",
"R3",
"F1.4;F1.21",
"high",
"",
"canon_object_types.csv"
],
[
"OBT271",
"video game console",
"console",
"object-type",
"Things",
"THEME",
"GL",
"1972",
"",
"Magnavox Odyssey 1972",
"A home machine for playing games on a screen.",
"electronics; plastic",
"Magnavox Odyssey; Famicom; PlayStation",
"play and music",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.4;F1.21",
"high",
"",
"canon_object_types.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
