insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"OBT272",
"toe prosthesis",
"Cairo toe; Greville Chester toe",
"object-type",
"Things",
"F1.6",
"AF-EGY",
"-950",
"",
"c. 950–710 BCE",
"Carved wooden and cartonnage toes fitted to feet, among the earliest known functional prostheses.",
"wood; leather; cartonnage",
"Cairo toe (Tabaketenmut); Greville Chester toe (British Museum)",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons; British Museum collection online (link out)",
"R1",
"F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT273",
"prosthetic limb",
"artificial leg; prosthesis",
"object-type",
"Things",
"THEME",
"GL",
"-300",
"",
"Capua leg c. 300 BCE (destroyed 1941)",
"An artificial limb replacing a lost one.",
"wood; bronze; iron; carbon fibre",
"Capua leg; Götz von Berlichingen's iron hand; Jaipur foot",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Wikimedia Commons",
"R2",
"F1.22a",
"high",
"The Jaipur foot (1968) is a low-cost design.",
"canon_object_types.csv"
],
[
"OBT274",
"crutch",
"crutch",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient; dates uncertain",
"A support under the arm for walking.",
"wood; aluminium",
"wooden underarm crutch; forearm crutch",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Wikimedia Commons",
"R3",
"F1.22a",
"low",
"An often-cited Egyptian tomb depiction (c. 2830 BCE) needs checking.",
"canon_object_types.csv"
],
[
"OBT275",
"walking stick",
"cane",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A stick for support, also a sign of age and status.",
"wood; metal",
"",
"care and access;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT276",
"spectacles",
"eyeglasses",
"object-type",
"Things",
"F1.11;THEME",
"EU-WCE;GL",
"1286",
"",
"Pisa c. 1286",
"Lenses mounted before the eyes to correct sight.",
"glass; quartz; horn; metal",
"rivet spectacles; Chinese aidai; mass-market frames",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT277",
"hearing trumpet",
"ear trumpet",
"object-type",
"Things",
"THEME",
"EU-WCE",
"1650",
"",
"17th century",
"A funnel collecting sound into the ear.",
"tin; silver; horn",
"Beethoven's ear trumpets",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Science Museum Group collection (link out; data CC0)",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT278",
"hearing aid",
"hearing aid",
"object-type",
"Things",
"THEME",
"GL",
"1898",
"",
"Electric carbon aid (Akouphone) 1898",
"An electronic device amplifying sound.",
"carbon; vacuum tubes; transistors",
"Akouphone; Zenith Radionic",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Science Museum Group collection (link out; data CC0)",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT279",
"wheelchair",
"wheeled chair",
"object-type",
"Things",
"THEME",
"GL",
"1595",
"",
"Philip II of Spain's chair 1595; earlier Chinese depictions claimed",
"A wheeled seat for moving a person who cannot walk.",
"wood; iron; steel; aluminium",
"Philip II invalid chair; Everest and Jennings folding chair",
"care and access;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Science Museum Group collection (link out; data CC0)",
"R2",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT280",
"braille writing equipment",
"braille slate; Perkins brailler",
"object-type",
"Things",
"THEME",
"EU-WCE;GL",
"1829",
"",
"Braille system 1829; Perkins brailler 1951",
"Tools and type for writing and printing raised-dot text.",
"slate; stylus; embossing",
"braille slate; Perkins brailler; braille printing",
"care and access;record and writing",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT281",
"white cane",
"long cane",
"object-type",
"Things",
"THEME",
"GL",
"1921",
"",
"1921 (James Biggs); long-cane technique 1940s",
"A cane that signals blindness and is used to navigate.",
"aluminium; fibreglass",
"",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT282",
"cradleboard",
"tikinagan; baby board",
"object-type",
"Things",
"F1.7;F1.12a",
"AM-WST;AM-EWD;AM-NWC;AS-NTH",
"",
"",
"Pre-contact",
"A board to carry and protect an infant.",
"wood; hide; beadwork",
"Kiowa beaded cradleboard; Anishinaabe tikinagan",
"care and access;transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Smithsonian NMAI (link out; consult community)",
"R2",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT283",
"baby carrier",
"sling; aguayo",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A cloth, net or basket used to carry infants while working.",
"cloth; netting; basketry",
"Andean aguayo; Hmong baby carrier; PNG bilum",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT284",
"infant feeding vessel",
"feeding bottle",
"object-type",
"Things",
"THEME",
"GL",
"-1200",
"",
"Bronze Age vessels with milk residues (c. 1200–800 BCE)",
"A spouted vessel for feeding infants.",
"clay; glass; plastic",
"Bronze Age feeding vessels; 19th-century glass bottles",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wellcome Collection (CC BY / PD); Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT285",
"medicine container",
"albarello; pharmacy jar",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Varies",
"Jars and boxes that store drugs, from maiolica albarelli to gourds.",
"maiolica; gourd; glass",
"albarello; Chinese medicine chest",
"care and access;food and storage",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT286",
"surgical instruments",
"surgical tools",
"object-type",
"Things",
"THEME",
"EU-GRR;AF-EGY;WA-IRN;GL",
"",
"",
"Roman sets (Pompeii); al-Zahrawi's illustrated instruments c. 1000",
"Instruments for cutting, cautery and extraction.",
"bronze; steel",
"Pompeii surgeon's kit; al-Zahrawi illustrations",
"care and access;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Wikimedia Commons",
"R2",
"F1.22a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT287",
"healing bowl",
"tasat al-sihha",
"object-type",
"Things",
"F1.10",
"WA-IRN;WA-LEV;WA-ARB",
"1150",
"",
"12th century onward",
"Inscribed metal bowls whose water was believed to cure.",
"brass; engraving",
"Zangid healing bowls",
"care and access;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT288",
"cupping vessel",
"hijama cup",
"object-type",
"Things",
"THEME",
"WA-ARB;AS-CHN;GL",
"",
"",
"Ancient",
"Cups placed on the skin to draw blood or tissue.",
"horn; glass; bronze",
"hijama cups",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD); Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT289",
"birthing stool",
"birth chair",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Ancient",
"A seat for giving birth upright.",
"wood",
"",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD)",
"R3",
"F1.18",
"low",
"",
"canon_object_types.csv"
],
[
"OBT290",
"denture",
"false teeth",
"object-type",
"Things",
"THEME",
"GL",
"-700",
"",
"Etruscan gold-band dental appliances c. 7th century BCE",
"Replacement teeth and bridges.",
"gold; ivory; porcelain; acrylic",
"Etruscan gold bridges; Japanese wooden dentures",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wellcome Collection (CC BY / PD)",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT291",
"mosquito net",
"net",
"object-type",
"Things",
"THEME",
"GL",
"",
"",
"Described in antiquity; now mass-made",
"Netting over sleepers that prevents malaria.",
"cotton; polyester; insecticide treatment",
"long-lasting insecticidal net",
"care and access;shelter",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT292",
"chewing stick",
"miswak; siwak",
"object-type",
"Things",
"THEME",
"WA-ARB;AF-HRN;AS-SAS",
"",
"",
"Ancient",
"A twig of Salvadora persica chewed to clean teeth.",
"arak wood",
"miswak",
"care and access",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22a",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT293",
"outrigger canoe",
"vaka; waka ama; lakana",
"object-type",
"Things",
"F1.12;F1.9;F1.6",
"OC-POL;OC-MEL;OC-MIC;AS-ISE;AF-MAD",
"",
"",
"Austronesian; date of origin uncertain",
"A hull stabilised by a float on booms.",
"breadfruit wood; sennit; pandanus sail",
"Marshallese walap; Malagasy lakana",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; Te Papa Collections Online (per-item; link out where restricted)",
"R2",
"F1.13;F1.29",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT294",
"voyaging canoe",
"drua; waʻa kaulua; vaka moana",
"object-type",
"Things",
"F1.12",
"OC-POL;OC-MEL",
"",
"",
"Pre-contact; revival with Hōkūleʻa 1975",
"Two hulls joined by a platform that carried people across the Pacific.",
"timber; sennit; pandanus sails",
"Fijian drua; Hōkūleʻa",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; community-published site",
"R1",
"F1.13;F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT295",
"dhow",
"sambuk; boum; lenj; jalibut",
"object-type",
"Things",
"F1.10;F1.13",
"WA-ARB;WA-IRN;AF-SWA;AS-SAS",
"",
"",
"Sewn-plank ships ancient; Belitung wreck 9th century",
"Sewn or nailed plank ships with lateen sails that sailed the monsoon.",
"teak; coir; nails",
"Belitung wreck; boum; jahazi; Emirati jalibut",
"transport;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons; Qatar Digital Library (open licence)",
"R1",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT296",
"junk",
"chuan",
"object-type",
"Things",
"F1.8",
"AS-CHN;AS-MSE",
"",
"",
"Song onward",
"A sailing ship with battened sails and watertight bulkheads.",
"timber; bulkheads; bamboo-battened sails",
"Quanzhou ship; Nanhai One",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT297",
"longship",
"langskip",
"object-type",
"Things",
"F1.11",
"EU-SCA",
"800",
"",
"c. 800–1100",
"A clinker-built ship driven by oars and sail.",
"oak; iron rivets; wool sail",
"Oseberg ship; Gokstad ship; Skuldelev ships",
"transport;war",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"OBT298",
"umiak",
"umiaq",
"object-type",
"Things",
"F1.7",
"AM-ARC;AS-NTH",
"",
"",
"Ancient",
"An open skin boat for hunting and travel.",
"walrus skin; driftwood",
"umiak",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_object_types.csv"
],
[
"OBT299",
"kayak",
"qajaq",
"object-type",
"Things",
"F1.7",
"AM-ARC;AS-NTH",
"",
"",
"Ancient",
"A covered skin boat fitted to one hunter.",
"sealskin; driftwood; bone",
"Greenlandic qajaq",
"transport;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R2",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT300",
"reed boat",
"tankwa; balsa de totora; mashuf",
"object-type",
"Things",
"THEME",
"AM-AND;WA-MES;AF-HRN;WA-ARB",
"-5000",
"",
"Bitumen-coated reed boat remains at H3 As-Sabiyah (Kuwait) c. 5000 BCE",
"Boats bound from reed bundles.",
"totora; papyrus; bitumen",
"Titicaca totora balsas; tankwa; Marsh Arab boats",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R2",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT301",
"birchbark canoe",
"wiigwaasi-jiimaan",
"object-type",
"Things",
"F1.7",
"AM-EWD",
"",
"",
"Pre-contact",
"A light canoe of birchbark on a cedar frame.",
"birchbark; spruce root; cedar; pitch",
"Anishinaabe and Wabanaki canoes",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R2",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT302",
"dugout canoe",
"pirogue",
"object-type",
"Things",
"THEME",
"GL",
"-8000",
"",
"Pesse canoe c. 8000 BCE; Dufuna canoe c. 6000 BCE",
"A boat carved from one log.",
"tree trunk; adze; fire",
"Pesse canoe; Dufuna canoe",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT303",
"coracle",
"quffa; thúng chai",
"object-type",
"Things",
"THEME",
"WA-MES;EU-BLC;AS-SAS;AS-MSE",
"",
"",
"Ancient",
"A round boat of woven frame covered with hide or pitch.",
"willow; hide; bitumen",
"Iraqi quffa; Welsh coracle; Vietnamese basket boat",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT304",
"balsa raft",
"jangada",
"object-type",
"Things",
"F1.7",
"AM-AND",
"",
"",
"Pre-Hispanic",
"Sailing rafts of balsa logs steered with centreboards.",
"balsa; guares",
"guares raft",
"transport;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT305",
"plank-built boat",
"Khufu ship; Abydos boats",
"object-type",
"Things",
"F1.6",
"AF-EGY",
"-3000",
"",
"Abydos boats c. 3000 BCE; Khufu ship c. 2500 BCE",
"Boats of planks lashed and joined, some buried beside kings.",
"cedar; rope lashing; mortise-and-tenon",
"Khufu ship; Abydos boats",
"transport;ritual and belief",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.28a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT306",
"wheeled cart",
"wagon; cart",
"object-type",
"Things",
"THEME",
"WA-MES;EU-EER;EU-WCE",
"-3500",
"",
"c. 3500–3300 BCE",
"A wheeled vehicle drawn by animals.",
"wood; axles",
"Ljubljana Marshes wheel; Bronocice pot",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R1",
"F1.5",
"high",
"",
"canon_object_types.csv"
],
[
"OBT307",
"chariot",
"chariot",
"object-type",
"Things",
"F1.12a;THEME",
"AS-CEN;AF-EGY;AS-CHN",
"-2000",
"",
"Sintashta c. 2000 BCE",
"A light two-wheeled spoked vehicle.",
"spoked wheel; bent wood",
"Sintashta burials; Tutankhamun's chariots; Shang chariot burials",
"transport;war;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R2",
"F1.5;F1.19a",
"high",
"",
"canon_object_types.csv"
],
[
"OBT308",
"saddle",
"saddle",
"object-type",
"Things",
"THEME",
"AS-CEN;GL",
"-400",
"",
"Pazyryk soft saddles c. 5th–3rd century BCE",
"A seat for riding.",
"felt; leather; wooden tree",
"Pazyryk saddles",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT309",
"stirrup",
"stirrup",
"object-type",
"Things",
"F1.8;F1.12a",
"AS-CHN;AS-KOR;AS-CEN",
"302",
"",
"Single mounting stirrup (Changsha figurine) 302; paired stirrups (Feng Sufu tomb) 415",
"A foot support hung from the saddle.",
"iron; bronze; wood",
"Feng Sufu stirrups",
"transport;war",
"museum and archaeological typology; makers' own terms where known",
"",
"funerary",
"Wikimedia Commons",
"R2",
"F1.13;F1.3",
"medium",
"Lynn White's \"stirrup thesis\" on feudalism is a how-histories-get-written case (F1.3).",
"canon_object_types.csv"
],
[
"OBT310",
"bridle and bit",
"bit",
"object-type",
"Things",
"THEME",
"AS-CEN;WA-ANA",
"-2000",
"",
"Bits and cheekpieces with Sintashta chariots; earlier bit wear debated",
"A bit and headstall controlling a horse.",
"bronze; iron; leather; antler cheekpieces",
"Sintashta cheekpieces",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT311",
"camel saddle",
"shadad; North Arabian saddle; tamzak",
"object-type",
"Things",
"F1.10;F1.6",
"WA-ARB;AF-SAH",
"-500",
"",
"North Arabian saddle c. 500–100 BCE (approximate)",
"Saddles that made camels usable for war and caravan.",
"wood; leather",
"Tuareg tamzak; Arabian shadad",
"transport;war",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT312",
"dog sled",
"qamutiik; nart",
"object-type",
"Things",
"F1.7",
"AM-ARC;AS-NTH",
"",
"",
"Zhokhov Island (Siberia) sled dogs c. 9,000 BP",
"A sledge drawn by dogs.",
"driftwood; bone; sinew",
"qamutiik",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT313",
"snowshoes",
"snowshoe",
"object-type",
"Things",
"THEME",
"AM-EWD;AM-ARC;AS-NTH",
"",
"",
"Ancient",
"Frames spreading weight over snow.",
"ash; rawhide",
"",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT314",
"skis",
"ski",
"object-type",
"Things",
"THEME",
"EU-EER;EU-SCA;AS-NTH",
"-6300",
"",
"Vis I (Russia) c. 6300 BCE",
"Boards for gliding over snow.",
"pine",
"Vis I ski; Kalvträsk ski",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT315",
"travois",
"travois",
"object-type",
"Things",
"F1.7",
"AM-WST",
"",
"",
"Pre-contact",
"A frame dragged by dog or horse.",
"poles; hide",
"",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"Indigenous-community",
"Wikimedia Commons; Library of Congress (PD items)",
"R3",
"F1.29",
"high",
"",
"canon_object_types.csv"
],
[
"OBT316",
"palanquin",
"palki; litter; gama",
"object-type",
"Things",
"THEME",
"AS-SAS;AS-KOR;AS-CHN;AM-AND",
"",
"",
"Ancient",
"A covered chair carried by bearers.",
"wood; lacquer; textile",
"Korean gama; Inka litter",
"transport;rule and display",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; e-museum Korea (KOGL Type 1)",
"R3",
"F1.23",
"medium",
"",
"canon_object_types.csv"
],
[
"OBT317",
"rickshaw",
"jinrikisha",
"object-type",
"Things",
"THEME",
"AS-JPN;AS-SAS",
"1869",
"",
"Japan c. 1869",
"A two-wheeled cart pulled by a runner, later by a cyclist.",
"wood; iron; bicycle parts",
"Dhaka cycle rickshaw",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.23",
"high",
"",
"canon_object_types.csv"
],
[
"OBT318",
"bicycle",
"bicycle",
"object-type",
"Things",
"THEME",
"GL",
"1817",
"",
"Draisine 1817; safety bicycle 1885",
"A human-powered two-wheeler.",
"steel tubes",
"Rover safety bicycle; Flying Pigeon",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT319",
"motor car",
"automobile",
"object-type",
"Things",
"THEME",
"GL",
"1886",
"",
"Benz Patent-Motorwagen 1886",
"A self-propelled road vehicle.",
"steel; internal combustion engine",
"Benz Patent-Motorwagen; Ford Model T",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19;F1.22",
"high",
"",
"canon_object_types.csv"
],
[
"OBT320",
"railway locomotive",
"locomotive",
"object-type",
"Things",
"THEME",
"GL",
"1804",
"",
"Trevithick 1804",
"A steam or electric engine that pulls trains.",
"iron; steam",
"Rocket; Shinkansen 0 Series",
"transport",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT321",
"aircraft",
"aeroplane",
"object-type",
"Things",
"THEME",
"GL",
"1903",
"",
"Wright Flyer 1903",
"A heavier-than-air flying machine.",
"spruce; aluminium; composites",
"Wright Flyer; DC-3",
"transport;war",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_object_types.csv"
],
[
"OBT322",
"shipping container",
"intermodal container",
"object-type",
"Things",
"F1.13;THEME",
"GL",
"1956",
"",
"McLean 1956; ISO standard 1968",
"A standard steel box that remade global trade.",
"corrugated steel",
"ISO 20-foot container",
"transport;exchange and value",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons",
"R2",
"F1.13;F1.22",
"high",
"",
"canon_object_types.csv"
],
[
"OBT323",
"magnetic compass",
"compass",
"object-type",
"Things",
"F1.8;THEME",
"AS-CHN;GL",
"1088",
"",
"Described by Shen Kuo 1088; navigation use by 1117",
"A magnetised needle showing direction.",
"lodestone; steel needle",
"dry compass; wet compass",
"transport;tools",
"museum and archaeological typology; makers' own terms where known",
"",
"none",
"Wikimedia Commons; Science Museum Group collection (link out; data CC0)",
"R2",
"F1.13",
"high",
"",
"canon_object_types.csv"
],
[
"PER001",
"Imhotep",
"Imhotep of Heliopolis",
"person",
"People",
"F1.6",
"AF-EGY",
"-2680",
"-2640",
"fl.; reign of Djoser (3rd Dynasty), approximate",
"Later Egyptian tradition credits the official Imhotep with designing the Step Pyramid of Djoser at Saqqara, the earliest large cut-stone monument in Egypt.",
"cut limestone;stepped mastaba construction",
"pyramid;funerary complex",
"ritual and belief;rule and display",
"Egyptian tradition (Manetho); Egyptologists, from his name on a Djoser statue base",
"the quarrymen, masons and rotating labour gangs who built the complex",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.23;F1.26",
"medium",
"His name and titles on a Djoser statue base are contemporary; the architect role is later tradition; he was later deified. links: DYN002; POL001",
"canon_people.csv"
],
[
"PER002",
"Irtysen",
"Irtisen",
"person",
"People",
"F1.6",
"AF-EGY",
"-2050",
"-2000",
"fl.; reign of Mentuhotep II (11th Dynasty), approximate",
"His funerary stela (Louvre C 14) is a rare Egyptian text in which a craftsman describes his own skills in carving and in preparing materials, which he says he taught only to his eldest son.",
"stone carving;pigment or inlay preparation",
"stela;statue",
"ritual and belief;record and writing",
"Egyptologists (Louvre stela C 14)",
"the workshop whose methods were kept within the family; the labourers who quarried and moved stone",
"funerary",
"Wikimedia Commons",
"R3",
"F1.28;F1.26",
"medium",
"Translations of the technical passage differ; check against the Louvre record. links: DYN003",
"canon_people.csv"
],
[
"PER003",
"Senenmut",
"Senmut",
"person",
"People",
"F1.6",
"AF-EGY",
"-1480",
"-1460",
"fl.; under Hatshepsut, death date unknown",
"The steward of Hatshepsut is associated with the design of her temple at Deir el-Bahari and appears in unusual block statues holding the princess Neferure.",
"limestone temple building;block statue",
"temple;statue",
"rule and display;ritual and belief",
"Egyptologists (titles, statues and tombs)",
"the builders and quarry labourers; the uncertainty over how much he himself designed",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.26",
"medium",
"Architect attribution is inferred from titles and proximity. links: DYN004",
"canon_people.csv"
],
[
"PER004",
"Hatshepsut",
"Maatkare Hatshepsut",
"person",
"People",
"F1.6",
"AF-EGY",
"-1479",
"-1458",
"reign dates, approximate",
"As king she commissioned the temple at Deir el-Bahari, obelisks at Karnak and an expedition to Punt whose return with incense trees is carved in her temple reliefs.",
"limestone architecture;granite obelisks;relief carving",
"temple;obelisk;statue",
"rule and display;ritual and belief;exchange and value",
"Egyptologists; her own inscriptions",
"the builders and voyagers; the people of Punt shown in the reliefs",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"The Met holds many statues from Deir el-Bahari. links: DYN004; POL001",
"canon_people.csv"
],
[
"PER005",
"Thutmose (sculptor)",
"Djehutymose",
"person",
"People",
"F1.6",
"AF-EGY",
"-1350",
"-1330",
"fl.; Amarna period, approximate",
"Excavators identified a house and workshop at Amarna as his from an inscribed fragment; it held plaster studies and the painted bust of Nefertiti.",
"limestone;gypsum plaster;painted surface",
"bust;portrait head;plaster study",
"rule and display",
"German excavators under Ludwig Borchardt (1912)",
"the assistants whose plaster and stone studies were found in the workshop",
"none",
"Wikimedia Commons",
"R3",
"F1.26;F1.24",
"medium",
"Identification rests on an ivory horse blinker naming a sculptor Thutmose; the bust is in Berlin and Egypt has asked for its return. links: STY082",
"canon_people.csv"
],
[
"PER006",
"Sennedjem",
"Sennedjem of Deir el-Medina",
"person",
"People",
"F1.6",
"AF-EGY",
"-1300",
"-1250",
"fl.; reigns of Seti I and Ramesses II, approximate",
"A workman of the royal tomb-builders' village, his painted tomb (TT1) and its coffins and furniture show what the royal craftsmen made for their own families.",
"wall painting;painted wooden coffins;rock-cut tomb",
"tomb painting;coffin;shabti;furniture",
"ritual and belief;rule and display",
"Egyptologists (tomb found intact in 1886); his own titles (\"Servant in the Place of Truth\")",
"his wife Iyneferti and relatives shown in the tomb; the fellow workmen who helped cut and paint it",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.23;F1.28",
"high",
"Verified round 2: the Met holds about 29 items from TT1, including the coffin sets of Iyneferti and of Khonsu; Sennedjem's own coffin set and sarcophagus are in Cairo (National Museum of Egyptian Civilization). links: MKR090",
"canon_people.csv"
],
[
"PER007",
"Amanishakheto",
"Kandake Amanishakheto",
"person",
"People",
"F1.6",
"AF-NUB",
"-10",
"10",
"fl.; late 1st century BCE to early 1st century CE, approximate",
"The Meroitic queen's pyramid at Meroe held gold jewellery that Giuseppe Ferlini found when he pulled down its top in 1834; the pieces are now in Munich and Berlin.",
"gold;cloisonné;glass inlay",
"jewellery;shield ring;armlet",
"clothing and adornment;rule and display",
"Meroitic inscriptions; Egyptologists",
"the Meroitic goldsmiths; Sudanese claims to objects now held abroad",
"funerary;conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24;F1.18",
"medium",
"Reign dates uncertain; parts of Ferlini's account are doubted. links: POL003",
"canon_people.csv"
],
[
"PER008",
"Giuseppe Ferlini",
"",
"person",
"People",
"F1.6;F1.11",
"AF-NUB",
"1797",
"1870",
"birth year given as 1797 or 1800",
"The Italian physician and treasure hunter pulled down pyramids at Meroe in 1834 and sold the gold he found to the royal collections in Munich and Berlin.",
"demolition;treasure hunting",
"jewellery",
"rule and display",
"himself (his published account); museum records",
"the Meroitic makers and the people buried there; Sudanese claims to the objects",
"conflict-looting;funerary",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"Treated as looting in current scholarship. links: POL003",
"canon_people.csv"
],
[
"PER009",
"Gebre Mesqel Lalibela",
"Lalibela",
"person",
"People",
"F1.6",
"AF-HRN",
"1181",
"1221",
"reign dates, approximate",
"Ethiopian tradition credits the Zagwe king with ordering the rock-hewn churches of Lalibela, though archaeologists date parts of the complex earlier.",
"rock-cut architecture;relief carving",
"church",
"ritual and belief;rule and display",
"Ethiopian Orthodox tradition; hagiography (Gadla Lalibela)",
"the stone-cutters, whose names do not survive; builders of the earlier parts of the complex",
"sacred",
"Wikimedia Commons",
"R3",
"F1.17;F1.16",
"medium",
"The churches are active places of worship. links: DYN033",
"canon_people.csv"
],
[
"PER010",
"Zara Yaqob",
"Zar'a Ya'eqob",
"person",
"People",
"F1.6",
"AF-HRN",
"1434",
"1468",
"reign dates",
"The Solomonic emperor promoted devotion to Mary, which increased demand for painted Marian icons and illuminated books of the Miracles of Mary.",
"panel painting;manuscript illumination",
"icon;manuscript",
"ritual and belief;rule and display",
"Ethiopian royal chronicles; art historians",
"the monastic painters, among them Fre Seyon, and the scribes",
"sacred",
"Wikimedia Commons;Walters Art Museum (CC0)",
"R3",
"F1.17;F1.16",
"high",
"links: POL007",
"canon_people.csv"
],
[
"PER011",
"Fre Seyon",
"",
"person",
"People",
"F1.6",
"AF-HRN",
"1445",
"1480",
"fl.; approximate",
"The monk-painter is the earliest named Ethiopian painter to whom surviving icons of Mary and Child are attributed, working in the reign of Zara Yaqob.",
"tempera on gessoed panel",
"icon;diptych",
"ritual and belief",
"art historians (Marilyn Heldman), from inscriptions naming him",
"workshop assistants and unnamed monastic painters",
"sacred",
"Wikimedia Commons",
"R3",
"F1.26;F1.16",
"medium",
"Attributions rest on a few inscribed icons.",
"canon_people.csv"
],
[
"PER012",
"Tewodros II",
"Kassa Hailu",
"person",
"People",
"F1.6",
"AF-HRN",
"1818",
"1868",
"born c. 1818; reigned 1855–1868",
"The emperor gathered manuscripts, crowns and church objects at Maqdala, which British forces took after his death in 1868; hundreds of manuscripts went to British libraries and museums.",
"manuscript collecting;court patronage",
"manuscript;crown;tabot",
"rule and display;ritual and belief",
"Ethiopian chronicles; British expedition records",
"the scribes and craftsmen whose work he gathered; the Ethiopian Church's claim to the tabotat",
"conflict-looting;sacred",
"British Library digitised manuscripts (public-domain items);Wikimedia Commons",
"R3",
"F1.24;F1.19a",
"high",
"Tabotat must not be displayed. links: POL007",
"canon_people.csv"
],
[
"PER013",
"Richard Rivington Holmes",
"Richard Holmes",
"person",
"People",
"F1.6;F1.11",
"AF-HRN;EU-BLC",
"1835",
"1911",
"",
"The British Museum's representative on the 1868 Maqdala expedition bought looted manuscripts and objects at the army's prize auction for British collections.",
"purchase at prize auction",
"manuscript;processional cross;crown",
"rule and display",
"British Museum records",
"the Ethiopian makers and owners; the soldiers' looting that came before the auction",
"conflict-looting",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"Later Royal Librarian at Windsor.",
"canon_people.csv"
],
[
"PER014",
"Olowe of Ise",
"Olowe",
"person",
"People",
"F1.6",
"AF-GUI",
"1873",
"1938",
"born c. 1873–75, died 1938",
"The Yorùbá carver made palace doors, veranda posts and lidded bowls for Ekiti rulers; a door he carved for the Ogoga of Ikere went to the British Empire Exhibition in 1924 and then to the British Museum.",
"wood carving;high relief;polychromy",
"veranda post;palace door;lidded bowl",
"rule and display;ritual and belief",
"Yorùbá oral praise (oriki); art historians (Roslyn Walker)",
"the assistants who roughed out his work; the exchange by which the Ikere door left Nigeria",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons;collection search link-out only (works in copyright)",
"R1",
"F1.26;F1.24;F1.17",
"high",
"Useful for attribution: named by praise poetry, not signature. links: EVT012",
"canon_people.csv"
],
[
"PER015",
"Areogun",
"Areogun of Osi-Ilorin",
"person",
"People",
"F1.6",
"AF-GUI",
"1880",
"1954",
"approximate",
"The Yorùbá carver from Osi-Ilorin made Epa masks, doors and figures for shrines and palaces, and later also for church and colonial patrons.",
"wood carving",
"Epa mask;door;figure",
"ritual and belief;rule and display",
"art historians; Yorùbá oral record",
"his workshop, including his son George Bandele",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER016",
"Lamidi Olonade Fakeye",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1928",
"2009",
"",
"The Yorùbá carver trained at the Oye-Ekiti Catholic workshop and made doors and figures for churches, universities and collectors, carrying an Ekiti carving lineage into modern institutions.",
"wood carving",
"door;panel;figure",
"ritual and belief;rule and display",
"himself; art historians",
"his teacher George Bandele and the lineage workshop",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.29;F1.17",
"high",
"",
"canon_people.csv"
],
[
"PER017",
"Esigie",
"Oba Esigie",
"person",
"People",
"F1.6",
"AF-GUI",
"1504",
"1550",
"reign dates, approximate",
"Benin tradition links the Oba's reign to brass plaques, ivory pendant masks made for his mother Idia and early trade with the Portuguese that brought brass in quantity.",
"lost-wax casting;ivory carving",
"plaque;pendant mask;commemorative head",
"rule and display;ritual and belief",
"Benin court historians; art historians",
"the Igun Eronmwon casters and Igbesanmwan carvers who made the works",
"conflict-looting",
"Digital Benin (licence per lending museum);Met Open Access (CC0);British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.17;F1.24",
"medium",
"Dating plaques to his reign is debated. links: DYN038; POL026; MKR001; MKR002",
"canon_people.csv"
],
[
"PER018",
"Idia",
"Iyoba Idia",
"person",
"People",
"F1.6",
"AF-GUI",
"1504",
"1550",
"fl.; mother of Esigie, approximate",
"The first Iyoba (Queen Mother) of Benin is associated with ivory pendant masks worn at court, several of which were taken in 1897.",
"ivory carving;iron inlay",
"pendant mask;commemorative head",
"rule and display;ritual and belief",
"Benin court tradition; art historians",
"the ivory carvers; the women of the court beyond royal title-holders",
"conflict-looting",
"Met Open Access (CC0);British Museum Collection Online (CC BY-NC-SA, link out);Digital Benin (licence per lending museum);Wikimedia Commons",
"R3",
"F1.17;F1.24;F1.18",
"medium",
"The masks' identification with Idia is traditional. links: MKR002",
"canon_people.csv"
],
[
"PER019",
"Ovonramwen Nogbaisi",
"Oba Ovonramwen",
"person",
"People",
"F1.6",
"AF-GUI",
"1857",
"1914",
"born c. 1857; reigned 1888–1897",
"The Oba reigned when British forces took Benin City in 1897 and removed thousands of court objects; he died in exile in Calabar.",
"court patronage",
"altar object;plaque;commemorative head",
"rule and display",
"Benin court; British records",
"the guild casters and carvers whose work was taken",
"conflict-looting",
"Digital Benin (licence per lending museum);Wikimedia Commons",
"R3",
"F1.24;F1.19a",
"high",
"links: DYN038; POL026",
"canon_people.csv"
],
[
"PER020",
"Ewuare II",
"Oba Ewuare II",
"person",
"People",
"F1.6",
"AF-GUI",
"1953",
"",
"born 1953; crowned 2016; living",
"The present Oba is a leading claimant for the return of Benin works taken in 1897 and the head of the court under which the casting and carving guilds still work.",
"court patronage",
"altar object",
"rule and display",
"Benin palace",
"the guild members; other Nigerian bodies in disputes over custody",
"conflict-looting;living-community",
"Digital Benin (licence per lending museum);community-published site (link-out)",
"R3",
"F1.24",
"high",
"Custody of returned objects has been disputed between the palace and state bodies. links: INS082",
"canon_people.csv"
],
[
"PER021",
"Harry Rawson",
"Sir Harry Holdsworth Rawson",
"person",
"People",
"F1.6;F1.11",
"AF-GUI;EU-BLC",
"1843",
"1910",
"",
"The British admiral commanded the 1897 punitive expedition that burned Benin City and removed its brass and ivory works, many later auctioned in London.",
"military expedition",
"plaque;commemorative head;carved tusk",
"war",
"British Admiralty records",
"the Benin guild makers; the people killed in the attack",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24;F1.19a",
"high",
"links: POL026; POL137",
"canon_people.csv"
],
[
"PER022",
"Felix von Luschan",
"",
"person",
"People",
"F1.11;F1.6",
"EU-WCE;AF-GUI",
"1854",
"1924",
"",
"The Berlin museum curator acquired hundreds of Benin works after 1897 and published Die Altertümer von Benin (1919), building one of the largest holdings.",
"museum acquisition;catalogue",
"plaque;commemorative head",
"rule and display",
"himself",
"the Benin makers; the soldiers and dealers who supplied him",
"conflict-looting",
"Digital Benin (licence per lending museum);Internet Archive (public-domain scans)",
"R3",
"F1.24;F1.3",
"high",
"He also collected human remains; that collection raises further issues.",
"canon_people.csv"
],
[
"PER023",
"Augustus Pitt Rivers",
"Augustus Henry Lane Fox Pitt Rivers",
"person",
"People",
"F1.11",
"EU-BLC",
"1827",
"1900",
"",
"The army officer and collector arranged objects in typological series meant to show technical evolution and gave his collection to Oxford in 1884.",
"typological display;excavation",
"weapon;tool;lock and key",
"tools;war",
"himself; Oxford University",
"the makers of the objects; the people from whom Benin and other works were taken",
"conflict-looting",
"Pitt Rivers Museum Collections Online (link out);Wikimedia Commons",
"R2",
"F1.24;F1.3",
"high",
"He bought Benin works after 1897 for his second, private museum at Farnham. links: INS053",
"canon_people.csv"
],
[
"PER024",
"Mansa Musa",
"Musa Keita I",
"person",
"People",
"F1.6",
"AF-SAH",
"1312",
"1337",
"reign dates, approximate",
"The Mali ruler's pilgrimage to Mecca in 1324 spent so much gold in Cairo that chroniclers noted its effect, and tradition says he brought the poet-architect al-Sahili back with him.",
"patronage;gold exchange",
"mosque;manuscript",
"rule and display;exchange and value;ritual and belief",
"Arabic chroniclers (al-Umari); the Catalan Atlas (1375)",
"the gold miners of Bambuk and Bure; the enslaved people who travelled in his caravan",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"links: POL036; DYN034; NET010",
"canon_people.csv"
],
[
"PER025",
"Abu Ishaq al-Sahili",
"Abu Ishaq Ibrahim al-Sahili",
"person",
"People",
"F1.10;F1.6",
"AF-SAH;EU-IBE",
"1290",
"1346",
"born c. 1290 in Granada; died 1346 in Timbuktu",
"The Andalusi poet is credited by tradition with designing a palace and the Djinguereber mosque for Mansa Musa, though the earthen building tradition he worked in was local.",
"earthen architecture",
"mosque;palace",
"ritual and belief;rule and display",
"Ibn Battuta and Ibn Khaldun; later tradition",
"the local masons who built and maintain the mosques",
"none",
"Wikimedia Commons",
"R3",
"F1.26;F1.13",
"medium",
"Attribution is traditional and debated. links: POL036",
"canon_people.csv"
],
[
"PER026",
"Ismaila Traoré",
"Ismaïla Traoré",
"person",
"People",
"F1.6",
"AF-SAH",
"1906",
"1907",
"fl.; life dates unknown",
"As head of the Djenné masons' guild he led the rebuilding of the Great Mosque of Djenné, completed in 1907.",
"mud brick;earth plaster;toron beams",
"mosque",
"ritual and belief",
"Djenné oral tradition; French colonial records",
"the masons' guild and the townspeople who replaster the mosque each year",
"none",
"Wikimedia Commons",
"R3",
"F1.29;F1.23",
"medium",
"Dates are his floruit only.",
"canon_people.csv"
],
[
"PER027",
"Abdel Kader Haidara",
"",
"person",
"People",
"F1.6",
"AF-SAH",
"1981",
"",
"fl.; took charge of his family library in 1981; birth year not verified; living",
"The Timbuktu librarian organised the evacuation of hundreds of thousands of manuscripts to Bamako in 2012–13 to protect them from occupying armed groups.",
"conservation;manuscript rescue",
"manuscript",
"record and writing",
"himself; press reports",
"the families who own the manuscripts and the couriers who carried them",
"living-community",
"community-published site (link-out)",
"R3",
"F1.24;F1.19a",
"high",
"Figures for manuscripts moved vary (about 350,000–377,000). links: MKR010",
"canon_people.csv"
],
[
"PER028",
"Osei Tutu",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1660",
"1717",
"approximate; died c. 1717",
"The founder of the Asante state is linked by tradition with the Golden Stool, the sacred seat of the nation, and with the rise of Kumasi's goldsmith and weaving crafts.",
"gold casting;regalia",
"stool;regalia",
"rule and display;ritual and belief",
"Asante oral tradition",
"the priest Okomfo Anokye whom tradition credits with bringing the Stool; the goldsmiths",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16;F1.17",
"medium",
"The Golden Stool is not displayed; do not illustrate. links: POL029; DYN039",
"canon_people.csv"
],
[
"PER029",
"Njoya",
"Ibrahim Njoya",
"person",
"People",
"F1.6",
"AF-CEN",
"1860",
"1933",
"born c. 1860s; ruled from c. 1886/89",
"The Bamum king created the Bamum script, ran royal workshops for brass casting, beadwork and weaving at Foumban and designed a new palace.",
"script invention;brass casting;beadwork",
"throne;manuscript;palace",
"record and writing;rule and display",
"Bamum court; German and French colonial records",
"the palace artisans and scribes; the women of the court who did much of the beadwork",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.17",
"high",
"His beaded throne was given to Kaiser Wilhelm II in 1908 (now Berlin). links: MKR004; POL025",
"canon_people.csv"
],
[
"PER030",
"Emil Torday",
"Torday Emil",
"person",
"People",
"F1.6;F1.11",
"AF-CEN;EU-BLC",
"1875",
"1931",
"",
"The Hungarian ethnographer collected thousands of Kuba and other Congo objects for the British Museum in 1907–09, including ndop figures.",
"collecting;ethnography",
"ndop figure;textile;cup",
"rule and display",
"himself; British Museum",
"the Kuba makers; the colonial conditions of acquisition",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: POL022; POL140",
"canon_people.csv"
],
[
"PER031",
"Leo Frobenius",
"",
"person",
"People",
"F1.11;F1.6",
"EU-WCE;AF-GUI",
"1873",
"1938",
"",
"The German ethnologist removed objects from Ife in 1910 and built theories of African culture circles from collections gathered on his expeditions.",
"expedition collecting;rock-art copying",
"head;rock-art copy",
"ritual and belief",
"himself",
"the Ife people and court from whom works were taken; his African assistants",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24;F1.3",
"high",
"The Olokun head he acquired was seized by the colonial authorities; the one in Ife may be a later copy. links: CIV011",
"canon_people.csv"
],
[
"PER032",
"Ladi Kwali",
"Hadiza Ladi Kwali",
"person",
"People",
"F1.6",
"AF-GUI",
"1925",
"1984",
"born c. 1925",
"The Gbari potter from Kwali made hand-built water pots and then, at the Abuja Pottery Training Centre, glazed stoneware that was shown in London (Berkeley Galleries, 1958–62), Paris and Washington.",
"coil building;wheel throwing;stoneware glaze",
"water pot;jar;bowl",
"food and storage;ritual and belief",
"herself; Michael Cardew; exhibitions",
"the Gbari women potters, including her aunt, from whom she learned",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R2",
"F1.18;F1.26;F1.20",
"high",
"Pictured on the Nigerian 20 naira note.",
"canon_people.csv"
],
[
"PER033",
"Michael Cardew",
"",
"person",
"People",
"F1.11;F1.6",
"EU-BLC;AF-GUI",
"1901",
"1983",
"",
"The English potter ran the Abuja Pottery Training Centre in northern Nigeria from 1951, after working at Vumë in Ghana, joining Leach-style stoneware to local potters' skills.",
"wheel throwing;stoneware;wood firing",
"jar;bowl;teapot",
"food and storage",
"himself (Pioneer Pottery, 1969)",
"the Nigerian and Ghanaian potters at Abuja and Vumë, few of whom are named",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.20;F1.26",
"high",
"links: MOV041",
"canon_people.csv"
],
[
"PER034",
"Uche Okeke",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1933",
"2016",
"",
"The Nigerian artist adapted Igbo uli body and wall designs, traditionally painted by women, into modern drawing and painting and taught this approach at Nsukka.",
"uli line drawing;ink",
"drawing;painting",
"clothing and adornment;ritual and belief",
"himself; the Zaria Art Society",
"the Igbo women uli painters whose motifs he adapted",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.2;F1.18",
"high",
"links: MOV072; SCH015",
"canon_people.csv"
],
[
"PER035",
"Ben Enwonwu",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1917",
"1994",
"",
"The Nigerian sculptor and painter, son of an Igbo carver, made public sculptures such as Anyanwu (1955) and had an early international career.",
"bronze casting;wood carving;painting",
"public sculpture;painting",
"rule and display",
"himself; art historians (Sylvester Ogbechie)",
"his father's carving practice; the Onitsha masquerade makers whose forms he painted",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER036",
"El Anatsui",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1944",
"",
"born 1944; living",
"The Ghanaian artist, long based at Nsukka, joins flattened bottle caps and foil seals with copper wire into large hangings that recall kente cloth and trade histories.",
"aluminium bottle caps;copper wire;assemblage",
"wall hanging;sculpture",
"exchange and value;ritual and belief",
"himself; museums",
"the studio assistants who cut, fold and join the caps",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.22;F1.13",
"high",
"links: MKR003; SCH015",
"canon_people.csv"
],
[
"PER037",
"Demas Nwoko",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"1935",
"",
"born 1935; living",
"The Nigerian artist and architect built the Dominican Chapel in Ibadan and his New Culture Studio, using local materials and forms shaped by climate.",
"architecture;concrete;earth;carving",
"chapel;studio;furniture",
"shelter;ritual and belief",
"himself; architectural critics",
"the builders and craftsmen who worked on his buildings",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"high",
"links: MOV072",
"canon_people.csv"
],
[
"PER038",
"Ibrahim El-Salahi",
"",
"person",
"People",
"F1.6;F1.10",
"AF-NUB",
"1930",
"",
"born 1930; living",
"The Sudanese painter drew on Arabic calligraphy and Sudanese decorative forms to help found the modernism of the Khartoum School.",
"drawing;painting;calligraphic line",
"painting;drawing",
"record and writing",
"himself; art historians (Salah Hassan)",
"the calligraphers and craft makers whose forms he adapted",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: SCH017; MOV077",
"canon_people.csv"
],
[
"PER039",
"Kamala Ibrahim Ishaq",
"",
"person",
"People",
"F1.6",
"AF-NUB",
"1939",
"",
"born 1939; living",
"The Sudanese painter co-founded the Crystalist group in 1976 and drew on women's zar spirit-possession gatherings in her work.",
"painting",
"painting",
"ritual and belief",
"herself; the Crystalist Manifesto",
"the women of the zar gatherings she painted",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER040",
"Chaibia Tallal",
"Chaïbia Talal",
"person",
"People",
"F1.6;F1.10",
"AF-MAG",
"1929",
"2004",
"",
"The self-taught Moroccan painter began in the 1960s and was exhibited in Europe, where critics framed her work as 'naive' or art brut, a label later questioned.",
"painting",
"painting",
"rule and display",
"herself; critics (Pierre Gaudibert)",
"the rural colour and textile traditions she drew on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.20",
"high",
"Check the critic credited with her 1966 debut.",
"canon_people.csv"
],
[
"PER041",
"Farid Belkahia",
"",
"person",
"People",
"F1.6;F1.10",
"AF-MAG",
"1934",
"2014",
"",
"The Casablanca School artist worked on hammered copper and on lambskin coloured with henna, taking materials and signs from Amazigh and urban crafts.",
"copper repoussé;henna on skin;natural dyes",
"wall piece;relief",
"rule and display",
"himself; the Casablanca School",
"the tanners, dyers and coppersmiths of Marrakech who prepared his materials",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.2",
"high",
"links: SCH018",
"canon_people.csv"
],
[
"PER042",
"Mohamed Melehi",
"",
"person",
"People",
"F1.6;F1.10",
"AF-MAG",
"1936",
"2020",
"",
"The Moroccan painter and designer of the Casablanca School made hard-edge wave paintings and covers for the review Souffles, and brought Amazigh crafts into art teaching.",
"painting;graphic design",
"painting;magazine cover;poster",
"record and writing",
"himself; the Casablanca School",
"fellow teachers Farid Belkahia, Toni Maraini and Bert Flint; the artisans whose work entered the syllabus",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.2",
"high",
"links: SCH018",
"canon_people.csv"
],
[
"PER043",
"Hassan Fathy",
"",
"person",
"People",
"F1.6",
"AF-EGY",
"1900",
"1989",
"",
"The Egyptian architect built New Gourna (from 1946) in mud brick with Nubian vault-building masons and argued for local building in Architecture for the Poor.",
"mud brick;Nubian vault;dome",
"house;village;mosque",
"shelter",
"himself (Gourna: A Tale of Two Villages, 1969)",
"the Nubian masons whose vaulting technique he used; the Gourna residents who resisted being moved",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R2",
"F1.22;F1.29",
"high",
"links: STY054",
"canon_people.csv"
],
[
"PER044",
"Ramses Wissa Wassef",
"",
"person",
"People",
"F1.6",
"AF-EGY",
"1911",
"1974",
"",
"The Egyptian architect founded a tapestry workshop at Harrania in 1952 where village children learned to weave their own designs directly on the loom without cartoons.",
"tapestry weaving;natural dyes",
"tapestry",
"clothing and adornment",
"himself; the art centre",
"his wife Sophie Habib Gorgy, who continued the centre; the weavers themselves",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: MKR017",
"canon_people.csv"
],
[
"PER045",
"Susanne Wenger",
"Adunni Olorisha",
"person",
"People",
"F1.6",
"AF-GUI",
"1915",
"2009",
"",
"The Austrian artist, who became an Osun priestess, worked with Yorùbá builders and sculptors of the New Sacred Art group to rebuild shrines in the Osun-Osogbo grove.",
"cement sculpture;earth architecture",
"shrine;sculpture",
"ritual and belief",
"herself; the Osun-Osogbo community",
"the Nigerian artists of the New Sacred Art group, such as Adebisi Akanji",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"The grove is a World Heritage site and active shrine.",
"canon_people.csv"
],
[
"PER046",
"Ulli Beier",
"",
"person",
"People",
"F1.6;F1.12",
"AF-GUI;OC-MEL",
"1922",
"2011",
"",
"The German editor co-founded the Mbari Club in Ibadan and the journal Black Orpheus and backed the Oshogbo workshops, shaping how Nigerian modern art reached foreign audiences; he later worked in Papua New Guinea.",
"editing;workshop organising",
"journal;exhibition",
"record and writing",
"himself",
"Georgina Beier, who ran workshops; the Nigerian co-founders of Mbari",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.17",
"high",
"links: INS001; SCH014",
"canon_people.csv"
],
[
"PER047",
"Nike Davies-Okundaye",
"Nike Okundaye",
"person",
"People",
"F1.6",
"AF-GUI",
"1951",
"",
"born 1951; living",
"The Yorùbá textile artist teaches adire indigo resist-dyeing through art centres in Osogbo, Lagos and elsewhere, keeping a women's craft in active training.",
"adire resist-dyeing;indigo;batik",
"textile;wrapper",
"clothing and adornment",
"herself",
"the women dyers of Osogbo from whom she learned",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: MKR006",
"canon_people.csv"
],
[
"PER048",
"Esther Mahlangu",
"",
"person",
"People",
"F1.6",
"AF-SOU",
"1935",
"",
"born 1935; living",
"The Ndebele painter carried women's homestead-painting designs onto canvas and objects, including a BMW Art Car in 1991.",
"wall painting;acrylic;feather brush",
"mural;car;canvas",
"shelter;clothing and adornment",
"herself; museums",
"the Ndebele women who paint homesteads without public credit",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.2",
"high",
"links: STY090",
"canon_people.csv"
],
[
"PER049",
"Noria Mabasa",
"",
"person",
"People",
"F1.6",
"AF-SOU",
"1938",
"",
"born 1938; living",
"The Venda artist worked first in clay and then in wood, a medium locally reserved for men, making large carved figures.",
"clay modelling;wood carving",
"figure;sculpture",
"ritual and belief",
"herself",
"the women potters whose practice she began in",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER050",
"Nesta Nala",
"",
"person",
"People",
"F1.6",
"AF-SOU",
"1940",
"2005",
"",
"The Zulu potter made burnished beer vessels (izinkamba) with raised amasumpa patterns and trained her daughters in the craft.",
"coil building;burnishing;pit firing",
"beer vessel",
"food and storage;ritual and belief",
"herself; museums",
"the women potters who taught her, including her mother",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER051",
"Bonnie Ntshalintshali",
"",
"person",
"People",
"F1.6",
"AF-SOU",
"1967",
"1999",
"",
"The Ardmore ceramicist made painted figurative sculptures of biblical and everyday scenes.",
"modelled earthenware;painted glaze",
"figure group",
"ritual and belief",
"herself; Ardmore studio",
"Fée Halsted, who founded Ardmore, and the other Ardmore artists",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"medium",
"",
"canon_people.csv"
],
[
"PER052",
"Kane Kwei",
"Seth Kane Kwei",
"person",
"People",
"F1.6",
"AF-GUI",
"1922",
"1992",
"",
"The Ga carpenter from Teshie is credited with popularising figurative coffins shaped as objects linked to the dead person's life.",
"wood carving;carpentry;painting",
"figurative coffin",
"ritual and belief",
"himself; Western collectors after 1974",
"other carpenters making such coffins, such as Ataa Oko; his apprentices, including Paa Joe",
"funerary",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.16",
"medium",
"Who first made such coffins is disputed. links: STY179",
"canon_people.csv"
],
[
"PER053",
"Edward Saidi Tingatinga",
"",
"person",
"People",
"F1.6",
"AF-SWA",
"1932",
"1972",
"",
"The Tanzanian painter began painting with enamel house paint on ceiling board in Dar es Salaam around 1968, founding a style continued by a cooperative.",
"enamel paint;board",
"painting",
"rule and display",
"himself; the Tingatinga cooperative",
"the relatives and apprentices who continued the style",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29",
"high",
"links: SCH013",
"canon_people.csv"
],
[
"PER054",
"Chéri Samba",
"",
"person",
"People",
"F1.6",
"AF-CEN",
"1956",
"",
"born 1956; living",
"The Kinshasa painter started as a sign painter and made text-and-image paintings central to Congolese popular painting.",
"acrylic painting;sign painting",
"painting",
"record and writing",
"himself; exhibitions (Magiciens de la Terre, 1989)",
"the sign-painting workshops and fellow popular painters",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.20",
"high",
"links: STY093; EVT027",
"canon_people.csv"
],
[
"PER055",
"Papa Ibra Tall",
"",
"person",
"People",
"F1.6",
"AF-SAH",
"1935",
"2015",
"",
"The Senegalese artist directed the tapestry workshop at Thiès from 1966, turning paintings of the École de Dakar into woven hangings.",
"tapestry weaving",
"tapestry",
"rule and display",
"himself; the Senegalese state",
"the weavers of Thiès who wove the tapestries",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.17",
"high",
"links: SCH016; POL240",
"canon_people.csv"
],
[
"PER056",
"Léopold Sédar Senghor",
"",
"person",
"People",
"F1.6",
"AF-SAH",
"1906",
"2001",
"",
"As Senegal's first president he funded the École de Dakar, the Thiès tapestry works and the 1966 World Festival of Negro Arts as state cultural policy.",
"state patronage",
"tapestry;painting",
"rule and display",
"himself; the Senegalese state",
"artists working outside the Negritude style the state favoured",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.15",
"high",
"links: MOV073; EVT022; POL240",
"canon_people.csv"
],
[
"PER057",
"Felwine Sarr",
"",
"person",
"People",
"F1.6;THEME",
"AF-SAH",
"1972",
"",
"born 1972; living",
"The Senegalese economist co-wrote with Bénédicte Savoy the 2018 report to the French president that recommended returning African objects taken in the colonial period.",
"report writing;provenance review",
"report",
"record and writing",
"himself; the French presidency",
"the communities of origin consulted unevenly; museum staff in Africa",
"living-community",
"open-access report or journal article (link out)",
"R3",
"F1.24",
"high",
"The report is openly available.",
"canon_people.csv"
],
[
"PER058",
"Bénédicte Savoy",
"",
"person",
"People",
"F1.11;THEME",
"EU-WCE",
"1972",
"",
"born 1972; living",
"The French art historian co-wrote the 2018 restitution report and has written on the history of European museums' demands for and refusals of returns.",
"provenance research",
"report;book",
"record and writing",
"herself",
"earlier African restitution claims and claimants, such as those of the 1970s",
"living-community",
"open-access report or journal article (link out)",
"R3",
"F1.24;F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER059",
"Nana Oforiatta Ayim",
"",
"person",
"People",
"F1.6",
"AF-GUI",
"2019",
"",
"fl.; curated Ghana's first Venice Biennale pavilion in 2019; birth year not verified; living",
"The Ghanaian writer and art historian curated Ghana's first Venice Biennale pavilion (2019) and leads a pan-African cultural encyclopaedia project.",
"curating;writing",
"exhibition;encyclopaedia",
"record and writing",
"herself",
"the makers and archivists documented by the encyclopaedia",
"living-community",
"community-published site (link-out)",
"R3",
"F1.24;F1.3",
"medium",
"Birth year could not be verified from a reliable source in the round-2 check, so a floruit is given.",
"canon_people.csv"
],
[
"PER060",
"Ranavalona I",
"",
"person",
"People",
"F1.6",
"AF-MAD",
"1778",
"1861",
"born c. 1778; reigned 1828–1861",
"The Merina queen used forced labour (fanompoana) to build Jean Laborde's foundries and workshops at Mantasoa, which made guns, glass, soap and textiles.",
"state workshops;forced labour",
"gun;glass;cloth",
"war;rule and display",
"Merina court records; missionary accounts",
"the forced labourers at Mantasoa, many of whom died",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"links: POL018",
"canon_people.csv"
],
[
"PER061",
"Jean Laborde",
"",
"person",
"People",
"F1.6",
"AF-MAD",
"1805",
"1878",
"",
"The French adventurer built an industrial complex at Mantasoa for Ranavalona I, casting cannon and making glass, soap and silk with thousands of forced labourers.",
"iron founding;glassmaking;soap making",
"cannon;glass;soap",
"war;tools",
"himself; Merina court",
"the forced labourers who did the work",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"links: POL018",
"canon_people.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
