insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PER062",
"Tippu Tip",
"Hamad bin Muhammad al-Murjabi",
"person",
"People",
"F1.6",
"AF-SWA;AF-CEN",
"1837",
"1905",
"born c. 1837",
"The Zanzibari trader ran caravans into the Congo basin that moved ivory to the coast for Indian, European and American workshops, using enslaved porters and trading enslaved people.",
"ivory trade;caravan trade",
"ivory tusk",
"exchange and value",
"himself (his autobiography); colonial records",
"the enslaved porters and captives; the elephant hunters",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.23",
"high",
"links: NET014; POL011",
"canon_people.csv"
],
[
"PER063",
"Ghezo",
"Guezo",
"person",
"People",
"F1.6",
"AF-GUI",
"1818",
"1858",
"reign dates",
"The Dahomey king's reign saw court appliqué cloths and brass works expand, funded in part by the Atlantic trade in enslaved people.",
"appliqué;brass casting",
"appliqué cloth;brass figure",
"rule and display;war",
"Dahomey court; European visitors' accounts",
"the enslaved people sold; the Yemadje and other court artisans",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.23",
"high",
"links: POL030; MKR005",
"canon_people.csv"
],
[
"PER064",
"Béhanzin",
"Gbêhanzin",
"person",
"People",
"F1.6",
"AF-GUI",
"1845",
"1906",
"born c. 1845; reigned 1889–1894",
"The last independent king of Dahomey's palace works, including royal statues, were taken by French forces in 1892; 26 of them were returned to Benin in 2021.",
"court patronage;wood carving;appliqué",
"royal statue;throne;door",
"rule and display",
"Dahomey court; French military records",
"the court artists who carved the royal statues, such as Sosa Adede",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"Attributions of the royal statues to named carvers need checking. links: POL030",
"canon_people.csv"
],
[
"PER065",
"Ibn Khaldun",
"Abd al-Rahman ibn Khaldun",
"person",
"People",
"F1.10;F1.6;THEME",
"AF-MAG",
"1332",
"1406",
"",
"The North African historian's Muqaddimah (1377) treats crafts as a product of settled urban life and explains their decline with the decline of cities.",
"historiography",
"text",
"record and writing",
"himself",
"rural and nomadic makers whom his model ranked below urban crafts",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.3;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER066",
"Muhammad Ali Pasha",
"Muhammad Ali of Egypt",
"person",
"People",
"F1.6",
"AF-EGY",
"1769",
"1849",
"",
"The governor of Egypt set up state factories for cotton spinning and weaving, arms and shipbuilding from the 1810s, staffed largely with conscripted workers.",
"state factories;cotton spinning;weaving",
"cloth;gun;ship",
"war;clothing and adornment",
"historians",
"the conscripted workers and the peasants forced to grow cotton",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"links: DYN008",
"canon_people.csv"
],
[
"PER067",
"Amina of Zazzau",
"Queen Amina",
"person",
"People",
"F1.6",
"AF-SAH",
"1550",
"1610",
"fl.; dates disputed: often given as reign c. 1576–1610 (16th century), but the Kano Chronicle makes her a contemporary of Muhammad Dauda (r. 1421–38)",
"Hausa tradition credits the queen of Zazzau with fortifying towns with earthen walls (ganuwar Amina).",
"earthen walls",
"town wall",
"war;shelter",
"Hausa oral tradition; the Kano Chronicle",
"the labourers and later rulers who built and kept the walls",
"none",
"Wikimedia Commons",
"R3",
"F1.29",
"low",
"Historicity is debated; written accounts are late. links: POL032",
"canon_people.csv"
],
[
"PER068",
"Reinata Sadimba",
"",
"person",
"People",
"F1.6",
"AF-SWA",
"1945",
"",
"born 1945; living",
"The Makonde artist makes figurative ceramic sculptures, extending a pot-making practice associated with Makonde women.",
"coil-built clay;open firing",
"sculpture;pot",
"ritual and belief",
"herself",
"the Makonde women potters from whom she learned",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"medium",
"Birth year verified (AWARE). links: STY177",
"canon_people.csv"
],
[
"PER069",
"Magdalene Odundo",
"",
"person",
"People",
"F1.6;F1.11",
"AF-SWA;EU-BLC",
"1950",
"",
"born 1950; living",
"The Kenyan-born potter, based in Britain, makes hand-built burnished vessels fired to black and orange, drawing on potters she studied in Nigeria and Kenya.",
"coil building;burnishing;reduction firing",
"vessel",
"food and storage",
"herself",
"the Gbari and other potters she learned from, including at Abuja",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER070",
"Margaret Trowell",
"",
"person",
"People",
"F1.6",
"AF-SWA",
"1904",
"1985",
"",
"The British teacher started art classes at Makerere in Kampala in 1937 that became East Africa's leading art school.",
"art teaching",
"painting;craft",
"rule and display",
"herself (African Tapestry, 1957)",
"the Ugandan students and teachers who shaped the school",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: INS002",
"canon_people.csv"
],
[
"PER071",
"K'inich Janaab Pakal",
"Pakal the Great",
"person",
"People",
"F1.7",
"AM-MES",
"603",
"683",
"reigned 615–683",
"The Palenque king commissioned the Temple of the Inscriptions, whose tomb held his jade mosaic mask and a carved sarcophagus lid.",
"limestone relief;jade mosaic;stucco",
"sarcophagus;funerary mask;temple",
"rule and display;ritual and belief",
"Maya inscriptions; epigraphers",
"the sculptors and stucco workers of Palenque",
"funerary",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: CIV018",
"canon_people.csv"
],
[
"PER072",
"Lady Six Sky",
"Ix Wak Chanil Ajaw",
"person",
"People",
"F1.7",
"AM-MES",
"682",
"741",
"fl.; arrived at Naranjo 682, died 741",
"The noblewoman from Dos Pilas held power at Naranjo and is shown on stelae she commissioned standing over a captive.",
"limestone relief",
"stela",
"rule and display;war",
"Maya inscriptions; epigraphers",
"the sculptors of the Naranjo stelae; the captives shown",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"medium",
"Her exact title and role are debated. links: CIV018",
"canon_people.csv"
],
[
"PER073",
"Aj Maxam",
"Ah Maxam",
"person",
"People",
"F1.7",
"AM-MES",
"750",
"810",
"fl.; mid-to-late 8th century (Art Institute of Chicago); his father acceded at Naranjo in 765 and one study puts his birth in the 770s, so activity may run to c. 800",
"A painter-scribe of Naranjo, son of a Naranjo king and a noblewoman from Yaxha, signed polychrome drinking vessels, showing that elite Maya painters could be named.",
"slip painting;polychrome ceramic",
"cylinder vessel",
"record and writing;ritual and belief",
"epigraphers, from signatures on vessels",
"the potters who formed the vessels he painted",
"funerary",
"Wikimedia Commons",
"R3",
"F1.26;F1.28",
"medium",
"Verified round 2: the Water-Lily Vessel inscription names him, his royal Naranjo lineage and his parents; his mother was a lady of Yaxha. links: MKR021",
"canon_people.csv"
],
[
"PER074",
"Moctezuma II",
"Motecuhzoma Xocoyotzin",
"person",
"People",
"F1.7",
"AM-MES",
"1466",
"1520",
"reigned 1502–1520",
"The Mexica ruler kept featherworkers, goldsmiths and lapidaries whose work reached Europe through Cortés; a feather headdress in Vienna was later linked to him by tradition.",
"featherwork;gold casting;turquoise mosaic",
"headdress;shield;mosaic mask",
"rule and display;ritual and belief",
"Spanish chroniclers; Nahua accounts (Florentine Codex)",
"the amanteca featherworkers and other artisans who made the objects",
"conflict-looting",
"Wikimedia Commons;Digital Florentine Codex, Getty Research Institute (link out)",
"R3",
"F1.17;F1.24",
"high",
"The Vienna headdress's link to him is not proven; Mexico has asked for its return. links: POL051; MKR019",
"canon_people.csv"
],
[
"PER075",
"Diego de Alvarado Huanitzin",
"Huanitzin",
"person",
"People",
"F1.7",
"AM-MES;AM-LAT",
"1500",
"1541",
"born c. 1500",
"The Nahua governor of Mexico-Tenochtitlan sent the feather mosaic Mass of Saint Gregory (1539) to Pope Paul III, the earliest dated colonial featherwork.",
"feather mosaic",
"feather painting",
"ritual and belief",
"inscription on the work; art historians",
"the amanteca featherworkers who made it",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.2",
"high",
"The work is in the Musée des Jacobins, Auch. links: MKR019",
"canon_people.csv"
],
[
"PER076",
"Bernardino de Sahagún",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1499",
"1590",
"",
"The Franciscan friar directed the Florentine Codex (completed c. 1577), in which Nahua scholars and painters recorded crafts such as featherwork, goldsmithing and lapidary work.",
"ethnographic compilation;manuscript",
"codex",
"record and writing",
"himself",
"the Nahua scholars (Antonio Valeriano, Martín Jacobita, Pedro de San Buenaventura, Alonso Vegerano), the painters and the elders they interviewed",
"none",
"Digital Florentine Codex, Getty Research Institute (link out);Wikimedia Commons",
"R2",
"F1.28;F1.3;F1.26",
"high",
"links: INS009",
"canon_people.csv"
],
[
"PER077",
"Martín de la Cruz",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1552",
"1552",
"fl.; 1552",
"A Nahua physician at Tlatelolco wrote the illustrated herbal known as the Libellus de Medicinalibus Indorum Herbis (1552), translated into Latin by Juan Badiano.",
"herbal compilation;manuscript painting",
"herbal manuscript",
"care and access;record and writing",
"the manuscript; historians",
"the unnamed painters of the plant images; the translator Juan Badiano",
"none",
"Wikimedia Commons",
"R3",
"F1.28",
"high",
"The manuscript was returned from the Vatican to Mexico in 1990. links: INS009",
"canon_people.csv"
],
[
"PER078",
"Felipe Guaman Poma de Ayala",
"",
"person",
"People",
"F1.7",
"AM-AND",
"1535",
"1616",
"born c. 1535; died after 1615",
"The Andean author drew nearly 400 pages of images in his letter to the Spanish king, the Nueva corónica y buen gobierno (c. 1615), recording Andean labour, crafts and colonial abuse.",
"pen drawing;manuscript",
"chronicle",
"record and writing",
"himself; the Royal Danish Library, which holds it",
"the Andean weavers, khipu keepers and workers he drew",
"human-flow",
"community-published site (link-out);Wikimedia Commons",
"R2",
"F1.28;F1.23",
"high",
"The Royal Danish Library publishes a free facsimile; the drawings show forced labour. links: MKR024; MKR023",
"canon_people.csv"
],
[
"PER079",
"Pachacuti",
"Pachacuti Inca Yupanqui",
"person",
"People",
"F1.7",
"AM-AND",
"1438",
"1471",
"reign dates, approximate",
"Inca tradition credits the ruler with rebuilding Cuzco in fitted stone masonry and expanding a state that moved craft specialists and organised cloth production across the Andes.",
"fitted stone masonry;state cloth production",
"palace;terrace;textile",
"rule and display;shelter",
"Spanish chroniclers from Inca oral histories",
"the mit'a labourers, aqllakuna and relocated artisans who did the work",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.23",
"medium",
"Chronology is from chroniclers and debated. links: POL061; MKR023; MKR025",
"canon_people.csv"
],
[
"PER080",
"Diego Quispe Tito",
"",
"person",
"People",
"F1.7",
"AM-LAT;AM-AND",
"1611",
"1681",
"died c. 1681",
"The Quechua painter was a leading master of the Cuzco School, signing religious paintings that set European print compositions among Andean birds and landscapes.",
"oil painting;print-based composition",
"religious painting",
"ritual and belief",
"signatures; art historians",
"workshop assistants; the European printmakers whose compositions he adapted",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.14",
"high",
"links: SCH004",
"canon_people.csv"
],
[
"PER081",
"Aleijadinho",
"Antônio Francisco Lisboa",
"person",
"People",
"F1.7",
"AM-LAT",
"1738",
"1814",
"born c. 1738",
"The Brazilian sculptor and architect, son of a Portuguese builder and an enslaved African woman, carved soapstone prophets at Congonhas and church façades in Minas Gerais.",
"soapstone carving;wood carving;architecture",
"church façade;statue",
"ritual and belief",
"contracts; an 1858 biography by Rodrigo Bretas",
"the enslaved assistants in his workshop",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.26;F1.23",
"high",
"Some biographical details rest on the 1858 biography. links: POL072",
"canon_people.csv"
],
[
"PER082",
"Juan Correa",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1646",
"1716",
"approximate",
"The Afro-Mexican painter ran a large Mexico City workshop producing altarpieces, folding screens and religious paintings.",
"oil painting;folding screen",
"altarpiece;folding screen",
"ritual and belief;rule and display",
"art historians",
"his workshop assistants",
"none",
"Wikimedia Commons;LACMA Collections Online (public-domain images)",
"R3",
"F1.26",
"medium",
"links: POL069",
"canon_people.csv"
],
[
"PER083",
"José Guadalupe Posada",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1852",
"1913",
"",
"The Mexican printmaker engraved images for cheap broadsides, including the calavera skeletons later taken up as national symbols.",
"type-metal engraving;zinc etching",
"broadside;print",
"record and writing",
"himself; later artists who promoted him (Diego Rivera, Jean Charlot)",
"his publisher Antonio Vanegas Arroyo and other workshop engravers",
"none",
"Library of Congress (public-domain items);Wikimedia Commons",
"R2",
"F1.29;F1.2",
"high",
"",
"canon_people.csv"
],
[
"PER084",
"Gerardo Murillo",
"Dr. Atl",
"person",
"People",
"F1.7",
"AM-LAT",
"1875",
"1964",
"",
"The Mexican painter co-organised the 1921 exhibition of popular arts and wrote Las artes populares en México (1922), helping make folk craft a national emblem.",
"exhibition;writing",
"book;painting",
"rule and display",
"himself; the Mexican state",
"the makers whose work was shown, often without names",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.3;F1.29",
"high",
"links: POL076",
"canon_people.csv"
],
[
"PER085",
"Frida Kahlo",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1907",
"1954",
"",
"The Mexican painter wore Tehuana dress from the Isthmus of Tehuantepec as self-presentation, making Zapotec women's clothing an internationally known image.",
"painting;dress",
"painting;huipil",
"clothing and adornment",
"herself; museums (her clothes shown from 2004)",
"the Zapotec women who wove and embroidered the huipiles and skirts she wore",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.2;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER086",
"Clara Porset",
"",
"person",
"People",
"F1.7",
"AM-LAT;AM-CAR",
"1895",
"1981",
"",
"The Cuban-born designer, working in Mexico, redesigned the butaque chair with rural makers and organised the exhibition El arte en la vida diaria (1952).",
"furniture design;woven palm and ixtle",
"chair;furniture",
"shelter",
"herself",
"the rural carpenters and weavers who made her furniture",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER087",
"Pedro Friedeberg",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1936",
"2026",
"born 11 January 1936 in Florence; died 5 March 2026",
"The Italian-born Mexican artist is known for the Hand-Foot Chair (from 1962), a carved sculptural chair made by artisans.",
"carved wood;gilding",
"chair",
"shelter",
"himself",
"the carpenters who carve the chairs",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER088",
"Juan Quezada",
"",
"person",
"People",
"F1.7",
"AM-LAT;AM-WST",
"1940",
"2022",
"",
"The Chihuahua potter taught himself to make pots in the manner of ancient Paquimé (Casas Grandes) ware, starting the Mata Ortiz pottery revival in the 1970s.",
"coil building;burnishing;mineral paint",
"jar",
"food and storage",
"himself; the promoter Spencer MacCallum",
"the family potters of Mata Ortiz, such as his sister Lydia Quezada",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER089",
"Teodora Blanco",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1928",
"1980",
"",
"The Oaxacan potter of Santa María Atzompa modelled clay figures of women with applied decoration that became widely collected.",
"modelled clay;appliqué",
"figure",
"ritual and belief",
"herself; collectors",
"the Atzompa family potters who continued her designs",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.18",
"medium",
"",
"canon_people.csv"
],
[
"PER090",
"Rosa Real Mateo",
"Doña Rosa",
"person",
"People",
"F1.7",
"AM-LAT",
"1900",
"1980",
"born c. 1900",
"The potter of San Bartolo Coyotepec is credited with burnishing black clay before firing to give it a shiny surface in the 1950s.",
"burnishing;reduction firing",
"jar;figure",
"food and storage",
"her family workshop; tourism writers",
"the earlier Coyotepec potters whose matte black ware she changed",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.18",
"medium",
"",
"canon_people.csv"
],
[
"PER091",
"Hector Hyppolite",
"",
"person",
"People",
"F1.7",
"AM-CAR",
"1894",
"1948",
"",
"The Haitian Vodou priest and painter joined the Centre d'Art in 1944 and became its best-known artist, painting the lwa with house paint and feathers.",
"enamel house paint;painting",
"painting",
"ritual and belief",
"himself; the Centre d'Art; André Breton",
"the Vodou communities whose spirits he painted",
"sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.26",
"high",
"links: INS018",
"canon_people.csv"
],
[
"PER092",
"Edna Manley",
"",
"person",
"People",
"F1.7",
"AM-CAR",
"1900",
"1987",
"",
"The English-born Jamaican sculptor carved figures such as Negro Aroused (1935) and helped found Jamaica's school of art.",
"wood carving;bronze",
"sculpture",
"rule and display",
"herself",
"the Jamaican students and artists at the school",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER093",
"Amelia Peláez",
"",
"person",
"People",
"F1.7",
"AM-CAR",
"1896",
"1968",
"",
"The Cuban painter took the stained-glass fanlights and ironwork of colonial Havana houses into paintings, ceramics and murals.",
"painting;ceramics;mural",
"painting;ceramic;mural",
"shelter",
"herself",
"the anonymous glaziers and ironworkers of colonial Havana",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.15",
"high",
"",
"canon_people.csv"
],
[
"PER094",
"Lina Bo Bardi",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1914",
"1992",
"",
"The Italian-born Brazilian architect designed the São Paulo Museum of Art and SESC Pompéia and collected and exhibited northeastern Brazilian popular objects.",
"concrete;architecture;exhibition design",
"museum;chair;exhibition",
"shelter",
"herself",
"the northeastern makers whose objects she exhibited",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER095",
"Oscar Niemeyer",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1907",
"2012",
"",
"The Brazilian architect designed the main buildings of Brasília in curved reinforced concrete.",
"reinforced concrete",
"public building;church",
"shelter;rule and display",
"himself",
"the migrant workers (candangos) who built Brasília; engineer Joaquim Cardozo",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: STY075",
"canon_people.csv"
],
[
"PER096",
"Roberto Burle Marx",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1909",
"1994",
"",
"The Brazilian landscape designer planted gardens with native species and designed the wave-patterned pavements of Copacabana.",
"landscape design;mosaic paving;tile",
"garden;pavement",
"shelter",
"himself",
"the gardeners and plant collectors, and local plant knowledge he drew on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.22",
"high",
"",
"canon_people.csv"
],
[
"PER097",
"Lygia Clark",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1920",
"1988",
"",
"The Brazilian artist moved from hinged metal Bichos (1960) to objects made to be handled by participants in therapeutic sessions.",
"hinged metal;fabric;found materials",
"sculpture;relational object",
"care and access;play and music",
"herself",
"the participants whose handling completed the works",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: MOV064",
"canon_people.csv"
],
[
"PER098",
"Hélio Oiticica",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1937",
"1980",
"",
"The Brazilian artist made the Parangolés (from 1964), capes and banners worn in movement by samba dancers of Mangueira.",
"fabric;plastic;paint",
"cape;banner;installation",
"clothing and adornment;play and music",
"himself",
"the Mangueira samba school members who wore and helped shape the capes",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.4",
"high",
"links: MOV064; MOV065",
"canon_people.csv"
],
[
"PER099",
"Lygia Pape",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1927",
"2004",
"",
"The Brazilian artist made the Livro da criação and Divisor (1968), a huge cloth pierced for many heads worn by a crowd.",
"woodcut;book object;cloth",
"book;performance cloth",
"clothing and adornment;play and music",
"herself",
"the participants who wore Divisor",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: MOV064",
"canon_people.csv"
],
[
"PER100",
"Geraldo de Barros",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1923",
"1998",
"",
"The Brazilian artist co-founded the furniture cooperative Unilabor in 1954, where workers shared ownership of production.",
"furniture design;cooperative production",
"chair;table",
"shelter",
"himself",
"the Unilabor workers and the Dominican friar João Batista Pereira dos Santos who co-founded it",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.17",
"high",
"links: MOV063",
"canon_people.csv"
],
[
"PER101",
"Tarsila do Amaral",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1886",
"1973",
"",
"The Brazilian painter's Abaporu (1928) prompted the Antropofagia movement's idea of 'devouring' European culture.",
"oil painting",
"painting",
"rule and display",
"herself; Oswald de Andrade",
"the Afro-Brazilian and Indigenous imagery she drew on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.2;F1.20",
"high",
"links: MOV060",
"canon_people.csv"
],
[
"PER102",
"Joaquín Torres-García",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1874",
"1949",
"",
"The Uruguayan artist made wooden toys and constructive paintings and ran a workshop in Montevideo (from 1943) joining Andean signs with modernist grids.",
"painting;wood toys;workshop teaching",
"painting;toy",
"play and music",
"himself",
"the workshop members; the Andean makers whose signs he borrowed",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.2",
"high",
"links: SCH007",
"canon_people.csv"
],
[
"PER103",
"Gego",
"Gertrud Goldschmidt",
"person",
"People",
"F1.7",
"AM-LAT",
"1912",
"1994",
"",
"The German-born Venezuelan artist, trained as an architect, made the Reticulárea, room-filling nets of linked wire (from 1969).",
"wire;linking",
"installation",
"shelter",
"herself",
"the assistants who helped assemble the nets",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER104",
"Olga de Amaral",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1932",
"",
"born 1932; living",
"The Colombian textile artist makes woven and gilded hangings that combine fibre, gesso and gold leaf.",
"weaving;gold leaf;gesso",
"wall hanging",
"rule and display",
"herself",
"the weavers who work in her studio",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER105",
"Violeta Parra",
"",
"person",
"People",
"F1.7",
"AM-LAT",
"1917",
"1967",
"",
"The Chilean singer and artist made embroidered arpilleras and wool tapestries, shown at the Musée des Arts Décoratifs in Paris in 1964.",
"embroidery;arpillera;wool",
"tapestry",
"rule and display",
"herself",
"the rural women embroiderers whose techniques she used",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER106",
"Sheila Hicks",
"",
"person",
"People",
"F1.11;F1.7",
"AM-EWD;EU-WCE",
"1934",
"",
"born 1934; living",
"The American textile artist studied Andean weaving and worked in Mexico, Chile and India, making woven and wrapped works from miniatures to architectural scale.",
"weaving;wrapping",
"textile;wall hanging",
"rule and display",
"herself",
"the Andean weavers she studied; the workshops that wove her designs",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER107",
"Nampeyo",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1859",
"1942",
"born c. 1859",
"The Hopi-Tewa potter of Hano developed a style from ancient Sikyatki pottery designs, starting a family line of potters.",
"coil building;polished slip;mineral paint",
"jar;bowl",
"food and storage",
"herself; archaeologists and tourist promoters",
"her daughters, who painted her pots as her eyesight failed; the Hopi women potters around her",
"Indigenous-community",
"Smithsonian Open Access (CC0);Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked);community-published site (link-out)",
"R1",
"F1.26;F1.29;F1.2",
"high",
"Some communities follow protocols about images of the deceased; consult. links: MKR028; STY077",
"canon_people.csv"
],
[
"PER108",
"Maria Martinez",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1887",
"1980",
"",
"The San Ildefonso Pueblo potter and her husband Julian developed polished black-on-black ware around 1918–19, and her signature on pots from the 1920s changed how Pueblo pottery was sold.",
"coil building;burnishing;smudge firing",
"jar;plate",
"food and storage",
"herself; museum and dealer promotion",
"Julian and later relatives who painted her pots; other San Ildefonso potters whose pots she is said to have signed",
"Indigenous-community",
"Smithsonian Open Access (CC0);Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked);collection search link-out only (works in copyright)",
"R2",
"F1.26;F1.29;F1.18",
"high",
"Signing of other potters' work is reported; verify. links: STY077",
"canon_people.csv"
],
[
"PER109",
"Julian Martinez",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1879",
"1943",
"",
"The San Ildefonso painter decorated Maria Martinez's pots, developing matte-on-polished black designs such as the avanyu water serpent.",
"mineral paint;slip painting",
"jar;plate",
"food and storage",
"museum records",
"his role, often hidden by Maria's signature",
"Indigenous-community",
"Smithsonian Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.18",
"high",
"links: STY077",
"canon_people.csv"
],
[
"PER110",
"Margaret Tafoya",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1904",
"2001",
"",
"The Santa Clara Pueblo potter made large carved and polished black and red storage jars and passed her techniques to many descendants.",
"coil building;carving;burnishing",
"storage jar",
"food and storage",
"herself; family",
"the older Santa Clara potters she learned from",
"Indigenous-community",
"collection search link-out only (works in copyright);Smithsonian Open Access (CC0)",
"R3",
"F1.29;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER111",
"Lucy M. Lewis",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1898",
"1992",
"birth year given as 1890 to 1898",
"The Acoma Pueblo potter revived fine-line black-on-white designs from ancient Mimbres and other sherds.",
"coil building;fine-line painting",
"jar;bowl",
"food and storage",
"herself; museums",
"the ancestral potters whose designs she studied",
"Indigenous-community",
"collection search link-out only (works in copyright);Smithsonian Open Access (CC0)",
"R3",
"F1.29;F1.2",
"high",
"",
"canon_people.csv"
],
[
"PER112",
"Hosteen Klah",
"Hastiin Tłʼah",
"person",
"People",
"F1.7",
"AM-WST",
"1867",
"1937",
"",
"The Diné medicine man and weaver, recognised as nádleehí, wove textiles with sandpainting designs, which many Diné thought improper, and co-founded a museum with Mary Cabot Wheelwright.",
"handspun wool;tapestry weaving",
"rug;sandpainting textile",
"ritual and belief",
"himself; Wheelwright Museum",
"the Diné singers whose ceremonies the designs come from; his nieces who helped weave",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright);community-published site (link-out)",
"R3",
"F1.16;F1.18",
"high",
"Ceremonial designs are sacred; consult before showing. links: STY078",
"canon_people.csv"
],
[
"PER113",
"Mary Cabot Wheelwright",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1878",
"1958",
"",
"The Boston collector founded the House of Navajo Religion (1937, now the Wheelwright Museum) in Santa Fe with Hosteen Klah.",
"collecting;museum founding",
"sandpainting textile;recording",
"ritual and belief",
"herself",
"the Diné singers whose knowledge she recorded",
"sacred;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.24",
"high",
"Museum returned some ceremonial items in the 1970s; verify.",
"canon_people.csv"
],
[
"PER114",
"Daisy Taugelchee",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1909",
"1990",
"",
"The Diné weaver from Two Grey Hills spun very fine wool and wove tapestries of exceptional thread count in natural fleece colours.",
"handspinning;tapestry weaving",
"rug;tapestry",
"clothing and adornment;shelter",
"herself; museums",
"the Two Grey Hills weavers and traders who set the regional style",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: STY078",
"canon_people.csv"
],
[
"PER115",
"Juan Lorenzo Hubbell",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1853",
"1930",
"",
"The trader at Ganado encouraged Diné weavers to make rugs from designs painted for his catalogue, steering weaving towards a market of floor rugs.",
"trading;design catalogue",
"rug",
"exchange and value",
"himself; trading post records",
"the weavers, whose names were rarely recorded",
"Indigenous-community",
"community-published site (link-out);Wikimedia Commons",
"R3",
"F1.17;F1.21",
"high",
"links: INS013",
"canon_people.csv"
],
[
"PER116",
"Sequoyah",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1770",
"1843",
"born c. 1770",
"The Cherokee silversmith devised the Cherokee syllabary (1821), which spread quickly and was cast in type for the Cherokee Phoenix (1828).",
"syllabary design;silversmithing",
"syllabary;newspaper",
"record and writing",
"Cherokee Nation; historians",
"the Cherokee printers and his daughter Ayoka who helped demonstrate it",
"Indigenous-community",
"Library of Congress (public-domain items);Wikimedia Commons",
"R3",
"F1.5",
"high",
"links: POL065",
"canon_people.csv"
],
[
"PER117",
"Dat So La Lee",
"Louisa Keyser",
"person",
"People",
"F1.7",
"AM-WST",
"1850",
"1925",
"birth year uncertain; promoters claimed c. 1829",
"The Washoe basket weaver made fine coiled degikup baskets sold by the Carson City dealers Abe and Amy Cohn, who invented stories about her age and her designs' meanings.",
"coiled basketry;willow;bracken fern root",
"basket",
"food and storage;ritual and belief",
"herself; her dealers' certificates",
"the Washoe women weavers whose tradition she worked in; the dealers' fabrications",
"Indigenous-community",
"collection search link-out only (works in copyright);community-published site (link-out)",
"R2",
"F1.26;F1.21",
"high",
"Useful for how dealers built authorship.",
"canon_people.csv"
],
[
"PER118",
"Elsie Allen",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1899",
"1990",
"",
"The Pomo basket weaver broke with the custom of destroying a weaver's baskets at death and taught Pomo basketry to keep it alive.",
"coiled and twined basketry;sedge root;feathers",
"basket",
"food and storage;ritual and belief",
"herself (Pomo Basketmaking, 1972)",
"her mother and grandmother, whose baskets she kept",
"Indigenous-community",
"collection search link-out only (works in copyright);community-published site (link-out)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER119",
"Charles Edenshaw",
"Da.axiigang",
"person",
"People",
"F1.7",
"AM-NWC",
"1839",
"1920",
"born c. 1839",
"The Haida carver and jeweller made argillite carvings, engraved silver bracelets and painted hats, and drew designs for anthropologists Franz Boas and John Swanton.",
"argillite carving;silver engraving;painting",
"bracelet;argillite carving;hat",
"clothing and adornment;rule and display",
"himself; anthropologists; museums",
"his wife Isabella Edenshaw, who wove the spruce-root hats he painted",
"Indigenous-community",
"collection search link-out only (works in copyright);Smithsonian Open Access (CC0)",
"R2",
"F1.26;F1.18",
"high",
"links: STY076",
"canon_people.csv"
],
[
"PER120",
"Isabella Edenshaw",
"Kwii.aang",
"person",
"People",
"F1.7",
"AM-NWC",
"1858",
"1926",
"born c. 1858 (Museum of Anthropology, UBC; some sources give c. 1842); died 1926",
"The Haida weaver made spruce-root hats and baskets, several painted by her husband Charles Edenshaw, and is often left out of attributions to him.",
"spruce-root weaving",
"hat;basket",
"clothing and adornment",
"museum records; Haida family history",
"herself, when works are credited to Charles alone",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.18",
"medium",
"Dates checked round 2: MOA gives 1858–1926; birth year is disputed.",
"canon_people.csv"
],
[
"PER121",
"Willie Seaweed",
"Hilamas",
"person",
"People",
"F1.7",
"AM-NWC",
"1873",
"1967",
"born c. 1873",
"The Kwakwaka'wakw carver made masks, poles and potlatch objects with compass-drawn forms and continued carving while potlatches were banned.",
"wood carving;painting",
"mask;pole;headdress",
"ritual and belief;rule and display",
"himself; art historian Bill Holm",
"the potlatch hosts and dancers for whom the masks were made",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.16;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER122",
"Mungo Martin",
"Nakapankam",
"person",
"People",
"F1.7",
"AM-NWC",
"1879",
"1962",
"born c. 1879",
"The Kwakwaka'wakw carver restored and replicated poles for the University of British Columbia and the BC Provincial Museum from 1947 and built a big house in Victoria in 1953.",
"wood carving;painting",
"totem pole;house",
"rule and display;ritual and belief",
"himself; museum programmes",
"the apprentices he trained, including Henry Hunt and Tony Hunt",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.24;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER123",
"Ellen Neel",
"",
"person",
"People",
"F1.7",
"AM-NWC",
"1916",
"1966",
"",
"The Kwakwaka'wakw carver, among the first women to carve totem poles professionally, ran a carving business in Vancouver's Stanley Park and carved poles for public sites.",
"wood carving;painting",
"totem pole;souvenir carving",
"rule and display",
"herself",
"the family carvers who worked with her",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER124",
"Bill Reid",
"",
"person",
"People",
"F1.7",
"AM-NWC",
"1920",
"1998",
"",
"The Haida artist relearned Haida design from museum pieces and made jewellery and large sculptures such as The Spirit of Haida Gwaii (1991).",
"gold and silver engraving;wood carving;bronze casting",
"jewellery;sculpture",
"clothing and adornment;rule and display",
"himself",
"the many assistants who carved and cast his large works",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.24",
"high",
"links: STY076",
"canon_people.csv"
],
[
"PER125",
"Florence Davidson",
"Jaadal q'egangaa",
"person",
"People",
"F1.7",
"AM-NWC",
"1896",
"1993",
"",
"The Haida button-blanket maker, daughter of Charles and Isabella Edenshaw, kept regalia making alive in Old Massett.",
"appliqué;button blanket",
"button blanket",
"clothing and adornment;rule and display",
"her life history recorded by Margaret Blackman (During My Time, 1982)",
"the other women regalia makers",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER126",
"Jennie Thlunaut",
"Shax'saani Keek'",
"person",
"People",
"F1.7",
"AM-NWC",
"1892",
"1986",
"born c. 1890–92",
"The Tlingit weaver made some fifty Chilkat robes and taught the technique to younger weavers in the 1980s.",
"Chilkat weaving;mountain goat wool;cedar bark",
"robe;tunic",
"clothing and adornment;ritual and belief",
"herself; weaving students",
"the earlier Chilkat weavers she learned from",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER127",
"George Hunt",
"",
"person",
"People",
"F1.7",
"AM-NWC",
"1854",
"1933",
"",
"The Tlingit-English Kwakwaka'wakw interpreter collected objects for museums and wrote much of the Kwakwaka'wakw material published under Franz Boas's name.",
"collecting;ethnographic writing",
"mask;text",
"record and writing",
"Boas's publications; historians",
"himself, as uncredited co-author; the families from whom objects were bought",
"Indigenous-community",
"Internet Archive (public-domain scans)",
"R3",
"F1.26;F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER128",
"Franz Boas",
"",
"person",
"People",
"F1.7;THEME",
"AM-NWC;AM-EWD",
"1858",
"1942",
"",
"The German-American anthropologist's Primitive Art (1927) analysed Northwest Coast design as a formal system and shaped museum collecting in New York.",
"ethnography;museum collecting",
"text",
"record and writing",
"himself",
"George Hunt and other Indigenous co-researchers",
"Indigenous-community",
"Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.24",
"high",
"links: STY076",
"canon_people.csv"
],
[
"PER129",
"Kenojuak Ashevak",
"",
"person",
"People",
"F1.7",
"AM-ARC",
"1927",
"2013",
"",
"The Inuk artist from Kinngait (Cape Dorset) made drawings translated into prints such as The Enchanted Owl (1960).",
"drawing;stone-cut print;stencil",
"print;drawing",
"rule and display",
"herself; West Baffin Eskimo Co-operative",
"the printmakers who cut the stones from her drawings",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.26",
"high",
"links: MKR029",
"canon_people.csv"
],
[
"PER130",
"Pitseolak Ashoona",
"",
"person",
"People",
"F1.7",
"AM-ARC",
"1904",
"1983",
"born c. 1904",
"The Inuk artist of Kinngait made thousands of drawings of camp life that were printed by the co-operative.",
"drawing;print",
"print;drawing",
"rule and display",
"herself (Pictures Out of My Life, 1971)",
"the printmakers who cut her images",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"high",
"links: MKR029",
"canon_people.csv"
],
[
"PER131",
"Jessie Oonark",
"",
"person",
"People",
"F1.7",
"AM-ARC",
"1906",
"1985",
"",
"The Inuk artist of Qamani'tuaq (Baker Lake) made drawings, prints and large wall hangings of appliquéd felt and stroud.",
"appliqué;drawing;stencil print",
"wall hanging;print",
"clothing and adornment;rule and display",
"herself; Baker Lake studio",
"her children, several of whom became artists; the women sewers of Baker Lake",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER132",
"Aron of Kangeq",
"",
"person",
"People",
"F1.7",
"AM-ARC",
"1822",
"1869",
"",
"The Greenlandic hunter and artist made woodcuts and watercolours of Inuit tales for Hinrich Rink's collection, printed at Godthåb (Nuuk).",
"woodcut;watercolour",
"print;illustration",
"record and writing",
"Hinrich Rink; Greenland National Museum",
"other Greenlandic contributors to Rink's collection",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.29;F1.28",
"high",
"links: POL080",
"canon_people.csv"
],
[
"PER133",
"David Drake",
"Dave the Potter",
"person",
"People",
"F1.7",
"AM-EWD",
"1801",
"1870",
"born c. 1801; died c. 1870s",
"An enslaved potter at Edgefield, South Carolina, he turned large alkaline-glazed stoneware storage jars and inscribed some with his name, dates and couplets, though literacy was banned for enslaved people.",
"wheel throwing;alkaline glaze",
"storage jar",
"food and storage",
"his inscriptions; museums",
"the other enslaved potters of Edgefield whose names are not on their jars",
"human-flow",
"Met Open Access (CC0);Smithsonian Open Access (CC0)",
"R1",
"F1.23;F1.26;F1.28",
"high",
"Content note needed.",
"canon_people.csv"
],
[
"PER134",
"Harriet Powers",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1837",
"1910",
"",
"Born enslaved in Georgia, she made appliqué quilts with Bible and local scenes; two survive, in the Smithsonian and the Museum of Fine Arts, Boston.",
"appliqué;hand and machine stitching",
"quilt",
"clothing and adornment;ritual and belief",
"herself; Jennie Smith, who bought and described a quilt",
"the enslaved women quilters whose names are lost",
"human-flow",
"Smithsonian Open Access (CC0)",
"R2",
"F1.23;F1.18",
"high",
"Content note needed. links: MKR034",
"canon_people.csv"
],
[
"PER135",
"Elizabeth Keckley",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1818",
"1907",
"born c. 1818",
"Born enslaved, she bought her freedom through dressmaking and became Mary Todd Lincoln's dressmaker, writing Behind the Scenes (1868).",
"dressmaking",
"dress",
"clothing and adornment",
"herself (Behind the Scenes)",
"the seamstresses she employed; the enslaved women whose sewing supported slaveholding households",
"human-flow",
"Smithsonian Open Access (CC0);Library of Congress (public-domain items)",
"R3",
"F1.23;F1.18",
"high",
"Content note needed.",
"canon_people.csv"
],
[
"PER136",
"Thomas Day",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1801",
"1861",
"died c. 1861",
"The free Black cabinetmaker of Milton, North Carolina, ran one of the state's largest furniture workshops and himself held enslaved workers.",
"cabinetmaking;joinery",
"chair;cabinet;interior woodwork",
"shelter",
"historians; museum records",
"the enslaved and hired workers in his shop",
"human-flow",
"community-published site (link-out)",
"R3",
"F1.23;F1.26",
"high",
"Context: he both faced racial restriction and enslaved others.",
"canon_people.csv"
],
[
"PER137",
"John Hemmings",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1776",
"1833",
"",
"The enslaved joiner at Monticello made furniture and woodwork for Thomas Jefferson's houses and was freed by Jefferson's will.",
"joinery;cabinetmaking",
"furniture;interior woodwork",
"shelter",
"Monticello records",
"the other enslaved craftsmen at Monticello",
"human-flow",
"community-published site (link-out)",
"R3",
"F1.23",
"high",
"",
"canon_people.csv"
],
[
"PER138",
"Mary Lee Bendolph",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1935",
"",
"born 1935; living",
"The Gee's Bend quilter makes quilts from worn clothing and scraps in improvised patterns, shown in museums since 2002.",
"piecing;quilting;reused cloth",
"quilt",
"clothing and adornment",
"herself; museums",
"the other Gee's Bend quilters and the collectors who framed their work as art",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.22a",
"high",
"links: MKR034",
"canon_people.csv"
],
[
"PER139",
"Annie Mae Young",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1928",
"2012",
"",
"The Gee's Bend quilter pieced quilts from work clothes, including a well-known quilt of denim and corduroy made around 1976.",
"piecing;quilting;reused cloth",
"quilt",
"clothing and adornment",
"herself; museums",
"the other Gee's Bend quilters",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.22a",
"high",
"links: MKR034",
"canon_people.csv"
],
[
"PER140",
"Faith Ringgold",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1930",
"2024",
"",
"The American artist made story quilts from 1980, joining painting with quilting learned from her mother's family.",
"painting on cloth;quilting",
"story quilt",
"record and writing;clothing and adornment",
"herself",
"her mother Willi Posey, a dressmaker who sewed early quilts with her",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER141",
"Ann Lee",
"Mother Ann Lee",
"person",
"People",
"F1.7",
"AM-EWD;EU-BLC",
"1736",
"1784",
"",
"The English-born founder of the Shakers in America led the community whose rules later shaped its plain furniture, oval boxes and tools.",
"religious leadership",
"chair;box",
"ritual and belief",
"Shaker tradition",
"the Shaker makers, many unnamed, who made the objects after her death",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: MKR030",
"canon_people.csv"
],
[
"PER142",
"Eli Whitney",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1765",
"1825",
"",
"The American inventor patented a cotton gin (1794) that made short-staple cotton profitable and helped expand slavery in the US South.",
"cotton ginning",
"cotton gin",
"tools",
"patent records; historians",
"the enslaved people whose forced labour grew the cotton; earlier gin makers",
"human-flow",
"Library of Congress (public-domain items);Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"His claims about interchangeable musket parts are exaggerated. links: NET056",
"canon_people.csv"
],
[
"PER143",
"Henry Ford",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1863",
"1947",
"",
"The American manufacturer introduced the moving assembly line at Highland Park in 1913 to build the Model T.",
"assembly line;interchangeable parts",
"car",
"transport",
"himself; Ford Motor Company",
"the engineers who designed the line and the workers who ran it; the rubber workers at Fordlândia",
"none",
"Library of Congress (public-domain items)",
"R3",
"F1.19",
"high",
"links: INS065",
"canon_people.csv"
],
[
"PER144",
"Candace Wheeler",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1827",
"1923",
"",
"The American textile designer co-founded the Society of Decorative Art (1877) to sell women's needlework and directed the Women's Building interiors at the 1893 Chicago fair.",
"textile design;embroidery",
"textile;interior",
"shelter;clothing and adornment",
"herself",
"the women needleworkers whose work the society sold",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.18;F1.17",
"high",
"links: EVT007",
"canon_people.csv"
],
[
"PER145",
"Louis Comfort Tiffany",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1848",
"1933",
"",
"The American designer ran the studios whose leaded-glass windows and lamps used opalescent glass made in his own furnaces.",
"opalescent glass;leaded glass;favrile glass",
"lamp;window;vase",
"shelter",
"himself; Tiffany Studios",
"Clara Driscoll and the women glass cutters who designed and made many lamps",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R2",
"F1.26;F1.18",
"high",
"links: MKR032",
"canon_people.csv"
],
[
"PER146",
"Clara Driscoll",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1861",
"1944",
"",
"She headed Tiffany Studios' women's glass-cutting department and designed lamps such as the Dragonfly, credited only after her letters were found in 2005.",
"leaded glass;design",
"lamp",
"shelter",
"her letters (found 2005); curators",
"herself and the 'Tiffany Girls' she supervised",
"none",
"Met Open Access (CC0)",
"R2",
"F1.26;F1.18;F1.23",
"high",
"links: MKR032",
"canon_people.csv"
],
[
"PER147",
"Maria Longworth Nichols",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1849",
"1932",
"",
"The Cincinnati heiress founded Rookwood Pottery in 1880, employing decorators, many of them women, to paint underglaze art pottery.",
"underglaze slip painting",
"vase",
"rule and display",
"herself",
"the Rookwood decorators and throwers, including many women",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.18;F1.17",
"high",
"",
"canon_people.csv"
],
[
"PER148",
"Adelaide Alsop Robineau",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1865",
"1929",
"",
"The American potter carved porcelain with great patience, including the Scarab Vase (1910), and edited the magazine Keramic Studio.",
"carved porcelain;high-fire glaze",
"vase",
"rule and display",
"herself",
"the china painters who read and wrote for her magazine",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.20;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER149",
"Marion Mahony Griffin",
"",
"person",
"People",
"F1.7;F1.12",
"AM-EWD;OC-AUS",
"1871",
"1961",
"",
"The American architect made many of the presentation drawings for Frank Lloyd Wright's early work and co-designed Canberra's plan with Walter Burley Griffin.",
"architectural drawing;town planning",
"drawing;house;town plan",
"shelter",
"herself (The Magic of America)",
"herself, when drawings are credited to Wright or Griffin",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.26;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER150",
"Raymond Loewy",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1893",
"1986",
"",
"The French-born American industrial designer restyled products from locomotives to the Coldspot refrigerator (1934) to sell them, calling his rule 'most advanced yet acceptable'.",
"industrial design;streamlining",
"refrigerator;locomotive;logo",
"food and storage;transport",
"himself (Never Leave Well Enough Alone, 1951)",
"the staff designers in his firm",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.21;F1.19",
"high",
"links: STY043",
"canon_people.csv"
],
[
"PER151",
"Henry Dreyfuss",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1904",
"1972",
"",
"The American industrial designer published body-measurement charts (The Measure of Man, 1960) and designed telephones for Bell and tractors for John Deere.",
"industrial design;anthropometry",
"telephone;tractor",
"care and access;tools",
"himself (Designing for People, 1955)",
"Alvin Tilley and the staff who drew the anthropometric charts",
"none",
"Cooper Hewitt Open Access (CC0 metadata, images where PD);collection search link-out only (works in copyright)",
"R3",
"F1.19;F1.21",
"high",
"links: MOV047",
"canon_people.csv"
],
[
"PER152",
"Charles Eames",
"",
"person",
"People",
"F1.7;F1.9",
"AM-WST;AS-SAS",
"1907",
"1978",
"",
"The American designer, with Ray Eames, developed moulded plywood and fibreglass furniture, films and the 1958 India Report that led to the National Institute of Design.",
"moulded plywood;fibreglass;film",
"chair;film;exhibition",
"shelter",
"himself and Ray Eames; Herman Miller",
"Ray Eames, often cast as his assistant; the office staff",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.20;F1.26",
"high",
"links: INS033",
"canon_people.csv"
],
[
"PER153",
"Ray Eames",
"Bernice Alexandra Kaiser",
"person",
"People",
"F1.7;F1.9",
"AM-WST;AS-SAS",
"1912",
"1988",
"",
"The American designer and painter was an equal partner in the Eames Office's furniture, films and exhibitions, a role long described as secondary.",
"moulded plywood;graphic design;film",
"chair;textile;film",
"shelter",
"herself; historians",
"herself, when work is credited to Charles alone",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.18;F1.26",
"high",
"links: INS033",
"canon_people.csv"
],
[
"PER154",
"Florence Knoll",
"Florence Knoll Bassett",
"person",
"People",
"F1.7",
"AM-EWD",
"1917",
"2019",
"",
"The American architect and designer ran Knoll's Planning Unit, shaping the modern office interior and its furniture.",
"interior planning;furniture design",
"office interior;table;sofa",
"shelter",
"herself",
"the designers and upholsterers in the Planning Unit",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER155",
"Eva Zeisel",
"",
"person",
"People",
"F1.7;F1.11",
"AM-EWD;EU-EER",
"1906",
"2011",
"",
"The Hungarian-born ceramic designer worked in German and Soviet factories, was imprisoned in the Soviet Union in 1936–37, and designed mass-produced tableware in the US.",
"slip casting;industrial ceramic design",
"tableware",
"food and storage",
"herself",
"the factory workers who made her designs",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.18;F1.19",
"high",
"",
"canon_people.csv"
],
[
"PER156",
"Ruth Asawa",
"",
"person",
"People",
"F1.7",
"AM-WST",
"1926",
"2013",
"",
"The Japanese American artist, interned as a teenager, made looped-wire hanging sculptures from a crochet technique she learned from basket makers in Toluca, Mexico, in 1947.",
"looped wire",
"hanging sculpture",
"rule and display",
"herself",
"the Toluca basket makers whose loop she adapted",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.2",
"high",
"",
"canon_people.csv"
],
[
"PER157",
"Isamu Noguchi",
"",
"person",
"People",
"F1.7;F1.8",
"AM-EWD;AS-JPN",
"1904",
"1988",
"",
"The Japanese American sculptor designed the Akari paper lanterns (from 1951), made in Gifu by lantern workshops such as Ozeki.",
"washi paper;bamboo;stone carving",
"lamp;table;garden",
"shelter",
"himself",
"the Gifu lantern makers who make the Akari",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.14",
"high",
"",
"canon_people.csv"
],
[
"PER158",
"George Gustav Heye",
"",
"person",
"People",
"F1.7",
"AM-EWD",
"1874",
"1957",
"",
"The American collector amassed hundreds of thousands of Indigenous objects for his Museum of the American Indian (1916), now part of the Smithsonian's NMAI.",
"collecting;museum founding",
"ceremonial object;textile",
"ritual and belief",
"himself",
"the communities whose objects, including burial goods, he bought",
"Indigenous-community;funerary",
"Smithsonian Open Access (CC0)",
"R3",
"F1.24",
"high",
"links: INS080",
"canon_people.csv"
],
[
"PER159",
"Leizu",
"Xiling Shi",
"person",
"People",
"F1.8",
"AS-CHN",
"-2700",
"-2600",
"legendary; traditional date only",
"Chinese legend credits the consort of the Yellow Emperor with discovering silk reeling and starting sericulture, a story used to give silk an origin in women's work.",
"sericulture;silk reeling",
"silk",
"clothing and adornment",
"Chinese tradition; later ritual cult of the silkworm deity",
"the unnamed Neolithic women and men who domesticated the silkworm, shown by archaeology",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.29",
"low",
"Legend, not a historical person; archaeological silk is older than the traditional date. links: POL156",
"canon_people.csv"
],
[
"PER160",
"Lu Ban",
"Gongshu Ban",
"person",
"People",
"F1.8",
"AS-CHN",
"-507",
"-444",
"traditional dates; attributions legendary",
"Chinese tradition names Lu Ban as the patron of carpenters and credits him with tools such as the saw and carpenter's square; the Lu Ban Jing building manual was attributed to him centuries later.",
"carpentry;joinery",
"tool;building manual",
"tools;shelter",
"carpenters' guild tradition; later texts (Lu Ban Jing, Ming)",
"the carpenters whose inventions were gathered under his name",
"none",
"Wikimedia Commons;Chinese Text Project (link out)",
"R3",
"F1.26;F1.29",
"low",
"Treat as legend; the Lu Ban Jing is a Ming compilation.",
"canon_people.csv"
],
[
"PER161",
"Cai Lun",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"50",
"121",
"born c. 50–62, died 121",
"The Han court eunuch is credited in the Hou Hanshu with presenting an improved paper made from bark, hemp and rags in 105 CE, though earlier paper has been excavated.",
"papermaking",
"paper",
"record and writing",
"the Hou Hanshu (5th century); later tradition",
"the earlier, unnamed papermakers whose paper predates him",
"none",
"Wikimedia Commons;Chinese Text Project (link out)",
"R3",
"F1.5;F1.26",
"high",
"links: POL160",
"canon_people.csv"
],
[
"PER162",
"Bi Sheng",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"990",
"1051",
"fl. 1040s; dates approximate",
"Shen Kuo's Dream Pool Essays credits the commoner Bi Sheng with printing from movable type made of baked clay in the 1040s.",
"movable clay type",
"printed book",
"record and writing",
"Shen Kuo's Dream Pool Essays",
"the printers who kept using woodblocks, which suited Chinese script better",
"none",
"Wikimedia Commons;Chinese Text Project (link out)",
"R3",
"F1.5",
"high",
"No book printed by him survives. links: POL166",
"canon_people.csv"
],
[
"PER163",
"Shen Kuo",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1031",
"1095",
"",
"The Song official's Dream Pool Essays (c. 1088) record techniques including movable type, the magnetic needle and steelmaking.",
"observation;technical writing",
"text",
"record and writing",
"himself",
"the craftsmen whose methods he recorded, such as Bi Sheng and the builder Yu Hao",
"none",
"Chinese Text Project (link out);Wikimedia Commons",
"R3",
"F1.28;F1.5",
"high",
"links: POL166",
"canon_people.csv"
],
[
"PER164",
"Li Jie",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1065",
"1110",
"",
"The Song court architect compiled the Yingzao fashi (1103), a building standard with modular timber units and labour quotas.",
"timber framing;modular bracketing",
"building manual",
"shelter;record and writing",
"himself; the Song court",
"the carpenters whose practice the manual codified",
"none",
"Chinese Text Project (link out);Wikimedia Commons",
"R3",
"F1.28;F1.19",
"high",
"links: POL166",
"canon_people.csv"
],
[
"PER165",
"Huang Daopo",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1245",
"1330",
"approximate; partly legendary",
"Songjiang tradition credits her with bringing cotton ginning, spinning and weaving tools and methods from the Li people of Hainan, founding the Songjiang cotton industry.",
"cotton ginning;spinning;weaving",
"cloth;tool",
"clothing and adornment",
"local gazetteers; a Yuan poem by Tao Zongyi",
"the Li women of Hainan who taught her",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.14",
"medium",
"Details are traditional.",
"canon_people.csv"
],
[
"PER166",
"Huizong",
"Emperor Huizong of Song",
"person",
"People",
"F1.8",
"AS-CHN",
"1082",
"1135",
"",
"The Song emperor collected antiquities, ran a painting academy and is associated with Ru ware made for the court.",
"calligraphy (slender gold script);court patronage",
"painting;ceramic;catalogue",
"rule and display",
"Song court records; historians",
"the academy painters and Ru kiln potters",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL166",
"canon_people.csv"
],
[
"PER167",
"Song Yingxing",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1587",
"1666",
"died c. 1666",
"The Ming scholar's Tiangong kaiwu (1637) describes and illustrates crafts from rice growing and silk weaving to ceramics, metal casting and papermaking.",
"technical writing;illustration",
"book",
"record and writing",
"himself",
"the artisans he watched and drew, who are unnamed",
"none",
"Chinese Text Project (link out);Internet Archive (public-domain scans);Wikimedia Commons",
"R2",
"F1.28;F1.19",
"high",
"links: POL168",
"canon_people.csv"
],
[
"PER168",
"Tang Ying",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1682",
"1756",
"",
"The superintendent of the imperial kilns at Jingdezhen wrote captions for the illustrated Taoye tushuo (1743) describing twenty stages of porcelain making.",
"porcelain production;technical writing",
"porcelain;treatise",
"food and storage;rule and display",
"himself; Qing court",
"the potters, painters and kiln workers, divided into many specialisms",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Wikimedia Commons",
"R3",
"F1.28;F1.19",
"high",
"links: MKR036",
"canon_people.csv"
],
[
"PER169",
"Qianlong Emperor",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1711",
"1799",
"",
"The Qing emperor ordered objects and archaistic copies from the palace workshops, inscribed poems on antiques and catalogued a large collection.",
"court patronage;cataloguing",
"porcelain;jade;catalogue",
"rule and display",
"Qing court records",
"the workshop artisans and the Uyghur jade carvers whose stone came from Khotan",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Met Open Access (CC0)",
"R3",
"F1.17;F1.14",
"high",
"links: INS020; POL169",
"canon_people.csv"
],
[
"PER170",
"Giuseppe Castiglione",
"Lang Shining",
"person",
"People",
"F1.8;F1.11",
"AS-CHN",
"1688",
"1766",
"",
"The Italian Jesuit painter at the Qing court joined European perspective with Chinese painting and helped design the European-style palaces at the Yuanmingyuan.",
"painting;architectural design",
"painting;palace",
"rule and display",
"Qing court records; art historians",
"the Chinese court painters who worked with him",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Wikimedia Commons",
"R3",
"F1.2;F1.13",
"high",
"The Yuanmingyuan was looted and burned in 1860.",
"canon_people.csv"
],
[
"PER171",
"Empress Dowager Cixi",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1835",
"1908",
"",
"The Qing empress dowager commissioned porcelain with her Dayazhai mark and had Western-style portraits painted and photographed for display.",
"court patronage;photography",
"porcelain;portrait",
"rule and display",
"Qing court records",
"the court painters and potters; the photographer Xunling",
"none",
"National Palace Museum Taipei Open Data (check per-item terms);Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: POL169",
"canon_people.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
