insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PER172",
"Lu Yu",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"733",
"804",
"",
"The Tang writer's Classic of Tea (Chajing) set out the equipment and ceramics for preparing tea, ranking kiln wares by how they showed the tea's colour.",
"technical writing",
"treatise;tea bowl",
"food and storage",
"himself",
"the tea pickers and potters of Yue and Xing kilns",
"none",
"Chinese Text Project (link out);Wikimedia Commons",
"R3",
"F1.28",
"high",
"links: POL162",
"canon_people.csv"
],
[
"PER173",
"Zheng He",
"",
"person",
"People",
"F1.8;F1.13",
"AS-CHN",
"1371",
"1433",
"died 1433 or 1435",
"The Ming admiral led seven fleets across the Indian Ocean (1405–33) that carried porcelain and silk as gifts and brought back goods and animals.",
"shipbuilding;navigation",
"treasure ship;porcelain",
"transport;exchange and value",
"Ming records; stelae he set up",
"the shipwrights and sailors; the Hui Muslim and other interpreters",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: NET005; NET054",
"canon_people.csv"
],
[
"PER174",
"Liang Sicheng",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1901",
"1972",
"",
"The Chinese architectural historian surveyed early timber buildings in the 1930s and decoded the Yingzao fashi.",
"building survey;architectural history",
"measured drawing;text",
"shelter;record and writing",
"himself; Society for Research in Chinese Architecture",
"Lin Huiyin and the surveyors who worked with him",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER175",
"Lin Huiyin",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1904",
"1955",
"",
"The Chinese architect and historian surveyed early temples with Liang Sicheng and helped design the national emblem of the People's Republic (1950).",
"building survey;design",
"measured drawing;emblem",
"shelter;rule and display",
"herself; historians",
"herself, when survey work is credited to Liang alone",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.18",
"high",
"links: POL171",
"canon_people.csv"
],
[
"PER176",
"Wang Shixiang",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1914",
"2009",
"",
"The Chinese scholar's studies of Ming furniture and lacquer established how these crafts were constructed and dated.",
"furniture study;lacquer study",
"chair;table;lacquer",
"shelter",
"himself",
"the cabinetmakers and lacquerers whose techniques he recorded",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.3;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER177",
"Xu Bing",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1955",
"",
"born 1955; living",
"The Chinese artist hand-carved thousands of invented characters for Book from the Sky (1987–91), printed and bound in traditional form.",
"woodblock carving;printing;bookbinding",
"book;installation",
"record and writing",
"himself",
"the printers and binders who helped produce the books",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.5;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER178",
"Ai Weiwei",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1957",
"",
"born 1957; living",
"The Chinese artist had about 1,600 Jingdezhen artisans make some 100 million porcelain seeds for Sunflower Seeds (2010).",
"porcelain;hand painting",
"installation",
"rule and display",
"himself",
"the Jingdezhen workers who made the seeds",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.23;F1.21",
"high",
"links: MKR036",
"canon_people.csv"
],
[
"PER179",
"Wang Shu",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1963",
"",
"born 1963; living",
"The Chinese architect built the Ningbo History Museum (2008) with walls of salvaged bricks and tiles laid by local masons in the wapan technique.",
"reused brick and tile;wapan masonry",
"museum;campus",
"shelter",
"himself; Pritzker Prize (2012)",
"Lu Wenyu, his partner, who was not named in the prize; the masons",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.22a;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER180",
"Lu Wenyu",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1967",
"",
"born 1967; living",
"The Chinese architect co-founded Amateur Architecture Studio with Wang Shu and co-designed its buildings, though the 2012 Pritzker Prize went to him alone.",
"reused brick and tile;wapan masonry",
"museum;campus",
"shelter",
"herself; press",
"herself, when the studio's work is credited to Wang alone",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.18",
"medium",
"Birth year 1967 per Wikipedia and Bloomsbury Encyclopedia; some web sources give 1966.",
"canon_people.csv"
],
[
"PER181",
"Aurel Stein",
"",
"person",
"People",
"F1.8;F1.12a;F1.13",
"AS-CHN;AS-CEN",
"1862",
"1943",
"",
"The Hungarian-British archaeologist bought thousands of manuscripts and paintings from the Dunhuang library cave in 1907 and removed murals and objects from Silk Road sites.",
"expedition collecting",
"manuscript;painting;textile",
"record and writing;ritual and belief",
"himself",
"the monks and communities of Dunhuang; Chinese scholars who later called it plunder",
"conflict-looting",
"International Dunhuang Programme (link out);British Museum Collection Online (CC BY-NC-SA, link out)",
"R3",
"F1.24",
"high",
"Whether to call this looting is debated; the flag follows Chinese claims. links: NET001",
"canon_people.csv"
],
[
"PER182",
"Wang Yuanlu",
"",
"person",
"People",
"F1.8",
"AS-CHN",
"1849",
"1931",
"born c. 1849",
"The Daoist abbot who looked after the Mogao caves found the sealed library cave in 1900 and sold much of its contents to Stein, Pelliot and others to fund repairs.",
"custodianship;sale",
"manuscript;painting",
"record and writing;ritual and belief",
"Stein's and Pelliot's accounts",
"the Buddhist monks who sealed the cave; Chinese officials who failed to protect it",
"none",
"International Dunhuang Programme (link out)",
"R3",
"F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER183",
"Albert von Le Coq",
"",
"person",
"People",
"F1.12a;F1.11",
"AS-CEN;EU-WCE",
"1860",
"1930",
"",
"The German archaeologist led Turfan expeditions (1904–14) that sawed Buddhist murals from the walls of Bezeklik and other caves and took them to Berlin, where some were destroyed in 1945.",
"mural removal;expedition collecting",
"mural;manuscript",
"ritual and belief",
"himself",
"the Uyghur communities of Turfan; the painters of the murals",
"conflict-looting",
"Staatliche Museen zu Berlin SMB-digital (check per-item terms);International Dunhuang Programme (link out)",
"R3",
"F1.24;F1.19a",
"high",
"links: POL231",
"canon_people.csv"
],
[
"PER184",
"Kublai Khan",
"Emperor Shizu of Yuan",
"person",
"People",
"F1.8;F1.12a",
"AS-CHN;AS-CEN",
"1215",
"1294",
"",
"The Mongol ruler of China brought artisans from across his empire to his capital Dadu, including the Nepalese maker Araniko.",
"court patronage;artisan relocation",
"temple;stupa;textile",
"rule and display",
"Yuan records; historians",
"the artisans moved or registered in hereditary artisan households",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"links: POL167; MKR092",
"canon_people.csv"
],
[
"PER185",
"Zanabazar",
"Öndör Gegeen",
"person",
"People",
"F1.12a;F1.8",
"AS-CEN",
"1635",
"1723",
"",
"The first Mongolian Jebtsundamba Khutuktu cast gilt-bronze Buddhist figures and created the Soyombo script.",
"lost-wax casting;gilding;script design",
"gilt-bronze figure;script",
"ritual and belief;record and writing",
"Mongolian Buddhist tradition; art historians",
"the workshop casters; Newar and Tibetan traditions he learned from",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16;F1.5",
"high",
"links: SCH045",
"canon_people.csv"
],
[
"PER186",
"François Xavier d'Entrecolles",
"",
"person",
"People",
"F1.8;F1.11",
"AS-CHN",
"1664",
"1741",
"",
"The French Jesuit's letters from Jingdezhen (1712, 1722) described porcelain making in detail and were read in Europe during the search for its recipe.",
"observation;letter writing",
"letter",
"record and writing",
"himself; Jesuit publications",
"the Jingdezhen potters who showed him their methods",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.14;F1.28",
"high",
"links: MKR036",
"canon_people.csv"
],
[
"PER187",
"Sejong",
"King Sejong the Great",
"person",
"People",
"F1.8",
"AS-KOR",
"1397",
"1450",
"",
"The Joseon king had the Korean alphabet (Hunminjeongeum) created and promulgated (1443–46) and sponsored instruments for astronomy and rain gauging.",
"alphabet design;instrument making",
"script;rain gauge;water clock",
"record and writing;tools",
"Joseon royal records",
"the scholars of the Hall of Worthies and craftsmen such as Jang Yeong-sil",
"none",
"National Museum of Korea e-museum (KOGL Type 1 where marked);Wikimedia Commons",
"R3",
"F1.5;F1.17",
"high",
"links: POL177",
"canon_people.csv"
],
[
"PER188",
"Jang Yeong-sil",
"",
"person",
"People",
"F1.8",
"AS-KOR",
"1390",
"1442",
"born c. 1390; last recorded 1442",
"Born to a government slave mother, the Joseon craftsman built water clocks and astronomical instruments for King Sejong.",
"water clock;bronze casting;instrument making",
"water clock;sundial",
"tools;record and writing",
"Joseon royal records",
"the other state artisans; his own lowborn status, which limited his records",
"human-flow",
"National Museum of Korea e-museum (KOGL Type 1 where marked);Wikimedia Commons",
"R3",
"F1.23;F1.26",
"medium",
"Birth and death dates unknown.",
"canon_people.csv"
],
[
"PER189",
"Baegun Gyeonghan",
"",
"person",
"People",
"F1.8",
"AS-KOR",
"1298",
"1374",
"",
"The Korean Seon monk compiled the Jikji, printed with metal movable type at Heungdeok temple in 1377, the oldest surviving book printed that way.",
"metal movable type",
"printed book",
"record and writing",
"colophon of the Jikji; UNESCO",
"his disciples Seokchan and Daldam and the nun Myodeok who funded the printing",
"none",
"Gallica BnF (public-domain items, link out for reuse);Wikimedia Commons",
"R3",
"F1.5;F1.24",
"high",
"The only known copy is in the Bibliothèque nationale de France; Korea seeks it. links: POL176",
"canon_people.csv"
],
[
"PER190",
"Sin Saimdang",
"",
"person",
"People",
"F1.8",
"AS-KOR",
"1504",
"1551",
"",
"The Joseon painter and calligrapher is known for paintings of plants and insects, with embroidery also attributed to her.",
"ink and colour painting;embroidery",
"painting;screen",
"rule and display",
"later Confucian writers who framed her as the model mother",
"the unnamed women embroiderers of Joseon households",
"none",
"National Museum of Korea e-museum (KOGL Type 1 where marked);Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"Several attributions are uncertain.",
"canon_people.csv"
],
[
"PER191",
"Yi Sam-pyeong",
"Kanagae Sanbei",
"person",
"People",
"F1.8",
"AS-KOR;AS-JPN",
"1598",
"1655",
"fl.; taken to Japan c. 1598, died 1655",
"A Korean potter taken to Japan during the 1592–98 invasions, he is credited by tradition with finding porcelain clay at Izumiyama and starting porcelain production at Arita around 1616.",
"porcelain;kaolin prospecting;climbing kiln",
"porcelain",
"food and storage",
"Arita tradition; the Nabeshima domain; a 20th-century monument",
"the hundreds of other Korean potters taken to Japan, such as those settled in Satsuma",
"human-flow",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.23;F1.13",
"medium",
"Founding story is traditional. links: MKR039; MKR040; DIA012",
"canon_people.csv"
],
[
"PER192",
"Asakawa Takumi",
"",
"person",
"People",
"F1.8",
"AS-KOR",
"1891",
"1931",
"",
"The Japanese forester in Seoul collected Joseon everyday wares and helped Yanagi found the Joseon Folk Art Museum (1924).",
"collecting;writing",
"ceramic;furniture",
"food and storage",
"himself (books on Joseon tableware and furniture)",
"the Korean makers of the everyday wares he collected",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.24;F1.29",
"high",
"links: MOV096",
"canon_people.csv"
],
[
"PER193",
"Tori Busshi",
"Kuratsukuri no Tori",
"person",
"People",
"F1.8",
"AS-JPN",
"600",
"630",
"fl.; early 7th century",
"The sculptor of Korean or Chinese immigrant descent cast the Shaka Triad at Hōryūji (623).",
"bronze casting;gilding",
"Buddhist figure",
"ritual and belief",
"inscription on the halo",
"the immigrant craft lineages (saddle makers) from which he came",
"sacred",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.13;F1.16",
"high",
"links: POL178",
"canon_people.csv"
],
[
"PER194",
"Jōchō",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1020",
"1057",
"fl.; died 1057",
"The Heian sculptor carved the Amida at the Byōdōin (1053) and is credited with refining the joined-block (yosegi-zukuri) technique used by workshops.",
"joined-block wood carving;gilding",
"Buddhist figure",
"ritual and belief",
"Heian records; later sculptors' lineages",
"the workshop carvers who made the separate blocks",
"sacred",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.19;F1.16",
"high",
"links: POL180",
"canon_people.csv"
],
[
"PER195",
"Unkei",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1150",
"1223",
"born c. 1150",
"The Kei school sculptor made realistic Buddhist and guardian figures, including with Kaikei the Nandaimon guardians at Tōdaiji (1203).",
"joined-block wood carving;crystal eyes",
"Buddhist figure;guardian figure",
"ritual and belief",
"inscriptions; temple records",
"the workshop of about 20 carvers who helped make the guardians",
"sacred",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.26;F1.16",
"high",
"links: SCH039",
"canon_people.csv"
],
[
"PER196",
"Ashikaga Yoshimasa",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1436",
"1490",
"",
"The Muromachi shogun built the Ginkakuji retreat and sponsored the tea gatherings, flower arranging and collections of Chinese objects known as Higashiyama culture.",
"patronage;collecting",
"tea utensil;painting;building",
"rule and display",
"historians",
"the dōbōshū advisers of low rank who judged and arranged the objects",
"none",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: DYN069",
"canon_people.csv"
],
[
"PER197",
"Sen no Rikyū",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1522",
"1591",
"",
"The tea master shaped wabi tea, commissioning plain objects such as Chōjirō's tea bowls and a two-mat tea room.",
"tea practice;commissioning",
"tea bowl;tea room;bamboo utensil",
"food and storage;ritual and belief",
"tea school tradition",
"the potters, bamboo cutters and carpenters who made his utensils",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.17",
"high",
"links: STY150",
"canon_people.csv"
],
[
"PER198",
"Raku Chōjirō",
"Chōjirō",
"person",
"People",
"F1.8",
"AS-JPN",
"1574",
"1589",
"fl.; earliest dated work 1574, died 1589",
"The Kyoto tile maker hand-built low-fired tea bowls for Sen no Rikyū, the start of the Raku family line.",
"hand building;low-temperature firing",
"tea bowl",
"food and storage",
"Raku family tradition",
"his father Ameya, said to be an immigrant, and the family members who worked with him",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26;F1.17",
"medium",
"Early history is traditional. links: MKR041",
"canon_people.csv"
],
[
"PER199",
"Toyotomi Hideyoshi",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1537",
"1598",
"",
"The Japanese ruler had a portable golden tea room built and invaded Korea (1592–98), during which Korean potters were taken to Japan.",
"patronage;war",
"tea room;tea utensil",
"rule and display;war",
"historians",
"the Korean potters taken to Japan; the people killed in Korea",
"human-flow",
"ColBase Japan national museums (check per-item terms);Wikimedia Commons",
"R3",
"F1.17;F1.19a",
"high",
"links: DYN070; DIA012",
"canon_people.csv"
],
[
"PER200",
"Hon'ami Kōetsu",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1558",
"1637",
"",
"The Kyoto calligrapher, potter and lacquer designer founded an artists' community at Takagamine and is credited with designs for lacquer and tea bowls.",
"calligraphy;raku ware;lacquer design",
"tea bowl;writing box;scroll",
"record and writing;food and storage",
"Rinpa tradition; art historians",
"Sōtatsu and the lacquerers who made his designs",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26;F1.17",
"high",
"links: STY147",
"canon_people.csv"
],
[
"PER201",
"Sakaida Kakiemon I",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1596",
"1666",
"",
"The Arita potter is credited with developing overglaze enamels on porcelain in the 1640s, the start of the Kakiemon style exported to Europe.",
"overglaze enamel;porcelain",
"dish;figure",
"food and storage",
"Kakiemon family tradition",
"the other Arita workshops and the Chinese enamel methods he learned",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26;F1.14",
"medium",
"Early attribution is traditional. links: MKR040",
"canon_people.csv"
],
[
"PER202",
"Nonomura Ninsei",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1646",
"1677",
"fl.; approximate",
"The Kyoto potter at Omuro was among the first Japanese potters to mark his wares with his name, making enamelled tea-ceremony stoneware for aristocrats.",
"wheel throwing;overglaze enamel",
"tea jar;incense burner",
"food and storage;ritual and belief",
"his seal; art historians",
"the kiln workers of the Omuro workshop",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER203",
"Ogata Kōrin",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1658",
"1716",
"",
"The Kyoto painter designed screens, kimono and lacquer in the Rinpa manner and painted designs on his brother Kenzan's ceramics.",
"painting;textile design;lacquer design",
"folding screen;kosode;lacquer box",
"clothing and adornment;rule and display",
"art historians; later Rinpa followers",
"the textile dyers and lacquerers who made his designs",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26",
"high",
"links: STY147",
"canon_people.csv"
],
[
"PER204",
"Ogata Kenzan",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1663",
"1743",
"",
"The Kyoto potter ran a workshop making painted stoneware dishes, many signed with his name but made by his assistants.",
"stoneware;underglaze painting",
"dish;tea bowl",
"food and storage",
"his signatures; art historians",
"the workshop potters, and later makers who used the Kenzan name",
"none",
"Met Open Access (CC0);ColBase Japan national museums (check per-item terms)",
"R3",
"F1.26;F1.14",
"high",
"The Kenzan name was inherited and copied, which makes attribution hard. links: STY147",
"canon_people.csv"
],
[
"PER205",
"Tsutaya Jūzaburō",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1750",
"1797",
"",
"The Edo publisher commissioned and sold woodblock prints and books by Utamaro, Sharaku and others.",
"publishing;woodblock printing",
"print;book",
"record and writing;exchange and value",
"publishers' seals on prints",
"the block carvers and printers whose names were not printed",
"none",
"Met Open Access (CC0);Art Institute of Chicago (CC0)",
"R3",
"F1.17;F1.21",
"high",
"links: MKR043",
"canon_people.csv"
],
[
"PER206",
"Katsushika Hokusai",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1760",
"1849",
"",
"The Edo artist designed prints and design books such as the Hokusai Manga, which circulated in Europe and fed Japonisme.",
"woodblock print design",
"print;design book",
"record and writing",
"himself; publishers; European collectors",
"the carvers and printers who turned his drawings into prints; his daughter Katsushika Ōi",
"none",
"Met Open Access (CC0);Art Institute of Chicago (CC0);National Museum of Asian Art via Smithsonian Open Access (CC0 where marked)",
"R2",
"F1.26;F1.14",
"high",
"links: STY148; STY030",
"canon_people.csv"
],
[
"PER207",
"Katsushika Ōi",
"Oei",
"person",
"People",
"F1.8",
"AS-JPN",
"1800",
"1866",
"approximate",
"The painter, Hokusai's daughter, worked in his studio and made her own paintings with strong light effects; some works credited to him may be hers.",
"painting;print design",
"painting",
"rule and display",
"art historians",
"herself, when studio work is credited to her father",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26;F1.18",
"medium",
"Birth and death dates uncertain.",
"canon_people.csv"
],
[
"PER208",
"Okakura Kakuzō",
"Okakura Tenshin",
"person",
"People",
"F1.8",
"AS-JPN",
"1863",
"1913",
"",
"The Japanese art critic helped found the Tokyo School of Fine Arts and wrote The Book of Tea (1906) in English, presenting tea and craft as Asian ideals.",
"criticism;museum curating",
"text",
"record and writing",
"himself",
"the artists and craftsmen he wrote about; the colonial politics of 'Asia is one'",
"none",
"Project Gutenberg;Internet Archive (public-domain scans)",
"R3",
"F1.3",
"high",
"links: INS026; MOV093",
"canon_people.csv"
],
[
"PER209",
"Sōetsu Yanagi",
"Muneyoshi Yanagi",
"person",
"People",
"F1.8",
"AS-JPN",
"1889",
"1961",
"",
"The Japanese philosopher named mingei (folk craft) in 1925, founded the Japan Folk Crafts Museum and argued that anonymous makers made the most beautiful things.",
"criticism;collecting;museum founding",
"ceramic;textile;writing",
"record and writing",
"himself",
"the named women weavers and rural makers his theory of anonymity left unnamed; Korean makers whose work he collected",
"none",
"collection search link-out only (works in copyright)",
"R1",
"F1.3;F1.29;F1.26",
"high",
"Kim Brandt's work shows mingei's links with empire. links: MOV096; INS027",
"canon_people.csv"
],
[
"PER210",
"Shōji Hamada",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1894",
"1978",
"",
"The potter set up his workshop at Mashiko in 1924, joining local folk-pottery methods to mingei ideas, and was named a Living National Treasure in 1955.",
"stoneware;wheel throwing;poured glaze",
"vessel;plate",
"food and storage",
"himself; Mingei movement",
"the Mashiko potters whose kilns and methods he used",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29",
"high",
"links: MOV096; INS028",
"canon_people.csv"
],
[
"PER211",
"Kawai Kanjirō",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1890",
"1966",
"",
"The Kyoto potter co-founded the mingei movement and made stoneware and wood carvings, refusing honours such as Living National Treasure.",
"stoneware;glaze research;wood carving",
"vessel;carving",
"food and storage",
"himself",
"his kiln workers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29",
"high",
"links: MOV096",
"canon_people.csv"
],
[
"PER212",
"Serizawa Keisuke",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1895",
"1984",
"",
"The textile artist adapted Okinawan bingata stencil dyeing into katazome, making kimono, screens and books, and was a Living National Treasure.",
"katazome stencil dyeing",
"kimono;screen;book",
"clothing and adornment",
"himself",
"the Okinawan bingata dyers he learned from",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.29;F1.14",
"high",
"",
"canon_people.csv"
],
[
"PER213",
"Bernard Leach",
"",
"person",
"People",
"F1.8;F1.11",
"AS-JPN;EU-BLC",
"1887",
"1979",
"",
"The British potter trained in Japan and set up the Leach Pottery at St Ives with Shōji Hamada in 1920, spreading East Asian stoneware ideas to studio potters through A Potter's Book (1940).",
"stoneware;wheel throwing",
"vessel",
"food and storage",
"himself",
"Hamada, Matsubayashi Tsurunosuke and the St Ives apprentices; the Japanese and Korean potters he copied",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.14",
"high",
"links: MOV041",
"canon_people.csv"
],
[
"PER214",
"Kayano Shigeru",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1926",
"2006",
"",
"The Ainu craftsman and collector built up the Nibutani Ainu Culture Museum and campaigned for Ainu rights, becoming the first Ainu member of Japan's national parliament.",
"wood carving;collecting",
"carving;utensil",
"ritual and belief",
"himself",
"the Ainu makers of the objects he gathered",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.24;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER215",
"Kenzo Tange",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1913",
"2005",
"",
"The Japanese architect designed the Hiroshima Peace Memorial Park and the Yoyogi National Gymnasium for the 1964 Tokyo Olympics.",
"reinforced concrete;suspension roof",
"stadium;memorial",
"shelter",
"himself",
"the engineer Yoshikatsu Tsuboi and the Metabolist architects in his office",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: MOV026; EVT021",
"canon_people.csv"
],
[
"PER216",
"Sori Yanagi",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1915",
"2011",
"",
"The Japanese industrial designer, son of Sōetsu Yanagi, designed the plywood Butterfly Stool (1954) and kitchenware developed from full-size models.",
"moulded plywood;model making",
"stool;kettle;cutlery",
"shelter;food and storage",
"himself",
"the Tendo Mokko workers who made the stool",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER217",
"Kenji Ekuan",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1929",
"2015",
"",
"The Japanese industrial designer led GK Design, whose Kikkoman soy sauce bottle (1961) became a standard table object.",
"industrial design;glass bottle",
"bottle;motorcycle;train",
"food and storage;transport",
"himself; GK Design",
"the GK team members who co-designed the bottle",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER218",
"Issey Miyake",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1938",
"2022",
"",
"The Japanese designer developed garment-pleating methods (Pleats Please, 1993) and A-POC, clothing cut from one continuous tube of knitted cloth.",
"heat pleating;machine knitting",
"garment",
"clothing and adornment",
"himself",
"textile engineer Makiko Minagawa and Dai Fujiwara who co-developed the techniques",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER219",
"Rei Kawakubo",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1942",
"",
"born 1942; living",
"The Japanese designer founded Comme des Garçons and showed black, torn and asymmetric clothing in Paris from 1981.",
"garment construction;distressed textile",
"garment",
"clothing and adornment",
"herself",
"the pattern makers and textile mills she works with",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER220",
"Hanae Mori",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1926",
"2022",
"",
"The Japanese fashion designer became the first Asian woman admitted to the Paris haute couture federation (1977), with clothes using butterfly motifs and Japanese textiles.",
"couture;textile printing",
"garment",
"clothing and adornment",
"herself",
"the Japanese textile workshops that made her fabrics",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER221",
"Eiko Ishioka",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1938",
"2012",
"",
"The Japanese designer worked in advertising, stage and film costume, including costumes for Bram Stoker's Dracula (1992).",
"art direction;costume design",
"poster;costume",
"clothing and adornment;play and music",
"herself",
"the costume makers who built her designs",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER222",
"Kazuyo Sejima",
"",
"person",
"People",
"F1.8",
"AS-JPN",
"1956",
"",
"born 1956; living",
"The Japanese architect co-founded SANAA, designing light, thin-walled buildings such as the 21st Century Museum in Kanazawa.",
"steel;glass;thin structure",
"museum;house",
"shelter",
"herself; Pritzker Prize (2010, with Ryue Nishizawa)",
"the engineers such as Mutsuro Sasaki",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER223",
"Kim Brandt",
"",
"person",
"People",
"THEME;F1.8",
"AS-JPN;AM-EWD",
"2007",
"",
"fl.; Kingdom of Beauty published 2007; birth year not recorded here; living",
"The American historian's Kingdom of Beauty (2007) showed how the Japanese folk craft movement was tied to imperial expansion and consumer markets.",
"historiography",
"book",
"record and writing",
"herself",
"the Korean, Okinawan and Ainu makers drawn into mingei collecting",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.29",
"medium",
"Verify author details. links: MOV096",
"canon_people.csv"
],
[
"PER224",
"Ashoka",
"Aśoka Maurya",
"person",
"People",
"F1.9",
"AS-SAS",
"-268",
"-232",
"reign dates, approximate",
"The Maurya emperor had edicts cut on rocks and polished sandstone pillars crowned with animal capitals across the subcontinent.",
"stone polishing;rock inscription;pillar carving",
"pillar;capital;edict",
"record and writing;rule and display",
"his own inscriptions; historians",
"the stone-cutters of the Chunar quarries and the scribes who adapted the texts to local scripts",
"none",
"Wikimedia Commons;Indian Culture portal, Ministry of Culture (link out)",
"R3",
"F1.17;F1.28",
"high",
"links: POL186",
"canon_people.csv"
],
[
"PER225",
"Sembiyan Mahadevi",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"941",
"1001",
"fl.; approximate",
"The Chola queen dowager paid for temples to be rebuilt in stone and for bronze festival images, named in inscriptions as her gifts.",
"bronze casting;stone temple building",
"temple;festival bronze",
"ritual and belief",
"temple inscriptions",
"the sthapati bronze casters, who are not named",
"sacred",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.18",
"medium",
"A bronze in the Freer is traditionally identified as her portrait. links: STY120; MKR051",
"canon_people.csv"
],
[
"PER226",
"Rajaraja Chola I",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"985",
"1014",
"reign dates",
"The Chola king built the Brihadisvara temple at Thanjavur (completed c. 1010), whose inscriptions list donated bronzes, jewels and temple staff.",
"granite temple building;bronze casting",
"temple;festival bronze",
"ritual and belief;rule and display",
"temple inscriptions",
"the architect named in inscriptions as Kunjara Mallan Raja Raja Perunthachan, and the dancers and servants listed",
"sacred",
"Wikimedia Commons",
"R3",
"F1.17;F1.28",
"high",
"links: POL192",
"canon_people.csv"
],
[
"PER227",
"Akbar",
"Jalal-ud-din Muhammad Akbar",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1542",
"1605",
"",
"The Mughal emperor organised imperial workshops for painting, textiles and metalwork and commissioned large illustrated manuscripts such as the Hamzanama.",
"court workshop;manuscript painting",
"manuscript;textile;carpet",
"rule and display;record and writing",
"Abu'l Fazl's Ain-i Akbari",
"the painters, weavers and artisans of the karkhanas, many named only in manuscript margins",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL197; MKR044",
"canon_people.csv"
],
[
"PER228",
"Jahangir",
"",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1569",
"1627",
"",
"The Mughal emperor valued single-artist paintings, recorded his judgements of painters in his memoirs and ordered natural history studies from Mansur.",
"court patronage;album making",
"album;painting",
"rule and display",
"his memoirs (Jahangirnama)",
"the painters, gilders and margin-painters of the albums",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.17;F1.26",
"high",
"links: POL197",
"canon_people.csv"
],
[
"PER229",
"Nur Jahan",
"",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1577",
"1645",
"",
"The Mughal empress commissioned the tomb of her father Itmad-ud-Daulah at Agra and is credited by tradition with textile and dress designs.",
"inlaid marble;architecture;textile design",
"tomb;textile",
"rule and display;clothing and adornment",
"Mughal chronicles; tradition",
"the stone inlayers and weavers",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"Design attributions are traditional. links: POL197",
"canon_people.csv"
],
[
"PER230",
"Shah Jahan",
"",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1592",
"1666",
"",
"The Mughal emperor commissioned the Taj Mahal, the Red Fort at Delhi and the Peacock Throne.",
"white marble;pietra dura;architecture",
"tomb;fort;throne",
"rule and display;ritual and belief",
"Mughal chronicles",
"the builders led by Ustad Ahmad Lahauri and the thousands of stone-cutters and inlayers",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL197",
"canon_people.csv"
],
[
"PER231",
"Jahanara Begum",
"",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1614",
"1681",
"",
"The Mughal princess funded the design of Chandni Chowk market street in Delhi, a caravanserai and a mosque in Agra.",
"urban planning;architecture",
"market street;caravanserai;mosque",
"exchange and value;rule and display",
"Mughal chronicles",
"the builders and merchants who made the market",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: POL197",
"canon_people.csv"
],
[
"PER232",
"Basawan",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1560",
"1600",
"fl.; approximate",
"The Hindu painter was one of Akbar's leading artists, known for modelling and space learned in part from European prints.",
"opaque watercolour",
"manuscript painting",
"rule and display",
"names in manuscript margins; Abu'l Fazl",
"the colourists and assistants who completed his compositions",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26;F1.14",
"high",
"links: SCH022",
"canon_people.csv"
],
[
"PER233",
"Daswanth",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1560",
"1584",
"fl.; died 1584",
"The son of a palanquin bearer, he was praised by Abu'l Fazl as a leading painter of Akbar's workshop and designed many Razmnama images.",
"opaque watercolour",
"manuscript painting",
"rule and display",
"Abu'l Fazl's Ain-i Akbari; marginal inscriptions",
"the colourists who painted his designs",
"none",
"Wikimedia Commons",
"R3",
"F1.26;F1.23",
"high",
"links: SCH022",
"canon_people.csv"
],
[
"PER234",
"Mansur",
"Ustad Mansur",
"person",
"People",
"F1.9",
"AS-SAS",
"1590",
"1630",
"fl.; approximate",
"Jahangir's painter of animals and plants made precise studies of birds, flowers and a zebra and turkey brought to the court.",
"opaque watercolour",
"natural history painting",
"rule and display",
"Jahangir's memoirs; signatures",
"the traders and keepers who brought the animals",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26",
"high",
"links: SCH022",
"canon_people.csv"
],
[
"PER235",
"Bishandas",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1590",
"1640",
"fl.; approximate",
"The Mughal portrait painter was sent with Jahangir's embassy to Shah Abbas (1613–19) to paint portraits of the Safavid court.",
"opaque watercolour;portraiture",
"portrait",
"rule and display",
"Jahangir's memoirs; signatures",
"assistants who painted borders",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26;F1.13",
"high",
"links: SCH022",
"canon_people.csv"
],
[
"PER236",
"Sahifa Banu",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1600",
"1630",
"fl.; approximate",
"One of the few named women painters at the Mughal court, known from an early 17th-century portrait of Shah Tahmasp (V&A) whose inscription names her as its painter.",
"opaque watercolour",
"portrait",
"rule and display",
"a signature on one or two works",
"the other women of the zenana whose painting went unrecorded",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"medium",
"Few works attributed.",
"canon_people.csv"
],
[
"PER237",
"Ustad Ahmad Lahauri",
"",
"person",
"People",
"F1.9;F1.10",
"AS-SAS",
"1580",
"1649",
"approximate",
"The architect is named in a later text by his son as chief builder of the Taj Mahal and the Red Fort at Delhi.",
"architecture;geometry",
"tomb;fort",
"rule and display",
"a 17th-century text by his son Lutfullah Muhandis",
"the calligrapher Amanat Khan and the many masons and inlayers",
"none",
"Wikimedia Commons",
"R3",
"F1.26",
"medium",
"Attribution rests on one source.",
"canon_people.csv"
],
[
"PER238",
"Nainsukh",
"",
"person",
"People",
"F1.9",
"AS-HIM",
"1710",
"1778",
"approximate",
"The Pahari painter of the Guler family worked for Raja Balwant Singh of Jasrota, painting intimate scenes of his patron's daily life.",
"opaque watercolour",
"album painting",
"rule and display",
"art historian B. N. Goswamy, from inscriptions and records",
"the family workshop of Pandit Seu",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26",
"high",
"links: SCH025; SCH026",
"canon_people.csv"
],
[
"PER239",
"Tipu Sultan",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1751",
"1799",
"",
"The ruler of Mysore commissioned tiger-emblem arms and the mechanical organ Tipu's Tiger; British troops took his treasury after the siege of Seringapatam in 1799.",
"gun making;mechanical organ;gold",
"gun;throne finial;automaton",
"war;rule and display",
"British and Mysore records",
"the Mysore gunsmiths and makers of the Tiger; French craftsmen at his court",
"conflict-looting",
"V&A collections (link out);Wikimedia Commons",
"R3",
"F1.24;F1.19a",
"high",
"links: POL199",
"canon_people.csv"
],
[
"PER240",
"Raja Ravi Varma",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1848",
"1906",
"",
"The Indian painter set up a lithographic press near Bombay (1894) that printed his images of Hindu gods for mass sale.",
"oil painting;chromolithography",
"print;painting",
"ritual and belief",
"himself",
"the press workers and the German technician Fritz Schleicher, who later took over the press",
"none",
"Wikimedia Commons",
"R3",
"F1.21;F1.14",
"high",
"",
"canon_people.csv"
],
[
"PER241",
"John Lockwood Kipling",
"",
"person",
"People",
"F1.9;F1.11",
"AS-SAS",
"1837",
"1911",
"",
"The British teacher headed the Mayo School of Art in Lahore (1875–93) and the Lahore Museum, recording Punjabi crafts.",
"art teaching;craft survey",
"text;drawing",
"record and writing",
"himself",
"the Punjabi artisans and his assistant Ram Singh",
"none",
"Wikimedia Commons",
"R3",
"F1.20;F1.24",
"high",
"links: INS031",
"canon_people.csv"
],
[
"PER242",
"George Birdwood",
"",
"person",
"People",
"F1.11;F1.9",
"EU-BLC;AS-SAS",
"1832",
"1917",
"",
"The British official's The Industrial Arts of India (1880) catalogued Indian crafts for British design education and praised village work as timeless.",
"cataloguing",
"text",
"record and writing",
"himself; South Kensington Museum",
"the makers he described as unchanging, denying them history",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.15",
"high",
"links: INS052",
"canon_people.csv"
],
[
"PER243",
"Abanindranath Tagore",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1871",
"1951",
"",
"The Calcutta painter led the Bengal School, adapting Mughal and Japanese wash techniques for a national style.",
"watercolour wash;tempera",
"painting",
"rule and display",
"himself; E. B. Havell",
"the artisans and folk painters outside the school's elite nationalism",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: MOV082",
"canon_people.csv"
],
[
"PER244",
"Nandalal Bose",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1882",
"1966",
"",
"The Indian artist led Kala Bhavana at Santiniketan, made posters for the 1938 Haripura Congress and illuminated the Constitution of India.",
"tempera;woodcut;mural",
"poster;mural;manuscript",
"rule and display;record and writing",
"himself",
"his students who illuminated the Constitution pages with him",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.20;F1.17",
"high",
"links: INS032; SCH028",
"canon_people.csv"
],
[
"PER245",
"Rabindranath Tagore",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1861",
"1941",
"",
"The Bengali poet founded Visva-Bharati at Santiniketan and the rural centre Sriniketan, where crafts like leather, weaving and batik were taught.",
"institution founding",
"school",
"care and access",
"himself",
"the teachers and village craftspeople of Sriniketan",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.20",
"high",
"links: INS032; SCH028",
"canon_people.csv"
],
[
"PER246",
"Ananda Coomaraswamy",
"",
"person",
"People",
"F1.9;THEME",
"AS-SAS;AM-EWD",
"1877",
"1947",
"",
"The Ceylonese-born scholar's Mediaeval Sinhalese Art (1908) and later writing described craft as traditional knowledge threatened by industry; he later curated at Boston.",
"craft survey;criticism;curating",
"text",
"record and writing",
"himself",
"the Kandyan craftsmen whose knowledge he recorded",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER247",
"Mohandas Karamchand Gandhi",
"Mahatma Gandhi",
"person",
"People",
"F1.9",
"AS-SAS",
"1869",
"1948",
"",
"The Indian leader made hand-spinning and khadi cloth a political act against imported British cloth.",
"hand spinning;charkha",
"khadi cloth;spinning wheel",
"clothing and adornment;exchange and value",
"himself",
"the women spinners whose paid labour khadi depended on",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.17",
"high",
"links: MOV081",
"canon_people.csv"
],
[
"PER248",
"Kamaladevi Chattopadhyay",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1903",
"1988",
"",
"The Indian activist chaired the All India Handicrafts Board from 1952 and built cooperatives, emporia and institutions to support craft workers.",
"policy;cooperatives",
"textile;craft emporium",
"exchange and value;care and access",
"herself",
"the craft workers whose names rarely appeared on the goods",
"none",
"Wikimedia Commons",
"R1",
"F1.17;F1.18;F1.29",
"high",
"links: INS034; MOV086",
"canon_people.csv"
],
[
"PER249",
"Pupul Jayakar",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1915",
"1997",
"",
"The Indian cultural administrator directed handloom and handicraft bodies and the Festivals of India abroad in the 1980s.",
"policy;exhibition",
"textile;exhibition",
"exchange and value",
"herself",
"the weavers and artisans shown abroad",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.15",
"high",
"links: MOV086",
"canon_people.csv"
],
[
"PER250",
"Gira Sarabhai",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1923",
"2021",
"",
"The Indian designer co-founded the Calico Museum of Textiles (1949) and the National Institute of Design in Ahmedabad.",
"institution founding;architecture",
"museum;textile",
"rule and display",
"herself",
"the weavers and dyers whose textiles the museum holds",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.24;F1.18",
"high",
"links: INS033",
"canon_people.csv"
],
[
"PER251",
"Gautam Sarabhai",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1917",
"1995",
"",
"The Indian industrialist co-founded the National Institute of Design (1961) after inviting Charles and Ray Eames to write the India Report (1958).",
"institution founding",
"school",
"care and access",
"himself",
"the craftspeople studied by the institute",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.17;F1.20",
"high",
"links: INS033",
"canon_people.csv"
],
[
"PER252",
"Charles Correa",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1930",
"2015",
"",
"The Indian architect designed the Gandhi Smarak Sangrahalaya and Jawahar Kala Kendra and low-rise housing using courtyards and open-to-sky space.",
"architecture;brick;climatic design",
"museum;housing",
"shelter",
"himself",
"the builders and masons",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: STY055",
"canon_people.csv"
],
[
"PER253",
"Balkrishna Doshi",
"B. V. Doshi",
"person",
"People",
"F1.9",
"AS-SAS",
"1927",
"2023",
"",
"The Indian architect worked with Le Corbusier and Louis Kahn and designed the Aranya low-cost housing in Indore, the first Indian to win the Pritzker Prize (2018).",
"architecture;concrete;site-and-services housing",
"housing;school",
"shelter",
"himself",
"the residents who built their own houses at Aranya",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.22a",
"high",
"",
"canon_people.csv"
],
[
"PER254",
"Laurie Baker",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1917",
"2007",
"",
"The British-born Indian architect built cheap brick buildings in Kerala with rat-trap bond and jali walls, cutting cement and steel.",
"brick masonry;rat-trap bond;jali",
"house;church;school",
"shelter",
"himself",
"the Kerala masons whose methods he learned",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.22;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER255",
"Pierre Jeanneret",
"",
"person",
"People",
"F1.11;F1.9",
"EU-WCE;AS-SAS",
"1896",
"1967",
"",
"The Swiss architect worked in Chandigarh (1951–65), designing furniture of teak and cane made by local carpenters, much later resold abroad.",
"teak;cane;carpentry",
"chair;table",
"shelter",
"himself; auction market",
"the Chandigarh carpenters who made the furniture",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.24",
"high",
"links: STY056",
"canon_people.csv"
],
[
"PER256",
"Maqbool Fida Husain",
"M. F. Husain",
"person",
"People",
"F1.9",
"AS-SAS",
"1915",
"2011",
"",
"The Indian painter began as a painter of cinema hoardings and made furniture and toys before becoming a leading member of the Progressive Artists' Group.",
"oil painting;hoarding painting;toy making",
"painting;toy",
"rule and display",
"himself",
"the hoarding painters' workshops he trained in",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.4",
"high",
"links: MOV083",
"canon_people.csv"
],
[
"PER257",
"Jangarh Singh Shyam",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1962",
"2001",
"",
"The Pardhan Gond artist moved from wall painting to paper and canvas at Bharat Bhavan in Bhopal, founding the Jangarh Kalam.",
"acrylic;ink;wall painting",
"painting",
"ritual and belief",
"himself; J. Swaminathan",
"the Gond artists who followed him; the dealers who controlled his contracts",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"high",
"links: SCH027",
"canon_people.csv"
],
[
"PER258",
"Sita Devi",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1914",
"2005",
"",
"The Mithila painter from Jitwarpur was among the first to move the region's wall painting onto paper for sale after the 1966–68 drought.",
"ink and colour on paper",
"painting",
"ritual and belief",
"herself; the All India Handicrafts Board",
"the Mithila women painters of earlier generations",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: STY124",
"canon_people.csv"
],
[
"PER259",
"Ganga Devi",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1928",
"1991",
"",
"The Mithila painter from a Kayastha family made line paintings and large series, including a series on her travels and her illness.",
"ink line painting",
"painting;mural",
"ritual and belief",
"herself",
"the Mithila women painters",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: STY124",
"canon_people.csv"
],
[
"PER260",
"Jivya Soma Mashe",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1934",
"2018",
"",
"The Warli artist was among the first men to take up the Warli wedding painting practice and bring it onto paper for sale.",
"rice paste;ink on paper",
"painting",
"ritual and belief",
"himself",
"the Warli women who painted the chowk for weddings",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"links: STY125",
"canon_people.csv"
],
[
"PER261",
"Mrinalini Mukherjee",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1949",
"2015",
"",
"The Indian sculptor knotted dyed hemp into large figures, and later worked in ceramics and bronze.",
"hemp knotting;ceramics;bronze",
"sculpture",
"ritual and belief",
"herself",
"the rope makers and knotting traditions she drew on",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER262",
"Martand Singh",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1947",
"2017",
"",
"The Indian textile revivalist curated the Vishwakarma exhibitions (1980s), commissioning weavers to recreate historic Indian textiles.",
"exhibition;revival weaving",
"textile",
"clothing and adornment",
"himself",
"the weavers who made the pieces",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.28a",
"high",
"links: MOV086",
"canon_people.csv"
],
[
"PER263",
"Jasleen Dhamija",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1933",
"2023",
"",
"The Indian textile historian worked for the handicrafts board and the UN on crafts across Asia and Africa and wrote on Indian textiles.",
"textile research",
"text",
"record and writing",
"herself",
"the makers she documented",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER264",
"Nelly Sethna",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1932",
"1992",
"",
"The Indian textile designer, trained in weaving at Cranbrook, designed for Bombay Dyeing, helped set up textile design at the National Institute of Design (1966) and researched kalamkari printing at Masulipatnam, bringing disused carved blocks back into use.",
"textile design;handloom",
"textile;tapestry",
"clothing and adornment",
"herself",
"the weavers and kalamkari printers who made her designs",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"medium",
"Round 2: the earlier claim about Weavers' Service Centres could not be sourced and was replaced.",
"canon_people.csv"
],
[
"PER265",
"Minnette de Silva",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1918",
"1998",
"",
"The Sri Lankan architect built modern houses in Kandy using local craftsmen, lacquer and dumbara weaving, and was the first Asian woman member of RIBA.",
"architecture;craft integration",
"house",
"shelter",
"herself",
"the Kandyan craftsmen she employed",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.18",
"high",
"links: STY055",
"canon_people.csv"
],
[
"PER266",
"Geoffrey Bawa",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1919",
"2003",
"",
"The Sri Lankan architect designed houses, hotels and the Parliament at Kotte shaped by climate, gardens and local craft.",
"architecture;landscape",
"house;hotel;parliament",
"shelter;rule and display",
"himself",
"the craftsmen and artists such as Laki Senanayake and Barbara Sansoni who worked on his buildings",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: STY055",
"canon_people.csv"
],
[
"PER267",
"Barbara Sansoni",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1928",
"2022",
"",
"The Sri Lankan designer founded Barefoot (1964), a handloom enterprise whose colour-block cottons are woven by rural women.",
"handloom;colour design",
"textile",
"clothing and adornment",
"herself",
"the weavers of Barefoot",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER268",
"Ena de Silva",
"",
"person",
"People",
"F1.9",
"AS-SAS",
"1922",
"2015",
"",
"The Sri Lankan batik artist made large batik hangings and set up a village workshop at Aluvihare employing local people.",
"batik;wax resist",
"textile;wall hanging",
"clothing and adornment",
"herself",
"the village workers of Aluvihare",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER269",
"Situ Panchen Chökyi Jungne",
"",
"person",
"People",
"F1.9",
"AS-HIM",
"1700",
"1774",
"",
"The Tibetan lama revived the Karma Gadri painting style and edited the Derge edition of the Kangyur printed from woodblocks.",
"thangka painting;woodblock printing",
"thangka;printed canon",
"ritual and belief;record and writing",
"Tibetan tradition",
"the Derge block carvers and his painting assistants",
"sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16;F1.28",
"high",
"links: SCH031; INS037",
"canon_people.csv"
],
[
"PER270",
"Thangtong Gyalpo",
"",
"person",
"People",
"F1.9",
"AS-HIM",
"1385",
"1464",
"traditional dates; some sources give a much longer life",
"The Tibetan engineer-saint is credited with building iron-chain suspension bridges and founding Tibetan opera.",
"iron chain forging;bridge building",
"bridge;stupa",
"transport;ritual and belief",
"Tibetan and Bhutanese tradition",
"the ironworkers and villagers who built the bridges",
"sacred",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"",
"canon_people.csv"
],
[
"PER271",
"Araniko",
"Anige",
"person",
"People",
"F1.9;F1.8",
"AS-HIM;AS-CHN",
"1245",
"1306",
"",
"The Newar artisan led craftsmen from Nepal to the Mongol court, where he designed the White Stupa in Beijing and headed imperial workshops.",
"bronze casting;architecture",
"stupa;Buddhist figure",
"ritual and belief",
"Yuan records",
"the Newar craftsmen who travelled with him",
"sacred",
"Wikimedia Commons;Met Open Access (CC0)",
"R3",
"F1.13;F1.17",
"high",
"links: SCH032; POL167",
"canon_people.csv"
],
[
"PER272",
"Suryavarman II",
"",
"person",
"People",
"F1.9",
"AS-MSE",
"1113",
"1150",
"reign dates, approximate",
"The Khmer king built Angkor Wat, with its long bas-reliefs, as his state temple.",
"sandstone construction;relief carving",
"temple",
"ritual and belief;rule and display",
"inscriptions; historians",
"the quarry workers, carvers and bonded labourers",
"sacred",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL209",
"canon_people.csv"
],
[
"PER273",
"Jayavarman VII",
"",
"person",
"People",
"F1.9",
"AS-MSE",
"1181",
"1218",
"reign dates, approximate",
"The Khmer king built Angkor Thom and the Bayon and founded hospitals and rest houses listed in inscriptions.",
"laterite and sandstone construction",
"temple;hospital",
"ritual and belief;care and access",
"inscriptions; historians",
"the labourers and temple servants listed in inscriptions",
"sacred;human-flow",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"Temple inscriptions list bonded workers. links: POL209",
"canon_people.csv"
],
[
"PER274",
"Kartini",
"Raden Ajeng Kartini",
"person",
"People",
"F1.9",
"AS-ISE",
"1879",
"1904",
"",
"The Javanese writer arranged sales of Jepara woodcarving to Dutch buyers through the Oost en West society.",
"woodcarving promotion",
"carving;furniture",
"exchange and value",
"her letters (published 1911)",
"the Jepara carvers whose work she promoted, few of them named",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.17",
"medium",
"Round 2: sources confirm she marketed Jepara carving to Semarang, Batavia and the Netherlands and worked with the Oost en West association; the scale of her role beyond that is less documented.",
"canon_people.csv"
],
[
"PER275",
"Eliza van Zuylen",
"",
"person",
"People",
"F1.9",
"AS-ISE",
"1863",
"1947",
"",
"The Indo-European batik entrepreneur ran a large workshop in Pekalongan producing floral batik signed with her name.",
"batik;wax resist",
"sarong;batik cloth",
"clothing and adornment",
"her signature on cloths",
"the Javanese women who drew the wax and dyed the cloth",
"none",
"Tropenmuseum/Wereldmuseum photos on Wikimedia Commons (CC BY-SA);Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"links: MKR054",
"canon_people.csv"
],
[
"PER276",
"Nguyễn Gia Trí",
"",
"person",
"People",
"F1.9",
"AS-MSE",
"1908",
"1993",
"",
"The Vietnamese painter turned traditional lacquer into a painting medium with large layered and polished panels.",
"lacquer;eggshell inlay;polishing",
"panel;screen",
"rule and display",
"himself",
"the lacquer craftsmen of Hanoi",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: SCH033",
"canon_people.csv"
],
[
"PER277",
"Lang Dulay",
"",
"person",
"People",
"F1.9",
"AS-ISE",
"1928",
"2015",
"born c. 1928",
"The T'boli weaver of t'nalak abaca cloth received the National Living Treasures award of the Philippines (1998).",
"abaca;ikat;tie-dye",
"cloth",
"clothing and adornment;ritual and belief",
"herself; T'boli community",
"the T'boli women weavers whose designs come in dreams",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER278",
"Whang-od Oggay",
"",
"person",
"People",
"F1.9",
"AS-ISE",
"1917",
"",
"born c. 1917; living",
"The Kalinga tattooist of Buscalan practises batok hand-tapped tattooing and has trained younger relatives.",
"hand-tapped tattoo;soot ink",
"tattoo",
"clothing and adornment;ritual and belief",
"herself; the Buscalan community",
"the Kalinga tattooists before her",
"Indigenous-community;living-community",
"community-published site (link-out)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER279",
"Puabi",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-2600",
"-2550",
"fl.; approximate",
"The woman buried in tomb PG 800 at Ur, named on a cylinder seal, was laid out with a headdress of gold leaves and beaded capes of lapis lazuli and carnelian.",
"gold sheet;lapis lazuli;carnelian beadwork",
"headdress;bead cape;cylinder seal",
"clothing and adornment;rule and display",
"Leonard Woolley's excavation (1927–28); her seal",
"the attendants buried with her; the metalworkers and bead makers",
"funerary",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.24;F1.18",
"high",
"Her title (queen) comes from the seal; finds are split among Baghdad, London and Philadelphia. links: CIV056; NET018",
"canon_people.csv"
],
[
"PER280",
"Enheduanna",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-2285",
"-2250",
"fl.; approximate",
"The daughter of Sargon of Akkad, high priestess at Ur, is shown on an inscribed alabaster disc and is credited with hymns, often called the earliest named author.",
"relief carving;cuneiform",
"disc;hymn",
"ritual and belief;record and writing",
"the disc's inscription; later copies of hymns",
"the scribes who copied the hymns centuries later; the carver of the disc",
"sacred",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5;F1.18;F1.28",
"high",
"Authorship of the hymns is debated. links: POL093",
"canon_people.csv"
],
[
"PER281",
"Gudea",
"Gudea of Lagash",
"person",
"People",
"F1.9a",
"WA-MES",
"-2144",
"-2124",
"reign dates, approximate",
"The ruler of Lagash had many diorite statues of himself carved, with inscriptions saying the stone and timber for his temple came from distant lands such as Magan.",
"diorite carving;temple building",
"statue;foundation peg",
"rule and display;ritual and belief",
"his own inscriptions",
"the sculptors and the traders who brought diorite from Magan",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"links: POL092; CIV061",
"canon_people.csv"
],
[
"PER282",
"Ea-nasir",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-1760",
"-1740",
"fl.; approximate",
"The Ur merchant dealt in copper from Dilmun and is known from tablets, including a customer's complaint about poor-quality ingots.",
"copper trade",
"ingot;letter tablet",
"exchange and value",
"cuneiform tablets from his house; historians",
"the miners and smelters of Magan; the customers who wrote to him",
"none",
"Cuneiform Digital Library Initiative (link out);British Museum Collection Online (CC BY-NC-SA, link out)",
"R3",
"F1.13;F1.28",
"high",
"links: NET016; POL095",
"canon_people.csv"
],
[
"PER283",
"Lamassī",
"",
"person",
"People",
"F1.9a",
"WA-ANA;WA-MES",
"-1900",
"-1860",
"fl.; approximate",
"The Assur woman, wife of the merchant Pūšu-kēn, wove textiles for export to Kanesh and wrote letters about cloth, prices and household matters.",
"wool weaving;letter writing",
"textile;letter tablet",
"clothing and adornment;exchange and value",
"the Kanesh archive; Assyriologists",
"the other Assur women weavers and the enslaved workers in their houses",
"human-flow",
"Cuneiform Digital Library Initiative (link out)",
"R3",
"F1.18;F1.28",
"medium",
"Old Assyrian households held enslaved people. links: INS093; NET017",
"canon_people.csv"
],
[
"PER284",
"Tapputi",
"Tapputi-Belatekallim",
"person",
"People",
"F1.9a",
"WA-MES",
"-1250",
"-1150",
"fl.; approximate",
"A cuneiform tablet names Tapputi, a palace overseer, as a perfume maker and records her distillation-like method, often cited as the earliest named chemist.",
"perfume making;extraction",
"perfume;tablet",
"clothing and adornment",
"a cuneiform text; historians of chemistry",
"the assistant named with her and other palace perfumers",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.28",
"medium",
"Claims of 'first chemist' are later framing.",
"canon_people.csv"
],
[
"PER285",
"Ashurbanipal",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-669",
"-631",
"reign dates, approximate",
"The Assyrian king gathered cuneiform tablets at Nineveh into a library and commissioned the lion-hunt reliefs.",
"tablet collecting;relief carving",
"tablet;relief",
"record and writing;rule and display",
"his own inscriptions; excavators",
"the scribes who copied the tablets and the sculptors of the reliefs",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out);Cuneiform Digital Library Initiative (link out)",
"R3",
"F1.28;F1.17",
"high",
"links: POL096",
"canon_people.csv"
],
[
"PER286",
"Nebuchadnezzar II",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-605",
"-562",
"reign dates",
"The Babylonian king rebuilt Babylon with glazed-brick gates and processional walls such as the Ishtar Gate, stamped bricks naming him.",
"glazed moulded brick;stamped brick",
"gate;wall",
"rule and display;ritual and belief",
"his own inscriptions",
"the brickmakers and deported people, including Judaeans, in Babylon",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.23",
"high",
"links: POL097",
"canon_people.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
