insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PER287",
"Ennigaldi-Nanna",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"-555",
"-540",
"fl.; approximate",
"The priestess at Ur, daughter of Nabonidus, lived where Woolley found older objects kept together with a labelled clay cylinder, which he called a museum.",
"collecting;labelling",
"clay cylinder;antiquity",
"ritual and belief;record and writing",
"Leonard Woolley's excavation report",
"the older makers whose objects were gathered",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.24;F1.3",
"medium",
"The 'first museum' label is Woolley's interpretation.",
"canon_people.csv"
],
[
"PER288",
"Darius I",
"",
"person",
"People",
"F1.9a",
"WA-IRN",
"-522",
"-486",
"reign dates",
"The Achaemenid king's foundation charter at Susa lists the craftsmen and materials brought from across the empire to build his palace.",
"palace building;glazed brick;stone carving",
"palace;relief;foundation text",
"rule and display",
"his own inscriptions",
"the workers of Persepolis paid in rations (kurtas)",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"Status of the workers varied; some were deportees. links: POL105; MKR091",
"canon_people.csv"
],
[
"PER289",
"Ennion",
"",
"person",
"People",
"F1.9a;F1.11",
"WA-LEV;EU-GRR",
"1",
"50",
"fl.; first half of the 1st century CE",
"The glassmaker from Sidon signed mould-blown cups and jugs with his name in Greek, one of the first known glass signatures.",
"mould-blown glass",
"cup;jug",
"food and storage",
"signatures on vessels; archaeologists",
"the workshop blowers and the copyists of his moulds",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.26;F1.14",
"high",
"links: POL120",
"canon_people.csv"
],
[
"PER290",
"Toros Roslin",
"",
"person",
"People",
"F1.9a;F1.10",
"WA-ANA;WA-CAU",
"1210",
"1270",
"approximate",
"The Armenian manuscript painter at Hromkla in Cilicia signed Gospel books with rich colour and figures.",
"illumination;gold leaf",
"Gospel book",
"ritual and belief;record and writing",
"colophons",
"the scribes and binders",
"sacred",
"Walters Art Museum (CC0);Wikimedia Commons",
"R3",
"F1.26",
"high",
"links: SCH046; POL110",
"canon_people.csv"
],
[
"PER291",
"Momik",
"",
"person",
"People",
"F1.9a",
"WA-CAU",
"1270",
"1333",
"died 1333; birth date unknown",
"The Armenian architect, sculptor and illuminator carved khachkars and worked on the church at Noravank.",
"stone carving;architecture;illumination",
"khachkar;church",
"ritual and belief",
"inscriptions; Armenian tradition",
"his workshop",
"sacred",
"Wikimedia Commons",
"R3",
"F1.26",
"medium",
"",
"canon_people.csv"
],
[
"PER292",
"Austen Henry Layard",
"",
"person",
"People",
"F1.9a;F1.11",
"WA-MES;EU-BLC",
"1817",
"1894",
"",
"The British excavator dug at Nimrud and Nineveh (1845–51) and shipped reliefs and colossi to the British Museum.",
"excavation;removal",
"relief;lamassu",
"rule and display",
"himself (Nineveh and Its Remains)",
"the local labourers and Hormuzd Rassam, who ran the digs",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out);Internet Archive (public-domain scans)",
"R3",
"F1.24",
"high",
"Excavated under Ottoman permits.",
"canon_people.csv"
],
[
"PER293",
"Hormuzd Rassam",
"",
"person",
"People",
"F1.9a;F1.6",
"WA-MES;AF-HRN",
"1826",
"1910",
"",
"The Assyrian Christian archaeologist from Mosul found the Ashurbanipal library tablets and the lion-hunt reliefs, but was long overshadowed by British excavators.",
"excavation",
"tablet;relief",
"rule and display",
"himself; British Museum",
"himself, when finds were credited to Layard",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out)",
"R3",
"F1.24;F1.26",
"high",
"He was also a British envoy held captive by Tewodros II before Maqdala.",
"canon_people.csv"
],
[
"PER294",
"Gertrude Bell",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"1868",
"1926",
"",
"The British official and archaeologist set up the Iraq Museum's collection and drafted Iraq's antiquities law, passed in 1924.",
"museum founding;antiquities law",
"museum",
"rule and display",
"herself",
"Iraqi archaeologists and the division of finds that favoured foreign excavators",
"none",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER295",
"Leonard Woolley",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"1880",
"1960",
"",
"The British archaeologist excavated the Royal Cemetery of Ur (1922–34), whose finds were divided between Baghdad, London and Philadelphia.",
"excavation;reconstruction",
"headdress;lyre;gaming board",
"rule and display",
"himself",
"Katharine Woolley and the Iraqi workforce led by foreman Hamoudi",
"funerary",
"British Museum Collection Online (CC BY-NC-SA, link out);open-access excavation reports",
"R3",
"F1.24;F1.28a",
"high",
"links: CIV056",
"canon_people.csv"
],
[
"PER296",
"Katharine Woolley",
"",
"person",
"People",
"F1.9a",
"WA-MES",
"1888",
"1945",
"",
"The British archaeologist worked on the Ur excavations and drew reconstructions of finds such as Puabi's headdress.",
"archaeological drawing;reconstruction",
"drawing",
"rule and display",
"herself",
"herself, when work is credited to Leonard alone",
"none",
"open-access excavation reports",
"R3",
"F1.18;F1.28a",
"medium",
"Round 2: an early reconstruction of Puabi's headdress by Katharine Woolley is documented (ISAW exhibition).",
"canon_people.csv"
],
[
"PER297",
"Heinrich Schliemann",
"",
"person",
"People",
"F1.11;F1.9a",
"WA-ANA;EU-GRR",
"1822",
"1890",
"",
"The German businessman dug at Troy (Hisarlik) and Mycenae, smuggled 'Priam's Treasure' out of the Ottoman Empire, and its removal to Moscow in 1945 made it wartime loot as well.",
"excavation;removal",
"gold jewellery;vessel",
"rule and display",
"himself",
"the Ottoman authorities and local workers; Sophia Schliemann, pictured in the jewels; the Bronze Age makers",
"conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24;F1.19a",
"high",
"links: POL116; POL150",
"canon_people.csv"
],
[
"PER298",
"Ibn Muqla",
"Abu Ali Muhammad ibn Muqla",
"person",
"People",
"F1.10",
"WA-MES",
"886",
"940",
"",
"The Abbasid vizier is credited with a proportioned system for Arabic scripts, measuring letters in rhombic dots of the pen.",
"calligraphy;proportion system",
"Qur'an;document",
"record and writing",
"later calligraphic tradition",
"the scribes who used and refined the system",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.15",
"high",
"No works securely by him survive. links: DYN010",
"canon_people.csv"
],
[
"PER299",
"Ibn al-Bawwab",
"",
"person",
"People",
"F1.10",
"WA-MES",
"960",
"1022",
"born c. 960s; died 1022",
"The Baghdad calligrapher refined proportioned scripts; a Qur'an copied by him in 1000–01 is in the Chester Beatty Library.",
"calligraphy;illumination",
"Qur'an",
"record and writing;ritual and belief",
"colophon; later tradition",
"the paper makers and illuminators; his early trade as a house painter",
"sacred",
"Wikimedia Commons",
"R3",
"F1.26",
"high",
"links: DYN013",
"canon_people.csv"
],
[
"PER300",
"Yaqut al-Musta'simi",
"",
"person",
"People",
"F1.10",
"WA-MES",
"1221",
"1298",
"approximate",
"The Abbasid court calligrapher refined the six scripts, and his name was later forged on many manuscripts.",
"calligraphy;cut reed pen",
"Qur'an;manuscript",
"record and writing;ritual and belief",
"later calligraphic tradition",
"his students; the many copyists whose work carries his name",
"sacred",
"Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14;F1.26",
"high",
"links: DYN010",
"canon_people.csv"
],
[
"PER301",
"Zubaidah bint Ja'far",
"",
"person",
"People",
"F1.10",
"WA-ARB;WA-MES",
"766",
"831",
"born c. 766",
"The Abbasid princess funded wells, cisterns and stations along the pilgrim road from Kufa to Mecca, later called Darb Zubaydah.",
"cistern;well building",
"road station;cistern",
"transport;care and access",
"Arabic chroniclers",
"the builders and the Bedouin who maintained the route",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: DYN010",
"canon_people.csv"
],
[
"PER302",
"Fatima al-Fihri",
"",
"person",
"People",
"F1.10;F1.6",
"AF-MAG",
"800",
"880",
"fl.; mosque founded 859",
"Tradition credits the woman from Kairouan with founding the Qarawiyyin mosque in Fez in 859, later a centre of learning.",
"patronage;architecture",
"mosque",
"ritual and belief;care and access",
"later historians (Ibn Abi Zar, 14th century)",
"the builders; the lack of contemporary sources",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"medium",
"Early sources are thin.",
"canon_people.csv"
],
[
"PER303",
"al-ʿIjliyya bint al-ʿIjliyy",
"Mariam al-Ijliya; Mariam al-Asturlabiyya (modern names)",
"person",
"People",
"F1.10",
"WA-LEV",
"944",
"967",
"fl.; approximate",
"Ibn al-Nadim names her, the daughter of the astrolabe maker al-ʿIjliyy and like him a pupil of Nastulus, as an astrolabe maker employed by Sayf al-Dawla in Aleppo.",
"astrolabe making;brass engraving",
"astrolabe",
"tools;record and writing",
"Ibn al-Nadim's Fihrist",
"the other women instrument makers unrecorded",
"none",
"Wikimedia Commons",
"R3",
"F1.18",
"low",
"Known from one source (Ibn al-Nadim, Fihrist); the first name 'Mariam' is a modern addition not found there.",
"canon_people.csv"
],
[
"PER304",
"Al-Jazari",
"Ismail ibn al-Razzaz al-Jazari",
"person",
"People",
"F1.10",
"WA-ANA",
"1136",
"1206",
"",
"The engineer at the Artuqid court wrote The Book of Knowledge of Ingenious Mechanical Devices (1206), with drawings of clocks, pumps and automata.",
"mechanical engineering;technical drawing",
"treatise;water clock;automaton",
"tools;record and writing",
"himself",
"the craftsmen who built the machines; the painters of later copies",
"none",
"British Library digitised manuscripts (public-domain items);Wikimedia Commons",
"R3",
"F1.28;F1.19",
"high",
"links: DYN019",
"canon_people.csv"
],
[
"PER305",
"Abu Zayd al-Kashani",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1186",
"1219",
"fl.; dated works",
"The Kashan potter signed and dated more lustre and mina'i wares than any other potter of the period.",
"lustre;mina'i overglaze;fritware",
"bowl;tile",
"food and storage;rule and display",
"signatures on wares",
"the family potters and the painters he worked with",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.26",
"high",
"links: MKR056",
"canon_people.csv"
],
[
"PER306",
"Abu'l Qasim Kashani",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1290",
"1320",
"fl.; treatise 1301",
"A member of a Kashan potters' family wrote a treatise on precious stones (1301) with a chapter on how fritware and lustre were made.",
"technical writing;fritware;lustre",
"treatise",
"record and writing",
"himself",
"the potters whose recipes he recorded",
"none",
"Wikimedia Commons",
"R3",
"F1.28",
"high",
"links: MKR056",
"canon_people.csv"
],
[
"PER307",
"Muhammad ibn al-Zayn",
"",
"person",
"People",
"F1.10",
"AF-EGY;WA-LEV",
"1300",
"1340",
"fl.; approximate",
"The Mamluk metalworker signed the brass basin inlaid with silver and gold known as the Baptistère de Saint Louis, now in the Louvre.",
"brass;silver and gold inlay",
"basin",
"rule and display",
"signatures on the basin",
"workshop inlayers",
"none",
"Wikimedia Commons",
"R3",
"F1.26;F1.24",
"high",
"links: STY104",
"canon_people.csv"
],
[
"PER308",
"Sultan Hasan",
"al-Nasir Hasan",
"person",
"People",
"F1.10",
"AF-EGY",
"1335",
"1361",
"",
"The Mamluk sultan built the huge madrasa-mosque in Cairo (1356–63), funded in part, historians suggest, from estates left by plague victims.",
"stone masonry;carved stucco;inlaid metal doors",
"mosque;madrasa",
"ritual and belief;rule and display",
"Mamluk chroniclers",
"the masons and the workers who died in the plague years",
"none",
"Wikimedia Commons;Archnet (link-out)",
"R3",
"F1.17",
"high",
"links: POL042",
"canon_people.csv"
],
[
"PER309",
"Baysunghur",
"",
"person",
"People",
"F1.10;F1.12a",
"AS-CEN;WA-IRN",
"1397",
"1433",
"",
"The Timurid prince ran a library-workshop at Herat whose calligraphers, painters and binders made manuscripts such as his Shahnama (1430).",
"court workshop;manuscript",
"manuscript",
"record and writing;rule and display",
"a report (arzadasht) from his workshop",
"the forty calligraphers and the painters named in the report",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.28",
"high",
"links: INS043; SCH019",
"canon_people.csv"
],
[
"PER310",
"Kamal ud-Din Bihzad",
"",
"person",
"People",
"F1.10",
"AS-CEN;WA-IRN",
"1450",
"1535",
"approximate",
"The Herat painter, later head of the Safavid royal library at Tabriz, was praised for painting that later artists copied and forged.",
"opaque watercolour",
"manuscript painting",
"rule and display",
"Persian writers; signatures",
"his workshop and the many painters later credited in his name",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.26;F1.14",
"high",
"links: SCH019",
"canon_people.csv"
],
[
"PER311",
"Shah Tahmasp I",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1514",
"1576",
"",
"The Safavid shah commissioned a Shahnama with 258 paintings, which he later gave to the Ottoman sultan.",
"court patronage;manuscript",
"manuscript;carpet",
"rule and display",
"Safavid chronicles",
"the painters, gilders and binders of his workshop",
"none",
"Met Open Access (CC0)",
"R3",
"F1.17",
"high",
"The manuscript was later broken up (Houghton Shahnama). links: POL236",
"canon_people.csv"
],
[
"PER312",
"Maqsud Kashani",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1539",
"1540",
"fl.; dated 946 AH",
"The name woven into the Ardabil carpets with the date 946 AH (1539–40), whether as weaver, designer or overseer.",
"knotted wool pile;silk",
"carpet",
"ritual and belief;shelter",
"the woven inscription",
"the many weavers who knotted the carpets",
"none",
"Wikimedia Commons",
"R3",
"F1.26",
"high",
"His role is uncertain. links: POL236",
"canon_people.csv"
],
[
"PER313",
"Shah Abbas I",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1571",
"1629",
"",
"The Safavid shah rebuilt Isfahan and moved Armenian merchants and craftsmen from Julfa to New Julfa (1604–05) to run the silk trade.",
"urban planning;silk trade",
"mosque;bazaar;silk",
"exchange and value;rule and display",
"Safavid chronicles",
"the deported Armenians and Georgians",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.13",
"high",
"links: POL236; INS046",
"canon_people.csv"
],
[
"PER314",
"Reza Abbasi",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1565",
"1635",
"approximate",
"The Isfahan painter made single-page drawings and paintings for albums, sold to a wider market than the royal library.",
"ink drawing;opaque watercolour",
"album page",
"rule and display",
"signatures",
"his workshop and students",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.21;F1.26",
"high",
"links: SCH021",
"canon_people.csv"
],
[
"PER315",
"Mir Emad Hasani",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1554",
"1615",
"",
"The Safavid calligrapher is regarded as a master of nastaliq; his samples were collected and copied widely.",
"calligraphy;nastaliq",
"album page",
"record and writing",
"later calligraphic tradition",
"students who continued his style",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER316",
"Suleiman I",
"Süleyman the Magnificent",
"person",
"People",
"F1.10;F1.11",
"WA-ANA;EU-BYZ",
"1494",
"1566",
"",
"The Ottoman sultan's court workshops (ehl-i hiref) set the court style in tiles, textiles, book arts and metalwork.",
"court workshops;Iznik tile",
"mosque;tile;kaftan",
"rule and display",
"Ottoman registers",
"the paid artisans listed in court registers",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: INS041; STY109",
"canon_people.csv"
],
[
"PER317",
"Hürrem Sultan",
"Roxelana",
"person",
"People",
"F1.10",
"WA-ANA",
"1502",
"1558",
"born c. 1502–04",
"The wife of Suleiman, taken captive as a young woman, funded the Haseki Hürrem complex in Istanbul and charitable foundations in Jerusalem, Mecca and Edirne.",
"patronage",
"mosque;soup kitchen;bath",
"ritual and belief;care and access",
"Ottoman records",
"the builders; the other enslaved women of the harem",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: INS044",
"canon_people.csv"
],
[
"PER318",
"Mihrimah Sultan",
"",
"person",
"People",
"F1.10",
"WA-ANA",
"1522",
"1578",
"",
"The Ottoman princess commissioned two mosques by Sinan in Istanbul, at Üsküdar and Edirnekapı.",
"patronage",
"mosque",
"ritual and belief",
"Ottoman records",
"the builders",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER319",
"Mimar Sinan",
"",
"person",
"People",
"F1.10",
"WA-ANA",
"1490",
"1588",
"born c. 1490",
"The Ottoman chief architect, recruited through the devshirme levy of Christian boys, designed hundreds of buildings, including the Süleymaniye and Selimiye mosques.",
"stone masonry;dome construction",
"mosque;bridge;bath",
"ritual and belief;shelter",
"his autobiographies (tezkire)",
"the corps of court architects, masons and labourers",
"human-flow",
"Wikimedia Commons;Archnet (link-out)",
"R3",
"F1.17;F1.26",
"high",
"Devshirme was a forced levy. links: STY109",
"canon_people.csv"
],
[
"PER320",
"Şahkulu",
"Shahkulu",
"person",
"People",
"F1.10",
"WA-ANA",
"1515",
"1556",
"fl.; brought to Istanbul 1515; died by 1555–56; birth date unknown",
"The Iranian court painter, trained in Tabriz and brought to Istanbul in 1515, led the saz style of feathery leaves and fantastic creatures used in tiles and textiles.",
"ink drawing;design",
"drawing;tile design",
"rule and display",
"Ottoman palace registers",
"the tile makers and weavers who used his designs",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.15",
"high",
"links: STY110; INS042",
"canon_people.csv"
],
[
"PER321",
"Kara Memi",
"",
"person",
"People",
"F1.10",
"WA-ANA",
"1545",
"1566",
"fl.; approximate",
"The Ottoman court illuminator developed the floral style of tulips, carnations and hyacinths that spread to tiles and textiles.",
"illumination;gold",
"manuscript;tile design",
"rule and display",
"Ottoman palace registers",
"the tile painters and weavers who used the designs",
"none",
"Wikimedia Commons",
"R3",
"F1.15",
"high",
"links: INS042",
"canon_people.csv"
],
[
"PER322",
"Şeyh Hamdullah",
"Sheikh Hamdullah",
"person",
"People",
"F1.10",
"WA-ANA",
"1436",
"1520",
"",
"The Ottoman calligrapher reworked Yaqut's six scripts into the Ottoman style taught for centuries.",
"calligraphy",
"Qur'an;album",
"record and writing",
"Ottoman calligraphic tradition",
"his students",
"sacred",
"Wikimedia Commons",
"R3",
"F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER323",
"Timur",
"Tamerlane",
"person",
"People",
"F1.12a;F1.10",
"AS-CEN",
"1336",
"1405",
"",
"The conqueror took craftsmen from captured cities such as Damascus to Samarkand to build and decorate his capital.",
"tile mosaic;architecture",
"mosque;tomb",
"rule and display",
"Clavijo and Persian chroniclers",
"the deported craftsmen",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.23",
"high",
"links: POL235",
"canon_people.csv"
],
[
"PER324",
"Chinggis Khan",
"Genghis Khan",
"person",
"People",
"F1.12a",
"AS-CEN",
"1162",
"1227",
"born c. 1162",
"The Mongol ruler's armies spared and deported artisans from conquered cities, forming artisan colonies across the empire.",
"artisan relocation",
"textile;metalwork",
"war",
"Persian and Chinese chroniclers",
"the deported artisans",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.23",
"high",
"links: POL233; MKR092",
"canon_people.csv"
],
[
"PER325",
"Ibn Battuta",
"",
"person",
"People",
"F1.13;F1.10",
"AF-MAG;GL",
"1304",
"1369",
"died 1368 or 1369",
"The Moroccan traveller's Rihla describes goods and makers from Mali to China, including cloth, copper and porcelain.",
"travel writing",
"text",
"record and writing",
"himself; his editor Ibn Juzayy",
"his editor who shaped the text",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.13;F1.28",
"high",
"links: NET005",
"canon_people.csv"
],
[
"PER326",
"Abraham Ben Yiju",
"",
"person",
"People",
"F1.13;F1.9",
"AF-MAG;AS-SAS",
"1120",
"1160",
"fl.; approximate",
"The Tunisian Jewish merchant ran a bronze workshop in Mangalore and traded with Aden, as recorded in Cairo Geniza letters.",
"bronze casting;trade",
"bronze vessel;letter",
"exchange and value",
"Cairo Geniza letters; S. D. Goitein",
"Ashu, the enslaved Nair woman he freed and married, and his Indian slave-agent Bomma",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.28",
"medium",
"links: DIA004",
"canon_people.csv"
],
[
"PER327",
"Hassan Massoudy",
"",
"person",
"People",
"F1.10;F1.11",
"WA-MES;EU-WCE",
"1944",
"",
"born 1944; living",
"The Iraqi calligrapher, based in Paris, makes large Arabic calligraphies with wide reed and card tools.",
"calligraphy",
"work on paper",
"record and writing",
"himself",
"the Baghdad calligraphers he trained with",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER328",
"Mohammad Ehsai",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1939",
"",
"born 1939; living",
"The Iranian calligrapher-painter turns nastaliq letters into large abstract compositions.",
"calligraphy;painting",
"painting",
"record and writing",
"himself",
"the calligraphic lineage he trained in",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: MOV077",
"canon_people.csv"
],
[
"PER329",
"Monir Shahroudy Farmanfarmaian",
"",
"person",
"People",
"F1.10",
"WA-IRN",
"1922",
"2019",
"",
"The Iranian artist made mirror mosaics with craftsmen trained in shrine mirror work (ayeneh-kari).",
"mirror mosaic;reverse glass painting",
"mosaic;relief",
"rule and display",
"herself",
"the mirror craftsmen who cut and set the pieces",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER330",
"Jewad Selim",
"",
"person",
"People",
"F1.10",
"WA-MES",
"1919",
"1961",
"",
"The Iraqi sculptor co-founded the Baghdad Modern Art Group and designed the Monument of Freedom in Baghdad.",
"bronze;relief",
"monument",
"rule and display",
"himself",
"the Italian foundry and workers who cast the figures",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: MOV078",
"canon_people.csv"
],
[
"PER331",
"Lorna Selim",
"",
"person",
"People",
"F1.10",
"WA-MES",
"1928",
"2021",
"",
"The British-born painter married the sculptor Jewad Selim, taught drawing to architecture students at Baghdad University in the 1960s and painted the city's vernacular buildings.",
"painting;drawing",
"painting",
"rule and display",
"herself",
"herself, as the partner of a famous sculptor",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"medium",
"",
"canon_people.csv"
],
[
"PER332",
"Shakir Hassan Al Said",
"",
"person",
"People",
"F1.10",
"WA-MES",
"1925",
"2004",
"",
"The Iraqi painter and theorist developed the One Dimension group (1971), using Arabic letters and wall surfaces.",
"painting;theory",
"painting",
"record and writing",
"himself",
"the calligraphers and wall writers whose marks he used",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.5",
"high",
"links: MOV078; MOV077",
"canon_people.csv"
],
[
"PER333",
"Madiha Omar",
"",
"person",
"People",
"F1.10",
"WA-MES",
"1908",
"2005",
"",
"The Syrian-born Iraqi painter exhibited abstractions of Arabic letters in 1949, an early example of the hurufiyya movement.",
"painting;letter forms",
"painting",
"record and writing",
"herself",
"the calligraphers whose letters she reshaped",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"links: MOV077",
"canon_people.csv"
],
[
"PER334",
"Saloua Raouda Choucair",
"",
"person",
"People",
"F1.10",
"WA-LEV",
"1916",
"2017",
"",
"The Lebanese artist made modular sculptures of interlocking parts, drawing on Islamic geometry and poetry.",
"stone;wood;modular sculpture",
"sculpture",
"rule and display",
"herself",
"the craftsmen who cut her pieces",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER335",
"Fahrelnissa Zeid",
"",
"person",
"People",
"F1.10",
"WA-ANA;WA-LEV",
"1901",
"1991",
"",
"The Turkish painter made large abstract paintings and later painted chicken bones and resin works in Amman.",
"painting;resin",
"painting",
"rule and display",
"herself",
"her students in Amman",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER336",
"Wijdan Ali",
"",
"person",
"People",
"F1.10;THEME",
"WA-LEV",
"1939",
"",
"born 1939; living",
"The Jordanian artist and art historian founded the Jordan National Gallery of Fine Arts and wrote on modern art in the Islamic world.",
"painting;art history",
"book;painting",
"record and writing",
"herself",
"the artists outside capitals left out of national surveys",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER337",
"Hassan Sharif",
"",
"person",
"People",
"F1.10",
"WA-ARB",
"1951",
"2016",
"",
"The Emirati artist made 'Objects', bundles of cheap manufactured goods woven and tied, a comment on consumer culture in Dubai.",
"weaving;tying;assemblage",
"object;installation",
"exchange and value",
"himself",
"the migrant workers and makers of the goods he used",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21;F1.22",
"high",
"",
"canon_people.csv"
],
[
"PER338",
"Abdulqader Al Rais",
"",
"person",
"People",
"F1.10",
"WA-ARB",
"1951",
"",
"born 1951; living",
"The Emirati painter is known for watercolours of old Dubai houses and later for abstractions with Arabic letters.",
"watercolour;painting",
"painting",
"rule and display",
"himself",
"the builders of the coral and gypsum houses he painted",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.29",
"medium",
"",
"canon_people.csv"
],
[
"PER339",
"Najat Makki",
"",
"person",
"People",
"F1.10",
"WA-ARB",
"1956",
"",
"born 1956; living",
"The Emirati painter was the first Emirati woman to receive a government scholarship to study art abroad (1977), later took a doctorate in Cairo (2001), and works with colour, light and Emirati settings and folklore.",
"painting;relief",
"painting",
"rule and display",
"herself",
"the women's crafts she drew on",
"living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"medium",
"Biography checked round 2 (Wikipedia).",
"canon_people.csv"
],
[
"PER340",
"Safeya Binzagr",
"",
"person",
"People",
"F1.10",
"WA-ARB",
"1940",
"2024",
"",
"The Saudi painter documented Hijazi dress, houses and customs and opened a cultural centre in Jeddah (Darat Safeya Binzagr).",
"painting;etching;costume collection",
"painting;dress",
"clothing and adornment",
"herself",
"the women whose dress and customs she recorded",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"medium",
"Death year 2024 verified.",
"canon_people.csv"
],
[
"PER341",
"Sergei Rudenko",
"",
"person",
"People",
"F1.12a",
"AS-CEN;AS-NTH",
"1885",
"1969",
"",
"The Soviet archaeologist excavated the frozen Pazyryk tombs in the Altai (1929, 1947–49), finding the oldest known knotted pile carpet.",
"excavation",
"carpet;saddle;felt",
"clothing and adornment;transport",
"himself",
"the Altai peoples who regard the burials as ancestral",
"funerary;ancestral",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: CIV087; STY098",
"canon_people.csv"
],
[
"PER342",
"Peter I",
"Peter the Great",
"person",
"People",
"F1.11;F1.12a",
"EU-EER;AS-NTH",
"1672",
"1725",
"",
"The Russian tsar founded the Kunstkamera and gathered Siberian gold from burial mounds, now in the Hermitage.",
"collecting;shipbuilding",
"gold plaque;ship",
"rule and display",
"himself; Russian state",
"the grave robbers and Siberian peoples; the makers of the Scythian-Siberian gold",
"funerary",
"Wikimedia Commons",
"R3",
"F1.24;F1.17",
"high",
"links: POL144",
"canon_people.csv"
],
[
"PER343",
"Tupaia",
"",
"person",
"People",
"F1.12;F1.13",
"OC-POL",
"1725",
"1770",
"born c. 1725; died 1770 in Batavia",
"The Raiatean navigator and priest sailed with Cook in 1769, drew a chart of some 70 Pacific islands from his knowledge and made drawings of the voyage once credited to Joseph Banks.",
"wayfinding;drawing",
"chart;drawing",
"transport;record and writing",
"the voyage records; historians (drawings reattributed in 1997)",
"himself, when his drawings were credited to Banks; the navigators whose knowledge he held",
"Indigenous-community",
"British Library digitised manuscripts (public-domain items);Wikimedia Commons",
"R2",
"F1.26;F1.13",
"high",
"links: NET045",
"canon_people.csv"
],
[
"PER344",
"Mau Piailug",
"Pius Mau Piailug",
"person",
"People",
"F1.12;F1.13",
"OC-MIC;OC-POL",
"1932",
"2010",
"",
"The navigator from Satawal guided the voyaging canoe Hōkūleʻa from Hawaiʻi to Tahiti in 1976 without instruments and later taught Hawaiian navigators.",
"wayfinding;canoe sailing",
"voyaging canoe",
"transport",
"himself; the Polynesian Voyaging Society",
"the Satawal navigators who taught him; his breaking of the rule that such knowledge stayed in the lineage",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.13;F1.29",
"high",
"links: NET045",
"canon_people.csv"
],
[
"PER345",
"Herb Kawainui Kāne",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1928",
"2011",
"",
"The Hawaiian artist designed the voyaging canoe Hōkūleʻa from historical drawings and co-founded the Polynesian Voyaging Society (1973).",
"canoe design;painting",
"voyaging canoe;painting",
"transport",
"himself",
"the builders of Hōkūleʻa; the Pacific canoe-builders whose designs were drawn by Europeans",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.28a;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER346",
"James Cook",
"",
"person",
"People",
"F1.12;F1.11",
"OC-POL;EU-BLC",
"1728",
"1779",
"",
"The British naval officer's three Pacific voyages (1768–79) brought back thousands of Pacific objects to Britain, now spread across many museums.",
"voyaging;collecting by exchange and seizure",
"cloak;headdress;adze",
"rule and display",
"voyage journals; museums",
"the Pacific makers and Tupaia; the objects taken by force or in unequal exchange",
"Indigenous-community",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: NET045",
"canon_people.csv"
],
[
"PER347",
"Liliʻuokalani",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1838",
"1917",
"",
"The last queen of the Hawaiian Kingdom made a signed crazy quilt with her companions while imprisoned in ʻIolani Palace after the 1895 uprising.",
"quilting;embroidery",
"quilt",
"clothing and adornment;rule and display",
"herself; ʻIolani Palace",
"the women who stitched with her",
"Indigenous-community",
"community-published site (link-out);Wikimedia Commons",
"R3",
"F1.18;F1.19a",
"high",
"links: POL083; DYN095",
"canon_people.csv"
],
[
"PER348",
"Sālote Tupou III",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1900",
"1965",
"",
"The Queen of Tonga supported women's production of barkcloth (ngatu) and fine mats and founded the Langafonua women's association (1953).",
"barkcloth;mat weaving",
"ngatu;fine mat",
"clothing and adornment;exchange and value",
"Tongan state",
"the women's kautaha groups who made the cloth",
"none",
"community-published site (link-out)",
"R3",
"F1.18;F1.17",
"high",
"links: POL085; MKR088",
"canon_people.csv"
],
[
"PER349",
"Āpirana Ngata",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1874",
"1950",
"",
"The Māori politician set up the School of Māori Arts and Crafts at Rotorua (1926) to train carvers and build meeting houses.",
"whakairo;meeting house building",
"meeting house;carving",
"rule and display;ritual and belief",
"himself; New Zealand government",
"the tohunga whakairo who taught; iwi styles narrowed by one school's teaching",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.17;F1.29",
"high",
"links: INS085",
"canon_people.csv"
],
[
"PER350",
"Te Puea Hērangi",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1883",
"1952",
"",
"The Waikato leader built Tūrangawaewae marae at Ngāruawāhia and brought carvers to decorate its buildings.",
"patronage;marae building",
"meeting house;canoe",
"rule and display;ritual and belief",
"Waikato-Tainui",
"the carvers and the community labour that built the marae",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.17;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER351",
"Tene Waitere",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1853",
"1931",
"born c. 1853–54",
"The Ngāti Tarawhai carver made meeting-house carvings and pieces for tourists and collectors, including for Hinemihi, now at Clandon Park in England.",
"whakairo",
"meeting house carving;panel",
"rule and display;ritual and belief",
"himself; museums",
"the carving school he trained in",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.26;F1.21",
"high",
"links: SCH044",
"canon_people.csv"
],
[
"PER352",
"Pine Taiapa",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1901",
"1972",
"",
"The Ngāti Porou carver trained at the Rotorua school and carved many meeting houses across New Zealand.",
"whakairo",
"meeting house",
"ritual and belief",
"himself",
"the carvers who worked under him",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.29",
"high",
"links: INS085",
"canon_people.csv"
],
[
"PER353",
"Rangimārie Hetet",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1892",
"1995",
"",
"The Ngāti Maniapoto weaver kept kākahu (cloak) weaving alive and taught her daughter Diggeress Te Kanawa.",
"harakeke fibre;finger weaving",
"cloak",
"clothing and adornment;rule and display",
"herself",
"the women weavers who taught her",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER354",
"Diggeress Te Kanawa",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1920",
"2009",
"",
"The Ngāti Maniapoto weaver taught cloak-weaving widely and wrote a book on Māori fibre weaving (1992).",
"harakeke fibre;finger weaving",
"cloak;kete",
"clothing and adornment",
"herself",
"the weavers of her family lineage",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER355",
"Emily Schuster",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1927",
"1997",
"",
"The Te Arawa weaver headed weaving at the New Zealand Māori Arts and Crafts Institute in Rotorua.",
"harakeke fibre;weaving",
"cloak;kete;tukutuku panel",
"clothing and adornment",
"herself",
"the weavers who trained there",
"Indigenous-community",
"Te Papa Collections Online (CC BY items, taonga Maori images for research and education only)",
"R3",
"F1.18",
"high",
"links: INS085",
"canon_people.csv"
],
[
"PER356",
"Gordon Walters",
"",
"person",
"People",
"F1.12",
"OC-POL",
"1919",
"1995",
"",
"The Pākehā painter used the Māori koru form in hard-edge paintings from the 1950s, later criticised as appropriation.",
"painting",
"painting",
"rule and display",
"himself; critics",
"the Māori carvers and kowhaiwhai painters whose form he took",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.2",
"high",
"",
"canon_people.csv"
],
[
"PER357",
"Linda Tuhiwai Smith",
"",
"person",
"People",
"THEME;F1.12",
"OC-POL",
"1950",
"",
"born 1950; living",
"The Māori scholar's Decolonizing Methodologies (1999) set out how research on Indigenous peoples can be done with and for them.",
"research methodology",
"book",
"record and writing",
"herself",
"earlier Indigenous thinkers she builds on",
"Indigenous-community;living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER358",
"Te Rangi Hīroa",
"Peter Buck",
"person",
"People",
"F1.12;THEME",
"OC-POL",
"1877",
"1951",
"born c. 1877",
"The Māori doctor and anthropologist studied Pacific material culture and directed the Bishop Museum in Honolulu, writing on Pacific voyaging and crafts.",
"ethnography;museum direction",
"book",
"record and writing",
"himself",
"the makers and communities he studied",
"Indigenous-community",
"Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER359",
"Albert Namatjira",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1902",
"1959",
"",
"The Western Arrernte painter from Hermannsburg made watercolour landscapes of Country and lost control of his copyright after his death until it was returned to his family in 2017.",
"watercolour",
"painting",
"rule and display",
"himself; Rex Battarbee who taught him",
"the Hermannsburg family painters; his family, long denied copyright",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.14",
"high",
"Some communities avoid naming or showing images of the deceased; check family wishes. links: SCH042",
"canon_people.csv"
],
[
"PER360",
"Emily Kame Kngwarreye",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1910",
"1996",
"born c. 1910",
"The Anmatyerre artist from Utopia moved from batik to painting in 1988 and made thousands of paintings rooted in body designs and Country.",
"batik;acrylic painting",
"painting;batik",
"ritual and belief",
"herself; Utopia community; dealers",
"the Utopia women whose batik group she came from",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"Some communities avoid naming the deceased; check protocol. links: MKR085",
"canon_people.csv"
],
[
"PER361",
"Clifford Possum Tjapaltjarri",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1932",
"2002",
"born c. 1932",
"The Anmatyerre artist was a founding painter of Papunya Tula, making large map-like paintings of Country; forgeries of his work led to court cases.",
"acrylic dot painting",
"painting",
"ritual and belief",
"himself; Papunya Tula Artists",
"the Papunya men and women painters; the family members who helped paint",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.14;F1.26",
"high",
"Some communities avoid naming the deceased; check protocol. links: MKR080; MOV100",
"canon_people.csv"
],
[
"PER362",
"Geoffrey Bardon",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1940",
"2003",
"",
"The art teacher at Papunya in 1971 encouraged men to paint a school mural and then boards, the start of the Papunya Tula movement.",
"art teaching",
"mural;painting",
"rule and display",
"himself",
"the Papunya men who painted, who led the movement",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.26",
"high",
"links: MKR080; MOV100",
"canon_people.csv"
],
[
"PER363",
"Rover Thomas",
"Joolama",
"person",
"People",
"F1.12",
"OC-AUS",
"1926",
"1998",
"born c. 1926",
"The Kukatja-Wangkajunga artist began painting in the East Kimberley after a 1970s dream, founding the Krill Krill ceremony and painting its boards in ochre.",
"natural ochre;painting",
"painting;ceremonial board",
"ritual and belief",
"himself; Warmun community",
"Paddy Jaminji, who first painted the boards",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.16;F1.20",
"high",
"Some communities avoid naming the deceased. links: STY157; MKR086",
"canon_people.csv"
],
[
"PER364",
"Yirawala",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1897",
"1976",
"born c. 1897",
"The Kuninjku bark painter from western Arnhem Land painted spirit beings and ancestral stories.",
"bark painting;ochre",
"bark painting",
"ritual and belief",
"himself; collector Sandra Holmes",
"his family painters",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.16",
"high",
"Some communities avoid naming the deceased. links: STY155",
"canon_people.csv"
],
[
"PER365",
"Wandjuk Marika",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1927",
"1987",
"",
"The Yolŋu artist campaigned for artists' copyright after finding his clan design reproduced on tea towels without consent.",
"bark painting;advocacy",
"bark painting",
"ritual and belief",
"himself; Aboriginal Arts Board",
"his clan, the owners of the designs",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.14;F1.24",
"high",
"Some communities avoid naming the deceased. links: MKR084",
"canon_people.csv"
],
[
"PER366",
"Narritjin Maymuru",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1916",
"1981",
"born c. 1916",
"The Yolŋu painter from Yirrkala made bark paintings for sale and helped paint the Yirrkala Church Panels (1962–63).",
"bark painting;ochre",
"bark painting;panel",
"ritual and belief",
"himself",
"the clan leaders who painted the panels together",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.16;F1.29",
"high",
"Some communities avoid naming the deceased. links: STY156",
"canon_people.csv"
],
[
"PER367",
"Gulumbu Yunupingu",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1943",
"2012",
"born c. 1943",
"The Yolŋu artist painted star-filled barks and larrakitj poles and won the Telstra award in 2004.",
"bark painting;ochre",
"bark painting;larrakitj",
"ritual and belief",
"herself; Buku-Larrnggay Mulka",
"the Yolŋu women painters of Yirrkala",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18",
"high",
"Some communities avoid naming the deceased. links: MKR084",
"canon_people.csv"
],
[
"PER368",
"Yvonne Koolmatrie",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1944",
"",
"born 1944; living",
"The Ngarrindjeri weaver revived coiled sedge basketry and eel traps learned from elder Dorothy Kartinyeri.",
"coiled sedge weaving",
"basket;eel trap",
"food and storage",
"herself",
"the Ngarrindjeri elders who taught her",
"Indigenous-community;living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER369",
"Ken Thaiday Sr",
"",
"person",
"People",
"F1.12",
"OC-MEL;OC-AUS",
"1950",
"",
"born 1950; living",
"The Torres Strait Islander artist makes kinetic dance headdresses (dhari) and hammerhead shark sculptures from mixed materials.",
"wood;plywood;feathers;moving parts",
"headdress;dance machine",
"ritual and belief;play and music",
"himself",
"the dancers who wear the headdresses",
"Indigenous-community;living-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.4;F1.16",
"high",
"",
"canon_people.csv"
],
[
"PER370",
"Margaret Preston",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1875",
"1963",
"",
"The Australian modernist urged the use of Aboriginal designs in national design from 1925 and used them in prints and textiles.",
"woodcut;stencil;painting",
"print;textile",
"rule and display",
"herself",
"the Aboriginal artists whose designs she used without consent",
"Indigenous-community",
"collection search link-out only (works in copyright)",
"R3",
"F1.2;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER371",
"Baldwin Spencer",
"",
"person",
"People",
"F1.12",
"OC-AUS",
"1860",
"1929",
"",
"The biologist-anthropologist collected sacred and everyday objects in central and northern Australia for the Melbourne museum and published with Francis Gillen.",
"collecting;ethnography",
"tjurunga;bark painting",
"ritual and belief",
"himself",
"Francis Gillen and the Arrernte men whose objects and ceremonies he recorded",
"Indigenous-community;sacred",
"collection search link-out only (works in copyright)",
"R3",
"F1.24",
"high",
"Sacred objects must not be displayed.",
"canon_people.csv"
],
[
"PER372",
"Jean-Marie Tjibaou",
"",
"person",
"People",
"F1.12",
"OC-MEL",
"1936",
"1989",
"",
"The Kanak leader organised the Mélanésia 2000 festival (1975); the Tjibaou Cultural Centre in Nouméa (1998) is named after him.",
"festival organising",
"festival;cultural centre",
"rule and display",
"himself",
"the Kanak makers whose work the festival showed",
"Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.24;F1.15",
"high",
"",
"canon_people.csv"
],
[
"PER373",
"Emmanuel Kasarhérou",
"",
"person",
"People",
"F1.12;F1.11",
"OC-MEL;EU-WCE",
"1960",
"",
"born 1960; living",
"The Kanak curator directed the Tjibaou Cultural Centre and became president of the Musée du quai Branly in 2020.",
"curating;provenance research",
"exhibition",
"rule and display",
"himself",
"the Kanak communities whose objects are in Paris",
"Indigenous-community;living-community",
"Musee du quai Branly (link out)",
"R3",
"F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER374",
"Exekias",
"",
"person",
"People",
"F1.11",
"EU-GRR",
"-550",
"-525",
"fl.; approximate",
"The Athenian potter and painter signed black-figure vases as both maker and painter, including the Dionysos cup and the amphora of Achilles and Ajax playing a board game.",
"black-figure painting;incision;wheel throwing",
"amphora;kylix",
"food and storage;ritual and belief",
"signatures on vases; art historians",
"the workshop hands and the enslaved or foreign workers common in Athenian potteries",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.26;F1.28",
"high",
"Athenian workshops used enslaved labour; content note. links: STY003; POL117",
"canon_people.csv"
],
[
"PER375",
"Euphronios",
"",
"person",
"People",
"F1.11",
"EU-GRR",
"-520",
"-470",
"fl.; approximate",
"The Athenian red-figure painter, later a potter, signed vases including a calyx krater that the Metropolitan Museum returned to Italy in 2008 after evidence it had been looted from an Etruscan tomb.",
"red-figure painting;relief line",
"calyx krater;kylix",
"food and storage;ritual and belief",
"signatures; art historians",
"the potters whose shapes he painted; the Etruscan buyers and tomb context destroyed by looters",
"conflict-looting;funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.24;F1.26",
"high",
"Looted from Cerveteri in 1971; returned 2008. links: STY003",
"canon_people.csv"
],
[
"PER376",
"John Beazley",
"Sir John Davidson Beazley",
"person",
"People",
"THEME;F1.11",
"EU-BLC;EU-GRR",
"1885",
"1970",
"",
"The Oxford scholar attributed tens of thousands of Athenian vases to named and nicknamed painters (such as the Berlin Painter) by drawing style, a method that also shaped the antiquities market.",
"stylistic attribution",
"vase",
"record and writing",
"himself; the Beazley Archive",
"the workshop members and potters whom individual-painter attribution hides",
"none",
"community-published site (link-out)",
"R3",
"F1.26;F1.3",
"high",
"The Beazley Archive database is free to search.",
"canon_people.csv"
],
[
"PER377",
"Pheidias",
"Phidias",
"person",
"People",
"F1.11",
"EU-GRR",
"-480",
"-430",
"approximate",
"The Athenian sculptor oversaw the Parthenon sculptures and made the gold and ivory statues of Athena Parthenos and Zeus at Olympia, whose workshop has been excavated.",
"chryselephantine;marble carving;bronze",
"cult statue;frieze",
"ritual and belief;rule and display",
"ancient writers (Plutarch, Pausanias); archaeologists",
"the many carvers who worked the Parthenon marbles under him",
"none",
"Wikimedia Commons",
"R3",
"F1.26;F1.17",
"high",
"A cup inscribed 'I belong to Pheidias' was found in the Olympia workshop. links: POL117",
"canon_people.csv"
],
[
"PER378",
"Vitruvius",
"Marcus Vitruvius Pollio",
"person",
"People",
"F1.11;THEME",
"EU-GRR",
"-80",
"-15",
"born c. 80–70 BCE; died after c. 15 BCE",
"The Roman architect-engineer wrote De architectura, the only architectural treatise surviving from antiquity, on building, materials and machines.",
"technical writing;architecture;engineering",
"treatise",
"shelter;record and writing",
"himself; Renaissance readers",
"the builders and slaves whose practice he wrote about",
"none",
"LacusCurtius (public-domain translations);Internet Archive (public-domain scans)",
"R3",
"F1.28;F1.3",
"high",
"links: POL120",
"canon_people.csv"
],
[
"PER379",
"Pliny the Elder",
"Gaius Plinius Secundus",
"person",
"People",
"F1.11;THEME",
"EU-GRR",
"23",
"79",
"",
"The Roman writer's Natural History (77 CE) records materials and crafts from dyes and glass to bronze and pigments, and includes stories of named Greek artists.",
"encyclopedic writing",
"text",
"record and writing",
"himself",
"the craftspeople whose techniques he reported second-hand",
"none",
"LacusCurtius (public-domain translations);Internet Archive (public-domain scans)",
"R3",
"F1.28;F1.3",
"high",
"links: POL120",
"canon_people.csv"
],
[
"PER380",
"Marcus Perennius",
"Perennius",
"person",
"People",
"F1.11",
"EU-GRR",
"-30",
"10",
"fl.; approximate",
"The Arretine pottery's stamps show the workshop passing to men who had worked in it: first Perennius's freedman Marcus Perennius Tigranus, then Marcus Perennius Bargathes.",
"mould-made red gloss ware;stamps",
"bowl;cup",
"food and storage",
"stamps on the ware; archaeologists",
"the enslaved workers whose names appear only in stamps",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.23;F1.26",
"medium",
"Round 2: Tigranus is described as a freedman of M. Perennius; Bargathes followed him as owner (Phase 3, c. 25–30 CE per Porten Palange). Earlier enslaved status is likely but not explicitly sourced here. links: POL120",
"canon_people.csv"
],
[
"PER381",
"Eurysaces",
"Marcus Vergilius Eurysaces",
"person",
"People",
"F1.11",
"EU-GRR",
"-50",
"-20",
"fl.; approximate",
"The freedman baker built a tomb at Rome's Porta Maggiore with a frieze showing the stages of bread making in his bakery.",
"travertine;relief carving",
"tomb;relief",
"food and storage;ritual and belief",
"his tomb inscription",
"the enslaved workers shown in the frieze",
"human-flow;funerary",
"Wikimedia Commons",
"R3",
"F1.23;F1.19",
"high",
"links: POL120",
"canon_people.csv"
],
[
"PER382",
"Theodora",
"Empress Theodora",
"person",
"People",
"F1.11",
"EU-BYZ",
"500",
"548",
"born c. 500",
"The Byzantine empress, co-ruler with Justinian, is shown with her court in the mosaic at San Vitale, Ravenna, during a reign that rebuilt Hagia Sophia.",
"mosaic;silk",
"mosaic;church",
"rule and display",
"Procopius; mosaics",
"the mosaicists; the architects Anthemius and Isidore of Hagia Sophia",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: POL121",
"canon_people.csv"
],
[
"PER383",
"Ende",
"",
"person",
"People",
"F1.11",
"EU-IBE",
"975",
"975",
"fl.; 975",
"The painter is named in the colophon of the Girona Beatus (975) as 'painter and servant of God', one of the earliest named women illuminators in Europe.",
"manuscript illumination",
"manuscript",
"ritual and belief",
"the colophon",
"the scribe Senior and the monastery workshop",
"sacred",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER384",
"Theophilus Presbyter",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1100",
"1120",
"fl.; approximate",
"The author of De diversis artibus described pigments, glassmaking, stained glass, metalworking and organ building in detail.",
"technical writing;glass;metalwork",
"treatise",
"record and writing;ritual and belief",
"the text; historians who suggest he was Roger of Helmarshausen",
"the workshop makers whose methods he wrote down",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.28",
"high",
"Identity uncertain.",
"canon_people.csv"
],
[
"PER385",
"Suger",
"Abbot Suger",
"person",
"People",
"F1.11",
"EU-WCE",
"1081",
"1151",
"",
"The abbot of Saint-Denis rebuilt its church with a new choir of stained glass and wrote an account defending the costly materials.",
"stained glass;goldsmith work;architecture",
"church;liturgical vessel",
"ritual and belief;rule and display",
"his own writings",
"the masons, glaziers and goldsmiths he names only in part",
"sacred",
"National Gallery of Art Washington Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.28",
"high",
"The eagle vase he adapted is in the Louvre. links: STY013",
"canon_people.csv"
],
[
"PER386",
"Christine de Pizan",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1364",
"1430",
"died c. 1430",
"The Venetian-born writer in Paris oversaw the production of her own illustrated manuscripts and praised the illuminator Anastaise.",
"manuscript supervision;writing",
"manuscript",
"record and writing",
"herself",
"Anastaise and the scribes and painters she worked with",
"none",
"British Library digitised manuscripts (public-domain items);Gallica BnF (public-domain items, link out for reuse)",
"R3",
"F1.18;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER387",
"Anastaise",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1400",
"1405",
"fl.; approximate",
"Christine de Pizan names her as the most skilled painter of borders and backgrounds in Paris, but no work can now be securely attributed to her.",
"manuscript illumination",
"manuscript border",
"record and writing",
"Christine de Pizan's City of Ladies (1405)",
"herself, whose work is unattributed",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"medium",
"Known only from one text.",
"canon_people.csv"
],
[
"PER388",
"Cennino Cennini",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1360",
"1427",
"born c. 1360; died before 1427",
"The Florentine painter's Il libro dell'arte describes workshop methods from grinding pigments to gilding panels.",
"technical writing;tempera;gilding",
"treatise",
"record and writing",
"himself",
"the apprentices and grinders of pigments in the workshop",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER389",
"Lorenzo de' Medici",
"Lorenzo il Magnifico",
"person",
"People",
"F1.11",
"EU-WCE",
"1449",
"1492",
"",
"The Florentine banker-ruler collected antique gems and vases, which he had engraved with his name, and supported artists' training.",
"collecting;patronage",
"vase;gem",
"rule and display",
"Medici inventories; Vasari",
"the workshop artists and the gem cutters",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.24",
"high",
"links: DYN088",
"canon_people.csv"
],
[
"PER390",
"Isabella d'Este",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1474",
"1539",
"",
"The Marchioness of Mantua commissioned paintings to detailed written programmes and collected antiquities for her studiolo.",
"patronage;collecting",
"painting;antiquity",
"rule and display",
"her letters",
"the painters she instructed and the agents who bought for her",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: DYN089",
"canon_people.csv"
],
[
"PER391",
"Johannes Gutenberg",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1400",
"1468",
"born c. 1400",
"The Mainz goldsmith developed a type-casting mould, oil-based ink and press used to print the Bible around 1455.",
"type casting;press printing",
"printed book",
"record and writing",
"court records; historians",
"his partners Johann Fust and Peter Schöffer; the earlier East Asian movable type",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.19",
"high",
"",
"canon_people.csv"
],
[
"PER392",
"Albrecht Dürer",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1471",
"1528",
"",
"The Nuremberg artist sold woodcuts and engravings across Europe and complained to Venice about copies of his prints by Marcantonio Raimondi.",
"woodcut;engraving",
"print",
"record and writing",
"himself",
"the block cutters who cut his woodcuts; his wife Agnes, who sold the prints",
"none",
"National Gallery of Art Washington Open Access (CC0);Met Open Access (CC0)",
"R2",
"F1.14;F1.21",
"high",
"links: MKR066",
"canon_people.csv"
],
[
"PER393",
"Marcantonio Raimondi",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1480",
"1534",
"approximate",
"The Bolognese engraver copied Dürer's prints with his monogram and later spread Raphael's designs across Europe through reproductive engravings.",
"engraving",
"print",
"record and writing",
"Vasari",
"the workshop engravers who continued his work",
"none",
"Met Open Access (CC0);National Gallery of Art Washington Open Access (CC0)",
"R3",
"F1.14",
"high",
"Vasari's story of a Venetian lawsuit is not confirmed by records.",
"canon_people.csv"
],
[
"PER394",
"Properzia de' Rossi",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1490",
"1530",
"approximate",
"The Bolognese sculptor carved tiny figures on fruit stones and marble reliefs for San Petronio, one of few women sculptors Vasari wrote about.",
"micro-carving;marble relief",
"relief;carved stone",
"rule and display",
"Vasari",
"the other women who carved at small scale",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER395",
"Giorgio Vasari",
"",
"person",
"People",
"F1.11;THEME",
"EU-WCE",
"1511",
"1574",
"",
"The painter's Lives of the Artists (1550, 1568) built a story of Italian art as progress by named individuals, set against craft and 'lesser' arts.",
"biography;history writing",
"book",
"record and writing",
"himself",
"anonymous workshops, women and makers outside Italy",
"none",
"Internet Archive (public-domain scans);Project Gutenberg",
"R3",
"F1.3;F1.26",
"high",
"links: INS049",
"canon_people.csv"
],
[
"PER396",
"Bernard Palissy",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1510",
"1590",
"born c. 1510; died c. 1590",
"The French potter made lead-glazed dishes with life-cast snakes and fish and wrote about his long search for enamel glazes.",
"life casting;lead glaze",
"rustic dish;grotto",
"food and storage;rule and display",
"himself",
"his helpers and the later imitators whose work is sold as his",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER397",
"Wenzel Jamnitzer",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1508",
"1585",
"",
"The Nuremberg goldsmith used life casting of plants and animals in silver and made precious display objects for Habsburg patrons.",
"life casting;silver;gilding",
"table centrepiece;ewer",
"rule and display",
"art historians",
"his family workshop and assistants",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0)",
"R3",
"F1.26;F1.17",
"high",
"links: MKR066",
"canon_people.csv"
],
[
"PER398",
"Georgius Agricola",
"Georg Bauer",
"person",
"People",
"F1.11",
"EU-WCE",
"1494",
"1555",
"",
"The German physician's De re metallica (1556) described mining and smelting with detailed woodcuts.",
"technical writing;mining;smelting",
"treatise",
"tools;record and writing",
"himself",
"the miners, including children, whose work the woodcuts show",
"none",
"Internet Archive (public-domain scans);Project Gutenberg",
"R3",
"F1.28;F1.22",
"high",
"",
"canon_people.csv"
],
[
"PER399",
"Maria Sibylla Merian",
"",
"person",
"People",
"F1.11;F1.7",
"EU-WCE;AM-CAR",
"1647",
"1717",
"",
"The German naturalist and engraver studied insects in Suriname (1699–1701) and published Metamorphosis insectorum Surinamensium (1705), crediting knowledge from enslaved African and Indigenous people.",
"engraving;watercolour;natural history",
"book;watercolour",
"record and writing",
"herself",
"the enslaved and Indigenous people who collected specimens and shared plant knowledge; her daughters",
"human-flow",
"Wikimedia Commons;Rijksmuseum (CC0)",
"R3",
"F1.18;F1.28",
"high",
"",
"canon_people.csv"
],
[
"PER400",
"Louis XIV",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1638",
"1715",
"",
"The French king made royal manufactures such as the Gobelins supply Versailles, using luxury production as state policy.",
"state manufactures;tapestry;furniture",
"palace;tapestry",
"rule and display",
"French royal records",
"the weavers, cabinetmakers and foreign craftsmen recruited to France",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.19",
"high",
"links: MKR068; DYN085",
"canon_people.csv"
],
[
"PER401",
"Jean-Baptiste Colbert",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1619",
"1683",
"",
"The French minister set rules for manufactures, brought in foreign workers such as Venetian glassmakers and founded the Gobelins as a royal works.",
"industrial policy;regulation",
"tapestry;mirror",
"rule and display;exchange and value",
"French royal records",
"the craftsmen lured from Venice and Flanders; the colonial trade he promoted, including the Code Noir drafted under him",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.14",
"high",
"The Code Noir (1685) regulated slavery in French colonies. links: MKR068",
"canon_people.csv"
],
[
"PER402",
"Johann Friedrich Böttger",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1682",
"1719",
"",
"The alchemist, held under guard by Augustus the Strong, worked with Tschirnhaus to make the first European hard-paste porcelain (1708–09), leading to the Meissen factory.",
"hard-paste porcelain;kaolin",
"porcelain",
"food and storage;rule and display",
"Meissen records",
"Ehrenfried Walther von Tschirnhaus and the miners and workers who ran the experiments",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14;F1.19",
"high",
"He was kept prisoner to guard the secret. links: MKR069",
"canon_people.csv"
],
[
"PER403",
"Madame de Pompadour",
"Jeanne-Antoinette Poisson",
"person",
"People",
"F1.11",
"EU-WCE",
"1721",
"1764",
"",
"The mistress of Louis XV supported the Vincennes-Sèvres porcelain works and bought and promoted its wares.",
"patronage;porcelain",
"porcelain;furniture",
"rule and display",
"court records",
"the painters and gilders of Sèvres, many of them women",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17;F1.18",
"high",
"links: MKR070",
"canon_people.csv"
],
[
"PER404",
"Catherine II",
"Catherine the Great",
"person",
"People",
"F1.11",
"EU-EER",
"1729",
"1796",
"",
"The Russian empress ordered the Frog Service from Wedgwood and bought whole European art collections, forming the Hermitage.",
"patronage;collecting",
"tableware;painting",
"rule and display",
"Russian court records",
"the Wedgwood painters of the Frog Service; the serfs whose labour funded the court",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.17;F1.24",
"high",
"links: POL144",
"canon_people.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
