insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PER405",
"Hans Sloane",
"",
"person",
"People",
"F1.11;F1.7",
"EU-BLC;AM-CAR",
"1660",
"1753",
"",
"The physician's collection, built partly with wealth from Jamaican slave plantations, became the founding collection of the British Museum (1753).",
"collecting",
"specimen;object;book",
"rule and display",
"his will; British Museum",
"the enslaved people whose labour funded him and whose objects he collected",
"human-flow",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: INS051",
"canon_people.csv"
],
[
"PER406",
"Thomas Chippendale",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1718",
"1779",
"",
"The London cabinetmaker published The Gentleman and Cabinet-Maker's Director (1754), a pattern book that spread his designs, often in mahogany cut by enslaved workers.",
"mahogany cabinetmaking;pattern book",
"chair;cabinet",
"shelter",
"himself",
"the workshop joiners and carvers; enslaved woodcutters in the Caribbean and Central America",
"human-flow",
"Met Open Access (CC0);Internet Archive (public-domain scans)",
"R2",
"F1.21;F1.23",
"high",
"",
"canon_people.csv"
],
[
"PER407",
"Anna Maria Garthwaite",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1690",
"1763",
"",
"The English designer drew hundreds of floral patterns for Spitalfields silk weavers; many survive in the V&A.",
"silk design;drawing",
"silk design",
"clothing and adornment",
"herself; her dated drawings",
"the weavers, many of them Huguenot, who wove her designs",
"none",
"V&A collections (link out);Met Open Access (CC0)",
"R3",
"F1.18;F1.26",
"high",
"links: DIA010",
"canon_people.csv"
],
[
"PER408",
"Hester Bateman",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1708",
"1794",
"",
"The London silversmith ran her late husband's workshop and registered her own mark, producing domestic silver in large quantity.",
"silversmithing;sheet silver",
"teapot;spoon",
"food and storage",
"her hallmarks",
"her sons and workers",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER409",
"Eleanor Coade",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1733",
"1821",
"",
"The businesswoman ran a London factory making Coade stone, a durable fired ceramic used for statues and architectural ornament.",
"fired ceramic stone;moulding",
"statue;ornament",
"shelter;rule and display",
"her catalogues",
"the modellers and workers of her factory",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.19",
"high",
"",
"canon_people.csv"
],
[
"PER410",
"Josiah Wedgwood",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1730",
"1795",
"",
"The Staffordshire potter divided factory work into specialisms, used showrooms and catalogues, and made the anti-slavery medallion (1787) with its kneeling enslaved man.",
"jasperware;creamware;factory division of labour",
"tableware;medallion",
"food and storage;exchange and value",
"himself; his firm",
"the workers, including children; the enslaved people depicted as supplicants rather than agents",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.19;F1.21",
"high",
"links: MKR072",
"canon_people.csv"
],
[
"PER411",
"Matthew Boulton",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1728",
"1809",
"",
"The Birmingham manufacturer ran the Soho Manufactory, made buttons, ormolu and steam engines with James Watt, and minted coins by steam.",
"metal stamping;ormolu;steam power",
"button;steam engine;coin",
"exchange and value;tools",
"himself",
"the Soho workers; James Watt and William Murdoch",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_people.csv"
],
[
"PER412",
"Ada Lovelace",
"Augusta Ada King",
"person",
"People",
"F1.11;THEME",
"EU-BLC",
"1815",
"1852",
"",
"The English mathematician's notes on Babbage's Analytical Engine (1843) compared it to the Jacquard loom weaving patterns and set out a program for it.",
"mathematics;algorithm",
"notes",
"record and writing",
"herself",
"the weavers whose punched-card looms inspired the analogy",
"none",
"Wikimedia Commons",
"R3",
"F1.21;F1.18",
"high",
"",
"canon_people.csv"
],
[
"PER413",
"Henry Cole",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1808",
"1882",
"",
"The British civil servant organised the Great Exhibition of 1851 and became the first director of the South Kensington Museum.",
"exhibition;museum founding;design reform",
"exhibition;museum",
"rule and display",
"himself",
"the craftspeople of India and elsewhere whose goods were shown as examples",
"none",
"V&A collections (link out);Wikimedia Commons",
"R3",
"F1.19;F1.15",
"high",
"links: EVT001; INS052",
"canon_people.csv"
],
[
"PER414",
"Prince Albert",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1819",
"1861",
"",
"The consort of Queen Victoria led the Royal Commission for the 1851 Great Exhibition, whose profits bought the South Kensington land.",
"patronage;exhibition",
"exhibition;museum",
"rule and display",
"Royal Commission records",
"the workers who built the Crystal Palace",
"none",
"Wikimedia Commons",
"R3",
"F1.17;F1.19",
"high",
"links: EVT001",
"canon_people.csv"
],
[
"PER415",
"Owen Jones",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1809",
"1874",
"",
"The architect's Grammar of Ornament (1856) set patterns from Egypt, the Islamic world, India, China and Oceania side by side as models for design.",
"chromolithography;ornament theory",
"book",
"record and writing",
"himself",
"the makers of the ornament, reduced to 'styles'",
"none",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R2",
"F1.15;F1.2",
"high",
"links: STY032",
"canon_people.csv"
],
[
"PER416",
"Gottfried Semper",
"",
"person",
"People",
"F1.11;THEME",
"EU-WCE",
"1803",
"1879",
"",
"The German architect argued in Style (1860–63) that architecture grew from crafts such as weaving, pottery, carpentry and masonry, using a Caribbean hut shown in 1851.",
"theory;architecture",
"book;building",
"record and writing;shelter",
"himself",
"the Trinidad builders of the hut he saw at the Great Exhibition",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.15",
"high",
"links: EVT001",
"canon_people.csv"
],
[
"PER417",
"John Ruskin",
"",
"person",
"People",
"F1.11;THEME",
"EU-BLC",
"1819",
"1900",
"",
"The critic's 'The Nature of Gothic' (1853) argued that the freedom of medieval carvers was visible in their work and condemned the division of labour.",
"criticism",
"book",
"record and writing",
"himself",
"the women and colonial makers his medieval ideal overlooked",
"none",
"Project Gutenberg;Internet Archive (public-domain scans)",
"R3",
"F1.3;F1.19",
"high",
"links: STY027; MOV005",
"canon_people.csv"
],
[
"PER418",
"William Morris",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1834",
"1896",
"",
"The designer ran Morris & Co., reviving hand block printing, natural dyeing and tapestry weaving, and argued for socialism and useful work.",
"block printing;natural dye;tapestry",
"wallpaper;textile;book",
"shelter;clothing and adornment",
"himself",
"Jane and May Morris, Kate Faulkner and the dyers and weavers at Merton Abbey",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD);Internet Archive (public-domain scans)",
"R2",
"F1.18;F1.19;F1.29",
"high",
"links: MKR076; MOV005",
"canon_people.csv"
],
[
"PER419",
"Jane Morris",
"Jane Burden",
"person",
"People",
"F1.11",
"EU-BLC",
"1839",
"1914",
"",
"The embroiderer worked out techniques for early Morris embroideries and is better known as a model for Pre-Raphaelite painters.",
"embroidery",
"hanging;cover",
"clothing and adornment",
"herself; family records",
"herself, when embroidery is credited to William Morris",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"links: MKR076",
"canon_people.csv"
],
[
"PER420",
"May Morris",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1862",
"1938",
"",
"The designer ran Morris & Co.'s embroidery department from 1885, designed wallpapers and co-founded the Women's Guild of Arts (1907).",
"embroidery;wallpaper design",
"embroidery;wallpaper",
"clothing and adornment;shelter",
"herself",
"herself, when designs are credited to her father",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"links: MKR076; MOV005",
"canon_people.csv"
],
[
"PER421",
"Christopher Dresser",
"",
"person",
"People",
"F1.11;F1.8",
"EU-BLC;AS-JPN",
"1834",
"1904",
"",
"The designer visited Japan in 1876–77, wrote on Japanese craft and designed metalwork and glass for factory production.",
"electroplated metal;design for industry",
"teapot;toast rack",
"food and storage",
"himself",
"the factory workers and Japanese makers he learned from",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.19;F1.14",
"high",
"links: STY030",
"canon_people.csv"
],
[
"PER422",
"Charles Rennie Mackintosh",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1868",
"1928",
"",
"The Glasgow architect designed the Glasgow School of Art and complete interiors, working closely with Margaret Macdonald.",
"architecture;furniture;stencil",
"chair;building",
"shelter",
"himself",
"Margaret Macdonald, whose share of their interiors was long underplayed",
"none",
"Wikimedia Commons;collection search link-out only (works in copyright)",
"R3",
"F1.26;F1.20",
"high",
"links: STY038",
"canon_people.csv"
],
[
"PER423",
"Margaret Macdonald",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1864",
"1933",
"",
"The Glasgow artist made gesso panels, metalwork and embroidery for interiors she designed with Charles Rennie Mackintosh.",
"gesso;metal repoussé;embroidery",
"panel;textile",
"rule and display;shelter",
"herself",
"herself, when joint work is credited to her husband",
"none",
"Wikimedia Commons",
"R3",
"F1.18;F1.26",
"high",
"links: STY038",
"canon_people.csv"
],
[
"PER424",
"Josef Hoffmann",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1870",
"1956",
"",
"The Viennese architect co-founded the Wiener Werkstätte (1903), whose workshops made silver, furniture and textiles to his and others' designs.",
"silver;furniture;design",
"cutlery;chair;building",
"shelter;food and storage",
"himself",
"the Werkstätte craftsmen and the women designers of its later years",
"none",
"Met Open Access (CC0);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.18;F1.20",
"high",
"links: MKR077",
"canon_people.csv"
],
[
"PER425",
"Adolf Loos",
"",
"person",
"People",
"F1.11;THEME",
"EU-WCE",
"1870",
"1933",
"",
"The Viennese architect's essay 'Ornament and Crime' argued that ornament was wasted labour, citing tattooed Papuans and 'criminals' as examples.",
"criticism;architecture",
"essay;building",
"record and writing",
"himself",
"the Pacific peoples and craftspeople his argument cast as primitive",
"none",
"Wikimedia Commons",
"R3",
"F1.15;F1.3",
"high",
"The essay's date (1908 or 1910) is debated.",
"canon_people.csv"
],
[
"PER426",
"Alois Riegl",
"",
"person",
"People",
"F1.11;THEME",
"EU-WCE",
"1858",
"1905",
"",
"The Austrian art historian, a textile curator in Vienna, argued in Stilfragen (1893) that ornament developed through artistic will rather than technique or material alone.",
"art history;ornament study",
"book",
"record and writing",
"himself",
"the carpet weavers whose work he studied",
"none",
"Internet Archive (public-domain scans)",
"R3",
"F1.15;F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER427",
"Frida Hansen",
"",
"person",
"People",
"F1.11",
"EU-SCA",
"1855",
"1931",
"",
"The Norwegian weaver developed a transparent weaving technique and made large tapestries in the Art Nouveau style.",
"tapestry;transparent weave",
"tapestry",
"shelter",
"herself",
"the weavers in her workshop",
"none",
"DigitaltMuseum Norway/Sweden (CC BY items);Wikimedia Commons",
"R3",
"F1.18",
"high",
"links: STY040",
"canon_people.csv"
],
[
"PER428",
"Johan Turi",
"",
"person",
"People",
"F1.11",
"EU-SCA",
"1854",
"1936",
"",
"The Sámi reindeer herder and artist wrote and illustrated Muitalus sámiid birra (1910), the first book by a Sámi author about Sámi life.",
"writing;drawing",
"book;drawing",
"record and writing",
"himself; editor Emilie Demant Hatt",
"Emilie Demant Hatt, who helped publish; the Sámi duodji makers he described",
"Indigenous-community",
"Internet Archive (public-domain scans);Wikimedia Commons",
"R3",
"F1.28;F1.29",
"high",
"",
"canon_people.csv"
],
[
"PER429",
"Peter Behrens",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1868",
"1940",
"",
"The German architect was artistic adviser to AEG from 1907, designing its turbine hall, kettles, lamps and logo.",
"industrial design;architecture;graphic design",
"kettle;lamp;factory",
"food and storage;shelter",
"himself; AEG",
"the AEG engineers and factory workers",
"none",
"Cooper Hewitt Open Access (CC0 metadata, images where PD);Wikimedia Commons",
"R3",
"F1.19;F1.21",
"high",
"links: INS064; MOV011",
"canon_people.csv"
],
[
"PER430",
"Walter Gropius",
"",
"person",
"People",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1883",
"1969",
"",
"The German architect founded the Bauhaus (1919) and later taught at Harvard.",
"architecture;teaching",
"building;school",
"shelter",
"himself",
"the women students steered into weaving; the craft masters",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER431",
"Anni Albers",
"",
"person",
"People",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1899",
"1994",
"",
"The Bauhaus weaver made textiles for industry and wall hangings, studied Andean textiles and wrote On Weaving (1965).",
"handweaving;industrial textile;print",
"textile;wall hanging",
"clothing and adornment;shelter",
"herself",
"the Andean weavers she studied; the Bauhaus policy that put women into weaving",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"She travelled in Mexico with Josef Albers. links: INS057; INS059",
"canon_people.csv"
],
[
"PER432",
"Gunta Stölzl",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1897",
"1983",
"",
"The weaver led the Bauhaus weaving workshop (1926–31), turning it towards textiles for industry.",
"handweaving;jacquard",
"textile",
"clothing and adornment;shelter",
"herself",
"the women students of the workshop",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER433",
"Otti Berger",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1898",
"1944",
"",
"The Bauhaus weaver developed textiles and patented fabrics, and was murdered at Auschwitz in 1944.",
"weaving;textile patent",
"textile",
"clothing and adornment;shelter",
"herself; patents",
"herself, excluded from emigration and credit",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.19a",
"high",
"",
"canon_people.csv"
],
[
"PER434",
"Marianne Brandt",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1893",
"1983",
"",
"The Bauhaus metalworker designed tea sets and lamps, including the Kandem lamps made in quantity with Körting & Mathiesen.",
"metal spinning;brass;design for industry",
"teapot;lamp",
"food and storage;shelter",
"herself",
"the male metal workshop that resisted her entry",
"none",
"Met Open Access (CC0);collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER435",
"Marcel Breuer",
"",
"person",
"People",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1902",
"1981",
"",
"The Bauhaus designer made tubular steel chairs from 1925 and later architecture in the United States.",
"tubular steel;bent plywood",
"chair;building",
"shelter",
"himself",
"the metal fabricators; disputes with Mart Stam over the cantilever chair",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.14",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER436",
"Lilly Reich",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1885",
"1947",
"",
"The German designer co-designed furniture and exhibitions with Mies van der Rohe, including the Barcelona chair and pavilion interiors (1929).",
"exhibition design;furniture;textile",
"chair;exhibition",
"shelter",
"herself",
"herself, when joint work is credited to Mies alone",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.26",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER437",
"Ludwig Mies van der Rohe",
"",
"person",
"People",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1886",
"1969",
"",
"The German architect designed the Barcelona Pavilion and chair (1929) with Lilly Reich and steel and glass towers in the US.",
"steel frame;glass;stone",
"building;chair",
"shelter",
"himself",
"Lilly Reich and the builders",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20;F1.26",
"high",
"links: INS057",
"canon_people.csv"
],
[
"PER438",
"Margarete Schütte-Lihotzky",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1897",
"2000",
"",
"The Austrian architect designed the Frankfurt Kitchen (1926), a compact fitted kitchen installed in about 10,000 flats.",
"fitted kitchen;time-and-motion planning",
"kitchen",
"food and storage;care and access",
"herself",
"the housewives whose work the kitchen was meant to speed up",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.19",
"high",
"",
"canon_people.csv"
],
[
"PER439",
"Le Corbusier",
"Charles-Édouard Jeanneret",
"person",
"People",
"F1.11;F1.9",
"EU-WCE;AS-SAS",
"1887",
"1965",
"",
"The Swiss-French architect wrote on machine-age design and planned Chandigarh, whose buildings used local labour and materials.",
"reinforced concrete;planning",
"building;city plan",
"shelter",
"himself",
"Charlotte Perriand and Pierre Jeanneret; the Indian builders of Chandigarh",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.20",
"high",
"links: STY056",
"canon_people.csv"
],
[
"PER440",
"Charlotte Perriand",
"",
"person",
"People",
"F1.11;F1.8",
"EU-WCE;AS-JPN",
"1903",
"1999",
"",
"The French designer made tubular steel furniture with Le Corbusier's office and in 1940–42 advised Japanese craft industries on export design.",
"tubular steel;bamboo;wood",
"chair;chaise longue",
"shelter",
"herself",
"herself, when chairs are credited to Le Corbusier; the Japanese craftsmen she worked with",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.26;F1.14",
"high",
"",
"canon_people.csv"
],
[
"PER441",
"Eileen Gray",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1878",
"1976",
"",
"The Irish designer made lacquer furniture trained with the Japanese lacquerer Seizo Sugawara and designed the house E-1027.",
"lacquer;tubular steel;architecture",
"screen;chair;house",
"shelter",
"herself",
"Seizo Sugawara; Jean Badovici, credited with E-1027",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER442",
"Sonia Delaunay",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1885",
"1979",
"",
"The Ukrainian-born artist designed printed fabrics and clothing in Paris from colour abstractions.",
"textile printing;fashion",
"textile;garment",
"clothing and adornment",
"herself",
"the factory printers of her fabrics",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER443",
"Alvar Aalto",
"",
"person",
"People",
"F1.11",
"EU-SCA",
"1898",
"1976",
"",
"The Finnish architect designed bent birch plywood furniture and buildings with his wife Aino.",
"bent plywood;architecture",
"chair;building",
"shelter",
"himself",
"Aino Aalto and the Artek and factory workers",
"none",
"collection search link-out only (works in copyright);Finna.fi (CC BY items)",
"R3",
"F1.20;F1.26",
"high",
"links: STY048",
"canon_people.csv"
],
[
"PER444",
"Aino Aalto",
"",
"person",
"People",
"F1.11",
"EU-SCA",
"1894",
"1949",
"",
"The Finnish architect-designer co-designed buildings and furniture with Alvar and designed the Bölgeblick glassware (1932).",
"glass;furniture;architecture",
"glass;building",
"food and storage;shelter",
"herself",
"herself, when joint work is credited to Alvar",
"none",
"collection search link-out only (works in copyright);Finna.fi (CC BY items)",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_people.csv"
],
[
"PER445",
"Varvara Stepanova",
"",
"person",
"People",
"F1.11",
"EU-EER",
"1894",
"1958",
"",
"The Constructivist designer made textile designs for the First State Textile Print Factory in Moscow and sportswear.",
"textile print design",
"textile;sportswear",
"clothing and adornment",
"herself",
"the factory printers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"links: MOV019",
"canon_people.csv"
],
[
"PER446",
"Lyubov Popova",
"",
"person",
"People",
"F1.11",
"EU-EER",
"1889",
"1924",
"",
"The Constructivist painter designed textiles for mass production in Moscow and stage sets.",
"textile print design;stage design",
"textile;stage set",
"clothing and adornment;play and music",
"herself",
"the factory printers",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.20",
"high",
"links: MOV019",
"canon_people.csv"
],
[
"PER447",
"El Lissitzky",
"",
"person",
"People",
"F1.11",
"EU-EER;EU-WCE",
"1890",
"1941",
"",
"The Russian artist designed books, exhibitions and Proun works, bringing Constructivist design to Germany.",
"typography;exhibition design",
"book;poster;exhibition",
"record and writing",
"himself",
"his wife Sophie Lissitzky-Küppers",
"none",
"collection search link-out only (works in copyright);Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: MOV019",
"canon_people.csv"
],
[
"PER448",
"Otto Neurath",
"",
"person",
"People",
"F1.11",
"EU-WCE;EU-BLC",
"1882",
"1945",
"",
"The Austrian economist developed Isotype picture statistics with Marie Reidemeister and Gerd Arntz.",
"pictogram;statistics",
"chart;book",
"record and writing;care and access",
"himself",
"Marie Neurath and Gerd Arntz",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.21",
"high",
"links: MOV022",
"canon_people.csv"
],
[
"PER449",
"Marie Neurath",
"",
"person",
"People",
"F1.11",
"EU-WCE;EU-BLC",
"1898",
"1986",
"",
"The German designer transformed data into Isotype charts and later made children's books.",
"pictogram;information design",
"chart;book",
"record and writing;care and access",
"herself",
"herself, as the 'transformer'",
"none",
"collection search link-out only (works in copyright)",
"R3",
"F1.18;F1.26",
"high",
"links: MOV022",
"canon_people.csv"
],
[
"PER450",
"Maija Isola",
"",
"person",
"People",
"F1.11",
"EU-SCA",
"1927",
"2001",
"",
"The Finnish textile designer drew hundreds of large-scale prints for Marimekko, including Unikko (1964), made by screen printing on cotton.",
"screen printing;pattern design",
"printed textile",
"clothing and adornment;shelter",
"herself; Marimekko",
"Armi Ratia, who founded Marimekko; the factory printers",
"none",
"collection search link-out only (works in copyright);Finna.fi (CC BY items)",
"R3",
"F1.18;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER451",
"Dieter Rams",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1932",
"",
"born 1932; living",
"The German designer led Braun's design department and set out ten principles of good design, applied to radios, shavers and the Vitsoe shelving system.",
"industrial design;sheet metal;plastics",
"radio;record player;shelving",
"shelter;play and music",
"himself; Braun",
"Hans Gugelot and the Braun engineers and designers who worked with him",
"living-community",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.21;F1.20",
"high",
"links: INS067; MOV025",
"canon_people.csv"
],
[
"PER452",
"Ettore Sottsass",
"",
"person",
"People",
"F1.11",
"EU-WCE",
"1917",
"2007",
"",
"The Italian designer designed Olivetti's Elea computer and Valentine typewriter (1969) and founded the Memphis group (1981) with patterned plastic laminates.",
"industrial design;plastic laminate;ceramics",
"typewriter;computer;furniture",
"record and writing;shelter",
"himself",
"the Olivetti engineers, such as Mario Tchou on the Elea, and the Memphis designers",
"none",
"collection search link-out only (works in copyright);Cooper Hewitt Open Access (CC0 metadata, images where PD)",
"R3",
"F1.20;F1.21",
"high",
"links: INS066; MOV029",
"canon_people.csv"
],
[
"PER453",
"Lord Elgin",
"Thomas Bruce, 7th Earl of Elgin",
"person",
"People",
"F1.11",
"EU-GRR;EU-BLC",
"1766",
"1841",
"",
"The British ambassador to the Ottoman court had sculptures removed from the Parthenon (1801–12) and sold them to the British Museum in 1816; Greece has long asked for their return.",
"removal of architectural sculpture",
"marble sculpture;frieze",
"rule and display;ritual and belief",
"himself; parliamentary inquiry (1816); British Museum",
"the Greek workers who cut the sculptures free; the Athenians who objected",
"conflict-looting",
"British Museum Collection Online (CC BY-NC-SA, link out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"Whether his Ottoman permission covered removal is disputed. links: POL117",
"canon_people.csv"
],
[
"PER454",
"Melina Mercouri",
"",
"person",
"People",
"F1.11",
"EU-GRR",
"1920",
"1994",
"",
"As Greece's culture minister (1981–89) she launched the campaign, from 1982, for the return of the Parthenon sculptures from London.",
"advocacy",
"marble sculpture",
"rule and display",
"herself; the Greek state",
"earlier Greek requests for return, made since the 19th century",
"none",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER455",
"Henry Christy",
"",
"person",
"People",
"F1.11",
"EU-BLC",
"1810",
"1865",
"",
"The banker bought ethnographic and prehistoric objects, including Mexican turquoise mosaics, and his collection went to the British Museum after his death.",
"collecting",
"mosaic;stone tool;object",
"rule and display",
"himself; British Museum",
"the makers and the routes by which dealers obtained the objects",
"none",
"British Museum Collection Online (CC BY-NC-SA, link out)",
"R3",
"F1.24",
"high",
"links: INS051",
"canon_people.csv"
],
[
"PER456",
"Marcel Griaule",
"",
"person",
"People",
"F1.11;F1.6",
"EU-WCE;AF-SAH",
"1898",
"1956",
"",
"The French ethnographer led the Dakar-Djibouti mission (1931–33), which took about 3,500 objects to Paris, some by force, as Michel Leiris recorded.",
"ethnographic collecting",
"mask;altar object;painting",
"ritual and belief",
"himself; Michel Leiris (L'Afrique fantôme, 1934)",
"the Dogon, Bamana and other communities from whom objects were taken",
"conflict-looting;sacred",
"Musee du quai Branly (link out)",
"R3",
"F1.24;F1.3",
"high",
"Includes the seizure of a boli from a Bamana shrine.",
"canon_people.csv"
],
[
"PER457",
"Dan Hicks",
"",
"person",
"People",
"F1.11;THEME",
"EU-BLC",
"1972",
"",
"born 1972; living",
"The British archaeologist's The Brutish Museums (2020) argued that museums holding objects taken from Benin in 1897 should return them.",
"provenance research;curating",
"book",
"record and writing",
"himself",
"the Nigerian scholars and claimants who argued for return long before",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.24",
"high",
"links: INS053",
"canon_people.csv"
],
[
"PER458",
"Marcel Mauss",
"",
"person",
"People",
"THEME",
"EU-WCE",
"1872",
"1950",
"",
"The French anthropologist's The Gift (1925) and 'Techniques of the Body' (1935) shaped how exchange and learned bodily skill are studied.",
"anthropology",
"book;essay",
"record and writing",
"himself",
"the Pacific and Northwest Coast peoples whose practices his sources described",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_people.csv"
],
[
"PER459",
"V. Gordon Childe",
"Vere Gordon Childe",
"person",
"People",
"THEME",
"EU-BLC;OC-AUS",
"1892",
"1957",
"",
"The Australian-born archaeologist named the 'Neolithic Revolution' and 'Urban Revolution', framing making and settlement as stages.",
"archaeology;historiography",
"book",
"record and writing",
"himself",
"the mobile and non-urban peoples whom stage models ranked as behind",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.30;F1.5",
"high",
"",
"canon_people.csv"
],
[
"PER460",
"Arnold J. Toynbee",
"",
"person",
"People",
"THEME",
"EU-BLC",
"1889",
"1975",
"",
"The British historian's A Study of History (1934–61) compared some two dozen 'civilisations' rising and falling, a model the Atlas avoids.",
"historiography",
"book",
"record and writing",
"himself",
"stateless and connected peoples outside his list of civilisations",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3",
"high",
"Shown as historiography, not as a frame.",
"canon_people.csv"
],
[
"PER461",
"Samuel P. Huntington",
"",
"person",
"People",
"THEME",
"AM-EWD",
"1927",
"2008",
"",
"The American political scientist's The Clash of Civilizations (1996) divided the world into civilisations defined largely by religion, a framing the Atlas treats as a historical source, not a model.",
"political science;historiography",
"book",
"record and writing",
"himself",
"the mixed, mobile and connected communities his blocs flatten",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3",
"high",
"Shown as historiography, not as a frame.",
"canon_people.csv"
],
[
"PER462",
"André Leroi-Gourhan",
"",
"person",
"People",
"THEME",
"EU-WCE",
"1911",
"1986",
"",
"The French archaeologist developed the chaîne opératoire, the study of making as a sequence of gestures and choices.",
"archaeology;technology study",
"book",
"tools;record and writing",
"himself (Le Geste et la parole, 1964–65)",
"the makers whose gestures are reconstructed without their words",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.28a",
"high",
"",
"canon_people.csv"
],
[
"PER463",
"Pierre Lemonnier",
"",
"person",
"People",
"THEME",
"EU-WCE;OC-MEL",
"1948",
"",
"born 1948; living",
"The French anthropologist of techniques studied Anga making in Papua New Guinea and argued that technical choices are social choices.",
"anthropology of techniques",
"book",
"record and writing",
"himself",
"the Anga makers he studied",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3",
"medium",
"Birth year verified (IdRef authority record).",
"canon_people.csv"
],
[
"PER464",
"Igor Kopytoff",
"",
"person",
"People",
"THEME",
"AM-EWD",
"1930",
"2013",
"",
"The anthropologist's essay 'The Cultural Biography of Things' (1986) showed how an object moves between being a commodity and a singular thing.",
"anthropology",
"essay",
"record and writing",
"himself",
"the makers whose part in an object's life comes first and is often forgotten",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.24",
"high",
"",
"canon_people.csv"
],
[
"PER465",
"Arjun Appadurai",
"",
"person",
"People",
"THEME",
"AM-EWD;AS-SAS",
"1949",
"",
"born 1949; living",
"The Mumbai-born anthropologist edited The Social Life of Things (1986), treating commodities as having careers across regimes of value.",
"anthropology",
"book",
"record and writing",
"himself",
"the producers whose labour is outside the exchange view",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_people.csv"
],
[
"PER466",
"Nelson Graburn",
"",
"person",
"People",
"THEME",
"AM-WST;AM-ARC",
"1936",
"2025",
"born 1936; died 2025",
"The anthropologist edited Ethnic and Tourist Arts (1976), which took souvenir and market art made by colonised peoples seriously.",
"anthropology",
"book",
"record and writing",
"himself",
"the Inuit and other artists whose own accounts of their work were fewer in print",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER467",
"Ron Eglash",
"",
"person",
"People",
"THEME",
"AM-EWD;AF-GUI",
"1958",
"",
"born 1958; living",
"The ethnomathematician's African Fractals (1999) showed recursive geometry in African settlement plans, textiles and hairstyles.",
"ethnomathematics",
"book",
"record and writing",
"himself",
"the African builders, weavers and braiders whose knowledge he analysed",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.15",
"high",
"",
"canon_people.csv"
],
[
"PER468",
"David Graeber",
"",
"person",
"People",
"THEME",
"EU-BLC;AM-EWD",
"1961",
"2020",
"",
"The anthropologist co-wrote The Dawn of Everything (2021), arguing that early societies experimented with many social forms rather than passing through fixed stages.",
"anthropology",
"book",
"record and writing",
"himself and David Wengrow",
"the archaeologists and Indigenous thinkers whose work the book synthesises",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.30",
"high",
"",
"canon_people.csv"
],
[
"PER469",
"David Wengrow",
"",
"person",
"People",
"THEME",
"EU-BLC",
"1972",
"",
"born 1972; living",
"The archaeologist co-wrote The Dawn of Everything (2021) and has written on early branding and the origins of monsters in images.",
"archaeology",
"book",
"record and writing",
"himself and David Graeber",
"the excavators whose data the book draws on",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.30",
"high",
"",
"canon_people.csv"
],
[
"PER470",
"Janet Abu-Lughod",
"",
"person",
"People",
"THEME",
"AM-EWD",
"1928",
"2013",
"",
"The sociologist's Before European Hegemony (1989) described a linked 13th-century world economy from Flanders to China.",
"historical sociology",
"book",
"record and writing",
"herself",
"the weavers, sailors and artisans behind the trade circuits",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.13",
"high",
"",
"canon_people.csv"
],
[
"PER471",
"Nikolaus Pevsner",
"",
"person",
"People",
"THEME;F1.11",
"EU-BLC",
"1902",
"1983",
"",
"The German-British historian's Pioneers of the Modern Movement (1936) traced modern design from Morris to Gropius as a single European line.",
"design history",
"book",
"record and writing",
"himself",
"women designers and makers outside Europe and North America",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.20",
"high",
"",
"canon_people.csv"
],
[
"PER472",
"Reyner Banham",
"",
"person",
"People",
"THEME;F1.11",
"EU-BLC;AM-WST",
"1922",
"1988",
"",
"The British critic's Theory and Design in the First Machine Age (1960) and later writing took popular and technical design seriously.",
"criticism",
"book",
"record and writing",
"himself",
"the makers and users of the vernacular objects he wrote about",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER473",
"Victor Papanek",
"",
"person",
"People",
"THEME",
"AM-EWD;EU-WCE",
"1923",
"1998",
"",
"The Austrian-American designer's Design for the Real World (1971) attacked consumer design and called for design for need, including cheap radios for developing countries.",
"design criticism",
"book",
"record and writing",
"himself",
"the communities whose needs he defined for them",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.22;F1.3",
"high",
"links: MOV046",
"canon_people.csv"
],
[
"PER474",
"Victor Margolin",
"",
"person",
"People",
"THEME",
"AM-EWD",
"1941",
"2019",
"",
"The American historian wrote a multi-volume World History of Design (2015–) that went beyond the European canon.",
"design history",
"book",
"record and writing",
"himself",
"the makers still left outside published sources",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER475",
"Adrian Forty",
"",
"person",
"People",
"THEME",
"EU-BLC",
"1948",
"",
"born 1948; living",
"The British historian's Objects of Desire (1986) linked design to social history and commerce.",
"design history",
"book",
"record and writing",
"himself",
"the factory workers whose making is less visible than the design",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.21",
"high",
"",
"canon_people.csv"
],
[
"PER476",
"Tony Fry",
"",
"person",
"People",
"THEME",
"OC-AUS",
"1999",
"",
"fl.; Defuturing published 1999; birth year not verified; living",
"The design theorist, working in Australia, argued in Defuturing (1999) that design often destroys futures.",
"design theory",
"book",
"record and writing",
"himself",
"Indigenous thinkers on sustainability",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.22;F1.3",
"medium",
"Birth year and birthplace could not be verified in the round-2 check; floruit given and \"British-born\" removed.",
"canon_people.csv"
],
[
"PER477",
"Arturo Escobar",
"",
"person",
"People",
"THEME",
"AM-LAT;AM-EWD",
"1952",
"",
"born 1952; living",
"The Colombian anthropologist's Designs for the Pluriverse (2018) argued for design based on community autonomy.",
"anthropology;design theory",
"book",
"record and writing",
"himself",
"Afro-Colombian and Indigenous movements he draws on",
"living-community",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.22;F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER478",
"Alfred Gell",
"",
"person",
"People",
"THEME",
"EU-BLC;OC-MEL",
"1945",
"1997",
"",
"The British anthropologist's Art and Agency (1998) argued that made objects act as agents in social relations, using Pacific examples.",
"anthropology",
"book",
"record and writing",
"himself",
"the Pacific makers whose objects he theorised",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.16",
"high",
"",
"canon_people.csv"
],
[
"PER479",
"Rozsika Parker",
"",
"person",
"People",
"THEME",
"EU-BLC",
"1945",
"2010",
"",
"The British art historian's The Subversive Stitch (1984) showed how embroidery was made into a sign of femininity.",
"art history",
"book",
"record and writing",
"herself",
"the working-class embroiderers who sewed for pay",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.18;F1.3",
"high",
"",
"canon_people.csv"
],
[
"PER480",
"Edward Said",
"",
"person",
"People",
"THEME",
"AM-EWD;WA-LEV",
"1935",
"2003",
"",
"The Palestinian-American critic's Orientalism (1978) showed how European writing and art constructed an 'Orient'.",
"criticism",
"book",
"record and writing",
"himself",
"the makers whose work was framed as Orientalist decor",
"none",
"library link-out (in copyright); open-access articles where they exist",
"R3",
"F1.3;F1.2",
"high",
"links: STY031",
"canon_people.csv"
],
[
"PRD001",
"Predynastic period (Egypt)",
"Naqada period (Upper Egypt); Neolithic and Chalcolithic Egypt",
"period",
"Time",
"F1.6",
"AF-EGY",
"-5300",
"-3000",
"conventional; after Shaw 2000",
"Naqada and Lower Egyptian communities made painted pottery, stone vessels, palettes and ivory work that set the craft base of the pharaonic state.",
"painted pottery;stone vessel drilling;flint knapping",
"palette;stone vessel;ripple-flaked knife",
"food and storage;ritual and belief",
"Egyptologists (Petrie's sequence dating, refined by Kaiser and Hendrickx)",
"Nubian and desert neighbours; the unnamed village makers",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: ARC013; ARC014; ARC015.",
"canon_periods.csv"
],
[
"PRD002",
"Early Dynastic Period (Egypt)",
"Archaic Period; Dynasties 1–2",
"period",
"Time",
"F1.6",
"AF-EGY",
"-3000",
"-2686",
"conventional; after Shaw 2000",
"The first dynasties organised royal workshops for stone vessels, copper tools, ivory and furniture found in the royal tombs at Abydos and Saqqara.",
"stone vessel making;copper working;ivory carving",
"stone vessel;label;furniture",
"rule and display;record and writing",
"Egyptologists (Manetho's dynasties as modern chronological units)",
"non-royal Egyptians and the retainers buried with kings",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: DYN001; POL001; INV002.",
"canon_periods.csv"
],
[
"PRD003",
"Old Kingdom (Egypt)",
"Pyramid Age; Dynasties 3–6",
"period",
"Time",
"F1.6",
"AF-EGY",
"-2686",
"-2160",
"conventional; after Shaw 2000",
"State-organised crews quarried, moved and dressed stone for pyramids, while tomb workshops produced statuary and relief on a new scale.",
"quarrying;stone dressing;relief carving",
"pyramid;statue;tomb relief",
"ritual and belief;rule and display;shelter",
"Egyptologists; the term was set in 19th-century German Egyptology (Bunsen)",
"the workers' own view, known from Giza workers' town and graffiti of crews",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30;F1.23",
"high",
"links: DYN002.",
"canon_periods.csv"
],
[
"PRD004",
"First Intermediate Period (Egypt)",
"Dynasties 7–11 (early)",
"period",
"Time",
"F1.6",
"AF-EGY",
"-2160",
"-2055",
"conventional; after Shaw 2000",
"With royal power divided, provincial workshops made their own styles of coffins, stelae and models.",
"wood carving;painting",
"coffin;stele;tomb model",
"ritual and belief",
"Egyptologists",
"the provincial makers the \"decline\" label devalues",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30;F1.3",
"high",
"\"Intermediate\" frames it as a gap; many scholars now stress regional creativity.",
"canon_periods.csv"
],
[
"PRD005",
"Middle Kingdom (Egypt)",
"Dynasties 11 (late)–13",
"period",
"Time",
"F1.6",
"AF-EGY",
"-2055",
"-1650",
"conventional; after Shaw 2000",
"Middle Kingdom workshops produced jewellery, block statues and coffins that later Egyptians treated as a classical model.",
"goldsmithing;faience;stone sculpture",
"pectoral;block statue;coffin",
"clothing and adornment;ritual and belief",
"Egyptologists",
"Nubians under Egyptian fortress control",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: DYN003.",
"canon_periods.csv"
],
[
"PRD006",
"Second Intermediate Period (Egypt)",
"Hyksos period; Dynasties 13–17",
"period",
"Time",
"F1.6",
"AF-EGY",
"-1650",
"-1550",
"conventional; after Shaw 2000",
"Hyksos rulers in the Delta and Kerma power to the south brought horses, chariots and Levantine bronze-working into Egypt.",
"bronze casting;chariot making",
"chariot;scarab;dagger",
"war;transport",
"Egyptologists",
"the Levantine and Nubian people cast as invaders",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30;F1.3",
"high",
"links: ARC019; POL002.",
"canon_periods.csv"
],
[
"PRD007",
"New Kingdom (Egypt)",
"Dynasties 18–20",
"period",
"Time",
"F1.6",
"AF-EGY",
"-1550",
"-1069",
"conventional; after Shaw 2000",
"Royal and temple workshops, and the village of Deir el-Medina, produced tomb painting, glass, faience and furniture for an imperial state reaching from Nubia to the Levant.",
"glass;faience;painting;woodworking",
"tomb painting;glass vessel;chair",
"rule and display;ritual and belief",
"Egyptologists",
"captive and tribute labour from Nubia and the Levant",
"funerary;human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30;F1.23",
"high",
"links: DYN004; DYN005; INV026.",
"canon_periods.csv"
],
[
"PRD008",
"Amarna period (Egypt)",
"reign of Akhenaten and successors",
"period",
"Time",
"F1.6",
"AF-EGY",
"-1353",
"-1336",
"approx.; Akhenaten's reign",
"Akhenaten's court at Amarna changed royal art, and the excavated workshop of Thutmose shows how portrait sculpture was made.",
"stone sculpture;plaster casting",
"bust;relief;talatat",
"rule and display;ritual and belief",
"Egyptologists",
"the Amarna workers' cemeteries, which show hard labour",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: STY082.",
"canon_periods.csv"
],
[
"PRD009",
"Third Intermediate Period (Egypt)",
"Dynasties 21–25",
"period",
"Time",
"F1.6",
"AF-EGY",
"-1069",
"-664",
"conventional; after Shaw 2000",
"Divided rule by Libyan and Kushite dynasties saw fine bronze statuary and reused tomb goods.",
"bronze casting;inlay",
"bronze statue;coffin",
"ritual and belief",
"Egyptologists (term popularised by Kenneth Kitchen, 1972)",
"Libyan and Kushite rulers labelled as foreign",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30;F1.3",
"high",
"links: DYN006.",
"canon_periods.csv"
],
[
"PRD010",
"Late Period (Egypt)",
"Dynasties 26–31",
"period",
"Time",
"F1.6",
"AF-EGY",
"-664",
"-332",
"conventional; after Shaw 2000",
"Saite rulers revived Old Kingdom styles, and workshops mass-produced bronze votive figures and animal mummies.",
"bronze casting;archaism",
"votive bronze;shabti",
"ritual and belief",
"Egyptologists",
"the Persian rulers of Egypt, often erased from narratives",
"funerary;sacred",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: DYN007.",
"canon_periods.csv"
],
[
"PRD011",
"Ptolemaic period (Egypt)",
"Hellenistic Egypt",
"period",
"Time",
"F1.6;F1.11",
"AF-EGY",
"-332",
"-30",
"conventional",
"Greek and Egyptian workshops worked side by side, making temples in Egyptian style and Alexandrian glass, faience and portraits.",
"glass;faience;temple building",
"temple;portrait;glass vessel",
"rule and display;ritual and belief",
"Egyptologists and classicists",
"the Egyptian majority behind Greek-centred accounts",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL119; CIV068.",
"canon_periods.csv"
],
[
"PRD012",
"Roman and Byzantine Egypt",
"Roman period (Egypt)",
"period",
"Time",
"F1.6;F1.11",
"AF-EGY",
"-30",
"641",
"30 BCE–641 CE",
"Egypt supplied grain and made linen, papyrus and painted mummy portraits, and later Coptic textiles.",
"encaustic painting;linen weaving;tapestry",
"mummy portrait;tunic;papyrus",
"clothing and adornment;record and writing;ritual and belief",
"historians and papyrologists",
"the rural population known mainly through tax records",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL120; STY083. \"Coptic period\" is a contested alternative label.",
"canon_periods.csv"
],
[
"PRD013",
"Napatan period (Kush)",
"Napatan phase",
"period",
"Time",
"F1.6",
"AF-NUB",
"-750",
"-270",
"approx.",
"Kushite kings at Napata built pyramids and temples and made bronze, gold and faience in forms that blended Egyptian and local traditions.",
"bronze casting;goldsmithing;pyramid building",
"pyramid;shabti;statue",
"ritual and belief;rule and display",
"Nubiologists (Reisner's excavations and later chronology)",
"Nubian self-definition beyond Egyptian models",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL003; DYN006; CIV002.",
"canon_periods.csv"
],
[
"PRD014",
"Meroitic period (Kush)",
"Meroitic phase",
"period",
"Time",
"F1.6",
"AF-NUB",
"-270",
"350",
"approx.; start debated",
"Kushite rulers based at Meroë smelted iron, wrote in Meroitic script and made painted pottery and gold jewellery.",
"iron smelting;painted pottery;goldsmithing",
"pottery;jewellery;pyramid",
"record and writing;clothing and adornment",
"Nubiologists",
"Meroitic, still only partly read",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL003.",
"canon_periods.csv"
],
[
"PRD015",
"Medieval (Christian) Nubian period",
"Christian Nubia",
"period",
"Time",
"F1.6",
"AF-NUB",
"550",
"1500",
"approx.",
"Christian kingdoms of Nobadia, Makuria and Alwa painted church murals, made manuscripts and fine painted pottery.",
"wall painting;pottery;manuscript",
"church mural;pottery",
"ritual and belief",
"Nubiologists; Polish excavations at Faras",
"Nubian Muslims and the gradual change after 1300",
"sacred",
"PeriodO (period gazetteer; link-out); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL004.",
"canon_periods.csv"
],
[
"PRD016",
"Earlier Stone Age (Africa)",
"ESA",
"period",
"Time",
"F1.6",
"GL",
"-3300000",
"-300000",
"approx.; ends at different times by region",
"The ESA covers the earliest known stone tools, from Lomekwian and Oldowan flakes to Acheulean hand axes.",
"stone knapping",
"flake;hand axe;cleaver",
"tools",
"Goodwin and van Riet Lowe (1929) for southern Africa",
"the hominin makers who were not Homo sapiens",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Smithsonian Open Access (CC0 where designated)",
"R3",
"F1.30",
"high",
"links: ARC001; ARC002; ARC003; INV139; INV140.",
"canon_periods.csv"
],
[
"PRD017",
"Middle Stone Age (Africa)",
"MSA",
"period",
"Time",
"F1.6",
"GL",
"-300000",
"-40000",
"approx.; ends regionally c. 50,000–25,000 years ago",
"The MSA saw prepared-core tools, ochre use, shell beads and engraved pieces associated with early Homo sapiens.",
"prepared-core knapping;ochre processing;bead making",
"point;shell bead;engraved ochre",
"tools;clothing and adornment",
"Goodwin and van Riet Lowe (1929)",
"the Eurocentric \"Upper Palaeolithic revolution\" frame it challenged",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: ARC004. Period row; ARC004 is the technocomplex.",
"canon_periods.csv"
],
[
"PRD018",
"Later Stone Age (Africa)",
"LSA",
"period",
"Time",
"F1.6",
"AF-SOU;AF-SWA;AF-CEN;AF-GUI",
"-50000",
"1900",
"approx.; start c. 50,000–20,000 years ago by region; continues into the recent past",
"The LSA covers microlithic tools, ostrich-eggshell beads and rock art made by hunter-gatherers, in some places into the 19th century.",
"microlith;ostrich-eggshell bead making;rock painting",
"bead;rock art;bow",
"tools;clothing and adornment;ritual and belief",
"Goodwin and van Riet Lowe (1929)",
"the living San and other descendants, framed as \"prehistoric\"",
"Indigenous-community",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30;F1.3",
"high",
"links: ARC009. The ESA/MSA/LSA scheme was built to avoid European terms.",
"canon_periods.csv"
],
[
"PRD019",
"African Humid Period",
"Green Sahara",
"period",
"Time",
"F1.6;THEME",
"AF-SAH;AF-MAG;AF-EGY",
"-12500",
"-3500",
"approx.; end time-transgressive, c. 6,000–4,500 years ago",
"A wetter Sahara supported fishing, herding and early pottery, and its drying pushed people towards the Nile and the Sahel.",
"pottery;bone harpoon;herding",
"pottery;harpoon;rock art",
"food and storage",
"palaeoclimatologists",
"regional variation hidden by one label",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R3",
"F1.30;F1.22",
"high",
"links: INV022; ARC012.",
"canon_periods.csv"
],
[
"PRD020",
"Pastoral period (Saharan rock art)",
"Bovidian period",
"period",
"Time",
"F1.6",
"AF-SAH;AF-MAG",
"-5000",
"-2000",
"approx.",
"Paintings and engravings of cattle herds and camp scenes record herding life in the green Sahara.",
"rock painting;rock engraving",
"painting",
"ritual and belief;food and storage",
"rock art scholars (Lhote, Mori)",
"the herders' own descendants and regional variation",
"sacred;Indigenous-community",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD021",
"Camel period (Saharan rock art)",
"Cameline period",
"period",
"Time",
"F1.6",
"AF-SAH;AF-MAG",
"-200",
"1900",
"approx.; continues into recent times",
"Images of camels and Tifinagh inscriptions mark the camel's arrival in the Sahara and the trans-Saharan routes.",
"rock engraving;Tifinagh inscription",
"engraving",
"transport;record and writing",
"rock art scholars",
"the Tuareg and other living descendants",
"Indigenous-community",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.30",
"medium",
"links: NET010; INV073.",
"canon_periods.csv"
],
[
"PRD022",
"Early Iron Age (eastern and southern Africa)",
"EIA; Chifumbaze complex",
"period",
"Time",
"F1.6",
"AF-SWA;AF-SOU;AF-CEN",
"-500",
"1000",
"c. 500 BCE in the Great Lakes; c. 200–1000 CE in southern Africa",
"Farming communities smelted iron, made comb-stamped pottery and kept cattle, associated with Bantu-speaking expansions.",
"iron smelting;pottery;farming",
"pottery;iron hoe",
"tools;food and storage",
"archaeologists (Phillipson; Huffman)",
"foragers who were already there; the language labels",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: ARC023; HOR016; INV087.",
"canon_periods.csv"
],
[
"PRD023",
"Later Iron Age (southern Africa)",
"LIA",
"period",
"Time",
"F1.6",
"AF-SOU",
"1000",
"1850",
"approx.",
"Later farming states such as Mapungubwe and Great Zimbabwe built stone enclosures, worked gold and traded to the coast.",
"dry-stone walling;gold working;cotton spinning",
"stone enclosure;gold rhino;spindle whorl",
"shelter;exchange and value",
"archaeologists (Huffman)",
"oral histories of the descendant communities",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Zamani Project (link-out)",
"R3",
"F1.30",
"high",
"links: ARC040; ARC041; POL014; POL015.",
"canon_periods.csv"
],
[
"PRD024",
"Aksumite period",
"Aksumite era",
"period",
"Time",
"F1.6",
"AF-HRN",
"50",
"700",
"approx.",
"Aksum made stone stelae, gold coins with Ge'ez inscriptions and churches, trading via Adulis.",
"stone carving;coin minting;building",
"stele;coin",
"rule and display;exchange and value",
"Ethiopianists and archaeologists",
"the pre-Aksumite and later Ethiopian periods",
"none",
"PeriodO (period gazetteer; link-out); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL006; CIV003.",
"canon_periods.csv"
],
[
"PRD025",
"Gondarine period (Ethiopia)",
"Gondar period",
"period",
"Time",
"F1.6",
"AF-HRN",
"1632",
"1769",
"approx.",
"The royal capital at Gondar built castles and churches and supported painting in a distinctive \"Gondarine\" style.",
"church painting;castle building",
"church painting;manuscript",
"ritual and belief;rule and display",
"Ethiopianists",
"non-Amhara Ethiopians",
"sacred",
"Wikimedia Commons; British Library Endangered Archives Programme",
"R3",
"F1.30",
"high",
"links: SCH010.",
"canon_periods.csv"
],
[
"PRD026",
"Atlantic era (West and Central Africa)",
"era of the Atlantic trade",
"period",
"Time",
"F1.6;F1.13",
"AF-GUI;AF-CEN;AF-SAH",
"1450",
"1850",
"approx.",
"European ships brought cloth, beads, metals and guns, and the trafficking of enslaved people reshaped states, crafts and trade in West and Central Africa.",
"brass casting;weaving;bead trade",
"manilla;cloth;bead",
"exchange and value",
"historians of Africa",
"African agency, seen too often only as reaction",
"human-flow",
"SlaveVoyages (historical data public domain); PeriodO (period gazetteer; link-out)",
"R2",
"F1.30;F1.13",
"high",
"links: NET034; NET035; NET015.",
"canon_periods.csv"
],
[
"PRD027",
"Mfecane",
"Difaqane",
"period",
"Time",
"F1.6",
"AF-SOU",
"1815",
"1840",
"approx.",
"A period of wars and migrations in southern Africa is linked with the rise of the Zulu kingdom, though the term is contested.",
"none specific",
"none specific",
"war",
"historians (Omer-Cooper 1966; challenged by Cobbing 1988)",
"colonial and slave-raiding pressures",
"human-flow",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"medium",
"Contested label; links: POL017.",
"canon_periods.csv"
],
[
"PRD028",
"Colonial period (Africa)",
"colonial era",
"period",
"Time",
"F1.6",
"GL",
"1885",
"1975",
"approx.; ends by region",
"Colonial rule brought mission schools, forced labour and new markets that shaped carving, weaving and metalwork.",
"none specific",
"none specific",
"rule and display",
"historians",
"African continuities through the period",
"human-flow",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"",
"canon_periods.csv"
],
[
"PRD029",
"Nahda",
"Arab Renaissance",
"period",
"Time",
"F1.10",
"AF-EGY;WA-LEV",
"1850",
"1914",
"approx.",
"The Arabic cultural revival brought printing, journals and new styles of type and design.",
"printing;typography",
"newspaper;book",
"record and writing",
"historians of the Arab world",
"non-urban and non-elite Arabs",
"none",
"PeriodO (period gazetteer; link-out); Digital Library of the Middle East",
"R3",
"F1.30",
"high",
"",
"canon_periods.csv"
],
[
"PRD030",
"Ubaid period",
"Ubaid",
"period",
"Time",
"F1.9a",
"WA-MES;WA-ARB",
"-6500",
"-3800",
"approx.",
"Ubaid villages made painted buff pottery, clay sickles and mud-brick temples that spread from southern Mesopotamia to the Gulf.",
"painted pottery;mud brick",
"pottery;clay sickle",
"food and storage;shelter",
"Near Eastern archaeologists (named after Tell al-'Ubaid; 1930 Baghdad conference)",
"the Gulf coast communities treated as periphery",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: ARC053. Period row; ARC053 is the culture.",
"canon_periods.csv"
],
[
"PRD031",
"Uruk period",
"Uruk",
"period",
"Time",
"F1.9a",
"WA-MES;WA-IRN;WA-ANA",
"-4000",
"-3100",
"approx.",
"Uruk-period cities used mass-produced bevelled-rim bowls, cylinder seals and the first proto-cuneiform tablets to organise labour and goods.",
"mass-produced pottery;seal carving;writing",
"bevelled-rim bowl;cylinder seal;tablet",
"record and writing;food and storage",
"Near Eastern archaeologists (1930 Baghdad conference)",
"the workers paid in rations",
"human-flow",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out); Met Open Access (CC0)",
"R2",
"F1.30;F1.5",
"high",
"links: ARC054; HOR010; INV001; INV172. Ration labour flagged as human-flow.",
"canon_periods.csv"
],
[
"PRD032",
"Early Dynastic period (Mesopotamia)",
"ED I–III",
"period",
"Time",
"F1.9a",
"WA-MES",
"-2900",
"-2350",
"approx.",
"Sumerian city-states made the Royal Tombs of Ur's gold, lapis and shell inlay work, votive statues and inscribed monuments.",
"goldsmithing;shell inlay;statue carving",
"lyre;votive statue;standard",
"ritual and belief;rule and display;play and music",
"Assyriologists (Frankfort's Diyala sequence)",
"the retainers buried in the Ur royal tombs",
"funerary",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out); Met Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: POL092; CIV056; NET018.",
"canon_periods.csv"
],
[
"PRD033",
"Akkadian period",
"Sargonic period",
"period",
"Time",
"F1.9a",
"WA-MES",
"-2334",
"-2154",
"Middle Chronology",
"The Akkadian kings commissioned victory stelae, cast copper heads and fine seals.",
"copper casting;seal carving;relief",
"stele;seal;bust",
"rule and display",
"Assyriologists",
"the conquered cities",
"none",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL093.",
"canon_periods.csv"
],
[
"PRD034",
"Ur III period",
"Neo-Sumerian period",
"period",
"Time",
"F1.9a",
"WA-MES",
"-2112",
"-2004",
"Middle Chronology",
"Ur III kings ran state textile and craft workshops recorded on tens of thousands of tablets.",
"weaving;accounting",
"tablet;textile",
"record and writing;clothing and adornment",
"Assyriologists",
"the women weavers and dependent labourers in the tablets",
"human-flow",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out)",
"R2",
"F1.30;F1.23",
"high",
"links: POL094; INS092.",
"canon_periods.csv"
],
[
"PRD035",
"Old Babylonian period",
"Old Babylonian",
"period",
"Time",
"F1.9a",
"WA-MES",
"-1894",
"-1595",
"Middle Chronology",
"Hammurabi's Babylon issued a law code with wages and liability for builders and craftsmen.",
"stele carving;writing",
"stele;tablet",
"record and writing",
"Assyriologists",
"the enslaved people named in the code",
"human-flow",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out)",
"R2",
"F1.30",
"high",
"links: POL095; TXT038.",
"canon_periods.csv"
],
[
"PRD036",
"Kassite period",
"Middle Babylonian period",
"period",
"Time",
"F1.9a",
"WA-MES",
"-1595",
"-1155",
"Middle Chronology",
"Kassite rulers made glass, moulded brick facades and boundary stones (kudurru).",
"glass;moulded brick",
"kudurru;glass",
"record and writing;rule and display",
"Assyriologists",
"the Kassite language and origins",
"none",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out)",
"R3",
"F1.30",
"high",
"links: TXT039.",
"canon_periods.csv"
],
[
"PRD037",
"Neo-Assyrian period",
"Neo-Assyrian",
"period",
"Time",
"F1.9a",
"WA-MES",
"-911",
"-609",
"approx.",
"Assyrian palaces were lined with carved reliefs and filled with ivory furniture, much of it taken as tribute and booty from Levantine workshops.",
"relief carving;ivory carving",
"relief;ivory",
"rule and display",
"Assyriologists",
"the craftsmen, including deportees, and the Levantine workshops whose ivories came as tribute and booty",
"human-flow;conflict-looting",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cuneiform Digital Library Initiative (link-out)",
"R2",
"F1.30",
"high",
"links: POL096; STY169.",
"canon_periods.csv"
],
[
"PRD038",
"Neo-Babylonian period",
"Neo-Babylonian",
"period",
"Time",
"F1.9a",
"WA-MES",
"-626",
"-539",
"approx.",
"Neo-Babylonian kings rebuilt Babylon with glazed-brick gates and processional ways such as the Ishtar Gate, using deported craftsmen among others.",
"glazed brick",
"gate",
"shelter;rule and display",
"Assyriologists",
"the Judaean and other deported communities",
"human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL097.",
"canon_periods.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
