insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PRD039",
"Middle Elamite period",
"Middle Elamite",
"period",
"Time",
"F1.9a",
"WA-IRN",
"-1500",
"-1100",
"approx.",
"Middle Elamite kings built the ziggurat at Chogha Zanbil and made glazed bricks, bronze statues and glass.",
"glazed brick;bronze casting;glass",
"ziggurat;statue",
"ritual and belief;rule and display",
"Elamologists",
"the builders of Chogha Zanbil",
"none",
"PeriodO (period gazetteer; link-out); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL098; OCC005.",
"canon_periods.csv"
],
[
"PRD040",
"Iron Age I–III (western Iran)",
"Young's Iron Age scheme",
"period",
"Time",
"F1.9a",
"WA-IRN",
"-1450",
"-550",
"Iron I c. 1450–1100; II c. 1100–800; III c. 800–550 BCE",
"The sequence covers grey-ware cemeteries, Hasanlu's gold bowl and the Luristan and Marlik bronzes.",
"grey ware;bronze casting;goldsmithing",
"gold bowl;bronze finial;grey ware",
"ritual and belief;war",
"archaeologists (T. Cuyler Young Jr, 1965; Dyson at Hasanlu)",
"objects looted from unrecorded sites",
"funerary;conflict-looting",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); open-access excavation reports",
"R3",
"F1.30",
"medium",
"links: ARC057; ARC058; STY097.",
"canon_periods.csv"
],
[
"PRD041",
"Chalcolithic (Southern Levant)",
"Ghassulian period",
"period",
"Time",
"F1.9a",
"WA-LEV",
"-4500",
"-3600",
"approx.",
"Makers in the Southern Levant cast complex copper objects by lost wax, as in the Nahal Mishmar hoard, and made ivory figurines and churns.",
"lost-wax casting;arsenical copper;ivory carving",
"crown;mace head;churn",
"ritual and belief",
"Levantine archaeologists",
"the herders and villages outside the big sites",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: ARC055; INV079.",
"canon_periods.csv"
],
[
"PRD042",
"Early Bronze Age (Southern Levant)",
"EB I–IV",
"period",
"Time",
"F1.9a;F1.6",
"WA-LEV",
"-3600",
"-2000",
"approx.; EB IV (Intermediate Bronze Age) c. 2500–2000",
"Walled towns grew with trade in wine, oil and copper to Egypt, and EB IV saw a return to village life.",
"pottery;copper working;olive oil pressing",
"jar;copper tool",
"food and storage;exchange and value",
"Levantine archaeologists (Albright tradition)",
"the pastoral groups of EB IV cast as \"nomads\"",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"",
"canon_periods.csv"
],
[
"PRD043",
"Middle Bronze Age (Levant)",
"MB I–III",
"period",
"Time",
"F1.9a",
"WA-LEV",
"-2000",
"-1550",
"approx.; subdivisions and labels vary",
"Canaanite city-states built rampart towns and made fast-wheel pottery, tin bronze and ivory furniture fittings.",
"fast wheel pottery;tin bronze;ivory carving",
"pottery;dagger;ivory inlay",
"shelter;war",
"Levantine archaeologists",
"competing MB labelling systems (MB I vs MB IIA)",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"",
"canon_periods.csv"
],
[
"PRD044",
"Late Bronze Age (Levant)",
"LB I–II",
"period",
"Time",
"F1.9a;F1.13",
"WA-LEV;WA-ANA",
"-1550",
"-1200",
"approx.",
"Levantine ports such as Ugarit traded copper, tin, glass and purple dye across the eastern Mediterranean, and alphabetic scripts spread.",
"glass;purple dyeing;ivory carving;alphabet",
"glass ingot;ivory;tablet",
"exchange and value;record and writing",
"Levantine archaeologists",
"the collapse narrative's focus on elites",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R2",
"F1.30;F1.13",
"high",
"links: POL100; NET020; INV007.",
"canon_periods.csv"
],
[
"PRD045",
"Iron Age (Levant)",
"Iron I–II",
"period",
"Time",
"F1.9a",
"WA-LEV",
"-1200",
"-586",
"approx.; end at the Babylonian conquest of Judah",
"Small kingdoms such as Israel, Judah, Moab and the Phoenician cities made ivories, inscribed seals and pottery.",
"ivory carving;seal carving;pottery",
"ivory;seal;pottery",
"record and writing;rule and display",
"Levantine and biblical archaeologists",
"the politics of biblical archaeology and whose sites get dug",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.30;F1.3",
"high",
"links: POL102; STY169.",
"canon_periods.csv"
],
[
"PRD046",
"Early Bronze Age (Anatolia)",
"EBA Anatolia",
"period",
"Time",
"F1.9a",
"WA-ANA",
"-3000",
"-2000",
"approx.",
"Anatolian workshops made the Troy \"treasures\" and the Alaca Höyük standards in gold, silver and bronze.",
"goldsmithing;bronze casting",
"standard;jewellery",
"ritual and belief;rule and display",
"Anatolian archaeologists",
"the looted and dispersed finds",
"funerary;conflict-looting",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Wikimedia Commons",
"R3",
"F1.30",
"high",
"",
"canon_periods.csv"
],
[
"PRD047",
"Assyrian Colony period (Anatolia)",
"Kārum period",
"period",
"Time",
"F1.9a;F1.13",
"WA-ANA",
"-1970",
"-1700",
"approx.",
"Assyrian merchants at Kanesh traded tin and textiles for Anatolian silver, and local potters made beak-spouted jugs and animal vessels.",
"wheel pottery;trade",
"beak-spouted jug;rhyton",
"exchange and value",
"Anatolian archaeologists and Assyriologists",
"the Anatolian majority in Kanesh",
"none",
"PeriodO (period gazetteer; link-out); Cuneiform Digital Library Initiative (link-out)",
"R3",
"F1.30",
"high",
"links: NET017; INS093.",
"canon_periods.csv"
],
[
"PRD048",
"Iron Age (Anatolia)",
"Anatolian Iron Age",
"period",
"Time",
"F1.9a",
"WA-ANA",
"-1200",
"-550",
"approx.",
"Phrygian, Neo-Hittite, Urartian and Lydian states made inlaid wooden furniture, bronze cauldrons and the first coins.",
"woodworking;bronze casting;coin minting",
"furniture;cauldron;coin",
"shelter;exchange and value",
"Anatolian archaeologists",
"non-state groups",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL103; POL104; INV169.",
"canon_periods.csv"
],
[
"PRD049",
"Iron Age (southeastern Arabia)",
"Iron Age II falaj period",
"period",
"Time",
"F1.9a",
"WA-ARB",
"-1300",
"-300",
"approx.",
"Communities in Oman and the UAE dug falaj channels, and made soft-stone vessels and bronze weapons.",
"falaj building;soft-stone carving;bronze casting",
"vessel;dagger",
"food and storage",
"Gulf archaeologists",
"the pastoral groups of the interior",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: INV137.",
"canon_periods.csv"
],
[
"PRD050",
"Late Pre-Islamic period (Arabia)",
"PIR period",
"period",
"Time",
"F1.9a",
"WA-ARB",
"-300",
"630",
"approx.",
"Arabian towns such as Mleiha and ed-Dur minted coins, made glass and traded with Rome, Parthia and India.",
"coin minting;glass;trade",
"coin;glass",
"exchange and value",
"Gulf archaeologists",
"nomadic and non-literate groups",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD051",
"Jahiliyya",
"Age of Ignorance",
"period",
"Time",
"F1.10;F1.9a",
"WA-ARB",
"-500",
"610",
"contested label",
"Islamic tradition uses the label for pre-Islamic Arabia, hiding the written, built and crafted cultures of Saba, Nabataea and others.",
"none specific",
"none specific",
"ritual and belief",
"Islamic historiography",
"the pre-Islamic Arabian makers",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label; links: POL112; POL113.",
"canon_periods.csv"
],
[
"PRD052",
"Late Bronze–Early Iron Age (South Caucasus)",
"Lchashen–Metsamor",
"period",
"Time",
"F1.9a",
"WA-CAU",
"-1500",
"-800",
"approx.",
"South Caucasian communities made bronze belts, wagons and weapons found in Lchashen and Metsamor burials.",
"bronze casting;wagon building",
"belt;wagon;dagger",
"transport;war",
"Caucasus archaeologists",
"the regional terminology",
"funerary",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD053",
"Early Cycladic period",
"EC I–III",
"period",
"Time",
"F1.11",
"EU-GRR",
"-3200",
"-2000",
"approx.",
"Cycladic islanders carved marble figurines and vessels and made longboats, known mostly from looted graves.",
"marble carving;obsidian working",
"figurine;vessel",
"ritual and belief",
"Aegean archaeologists (Tsountas; Renfrew)",
"the context lost to looting driven by the modern art market",
"funerary;conflict-looting",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30;F1.24",
"high",
"links: CIV076.",
"canon_periods.csv"
],
[
"PRD054",
"Middle Minoan period",
"MM I–III",
"period",
"Time",
"F1.11",
"EU-GRR",
"-2000",
"-1600",
"approx.",
"The first palaces made eggshell-thin Kamares ware on the fast wheel and early Cretan scripts.",
"fast-wheel pottery;writing",
"Kamares ware;seal",
"food and storage;record and writing",
"Arthur Evans",
"non-palatial Crete",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL115.",
"canon_periods.csv"
],
[
"PRD055",
"Late Minoan period",
"LM I–III",
"period",
"Time",
"F1.11",
"EU-GRR",
"-1600",
"-1100",
"approx.",
"Later palaces made frescoes, marine-style pots and Linear A, then Linear B tablets under Mycenaean control.",
"fresco;pottery;writing",
"fresco;marine-style jar;tablet",
"ritual and belief;record and writing",
"Arthur Evans",
"Evans's reconstructions, now debated",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Wikimedia Commons",
"R3",
"F1.30;F1.28a",
"high",
"",
"canon_periods.csv"
],
[
"PRD056",
"Late Helladic period",
"Mycenaean period",
"period",
"Time",
"F1.11",
"EU-GRR",
"-1600",
"-1100",
"approx.",
"Mycenaean palaces ran workshops for bronze, perfume, textiles and chariot parts recorded in Linear B.",
"bronze;perfume;Linear B",
"tablet;armour;stirrup jar",
"record and writing;war",
"Wace and Blegen (1918)",
"the workers recorded in Linear B",
"human-flow",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Met Open Access (CC0)",
"R2",
"F1.30;F1.23",
"high",
"links: POL116; CIV075.",
"canon_periods.csv"
],
[
"PRD057",
"Early Iron Age (Greece)",
"Greek \"Dark Age\"",
"period",
"Time",
"F1.11",
"EU-GRR",
"-1100",
"-750",
"contested label",
"After the palace collapse, iron working spread and Lefkandi shows wealth and long-distance trade.",
"iron smelting;pottery",
"protogeometric pottery",
"tools",
"classical archaeologists",
"the \"dark\" label, contradicted by finds",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30;F1.3",
"high",
"Contested label.",
"canon_periods.csv"
],
[
"PRD058",
"Geometric period (Greece)",
"Protogeometric and Geometric",
"period",
"Time",
"F1.11",
"EU-GRR",
"-1050",
"-700",
"approx.",
"Athenian potters made large geometric grave markers, and the alphabet was adapted.",
"pottery painting;alphabet",
"amphora;krater",
"ritual and belief;record and writing",
"classical archaeologists",
"non-Attic workshops",
"funerary",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: STY001.",
"canon_periods.csv"
],
[
"PRD059",
"Archaic period (Greece)",
"Archaic Greece",
"period",
"Time",
"F1.11",
"EU-GRR",
"-800",
"-480",
"approx.; start variously 776 or c. 700 BCE; end 480 BCE",
"Greek city-states built stone temples, carved kouroi and korai, and Corinthian and Athenian potters developed black-figure painting for export.",
"marble carving;black-figure painting;bronze casting",
"kouros;amphora;temple",
"ritual and belief;exchange and value",
"classical archaeologists and art historians",
"the Phoenician, Egyptian and Anatolian sources of many techniques",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30",
"high",
"links: STY003; STY002.",
"canon_periods.csv"
],
[
"PRD060",
"Classical period (Greece)",
"Classical Greece",
"period",
"Time",
"F1.11",
"EU-GRR",
"-480",
"-323",
"conventional; 480 (Persian Wars) to 323 BCE (death of Alexander)",
"Athenian workshops made red-figure pottery, bronze statues and the Parthenon sculptures, later treated in Europe as the standard of art.",
"red-figure painting;bronze casting;marble carving",
"vase;statue;temple sculpture",
"ritual and belief;rule and display",
"classicists; Winckelmann's 18th-century ideal",
"the enslaved and metic workers in Athenian workshops",
"human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30;F1.3",
"high",
"links: STY004; POL117. \"Classical\" as norm is a F1.3 topic.",
"canon_periods.csv"
],
[
"PRD061",
"Hellenistic period",
"Hellenistic age",
"period",
"Time",
"F1.11;F1.9a",
"EU-GRR;WA-ANA;WA-LEV;AF-EGY;WA-IRN",
"-323",
"-31",
"conventional; 323 BCE to Actium (31 BCE)",
"Kingdoms founded after Alexander spread Greek workshops from Egypt to Bactria, with new work in glass, gems, bronze and mosaic.",
"mould-blown glass;gem engraving;mosaic",
"statue;cameo;mosaic",
"rule and display",
"historians (term popularised by J. G. Droysen, 1836)",
"the Egyptian, Iranian and Indian makers who shaped \"Greek\" art",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30",
"high",
"links: CIV068; STY005; POL119.",
"canon_periods.csv"
],
[
"PRD062",
"Roman Republic",
"Republican period",
"period",
"Time",
"F1.11",
"EU-GRR",
"-509",
"-27",
"conventional",
"The Republic expanded across the Mediterranean, and conquest brought Greek art, artists and enslaved craftworkers to Rome.",
"concrete;bronze;wall painting",
"portrait bust;wall painting",
"rule and display;war",
"historians of Rome",
"the enslaved people who did much of the craft work",
"human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: POL120; INV135.",
"canon_periods.csv"
],
[
"PRD063",
"Roman Imperial period",
"Principate and Late Empire",
"period",
"Time",
"F1.11;F1.6;F1.9a",
"EU-GRR;EU-WCE;EU-BLC;AF-MAG;AF-EGY;WA-LEV;WA-ANA",
"-27",
"476",
"27 BCE to 476 CE in the West; East continues as Byzantium",
"Empire-wide workshops made terra sigillata, glass, mosaics and concrete buildings.",
"terra sigillata;glassblowing;mosaic;concrete",
"bowl;glass vessel;mosaic",
"shelter;food and storage",
"historians of Rome",
"provincial makers counted as \"Roman\"",
"human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30",
"high",
"links: POL120; INV027; INV136.",
"canon_periods.csv"
],
[
"PRD064",
"Late Antiquity",
"late antique period",
"period",
"Time",
"F1.11;F1.10;F1.9a",
"EU-GRR;EU-BYZ;WA-LEV;AF-EGY;WA-IRN",
"250",
"750",
"approx.; Peter Brown's \"world of late antiquity\"",
"The label treats the late Roman, early Byzantine, Sasanian and early Islamic worlds as a continuous era of silk, mosaic, ivory and manuscript making.",
"mosaic;ivory carving;silk weaving;codex",
"mosaic;diptych;codex",
"ritual and belief;record and writing",
"Peter Brown (1971) and followers",
"the Germanic and steppe peoples cast as outsiders",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.30;F1.3",
"high",
"Replaces \"decline and fall\"; links: OCC020.",
"canon_periods.csv"
],
[
"PRD065",
"Early Byzantine period",
"Early Byzantine",
"period",
"Time",
"F1.11",
"EU-BYZ;WA-ANA;WA-LEV",
"330",
"843",
"approx.; 330 to the end of Iconoclasm",
"Constantinople's workshops made Hagia Sophia, silk textiles, ivories and the earliest surviving icons.",
"mosaic;silk weaving;icon painting",
"mosaic;icon;silk",
"ritual and belief",
"Byzantinists",
"the provinces and the Coptic, Syrian and Armenian makers",
"sacred",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL121.",
"canon_periods.csv"
],
[
"PRD066",
"Middle Byzantine period",
"Middle Byzantine",
"period",
"Time",
"F1.11",
"EU-BYZ;WA-ANA",
"843",
"1204",
"approx.",
"After Iconoclasm, enamel, ivory and icon workshops flourished and supplied Rus and Italy.",
"cloisonné enamel;ivory carving",
"enamel;icon",
"ritual and belief",
"Byzantinists",
"non-elite makers",
"sacred",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: DYN077.",
"canon_periods.csv"
],
[
"PRD067",
"Late Byzantine period",
"Palaiologan period",
"period",
"Time",
"F1.11",
"EU-BYZ",
"1261",
"1453",
"approx.; after the Latin occupation 1204–1261",
"Palaiologan patrons commissioned mosaics and frescoes such as those of the Chora church.",
"mosaic;fresco",
"mosaic",
"ritual and belief",
"Byzantinists",
"Latin and Ottoman neighbours",
"sacred",
"PeriodO (period gazetteer; link-out); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: DYN078.",
"canon_periods.csv"
],
[
"PRD068",
"Upper Palaeolithic (Europe)",
"Late Palaeolithic in some traditions",
"period",
"Time",
"F1.11",
"EU-WCE;EU-IBE;EU-EER",
"-43000",
"-10000",
"approx.",
"Upper Palaeolithic people in Europe made cave paintings, carved ivory figurines, bone needles and blade tools.",
"blade knapping;ivory carving;cave painting",
"figurine;needle;cave painting",
"ritual and belief;clothing and adornment;tools",
"European prehistorians (Lartet and Christy; Breuil; de Mortillet)",
"older art and ornament from Africa and Asia that the \"creative explosion\" story overlooked",
"sacred",
"PeriodO (period gazetteer; link-out); Wikimedia Commons; open-access excavation reports",
"R3",
"F1.30;F1.3",
"high",
"links: ARC070; ARC071; ARC072; ARC073; INV154.",
"canon_periods.csv"
],
[
"PRD069",
"Mesolithic (northern Europe)",
"Mesolithic",
"period",
"Time",
"F1.11",
"EU-SCA;EU-BLC;EU-WCE",
"-9700",
"-4000",
"approx.; ends with farming, earlier in the south",
"Post-glacial hunter-fishers made microliths, dugout canoes, fish traps and antler tools.",
"microlith;dugout canoe;fish trap",
"canoe;harpoon;fish trap",
"food and storage;transport",
"European prehistorians (term from Hodder Westropp, 1866; later defined by Grahame Clark and others)",
"the persistence of foraging alongside farmers",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: ARC074; ARC075; INV109.",
"canon_periods.csv"
],
[
"PRD070",
"Three-age system (Stone, Bronze, Iron)",
"Thomsen's three ages",
"period",
"Time",
"F1.11;THEME",
"EU-SCA",
"-10000",
"1",
"approx.; defined for Danish collections",
"Christian Jürgensen Thomsen arranged the Danish national collection by the material of tools, creating the Stone, Bronze and Iron Age sequence later applied far beyond the region it was built for.",
"stone;bronze;iron",
"axe;sword;display case",
"tools",
"C. J. Thomsen (Guide to Northern Antiquities, 1836)",
"regions where copper, bronze and iron arrived in other orders or not at all (sub-Saharan Africa, Americas, Oceania)",
"none",
"PeriodO (period gazetteer; link-out); Internet Archive (public-domain texts)",
"R1",
"F1.30;F1.3",
"high",
"Always give the region when using these ages.",
"canon_periods.csv"
],
[
"PRD071",
"Copper Age (Balkans)",
"Chalcolithic / Eneolithic (southeast Europe)",
"period",
"Time",
"F1.11",
"EU-BYZ;EU-EER",
"-5000",
"-3500",
"approx.",
"Balkan communities mined and smelted copper and made the gold of the Varna cemetery.",
"copper smelting;goldsmithing;graphite painting",
"gold ornament;copper axe",
"clothing and adornment;ritual and belief",
"Balkan prehistorians",
"the \"Old Europe\" label's romantic claims",
"funerary",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: ARC080; ARC081; INV076; INV078.",
"canon_periods.csv"
],
[
"PRD072",
"Bronze Age (Central Europe, Reinecke)",
"Bz A–D; Hallstatt A–B",
"period",
"Time",
"F1.11",
"EU-WCE",
"-2200",
"-800",
"approx.",
"Reinecke's scheme dates Central European bronze hoards, weapons and ornaments by type.",
"bronze casting;hoarding",
"sword;axe;ornament",
"war;exchange and value",
"Paul Reinecke (from 1902)",
"the people behind the types",
"none",
"PeriodO (period gazetteer; link-out); Europeana (per-item rights)",
"R3",
"F1.30",
"high",
"links: ARC089; ARC092; NET026.",
"canon_periods.csv"
],
[
"PRD073",
"Bronze Age (Britain and Ireland)",
"British Bronze Age",
"period",
"Time",
"F1.11",
"EU-BLC",
"-2500",
"-800",
"approx.",
"Metalworkers in Britain and Ireland made gold lunulae, bronze axes and beakers, trading tin and copper.",
"goldsmithing;bronze casting;tin mining",
"lunula;axe;beaker",
"clothing and adornment;tools",
"British prehistorians",
"the continental migrants shown by aDNA",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports; Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: HOR011; NET026.",
"canon_periods.csv"
],
[
"PRD074",
"Migration Period",
"Völkerwanderung",
"period",
"Time",
"F1.11",
"EU-WCE;EU-SCA;EU-BYZ",
"375",
"568",
"approx.",
"Migrating groups carried garnet cloisonné and animal-style metalwork across Europe.",
"garnet cloisonné;gold casting",
"brooch;bracteate",
"clothing and adornment",
"German and Scandinavian historians",
"the Roman population who stayed",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Europeana (per-item rights)",
"R3",
"F1.30;F1.3",
"high",
"links: STY008.",
"canon_periods.csv"
],
[
"PRD075",
"Viking Age",
"Viking period",
"period",
"Time",
"F1.11;F1.13",
"EU-SCA;EU-BLC;EU-EER",
"793",
"1066",
"conventional",
"Norse traders, raiders and settlers made ships, silver hoards and animal-style art from Kyiv to Greenland.",
"shipbuilding;silverwork",
"ship;brooch;hoard",
"transport;exchange and value",
"Scandinavian historians",
"Sámi, Slavic and other partners",
"none",
"PeriodO (period gazetteer; link-out); Europeana (per-item rights)",
"R2",
"F1.30",
"high",
"links: CIV080; STY159.",
"canon_periods.csv"
],
[
"PRD076",
"Anglo-Saxon period",
"early medieval England",
"period",
"Time",
"F1.11",
"EU-BLC",
"410",
"1066",
"conventional",
"Early English kingdoms made the Sutton Hoo gold and garnet work, the Lindisfarne Gospels and opus anglicanum embroidery.",
"goldsmithing;garnet cloisonné;illumination;embroidery",
"buckle;gospel book;embroidery",
"ritual and belief;clothing and adornment",
"English historians",
"the Britons and later Norse; the term's use by white-supremacist groups has led many scholars to prefer \"early medieval England\"",
"none",
"PeriodO (period gazetteer; link-out); Wikimedia Commons; British Library public-domain images (Flickr Commons)",
"R3",
"F1.30;F1.3",
"high",
"Contested label; links: POL122; STY009.",
"canon_periods.csv"
],
[
"PRD077",
"Reconquista",
"\"reconquest\" of Iberia",
"period",
"Time",
"F1.11;F1.10",
"EU-IBE",
"718",
"1492",
"contested label; traditional start at Covadonga (c. 718–722)",
"The label presents eight centuries as a Christian recovery of Iberia and hides long periods of shared making, as in Mudéjar building and lustreware.",
"plasterwork;lustreware;carpentry",
"tile;ceiling",
"war;shelter",
"Spanish nationalist and Catholic historiography",
"the Muslim and Jewish makers who stayed after conquest",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label; links: STY015; POL153; POL154.",
"canon_periods.csv"
],
[
"PRD078",
"Early Middle Ages (Europe)",
"Early medieval period; \"Dark Ages\" (older, contested)",
"period",
"Time",
"F1.11",
"EU-WCE;EU-BLC;EU-IBE",
"500",
"1000",
"conventional; the term \"Middle Ages\" was coined by 15th-century humanists",
"Monasteries and courts in western Europe made illuminated gospel books, reliquaries and metalwork, often using Mediterranean and eastern materials.",
"illumination;goldsmithing;parchment making",
"gospel book;reliquary",
"record and writing;ritual and belief",
"European historians (humanist label \"medium aevum\")",
"the Byzantine and Islamic worlds, where there was no \"middle age\"",
"none",
"PeriodO (period gazetteer; link-out); Wikimedia Commons; Europeana (per-item rights)",
"R3",
"F1.30;F1.3",
"high",
"",
"canon_periods.csv"
],
[
"PRD079",
"High Middle Ages (Europe)",
"High Medieval period",
"period",
"Time",
"F1.11",
"EU-WCE;EU-BLC;EU-IBE",
"1000",
"1300",
"conventional",
"Growing towns built cathedrals and organised crafts into guilds, while stained glass, tapestry and enamel workshops served church and court.",
"stone masonry;stained glass;Limoges enamel",
"cathedral;window;reliquary",
"ritual and belief;shelter",
"European historians",
"women's and rural craft outside guilds",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.30",
"high",
"links: STY012; STY013.",
"canon_periods.csv"
],
[
"PRD080",
"Renaissance (Italy)",
"Rinascimento",
"period",
"Time",
"F1.11",
"EU-GRR;EU-WCE",
"1400",
"1600",
"approx.; label from Michelet (1855) and Burckhardt (1860)",
"The label casts Italian and later European art of c. 1400–1600 as a rebirth of antiquity, stressing named artists over workshops.",
"panel painting;bronze casting;linear perspective",
"painting;sculpture;medal",
"rule and display;ritual and belief",
"Vasari; Michelet; Burckhardt",
"workshop assistants, women makers, and Islamic and Byzantine sources",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); National Gallery of Art (US) Open Access; Wikimedia Commons",
"R2",
"F1.30;F1.3",
"high",
"links: STY019; TXT005.",
"canon_periods.csv"
],
[
"PRD081",
"Early modern period",
"early modern",
"period",
"Time",
"F1.11;F1.13;THEME",
"GL",
"1500",
"1800",
"approx.; contested outside Europe",
"Historians use the term for the era of global maritime trade, print and early empires, now often applied beyond Europe.",
"printing;global trade",
"none specific",
"exchange and value",
"European historians, extended by global historians",
"societies whose histories do not fit the European turning points",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label.",
"canon_periods.csv"
],
[
"PRD082",
"Age of Discovery",
"Age of Exploration; Age of Contact",
"period",
"Time",
"F1.11;F1.13;THEME",
"GL",
"1415",
"1600",
"approx.; Ceuta 1415 often used as start",
"The label celebrates European voyages that opened sea routes for trade in textiles, porcelain, silver and people, but names the period from the voyagers' side.",
"shipbuilding;navigation;cartography",
"map;ship;globe",
"transport;exchange and value",
"European historians",
"the peoples \"discovered\", and Asian and African sailors already on the routes",
"human-flow",
"PeriodO (period gazetteer; link-out); Library of Congress (per-item rights; many public domain); Wikimedia Commons",
"R2",
"F1.30;F1.3",
"high",
"Contested label; links: OCC053; OCC052.",
"canon_periods.csv"
],
[
"PRD083",
"Industrial Revolution (Britain)",
"First Industrial Revolution",
"period",
"Time",
"F1.11",
"EU-BLC",
"1760",
"1840",
"approx.; term popularised by Arnold Toynbee's lectures (1881, publ. 1884)",
"Water and steam power, coke-smelted iron and factory spinning moved much textile and metal making from homes and workshops into mills.",
"steam power;factory spinning;coke smelting",
"spinning machine;cast iron;printed cotton",
"tools;clothing and adornment",
"economic historians (Toynbee; later debate on gradualism)",
"Indian and other textile industries it undercut, enslaved cotton growers, child workers",
"human-flow",
"PeriodO (period gazetteer; link-out); Science Museum Group Collection (link-out); Yale Center for British Art (public-domain images)",
"R1",
"F1.30;F1.19",
"high",
"links: INV174; OCC101; OCC093.",
"canon_periods.csv"
],
[
"PRD084",
"Long nineteenth century",
"long 19th century",
"period",
"Time",
"F1.11;THEME",
"GL",
"1789",
"1914",
"Eric Hobsbawm's periodisation",
"Hobsbawm framed 1789–1914 as the age of revolution, capital and empire, during which industrial making and colonial extraction grew together.",
"none specific",
"none specific",
"exchange and value",
"Eric Hobsbawm (trilogy 1962–1987)",
"non-European periodisations of the same years",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"",
"canon_periods.csv"
],
[
"PRD085",
"Machine Age",
"Machine Age (design history)",
"period",
"Time",
"F1.11;F1.7;THEME",
"EU-WCE;AM-EWD",
"1880",
"1945",
"approx.; label popular in the 1920s–30s (e.g. the 1927 Machine-Age Exposition, New York)",
"Designers and artists of the interwar years celebrated machines and machine-made forms in streamlined and modernist products.",
"chrome plating;tubular steel;Bakelite",
"chair;radio;locomotive",
"tools;transport;shelter",
"design historians; the period's own promoters",
"the craft labour behind \"machine-made\" looks",
"none",
"PeriodO (period gazetteer; link-out); Smithsonian Open Access (CC0 where designated); Library of Congress (per-item rights; many public domain)",
"R2",
"F1.30;F1.19",
"medium",
"links: STY043; OCC209. Date span varies by author.",
"canon_periods.csv"
],
[
"PRD086",
"Cold War",
"Cold War period",
"period",
"Time",
"F1.11;F1.7;THEME",
"GL",
"1947",
"1991",
"conventional",
"Rivalry between the US and USSR used design, exhibitions and craft as propaganda, from the \"kitchen debate\" to Soviet and US pavilions.",
"none specific",
"appliance;pavilion;poster",
"rule and display",
"historians",
"the hot wars fought in Asia, Africa and Latin America",
"none",
"PeriodO (period gazetteer; link-out); Library of Congress (per-item rights; many public domain)",
"R3",
"F1.30",
"high",
"",
"canon_periods.csv"
],
[
"PRD087",
"Tatar yoke",
"Mongol yoke",
"period",
"Time",
"F1.11;F1.12a",
"EU-EER",
"1240",
"1480",
"contested label",
"Russian historiography used the label for Golden Horde overlordship, hiding its trade and craft links with the steppe and Central Asia.",
"none specific",
"none specific",
"rule and display",
"Russian historiography",
"Golden Horde workshops and exchange",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label; links: POL143; POL233.",
"canon_periods.csv"
],
[
"PRD088",
"Tourkokratia",
"Ottoman period in Greece",
"period",
"Time",
"F1.11;F1.10",
"EU-BYZ",
"1453",
"1821",
"contested label",
"Greek historiography calls the period of Ottoman rule \"Turkish rule\", which obscures shared crafts and Greek workshops across the empire.",
"silverwork;embroidery;icon painting",
"icon;embroidery",
"ritual and belief",
"Greek national historiography",
"Greek makers who prospered under Ottoman rule",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label.",
"canon_periods.csv"
],
[
"PRD089",
"Information Age",
"Digital age",
"period",
"Time",
"F1.7;F1.13;THEME",
"GL",
"1970",
"",
"approx.; label from the 1970s–90s",
"Microprocessors, personal computers and networks moved design, publishing and much manufacturing control into software.",
"software;digital fabrication",
"computer;website",
"record and writing",
"sociologists and historians (e.g. Manuel Castells)",
"the mining and assembly labour behind devices",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30",
"high",
"links: INV050; INV051; NET063.",
"canon_periods.csv"
],
[
"PRD090",
"Anthropocene",
"Anthropocene",
"period",
"Time",
"THEME;F1.13",
"GL",
"1950",
"",
"proposed start c. 1950; formal epoch rejected by the IUGS in 2024",
"Scientists proposed that humans now shape the Earth system enough to name a new epoch, with plastics, concrete and fallout as markers.",
"plastics;concrete;radionuclides",
"none specific",
"care and access",
"Paul Crutzen and Eugene Stoermer (2000); Anthropocene Working Group (from 2009)",
"who caused the change; alternatives such as Capitalocene and Plantationocene",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R1",
"F1.30;F1.22;F1.3",
"high",
"Contested label; formal proposal (Crawford Lake) rejected in March 2024.",
"canon_periods.csv"
],
[
"PRD091",
"Last Glacial Maximum",
"LGM",
"period",
"Time",
"THEME",
"GL",
"-24500",
"-17000",
"c. 26,500–19,000 years ago",
"At the coldest point of the last ice age, people made sewn clothing, used mammoth bone for shelters in Eastern Europe and occupied cold regions.",
"sewing;bone building",
"needle;mammoth-bone dwelling",
"clothing and adornment;shelter",
"palaeoclimatologists",
"regional variation in timing",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R3",
"F1.30;F1.22",
"high",
"",
"canon_periods.csv"
],
[
"PRD092",
"Holocene",
"Holocene epoch",
"period",
"Time",
"THEME",
"GL",
"-9700",
"",
"from 11,700 years before 2000 CE",
"The present warm epoch covers farming, cities, metals and almost all the making in this atlas.",
"none specific",
"none specific",
"care and access",
"International Commission on Stratigraphy",
"the Anthropocene debate over whether it has ended",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R3",
"F1.30;F1.22",
"high",
"",
"canon_periods.csv"
],
[
"PRD093",
"Meghalayan Age",
"4.2-kiloyear event",
"period",
"Time",
"THEME",
"GL",
"-2250",
"",
"from 4,250 years before 2000 CE (formalised 2018)",
"A drought event about 4,200 years ago, used to define the latest Holocene stage, is linked by some to changes in Akkadian, Indus and Egyptian societies.",
"none specific",
"none specific",
"food and storage",
"International Commission on Stratigraphy",
"critics of climate-driven collapse stories",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R3",
"F1.30;F1.22;F1.3",
"high",
"The causal links are debated.",
"canon_periods.csv"
],
[
"PRD094",
"Little Ice Age",
"Little Ice Age",
"period",
"Time",
"THEME",
"GL",
"1300",
"1850",
"approx.; start dated 1300–1600 by author",
"Colder centuries in parts of the Northern Hemisphere are linked by historians with harvest failures, frozen rivers and the end of Norse Greenland.",
"none specific",
"none specific",
"food and storage",
"palaeoclimatologists (François Matthes, 1939) and historians",
"regional variation and the debate on causes",
"none",
"PeriodO (period gazetteer; link-out); open-access journals (DOAJ, SciELO, Persée)",
"R3",
"F1.30;F1.22;F1.3",
"medium",
"Contested; start dated 1300–1600 by author.",
"canon_periods.csv"
],
[
"PRD095",
"Xia (contested period)",
"Xia dynasty (traditional)",
"period",
"Time",
"F1.8",
"AS-CHN",
"-2070",
"-1600",
"traditional; dates from the Xia–Shang–Zhou Chronology Project (2000)",
"Chinese historiography places a Xia dynasty before the Shang, and some archaeologists identify it with Erlitou's bronze-casting centre, though no Xia writing has been found.",
"bronze casting;jade carving",
"jue vessel;jade blade",
"ritual and belief;rule and display",
"traditional Chinese historiography (Sima Qian); Xia–Shang–Zhou Chronology Project",
"the many other Late Neolithic centres the dynastic line leaves out",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30;F1.3",
"medium",
"Contested; links: ARC125.",
"canon_periods.csv"
],
[
"PRD096",
"Spring and Autumn period",
"Chunqiu",
"period",
"Time",
"F1.8",
"AS-CHN",
"-770",
"-476",
"conventional; named after the Chunqiu annals",
"Rival Zhou states cast inscribed ritual bronzes with new pattern-block methods and began iron use.",
"piece-mould casting;pattern blocks;iron",
"ritual bronze;bell set",
"ritual and belief;play and music",
"Chinese historiography",
"non-Zhou peoples such as the Rong and Yi",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: POL158.",
"canon_periods.csv"
],
[
"PRD097",
"Warring States period",
"Zhanguo",
"period",
"Time",
"F1.8",
"AS-CHN",
"-475",
"-221",
"conventional",
"Competing states mass-produced iron tools and crossbows, made lacquerware, silk and inlaid bronzes, and wrote the Kaogongji on crafts.",
"cast iron;lacquer;silk weaving;inlay",
"crossbow;lacquer cup;inlaid bronze",
"war;tools;ritual and belief",
"Chinese historiography (after the Zhanguo ce)",
"the conscript and convict labour in state workshops",
"human-flow",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.30;F1.17",
"high",
"links: TXT091; INV167; INV089.",
"canon_periods.csv"
],
[
"PRD098",
"Six Dynasties",
"Liuchao",
"period",
"Time",
"F1.8",
"AS-CHN",
"220",
"589",
"conventional; the six southern capitals at Jiankang",
"Southern courts developed calligraphy, painting theory and celadon, while Buddhism brought cave temples in the north.",
"calligraphy;celadon;cave carving",
"calligraphy;celadon;Buddhist image",
"record and writing;ritual and belief",
"Chinese historiography",
"the northern dynasties, the term centres the south",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.30;F1.3",
"high",
"links: POL161.",
"canon_periods.csv"
],
[
"PRD099",
"Northern Song period",
"Bei Song",
"period",
"Time",
"F1.8",
"AS-CHN",
"960",
"1127",
"conventional",
"From Kaifeng, the Song court and markets made Ru, Ding and Jun wares, printed books and the Yingzao fashi building manual.",
"stoneware;porcelain;printing;timber framing",
"Ru ware;printed book;building manual",
"record and writing;shelter",
"Chinese historiography",
"the Liao and Xi Xia, who shared its technologies",
"none",
"PeriodO (period gazetteer; link-out); National Palace Museum Taipei Open Data (CC BY 4.0); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: POL166; TXT092; OCC032.",
"canon_periods.csv"
],
[
"PRD100",
"Southern Song period",
"Nan Song",
"period",
"Time",
"F1.8",
"AS-CHN",
"1127",
"1279",
"conventional",
"From Hangzhou the court supported Longquan celadon, Guan ware, academy painting and a large maritime trade.",
"celadon;academy painting;shipbuilding",
"Longquan celadon;painting",
"exchange and value",
"Chinese historiography",
"the Jin in the north",
"none",
"PeriodO (period gazetteer; link-out); National Palace Museum Taipei Open Data (CC BY 4.0); Met Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: SCH034.",
"canon_periods.csv"
],
[
"PRD101",
"Transitional period (Chinese porcelain)",
"Ming–Qing transition",
"period",
"Time",
"F1.8;F1.13",
"AS-CHN",
"1620",
"1683",
"approx.; ceramic historians' label",
"During the Ming–Qing wars, Jingdezhen potters made blue-and-white with new narrative scenes for private and export buyers.",
"blue-and-white porcelain",
"jar;vase",
"food and storage;exchange and value",
"ceramic historians and collectors (20th century)",
"the potters' conditions during the wars",
"none",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0); Rijksmuseum (CC0/PDM)",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD102",
"High Qing",
"Kang–Qian era",
"period",
"Time",
"F1.8",
"AS-CHN",
"1683",
"1796",
"approx.",
"Under the Kangxi, Yongzheng and Qianlong emperors, palace workshops made enamels, porcelain, jade and glass.",
"painted enamel;porcelain;jade carving",
"enamel;porcelain;jade",
"rule and display",
"Chinese and Western historians",
"the Taiwanese, Tibetan and Xinjiang conquests of the same years",
"none",
"PeriodO (period gazetteer; link-out); National Palace Museum Taipei Open Data (CC BY 4.0); Met Open Access (CC0)",
"R3",
"F1.30",
"high",
"links: INS020; POL169.",
"canon_periods.csv"
],
[
"PRD103",
"Century of Humiliation",
"Bainian guochi",
"period",
"Time",
"F1.8",
"AS-CHN",
"1839",
"1949",
"contested label",
"The label frames the Opium Wars to 1949 as foreign humiliation, a frame that shapes PRC restitution demands such as for the Yuanmingyuan bronzes.",
"none specific",
"none specific",
"rule and display",
"Chinese nationalist and PRC historiography",
"Chinese modernisation from within",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"high",
"Contested label.",
"canon_periods.csv"
],
[
"PRD104",
"Republican period (China)",
"Minguo",
"period",
"Time",
"F1.8",
"AS-CHN",
"1912",
"1949",
"conventional",
"The Republic brought art schools, modern printing, advertising posters and new dress such as the qipao.",
"lithography;photography",
"poster;qipao",
"clothing and adornment",
"Chinese historiography",
"rural makers and warlord regions",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30",
"high",
"links: INS023.",
"canon_periods.csv"
],
[
"PRD105",
"Mao era",
"Maoist period",
"period",
"Time",
"F1.8",
"AS-CHN",
"1949",
"1976",
"conventional",
"State planning organised crafts into co-operatives and produced propaganda posters and export crafts.",
"poster printing;co-operative craft",
"poster;export craft",
"rule and display",
"Chinese historiography",
"the famine and persecution of makers",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30",
"high",
"links: OCC227; OCC236.",
"canon_periods.csv"
],
[
"PRD106",
"Reform era (China)",
"Reform and opening",
"period",
"Time",
"F1.8",
"AS-CHN",
"1978",
"",
"from 1978",
"Economic reform turned coastal China into a centre of export manufacture and revived private craft.",
"mass manufacture",
"electronics;garment",
"exchange and value",
"Chinese historiography",
"migrant workers",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30",
"high",
"links: OCC248.",
"canon_periods.csv"
],
[
"PRD107",
"Imperial reign eras (nianhao) as dating units",
"era names",
"period",
"Time",
"F1.8;THEME",
"AS-CHN;AS-KOR;AS-JPN;AS-MSE",
"-140",
"1912",
"first era name 140 BCE; Chinese use ended 1912; Japan still uses nengō",
"Reign marks such as \"Da Ming Chenghua nian zhi\" date porcelain and other wares, and are copied on later pieces.",
"reign marks",
"porcelain",
"record and writing",
"Chinese, Korean, Vietnamese and Japanese courts",
"makers who copied marks as homage",
"none",
"PeriodO (period gazetteer; link-out); National Palace Museum Taipei Open Data (CC BY 4.0)",
"R2",
"F1.30;F1.14",
"high",
"",
"canon_periods.csv"
],
[
"PRD108",
"Era of Fragmentation (Tibet)",
"sil bu'i dus",
"period",
"Time",
"F1.9",
"AS-HIM",
"842",
"978",
"approx.",
"After the Tibetan empire broke up, monasteries lost royal patronage, and Buddhist making revived later with the \"later spread\".",
"none specific",
"none specific",
"ritual and belief",
"Tibetan Buddhist historiography",
"local Bon and lay traditions the Buddhist frame hides",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"medium",
"links: POL163.",
"canon_periods.csv"
],
[
"PRD109",
"Later spread of Buddhism (Tibet)",
"phyi dar",
"period",
"Time",
"F1.9",
"AS-HIM;AS-SAS",
"978",
"1300",
"approx.; from the late 10th century",
"Monasteries such as Tabo and Alchi were built and painted with help from Kashmiri and Indian craftsmen.",
"mural painting;clay sculpture;metal casting",
"mural;thangka;bronze",
"ritual and belief",
"Tibetan historiography (snga dar/phyi dar)",
"the lay patrons and Kashmiri artists",
"sacred",
"PeriodO (period gazetteer; link-out); Met Open Access (CC0)",
"R3",
"F1.30",
"medium",
"links: POL204; BEL023.",
"canon_periods.csv"
],
[
"PRD110",
"Palaeolithic (Japan)",
"Japanese Palaeolithic; Pre-ceramic",
"period",
"Time",
"F1.8",
"AS-JPN",
"-36000",
"-14000",
"approx.",
"People in Japan made edge-ground stone axes and blade tools, among the earliest ground-stone tools known.",
"edge grinding;blade knapping",
"axe;blade",
"tools",
"Japanese archaeologists",
"the 2000 hoax (Fujimura) that faked older sites",
"none",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"high",
"links: INV148.",
"canon_periods.csv"
],
[
"PRD111",
"Incipient Jōmon",
"Sōsōki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-14000",
"-9000",
"approx.; calibrated dates vary by author",
"Foragers in Japan made small, round- or pointed-based pots with linear-relief and cord decoration, among the oldest known pottery anywhere.",
"coil-built pottery;cord marking",
"cooking pot",
"food and storage",
"Japanese archaeologists; Yamanouchi Sugao's sequence (1937)",
"the separate dates for Hokkaido and the Ryukyus",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30;F1.5",
"medium",
"links: ARC133; INV021.",
"canon_periods.csv"
],
[
"PRD112",
"Initial Jōmon",
"Sōki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-9000",
"-5000",
"approx.",
"More settled communities made pointed-base cord-marked pots for boiling and left the first large shell middens.",
"cord-marked pottery;shell collecting",
"cooking pot;shell midden",
"food and storage",
"Japanese archaeologists; Yamanouchi Sugao (1937)",
"variation between regional pottery types",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"medium",
"links: ARC133.",
"canon_periods.csv"
],
[
"PRD113",
"Early Jōmon",
"Zenki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-5000",
"-3500",
"approx.",
"Red lacquered combs and bowls from wet sites such as Torihama show lacquer use, alongside flat-based pots and plant-fibre cordage.",
"lacquer;pottery;cordage",
"lacquered comb;bowl",
"clothing and adornment;food and storage",
"Japanese archaeologists; Yamanouchi Sugao (1937)",
"the women potters inferred but rarely named in accounts",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"medium",
"links: INV030.",
"canon_periods.csv"
],
[
"PRD114",
"Middle Jōmon",
"Chūki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-3500",
"-2500",
"approx.",
"Large villages such as Sannai-Maruyama built large timber buildings and made clay figurines, while flame-rimmed pots were made in the Shinano River basin.",
"coil-built pottery;figurine modelling;timber building",
"flame-style pot;dogū",
"ritual and belief;food and storage",
"Japanese archaeologists; Yamanouchi Sugao (1937)",
"the modern nationalist use of Jōmon as \"original Japanese\"",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Japan Search",
"R2",
"F1.30;F1.3",
"medium",
"",
"canon_periods.csv"
],
[
"PRD115",
"Late Jōmon",
"Kōki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-2500",
"-1300",
"approx.",
"Communities built stone circles in the north and made finer lacquered wares, earplugs and spouted vessels.",
"stone setting;lacquer;fine pottery",
"stone circle;earplug;spouted vessel",
"ritual and belief;clothing and adornment",
"Japanese archaeologists; Yamanouchi Sugao (1937)",
"the Ainu link to northern Jōmon descendants",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD116",
"Final Jōmon",
"Banki",
"period",
"Time",
"F1.8",
"AS-JPN",
"-1300",
"-900",
"approx.; lasts later in northern Japan",
"The Kamegaoka culture of northern Japan made goggle-eyed figurines and fine lacquered pottery as rice farming began in Kyushu.",
"lacquer;pottery;figurine modelling",
"shakōki dogū;lacquered pot",
"ritual and belief",
"Japanese archaeologists; Yamanouchi Sugao (1937)",
"its overlap with early Yayoi in western Japan",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Japan Search",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD117",
"Yayoi period",
"Yayoi jidai",
"period",
"Time",
"F1.8",
"AS-JPN;AS-KOR",
"-900",
"250",
"start revised to c. 1000–900 BCE by AMS dating (National Museum of Japanese History, 2003); older texts say c. 300 BCE",
"Rice farming, bronze bells and mirrors, iron tools and wheel-less red pottery arrived with migrants from the Korean peninsula.",
"wet-rice farming;bronze casting;iron forging;weaving",
"dōtaku bell;mirror;pottery",
"food and storage;ritual and belief",
"Japanese historiography (named after the Yayoi-chō site in Tokyo, 1884)",
"the Jōmon people of the north who kept foraging, and the Korean origin of many techniques",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.30;F1.13",
"high",
"links: ARC134; ARC131.",
"canon_periods.csv"
],
[
"PRD118",
"Kofun period",
"Kofun jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"250",
"538",
"approx.; some end it at 710",
"Rulers were buried in keyhole-shaped mounds ringed with haniwa figures and filled with iron armour, mirrors and stoneware made with Korean techniques.",
"haniwa modelling;Sue stoneware;iron armour",
"haniwa;armour;mirror",
"ritual and belief;war",
"Japanese historiography",
"the Korean immigrant makers (toraijin) who brought many techniques",
"funerary",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.30;F1.13",
"high",
"links: ARC135; POL178.",
"canon_periods.csv"
],
[
"PRD119",
"Asuka period",
"Asuka jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"538",
"710",
"approx.",
"Buddhism and Korean and Chinese builders brought temple architecture, gilt-bronze images and roof tiles to the Yamato court.",
"temple carpentry;gilt bronze;roof tile",
"temple;Buddha image",
"ritual and belief;shelter",
"Japanese historiography (after the Asuka capital)",
"the Baekje craftsmen credited only as a group",
"sacred",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"high",
"links: OCC021.",
"canon_periods.csv"
],
[
"PRD120",
"Nara period",
"Nara jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"710",
"794",
"conventional",
"The court at Heijō-kyō cast the Great Buddha of Tōdai-ji and stored imported and local treasures in the Shōsōin.",
"bronze casting;lacquer;dry-lacquer sculpture",
"Great Buddha;Shōsōin treasure",
"ritual and belief;rule and display",
"Japanese historiography",
"the corvée labourers who cast the Great Buddha",
"human-flow;sacred",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R2",
"F1.30",
"high",
"links: POL179.",
"canon_periods.csv"
],
[
"PRD121",
"Heian period",
"Heian jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"794",
"1185",
"conventional",
"The Kyoto court made kana calligraphy, narrative handscrolls, lacquer with maki-e and Pure Land temples such as the Byōdō-in.",
"maki-e lacquer;kana calligraphy;yamato-e painting",
"handscroll;lacquer box;temple",
"record and writing;rule and display",
"Japanese historiography",
"provincial and non-aristocratic life",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: POL180; STY145; OCC028.",
"canon_periods.csv"
],
[
"PRD122",
"Kamakura period",
"Kamakura jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1185",
"1333",
"conventional; start variously 1185 or 1192",
"The shogunate's era saw Kei school sculpture, Zen temple building and Seto glazed stoneware.",
"joined-block sculpture;Zen carpentry;glazed stoneware",
"Buddhist image;temple;jar",
"ritual and belief",
"Japanese historiography",
"the imperial court in Kyoto",
"sacred",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"high",
"links: POL181; SCH039.",
"canon_periods.csv"
],
[
"PRD123",
"Muromachi period",
"Muromachi jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1336",
"1573",
"conventional",
"Ashikaga patronage supported ink painting, Noh masks, the tea ceremony and trade with Ming China.",
"ink painting;mask carving;tea utensils",
"Noh mask;tea bowl",
"ritual and belief;play and music",
"Japanese historiography",
"the rural and Ryukyuan worlds",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: POL182; STY146.",
"canon_periods.csv"
],
[
"PRD124",
"Sengoku period",
"Warring States period (Japan)",
"period",
"Time",
"F1.8",
"AS-JPN",
"1467",
"1568",
"approx.; end dated 1568, 1590 or 1615",
"Constant war brought castle building, mass production of guns after 1543 and armour for foot soldiers.",
"castle building;gunsmithing;armour",
"castle;matchlock;armour",
"war",
"Japanese historiography",
"the people displaced by war",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30",
"high",
"links: OCC047; OCC061.",
"canon_periods.csv"
],
[
"PRD125",
"Azuchi–Momoyama period",
"Momoyama",
"period",
"Time",
"F1.8",
"AS-JPN",
"1568",
"1600",
"conventional; sometimes to 1615",
"Nobunaga and Hideyoshi commissioned gold-leaf screens, castles and tea wares.",
"gold-leaf painting;castle building;tea ware",
"folding screen;tea bowl",
"rule and display",
"Japanese historiography",
"the Korean potters brought by force",
"human-flow",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0)",
"R2",
"F1.30",
"high",
"links: DYN070; SCH040; OCC071.",
"canon_periods.csv"
],
[
"PRD126",
"Edo period",
"Tokugawa period",
"period",
"Time",
"F1.8",
"AS-JPN",
"1603",
"1868",
"conventional",
"Under Tokugawa rule, urban markets supported woodblock prints, textiles, lacquer and porcelain for domestic and export buyers.",
"woodblock printing;yūzen dyeing;porcelain",
"print;kimono;Imari",
"clothing and adornment;exchange and value",
"Japanese historiography",
"the Ainu, Ryukyuans and outcaste groups (burakumin) who did leather and other crafts",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0); Art Institute of Chicago (CC0 public-domain works)",
"R1",
"F1.30",
"high",
"links: POL183; DYN071; STY148.",
"canon_periods.csv"
],
[
"PRD127",
"Meiji period",
"Meiji jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1868",
"1912",
"era name of Emperor Meiji",
"The Meiji state industrialised, sent crafts to world's fairs, founded art schools and museums, and redirected sword and temple makers to export goods.",
"export metalwork;cloisonné;silk reeling",
"cloisonné;export porcelain;silk",
"exchange and value;rule and display",
"Japanese historiography (imperial era names)",
"the Ainu and Ryukyuans absorbed by the state, and the women in silk mills",
"none",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms); Met Open Access (CC0); NDL Digital Collections (public-domain items)",
"R2",
"F1.30;F1.19",
"high",
"links: POL185; OCC156; INS026.",
"canon_periods.csv"
],
[
"PRD128",
"Taishō period",
"Taishō jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1912",
"1926",
"era name",
"Urban consumer culture brought department stores, modern design, sōsaku-hanga prints and the start of the Mingei circle.",
"woodblock printing;graphic design",
"print;poster;kimono",
"clothing and adornment;rule and display",
"Japanese historiography",
"colonised Korea and Taiwan, whose makers served the empire",
"none",
"PeriodO (period gazetteer; link-out); NDL Digital Collections (public-domain items)",
"R3",
"F1.30",
"high",
"links: MOV094; MOV095.",
"canon_periods.csv"
],
[
"PRD129",
"Shōwa period",
"Shōwa jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1926",
"1989",
"era name",
"The era runs from militarism and war through occupation to the post-war boom in cameras, electronics and cars and the Living National Treasures system.",
"electronics;automotive manufacture;craft designation",
"camera;radio;car",
"tools;transport",
"Japanese historiography",
"the wartime forced labour of Koreans and Chinese",
"human-flow",
"PeriodO (period gazetteer; link-out); NDL Digital Collections (public-domain items)",
"R3",
"F1.30",
"high",
"links: INS028; INS029; MOV096.",
"canon_periods.csv"
],
[
"PRD130",
"Epi-Jōmon (Hokkaido)",
"Zoku-Jōmon",
"period",
"Time",
"F1.8",
"AS-JPN",
"-300",
"700",
"approx.",
"Hokkaido foragers kept making cord-marked pottery while rice farming spread in the south.",
"cord-marked pottery;fishing",
"pottery",
"food and storage",
"Japanese archaeologists",
"the ancestors of the Ainu",
"Indigenous-community",
"PeriodO (period gazetteer; link-out); open-access excavation reports",
"R3",
"F1.30",
"medium",
"links: ARC136; ARC114.",
"canon_periods.csv"
],
[
"PRD131",
"Ainu culture period",
"Ainu bunka ki",
"period",
"Time",
"F1.8;F1.12a",
"AS-JPN;AS-NTH",
"1200",
"1868",
"approx.",
"Ainu made elm-bark cloth (attus), appliqué robes and ritual inau carvings, and traded with Japanese and the Amur region.",
"elm-bark weaving;appliqué;woodcarving",
"attus robe;inau;ikupasuy",
"clothing and adornment;ritual and belief",
"Japanese archaeologists; Ainu communities",
"the Ainu present, which \"period\" can hide",
"Indigenous-community;living-community",
"PeriodO (period gazetteer; link-out); ColBase (Japan Government Standard Terms)",
"R3",
"F1.30;F1.3",
"medium",
"Label contested; Ainu culture continues today.",
"canon_periods.csv"
],
[
"PRD132",
"Gusuku period",
"Gusuku jidai",
"period",
"Time",
"F1.8",
"AS-JPN",
"1100",
"1429",
"approx.",
"Local lords in Okinawa built stone gusuku fortresses and traded with China, leading to the Ryukyu Kingdom.",
"stone walling;trade",
"gusuku",
"shelter;war",
"Okinawan historiography",
"the commoners and the northern Amami islands",
"none",
"PeriodO (period gazetteer; link-out); Wikimedia Commons",
"R3",
"F1.30",
"medium",
"links: POL184.",
"canon_periods.csv"
],
[
"PRD133",
"Gojoseon (contested period)",
"Old Joseon",
"period",
"Time",
"F1.8",
"AS-KOR;AS-CHN",
"-2333",
"-108",
"traditional founding 2333 BCE from later texts; historical from c. 4th century BCE",
"Korean tradition dates Gojoseon's founding to 2333 BCE, while archaeology links the later state with mandolin-shaped bronze daggers and dolmens.",
"bronze casting;dolmen building",
"mandolin-shaped dagger;dolmen",
"war;ritual and belief",
"Korean traditional historiography (Samguk yusa, 1280s)",
"the many non-Gojoseon groups on the peninsula",
"none",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons",
"R3",
"F1.30;F1.3",
"medium",
"Contested; links: ARC132.",
"canon_periods.csv"
],
[
"PRD134",
"Proto-Three Kingdoms period",
"Samhan period",
"period",
"Time",
"F1.8",
"AS-KOR",
"-100",
"300",
"approx.",
"Iron production in the south of Korea supplied iron ingots and armour traded to Japan.",
"iron smelting;pottery",
"iron ingot;pottery",
"tools;exchange and value",
"Korean archaeologists",
"the chiefdoms not named in Chinese texts",
"none",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons",
"R3",
"F1.30",
"medium",
"",
"canon_periods.csv"
],
[
"PRD135",
"Three Kingdoms period (Korea)",
"Samguk sidae",
"period",
"Time",
"F1.8",
"AS-KOR",
"-57",
"668",
"traditional founding dates from the Samguk sagi (1145)",
"Goguryeo, Baekje and Silla (with Gaya) made tomb murals, gold crowns and Buddhist sculpture, and sent craftsmen to Japan.",
"goldsmithing;tomb painting;stoneware",
"gold crown;mural;gilt-bronze Buddha",
"ritual and belief;rule and display",
"Korean historiography (Samguk sagi)",
"Gaya, left out of \"three\"",
"funerary",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons; Korean national e-museum (KOGL Type 1 items only)",
"R2",
"F1.30;F1.3",
"high",
"links: POL172; POL173; POL174.",
"canon_periods.csv"
],
[
"PRD136",
"Unified Silla period",
"Tongil Silla",
"period",
"Time",
"F1.8",
"AS-KOR",
"668",
"935",
"conventional",
"Unified Silla built the Seokguram grotto and Bulguksa temple and cast large bronze bells such as the Divine Bell of King Seongdeok.",
"stone carving;bell casting",
"bell;grotto sculpture",
"ritual and belief",
"Korean historiography",
"Balhae in the north, which the term sets aside",
"sacred",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons",
"R3",
"F1.30;F1.3",
"high",
"links: POL174.",
"canon_periods.csv"
],
[
"PRD137",
"North–South States period",
"Nambukguk sidae",
"period",
"Time",
"F1.8",
"AS-KOR;AS-CHN;AS-NTH",
"698",
"926",
"alternative to \"Unified Silla\"",
"The label pairs Silla with Balhae in Manchuria, whose Buddhist and tile work is otherwise left out of Korean history.",
"roof tiles;Buddhist sculpture",
"roof tile",
"shelter;ritual and belief",
"Korean historians (after Yu Deuk-gong, 1784)",
"the Chinese and Russian claims to Balhae",
"none",
"PeriodO (period gazetteer; link-out)",
"R3",
"F1.30;F1.3",
"medium",
"links: POL175.",
"canon_periods.csv"
],
[
"PRD138",
"Goryeo period",
"Goryeo sidae",
"period",
"Time",
"F1.8",
"AS-KOR",
"918",
"1392",
"conventional",
"Goryeo potters made inlaid celadon, and printers carved the Tripitaka Koreana and cast metal type.",
"inlaid celadon;woodblock carving;metal type",
"celadon;Tripitaka block;book",
"ritual and belief;record and writing",
"Korean historiography",
"the Mongol overlordship's share",
"none",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons; Korean national e-museum (KOGL Type 1 items only)",
"R2",
"F1.30",
"high",
"links: POL176; STY139; INV042; TXT108.",
"canon_periods.csv"
],
[
"PRD139",
"Joseon period",
"Joseon sidae",
"period",
"Time",
"F1.8",
"AS-KOR",
"1392",
"1897",
"conventional",
"Joseon court workshops made white porcelain and buncheong ware, state painters recorded rituals in uigwe, and Hangul was created.",
"white porcelain;buncheong;uigwe painting",
"porcelain;screen;uigwe",
"record and writing;rule and display",
"Korean historiography",
"the lowborn (cheonmin) artisans and slaves (nobi)",
"human-flow",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons; Korean national e-museum (KOGL Type 1 items only); Kyujanggak / Uigwe (link-out)",
"R2",
"F1.30",
"high",
"links: POL177; STY140; STY141; INS024.",
"canon_periods.csv"
],
[
"PRD140",
"Japanese colonial period (Korea)",
"Iljeu sidae",
"period",
"Time",
"F1.8",
"AS-KOR;AS-JPN",
"1910",
"1945",
"conventional",
"Colonial rule set up industrial exhibitions, museums and Korean craft revivals under Japanese direction, while taking many artworks to Japan.",
"export craft;conservation",
"celadon replica;lacquer",
"rule and display",
"Korean historiography",
"Korean agency within colonial structures",
"human-flow;conflict-looting",
"PeriodO (period gazetteer; link-out); KOGL Type 1 images on Wikimedia Commons",
"R3",
"F1.30;F1.24",
"high",
"links: EVT011.",
"canon_periods.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
