insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PLC024",
"Chouara tannery",
"Fez, Morocco",
"place",
"Place",
"F1.10",
"AF-MAG",
"1100",
"",
"approx.; tanneries attested for centuries, founding date uncertain; ongoing",
"The dye and tanning pits of the Fez medina process hides into leather by hand, a working district tied to the city's craft guilds.",
"tanning;natural dyeing;leather working",
"site type: tannery;leather;babouche",
"clothing and adornment",
"the guilds; historians",
"tannery workers' health and wages",
"living-community",
"Wikimedia Commons;community-published site (link-out)",
"R2",
"F1.22a;F1.23",
"medium",
"links: MKR014. Founding date to verify.",
"canon_places.csv"
],
[
"PLC025",
"Sijilmasa",
"Rissani, Tafilalt, Morocco",
"place",
"Place",
"F1.10;F1.13",
"AF-MAG",
"757",
"1400",
"founded c. 757; declined 14th c.",
"Sijilmasa was the northern Saharan terminus of the gold trade and minted gold dinars from West African gold.",
"coin minting;gold refining;mud brick",
"site type: caravan city and mint;dinar",
"exchange and value",
"historians; archaeologists (Moroccan-American project)",
"enslaved people carried north by the same caravans",
"human-flow",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13",
"high",
"links: NET010.",
"canon_places.csv"
],
[
"PLC026",
"Mogador",
"Essaouira island, Morocco",
"place",
"Place",
"F1.6;F1.11",
"AF-MAG",
"-650",
"50",
"approx.; Phoenician outpost 7th-6th c. BCE; dye works under Juba II",
"The island was a Phoenician trading post and later a dye works associated with the Gaetulian purple mentioned by Pliny.",
"murex dyeing;trade",
"site type: island trading post;amphora;dye works",
"exchange and value;clothing and adornment",
"archaeologists; Pliny the Elder",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.18;F1.13",
"medium",
"Link between the island and Juba II's purple dye works to verify.",
"canon_places.csv"
],
[
"PLC027",
"Timbuktu",
"Tombouctou, Mali",
"place",
"Place",
"F1.6;F1.10;F1.13",
"AF-SAH",
"1100",
"",
"founded c. 1100; ongoing",
"Timbuktu's mosques and family libraries hold manuscripts copied, bound and traded in the city, which was also a market for salt, gold and books.",
"manuscript copying;leather binding;earthen architecture",
"site type: trading city and manuscript centre;manuscript;binding;mosque",
"record and writing;exchange and value",
"scholars; the families holding libraries",
"enslaved and servile workers in the trans-Saharan trade; the 2012 destruction of mausoleums",
"sacred;conflict-looting;human-flow",
"Wikimedia Commons;community-published site (link-out)",
"R1",
"F1.13;F1.28;F1.19a",
"high",
"links: MKR010; POL036; POL037. Manuscripts were evacuated to Bamako in 2012-13.",
"canon_places.csv"
],
[
"PLC028",
"Djenné",
"Djenné, Mali",
"place",
"Place",
"F1.6;F1.10",
"AF-SAH",
"1200",
"",
"town from c. 13th c.; Great Mosque rebuilt 1907; ongoing",
"The barey masons' corporation leads the yearly replastering of the Great Mosque in mud, a collective building practice in a trading town of the inland Niger Delta.",
"earthen architecture;mud plaster;toron timbers",
"site type: town, mosque and masons' quarter;mud-brick building",
"shelter;ritual and belief",
"the barey masons; UNESCO",
"women and youths who carry water and plaster",
"sacred;living-community",
"Wikimedia Commons;community-published site (link-out)",
"R1",
"F1.29;F1.22a",
"high",
"links: ARC031.",
"canon_places.csv"
],
[
"PLC029",
"Djenné-Djeno",
"Jenne-jeno, Mali",
"place",
"Place",
"F1.6",
"AF-SAH",
"-250",
"1400",
"approx.; c. 250 BCE-1400 CE",
"Excavations found an urban cluster with iron-working, potting and imported glass beads that predates the trans-Saharan caravan trade.",
"iron smelting;pottery;terracotta;glass beads",
"site type: urban tell;terracotta figure;bead;pottery",
"exchange and value;tools",
"archaeologists (Susan and Roderick McIntosh)",
"the looting of Inland Niger Delta terracottas for the art market",
"conflict-looting",
"open-access excavation reports;Wikimedia Commons",
"R2",
"F1.24;F1.5",
"high",
"links: ARC031; ARC032; INV131.",
"canon_places.csv"
],
[
"PLC030",
"Gao",
"Gao, Mali",
"place",
"Place",
"F1.6;F1.10",
"AF-SAH",
"700",
"",
"approx.; Gao-Saney 7th-10th c.; Songhay capital 15th-16th c.",
"Gao was a Niger River market whose royal cemetery had inscribed marble stelae imported from al-Andalus, and later the capital of Songhay.",
"marble carving;glass beads;earthen architecture",
"site type: river market and capital;tombstone;bead;tomb",
"exchange and value;ritual and belief",
"archaeologists; historians",
"",
"funerary;sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: POL037. Almería origin of the stelae to verify.",
"canon_places.csv"
],
[
"PLC031",
"Essouk-Tadmekka",
"Essouk, Kidal, Mali",
"place",
"Place",
"F1.6;F1.13",
"AF-SAH",
"800",
"1400",
"approx.",
"Excavations found clay coin moulds of about the 11th century, evidence that gold was cast into coin blanks inside the Sahara.",
"gold casting;clay moulds",
"site type: caravan town;coin mould;crucible",
"exchange and value",
"archaeologists (Sam Nixon)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"",
"canon_places.csv"
],
[
"PLC032",
"Taghaza",
"Taghaza, northern Mali",
"place",
"Place",
"F1.6;F1.10",
"AF-SAH",
"1000",
"1585",
"approx.; described 1352; abandoned after 1585",
"Ibn Battuta described Taghaza in 1352 as a salt-mining town built of salt blocks, where the salt was cut by enslaved workers.",
"rock-salt quarrying",
"site type: salt mine;salt slab",
"exchange and value;food and storage",
"Ibn Battuta; historians",
"the enslaved miners",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23;F1.28",
"medium",
"",
"canon_places.csv"
],
[
"PLC033",
"Kofar Mata dye pits",
"Kano, Nigeria",
"place",
"Place",
"F1.6;F1.10",
"AF-SAH",
"1498",
"",
"tradition dates the pits to the late 15th c.; ongoing",
"Dyers work indigo in cement-lined pits at Kofar Mata, a surviving part of the dyeing industry that made Kano's cloth known across the Sahel.",
"indigo dyeing;resist dyeing",
"site type: dye pits;indigo cloth;turban",
"clothing and adornment;exchange and value",
"the dyers; historians",
"",
"living-community",
"Wikimedia Commons;community-published site (link-out)",
"R2",
"F1.18",
"medium",
"links: MKR006 (maker-community node for the same dyers; merge or keep as place). Founding date to verify.",
"canon_places.csv"
],
[
"PLC034",
"Masaga glass quarter",
"Bida, Niger State, Nigeria",
"place",
"Place",
"F1.6",
"AF-SAH;AF-GUI",
"1850",
"",
"approx.; Nupe capital founded 1850s; ongoing",
"Glassmakers of the Masaga quarter make bangles and beads by remelting recycled glass, a craft the guild links to Nupe history.",
"glass remelting;bead making",
"site type: craft quarter;glass bangle;bead",
"clothing and adornment",
"the guild; ethnographers (S. F. Nadel)",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"Earlier origins claimed; to verify.",
"canon_places.csv"
],
[
"PLC035",
"Gorée",
"Île de Gorée, Dakar, Senegal",
"place",
"Place",
"F1.6;F1.13",
"AF-SAH",
"1444",
"",
"European trading post from 15th c.; memorial site",
"Gorée was a European trading post in the Atlantic trade in enslaved Africans and is now a memorial whose House of Slaves is central to debates about how that trade is presented.",
"stone and lime building",
"site type: island trading post and memorial;building",
"exchange and value",
"UNESCO; the Senegalese state; historians",
"the scale of embarkations from Gorée is debated",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.24;F1.3",
"high",
"links: NET035.",
"canon_places.csv"
],
[
"PLC036",
"Museum of Black Civilisations",
"Musée des Civilisations noires, Dakar, Senegal",
"place",
"Place",
"F1.6;THEME",
"AF-SAH",
"2018",
"",
"opened December 2018",
"The museum, first proposed at the 1966 Dakar festival, presents African and diaspora histories and receives returned objects.",
"museum display",
"site type: museum;sculpture;textile",
"rule and display",
"the Senegalese state",
"",
"none",
"collection search link-out only",
"R3",
"F1.24",
"high",
"links: INS083; EVT022. Place node for the building; merge with INS083 if preferred.",
"canon_places.csv"
],
[
"PLC037",
"Igun Street",
"Igun Eronmwon quarter, Benin City, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1300",
"",
"approx.; oral history dates the guild to the 13th-14th c.; ongoing",
"Igun Street is the hereditary quarter of the Benin brass-casters' guild, where lost-wax casting for the Oba's court continues.",
"lost-wax casting;brass;clay core",
"site type: craft street;commemorative head;plaque;bell",
"rule and display;ritual and belief",
"the guild; the Oba's court",
"apprentices; women's work in the households",
"living-community;ancestral",
"community-published site (link-out);collection search link-out only",
"R1",
"F1.17;F1.24",
"high",
"links: MKR001; POL026.",
"canon_places.csv"
],
[
"PLC038",
"Oba's Palace, Benin City",
"Ogbe; Benin City, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1300",
"",
"approx.; ongoing",
"The royal palace commissioned Benin's brass plaques, ivories and altar objects and was sacked by the British punitive expedition in February 1897.",
"brass casting;ivory carving;earthen architecture",
"site type: royal palace and altar complex;plaque;carved tusk;altar",
"rule and display;ritual and belief",
"the Oba; historians",
"",
"conflict-looting;sacred;ancestral;living-community",
"collection search link-out only;community-published site (link-out)",
"R1",
"F1.24;F1.19a",
"high",
"links: CIV012; POL026; INS082.",
"canon_places.csv"
],
[
"PLC039",
"National Museum, Benin City",
"Benin City, Nigeria",
"place",
"Place",
"F1.6;THEME",
"AF-GUI",
"1973",
"",
"present building opened 1973; a museum was first set up in 1946",
"The museum holds Benin castings left in Nigeria or bought back and is one of the places where returned objects are discussed.",
"museum display",
"site type: museum;brass casting;ivory",
"rule and display",
"the National Commission for Museums and Monuments",
"",
"ancestral",
"collection search link-out only",
"R3",
"F1.24",
"medium",
"Opened to the public 1973 (Wikipedia; Nigerian Observer 2022); 1946 origin from a single press source.",
"canon_places.csv"
],
[
"PLC040",
"National Museum, Lagos",
"Onikan, Lagos, Nigeria",
"place",
"Place",
"F1.6;THEME",
"AF-GUI",
"1957",
"",
"opened 1957",
"The museum, founded by Kenneth Murray, holds Nok, Ife, Igbo-Ukwu and Benin works and shaped how Nigerian antiquities were catalogued and displayed.",
"museum display",
"site type: museum;terracotta;brass casting",
"rule and display",
"the Nigerian Antiquities Service (Kenneth Murray; Bernard Fagg)",
"the excavators and communities from whom objects came",
"none",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC041",
"Wunmonije Compound",
"Ile-Ife, Osun State, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1200",
"1450",
"approx.; heads found 1938",
"Builders digging in the compound in 1938 found the copper-alloy Ife heads that changed European ideas of African casting.",
"copper-alloy casting;lost-wax casting",
"site type: find site near the palace;cast head",
"rule and display;ritual and belief",
"archaeologists; the Ooni's palace",
"the export of some heads in 1938-39",
"sacred;conflict-looting",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24;F1.3",
"high",
"links: CIV011; POL027. Some heads left Nigeria via William Bascom; verify.",
"canon_places.csv"
],
[
"PLC042",
"Igbo Olokun",
"Olokun Grove, Ile-Ife, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1000",
"1500",
"approx.; 11th-15th c.",
"Crucible fragments and beads show that high-lime, high-alumina glass was made here from local materials, a primary glass industry in West Africa.",
"primary glassmaking;crucible;bead making",
"site type: glass workshop;glass bead;crucible",
"clothing and adornment;exchange and value",
"archaeologists (Babalola et al.)",
"",
"sacred",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"links: INV028.",
"canon_places.csv"
],
[
"PLC043",
"Igbo-Ukwu",
"Igbo Isaiah, Igbo Richard and Igbo Jonah, Anambra State, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"800",
"1000",
"approx.; 9th-10th c.",
"Leaded-bronze castings with fine lost-wax detail, glass beads and a richly furnished burial were excavated at three compounds.",
"leaded bronze;lost-wax casting;glass beads",
"site type: excavated compounds and burial;vessel;regalia;bead",
"ritual and belief;rule and display",
"archaeologists (Thurstan Shaw)",
"",
"funerary;sacred",
"open-access excavation reports;Wikimedia Commons;collection search link-out only",
"R2",
"F1.5",
"high",
"links: ARC034.",
"canon_places.csv"
],
[
"PLC044",
"Taruga",
"Taruga, near Abuja, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"-600",
"1",
"approx.",
"Taruga's furnaces are among the earliest dated iron-smelting sites in West Africa, in the region whose Nok terracottas are heavily looted.",
"iron smelting;terracotta",
"site type: iron-smelting site and settlement;furnace;terracotta figure",
"tools;ritual and belief",
"archaeologists (Bernard Fagg; Goethe University Frankfurt Nok project)",
"the looting of Nok terracottas",
"conflict-looting",
"open-access excavation reports;collection search link-out only",
"R2",
"F1.5;F1.24",
"medium",
"links: ARC028; CIV006; INV087.",
"canon_places.csv"
],
[
"PLC045",
"Jos Plateau tin fields",
"Jos Plateau, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1904",
"",
"colonial tin mining from 1900s",
"Colonial tin mining exposed the first known Nok terracottas (1928, and more from 1943), and during the Second World War the colonial state imposed forced labour on the mines.",
"tin mining;alluvial mining",
"site type: mining district;tin;terracotta find",
"exchange and value",
"colonial companies; historians",
"conscripted mine workers",
"human-flow",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.22;F1.23",
"medium",
"links: ARC028. Wartime forced labour: Freund, J. African History (labour migration to the tin mines 1903-1945).",
"canon_places.csv"
],
[
"PLC046",
"Bonwire",
"Bonwire, Ashanti Region, Ghana",
"place",
"Place",
"F1.6",
"AF-GUI",
"1700",
"",
"approx.; ongoing",
"Bonwire's weavers make strip-woven kente on narrow looms, with named patterns once reserved for the Asante court.",
"narrow-strip loom;silk;cotton;supplementary weft",
"site type: weaving village;kente cloth",
"clothing and adornment;rule and display",
"the weavers; the Asantehene's court",
"women spinners and traders; printed kente copies",
"living-community",
"Met Open Access (CC0);community-published site (link-out)",
"R2",
"F1.18;F1.14",
"high",
"links: MKR003; PRA002.",
"canon_places.csv"
],
[
"PLC047",
"Kumasi",
"Manhyia, Kumasi, Ghana",
"place",
"Place",
"F1.6",
"AF-GUI",
"1700",
"",
"approx.; Asante capital from c. 1700",
"The Asante capital commissioned goldwork, cast brass goldweights and regalia, and was looted by British forces in 1874 and again in 1896-1900.",
"goldworking;lost-wax casting;brass",
"site type: royal capital;goldweight;regalia;stool",
"rule and display;exchange and value",
"the Asantehene; historians",
"",
"conflict-looting;ancestral",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: POL029.",
"canon_places.csv"
],
[
"PLC048",
"Elmina Castle",
"São Jorge da Mina, Elmina, Ghana",
"place",
"Place",
"F1.6;F1.13",
"AF-GUI",
"1482",
"1872",
"Portuguese 1482; Dutch 1637-1872",
"The castle was a Portuguese and then Dutch trading fort for gold and, increasingly, for enslaved Africans held in its dungeons.",
"stone construction;trade goods",
"site type: trading fort and dungeon;manilla;cloth",
"exchange and value;war",
"UNESCO; the Ghanaian state; historians",
"",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13;F1.24",
"high",
"links: NET035.",
"canon_places.csv"
],
[
"PLC049",
"Ouidah",
"Glexwe; Ouidah, Benin",
"place",
"Place",
"F1.6;F1.13",
"AF-GUI",
"1670",
"1860",
"approx.",
"Ouidah was a principal port of the Atlantic slave trade from the Bight of Benin and today has a memorial route to the beach.",
"trade goods;cowries",
"site type: port and memorial route;cowrie;cloth",
"exchange and value",
"historians; the Beninese state",
"",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13;F1.24",
"high",
"links: POL030; NET035.",
"canon_places.csv"
],
[
"PLC050",
"Abomey Royal Palaces",
"Abomey, Zou, Benin",
"place",
"Place",
"F1.6",
"AF-GUI",
"1645",
"1894",
"approx.",
"The Dahomey palaces had appliqué workshops and painted clay reliefs, and French troops took royal objects in 1892, 26 of which were returned in 2021.",
"appliqué;earthen relief;brass casting",
"site type: royal palace complex;appliqué hanging;throne;relief",
"rule and display;ritual and belief",
"the kings of Dahomey; UNESCO",
"",
"conflict-looting;sacred",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: POL030; MKR005.",
"canon_places.csv"
],
[
"PLC051",
"Krobo bead-making",
"Odumase-Krobo, Eastern Region, Ghana",
"place",
"Place",
"F1.6",
"AF-GUI",
"1900",
"",
"approx.; ongoing",
"Krobo bead-makers fire powdered recycled glass in clay moulds to make beads worn at the dipo rite and sold at markets.",
"powder-glass bead making;clay moulds",
"site type: bead workshops and market;glass bead",
"clothing and adornment;ritual and belief",
"the bead-makers",
"",
"living-community",
"Wikimedia Commons;community-published site (link-out)",
"R3",
"F1.29;F1.22a",
"medium",
"Start date approximate.",
"canon_places.csv"
],
[
"PLC052",
"Osun-Osogbo Sacred Grove",
"Osogbo, Osun State, Nigeria",
"place",
"Place",
"F1.6",
"AF-GUI",
"1950",
"",
"grove old; New Sacred Art from 1950s",
"The grove's shrines were rebuilt from the 1950s by Susanne Wenger and local artists of the New Sacred Art, and it is still the site of the annual Osun festival.",
"earthen and cement sculpture;shrine building",
"site type: sacred grove;shrine sculpture",
"ritual and belief",
"Osun devotees; Susanne Wenger and collaborators; UNESCO",
"the Yoruba artists whose work is credited to Wenger",
"sacred;living-community",
"Wikimedia Commons;community-published site (link-out)",
"R3",
"F1.16;F1.26",
"high",
"",
"canon_places.csv"
],
[
"PLC053",
"Bunce Island",
"Sierra Leone River",
"place",
"Place",
"F1.6;F1.13",
"AF-GUI",
"1670",
"1807",
"approx.",
"British traders held captives at Bunce Island's fort before shipping them to the Americas, including rice-growing Carolina and Georgia.",
"stone construction;trade goods",
"site type: slave-trading fort;ruins",
"exchange and value",
"historians",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: NET035.",
"canon_places.csv"
],
[
"PLC054",
"Mbanza Kongo",
"São Salvador, Zaire province, Angola",
"place",
"Place",
"F1.6",
"AF-CEN",
"1390",
"",
"approx.; capital from late 14th c.",
"The Kongo capital commissioned raffia cloth, ivory and brass crucifixes, and its links with Portugal also fed the slave trade.",
"raffia weaving;ivory carving;brass casting",
"site type: royal capital;raffia cloth;crucifix",
"rule and display;ritual and belief;exchange and value",
"the Kongo kings; UNESCO",
"captives sold through the capital",
"human-flow",
"Wikimedia Commons;Met Open Access (CC0)",
"R2",
"F1.14",
"high",
"links: POL020; CIV013.",
"canon_places.csv"
],
[
"PLC055",
"Loango Bay",
"Loango, Republic of the Congo",
"place",
"Place",
"F1.6",
"AF-CEN",
"1600",
"1910",
"approx.",
"Loango was a port for enslaved captives and later a centre where carvers made relief-carved ivory tusks for European buyers.",
"ivory carving;trade goods",
"site type: port and carvers' workshops;carved tusk",
"exchange and value",
"historians; museums",
"captives shipped from the coast",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.13;F1.14",
"medium",
"links: POL021.",
"canon_places.csv"
],
[
"PLC056",
"Nsheng",
"Mushenge; Kasai, DR Congo",
"place",
"Place",
"F1.6",
"AF-CEN",
"1625",
"",
"approx.; Kuba capital",
"The Kuba royal capital was the centre for raffia cut-pile and embroidered cloth, carved cups and the ndop king figures.",
"raffia weaving;cut-pile embroidery;wood carving",
"site type: royal capital;raffia cloth;ndop figure;cup",
"rule and display;clothing and adornment",
"the Kuba kings; ethnographers (Emil Torday)",
"women embroiderers",
"living-community",
"Met Open Access (CC0);Wikimedia Commons;collection search link-out only",
"R3",
"F1.18",
"medium",
"links: POL022.",
"canon_places.csv"
],
[
"PLC057",
"Foumban",
"Bamum Palace and Rue des Artisans, Foumban, Cameroon",
"place",
"Place",
"F1.6",
"AF-CEN",
"1394",
"",
"dynasty traditionally from 1394; palace 1917; ongoing",
"Under Sultan Njoya the royal workshops at Foumban made beadwork, brass and carvings, and an artisans' street continues the work.",
"beadwork;lost-wax brass casting;wood carving",
"site type: royal palace and craft street;beaded throne;mask;brass pipe",
"rule and display",
"Sultan Njoya; the Bamum court",
"",
"living-community",
"Wikimedia Commons;collection search link-out only",
"R2",
"F1.17",
"medium",
"links: MKR004; POL025.",
"canon_places.csv"
],
[
"PLC058",
"Ishango",
"Ishango, Virunga, DR Congo",
"place",
"Place",
"F1.6",
"AF-CEN",
"-20000",
"",
"approx.; c. 20,000 BP",
"A notched bone tool found at Ishango in 1950 is one of the best-known early tally-like objects.",
"bone carving;notching",
"site type: lakeside site;notched bone;harpoon",
"record and writing;tools",
"archaeologists (Jean de Heinzelin)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.5",
"medium",
"links: INV011. Interpretations as counting device are debated.",
"canon_places.csv"
],
[
"PLC059",
"Sanga",
"Upemba Depression, Katanga, DR Congo",
"place",
"Place",
"F1.6",
"AF-CEN",
"700",
"1400",
"approx.",
"Kisalian burials at Sanga contained copper cross-ingots, iron and fine pottery, marking a regional copper currency.",
"copper casting;iron;pottery",
"site type: cemetery;copper cross;pottery",
"exchange and value;ritual and belief",
"archaeologists (Jacques Nenquin; Pierre de Maret)",
"",
"funerary",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: ARC038.",
"canon_places.csv"
],
[
"PLC060",
"Union Minière mines of Katanga",
"Élisabethville (Lubumbashi) and Kipushi, DR Congo",
"place",
"Place",
"F1.6;THEME",
"AF-CEN",
"1906",
"1967",
"Union Minière du Haut-Katanga 1906-1967",
"Colonial copper and cobalt mining in Katanga recruited labour by coercion in its early decades and supplied metals for global industry.",
"copper mining;smelting",
"site type: mining district;copper ingot",
"exchange and value",
"colonial companies; historians",
"forcibly recruited miners",
"human-flow",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.22;F1.23",
"medium",
"links: POL140.",
"canon_places.csv"
],
[
"PLC061",
"Royal Museum for Central Africa",
"AfricaMuseum, Tervuren, Belgium",
"place",
"Place",
"F1.11;THEME",
"EU-BLC;AF-CEN",
"1910",
"",
"museum 1910; 1897 colonial exhibition on the site",
"Built as a museum of the Congo Free State, it displayed Congolese objects and, in 1897, Congolese people, and reopened in 2018 after a redesign.",
"museum display",
"site type: museum and former exhibition ground;sculpture;mask",
"rule and display",
"the Belgian state",
"the Congolese people exhibited in 1897, seven of whom died",
"conflict-looting;human-flow",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24;F1.3",
"high",
"links: POL140; NET060.",
"canon_places.csv"
],
[
"PLC062",
"Ingombe Ilede",
"Ingombe Ilede, Southern Province, Zambia",
"place",
"Place",
"F1.6",
"AF-CEN;AF-SOU",
"1300",
"1500",
"approx.; 14th-15th c.",
"Burials here contained copper ingots, gold, glass beads, cloth and wire-drawing tools, linking the Zambezi to Indian Ocean trade.",
"copper casting;wire drawing;cotton cloth",
"site type: settlement and cemetery;copper ingot;wire bangle;bead",
"exchange and value",
"archaeologists (Brian Fagan)",
"",
"funerary",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"",
"canon_places.csv"
],
[
"PLC063",
"Gona",
"Afar Region, Ethiopia",
"place",
"Place",
"F1.6",
"AF-HRN",
"-2600000",
"",
"approx.; c. 2.6 million years",
"Stone tools from Gona, about 2.6 million years old, are among the earliest known Oldowan artefacts.",
"stone knapping",
"site type: open-air archaeological locality;stone core;flake",
"tools",
"palaeoanthropologists (Semaw et al.)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"links: ARC002; INV139.",
"canon_places.csv"
],
[
"PLC064",
"Yeha",
"Tigray, Ethiopia",
"place",
"Place",
"F1.6;F1.9a",
"AF-HRN;WA-ARB",
"-800",
"-300",
"approx.; Great Temple c. 7th c. BCE",
"The Great Temple at Yeha shows ashlar masonry and inscriptions linked to South Arabian building traditions.",
"ashlar masonry;stone carving",
"site type: temple and settlement;inscription;altar",
"ritual and belief",
"archaeologists (DAI)",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"links: ARC021.",
"canon_places.csv"
],
[
"PLC065",
"Aksum",
"Tigray, Ethiopia",
"place",
"Place",
"F1.6",
"AF-HRN",
"1",
"900",
"approx.",
"Aksum's carved granite stelae, coinage and workshops record a Red Sea kingdom, and one stela taken to Rome in 1937 was returned in 2005.",
"granite carving;coin minting",
"site type: royal city and stelae field;stela;coin",
"rule and display;exchange and value",
"archaeologists; UNESCO",
"",
"sacred;conflict-looting",
"Wikimedia Commons;open-access excavation reports;British Museum collection search (link-out)",
"R2",
"F1.24",
"high",
"links: POL006; CIV003.",
"canon_places.csv"
],
[
"PLC066",
"Adulis",
"Zula, Eritrea",
"place",
"Place",
"F1.6;F1.13",
"AF-HRN",
"-100",
"700",
"approx.",
"Adulis was Aksum's Red Sea port, named in the Periplus, where ivory, tortoiseshell and imports passed through.",
"trade goods;glass;pottery",
"site type: port;amphora;glass",
"exchange and value;transport",
"archaeologists; the Periplus of the Erythraean Sea",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: NET032.",
"canon_places.csv"
],
[
"PLC067",
"Lalibela",
"Lalibela, Amhara, Ethiopia",
"place",
"Place",
"F1.6",
"AF-HRN",
"1180",
"",
"approx.; traditionally reign of King Lalibela, c. late 12th-early 13th c.; ongoing",
"Churches carved down into the rock were cut as whole buildings from the living stone and remain in use.",
"rock-cut architecture;wall painting",
"site type: rock-hewn churches;church;cross;manuscript",
"ritual and belief",
"the Ethiopian Orthodox Church; UNESCO",
"",
"sacred;living-community",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"Construction chronology debated.",
"canon_places.csv"
],
[
"PLC068",
"Fasil Ghebbi",
"Gondar, Amhara, Ethiopia",
"place",
"Place",
"F1.6",
"AF-HRN",
"1636",
"1855",
"approx.",
"The Gondar royal enclosure and nearby churches such as Debre Birhan Selassie show court patronage of painting and building.",
"stone masonry;wall painting",
"site type: royal enclosure;castle;mural;manuscript",
"rule and display;ritual and belief",
"the Gondarine kings; UNESCO",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL007.",
"canon_places.csv"
],
[
"PLC069",
"Amba Maqdala",
"Maqdala, Amhara, Ethiopia",
"place",
"Place",
"F1.6",
"AF-HRN",
"1868",
"",
"Emperor Tewodros II's fortress; British assault April 1868",
"British forces took manuscripts, crowns and church objects from Maqdala in 1868, and some are now subject to return requests.",
"manuscripts;metalwork",
"site type: fortress and looting site;manuscript;crown;tabot",
"rule and display;ritual and belief",
"historians; the Ethiopian state",
"",
"conflict-looting;sacred",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24;F1.19a",
"high",
"links: POL007.",
"canon_places.csv"
],
[
"PLC070",
"Harar Jugol",
"Harar, Ethiopia",
"place",
"Place",
"F1.6;F1.10",
"AF-HRN",
"1500",
"",
"walls 16th c.; ongoing",
"The walled city has quarters of basket weavers, bookbinders and painted Harari houses, and a manuscript tradition.",
"basketry;bookbinding;house decoration",
"site type: walled city;basket;manuscript;house interior",
"ritual and belief;shelter",
"the Harari; UNESCO",
"",
"sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_places.csv"
],
[
"PLC071",
"Lomekwi 3",
"West Turkana, Kenya",
"place",
"Place",
"F1.6",
"AF-SWA",
"-3300000",
"",
"approx.; c. 3.3 million years",
"Stone cores and flakes about 3.3 million years old were reported in 2015 as the earliest known stone tools.",
"stone knapping",
"site type: open-air archaeological locality;stone core;flake",
"tools",
"palaeoanthropologists (Harmand et al. 2015)",
"",
"none",
"open-access excavation reports",
"R2",
"F1.5",
"medium",
"links: ARC001; INV139. Dating and deliberate knapping are debated.",
"canon_places.csv"
],
[
"PLC072",
"Olduvai Gorge",
"Oldupai, Ngorongoro, Tanzania",
"place",
"Place",
"F1.6",
"AF-SWA",
"-2000000",
"",
"approx.; Oldowan c. 2.0 million years; Acheulean from c. 1.7 million years",
"Olduvai's layered deposits gave the Oldowan its name and show stone tools changing over about two million years.",
"stone knapping;butchery",
"site type: gorge with archaeological localities;chopper;hand axe;flake",
"tools",
"palaeoanthropologists (Mary and Louis Leakey)",
"Maasai and Tanzanian field workers",
"none",
"open-access excavation reports;Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"links: ARC002; ARC003.",
"canon_places.csv"
],
[
"PLC073",
"Olorgesailie",
"Olorgesailie, Kajiado, Kenya",
"place",
"Place",
"F1.6",
"AF-SWA",
"-1200000",
"-300000",
"approx.",
"Olorgesailie holds dense Acheulean hand-axe sites and, from about 320,000 years ago, obsidian brought from far away and pigment use.",
"stone knapping;obsidian;pigment",
"site type: basin with archaeological localities;hand axe;obsidian point;pigment",
"tools",
"palaeoanthropologists (Brooks et al. 2018)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"links: ARC003; ARC004.",
"canon_places.csv"
],
[
"PLC074",
"Panga ya Saidi",
"Kilifi County, Kenya",
"place",
"Place",
"F1.6",
"AF-SWA",
"-78000",
"",
"approx.; burial c. 78,000 years",
"The cave holds long sequences of stone tools and beads and the burial of a child about 78,000 years ago.",
"stone knapping;shell beads",
"site type: cave;burial;bead;stone tool",
"ritual and belief;clothing and adornment",
"archaeologists (Max Planck; National Museums of Kenya)",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC075",
"Shanga",
"Pate Island, Kenya",
"place",
"Place",
"F1.6;F1.10",
"AF-SWA",
"750",
"1425",
"approx.",
"Excavations at Shanga traced a Swahili town from timber buildings to coral mosques, with beads, local pottery and imports.",
"coral-stone building;pottery;bead",
"site type: town;mosque;pottery;coin",
"exchange and value;ritual and belief",
"archaeologists (Mark Horton)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: CIV004.",
"canon_places.csv"
],
[
"PLC076",
"Kilwa Kisiwani",
"Kilwa, Lindi, Tanzania",
"place",
"Place",
"F1.6;F1.10;F1.13",
"AF-SWA",
"900",
"1600",
"approx.; 10th-16th c.",
"Kilwa's Great Mosque, Husuni Kubwa palace and coin mint served a Swahili port that controlled gold shipped north from Sofala.",
"coral-stone building;coin minting",
"site type: port and palace;coin;mosque;imported porcelain",
"exchange and value;rule and display",
"archaeologists (Neville Chittick); UNESCO",
"enslaved labour in later Kilwa trade",
"human-flow",
"Wikimedia Commons;open-access excavation reports;British Museum collection search (link-out)",
"R1",
"F1.13",
"high",
"links: POL009; NET011. 18th-19th c. Kilwa Kivinje slave trade.",
"canon_places.csv"
],
[
"PLC077",
"Gede",
"Gedi, Kilifi County, Kenya",
"place",
"Place",
"F1.6;F1.10",
"AF-SWA",
"1100",
"1650",
"approx.",
"Gede's coral-stone houses, mosques and palace show the plan of a Swahili town with imported Chinese and Islamic ceramics.",
"coral-stone building;pottery",
"site type: town ruins;palace;imported ceramic",
"shelter;exchange and value",
"archaeologists (James Kirkman)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC078",
"Lamu Old Town",
"Lamu, Kenya",
"place",
"Place",
"F1.6;F1.10",
"AF-SWA",
"1370",
"",
"approx.; ongoing",
"Lamu's carpenters and carvers make carved doors, furniture and dhows in a town whose houses keep Swahili building methods.",
"wood carving;coral-stone building;dhow building",
"site type: town and craft quarter;carved door;chair;dhow",
"shelter;transport",
"the Lamu community; UNESCO",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"high",
"links: MKR015; POL010.",
"canon_places.csv"
],
[
"PLC079",
"Fort Jesus",
"Mombasa, Kenya",
"place",
"Place",
"F1.6;F1.13",
"AF-SWA",
"1593",
"",
"built 1593-96; port older",
"The Portuguese fort at Mombasa's harbour changed hands between Portugal and Oman and is a museum of the port's trade finds.",
"stone fortification",
"site type: fort and museum;ceramic;cannon",
"war;exchange and value",
"UNESCO; National Museums of Kenya",
"enslaved labour in the port",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC080",
"Zanzibar Stone Town",
"Unguja, Zanzibar, Tanzania",
"place",
"Place",
"F1.6;F1.10;F1.13",
"AF-SWA",
"1830",
"",
"approx.; Omani capital from 1830s",
"Stone Town's carved doors and houses were built on the clove, ivory and slave trades, and its slave market closed in 1873.",
"wood carving;coral-stone building",
"site type: port town and former slave market;carved door;chest",
"exchange and value;shelter",
"UNESCO; the Zanzibari state",
"the enslaved people traded and those who worked clove plantations",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13;F1.23",
"high",
"links: POL011.",
"canon_places.csv"
],
[
"PLC081",
"Kasubi Tombs",
"Kampala, Uganda",
"place",
"Place",
"F1.6",
"AF-SWA",
"1882",
"",
"built 1882; rebuilding after 2010 fire",
"The thatched royal tomb house of the Buganda kings is built and maintained by hereditary clans using reed, barkcloth and thatch.",
"thatching;barkcloth;reed weaving",
"site type: royal tombs;barkcloth;thatched house",
"ritual and belief;rule and display",
"the Buganda kingdom; UNESCO",
"",
"funerary;sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16;F1.28a",
"high",
"links: POL012; PRA001.",
"canon_places.csv"
],
[
"PLC082",
"Kibiro",
"Lake Albert, Hoima, Uganda",
"place",
"Place",
"F1.6",
"AF-SWA",
"1300",
"",
"approx.; ongoing",
"Women at Kibiro have made salt by filtering and boiling saline soil for centuries, trading it across the Great Lakes region.",
"salt making;pottery",
"site type: salt-working site;salt;pot",
"food and storage;exchange and value",
"archaeologists (Graham Connah)",
"",
"living-community",
"open-access excavation reports",
"R3",
"F1.18;F1.29",
"medium",
"",
"canon_places.csv"
],
[
"PLC083",
"Blombos Cave",
"Western Cape, South Africa",
"place",
"Place",
"F1.6",
"AF-SOU",
"-100000",
"-70000",
"approx.; ochre toolkit c. 100,000 years; engravings and beads c. 75,000-73,000 years",
"Blombos has an ochre-processing toolkit from about 100,000 years ago, engraved ochre and shell beads, and a crosshatched drawing on stone.",
"ochre processing;engraving;shell beads",
"site type: cave;engraved ochre;shell bead;abalone container",
"clothing and adornment;record and writing",
"archaeologists (Christopher Henshilwood)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R1",
"F1.5",
"high",
"links: INV142; INV144; ARC007.",
"canon_places.csv"
],
[
"PLC084",
"Pinnacle Point",
"Mossel Bay, Western Cape, South Africa",
"place",
"Place",
"F1.6",
"AF-SOU",
"-164000",
"-50000",
"approx.",
"Caves at Pinnacle Point record ochre use and shellfish gathering about 164,000 years ago and, later, heat-treated stone and small blades.",
"ochre;heat treatment;microlith",
"site type: coastal caves;ochre;blade;shell",
"tools;food and storage",
"archaeologists (Curtis Marean)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"",
"canon_places.csv"
],
[
"PLC085",
"Diepkloof Rock Shelter",
"Western Cape, South Africa",
"place",
"Place",
"F1.6",
"AF-SOU",
"-65000",
"-55000",
"approx.",
"Hundreds of fragments of engraved ostrich-eggshell water containers, about 60,000 years old, show repeated geometric motifs.",
"ostrich-eggshell engraving",
"site type: rock shelter;engraved eggshell container",
"food and storage;record and writing",
"archaeologists (Texier et al.)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"links: ARC008.",
"canon_places.csv"
],
[
"PLC086",
"Mapungubwe",
"Limpopo, South Africa",
"place",
"Place",
"F1.6",
"AF-SOU",
"1220",
"1290",
"approx.",
"Burials on Mapungubwe Hill included gold-foil animals, and the town traded ivory and gold for Indian Ocean glass beads.",
"gold foil;glass beads;ivory",
"site type: hilltop capital and burials;gold rhinoceros;bead",
"rule and display;exchange and value",
"archaeologists (University of Pretoria)",
"descendant communities whose ancestors were exhumed",
"funerary;ancestral",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.24;F1.13",
"high",
"links: ARC040; CIV014; POL014. Gold was found by prospectors in 1933.",
"canon_places.csv"
],
[
"PLC087",
"Great Zimbabwe",
"Masvingo, Zimbabwe",
"place",
"Place",
"F1.6",
"AF-SOU",
"1200",
"1450",
"approx.",
"Dry-stone enclosures at Great Zimbabwe housed a trading capital, and its carved soapstone birds were removed by colonial collectors and returned in stages, the last in 2026.",
"dry-stone masonry;soapstone carving;gold",
"site type: stone-walled capital;soapstone bird;imported ceramic",
"rule and display;exchange and value",
"archaeologists (Gertrude Caton-Thompson)",
"the colonial denial that Africans built it",
"sacred;conflict-looting",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.3;F1.24",
"high",
"links: ARC041; CIV005; POL015. Birds returned from South Africa 1981, Germany (loan agreed 2000, public 2003) and the last, from Groote Schuur, 15 April 2026. See OCC169.",
"canon_places.csv"
],
[
"PLC088",
"Sofala",
"Nova Sofala, Mozambique",
"place",
"Place",
"F1.6;F1.13",
"AF-SWA;AF-SOU",
"900",
"1700",
"approx.",
"Sofala was the southern Swahili port for Zimbabwean gold and ivory before a Portuguese fort took it over in 1505.",
"trade goods",
"site type: port;gold;ivory",
"exchange and value",
"historians",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"links: NET011.",
"canon_places.csv"
],
[
"PLC089",
"Kimberley Mine",
"Big Hole, Kimberley, South Africa",
"place",
"Place",
"F1.6;THEME",
"AF-SOU",
"1871",
"1914",
"approx.",
"Diamond mining at the Big Hole used closed compounds to control African migrant workers, a system copied across South African mining.",
"open-pit mining;diamond",
"site type: mine;diamond",
"exchange and value",
"De Beers; historians",
"African miners in the compounds",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC090",
"Witwatersrand goldfields",
"Johannesburg, South Africa",
"place",
"Place",
"F1.6;THEME",
"AF-SOU",
"1886",
"",
"from 1886; ongoing",
"The Rand's deep gold mines relied on migrant labour under contract and compound systems, including Chinese indentured workers in 1904-10.",
"deep-level mining;cyanide process",
"site type: mining district;gold",
"exchange and value",
"mining houses; historians",
"migrant miners from across southern Africa; Chinese indentured labourers",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC091",
"Iziko Slave Lodge",
"Cape Town, South Africa",
"place",
"Place",
"F1.6;THEME",
"AF-SOU",
"1679",
"1811",
"approx.",
"The VOC housed the people it enslaved in this building, now a museum on slavery at the Cape.",
"brick building",
"site type: slave lodge and museum",
"shelter",
"Iziko Museums; historians",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.24;F1.23",
"high",
"links: INS038.",
"canon_places.csv"
],
[
"PLC092",
"Game Pass Shelter",
"Kamberg, uKhahlamba-Drakensberg, South Africa",
"place",
"Place",
"F1.6",
"AF-SOU",
"-1000",
"1800",
"approx.; paintings mostly last few thousand years",
"The shelter's painted eland panel is central to readings of San rock painting as religious imagery.",
"mineral pigment;blood;painting",
"site type: rock shelter;rock painting",
"ritual and belief",
"San descendants; archaeologists (David Lewis-Williams)",
"",
"sacred;Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"Dates uncertain.",
"canon_places.csv"
],
[
"PLC093",
"Mahilaka",
"Mahajamba Bay, Madagascar",
"place",
"Place",
"F1.6;F1.13",
"AF-MAD",
"900",
"1500",
"approx.",
"Mahilaka was an early walled trading town in north-west Madagascar that imported glass and ceramics and worked chlorite schist.",
"chlorite-schist carving;trade goods",
"site type: trading town;stone vessel;imported ceramic",
"exchange and value",
"archaeologists (Chantal Radimilahy)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: ARC044.",
"canon_places.csv"
],
[
"PLC094",
"Iharana",
"Vohémar, SAVA, Madagascar",
"place",
"Place",
"F1.6;F1.13",
"AF-MAD",
"1300",
"1650",
"approx.",
"Graves at Iharana held imported Chinese celadon and carved chlorite-schist vessels and were heavily dug by collectors.",
"chlorite-schist carving;imported ceramics",
"site type: cemetery;stone vessel;celadon",
"ritual and belief;exchange and value",
"archaeologists",
"",
"funerary;conflict-looting",
"open-access excavation reports",
"R3",
"F1.24",
"medium",
"links: ARC045.",
"canon_places.csv"
],
[
"PLC095",
"Ambohimanga",
"Royal Hill of Ambohimanga, Madagascar",
"place",
"Place",
"F1.6",
"AF-MAD",
"1700",
"",
"approx.; ongoing",
"The royal hill of the Merina kings is a sacred site of wooden houses, tombs and ritual gates.",
"timber building;stone wall",
"site type: royal hill;wooden house;tomb",
"ritual and belief;rule and display",
"the Merina kingdom; UNESCO",
"",
"sacred;funerary",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: POL018.",
"canon_places.csv"
],
[
"PLC096",
"Rova of Antananarivo",
"Manjakamiadana, Antananarivo, Madagascar",
"place",
"Place",
"F1.6",
"AF-MAD",
"1610",
"1896",
"approx.",
"The Merina royal compound combined Malagasy timber building with palaces designed with European craftsmen, and was badly damaged by fire in 1995.",
"timber building;stone cladding",
"site type: royal compound;palace",
"rule and display",
"the Merina kingdom; missionaries (James Cameron)",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"links: POL018.",
"canon_places.csv"
],
[
"PLC097",
"Zafimaniry villages",
"Antoetra, Amoron'i Mania, Madagascar",
"place",
"Place",
"F1.6",
"AF-MAD",
"1800",
"",
"approx.; ongoing",
"Zafimaniry carpenters build and decorate houses and furniture in hardwood with geometric carving, a knowledge on UNESCO's intangible heritage Representative List (proclaimed 2003, inscribed 2008).",
"wood carving;joinery",
"site type: villages;carved house;shutter;stool",
"shelter",
"the Zafimaniry",
"",
"living-community",
"Wikimedia Commons;community-published site (link-out)",
"R3",
"F1.29",
"medium",
"",
"canon_places.csv"
],
[
"PLC098",
"Aapravasi Ghat",
"Port Louis, Mauritius",
"place",
"Place",
"F1.6;F1.13",
"AF-MAD",
"1849",
"1923",
"approx.",
"The immigration depot processed indentured labourers, mostly from India, who were brought to work Mauritian sugar estates.",
"stone building",
"site type: immigration depot",
"shelter",
"UNESCO; historians",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23",
"high",
"links: DIA009.",
"canon_places.csv"
],
[
"PLC099",
"Ipiutak site",
"Point Hope (Tikiġaq), Alaska, USA",
"place",
"Place",
"F1.7",
"AM-ARC",
"1",
"800",
"approx.",
"Burials at the Ipiutak site contained openwork ivory carvings and ivory masks and eyes, made without the ground-slate tools common elsewhere in the Arctic.",
"ivory carving;antler;engraving",
"site type: village and cemetery;ivory openwork carving;burial mask;harpoon head",
"ritual and belief;tools",
"archaeologists (Larsen, Rainey and Giddings, 1939-41)",
"the Tikiġaq community whose ancestors were excavated",
"funerary;Indigenous-community",
"open-access excavation reports;collection search link-out only",
"R3",
"F1.24",
"medium",
"links: ARC168.",
"canon_places.csv"
],
[
"PLC100",
"Nunalleq",
"near Quinhagak, Alaska, USA",
"place",
"Place",
"F1.7",
"AM-ARC",
"1350",
"1675",
"approx.",
"A Yup'ik sod house village preserved in permafrost has yielded tens of thousands of wooden, grass and ivory objects in a dig run with the village corporation.",
"wood carving;grass weaving;ivory;skin sewing",
"site type: excavated village;mask;bentwood bowl;grass basket;doll",
"clothing and adornment;ritual and belief;food and storage",
"the Quinhagak community (Qanirtuuq Inc.); University of Aberdeen",
"",
"Indigenous-community;ancestral",
"community-published site (link-out);open-access excavation reports",
"R2",
"F1.26;F1.24",
"high",
"Coastal erosion prompted the excavation from 2009; finds kept in a local centre.",
"canon_places.csv"
],
[
"PLC101",
"Kinngait Studios",
"Cape Dorset, Nunavut, Canada",
"place",
"Place",
"F1.7",
"AM-ARC",
"1957",
"",
"printmaking from 1957; co-operative from 1959; ongoing",
"The print studio at Kinngait turned drawings by Inuit artists into stonecut and stencil editions sold through an annual collection.",
"stonecut printing;stencil;drawing",
"site type: print studio;print;drawing",
"record and writing;exchange and value",
"the West Baffin Eskimo Co-operative; James Houston",
"printers and cutters whose names are less visible than the artists'",
"living-community;Indigenous-community",
"collection search link-out only",
"R2",
"F1.26;F1.17;F1.20",
"high",
"links: MKR029; POL079.",
"canon_places.csv"
],
[
"PLC102",
"Savissivik",
"Cape York meteorite find sites, Greenland",
"place",
"Place",
"F1.7",
"AM-ARC",
"800",
"1897",
"approx.",
"Inughuit cold-hammered iron from the Cape York meteorites into blades until Robert Peary removed the largest pieces to New York in 1894-97.",
"cold-worked meteoritic iron",
"site type: meteorite source;iron blade;harpoon",
"tools",
"the Inughuit; Robert Peary; American Museum of Natural History",
"the six Inughuit Peary brought to New York in 1897, four of whom died there",
"conflict-looting;Indigenous-community",
"collection search link-out only",
"R3",
"F1.24;F1.22",
"high",
"links: NET044. Start date approximate.",
"canon_places.csv"
],
[
"PLC103",
"Qilakitsoq",
"Uummannaq Fjord, Greenland",
"place",
"Place",
"F1.7",
"AM-ARC",
"1475",
"",
"approx.; burial c. 1475 CE; found 1972",
"Naturally mummified women and children buried at Qilakitsoq wore sealskin and bird-skin clothing that shows Inuit sewing and tailoring.",
"skin sewing;bird-skin clothing",
"site type: burial;parka;boot",
"clothing and adornment",
"Greenland National Museum and Archives",
"",
"funerary;Indigenous-community",
"collection search link-out only",
"R3",
"F1.18",
"high",
"",
"canon_places.csv"
],
[
"PLC104",
"Hvalsey Church",
"Qaqortukulooq, Greenland",
"place",
"Place",
"F1.11",
"AM-ARC;EU-SCA",
"1300",
"1408",
"approx.; last written record 1408",
"The stone church of the Norse Eastern Settlement is the best-preserved Norse building in Greenland, last documented at a wedding in 1408.",
"stone masonry",
"site type: church ruin",
"ritual and belief",
"historians; archaeologists",
"",
"sacred",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC105",
"L'Anse aux Meadows",
"Newfoundland, Canada",
"place",
"Place",
"F1.7;F1.11",
"AM-ARC;AM-EWD;EU-SCA",
"1000",
"1025",
"approx.; wood cut with metal blades dated 1021",
"The Norse camp has evidence of bog-iron smelting, carpentry and ship repair, and wood cut with metal tools dated to 1021.",
"bog-iron smelting;carpentry",
"site type: Norse camp;iron slag;spindle whorl;rivet",
"shelter;transport",
"archaeologists (Anne Stine and Helge Ingstad)",
"the Indigenous peoples of Newfoundland at the time",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"Kuitems et al. 2021 Nature.",
"canon_places.csv"
],
[
"PLC106",
"Ozette",
"Cape Alava, Washington, USA",
"place",
"Place",
"F1.7",
"AM-NWC",
"1500",
"1750",
"approx.; houses buried by mudslide c. 1700",
"A mudslide buried Makah houses with their wooden boxes, baskets, whaling gear and looms, excavated with the Makah and kept at their museum.",
"wood carving;basketry;weaving;whaling gear",
"site type: buried village;bentwood box;basket;harpoon;loom",
"shelter;food and storage;tools",
"the Makah Tribe; archaeologists (Richard Daugherty)",
"",
"Indigenous-community;ancestral",
"community-published site (link-out);collection search link-out only",
"R2",
"F1.26;F1.24",
"high",
"Makah Cultural and Research Center opened 1979.",
"canon_places.csv"
],
[
"PLC107",
"SGang Gwaay Llnagaay",
"Ninstints, Haida Gwaii, BC, Canada",
"place",
"Place",
"F1.7",
"AM-NWC",
"1700",
"1880",
"approx.",
"The Haida village's house and mortuary poles are carved cedar monuments, several of which were removed to museums in 1957.",
"red-cedar carving;timber building",
"site type: village and mortuary site;mortuary pole;house frontal pole",
"ritual and belief;rule and display",
"the Haida Nation; UNESCO",
"the smallpox epidemic that emptied the village",
"funerary;sacred;Indigenous-community",
"Wikimedia Commons;collection search link-out only",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC108",
"U'mista Cultural Centre",
"Alert Bay, Cormorant Island, BC, Canada",
"place",
"Place",
"F1.7;THEME",
"AM-NWC",
"1980",
"",
"opened 1980; regalia seized 1922",
"Regalia surrendered after the 1921 potlatch at Village Island were taken under the potlatch ban and were partly returned to this Kwakwaka'wakw centre from 1979.",
"wood carving;painting;regalia",
"site type: community museum;mask;copper;regalia",
"ritual and belief",
"the 'Namgis First Nation; the Kwakwaka'wakw",
"",
"conflict-looting;sacred;Indigenous-community",
"community-published site (link-out);collection search link-out only",
"R2",
"F1.24",
"high",
"Objects went to the National Museum of Canada, the Royal Ontario Museum and George Heye.",
"canon_places.csv"
],
[
"PLC109",
"Yuquot",
"Friendly Cove, Nootka Sound, BC, Canada",
"place",
"Place",
"F1.7;F1.13",
"AM-NWC",
"1778",
"1795",
"maritime fur-trade node from 1778",
"Yuquot was a focus of the maritime fur trade after 1778, and its Whalers' Shrine was removed to the American Museum of Natural History in 1904.",
"wood carving;fur trade",
"site type: village and trading anchorage;shrine;sea-otter pelt",
"ritual and belief;exchange and value",
"the Mowachaht/Muchalaht First Nation",
"",
"sacred;conflict-looting;Indigenous-community",
"collection search link-out only",
"R3",
"F1.13;F1.24",
"high",
"links: NET043. Shrine acquired by George Hunt for Franz Boas.",
"canon_places.csv"
],
[
"PLC110",
"c̓əsnaʔəm",
"Marpole Midden, Vancouver, BC, Canada",
"place",
"Place",
"F1.7",
"AM-NWC",
"-1000",
"1700",
"approx.",
"The Musqueam village and burial ground gave the Marpole phase its name, and in 2012 Musqueam protests stopped a development on it.",
"stone carving;antler;ground slate",
"site type: village and burial ground;stone bowl;ground-slate knife",
"ritual and belief;tools",
"the Musqueam; archaeologists",
"",
"funerary;ancestral;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.24;F1.3",
"high",
"links: ARC170.",
"canon_places.csv"
],
[
"PLC111",
"Museum of Anthropology at UBC",
"Vancouver, BC, Canada",
"place",
"Place",
"F1.7;THEME",
"AM-NWC",
"1976",
"",
"museum 1949; Erickson building 1976",
"The museum's Great Hall displays Northwest Coast poles and has developed co-management and loan practices with First Nations.",
"museum display",
"site type: museum;pole;bentwood box",
"rule and display",
"University of British Columbia; First Nations partners",
"",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC112",
"Chaco Canyon",
"Pueblo Bonito, New Mexico, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"850",
"1150",
"approx.",
"Chaco's great houses held turquoise, macaw feathers, shell and cylinder jars with cacao residue brought along regional roads.",
"masonry;turquoise working;pottery",
"site type: ceremonial and trading centre;cylinder jar;turquoise ornament;great house",
"ritual and belief;exchange and value",
"archaeologists; Pueblo descendant communities",
"",
"sacred;ancestral;Indigenous-community",
"Wikimedia Commons;open-access excavation reports;Smithsonian Open Access (CC0)",
"R2",
"F1.13",
"high",
"links: CIV024; HOR008; NET038; NET039.",
"canon_places.csv"
],
[
"PLC113",
"Cerrillos Hills turquoise mines",
"Mount Chalchihuitl, New Mexico, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"900",
"",
"approx.; ancestral Pueblo, Spanish and later mining",
"Ancestral Pueblo miners dug turquoise at Mount Chalchihuitl, one of several sources that supplied Chaco and later trade.",
"turquoise mining;stone hammers",
"site type: mine;turquoise",
"clothing and adornment;exchange and value",
"archaeologists; geochemists",
"",
"sacred",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.22",
"medium",
"links: NET039. Isotope studies show Chaco turquoise came from several sources.",
"canon_places.csv"
],
[
"PLC114",
"Paquimé",
"Casas Grandes, Chihuahua, Mexico",
"place",
"Place",
"F1.7",
"AM-WST;AM-MES",
"1200",
"1450",
"approx.",
"Paquimé had macaw breeding pens, shell and copper stores and polychrome pottery, a hub between the Southwest and Mesoamerica.",
"macaw breeding;shell working;polychrome pottery",
"site type: town and exchange hub;macaw pen;polychrome jar;shell ornament",
"exchange and value;ritual and belief",
"archaeologists (Charles Di Peso)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"links: ARC178.",
"canon_places.csv"
],
[
"PLC115",
"Mimbres Valley sites",
"Grant County, New Mexico, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1000",
"1130",
"approx.; Classic Mimbres",
"Painted black-on-white bowls were placed over the dead with a hole broken through them, and bulldozer looting destroyed many sites.",
"coil pottery;mineral paint",
"site type: village and burial sites;painted bowl",
"ritual and belief",
"archaeologists; Pueblo descendant communities",
"",
"funerary;conflict-looting",
"open-access excavation reports;collection search link-out only",
"R3",
"F1.24",
"high",
"links: ARC176.",
"canon_places.csv"
],
[
"PLC116",
"Hubbell Trading Post",
"Ganado, Arizona, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1878",
"",
"founded 1878; ongoing",
"John Lorenzo Hubbell's post bought Navajo rugs and silver and urged weavers towards designs such as Ganado Red that sold to outside buyers.",
"weaving;silversmithing",
"site type: trading post;rug;silver jewellery",
"exchange and value",
"the traders; Navajo weavers",
"Navajo women weavers credited under the trader's name",
"living-community;Indigenous-community",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.14;F1.26",
"high",
"links: INS013.",
"canon_places.csv"
],
[
"PLC117",
"Acoma Pueblo",
"Sky City, New Mexico, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1150",
"",
"approx.; ongoing",
"Potters at Acoma make thin-walled, painted jars from local clay, one of the longest-inhabited places in North America.",
"coil pottery;mineral paint",
"site type: village;painted jar",
"food and storage;ritual and belief",
"the Acoma Pueblo",
"",
"living-community;Indigenous-community",
"collection search link-out only",
"R3",
"F1.29",
"high",
"",
"canon_places.csv"
],
[
"PLC118",
"Sikyátki",
"First Mesa, Arizona, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1375",
"1625",
"approx.",
"Excavations here in 1895 showed Sikyátki polychrome to the Hano potter Nampeyo, whose revival style changed Hopi pottery.",
"coil pottery;polychrome",
"site type: ancestral village;polychrome bowl",
"food and storage",
"archaeologists (J. W. Fewkes); Nampeyo",
"the Hopi whose ancestors' graves were dug",
"funerary;Indigenous-community",
"Smithsonian Open Access (CC0);collection search link-out only",
"R3",
"F1.14;F1.26",
"high",
"links: MKR028.",
"canon_places.csv"
],
[
"PLC119",
"Santa Fe Plaza",
"Santa Fe, New Mexico, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1922",
"",
"Indian Market from 1922; ongoing",
"The plaza hosts the Indian Market, whose juried categories and prizes have shaped what Native American makers produce for sale.",
"jewellery;pottery;weaving",
"site type: market;pottery;jewellery",
"exchange and value",
"SWAIA; Native American artists",
"",
"living-community;Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.21;F1.15",
"high",
"",
"canon_places.csv"
],
[
"PLC120",
"Pipestone quarries",
"Pipestone, Minnesota, USA",
"place",
"Place",
"F1.7",
"AM-WST",
"1600",
"",
"approx.; quarrying older than date shown; ongoing",
"Plains peoples quarry the red catlinite used for pipe bowls here, a right reserved to Native Americans at the national monument.",
"catlinite quarrying;stone carving",
"site type: quarry;pipe bowl",
"ritual and belief",
"the Dakota and other Plains nations; National Park Service",
"",
"sacred;Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"Start of quarrying uncertain.",
"canon_places.csv"
],
[
"PLC121",
"Cahokia",
"Collinsville, Illinois, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"1050",
"1350",
"approx.",
"The largest Mississippian town had copper workshops, flint-clay figure carving and mound building, and Mound 72 held mass burials.",
"earthwork;copper sheet working;flint-clay carving",
"site type: mound centre;copper plate;figurine;chunkey stone",
"ritual and belief;rule and display",
"archaeologists",
"the people sacrificed in Mound 72",
"funerary;ancestral",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5",
"high",
"links: POL062; CIV023.",
"canon_places.csv"
],
[
"PLC122",
"Poverty Point",
"West Carroll Parish, Louisiana, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"-1700",
"-1100",
"approx.",
"Hunter-gatherers built concentric earthen ridges and mounds here and brought stone and copper from hundreds of kilometres away.",
"earthwork;fired clay cooking balls;stone lapidary",
"site type: earthwork and exchange centre;clay cooking ball;stone bead",
"exchange and value;ritual and belief",
"archaeologists",
"",
"ancestral",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"high",
"links: ARC181; INV133.",
"canon_places.csv"
],
[
"PLC123",
"Spiro Mounds",
"Le Flore County, Oklahoma, USA",
"place",
"Place",
"F1.7",
"AM-EWD;AM-WST",
"900",
"1450",
"approx.",
"The Craig Mound's burial chamber held engraved shell, copper and textiles and was dug out for sale by a mining company in 1933-35.",
"shell engraving;copper repoussé;textile",
"site type: mound centre;engraved shell cup;copper plate;textile",
"ritual and belief;rule and display",
"archaeologists; the looters",
"the Caddo and Wichita descendants",
"funerary;conflict-looting",
"collection search link-out only;Smithsonian Open Access (CC0)",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC124",
"Hopewell Mound Group",
"Ross County, Ohio, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"-100",
"500",
"approx.",
"Hopewell mounds held objects of mica, copper, Yellowstone obsidian and shark teeth, and were dug in 1891-92 for display at the Chicago fair.",
"mica cutting;copper working;obsidian",
"site type: earthwork and burial mounds;mica hand;copper effigy;obsidian blade",
"ritual and belief;exchange and value",
"archaeologists (Warren K. Moorehead); UNESCO",
"",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.24;F1.13",
"high",
"links: ARC183; ISP002.",
"canon_places.csv"
],
[
"PLC125",
"Lowell mills",
"Lowell, Massachusetts, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"1823",
"1920",
"approx.",
"Lowell's water-powered cotton mills employed young women from New England farms, who wrote and struck over wages and hours, spinning cotton grown by enslaved people.",
"power loom;water power;cotton spinning",
"site type: mill town;cotton cloth;boarding house",
"clothing and adornment",
"industrialists (Boston Associates); the mill women; historians",
"the enslaved people who grew the cotton",
"human-flow",
"Library of Congress HABS/HAER (public domain);Library of Congress (public-domain items);Wikimedia Commons",
"R1",
"F1.23;F1.18;F1.19",
"high",
"links: MKR031; NET056.",
"canon_places.csv"
],
[
"PLC126",
"Highland Park Ford Plant",
"Highland Park, Michigan, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"1910",
"1927",
"approx.",
"Ford introduced the moving assembly line for the Model T here in 1913, dividing car-making into timed tasks.",
"assembly line;interchangeable parts",
"site type: factory;car",
"transport",
"Ford Motor Company; Albert Kahn (architect)",
"the migrant workers who bore the pace of the line",
"none",
"Library of Congress (public-domain items);Library of Congress HABS/HAER (public domain);Wikimedia Commons",
"R2",
"F1.19;F1.23",
"high",
"links: INS065.",
"canon_places.csv"
],
[
"PLC127",
"Charleston",
"Charles Town, South Carolina, USA",
"place",
"Place",
"F1.7;F1.13",
"AM-EWD",
"1670",
"",
"founded 1670; ongoing",
"Charleston was a leading port for enslaved Africans, whose skills in rice growing, Colono pottery and basketry shaped the Lowcountry.",
"Colono ware;coiled sweetgrass basketry;ironwork",
"site type: port;sweetgrass basket;Colono ware",
"exchange and value",
"historians; the Gullah Geechee community",
"",
"human-flow;living-community",
"Library of Congress (public-domain items);Wikimedia Commons",
"R2",
"F1.13;F1.23",
"high",
"links: ARC201; DIA008. International African American Museum at Gadsden's Wharf (opened 2023).",
"canon_places.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
