insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PLC128",
"Jackson Park",
"World's Columbian Exposition grounds, Chicago, USA",
"place",
"Place",
"F1.7",
"AM-EWD;GL",
"1893",
"1893",
"fair May-October 1893",
"The 1893 fair displayed industry in the 'White City' and placed peoples in ranked villages on the Midway Plaisance, a model protested by Ida B. Wells and Frederick Douglass.",
"exhibition building;staff plaster",
"site type: world's-fair ground;exhibition building;display",
"rule and display",
"the fair's organisers; anthropologists (F. W. Putnam)",
"the Indigenous and non-Western people exhibited",
"none",
"Library of Congress (public-domain items);Internet Archive (public-domain books);Wikimedia Commons",
"R2",
"F1.19;F1.15",
"high",
"links: EVT007. Conditions of the people exhibited on the Midway to verify.",
"canon_places.csv"
],
[
"PLC129",
"Smithsonian Institution, National Mall",
"Washington, DC, USA",
"place",
"Place",
"F1.7;THEME",
"AM-EWD",
"1855",
"",
"institution 1846; Castle 1855",
"The Smithsonian's museums on the Mall classified American and world material culture, and its Open Access release put millions of images under CC0.",
"museum display",
"site type: museum complex;specimen;object",
"rule and display",
"the United States government",
"",
"none",
"Smithsonian Open Access (CC0)",
"R2",
"F1.24;F1.3",
"high",
"links: INS080.",
"canon_places.csv"
],
[
"PLC130",
"Metropolitan Museum of Art",
"Fifth Avenue, New York, USA",
"place",
"Place",
"F1.7;THEME",
"AM-EWD",
"1880",
"",
"founded 1870; building opened 1880",
"The Met's collections and 2017 Open Access policy make it one of the main free image sources for world making, alongside disputes over looted antiquities.",
"museum display",
"site type: museum;object",
"rule and display",
"trustees and donors",
"",
"conflict-looting",
"Met Open Access (CC0)",
"R2",
"F1.24",
"high",
"Several antiquities returned to Italy, Egypt and others after seizures; details to verify.",
"canon_places.csv"
],
[
"PLC131",
"Cranbrook",
"Bloomfield Hills, Michigan, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"1932",
"",
"academy 1932; ongoing",
"Eliel Saarinen's academy campus trained designers such as Charles and Ray Eames, Florence Knoll and Harry Bertoia.",
"architecture;furniture;textile",
"site type: campus and workshops;chair;textile",
"shelter",
"George Booth; Eliel Saarinen",
"Loja Saarinen's weaving studio and other women's workshops",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_places.csv"
],
[
"PLC132",
"Lake Eden campus",
"Black Mountain College, North Carolina, USA",
"place",
"Place",
"F1.7",
"AM-EWD",
"1941",
"1957",
"college 1933-57; at Lake Eden 1941-57",
"Students built the Studies Building and worked in the weaving and pottery studios at Lake Eden under teachers including Anni and Josef Albers.",
"weaving;pottery;building",
"site type: college campus;textile;pot",
"shelter",
"the college",
"students' and staff labour on the farm and buildings",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: INS059; DIA011.",
"canon_places.csv"
],
[
"PLC133",
"Templo Mayor precinct",
"Tenochtitlan, Mexico City, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"1325",
"1521",
"approx.",
"Offerings buried in the Mexica main temple include stone, shell, gold and feather work, found in excavations since 1978.",
"stone carving;goldwork;shell;featherwork",
"site type: temple precinct;offering;stone sculpture",
"ritual and belief;rule and display",
"the Proyecto Templo Mayor (INAH)",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.16",
"high",
"links: POL051; CIV020.",
"canon_places.csv"
],
[
"PLC134",
"Tlatelolco market",
"Tlatelolco, Mexico City, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"1337",
"1521",
"approx.",
"Spanish writers described the Tlatelolco market's ordered sections for cloth, feathers, obsidian and cacao, and the Colegio de Santa Cruz later produced the Florentine Codex nearby.",
"obsidian;cloth;featherwork;cacao",
"site type: market;cotton mantle;obsidian blade;cacao bean",
"exchange and value",
"Hernán Cortés; Bernal Díaz; Sahagún's collaborators",
"the Nahua scholars and painters of the Florentine Codex",
"none",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R1",
"F1.13;F1.28",
"high",
"links: INS009; INS007; MKR019.",
"canon_places.csv"
],
[
"PLC135",
"Teotihuacan",
"San Juan Teotihuacan, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"-100",
"550",
"approx.",
"Apartment compounds at Teotihuacan housed obsidian, lapidary and pottery workshops and a neighbourhood of Oaxacan migrants.",
"obsidian knapping;lapidary;mural painting",
"site type: city with craft neighbourhoods;obsidian blade;mask;mural",
"tools;ritual and belief",
"archaeologists",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports;Met Open Access (CC0)",
"R2",
"F1.5",
"high",
"links: CIV026; POL044.",
"canon_places.csv"
],
[
"PLC136",
"Sierra de las Navajas",
"Pachuca obsidian source, Hidalgo, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"-100",
"1521",
"approx.",
"Mines here produced the green-gold obsidian traded across Mesoamerica from Teotihuacan to Aztec times.",
"obsidian mining;blade making",
"site type: obsidian mine;prismatic blade",
"tools;exchange and value",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"F1.22;F1.13",
"high",
"links: NET037.",
"canon_places.csv"
],
[
"PLC137",
"San Lorenzo",
"Veracruz, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"-1400",
"-1000",
"approx.",
"Olmec sculptors carved colossal basalt heads at San Lorenzo from stone hauled from the Tuxtla mountains.",
"basalt carving;earthwork",
"site type: ceremonial centre;colossal head",
"rule and display",
"archaeologists",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.28a",
"high",
"links: ARC185; CIV019.",
"canon_places.csv"
],
[
"PLC138",
"La Venta",
"Tabasco, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"-900",
"-400",
"approx.",
"Olmec builders at La Venta buried massive serpentine block offerings and jade figurines and celts.",
"jade carving;serpentine;earthwork",
"site type: ceremonial centre;jade celt;figurine;mosaic pavement",
"ritual and belief",
"archaeologists",
"",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"high",
"links: ARC185.",
"canon_places.csv"
],
[
"PLC139",
"Aguateca",
"Petén, Guatemala",
"place",
"Place",
"F1.7",
"AM-MES",
"700",
"810",
"approx.; abandoned c. 810 after attack",
"Elite houses burned and abandoned in haste kept the tools of scribes, carvers and weavers where they worked.",
"shell carving;writing;weaving;stone",
"site type: burned elite houses;paint pot;spindle whorl;shell ornament",
"record and writing;tools",
"archaeologists (Takeshi Inomata)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC140",
"Joya de Cerén",
"La Libertad, El Salvador",
"place",
"Place",
"F1.7",
"AM-MES;AM-CAM",
"580",
"660",
"approx.; buried by volcanic ash c. 600-660",
"Volcanic ash buried a farming village with its pots, tools, stored food and gardens, showing everyday making outside elite centres.",
"earthen building;pottery;agriculture",
"site type: buried village;pot;grinding stone",
"food and storage;shelter",
"archaeologists (Payson Sheets)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.22a;F1.29",
"high",
"",
"canon_places.csv"
],
[
"PLC141",
"Motagua Valley jadeite sources",
"Motagua River, Guatemala",
"place",
"Place",
"F1.7",
"AM-MES",
"-1500",
"1521",
"approx.",
"The only known Mesoamerican jadeite came from the Motagua valley, supplying Olmec and Maya carvers.",
"jadeite;lapidary",
"site type: stone source;jade celt;jade ornament",
"ritual and belief;exchange and value",
"geologists; archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"F1.22;F1.13",
"medium",
"Some sources identified after Hurricane Mitch (1998).",
"canon_places.csv"
],
[
"PLC142",
"Sacred Cenote, Chichén Itzá",
"Yucatán, Mexico",
"place",
"Place",
"F1.7",
"AM-MES",
"800",
"1500",
"approx.",
"Offerings of gold, jade, copal and textiles were dredged from the cenote in 1904-10 by Edward Thompson and taken to the Peabody Museum.",
"goldwork;jade;copal;textile",
"site type: sacred well;gold disc;jade;copal",
"ritual and belief",
"the Maya; Edward H. Thompson; Peabody Museum",
"",
"sacred;conflict-looting",
"collection search link-out only;Wikimedia Commons",
"R3",
"F1.24",
"high",
"Partial returns to Mexico (dates to verify).",
"canon_places.csv"
],
[
"PLC143",
"Sitio Conte",
"Coclé, Panama",
"place",
"Place",
"F1.7",
"AM-CAM",
"450",
"900",
"approx.",
"Burials at Sitio Conte held hammered gold plaques, cast pendants and painted pottery excavated by Harvard and Penn in the 1930s-40s.",
"gold hammering;lost-wax casting;polychrome pottery",
"site type: cemetery;gold plaque;pendant;polychrome plate",
"rule and display",
"archaeologists (Samuel Lothrop; J. Alden Mason)",
"",
"funerary",
"collection search link-out only;open-access excavation reports",
"R3",
"F1.24",
"high",
"links: ARC190; POL054.",
"canon_places.csv"
],
[
"PLC144",
"Diquís stone spheres",
"Finca 6, Palmar Sur, Costa Rica",
"place",
"Place",
"F1.7",
"AM-CAM",
"500",
"1500",
"approx.",
"Settlements in the Diquís delta have precisely shaped granodiorite spheres placed in alignments.",
"stone shaping;granodiorite",
"site type: settlements with stone spheres;stone sphere",
"ritual and belief;rule and display",
"archaeologists; UNESCO",
"",
"none",
"Wikimedia Commons",
"R3",
"",
"high",
"links: ARC191.",
"canon_places.csv"
],
[
"PLC145",
"Teyuna",
"Ciudad Perdida, Sierra Nevada de Santa Marta, Colombia",
"place",
"Place",
"F1.7",
"AM-CAM",
"800",
"1600",
"approx.",
"The terraced Tairona town was found by looters in 1972 and remains sacred to the Kogi, Arhuaco, Wiwa and Kankuamo.",
"stone terracing;goldwork",
"site type: terraced town;gold ornament;stone path",
"shelter;ritual and belief",
"the Sierra Nevada peoples; ICANH",
"",
"sacred;conflict-looting;Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.24",
"medium",
"links: ARC192.",
"canon_places.csv"
],
[
"PLC146",
"Museo del Oro",
"Banco de la República, Bogotá, Colombia",
"place",
"Place",
"F1.7;THEME",
"AM-CAM;AM-AND",
"1939",
"",
"founded 1939",
"The bank's gold museum, begun with the purchase of a Quimbaya poporo, holds large collections of pre-Hispanic metalwork.",
"museum display",
"site type: museum;gold ornament;poporo",
"rule and display",
"Banco de la República",
"",
"none",
"collection search link-out only;Wikimedia Commons",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC147",
"Lake Guatavita",
"Cundinamarca, Colombia",
"place",
"Place",
"F1.7",
"AM-CAM;AM-AND",
"600",
"1600",
"approx.",
"Muisca offerings to the lake behind the El Dorado story led colonial and later companies to try to drain it for gold.",
"goldwork;tumbaga",
"site type: sacred lake;tunjo;gold offering",
"ritual and belief",
"the Muisca; historians",
"",
"sacred;conflict-looting",
"Wikimedia Commons",
"R3",
"F1.24",
"high",
"links: POL056; CIV040.",
"canon_places.csv"
],
[
"PLC148",
"San Agustín",
"Huila, Colombia",
"place",
"Place",
"F1.7",
"AM-CAM;AM-AND",
"1",
"900",
"approx.",
"Hundreds of carved stone statues guard mounds and tombs in the San Agustín region.",
"stone carving",
"site type: funerary landscape;statue;tomb",
"ritual and belief",
"archaeologists; UNESCO",
"",
"funerary;sacred",
"Wikimedia Commons",
"R3",
"",
"high",
"links: ARC194.",
"canon_places.csv"
],
[
"PLC149",
"Portobelo",
"Colón, Panama",
"place",
"Place",
"F1.7;F1.13",
"AM-CAM;AM-LAT",
"1597",
"1739",
"approx.",
"Portobelo held the fairs where Peruvian silver met Spanish fleets and where enslaved Africans were landed and sold.",
"trade goods;fortification",
"site type: fair port and fortifications",
"exchange and value",
"historians; UNESCO",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC150",
"Caguana",
"Utuado, Puerto Rico",
"place",
"Place",
"F1.7",
"AM-CAR",
"1200",
"1500",
"approx.",
"Stone-lined ball courts at Caguana carry carved petroglyphs of Taíno figures.",
"stone carving;petroglyph",
"site type: ceremonial centre;petroglyph;ball court",
"ritual and belief;play and music",
"archaeologists",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"links: CIV030.",
"canon_places.csv"
],
[
"PLC151",
"La Isabela",
"Puerto Plata, Dominican Republic",
"place",
"Place",
"F1.7;F1.13",
"AM-CAR;AM-LAT",
"1494",
"1498",
"approx.",
"Columbus's first town had a kiln making lead-glazed pottery and metalworking debris, and Taíno were forced to supply it with food and gold.",
"lead-glazed pottery;metallurgy",
"site type: colonial town;pottery;kiln",
"food and storage;exchange and value",
"archaeologists (Kathleen Deagan)",
"the Taíno forced to supply the settlers",
"human-flow",
"open-access excavation reports;Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC152",
"La Hueca-Sorcé",
"Vieques, Puerto Rico",
"place",
"Place",
"F1.7",
"AM-CAR",
"-200",
"600",
"approx.",
"Early ceramic-age lapidaries at Sorcé carved amethyst, carnelian and jadeitite into pendants including condor figures.",
"lapidary;stone drilling",
"site type: settlement and lapidary workshop;condor pendant;bead",
"clothing and adornment;exchange and value",
"archaeologists (Chanlatte and Narganes)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: ARC197; NET042. Chronology and 'Huecoid' label debated.",
"canon_places.csv"
],
[
"PLC153",
"Port Royal",
"Kingston Harbour, Jamaica",
"place",
"Place",
"F1.7;F1.13",
"AM-CAR",
"1655",
"1692",
"sank in earthquake 1692",
"Much of the town sank in 1692, preserving pewterers', potters' and pipe-makers' goods in a port that also traded enslaved Africans.",
"pewter;clay pipes;trade goods",
"site type: submerged port town;pewter plate;clay pipe",
"exchange and value",
"archaeologists (Texas A&M)",
"",
"human-flow",
"open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC154",
"Newton Plantation burial ground",
"Christ Church, Barbados",
"place",
"Place",
"F1.7",
"AM-CAR",
"1660",
"1820",
"approx.",
"The burial ground of enslaved people at a sugar estate is the most studied in the Caribbean, with beads, pipes and a carnelian necklace.",
"beads;clay pipes",
"site type: burial ground;bead necklace;clay pipe",
"ritual and belief;clothing and adornment",
"archaeologists (Jerome Handler)",
"",
"funerary;human-flow",
"open-access excavation reports",
"R3",
"F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC155",
"Partagás cigar factory",
"Real Fábrica de Tabacos Partagás, Havana, Cuba",
"place",
"Place",
"F1.7",
"AM-CAR",
"1845",
"",
"founded 1845",
"Cigar rollers in Havana's factories paid lectores to read to them while they worked, a practice begun in the 1860s.",
"tobacco rolling",
"site type: factory;cigar",
"exchange and value",
"the factory; the workers",
"the enslaved labour on tobacco and sugar land",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23;F1.29;F1.19",
"medium",
"Reading practice started 1865 in another Havana factory.",
"canon_places.csv"
],
[
"PLC156",
"Monte Verde",
"Llanquihue, Chile",
"place",
"Place",
"F1.7",
"AM-AND",
"-12500",
"",
"approx.; c. 14,500 cal BP",
"Monte Verde preserved wooden foundations, knotted cordage and stored plants, pushing back the date for people in the Americas.",
"woodworking;cordage;stone tools",
"site type: open-air camp;cordage;wooden stake;stone tool",
"shelter;tools",
"archaeologists (Tom Dillehay)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"Acceptance debated in the 1990s; now widely accepted.",
"canon_places.csv"
],
[
"PLC157",
"Caral",
"Supe valley, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"-2600",
"-2000",
"approx.",
"Platform mounds and sunken plazas at Caral were built with shicra bags of stones by a society that grew cotton for nets.",
"shicra bags;stone masonry;cotton",
"site type: early urban centre;platform mound;flute",
"shelter;ritual and belief",
"archaeologists (Ruth Shady)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.5",
"high",
"links: CIV031; INV130.",
"canon_places.csv"
],
[
"PLC158",
"Huaca Prieta",
"Chicama valley, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"-13000",
"-1800",
"approx.",
"Twined cotton textiles from the mound include fabric dyed with indigo about 6,200 years ago, the earliest known indigo use.",
"twining;indigo dyeing;cotton",
"site type: mound;twined textile;gourd",
"clothing and adornment",
"archaeologists (Junius Bird; Tom Dillehay)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5;F1.18",
"high",
"links: INV102; INV101.",
"canon_places.csv"
],
[
"PLC159",
"Chavín de Huántar",
"Áncash, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"-1200",
"-500",
"approx.",
"Stone galleries at Chavín hold carved slabs and the Lanzón, and its imagery spread on textiles and gold across the Andes.",
"stone carving;goldwork;textile",
"site type: temple centre;carved slab;gold crown",
"ritual and belief",
"archaeologists (Julio C. Tello)",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: CIV032; HOR001.",
"canon_places.csv"
],
[
"PLC160",
"Huaca Rajada",
"Sipán, Lambayeque, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"100",
"700",
"approx.; Lord of Sipán c. 250",
"After looters broke into a tomb in 1987, archaeologists excavated the intact burial of the 'Lord of Sipán' with gold and copper ornaments.",
"gold and copper working;shell",
"site type: burial platform;ear ornament;necklace",
"rule and display",
"archaeologists (Walter Alva)",
"",
"funerary;conflict-looting",
"open-access excavation reports;Wikimedia Commons",
"R2",
"F1.24",
"high",
"links: CIV033; POL057.",
"canon_places.csv"
],
[
"PLC161",
"Chan Chan",
"La Libertad, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"850",
"1470",
"approx.",
"The adobe capital of Chimor had walled palaces and artisans' quarters of metalworkers and weavers, many of whom the Inca moved to Cuzco.",
"adobe relief;metalworking;weaving",
"site type: capital with artisans' quarters;adobe frieze;textile",
"rule and display",
"archaeologists; UNESCO",
"",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.23",
"high",
"links: MKR025; POL060. human-flow for Inca relocation of artisans.",
"canon_places.csv"
],
[
"PLC162",
"Qorikancha",
"Cuzco, Peru",
"place",
"Place",
"F1.7",
"AM-AND",
"1440",
"1533",
"approx.",
"The Inca temple's walls were sheathed in gold that was stripped in 1533 for Atahualpa's ransom and melted down.",
"ashlar masonry;gold sheet",
"site type: temple;masonry;gold sheet",
"ritual and belief;rule and display",
"the Inca; Spanish chroniclers",
"",
"sacred;conflict-looting",
"Wikimedia Commons",
"R2",
"F1.24;F1.19a",
"high",
"links: POL061.",
"canon_places.csv"
],
[
"PLC163",
"Cerro Rico",
"Potosí, Bolivia",
"place",
"Place",
"F1.7;F1.13",
"AM-AND;AM-LAT",
"1545",
"",
"silver found 1545; mita from 1573; ongoing mining",
"Silver from Potosí, mined by Andean men drafted under the mita, fed Spanish coinage and the Manila and Chinese silver trade.",
"silver mining;mercury amalgamation;coin minting",
"site type: mine and mint town;peso;ingot",
"exchange and value",
"the Spanish Crown; historians",
"the mitayos and enslaved Africans at the mint; child miners today",
"human-flow;living-community",
"Wikimedia Commons;collection search link-out only",
"R1",
"F1.22;F1.23;F1.13",
"high",
"links: INS008; NET036.",
"canon_places.csv"
],
[
"PLC164",
"Huancavelica",
"Santa Bárbara mercury mine, Peru",
"place",
"Place",
"F1.7",
"AM-AND;AM-LAT",
"1564",
"1813",
"approx.",
"Mercury from Huancavelica, dug by drafted mitayos who were poisoned by it, was used to refine Potosí silver.",
"mercury mining;smelting",
"site type: mercury mine;mercury flask",
"exchange and value",
"the Spanish Crown; historians",
"the mitayos",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC165",
"Chinchorro sites",
"Camarones and Arica, Chile",
"place",
"Place",
"F1.7",
"AM-AND",
"-5000",
"-1500",
"approx.",
"Chinchorro fishers made the earliest known artificially prepared mummies, rebuilt with sticks, reeds and clay.",
"artificial mummification;reed binding",
"site type: settlements and cemeteries;mummy;fishhook",
"ritual and belief",
"archaeologists; UNESCO",
"",
"funerary",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"links: ARC202; INV158.",
"canon_places.csv"
],
[
"PLC166",
"Chuquicamata",
"Calama, Chile",
"place",
"Place",
"THEME",
"AM-AND",
"1915",
"",
"open-pit mining from 1915; ongoing",
"One of the largest open-pit copper mines supplies copper for wiring and electronics.",
"open-pit mining;electrolytic refining",
"site type: mine;copper cathode",
"exchange and value",
"Anaconda; Codelco",
"Atacameño communities and water loss",
"living-community",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC167",
"Chulucanas",
"Piura, Peru",
"place",
"Place",
"F1.7",
"AM-AND;AM-LAT",
"1960",
"",
"approx.; ongoing",
"Potters in Chulucanas make burnished, smoke-resist decorated ceramics developed from the 1960s with reference to ancient Vicús wares.",
"paddle and anvil;burnishing;smoke resist",
"site type: pottery town;jar;figure",
"food and storage;exchange and value",
"the potters; the Peruvian state",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.14;F1.21",
"medium",
"Denomination of origin \"Cerámica de Chulucanas\" granted 26 July 2006; 1960s revival and Vicús reference not independently confirmed.",
"canon_places.csv"
],
[
"PLC168",
"Camutins mounds",
"Marajó Island, Pará, Brazil",
"place",
"Place",
"F1.7",
"AM-AMZ",
"400",
"1400",
"approx.",
"Marajoara mound builders made polychrome burial urns and pottery with incised and painted designs.",
"polychrome pottery;earthwork",
"site type: mound complex;burial urn;tanga",
"ritual and belief;clothing and adornment",
"archaeologists (Anna Roosevelt; Denise Schaan)",
"",
"funerary",
"open-access excavation reports;collection search link-out only",
"R2",
"F1.5",
"medium",
"links: ARC214; CIV038; POL081.",
"canon_places.csv"
],
[
"PLC169",
"Taperinha",
"Santarém, Pará, Brazil",
"place",
"Place",
"F1.7",
"AM-AMZ",
"-5000",
"-4000",
"approx.; c. 7,000 BP",
"Pottery from the Taperinha shell mound is among the earliest known in the Americas.",
"pottery",
"site type: shell mound;potsherd",
"food and storage",
"archaeologists (Anna Roosevelt)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"links: INV023.",
"canon_places.csv"
],
[
"PLC170",
"Llanos de Mojos settlements",
"Cotoca and Landívar, Beni, Bolivia",
"place",
"Place",
"F1.7",
"AM-AMZ",
"500",
"1400",
"approx.",
"Lidar revealed Casarabe towns with platform mounds and causeways in the Amazon savanna.",
"earthwork;canal building",
"site type: urban settlements;causeway;platform",
"shelter;transport",
"archaeologists (Heiko Prümers et al. 2022)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"links: ARC216.",
"canon_places.csv"
],
[
"PLC171",
"Cueva de las Manos",
"Santa Cruz, Argentina",
"place",
"Place",
"F1.7",
"AM-AMZ",
"-7300",
"700",
"approx.",
"Stencilled hands and hunting scenes were painted here over thousands of years by Patagonian hunter-gatherers.",
"mineral pigment;stencil",
"site type: cave;hand stencil",
"ritual and belief",
"archaeologists; UNESCO",
"",
"sacred",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC172",
"São Miguel Arcanjo",
"São Miguel das Missões, Rio Grande do Sul, Brazil",
"place",
"Place",
"F1.7",
"AM-AMZ;AM-LAT",
"1687",
"1768",
"approx.",
"Guaraní carvers, masons and musicians worked in the Jesuit reduction whose church and sculpture survive.",
"stone masonry;wood carving",
"site type: mission town;church;saint figure",
"ritual and belief",
"Jesuits; the Guaraní",
"the Guaraní makers credited to the Jesuits",
"none",
"Wikimedia Commons",
"R3",
"F1.26",
"high",
"links: MKR027.",
"canon_places.csv"
],
[
"PLC173",
"La Chorrera",
"Putumayo, Colombia",
"place",
"Place",
"F1.7",
"AM-AMZ",
"1900",
"1913",
"approx.",
"Rubber collection by the Peruvian Amazon Company at La Chorrera enslaved and killed Uitoto and other peoples, as documented by Roger Casement.",
"wild rubber tapping",
"site type: rubber station;rubber",
"exchange and value",
"Roger Casement; historians",
"the Uitoto, Bora, Andoke and others",
"human-flow",
"Wikimedia Commons;Internet Archive (public-domain books)",
"R2",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC174",
"Fordlândia",
"Aveiro, Pará, Brazil",
"place",
"Place",
"F1.7",
"AM-AMZ",
"1928",
"1945",
"approx.",
"Ford built a company town to grow rubber for tyres here, and the plantation failed through leaf blight and worker unrest.",
"plantation;rubber",
"site type: company town;rubber",
"exchange and value",
"Ford Motor Company",
"Brazilian workers",
"none",
"Wikimedia Commons",
"R3",
"F1.22;F1.19",
"high",
"links: INS065.",
"canon_places.csv"
],
[
"PLC175",
"Puebla potteries",
"Puebla de los Ángeles, Mexico",
"place",
"Place",
"F1.7",
"AM-LAT",
"1550",
"",
"approx.; guild ordinances 1653; ongoing",
"Puebla potters made tin-glazed talavera poblana under guild rules, adapting Spanish methods and Chinese blue-and-white designs.",
"tin glaze;cobalt blue",
"site type: pottery centre;tile;jar",
"food and storage;shelter",
"the potters' guild; the Mexican state",
"Indigenous and African workers in the potteries",
"living-community",
"Wikimedia Commons;Met Open Access (CC0)",
"R2",
"F1.14",
"high",
"links: PRA046.",
"canon_places.csv"
],
[
"PLC176",
"Acapulco",
"Guerrero, Mexico",
"place",
"Place",
"F1.7;F1.13",
"AM-LAT",
"1565",
"1815",
"galleon port 1565-1815",
"Acapulco was the American terminus of the Manila galleon, where Chinese silk and porcelain arrived for silver and enslaved Asians were landed.",
"trade goods",
"site type: port;porcelain;silk",
"exchange and value;transport",
"historians",
"enslaved Asian 'chinos'",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: INS040; NET036.",
"canon_places.csv"
],
[
"PLC177",
"Veracruz",
"Veracruz, Mexico",
"place",
"Place",
"F1.7;F1.13",
"AM-LAT",
"1519",
"",
"founded 1519; ongoing",
"Veracruz was New Spain's Atlantic port for the treasure fleets and for enslaved Africans.",
"trade goods",
"site type: port;fort",
"exchange and value",
"historians",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: POL069.",
"canon_places.csv"
],
[
"PLC178",
"Cartagena de Indias",
"Bolívar, Colombia",
"place",
"Place",
"F1.7;F1.13",
"AM-LAT",
"1533",
"",
"founded 1533; ongoing",
"Cartagena was a main port for enslaved Africans entering Spanish South America and a fortified node of the fleet system.",
"fortification;trade goods",
"site type: port and fortifications",
"exchange and value;war",
"historians; UNESCO",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC179",
"Salvador da Bahia",
"Bahia, Brazil",
"place",
"Place",
"F1.7;F1.13",
"AM-LAT",
"1549",
"",
"founded 1549; ongoing",
"Salvador was Brazil's colonial capital and a major port for enslaved Africans, whose carpenters and gilders worked on its churches.",
"gilding;wood carving;sugar",
"site type: port city;church;gilded altarpiece",
"exchange and value;ritual and belief",
"historians; UNESCO",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.23",
"high",
"links: DIA008.",
"canon_places.csv"
],
[
"PLC180",
"Ouro Preto",
"Vila Rica, Minas Gerais, Brazil",
"place",
"Place",
"F1.7",
"AM-LAT",
"1698",
"",
"approx.; gold rush from 1690s; ongoing",
"Enslaved miners dug the gold of Vila Rica, whose churches carry soapstone and wood carving by Aleijadinho and his workshop.",
"gold mining;soapstone carving;wood carving",
"site type: mining town;church;soapstone sculpture",
"ritual and belief;exchange and value",
"historians; UNESCO",
"the enslaved miners and the workshop assistants credited to Aleijadinho",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.26;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC181",
"Valongo Wharf",
"Cais do Valongo, Rio de Janeiro, Brazil",
"place",
"Place",
"F1.7",
"AM-LAT",
"1811",
"1831",
"approx.",
"The stone wharf where hundreds of thousands of enslaved Africans landed was uncovered in 2011 with beads, amulets and pipes.",
"stone paving;beads",
"site type: wharf and memorial;bead;amulet",
"exchange and value",
"archaeologists; the Brazilian state; UNESCO",
"",
"human-flow",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.24;F1.23",
"high",
"UNESCO World Heritage 2017 (Valongo Wharf Archaeological Site), verified.",
"canon_places.csv"
],
[
"PLC182",
"Taxco",
"Guerrero, Mexico",
"place",
"Place",
"F1.7",
"AM-LAT",
"1931",
"",
"silver mining from 1530s; design workshops from 1931",
"William Spratling's workshop from 1931 trained local silversmiths, making Taxco a centre of modern Mexican silver design.",
"silversmithing",
"site type: mining town and workshops;silver jewellery",
"clothing and adornment",
"William Spratling; local silversmiths",
"the Mexican silversmiths who ran the benches",
"living-community",
"Wikimedia Commons",
"R3",
"F1.20;F1.26",
"high",
"",
"canon_places.csv"
],
[
"PLC183",
"Museo Nacional de Antropología",
"Chapultepec, Mexico City, Mexico",
"place",
"Place",
"F1.7;THEME",
"AM-LAT;AM-MES",
"1964",
"",
"opened 1964",
"The museum's design placed the Mexica hall at its centre, and the moving of a Tlaloc monolith from Coatlinchan for it met local protest.",
"museum display",
"site type: museum;stone sculpture",
"rule and display",
"the Mexican state; Pedro Ramírez Vázquez",
"the Coatlinchan community",
"none",
"collection search link-out only;Wikimedia Commons",
"R2",
"F1.24;F1.3",
"high",
"",
"canon_places.csv"
],
[
"PLC184",
"Xianrendong",
"Xianren Cave, Wannian, Jiangxi, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"-18000",
"-15000",
"approx.; earliest sherds c. 20,000-19,000 cal BP",
"Potsherds from Xianrendong, dated to about 20,000 years ago, are among the earliest known pottery anywhere, made by hunter-gatherers.",
"hand-built pottery;open firing",
"site type: cave;potsherd",
"food and storage",
"archaeologists (Wu et al. 2012)",
"",
"none",
"open-access excavation reports",
"R2",
"F1.5",
"high",
"links: INV020.",
"canon_places.csv"
],
[
"PLC185",
"Liangzhu",
"Yuhang, Hangzhou, Zhejiang, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"-3300",
"-2300",
"approx.",
"Elite graves at Liangzhu held jade cong, bi and axes carved with a repeated face motif, in a walled city with large water-control dams.",
"jade working;abrasive cutting;earthwork",
"site type: walled city and cemeteries;jade cong;jade bi",
"ritual and belief;rule and display",
"archaeologists; UNESCO",
"",
"funerary",
"open-access excavation reports;Wikimedia Commons;Met Open Access (CC0)",
"R3",
"F1.5",
"high",
"links: ARC122.",
"canon_places.csv"
],
[
"PLC186",
"Yinxu",
"Anyang, Henan, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"-1250",
"-1046",
"approx.; late Shang capital",
"Foundry sites at the late Shang capital produced piece-mould bronze vessels, and the tomb of Fu Hao held hundreds of bronzes and jades.",
"piece-mould bronze casting;jade carving;oracle-bone inscription",
"site type: royal capital, foundries and tombs;ritual bronze vessel;oracle bone;jade",
"ritual and belief;record and writing;rule and display",
"archaeologists (Academia Sinica, later CASS)",
"the foundry workers and captives buried in royal tombs",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5;F1.16",
"high",
"links: POL156; INV003.",
"canon_places.csv"
],
[
"PLC187",
"Mausoleum of the First Qin Emperor",
"Lintong, Xi'an, Shaanxi, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"-246",
"-208",
"approx.",
"Terracotta figures for the emperor's tomb were made in standardised parts by workshops whose foremen stamped their names, with convict labourers buried nearby.",
"modular clay figures;mould and hand building;bronze casting",
"site type: imperial tomb complex;terracotta figure;bronze chariot;weapon",
"ritual and belief;war;rule and display",
"archaeologists; UNESCO",
"the conscript and convict labourers",
"funerary;human-flow",
"Wikimedia Commons;open-access excavation reports",
"R1",
"F1.23;F1.26",
"high",
"links: POL159.",
"canon_places.csv"
],
[
"PLC188",
"Mogao Caves",
"Dunhuang, Gansu, China",
"place",
"Place",
"F1.8;F1.12a;F1.13",
"AS-CHN;AS-CEN",
"366",
"1400",
"approx.; Library Cave sealed early 11th c.; opened 1900",
"Painted cave temples and the sealed Library Cave, whose manuscripts and the dated 868 Diamond Sutra were taken by Stein, Pelliot and others after 1907, record Silk Road making and faith.",
"wall painting;clay sculpture;woodblock printing;paper",
"site type: cave-temple complex and manuscript cache;mural;manuscript;printed scroll;banner",
"ritual and belief;record and writing",
"Buddhist patrons; archaeologists and explorers; the Dunhuang Academy",
"the monks and local community who kept the cave; the collectors' dispersal of its contents",
"sacred;conflict-looting",
"International Dunhuang Programme (link-out);British Museum collection search (link-out);Wikimedia Commons",
"R1",
"F1.13;F1.24;F1.28",
"high",
"links: NET001; NET003; INV039.",
"canon_places.csv"
],
[
"PLC189",
"Chang'an",
"Daxing-Chang'an, Xi'an, Shaanxi, China",
"place",
"Place",
"F1.8;F1.13",
"AS-CHN",
"582",
"904",
"Sui-Tang city",
"The Tang capital's East and West Markets were regulated trading quarters where Sogdian and other foreign merchants sold goods from across Asia.",
"trade goods;silk;silver",
"site type: capital with regulated markets;silver vessel;sancai figure",
"exchange and value",
"historians; archaeologists",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: POL162; DIA001.",
"canon_places.csv"
],
[
"PLC190",
"Quanzhou",
"Zaitun, Fujian, China",
"place",
"Place",
"F1.8;F1.13",
"AS-CHN",
"900",
"1400",
"approx.; peak Song-Yuan",
"Quanzhou was a major Song-Yuan port with a multi-faith merchant community and kilns producing wares for export.",
"shipbuilding;ceramics;stone carving",
"site type: port;ship;export ceramic;tombstone",
"exchange and value;transport",
"historians; UNESCO",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13",
"high",
"A 13th-c. ship excavated at Houzhu in 1974.",
"canon_places.csv"
],
[
"PLC191",
"Guangzhou",
"Canton, Guangdong, China",
"place",
"Place",
"F1.8;F1.13",
"AS-CHN",
"-200",
"",
"approx.; ongoing",
"Canton was China's southern port for foreign trade, and under the Canton System (1757-1842) its workshops painted export porcelain, enamels and pictures to order.",
"overglaze enamel;export painting;lacquer",
"site type: port and export workshops;export porcelain;painted enamel;export painting",
"exchange and value",
"historians; museums",
"the painters and decorators who worked to foreign order",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Wikimedia Commons",
"R2",
"F1.13;F1.14",
"high",
"links: INS021.",
"canon_places.csv"
],
[
"PLC192",
"Jingdezhen",
"Jiangxi, China",
"place",
"Place",
"F1.8;F1.13",
"AS-CHN",
"1004",
"",
"name from 1004; imperial kiln from 1369; ongoing",
"Jingdezhen's kilns and imperial factory made porcelain in a divided production line, and its blue-and-white travelled worldwide.",
"porcelain;cobalt underglaze;dragon kiln;division of labour",
"site type: kiln town and imperial factory;blue-and-white jar;dish;vase",
"food and storage;exchange and value;rule and display",
"the imperial court; Père d'Entrecolles (letters 1712, 1722)",
"the many named stages of workers behind each piece",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);National Palace Museum Open Data (licence to verify);Wikimedia Commons",
"R1",
"F1.13;F1.14;F1.23",
"high",
"links: MKR036; INV031; NET054.",
"canon_places.csv"
],
[
"PLC193",
"Longquan kilns",
"Dayao, Longquan, Zhejiang, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"950",
"1650",
"approx.",
"Longquan kilns made thick-glazed green celadon traded from Japan to East Africa.",
"celadon glaze;dragon kiln",
"site type: kiln complex;celadon dish;vase",
"food and storage;exchange and value",
"archaeologists; potters",
"",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: PRA073.",
"canon_places.csv"
],
[
"PLC194",
"Ding kilns",
"Jiancicun, Quyang, Hebei, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"800",
"1300",
"approx.",
"Ding potters made thin white porcelain fired upside down, whose unglazed rims were then bound in metal.",
"white porcelain;mould impressing;inverted firing",
"site type: kiln complex;white bowl;dish",
"food and storage",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_places.csv"
],
[
"PLC195",
"Yaozhou kilns",
"Huangbao, Tongchuan, Shaanxi, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"618",
"1368",
"approx.",
"Yaozhou kilns made carved and moulded olive-green celadon, especially in the Northern Song.",
"celadon glaze;carving;moulding",
"site type: kiln complex;carved celadon bowl",
"food and storage",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC196",
"Yuanmingyuan",
"Old Summer Palace, Beijing, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"1709",
"1860",
"built from 1709; looted and burned October 1860",
"British and French troops looted and burned the imperial garden palaces in 1860, dispersing their porcelain, bronzes and jades to Europe.",
"garden building;imperial collection",
"site type: imperial palace-garden and looting site;bronze zodiac head;porcelain;jade",
"rule and display",
"historians; the Chinese state",
"",
"conflict-looting",
"Wikimedia Commons;collection search link-out only",
"R2",
"F1.24;F1.19a",
"high",
"links: POL169.",
"canon_places.csv"
],
[
"PLC197",
"Dafen Oil Painting Village",
"Longgang, Shenzhen, China",
"place",
"Place",
"F1.8",
"AS-CHN",
"1989",
"",
"from 1989; ongoing",
"Painters in Dafen produce hand-painted copies of famous paintings in large numbers for export and decor markets.",
"oil painting;copying",
"site type: painting village;copy painting",
"exchange and value",
"the painters; dealers",
"the painters whose skill is sold as reproduction",
"living-community",
"Wikimedia Commons",
"R3",
"F1.14;F1.21",
"high",
"",
"canon_places.csv"
],
[
"PLC198",
"Gangjin celadon kilns",
"Sadang-ri, Gangjin, Korea",
"place",
"Place",
"F1.8",
"AS-KOR",
"900",
"1400",
"approx.",
"Gangjin kilns made Goryeo celadon, including inlaid (sanggam) wares and tiles for the court.",
"celadon glaze;inlay (sanggam);kiln firing",
"site type: kiln complex;inlaid celadon vase;tile",
"food and storage;rule and display",
"archaeologists; the Goryeo court",
"",
"none",
"National Museum of Korea e-museum (KOGL Type 1);Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.5",
"high",
"links: STY139; POL176.",
"canon_places.csv"
],
[
"PLC199",
"Haeinsa Janggyeong Panjeon",
"Hapcheon, South Gyeongsang, Korea",
"place",
"Place",
"F1.8",
"AS-KOR",
"1237",
"",
"woodblocks carved 1237-48; at Haeinsa from 1398",
"More than 80,000 woodblocks of the Tripitaka Koreana are stored in ventilated halls built to keep them from decay.",
"woodblock carving;storage architecture",
"site type: temple and woodblock repository;printing block",
"ritual and belief;record and writing",
"the Goryeo state; the temple; UNESCO",
"the carvers",
"sacred",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons",
"R3",
"F1.28;F1.16",
"high",
"links: INV039.",
"canon_places.csv"
],
[
"PLC200",
"Heungdeoksa",
"Cheongju, North Chungcheong, Korea",
"place",
"Place",
"F1.8",
"AS-KOR",
"1377",
"",
"Jikji printed 1377",
"The Buddhist text Jikji was printed at Heungdeoksa in 1377 with movable metal type, and the only surviving copy is in the Bibliothèque nationale de France.",
"movable metal type;printing",
"site type: temple site and printing museum;printed book",
"record and writing",
"historians; the Korean state",
"",
"sacred",
"National Museum of Korea e-museum (KOGL Type 1);Gallica (public-domain items)",
"R3",
"F1.5;F1.24",
"high",
"links: INV042.",
"canon_places.csv"
],
[
"PLC201",
"Gyeongju",
"Seorabeol, North Gyeongsang, Korea",
"place",
"Place",
"F1.8",
"AS-KOR",
"-57",
"935",
"Silla capital, traditional dates",
"Silla royal tombs at Gyeongju held gold crowns, glass vessels from the west and ornaments made in local workshops.",
"goldwork;granulation;glass",
"site type: royal capital and tombs;gold crown;glass vessel",
"rule and display;ritual and belief",
"archaeologists; UNESCO",
"",
"funerary",
"National Museum of Korea e-museum (KOGL Type 1);Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: POL174.",
"canon_places.csv"
],
[
"PLC202",
"National Museum of Korea",
"Yongsan, Seoul, Korea",
"place",
"Place",
"F1.8;THEME",
"AS-KOR",
"2005",
"",
"Yongsan building 2005; origins in 1909 and 1915 museums",
"The national museum's collections trace to palace and colonial museums and are released under open reuse terms.",
"museum display",
"site type: museum;celadon;Buddhist sculpture",
"rule and display",
"the Korean state",
"the colonial-period collecting it inherited",
"none",
"National Museum of Korea e-museum (KOGL Type 1)",
"R2",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC203",
"Arita",
"Izumiyama and Tengudani kiln sites, Saga, Japan",
"place",
"Place",
"F1.8;F1.13",
"AS-JPN",
"1616",
"",
"porcelain from c. 1616; export via VOC from 1659; ongoing",
"Korean potters brought to Japan after the invasions of the 1590s are credited with finding porcelain stone at Izumiyama, starting Japanese porcelain exported as Imari.",
"porcelain;underglaze blue;overglaze enamel",
"site type: quarry and kiln town;Imari dish;Kakiemon jar",
"food and storage;exchange and value",
"the Nabeshima domain; historians",
"the Korean potters taken by force",
"human-flow;living-community",
"ColBase (Japan Government Standard Terms);Rijksmuseum (CC0);Met Open Access (CC0)",
"R1",
"F1.13;F1.14",
"high",
"links: MKR039; MKR040; DIA012; INS038.",
"canon_places.csv"
],
[
"PLC204",
"Seto kilns",
"Seto, Aichi, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"1200",
"",
"approx.; ongoing",
"Seto potters made glazed stoneware from about the 13th century, and 'setomono' became a general word for ceramics.",
"glazed stoneware;kiln firing",
"site type: kiln town;tea caddy;jar",
"food and storage",
"historians; the potters",
"",
"living-community",
"ColBase (Japan Government Standard Terms);Met Open Access (CC0)",
"R3",
"F1.5",
"high",
"",
"canon_places.csv"
],
[
"PLC205",
"Bizen kilns",
"Imbe, Okayama, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"1200",
"",
"approx.; ongoing",
"Bizen potters fire unglazed stoneware for many days in wood-fired kilns, valued in tea ceremony.",
"unglazed stoneware;anagama firing",
"site type: kiln town;water jar;vase",
"food and storage;ritual and belief",
"historians; the potters",
"",
"living-community",
"ColBase (Japan Government Standard Terms);Met Open Access (CC0)",
"R3",
"",
"high",
"",
"canon_places.csv"
],
[
"PLC206",
"Nishijin",
"Kyoto, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"1467",
"",
"name from the Ōnin War western camp; ongoing",
"Nishijin weavers make figured silks for kimono and obi and adopted the Jacquard loom after weavers were sent to Lyon in 1872.",
"drawloom;Jacquard loom;silk",
"site type: weaving district;obi;kimono",
"clothing and adornment",
"the weavers' guilds",
"family members who do preparatory work",
"living-community",
"ColBase (Japan Government Standard Terms);Met Open Access (CC0)",
"R2",
"F1.18;F1.14",
"high",
"links: MKR042; INV107.",
"canon_places.csv"
],
[
"PLC207",
"Nagasaki and Dejima",
"Nagasaki, Japan",
"place",
"Place",
"F1.8;F1.13",
"AS-JPN",
"1571",
"1859",
"port from 1571; Dutch on Dejima 1641-1859",
"Dejima was the only European trading post permitted under Tokugawa rule, shipping Japanese porcelain and lacquer and bringing in books and goods.",
"trade goods;lacquer;porcelain",
"site type: artificial island trading post;export porcelain;lacquer box",
"exchange and value",
"the Tokugawa shogunate; the VOC",
"Japanese interpreters and workers on the island",
"none",
"Rijksmuseum (CC0);ColBase (Japan Government Standard Terms)",
"R2",
"F1.13",
"high",
"links: INS025; POL183.",
"canon_places.csv"
],
[
"PLC208",
"Tokyo National Museum",
"Ueno, Tokyo, Japan",
"place",
"Place",
"F1.8;THEME",
"AS-JPN",
"1872",
"",
"founded 1872",
"Japan's oldest museum grew from the 1872 Yushima exhibition and built the national categories of Japanese art.",
"museum display",
"site type: museum;scroll;ceramic;sword",
"rule and display",
"the Japanese state",
"",
"none",
"ColBase (Japan Government Standard Terms)",
"R2",
"F1.24;F1.3",
"high",
"links: EVT002.",
"canon_places.csv"
],
[
"PLC209",
"Sannai-Maruyama",
"Aomori, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"-3900",
"-2200",
"approx.",
"The Jōmon village used lacquered wares, jade from Itoigawa and obsidian from distant sources, around large post buildings.",
"lacquer;jade;obsidian;pottery",
"site type: village;lacquered bowl;jade bead;clay figurine",
"food and storage;ritual and belief",
"archaeologists; UNESCO",
"",
"none",
"open-access excavation reports;ColBase (Japan Government Standard Terms)",
"R3",
"F1.5",
"high",
"links: ARC133.",
"canon_places.csv"
],
[
"PLC210",
"Shōsōin",
"Tōdai-ji, Nara, Japan",
"place",
"Place",
"F1.8;F1.13",
"AS-JPN",
"756",
"",
"founded 756; ongoing",
"The imperial storehouse holds objects given in 756 and later, including Tang Chinese, Persian-style and Japanese musical instruments, textiles and glass.",
"lacquer;inlay;textile;glass",
"site type: storehouse;lute;textile;glass bowl",
"rule and display;play and music",
"the Imperial Household Agency",
"",
"sacred",
"collection search link-out only;ColBase (Japan Government Standard Terms)",
"R2",
"F1.13;F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC211",
"Iwami Ginzan",
"Ōda, Shimane, Japan",
"place",
"Place",
"F1.8;F1.13",
"AS-JPN",
"1526",
"1923",
"approx.",
"Silver from Iwami, refined by cupellation from the 1530s, fed Japan's trade with China and the Portuguese.",
"silver mining;cupellation",
"site type: mine and mining town;silver ingot",
"exchange and value",
"historians; UNESCO",
"the miners",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC212",
"Sado Island gold mines",
"Sado, Niigata, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"1601",
"1989",
"approx.",
"Sado's gold and silver mines ran from the Edo period, and Korean workers were mobilised to them during the Second World War.",
"gold mining;hand tools",
"site type: mine;gold coin",
"exchange and value",
"historians; UNESCO",
"the Korean labourers and Edo-period forced labour",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"Framing of Korean labour disputed between states.",
"canon_places.csv"
],
[
"PLC213",
"Tomioka Silk Mill",
"Tomioka, Gunma, Japan",
"place",
"Place",
"F1.8",
"AS-JPN",
"1872",
"1987",
"approx.",
"The state silk-reeling mill, set up with a French engineer, trained young women who spread mechanised reeling across Japan.",
"mechanised silk reeling",
"site type: factory;raw silk",
"clothing and adornment",
"the Meiji government; Paul Brunat",
"the women reelers",
"none",
"Wikimedia Commons",
"R3",
"F1.23;F1.18;F1.19",
"high",
"",
"canon_places.csv"
],
[
"PLC214",
"Mehrgarh",
"Kachi Plain, Balochistan, Pakistan",
"place",
"Place",
"F1.9",
"AS-SAS",
"-7000",
"-2500",
"approx.",
"Mehrgarh records early farming, cotton, drilled teeth and bead-making in South Asia.",
"bead drilling;pottery;cotton",
"site type: settlement and cemetery;bead;pottery;figurine",
"food and storage;clothing and adornment",
"archaeologists (Jean-François Jarrige)",
"",
"funerary",
"open-access excavation reports",
"R2",
"F1.5",
"high",
"links: ARC137; INV156; INV100.",
"canon_places.csv"
],
[
"PLC215",
"Harappa",
"Sahiwal, Punjab, Pakistan",
"place",
"Place",
"F1.9",
"AS-SAS",
"-3300",
"-1300",
"approx.",
"Workshops at Harappa made stone beads, shell bangles, faience and seals under standard weights.",
"bead drilling;faience;shell cutting;seal carving",
"site type: city with craft quarters;carnelian bead;seal;shell bangle",
"clothing and adornment;record and writing;exchange and value",
"archaeologists (Harappa Archaeological Research Project)",
"",
"none",
"open-access excavation reports;Wikimedia Commons",
"R2",
"F1.5",
"high",
"links: ARC139; CIV048; INV173.",
"canon_places.csv"
],
[
"PLC216",
"Lothal",
"Ahmedabad district, Gujarat, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"-2400",
"-1900",
"approx.",
"Lothal had a bead workshop and a large brick basin interpreted as a dock linked to Gulf trade.",
"bead making;brick building",
"site type: town with dock and workshop;bead;seal",
"exchange and value;transport",
"archaeologists (S. R. Rao)",
"",
"none",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"medium",
"Dock interpretation debated.",
"canon_places.csv"
],
[
"PLC217",
"Zawar",
"Udaipur district, Rajasthan, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"-500",
"1800",
"approx.; mining from 1st millennium BCE",
"Retorts at Zawar show zinc distilled on an industrial scale by the medieval period, long before Europe.",
"zinc distillation;retort;mining",
"site type: mine and smelting site;retort;zinc",
"exchange and value",
"archaeometallurgists (Paul Craddock et al.)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.5;F1.22",
"medium",
"links: INV091. Distilled zinc from c. 9th c. CE, commercial scale from c. 12th c.; halted c. 1812 (Kharakwal; Craddock).",
"canon_places.csv"
],
[
"PLC218",
"Arikamedu",
"Puducherry, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"-200",
"200",
"approx.",
"Arikamedu's finds of Mediterranean amphorae and Arretine ware beside local bead-making show a port in the Roman-Indian trade.",
"bead making;trade goods",
"site type: port;amphora;Arretine sherd;bead",
"exchange and value",
"archaeologists (Mortimer Wheeler; Vimala Begley)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC219",
"Muziris",
"Muchiri; possibly Pattanam, Kerala, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"-100",
"400",
"approx.",
"Muziris was the Malabar pepper port named in the Muziris papyrus, probably located at Pattanam.",
"pepper trade;beads",
"site type: port;amphora;bead",
"exchange and value",
"classical sources; archaeologists (KCHR)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"Identification with Pattanam debated.",
"canon_places.csv"
],
[
"PLC220",
"Barygaza",
"Bharuch, Gujarat, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"-100",
"300",
"approx.",
"The Periplus describes Barygaza as a port exporting cotton cloth, indigo and agate.",
"cotton textile;agate",
"site type: port;cloth;bead",
"exchange and value",
"the Periplus of the Erythraean Sea",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_places.csv"
],
[
"PLC221",
"Calicut",
"Kozhikode, Kerala, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"1300",
"",
"approx.; ongoing",
"Calicut was a pepper and cotton-cloth port under the Zamorins, reached by Vasco da Gama in 1498, and 'calico' is named after it.",
"cotton weaving;pepper trade",
"site type: port;calico",
"exchange and value",
"historians",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13;F1.18",
"high",
"",
"canon_places.csv"
],
[
"PLC222",
"Chandni Chowk",
"Shahjahanabad, Delhi, India",
"place",
"Place",
"F1.9;F1.10",
"AS-SAS",
"1650",
"",
"approx.; ongoing",
"The market street of Shahjahanabad grew with the Mughal karkhanas that made textiles, jewellery and metalwork for court and sale.",
"goldwork;embroidery;metalwork",
"site type: market street and workshops;jewellery;embroidery",
"exchange and value;clothing and adornment",
"the Mughal court; historians",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"links: MKR044.",
"canon_places.csv"
],
[
"PLC223",
"Varanasi weavers' quarters",
"Madanpura and Peeli Kothi, Varanasi, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"1600",
"",
"approx.; ongoing",
"Weavers in Varanasi, many of them Ansari Muslims, weave Banarasi silk brocades on handlooms.",
"brocade;handloom;silk",
"site type: weavers' quarters;sari;brocade",
"clothing and adornment",
"the weaving communities",
"the weavers' indebtedness to traders",
"living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.18",
"medium",
"links: MKR046.",
"canon_places.csv"
],
[
"PLC224",
"Jamdani villages of Rupganj",
"Rupganj and Demra, Narayanganj-Dhaka, Bangladesh",
"place",
"Place",
"F1.9",
"AS-SAS",
"1700",
"",
"approx.; ongoing",
"Weavers here make jamdani, a fine cotton with supplementary-weft motifs inserted by hand, successor to Dhaka muslin.",
"supplementary weft;fine cotton;handloom",
"site type: weaving villages;jamdani sari",
"clothing and adornment",
"the weavers; UNESCO (intangible heritage: \"Traditional art of Jamdani weaving\", 2013)",
"women's thread preparation",
"living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.18",
"medium",
"links: MKR047; PRA103.",
"canon_places.csv"
],
[
"PLC225",
"Patan",
"Anhilwad Patan, Gujarat, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"1100",
"",
"approx.; ongoing",
"Salvi families in Patan weave double-ikat patola, dyeing warp and weft separately before weaving.",
"double ikat;silk",
"site type: weaving town;patola",
"clothing and adornment",
"the Salvi families",
"",
"living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.18",
"medium",
"links: MKR048; PRA108.",
"canon_places.csv"
],
[
"PLC226",
"Machilipatnam",
"Masulipatnam, Andhra Pradesh, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"1600",
"",
"approx.; ongoing",
"Machilipatnam's dyers and block-printers made the mordant-dyed chintz sought by the Dutch and English companies.",
"mordant dyeing;block printing;kalamkari",
"site type: port and dyeing town;chintz;palampore",
"clothing and adornment;exchange and value",
"the dyers; the East India companies",
"",
"living-community",
"Rijksmuseum (CC0);Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.18;F1.13",
"high",
"links: MKR049; NET055.",
"canon_places.csv"
],
[
"PLC227",
"Pulicat",
"Pazhaverkadu, Tamil Nadu, India",
"place",
"Place",
"F1.9;F1.13",
"AS-SAS",
"1613",
"1825",
"approx.",
"The VOC's Fort Geldria at Pulicat bought Coromandel chintz and also shipped enslaved people from the coast.",
"mordant dyeing;trade goods",
"site type: port and trading fort;chintz",
"exchange and value",
"the VOC; historians",
"the enslaved people shipped from the Coromandel coast",
"human-flow",
"Rijksmuseum (CC0);Wikimedia Commons",
"R3",
"F1.13;F1.18",
"medium",
"links: INS038.",
"canon_places.csv"
],
[
"PLC228",
"Santiniketan",
"Birbhum, West Bengal, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"1919",
"",
"Kala Bhavana 1919; ongoing",
"Kala Bhavana under Nandalal Bose taught art alongside local crafts and murals in an open-air setting.",
"mural;printmaking;leather craft",
"site type: art school campus;mural;print",
"ritual and belief;record and writing",
"Rabindranath Tagore; Nandalal Bose",
"the Santal and craft teachers",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: SCH028; INS032.",
"canon_places.csv"
],
[
"PLC229",
"NID Ahmedabad",
"Paldi, Ahmedabad, India",
"place",
"Place",
"F1.9",
"AS-SAS",
"1961",
"",
"founded 1961",
"The design school founded after the Eames India Report of 1958 trained designers to work with Indian craft and industry.",
"design education",
"site type: design school campus;prototype",
"tools",
"the Indian government; the Sarabhai family; Charles and Ray Eames",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"links: INS033.",
"canon_places.csv"
],
[
"PLC230",
"Jokhang and Barkhor",
"Lhasa, Tibet",
"place",
"Place",
"F1.8",
"AS-HIM",
"647",
"",
"traditional founding 7th c.; ongoing",
"The Jokhang temple and the Barkhor pilgrim circuit around it are a centre of Tibetan Buddhist devotion and trade in ritual objects.",
"metal casting;thangka painting;wood carving",
"site type: temple and market circuit;statue;thangka",
"ritual and belief;exchange and value",
"Tibetan Buddhists; UNESCO (Jokhang only, added 2000 to the Potala Palace listing)",
"",
"sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_places.csv"
],
[
"PLC231",
"Tabo Monastery",
"Spiti, Himachal Pradesh, India",
"place",
"Place",
"F1.8",
"AS-HIM",
"996",
"",
"founded 996; ongoing",
"Tabo's clay sculptures and wall paintings are among the earliest surviving in western Tibetan Buddhism.",
"clay sculpture;wall painting",
"site type: monastery;mural;clay sculpture",
"ritual and belief",
"the Guge kings; Rinchen Zangpo tradition",
"",
"sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: POL204.",
"canon_places.csv"
],
[
"PLC232",
"Patan metal workshops",
"Lalitpur, Kathmandu Valley, Nepal",
"place",
"Place",
"F1.9",
"AS-HIM",
"1400",
"",
"approx.; ongoing",
"Newar metalworkers cast gilded copper images by lost-wax methods for Nepal and Tibet.",
"lost-wax casting;gilding;repoussé",
"site type: craft town;gilt-copper image",
"ritual and belief",
"the Newar castes",
"",
"sacred;living-community",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_places.csv"
],
[
"PLC233",
"Samdzong",
"Upper Mustang, Nepal",
"place",
"Place",
"F1.8",
"AS-HIM",
"200",
"650",
"approx.",
"Cave tombs at Samdzong held a gold-and-silver funerary mask, glass beads and textiles showing trade across the Himalaya.",
"goldwork;glass beads;textile",
"site type: cave tombs;funerary mask;bead",
"ritual and belief;exchange and value",
"archaeologists (Mark Aldenderfer)",
"",
"funerary",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: ARC152.",
"canon_places.csv"
],
[
"PLC234",
"Srinagar",
"Kashmir",
"place",
"Place",
"F1.9",
"AS-HIM;AS-SAS",
"1500",
"",
"approx.; ongoing",
"Srinagar's workshops wove kani shawls and made papier-mâché and walnut carving for trade.",
"twill-tapestry weaving;papier-mâché;wood carving",
"site type: craft city;shawl;box",
"clothing and adornment;exchange and value",
"historians; the craft communities",
"",
"living-community",
"V&A collections search (link-out);Met Open Access (CC0)",
"R3",
"F1.14",
"medium",
"links: MKR045.",
"canon_places.csv"
],
[
"PLC235",
"Ban Chiang",
"Udon Thani, Thailand",
"place",
"Place",
"F1.9",
"AS-MSE",
"-2000",
"200",
"approx.; chronology debated",
"Burials at Ban Chiang contain bronze and painted pottery, and looting for the market in the 1960s-70s damaged the site.",
"bronze casting;painted pottery",
"site type: settlement and cemetery;painted jar;bronze bangle",
"ritual and belief;clothing and adornment",
"archaeologists (Chester Gorman; Pisit Charoenwongsa)",
"",
"funerary;conflict-looting",
"open-access excavation reports;collection search link-out only",
"R3",
"F1.24",
"high",
"links: ARC155.",
"canon_places.csv"
],
[
"PLC236",
"Óc Eo",
"An Giang, Vietnam",
"place",
"Place",
"F1.9;F1.13",
"AS-MSE",
"100",
"700",
"approx.",
"The port of Funan had bead and metal workshops and finds from India, China and Rome.",
"bead making;goldwork",
"site type: port town;bead;seal;coin",
"exchange and value",
"archaeologists (Louis Malleret)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"high",
"links: ARC159; POL207.",
"canon_places.csv"
],
[
"PLC237",
"Angkor",
"Siem Reap, Cambodia",
"place",
"Place",
"F1.9",
"AS-MSE",
"802",
"1431",
"approx.",
"A royal bronze foundry excavated near the Angkor Thom palace shows how Khmer images were cast, beside quarries and kilns that supplied the temples.",
"bronze casting;sandstone carving;stoneware",
"site type: royal capital and foundry;bronze image;stoneware",
"ritual and belief;rule and display",
"archaeologists (Polkinghorne et al.); UNESCO",
"",
"sacred",
"Wikimedia Commons;Met Open Access (CC0)",
"R2",
"F1.16",
"medium",
"links: POL209. Foundry excavated from 2012.",
"canon_places.csv"
],
[
"PLC238",
"Si Satchanalai kilns",
"Sawankhalok, Sukhothai, Thailand",
"place",
"Place",
"F1.9",
"AS-MSE",
"1300",
"1600",
"approx.",
"Kilns along the Yom river made celadon and painted stoneware exported across Southeast Asia.",
"celadon;cross-draught kiln",
"site type: kiln complex;celadon dish",
"food and storage;exchange and value",
"archaeologists",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.13",
"medium",
"links: POL212.",
"canon_places.csv"
],
[
"PLC239",
"Bagan",
"Pagan, Mandalay Region, Myanmar",
"place",
"Place",
"F1.9",
"AS-MSE",
"1044",
"1287",
"approx.; lacquer industry ongoing",
"Thousands of brick temples at Bagan were painted and decorated, and the town is now a centre of lacquerware.",
"brick building;wall painting;lacquer",
"site type: temple plain and craft town;mural;lacquer box",
"ritual and belief",
"Burmese kings; UNESCO",
"",
"sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16",
"high",
"links: POL210; PRA115.",
"canon_places.csv"
],
[
"PLC240",
"Hội An",
"Faifo, Quảng Nam, Vietnam",
"place",
"Place",
"F1.9;F1.13",
"AS-MSE",
"1500",
"1800",
"approx.",
"Hội An was a trading port where Japanese and Chinese merchants settled and Vietnamese ceramics were shipped.",
"trade goods;timber building",
"site type: port town;ceramic",
"exchange and value",
"historians; UNESCO",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC241",
"Khao Sam Kaeo",
"Chumphon, Thailand",
"place",
"Place",
"F1.9;F1.13",
"AS-MSE",
"-400",
"-100",
"approx.",
"Glass and stone bead workshops using South Asian techniques show an early cross-Bay of Bengal craft community.",
"glass beads;stone beads",
"site type: port settlement and workshops;bead",
"clothing and adornment;exchange and value",
"archaeologists (Bérénice Bellina)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: NET007.",
"canon_places.csv"
],
[
"PLC242",
"Leang Tedongnge",
"Maros-Pangkep, South Sulawesi, Indonesia",
"place",
"Place",
"F1.9",
"AS-ISE",
"-43500",
"",
"approx.; at least 45,500 years",
"A painting of a pig dated to at least 45,500 years ago is among the earliest known figurative images.",
"mineral pigment;painting",
"site type: cave;rock painting",
"ritual and belief",
"archaeologists (Brumm et al. 2021)",
"",
"none",
"open-access excavation reports",
"R2",
"F1.5",
"high",
"links: INV145.",
"canon_places.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
