insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PLC365",
"Altamira",
"Santillana del Mar, Cantabria, Spain",
"place",
"Place",
"F1.11",
"EU-IBE",
"-34000",
"-11000",
"approx.",
"Polychrome bison at Altamira were dismissed as fakes after their 1879 discovery until Paleolithic art was accepted in 1902.",
"mineral pigment;engraving",
"site type: painted cave;wall painting",
"ritual and belief",
"archaeologists (Marcelino Sanz de Sautuola)",
"María Sanz de Sautuola, credited with first seeing the paintings",
"sacred",
"Wikimedia Commons",
"R2",
"F1.3;F1.28a",
"high",
"links: ARC073.",
"canon_places.csv"
],
[
"PLC366",
"Lagar Velho",
"Lapedo valley, Leiria, Portugal",
"place",
"Place",
"F1.11",
"EU-IBE",
"-27000",
"",
"approx.; c. 29,000 cal BP",
"The burial of a child with ochre and a shell pendant is one of the best-studied Gravettian burials in Iberia.",
"ochre;shell pendant",
"site type: rock shelter;burial",
"ritual and belief",
"archaeologists (João Zilhão)",
"",
"funerary",
"open-access excavation reports",
"R3",
"",
"medium",
"links: ARC071.",
"canon_places.csv"
],
[
"PLC367",
"Rio Tinto",
"Minas de Riotinto, Huelva, Spain",
"place",
"Place",
"F1.11",
"EU-IBE",
"-3000",
"",
"approx.; ongoing",
"Copper and silver have been mined at Rio Tinto from prehistory through Rome to the company founded in 1873.",
"copper and silver mining;smelting",
"site type: mining district;slag",
"exchange and value",
"historians; Rio Tinto Company",
"the miners and their 1888 protest",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC368",
"Almadén",
"Ciudad Real, Spain",
"place",
"Place",
"F1.11",
"EU-IBE",
"1550",
"2003",
"approx.; ancient mining older",
"Almadén's mercury, mined partly by convicts and enslaved people, was shipped to the Americas to refine silver.",
"mercury mining;distillation",
"site type: mine;mercury",
"exchange and value",
"historians; UNESCO",
"convict and enslaved miners",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC369",
"Madinat al-Zahra",
"Córdoba, Spain",
"place",
"Place",
"F1.10",
"EU-IBE",
"936",
"1010",
"approx.",
"The caliphal palace city had workshops for carved ivory boxes, marble and textiles.",
"ivory carving;marble carving",
"site type: palace city;ivory pyxis;capital",
"rule and display",
"the Umayyad caliphs; UNESCO",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.17",
"high",
"links: POL153.",
"canon_places.csv"
],
[
"PLC370",
"Seville",
"Sevilla, Spain",
"place",
"Place",
"F1.11;F1.13",
"EU-IBE",
"1503",
"1717",
"approx.",
"Seville held the royal monopoly on trade with the Americas, and its Triana potters made tiles for both sides of the Atlantic.",
"tin-glazed tile;trade goods",
"site type: port city;tile;silver",
"exchange and value",
"historians",
"enslaved Africans in the city",
"human-flow",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"links: INS089.",
"canon_places.csv"
],
[
"PLC371",
"Lisbon",
"Lisboa, Portugal",
"place",
"Place",
"F1.11;F1.13",
"EU-IBE",
"1500",
"1755",
"approx.",
"Lisbon received Asian and African goods and enslaved Africans through the Casa da Índia until the 1755 earthquake.",
"trade goods;ivory",
"site type: port city;saltcellar;porcelain",
"exchange and value",
"historians",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: POL136.",
"canon_places.csv"
],
[
"PLC372",
"Talavera de la Reina",
"Toledo, Spain",
"place",
"Place",
"F1.11",
"EU-IBE",
"1500",
"",
"approx.; ongoing",
"Talavera's tin-glazed potters supplied tiles and wares that gave their name to Mexican talavera.",
"tin glaze;painted tile",
"site type: pottery town;tile;jar",
"food and storage;shelter",
"the potters",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.14",
"high",
"links: PRA046.",
"canon_places.csv"
],
[
"PLC373",
"Manises",
"Valencia, Spain",
"place",
"Place",
"F1.10;F1.11",
"EU-IBE",
"1300",
"1500",
"approx.",
"Manises potters made lustreware exported across Europe, including to Italian patrons.",
"lustre;tin glaze",
"site type: pottery town;lustre dish",
"food and storage;rule and display",
"historians",
"",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.14",
"high",
"",
"canon_places.csv"
],
[
"PLC374",
"Sungir",
"Vladimir, Russia",
"place",
"Place",
"F1.11",
"EU-EER",
"-32000",
"",
"approx.",
"Burials at Sungir held thousands of mammoth-ivory beads sewn on clothing.",
"ivory beads",
"site type: burials;bead;spear",
"clothing and adornment;ritual and belief",
"archaeologists (Otto Bader)",
"",
"funerary",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"",
"canon_places.csv"
],
[
"PLC375",
"Nerev End",
"Veliky Novgorod, Russia",
"place",
"Place",
"F1.11",
"EU-EER",
"950",
"1500",
"approx.",
"Excavations here found birch-bark letters and workshops of leatherworkers and jewellers.",
"birch-bark writing;leather;amber",
"site type: excavated town;birch-bark letter;shoe",
"record and writing",
"archaeologists (Artemiy Artsikhovsky)",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.28",
"high",
"links: POL142.",
"canon_places.csv"
],
[
"PLC376",
"Kremlin Armoury",
"Moscow, Russia",
"place",
"Place",
"F1.11",
"EU-EER",
"1500",
"1700",
"approx.",
"The tsars' workshops made arms, icons, goldwork and textiles, including work by Simon Ushakov.",
"goldwork;icon painting;arms",
"site type: court workshops;icon;helmet",
"rule and display;war",
"the tsars",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"links: POL143.",
"canon_places.csv"
],
[
"PLC377",
"Imperial Porcelain Factory",
"St Petersburg, Russia",
"place",
"Place",
"F1.11",
"EU-EER",
"1744",
"",
"founded 1744; ongoing",
"The factory made court porcelain and after 1917 painted agitprop designs on its stock.",
"porcelain;overglaze painting",
"site type: porcelain manufactory;plate",
"rule and display",
"the court; the Soviet state",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"high",
"",
"canon_places.csv"
],
[
"PLC378",
"Vkhutemas building",
"Myasnitskaya Street, Moscow, Russia",
"place",
"Place",
"F1.11",
"EU-EER",
"1920",
"1930",
"approx.",
"The Higher Art and Technical Studios taught Constructivist design here.",
"design education;metalwork;textile",
"site type: school building;textile;poster",
"tools",
"the Soviet state; Rodchenko; Popova",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.20",
"medium",
"links: INS058.",
"canon_places.csv"
],
[
"PLC379",
"Wieliczka Salt Mine",
"Kraków, Poland",
"place",
"Place",
"F1.11",
"EU-EER",
"1250",
"1996",
"approx.",
"Miners at Wieliczka carved chapels and statues out of rock salt.",
"salt mining;salt carving",
"site type: mine;salt sculpture",
"ritual and belief;food and storage",
"historians; UNESCO",
"",
"sacred",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC380",
"Magnitogorsk",
"Chelyabinsk Oblast, Russia",
"place",
"Place",
"F1.11",
"EU-EER;AS-NTH",
"1929",
"",
"approx.; ongoing",
"The Soviet steel city was built from 1929 largely by deported peasants and prisoners.",
"steelmaking",
"site type: steel city;steel",
"tools",
"the Soviet state",
"the deported and imprisoned labourers",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23;F1.22;F1.20",
"high",
"links: POL151.",
"canon_places.csv"
],
[
"PLC381",
"Birka",
"Björkö, Sweden",
"place",
"Place",
"F1.11;F1.13",
"EU-SCA",
"750",
"975",
"approx.",
"Graves at Birka held silks and silver from far away, and workshops made beads and combs.",
"beads;comb-making;textile",
"site type: trading town and cemetery;bead;comb;silk",
"exchange and value;clothing and adornment",
"archaeologists (Hjalmar Stolpe)",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: NET027.",
"canon_places.csv"
],
[
"PLC382",
"Hedeby",
"Haithabu, Schleswig-Holstein, Germany",
"place",
"Place",
"F1.11;F1.13",
"EU-SCA",
"800",
"1066",
"approx.",
"Hedeby's workshops made glass beads, combs and metalwork in a trading town between the Baltic and North Sea.",
"beads;comb-making;metalwork",
"site type: trading town;bead;mould",
"exchange and value",
"archaeologists; UNESCO",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_places.csv"
],
[
"PLC383",
"Oseberg ship burial",
"Tønsberg, Vestfold, Norway",
"place",
"Place",
"F1.11",
"EU-SCA",
"834",
"",
"burial 834",
"The ship burial of two women held a carved cart and sleighs, looms and tapestry fragments.",
"wood carving;weaving",
"site type: ship burial;cart;tapestry",
"ritual and belief;transport",
"archaeologists",
"",
"funerary",
"Wikimedia Commons",
"R3",
"F1.18",
"high",
"links: POL148.",
"canon_places.csv"
],
[
"PLC384",
"Falun Mine",
"Falun, Dalarna, Sweden",
"place",
"Place",
"F1.11",
"EU-SCA",
"1000",
"1992",
"approx.",
"Copper from Falun funded Sweden's empire, and its by-product became the red paint on Swedish wooden houses.",
"copper mining;pigment",
"site type: mine;copper;red paint",
"exchange and value;shelter",
"historians; UNESCO",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"links: POL149.",
"canon_places.csv"
],
[
"PLC385",
"Bryggen",
"Bergen, Norway",
"place",
"Place",
"F1.11;F1.13",
"EU-SCA",
"1360",
"1754",
"Hanseatic Kontor period",
"Hanseatic merchants at Bryggen traded stockfish for grain and goods, and runic sticks found there record everyday messages.",
"stockfish trade;timber building;runes",
"site type: wharf and trading houses;runic stick",
"exchange and value;record and writing",
"historians; UNESCO",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.13",
"high",
"links: INS088.",
"canon_places.csv"
],
[
"PLC386",
"Jokkmokk winter market",
"Jokkmokk, Sápmi, Sweden",
"place",
"Place",
"F1.11",
"EU-SCA",
"1605",
"",
"from 1605; ongoing",
"Sámi makers sell duodji at the market, which the Swedish crown set up to collect taxes.",
"duodji;antler carving;leather",
"site type: market;knife;belt",
"exchange and value",
"the Sámi; the Swedish crown",
"",
"Indigenous-community;living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_places.csv"
],
[
"PLC387",
"Kiruna",
"Kiruna, Sápmi, Sweden",
"place",
"Place",
"THEME",
"EU-SCA",
"1900",
"",
"approx.; ongoing",
"Iron-ore mining at Kiruna now requires moving the town and conflicts with Sámi reindeer herding.",
"iron-ore mining",
"site type: mine;iron ore",
"tools",
"LKAB",
"Sámi reindeer herders",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC388",
"Madjedbebe",
"Mirarr Country, Northern Territory, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-63000",
"",
"approx.; c. 65,000 years (Clarkson et al. 2017), contested",
"Ground-edge axe fragments, grindstones and ochre from Madjedbebe are dated by the excavators to around 65,000 years ago, a date other archaeologists contest.",
"ground-edge axe;ochre;grindstone",
"site type: rock shelter;axe;grindstone",
"tools;ritual and belief",
"the Mirarr; archaeologists (Chris Clarkson)",
"",
"Indigenous-community;sacred",
"community-published site (link-out)",
"R2",
"F1.5",
"medium",
"links: INV148.",
"canon_places.csv"
],
[
"PLC389",
"Carpenter's Gap",
"Windjana Gorge, Kimberley, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-47000",
"",
"approx.",
"A fragment of a ground-edge axe from Carpenter's Gap is dated to about 45,000-49,000 years ago.",
"ground-edge axe",
"site type: rock shelter;axe fragment",
"tools",
"the Bunuba; archaeologists",
"",
"Indigenous-community",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"links: INV148.",
"canon_places.csv"
],
[
"PLC390",
"Nawarla Gabarnmang",
"Jawoyn Country, Arnhem Land, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-44000",
"",
"approx.",
"Jawoyn rock shelter with a painted ceiling, a charcoal drawing about 28,000 years old and an early ground-edge axe fragment.",
"charcoal drawing;painting;ground-edge axe",
"site type: rock shelter;painting;axe fragment",
"ritual and belief;tools",
"the Jawoyn; archaeologists (Bruno David)",
"",
"sacred;Indigenous-community",
"open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_places.csv"
],
[
"PLC391",
"Budj Bim",
"Gunditjmara Country, Victoria, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-4600",
"",
"approx.; at least 6,600 years; ongoing",
"The Gunditjmara built channels, weirs and traps in lava flows to farm eels.",
"stone channel building;woven eel trap",
"site type: aquaculture landscape;eel trap;stone house",
"food and storage",
"the Gunditjmara; UNESCO",
"",
"Indigenous-community;sacred",
"community-published site (link-out)",
"R1",
"F1.5;F1.22",
"high",
"links: INV062.",
"canon_places.csv"
],
[
"PLC392",
"Willandra Lakes",
"Lake Mungo, NSW, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-40000",
"",
"approx.",
"Mungo Lady and Mungo Man, about 40,000 years old, were taken for study and later returned to their people.",
"cremation;ochre burial",
"site type: lakes landscape;burial",
"ritual and belief",
"the Paakantyi, Mutthi Mutthi and Ngiyampaa; UNESCO",
"",
"funerary;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC393",
"Murujuga",
"Burrup Peninsula, Western Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-40000",
"",
"approx.; ongoing",
"Murujuga has more than a million rock engravings, now beside heavy industry.",
"petroglyph",
"site type: rock engravings;petroglyph",
"ritual and belief",
"the Ngarda-Ngarli; UNESCO (inscribed July 2025)",
"",
"sacred;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC394",
"Wilgie Mia",
"Weld Range, Western Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-28000",
"",
"approx.; c. 30,000 years is an estimate from the volume mined (V. Winton), not a scientific date",
"Aboriginal miners dug red and yellow ochre at Wilgie Mia, traded widely.",
"ochre mining",
"site type: ochre mine;ochre",
"ritual and belief;exchange and value",
"the Wajarri Yamatji",
"",
"sacred;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.22;F1.13",
"low",
"Start date uncertain: no published dates; National Heritage List (2011) gives none; the 27,000-40,000-year figures in popular sources are unsupported.",
"canon_places.csv"
],
[
"PLC395",
"Mount William",
"Wil-im-ee Moor-ring, Victoria, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-1000",
"1840",
"approx.",
"Wurundjeri quarried greenstone at Mount William for axes traded across southeast Australia.",
"greenstone quarrying;ground axe",
"site type: stone quarry;axe",
"tools;exchange and value",
"the Wurundjeri; archaeologists (Isabel McBryde)",
"",
"sacred;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.13",
"medium",
"links: NET053.",
"canon_places.csv"
],
[
"PLC396",
"Juukan Gorge",
"Pilbara, Western Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"-46000",
"2020",
"approx.; destroyed May 2020",
"Two rock shelters were blown up by Rio Tinto in 2020 to expand an iron-ore mine.",
"",
"site type: rock shelters;stone tool",
"ritual and belief",
"the Puutu Kunti Kurrama and Pinikura",
"",
"sacred;conflict-looting;Indigenous-community",
"community-published site (link-out)",
"R2",
"F1.22;F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC397",
"Port Arthur",
"Tasmania, Australia",
"place",
"Place",
"F1.12",
"OC-AUS",
"1830",
"1877",
"approx.",
"Convicts at Port Arthur built ships and made shoes and other goods.",
"shipbuilding;shoemaking",
"site type: penal settlement;ship",
"tools",
"the colonial state; UNESCO",
"",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC398",
"Kuk Swamp",
"Wahgi valley, Papua New Guinea",
"place",
"Place",
"F1.12",
"OC-MEL",
"-8000",
"",
"approx.",
"Mounds and drainage ditches at Kuk show plant cultivation in the New Guinea highlands by about 7,000 years ago, with earlier plant use around 10,000 years ago.",
"drainage;mounding;plant cultivation",
"site type: wetland;ditch",
"food and storage",
"archaeologists (Jack Golson; Tim Denham); UNESCO",
"",
"Indigenous-community",
"open-access excavation reports",
"R3",
"F1.5",
"high",
"links: INV055.",
"canon_places.csv"
],
[
"PLC399",
"Talasea obsidian sources",
"Kutau-Bao, Willaumez Peninsula, New Britain, Papua New Guinea",
"place",
"Place",
"F1.12",
"OC-MEL",
"-20000",
"",
"approx.",
"Obsidian from Talasea was carried as far as Borneo and Fiji during the Lapita period.",
"obsidian",
"site type: obsidian source;flake",
"tools;exchange and value",
"archaeologists",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: NET046.",
"canon_places.csv"
],
[
"PLC400",
"Lapita type site",
"Site 13, Foué peninsula, Koné, New Caledonia",
"place",
"Place",
"F1.12",
"OC-MEL",
"-1100",
"-800",
"approx.",
"Pottery from the Koné site named the Lapita culture, known for its dentate-stamped designs.",
"dentate stamping",
"site type: excavated site;potsherd",
"food and storage;ritual and belief",
"archaeologists (Gifford and Shutler, 1952)",
"",
"none",
"open-access excavation reports",
"R2",
"F1.13",
"high",
"links: ARC224; CIV091.",
"canon_places.csv"
],
[
"PLC401",
"Teouma",
"Efate, Vanuatu",
"place",
"Place",
"F1.12",
"OC-MEL",
"-1000",
"-800",
"approx.; c. 3,000 years ago",
"The earliest known cemetery of the first settlers of Vanuatu held dentate-stamped Lapita pots, some used as burial vessels, and headless burials whose skulls were moved.",
"dentate stamping;shell ornament",
"site type: cemetery;Lapita pot;shell bracelet",
"ritual and belief",
"archaeologists (Stuart Bedford; Matthew Spriggs; Vanuatu Cultural Centre)",
"",
"funerary;ancestral",
"open-access excavation reports",
"R3",
"F1.16",
"high",
"links: ARC224; HOR013.",
"canon_places.csv"
],
[
"PLC402",
"Langa Langa Lagoon",
"Malaita, Solomon Islands",
"place",
"Place",
"F1.12",
"OC-MEL",
"1600",
"",
"approx.; start uncertain; ongoing",
"Langa Langa makers grind, drill and string small shell discs into shell money still used for bride price and compensation.",
"shell grinding;drilling;stringing",
"site type: lagoon villages;shell money strand",
"exchange and value;ritual and belief",
"the Langa Langa people",
"",
"living-community;Indigenous-community",
"community-published site (link-out)",
"R3",
"F1.29",
"medium",
"links: PRA214. Start date uncertain.",
"canon_places.csv"
],
[
"PLC403",
"Roi Mata's Domain",
"Efate, Lelepa and Artok, Vanuatu",
"place",
"Place",
"F1.12",
"OC-MEL",
"1600",
"",
"approx.; burial c. 1600; ongoing custom",
"The residence, death place and burial of the chief Roi Mata remain governed by oral tradition and a tabu kept by local communities.",
"oral tradition;burial",
"site type: chiefly residence and burial site;burial",
"ritual and belief",
"the local communities; UNESCO",
"",
"funerary;sacred;living-community",
"Wikimedia Commons",
"R3",
"F1.16;F1.29",
"medium",
"",
"canon_places.csv"
],
[
"PLC404",
"Kiriwina",
"Trobriand Islands, Milne Bay, Papua New Guinea",
"place",
"Place",
"F1.12",
"OC-MEL",
"1800",
"",
"approx.; ongoing",
"Kiriwina's carvers make canoe prow-boards and splashboards for voyages in the kula ring, which exchanges shell necklaces and armbands between islands.",
"wood carving;shell valuables;canoe building",
"site type: island villages;canoe prow-board;shell necklace;armband",
"exchange and value;transport",
"the Trobriand islanders; Bronisław Malinowski",
"",
"living-community;Indigenous-community",
"community-published site (link-out);collection search link-out only",
"R3",
"F1.13",
"medium",
"links: NET047.",
"canon_places.csv"
],
[
"PLC405",
"Nan Madol",
"Pohnpei, Federated States of Micronesia",
"place",
"Place",
"F1.12",
"OC-MIC",
"1180",
"1628",
"approx.; monumental phase from c. 1180-1200",
"The Saudeleur built nearly a hundred artificial islets of stacked basalt columns and coral fill for chiefly residences and tombs.",
"columnar basalt stacking;coral fill",
"site type: islet ceremonial centre;tomb;stone wall",
"ritual and belief;rule and display",
"the Pohnpeian people; UNESCO",
"the labour levied from across Pohnpei",
"sacred;funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.28a",
"high",
"links: ARC230; POL088.",
"canon_places.csv"
],
[
"PLC406",
"Leluh",
"Kosrae, Federated States of Micronesia",
"place",
"Place",
"F1.12",
"OC-MIC",
"1250",
"1850",
"approx.",
"High walls of basalt columns on Leluh island enclosed a chiefly town with compounds, canals and tombs.",
"columnar basalt stacking",
"site type: walled chiefly town;wall;tomb",
"rule and display;shelter",
"archaeologists",
"",
"sacred;funerary",
"Wikimedia Commons;open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_places.csv"
],
[
"PLC407",
"Yap stone money banks",
"Yap, Federated States of Micronesia",
"place",
"Place",
"F1.12",
"OC-MIC",
"1600",
"",
"approx.; ongoing",
"Stone money discs in Yapese village banks change owner without being moved, their history held in shared memory.",
"stone money",
"site type: village stone-money bank;stone money disc",
"exchange and value",
"the Yapese",
"",
"living-community;Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.13;F1.29",
"medium",
"",
"canon_places.csv"
],
[
"PLC408",
"House of Taga",
"San José, Tinian, Northern Mariana Islands",
"place",
"Place",
"F1.12",
"OC-MIC",
"1300",
"1700",
"approx.",
"The tallest known latte stones, two-part limestone pillars that raised Chamorro buildings, stand at the House of Taga.",
"limestone quarrying;latte building",
"site type: latte-stone site;latte stone",
"shelter",
"the Chamorro; archaeologists",
"",
"ancestral",
"Wikimedia Commons",
"R3",
"",
"medium",
"links: ARC229.",
"canon_places.csv"
],
[
"PLC409",
"Bikini Atoll",
"Marshall Islands",
"place",
"Place",
"THEME",
"OC-MIC",
"1946",
"1958",
"nuclear tests 1946-58",
"The United States tested 23 nuclear devices at Bikini after removing its people, and those who returned in the 1970s were moved out again in 1978.",
"",
"site type: nuclear test site;shipwreck",
"war",
"the United States government; UNESCO",
"the Bikinians",
"living-community",
"Wikimedia Commons",
"R3",
"F1.19a;F1.22",
"high",
"23 tests at Bikini per UNESCO; World Heritage 2010 (Bikini Atoll Nuclear Test Site).",
"canon_places.csv"
],
[
"PLC410",
"Nauru phosphate fields",
"Nauru",
"place",
"Place",
"THEME",
"OC-MIC",
"1906",
"",
"approx.; ongoing",
"Phosphate mined for fertiliser by colonial companies, with indentured Chinese and Pacific Islander labour, left most of Nauru's interior stripped.",
"phosphate mining",
"site type: mining landscape;phosphate",
"exchange and value",
"the Pacific Phosphate Company; British Phosphate Commissioners",
"the Nauruans and indentured miners",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"",
"canon_places.csv"
],
[
"PLC411",
"Taputapuātea",
"Ra'iātea, French Polynesia",
"place",
"Place",
"F1.12",
"OC-POL",
"1000",
"",
"approx.; ongoing",
"Taputapuātea's stone marae were a centre for voyaging chiefs and priests, and it is still a meeting point for canoe revival voyages.",
"stone marae building;canoe voyaging",
"site type: marae complex;marae",
"ritual and belief;transport",
"the Mā'ohi; UNESCO",
"",
"sacred;Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.13;F1.16",
"high",
"links: NET045; CIV090.",
"canon_places.csv"
],
[
"PLC412",
"Rano Raraku",
"Rapa Nui",
"place",
"Place",
"F1.12",
"OC-POL",
"1100",
"1680",
"approx.",
"Most of Rapa Nui's moai were carved from the volcanic tuff of Rano Raraku, where hundreds of unfinished figures remain.",
"tuff carving;basalt tools",
"site type: quarry;moai;basalt pick",
"ritual and belief",
"the Rapanui; archaeologists",
"",
"sacred;ancestral;Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.28a",
"high",
"links: CIV092.",
"canon_places.csv"
],
[
"PLC413",
"Orongo",
"Rapa Nui",
"place",
"Place",
"F1.12",
"OC-POL",
"1500",
"1868",
"approx.",
"The birdman ceremonial village has carved petroglyphs, and the basalt moai Hoa Hakananai'a was taken from it by a British ship's crew in 1868.",
"basalt carving;petroglyph",
"site type: ceremonial village;moai;petroglyph",
"ritual and belief",
"the Rapanui",
"",
"sacred;conflict-looting;Indigenous-community",
"British Museum collection search (link-out);Wikimedia Commons",
"R3",
"F1.24",
"high",
"Rapanui have asked for its return.",
"canon_places.csv"
],
[
"PLC414",
"Te Papa Tongarewa",
"Wellington, Aotearoa New Zealand",
"place",
"Place",
"THEME",
"OC-POL",
"1998",
"",
"opened 1998",
"The national museum is run on a bicultural partnership with Māori and leads the repatriation of Māori and Moriori ancestral remains.",
"museum display",
"site type: museum;taonga;cloak",
"rule and display",
"the New Zealand state; iwi partners",
"",
"Indigenous-community;ancestral",
"Te Papa Collections Online (CC BY where marked)",
"R2",
"F1.24",
"high",
"links: INS087.",
"canon_places.csv"
],
[
"PLC415",
"Bishop Museum",
"Honolulu, Hawaiʻi",
"place",
"Place",
"THEME",
"OC-POL",
"1889",
"",
"founded 1889",
"Founded in memory of the Hawaiian aliʻi Bernice Pauahi Bishop, the museum holds royal feather cloaks and Pacific collections.",
"museum display",
"site type: museum;feather cloak;feather image",
"rule and display",
"Charles Reed Bishop",
"",
"Indigenous-community",
"collection search link-out only",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC416",
"Wairau Bar",
"Marlborough, Aotearoa New Zealand",
"place",
"Place",
"F1.12",
"OC-POL",
"1280",
"1350",
"approx.",
"One of the earliest settlements in Aotearoa held stone adzes, moa-egg vessels and burials, whose remains were returned to Rangitāne in 2009.",
"stone adzes;moa-bone ornaments",
"site type: settlement and burial ground;adze;necklace",
"tools;ritual and belief",
"Rangitāne o Wairau; archaeologists",
"",
"funerary;ancestral;Indigenous-community",
"open-access excavation reports",
"R3",
"F1.24",
"high",
"",
"canon_places.csv"
],
[
"PLC417",
"Arahura River",
"Te Tai Poutini (West Coast), Aotearoa New Zealand",
"place",
"Place",
"F1.12",
"OC-POL",
"1300",
"",
"approx.; ongoing",
"The Arahura is a main source of pounamu (nephrite), shaped into adzes and hei-tiki and now owned by Ngāi Tahu.",
"pounamu working;abrasion",
"site type: stone source;hei-tiki;adze;mere",
"ritual and belief;tools",
"Ngāi Tahu (Ngāti Waewae)",
"",
"sacred;Indigenous-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked)",
"R3",
"F1.22",
"high",
"",
"canon_places.csv"
],
[
"PLC418",
"Keanakākoʻi",
"Mauna Kea, Hawaiʻi",
"place",
"Place",
"F1.12",
"OC-POL",
"1100",
"1800",
"approx.",
"Hawaiian adze makers worked fine basalt near the summit of Mauna Kea.",
"basalt knapping;adze making",
"site type: adze quarry;adze",
"tools",
"Native Hawaiians; archaeologists",
"",
"sacred;Indigenous-community",
"open-access excavation reports",
"R3",
"F1.22",
"medium",
"",
"canon_places.csv"
],
[
"PLC419",
"Nukuleka",
"Tongatapu, Tonga",
"place",
"Place",
"F1.12",
"OC-POL",
"-900",
"-700",
"approx.",
"Nukuleka has some of the earliest dated Lapita pottery in Polynesia.",
"dentate stamping",
"site type: settlement;potsherd",
"food and storage",
"archaeologists (David Burley)",
"",
"none",
"open-access excavation reports",
"R3",
"F1.13",
"medium",
"links: ARC224.",
"canon_places.csv"
],
[
"POL001",
"Pharaonic Egyptian state",
"Kemet; Ancient Egypt (dynastic)",
"polity",
"People",
"F1.6",
"AF-EGY;AF-NUB",
"-3100",
"-332",
"c.; conventional unification to Macedonian conquest; Seshat splits it into period polities (Old, Middle, New Kingdom, Late Period)",
"Royal and temple workshops organised stone, metal, faience, linen and papyrus production at state scale for nearly three millennia.",
"stone carving; faience; lost-wax copper-alloy casting; linen weaving; papyrus making; gold working",
"statues; reliefs; coffins; jewellery; linen; papyri",
"rule and display;ritual and belief;record and writing;clothing and adornment",
"Egyptologists; Manetho's king-list (3rd c. BCE); the state's own king-lists",
"mostly anonymous workers (Deir el-Medina a rare named exception); conscripted and enslaved labour; Nubian, Libyan and Levantine neighbours and captives; intermediate periods; present-day Egyptians' relation to the past",
"funerary;sacred;conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Brooklyn Museum (CC BY where marked);British Museum collection search (link out);Wikimedia Commons",
"R1",
"F1.5;F1.16;F1.23;F1.24",
"high",
"Dynasties grouped as DYN rows; funerary material hidden by default; many museum objects left Egypt under colonial-era partage and dealing.",
"canon_polities.csv"
],
[
"POL002",
"Kingdom of Kerma",
"Early Kush; Kerma culture state",
"polity",
"People",
"F1.6",
"AF-NUB",
"-2500",
"-1500",
"c.; Egyptian conquest c. 1500 BCE",
"Kerma's workshops made thin-walled black-topped red beakers and faience inlays and built mud-brick deffufa temples.",
"handmade ceramics; faience; mud-brick architecture; mica cut-outs",
"beakers; deffufa; funerary beds",
"rule and display;ritual and belief;shelter;food and storage",
"archaeologists (Reisner, Bonnet); Egyptian texts naming Kush",
"Egyptian hostile framing of Kush; retainers buried in royal tumuli; pastoralist neighbours; present-day Sudanese communities",
"funerary",
"Wikimedia Commons;open-access excavation reports;British Museum collection search (link out)",
"R2",
"F1.5",
"high",
"Reisner's early interpretations (Egyptian governors) were overturned; check museum captions.",
"canon_polities.csv"
],
[
"POL003",
"Kingdom of Kush (Napata and Meroë)",
"Kush; Napatan kingdom; Meroitic kingdom",
"polity",
"People",
"F1.6",
"AF-NUB;AF-EGY",
"-785",
"350",
"c.; Napatan phase to c. 300 BCE, Meroitic to c. 350 CE",
"Kushite rulers built pyramid fields and temples and Meroë smelted iron and wrote in its own Meroitic script.",
"iron smelting; sandstone building; gold working; painted ceramics; Meroitic script",
"pyramids; jewellery; painted pottery; stelae",
"rule and display;ritual and belief;record and writing;tools",
"Egyptologists and Sudan archaeologists; Kushite royal inscriptions",
"non-royal Meroitic makers; enslaved and conscripted labour; Blemmyes and other neighbours; Sudanese communities today",
"funerary;conflict-looting",
"Met Open Access (CC0);British Museum collection search (link out);Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5;F1.24",
"high",
"Ferlini's 1834 destruction of Amanishakheto's pyramid (jewellery in Berlin and Munich). Scale of Meroitic iron industry debated.",
"canon_polities.csv"
],
[
"POL004",
"Makuria",
"Christian Nubian kingdom of Dongola",
"polity",
"People",
"F1.6",
"AF-NUB",
"550",
"1500",
"c.; absorbed Nobadia by 7th c.; decline 14th–15th c.",
"Makurian churches such as Faras carried painted murals, and Nubian workshops produced a distinctive painted pottery.",
"tempera wall painting; wheel-made painted ceramics; mud-brick and stone building; Old Nubian writing",
"murals; pottery; manuscripts",
"ritual and belief;rule and display;record and writing;food and storage",
"excavation teams (Polish mission); Arabic sources on the baqt treaty",
"people sent north as tribute under the baqt; Nobadian and Alodian neighbours; non-Christian pastoralists",
"sacred",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.16",
"high",
"Faras murals split between Warsaw and Khartoum after 1960s UNESCO campaign.",
"canon_polities.csv"
],
[
"POL005",
"Mahdist State",
"Mahdiyya",
"polity",
"People",
"F1.6",
"AF-NUB",
"1885",
"1898",
"",
"The Mahdist state standardised the patched jibba tunic, banners and weapons, many of which entered museums as 1898 battlefield trophies.",
"patchwork; cotton; metalwork",
"jibba tunics; banners; swords",
"war;clothing and adornment;rule and display",
"historians; British military accounts",
"Sudanese families of the dead; enslaved people within the state; the Omdurman loot's route into collections",
"conflict-looting",
"Wikimedia Commons;British Museum collection search (link out)",
"R3",
"F1.19a;F1.24",
"high",
"Many \"Mahdist\" objects in UK museums are war loot from Omdurman.",
"canon_polities.csv"
],
[
"POL006",
"Kingdom of Aksum",
"Aksum; Axum",
"polity",
"People",
"F1.6",
"AF-HRN;WA-ARB",
"100",
"940",
"c.; 1st–10th c.",
"Aksum carved monolithic stelae, minted gold, silver and bronze coins and adopted Christianity under Ezana in the 4th century.",
"monolith quarrying and carving; coin minting; Ge'ez writing",
"stelae; coins; inscriptions",
"rule and display;ritual and belief;exchange and value;record and writing",
"historians; Periplus of the Erythraean Sea; Aksumite inscriptions",
"labour that quarried and moved stelae; Beja and other neighbours; Himyarite subjects during Aksumite rule in Yemen",
"conflict-looting",
"Wikimedia Commons;British Museum collection search (link out);open-access excavation reports",
"R1",
"F1.5;F1.13;F1.24",
"high",
"Stela taken to Rome 1937, returned 2005.",
"canon_polities.csv"
],
[
"POL007",
"Ethiopian Empire (Solomonic)",
"Abyssinia; Mängəstä Ityop'p'ya",
"polity",
"People",
"F1.6",
"AF-HRN",
"1270",
"1974",
"",
"The Solomonic court and church patronised illuminated manuscripts, icon painting and processional crosses across seven centuries.",
"parchment manuscripts; tempera icon painting; cast and forged crosses; woven and embroidered textiles",
"manuscripts; icons; crosses; royal textiles",
"rule and display;ritual and belief;record and writing;clothing and adornment",
"Ethiopian royal chronicles and the Kebra Nagast; historians",
"Muslim, Oromo, Beta Israel and southern peoples incorporated by conquest; enslaved people; objects taken at Maqdala 1868",
"sacred;conflict-looting",
"Walters Art Museum (CC0);Met Open Access (CC0);British Library digitised collections (public-domain items);Wikimedia Commons",
"R1",
"F1.16;F1.24",
"high",
"Solomonic dynasty is the same ruling house (no separate DYN row). Tabots are sacred and never displayed.",
"canon_polities.csv"
],
[
"POL008",
"Adal Sultanate",
"Adal",
"polity",
"People",
"F1.6;F1.10",
"AF-HRN",
"1415",
"1577",
"c.",
"Adal's centre Harar was walled in the 16th century and became a city of manuscripts and basketry.",
"stone and lime building; manuscript copying; coiled basketry",
"city walls; Qur'ans; baskets",
"rule and display;ritual and belief;war",
"historians; Futuh al-Habasha chronicle",
"pastoralist Somali and Afar communities; women basket-makers of Harar",
"none",
"Wikimedia Commons;British Library Endangered Archives Programme (link out; terms vary)",
"R3",
"F1.29",
"medium",
"Harar basketry is documented mostly for later periods.",
"canon_polities.csv"
],
[
"POL009",
"Kilwa Sultanate",
"Kilwa Kisiwani",
"polity",
"People",
"F1.6;F1.10",
"AF-SWA",
"960",
"1513",
"c.; traditional founding c. 10th c.; Portuguese sack 1505",
"Kilwa minted copper coins and built coral-stone mosques and the Husuni Kubwa palace set with imported ceramics.",
"coral-stone building; coin minting; imported ceramics used as architectural inlay",
"coins; mosques; palace",
"rule and display;exchange and value;ritual and belief;shelter",
"the Kilwa Chronicle; archaeologists (Chittick)",
"enslaved people traded; mainland gold and ivory producers; non-elite Swahili townspeople",
"human-flow",
"Wikimedia Commons;open-access excavation reports;British Museum collection search (link out)",
"R2",
"F1.13",
"high",
"Mahdali dynasty is a DYN row.",
"canon_polities.csv"
],
[
"POL010",
"Swahili city-states of the Lamu archipelago and Kenya coast",
"Pate; Lamu; Mombasa; Malindi",
"polity",
"People",
"F1.6;F1.10",
"AF-SWA",
"1000",
"1900",
"c.; each city had its own chronology",
"The Swahili towns produced carved wooden doors, coral-stone houses, furniture and manuscripts at the meeting of African, Arabian and Indian Ocean trades.",
"coral-stone building; woodcarving; plasterwork; manuscript copying",
"carved doors; chairs; plaster niches; manuscripts",
"shelter;rule and display;exchange and value;record and writing",
"historians; Swahili chronicles; archaeologists",
"enslaved plantation workers; mainland Mijikenda and others; women's craft",
"human-flow;living-community",
"Wikimedia Commons;Smithsonian Open Access (CC0 items);open-access excavation reports",
"R2",
"F1.13",
"medium",
"Debated as one \"polity\": a grouping of rival city-states.",
"canon_polities.csv"
],
[
"POL011",
"Sultanate of Zanzibar",
"Zanzibar",
"polity",
"People",
"F1.6;F1.10",
"AF-SWA;WA-ARB",
"1856",
"1964",
"separated from Oman 1856",
"Zanzibar's court and merchants commissioned carved doors, palaces and clove-plantation wealth built on enslaved labour.",
"woodcarving; coral-stone building; clove cultivation",
"doors; Beit al-Ajaib palace",
"rule and display;exchange and value;shelter",
"historians; the Busaidi court",
"enslaved people (slave market to 1873) and plantation workers; mainland caravans",
"human-flow",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R3",
"F1.13;F1.23",
"high",
"Link to Omani state row.",
"canon_polities.csv"
],
[
"POL012",
"Kingdom of Buganda",
"Buganda",
"polity",
"People",
"F1.6",
"AF-SWA",
"1300",
"",
"c. 14th c. start; abolished 1966, restored as a cultural kingdom 1993",
"Buganda's royal court organised barkcloth making and built the Kasubi royal tombs in thatch.",
"barkcloth beating; thatch architecture; drum making",
"barkcloth; royal drums; Kasubi tombs",
"rule and display;clothing and adornment;ritual and belief;shelter",
"Ganda court historians; Apolo Kagwa; historians",
"non-Ganda neighbours raided and subjected; bakopi commoners",
"living-community;funerary",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R2",
"F1.18;F1.29",
"high",
"Ugandan barkcloth making is on UNESCO's intangible heritage list (2008).",
"canon_polities.csv"
],
[
"POL013",
"Kingdom of Rwanda",
"Rwanda",
"polity",
"People",
"F1.6",
"AF-SWA;AF-CEN",
"1600",
"",
"c. 17th c.; monarchy abolished 1961",
"The Rwandan court patronised fine coiled basketry and the imigongo cattle-dung painted panels linked to the east of the kingdom.",
"coiled basketry; cow-dung relief painting",
"agaseke baskets; imigongo panels",
"rule and display;food and storage;shelter",
"court historians; historians",
"colonial racial categorisation of Hutu, Tutsi, Twa; Twa potters",
"living-community",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R3",
"F1.18;F1.29",
"medium",
"Imigongo origin story (Prince Kakira) is oral tradition.",
"canon_polities.csv"
],
[
"POL014",
"Mapungubwe",
"Kingdom of Mapungubwe",
"polity",
"People",
"F1.6",
"AF-SOU",
"1075",
"1220",
"c.",
"Mapungubwe elites were buried with gold foil objects including the gold rhinoceros, the earliest known gold-working in southern Africa at this scale.",
"gold foil over wooden cores; glass bead trade; ivory",
"gold rhinoceros; beads",
"rule and display;exchange and value",
"archaeologists; University of Pretoria excavations",
"commoners of the valley below the hill; the burials' descendants and apartheid-era silence about the site",
"funerary;ancestral",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.5;F1.24",
"high",
"Human remains reburied 2007; do not display burials.",
"canon_polities.csv"
],
[
"POL015",
"Great Zimbabwe",
"Great Zimbabwe state",
"polity",
"People",
"F1.6",
"AF-SOU",
"1100",
"1450",
"c.",
"Great Zimbabwe's builders raised mortarless granite enclosures and its elites handled gold, copper and imported glass beads and ceramics.",
"dry-stone walling; gold working; soapstone carving",
"enclosures; soapstone birds; ingots",
"rule and display;shelter;exchange and value;ritual and belief",
"archaeologists; colonial writers who denied African authorship",
"the Shona-speaking makers written out by colonial myth; commoners; the birds removed 1889–91",
"conflict-looting;ancestral",
"Wikimedia Commons;open-access excavation reports",
"R1",
"F1.3;F1.24",
"high",
"One bird returned from Germany (2003); the site is central to F1.3 historiography.",
"canon_polities.csv"
],
[
"POL016",
"Mutapa",
"Munhumutapa; Monomotapa",
"polity",
"People",
"F1.6",
"AF-SOU",
"1430",
"1760",
"c.",
"Mutapa's rulers controlled gold mining and trade with Swahili and Portuguese merchants in cloth and beads.",
"gold mining; alluvial panning; cloth trade",
"gold; imported cloth and beads",
"exchange and value;rule and display",
"Portuguese chroniclers; historians",
"gold miners including women and seasonal workers; captives of Portuguese prazo estates",
"human-flow",
"Wikimedia Commons",
"R3",
"F1.13;F1.22",
"medium",
"",
"canon_polities.csv"
],
[
"POL017",
"Zulu Kingdom",
"KwaZulu",
"polity",
"People",
"F1.6",
"AF-SOU",
"1816",
"1897",
"annexed by Britain 1887, to Natal 1897",
"Zulu royal authority shaped regimental shields, headrests, beadwork and dress codes.",
"cowhide shields; wood carving; glass beadwork",
"shields; headrests; beadwork",
"rule and display;war;clothing and adornment",
"Zulu oral tradition; historians",
"peoples conquered and displaced in the 1820s; women beadworkers; 1879 war loot in British collections",
"conflict-looting;living-community",
"Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.18;F1.19a",
"high",
"\"Mfecane\" framing contested.",
"canon_polities.csv"
],
[
"POL018",
"Merina Kingdom",
"Imerina; Kingdom of Madagascar",
"polity",
"People",
"F1.6",
"AF-MAD",
"1540",
"1897",
"c. 16th c. origins; unification under Andrianampoinimerina c. 1787–1810; French conquest 1895–97",
"The Merina court patronised silk lamba weaving and the timber palaces of the Rova at Antananarivo.",
"silk weaving; timber building; silversmithing",
"lamba akotifahana; Rova palaces",
"rule and display;clothing and adornment;ritual and belief",
"Tantaran ny Andriana (royal histories); historians",
"enslaved andevo who were a large share of producers; coastal Sakalava, Betsileo and other peoples",
"human-flow;funerary",
"Met Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R2",
"F1.18",
"high",
"Silk lamba also used as burial shrouds (funerary).",
"canon_polities.csv"
],
[
"POL019",
"Sakalava kingdoms",
"Menabe; Boina",
"polity",
"People",
"F1.6",
"AF-MAD",
"1600",
"1900",
"c. 17th–19th c.; French conquest",
"Sakalava royal cults kept relics of past kings (dady) and royal tombs with carved enclosures.",
"wood carving; royal relic shrines",
"tomb enclosures; relic shrines",
"ritual and belief;rule and display",
"Sakalava ritual specialists; historians (Feeley-Harnik)",
"enslaved people traded through Boina; Vezo and other neighbours",
"sacred;funerary;living-community",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"Relic shrines are sacred and active; no display.",
"canon_polities.csv"
],
[
"POL020",
"Kingdom of Kongo",
"Kongo dia Ntotila",
"polity",
"People",
"F1.6",
"AF-CEN",
"1390",
"1914",
"c.; Portuguese contact 1483; nominal kingdom to 1914",
"Kongo's court and Christian elites commissioned raffia textiles, ivory horns and crucifixes that joined Kongo and Catholic forms.",
"raffia pile and embroidered cloth; ivory carving; copper-alloy casting",
"raffia cloths; oliphants; crucifixes",
"rule and display;ritual and belief;clothing and adornment;exchange and value",
"Kongo and Portuguese written sources; historians (Thornton)",
"people enslaved and sold through Kongo's wars and ports; commoner weavers; Mbundu and other neighbours",
"human-flow;sacred",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection search (link out)",
"R1",
"F1.13;F1.16;F1.18",
"high",
"",
"canon_polities.csv"
],
[
"POL021",
"Kingdom of Loango",
"Loango",
"polity",
"People",
"F1.6",
"AF-CEN",
"1550",
"1883",
"c.; French protectorate 1883",
"Loango carvers made spiral-relief ivory tusks for European buyers depicting coastal trade, including enslaved people in coffles.",
"ivory carving in spiral relief",
"carved tusks",
"exchange and value;rule and display",
"historians; collectors' records",
"people depicted as captives; the carvers' names; Vili traders",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.14;F1.23",
"high",
"Tusks show slave coffles: content note.",
"canon_polities.csv"
],
[
"POL022",
"Kuba Kingdom",
"Bakuba; Bushoong kingdom",
"polity",
"People",
"F1.6",
"AF-CEN",
"1625",
"",
"c.; founding king Shyaam a-Mbul a-Ngoong c. 1625; kingship continues",
"The Kuba court patronised raffia cut-pile textiles, ndop royal figures and carved cups, with men weaving and women embroidering.",
"raffia weaving; cut-pile embroidery; wood carving",
"ndop figures; raffia cloths; cups; masks",
"rule and display;clothing and adornment;ritual and belief;exchange and value",
"Kuba oral histories; Emil Torday; Jan Vansina",
"subject groups (Kete, Twa); women embroiderers credited only as \"Kuba\"; colonial collecting",
"living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R1",
"F1.15;F1.18;F1.20",
"high",
"",
"canon_polities.csv"
],
[
"POL023",
"Luba Kingdom",
"Luba Empire",
"polity",
"People",
"F1.6",
"AF-CEN",
"1585",
"1889",
"c. 16th–19th c.",
"Luba officials used carved lukasa memory boards, staffs and caryatid stools to record and display royal history.",
"wood carving; bead and shell inlay",
"lukasa; stools; staffs; headrests",
"rule and display;record and writing;ritual and belief",
"Luba mnemonic specialists (Mbudye); scholars (Mary Nooter Roberts)",
"peripheral workshops such as the \"Buli Master\" (attribution debate); women titleholders",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R2",
"F1.26;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL024",
"Mangbetu Kingdom",
"Mangbetu",
"polity",
"People",
"F1.6",
"AF-CEN",
"1800",
"1890",
"c.",
"Mangbetu court style shaped harps, anthropomorphic pots and headdresses, many made for colonial-era demand.",
"pottery; wood carving; barkcloth",
"harps; figurative pots; knives",
"rule and display;play and music;clothing and adornment",
"Schildkrout and Keim; colonial collectors",
"the Azande and other neighbours; makers producing for collectors",
"living-community",
"Met Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R2",
"F1.14;F1.24",
"high",
"\"Mangbetu style\" partly a colonial-market creation.",
"canon_polities.csv"
],
[
"POL025",
"Bamum Kingdom",
"Bamoun",
"polity",
"People",
"F1.6",
"AF-CEN",
"1394",
"",
"c.; traditional founding; Sultan Ibrahim Njoya r. c. 1889–1933; kingdom continues",
"Njoya created the Bamum script and a palace workshop system for brass casting, beadwork and weaving.",
"lost-wax brass casting; beadwork; indigo-resist ndop cloth; Bamum script",
"beaded thrones; masks; script manuscripts; maps",
"rule and display;record and writing;clothing and adornment",
"Bamum chronicles; Njoya's own history",
"Grassfields neighbours; the throne Mandu Yenu given to Germany in 1908 (Berlin)",
"living-community;conflict-looting",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R1",
"F1.5;F1.24;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL026",
"Kingdom of Benin",
"Edo Kingdom; Ubinu",
"polity",
"People",
"F1.6",
"AF-GUI",
"1200",
"1897",
"c.; traditional dynasties from 13th c.; British sack 1897",
"Benin's royal guilds of brass casters (Igun Eronmwon) and ivory carvers produced plaques, heads and tusks for the Oba's court.",
"lost-wax brass casting; ivory carving; coral beadwork",
"plaques; commemorative heads; carved tusks; regalia",
"rule and display;ritual and belief;record and writing",
"Edo guilds and the Oba's court; historians",
"guilds as named makers; captives; Edo commoners; the 1897 looting",
"conflict-looting;living-community;ancestral",
"Digital Benin (open data);Met Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R1",
"F1.17;F1.23;F1.24",
"high",
"Oba dynasty (continuing) is a DYN row. Digital Benin gives object locations.",
"canon_polities.csv"
],
[
"POL027",
"Ife",
"Ile-Ife",
"polity",
"People",
"F1.6",
"AF-GUI",
"1000",
"",
"c.; florescence 12th–15th c.; the Ooni continues",
"Ife workshops cast naturalistic copper-alloy heads, modelled terracotta sculpture and made glass beads.",
"lost-wax casting of copper and zinc-brass; terracotta; glass bead making",
"heads; figures; beads",
"rule and display;ritual and belief",
"Yorùbá tradition; archaeologists (Willett)",
"present Yorùbá community; Frobenius's claim of foreign origin",
"sacred;living-community",
"Wikimedia Commons;British Museum collection search (link out);open-access excavation reports",
"R2",
"F1.3;F1.5",
"high",
"",
"canon_polities.csv"
],
[
"POL028",
"Oyo Empire",
"Ọ̀yọ́",
"polity",
"People",
"F1.6",
"AF-GUI",
"1400",
"1836",
"c.",
"Oyo's cavalry state drew wealth from cloth, horses and the sale of captives, and Shango worship shaped carved staffs.",
"wood carving; strip weaving; beadwork",
"oshe Shango staffs; cloth",
"rule and display;war;ritual and belief",
"Yorùbá historians (Samuel Johnson); historians",
"people sold into the Atlantic trade; tributary Aja and Egba; Hausa and Nupe makers",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13",
"medium",
"",
"canon_polities.csv"
],
[
"POL029",
"Asante Empire",
"Asante; Ashanti",
"polity",
"People",
"F1.6",
"AF-GUI",
"1701",
"1901",
"c.; British annexation 1901; the Asantehene continues",
"Asante royal patronage organised gold casting, brass goldweights, kente weaving and adinkra stamping.",
"gold casting; brass goldweights; kente strip weaving; adinkra stamping",
"goldweights; stools; kente; regalia",
"rule and display;exchange and value;clothing and adornment;ritual and belief",
"Asante court historians; historians (Wilks, McCaskie)",
"enslaved and tributary peoples; Fante and coastal neighbours; people sold on the coast; objects looted 1874 and 1896",
"conflict-looting;living-community;sacred",
"Met Open Access (CC0);Smithsonian Open Access (CC0 items);Wikimedia Commons;British Museum collection search (link out)",
"R1",
"F1.13;F1.18;F1.24",
"high",
"Golden Stool is sacred and never shown as an exhibit.",
"canon_polities.csv"
],
[
"POL030",
"Dahomey",
"Danxomè",
"polity",
"People",
"F1.6",
"AF-GUI",
"1600",
"1894",
"c.; French conquest 1892–94",
"Dahomey's court commissioned appliqué cloths, cast-brass figures by the Hountondji guild and earthen palace reliefs.",
"appliqué; brass casting; earthen relief",
"banners; reliefs; recades; thrones",
"rule and display;war;record and writing;ritual and belief",
"Fon royal historians; historians",
"people captured and sold to the Atlantic trade; the Agojie; 1892 French looting (26 objects returned to Benin 2021)",
"human-flow;conflict-looting",
"Wikimedia Commons;musée du quai Branly collection search (link out);open-access excavation reports",
"R1",
"F1.13;F1.19a;F1.24",
"high",
"",
"canon_polities.csv"
],
[
"POL031",
"Efik city-states of Old Calabar",
"Old Calabar",
"polity",
"People",
"F1.6",
"AF-GUI",
"1650",
"1884",
"c.; British protectorate 1884",
"Old Calabar's Ekpe society used nsibidi signs and indigo-resist ukara cloth as emblems of authority.",
"indigo resist dyeing; nsibidi signs",
"ukara cloth; masquerade dress",
"rule and display;ritual and belief;record and writing",
"historians; Antera Duke's diary; Ekpe members",
"Igbo dyers who made ukara; people sold through Calabar",
"human-flow;sacred",
"Wikimedia Commons;British Museum collection search (link out)",
"R3",
"F1.13;F1.28",
"medium",
"Debated as a polity (houses and society rather than a king). Ekpe knowledge is restricted.",
"canon_polities.csv"
],
[
"POL032",
"Hausa city-states",
"Hausa Bakwai; Kano; Katsina; Zaria",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"1000",
"1808",
"c.; incorporated into Sokoto Caliphate 1804–08",
"Kano and other Hausa cities ran indigo dye pits, leatherworking and embroidered-robe production traded across the Sahara.",
"indigo dyeing; leather tanning; embroidery",
"robes; leatherwork; dyed cloth",
"exchange and value;clothing and adornment;rule and display",
"Kano Chronicle; historians",
"enslaved workers; Fulani herders; non-Muslim neighbours",
"human-flow",
"Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.13;F1.18",
"medium",
"Kofar Mata dye pits' 1498 date is traditional.",
"canon_polities.csv"
],
[
"POL033",
"Sokoto Caliphate",
"Sokoto",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"1804",
"1903",
"",
"The caliphate's cities produced embroidered gowns, manuscripts and leather and expanded slave-based plantation production.",
"embroidery; indigo dyeing; manuscript copying",
"babban riga gowns; manuscripts; leatherwork",
"rule and display;ritual and belief;clothing and adornment;record and writing",
"historians; Sokoto scholars' writings",
"enslaved labour (a large share of the population); non-Muslim neighbours raided",
"human-flow",
"Wikimedia Commons;British Library Endangered Archives Programme (link out; terms vary)",
"R2",
"F1.13;F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL034",
"Kanem-Bornu",
"Kanem; Bornu",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"800",
"1893",
"c.; Kanem from c. 9th c.; Bornu from late 14th c.; Rabih's conquest 1893",
"Bornu scholars copied Qur'ans in a distinctive Kanembu hand, and the state traded horses and people across the Sahara.",
"manuscript copying; leatherwork; cotton weaving",
"Qur'ans; horse trappings",
"ritual and belief;record and writing;exchange and value",
"Arabic sources; Sayfawa king-lists; historians",
"people enslaved and exported north; Kotoko and other neighbours",
"human-flow",
"Wikimedia Commons;British Library digitised collections (public-domain items);British Library Endangered Archives Programme (link out; terms vary)",
"R2",
"F1.13",
"high",
"Sayfawa dynasty is a DYN row.",
"canon_polities.csv"
],
[
"POL035",
"Ghana (Wagadu)",
"Wagadu; Ghana Empire",
"polity",
"People",
"F1.6",
"AF-SAH",
"300",
"1240",
"c. 4th? to 13th century CE; dates debated; aligned with CIV007",
"Wagadu's rulers controlled gold and salt exchange described by al-Bakri in 1068.",
"gold trade; stone building",
"gold; houses",
"exchange and value;rule and display",
"al-Bakri and Arabic geographers; Soninke oral tradition; archaeologists",
"identification of the capital (Koumbi Saleh) debated; gold producers outside its control",
"living-community;human-flow",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.13",
"medium",
"Unrelated to the modern state of Ghana except by name.",
"canon_polities.csv"
],
[
"POL036",
"Mali Empire",
"Manden; Mali",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"1235",
"1600",
"c.; decline 15th–16th c.",
"Mali's rulers funded earthen mosques and scholarship at Timbuktu, and Sahelian gold under their control reached Mediterranean markets across the Sahara.",
"earthen architecture; gold trade; manuscript copying",
"mosques; manuscripts; gold",
"rule and display;ritual and belief;exchange and value;record and writing",
"Arabic writers (al-Umari, Ibn Battuta); griots and the Sunjata epic",
"enslaved people; nyamakalaw artisan groups (smiths, leatherworkers, griots); non-Muslim subjects",
"human-flow;living-community",
"Wikimedia Commons;Library of Congress (public-domain items);British Library Endangered Archives Programme (link out; terms vary)",
"R1",
"F1.13;F1.29",
"high",
"Keïta dynasty is a DYN row. Djinguereber attribution to al-Sahili is traditional. Djenné was at most an intermittent tributary of Mali (Tarikh al-Sudan says never conquered), so its mosque is not credited to Mali.",
"canon_polities.csv"
],
[
"POL037",
"Songhay Empire",
"Songhai",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"1464",
"1591",
"Moroccan invasion 1591",
"Songhay under Sonni Ali and the Askias ruled Gao and Timbuktu, where the mudbrick Tomb of Askia was built.",
"mudbrick architecture; manuscript copying",
"Tomb of Askia; manuscripts",
"rule and display;ritual and belief;record and writing",
"Timbuktu chronicles (Tarikh al-Sudan); historians",
"enslaved farming villages; Tuareg and Fulani neighbours",
"human-flow",
"Wikimedia Commons;British Library Endangered Archives Programme (link out; terms vary);Library of Congress (public-domain items)",
"R2",
"F1.13",
"high",
"Askia dynasty is a DYN row.",
"canon_polities.csv"
],
[
"POL038",
"Mossi kingdoms",
"Wagadugu; Yatenga",
"polity",
"People",
"F1.6",
"AF-SAH",
"1400",
"",
"c.; kingdoms continue under the Mogho Naba",
"Mossi political order separated ruling Nakomse from earth-priest groups, and masks belong mostly to the latter.",
"wood carving; strip weaving",
"masks; figures",
"rule and display;ritual and belief",
"historians; anthropologists",
"the Nyonyose (earlier inhabitants) who hold mask traditions; commoners",
"living-community;sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_polities.csv"
],
[
"POL039",
"Toucouleur (Umarian) state",
"Umarian Empire; Segu Tukulor",
"polity",
"People",
"F1.6;F1.10",
"AF-SAH",
"1852",
"1893",
"French conquest 1890–93",
"The treasure of Ségou, including Umar Tall's sword, was taken by French troops in 1890 and entered Paris collections.",
"metalwork; manuscripts",
"sword; manuscripts; jewellery",
"rule and display;war;ritual and belief",
"historians; French military archives",
"Bamana and other conquered peoples; the treasure's descendants",
"conflict-looting",
"Wikimedia Commons;musée du quai Branly collection search (link out)",
"R3",
"F1.19a;F1.24",
"medium",
"Sword attributed to Umar Tall returned to Senegal 2019.",
"canon_polities.csv"
],
[
"POL040",
"Carthage",
"Qart-hadasht",
"polity",
"People",
"F1.6;F1.11",
"AF-MAG;EU-GRR;EU-IBE",
"-814",
"-146",
"traditional foundation date; Roman destruction 146 BCE",
"Carthaginian workshops made glass-paste pendants, terracotta masks and purple dye, and the tophet held carved stelae.",
"core-formed glass; terracotta; purple dyeing; stone carving",
"pendants; masks; stelae",
"rule and display;ritual and belief;exchange and value",
"Greek and Roman historians; archaeologists",
"Libyan and Numidian subjects; enslaved people; Roman hostile framing",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.13",
"high",
"Tophet interpretation (child sacrifice) debated: handle with care.",
"canon_polities.csv"
],
[
"POL041",
"Fatimid Caliphate",
"Fatimids",
"polity",
"People",
"F1.10;F1.6",
"AF-MAG;AF-EGY;WA-LEV;WA-ARB",
"909",
"1171",
"",
"Fatimid Cairo's workshops produced lustreware, rock-crystal ewers, tiraz textiles and carved wood.",
"lustre ceramics; rock-crystal carving; tiraz embroidery; woodcarving",
"ewers; lustre bowls; tiraz; panels",
"rule and display;ritual and belief;clothing and adornment;exchange and value",
"historians; Fatimid sources; Cairo Geniza documents",
"Christian and Jewish artisans recorded in the Geniza; the Sunni majority; enslaved soldiers and servants",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R1",
"F1.13;F1.14;F1.17",
"high",
"Fatimid dynasty and polity are the same; no DYN row. Rock-crystal ewers dispersed from the treasury in the 1060s.",
"canon_polities.csv"
],
[
"POL042",
"Mamluk Sultanate",
"Mamluks",
"polity",
"People",
"F1.10;F1.6",
"AF-EGY;WA-LEV;WA-ARB",
"1250",
"1517",
"",
"Mamluk patrons commissioned enamelled glass lamps, inlaid brass, monumental Qur'ans and endowed complexes in Cairo.",
"enamelled glass; brass inlay with silver; illumination; stone architecture",
"mosque lamps; basins; Qur'ans",
"rule and display;ritual and belief;record and writing",
"historians; waqf documents",
"the enslaved origin of mamluks themselves; Coptic and Jewish artisans; peasants",
"human-flow",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R2",
"F1.13;F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL043",
"Omani state",
"Imamate and Sultanate of Oman; Muscat and Oman",
"polity",
"People",
"F1.10;F1.6",
"WA-ARB;AF-SWA",
"1650",
"",
"Ya'ruba expulsion of the Portuguese 1650; state continues",
"The Omani state built forts such as Nizwa and sustained silversmithing, dhow building and an Indian Ocean empire into East Africa.",
"silversmithing; dhow building; mudbrick and stone forts",
"khanjar daggers; forts; dhows",
"rule and display;war;transport;exchange and value",
"historians; Omani chronicles",
"enslaved East Africans on Omani plantations; Baluchi soldiers; Indian merchants",
"human-flow",
"Wikimedia Commons;Qatar Digital Library",
"R3",
"F1.13",
"medium",
"",
"canon_polities.csv"
],
[
"POL044",
"Teotihuacan",
"Teotihuacan state",
"polity",
"People",
"F1.7",
"AM-MES",
"-100",
"550",
"c.; collapse of centre c. 550 CE",
"Teotihuacan housed craft workshops in apartment compounds producing obsidian tools, pottery, murals and stone masks, and distributed Thin Orange ware made in southern Puebla.",
"obsidian knapping; lime-plaster mural painting; moulded ceramics; talud-tablero building",
"masks; murals; incense burners",
"rule and display;shelter;ritual and belief;tools",
"archaeologists; the later Mexica name",
"its own name and rulers unknown; foreign barrios (Oaxacan, Maya); present Nahua communities",
"sacred",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);LACMA (public-domain images);Wikimedia Commons;Mediateca INAH (link out; check terms)",
"R1",
"F1.3;F1.5",
"high",
"",
"canon_polities.csv"
],
[
"POL045",
"Monte Albán (Zapotec state)",
"Zapotec state",
"polity",
"People",
"F1.7",
"AM-MES",
"-500",
"850",
"c.",
"Monte Albán's elites commissioned carved stone slabs, effigy urns and painted tombs.",
"stone carving; moulded ceramic urns; tomb painting",
"urns; carved slabs",
"rule and display;ritual and belief",
"archaeologists (Caso, Marcus and Flannery)",
"Zapotec villages outside the capital; present Zapotec communities",
"funerary",
"Met Open Access (CC0);Wikimedia Commons;Mediateca INAH (link out; check terms)",
"R2",
"F1.5",
"high",
"",
"canon_polities.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
