insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"POL046",
"Tikal (Mutul)",
"Mutul",
"polity",
"People",
"F1.7",
"AM-MES",
"90",
"869",
"c.; dynastic count from c. 90 CE; last dated monument 869",
"Tikal's lords commissioned carved stelae and lintels, painted vessels and temple-pyramids signed by scribes and sculptors.",
"limestone carving; sapodilla-wood lintels; polychrome ceramics",
"stelae; lintels; vessels",
"rule and display;ritual and belief;record and writing",
"epigraphers (Martin and Grube); archaeologists",
"commoner farmers; captives shown on monuments; present Maya communities",
"sacred;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;LACMA (public-domain images)",
"R2",
"F1.28",
"high",
"Tikal's dynasty and polity treated as one row.",
"canon_polities.csv"
],
[
"POL047",
"Kaanul (Snake) kingdom",
"Kaan; Calakmul; Dzibanche",
"polity",
"People",
"F1.7",
"AM-MES",
"500",
"900",
"c.; seat moved from Dzibanche to Calakmul c. 635",
"The Kaanul kings commissioned codex-style painted vessels and stelae and dominated a network of client lords.",
"polychrome codex-style painting; limestone stelae",
"vessels; stelae; jade masks",
"rule and display;ritual and belief;record and writing",
"epigraphers; archaeologists",
"client cities; commoners; present Maya communities",
"sacred;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.28",
"medium",
"Dynasty and polity combined here; codex-style vessels heavily looted.",
"canon_polities.csv"
],
[
"POL048",
"Copán",
"Oxwitik",
"polity",
"People",
"F1.7",
"AM-MES;AM-CAM",
"426",
"822",
"dynasty founded by Yax K'uk' Mo' 426; last dated monument 822",
"Copán's rulers commissioned high-relief stelae and the Hieroglyphic Stairway, the longest known Maya inscription.",
"volcanic tuff carving; stucco; hieroglyphic writing",
"stelae; altars; stairway",
"rule and display;ritual and belief;record and writing",
"epigraphers; archaeologists",
"sculptors' workshops as makers; non-Maya neighbours to the east; present Ch'orti' communities",
"sacred",
"Wikimedia Commons;Penn Museum collection search (link out)",
"R2",
"F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL049",
"Tula (Tollan)",
"Toltec state",
"polity",
"People",
"F1.7",
"AM-MES",
"900",
"1150",
"c.",
"Tula's colonnaded buildings and warrior columns were later idealised by the Mexica, whose word toltecayotl meant fine craftsmanship.",
"basalt column carving; relief carving",
"atlantean columns; chacmools",
"rule and display;war",
"archaeologists; Mexica tradition",
"the gap between Mexica legend and archaeology; surrounding Otomí populations",
"none",
"Wikimedia Commons;Mediateca INAH (link out; check terms)",
"R3",
"F1.3",
"medium",
"Debated polity; much of \"Toltec\" is a Mexica retrospective.",
"canon_polities.csv"
],
[
"POL050",
"Mixtec kingdoms",
"Ñuu Savi; Tilantongo; Tututepec",
"polity",
"People",
"F1.7",
"AM-MES",
"900",
"1522",
"c.; many small kingdoms",
"Mixtec courts produced screenfold codices, cast gold jewellery and turquoise mosaics exchanged across Mesoamerica.",
"deerskin screenfold painting; lost-wax gold casting; turquoise mosaic",
"codices; jewellery; mosaic shields",
"rule and display;record and writing;ritual and belief;clothing and adornment",
"Mixtec codices themselves; scholars (Caso, Jansen and Pérez Jiménez)",
"many small ñuu reduced to one label; commoners; present Ñuu Savi communities",
"living-community",
"Wikimedia Commons;Mediateca INAH (link out; check terms);British Museum collection search (link out)",
"R2",
"F1.28;F1.26",
"high",
"Codex Zouche-Nuttall is in the British Museum; images via BM link-out.",
"canon_polities.csv"
],
[
"POL051",
"Mexica and the Triple Alliance",
"Aztec Empire; Excan Tlahtoloyan",
"polity",
"People",
"F1.7",
"AM-MES",
"1428",
"1521",
"",
"Tenochtitlan's tribute system brought feather mosaics, goldwork and textiles to the capital, where amanteca featherworkers and stone carvers served the rulers.",
"feather mosaic; stone sculpture; lost-wax goldwork; tribute cloth",
"featherwork shields and headdresses; sculpture; codices",
"rule and display;ritual and belief;exchange and value;war",
"colonial chroniclers (Sahagún); Nahua authors; archaeologists",
"tributary peoples; the allies Texcoco and Tlacopan; captives; Tlaxcala and other enemies",
"sacred;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;LACMA (public-domain images);Mediateca INAH (link out; check terms)",
"R1",
"F1.13;F1.17;F1.24",
"high",
"\"Aztec\" is a later scholarly label.",
"canon_polities.csv"
],
[
"POL052",
"Tlaxcala",
"Tlaxcallan",
"polity",
"People",
"F1.7",
"AM-MES;AM-LAT",
"1300",
"1821",
"c.; independent until 1519, then an allied Indigenous province under Spain with privileges until independence",
"Tlaxcalan painters made the Lienzo de Tlaxcala around 1552 to record their alliance with the Spanish.",
"painting on cloth; pictorial history",
"lienzos; codices",
"rule and display;record and writing",
"Tlaxcalan cabildo; historians",
"Tlaxcalans framed as \"traitors\"; commoners; lost original lienzo",
"none",
"Wikimedia Commons;Mediateca INAH (link out; check terms)",
"R3",
"F1.3;F1.28",
"medium",
"End date approximate; verify.",
"canon_polities.csv"
],
[
"POL053",
"Tarascan state",
"Purépecha; Irechecua",
"polity",
"People",
"F1.7",
"AM-MES",
"1350",
"1530",
"",
"The Tarascan state worked copper-bronze and gold-silver alloys and built yácata platforms, later hosting colonial featherwork and lacquer.",
"copper-bronze metallurgy; stone building; feather mosaic; lacquer",
"bells; tweezers; yácatas",
"rule and display;tools;ritual and belief",
"Relación de Michoacán; archaeologists",
"subject Otomí and Nahua groups; present P'urhépecha communities",
"living-community",
"Wikimedia Commons;Mediateca INAH (link out; check terms)",
"R2",
"F1.5",
"high",
"",
"canon_polities.csv"
],
[
"POL054",
"Coclé chiefdoms",
"Gran Coclé; Sitio Conte",
"polity",
"People",
"F1.7",
"AM-CAM",
"500",
"1520",
"c.",
"Coclé chiefs were buried with embossed gold plaques and polychrome pottery at sites such as Sitio Conte.",
"gold repoussé; tumbaga casting; polychrome ceramics",
"plaques; pendants; plates",
"rule and display;ritual and belief",
"archaeologists (Lothrop)",
"debated as polity; the buried people; present Ngäbe and Guna communities",
"funerary;conflict-looting",
"Wikimedia Commons;Penn Museum collection search (link out)",
"R3",
"F1.5",
"medium",
"Chiefdoms, not a state in Seshat terms.",
"canon_polities.csv"
],
[
"POL055",
"Taíno cacicazgos of Hispaniola",
"Taíno chiefdoms",
"polity",
"People",
"F1.7",
"AM-CAR",
"1200",
"1520",
"c.; destroyed by Spanish conquest",
"Taíno chiefs used carved duhos, cemí figures and cotton belts in rituals of authority.",
"wood carving; stone carving; cotton weaving; shell inlay",
"duhos; cemís; belts",
"rule and display;ritual and belief",
"Spanish chroniclers (Pané); archaeologists",
"people killed or enslaved after 1492; present Taíno revival communities",
"sacred;Indigenous-community",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.16;F1.24",
"medium",
"Debated polity (chiefdoms).",
"canon_polities.csv"
],
[
"POL056",
"Muisca Confederation",
"Muisca",
"polity",
"People",
"F1.7",
"AM-AND",
"800",
"1540",
"c.",
"Muisca goldsmiths cast tunjo votive figures and the Muisca raft by lost-wax in tumbaga.",
"lost-wax tumbaga casting; cotton textiles",
"tunjos; Muisca raft",
"ritual and belief;exchange and value",
"Spanish chroniclers; Museo del Oro; archaeologists",
"debated as confederation; commoners; present Muisca cabildos",
"sacred;Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.16",
"medium",
"",
"canon_polities.csv"
],
[
"POL057",
"Moche polities",
"Mochica",
"polity",
"People",
"F1.7",
"AM-AND",
"100",
"800",
"c.; northern and southern Moche may have been separate polities",
"Moche workshops made mould-made portrait and scene vessels and gilded copper regalia such as the Sipán burials.",
"mould-made ceramics; slip painting; gilded copper; alloy depletion gilding",
"portrait vessels; ear spools; nose ornaments",
"rule and display;ritual and belief;clothing and adornment",
"archaeologists (Larco, Alva, Donnan)",
"commoners; victims of sacrifice shown in art; present north-coast communities",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;LACMA (public-domain images)",
"R2",
"F1.3;F1.5",
"high",
"Debated polity; Sipán is a funerary context.",
"canon_polities.csv"
],
[
"POL058",
"Wari",
"Huari",
"polity",
"People",
"F1.7",
"AM-AND",
"600",
"1000",
"c.",
"Wari administrative centres used standardised tapestry tunics and early khipu to rule the central Andes.",
"interlocking tapestry; khipu cord recording; stone and adobe building",
"tunics; khipu; figurines",
"rule and display;record and writing;clothing and adornment",
"archaeologists",
"local populations under Wari; the weavers",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5;F1.18;F1.28",
"high",
"Debated as empire vs network.",
"canon_polities.csv"
],
[
"POL059",
"Tiwanaku",
"Tiahuanaco",
"polity",
"People",
"F1.7",
"AM-AND",
"500",
"1000",
"c.",
"Tiwanaku carved andesite gateways and monoliths, and its ritual networks spread tapestry, snuff trays and keros.",
"andesite and sandstone carving; tapestry; wooden keros",
"Gateway of the Sun; monoliths; snuff trays",
"rule and display;ritual and belief;clothing and adornment",
"archaeologists",
"Aymara present community; periphery colonies",
"sacred",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5",
"high",
"Debated polity.",
"canon_polities.csv"
],
[
"POL060",
"Chimor",
"Chimú kingdom",
"polity",
"People",
"F1.7",
"AM-AND",
"900",
"1470",
"",
"Chimú rulers built Chan Chan with carved adobe friezes and ran metal and textile workshops whose smiths the Inca later relocated to Cusco.",
"adobe relief; blackware; sheet metal; featherwork; textiles",
"friezes; blackware vessels; ear spools",
"rule and display;clothing and adornment;exchange and value",
"archaeologists; colonial chroniclers",
"smiths deported by the Inca; commoners; present Mochica-descended communities",
"funerary",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5;F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL061",
"Inca (Tawantinsuyu)",
"Inka Empire",
"polity",
"People",
"F1.7",
"AM-AND",
"1438",
"1533",
"conventional date for Pachacuti; Vilcabamba resistance to 1572",
"The Inca state recorded tribute on khipu, commissioned fine cumbi cloth from specialists and built fitted-stone masonry and roads.",
"khipu; interlocking tapestry (cumbi); ashlar masonry; metalwork",
"tunics; khipu; aryballos; roads",
"rule and display;record and writing;clothing and adornment;transport",
"colonial chroniclers (Guaman Poma, Garcilaso); archaeologists",
"mitmaqkuna resettled peoples; aqllakuna and yanakuna labour; Amazonian neighbours",
"sacred;living-community",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;Library of Congress (public-domain items)",
"R1",
"F1.5;F1.17;F1.18;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL062",
"Cahokia",
"Cahokia polity",
"polity",
"People",
"F1.7",
"AM-EWD",
"1050",
"1350",
"c.",
"Cahokia's builders raised Monks Mound and its elites used copper repoussé, shell and chunkey stones in Mississippian ritual.",
"earthwork building; copper repoussé; marine shell engraving; stone polishing",
"mounds; chunkey stones; gorgets",
"rule and display;ritual and belief;play and music",
"archaeologists",
"debated as state or paramount chiefdom; outlying farmers; descendant nations (Osage, Quapaw and others)",
"sacred;Indigenous-community;funerary",
"Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R2",
"F1.3",
"medium",
"Debated polity; not in Seshat as a state.",
"canon_polities.csv"
],
[
"POL063",
"Powhatan paramount chiefdom",
"Tsenacommacah",
"polity",
"People",
"F1.7",
"AM-EWD",
"1570",
"1646",
"c.",
"Powhatan's paramountcy collected tribute in copper, shell beads and deerskins, and \"Powhatan's Mantle\" survives in Oxford.",
"deerskin sewing; shell beadwork; copper trade",
"mantles; shell beads",
"rule and display;exchange and value",
"English colonists (Smith, Strachey); historians",
"women producers; communities outside Powhatan's tribute; present Virginia tribes",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.13;F1.24",
"medium",
"Mantle identification with Powhatan is traditional.",
"canon_polities.csv"
],
[
"POL064",
"Haudenosaunee Confederacy",
"Iroquois Confederacy; Five (later Six) Nations",
"polity",
"People",
"F1.7",
"AM-EWD",
"1450",
"",
"c.; founding date debated (12th–16th c.); continues",
"The Haudenosaunee recorded agreements in wampum belts and developed a beadwork economy that continues today.",
"shell wampum; glass beadwork; wood and bark",
"wampum belts; beaded bags; masks",
"rule and display;record and writing;exchange and value;ritual and belief",
"the Haudenosaunee themselves (Great Law of Peace); historians",
"women's clan authority; Wendat and other neighbours; masks that must not be shown",
"sacred;Indigenous-community;living-community",
"community-published site;Smithsonian Open Access (CC0 items)",
"R2",
"F1.26;F1.24",
"high",
"Medicine-society masks: do not display (Haudenosaunee policy).",
"canon_polities.csv"
],
[
"POL065",
"Cherokee Nation",
"Tsalagi",
"polity",
"People",
"F1.7",
"AM-EWD",
"1794",
"",
"c.; national council from 1790s; constitution 1827; continues",
"The Cherokee Nation printed a bilingual newspaper from 1828 in Sequoyah's syllabary, one of the rare scripts invented by one person.",
"syllabary; type founding; printing; basket weaving",
"Cherokee Phoenix; syllabary; baskets",
"rule and display;record and writing",
"Cherokee Nation; historians",
"enslaved African Americans held by Cherokee planters; forced removal (1838); Eastern Band",
"human-flow;living-community",
"Library of Congress (public-domain items);Smithsonian Open Access (CC0 items);community-published site",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL066",
"Chaco system",
"Chaco Canyon; Ancestral Pueblo great houses",
"polity",
"People",
"F1.7",
"AM-WST",
"850",
"1150",
"c.",
"Chacoan great houses concentrated turquoise, macaw feathers and cylinder jars that held cacao.",
"masonry; turquoise working; black-on-white pottery",
"great houses; cylinder jars; turquoise",
"rule and display;ritual and belief;shelter",
"archaeologists",
"debated polity; outlying communities; present Pueblo nations' own histories",
"sacred;Indigenous-community",
"Smithsonian Open Access (CC0 items);Wikimedia Commons",
"R3",
"F1.3;F1.26",
"medium",
"Debated polity.",
"canon_polities.csv"
],
[
"POL067",
"Hudson's Bay Company",
"HBC",
"polity",
"People",
"F1.7;F1.13",
"AM-ARC;AM-EWD;AM-WST;AM-NWC",
"1670",
"",
"chartered 1670; governed Rupert's Land until 1870; continues as a retailer",
"The company's trade posts reshaped Indigenous making with point blankets, glass beads, metal tools and demand for furs.",
"fur trapping; trade blankets; glass beads; metal tools",
"point blankets; beaded garments; trade guns",
"exchange and value;clothing and adornment;tools",
"the company's charter; historians",
"Cree, Dene, Métis and Inuit trappers and wives who processed furs; environmental cost",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.13;F1.22;F1.23",
"high",
"Company-state debated.",
"canon_polities.csv"
],
[
"POL068",
"Russian-American Company",
"RAC",
"polity",
"People",
"F1.7;F1.13",
"AM-ARC;AM-NWC",
"1799",
"1867",
"sale of Alaska 1867",
"The company compelled Unangan and Alutiiq hunters to take sea otters, and collected their gut parkas and bentwood hats.",
"sea-otter hunting; gut-skin sewing; bentwood",
"gut parkas; bentwood hats; baidarkas",
"exchange and value;clothing and adornment;transport",
"historians; Russian archives",
"coerced Unangan and Alutiiq labour; Tlingit resistance",
"Indigenous-community",
"Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL069",
"Viceroyalty of New Spain",
"Nueva España",
"polity",
"People",
"F1.7;F1.13",
"AM-LAT;AM-MES;AM-CAR;AS-ISE",
"1535",
"1821",
"",
"New Spain's guild ordinances and markets organised featherwork mosaics, folding screens, Puebla tin-glaze, casta paintings and goods from the Manila galleon.",
"feather mosaic; tin-glazed earthenware; enconchado; silver mining",
"biombos; Talavera; casta paintings; featherwork",
"rule and display;ritual and belief;exchange and value",
"the Spanish Crown; historians",
"Indigenous and African artisans excluded from guild mastership; enslaved miners; the Philippines governed from Mexico",
"human-flow;conflict-looting",
"Met Open Access (CC0);LACMA (public-domain images);Wikimedia Commons;Library of Congress (public-domain items)",
"R1",
"F1.13;F1.14;F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL070",
"Viceroyalty of Peru",
"Virreinato del Perú",
"polity",
"People",
"F1.7",
"AM-LAT;AM-AND",
"1542",
"1824",
"",
"Peru's silver from Potosí, worked under the forced mita, financed Cusco School painting, colonial tapestries and queros.",
"silver mining and minting; oil painting; tapestry; lacquered wood",
"coins; paintings; queros; tapestries",
"rule and display;exchange and value;ritual and belief",
"the Spanish Crown; historians",
"mita labourers; enslaved Africans; Andean painters' anonymity",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons;Brooklyn Museum (CC BY where marked)",
"R1",
"F1.13;F1.22;F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL071",
"Viceroyalty of New Granada",
"Nueva Granada",
"polity",
"People",
"F1.7",
"AM-LAT;AM-AND",
"1739",
"1819",
"first created 1717, suspended 1723, re-established 1739",
"New Granada's workshops in Quito and Pasto produced polychrome sculpture and barniz de Pasto (mopa-mopa resin) decoration.",
"polychrome wood sculpture; mopa-mopa resin; gold mining",
"sculpture; lacquered boxes",
"ritual and belief;rule and display;exchange and value",
"the Spanish Crown; historians",
"enslaved African miners; Indigenous barniz makers",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL072",
"Colonial Brazil",
"State of Brazil; Portuguese America",
"polity",
"People",
"F1.7",
"AM-LAT;AM-AMZ",
"1549",
"1815",
"Governor-General 1549; raised to kingdom 1815",
"Colonial Brazil's sugar and gold economies, built on enslaved African labour, funded the gilded churches of Bahia and Minas Gerais and sculptors such as Aleijadinho.",
"gilded woodcarving; soapstone sculpture; sugar production",
"altarpieces; church sculpture",
"ritual and belief;rule and display;exchange and value",
"the Portuguese Crown; historians",
"enslaved Africans and their descendants, many of them makers; Indigenous peoples",
"human-flow",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R2",
"F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL073",
"Quilombo dos Palmares",
"Palmares",
"polity",
"People",
"F1.7",
"AM-LAT",
"1605",
"1694",
"c.",
"Palmares was a maroon polity of formerly enslaved people whose settlements produced their own pottery and farmed the Serra da Barriga.",
"pottery; agriculture; palisade building",
"ceramics; settlements",
"shelter;food and storage;rule and display",
"historians; archaeologists; Afro-Brazilian memory",
"debated as a \"kingdom\"; Indigenous allies; people it held in servitude (debated)",
"human-flow;living-community",
"Wikimedia Commons;open-access excavation reports",
"R3",
"F1.23;F1.29",
"medium",
"",
"canon_polities.csv"
],
[
"POL074",
"Jamaican Maroons",
"Windward and Leeward Maroons",
"polity",
"People",
"F1.7",
"AM-CAR",
"1655",
"",
"c.; treaties 1739; communities continue",
"Maroon communities who escaped slavery kept the abeng horn, Kromanti ritual and their own drums.",
"horn signalling; drumming; plant knowledge",
"abeng; drums",
"rule and display;play and music;ritual and belief",
"Maroon communities; historians",
"people returned to slavery under the treaties; women's leadership (Nanny)",
"living-community;sacred;human-flow",
"Wikimedia Commons;community-published site",
"R3",
"F1.29",
"medium",
"",
"canon_polities.csv"
],
[
"POL075",
"Haiti",
"Ayiti; Kingdom of Haiti (1811–20)",
"polity",
"People",
"F1.7",
"AM-CAR",
"1804",
"",
"independence 1804; northern kingdom of Henri Christophe 1811–20",
"Independent Haiti built the Citadelle Laferrière and the Sans-Souci palace and later became a centre of painting and Vodou flag-making.",
"masonry fortification; painting; sequin-work",
"Citadelle; Vodou flags; paintings",
"rule and display;war;ritual and belief",
"Haitian state; historians",
"forced labour used by Christophe; the indemnity paid to France",
"living-community",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R2",
"F1.19a",
"high",
"",
"canon_polities.csv"
],
[
"POL076",
"Mexico, post-revolutionary state",
"Mexican state 1920–1940",
"polity",
"People",
"F1.7",
"AM-LAT;AM-MES",
"1920",
"1940",
"Obregón to Cárdenas",
"The Ministry of Education under Vasconcelos commissioned public murals, and the state promoted \"arte popular\" through the 1921 exhibition and craft policy.",
"fresco mural painting; ceramics; lacquer; textiles",
"murals; popular-art collections; posters",
"rule and display;record and writing",
"the Mexican state; historians",
"Indigenous makers turned into national symbols; women artists; rural producers",
"none",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R1",
"F1.17;F1.20",
"high",
"",
"canon_polities.csv"
],
[
"POL077",
"Cuba (revolutionary state)",
"Republic of Cuba since 1959",
"polity",
"People",
"F1.7",
"AM-CAR",
"1959",
"",
"continues",
"The Cuban state's film institute ICAIC and solidarity organisation OSPAAAL produced screen-printed posters that circulated worldwide.",
"screen printing; offset lithography",
"film posters; solidarity posters",
"rule and display;record and writing",
"the Cuban state; design historians",
"designers' names under state institutions; censorship",
"none",
"Wikimedia Commons;Library of Congress (public-domain items)",
"R2",
"F1.4;F1.20",
"medium",
"",
"canon_polities.csv"
],
[
"POL078",
"United States (federal craft and Indian arts policy)",
"USA",
"polity",
"People",
"F1.7;THEME",
"AM-EWD;AM-WST;AM-ARC;AM-NWC;OC-POL",
"1776",
"",
"continues",
"US federal policy both suppressed Native making (boarding schools) and regulated it through the Indian Arts and Crafts Board (1935) and the Indian Arts and Crafts Act (1990).",
"all media; certification and labelling law",
"Native arts; WPA posters; federal buildings",
"rule and display;exchange and value",
"the US state; historians",
"Native nations as sovereigns; enslaved makers before 1865; Hawaiian and Pacific peoples",
"Indigenous-community;human-flow",
"Library of Congress (public-domain items);Smithsonian Open Access (CC0 items);NYPL Digital Collections (public-domain items);Digital Public Library of America",
"R2",
"F1.17;F1.24;F1.26",
"high",
"",
"canon_polities.csv"
],
[
"POL079",
"Canada (Inuit art co-operatives)",
"Dominion of Canada",
"polity",
"People",
"F1.7",
"AM-ARC;AM-EWD;AM-NWC",
"1867",
"",
"continues",
"Canadian federal policy from 1949 promoted Inuit carving and, from 1959, printmaking through co-operatives such as Kinngait, while residential schools and relocations disrupted communities.",
"soapstone carving; stonecut and stencil printmaking",
"carvings; prints",
"exchange and value;rule and display",
"Canadian government; Canadian Handicrafts Guild; historians",
"Inuit authorship under co-op branding; disc-number system; potlatch ban on the Northwest Coast (1884–1951)",
"Indigenous-community",
"Wikimedia Commons",
"R2",
"F1.17;F1.23;F1.26",
"high",
"",
"canon_polities.csv"
],
[
"POL080",
"Danish colonial Greenland",
"Royal Greenland Trade Department (KGH)",
"polity",
"People",
"F1.7;F1.11",
"AM-ARC;EU-SCA",
"1721",
"1953",
"mission 1721; KGH trade monopoly from 1776; colony status ended 1953",
"Danish trade monopoly supplied glass beads and bought Greenlandic products, shaping Kalaallit beaded collars and carvings for sale.",
"glass beadwork; skin sewing; tupilak carving",
"beaded collars; tupilaat; kayaks",
"exchange and value;clothing and adornment",
"Danish state; historians",
"Kalaallit authority over their own economy; East and North Greenland communities",
"Indigenous-community",
"Wikimedia Commons;SMK Denmark (public domain)",
"R3",
"F1.13;F1.14",
"medium",
"",
"canon_polities.csv"
],
[
"POL081",
"Marajoara chiefdoms",
"Marajoara culture",
"polity",
"People",
"F1.7",
"AM-AMZ",
"400",
"1400",
"c.",
"Marajó Island communities made large polychrome and incised funerary urns on earthen mounds.",
"polychrome and incised pottery; mound building",
"funerary urns; tangas",
"ritual and belief;rule and display",
"archaeologists (Roosevelt, Schaan)",
"debated as polity; present Amazonian descendants",
"funerary",
"Wikimedia Commons",
"R3",
"F1.3",
"medium",
"Debated polity.",
"canon_polities.csv"
],
[
"POL082",
"Tapajó",
"Santarém culture",
"polity",
"People",
"F1.7",
"AM-AMZ",
"1000",
"1600",
"c.",
"The Tapajó centre at Santarém made caryatid vessels and green-stone muiraquitã amulets traded across Amazonia.",
"modelled pottery; greenstone carving",
"caryatid vessels; muiraquitã",
"ritual and belief;exchange and value",
"archaeologists; Portuguese chroniclers",
"debated as polity; people later enslaved by Portuguese",
"none",
"Wikimedia Commons",
"R3",
"F1.3",
"medium",
"Debated polity.",
"canon_polities.csv"
],
[
"POL083",
"Hawaiian Kingdom",
"Ke Aupuni Hawaiʻi",
"polity",
"People",
"F1.12",
"OC-POL",
"1795",
"1893",
"unification 1795–1810; overthrow 1893",
"Hawaiian rulers commissioned feather cloaks and helmets and later Kalākaua revived hula and built ʻIolani Palace.",
"featherwork on olonā netting; kapa beating; wood carving",
"ʻahuʻula; mahiole; kapa; palace",
"rule and display;ritual and belief;clothing and adornment",
"Hawaiian aliʻi and historians; Kamakau",
"makaʻāinana commoners who gathered feathers; kapu system's losers; the overthrow",
"sacred;Indigenous-community",
"community-published site;Wikimedia Commons;Smithsonian Open Access (CC0 items)",
"R1",
"F1.16;F1.24",
"high",
"Kamehameha dynasty folded into this row.",
"canon_polities.csv"
],
[
"POL084",
"Tuʻi Tonga maritime polity",
"Tuʻi Tonga; \"Tongan maritime empire\"",
"polity",
"People",
"F1.12",
"OC-POL;OC-MEL",
"950",
"1865",
"c.; last Tuʻi Tonga died 1865",
"The Tuʻi Tonga lineage built terraced stone tombs (langi) and drew fine mats, barkcloth and canoes through networks with Samoa and Fiji.",
"coral-limestone tomb building; ngatu barkcloth; fine mats; canoe building",
"langi; ngatu; kie mats",
"rule and display;exchange and value;transport",
"Tongan oral histories; archaeologists",
"debated as \"empire\"; Fijian canoe builders; commoners",
"funerary;ancestral",
"Wikimedia Commons;Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked)",
"R2",
"F1.13;F1.18",
"medium",
"Debated polity.",
"canon_polities.csv"
],
[
"POL085",
"Kingdom of Tonga",
"Puleʻanga Fakatuʻi ʻo Tonga",
"polity",
"People",
"F1.12",
"OC-POL",
"1875",
"",
"constitution 1875 under George Tupou I; continues",
"The constitutional monarchy maintained ngatu barkcloth and ta'ovala mats as royal and national dress.",
"barkcloth; pandanus weaving",
"ngatu; taʻovala",
"rule and display;clothing and adornment;exchange and value",
"the Tongan state; historians",
"women's barkcloth groups (kautaha) as makers",
"living-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked);Wikimedia Commons",
"R3",
"F1.18",
"high",
"Tupou dynasty covered here.",
"canon_polities.csv"
],
[
"POL086",
"Samoan paramount titles",
"Tafaʻifā; Tui Manuʻa",
"polity",
"People",
"F1.12",
"OC-POL",
"1000",
"1900",
"c.; dates approximate",
"Samoan chiefly authority circulated fine mats (ʻie tōga) as the highest exchange valuables.",
"pandanus fine-mat weaving; tattooing",
"ʻie tōga; tatau",
"exchange and value;rule and display;clothing and adornment",
"Samoan orators; historians",
"debated as a polity (distributed matai system); women weavers",
"living-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked)",
"R3",
"F1.13;F1.18",
"low",
"Samoa was not a state in Seshat terms; flagged for review.",
"canon_polities.csv"
],
[
"POL087",
"Tahiti (Pōmare kingdom)",
"Kingdom of Tahiti",
"polity",
"People",
"F1.12",
"OC-POL",
"1788",
"1880",
"French annexation 1880",
"The Pōmare rulers allied with missionaries, and older ritual images were burned while barkcloth and new textiles continued.",
"barkcloth; featherwork; tapa",
"tapa; mourner's costume (heva)",
"rule and display;ritual and belief;clothing and adornment",
"missionary accounts; historians",
"arioi society; people whose ritual objects were destroyed or collected",
"sacred;Indigenous-community",
"Wikimedia Commons;Te Papa Collections Online (CC BY where marked)",
"R3",
"F1.16;F1.24",
"medium",
"",
"canon_polities.csv"
],
[
"POL088",
"Saudeleur polity (Pohnpei)",
"Saudeleur dynasty",
"polity",
"People",
"F1.12",
"OC-MIC",
"1100",
"1628",
"c.; dates debated",
"The Saudeleur rulers built Nan Madol from stacked columnar basalt on artificial islets.",
"columnar basalt construction; coral fill",
"Nan Madol islets",
"rule and display;shelter;ritual and belief",
"Pohnpeian oral history; archaeologists",
"workers who moved the basalt; later Nahnmwarki chiefdoms",
"ancestral;funerary",
"Wikimedia Commons",
"R3",
"F1.3;F1.28",
"medium",
"Dynasty and polity combined.",
"canon_polities.csv"
],
[
"POL089",
"Bau chiefdom and Kingdom of Viti",
"Bau; Kubuna",
"polity",
"People",
"F1.12",
"OC-MEL;OC-POL",
"1760",
"1874",
"c.; Kingdom of Viti 1871–74 under Cakobau",
"Bau's chiefs commanded large drua double canoes and exchanges of barkcloth and whale ivory.",
"canoe building; masi barkcloth; whale-ivory carving",
"drua; masi; tabua",
"rule and display;transport;exchange and value",
"Fijian oral histories; historians",
"Lau and Tongan canoe builders; commoners; indentured Indian labour after 1879",
"living-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked);Wikimedia Commons",
"R3",
"F1.13",
"low",
"Debated polity.",
"canon_polities.csv"
],
[
"POL090",
"Commonwealth of Australia (Indigenous arts policy)",
"Australia",
"polity",
"People",
"F1.12;THEME",
"OC-AUS",
"1901",
"",
"continues",
"The Australian state removed Aboriginal children and suppressed culture, then from 1973 funded Aboriginal art through the Aboriginal Arts Board and art centres.",
"acrylic painting; bark painting; fibre",
"paintings; art-centre production",
"rule and display;exchange and value",
"the Australian state; historians",
"Stolen Generations; art-centre artists' copyright; Torres Strait Islanders",
"Indigenous-community;sacred",
"Museums Victoria Collections (CC BY or public domain where marked);Wikimedia Commons",
"R2",
"F1.17;F1.24;F1.26",
"high",
"Papunya Tula began 1971 with a school teacher; check claims about government role.",
"canon_polities.csv"
],
[
"POL091",
"New Zealand (colony and Dominion)",
"Aotearoa New Zealand state",
"polity",
"People",
"F1.12",
"OC-POL",
"1840",
"",
"Treaty of Waitangi 1840; continues",
"The New Zealand state confiscated Māori land and later, under Āpirana Ngata, founded the School of Māori Arts and Crafts at Rotorua (1926) to revive carving.",
"wood carving; weaving",
"meeting houses; carvings",
"rule and display;ritual and belief",
"NZ state; historians",
"iwi as peoples not states; land confiscation; women weavers",
"Indigenous-community",
"Te Papa Collections Online (CC BY where marked);Auckland Museum Collections Online (CC BY where marked)",
"R3",
"F1.17;F1.24",
"high",
"Iwi excluded as polities by design.",
"canon_polities.csv"
],
[
"POL092",
"Sumerian city-states",
"Uruk; Ur; Lagash; Kish; Early Dynastic Sumer",
"polity",
"People",
"F1.9a",
"WA-MES",
"-3500",
"-2334",
"c.; Uruk period to Akkadian conquest; middle chronology",
"Sumerian cities developed cuneiform accounting, cylinder seals and temple and palace workshops such as those behind the Royal Cemetery of Ur.",
"cuneiform on clay; cylinder-seal carving; shell and lapis inlay; gold sheet",
"seals; tablets; lyres; statues",
"rule and display;record and writing;ritual and belief;exchange and value",
"Assyriologists; archaeologists (Woolley)",
"temple-dependent labourers and women weavers; retainers buried at Ur; non-Sumerian speakers",
"funerary;conflict-looting",
"Met Open Access (CC0);Cuneiform Digital Library Initiative;Penn Museum collection search (link out);Wikimedia Commons;British Museum collection search (link out)",
"R1",
"F1.5;F1.28",
"high",
"A grouping of rival city-states, not one polity. Looting of Iraqi sites (1990s–2000s).",
"canon_polities.csv"
],
[
"POL093",
"Akkadian Empire",
"Akkad",
"polity",
"People",
"F1.9a",
"WA-MES;WA-IRN;WA-LEV",
"-2334",
"-2154",
"c.; middle chronology",
"Akkadian rulers commissioned victory stelae such as Naram-Sin's and cast copper royal heads, and scribes standardised administrative writing.",
"copper-alloy casting; relief carving; cylinder seals",
"stelae; royal heads; seals",
"rule and display;record and writing;war",
"Assyriologists; royal inscriptions",
"conquered Sumerian cities; deported and enslaved captives",
"conflict-looting",
"Met Open Access (CC0);Cuneiform Digital Library Initiative;Wikimedia Commons",
"R2",
"F1.28",
"high",
"Capital Agade not yet located.",
"canon_polities.csv"
],
[
"POL094",
"Third Dynasty of Ur",
"Ur III state",
"polity",
"People",
"F1.9a",
"WA-MES;WA-IRN",
"-2112",
"-2004",
"c.; middle chronology",
"Ur III tablets record state textile workshops employing thousands of women and children alongside the ziggurat of Ur.",
"wool weaving; brick architecture; cuneiform accounting",
"ziggurat; tablets; textiles (documented)",
"rule and display;record and writing;clothing and adornment;ritual and belief",
"Assyriologists; administrative archives",
"named women weavers treated as rations recipients; deportees",
"none",
"Cuneiform Digital Library Initiative;Met Open Access (CC0);Wikimedia Commons;Penn Museum collection search (link out)",
"R1",
"F1.18;F1.23;F1.28",
"high",
"Key case for obscured textile labour.",
"canon_polities.csv"
],
[
"POL095",
"Old Babylonian kingdom",
"First Dynasty of Babylon; Hammurabi's Babylon",
"polity",
"People",
"F1.9a",
"WA-MES",
"-1894",
"-1595",
"c.; middle chronology",
"Hammurabi's law stele and the Old Babylonian school tablets show how Babylon codified crafts, wages and liabilities for builders and makers.",
"basalt carving; cuneiform schooling",
"law stele; school tablets; terracotta plaques",
"rule and display;record and writing",
"Assyriologists",
"non-elite and enslaved people ranked lower in law; Amorite origins",
"none",
"Cuneiform Digital Library Initiative;Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.28",
"high",
"Stele is in the Louvre.",
"canon_polities.csv"
],
[
"POL096",
"Neo-Assyrian Empire",
"Assyria",
"polity",
"People",
"F1.9a",
"WA-MES;WA-ANA;WA-LEV;WA-IRN",
"-911",
"-609",
"",
"Assyrian kings commissioned carved palace reliefs and gathered ivories and craftsmen from conquered lands through tribute and deportation.",
"gypsum relief carving; ivory carving; bronze; glazed brick",
"palace reliefs; ivories; lamassu",
"rule and display;war;ritual and belief",
"Assyriologists; royal annals",
"deported peoples and captive craftsmen; Phoenician and Syrian ivory carvers; destruction at Nimrud (2015)",
"conflict-looting",
"Met Open Access (CC0);British Museum collection search (link out);Wikimedia Commons;Cuneiform Digital Library Initiative",
"R1",
"F1.13;F1.19a;F1.23;F1.24",
"high",
"",
"canon_polities.csv"
],
[
"POL097",
"Neo-Babylonian Empire",
"Chaldean dynasty",
"polity",
"People",
"F1.9a",
"WA-MES;WA-LEV",
"-626",
"-539",
"",
"Nebuchadnezzar II's Babylon was rebuilt with glazed-brick reliefs such as the Ishtar Gate.",
"moulded glazed brick; baked brick",
"Ishtar Gate; Processional Way",
"rule and display;ritual and belief",
"Assyriologists; archaeologists (Koldewey)",
"deported Judeans and others; the gate's removal to Berlin",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.24",
"high",
"",
"canon_polities.csv"
],
[
"POL098",
"Elam",
"Elamite kingdoms; Susiana; Anshan",
"polity",
"People",
"F1.9a",
"WA-IRN;WA-MES",
"-3200",
"-539",
"c.; long sequence with gaps",
"Elam developed Proto-Elamite writing, cast the bronze statue of Queen Napir-Asu and built the ziggurat at Chogha Zanbil.",
"bronze casting; bitumen compound; glazed brick; writing",
"statues; ziggurat; vessels",
"rule and display;ritual and belief;record and writing",
"archaeologists; Assyriologists",
"highland peoples; periods known only from Mesopotamian sources",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;Cuneiform Digital Library Initiative",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL099",
"Dilmun",
"Dilmun",
"polity",
"People",
"F1.9a",
"WA-ARB",
"-2200",
"-500",
"c.; florescence c. 2050–1700 BCE",
"Dilmun traders on Bahrain made stamp seals and built tens of thousands of burial mounds.",
"stone seal carving; copper trade; mound building",
"stamp seals; burial mounds",
"exchange and value;ritual and belief;rule and display",
"archaeologists; Mesopotamian texts",
"non-elite dead in the mounds; Magan and Meluhha partners",
"funerary",
"Wikimedia Commons;open-access excavation reports",
"R2",
"F1.13",
"high",
"Burial mounds are funerary.",
"canon_polities.csv"
],
[
"POL100",
"Ugarit",
"Ras Shamra",
"polity",
"People",
"F1.9a",
"WA-LEV",
"-1450",
"-1185",
"c.",
"Ugarit's scribes used a cuneiform alphabet and its workshops produced ivories and metalwork for Mediterranean trade.",
"cuneiform alphabet; ivory; bronze",
"tablets; ivories",
"record and writing;exchange and value",
"archaeologists; epigraphers",
"urban non-elite; Hittite overlords",
"none",
"Wikimedia Commons;Cuneiform Digital Library Initiative",
"R2",
"F1.5;F1.13",
"high",
"",
"canon_polities.csv"
],
[
"POL101",
"Hittite Empire",
"Hatti",
"polity",
"People",
"F1.9a",
"WA-ANA;WA-LEV",
"-1650",
"-1180",
"c.",
"Hittite kings commissioned rock reliefs such as Yazılıkaya and state-controlled metalwork, and wrote in cuneiform and Anatolian hieroglyphs.",
"rock relief; bronze casting; cuneiform tablets",
"reliefs; vessels; tablets",
"rule and display;ritual and belief;record and writing;war",
"Hittitologists; archives from Hattusa",
"Luwian and Hurrian neighbours; deportees; iron myth debated",
"none",
"Met Open Access (CC0);Wikimedia Commons;Cuneiform Digital Library Initiative",
"R2",
"F1.28",
"high",
"\"Hittite iron monopoly\" claim is outdated.",
"canon_polities.csv"
],
[
"POL102",
"Phoenician city-states",
"Tyre; Sidon; Byblos",
"polity",
"People",
"F1.9a;F1.11",
"WA-LEV;EU-GRR",
"-1200",
"-332",
"c.",
"Phoenician cities spread purple dye, glass, carved ivories and the alphabet across the Mediterranean.",
"murex purple dyeing; glass; ivory carving; alphabetic writing",
"ivories; glass; inscriptions",
"exchange and value;record and writing;clothing and adornment",
"historians; Greek sources",
"the murex workers; Assyrian-held ivories; enslaved people traded",
"none",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.5;F1.13;F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL103",
"Urartu",
"Biainili; Kingdom of Van",
"polity",
"People",
"F1.9a",
"WA-ANA;WA-CAU;WA-IRN",
"-860",
"-590",
"c.",
"Urartian kings built fortresses and commissioned bronze shields, cauldrons and furniture fittings.",
"bronze sheet and casting; stone fortification",
"shields; cauldrons; belts",
"rule and display;war;ritual and belief",
"archaeologists; Urartian inscriptions",
"subject populations; Armenian and Kurdish present communities",
"conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_polities.csv"
],
[
"POL104",
"Lydia",
"Lydian kingdom",
"polity",
"People",
"F1.9a",
"WA-ANA",
"-680",
"-547",
"",
"Lydia refined electrum and gold at Sardis and struck some of the earliest coins.",
"electrum coinage; gold refining",
"coins",
"exchange and value;rule and display",
"historians (Herodotus); archaeologists",
"refinery workers; Ionian Greek cities",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5;F1.13",
"high",
"",
"canon_polities.csv"
],
[
"POL105",
"Achaemenid Empire",
"Persian Empire",
"polity",
"People",
"F1.9a",
"WA-IRN;WA-MES;WA-ANA;WA-LEV;AF-EGY;AS-CEN;AS-SAS",
"-550",
"-330",
"",
"Persepolis tablets and Darius's Susa foundation charter record craftsmen and materials brought from across the empire to build royal palaces.",
"stone relief; glazed brick; gold and silver working",
"reliefs; rhyta; Oxus treasure",
"rule and display;exchange and value;ritual and belief",
"historians; royal inscriptions; Persepolis Fortification archive",
"workers paid in rations (kurtash); subject peoples shown as tribute-bearers",
"none",
"Met Open Access (CC0);Wikimedia Commons;British Museum collection search (link out)",
"R1",
"F1.13;F1.17;F1.23",
"high",
"Achaemenid dynasty same as polity.",
"canon_polities.csv"
],
[
"POL106",
"Parthian Empire",
"Arsacid Empire",
"polity",
"People",
"F1.9a",
"WA-IRN;WA-MES;AS-CEN",
"-247",
"224",
"",
"Parthian builders used the iwan, and workshops at Nisa carved ivory rhyta.",
"ivory carving; brick and stone architecture; coinage",
"rhyta; iwans; coins",
"rule and display;ritual and belief",
"historians; archaeologists",
"vassal kingdoms; Roman-biased sources",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.5",
"high",
"",
"canon_polities.csv"
],
[
"POL107",
"Sasanian Empire",
"Eranshahr",
"polity",
"People",
"F1.9a",
"WA-IRN;WA-MES;WA-CAU;AS-CEN",
"224",
"651",
"",
"Sasanian workshops made silver plates with royal hunts, carved rock reliefs and wove patterned silks copied far along trade routes.",
"silver repoussé and gilding; rock relief; silk weaving",
"plates; reliefs; silks",
"rule and display;ritual and belief;exchange and value",
"historians; archaeologists",
"Christian, Jewish and Manichaean subjects; deported Roman artisans",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL108",
"Kingdom of Armenia (antiquity)",
"Artaxiad and Arsacid Armenia",
"polity",
"People",
"F1.9a",
"WA-CAU;WA-ANA",
"-190",
"428",
"c.",
"Armenia adopted Christianity in c. 301 and Mesrop Mashtots created the Armenian alphabet around 405.",
"alphabet; stone architecture",
"Garni temple; manuscripts",
"rule and display;ritual and belief;record and writing",
"Armenian historians; historians",
"non-Christian subjects; Persian and Roman framing",
"none",
"Wikimedia Commons",
"R3",
"F1.5;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL109",
"Bagratid Armenia",
"Kingdom of Ani",
"polity",
"People",
"F1.9a",
"WA-CAU;WA-ANA",
"885",
"1045",
"",
"Bagratid patrons built stone churches at Ani and carved khachkars.",
"ashlar stone architecture; stone carving",
"churches; khachkars",
"ritual and belief;rule and display",
"historians; Armenian sources",
"Muslim, Syriac and Georgian subjects of Ani; masons whose names are rarely recorded; the site's neglect on the closed Turkish–Armenian border",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_polities.csv"
],
[
"POL110",
"Armenian Kingdom of Cilicia",
"Cilician Armenia",
"polity",
"People",
"F1.9a",
"WA-ANA;WA-LEV",
"1198",
"1375",
"principality from 1080",
"Cilician scriptoria produced illuminated manuscripts by painters such as Toros Roslin.",
"manuscript illumination",
"gospels",
"ritual and belief;record and writing",
"historians",
"non-Armenian subjects; lost manuscripts",
"sacred",
"Walters Art Museum (CC0);Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL111",
"Kingdom of Georgia",
"Sakartvelo",
"polity",
"People",
"F1.9a",
"WA-CAU",
"1008",
"1490",
"",
"The Georgian kingdom under the Bagrationi, especially Tamar, commissioned cloisonné enamel icons, repoussé metal and frescoed churches.",
"cloisonné enamel; silver repoussé; fresco",
"icons; triptychs; churches",
"ritual and belief;rule and display",
"historians; Georgian chronicles",
"non-Christian subjects; peasantry",
"sacred",
"Wikimedia Commons",
"R2",
"F1.16",
"high",
"Bagrationi dynasty folded into this row.",
"canon_polities.csv"
],
[
"POL112",
"Saba",
"Sheba",
"polity",
"People",
"F1.9a",
"WA-ARB",
"-1000",
"275",
"c.",
"Saba built the Marib dam and carved alabaster heads and inscriptions from incense-trade wealth.",
"alabaster carving; bronze casting; hydraulic building",
"funerary heads; inscriptions; dam",
"rule and display;ritual and belief;exchange and value",
"epigraphers; archaeologists",
"incense gatherers; neighbouring kingdoms (Qataban, Ma'in)",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.13",
"high",
"War since 2015 threatens sites.",
"canon_polities.csv"
],
[
"POL113",
"Nabataean Kingdom",
"Nabataea",
"polity",
"People",
"F1.9a",
"WA-ARB;WA-LEV",
"-300",
"106",
"c.; Roman annexation 106",
"Nabataeans carved rock-cut tomb façades at Petra and Hegra and made eggshell-thin painted pottery.",
"rock-cut architecture; fine painted ceramics; water engineering",
"façades; pottery",
"rule and display;ritual and belief;food and storage",
"historians; archaeologists",
"caravan labour; the Bdul community displaced from Petra in 1985",
"funerary",
"Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_polities.csv"
],
[
"POL114",
"Palmyra",
"Tadmor; Palmyrene Empire",
"polity",
"People",
"F1.9a",
"WA-LEV",
"-50",
"273",
"c.; Palmyrene Empire 270–273",
"Palmyrene sculptors carved limestone funerary portraits and the city's caravans linked Rome and Parthia.",
"limestone relief carving",
"funerary busts; temples",
"ritual and belief;exchange and value",
"historians; archaeologists",
"those portrayed; destruction by ISIS 2015; Khaled al-Asaad",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.19a",
"high",
"",
"canon_polities.csv"
],
[
"POL115",
"Minoan palatial polities",
"Knossos; Minoan Crete",
"polity",
"People",
"F1.11",
"EU-GRR",
"-2000",
"-1450",
"c.",
"Cretan palaces sustained workshops for Kamares ware, faience, stone vessels and Linear A records.",
"fine pottery; faience; stone vessels; fresco",
"Kamares ware; frescoes; seals",
"rule and display;ritual and belief;record and writing",
"archaeologists (Evans)",
"Evans's reconstructions; the name \"Minoan\" invented by him",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.3;F1.28",
"medium",
"Debated polity; name is modern.",
"canon_polities.csv"
],
[
"POL116",
"Mycenaean palatial states",
"Pylos; Mycenae; Knossos (Linear B)",
"polity",
"People",
"F1.11",
"EU-GRR",
"-1600",
"-1100",
"c.",
"Linear B tablets from Mycenaean palaces list bronze-smiths, perfumers and women textile workers assigned raw materials.",
"bronze; gold; textile; Linear B records",
"masks; tablets; weapons",
"rule and display;record and writing;war",
"archaeologists; Ventris and Chadwick",
"women and captive workers listed in tablets",
"funerary",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.18;F1.23;F1.28",
"high",
"",
"canon_polities.csv"
],
[
"POL117",
"Athens (classical polis)",
"Athenian democracy",
"polity",
"People",
"F1.11",
"EU-GRR",
"-508",
"-322",
"",
"Athens hosted potters and painters who signed black- and red-figure vessels and funded the Parthenon from imperial tribute.",
"red-figure painting; marble carving; bronze casting",
"vases; sculpture; coins",
"rule and display;ritual and belief;exchange and value",
"historians; ancient authors",
"enslaved workers and metics (many potters); women; tribute-paying allies",
"conflict-looting",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons;Getty Museum Open Content (public-domain images)",
"R1",
"F1.17;F1.23;F1.24",
"high",
"Parthenon sculptures in the British Museum.",
"canon_polities.csv"
],
[
"POL118",
"Etruscan city-states",
"Etruscan League",
"polity",
"People",
"F1.11",
"EU-GRR",
"-800",
"-264",
"c.",
"Etruscan workshops made bronze mirrors, bucchero pottery and granulated gold.",
"bronze casting and engraving; bucchero; gold granulation",
"mirrors; urns; jewellery",
"rule and display;ritual and belief;clothing and adornment",
"archaeologists; Roman authors",
"enslaved workers; Villanovan antecedents; tomb looting",
"funerary;conflict-looting",
"Met Open Access (CC0);Wikimedia Commons;Getty Museum Open Content (public-domain images)",
"R2",
"F1.24",
"high",
"",
"canon_polities.csv"
],
[
"POL119",
"Ptolemaic Kingdom",
"Ptolemaic Egypt",
"polity",
"People",
"F1.6;F1.11",
"AF-EGY;EU-GRR",
"-305",
"-30",
"",
"Ptolemaic rulers built Egyptian-style temples such as Edfu and Alexandria became a centre of glass, faience and scholarship.",
"glass; faience; temple building; papyrus",
"temples; glass; portraits",
"rule and display;ritual and belief;record and writing",
"historians; papyrologists",
"Egyptian peasants and temple workers; Jewish community of Alexandria",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL120",
"Rome (Republic and Empire)",
"Roman Republic; Roman Empire",
"polity",
"People",
"F1.11;F1.6;F1.9a",
"EU-GRR;EU-WCE;EU-BLC;EU-IBE;AF-MAG;AF-EGY;WA-LEV;WA-ANA",
"-509",
"476",
"Republic to 27 BCE; Western empire to 476; East continues as Byzantium",
"Roman production standardised stamped terra sigillata, spread glassblowing and relied on enslaved and freed makers across the provinces.",
"glassblowing; terra sigillata; concrete; mosaic; bronze",
"pottery; glass; mosaics; sculpture",
"rule and display;shelter;exchange and value;war",
"historians; archaeologists",
"enslaved and freed makers; provincial peoples; women's work",
"conflict-looting;human-flow",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Getty Museum Open Content (public-domain images);Wikimedia Commons;Europeana",
"R1",
"F1.5;F1.14;F1.23",
"high",
"",
"canon_polities.csv"
],
[
"POL121",
"Byzantine Empire",
"Eastern Roman Empire",
"polity",
"People",
"F1.11;F1.9a",
"EU-BYZ;WA-ANA;WA-LEV;AF-EGY",
"330",
"1453",
"",
"Byzantine emperors controlled silk production and guilds (Book of the Eparch) and patronised mosaics, icons and enamels.",
"mosaic; silk weaving; cloisonné enamel; icon painting",
"mosaics; icons; silks; ivories",
"rule and display;ritual and belief;clothing and adornment",
"historians; the empire's own \"Roman\" name",
"Jews, Armenians and other subjects; enslaved people; Iconoclasm's losses",
"sacred",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Walters Art Museum (CC0);Wikimedia Commons",
"R1",
"F1.14;F1.16;F1.17",
"high",
"\"Byzantine\" is a later label.",
"canon_polities.csv"
],
[
"POL122",
"Anglo-Saxon kingdoms",
"East Anglia; Mercia; Northumbria; Wessex",
"polity",
"People",
"F1.11",
"EU-BLC",
"450",
"1066",
"c.",
"Anglo-Saxon kingdoms produced the Sutton Hoo and Staffordshire hoard metalwork and, with monasteries, the Lindisfarne Gospels.",
"gold and garnet cloisonné; manuscript illumination; embroidery",
"buckles; helmets; gospels",
"rule and display;ritual and belief;war",
"historians (Bede); archaeologists",
"Britons; enslaved people; women embroiderers",
"funerary",
"British Library digitised collections (public-domain items);Wikimedia Commons;British Museum collection search (link out)",
"R2",
"F1.18",
"high",
"",
"canon_polities.csv"
],
[
"POL123",
"Early medieval Irish kingdoms",
"Gaelic Ireland",
"polity",
"People",
"F1.11",
"EU-BLC",
"500",
"1169",
"c.; Anglo-Norman invasion 1169",
"Irish kings and monasteries commissioned metalwork such as the Ardagh chalice and manuscripts such as the Book of Kells.",
"filigree; enamel; manuscript illumination",
"chalices; brooches; gospels",
"ritual and belief;rule and display",
"historians; Irish annals",
"unfree labour; Viking-era captives",
"sacred",
"Wikimedia Commons",
"R3",
"F1.16",
"medium",
"",
"canon_polities.csv"
],
[
"POL124",
"Carolingian Empire",
"Francia",
"polity",
"People",
"F1.11",
"EU-WCE",
"751",
"888",
"",
"Carolingian court schools produced illuminated manuscripts, ivories and the Palatine Chapel at Aachen.",
"manuscript illumination; ivory carving; goldsmithing",
"gospels; book covers; reliquaries",
"rule and display;ritual and belief;record and writing",
"historians; Einhard",
"Saxons converted by force; slaves traded; peasants",
"sacred",
"British Library digitised collections (public-domain items);Wikimedia Commons;Europeana",
"R2",
"F1.14;F1.28",
"high",
"Carolingian dynasty same as polity.",
"canon_polities.csv"
],
[
"POL125",
"Holy Roman Empire",
"Holy Roman Empire",
"polity",
"People",
"F1.11",
"EU-WCE",
"962",
"1806",
"Otto I 962 (Charlemagne 800 as precursor)",
"The Empire's courts and free imperial cities, such as Nuremberg, supported goldsmiths, printers and instrument-makers under guild rule.",
"goldsmithing; printing; clock and instrument making",
"regalia; prints; automata",
"rule and display;ritual and belief;exchange and value",
"historians",
"Jews; peasant makers outside guilds; women excluded from mastership",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Europeana;Wikimedia Commons",
"R2",
"F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL126",
"Kingdom of France",
"France (Capetian to Bourbon)",
"polity",
"People",
"F1.11",
"EU-WCE",
"987",
"1792",
"",
"The French crown under Colbert founded royal manufactures (Gobelins 1662, Sèvres royal from 1759) to set European luxury standards.",
"tapestry; porcelain; furniture; mirror glass",
"tapestries; porcelain; furniture",
"rule and display;exchange and value",
"historians",
"enslaved people in French Caribbean colonies; journeymen; women in the trades",
"human-flow",
"Met Open Access (CC0);Paris Musées (CC0);Wikimedia Commons;Getty Museum Open Content (public-domain images)",
"R2",
"F1.17;F1.19",
"high",
"Valois and Bourbon are DYN rows.",
"canon_polities.csv"
],
[
"POL127",
"Kingdom of England",
"England",
"polity",
"People",
"F1.11",
"EU-BLC",
"927",
"1707",
"",
"England's professional embroiderers in London made opus anglicanum vestments exported across Europe.",
"silk and gold embroidery; wool trade",
"vestments; manuscripts",
"rule and display;ritual and belief;clothing and adornment",
"historians",
"women embroiderers; Welsh and Irish neighbours; wool producers",
"none",
"Met Open Access (CC0);Wikimedia Commons;V&A collections search (link out)",
"R2",
"F1.18",
"high",
"Tudor dynasty is a DYN row.",
"canon_polities.csv"
],
[
"POL128",
"Burgundian State",
"Valois Burgundy; Burgundian Netherlands",
"polity",
"People",
"F1.11",
"EU-WCE;EU-BLC",
"1363",
"1482",
"",
"The Valois dukes of Burgundy commissioned Flemish tapestries, panel paintings and books of hours from urban workshops.",
"tapestry weaving; oil painting; illumination",
"tapestries; altarpieces; books of hours",
"rule and display;ritual and belief",
"historians",
"urban weavers and guild members; rebel cities",
"none",
"Met Open Access (CC0);Rijksmuseum (CC0);Wikimedia Commons",
"R2",
"F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL129",
"Dutch Republic",
"United Provinces",
"polity",
"People",
"F1.11;F1.13",
"EU-BLC",
"1581",
"1795",
"",
"The Dutch Republic's open art market and guilds produced paintings, Delftware imitating Chinese porcelain, and maps, financed partly by colonial trade.",
"oil painting; tin-glazed earthenware; engraving; printing",
"paintings; Delftware; maps",
"exchange and value;rule and display",
"historians",
"enslaved people via the West India Company; colonial subjects; women artists",
"human-flow",
"Rijksmuseum (CC0);Met Open Access (CC0);Wikimedia Commons",
"R1",
"F1.14;F1.17",
"high",
"Link to VOC row.",
"canon_polities.csv"
],
[
"POL130",
"Hanseatic League",
"Hansa",
"polity",
"People",
"F1.11;F1.13",
"EU-SCA;EU-WCE;EU-EER;EU-BLC",
"1356",
"1669",
"merchant association from 12th c.; first diet 1356; last diet 1669",
"Hanseatic trade carried Lübeck altarpieces, Flemish cloth and Baltic amber and furs, and standardised the cog ship.",
"shipbuilding; woodcarving; cloth trade",
"altarpieces; cogs; brass",
"exchange and value;transport",
"historians",
"Baltic peoples; non-German towns; debated polity",
"none",
"Europeana;Wikimedia Commons",
"R2",
"F1.13",
"high",
"Debated polity: a league of cities.",
"canon_polities.csv"
],
[
"POL131",
"Republic of Venice",
"Serenissima",
"polity",
"People",
"F1.11;F1.13",
"EU-GRR;EU-BYZ",
"697",
"1797",
"",
"Venice concentrated glassmakers on Murano (1291) under guild secrecy and made the city a centre of printing and lace.",
"glassblowing; printing; lace",
"glass; printed books; lace",
"exchange and value;rule and display",
"historians",
"Dalmatian and Greek subjects; enslaved people; glassmakers barred from emigrating",
"none",
"Met Open Access (CC0);Cleveland Museum of Art Open Access (CC0);Rijksmuseum (CC0);Wikimedia Commons",
"R1",
"F1.14;F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL132",
"Republic of Florence",
"Florence",
"polity",
"People",
"F1.11",
"EU-GRR",
"1115",
"1532",
"",
"Florence's guilds (Arte della Lana, Calimala) organised cloth production and commissioned public art.",
"wool cloth; painting; bronze casting",
"altarpieces; sculpture; textiles",
"rule and display;ritual and belief;exchange and value",
"historians; guild statutes",
"wool workers (Ciompi revolt 1378); enslaved domestic workers; women",
"none",
"Met Open Access (CC0);National Gallery of Art Washington (CC0);Wikimedia Commons",
"R1",
"F1.17;F1.23",
"high",
"Medici is a DYN row.",
"canon_polities.csv"
],
[
"POL133",
"Papal States",
"Patrimonium Sancti Petri",
"polity",
"People",
"F1.11",
"EU-GRR",
"756",
"1870",
"",
"Papal Rome ran mosaic and tapestry workshops and commissioned major painting and building.",
"mosaic; fresco; tapestry",
"chapels; mosaics; tapestries",
"rule and display;ritual and belief",
"historians",
"Jewish community in the ghetto; enslaved galley rowers",
"sacred",
"Wikimedia Commons;Met Open Access (CC0)",
"R2",
"F1.16;F1.17",
"high",
"",
"canon_polities.csv"
],
[
"POL134",
"Crown of Aragon",
"Aragon",
"polity",
"People",
"F1.11",
"EU-IBE;EU-GRR",
"1162",
"1716",
"",
"Aragon's Valencia and Manises lustreware workshops, many Muslim-run, exported across Europe.",
"lustre ceramics; silk",
"lustreware; textiles",
"exchange and value;rule and display",
"historians",
"Mudéjar and Morisco makers expelled 1609",
"none",
"Met Open Access (CC0);Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL135",
"Spanish Empire",
"Monarquía Hispánica",
"polity",
"People",
"F1.11;F1.13",
"GL",
"1492",
"1898",
"major American losses 1820s; Cuba and Philippines 1898",
"The Spanish empire's silver and trade channelled American and Asian materials into Europe and regulated colonial crafts.",
"silver; dyes (cochineal); ceramics",
"coins; textiles",
"rule and display;exchange and value",
"historians",
"Indigenous and African labour; expelled Jews and Moriscos",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons;Library of Congress (public-domain items)",
"R2",
"F1.13;F1.22",
"high",
"Habsburg is a DYN row; viceroyalties are separate rows.",
"canon_polities.csv"
],
[
"POL136",
"Portuguese Empire",
"Império Português",
"polity",
"People",
"F1.11;F1.13",
"GL",
"1415",
"1999",
"Ceuta 1415 to Macau 1999",
"Portuguese trade commissioned Afro-Portuguese ivories, Namban goods and Indo-Portuguese furniture and ran a large share of the Atlantic slave trade.",
"ivory; lacquer; tin-glaze (azulejo)",
"salt cellars; oliphants; azulejos",
"exchange and value;rule and display",
"historians",
"people enslaved and transported; colonised makers",
"human-flow",
"Met Open Access (CC0);Wikimedia Commons",
"R1",
"F1.13;F1.14",
"high",
"",
"canon_polities.csv"
],
[
"POL137",
"British Empire",
"British Empire",
"polity",
"People",
"F1.11;F1.13",
"GL",
"1607",
"1997",
"Jamestown 1607 to Hong Kong 1997",
"The empire built art schools, museums and exhibitions (from 1851) and extracted materials and objects across its territories.",
"industrial textiles; museum collecting",
"exhibitions; textiles; collections",
"rule and display;exchange and value",
"historians",
"enslaved people (trade to 1807, slavery to 1834/38); colonised makers; looted objects",
"human-flow;conflict-looting",
"British Library digitised collections (public-domain items);Wikimedia Commons;Library of Congress (public-domain items)",
"R1",
"F1.19;F1.22;F1.24",
"high",
"British Raj separate row.",
"canon_polities.csv"
],
[
"POL138",
"French colonial empire",
"Empire colonial français",
"polity",
"People",
"F1.11;F1.13",
"GL",
"1534",
"1980",
"c.; first empire from 16th c.; second 1830–1962; Vanuatu 1980",
"France's colonial exhibitions (1931) and ethnographic museums displayed objects taken from colonised peoples.",
"collecting; exhibitions",
"collections; posters",
"rule and display;exchange and value",
"historians",
"enslaved people in the Caribbean; colonised makers; looted objects (Sarr–Savoy report 2018)",
"human-flow;conflict-looting",
"Wikimedia Commons;musée du quai Branly collection search (link out)",
"R2",
"F1.24",
"high",
"",
"canon_polities.csv"
],
[
"POL139",
"German colonial empire",
"Deutsche Kolonien",
"polity",
"People",
"F1.11;F1.13",
"AF-SOU;AF-SWA;AF-CEN;AF-GUI;OC-MEL;OC-MIC;AS-CHN",
"1884",
"1919",
"",
"German colonial rule gathered large ethnographic collections through war and purchase, and committed genocide in Namibia (1904–08).",
"collecting",
"collections",
"rule and display",
"historians",
"Herero and Nama killed in the 1904–08 genocide; Maji Maji dead (1905–07); Cameroonian, Togolese and Pacific makers whose objects fill German museums; Chinese in Qingdao",
"conflict-looting;human-flow",
"Wikimedia Commons",
"R2",
"F1.19a;F1.24",
"high",
"",
"canon_polities.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
