insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"PRA112",
"Bidri ware",
"bidriware",
"living-practice",
"People",
"F1.9;F1.10",
"AS-SAS",
"1400",
"",
"Bahmani period c. 14th–15th century",
"Craftsmen inlay silver into a blackened zinc alloy.",
"zinc alloy; silver inlay; soil blackening",
"huqqa bases; boxes",
"exchange and value;rule and display",
"Bidar craftsmen",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_practices.csv"
],
[
"PRA113",
"Newar metal casting",
"Newar lost-wax casting; repoussé",
"living-practice",
"People",
"F1.9",
"AS-HIM",
"",
"",
"Tradition from at least the Licchavi period",
"Newar metalworkers in Patan cast and repoussé deity images for Nepal and Tibet.",
"lost-wax casting; repoussé; gilding",
"Buddhist and Hindu images",
"ritual and belief",
"Newar metalworkers (Patan)",
"",
"living-community;sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13;F1.16",
"medium",
"",
"canon_practices.csv"
],
[
"PRA114",
"Bhutanese thagzo weaving",
"thagzo",
"living-practice",
"People",
"F1.9",
"AS-HIM",
"",
"",
"Long-standing",
"Bhutanese women weave supplementary-weft kira and gho on backstrap and frame looms.",
"backstrap loom; silk; cotton",
"kira; gho",
"clothing and adornment",
"Bhutanese weavers",
"",
"living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"medium",
"",
"canon_practices.csv"
],
[
"PRA115",
"Myanmar lacquerware",
"yun",
"living-practice",
"People",
"F1.9",
"AS-MSE",
"",
"",
"Bagan tradition centuries old",
"Lacquerers coat bamboo and horsehair forms with thitsi lacquer and engrave coloured designs.",
"thitsi lacquer; bamboo; horsehair",
"betel boxes; bowls",
"food and storage",
"Bagan lacquerers",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_practices.csv"
],
[
"PRA116",
"Lao silk weaving",
"sinh weaving",
"living-practice",
"People",
"F1.9",
"AS-MSE",
"",
"",
"Long-standing",
"Lao women weave silk sinh skirts and ritual cloths with supplementary weft and ikat (mat mi).",
"silk; ikat; supplementary weft",
"sinh; pha biang",
"clothing and adornment;ritual and belief",
"Lao weavers",
"",
"living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"medium",
"",
"canon_practices.csv"
],
[
"PRA117",
"Cambodian silk weaving",
"hol; phamuong",
"living-practice",
"People",
"F1.9",
"AS-MSE",
"",
"",
"Long-standing",
"Khmer weavers make weft-ikat hol and plain phamuong silks.",
"silk; weft ikat",
"sampot hol; pidan",
"clothing and adornment;ritual and belief",
"Khmer weavers (Takeo)",
"",
"living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"medium",
"Pidan are temple hangings.",
"canon_practices.csv"
],
[
"PRA118",
"Sbek Thom, Khmer shadow theatre",
"Sbek Thom",
"living-practice",
"People",
"F1.9",
"AS-MSE",
"",
"",
"Proclaimed 2005, inscribed 2008",
"Makers cut large leather puppets and perform the Reamker by firelight.",
"cowhide; cutting; dyeing",
"Sbek Thom puppets",
"play and music;ritual and belief",
"UNESCO ICH list (2008; proclaimed 2005)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA119",
"Art of pottery-making of Chăm people",
"Bàu Trúc pottery",
"living-practice",
"People",
"F1.9",
"AS-MSE",
"",
"",
"Inscribed 2022, Urgent Safeguarding",
"Chăm women shape pots by walking around them and fire them in the open.",
"clay; hand building; open firing",
"pots",
"food and storage",
"UNESCO ICH list (2022, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_practices.csv"
],
[
"PRA120",
"Indonesian Batik",
"batik tulis; batik cap",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Inscribed 2009",
"Makers draw wax with a canting or stamp it with a cap and dye cloth in stages.",
"wax; canting; cap; natural and synthetic dyes",
"kain; sarong; iket",
"clothing and adornment;ritual and belief",
"UNESCO ICH list (2009)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Rijksmuseum (CC0); Wikimedia Commons",
"R1",
"F1.18;F1.14",
"high",
"",
"canon_practices.csv"
],
[
"PRA121",
"Indonesian Kris",
"keris making",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Proclaimed 2005, inscribed 2008",
"Smiths (empu) forge pattern-welded blades and makers carve hilts and sheaths.",
"iron; nickel; pattern welding; carving",
"keris",
"war;ritual and belief;rule and display",
"UNESCO ICH list (2008; proclaimed 2005)",
"",
"living-community;sacred",
"UNESCO ICH lists (link out; per-item photo licence); Rijksmuseum (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_practices.csv"
],
[
"PRA122",
"Noken multifunctional knotted or woven bag, handcraft of the people of Papua",
"noken",
"living-practice",
"People",
"F1.9;F1.12",
"AS-ISE;OC-MEL",
"",
"",
"Inscribed 2012, Urgent Safeguarding",
"Papuan makers knot and weave bark and orchid fibres into bags for carrying goods and children.",
"tree bark; orchid fibre; knotting",
"noken bags",
"care and access;transport;food and storage",
"UNESCO ICH list (2012, Urgent Safeguarding)",
"",
"Indigenous-community;living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA123",
"Pinisi, art of boatbuilding in South Sulawesi",
"pinisi",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Inscribed 2017",
"Konjo and Bugis shipwrights build wooden sailing ships without plans.",
"ironwood; teak; edge-joined planks",
"pinisi ships",
"transport;exchange and value",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_practices.csv"
],
[
"PRA124",
"Gamelan",
"gamelan making",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Inscribed 2021",
"Smiths forge bronze gongs and keys and tune whole sets to one another.",
"tin bronze; forging; tuning",
"gamelan sets",
"play and music;ritual and belief",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA125",
"Songket",
"songket",
"living-practice",
"People",
"F1.9",
"AS-ISE;AS-MSE",
"",
"",
"Inscribed 2021 (Malaysia)",
"Weavers insert gold or silver supplementary weft into silk or cotton.",
"silk; gold thread; supplementary weft",
"songket cloth",
"clothing and adornment;rule and display",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA126",
"Tais, traditional textile",
"tais",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Inscribed 2021, Urgent Safeguarding (Timor-Leste)",
"Timorese women weave ikat and supplementary-weft cloths used in exchange and ceremony.",
"cotton; ikat; backstrap loom",
"tais",
"clothing and adornment;exchange and value;ritual and belief",
"UNESCO ICH list (2021, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA127",
"Kebaya: knowledge, skills, traditions and practices",
"kebaya",
"living-practice",
"People",
"F1.9",
"AS-ISE;AS-MSE",
"",
"",
"Inscribed 2024 (Brunei, Indonesia, Malaysia, Singapore, Thailand)",
"Makers cut and embroider the kebaya blouse.",
"cotton voile; embroidery; lace",
"kebaya",
"clothing and adornment",
"UNESCO ICH list (2024)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.13",
"medium",
"Verify title and year.",
"canon_practices.csv"
],
[
"PRA128",
"T'nalak weaving",
"t'nalak",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Long-standing",
"T'boli women weave abaca ikat cloth from designs said to come in dreams.",
"abaca fibre; ikat; backstrap loom",
"t'nalak cloth",
"clothing and adornment;ritual and belief",
"T'boli weavers (Lake Sebu)",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA129",
"Pua kumbu weaving",
"pua kumbu",
"living-practice",
"People",
"F1.9",
"AS-ISE",
"",
"",
"Long-standing",
"Iban women weave warp-ikat cloths used in rites.",
"cotton; warp ikat; backstrap loom",
"pua kumbu",
"ritual and belief;clothing and adornment",
"Iban weavers (Sarawak)",
"",
"Indigenous-community;living-community;sacred",
"Wikimedia Commons; community-published site",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA130",
"Arabic calligraphy: knowledge, skills and practices",
"khatt",
"living-practice",
"People",
"F1.10",
"WA-ARB;WA-LEV;WA-MES;AF-EGY;AF-MAG",
"",
"",
"Inscribed 2021 (16 Arab states)",
"Calligraphers write Arabic script with reed pens in proportioned hands.",
"qalam; ink; paper",
"Qur'ans; inscriptions; panels",
"record and writing;ritual and belief",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Met Open Access (CC0); Qatar Digital Library (open licence); Wikimedia Commons",
"R1",
"F1.28",
"high",
"Project already holds PR-012.",
"canon_practices.csv"
],
[
"PRA131",
"Al Sadu, traditional weaving skills in the United Arab Emirates",
"Al Sadu",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Inscribed 2011 on the Urgent Safeguarding List; transferred to the Representative List 2025, when its safeguarding programme was also selected for the Register of Good Safeguarding Practices",
"Bedouin women spin sheep, goat and camel hair and weave warp-faced cloth on ground looms for tents and camel gear.",
"sheep, goat and camel hair; ground loom; warp-faced weaving",
"tent dividers; camel bags; rugs",
"shelter;transport",
"UNESCO ICH list (2011 Urgent Safeguarding; Representative List 2025)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R1",
"F1.18;F1.29",
"high",
"Project already includes Al Sadu (UAE).",
"canon_practices.csv"
],
[
"PRA132",
"Al Talli, traditional embroidery skills in the United Arab Emirates",
"Al Talli",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Inscribed 2022 (Representative List, not Urgent Safeguarding)",
"Emirati women braid cotton and metallic threads on a cushion (kajoojah) into bands for dress.",
"cotton and metallic threads; braiding cushion",
"decorative bands",
"clothing and adornment",
"UNESCO ICH list (2022)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA133",
"Arabic coffee, a symbol of generosity",
"qahwa",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Inscribed 2015 (UAE, Saudi Arabia, Oman, Qatar)",
"Hosts roast, grind and brew coffee in the dallah and serve it in a set order.",
"coffee beans; roasting; mortar; dallah",
"dallah; finjan",
"food and storage;ritual and belief",
"UNESCO ICH list (2015)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_practices.csv"
],
[
"PRA134",
"Al-Qatt Al-Asiri, female traditional interior wall decoration in Asir",
"Al-Qatt Al-Asiri",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Inscribed 2017",
"Asiri women paint interior walls with geometric designs.",
"pigments; plaster; brushes",
"painted majlis walls",
"shelter;rule and display",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18;F1.15",
"high",
"",
"canon_practices.csv"
],
[
"PRA135",
"Bisht making",
"bisht weaving and embroidery",
"living-practice",
"People",
"F1.10",
"WA-ARB;WA-MES;WA-LEV",
"",
"",
"Long-standing",
"Weavers and embroiderers make the bisht cloak of camel or goat wool with gold zari edging.",
"wool; handloom; zari embroidery",
"bisht",
"clothing and adornment;rule and display",
"Bisht makers (al-Ahsa and elsewhere)",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.17",
"low",
"A UNESCO nomination has been reported; status unverified—do not cite UNESCO.",
"canon_practices.csv"
],
[
"PRA136",
"Omani silversmithing",
"khanjar making",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Long-standing",
"Omani smiths make khanjar daggers and silver jewellery worn as dress and emblem.",
"silver; horn; filigree; granulation",
"khanjar; jewellery",
"war;rule and display;clothing and adornment",
"Omani silversmiths",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.17",
"medium",
"UNESCO status unverified—do not cite UNESCO.",
"canon_practices.csv"
],
[
"PRA137",
"The art of embroidery in Palestine, practices, skills, knowledge and rituals",
"tatreez",
"living-practice",
"People",
"F1.10",
"WA-LEV",
"",
"",
"Inscribed 2021",
"Palestinian women cross-stitch dresses (thobes) whose patterns mark village and occasion.",
"cotton and silk thread; cross-stitch; couching",
"thobes; cushions",
"clothing and adornment",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18;F1.19a",
"high",
"",
"canon_practices.csv"
],
[
"PRA138",
"Craftsmanship of Aleppo Ghar soap",
"Ghar soap",
"living-practice",
"People",
"F1.10",
"WA-LEV",
"",
"",
"Inscribed 2024 (Syria, Representative List); tradition centuries old",
"Soap makers cook olive oil and laurel oil with lye and cure bars for months.",
"olive oil; laurel oil; lye; curing",
"Ghar soap bars",
"care and access",
"UNESCO ICH list (2024)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.22a",
"high",
"Verify UNESCO inscription and year.",
"canon_practices.csv"
],
[
"PRA139",
"Crafting and playing the Oud",
"oud making",
"living-practice",
"People",
"F1.10",
"WA-LEV;WA-IRN",
"",
"",
"Inscribed 2022 (Iran, Syria)",
"Makers build bowl-backed lutes from thin wood staves.",
"wood staves; bending; carving",
"oud",
"play and music",
"UNESCO ICH list (2022)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"Verify title and year.",
"canon_practices.csv"
],
[
"PRA140",
"Harees dish",
"harees",
"living-practice",
"People",
"F1.10",
"WA-ARB",
"",
"",
"Inscribed 2023 (UAE, Oman, Saudi Arabia)",
"Cooks beat wheat and meat over long cooking into harees for Ramadan and feasts.",
"wheat; meat; long cooking; beating",
"harees",
"food and storage;ritual and belief",
"UNESCO ICH list (2023)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"Verify title and year.",
"canon_practices.csv"
],
[
"PRA141",
"Traditional skills of carpet weaving in Fars",
"Fars carpets",
"living-practice",
"People",
"F1.10",
"WA-IRN",
"",
"",
"Inscribed 2010",
"Qashqai and other weavers make wool carpets and flatweaves on horizontal looms.",
"wool; natural dyes; horizontal loom",
"Qashqai carpets; gabbeh",
"shelter;exchange and value",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA142",
"Traditional skills of carpet weaving in Kashan",
"Kashan carpets",
"living-practice",
"People",
"F1.10",
"WA-IRN",
"",
"",
"Inscribed 2010",
"Weavers make fine knotted carpets in Kashan on vertical looms.",
"wool; silk; asymmetric knots",
"Kashan carpets",
"shelter;exchange and value",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA143",
"Traditional skills of building and sailing Iranian Lenj boats in the Persian Gulf",
"lenj",
"living-practice",
"People",
"F1.10;F1.13",
"WA-IRN;WA-ARB",
"",
"",
"Inscribed 2011, Urgent Safeguarding",
"Shipwrights on the Iranian Gulf coast build wooden lenj and sailors navigate by stars and winds.",
"teak; hand tools; celestial navigation",
"lenj; dhows",
"transport;exchange and value",
"UNESCO ICH list (2011, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R1",
"F1.13;F1.29",
"high",
"Project already holds PR-011; \"lenj\" is the Persian Gulf wooden vessel (dhow family).",
"canon_practices.csv"
],
[
"PRA144",
"Art of crafting and playing with Kamantcheh/Kamancha",
"kamancheh",
"living-practice",
"People",
"F1.10",
"WA-IRN;WA-CAU",
"",
"",
"Inscribed 2017 (Azerbaijan, Iran)",
"Makers build spike fiddles with gourd or wooden bowls.",
"wood; skin; strings",
"kamancheh",
"play and music",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA145",
"Art of miniature",
"miniature painting",
"living-practice",
"People",
"F1.10",
"WA-IRN;WA-ANA;WA-CAU;AS-CEN",
"",
"",
"Inscribed 2020 (Azerbaijan, Iran, Turkey, Uzbekistan)",
"Painters make small, detailed paintings for books and albums.",
"mineral pigments; paper; fine brushes",
"manuscript paintings; album pages",
"record and writing",
"UNESCO ICH list (2020)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_practices.csv"
],
[
"PRA146",
"Flatbread making and sharing culture: Lavash, Katyrma, Jupka, Yufka",
"flatbread culture",
"living-practice",
"People",
"F1.10;F1.12a",
"WA-IRN;WA-ANA;WA-CAU;AS-CEN",
"",
"",
"Inscribed 2016 (Azerbaijan, Iran, Kazakhstan, Kyrgyzstan, Turkey)",
"Groups of women roll and bake thin flatbread in clay ovens or on griddles.",
"dough; rolling; tandir; saj griddle",
"lavash; yufka; katyrma",
"food and storage",
"UNESCO ICH list (2016)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA147",
"Lavash, the preparation, meaning and appearance of traditional bread as an expression of culture in Armenia",
"Armenian lavash",
"living-practice",
"People",
"F1.9a;F1.11",
"WA-CAU",
"",
"",
"Inscribed 2014",
"Armenian women stretch dough and bake lavash on the walls of a tonir.",
"dough; tonir oven",
"lavash",
"food and storage;ritual and belief",
"UNESCO ICH list (2014)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA148",
"Armenian cross-stones art. Symbolism and craftsmanship of Khachkars",
"khachkar carving",
"living-practice",
"People",
"F1.9a;F1.11",
"WA-CAU",
"",
"",
"Inscribed 2010",
"Carvers cut tuff stelae with crosses and interlace.",
"tuff; chisels",
"khachkars",
"ritual and belief",
"UNESCO ICH list (2010)",
"",
"living-community;sacred",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_practices.csv"
],
[
"PRA149",
"Ancient Georgian traditional Qvevri wine-making method",
"qvevri wine-making",
"living-practice",
"People",
"F1.9a;F1.11",
"WA-CAU",
"",
"",
"Inscribed 2013",
"Potters make qvevri and winemakers ferment grapes in them underground.",
"coiled clay; beeswax; burial",
"qvevri; wine",
"food and storage;ritual and belief",
"UNESCO ICH list (2013)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R1",
"F1.29",
"high",
"",
"canon_practices.csv"
],
[
"PRA150",
"Traditional art of Azerbaijani carpet weaving in the Republic of Azerbaijan",
"Azerbaijani carpet",
"living-practice",
"People",
"F1.10",
"WA-CAU",
"",
"",
"Inscribed 2010",
"Weavers make pile and flatwoven carpets in regional schools.",
"wool; knotting; natural dyes",
"carpets; kilims",
"shelter;exchange and value",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA151",
"Craftsmanship and performance art of the Tar",
"tar making",
"living-practice",
"People",
"F1.10",
"WA-CAU",
"",
"",
"Inscribed 2012",
"Makers carve a double-bowled lute from mulberry and stretch it with membrane.",
"mulberry wood; membrane",
"tar",
"play and music",
"UNESCO ICH list (2012)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA152",
"Copper craftsmanship of Lahij",
"Lahij copper",
"living-practice",
"People",
"F1.10",
"WA-CAU",
"",
"",
"Inscribed 2015",
"Coppersmiths in Lahij hammer and engrave copper vessels.",
"copper; hammering; engraving",
"vessels",
"food and storage",
"UNESCO ICH list (2015)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.22a",
"high",
"",
"canon_practices.csv"
],
[
"PRA153",
"Traditional art and symbolism of Kelaghayi, making and wearing women's silk headscarves",
"kelaghayi",
"living-practice",
"People",
"F1.10",
"WA-CAU",
"",
"",
"Inscribed 2014",
"Makers print silk headscarves with carved blocks.",
"silk; block printing; natural dyes",
"kelaghayi scarves",
"clothing and adornment",
"UNESCO ICH list (2014)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA154",
"Ebru, Turkish art of marbling",
"ebru",
"living-practice",
"People",
"F1.10",
"WA-ANA",
"",
"",
"Inscribed 2014",
"Marblers float pigments on thickened water and lift the pattern onto paper.",
"pigments; gum tragacanth size; ox gall; paper",
"marbled paper",
"record and writing",
"UNESCO ICH list (2014)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.28;F1.13",
"high",
"",
"canon_practices.csv"
],
[
"PRA155",
"Traditional craftsmanship of Çini-making",
"çini",
"living-practice",
"People",
"F1.10",
"WA-ANA",
"",
"",
"Inscribed 2016",
"Potters and painters make glazed tiles and wares in the Iznik tradition.",
"quartz-frit body; underglaze painting; glaze",
"tiles; plates",
"shelter;food and storage",
"UNESCO ICH list (2016)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.15",
"medium",
"Verify year.",
"canon_practices.csv"
],
[
"PRA156",
"Turkish coffee culture and tradition",
"Türk kahvesi",
"living-practice",
"People",
"F1.10",
"WA-ANA",
"",
"",
"Inscribed 2013",
"Makers roast and grind coffee finely and brew it in a cezve.",
"coffee; cezve; grinding",
"Turkish coffee",
"food and storage;ritual and belief",
"UNESCO ICH list (2013)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_practices.csv"
],
[
"PRA157",
"Karagöz",
"Karagöz shadow theatre",
"living-practice",
"People",
"F1.10",
"WA-ANA",
"",
"",
"Inscribed 2009",
"Makers cut coloured leather figures for shadow plays.",
"camel or cow hide; dyes; cutting",
"Karagöz figures",
"play and music",
"UNESCO ICH list (2009)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA158",
"Hüsn-i Hat, traditional calligraphy in Islamic art in Turkey",
"hüsn-i hat",
"living-practice",
"People",
"F1.10",
"WA-ANA",
"",
"",
"Inscribed 2021",
"Calligraphers write Arabic scripts in the Ottoman tradition with reed pens.",
"qalam; ink; burnished paper",
"levhas; murakkaa albums",
"record and writing;ritual and belief",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_practices.csv"
],
[
"PRA159",
"Traditional knowledge and skills in making Kyrgyz and Kazakh yurts (Turkic nomadic dwellings)",
"boz üy; kiiz üy",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Inscribed 2014 (Kazakhstan, Kyrgyzstan); extended 2025 as 'Traditional knowledge and skills in making Kyrgyz, Kazakh and Karakalpak yurts'",
"Kyrgyz and Kazakh makers build yurt frames and felt covers, men making the wood and women the felt and textiles.",
"willow; birch; felt; reed screens",
"yurts",
"shelter",
"UNESCO ICH list (2014)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18;F1.29",
"high",
"",
"canon_practices.csv"
],
[
"PRA160",
"Ala-kiyiz and Shyrdak, art of Kyrgyz traditional felt carpets",
"shyrdak",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Inscribed 2012, Urgent Safeguarding",
"Kyrgyz women make felt carpets by pressing coloured wool (ala-kiyiz) or cutting and sewing mosaic felt (shyrdak).",
"sheep wool; felting; mosaic cutting",
"ala-kiyiz; shyrdak",
"shelter",
"UNESCO ICH list (2012, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA161",
"Turkmen carpet weaving",
"Turkmen gul carpets",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Long-standing",
"Turkmen women knot carpets and tent bands with gul medallions associated with particular Turkmen groups.",
"wool; asymmetric knots; madder",
"main carpets; tent bands; bags",
"shelter;exchange and value",
"Turkmen weavers",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18",
"medium",
"UNESCO status unverified.",
"canon_practices.csv"
],
[
"PRA162",
"Suzani embroidery",
"suzani",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Surviving from the 18th century",
"Women embroider large cotton hangings for dowries in chain and couched stitches.",
"cotton; silk thread; basma couching",
"suzani hangings",
"shelter;ritual and belief",
"Uzbek and Tajik embroiderers",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA163",
"Chakan, embroidery art in the Republic of Tajikistan",
"chakan",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Inscribed 2018",
"Tajik women embroider dresses and hangings with colourful motifs.",
"cotton; silk thread; embroidery",
"dresses; hangings",
"clothing and adornment",
"UNESCO ICH list (2018)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA164",
"Central Asian ikat weaving",
"abr; atlas; adras",
"living-practice",
"People",
"F1.12a",
"AS-CEN",
"",
"",
"Long-standing; revived at Margilan",
"Dyers bind and dye warps and weavers make silk and half-silk ikat cloth.",
"silk; cotton; warp ikat",
"khan-atlas; adras",
"clothing and adornment",
"Uzbek dyers and weavers (Margilan)",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18",
"medium",
"",
"canon_practices.csv"
],
[
"PRA165",
"Compagnonnage, network for on-the-job transmission of knowledge and identities",
"compagnonnage",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2010; roots in medieval guild journeys",
"Journeymen in building, wood and metal trades travel between workshops to learn a craft and produce a masterpiece.",
"travelling apprenticeship; masterpiece",
"masterpieces; buildings",
"tools;shelter",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R1",
"F1.17",
"high",
"Project already holds PR-016.",
"canon_practices.csv"
],
[
"PRA166",
"Craftsmanship of mechanical watchmaking and art mechanics",
"watchmaking",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2020 (France, Switzerland)",
"Watchmakers in the Jura make mechanical movements and automata.",
"steel; brass; hand finishing",
"watches; automata; clocks",
"record and writing;tools",
"UNESCO ICH list (2020)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.19",
"high",
"",
"canon_practices.csv"
],
[
"PRA167",
"Art of glass beads",
"perle di vetro; perles de verre",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2020 (France, Italy)",
"Bead makers in Venice and France make glass beads at the flame and from drawn canes.",
"glass; lampworking; drawn canes",
"beads",
"clothing and adornment;exchange and value",
"UNESCO ICH list (2020)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_practices.csv"
],
[
"PRA168",
"Craft techniques and customary practices of cathedral workshops, or Bauhütten",
"Bauhütten",
"living-practice",
"People",
"F1.11",
"EU-WCE;EU-SCA",
"",
"",
"Selected 2020 for the Register of Good Safeguarding Practices (Austria, France, Germany, Norway, Switzerland); not a Representative List element",
"Cathedral workshops keep masons and other trades working together on repair across generations.",
"stone carving; glazing; carpentry",
"cathedral repairs",
"shelter;ritual and belief",
"UNESCO Register of Good Safeguarding Practices (2020)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.22a;F1.17",
"high",
"",
"canon_practices.csv"
],
[
"PRA169",
"Blaudruck/Modrotisk/Kékfestés/Modrotlač, resist block printing and indigo dyeing in Europe",
"Blaudruck",
"living-practice",
"People",
"F1.11",
"EU-WCE;EU-EER",
"",
"",
"Inscribed 2018 (Austria, Czechia, Germany, Hungary, Slovakia)",
"Printers block-print a resist paste on cloth and dye it in indigo.",
"carved blocks; resist paste; indigo",
"blue-print cloth",
"clothing and adornment",
"UNESCO ICH list (2018)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA170",
"Nordic clinker boat traditions",
"clinker boats",
"living-practice",
"People",
"F1.11",
"EU-SCA",
"",
"",
"Inscribed 2021 (Denmark, Finland, Iceland, Norway, Sweden)",
"Boatbuilders overlap planks and rivet them into light hulls.",
"overlapping planks; rivets; timber",
"clinker boats",
"transport",
"UNESCO ICH list (2021)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.28a",
"high",
"",
"canon_practices.csv"
],
[
"PRA171",
"Traditional violin craftsmanship in Cremona",
"Cremonese liuteria",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2012",
"Luthiers in Cremona make violins, violas, cellos and basses by hand.",
"spruce; maple; varnish",
"violins",
"play and music",
"UNESCO ICH list (2012)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA172",
"Art of dry stone construction, knowledge and techniques",
"dry stone walling",
"living-practice",
"People",
"F1.11",
"EU-WCE;EU-GRR;EU-IBE;EU-BLC",
"",
"",
"Inscribed 2018 as 'Art of dry stone walling, knowledge and techniques'; extended and renamed 2024",
"Wallers build terraces, walls and shelters without mortar.",
"stone; mortarless coursing",
"terraces; walls; huts",
"shelter;food and storage",
"UNESCO ICH list (2018; extended 2024)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.22",
"high",
"Multinational; check extension states.",
"canon_practices.csv"
],
[
"PRA173",
"Craftsmanship of Alençon needle lace-making",
"point d'Alençon",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2010",
"Lacemakers make needle lace in many specialist stages.",
"linen thread; needle lace",
"lace",
"clothing and adornment",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA174",
"Aubusson tapestry",
"Aubusson",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2009",
"Weavers make tapestries on low-warp looms from painted cartoons.",
"wool; low-warp loom; cartoons",
"tapestries",
"shelter;rule and display",
"UNESCO ICH list (2009)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.20",
"high",
"",
"canon_practices.csv"
],
[
"PRA175",
"Lacemaking in Croatia",
"Pag, Hvar and Lepoglava lace",
"living-practice",
"People",
"F1.11",
"EU-BYZ",
"",
"",
"Inscribed 2009",
"Women make needle, bobbin and agave lace in three Croatian centres.",
"linen; agave fibre; bobbins",
"lace",
"clothing and adornment",
"UNESCO ICH list (2009)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA176",
"Gingerbread craft from Northern Croatia",
"licitar",
"living-practice",
"People",
"F1.11",
"EU-BYZ",
"",
"",
"Inscribed 2010",
"Makers mould, bake and paint gingerbread hearts.",
"dough; moulds; food colouring",
"licitar hearts",
"food and storage;ritual and belief",
"UNESCO ICH list (2010)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA177",
"Craftmanship of Estremoz clay figures",
"bonecos de Estremoz",
"living-practice",
"People",
"F1.11",
"EU-IBE",
"",
"",
"Inscribed 2017",
"Makers model and paint clay figures of saints and daily life.",
"clay; modelling; painting",
"figures",
"ritual and belief;play and music",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_practices.csv"
],
[
"PRA178",
"Bisalhães black pottery manufacturing process",
"Bisalhães pottery",
"living-practice",
"People",
"F1.11",
"EU-IBE",
"",
"",
"Inscribed 2016, Urgent Safeguarding",
"Potters fire wares in pits sealed with earth to turn them black.",
"clay; wheel; pit reduction firing",
"black pots",
"food and storage",
"UNESCO ICH list (2016, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA179",
"Manufacture of cowbells",
"chocalhos",
"living-practice",
"People",
"F1.11",
"EU-IBE",
"",
"",
"Inscribed 2015, Urgent Safeguarding",
"Smiths cut, shape, braze and tune iron cowbells.",
"iron sheet; copper brazing; tuning",
"cowbells",
"tools;play and music",
"UNESCO ICH list (2015, Urgent Safeguarding)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.22a",
"high",
"",
"canon_practices.csv"
],
[
"PRA180",
"Craftsmanship of Horezu ceramics",
"Horezu",
"living-practice",
"People",
"F1.11",
"EU-BYZ",
"",
"",
"Inscribed 2012",
"Potters throw and slip-trail red clay wares with brown, green and blue designs.",
"red clay; slip trailing; horn tools",
"plates; jugs",
"food and storage",
"UNESCO ICH list (2012)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA181",
"Art of the traditional blouse with embroidery on the shoulder (altiţă)",
"ie; altiţă",
"living-practice",
"People",
"F1.11",
"EU-BYZ;EU-EER",
"",
"",
"Inscribed 2022 (Romania, Moldova)",
"Women sew and embroider the ie blouse with a shoulder band.",
"linen; cotton; embroidery",
"ie blouses",
"clothing and adornment",
"UNESCO ICH list (2022)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18;F1.2",
"high",
"Fashion-house copying case (F1.2).",
"canon_practices.csv"
],
[
"PRA182",
"Tradition of carpet-making in Chiprovtsi",
"Chiprovtsi kilims",
"living-practice",
"People",
"F1.11",
"EU-BYZ",
"",
"",
"Inscribed 2014",
"Women weave tapestry kilims on vertical looms.",
"wool; vertical loom; natural dyes",
"kilims",
"shelter",
"UNESCO ICH list (2014)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA183",
"Tinian marble craftsmanship",
"Tinos marble carving",
"living-practice",
"People",
"F1.11",
"EU-GRR",
"",
"",
"Inscribed 2015",
"Carvers on Tinos work marble for churches, houses and graves.",
"marble; chisels",
"fanlights; icon screens; grave markers",
"shelter;ritual and belief",
"UNESCO ICH list (2015)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.15",
"high",
"",
"canon_practices.csv"
],
[
"PRA184",
"Lefkara laces or Lefkaritika",
"Lefkaritika",
"living-practice",
"People",
"F1.11",
"EU-GRR",
"",
"",
"Inscribed 2009",
"Women in Lefkara make embroidered and drawn-thread lace.",
"linen; drawn thread; embroidery",
"lace",
"clothing and adornment;shelter",
"UNESCO ICH list (2009)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA185",
"Petrykivka decorative painting as a phenomenon of the Ukrainian ornamental folk art",
"Petrykivka",
"living-practice",
"People",
"F1.11",
"EU-EER",
"",
"",
"Inscribed 2013",
"Painters decorate houses and objects with floral brushwork.",
"paint; cat-hair brushes; fingertips",
"painted panels; walls",
"shelter;ritual and belief",
"UNESCO ICH list (2013)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.15",
"high",
"",
"canon_practices.csv"
],
[
"PRA186",
"Tradition of Kosiv painted ceramics",
"Kosiv ceramics",
"living-practice",
"People",
"F1.11",
"EU-EER",
"",
"",
"Inscribed 2019 (Representative List, not Urgent Safeguarding)",
"Potters paint slip designs on wheel-thrown wares.",
"clay; slip painting",
"plates; jugs",
"food and storage",
"UNESCO ICH list (2019)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA187",
"Handmade production of Christmas tree decorations from blown glass beads",
"Poděbrady glass decorations",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2020 (Czechia)",
"Makers blow, silver, colour and string glass beads into decorations.",
"glass tubing; blowing; silvering",
"ornaments",
"ritual and belief;play and music",
"UNESCO ICH list (2020)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_practices.csv"
],
[
"PRA188",
"Cross-crafting and its symbolism in Lithuania",
"kryždirbystė",
"living-practice",
"People",
"F1.11",
"EU-SCA",
"",
"",
"Proclaimed 2001, inscribed 2008",
"Carvers make wooden crosses and shrines with carved ornament.",
"oak; carving",
"crosses; roofed pillars",
"ritual and belief",
"UNESCO ICH list (2008; proclaimed 2001)",
"",
"living-community;sacred",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.16",
"high",
"Lithuania filed under EU-SCA (Baltic).",
"canon_practices.csv"
],
[
"PRA189",
"Organ craftsmanship and music",
"Orgelbau",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2017 (Germany)",
"Organ builders make pipes, wind systems and cases in specialist workshops.",
"metal pipes; wood; voicing",
"pipe organs",
"play and music;ritual and belief",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.4",
"high",
"",
"canon_practices.csv"
],
[
"PRA190",
"Craft of the miller operating windmills and watermills",
"molenaar",
"living-practice",
"People",
"F1.11",
"EU-BLC",
"",
"",
"Inscribed 2017 (Netherlands)",
"Millers maintain and run windmills and watermills to grind grain.",
"wind and water power; millstones",
"flour",
"food and storage;tools",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.22",
"high",
"",
"canon_practices.csv"
],
[
"PRA191",
"Skills related to perfume in Pays de Grasse",
"Grasse perfumery",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2018",
"Growers and perfumers cultivate flowers, extract essences and compose scents.",
"flowers; distillation; extraction",
"perfumes",
"care and access;exchange and value",
"UNESCO ICH list (2018)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.21",
"high",
"Official title includes \"the cultivation of perfume plants, the knowledge and processing of natural raw materials, and the art of perfume composition\".",
"canon_practices.csv"
],
[
"PRA192",
"Beer culture in Belgium",
"Belgian brewing",
"living-practice",
"People",
"F1.11",
"EU-BLC",
"",
"",
"Inscribed 2016",
"Brewers make many styles of beer, including monastic and spontaneous-fermentation beers.",
"malt; hops; fermentation",
"beers",
"food and storage",
"UNESCO ICH list (2016)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA193",
"Art of Neapolitan 'Pizzaiuolo'",
"pizzaiuolo",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2017",
"Pizza makers knead, shape and bake in wood-fired ovens.",
"dough; wood-fired oven",
"pizza",
"food and storage",
"UNESCO ICH list (2017)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_practices.csv"
],
[
"PRA194",
"Harris Tweed weaving",
"Clò Mòr",
"living-practice",
"People",
"F1.11",
"EU-BLC",
"",
"",
"Protected by the Harris Tweed Act 1993",
"Islanders of the Outer Hebrides handweave wool tweed at home.",
"wool; handloom; dyeing",
"tweed cloth",
"clothing and adornment",
"Harris Tweed Authority; Hebridean weavers",
"",
"living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.19;F1.23",
"high",
"Protected by statute rather than UNESCO.",
"canon_practices.csv"
],
[
"PRA195",
"Sámi duodji",
"duodji",
"living-practice",
"People",
"F1.11",
"EU-SCA",
"",
"",
"Long-standing",
"Sámi makers work reindeer hide, antler, wood and pewter thread into clothing, tools and containers.",
"reindeer hide; antler; birch burl; pewter thread",
"gákti; knives; guksi cups",
"clothing and adornment;tools;food and storage",
"Sámi duojárat",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.18;F1.2",
"high",
"Fake Sámi dress and souvenirs are an F1.2 issue.",
"canon_practices.csv"
],
[
"PRA196",
"Kraków nativity scene (szopka) tradition",
"szopka krakowska",
"living-practice",
"People",
"F1.11",
"EU-WCE",
"",
"",
"Inscribed 2018",
"Makers build ornate nativity scenes modelled on Kraków buildings.",
"cardboard; foil; wood",
"szopki",
"ritual and belief;play and music",
"UNESCO ICH list (2018)",
"",
"living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_practices.csv"
],
[
"PRA197",
"Pacific wayfinding",
"traditional navigation",
"living-practice",
"People",
"F1.12",
"OC-POL;OC-MIC;OC-MEL",
"",
"",
"Ancient; revived since the 1970s (Hōkūleʻa 1976 voyage)",
"Navigators read stars, swells, birds and clouds to voyage without instruments, and build the canoes that carry them.",
"star compass; swell reading; canoe building",
"voyaging canoes; stick charts",
"transport;record and writing",
"Pacific navigators; Polynesian Voyaging Society",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R1",
"F1.13;F1.29",
"high",
"Project already holds PR-010.",
"canon_practices.csv"
],
[
"PRA198",
"Carolinian wayfinding and canoe making",
"Carolinian navigation",
"living-practice",
"People",
"F1.12",
"OC-MIC",
"",
"",
"Inscribed 2021, Urgent Safeguarding (Federated States of Micronesia)",
"Carolinian navigators and builders make outrigger canoes and teach navigation.",
"breadfruit wood; sennit; star compass",
"outrigger canoes",
"transport",
"UNESCO ICH list (2021, Urgent Safeguarding)",
"",
"Indigenous-community;living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R2",
"F1.13;F1.29",
"medium",
"Verify title.",
"canon_practices.csv"
],
[
"PRA199",
"Tongan ngatu making",
"ngatu",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Long-standing",
"Tongan women beat hiapo bark into sheets, paste them and rub designs from kupesi tablets.",
"hiapo bark; beaters; kupesi; tongan dyes",
"ngatu; kupesi",
"clothing and adornment;exchange and value;ritual and belief",
"Tongan women's kautaha (work groups)",
"",
"Indigenous-community;living-community",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA200",
"Fijian masi making",
"masi",
"living-practice",
"People",
"F1.12",
"OC-MEL",
"",
"",
"Long-standing",
"Fijian women beat masi and print it with stencils.",
"paper mulberry bark; stencils; natural dyes",
"masi kesa",
"clothing and adornment;ritual and belief",
"Fijian masi makers (Moce, Vatulele)",
"",
"Indigenous-community;living-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA201",
"Hawaiian kapa making",
"kapa",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; revived from the 1970s",
"Kapa makers ferment and beat wauke bark and print designs with bamboo stamps.",
"wauke bark; beaters; ʻohe kāpala stamps",
"kapa",
"clothing and adornment;ritual and belief",
"Kanaka Maoli kapa makers",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA202",
"Samoan fine-mat weaving",
"ʻie tōga weaving",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Long-standing",
"Samoan women plait fine pandanus mats for exchange at life events.",
"pandanus; fine plaiting",
"ʻie tōga",
"exchange and value;ritual and belief",
"Samoan women weavers",
"",
"Indigenous-community;living-community",
"Te Papa Collections Online (per-item; link out where restricted); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA203",
"Marshallese jaki-ed weaving",
"jaki-ed",
"living-practice",
"People",
"F1.12",
"OC-MIC",
"",
"",
"Long-standing; revived",
"Marshallese women plait pandanus into clothing mats with fine borders.",
"pandanus; hibiscus fibre; plaiting",
"jaki-ed mats",
"clothing and adornment;shelter",
"Marshallese weavers",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.18",
"medium",
"",
"canon_practices.csv"
],
[
"PRA204",
"Whakairo (Māori carving)",
"whakairo",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; living",
"Māori carvers work wood, bone and pounamu into meeting houses, canoes and taonga.",
"tōtara; pounamu; bone; adzes and chisels",
"wharenui carvings; waka prows; hei tiki",
"ritual and belief;rule and display",
"Māori carvers",
"",
"Indigenous-community;ancestral;sacred",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); community-published site",
"R2",
"F1.24",
"high",
"NZ Māori Arts and Crafts Institute (Te Puia).",
"canon_practices.csv"
],
[
"PRA205",
"Raranga and whatu (Māori weaving)",
"raranga; whatu; tukutuku",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; living",
"Māori weavers plait harakeke and twine muka into cloaks, baskets and panels.",
"harakeke; muka; feathers; twining",
"kākahu cloaks; kete; tukutuku panels",
"clothing and adornment;food and storage;shelter",
"Māori weavers",
"",
"Indigenous-community;sacred",
"Te Papa Collections Online (per-item; link out where restricted); Auckland Museum Collections Online (per-item); community-published site",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA206",
"Tā moko",
"tā moko",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; revived",
"Tohunga tā moko carve and ink designs into skin that carry genealogy.",
"uhi chisels; needles; pigment",
"moko",
"clothing and adornment;ritual and belief",
"Māori tā moko practitioners",
"",
"Indigenous-community;sacred",
"community-published site",
"R3",
"F1.2;F1.24",
"high",
"Toi moko (preserved heads) are ancestral remains—never display; repatriation.",
"canon_practices.csv"
],
[
"PRA207",
"Samoan tatau",
"pe'a; malu",
"living-practice",
"People",
"F1.12",
"OC-POL",
"",
"",
"Pre-contact; unbroken",
"Tufuga ta tatau tap bone combs to mark the pe'a and malu.",
"au combs; mallet; soot pigment",
"pe'a; malu",
"clothing and adornment;ritual and belief",
"Samoan tufuga ta tatau",
"",
"Indigenous-community;sacred",
"community-published site",
"R3",
"F1.2",
"high",
"",
"canon_practices.csv"
],
[
"PRA208",
"Aboriginal fibre work",
"fibre weaving",
"living-practice",
"People",
"F1.12",
"OC-AUS",
"",
"",
"Ancient; living",
"Aboriginal women gather, dye and coil or twine fibres into baskets, mats, nets and sculptures.",
"pandanus; sedge; natural dyes; coiling; twining",
"dilly bags; mats; fish traps; fibre sculptures",
"food and storage;tools;clothing and adornment",
"Aboriginal weavers (e.g. Yolŋu, Ngarrindjeri, Tjanpi Desert Weavers)",
"",
"Indigenous-community;sacred",
"community-published site; Wikimedia Commons",
"R2",
"F1.18",
"high",
"Some designs and forms are restricted.",
"canon_practices.csv"
],
[
"PRA209",
"Bark painting",
"Arnhem Land bark painting",
"living-practice",
"People",
"F1.12",
"OC-AUS",
"",
"",
"Ancient; bark painting for exchange from the 20th century",
"Artists paint ochre on stringybark with fine brushes, including clan designs.",
"stringybark; ochre; rarrk crosshatching",
"bark paintings; larrakitj poles",
"ritual and belief;record and writing",
"Yolŋu and other Arnhem Land artists; art centres",
"",
"Indigenous-community;sacred",
"community-published site",
"R2",
"F1.24;F1.26",
"high",
"Yirrkala Bark Petitions (1963) are primary sources; designs may be restricted.",
"canon_practices.csv"
],
[
"PRA210",
"Western Desert acrylic painting",
"Papunya Tula",
"living-practice",
"People",
"F1.12",
"OC-AUS",
"1971",
"",
"Papunya, 1971",
"Artists paint Tjukurrpa in acrylic on board and canvas, first at Papunya.",
"acrylic; dotting; canvas",
"paintings",
"ritual and belief;exchange and value",
"Papunya Tula Artists and desert art centres",
"",
"Indigenous-community;sacred",
"community-published site",
"R2",
"F1.20;F1.24",
"high",
"Some early works showed restricted content and were withdrawn.",
"canon_practices.csv"
],
[
"PRA211",
"Budj Bim aquaculture",
"kooyang aquaculture",
"living-practice",
"People",
"F1.12",
"OC-AUS",
"-4600",
"",
"Channels c. 6,600 years old; living",
"Gunditjmara people build and maintain stone channels, weirs and woven traps to farm kooyang (eels).",
"basalt channels; weirs; woven eel baskets",
"eel traps; channels; stone huts",
"food and storage;tools",
"Gunditjmara people",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R1",
"F1.22;F1.3",
"high",
"Project already holds PR-018. Budj Bim is a World Heritage cultural landscape (2019), not a UNESCO ICH element.",
"canon_practices.csv"
],
[
"PRA212",
"Vanuatu sand drawings",
"sandroing",
"living-practice",
"People",
"F1.12",
"OC-MEL",
"",
"",
"Proclaimed 2003, inscribed 2008",
"Drawers trace continuous lines in sand to record rituals, stories and messages.",
"finger drawing in sand",
"sand drawings",
"record and writing;ritual and belief",
"UNESCO ICH list (2008; proclaimed 2003)",
"",
"Indigenous-community;living-community",
"UNESCO ICH lists (link out; per-item photo licence); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_practices.csv"
],
[
"PRA213",
"Bilum making",
"bilum",
"living-practice",
"People",
"F1.12",
"OC-MEL",
"",
"",
"Long-standing",
"Women in Papua New Guinea loop plant and synthetic fibre into net bags for carrying food and infants.",
"plant fibre; synthetic yarn; looping",
"bilums",
"food and storage;care and access;transport",
"PNG women bilum makers",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R2",
"F1.18",
"high",
"",
"canon_practices.csv"
],
[
"PRA214",
"Langa Langa shell money making",
"tafuliʻae",
"living-practice",
"People",
"F1.12",
"OC-MEL",
"",
"",
"Long-standing",
"Langa Langa makers grind, drill and string shell discs into currency used in bride price.",
"shell; drilling; grinding; stringing",
"tafuliʻae strings",
"exchange and value;ritual and belief",
"Langa Langa Lagoon makers (Malaita)",
"",
"Indigenous-community;living-community",
"Wikimedia Commons; community-published site",
"R3",
"F1.29",
"medium",
"",
"canon_practices.csv"
],
[
"TEC001",
"Oldowan core-and-flake knapping",
"Mode 1",
"technique",
"Things",
"F1.6;THEME",
"AF-HRN;AF-SWA;AF-SOU",
"-2600000",
"-1000000",
"Gona, Ethiopia c.2.6 Ma; Lomekwi 3 (Kenya) c.3.3 Ma contested; persists alongside Acheulean",
"Hominins struck sharp flakes from cobbles with a hammerstone, the earliest well-documented systematic tool-making.",
"hard-hammer percussion; basalt; quartz",
"choppers; flakes; cores",
"tools",
"archaeologists (Mary Leakey's Olduvai typology)",
"",
"none",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.28a",
"high",
"Lomekwian (3.3 Ma) should be noted as contested earlier case.",
"canon_techniques.csv"
],
[
"TEC002",
"Acheulean handaxe making",
"Mode 2; bifacial shaping",
"technique",
"Things",
"F1.6;F1.9;F1.9a;F1.11",
"AF-SWA;AF-HRN;AF-SOU;AS-SAS;WA-LEV;EU-WCE;EU-IBE",
"-1760000",
"-130000",
"Kokiselei, West Turkana c.1.76 Ma; ends at different times regionally",
"Knappers thinned a stone blank from both faces to a planned symmetrical form, showing a mental template carried over a million years.",
"bifacial percussion; soft-hammer thinning",
"handaxes; cleavers",
"tools",
"archaeologists (named after Saint-Acheul, France)",
"Named after a French site though earliest examples are African.",
"none",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R1",
"F1.3;F1.28a",
"high",
"",
"canon_techniques.csv"
],
[
"TEC003",
"Levallois prepared-core technique",
"Mode 3",
"technique",
"Things",
"F1.6;F1.9a;F1.11;F1.12a",
"AF-SWA;AF-SOU;WA-LEV;EU-WCE;AS-CEN",
"-400000",
"-40000",
"first known c.400–300 ka; earlier claims contested",
"Knappers shaped a core so that a flake of predetermined size and shape could be removed in one blow.",
"prepared-core percussion",
"Levallois flakes; points",
"tools",
"archaeologists (named after Levallois-Perret, France)",
"",
"none",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons; open-access excavation reports",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC004",
"Pressure flaking",
"pressure retouch",
"technique",
"Things",
"F1.6;F1.7;F1.11",
"AF-SOU;AM-WST;EU-WCE;AF-EGY;EU-SCA",
"-75000",
"",
"Blombos Cave silcrete points c.75 ka (Mourre et al. 2010)",
"Pushing a pointed tool against an edge (often of heat-treated stone) removes thin, controlled flakes, used for fine points such as Solutrean leaves, Egyptian ripple-flaked knives and Danish flint daggers.",
"antler or copper pressers",
"points; knives; daggers",
"tools;war",
"archaeologists",
"",
"none",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC005",
"Microlith production and hafting",
"composite tool making",
"technique",
"Things",
"F1.6;F1.9;F1.11;F1.12",
"AF-SOU;AS-SAS;EU-WCE;OC-AUS",
"-71000",
"",
"Pinnacle Point 5-6 c.71 ka; compound adhesives at Sibudu c.70 ka",
"Small standardised stone inserts were glued or bound into wooden or bone shafts to make replaceable composite tools and weapons.",
"backing; resin and ochre adhesives",
"microliths; arrows; barbed spears",
"tools;war",
"archaeologists",
"",
"none",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons; open-access excavation reports",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC006",
"Microblade technology",
"wedge-shaped core microblades",
"technique",
"Things",
"F1.12a;F1.8;F1.7",
"AS-NTH;AS-CHN;AS-JPN;AM-ARC",
"-25000",
"",
"c.25 ka in Siberia and North China; in Alaska by c.14 ka",
"Tiny parallel blades pressed from prepared cores were set into slotted bone and antler points, a toolkit carried into the Americas.",
"pressure blade removal; slotted bone points",
"microblades; composite points",
"tools",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC007",
"Edge-ground and polished stone",
"ground-stone axe making",
"technique",
"Things",
"F1.12;F1.8;F1.9a;F1.11;F1.7",
"OC-AUS;AS-JPN;WA-LEV;EU-WCE;OC-POL;AM-MES",
"-44000",
"",
"edge-ground axe fragment, Carpenter's Gap, Australia c.46–44 ka (Hiscock et al. 2016); Japan c.38 ka; Neolithic polishing widespread later",
"Grinding stone against abrasive sandstone and water produced durable edges and polished surfaces for axes, adzes and ornaments.",
"pecking; grinding; polishing",
"axes; adzes; celts; mortars",
"tools",
"archaeologists",
"Early Australian date overturns a Europe-centred 'Neolithic' definition.",
"none",
"Met Open Access (CC0); Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons; Auckland Museum Online Collection (CC BY where marked)",
"R2",
"F1.3;F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC008",
"Hardstone and jade working with abrasives",
"lapidary sawing and drilling of nephrite and jadeite",
"technique",
"Things",
"F1.8;F1.7;F1.12",
"AS-CHN;AM-MES;OC-POL;AS-ISE;AS-KOR",
"-6000",
"",
"Xinglongwa jade earrings c.6200–5400 BCE; Olmec jadeite; Māori pounamu",
"Because jade is too tough to carve, makers sawed, drilled and polished it with harder abrasive sand and string, bamboo or stone tools.",
"string sawing; tubular drilling; abrasive polishing",
"cong; bi; celts; hei-tiki; masks",
"ritual and belief;rule and display;clothing and adornment",
"archaeologists; makers",
"Pounamu is a taonga with protocols.",
"sacred;Indigenous-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; Te Papa Collections Online (CC BY where marked; otherwise link out); Wikimedia Commons",
"R2",
"F1.5;F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC009",
"Shell bead making",
"perforated shell beads",
"technique",
"Things",
"F1.6;F1.9a",
"AF-MAG;AF-SOU;WA-LEV",
"-100000",
"",
"perforated Nassarius shells at Skhul (c.100–135 ka), Taforalt (c.82 ka) and Blombos (c.75 ka)",
"Perforating and stringing small shells is among the oldest evidence of personal ornament and symbolic making.",
"perforation; ochre colouring; stringing",
"beads",
"clothing and adornment",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.15",
"high",
"",
"canon_techniques.csv"
],
[
"TEC010",
"Ostrich eggshell bead making",
"OES beads",
"technique",
"Things",
"F1.6",
"AF-SWA;AF-SOU;AF-HRN",
"-50000",
"",
"c.50 ka in East Africa (earlier claims exist); ongoing among San and other makers",
"Makers break, drill and grind ostrich eggshell into standard disc beads used in gift exchange over tens of thousands of years.",
"drilling; grinding; stringing",
"beads; aprons",
"clothing and adornment;exchange and value",
"archaeologists; San communities",
"",
"living-community",
"British Museum EMKP (CC); Wikimedia Commons; open-access journal articles",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC011",
"Bone and antler working",
"groove-and-splinter technique",
"technique",
"Things",
"F1.6;F1.11;F1.12a",
"AF-CEN;EU-WCE;EU-SCA;AS-NTH",
"-90000",
"",
"Katanda barbed bone points (DR Congo) c.90 ka, dating debated; groove-and-splinter in Upper Palaeolithic Europe",
"Makers split, ground and carved bone and antler into points, harpoons, needles and figures.",
"grooving; splitting; grinding",
"harpoons; points; needles; spear-throwers",
"tools",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC012",
"Eyed-needle sewing",
"bone needle sewing",
"technique",
"Things",
"F1.12a;F1.11",
"AS-NTH;WA-CAU;EU-EER",
"-40000",
"",
"earliest reliable eyed needles c. 45–40 ka in Siberia (Strashnaya Cave 44–49 ka); the Denisova Cave claim of c. 50 ka rests on one radiocarbon date and most of layer 11 dates 25–20 ka; Mezmaiskaya (Caucasus) 36–28 ka",
"The eyed needle allowed close-fitting sewn clothing, which made life in cold northern climates possible.",
"bone needles; sinew thread",
"needles; fitted garments",
"clothing and adornment;tools",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC013",
"Cordage and string twisting",
"plying",
"technique",
"Things",
"THEME;F1.11",
"EU-WCE",
"-50000",
"",
"three-ply cord fragment, Abri du Maras, France c.41–52 ka (Neanderthal)",
"Twisting and plying plant fibres into string underlies nets, snares, bags, textiles and binding.",
"twisting; plying; bast fibre",
"cord; string; nets",
"tools;clothing and adornment",
"archaeologists",
"",
"none",
"open-access journal articles",
"R3",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC014",
"Ochre and pigment processing",
"ochre grinding",
"technique",
"Things",
"F1.6;THEME",
"AF-SOU;AF-SWA",
"-100000",
"",
"Blombos Cave ochre-processing kits c.100 ka; ochre use c.300 ka at Olorgesailie",
"Grinding ochre and mixing it with binders in shell containers is among the earliest recipes for a manufactured material.",
"grinding; mixing binders; abalone-shell containers",
"pigment; paint kits",
"ritual and belief;clothing and adornment",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
