insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"TEC015",
"Rock painting",
"cave painting; parietal painting",
"technique",
"Things",
"F1.9;F1.6;F1.11;F1.12;F1.7",
"AS-ISE;OC-AUS;EU-IBE;EU-WCE;AF-SOU;AM-AND;AM-AMZ",
"-51000",
"",
"Leang Karampuang, Sulawesi c.51 ka; Iberian hand stencils >64 ka contested; ongoing in some communities",
"Painters applied ochre, charcoal and other pigments to rock by hand, brush, stencil and spray, in some places over tens of thousands of years.",
"spray stencilling; brush painting; pigment mixing",
"painted panels; hand stencils",
"ritual and belief;record and writing",
"archaeologists; communities",
"Many sites are sacred to living communities.",
"sacred;Indigenous-community",
"Wikimedia Commons; open-access excavation reports; community-published site",
"R2",
"F1.3;F1.16;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC016",
"Rock engraving",
"petroglyph making",
"technique",
"Things",
"F1.6;F1.12;F1.12a;F1.11;F1.7",
"AF-SOU;OC-AUS;AS-CEN;EU-SCA;AM-WST",
"-75000",
"",
"engraved ochre, Blombos c.75 ka; Murujuga petroglyphs possibly >40 ka; engraved shell at Trinil c.500 ka contested",
"Pecking, incising and abrading rock surfaces produced lasting images, from Murujuga to Tamgaly to Alta.",
"pecking; incising; abrading",
"petroglyphs; engraved plaques",
"ritual and belief;record and writing",
"archaeologists; communities",
"",
"sacred;Indigenous-community",
"Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out); community-published site",
"R3",
"F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC017",
"Fire-setting (mining)",
"fire-setting",
"technique",
"Things",
"F1.11;THEME",
"EU-BYZ;EU-BLC;EU-WCE",
"-5000",
"",
"Rudna Glava copper mine, Serbia, 5th millennium BCE; used until the 19th c.",
"Miners heated rock faces with fire so they cracked, then broke them with stone hammers to reach ore and flint.",
"fire; stone mauls; antler picks",
"mine galleries",
"tools",
"archaeologists; mining historians",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC018",
"Early fired-clay vessels",
"earliest pottery",
"technique",
"Things",
"F1.8;F1.6",
"AS-CHN;AS-JPN;AS-NTH;AF-SAH",
"-18000",
"",
"Xianrendong Cave, China c.20–19 ka BP; Japan c.16 ka; Ounjougou, Mali c.9400 BCE — invented several times",
"Hunter-gatherers in East Asia and later in the Sahara made fired clay vessels independently, long before farming.",
"coil or slab forming; open firing",
"cooking pots",
"food and storage",
"archaeologists",
"Undoes the idea that pottery follows agriculture.",
"none",
"open-access journal articles; Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC019",
"Coil building",
"coiling; hand-building; pinch forming",
"technique",
"Things",
"THEME",
"GL;AM-WST;AF-GUI;OC-MEL",
"",
"",
"among the earliest and most widespread forming methods; ongoing",
"Building vessels from rolled ropes of clay allows large and varied forms without a wheel, as in Pueblo, Nigerian and Papuan pottery.",
"coiling; scraping; smoothing",
"jars; pots; large storage vessels",
"food and storage",
"makers; archaeologists",
"Many coil traditions are women's practice.",
"living-community",
"Met Open Access (CC0); Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R2",
"F1.18;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC020",
"Paddle-and-anvil forming",
"beating",
"technique",
"Things",
"F1.9;F1.12;F1.6",
"AS-SAS;AS-MSE;AS-ISE;OC-MEL;AF-CEN",
"",
"",
"ancient; ongoing",
"Beating a clay form with a paddle against a stone or clay anvil held inside thins and shapes the wall.",
"paddling; anvil; carved paddles",
"cooking pots; water jars",
"food and storage",
"makers; ethnoarchaeologists",
"",
"living-community",
"Wikimedia Commons; open-access journal articles",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC021",
"Press-moulding",
"mould-made ceramics",
"technique",
"Things",
"F1.7;F1.9a;F1.8;F1.11",
"AM-AND;WA-MES;AS-CHN;EU-GRR",
"-2000",
"",
"moulded plaques in Mesopotamia early 2nd millennium BCE; Moche mould-made vessels 100–800 CE",
"Pressing clay into fired moulds allowed repeated figures and vessels in series, as in Moche portrait vessels and Roman lamps.",
"two-part moulds; slip joining",
"portrait vessels; lamps; plaques; figurines",
"food and storage;ritual and belief",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.14;F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC022",
"Potter's wheel throwing",
"wheel-throwing",
"technique",
"Things",
"F1.9a;F1.9;F1.8;F1.11;F1.6",
"WA-MES;WA-LEV;AS-SAS;AS-CHN;AF-EGY",
"-4500",
"",
"slow wheel in Mesopotamia and Levant c.4500–3500 BCE; fast wheel later and debated; not used in pre-Hispanic Americas",
"The rotating wheel allowed faster, thinner and more uniform vessels and often shifted pottery toward specialist workshops.",
"wheel-throwing; wheel-finishing",
"jars; bowls; cups",
"food and storage",
"archaeologists",
"Wheel pottery is not a measure of 'advancement'; many societies chose not to adopt it.",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC023",
"Slip casting",
"slip-cast ceramics",
"technique",
"Things",
"F1.11",
"EU-BLC",
"1740",
"",
"Staffordshire c.1740s with plaster-of-Paris moulds",
"Pouring liquid clay into absorbent plaster moulds made thin, identical wares in quantity, a basis of industrial ceramics.",
"plaster moulds; deflocculated slip",
"teapots; figures; sanitaryware",
"food and storage;care and access",
"historians of ceramics",
"",
"none",
"Met Open Access (CC0); V&A collections (link out); Wikimedia Commons",
"R3",
"F1.19",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC024",
"Burnishing",
"polishing leather-hard clay",
"technique",
"Things",
"THEME;F1.7;F1.6",
"GL;AM-WST;AF-GUI",
"",
"",
"ancient and widespread; ongoing (e.g. San Ildefonso blackware from 1918–19)",
"Rubbing leather-hard clay with a smooth stone compacts and shines the surface without glaze, as in San Ildefonso blackware.",
"polishing stones; slips",
"burnished pots; blackware",
"food and storage;ritual and belief",
"makers",
"",
"living-community",
"Met Open Access (CC0); Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC025",
"Open firing",
"bonfire firing; pit firing",
"technique",
"Things",
"THEME",
"GL",
"",
"",
"earliest firing method; ongoing",
"Firing pots in an open bonfire or pit with fuel packed around them needs no kiln and is still used by many potters.",
"bonfire; dung or wood fuel; smudging",
"cooking pots; water jars",
"food and storage",
"makers; ethnoarchaeologists",
"",
"living-community",
"Wikimedia Commons; open-access journal articles",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC026",
"Updraft kiln",
"two-chamber updraft kiln",
"technique",
"Things",
"F1.9a;F1.8;F1.6",
"WA-MES;AS-CHN;AF-EGY",
"-6000",
"",
"Halaf and Samarran kilns c.6000 BCE (e.g. Yarim Tepe); Yangshao kilns in China",
"Separating the firebox from the ware chamber gave potters more even and higher temperatures than open firing.",
"kiln building; wood firing",
"painted pottery",
"food and storage",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC027",
"Dragon kiln",
"longyao; climbing tube kiln",
"technique",
"Things",
"F1.8;F1.9",
"AS-CHN;AS-MSE",
"-1500",
"",
"proto-dragon kilns in Zhejiang in the Shang period; mature from Eastern Han",
"Long sloping tunnel kilns built up hillsides reached stoneware temperatures and fired thousands of pieces at once.",
"hillside kiln; wood firing",
"celadon; stoneware jars",
"food and storage;exchange and value",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.19",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC028",
"Anagama",
"tunnel kiln",
"technique",
"Things",
"F1.8",
"AS-KOR;AS-JPN",
"400",
"",
"introduced from Korea to Japan c.5th c. for Sue ware",
"A single-chamber sloping tunnel kiln whose long wood firings leave natural ash glaze and flashing on the ware.",
"wood firing; natural ash glaze",
"Sue ware; Bizen; Shigaraki",
"food and storage;ritual and belief",
"makers; archaeologists",
"",
"none",
"ColBase Japan national museums (Japan Government Standard Terms); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC029",
"Noborigama",
"multi-chamber climbing kiln",
"technique",
"Things",
"F1.8",
"AS-JPN;AS-KOR",
"1590",
"",
"Korean-derived chambered kilns in Karatsu c.1590s–1600s",
"A stepped series of chambers up a slope reuses heat from one chamber to the next, raising output for stoneware and porcelain.",
"chambered kiln; wood firing",
"Karatsu ware; Arita porcelain",
"food and storage",
"makers; historians",
"",
"none",
"ColBase Japan national museums (Japan Government Standard Terms); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.14",
"medium",
"Links to Korean potters diaspora.",
"canon_techniques.csv"
],
[
"TEC030",
"Ash glaze",
"natural and applied ash glaze",
"technique",
"Things",
"F1.8",
"AS-CHN;AS-JPN;AS-KOR",
"-1500",
"",
"Shang proto-porcelain in southern China c.1500 BCE",
"Wood ash, melting on or mixed into a glaze at high temperature, gives the earliest high-fired glazes in East Asia.",
"wood ash; feldspar; high firing",
"proto-porcelain; Sanage ware",
"food and storage",
"archaeologists; ceramic historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms)",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC031",
"Lead glaze",
"low-fired lead glaze; sancai",
"technique",
"Things",
"F1.8;F1.9a;F1.11;F1.10",
"AS-CHN;WA-ANA;EU-GRR;WA-IRN",
"-200",
"",
"Roman lead-glazed wares and Han China c.2nd–1st c. BCE; Tang sancai 8th c.",
"Lead-based glazes melt at low temperature and take bright copper greens, iron ambers and cobalt blues.",
"lead oxide; silica; colouring oxides",
"sancai figures; Roman glazed cups; slipware",
"food and storage;ritual and belief",
"ceramic historians",
"Lead exposure of workers.",
"funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R3",
"F1.23",
"medium",
"Independent inventions debated.",
"canon_techniques.csv"
],
[
"TEC032",
"Tin-opacified glaze",
"tin glaze; maiolica; faience; Delftware",
"technique",
"Things",
"F1.10;F1.11",
"WA-MES;EU-IBE;EU-WCE;EU-BLC",
"800",
"",
"Abbasid Basra c.8th–9th c.",
"Adding tin oxide made an opaque white glaze imitating Chinese porcelain, spreading from Iraq to Spain, Italy and the Netherlands.",
"tin oxide; lead glaze; in-glaze painting",
"maiolica; Delftware; azulejos",
"food and storage;rule and display",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Rijksmuseum (public-domain images); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC033",
"Lustre painting on ceramics",
"lustreware",
"technique",
"Things",
"F1.10;F1.11",
"WA-MES;AF-EGY;WA-IRN;EU-IBE",
"800",
"",
"lustre on glass in Egypt 8th c.; on ceramics in Abbasid Iraq 9th c.",
"A third firing in reducing conditions leaves nanoparticles of silver and copper that give a metallic sheen.",
"silver and copper pigments; reduction firing",
"lustre bowls; tiles",
"rule and display;ritual and belief",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC034",
"Celadon",
"greenware; Yue ware; Longquan; Goryeo cheongja",
"technique",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-MSE",
"100",
"",
"Yue wares from Eastern Han; Goryeo inlaid celadon 12th c.",
"Iron-bearing glazes fired in reduction turn jade-green, prized in China, Korea and across the Indian Ocean.",
"iron glaze; reduction firing; sanggam inlay",
"bowls; maebyeong; incense burners",
"food and storage;ritual and belief",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Museum of Korea e-museum (KOGL Type 1 where marked); National Palace Museum Taipei Open Data",
"R2",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC035",
"Porcelain making",
"hard-paste porcelain",
"technique",
"Things",
"F1.8;F1.11",
"AS-CHN;AS-KOR;AS-JPN;EU-WCE",
"580",
"",
"white porcelain in northern China 6th c.; Jingdezhen from Song; Meissen 1708–09",
"Kaolin and porcelain stone fired to about 1300°C make a white, translucent body that other regions spent centuries trying to copy.",
"kaolin; petuntse; high firing",
"bowls; vases; export wares",
"food and storage;rule and display;exchange and value",
"ceramic historians",
"Kiln workers and decorators, often unnamed.",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; Rijksmuseum (public-domain images); Cleveland Museum of Art Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms)",
"R1",
"F1.14;F1.13;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC036",
"Fritware",
"stonepaste; kashi",
"technique",
"Things",
"F1.10",
"WA-IRN;WA-MES;AF-EGY;WA-ANA",
"1100",
"",
"Seljuq Iran and Fatimid–Ayyubid Egypt c.11th–12th c.; İznik 15th–17th c.",
"Ground quartz with glass frit and a little clay gave Islamic potters a white body close to porcelain.",
"quartz; glass frit; alkaline glaze",
"İznik tiles; bowls",
"food and storage;shelter;rule and display",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0)",
"R2",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC037",
"Underglaze cobalt blue",
"blue-and-white",
"technique",
"Things",
"F1.8;F1.10",
"AS-CHN;WA-MES;WA-IRN",
"800",
"",
"cobalt on Abbasid wares 9th c.; Jingdezhen blue-and-white from c.1320s using Persian cobalt",
"Cobalt painted under a clear glaze produced blue-and-white wares traded and copied from Iran to Delft to Puebla.",
"cobalt oxide; underglaze painting",
"jars; dishes; kraak ware",
"food and storage;exchange and value",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; Rijksmuseum (public-domain images); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.13;F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC038",
"Overglaze enamel on ceramics",
"mina'i; doucai; famille rose; Imari",
"technique",
"Things",
"F1.8;F1.10",
"WA-IRN;AS-CHN;AS-JPN",
"1170",
"",
"mina'i ware in Iran late 12th c.; doucai 1460s; Arita enamels 1640s",
"Coloured enamels painted over a fired glaze and refired at lower temperature widened the palette of ceramics.",
"enamel pigments; low refiring",
"mina'i bowls; famille rose; Kakiemon",
"food and storage;rule and display",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms); National Palace Museum Taipei Open Data",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC039",
"Raku",
"raku-yaki",
"technique",
"Things",
"F1.8;THEME",
"AS-JPN",
"1575",
"",
"Chōjirō with Sen no Rikyū c.1570s–80s; Western 'raku' from c.1960 differs",
"Hand-shaped tea bowls pulled red-hot from the kiln and cooled quickly, made for the tea ceremony by the Raku family line.",
"hand shaping; quick firing",
"tea bowls",
"food and storage;ritual and belief",
"Raku family; tea masters",
"American post-firing reduction raku is a separate adaptation.",
"living-community",
"ColBase Japan national museums (Japan Government Standard Terms); Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC040",
"Salt glaze",
"salt-glazed stoneware",
"technique",
"Things",
"F1.11",
"EU-WCE;EU-BLC",
"1400",
"",
"Rhineland (Siegburg, Raeren) c.15th c.",
"Throwing salt into a hot kiln forms a thin orange-peel glaze on stoneware, used for Rhenish jugs and later English and American wares.",
"salt vapour glazing",
"Bartmann jugs; crocks",
"food and storage",
"ceramic historians",
"",
"none",
"Met Open Access (CC0); Rijksmuseum (public-domain images); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC041",
"Terra sigillata moulding",
"samian ware; Arretine ware",
"technique",
"Things",
"F1.11",
"EU-GRR;EU-WCE",
"-40",
"",
"Arretine ware from c.40 BCE; Gaulish samian 1st–3rd c. CE",
"Red gloss slip over bowls formed in stamped moulds produced standard tableware across the Roman Empire, often stamped with workshop names.",
"fine gloss slip; decorated moulds; potter's stamps",
"bowls; plates",
"food and storage",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; Europeana; Archaeology Data Service (open reports)",
"R2",
"F1.19;F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC042",
"Attic black-figure and red-figure",
"three-stage iron reduction firing",
"technique",
"Things",
"F1.11",
"EU-GRR",
"-700",
"-300",
"black-figure Corinth c.700 BCE; red-figure Athens c.530 BCE",
"Controlling oxidising and reducing phases turned a fine iron-rich slip black against the orange body, allowing painted scenes.",
"refined slip; three-stage firing",
"amphorae; kylikes; kraters",
"food and storage;ritual and belief",
"archaeologists; art historians (J.D. Beazley attributions)",
"Workshop labour, including enslaved workers.",
"none",
"Met Open Access (CC0); Walters Art Museum (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC043",
"Egyptian faience",
"self-glazing quartz ceramic",
"technique",
"Things",
"F1.6;F1.9a;F1.9",
"AF-EGY;WA-MES;AS-SAS",
"-4000",
"",
"Predynastic Egypt and Mesopotamia; Harappan faience",
"Ground quartz mixed with alkali forms its own glaze by efflorescence or cementation on firing, used for bright blue-green amulets and tiles.",
"quartz paste; efflorescence glazing",
"amulets; shabtis; tiles; beads",
"ritual and belief;clothing and adornment",
"archaeologists",
"",
"funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R2",
"F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC044",
"Polychrome slip painting (Andes and Mesoamerica)",
"Nasca polychrome; Maya polychrome",
"technique",
"Things",
"F1.7",
"AM-AND;AM-MES",
"-100",
"",
"Nasca from c.100 BCE; Maya Classic 250–900 CE",
"Many-coloured mineral slips burnished and fired produced painted vessels carrying mythic scenes and hieroglyphic texts.",
"mineral slips; burnishing; fine brushes",
"Nasca bowls; Maya cylinder vases",
"ritual and belief;food and storage",
"archaeologists",
"",
"funerary;conflict-looting",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.24",
"high",
"Many Maya vases looted.",
"canon_techniques.csv"
],
[
"TEC045",
"Qvevri making",
"kvevri",
"technique",
"Things",
"F1.9a;F1.11",
"WA-CAU",
"-6000",
"",
"wine residues in jars at Gadachrili Gora, Georgia c.6000 BCE; qvevri tradition ongoing (UNESCO 2013)",
"Georgian potters coil large egg-shaped jars, lined with beeswax and buried to ferment and store wine.",
"coiling; beeswax lining",
"qvevri",
"food and storage",
"makers; UNESCO",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC046",
"Core-formed glass",
"core-forming",
"technique",
"Things",
"F1.9a;F1.6",
"WA-MES;AF-EGY",
"-1500",
"",
"Mesopotamia and Egypt c.1500 BCE",
"Hot glass was trailed around a removable core of clay and dung, then combed into festoons, to make small vessels before blowing.",
"core; trailing; combing",
"alabastra; amphoriskoi",
"ritual and belief;care and access",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC047",
"Cast and cold-worked glass",
"mould-cast glass",
"technique",
"Things",
"F1.9a;F1.11;F1.6",
"WA-MES;EU-GRR;AF-EGY",
"-1500",
"",
"Late Bronze Age; Hellenistic cast bowls",
"Glass was cast in moulds or slumped over forms and then ground and polished like stone.",
"lost-wax and open moulds; grinding",
"bowls; inlays; plaques",
"food and storage;rule and display",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC048",
"Glassblowing",
"free-blowing; mould-blowing; cristallo",
"technique",
"Things",
"F1.9a;F1.11",
"WA-LEV;EU-GRR",
"-50",
"",
"Levant c.1st c. BCE; mould-blowing by 1st c. CE (e.g. Ennion)",
"Inflating a gather of glass on a blowpipe made glass cheap and fast to shape, spreading it across the Roman world and beyond.",
"blowpipe; moulds; annealing",
"bottles; cups; flasks",
"food and storage",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R1",
"F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC049",
"Enamelled and gilded glass",
"Mamluk enamelled glass",
"technique",
"Things",
"F1.10;F1.11",
"WA-LEV;AF-EGY",
"1170",
"",
"Syria and Egypt late 12th–14th c.; earlier Roman examples",
"Enamel and gold fired onto blown glass decorated mosque lamps, beakers and bottles later copied in Venice.",
"enamel painting; low refiring",
"mosque lamps; beakers",
"ritual and belief;rule and display",
"historians",
"",
"none",
"Met Open Access (CC0); Walters Art Museum (CC0); Cleveland Museum of Art Open Access (CC0)",
"R2",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC050",
"Cameo glass",
"cased and carved glass",
"technique",
"Things",
"F1.11;F1.8",
"EU-GRR;EU-BLC;AS-CHN",
"-25",
"",
"Roman c.25 BCE–50 CE (Portland Vase); 19th-c. English revival; Qing carved glass",
"Layers of differently coloured glass are cut back to leave a relief image.",
"casing; wheel cutting",
"vases; plaques; snuff bottles",
"rule and display",
"historians",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC051",
"Float glass",
"float process",
"technique",
"Things",
"F1.11;THEME",
"EU-BLC",
"1959",
"",
"Pilkington, announced 1959",
"Floating molten glass on molten tin made flat, even sheet glass at industrial scale for curtain walls and screens.",
"tin bath; continuous production",
"sheet glass",
"shelter",
"patent records; Pilkington",
"",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.19;F1.22",
"high",
"",
"canon_techniques.csv"
],
[
"TEC052",
"Indo-Pacific drawn glass beads",
"lada technique",
"technique",
"Things",
"F1.9",
"AS-SAS;AS-MSE;AS-ISE",
"-400",
"",
"Arikamedu, Mantai, Khao Sam Kaeo from c.4th c. BCE",
"Drawing hollow glass tubes and cutting them made small monochrome beads by the million, traded across the Indian Ocean.",
"glass drawing; cutting; reheating",
"seed beads",
"clothing and adornment;exchange and value",
"archaeologists (Peter Francis Jr.)",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC053",
"Ile-Ife glass making",
"Ife primary glass",
"technique",
"Things",
"F1.6",
"AF-GUI",
"1000",
"1500",
"c.11th–15th c. (Babalola et al. 2017)",
"Makers at Ile-Ife produced their own high-lime, high-alumina glass from local materials and made beads in quantity.",
"primary glass making; crucibles; bead drawing",
"glass beads; crucibles",
"clothing and adornment;rule and display",
"archaeologists (Abidemi Babalola)",
"Refutes the assumption that African glass beads were all imported.",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.3;F1.5",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC054",
"Cold-hammering native copper",
"annealed native copper working",
"technique",
"Things",
"F1.9a;F1.7",
"WA-ANA;WA-IRN;AM-EWD",
"-8000",
"",
"Çayönü, Anatolia c.8th millennium BCE; Old Copper Complex, Great Lakes c.5000–1000 BCE (some earlier)",
"Native copper was hammered and annealed into awls, beads and points without smelting, in Anatolia and independently around the Great Lakes.",
"hammering; annealing",
"awls; beads; points; knives",
"tools;clothing and adornment",
"archaeologists",
"",
"Indigenous-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); open-access excavation reports; Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC055",
"Copper smelting",
"extractive copper metallurgy",
"technique",
"Things",
"F1.11;F1.9a;F1.7",
"EU-BYZ;WA-IRN;WA-LEV;AM-AND",
"-5000",
"",
"Belovode, Serbia c.5000 BCE; Tal-i Iblis, Iran 5th millennium; independent Andean development later",
"Reducing copper ore in a hot charcoal fire produced metal from stone, a process invented more than once.",
"crucible and furnace smelting; charcoal",
"ingots; tools; ornaments",
"tools;exchange and value",
"archaeometallurgists",
"",
"none",
"open-access excavation reports; open-access journal articles; Wikimedia Commons",
"R1",
"F1.5;F1.22",
"high",
"",
"canon_techniques.csv"
],
[
"TEC056",
"Arsenical copper alloying",
"arsenical bronze",
"technique",
"Things",
"F1.9a;F1.11;F1.7",
"WA-LEV;WA-ANA;WA-CAU;WA-IRN;AM-AND",
"-4000",
"",
"Nahal Mishmar hoard c.3700 BCE; Andes later",
"Copper with arsenic was harder and castable, used for the Nahal Mishmar hoard and later in Andean metallurgy.",
"smelting arsenic-rich ores; casting",
"maceheads; axes; ornaments",
"tools;ritual and belief",
"archaeometallurgists",
"Arsenic fumes harmed smiths.",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC057",
"Tin bronze alloying",
"tin bronze",
"technique",
"Things",
"F1.9a;F1.11;F1.8;F1.9",
"WA-MES;WA-ANA;EU-BYZ;AS-CHN;AS-MSE",
"-3000",
"",
"tin bronze foil at Pločnik c.4650 BCE contested; regular use c.3000 BCE; China c.2000 BCE",
"Alloying copper with about ten per cent tin produced a stronger, better-casting metal whose supply drove long-distance trade.",
"alloying; casting",
"weapons; vessels; mirrors; drums",
"tools;war;ritual and belief",
"archaeometallurgists",
"'Bronze Age' dates differ by region.",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.5;F1.30",
"high",
"",
"canon_techniques.csv"
],
[
"TEC058",
"Lost-wax casting",
"cire perdue; investment casting",
"technique",
"Things",
"F1.9;F1.9a;F1.6;F1.7;F1.11",
"AS-SAS;WA-LEV;AF-GUI;AS-HIM;AM-CAM;AS-MSE",
"-4000",
"",
"Mehrgarh amulet c.4000 BCE (Thoury et al. 2016); Nahal Mishmar c.3700 BCE; Igbo-Ukwu 9th–10th c. CE; Benin, Chola, Newar, Muisca",
"A wax model encased in clay is melted out and replaced by metal, allowing complex one-off castings.",
"wax modelling; clay investment; casting",
"Benin plaques; Chola bronzes; tunjos; Akan goldweights",
"ritual and belief;rule and display",
"makers; archaeometallurgists",
"Benin works looted 1897.",
"conflict-looting;sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons; British Museum EMKP (CC)",
"R1",
"F1.5;F1.24",
"high",
"",
"canon_techniques.csv"
],
[
"TEC059",
"Piece-mould casting",
"section-mould bronze casting",
"technique",
"Things",
"F1.8",
"AS-CHN",
"-1700",
"-200",
"Erlitou c.1700 BCE to Han",
"Chinese founders cast ritual bronzes in assembled clay section-moulds, organised in large workshops such as those at Anyang.",
"clay piece-moulds; model carving; assembly",
"ding; gui; zun; bells",
"ritual and belief;rule and display;play and music",
"archaeologists",
"",
"funerary",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R2",
"F1.5;F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC060",
"Repoussé and chasing",
"sheet-metal embossing",
"technique",
"Things",
"F1.9a;F1.11;F1.7;F1.9",
"WA-MES;EU-GRR;AM-AND;AM-EWD;AS-HIM",
"-3000",
"",
"Mesopotamia and Egypt by 3rd millennium BCE; Andean goldwork; Mississippian copper plates; Newar metalwork",
"Hammering sheet metal from the back and refining from the front forms relief images and vessels.",
"annealing; pitch bowl; punches",
"vessels; plaques; masks; plates",
"rule and display;ritual and belief",
"makers",
"",
"sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC061",
"Granulation",
"gold granulation",
"technique",
"Things",
"F1.9a;F1.11",
"WA-MES;EU-GRR",
"-2500",
"",
"Ur c.2500 BCE; Etruscan fine granulation 7th c. BCE",
"Tiny gold spheres were fused to a gold ground by colloidal or eutectic bonding.",
"granule making; diffusion bonding",
"earrings; fibulae; pendants",
"clothing and adornment",
"archaeologists",
"",
"funerary",
"Met Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC062",
"Filigree",
"wirework",
"technique",
"Things",
"F1.9a;F1.11;F1.9;F1.7",
"WA-MES;EU-GRR;AS-SAS;AM-LAT",
"-2500",
"",
"Mesopotamia 3rd millennium BCE; ongoing (Cuttack, Mompox)",
"Fine twisted wires were soldered into openwork patterns in gold and silver.",
"wire twisting; soldering",
"earrings; boxes; frames",
"clothing and adornment",
"makers",
"",
"living-community",
"Met Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC063",
"Wire drawing",
"draw-plate wire drawing",
"technique",
"Things",
"F1.11;THEME",
"EU-SCA;EU-WCE",
"550",
"",
"earliest confirmed draw-plates 6th–8th c. CE (Old Uppsala, Vendel Period; Merovingian finds); Viking Age plates at Birka, Haithabu and Staraya Ladoga; drawn wire of Roman date claimed; earlier wire made by strip-twisting and hammering",
"Pulling metal through a series of shrinking holes produced uniform wire for chain mail, jewellery and later cables.",
"draw-plate; annealing",
"wire; mail; chains",
"clothing and adornment;war",
"archaeometallurgists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"",
"medium",
"Date of first draw-plate uncertain; verify.",
"canon_techniques.csv"
],
[
"TEC064",
"Leaf gilding",
"gold leaf; gold beating",
"technique",
"Things",
"F1.6;F1.8;F1.9",
"AF-EGY;AS-CHN;AS-MSE;AS-SAS",
"-2500",
"",
"Egypt Old Kingdom; ongoing (Mandalay gold beaters)",
"Gold beaten into leaves thinner than paper was laid over wood, gesso and stone.",
"gold beating; gesso; bole",
"coffins; Buddha images; frames",
"ritual and belief;rule and display",
"makers",
"",
"living-community;sacred",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC065",
"Fire gilding",
"mercury gilding; amalgam gilding",
"technique",
"Things",
"F1.8;F1.11",
"AS-CHN;EU-GRR;AS-JPN",
"-400",
"",
"Warring States China c.4th c. BCE; Roman",
"Gold dissolved in mercury was painted on and the mercury driven off by heat, poisoning many gilders.",
"mercury amalgam; heating",
"gilt bronzes; buckles; statues",
"ritual and belief;rule and display",
"archaeometallurgists",
"Mercury poisoning of gilders.",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC066",
"Depletion gilding",
"tumbaga; mise en couleur",
"technique",
"Things",
"F1.7",
"AM-CAM;AM-AND",
"1",
"",
"first millennium BCE–CE in Colombia and the Isthmus; Moche also used electrochemical plating",
"Gold–copper alloy objects were heated and treated with acidic plant juices to remove copper at the surface, leaving a gold-rich skin.",
"tumbaga casting; oxidation; pickling",
"pendants; nose ornaments",
"clothing and adornment;ritual and belief",
"archaeometallurgists (Heather Lechtman)",
"",
"sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.5",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC067",
"Niello inlay",
"niello",
"technique",
"Things",
"F1.11;F1.10",
"EU-GRR;EU-BYZ;WA-IRN;EU-EER",
"1",
"",
"Roman from 1st c. CE; Bronze Age black inlays debated",
"A black sulphide of silver or copper was fused into engraved lines in silver.",
"metal sulphides; engraving",
"spoons; reliquaries; belt fittings",
"rule and display;ritual and belief",
"historians",
"",
"none",
"Met Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC068",
"Metal inlay (damascening and koftgari)",
"inlaid brass; koftgari; Toledo damascene",
"technique",
"Things",
"F1.10;F1.9;F1.11",
"WA-IRN;WA-MES;AS-SAS;EU-IBE",
"1100",
"",
"Khurasan and Mosul inlaid brass 12th–13th c.; Mughal koftgari; Toledo damascene",
"Silver, gold and copper wire or sheet was hammered into engraved or cross-hatched grounds on brass or steel.",
"undercutting; cross-hatching; wire inlay",
"ewers; basins; weapons",
"rule and display;war",
"historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0)",
"R2",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC069",
"Bidri",
"bidriware",
"technique",
"Things",
"F1.9;F1.10",
"AS-SAS",
"1400",
"",
"Bahmani Bidar 14th–15th c.; ongoing",
"A zinc alloy cast in Bidar is inlaid with silver and blackened with a paste of soil and ammonium chloride.",
"zinc alloy casting; silver inlay; soil blackening",
"huqqa bases; boxes; basins",
"rule and display",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC070",
"Bloomery iron smelting",
"direct-process iron",
"technique",
"Things",
"F1.9a;F1.6;F1.11;F1.9",
"WA-ANA;WA-LEV;AF-SAH;AF-CEN;EU-WCE;AS-SAS",
"-1200",
"",
"widespread by c.1200 BCE in Anatolia and the Levant; early African dates (e.g. Termit, Nsukka) debated",
"Smelting iron ore below its melting point produced a spongy bloom that smiths consolidated by hammering, invented more than once.",
"bloomery furnace; forging",
"tools; weapons; hoes",
"tools;war",
"archaeometallurgists",
"Diffusion vs independent African invention is debated.",
"none",
"open-access excavation reports; open-access journal articles; Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC071",
"Blast furnace and cast iron",
"cast iron",
"technique",
"Things",
"F1.8;F1.11",
"AS-CHN;EU-SCA;EU-WCE",
"-500",
"",
"China c.5th c. BCE; Lapphyttan, Sweden c.1150–1350 CE",
"Tall furnaces made liquid iron that could be cast in moulds; China cast iron tools and moulds at scale from the Warring States.",
"blast furnace; moulds; decarburisation",
"ploughshares; pots; moulds",
"tools;food and storage",
"archaeometallurgists",
"",
"none",
"open-access excavation reports; open-access journal articles; Wikimedia Commons",
"R3",
"F1.5;F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC072",
"Haya preheated furnace",
"Haya steelmaking",
"technique",
"Things",
"F1.6",
"AF-SWA",
"1",
"",
"Schmidt and Avery (1978) dated preheated-blast smelting at KM2/KM3 (Kemondo Bay) to c. 1,500–2,000 years ago; the preheating and 'steel' claims were challenged by Rehder (1986) and Eggert (1987)",
"Haya smelters in northwest Tanzania ran furnaces with preheated air blasts, reconstructed in the 1970s with elders.",
"preheated tuyères; natural-draught and bellows furnaces",
"blooms; steel",
"tools",
"archaeologists (Peter Schmidt); Haya smelters",
"Reconstruction depended on Haya elders' knowledge.",
"Indigenous-community;living-community",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.28a;F1.3",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC073",
"Crucible steel",
"wootz; ukku; Damascus steel",
"technique",
"Things",
"F1.9;F1.12a;F1.10",
"AS-SAS;AS-CEN;WA-IRN",
"-300",
"",
"South India and Sri Lanka (Kodumanal, Tissamaharama) from late 1st millennium BCE; Merv 9th–10th c.",
"Iron and carbon sealed in clay crucibles produced high-carbon steel whose patterned blades were prized across West Asia.",
"crucible smelting; controlled forging",
"swords; ingots",
"war;tools",
"archaeometallurgists",
"",
"none",
"Met Open Access (CC0); open-access journal articles; Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC074",
"Pattern welding",
"pamor (Java)",
"technique",
"Things",
"F1.11;F1.9",
"EU-WCE;EU-SCA;EU-BLC;AS-ISE",
"200",
"",
"Roman and Migration Period swords from 2nd–3rd c.; Javanese kris pamor",
"Twisting and forge-welding bars of different iron and steel produced patterned, layered blades, in Europe and in Javanese kris.",
"forge welding; twisting; etching",
"swords; kris",
"war;ritual and belief",
"archaeologists; makers",
"",
"sacred;living-community",
"Met Open Access (CC0); Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC075",
"Tatara smelting",
"tatara-buki",
"technique",
"Things",
"F1.8",
"AS-JPN",
"550",
"",
"from c.6th c.; Edo-period form; still operated for tamahagane in Shimane",
"A clay box furnace fed with iron sand and charcoal for three days produces tamahagane steel for Japanese swords.",
"iron sand; clay furnace",
"tamahagane; swords",
"war;tools;ritual and belief",
"makers; historians",
"",
"living-community",
"ColBase Japan national museums (Japan Government Standard Terms); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC076",
"High-tin bronze forging",
"gong forging; bangjja",
"technique",
"Things",
"F1.9;F1.8",
"AS-ISE;AS-MSE;AS-KOR;AS-SAS",
"-400",
"",
"Ban Don Ta Phet, Thailand c.4th c. BCE; Javanese gamelan gongs; Korean bangjja yugi",
"Bronze with about 20–25 per cent tin, brittle when cast, is hot-forged and quenched to make resonant gongs and bowls.",
"hot forging; quenching",
"gongs; bowls; mirrors",
"play and music;food and storage",
"archaeometallurgists; makers",
"",
"living-community",
"Met Open Access (CC0); National Museum of Korea e-museum (KOGL Type 1 where marked); Wikimedia Commons",
"R3",
"F1.4",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC077",
"Cloisonné enamel",
"cloisonné",
"technique",
"Things",
"F1.11;F1.8",
"EU-GRR;EU-BYZ;AS-CHN;AS-JPN",
"-1300",
"",
"Cypriot rings c.13th–12th c. BCE; Byzantine 9th–12th c.; Chinese jingtai 15th c.",
"Enamel was fused into cells formed by thin metal strips soldered to a base.",
"cloisons; vitreous enamel",
"icons; reliquaries; vases",
"ritual and belief;rule and display",
"historians",
"",
"sacred",
"Met Open Access (CC0); Walters Art Museum (CC0); National Palace Museum Taipei Open Data",
"R3",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC078",
"Champlevé enamel",
"Limoges enamel",
"technique",
"Things",
"F1.11",
"EU-WCE;EU-BLC",
"-300",
"",
"La Tène red enamel; Limoges 12th–13th c.",
"Enamel fills troughs carved or cast into a thick metal surface.",
"carving; vitreous enamel",
"reliquaries; fittings; chasses",
"ritual and belief",
"historians",
"",
"sacred",
"Met Open Access (CC0); Walters Art Museum (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC079",
"Zinc distillation",
"Zawar zinc smelting",
"technique",
"Things",
"F1.9",
"AS-SAS",
"900",
"",
"Zawar, Rajasthan c.9th c. CE onward; industrial scale 12th–18th c.",
"Rajasthani smelters used inverted retorts to condense zinc vapour, the earliest large-scale production of metallic zinc.",
"downward distillation; retorts",
"zinc ingots; brass; bidri alloy",
"tools;exchange and value",
"archaeometallurgists (Paul Craddock)",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC080",
"Patio process",
"mercury amalgamation of silver",
"technique",
"Things",
"F1.7",
"AM-LAT;AM-AND",
"1554",
"",
"Bartolomé de Medina, Pachuca 1554; used at Potosí from 1570s",
"Mixing crushed ore with mercury and salt in open patios made Spanish American silver mining vastly productive, using forced mita labour and poisoning workers.",
"amalgamation; mercury",
"silver bars; coins",
"exchange and value",
"historians",
"Andean mitayos and enslaved workers.",
"human-flow",
"Library of Congress (public-domain items); Wikimedia Commons",
"R3",
"F1.22;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC081",
"Sericulture and silk reeling",
"silk production",
"technique",
"Things",
"F1.8",
"AS-CHN",
"-3000",
"",
"silk fabric at Qianshanyang c.2700 BCE; silk proteins at Jiahu c.6500 BCE claimed",
"Raising silkworms on mulberry and reeling continuous filament from cocoons gave China a fibre it controlled for centuries.",
"mulberry cultivation; reeling; throwing",
"silk thread; fabric",
"clothing and adornment;exchange and value",
"historians; archaeologists",
"Largely women's labour.",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; Wikimedia Commons",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC082",
"Bast fibre processing",
"retting; scutching; hackling",
"technique",
"Things",
"F1.9a;F1.11;F1.8",
"WA-CAU;WA-LEV;EU-WCE;AS-CHN",
"-30000",
"",
"dyed wild flax fibres, Dzudzuana Cave, Georgia c.30 ka (contested); linen at Nahal Hemar c.6500 BCE",
"Rotting and beating flax, hemp or ramie stems frees long fibres for spinning linen and cordage.",
"retting; scutching; hackling",
"linen; cordage",
"clothing and adornment",
"archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC083",
"Drop-spindle spinning",
"hand spindle spinning; supported spindle",
"technique",
"Things",
"THEME;F1.9a;F1.7",
"GL;WA-LEV;AM-AND",
"-7000",
"",
"spindle whorls in the Neolithic Near East c.7th millennium BCE; ongoing",
"A weighted spindle twists fibre into yarn, a portable technique that occupied much of many women's time.",
"spindle; whorl; distaff",
"yarn",
"clothing and adornment",
"archaeologists; makers",
"Hours of spinning labour are rarely counted.",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC084",
"Spinning wheel",
"charkha; great wheel",
"technique",
"Things",
"F1.9;F1.8;F1.10;F1.11",
"AS-SAS;AS-CHN;WA-IRN;EU-WCE",
"1000",
"",
"c.1000 CE in Asia (origins debated); Europe 13th c.; Gandhi's charkha 1920s",
"Turning a wheel to spin the spindle sped yarn production and later became a political symbol in India's swadeshi movement.",
"wheel spinning",
"yarn",
"clothing and adornment",
"historians",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; Library of Congress (public-domain items)",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC085",
"Backstrap loom weaving",
"body-tensioned loom",
"technique",
"Things",
"F1.7;F1.9;F1.8",
"AM-MES;AM-AND;AS-MSE;AS-ISE;AS-CHN;AS-HIM",
"-5000",
"",
"loom parts at Hemudu, China c.5000 BCE; ancient in the Andes and Mesoamerica; ongoing",
"The weaver tensions the warp with her body, producing fine cloth on a portable loom still used from Guatemala to Laos.",
"backstrap loom; supplementary weft",
"huipiles; sashes; cloth",
"clothing and adornment",
"makers; archaeologists",
"",
"living-community;Indigenous-community",
"Met Open Access (CC0); Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R2",
"F1.18;F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC086",
"Warp-weighted loom",
"warp-weighted loom",
"technique",
"Things",
"F1.11;F1.9a",
"EU-WCE;EU-SCA;WA-ANA;EU-GRR",
"-5500",
"",
"loom weights from Neolithic southeast Europe and Anatolia; in use in Scandinavia into the 20th c.",
"An upright loom with clay or stone weights on the warp made wide woollen cloth and sails.",
"clay loom weights; upright loom",
"cloth; sails",
"clothing and adornment;transport",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC087",
"Horizontal ground loom",
"staked ground loom",
"technique",
"Things",
"F1.6;F1.9a;F1.12a;F1.10",
"AF-EGY;WA-ARB;AS-CEN;WA-IRN",
"-3700",
"",
"possible loom on a Naqada I–II bowl from Badari tomb 3802 (Petrie Museum UC9547), c. 3900–3500 BCE; used by Bedouin and Central Asian weavers today",
"Warp stretched between beams pegged to the ground allows long cloth and tent strips to be woven by nomadic weavers.",
"ground loom",
"linen; tent bands; rugs",
"clothing and adornment;shelter",
"archaeologists; makers",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC088",
"Treadle loom",
"foot-powered loom; horizontal frame loom",
"technique",
"Things",
"F1.8;F1.11;F1.9",
"AS-CHN;EU-WCE;AS-SAS",
"-200",
"",
"Han China depictions; Europe 11th c.",
"Foot pedals lifting harnesses freed the weaver's hands and sped plain and twill weaving.",
"treadles; heddles",
"cloth",
"clothing and adornment",
"historians of technology",
"",
"none",
"Wikimedia Commons; open-access journal articles",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC089",
"Drawloom",
"pattern loom",
"technique",
"Things",
"F1.8;F1.10;F1.11",
"AS-CHN;WA-IRN;EU-WCE",
"-150",
"",
"Laoguanshan, Chengdu loom models c.2nd c. BCE (pattern loom; whether a drawloom proper is debated)",
"A second person pulling pattern cords allowed complex repeating figured silks.",
"figure harness; draw-boy",
"figured silks; lampas",
"clothing and adornment;rule and display",
"historians of textiles",
"",
"none",
"Met Open Access (CC0); open-access journal articles",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC090",
"Jacquard loom",
"Jacquard mechanism",
"technique",
"Things",
"F1.11",
"EU-WCE",
"1804",
"",
"Joseph-Marie Jacquard 1804",
"Punched cards selected warp threads automatically, displacing draw-boys and inspiring early computing.",
"punched cards; figure harness",
"figured silks; portraits in silk",
"clothing and adornment",
"patents; historians",
"Lyon silk workers' revolts (1831, 1834).",
"none",
"Met Open Access (CC0); Wikimedia Commons; Google Patents / national patent offices (public documents)",
"R2",
"F1.19;F1.21",
"high",
"",
"canon_techniques.csv"
],
[
"TEC091",
"Power loom and mechanised spinning",
"mechanised weaving; flying shuttle; spinning jenny; water frame; spinning mule",
"technique",
"Things",
"F1.11",
"EU-BLC",
"1785",
"",
"flying shuttle 1733 (John Kay); jenny c.1764, water frame 1769, mule 1779; power loom 1785 (Edmund Cartwright)",
"Spinning machines and then steam-driven looms moved textile making into factories and undercut hand weavers in Britain and India.",
"flying shuttle; power loom",
"cotton cloth",
"clothing and adornment",
"patents; historians",
"Displaced handloom weavers in Britain and India.",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC092",
"Tapestry weaving",
"kesi; kilim; tapestry",
"technique",
"Things",
"F1.6;F1.7;F1.11;F1.8",
"AF-EGY;AM-AND;EU-WCE;AS-CHN",
"-1400",
"",
"Thutmose IV tomb tapestry c.1400 BCE; Andean tapestry tunics; Chinese kesi from Tang",
"Discontinuous wefts beaten down to hide the warp let weavers build images colour by colour.",
"discontinuous weft; interlocking",
"tunics; hangings; kilims",
"clothing and adornment;rule and display",
"historians of textiles",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); National Palace Museum Taipei Open Data",
"R2",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC093",
"Brocade",
"supplementary-weft patterning; songket; kinkhab",
"technique",
"Things",
"F1.8;F1.9;F1.10",
"AS-CHN;AS-SAS;AS-ISE;WA-IRN",
"500",
"",
"supplementary-weft silks by mid-1st millennium CE; earliest date depends on definition",
"Extra pattern wefts, often gold or silver thread, float over a ground weave.",
"supplementary weft; metallic thread",
"songket; Banarasi saris; robes",
"clothing and adornment;rule and display",
"historians of textiles",
"",
"living-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC094",
"Samite",
"weft-faced compound twill",
"technique",
"Things",
"F1.12a;F1.10;F1.11",
"WA-IRN;AS-CEN;EU-BYZ",
"500",
"",
"Sasanian, Sogdian and Byzantine silks c.6th c.",
"A compound twill with hidden binding warps produced the roundel silks traded across Eurasia.",
"compound weave",
"roundel silks; reliquary wrappings",
"clothing and adornment;ritual and belief",
"historians of textiles",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC095",
"Velvet weaving",
"pile weaving",
"technique",
"Things",
"F1.10;F1.11",
"WA-ANA;EU-WCE;WA-IRN",
"1300",
"",
"Italian velvets 14th c.; Ottoman Bursa and Safavid velvets; earlier origins debated",
"Extra warp loops woven over rods and cut form a soft pile, often patterned in gold.",
"pile warp; rods",
"kaftans; hangings",
"clothing and adornment;rule and display",
"historians of textiles",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Rijksmuseum (public-domain images)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC096",
"Warp ikat",
"ikat; abrband",
"technique",
"Things",
"F1.9;F1.12a;F1.7;F1.10",
"AS-ISE;AS-CEN;AM-AND;AS-SAS;WA-ARB",
"600",
"",
"depicted at Ajanta c.5th–6th c.; Yemeni ikat 10th c.; antiquity likely greater",
"Warp threads are tied and dyed before weaving, so the pattern blurs slightly as it emerges.",
"resist binding; dyeing; weaving",
"robes; hangings; shrouds",
"clothing and adornment;ritual and belief",
"makers; historians",
"The Malay word 'ikat' was adopted by Dutch scholars.",
"living-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Rijksmuseum (public-domain images)",
"R2",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC097",
"Double ikat",
"patola; geringsing",
"technique",
"Things",
"F1.9",
"AS-SAS;AS-ISE",
"1300",
"",
"patola in Gujarat by c.13th–14th c.; geringsing in Tenganan, Bali",
"Both warp and weft are resist-dyed so that pattern appears only when they align, made in Patan and Tenganan.",
"double resist; precise alignment",
"patola; geringsing",
"clothing and adornment;ritual and belief;exchange and value",
"makers (Salvi family, Patan)",
"",
"living-community;sacred",
"Met Open Access (CC0); Rijksmuseum (public-domain images); Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC098",
"Jamdani",
"jamdani muslin",
"technique",
"Things",
"F1.9",
"AS-SAS",
"1600",
"",
"Mughal-era Dhaka muslin; UNESCO 2013",
"Discontinuous supplementary wefts inlaid by hand on fine cotton make floral patterns in Bengal muslin.",
"discontinuous supplementary weft; fine cotton",
"saris; muslins",
"clothing and adornment",
"makers; UNESCO",
"",
"living-community",
"Met Open Access (CC0); V&A collections (link out); UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC099",
"Narrow-strip weaving",
"kente; strip cloth",
"technique",
"Things",
"F1.6",
"AF-GUI;AF-SAH",
"1050",
"",
"Tellem caves, Mali c.11th c.; Asante and Ewe kente 17th–18th c.",
"Long narrow strips woven on double-heddle treadle looms are sewn edge to edge into large cloths.",
"double-heddle loom; strip joining",
"kente; kita; pagne",
"clothing and adornment;rule and display",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); British Museum EMKP (CC); Wikimedia Commons",
"R2",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC100",
"Felt making",
"fulled wool felt",
"technique",
"Things",
"F1.12a;F1.9a",
"AS-CEN;AS-NTH;WA-ANA",
"-2000",
"",
"Pazyryk felts c.4th–3rd c. BCE; earlier Bronze Age examples",
"Wool matted with heat, moisture and pressure makes a dense fabric for tents, carpets and clothing without spinning or weaving.",
"rolling; fulling; appliqué",
"yurt covers; shyrdak; hats",
"shelter;clothing and adornment",
"archaeologists; makers",
"",
"living-community;funerary",
"Met Open Access (CC0); Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R2",
"F1.18;F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC101",
"Knotted-pile carpet weaving",
"hand-knotted carpets",
"technique",
"Things",
"F1.12a;F1.10",
"AS-CEN;WA-IRN;WA-ANA;WA-CAU;AS-HIM;AS-SAS",
"-400",
"",
"Pazyryk carpet c.4th–3rd c. BCE",
"Rows of wool knots tied around warp threads and clipped make a durable, patterned pile.",
"symmetrical and asymmetrical knots; Tibetan knot",
"carpets; saddle covers",
"shelter;rule and display",
"historians; makers",
"Child labour in some modern production.",
"funerary;living-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R2",
"F1.13;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC102",
"Looping and nålbinding",
"bilum; needle-binding",
"technique",
"Things",
"F1.12;F1.11;F1.9a",
"OC-MEL;EU-SCA;WA-LEV",
"-6500",
"",
"looped fabrics at Nahal Hemar c.6500 BCE; bilum making ongoing in Papua New Guinea",
"Loops of a single thread worked with a needle or fingers make stretchy bags and garments, as in Papua New Guinean bilum.",
"looping; single needle",
"bilums; socks; bags",
"clothing and adornment;food and storage",
"makers; archaeologists",
"",
"living-community",
"Wikimedia Commons; Auckland Museum Online Collection (CC BY where marked)",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC103",
"Knotting and netting",
"net making",
"technique",
"Things",
"THEME;F1.11",
"EU-SCA;GL",
"-8300",
"",
"Antrea net, Finland c.8300 BCE",
"Knotted nets captured fish and game and carried loads.",
"mesh gauges; knotting",
"fishing nets; bags",
"food and storage;tools",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC104",
"Khipu construction",
"quipu",
"technique",
"Things",
"F1.7",
"AM-AND",
"600",
"",
"Wari khipu c.600 CE; Inca khipu to 16th c.; earlier Caral example contested",
"Cords spun, plied, dyed and knotted in fixed positions recorded numbers and possibly narrative for the Inca state.",
"plying direction; knot types; colour coding",
"khipu",
"record and writing;rule and display",
"scholars (Khipu Database Project); Andean communities",
"Khipu decipherment remains incomplete; communities still keep some khipu.",
"Indigenous-community",
"Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.5;F1.28",
"high",
"",
"canon_techniques.csv"
],
[
"TEC105",
"Coiled basketry",
"coiling",
"technique",
"Things",
"F1.7;F1.6;THEME",
"AM-WST;AM-EWD;AF-SOU;AF-GUI",
"-6000",
"",
"coiled baskets in the Great Basin and Egypt by the Holocene; ongoing",
"Stitching a continuous bundle into a spiral makes watertight baskets, trays and granaries.",
"bundle foundation; stitching; awls",
"baskets; trays; winnowers",
"food and storage",
"makers",
"",
"living-community;Indigenous-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC106",
"Twined basketry",
"twining",
"technique",
"Things",
"F1.7;F1.11;THEME",
"AM-WST;AM-NWC;EU-WCE",
"-26000",
"",
"twined textile impressions at Dolní Věstonice c.26 ka; ongoing",
"Pairs of weft elements twisted around warps make bags, hats and mats, including Northwest Coast spruce-root hats.",
"twining; spruce root; cedar bark",
"hats; bags; mats",
"food and storage;clothing and adornment",
"makers; archaeologists",
"",
"living-community;Indigenous-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC107",
"Plaiting",
"checker and twill plaiting; pandanus plaiting",
"technique",
"Things",
"F1.12;F1.9;THEME",
"OC-POL;OC-MIC;AS-ISE;AF-MAD",
"",
"",
"ancient; ongoing",
"Interlacing flat strips of pandanus, palm or bamboo makes mats, sails and baskets across the Pacific and Southeast Asia.",
"pandanus; coconut leaf; bamboo",
"mats; sails; fine mats ('ie toga)",
"shelter;transport;exchange and value",
"makers",
"",
"living-community",
"Auckland Museum Online Collection (CC BY where marked); Te Papa Collections Online (CC BY where marked; otherwise link out); Wikimedia Commons",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC108",
"Barkcloth beating",
"tapa; siapo; ngatu; kapa",
"technique",
"Things",
"F1.12;F1.9;F1.6;F1.7",
"OC-POL;AS-ISE;AF-SWA;AM-MES;AS-CHN",
"-6000",
"",
"stone beaters in southern China c.6000 BCE; Pacific tapa; Ugandan barkcloth (UNESCO 2008)",
"Inner bark of mulberry and fig trees is soaked and beaten into sheets, then decorated, across the Pacific, Africa and Mesoamerica.",
"beating; felting; stencilling",
"tapa; ngatu; barkcloth",
"clothing and adornment;exchange and value;ritual and belief",
"makers; archaeologists",
"",
"living-community;Indigenous-community",
"Te Papa Collections Online (CC BY where marked; otherwise link out); Auckland Museum Online Collection (CC BY where marked); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC109",
"Featherwork",
"feather mosaic; feather cloaks",
"technique",
"Things",
"F1.7;F1.12",
"AM-AND;AM-MES;OC-POL;AM-AMZ",
"600",
"",
"Wari feather panels c.600–900; Hawaiian ʻahu ʻula; Nahua amanteca feather mosaic; Amazonian featherwork ongoing",
"Feathers tied into netting or glued to backings made cloaks, headdresses and mosaics of high rank.",
"feather knotting; netting; gluing",
"cloaks; headdresses; panels",
"rule and display;ritual and belief",
"makers; historians",
"Much featherwork is sacred and restricted.",
"sacred;Indigenous-community",
"Met Open Access (CC0); Te Papa Collections Online (CC BY where marked; otherwise link out); Wikimedia Commons",
"R3",
"F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC110",
"Porcupine quillwork",
"quill embroidery",
"technique",
"Things",
"F1.7",
"AM-EWD;AM-WST;AM-ARC",
"",
"",
"pre-contact; ongoing",
"Flattened, dyed porcupine quills are sewn or wrapped onto hide and birchbark.",
"quill flattening; dyeing; sewing",
"moccasins; bags; birchbark boxes",
"clothing and adornment",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC111",
"Beadwork",
"seed-bead embroidery; loom beadwork",
"technique",
"Things",
"F1.7;F1.6",
"AM-WST;AM-EWD;AF-SOU;AF-SWA;AF-GUI",
"",
"",
"shell and seed beadwork ancient; glass seed-bead work expands with trade beads from 16th–19th c.; ongoing",
"Sewing and weaving glass beads into garments and regalia created visual languages from Lakota to Zulu to Yoruba.",
"lazy stitch; netting; loom",
"regalia; crowns; bags",
"clothing and adornment;rule and display",
"makers",
"",
"living-community;Indigenous-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC112",
"Embroidery",
"needlework",
"technique",
"Things",
"THEME;F1.8",
"GL;AS-CHN",
"-400",
"",
"chain-stitch silk embroidery at Mashan, China c.4th–3rd c. BCE; earlier fragmentary evidence",
"Stitching thread onto a ground fabric adds pattern and image and is one of the most widespread decorative crafts.",
"chain stitch; satin stitch; couching",
"robes; panels; samplers",
"clothing and adornment;ritual and belief",
"makers",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Rijksmuseum (public-domain images)",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC113",
"Opus anglicanum",
"English medieval goldwork",
"technique",
"Things",
"F1.11",
"EU-BLC",
"1200",
"1350",
"approximate",
"Professional London workshops embroidered silk and gold vestments using underside couching, prized by popes.",
"underside couching; split stitch",
"copes; chasubles",
"ritual and belief",
"historians",
"Women embroiderers named in few records.",
"sacred",
"Met Open Access (CC0); V&A collections (link out)",
"R3",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC114",
"Kantha",
"kantha stitch",
"technique",
"Things",
"F1.9",
"AS-SAS",
"",
"",
"long-standing; ongoing",
"Bengali women layer worn saris and stitch them with running stitches into quilts and wraps.",
"running stitch; layering",
"quilts; wraps",
"clothing and adornment;care and access",
"makers",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18;F1.22a",
"high",
"",
"canon_techniques.csv"
],
[
"TEC115",
"Sashiko and boro",
"sashiko; boro",
"technique",
"Things",
"F1.8",
"AS-JPN",
"1700",
"",
"Edo-period rural practice; approximate",
"Running stitches reinforce and patch layered indigo cotton, turning repair into pattern.",
"running stitch; patching",
"jackets; futon covers",
"clothing and adornment;care and access",
"makers",
"",
"living-community",
"ColBase Japan national museums (Japan Government Standard Terms); Wikimedia Commons",
"R3",
"F1.22a;F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC116",
"Mola reverse appliqué",
"mola",
"technique",
"Things",
"F1.7",
"AM-CAM",
"1880",
"",
"late 19th–early 20th c.",
"Guna women cut through layered cotton to reveal colours below, making blouse panels.",
"reverse appliqué",
"mola panels; blouses",
"clothing and adornment",
"Guna makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
