insert into public.canon_nodes ("id", "name", "other_names", "kind", "family", "world", "sub_regions", "start_year", "end_year", "date_note", "making_significance", "materials_techniques", "object_types", "functions", "defined_by", "leaves_out", "sensitivity", "free_sources", "tier", "units", "confidence", "notes", "source_file")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17), public.cw_text(x->18), public.cw_text(x->19), public.cw_text(x->20), public.cw_text(x->21), public.cw_text(x->22)
from jsonb_array_elements($cwb$[
[
"TEC117",
"Quilting",
"quilting",
"technique",
"Things",
"THEME;F1.7;F1.11",
"AM-EWD;EU-BLC;AS-CEN",
"-100",
"",
"quilted textiles at Noin-Ula, Mongolia c.1st c. BCE; ongoing",
"Layers stitched together make warm bedding and armour and have carried community designs such as Gee's Bend quilts.",
"layering; running stitch; piecing",
"quilts; armour",
"shelter;war",
"makers; historians",
"",
"living-community",
"Smithsonian Open Access (CC0); Met Open Access (CC0); Library of Congress (public-domain items)",
"R2",
"F1.18;F1.22a",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC118",
"Mordant dyeing",
"mordanting",
"technique",
"Things",
"F1.9;F1.6",
"AS-SAS;AF-EGY",
"-2500",
"",
"madder-dyed cotton at Mohenjo-daro c.2500 BCE (as usually cited)",
"Metal salts such as alum fix natural dyes to fibre and let one dye give several colours.",
"alum; iron; mordant printing",
"dyed cloth",
"clothing and adornment",
"historians of dyeing",
"",
"none",
"open-access journal articles; Met Open Access (CC0)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC119",
"Block printing on textiles",
"woodblock textile printing",
"technique",
"Things",
"F1.9;F1.8",
"AS-SAS;AS-CHN;AF-EGY",
"-200",
"",
"printed silk from Han tombs c.2nd c. BCE; Indian block prints at Fustat 13th–15th c.",
"Carved wooden blocks stamp mordants, resists or dyes onto cloth in repeating patterns.",
"carved blocks; mordant printing",
"trade cloth; ajrak; bagru",
"clothing and adornment;exchange and value",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); V&A collections (link out); Wikimedia Commons",
"R2",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC120",
"Kalamkari",
"chintz painting; pen-drawn mordant painting",
"technique",
"Things",
"F1.9",
"AS-SAS",
"1400",
"",
"Coromandel painted cottons from c.15th c.; Machilipatnam and Srikalahasti ongoing",
"Mordants and wax resist drawn with a kalam and dyed with madder and indigo produced the painted cottons Europe called chintz.",
"kalam; mordant painting; wax resist",
"palampores; temple cloths",
"clothing and adornment;ritual and belief;exchange and value",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); Rijksmuseum (public-domain images); V&A collections (link out)",
"R2",
"F1.13;F1.14",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC121",
"Batik",
"wax-resist dyeing",
"technique",
"Things",
"F1.9",
"AS-ISE",
"1600",
"",
"Javanese canting batik documented from 17th c.; wax resist older elsewhere; UNESCO 2009",
"Hot wax drawn with a canting or stamped with a cap resists dye through repeated baths.",
"canting; cap; wax resist",
"kain panjang; sarong",
"clothing and adornment;ritual and belief",
"makers",
"",
"living-community",
"Rijksmuseum (public-domain images); Met Open Access (CC0); Wikimedia Commons",
"R2",
"F1.18;F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC122",
"Tie-resist dyeing",
"bandhani; shibori; plangi; tie-dye",
"technique",
"Things",
"F1.9;F1.8;F1.7",
"AS-SAS;AS-JPN;AS-CHN;AM-AND",
"500",
"",
"Wari tie-dyed tunics c.600 CE; Shōsōin textiles 8th c.; Ajanta depictions",
"Binding, stitching or folding cloth before dyeing leaves resisted patterns of dots and lines.",
"binding; stitching; clamping",
"odhnis; kimono; tunics",
"clothing and adornment",
"makers",
"",
"living-community",
"Met Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC123",
"Adire",
"adire eleko; adire oniko",
"technique",
"Things",
"F1.6",
"AF-GUI",
"1880",
"",
"late 19th c. with imported cotton shirting",
"Yoruba women resist-dye cotton with cassava starch or tying before indigo dyeing.",
"cassava starch resist; tying; indigo",
"adire cloths",
"clothing and adornment",
"Yoruba makers",
"",
"living-community",
"British Museum EMKP (CC); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC124",
"Bogolanfini",
"mud cloth",
"technique",
"Things",
"F1.6",
"AF-SAH",
"",
"",
"long-standing; ongoing",
"Bamana dyers paint fermented iron-rich mud onto cloth pretreated with tannin, making dark patterns.",
"tannin mordant; iron mud painting",
"bogolan cloths",
"clothing and adornment;ritual and belief",
"makers",
"",
"living-community",
"British Museum EMKP (CC); Wikimedia Commons",
"R3",
"F1.18",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC125",
"Kuba raffia cut-pile and appliqué",
"Kuba cloth",
"technique",
"Things",
"F1.6",
"AF-CEN",
"1600",
"",
"documented from 17th c.",
"Kuba women embroider cut-pile patterns into raffia cloth woven by men.",
"raffia weaving; cut-pile embroidery; appliqué",
"skirts; panels",
"clothing and adornment;ritual and belief;exchange and value",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); British Museum EMKP (CC); Wikimedia Commons",
"R3",
"F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC126",
"Indigo vat dyeing",
"fermentation vat",
"technique",
"Things",
"F1.7;F1.6;F1.9;F1.8",
"AM-AND;AF-GUI;AF-SAH;AS-SAS;AS-JPN",
"-4200",
"",
"indigo-dyed cotton at Huaca Prieta, Peru c.6,200 years ago (Splitstoser et al. 2016)",
"Indigo is reduced in a fermentation vat to a soluble form that turns blue on the cloth in air.",
"fermentation vat; dipping; oxidation",
"indigo cloth",
"clothing and adornment",
"makers; historians",
"",
"living-community",
"Met Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms); Wikimedia Commons",
"R2",
"F1.5;F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC127",
"Tyrian purple dyeing",
"murex dyeing",
"technique",
"Things",
"F1.9a;F1.11",
"WA-LEV;EU-GRR",
"-1800",
"",
"Minoan Crete c.18th c. BCE; Levantine production; Byzantine imperial monopoly",
"Dye from thousands of murex snails per garment made purple cloth a marker of rank.",
"murex extraction; vat dyeing",
"purple cloth",
"rule and display;clothing and adornment",
"historians",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC128",
"Cochineal dyeing",
"cochineal carmine",
"technique",
"Things",
"F1.7",
"AM-MES;AM-AND;AM-LAT",
"-500",
"",
"Andean textiles from first millennium BCE; post-1521 export to Europe",
"Dried scale insects raised on nopal cactus produce a red that became New Spain's most valuable export after silver.",
"insect cultivation; mordant dyeing",
"textiles; paintings; lake pigments",
"clothing and adornment;exchange and value",
"historians",
"",
"Indigenous-community",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC129",
"Wax print",
"Dutch wax; African print",
"technique",
"Things",
"F1.6;F1.11",
"EU-BLC;AF-GUI",
"1850",
"",
"Dutch mechanised imitation batik from mid-19th c.; West African market from late 19th c.",
"Dutch firms industrialised resin-resist printing to imitate Javanese batik, and West African traders and wearers made it their own.",
"resin resist; roller printing",
"wax-print cloths",
"clothing and adornment",
"historians; companies",
"Designs named and adopted by West African women traders.",
"none",
"Wikimedia Commons; Rijksmuseum (public-domain images)",
"R3",
"F1.14;F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC130",
"Chilkat weaving",
"Naaxein",
"technique",
"Things",
"F1.7",
"AM-NWC",
"",
"",
"pre-contact origins; ongoing (revived late 20th c.)",
"Tlingit and other Northwest Coast weavers twine mountain-goat wool and cedar bark into curvilinear formline robes without a loom beam.",
"twining; hanging warp; formline",
"robes; aprons",
"rule and display;ritual and belief",
"makers",
"",
"Indigenous-community;sacred;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); community-published site",
"R3",
"F1.18;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC131",
"Diné upright-loom weaving",
"Navajo weaving",
"technique",
"Things",
"F1.7",
"AM-WST",
"1650",
"",
"learned from Pueblo weavers c.17th c.; ongoing",
"Diné weavers make tightly woven wool blankets and rugs on vertical looms, adapting designs for the trading-post market.",
"upright loom; tapestry weave",
"chief blankets; rugs",
"clothing and adornment;exchange and value",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Smithsonian Open Access (CC0); Wikimedia Commons",
"R3",
"F1.18;F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC132",
"Harakeke weaving",
"raranga; whatu; tāniko",
"technique",
"Things",
"F1.12",
"OC-POL",
"1300",
"",
"from Māori settlement of Aotearoa; ongoing",
"Māori weavers prepare harakeke (New Zealand flax) fibre and finger-weave cloaks and plait baskets and mats.",
"muka fibre; whatu finger-twining; raranga plaiting",
"kākahu cloaks; kete",
"clothing and adornment;food and storage;rule and display",
"Māori weavers",
"",
"Indigenous-community;living-community",
"Te Papa Collections Online (CC BY where marked; otherwise link out); Auckland Museum Online Collection (CC BY where marked)",
"R2",
"F1.18;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC133",
"Sadu weaving",
"Al Sadu",
"technique",
"Things",
"F1.10;F1.9a",
"WA-ARB",
"",
"",
"long-standing; ongoing; UNESCO: UAE Al Sadu 2011 (Urgent Safeguarding; Representative List 2025); 'Traditional weaving of Al Sadu' Kuwait and Saudi Arabia 2020, extended with Qatar 2025",
"Bedouin women weave tent dividers, bags and rugs of camel, goat and sheep hair on ground looms.",
"ground loom; warp-faced weave",
"tent dividers; saddle bags",
"shelter;transport",
"makers; UNESCO",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.18;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC134",
"Mortise-and-tenon joinery",
"mortise and tenon",
"technique",
"Things",
"F1.8;F1.11",
"AS-CHN;EU-WCE",
"-5100",
"",
"Linear Pottery wells in Germany c.5100 BCE; Hemudu, China c.5000 BCE",
"A projecting tenon fitted into a cut socket joins timbers without nails.",
"chiselling; pegging",
"wells; frames; furniture",
"shelter;tools",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC135",
"Dougong bracketing",
"bracket sets",
"technique",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"-400",
"",
"depicted from Warring States; standardised in the Yingzao Fashi (1103)",
"Interlocking timber bracket sets transfer roof loads to columns and were standardised in a Song building manual.",
"modular timber units",
"temple and palace roofs",
"shelter;rule and display",
"builders; Yingzao Fashi (1103)",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC136",
"Kerfed bentwood boxes",
"bentwood boxes",
"technique",
"Things",
"F1.7",
"AM-NWC",
"",
"",
"pre-contact; ongoing",
"A single cedar plank is kerfed, steamed and bent into four sides and sewn or pegged at the corner.",
"kerfing; steaming; sewing",
"boxes; chests",
"food and storage;ritual and belief",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC137",
"Steam-bent wood (Thonet)",
"bentwood furniture",
"technique",
"Things",
"F1.11",
"EU-WCE",
"1841",
"",
"Michael Thonet's patents from 1841; chair No. 14 (1859)",
"Steaming solid beech and bending it in iron forms allowed chairs made from a few parts and shipped flat.",
"steaming; iron forms; screws",
"café chairs; rocking chairs",
"shelter",
"patents; design historians",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.19;F1.20",
"high",
"",
"canon_techniques.csv"
],
[
"TEC138",
"Lacquer (urushi and qi)",
"urushi; qi lacquer",
"technique",
"Things",
"F1.8;F1.9",
"AS-CHN;AS-JPN;AS-KOR;AS-MSE",
"-6000",
"",
"Kuahuqiao lacquered bow, China c.6000 BCE; earlier Jōmon claims",
"Sap of the lacquer tree, applied in many thin cured layers, gives a hard waterproof surface for vessels, armour and furniture.",
"layering; curing in humidity; polishing",
"bowls; boxes; armour; furniture",
"food and storage;rule and display",
"makers; historians",
"Urushiol causes severe skin reactions for workers.",
"none",
"Met Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms); National Palace Museum Taipei Open Data; National Museum of Korea e-museum (KOGL Type 1 where marked)",
"R2",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC139",
"Marquetry and intarsia",
"inlay; khatam",
"technique",
"Things",
"F1.11;F1.10",
"EU-WCE;WA-IRN;WA-LEV",
"1450",
"",
"Italian intarsia 15th c.; Boulle marquetry 17th c.; Persian khatam; Egyptian inlay far older",
"Veneers of wood, shell, bone and metal are cut and fitted into pictures and patterns on furniture.",
"veneer cutting; fret saw",
"cabinets; studioli; boxes",
"shelter;rule and display",
"historians",
"",
"none",
"Met Open Access (CC0); Rijksmuseum (public-domain images); Walters Art Museum (CC0)",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC140",
"Wood turning",
"lathe turning",
"technique",
"Things",
"F1.11;F1.9a;F1.8",
"EU-GRR;WA-ANA;AS-CHN",
"-700",
"",
"turned bowl fragment from the Warrior's Tomb, Tarquinia c. 700 BCE; 7th-c. BCE turned dishes from Anatolian tumuli and lathe pivots from Thebes (Sitry); a Mycenaean claim (c. 1400–1100 BCE) is unproven",
"Rotating wood on a bow or pole lathe against a chisel produces bowls, legs and spindles.",
"bow lathe; pole lathe",
"bowls; spindles; legs",
"food and storage;shelter",
"historians of technology",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"",
"medium",
"Earliest date uncertain; verify.",
"canon_techniques.csv"
],
[
"TEC141",
"Dugout canoe building",
"dugout",
"technique",
"Things",
"F1.6;F1.11;F1.7;F1.12",
"AF-GUI;EU-BLC;AM-AMZ;OC-AUS",
"-8000",
"",
"Pesse canoe, Netherlands c.8000 BCE; Dufuna canoe, Nigeria c.6000 BCE",
"Hollowing a single log with fire and adzes makes a boat.",
"adzing; controlled burning",
"canoes",
"transport",
"archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC142",
"Lashed-lug boat building",
"balangay construction",
"technique",
"Things",
"F1.9",
"AS-ISE;AS-MSE",
"300",
"",
"Butuan boats c.4th–13th c. (dates vary)",
"Planks edge-joined with dowels are lashed to frames through carved lugs.",
"dowelling; lashing",
"balangay; outrigger vessels",
"transport",
"maritime archaeologists",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC143",
"Sewn-plank boat building",
"sewn boats; mtepe",
"technique",
"Things",
"F1.6;F1.9;F1.11;F1.10",
"AF-SWA;WA-ARB;AS-SAS;EU-BLC;AF-EGY",
"-2500",
"",
"Khufu ship c.2500 BCE (lashed); Ferriby boats c.2000 BCE; Indian Ocean sewn boats into the 20th c.",
"Planks stitched together with coir or fibre cord made flexible hulls for the Indian Ocean and early European rivers.",
"stitching; coir cord; caulking",
"mtepe; masula; Ferriby boats",
"transport",
"maritime archaeologists",
"",
"none",
"open-access excavation reports; Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC144",
"Dhow building",
"shell-first dhow construction",
"technique",
"Things",
"F1.10;F1.9;F1.6",
"WA-ARB;AS-SAS;AF-SWA",
"800",
"",
"nailed and sewn dhows from late 1st millennium CE; ongoing in Sur, Lamu and Gujarat",
"Shipwrights build dhow hulls plank-first by eye, using teak and nails or stitching.",
"plank-first; teak; lateen rig",
"boum; sambuk; jahazi",
"transport",
"makers",
"",
"living-community",
"Wikimedia Commons; Qatar Digital Library (licence per item; check)",
"R3",
"F1.13;F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC145",
"Clinker boat building",
"lapstrake",
"technique",
"Things",
"F1.11",
"EU-SCA;EU-BLC",
"300",
"",
"Nydam boat c.310–320 CE; Viking ships; UNESCO 2021 (Nordic clinker boats)",
"Overlapping planks riveted together form light, flexible hulls, as in Viking ships.",
"overlapping planks; clench nails",
"longships; faering",
"transport;war",
"archaeologists; makers",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC146",
"Outrigger and double-hulled canoe building",
"vaka; waʻa; proa",
"technique",
"Things",
"F1.12",
"OC-POL;OC-MIC;OC-MEL;AS-ISE",
"",
"",
"ancient; revived (Hōkūleʻa 1976)",
"Pacific builders lash hulls, outriggers and crossbeams with coconut fibre to make stable voyaging craft.",
"lashing; sennit; adzing",
"voyaging canoes; proas",
"transport",
"makers; voyaging societies",
"",
"Indigenous-community;living-community",
"Te Papa Collections Online (CC BY where marked; otherwise link out); Auckland Museum Online Collection (CC BY where marked); Wikimedia Commons",
"R2",
"F1.13;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC147",
"Skin-on-frame boats",
"kayak; umiak; qajaq",
"technique",
"Things",
"F1.7;F1.12a",
"AM-ARC;AS-NTH",
"",
"",
"ancient; Thule period c.1000 CE onward; ongoing",
"Arctic builders stretch sewn sea-mammal skins over lashed driftwood frames for hunting and transport boats.",
"skin sewing; lashing",
"kayaks; umiaks",
"transport;food and storage",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC148",
"Reed-bundle boats",
"totora boats; reed boats",
"technique",
"Things",
"F1.7;F1.9a",
"AM-AND;WA-MES",
"-5500",
"",
"bitumen-coated reed boat remains at As-Sabiyah, Kuwait c.5500 BCE; totora boats on Lake Titicaca ongoing",
"Bundled reeds lashed together float without planks, from Neolithic Gulf boats to Uros totora craft.",
"bundling; lashing; bitumen coating",
"reed boats",
"transport",
"makers; archaeologists",
"",
"living-community",
"open-access excavation reports; Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC149",
"Whakairo",
"Māori carving",
"technique",
"Things",
"F1.12",
"OC-POL",
"1300",
"",
"from Māori settlement; ongoing",
"Carvers work timber, bone and stone into meeting-house panels, canoe prows and taonga following whakapapa.",
"adzing; chiselling; pāua inlay",
"poupou; tauihu; waka huia",
"ritual and belief;rule and display",
"Māori carvers",
"",
"Indigenous-community;sacred;ancestral",
"Te Papa Collections Online (CC BY where marked; otherwise link out); Auckland Museum Online Collection (CC BY where marked)",
"R3",
"F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC150",
"Dry-stone masonry",
"dry-stone walling",
"technique",
"Things",
"F1.6;F1.11;F1.7",
"AF-SOU;EU-BLC;AM-AND;EU-GRR",
"-3500",
"",
"Neolithic Orkney c.3100 BCE and earlier; Great Zimbabwe 11th–15th c.; UNESCO 2018",
"Stones are fitted without mortar into walls, terraces and enclosures that drain and flex.",
"coursing; batter; through-stones",
"walls; enclosures; terraces",
"shelter;food and storage",
"makers; UNESCO",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC151",
"Ashlar masonry",
"dressed stone masonry",
"technique",
"Things",
"F1.6;F1.11;F1.9a",
"AF-EGY;EU-GRR;WA-LEV;AF-HRN",
"-2650",
"",
"Djoser complex, Saqqara c.2650 BCE",
"Squared, dressed blocks laid in regular courses allowed monumental stone architecture.",
"quarrying; dressing; lifting",
"temples; pyramids; stelae",
"shelter;rule and display",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC152",
"Cyclopean masonry",
"cyclopean walls",
"technique",
"Things",
"F1.11",
"EU-GRR",
"-1400",
"-1100",
"Mycenaean",
"Very large roughly shaped stones fitted without mortar formed Mycenaean citadel walls.",
"rough dressing; fitting",
"walls; gates",
"war;rule and display",
"archaeologists (name from Greek myth)",
"",
"none",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC153",
"Inca fitted stone masonry",
"polygonal ashlar",
"technique",
"Things",
"F1.7",
"AM-AND",
"1400",
"1532",
"approximate",
"Inca masons pounded and ground stones to fit tightly without mortar, making earthquake-resistant walls.",
"hammerstone pounding; fitting",
"walls; terraces; temples",
"shelter;rule and display",
"archaeologists",
"",
"living-community",
"Wikimedia Commons; UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC154",
"Mud brick",
"sun-dried brick",
"technique",
"Things",
"F1.9a;F1.6",
"WA-LEV;WA-MES;AF-EGY",
"-8500",
"",
"Levantine Pre-Pottery Neolithic c.9th millennium BCE; approximate",
"Mould-made or hand-shaped sun-dried bricks of earth and straw built most houses and many cities of West Asia and Egypt.",
"moulding; drying; mud mortar",
"houses; walls; ziggurats",
"shelter",
"archaeologists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.5",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC155",
"Fired brick",
"kiln-fired brick",
"technique",
"Things",
"F1.9a;F1.9;F1.8",
"WA-MES;AS-SAS;AS-CHN",
"-3500",
"",
"Mesopotamia 4th millennium BCE; Indus standard ratio bricks 3rd millennium BCE",
"Firing moulded bricks made durable, waterproof building units, standardised in Indus cities.",
"moulding; kiln firing",
"drains; walls; platforms",
"shelter;care and access",
"archaeologists",
"",
"none",
"Wikimedia Commons; open-access excavation reports",
"R3",
"F1.19",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC156",
"Rammed earth",
"hangtu; tapial; pisé",
"technique",
"Things",
"F1.8;F1.6;F1.11",
"AS-CHN;AF-MAG;EU-IBE",
"-2500",
"",
"Longshan walled towns c.2500 BCE; Maghribi tabia; Great Wall sections",
"Damp earth is pounded in layers inside formwork to make walls and platforms.",
"formwork; tamping",
"city walls; platforms; kasbahs",
"shelter;war",
"archaeologists",
"",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC157",
"Adobe",
"adobe",
"technique",
"Things",
"F1.7",
"AM-WST;AM-AND;AM-LAT",
"-3500",
"",
"Andean adobe before 3100 BCE (Los Morteros, Chao Valley) and c. 3500 BCE (Sechín Bajo); Pueblo puddled adobe; Spanish mould-made adobe from 16th c.",
"Earth, straw and water are moulded into bricks or puddled into courses for thick, thermally stable walls.",
"moulding; plastering",
"pueblos; missions; huacas",
"shelter",
"makers; archaeologists",
"",
"living-community",
"Wikimedia Commons; Library of Congress (public-domain items)",
"R3",
"F1.29",
"medium",
"Checked: earliest Andean adobe is Preceramic (4th millennium BCE), not 2nd millennium BCE.",
"canon_techniques.csv"
],
[
"TEC158",
"Cob",
"cob walling",
"technique",
"Things",
"F1.11",
"EU-BLC",
"1200",
"",
"medieval Devon and elsewhere; approximate",
"Earth mixed with straw is built up in wet layers without forms and trimmed into walls.",
"mixing; layering",
"farmhouses; walls",
"shelter",
"makers",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC159",
"Sudano-Sahelian earthen building",
"banco; crépissage",
"technique",
"Things",
"F1.6",
"AF-SAH",
"1200",
"",
"Great Mosque of Djenné rebuilt 1906–07 on 13th-c. foundations; annual replastering ongoing",
"Communities build and annually replaster mosques and houses in banco earth, using protruding timbers as scaffolding.",
"banco; toron; replastering festival",
"mosques; houses",
"shelter;ritual and belief",
"builders' guilds; communities",
"",
"living-community;sacred",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R2",
"F1.29;F1.22a",
"high",
"",
"canon_techniques.csv"
],
[
"TEC160",
"Lime plaster",
"burnt lime",
"technique",
"Things",
"F1.9a",
"WA-LEV;WA-ANA",
"-12000",
"",
"Natufian lime plaster c.12th millennium BCE; 'Ain Ghazal plaster statues c.7th millennium BCE",
"Burning limestone and slaking it made plaster for floors, skull modelling and statues.",
"lime burning; slaking",
"floors; statues; plastered skulls",
"shelter;ritual and belief",
"archaeologists",
"",
"funerary;ancestral",
"Wikimedia Commons; open-access excavation reports",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC161",
"Reinforced concrete",
"ferroconcrete",
"technique",
"Things",
"F1.11;THEME",
"EU-WCE",
"1867",
"",
"Joseph Monier patent 1867; Hennebique system 1892",
"Steel bars embedded in concrete carry tension, making frames, slabs and shells possible.",
"rebar; formwork",
"frames; slabs; shells",
"shelter;transport",
"patents; engineers",
"",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.20;F1.22",
"high",
"",
"canon_techniques.csv"
],
[
"TEC162",
"Mosaic",
"tessellated mosaic; clay-cone mosaic; smalti",
"technique",
"Things",
"F1.11;F1.10;F1.9a",
"EU-GRR;EU-BYZ;WA-LEV;WA-MES",
"-3500",
"",
"Uruk clay-cone mosaic c.3500 BCE; Gordion pebble mosaics 8th c. BCE; Hellenistic tesserae; glass wall mosaic from late antiquity",
"Small units of stone, clay or glass set in mortar made durable floors and walls.",
"tesserae; setting bed",
"floors; wall mosaics",
"shelter;ritual and belief",
"archaeologists",
"",
"sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R2",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC163",
"Stucco carving",
"carved plaster",
"technique",
"Things",
"F1.10;F1.7;F1.9a",
"WA-IRN;WA-MES;AM-MES",
"1",
"",
"Parthian and Sasanian; Maya Classic; Abbasid Samarra",
"Lime or gypsum plaster was modelled or carved wet into façades, masks and wall panels.",
"modelling; carving",
"façades; masks; panels",
"shelter;rule and display",
"archaeologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC164",
"True arch and vault",
"voussoir arch",
"technique",
"Things",
"F1.9a;F1.6",
"WA-MES;AF-EGY",
"-3000",
"",
"mud-brick vaults in Mesopotamia and Egypt by 3rd millennium BCE; approximate",
"Wedge-shaped units lock together to span openings; mud-brick vaults preceded Roman stone arches.",
"voussoirs; centering",
"vaults; gates",
"shelter",
"archaeologists",
"Europe-centred accounts start with Rome.",
"none",
"Wikimedia Commons",
"R3",
"F1.3",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC165",
"Corbel vault",
"corbelled vault",
"technique",
"Things",
"F1.11;F1.7",
"EU-BLC;AM-MES;EU-GRR",
"-3200",
"",
"Newgrange passage tomb c.3200 BCE; Mycenaean tholoi; Maya corbel arches",
"Each stone course projects a little past the one below until the gap closes.",
"corbelling",
"tombs; temples",
"shelter;ritual and belief",
"archaeologists",
"",
"funerary",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC166",
"Masonry dome",
"dome",
"technique",
"Things",
"F1.11;F1.10",
"EU-GRR;WA-IRN",
"-100",
"",
"Roman concrete domes from c.1st c. BCE; Pantheon 125 CE",
"Rotating an arch forms a dome, built in concrete, brick or stone over square spaces with transitional devices.",
"concrete; brick; centering",
"baths; temples; mosques",
"shelter;ritual and belief",
"architectural historians",
"",
"none",
"Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC167",
"Squinch",
"squinch",
"technique",
"Things",
"F1.9a;F1.10",
"WA-IRN",
"220",
"",
"Palace of Ardashir, Firuzabad c.220s CE",
"An arch across the corner of a square room turns it into an octagon for a dome.",
"arches; brick",
"domed halls",
"shelter",
"architectural historians",
"",
"none",
"Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC168",
"Muqarnas",
"stalactite vaulting",
"technique",
"Things",
"F1.10",
"WA-MES;WA-IRN;AF-MAG",
"1000",
"",
"late 10th–11th c. in Iraq, Iran and North Africa",
"Tiers of small niche units compose three-dimensional vaults and cornices from a geometric plan.",
"geometric modules; plaster; wood",
"vaults; portals",
"shelter;ritual and belief",
"architectural historians",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.15",
"high",
"",
"canon_techniques.csv"
],
[
"TEC169",
"Earthen mound building",
"earthworks",
"technique",
"Things",
"F1.7",
"AM-EWD",
"-3500",
"",
"Watson Brake c.3500 BCE; Poverty Point c.1700 BCE; Cahokia c.1050 CE",
"Communities moved basketloads of earth to build platform mounds, effigy mounds and ridges.",
"basket-loading; clay capping",
"platform mounds; effigy mounds",
"ritual and belief;rule and display",
"archaeologists; descendant nations",
"",
"ancestral;funerary;sacred;Indigenous-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC170",
"Snow-block construction",
"igluvijaq",
"technique",
"Things",
"F1.7",
"AM-ARC",
"",
"",
"long-standing",
"Inuit builders cut blocks of wind-packed snow with a knife and spiral them into a dome shelter.",
"snow knife; spiral courses",
"iglus",
"shelter",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC171",
"Yurt and ger construction",
"boz üy; ger",
"technique",
"Things",
"F1.12a",
"AS-CEN;AS-NTH",
"",
"",
"long-standing; UNESCO: Mongol ger 2013; Kyrgyz and Kazakh yurts 2014, extended to Karakalpak yurts 2025",
"A collapsible lattice wall, roof poles and a crown ring covered in felt make a portable house.",
"lattice; felt covering; bent wood",
"yurts; gers",
"shelter",
"makers; UNESCO",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC172",
"Vegetable tanning",
"bark tanning",
"technique",
"Things",
"F1.6;F1.9a;F1.11",
"AF-EGY;WA-LEV;EU-WCE;AF-SAH",
"-3000",
"",
"approximate; Egyptian and Near Eastern evidence; ongoing (e.g. Fez tanneries)",
"Soaking hides in tannin from bark, leaves or pods makes durable, rot-resistant leather.",
"tannin; liming; currying",
"shoes; bags; saddles",
"clothing and adornment;transport",
"historians",
"",
"living-community",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.23",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC173",
"Brain and smoke tanning",
"buckskin tanning",
"technique",
"Things",
"F1.7",
"AM-WST;AM-EWD;AM-ARC",
"",
"",
"long-standing; ongoing",
"Hides worked with brains and smoked become soft, washable buckskin.",
"brain emulsion; stretching; smoking",
"shirts; dresses; moccasins",
"clothing and adornment",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC174",
"Parchment making",
"vellum",
"technique",
"Things",
"F1.9a;F1.11;F1.6",
"WA-ANA;EU-WCE;AF-HRN",
"-200",
"",
"Pergamon tradition 2nd c. BCE; earlier leather rolls in Egypt; Ethiopian parchment ongoing",
"Skins are limed, stretched and scraped rather than tanned, producing a writing surface.",
"liming; stretching; scraping",
"codices; charters; Torah scrolls",
"record and writing;ritual and belief",
"historians",
"",
"sacred;living-community",
"Walters Art Museum (CC0); British Library (public-domain digitised items); Wikimedia Commons",
"R2",
"F1.28",
"high",
"",
"canon_techniques.csv"
],
[
"TEC175",
"Rawhide and parfleche",
"parfleche",
"technique",
"Things",
"F1.7",
"AM-WST",
"",
"",
"long-standing; ongoing",
"Plains makers paint stiff untanned hide and fold it into cases for food and belongings.",
"rawhide; painting",
"parfleche cases; drums",
"food and storage;play and music",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"",
"high",
"",
"canon_techniques.csv"
],
[
"TEC176",
"Fish-skin working",
"fish-skin clothing",
"technique",
"Things",
"F1.12a;F1.8;F1.7",
"AS-NTH;AS-JPN;AM-ARC",
"",
"",
"long-standing; revived (Nanai/Hezhe, Ainu, Yup'ik)",
"Salmon and other fish skins are scraped, softened and sewn into waterproof clothing and bags.",
"scraping; softening; sewing",
"coats; boots; bags",
"clothing and adornment",
"makers",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.18;F1.22",
"high",
"",
"canon_techniques.csv"
],
[
"TEC177",
"Tattooing",
"tatau; moko",
"technique",
"Things",
"THEME;F1.12",
"OC-POL;EU-WCE;AF-EGY;AS-JPN",
"-3300",
"",
"Ötzi c.3300 BCE; Egyptian tattooed mummies c.3000 BCE; Polynesian tatau",
"Pigment inserted into skin by puncture or cutting records identity, genealogy and status.",
"combs; needles; soot pigment",
"tatau; tā moko",
"clothing and adornment;ritual and belief",
"makers",
"",
"living-community;sacred;Indigenous-community",
"Wikimedia Commons; Te Papa Collections Online (CC BY where marked; otherwise link out)",
"R3",
"F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC178",
"Clay tablet and stylus",
"cuneiform writing",
"technique",
"Things",
"F1.9a",
"WA-MES;WA-ANA;WA-IRN",
"-3300",
"75",
"proto-cuneiform Uruk IV c.3300–3200 BCE; last dated tablet c.75 CE",
"Scribes pressed wedge marks into damp clay with a cut reed, producing durable records.",
"reed stylus; clay tablets; envelopes",
"tablets; envelopes",
"record and writing",
"Assyriologists",
"Writing invented independently several times.",
"none",
"Cuneiform Digital Library Initiative (link out); Met Open Access (CC0); Wikimedia Commons",
"R1",
"F1.5;F1.28",
"high",
"",
"canon_techniques.csv"
],
[
"TEC179",
"Cylinder seal carving",
"cylinder seals",
"technique",
"Things",
"F1.9a",
"WA-MES;WA-IRN",
"-3500",
"-300",
"approximate",
"Engraved stone cylinders rolled on clay left repeatable images marking ownership and authority.",
"hardstone engraving; drilling",
"seals; sealings",
"record and writing;rule and display",
"Assyriologists",
"",
"none",
"Met Open Access (CC0); Cuneiform Digital Library Initiative (link out)",
"R2",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC180",
"Papyrus making",
"papyrus",
"technique",
"Things",
"F1.6",
"AF-EGY",
"-3000",
"",
"blank roll from Hemaka's tomb c.3000 BCE; Wadi al-Jarf papyri c.2560 BCE",
"Strips of papyrus pith laid crosswise and pressed bond into sheets joined into rolls.",
"slicing; pressing; burnishing",
"rolls",
"record and writing",
"Egyptologists",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.28",
"high",
"",
"canon_techniques.csv"
],
[
"TEC181",
"Palm-leaf manuscript making",
"olai; lontar",
"technique",
"Things",
"F1.9",
"AS-SAS;AS-MSE;AS-ISE;AS-HIM",
"100",
"",
"earliest surviving fragments early centuries CE; in use into the 20th c.",
"Processed palm leaves are incised with a stylus and blackened, or written in ink, and strung between boards.",
"incising; soot inking; stringing",
"manuscripts",
"record and writing;ritual and belief",
"historians",
"",
"sacred",
"Wikimedia Commons; British Library (public-domain digitised items)",
"R3",
"F1.28",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC182",
"Birch-bark writing",
"birch-bark manuscripts",
"technique",
"Things",
"F1.9;F1.12a;F1.11",
"AS-SAS;AS-CEN;EU-EER",
"1",
"",
"Gandharan Buddhist scrolls c.1st c. CE; Novgorod birch-bark letters 11th–15th c.",
"Birch bark served as a writing surface for Gandharan sutras and everyday Novgorod letters.",
"ink; incising",
"scrolls; letters",
"record and writing",
"historians",
"",
"sacred",
"Wikimedia Commons; British Library (public-domain digitised items)",
"R3",
"F1.28;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC183",
"Bamboo and wooden slips",
"jiandu",
"technique",
"Things",
"F1.8",
"AS-CHN",
"-433",
"",
"earliest surviving datable set c.433 BCE (tomb of Marquis Yi of Zeng); earlier use implied",
"Strips of bamboo written in ink and bound with cord were China's main books before paper.",
"splitting; ink; binding",
"books; records",
"record and writing",
"historians",
"",
"funerary",
"Wikimedia Commons; open-access journal articles",
"R3",
"F1.28",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC184",
"Papermaking in China",
"paper",
"technique",
"Things",
"F1.8",
"AS-CHN",
"-200",
"",
"Fangmatan map paper c.2nd c. BCE; Cai Lun's reported improvements 105 CE",
"Macerated plant fibre formed on a screen mould made a cheap writing and wrapping sheet.",
"pulping; mould and deckle; drying",
"paper; books",
"record and writing",
"historians",
"The Cai Lun story simplifies a longer development.",
"none",
"National Palace Museum Taipei Open Data; Wikimedia Commons",
"R1",
"F1.13;F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC185",
"Papermaking in the Islamic world",
"Samarkand paper",
"technique",
"Things",
"F1.10;F1.12a",
"AS-CEN;WA-MES;AF-EGY",
"750",
"",
"traditionally linked to Talas 751 (contested); Baghdad paper by c.794",
"Rag-based paper spread from Central Asia to Baghdad, Cairo and al-Andalus and transformed book production.",
"rag pulping; sizing; burnishing",
"Qur'ans; books",
"record and writing",
"historians (Jonathan Bloom)",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons; Qatar Digital Library (licence per item; check)",
"R3",
"F1.13",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC186",
"European papermaking and watermarks",
"watermark",
"technique",
"Things",
"F1.11",
"EU-IBE;EU-WCE",
"1150",
"",
"Xàtiva c.1150s; Fabriano watermarks late 13th c.",
"Water-powered stamping mills and wire moulds with watermarks spread from Iberia and Italy.",
"stamping mill; wire mould; gelatin sizing",
"paper",
"record and writing",
"historians",
"",
"none",
"Wikimedia Commons; Gallica BnF (public-domain items)",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC187",
"Bark paper",
"amate; huun",
"technique",
"Things",
"F1.7",
"AM-MES",
"",
"",
"Maya and Aztec codices; Otomí amate-making in San Pablito ongoing",
"Fig and mulberry inner bark is boiled and beaten into sheets for codices and ritual paper.",
"boiling; beating",
"codices; ritual cut-paper",
"record and writing;ritual and belief",
"makers; historians",
"",
"sacred;living-community",
"Wikimedia Commons; Library of Congress (public-domain items)",
"R3",
"F1.28",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC188",
"Lokta paper",
"Nepali handmade paper",
"technique",
"Things",
"F1.9",
"AS-HIM",
"",
"",
"long-standing; ongoing",
"Bark of Daphne shrubs is cooked, beaten and formed on floating moulds for documents and prayer texts.",
"floating mould; bark pulp",
"paper; manuscripts",
"record and writing",
"makers",
"",
"living-community",
"Wikimedia Commons",
"R3",
"F1.29",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC189",
"Woodblock printing",
"xylography",
"technique",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"700",
"",
"Korean Dharani sutra before 751; Japanese Hyakumantō Darani 764–770; Diamond Sutra 868",
"Text and image carved in relief on a block are inked and printed by rubbing, enabling mass Buddhist texts.",
"block carving; rubbing",
"sutras; books; prints",
"record and writing;ritual and belief",
"historians",
"",
"sacred",
"International Dunhuang Programme (link out); National Museum of Korea e-museum (KOGL Type 1 where marked); Wikimedia Commons",
"R1",
"F1.5;F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC190",
"Ceramic movable type",
"clay type",
"technique",
"Things",
"F1.8",
"AS-CHN",
"1040",
"",
"Bi Sheng c.1040s (described by Shen Kuo)",
"Individual fired-clay characters were set in an iron frame for printing.",
"type moulding; setting",
"books",
"record and writing",
"Shen Kuo (Dream Pool Essays)",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.5",
"high",
"",
"canon_techniques.csv"
],
[
"TEC191",
"Metal movable type (Korea)",
"bronze type",
"technique",
"Things",
"F1.8",
"AS-KOR",
"1234",
"",
"recorded 1234; earliest surviving book Jikji 1377",
"Korean printers cast bronze type in sand moulds, printing Jikji before Gutenberg.",
"sand casting; setting",
"books",
"record and writing",
"historians",
"",
"none",
"National Museum of Korea e-museum (KOGL Type 1 where marked); Gallica BnF (public-domain items); Wikimedia Commons",
"R2",
"F1.5;F1.3",
"high",
"Jikji held by BnF.",
"canon_techniques.csv"
],
[
"TEC192",
"Metal type and press (Gutenberg)",
"typography",
"technique",
"Things",
"F1.11",
"EU-WCE",
"1450",
"",
"Mainz c.1450s",
"A hand mould for casting type, oil-based ink and an adapted screw press made printing in the Latin alphabet fast and repeatable.",
"type casting; press; oil ink",
"books; broadsheets",
"record and writing",
"historians",
"Not the first movable type.",
"none",
"Library of Congress (public-domain items); Gallica BnF (public-domain items); Wikimedia Commons",
"R1",
"F1.5;F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC193",
"Intaglio printmaking",
"engraving; etching",
"technique",
"Things",
"F1.11",
"EU-WCE",
"1430",
"",
"engraving c.1430s; etching c.1500",
"Lines cut or etched into metal plates hold ink that is pressed onto damp paper.",
"burin; acid; roller press",
"prints; maps",
"record and writing",
"historians",
"",
"none",
"Met Open Access (CC0); National Gallery of Art Washington Open Access (CC0); Rijksmuseum (public-domain images)",
"R2",
"F1.14",
"high",
"",
"canon_techniques.csv"
],
[
"TEC194",
"Lithography",
"lithograph",
"technique",
"Things",
"F1.11",
"EU-WCE",
"1796",
"",
"Alois Senefelder 1796",
"Printing from a flat greased stone let artists draw directly for print and made colour posters possible.",
"grease crayon; stone; press",
"posters; maps; prints",
"record and writing",
"historians",
"",
"none",
"Met Open Access (CC0); National Gallery of Art Washington Open Access (CC0); Library of Congress (public-domain items)",
"R3",
"F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC195",
"Letterpress",
"industrial letterpress; iron hand press",
"technique",
"Things",
"F1.11",
"EU-BLC",
"1800",
"",
"Stanhope iron press c.1800; steam press 1814; craft revival late 20th c.",
"Relief type printed on iron and steam presses produced newspapers and posters, later revived as craft.",
"iron press; wood type",
"posters; newspapers",
"record and writing",
"historians",
"",
"none",
"Library of Congress (public-domain items); NYPL Digital Collections (public-domain items)",
"R3",
"F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC196",
"Photography",
"photograph",
"technique",
"Things",
"F1.11",
"EU-WCE;EU-BLC",
"1826",
"",
"Niépce c.1826–27; daguerreotype and calotype 1839",
"Light-sensitive materials fixed camera images, changing how objects, people and places were recorded and reproduced.",
"camera; silver salts; negative-positive",
"photographs; albums",
"record and writing",
"historians",
"",
"none",
"Library of Congress (public-domain items); National Gallery of Art Washington Open Access (CC0); Rijksmuseum (public-domain images)",
"R2",
"F1.28;F1.4",
"high",
"",
"canon_techniques.csv"
],
[
"TEC197",
"Offset lithography",
"offset printing",
"technique",
"Things",
"F1.7",
"AM-EWD",
"1904",
"",
"Ira Rubel 1904; others",
"Ink transferred from a plate to a rubber blanket then to paper allowed fast, cheap colour printing.",
"plates; rubber blanket",
"magazines; packaging",
"record and writing",
"historians",
"",
"none",
"Wikimedia Commons; Library of Congress (public-domain items)",
"R3",
"F1.21",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC198",
"Screen printing",
"serigraphy",
"technique",
"Things",
"F1.7;F1.8",
"AM-EWD;AS-JPN",
"1907",
"",
"stencil precursors (e.g. katazome) older; silk-screen patent 1907",
"Ink forced through a mesh stencil prints flat colour on paper, textiles and objects.",
"mesh; stencil; squeegee",
"posters; T-shirts; prints",
"record and writing;clothing and adornment",
"historians",
"",
"none",
"MoMA collection (link out; metadata CC0); Library of Congress (public-domain items); Wikimedia Commons",
"R3",
"F1.21",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC199",
"CNC machining",
"numerical control",
"technique",
"Things",
"THEME",
"AM-EWD",
"1952",
"",
"MIT numerically controlled milling 1952",
"Coded instructions drive cutting machines, linking digital design to physical making.",
"coded toolpaths; milling",
"parts; furniture",
"tools",
"historians of technology",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21",
"high",
"",
"canon_techniques.csv"
],
[
"TEC200",
"3D printing",
"additive manufacturing",
"technique",
"Things",
"THEME",
"AS-JPN;AM-WST",
"1981",
"",
"Hideo Kodama 1981; Charles Hull stereolithography patent 1984–86",
"Objects are built layer by layer from digital files, enabling distributed and custom making.",
"stereolithography; fused deposition",
"prototypes; parts",
"tools;care and access",
"historians of technology; patents",
"",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.21;F1.28a",
"high",
"",
"canon_techniques.csv"
],
[
"TEC201",
"Laser cutting",
"laser cutting",
"technique",
"Things",
"THEME",
"AM-EWD",
"1965",
"",
"Western Electric 1965",
"A focused laser cuts or engraves sheet materials from digital drawings.",
"CO2 laser; vector files",
"signs; parts; models",
"tools",
"historians of technology",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.21",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC202",
"Semiconductor photolithography",
"chip fabrication",
"technique",
"Things",
"THEME",
"AM-WST;AS-CHN;AS-KOR",
"1959",
"",
"planar process and integrated circuits 1959; ongoing (Taiwan, Korea)",
"Light-patterned layers on silicon wafers make the integrated circuits in every digital device.",
"photoresist; etching; doping",
"chips",
"tools;record and writing",
"historians of technology",
"",
"none",
"Wikimedia Commons; NASA imagery (US public domain)",
"R3",
"F1.21;F1.22;F1.23",
"high",
"Taiwan coded AS-CHN; check convention.",
"canon_techniques.csv"
],
[
"TEC203",
"Fresco",
"buon fresco",
"technique",
"Things",
"F1.11;F1.9",
"EU-GRR;EU-WCE;AS-SAS",
"-1700",
"",
"Aegean wall painting c.1700 BCE (true fresco debated); Roman; Italian Renaissance",
"Pigments in water painted into wet lime plaster become part of the wall as it sets.",
"lime plaster; giornate",
"murals",
"shelter;ritual and belief",
"art historians",
"",
"sacred",
"Wikimedia Commons; Met Open Access (CC0)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC204",
"Egg tempera",
"tempera",
"technique",
"Things",
"F1.11;F1.6",
"EU-BYZ;EU-WCE;AF-HRN",
"500",
"",
"Byzantine icons from c.6th c.; Ethiopian icons",
"Pigments bound in egg yolk on gessoed panels dry fast and allow fine hatched modelling.",
"egg binder; gesso panels",
"icons; altarpieces",
"ritual and belief",
"art historians",
"",
"sacred",
"Met Open Access (CC0); Walters Art Museum (CC0); National Gallery of Art Washington Open Access (CC0)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC205",
"Oil painting",
"oil paint",
"technique",
"Things",
"F1.12a;F1.11",
"AS-CEN;EU-BLC;EU-WCE",
"650",
"",
"Bamiyan murals 7th c. with drying-oil binders; Netherlandish oil painting 15th c.",
"Pigments ground in drying oils allowed slow blending and glazes; earliest known use is in Bamiyan, not Flanders.",
"drying oils; glazes",
"panel and canvas paintings",
"rule and display;ritual and belief",
"conservation scientists; art historians",
"Europe-centred origin story.",
"none",
"National Gallery of Art Washington Open Access (CC0); Rijksmuseum (public-domain images); Met Open Access (CC0); SMK National Gallery of Denmark (CC0)",
"R2",
"F1.3",
"high",
"",
"canon_techniques.csv"
],
[
"TEC206",
"Encaustic",
"wax painting",
"technique",
"Things",
"F1.6;F1.11",
"AF-EGY;EU-GRR",
"-400",
"",
"Greek sources; Fayum portraits 1st–3rd c. CE",
"Pigments in hot beeswax were applied to wood panels, as in Roman-Egyptian mummy portraits.",
"hot wax; spatulas",
"mummy portraits; panels",
"ritual and belief",
"art historians",
"",
"funerary",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC207",
"Persianate and Mughal miniature painting",
"manuscript painting; nigarkari",
"technique",
"Things",
"F1.10;F1.9",
"WA-IRN;AS-SAS;WA-ANA",
"1300",
"",
"Ilkhanid Iran c.1300; Safavid, Ottoman, Mughal and Rajput workshops; ongoing",
"Workshop artists ground mineral pigments, painted in layers on burnished paper and signed collaborative pages.",
"mineral pigments; squirrel-hair brushes; burnishing",
"album pages; manuscripts",
"record and writing;rule and display",
"art historians",
"",
"none",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0); Staatliche Museen zu Berlin SMB-digital (CC BY-SA where marked)",
"R2",
"F1.17;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC208",
"Qalam calligraphy",
"reed-pen calligraphy",
"technique",
"Things",
"F1.10",
"WA-MES;WA-IRN;WA-ANA;AF-MAG",
"900",
"",
"proportioned scripts attributed to Ibn Muqla, 10th c.",
"Calligraphers cut reed pens at precise angles and wrote according to proportional systems based on the rhombic dot.",
"reed pen; carbon ink; burnished paper",
"Qur'ans; albums; inscriptions",
"record and writing;ritual and belief",
"calligraphers; historians",
"",
"sacred",
"Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0); Walters Art Museum (CC0)",
"R2",
"F1.15",
"high",
"",
"canon_techniques.csv"
],
[
"TEC209",
"Ink stick and brush",
"sumi; mo",
"technique",
"Things",
"F1.8",
"AS-CHN;AS-KOR;AS-JPN",
"-200",
"",
"carbon inks earlier; moulded ink cakes by Han",
"Soot bound with animal glue into sticks is ground on a stone and used with animal-hair brushes for writing and painting.",
"lamp black; glue; inkstone",
"calligraphy; ink paintings",
"record and writing",
"historians",
"",
"none",
"Met Open Access (CC0); National Palace Museum Taipei Open Data; ColBase Japan national museums (Japan Government Standard Terms)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC210",
"Lacquer painting",
"maki-e; sơn mài",
"technique",
"Things",
"F1.8;F1.9",
"AS-JPN;AS-MSE",
"750",
"",
"maki-e from Nara–Heian; Vietnamese sơn mài developed 1930s",
"Metal powders or pigments are sprinkled or painted into wet lacquer and polished.",
"sprinkled gold; polishing",
"boxes; screens; panels",
"rule and display",
"historians",
"",
"none",
"ColBase Japan national museums (Japan Government Standard Terms); Met Open Access (CC0)",
"R3",
"",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC211",
"Thangka painting",
"thangka",
"technique",
"Things",
"F1.9",
"AS-HIM",
"1000",
"",
"c.11th c.; ongoing",
"Painters grid sacred proportions on sized cotton and apply mineral pigments to make portable devotional images.",
"iconometric grids; mineral pigments",
"thangkas",
"ritual and belief",
"makers; monasteries",
"",
"sacred;living-community",
"Himalayan Art Resources (link out); Met Open Access (CC0); Cleveland Museum of Art Open Access (CC0)",
"R3",
"F1.16",
"high",
"",
"canon_techniques.csv"
],
[
"TEC212",
"Bark painting",
"Arnhem Land bark painting",
"technique",
"Things",
"F1.12",
"OC-AUS",
"",
"",
"long-standing; ongoing; commercial form from 20th c.",
"Artists paint ochres onto flattened stringybark with fine brushes, often in rarrk cross-hatching.",
"ochre; bark preparation; rarrk",
"bark paintings",
"ritual and belief;record and writing",
"artists; art centres",
"Ownership of designs belongs to clans.",
"Indigenous-community;sacred",
"community-published site; Trove National Library of Australia (link out; public-domain items where marked)",
"R3",
"F1.26;F1.20",
"high",
"",
"canon_techniques.csv"
],
[
"TEC213",
"Acrylic dot painting (Western Desert)",
"Papunya Tula painting",
"technique",
"Things",
"F1.12",
"OC-AUS",
"1971",
"",
"Papunya 1971",
"Western Desert artists translated ground and body designs into acrylic on board and canvas.",
"acrylic; dotting",
"canvases; boards",
"ritual and belief;exchange and value",
"artists; Papunya Tula Artists",
"Some early works disclosed restricted designs.",
"Indigenous-community;sacred",
"community-published site",
"R3",
"F1.20;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC214",
"Stick charts",
"mattang; meddo; rebbelib",
"technique",
"Things",
"F1.12",
"OC-MIC",
"",
"",
"long-standing; described by outsiders from the 19th c.",
"Marshallese navigators lashed sticks and shells to model ocean swell patterns and islands.",
"lashing; memory",
"stick charts",
"transport;record and writing",
"Marshallese navigators",
"",
"Indigenous-community;living-community",
"Smithsonian NMNH Anthropology via Smithsonian Open Access (CC0 where marked); Wikimedia Commons",
"R3",
"F1.28",
"high",
"",
"canon_techniques.csv"
],
[
"TEC215",
"Star compass wayfinding",
"non-instrument navigation",
"technique",
"Things",
"F1.12",
"OC-POL;OC-MIC",
"",
"",
"ancient; revived by Mau Piailug and Nainoa Thompson from 1976",
"Navigators hold a mental compass of star rising and setting points, swells and birds to cross open ocean.",
"star paths; swell reading",
"—",
"transport",
"navigators; voyaging societies",
"",
"Indigenous-community;living-community",
"community-published site; Wikimedia Commons",
"R3",
"F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC216",
"Astrolabe making",
"astrolabe",
"technique",
"Things",
"F1.10;F1.11",
"WA-MES;WA-IRN;EU-IBE",
"750",
"",
"Greek theory; early Islamic makers 8th c.; earliest surviving dated examples 10th c.",
"Engraved brass plates and a rete model the sky for time-telling and astronomy.",
"brass casting; engraving",
"astrolabes",
"tools;record and writing",
"historians of science",
"",
"none",
"Met Open Access (CC0); Wikimedia Commons",
"R3",
"F1.13",
"high",
"",
"canon_techniques.csv"
],
[
"TEC217",
"Agricultural terracing",
"terraces",
"technique",
"Things",
"F1.7;F1.9;F1.10;F1.8",
"AM-AND;AS-ISE;WA-ARB;AS-CHN",
"-3000",
"",
"approximate; many independent traditions; Andean, Yemeni, Ifugao and Hani terraces",
"Stepped, walled fields hold soil and water on steep slopes.",
"dry-stone walls; irrigation",
"terraces",
"food and storage",
"communities; archaeologists",
"Ifugao terrace ages debated.",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC218",
"Chinampas",
"raised garden plots",
"technique",
"Things",
"F1.7",
"AM-MES",
"1100",
"",
"approximate; Xochimilco chinampas ongoing",
"Plots built from lake mud and vegetation between canals made the Basin of Mexico highly productive.",
"mud piling; ahuejote trees",
"chinampas",
"food and storage",
"communities; archaeologists",
"",
"living-community;Indigenous-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC219",
"Budj Bim eel aquaculture",
"kooyang traps",
"technique",
"Things",
"F1.12",
"OC-AUS",
"-4600",
"",
"channels dated c.6,600 years ago; Budj Bim Cultural Landscape inscribed as World Heritage 2019 (not an ICH element)",
"Gunditjmara people shaped lava-flow channels, weirs and ponds to trap and hold eels.",
"stone channels; weirs; woven traps",
"traps; channels",
"food and storage",
"Gunditjmara people; UNESCO",
"",
"Indigenous-community",
"community-published site; UNESCO World Heritage / Intangible Cultural Heritage pages (link out)",
"R2",
"F1.22;F1.26",
"high",
"",
"canon_techniques.csv"
],
[
"TEC220",
"Qanat",
"karez; falaj; foggara",
"technique",
"Things",
"F1.9a;F1.10;F1.12a",
"WA-IRN;WA-ARB;AF-MAG;AS-CEN",
"-1000",
"",
"aflaj at Hili 15 and Bida Bint Saud (UAE) associated with Iron Age II pottery c. 1000–600 BCE; Iranian origin argued (English, Lightfoot), Arabian origin argued (Al Tikriti); secure absolute dates lacking (Charbonnier)",
"Gently sloping tunnels bring groundwater to fields and towns by gravity.",
"shaft sinking; tunnelling",
"qanats",
"food and storage;care and access",
"communities; UNESCO",
"",
"living-community",
"UNESCO World Heritage / Intangible Cultural Heritage pages (link out); Wikimedia Commons",
"R3",
"F1.22",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC221",
"Cultural burning",
"fire-stick farming; cool burning",
"technique",
"Things",
"F1.12",
"OC-AUS",
"",
"",
"deep antiquity; ongoing; term 'fire-stick farming' coined by Rhys Jones 1969",
"Aboriginal land managers use frequent low-intensity fire to shape vegetation and reduce fuel.",
"patch burning",
"landscapes",
"food and storage",
"Aboriginal communities",
"Indigenous knowledge suppressed under colonisation.",
"Indigenous-community;living-community",
"community-published site",
"R3",
"F1.22;F1.29",
"high",
"",
"canon_techniques.csv"
],
[
"TEC222",
"Amazonian dark earth",
"terra preta",
"technique",
"Things",
"F1.7",
"AM-AMZ",
"-500",
"",
"c.500 BCE onward; approximate",
"Charcoal, pottery and organic waste built persistent fertile soils along Amazonian rivers.",
"charcoal; midden",
"soils",
"food and storage",
"archaeologists; soil scientists",
"",
"Indigenous-community",
"open-access journal articles",
"R3",
"F1.22",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC223",
"Kintsugi",
"kintsukuroi",
"technique",
"Things",
"F1.8",
"AS-JPN",
"1500",
"",
"Muromachi period, c.15th–16th c.; approximate",
"Broken ceramics are rejoined with urushi lacquer and dusted with gold, displaying the repair.",
"urushi; gold powder",
"tea bowls",
"care and access",
"makers; tea practitioners",
"",
"none",
"Met Open Access (CC0); ColBase Japan national museums (Japan Government Standard Terms)",
"R3",
"F1.22a",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC224",
"Darning",
"darning",
"technique",
"Things",
"THEME",
"GL",
"",
"",
"long-standing",
"Weaving new threads across a hole restores worn textiles.",
"needle; darning mushroom",
"socks; garments",
"care and access;clothing and adornment",
"makers",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22a;F1.18",
"high",
"",
"canon_techniques.csv"
],
[
"TEC225",
"Visible mending",
"visible mending",
"technique",
"Things",
"THEME",
"GL",
"2010",
"",
"contemporary movement c.2010s",
"Menders make repairs deliberately visible as a stance against disposable consumption.",
"patching; darning",
"garments",
"care and access",
"makers; online communities",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.22a;F1.21",
"medium",
"",
"canon_techniques.csv"
],
[
"TEC226",
"Mesoamerican rubber processing",
"rubber from latex and morning glory",
"technique",
"Things",
"F1.7",
"AM-MES",
"-1600",
"",
"Paso de la Amada balls c.1600 BCE; El Manatí balls earlier; Hosler et al. 1999",
"Mixing Castilla elastica latex with morning-glory juice produced bouncing rubber for ballgame balls.",
"latex; morning-glory mixing",
"balls; sandals",
"play and music;ritual and belief",
"archaeologists (Hosler, Burkett and Tarkanian 1999)",
"",
"none",
"open-access journal articles; Wikimedia Commons",
"R3",
"F1.5;F1.4",
"high",
"",
"canon_techniques.csv"
],
[
"TEC227",
"Vulcanisation",
"vulcanised rubber",
"technique",
"Things",
"F1.7",
"AM-EWD",
"1844",
"",
"Charles Goodyear patent 1844; Thomas Hancock (UK) 1843",
"Heating rubber with sulphur made it stable, enabling tyres, hoses and footwear and a global demand for latex.",
"sulphur curing",
"tyres; hoses; shoes",
"transport;clothing and adornment",
"patents; historians",
"Demand drove forced rubber collection in Congo and Amazonia.",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.19;F1.22",
"high",
"",
"canon_techniques.csv"
],
[
"TEC228",
"Interchangeable parts",
"American system of manufactures",
"technique",
"Things",
"F1.11;F1.7",
"EU-WCE;AM-EWD",
"1785",
"",
"Honoré Blanc 1785; US armouries 1820s; standardised Qin crossbow triggers 3rd c. BCE as earlier parallel",
"Making parts to gauges so any part fits any product enabled mass production and repair by replacement.",
"gauges; jigs; machine tools",
"firearms; clocks",
"war;tools",
"historians of technology",
"",
"none",
"Wikimedia Commons",
"R3",
"F1.19",
"high",
"",
"canon_techniques.csv"
],
[
"TEC229",
"Moving assembly line",
"assembly line",
"technique",
"Things",
"F1.7",
"AM-EWD",
"1913",
"",
"Ford Highland Park 1913",
"Moving work past fixed workers cut assembly times and deskilled factory labour.",
"conveyor; task division",
"cars",
"transport",
"historians",
"Line workers' experience.",
"none",
"Library of Congress (public-domain items); Wikimedia Commons",
"R3",
"F1.19;F1.23",
"high",
"",
"canon_techniques.csv"
],
[
"TEC230",
"Injection moulding",
"plastic injection moulding",
"technique",
"Things",
"F1.7",
"AM-EWD",
"1872",
"",
"Hyatt brothers 1872; screw injection 1946",
"Molten plastic forced into steel moulds makes identical parts in seconds, the basis of plastic consumer goods.",
"steel moulds; thermoplastics",
"toys; housings; containers",
"tools;play and music",
"patents; historians",
"",
"none",
"Google Patents / national patent offices (public documents); Wikimedia Commons",
"R3",
"F1.21;F1.22",
"high",
"",
"canon_techniques.csv"
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
