insert into public.f1_world_set ("id", "kind", "status", "title", "date", "holder", "accession", "licence", "holder_and_licence_note", "provenance", "provenance_test", "test_basis", "history_gap", "action", "units", "roles", "verified_in", "met_object_id")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14), public.cw_text(x->15), public.cw_text(x->16), public.cw_text(x->17)
from jsonb_array_elements($cwb$[
[
"AS-001",
"asset",
"support",
", plates",
"1856",
"",
"",
"Public domain",
"Public domain",
"—",
"",
"",
"",
"",
"F1.11",
"The exhibition as taxonomy (to F1.15)",
"DD2",
""
],
[
"AS-003",
"asset",
"support",
"Catalan Atlas, sheet 6",
"1375",
"BnF",
"",
"To check",
"BnF Espagnol 30; public-domain work, reproduction terms to check",
"—",
"",
"",
"",
"",
"F1.13",
"Gold across the Sahara, as Europe drew it",
"DD2",
""
],
[
"DAT-001",
"dataset",
"support",
"Open Khipu Repository",
"—",
"",
"",
"To check",
"MIT-licensed data",
"—",
"",
"",
"",
"",
"F1.7",
"Ring 2 dataset",
"DD2",
""
],
[
"DOC-001",
"document",
"support",
"Ben Yiju's workshop accounts",
"1132–1149",
"Cambridge University Library",
"",
"To check",
"Cambridge University Library Or.1080 J95; image rights to check",
"—",
"",
"",
"",
"",
"F1.10",
"A workshop's own ledger",
"DD2",
""
],
[
"DOC-002",
"document",
"support",
"plates",
"1103 (later editions)",
"",
"",
"Public domain",
"Public domain; Wikisource scans",
"—",
"",
"",
"",
"",
"F1.8",
"The modular code",
"DD2",
""
],
[
"DOC-003",
"document",
"support",
"Dutch Company order for Bengal cloth, 1701",
"—",
"",
"",
"To check",
"Cited in Chaudhury; archive at the Nationaal Archief",
"—",
"",
"",
"",
"",
"F1.9",
"Cloth ordered by the thousand",
"DD2",
""
],
[
"DOC-004",
"document",
"support",
"",
"13th century, 1837 edition",
"",
"",
"Public domain",
"Public domain, Internet Archive",
"—",
"",
"",
"",
"",
"F1.11",
"The guild rule in the guild's words",
"DD2",
""
],
[
"PL-020",
"place",
"support",
"Madjedbebe (place)",
"Rock shelter, Mirarr Country, Northern Territory",
"",
"",
"To check",
"Excavation reports; both dates shown",
"Deep time; the contested line",
"",
"",
"",
"",
"F1.12",
"Deep time; the contested line",
"DD2",
""
],
[
"PL-021",
"place",
"support",
"Budj Bim (place)",
"Gunditjmara aquaculture landscape",
"",
"",
"To check",
"UNESCO; Gunditjmara-authored material to be sought first",
"Engineering without metal",
"",
"",
"",
"",
"F1.12",
"Engineering without metal",
"DD2",
""
],
[
"PL-030",
"place",
"support",
"Magan copper sites, Oman (place)",
"3rd millennium BCE",
"",
"",
"To check",
"Published surveys",
"—",
"",
"",
"",
"",
"F1.9a",
"The Gulf's first export",
"DD2",
""
],
[
"PL-040",
"place",
"support",
"Botai (place)",
"c. 3500 BCE",
"",
"",
"To check",
"Published sites",
"—",
"",
"",
"",
"",
"F1.12a",
"The revised first",
"DD2",
""
],
[
"PL-041",
"place",
"support",
"The lower Volga–Don steppe (place)",
"c. 2200–2000 BCE",
"",
"",
"To check",
"Librado et al.",
"—",
"",
"",
"",
"",
"F1.12a",
"Where domestic horses spread from",
"DD2",
""
],
[
"PR-010",
"practice",
"support",
"Wayfinding (practice)",
"Hawaiian and Micronesian non-instrument navigation",
"",
"",
"To check",
"Polynesian Voyaging Society, in its own words",
"The living practice",
"",
"",
"",
"",
"F1.12",
"The living practice",
"DD2",
""
],
[
"WS-001",
"object",
"exemplar",
"Proto-cuneiform tablet with seal impressions",
"c. 3100–2900 BCE, probably Uruk",
"Met",
"1988.433.1",
"Public domain",
"Met 1988.433.1, public domain",
"Until 1988, Erlenmeyer collection, purchased by Professor Hans and Marie-Louise Erlenmeyer between 1943 and the early 1960s; acquired by the Museum in 1988, purchased at the sale of Ancient Near Eastern texts form the Erlenmeyer collection, Christie's, London, December 13, 1988, lot 21",
"pass",
"In a documented private collection outside Iraq before 1970 (bought 1943 to early 1960s)",
"How and when it left Iraq is not recorded",
"",
"F1.5 F1.9a",
"Writing, Mesopotamia / F1.1's anchor; now with a documented sibling",
"DD1 DD2 + provenance pass 2026-09-28",
"329081"
],
[
"WS-002",
"object",
"exemplar",
"Wine vessel (jue), inscribed \"Father Yi of the Chu Clan\"",
"c. 1200 BCE, Shang",
"Cleveland",
"1960.42",
"CC0",
"Cleveland 1960.42, CC0",
"Acquired 1960, before the threshold",
"pass",
"In a museum or documented collection by 1960",
"",
"",
"F1.5 F1.8",
"Writing on bronze, beside the oracle bones / Piece-mould casting; the clan inscription (shared with F1.5)",
"DD1 DD2",
""
],
[
"WS-003",
"object",
"exemplar",
"Stone mason's chisel",
"c. 2051–2000 BCE",
"Met",
"27.3.12",
"Public domain",
"Met 27.3.12, public domain",
"Excavated by the Met at Deir el-Bahri, 1926–27",
"pass",
"Excavated by the Met at Deir el-Bahri, 1926–27",
"",
"",
"F1.5 F1.6 F1.9a",
"Metals; Egypt's copper-alloy tools (also F1.6) / Copper-alloy tools on the Nile (shared with F1.5) / Copper-alloy tools on the Nile (shared)",
"DD1 DD2",
""
],
[
"WS-004",
"object",
"exemplar",
"Chavín-style gold plaque",
"c. 500–200 BCE",
"Cleveland",
"1938.431",
"CC0",
"Cleveland 1938.431, CC0",
"Owned by 1938; findspot uncertain (\"Chongoyape?\")",
"pass",
"In a museum or documented collection by 1938",
"",
"",
"F1.5 F1.7",
"Metals, Andes: the cold-hammering tradition / The Early Horizon (shared with F1.5)",
"DD1 DD2",
""
],
[
"WS-005",
"object",
"case",
"Fire-flame cooking vessel (ka'en doki)",
"c. 2500 BCE, Jōmon",
"Cleveland",
"1984.68",
"CC0",
"Cleveland 1984.68, CC0",
"(Gallery Kapitan, Tokyo, Japan, sold to the Cleveland Museum of Art) (?–1984); The Cleveland Museum of Art (1984–)",
"fail",
"First record 1984; no excavation or export record published",
"Also: the museum reports that a base from a different vessel was used in a 20th-century reconstruction",
"Case, not exemplar: what a reconstruction and a missing history each hide. Replace the exemplar with an excavated flame vessel held in Japan (ColBase or a municipal museum; rights to check)",
"F1.5 F1.8",
"Pottery, East Asia; late in the sequence, since the oldest sherds are not in open collections / The deep end (shared with F1.5)",
"DD1 DD2 + provenance pass 2026-09-28",
""
],
[
"WS-006",
"object",
"exemplar",
"Block-printed cotton fragment",
"1200s–1300s",
"Cleveland",
"1929.845",
"CC0",
"Cleveland 1929.845, CC0",
"Acquired 1929",
"pass",
"In a museum or documented collection by 1929",
"",
"",
"F1.5 F1.13 F1.10 F1.9",
"Cotton and printing on cloth. Catalogued as \"Egypt, Mamluk\": that is where it was found; where it was made is a separate question / Indian Ocean cotton (shared with F1.5) / Indian cotton in Mamluk Egypt / Catalogued as \"Egypt, Mamluk\"; Barnes's work suggests the Gujarat question must be asked. The card shows both",
"DD1 DD2",
""
],
[
"WS-007",
"object",
"exemplar",
"Tunic",
"650–1000 CE, Wari",
"Met",
"2021.146",
"Public domain",
"Met 2021.146, public domain",
"[André Emmerich Gallery, New York, 1960s]; Guido and Nelly di Tella, Buenos Aires, ca. 1960s–2013; Claudia Quentin, New York, 2013–2021",
"pass-caveat",
"Outside Peru by the 1960s on the museum's record; the Met brackets the 1960s gallery step, which marks it as unconfirmed",
"Findspot unknown; the pre-1970 step is bracketed",
"",
"F1.5 F1.7",
"Cotton and camelid fibre, Andes / The Middle Horizon (shared with F1.5)",
"DD1 DD2 + provenance pass 2026-09-28",
"675980"
],
[
"WS-008",
"object",
"exemplar",
"One of the One Million Pagodas, with its printed invocation",
"c. 764–770, Japan",
"Met",
"30.47a–c",
"Public domain",
"Met 30.47a–c, public domain",
"Given 1930",
"pass",
"In a museum or documented collection by 1930",
"",
"",
"F1.5 F1.8",
"Printing / Printing as mass production",
"DD1 DD2",
""
],
[
"WS-010",
"object",
"exemplar",
"Plaque",
"1500s–1600s",
"Cleveland",
"1999.1",
"CC0",
"Cleveland 1999.1, CC0",
"Cast by the Igun Eronmwon; royal palace, Benin City; sent to England after the 1897 assault; British Museum until 1950, when the museum sold it through an agent; New York dealers; Cleveland in 1999",
"pass",
"In a museum or documented collection by 1897",
"",
"",
"F1.6 F1.13 F1.11",
"Brass, casting, the Atlantic metal route; 1897 and what followed / Rhineland brass on the Atlantic (shared with F1.6) / Rhineland brass: Europe's metal in Africa's casting (to F1.6)",
"DD1 DD2",
""
],
[
"WS-011",
"object",
"exemplar",
"Ancestral commemorative head (uhunmwun-elao)",
"Possibly mid-1500s or early 1600s",
"Cleveland",
"1938.6",
"CC0",
"Cleveland 1938.6, CC0",
"Royal palace until 1897; a London dealer, then Louis Carré, Paris; Cleveland in 1938",
"pass",
"In a museum or documented collection by 1897",
"",
"",
"F1.6",
"Casting in copper alloy with iron inlay",
"DD1",
""
],
[
"WS-012",
"object",
"exemplar",
"Gold weight (abrammuo), geometric form",
"1800s",
"Cleveland",
"1962.244",
"CC0",
"Cleveland 1962.244, CC0",
"Mr. and Mrs. Robert M. Hornung, Cleveland Heights, OH, given to the Cleveland Museum of Art (?–1962)",
"pass",
"In Cleveland since 1962",
"How it left Ghana is not recorded",
"",
"F1.6",
"Weighing gold dust: brass that measured gold",
"DD1 + provenance pass 2026-09-28",
""
],
[
"WS-013",
"object",
"exemplar",
"Gold weight (abrammuo), antelope",
"1800s",
"Cleveland",
"1935.306",
"CC0",
"Cleveland 1935.306, CC0",
"Acquired 1935",
"pass",
"In a museum or documented collection by 1935",
"",
"",
"F1.6",
"The same, figurative",
"DD1",
""
],
[
"WS-014",
"object",
"exemplar",
"Ceremonial axe (gano)",
"1900s, by 1928",
"Cleveland",
"1929.364",
"CC0",
"Cleveland 1929.364, CC0",
"Collected in 1927–28 by Paul B. Travis for the Gilpin Players of Karamu House and the African Art Sponsors, Cleveland; the 1928 checklist calls it \"Shangaan\" and notes a disc from a Swiss watch movement set into it",
"pass",
"In a museum or documented collection by 1927",
"",
"",
"F1.6",
"Iron in the south; reuse of imported metal; an African American collection of the 1920s; an attribution that has changed",
"DD1",
""
],
[
"WS-015",
"object",
"exemplar",
"Throwing knife and prestige sceptre (pingha)",
"1800–mid-1900s",
"Cleveland",
"2015.156",
"CC0",
"Cleveland 2015.156, CC0",
"Jacques Hautelet, La Jolla, CA (by at least 2004); Robert H. Jackson by gift to the Cleveland Museum of Art (?–2015); The Cleveland Museum of Art (2015–)",
"colonial-gap",
"Not an antiquity, so the 1970 test does not apply; made 1800 to mid-1900s in a colonised region and first recorded in 2004",
"Collection circumstances unknown",
"Replace with a throwing knife collected with a documented date and context; if none is licensed, show this one with its gap stated",
"F1.6",
"Iron as a form of value",
"DD1 + provenance pass 2026-09-28",
""
],
[
"WS-016",
"object",
"exemplar",
"Cup with geometric decoration, Meroitic",
"1st–3rd century",
"Met",
"13.125.37",
"Public domain",
"Met 13.125.37, public domain",
"Excavated at Faras, grave 1007, by the University of Oxford, 1911–12",
"pass",
"Excavated at Faras by the University of Oxford, 1911–12",
"",
"",
"F1.6",
"Nubia; filed by the Met under \"Egyptian Art\"",
"DD1",
""
],
[
"WS-020",
"object",
"exemplar",
"Jar with lion-head handles, Jingdezhen",
"1300s, Yuan",
"Cleveland",
"1962.154",
"CC0",
"Cleveland 1962.154, CC0",
"A New York dealer, sold to Cleveland in 1962",
"pass",
"In a museum or documented collection by 1962",
"",
"",
"F1.13 F1.8",
"The object carried along the route / Blue-and-white for export",
"DD2",
""
],
[
"WS-021",
"object",
"exemplar",
"Footed bowl, probably Kashan",
"Late 1100s–early 1200s",
"Cleveland",
"1915.581",
"CC0",
"Cleveland 1915.581, CC0",
"Bought in 1915",
"pass",
"In a museum or documented collection by 1915",
"",
"",
"F1.13 F1.10",
"Cobalt blue in Iran before Chinese blue-and-white / Cobalt in Iran (shared with F1.13)",
"DD2",
""
],
[
"WS-022",
"object",
"exemplar",
"Basin, Puebla, Mexico, by \"Master Potter A\"",
"About 1650",
"Met",
"12.3.1",
"Public domain",
"Met 12.3.1, public domain",
"Given in 1912",
"pass",
"In a museum or documented collection by 1912",
"",
"",
"F1.13 F1.7",
"The Manila galleon reaches Mexican kilns / Mexico after contact (shared with F1.13)",
"DD2",
""
],
[
"WS-030",
"object",
"to-license",
"Ground-edge axe fragment, Carpenter's Gap",
"44,000–49,000 years old",
"",
"",
"Image rights to request",
"Published finds; image rights to request",
"The earliest known ground edge",
"pass",
"Published excavation finds",
"",
"",
"F1.12",
"The earliest known ground edge",
"DD2",
""
],
[
"WS-031",
"object",
"rights-blocked",
"navigation chart",
"19th–early 20th century, Marshall Islands",
"Met",
"1978.412.826",
"Not public domain",
"Met 1978.412.826, not public domain; Smithsonian NMNH holds 15 charts, rights to check",
"The model of the sea",
"to-check",
"",
"",
"Case only until a licensed chart is found (Smithsonian NMNH holds 15; rights to check)",
"F1.12",
"The model of the sea",
"DD2",
""
],
[
"WS-032",
"object",
"to-license",
"Lapita dentate-stamped sherd",
"About 3,300 years ago",
"",
"",
"Image to license",
"Excavated material; museum image to be licensed",
"The pottery that maps the voyages",
"pass",
"Excavated material",
"",
"",
"F1.12",
"The pottery that maps the voyages",
"DD2",
""
],
[
"WS-033",
"object",
"rights-blocked",
"(barkcloth), Lau Islands, Fiji",
"Late 19th–early 20th century",
"Met",
"1977.395.3",
"Not public domain",
"Met 1977.395.3, not public domain",
"Case only, until a licensed example is found (Te Papa and Australian collections next)",
"to-check",
"",
"",
"Case only until a licensed barkcloth is found (Te Papa and Australian collections next)",
"F1.12",
"Case only, until a licensed example is found (Te Papa and Australian collections next)",
"DD2",
""
],
[
"WS-040",
"object",
"exemplar",
"Mosque lamp, Iznik",
"1585–95",
"Cleveland",
"1944.236",
"CC0",
"Cleveland 1944.236, CC0",
"A New York dealer, 1944",
"pass",
"In a museum or documented collection by 1944",
"",
"",
"F1.10",
"A fitting made for an endowed building",
"DD2",
""
],
[
"WS-041",
"object",
"exemplar",
"Large dish with artichokes, Iznik",
"c. 1535–40",
"Cleveland",
"1995.17",
"CC0",
"Cleveland 1995.17, CC0",
"Sulzbach; Stora; Scarisbrick [no dates]; (Oliver Hoare Ltd., London, UK, sold to the Cleveland Museum of Art) (?-1995); The Cleveland Museum of Art (1995-)",
"enquiry",
"Three named earlier owners, none dated; the test turns on whether any held it before 1970",
"Dates for the three named owners",
"Keep as a provisional exemplar with its line shown; ask Cleveland for the owners' dates",
"F1.10",
"The Iznik workshop at its peak",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-042",
"object",
"case",
"Tile spandrel with floral sprays, Iznik",
"c. 1570–75",
"Cleveland",
"2004.70",
"CC0",
"Cleveland 2004.70, CC0",
"(Momtaz Islamic Art, London, England, sold to the Cleveland Museum of Art) (?–2004); The Cleveland Museum of Art (2004–)",
"fail",
"First record 2004; an architectural element with no record of its building or its removal",
"Which building it came from",
"Drop as exemplar; the Iznik unit keeps WS-040 and WS-041",
"F1.10",
"Architectural tile; provenance to confirm",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-043",
"object",
"exemplar",
"Cover with four trees of life, Egypt",
"4th–5th century",
"Met",
"90.5.902",
"Public domain",
"Met 90.5.902, public domain",
"Emil Brugsch-Bey (until 1890; sold to Baker); George F. Baker, New York (1890; gifted to MMA)",
"pass",
"In the Met since 1890",
"Findspot unknown. The seller worked for Egypt's antiquities service; sales like this were legal then, which F1.24 can question",
"",
"F1.10",
"Egypt's weaving before Islam: the chapter opens on continuity",
"DD2 + provenance pass 2026-09-28",
"444375"
],
[
"WS-044",
"object",
"exemplar",
"Bottle, enamelled glass, Europe",
"c. 1900",
"Cleveland",
"1944.488",
"CC0",
"Cleveland 1944.488, CC0",
"A New York dealer, 1944",
"n/a",
"European decorative art of about 1900; not archaeological. In Cleveland since 1944",
"",
"",
"F1.10",
"The copying case: a Mamluk sultan's name on a European bottle",
"DD2",
""
],
[
"WS-045",
"object",
"exemplar",
"Mosque lamp by Philippe-Joseph Brocard, Paris",
"Late 1800s",
"Cleveland",
"1981.10",
"CC0",
"Cleveland 1981.10, CC0",
"Brocard, then dealers",
"n/a",
"Signed Paris work of the late 1800s; not archaeological",
"",
"",
"F1.10",
"The same, with a named maker",
"DD2",
""
],
[
"WS-050",
"object",
"exemplar",
"Mantle, Paracas (Cavernas style)",
"c. 300 BCE–200 CE",
"Cleveland",
"1946.226",
"CC0",
"Cleveland 1946.226, CC0",
"Given by the Norwebs in 1946; before that unknown. Passes the 1970 test; its removal from Peru is undocumented",
"pass",
"In a museum or documented collection by 1946",
"",
"",
"F1.7",
"Embroidery on camelid fibre; taught with the Gothenburg case",
"DD2",
""
],
[
"WS-051",
"object",
"exemplar",
"Tunic, Paracas",
"c. 300 BCE–200 CE",
"Cleveland",
"1946.227",
"CC0",
"Cleveland 1946.227, CC0",
"Same",
"pass",
"In a museum or documented collection by 1946",
"",
"",
"F1.7",
"Warp substitution and embroidery",
"DD2",
""
],
[
"WS-052",
"object",
"exemplar",
"Turban band (), Paracas",
"c. 300–100 BCE",
"Cleveland",
"1946.228",
"CC0",
"Cleveland 1946.228, CC0",
"Same",
"pass",
"In a museum or documented collection by 1946",
"",
"",
"F1.7",
"Needle netting",
"DD2",
""
],
[
"WS-053",
"object",
"exemplar",
"Inka khipu",
"c. 1400–1532",
"Cleveland",
"1940.469",
"CC0",
"Cleveland 1940.469, CC0",
"[none published]; credit line Gift of John Wise, accessioned 30 October 1940",
"pass",
"In Cleveland since 1940",
"Findspot and earlier owners unknown",
"",
"F1.7",
"The record without writing",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-054",
"object",
"exemplar",
"Wearing blanket, Diné, woman artist",
"c. 1875–80",
"Cleveland",
"1921.556",
"CC0",
"Cleveland 1921.556, CC0",
"No provenance in the record",
"pass",
"In a museum or documented collection by 1921",
"",
"",
"F1.7",
"Handspun, Germantown and bayeta in one cloth: the trade in the weave",
"DD2",
""
],
[
"WS-055",
"object",
"exemplar",
"Fourth-phase chief blanket style rug, Diné",
"c. 1900",
"Cleveland",
"1937.903",
"CC0",
"Cleveland 1937.903, CC0",
"Given by Amelia Elizabeth White, 1937",
"pass",
"In a museum or documented collection by 1937",
"",
"",
"F1.7",
"From blanket to rug: the trading post's market",
"DD2",
""
],
[
"WS-060",
"object",
"exemplar",
"Tripod cauldron ()",
"1200–1100 BCE, Shang",
"Cleveland",
"1960.288",
"CC0",
"Cleveland 1960.288, CC0",
"Frank Caro [1904–1980], New York, NY, given to the Cleveland Museum of Art by exchange (?–1960); The Cleveland Museum of Art (1960–)",
"pass",
"In Cleveland since 1960",
"History before Frank Caro not recorded",
"",
"F1.8",
"The foundry's scale",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-061",
"object",
"exemplar",
"Jar with cover, Jun ware",
"1100s, Northern Song or Jin",
"Cleveland",
"1957.36",
"CC0",
"Cleveland 1957.36, CC0",
"Men-chu Wang, Seller's no. 12",
"pass",
"In Cleveland since January 1957",
"A seller's number only",
"",
"F1.8",
"A glaze that runs and pools: the kiln as co-maker",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-062",
"object",
"exemplar",
"Vase with inlaid lotus, plum and bamboo",
"1300s, Goryeo",
"Cleveland",
"1918.471",
"CC0",
"Cleveland 1918.471, CC0",
"Bought by Langdon Warner, given 1918",
"pass",
"In a museum or documented collection by 1918",
"",
"",
"F1.8",
"Korea's inlay technique ()",
"DD2",
""
],
[
"WS-063",
"object",
"exemplar",
"Bowl with inlaid waterfowl, willow and reed",
"1300s, Goryeo",
"Cleveland",
"1918.458",
"CC0",
"Cleveland 1918.458, CC0",
"Bought by Warner in Korea; given 1918",
"pass",
"In a museum or documented collection by 1918",
"",
"",
"F1.8",
"The same; Warner's collecting as a case for F1.24",
"DD2",
""
],
[
"WS-070",
"object",
"exemplar",
"Nataraja, Shiva as Lord of Dance",
"1000s, Chola",
"Cleveland",
"1930.331",
"CC0",
"Cleveland 1930.331, CC0",
"C. T. Loo, New York, sold 1930",
"pass",
"In a museum or documented collection by 1930",
"",
"",
"F1.9",
"Lost-wax casting for a temple; the NGA case beside it",
"DD2",
""
],
[
"WS-071",
"object",
"exemplar",
"Shiva and Parvati",
"c. 1020–40",
"Cleveland",
"1961.94",
"CC0",
"Cleveland 1961.94, CC0",
"A New York dealer, 1961",
"pass",
"In a museum or documented collection by 1961",
"",
"",
"F1.9",
"The same workshop tradition",
"DD2",
""
],
[
"WS-072",
"object",
"to-license",
"Jamdani sari",
"Living practice",
"",
"",
"Weavers' images to license",
"Weavers' own images, to license",
"—",
"n/a",
"Living practice; images from the weavers, licensed",
"",
"",
"F1.9",
"The living cloth",
"DD2",
""
],
[
"WS-073",
"object",
"to-source",
"double-ikat silk, Patan",
"To source",
"",
"",
"To source",
"Not in Cleveland's CC0 set; Met or Rijksmuseum to check",
"—",
"to-check",
"",
"",
"",
"F1.9",
"Gujarat's silk for Indonesia",
"DD2",
""
],
[
"WS-074",
"object",
"to-source",
"Indus seal",
"c. 2500 BCE",
"Met",
"",
"To check",
"Met or Cleveland to check at record level",
"—",
"to-check",
"",
"",
"",
"F1.9",
"The signs (shared with F1.5)",
"DD2",
""
],
[
"WS-080",
"object",
"exemplar",
"Black-figure amphora, Attic",
"c. 530–520 BCE",
"Cleveland",
"1927.433",
"CC0",
"Cleveland 1927.433, CC0",
"Bateman collection, London; Florence dealers; sold 1927",
"pass",
"In a museum or documented collection by 1927",
"",
"",
"F1.11",
"The potter's and painter's workshop; the Mediterranean before Europe",
"DD2",
""
],
[
"WS-081",
"object",
"exemplar",
"Black-figure neck-amphora, Attic",
"515–510 BCE",
"Cleveland",
"1970.16",
"CC0",
"Cleveland 1970.16, CC0",
"The Cleveland Museum of Art, Cleveland, OH (1970—) [entry 1 not published]",
"pass",
"Accessioned 9 March 1970, eight months before the 17 November 1970 threshold",
"Earlier owners not published; the record's first entry is missing",
"",
"F1.11",
"Same",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-082",
"object",
"to-source",
"bowl with a maker's stamp",
"1st century",
"",
"",
"To check",
"To source from the Met or the British Museum at record level",
"—",
"to-check",
"",
"",
"",
"F1.11",
"The stamped mass product",
"DD2",
""
],
[
"WS-083",
"object",
"exemplar",
"Plate, Delft",
"1700s",
"Cleveland",
"1969.254",
"CC0",
"Cleveland 1969.254, CC0",
"No provenance in the record",
"n/a",
"Dutch decorative art of the 1700s; not archaeological. In Cleveland since 1969",
"",
"",
"F1.11",
"The copy of a copy (to F1.14)",
"DD2",
""
],
[
"WS-084",
"object",
"exemplar",
"Plate, English delftware",
"Mid-1700s",
"Cleveland",
"1986.31",
"CC0",
"Cleveland 1986.31, CC0",
"A Cleveland auction",
"n/a",
"English decorative art of the 1700s; not archaeological. Bought at a Cleveland auction, 1986",
"",
"",
"F1.11",
"Same, one step on",
"DD2",
""
],
[
"WS-085",
"object",
"exemplar",
"Portland Vase, Wedgwood jasperware",
"c. 1790",
"Cleveland",
"1918.823",
"CC0",
"Cleveland 1918.823, CC0",
"In the museum since 1918",
"n/a",
"Wedgwood factory product; in Cleveland since 1918",
"",
"",
"F1.11",
"The factory reproduces antiquity",
"DD2",
""
],
[
"WS-090",
"object",
"exemplar",
"Cuneiform tablet: distribution of barley and emmer",
"c. 3100–2900 BCE",
"Met",
"1988.433.2",
"Public domain",
"Met 1988.433.2, public domain",
"Until 1988, Erlenmeyer collection, purchased by Professor Hans and Marie-Louise Erlenmeyer between 1943 and the early 1960s; acquired by the Museum in 1988, purchased at the sale of Ancient Near Eastern texts form the Erlenmeyer collection, Christie's, London, December 13, 1988 [lot number truncated in the page summary]",
"pass",
"Same collection and sale as WS-001",
"How and when it left Iraq is not recorded",
"",
"F1.9a",
"The account as the first text",
"DD2 + provenance pass 2026-09-28",
"327384"
],
[
"WS-091",
"object",
"case",
"Horse bit with winged ibex cheekpieces, Luristan",
"800–600 BCE",
"Cleveland",
"1980.102",
"CC0",
"Cleveland 1980.102, CC0",
"[none published]; purchase from the J. H. Wade Fund, accessioned 9 September 1980",
"fail",
"First record 1980; no findspot",
"Everything before 1980",
"Case, not exemplar: Luristan as the textbook case of objects without a findspot (F1.24; West Asia chapter). WS-092 carries the horse-gear point",
"F1.9a F1.12a",
"Cast bronze for horses: the steppe link / Harness as art (shared)",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-092",
"object",
"exemplar",
"Master of Animals cheekpiece, Luristan",
"c. 700 BCE",
"Cleveland",
"1961.33",
"CC0",
"Cleveland 1961.33, CC0",
"Mrs. Christian R. Holmes; Mozaffar Cohen, Paris [no dates]",
"pass",
"In Cleveland since 1961; two named earlier owners",
"No findspot; Luristan bronzes as a group were mostly dug without record from 1928",
"",
"F1.9a",
"Same",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-093",
"object",
"exemplar",
"Amphoriskos, mould-blown glass",
"50–100 CE, Roman",
"Cleveland",
"1919.12",
"CC0",
"Cleveland 1919.12, CC0",
"Two names, no dates; acquired 1919",
"pass",
"In a museum or documented collection by 1919",
"",
"",
"F1.9a",
"Blown glass within a century of its invention",
"DD2",
""
],
[
"WS-094",
"object",
"exemplar",
"Janiform head flask, mould-blown",
"100–400 CE, eastern Mediterranean",
"Cleveland",
"1923.945",
"CC0",
"Cleveland 1923.945, CC0",
"No provenance in the record; acquired 1923",
"pass",
"In a museum or documented collection by 1923",
"",
"",
"F1.9a",
"Glass as a mould-made product",
"DD2",
""
],
[
"WS-095",
"object",
"exemplar",
"Cup signed \"Ennion made me\"",
"c. 1–50 CE",
"Met",
"17.194.225",
"Public domain",
"Met 17.194.225; licence to check at record level",
"Gift of J. Pierpont Morgan, 1917",
"pass",
"In the Met since 1917; public domain confirmed at record level",
"Findspot not in the open data",
"",
"F1.9a",
"A named maker",
"DD2 + provenance pass 2026-09-28",
"249469"
],
[
"WS-100",
"object",
"to-license",
"Pile carpet, Pazyryk barrow 5",
"5th–4th century BCE",
"State Hermitage",
"",
"Image rights to request (State Hermitage)",
"State Hermitage 1687-93; image rights to request",
"Excavated 1949",
"pass",
"In a museum or documented collection by 1949",
"",
"",
"F1.12a",
"The oldest pile carpet; origin argued",
"DD2",
""
],
[
"WS-101",
"object",
"case",
"Child's coat with ducks in pearl medallions",
"700s",
"Cleveland",
"1996.2.1",
"CC0",
"Cleveland 1996.2.1, CC0",
"(Sara Tremayne, Ltd., London, UK, sold to the Cleveland Museum of Art) (?–1996); The Cleveland Museum of Art (1996–)",
"fail",
"First record 1996; no findspot",
"Everything before 1996",
"Case, not exemplar. WS-102 (in Cleveland since 1959) becomes the steppe chapter's silk exemplar",
"F1.12a",
"Silk on the road; contested attribution shown",
"DD2 + provenance pass 2026-09-28",
""
],
[
"WS-102",
"object",
"exemplar",
"Roundels with hunters, samite",
"800s, eastern Iran or Central Asia",
"Cleveland",
"1959.124",
"CC0",
"Cleveland 1959.124, CC0",
"A Paris dealer, 1959",
"pass",
"In a museum or documented collection by 1959",
"",
"",
"F1.12a",
"Compound weave; riders as motif",
"DD2",
""
],
[
"WS-103",
"object",
"to-license",
"Sintashta chariot burial",
"c. 2000–1800 BCE",
"",
"",
"Excavation photographs; rights to request",
"Excavation photographs; rights to request",
"Excavated",
"pass",
"",
"",
"",
"F1.12a",
"The spoked wheel",
"DD2",
""
],
[
"WS-104",
"object",
"to-source",
"Ordos-style animal plaque",
"1st millennium BCE",
"",
"",
"To source",
"Not in Cleveland's CC0 set; the Met at record level",
"—",
"to-check",
"",
"",
"",
"F1.12a",
"Cast bronze on the move",
"DD2",
""
],
[
"WS-X02",
"object",
"excluded",
"Oracle bone",
"\"19th century or earlier\"",
"Met",
"67.55.50",
"To check",
"Met 67.55.50",
"The Met does not date it to the Shang",
"n/a",
"",
"",
"Excluded: the Met does not date it to the Shang",
"F1.5",
"Excluded: it cannot stand for Shang writing",
"DD1",
""
],
[
"WS-X03",
"object",
"excluded",
"Painted vase with ruler and scribe, Maya",
"600–900",
"Cleveland",
"1990.181",
"To check",
"Cleveland 1990.181",
"First recorded at a Los Angeles gallery in 1972, with no findspot: fails",
"fail",
"",
"",
"Taught in F1.24 as a provenance case",
"F1.5",
"Excluded as an exemplar; taught in F1.24 as a provenance case",
"DD1",
""
],
[
"WS-X04",
"object",
"excluded",
"Head, \"Nok-culture style region\"",
"Thermoluminescence date 20–620 CE",
"Cleveland",
"1995.21",
"To check",
"Cleveland 1995.21",
"First recorded with a Brussels dealer \"by at least 1994\": fails the test. Its date also falls after the end of Nok as the Frankfurt project now dates it",
"fail",
"",
"",
"Taught in F1.24 beside the Nok looting finding",
"F1.6",
"Excluded as an exemplar; taught in F1.24 beside the looting finding",
"DD1",
""
],
[
"WS-X05",
"object",
"excluded",
"The Belitung cargo",
"About 830",
"Asian Civilisations Museum",
"",
"To check",
"Asian Civilisations Museum, Singapore",
"Commercially salvaged",
"n/a",
"",
"",
"Commercial salvage; taught in F1.24",
"F1.13",
"Excluded as an exemplar; taught in F1.24 as a case about salvage",
"DD2",
""
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
