insert into public.f1_source_routes ("id", "name", "type", "covers_worlds", "covers_sub_regions", "access", "cost", "licence_content", "licence_metadata", "commercial_safe", "what_it_fills", "known_limits", "verified", "verification_url", "notes")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14)
from jsonb_array_elements($cwb$[
[
"SRC001",
"Cleveland Museum of Art Open Access",
"museum-api",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web collection + Open Access API (no key) + GitHub data dump",
"free",
"CC0 for public-domain works (in-copyright works excluded)",
"CC0",
"yes",
"High-res images and data across world collections (Egypt, Andes, Islamic textiles, East and South Asia, Africa)",
"In-copyright and some loan objects not CC0",
"yes 2026-09-28",
"https://www.clevelandart.org/open-access",
"Page states 'No key or token is required'; 61,000+ CC0 records via API. Also on Sketchfab CC0 programme."
],
[
"SRC002",
"The Met Open Access",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web collection (OA filter) + CSV on GitHub; public Collection API",
"free",
"CC0 for Open Access (public-domain) images",
"CC0",
"yes",
"400,000+ PD images; strongest single source for many worlds",
"Only works the Met believes PD; restricted images link out",
"yes 2026-09-28",
"https://www.metmuseum.org/policies/image-resources",
"Page says 406,000+ OA images; collection data CC0 'including commercial'. Collection API existence not checked on this page."
],
[
"SRC003",
"Art Institute of Chicago API",
"museum-api",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"REST API (no authentication) + IIIF images",
"free-limited (60 requests/min anonymous; higher on request)",
"Use only artworks tagged public domain (CC0 designation)",
"CC0 except 'description' field = CC BY 4.0",
"yes",
"PD images and structured data incl. textiles, Asian and Indigenous American collections",
"Attribute CC BY descriptions; copyrighted images excluded",
"yes 2026-09-28",
"https://api.artic.edu/docs/",
"Add AIC-User-Agent header as courtesy."
],
[
"SRC004",
"Smithsonian Open Access",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web portal + bulk data + 3D",
"free",
"CC0 where designated",
"CC0",
"yes",
"Millions of CC0 assets across 20+ Smithsonian units (NMAfA, Freer/Sackler, NMNH Anthropology, Cooper Hewitt, NMAH)",
"Only items marked CC0; third-party/privacy rights may still apply",
"yes 2026-09-28",
"https://www.si.edu/openaccess/faq",
"FAQ: CC0 'for commercial purposes without any attribution, permission, or fee'. Check NMAI/NMNH items for CARE sensitivity before display."
],
[
"SRC005",
"Smithsonian Open Access API (via api.data.gov)",
"museum-api",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"REST API; key issued through api.data.gov",
"free-with-key",
"CC0 where designated",
"CC0",
"yes",
"Programmatic search and harvest of Smithsonian CC0 records",
"Rate limit not stated in FAQ; api.data.gov default limits not checked",
"partial 2026-09-28",
"https://www.si.edu/openaccess/faq",
"Docs at edan.si.edu/openaccess/apidocs (not fetched)."
],
[
"SRC006",
"Smithsonian 3D Digitization (3d.si.edu)",
"3d",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Voyager viewer; downloads glTF/glb/obj for CC0 models",
"free",
"CC0 only where the model is marked CC0; others view-only",
"CC0 (Open Access records)",
"per-item",
"Downloadable 3D models of objects and sites for the web app",
"Many models not CC0: embed/view only",
"yes 2026-09-28",
"https://3d.si.edu/collections/openaccesshighlights",
"Page: 'If you see CC0 by a 3D model, it is yours to take and remix'. Formats per si.edu OA FAQ."
],
[
"SRC007",
"Cooper Hewitt collection data and API",
"museum-api",
"F1.11;F1.8;F1.7;THEME",
"GL",
"GitHub dataset + API",
"free",
"Images NOT covered by dataset licence (many images CC0 via Smithsonian Open Access)",
"CC0",
"per-item",
"Design/decorative-arts metadata; 19th-21st c. design, textiles, wallcoverings",
"Check each image in Smithsonian OA for CC0",
"yes 2026-09-28",
"https://github.com/cooperhewitt/collection",
"README: 'images are not included... not covered by the same license'."
],
[
"SRC008",
"National Gallery of Art (US) Open Access",
"museum-open-access",
"F1.11;F1.7;THEME",
"GL",
"Web + GitHub CSV (daily)",
"free",
"CC0 for open-access images",
"CC0",
"yes",
"European/American painting, prints, drawings; object data",
"Gallery can convey only its own rights",
"yes 2026-09-28",
"https://www.nga.gov/artworks/free-images-and-open-access",
"'free of charge for any use, whether commercial or non-commercial'."
],
[
"SRC009",
"Walters Art Museum",
"museum-open-access",
"F1.6;F1.8;F1.9;F1.10;F1.11",
"GL",
"Online collection + API",
"free",
"CC0 for works believed PD",
"unverified",
"yes",
"Manuscripts (Ethiopian, Islamic, Armenian, European), ancient and Asian art",
"Loans/copyright works excluded; credit requested",
"yes 2026-09-28",
"https://thewalters.org/about/policies/rights-reproductions/",
"Credit 'The Walters Art Museum' requested."
],
[
"SRC010",
"OPenn (Penn Libraries; hosts Walters legacy and partner manuscripts)",
"manuscript-library",
"F1.10;F1.11;F1.9;F1.6",
"GL",
"Direct file download (TIFF/JPEG + TEI)",
"free",
"'All materials on OPenn are in the public domain or released under Creative Commons licenses as Free Cultural Works'",
"per-item (see each repository page)",
"per-item",
"Complete manuscript image sets (Islamic, Ethiopic, Indic, European)",
"Check each repository's CC variant (BY vs BY-SA)",
"partial 2026-09-28",
"https://openn.library.upenn.edu/",
"Free Cultural Works = commercial allowed, but SA may apply."
],
[
"SRC011",
"Yale Center for British Art Open Access",
"museum-open-access",
"F1.11;F1.19",
"GL",
"Web collection downloads",
"free",
"Public-domain images free 'without further application, authorization, or fees' (Yale Open Access Policy)",
"unverified (see YCBA Open Data terms page)",
"yes",
"British art, prints, rare books on industry, empire and trade",
"In-copyright works need permission",
"yes 2026-09-28",
"https://britishart.yale.edu/using-images",
"Commercial use not explicitly mentioned; PD status implies it."
],
[
"SRC012",
"Yale University Art Gallery / Yale LUX",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"LUX cross-collection search",
"free",
"unverified",
"unverified",
"per-item",
"Yale art, natural history and library holdings in one search",
"Not checked",
"unverified",
"",
""
],
[
"SRC013",
"Getty Museum Open Content Program",
"museum-open-access",
"F1.11;F1.9a;F1.10",
"GL",
"Collection website downloads",
"free",
"CC0",
"unverified",
"yes",
"Antiquities, manuscripts, photographs, European decorative arts",
"Must not imply Getty endorsement",
"yes 2026-09-28",
"https://www.getty.edu/projects/open-content-program/faqs/",
"Suggested credit 'Digital image courtesy of Getty's Open Content Program'."
],
[
"SRC014",
"LACMA Collections Online (Public Domain High Resolution)",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web downloads",
"free",
"PD images 'free of charge and for use without restriction'",
"unverified",
"yes",
"Islamic, Latin American, Korean, Japanese, costume and textiles",
"User must clear third-party/privacy rights",
"yes 2026-09-28",
"https://www.lacma.org/about/contact-us/terms-use",
""
],
[
"SRC015",
"Princeton University Art Museum",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + IIIF",
"free",
"PD images: 'No approval required'",
"unverified",
"yes",
"Mesoamerican, Chinese, ancient Mediterranean",
"Credit line required",
"yes 2026-09-28",
"https://artmuseum.princeton.edu/art/image-use-and-access",
""
],
[
"SRC016",
"Brooklyn Museum Open Collection",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API (key)",
"unverified",
"unverified",
"unverified",
"per-item",
"Egypt, Africa, Americas, decorative arts",
"Not checked",
"unverified",
"",
""
],
[
"SRC017",
"Minneapolis Institute of Art (Mia)",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + GitHub data",
"free",
"PD works marked CC PDM; commercial use without permission",
"unverified",
"yes",
"Chinese, African, Native American, textiles",
"Only PDM-marked works",
"yes 2026-09-28",
"https://new.artsmia.org/copyright-and-image-access",
""
],
[
"SRC018",
"Harvard Art Museums (web + API)",
"museum-api",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"API requires key on request",
"free-with-key (cost not stated on page)",
"Downloads for personal, non-commercial use only",
"unverified",
"no",
"Object data for teaching; link-out images",
"Images non-commercial; link out only",
"partial 2026-09-28",
"https://harvardartmuseums.org/licensing",
"API page: every request needs apikey."
],
[
"SRC019",
"Library of Congress loc.gov JSON API",
"museum-api",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"JSON API over all loc.gov collections",
"free",
"per-item rights advisories",
"U.S. Government Work (guide text)",
"per-item",
"Programmatic access to LoC collections incl. maps, prints, newspapers",
"Per-item rights; bulk OCR throttled",
"partial 2026-09-28",
"https://guides.loc.gov/chronicling-america/additional-features",
"'no API key or authentication required'."
],
[
"SRC020",
"Library of Congress Prints & Photographs Online Catalog",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web catalogue",
"free",
"per-item ('No known restrictions' on many)",
"unverified",
"per-item",
"Photographs of workshops, industry, architecture, world fairs",
"Check each rights advisory",
"unverified",
"",
""
],
[
"SRC021",
"Chronicling America (LoC)",
"text-library",
"F1.7;F1.19;F1.21",
"AM-EWD;AM-WST;AM-LAT",
"Web portal/collection (see verification_url or site)",
"free-limited (no key; bulk OCR 10 requests per 10 min per IP)",
"not stated on guide page",
"U.S. Government Work (guide)",
"per-item",
"US newspapers for advertising, industry, exhibitions",
"Rights of papers not stated on checked page",
"partial 2026-09-28",
"https://guides.loc.gov/chronicling-america/additional-features",
""
],
[
"SRC022",
"National Jukebox (LoC)",
"audio",
"F1.4;THEME",
"AM-EWD;GL",
"Streaming under rightsholder permission",
"free",
"Pre-1923 recordings PD since 1 Jan 2022 (Music Modernization Act); 1923-1956 recordings still protected; labels >95 yrs PD",
"unverified",
"per-item",
"Early sound recordings for F1.4 (sound, performance)",
"Most post-1922 tracks: embed/link only",
"yes 2026-09-28",
"https://www.loc.gov/collections/national-jukebox/about-this-collection/rights-and-access/",
"'You will need written permission from the rightsholders' for copyrighted items."
],
[
"SRC023",
"World Digital Library (now at Library of Congress)",
"manuscript-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"loc.gov collection",
"free",
"'Absent any such restrictions, these materials are free to use and reuse'; per-item partner restrictions",
"unverified",
"per-item",
"Manuscripts, maps and books from partner libraries worldwide (e.g. Florentine Codex facsimile)",
"Check partner source info per item",
"yes 2026-09-28",
"https://www.loc.gov/collections/world-digital-library/about-this-collection/rights-and-access/",
"Credit '[source], World Digital Library'."
],
[
"SRC024",
"US National Archives Catalog",
"image-commons",
"F1.7;F1.19;F1.19a",
"GL",
"Web + API",
"unverified",
"Federal records generally PD (not re-verified)",
"unverified",
"per-item",
"Patent drawings, WPA craft, industry photography",
"Not checked",
"unverified",
"",
""
],
[
"SRC025",
"NYPL Digital Collections (public domain)",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API (api.repo.nypl.org)",
"free",
"PD items: 'No permission required. No restrictions on use.'",
"unverified",
"yes",
"Prints, photographs, maps, menus, trade catalogues",
"Only PD-flagged items",
"yes 2026-09-28",
"https://www.nypl.org/research/resources/public-domain-collections",
"180,000+ PD items."
],
[
"SRC026",
"Internet Archive (texts)",
"text-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API; download",
"free",
"per-item (uploader-stated); many PD scans; some lending-only copies",
"unverified",
"per-item",
"PD translations and treatises (Digital Library of India scans, university scans)",
"Lending-only items are in copyright; verify each",
"unverified",
"",
"Examples found: Hoover's Agricola, Hendrie's Theophilus, Acharya's Manasara (DLI scan)."
],
[
"SRC027",
"Prelinger Archives (Internet Archive)",
"film-video",
"F1.19;F1.21;F1.4;THEME",
"AM-EWD;GL",
"Download from archive.org",
"free",
"Per-film CC licence where shown; derivatives may be sold 'without any limitations'",
"Descriptions/metadata © Prelinger & Getty Images, no commercial reproduction",
"per-item",
"Industrial, advertising, educational films (making, factories, consumer society)",
"Do not copy descriptions commercially",
"yes 2026-09-28",
"https://help.archive.org/help/prelinger-archive/",
"Attribution appreciated not required."
],
[
"SRC028",
"HathiTrust full view",
"text-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web reader + downloads",
"free",
"Rights codes: pd = world; pdus = US IPs only (1899-1929 non-US works); CC variants incl. NC/ND",
"unverified",
"per-item",
"19th-early 20th c. scholarship, catalogues, journals",
"pdus blocked outside US; NC/ND items link out",
"yes 2026-09-28",
"https://www.hathitrust.org/the-collection/preservation/rights-database/",
""
],
[
"SRC029",
"Project Gutenberg",
"text-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web download",
"free",
"US public domain texts; PG trademark terms apply to branded files (not re-verified)",
"unverified",
"yes",
"Clean PD texts (e.g. Agricola De re metallica 1912 = ebook 38015)",
"US-centric PD judgements",
"unverified",
"",
""
],
[
"SRC030",
"Wikisource",
"text-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"free",
"PD source texts; transcriptions CC BY-SA (not re-verified)",
"unverified",
"yes",
"Transcribed PD translations (e.g. De re metallica 1912)",
"Quality varies",
"unverified",
"",
""
],
[
"SRC031",
"Wikimedia Commons",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API",
"free",
"Only free licences (CC0, PD, CC BY, CC BY-SA...); NC and ND not accepted",
"CC0 structured data (not re-verified)",
"yes",
"Largest pool of reusable images incl. museum batch uploads",
"Per-file attribution/share-alike; some files mis-licensed",
"yes 2026-09-28",
"https://commons.wikimedia.org/wiki/Commons:Licensing",
"Commons forbids -NC and -ND licences."
],
[
"SRC032",
"Wikidata",
"dataset",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"SPARQL + API + dumps",
"free",
"n/a",
"CC0",
"yes",
"Identifiers, dates, places for Atlas nodes; links to PeriodO, Getty, museums",
"Data quality varies",
"yes 2026-09-28",
"https://www.wikidata.org/wiki/Wikidata:Licensing",
""
],
[
"SRC033",
"Wikipedia (text)",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API",
"free",
"CC BY-SA 4.0 (not re-verified today)",
"n/a",
"yes",
"Background text (quote with attribution, share-alike)",
"Share-alike applies to adapted text",
"unverified",
"",
""
],
[
"SRC034",
"Openverse",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Search engine for CC/PD media",
"free",
"per-item",
"unverified",
"per-item",
"Finding CC0/CC BY images outside museums",
"Licence signals come from source",
"unverified",
"",
""
],
[
"SRC035",
"Digital Public Library of America (DPLA)",
"aggregator",
"F1.7;F1.11;F1.19",
"AM-EWD;AM-WST",
"Web portal/collection (see verification_url or site)",
"unverified",
"per-item",
"CC0 (not re-verified)",
"per-item",
"US libraries and archives aggregated",
"Not checked",
"unverified",
"",
""
],
[
"SRC036",
"Flickr Commons",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"free",
"'No known copyright restrictions' (institution-asserted)",
"unverified",
"per-item",
"Institutional photo archives",
"Not checked",
"unverified",
"",
""
],
[
"SRC037",
"The Public Domain Review",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web essays and curated links",
"free",
"Essays copyrighted (not re-verified); links to PD sources",
"unverified",
"no",
"Discovery of PD images and texts",
"Link out to originals",
"unverified",
"",
""
],
[
"SRC038",
"Rijksmuseum Data Services",
"museum-api",
"F1.11;F1.9;F1.8;F1.13",
"GL",
"Data services / collection online",
"free",
"PDM and/or CC0; rarely CC BY 4.0; third-party-copyright items not released",
"CC0 (policy)",
"yes",
"Dutch art, VOC trade goods, Asian export wares, Indonesian collections",
"Colonial-era material needs provenance note",
"yes 2026-09-28",
"https://data.rijksmuseum.nl/policy/information-and-data-policy",
"'All users, including commercial parties... same conditions'. API key requirement not stated."
],
[
"SRC039",
"Europeana (portal + Search API)",
"aggregator",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Portal + APIs (free key)",
"free-with-key",
"per-item rights statements; reusability=open returns PDM, CC0, CC BY, CC BY-SA",
"CC0 (not re-verified today)",
"per-item",
"Millions of European and colonial-collection items; filter to open reuse",
"Per-item; NC/in-copyright items link out",
"yes 2026-09-28",
"https://europeana.atlassian.net/wiki/spaces/EF/pages/2360508417/Europeana+API+FAQ",
"FAQ: read APIs 'free of charge', 'without any throttling or limiting'."
],
[
"SRC040",
"Europeana 3D",
"3d",
"F1.11",
"GL",
"Via Europeana portal/API",
"free-with-key",
"Per-item rights statements; guide recommends most restrictive where object and model differ; CC0 for waived rights",
"CC0 (not re-verified)",
"per-item",
"3D heritage models from European partners",
"Mixed rights",
"yes 2026-09-28",
"https://europeana.atlassian.net/wiki/spaces/EF/pages/2365227031/Publishing+guide+for+3D+content",
""
],
[
"SRC041",
"SMK Open (National Gallery of Denmark)",
"museum-api",
"F1.11",
"GL",
"Open API",
"free",
"PD artworks: data 'including photos, can be used freely'",
"free (not further specified)",
"yes",
"Danish/European art incl. Danish West Indies material",
"Check public_domain flag",
"yes 2026-09-28",
"https://www.smk.dk/en/article/smk-api/",
"No API key mentioned."
],
[
"SRC042",
"Paris Musées Collections (Open Content)",
"museum-api",
"F1.11",
"GL",
"Web + API (apicollections.parismusees.paris.fr)",
"free",
"CC0 for PD 2D works; HD 300 dpi/3000 px",
"unverified",
"yes",
"Paris museums incl. Musée Cernuschi (Asian art), Carnavalet, Galliera fashion",
"Good Practice Charter: cite source",
"yes 2026-09-28",
"https://www.parismusees.paris.fr/en/news/open-content-150000-works-from-the-museum-collections-of-the-city-of-paris-freely-available",
""
],
[
"SRC043",
"Nationalmuseum Sweden",
"museum-open-access",
"F1.11",
"GL",
"Web + Wikimedia Commons (3,000 images)",
"free",
"PD Mark for out-of-copyright works; CC BY-SA for in-copyright photography",
"unverified",
"yes",
"Swedish design, applied arts, porcelain",
"Preserve PD marks",
"yes 2026-09-28",
"https://www.nationalmuseum.se/en/explore-art-and-design/images/rights-and-reproductions",
""
],
[
"SRC044",
"Finnish National Gallery",
"museum-open-access",
"F1.11",
"GL",
"Web collection",
"free",
"CC0 (per Europeana announcement title; page redirected to archive)",
"unverified",
"yes",
"Finnish art and design",
"Page not fully read",
"partial 2026-09-28",
"https://pro.europeana.eu/post/hello-cc0-the-finnish-national-gallery-opens-up-its-collections",
""
],
[
"SRC045",
"Finna (Finland)",
"aggregator",
"F1.11",
"EU-SCA",
"Web portal/collection (see verification_url or site)",
"free",
"per-item",
"unverified",
"per-item",
"Finnish archives, libraries and museums incl. Sámi material",
"Not checked; Sámi sensitivity",
"unverified",
"",
""
],
[
"SRC046",
"DigitaltMuseum (Norway/Sweden)",
"aggregator",
"F1.11",
"EU-SCA",
"Web portal/collection (see verification_url or site)",
"free",
"Per-object licences set by each museum",
"unverified",
"per-item",
"Nordic material culture, Sámi duodji, industrial heritage",
"Institutions responsible for rights; check each object",
"partial 2026-09-28",
"https://dok.digitaltmuseum.org/en/about",
"Licence field per object not checked."
],
[
"SRC047",
"V&A Explore the Collections",
"museum-open-access",
"F1.11;F1.9;F1.10;F1.8;F1.19",
"GL",
"Web + API",
"free",
"Non-commercial only; max 768 px digital; ≤25% of project; must use V&A-served image URL, not host copies",
"unverified",
"no",
"Textiles, ceramics, South Asian and Islamic design, Great Exhibition material",
"LINK OUT / hotlink only; no hosting",
"yes 2026-09-28",
"https://www.vam.ac.uk/info/va-websites-terms-conditions/",
"Credit '© Victoria and Albert Museum, London'."
],
[
"SRC048",
"British Museum Collection Online",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web collection",
"free",
"CC BY-NC-SA 4.0",
"unverified",
"no",
"Very broad world coverage",
"Non-commercial; textbooks and commercial sites excluded",
"yes 2026-09-28",
"https://www.britishmuseum.org/terms-use/copyright-and-permissions",
"Link out if app ever charges."
],
[
"SRC049",
"British Museum on Sketchfab",
"3d",
"F1.6;F1.9a;F1.12",
"GL",
"Sketchfab viewer/download",
"free",
"CC BY-NC-SA 4.0 (Rosetta Stone model checked)",
"n/a",
"no",
"3D objects (tablets, Hoa Hakananai'a scan by SDCELAR)",
"Embed/link only for commercial product; Hoa Hakananai'a is ancestral (Rapa Nui)",
"yes 2026-09-28",
"https://sketchfab.com/3d-models/the-rosetta-stone-1e03509704a3490e99a173e53b93e282",
"BM terms also bar selling 3D prints."
],
[
"SRC050",
"British Library public-domain images (Flickr Commons 'Mechanical Curator')",
"image-commons",
"F1.11;F1.9;F1.13",
"GL",
"Flickr",
"free",
"Public domain (1m+ images from 17th-19th c. books)",
"unverified",
"yes",
"Book illustrations of trades, machines, ornament, travel",
"Captions auto-generated",
"partial 2026-09-28",
"https://www.libraryjournal.com/story/british-library-adds-1-million-public-domain-images-taken-from-17th-18th-and-19th-century-books-to-flickr-commons",
"Secondary source."
],
[
"SRC051",
"British Library Digitised Manuscripts",
"manuscript-library",
"F1.10;F1.11;F1.9;F1.8",
"GL",
"Web viewer + IIIF",
"unverified",
"unverified",
"unverified",
"per-item",
"Illuminated and Asian/Islamic manuscripts",
"Not checked",
"unverified",
"",
""
],
[
"SRC052",
"Wellcome Collection",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + IIIF + API",
"free",
"Per-item: PDM, CC BY, CC BY-NC",
"unverified",
"per-item",
"Medicine, pharmacy, alchemy, Asian and African manuscripts",
"Filter to PDM/CC BY",
"yes 2026-09-28",
"https://wellcomecollection.org/collections/accessing-our-collections",
""
],
[
"SRC053",
"Digital Bodleian",
"manuscript-library",
"F1.7;F1.10;F1.11;F1.9",
"GL",
"Web + IIIF",
"free",
"Mostly CC BY-NC 4.0; commercial needs permission and payment",
"unverified",
"no",
"Codex Mendoza, Islamic and South Asian manuscripts",
"Link out for commercial product",
"yes 2026-09-28",
"https://digital.bodleian.ox.ac.uk/terms/",
""
],
[
"SRC054",
"e-codices (Virtual Manuscript Library of Switzerland)",
"manuscript-library",
"F1.11",
"GL",
"Web + IIIF",
"free",
"Per-library: PDM items commercial OK; others CC BY-NC 3.0",
"unverified",
"per-item",
"Medieval manuscripts incl. St Gall plan-related material",
"Check each manuscript",
"yes 2026-09-28",
"https://www.e-codices.ch/en/about/terms",
""
],
[
"SRC055",
"Gallica (BnF)",
"text-library",
"F1.11;F1.10;F1.8;F1.6",
"GL",
"Web + IIIF + APIs",
"free",
"Non-commercial reuse free with source credit; COMMERCIAL reuse is paid and needs a licence",
"unverified",
"no",
"French treatises, Encyclopédie, Boileau, Villard, Jikji, colonial photography",
"Paid licence if app charges",
"yes 2026-09-28",
"https://gallica.bnf.fr/accueil/fr/html/conditions-dutilisation-de-gallica",
"'La réutilisation commerciale de ces contenus est payante'."
],
[
"SRC056",
"Science Museum Group Collection",
"museum-api",
"F1.19;F1.11;THEME",
"GL",
"Web + collection API",
"free",
"Images CC BY-NC-SA 4.0",
"CC0 (collection metadata)",
"no",
"Industry, machines, instruments",
"Images NC; metadata usable",
"yes 2026-09-28",
"https://www.sciencemuseumgroup.org.uk/creative-commons",
""
],
[
"SRC057",
"Tropenmuseum / Wereldmuseum images on Wikimedia Commons",
"image-commons",
"F1.9;F1.6;F1.7;F1.12",
"AS-ISE;AS-MSE;AF-GUI;AM-CAR",
"Web portal/collection (see verification_url or site)",
"free",
"KIT-license template = CC BY-SA 3.0 Unported (51,506 files)",
"unverified",
"yes",
"Colonial-era photographs and objects from Indonesia, Suriname, Africa",
"Colonial gaze; many images need content notes; share-alike",
"yes 2026-09-28",
"https://commons.wikimedia.org/wiki/Template:KIT-license",
"Count from Commons:Tropenmuseum."
],
[
"SRC058",
"Scan the World (MyMiniFactory)",
"3d",
"F1.11",
"GL",
"Download STL",
"free-with-registration (not re-verified)",
"Per-model; many CC0; some non-commercial",
"unverified",
"per-item",
"3D-printable sculpture and objects",
"Check each licence",
"yes 2026-09-28",
"https://www.myminifactory.com/scantheworld/faq/",
""
],
[
"SRC059",
"Sketchfab CC0 cultural heritage models",
"3d",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Sketchfab download",
"free-with-registration (not re-verified)",
"CC0 on items so marked (27 organisations at 2020 launch incl. Smithsonian, CMA, SMK, Science Museum Group)",
"n/a",
"per-item",
"Downloadable 3D heritage",
"Filter to CC0; other Sketchfab licences vary",
"yes 2026-09-28",
"https://sketchfab.com/blogs/community/sketchfab-launches-public-domain-dedication-for-3d-cultural-heritage/",
""
],
[
"SRC060",
"Pitt Rivers Museum Collections Online",
"museum-open-access",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web collection",
"free",
"Non-commercial educational and community use; commercial needs permission",
"unverified",
"no",
"Ethnographic collections worldwide",
"Sensitive/ancestral material; human remains policy",
"yes 2026-09-28",
"https://www.prm.ox.ac.uk/collections-online-terms-and-conditions",
"Credit '© Pitt Rivers Museum, University of Oxford'."
],
[
"SRC061",
"Horniman Museum",
"museum-open-access",
"F1.6;F1.4",
"GL",
"Web collection",
"unverified",
"unverified",
"unverified",
"per-item",
"Musical instruments, African collections",
"Not checked",
"unverified",
"",
""
],
[
"SRC062",
"Musée du quai Branly - Jacques Chirac",
"museum-open-access",
"F1.6;F1.7;F1.12;F1.9",
"GL",
"Web collection",
"unverified",
"unverified",
"unverified",
"no",
"African, Oceanic, American, Asian collections",
"Not checked; assume link out",
"unverified",
"",
""
],
[
"SRC063",
"Weltmuseum Wien online collection",
"museum-open-access",
"F1.7;F1.12;F1.6;F1.8",
"GL",
"Web collection",
"unverified",
"unverified",
"unverified",
"no",
"Feather work, Pacific, Benin",
"Not checked; assume link out",
"unverified",
"",
""
],
[
"SRC064",
"State Hermitage Museum",
"museum-open-access",
"F1.11;F1.12a;F1.10;F1.8",
"AS-CEN;EU-EER",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified (image-use page could not be retrieved)",
"unverified",
"no",
"Scythian gold, Pazyryk textiles, Sogdian silver",
"Treat as permission-only / link out until verified",
"unverified",
"https://www.hermitagemuseum.org/wps/portal/hermitage/about/image_usage_policy",
"Fetch blocked (robots/SSL)."
],
[
"SRC065",
"Staatliche Museen zu Berlin (SMB-digital)",
"museum-open-access",
"F1.6;F1.9a;F1.11;F1.10",
"GL",
"Web collection",
"unverified",
"unverified",
"unverified",
"per-item",
"Pergamon, Ethnologisches Museum",
"Not checked",
"unverified",
"",
""
],
[
"SRC066",
"Heidelberg University Library digital collections",
"manuscript-library",
"F1.11;F1.6",
"GL",
"Web + IIIF",
"unverified",
"unverified",
"unverified",
"per-item",
"Medieval treatises; Egyptological papyri",
"Not checked",
"unverified",
"",
""
],
[
"SRC067",
"Vatican Library (DigiVatLib)",
"manuscript-library",
"F1.11;F1.10;F1.7",
"GL",
"Web + IIIF",
"unverified",
"unverified",
"unverified",
"no",
"Codex Borgia, Vaticanus manuscripts",
"Not checked; assume link out",
"unverified",
"",
""
],
[
"SRC068",
"Cambridge Digital Library",
"manuscript-library",
"F1.10;F1.11;F1.13",
"GL",
"Web + IIIF",
"unverified",
"unverified",
"unverified",
"per-item",
"Cairo Genizah fragments, Islamic manuscripts",
"Not checked",
"unverified",
"",
""
],
[
"SRC069",
"Biblioteca Digital Hispánica (BNE)",
"text-library",
"F1.11;F1.7",
"EU-IBE;AM-LAT",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Spanish and colonial American books and manuscripts",
"Not checked",
"unverified",
"",
""
],
[
"SRC070",
"Chester Beatty digital collections",
"manuscript-library",
"F1.10;F1.8;F1.9",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"per-item",
"Islamic, East Asian manuscripts",
"Not checked",
"unverified",
"",
""
],
[
"SRC071",
"Te Papa Collections Online",
"museum-api",
"F1.12",
"OC-POL;OC-MEL;OC-MIC",
"Web portal/collection (see verification_url or site)",
"free",
"Per-item: Creative Commons (some CC BY-NC-ND), No Known Copyright Restrictions, All Rights Reserved",
"unverified",
"per-item",
"Aotearoa and Pacific collections",
"Taonga Māori images: research, study, personal and educational use only",
"yes 2026-09-28",
"https://www.tepapa.govt.nz/about-collections-online",
"Do not host taonga images even if technically downloadable."
],
[
"SRC072",
"Auckland War Memorial Museum Collections Online",
"museum-api",
"F1.12",
"OC-POL;OC-MEL",
"Web portal/collection (see verification_url or site)",
"free",
"CC BY 4.0 or No Known Copyright Restrictions for reusable images",
"unverified",
"per-item",
"NZ and Pacific material; war and social history",
"Māori and Pacific objects: personal research/private study only",
"yes 2026-09-28",
"https://www.aucklandmuseum.com/discover/collections/using-our-images",
"API at api.aucklandmuseum.com (not checked)."
],
[
"SRC073",
"DigitalNZ",
"aggregator",
"F1.12",
"OC-POL",
"Web portal/collection (see verification_url or site)",
"free",
"Per-item; filters: All rights reserved / Share / Modify / Use commercially / Unknown",
"unverified",
"per-item",
"NZ aggregator of 200+ partners",
"Rights shown from partner, may be out of date",
"partial 2026-09-28",
"https://digitalnz.org/help/reusing-items-on-digitalnz-and-copyright",
"API key terms not checked."
],
[
"SRC074",
"Trove (National Library of Australia)",
"aggregator",
"F1.12",
"OC-AUS;OC-MEL",
"Web portal/collection (see verification_url or site)",
"free-with-key (API key; 2020 terms enforced from April 2025; content download needs exemption)",
"per-item",
"unverified",
"per-item",
"Australian newspapers, images, archives",
"API terms restrict harvesting full content",
"partial 2026-09-28",
"https://updates.timsherratt.org/2025/04/11/update-on-trove-data-access.html",
"Trove terms page returned access denied."
],
[
"SRC075",
"Australian Museum",
"museum-open-access",
"F1.12",
"OC-AUS;OC-MEL",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Pacific and First Nations collections",
"Not checked; high sensitivity",
"unverified",
"",
""
],
[
"SRC076",
"Powerhouse (MAAS) Collection API",
"museum-api",
"F1.12;F1.19;THEME",
"OC-AUS",
"Web portal/collection (see verification_url or site)",
"free",
"Images: unverified",
"Creative Commons Attribution (Data.NSW listing)",
"per-item",
"Applied arts, design, technology",
"Old API superseded by MAAS public API",
"partial 2026-09-28",
"https://data.nsw.gov.au/data/dataset/powerhouse-museum-collection-api",
""
],
[
"SRC077",
"State Library of New South Wales",
"text-library",
"F1.12",
"OC-AUS",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Colonial Australian archives and images",
"Not checked",
"unverified",
"",
""
],
[
"SRC078",
"National Museum of Australia Collection API",
"museum-api",
"F1.12",
"OC-AUS",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Australian material culture",
"Terms page exists (not read)",
"unverified",
"",
""
],
[
"SRC079",
"NZ Electronic Text Collection (NZETC)",
"text-library",
"F1.12",
"OC-POL",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"PD NZ texts (e.g. Elsdon Best monographs)",
"Not checked",
"unverified",
"",
""
],
[
"SRC080",
"Te Ara Encyclopedia of New Zealand",
"open-literature",
"F1.12",
"OC-POL",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Authoritative NZ background incl. Māori arts",
"Not checked",
"unverified",
"",
""
],
[
"SRC081",
"National Palace Museum (Taipei) Open Data",
"museum-open-access",
"F1.8",
"AS-CHN",
"Web portal/collection (see verification_url or site)",
"free",
"Open Government Data License v1.0 and CC BY 4.0; attribution to NPM",
"unverified",
"yes",
"Chinese imperial collections (bronzes, ceramics, painting, jade)",
"Image size limits not stated",
"yes 2026-09-28",
"https://theme.npm.edu.tw/opendata/?lang=2",
"'users are not required to fill out an application'. OpenGLAM article: commercial reuse encouraged."
],
[
"SRC082",
"ColBase (National Institutes for Cultural Heritage, Japan)",
"museum-open-access",
"F1.8;F1.9",
"AS-JPN;AS-KOR;AS-CHN",
"Web portal/collection (see verification_url or site)",
"free",
"Conforms to Government of Japan Standard Terms of Use v2.0; commercial use permitted; cite source",
"unverified",
"yes",
"Tokyo, Kyoto, Nara, Kyushu National Museums",
"Some third-party items excluded",
"yes 2026-09-28",
"https://colbase.nich.go.jp/pages/term?locale=en",
"Credit format: 'Source: ColBase (URL)'."
],
[
"SRC083",
"National Museum of Korea e-museum",
"museum-open-access",
"F1.8",
"AS-KOR",
"Web portal/collection (see verification_url or site)",
"free",
"Mixed: 2010 release was non-commercial only; items explicitly marked KOGL Type 1 allow commercial use with attribution",
"unverified",
"per-item",
"Korean ceramics, metalwork, Goryeo printing",
"Use only items carrying KOGL Type 1 mark",
"partial 2026-09-28",
"https://www.museum.go.kr/site/eng/archive/united/8690",
"KOGL Type 1 confirmed on NMK file at Commons (File:Goryeosa, National Museum of Korea 01.jpg)."
],
[
"SRC084",
"KOGL Type 1 images on Wikimedia Commons (Korean public institutions)",
"image-commons",
"F1.8",
"AS-KOR",
"Web portal/collection (see verification_url or site)",
"free",
"KOGL Type 1: share and adapt, commercial or non-commercial, attribution",
"unverified",
"yes",
"Korean heritage images already cleared",
"Attribute source institution",
"yes 2026-09-28",
"https://commons.wikimedia.org/wiki/File:Goryeosa,_National_Museum_of_Korea_01.jpg",
""
],
[
"SRC085",
"Kyujanggak / Korean royal archives (Uigwe)",
"manuscript-library",
"F1.8",
"AS-KOR",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Uigwe royal protocol books",
"Not checked",
"unverified",
"",
""
],
[
"SRC086",
"Japan Search",
"aggregator",
"F1.8",
"AS-JPN",
"Web portal/collection (see verification_url or site)",
"free",
"Per-item secondary-use conditions displayed (commercial / non-commercial / attribution)",
"unverified",
"per-item",
"Cross-search of Japanese archives, museums, libraries",
"Per item",
"partial 2026-09-28",
"https://www.gov-online.go.jp/eng/publicity/book/hlj/html/202108/202108_09_en.html",
"API not confirmed from this page."
],
[
"SRC087",
"NDL Digital Collections (Japan)",
"text-library",
"F1.8",
"AS-JPN",
"Web portal/collection (see verification_url or site)",
"free",
"unverified (PD items widely reported as reusable)",
"unverified",
"per-item",
"Edo illustrated books, Meibutsu zue, Hokusai, Karakuri zui",
"Not checked directly",
"unverified",
"",
""
],
[
"SRC088",
"International Dunhuang Programme (IDP)",
"manuscript-library",
"F1.12a;F1.8;F1.13",
"AS-CEN;AS-CHN",
"Web portal/collection (see verification_url or site)",
"free",
"Default personal/non-commercial only; items marked Public Domain unrestricted; site text CC BY; partner institutions differ",
"unverified",
"per-item",
"Silk Road manuscripts, paintings, textiles",
"Commercial needs licence from holding institution",
"yes 2026-09-28",
"https://idp.bl.uk/copyright/",
""
],
[
"SRC089",
"Digital Silk Road Project (NII) - Toyo Bunko rare books",
"text-library",
"F1.12a;F1.13",
"AS-CEN",
"Web portal/collection (see verification_url or site)",
"free",
"unverified",
"unverified",
"per-item",
"Rare European travel books on Asia",
"Not checked",
"unverified",
"",
""
],
[
"SRC090",
"Chinese Text Project (ctext.org)",
"text-library",
"F1.8",
"AS-CHN",
"Web portal/collection (see verification_url or site)",
"free-limited (web reading; API via subscription)",
"Terms not retrieved; site warns against scraping",
"unverified",
"no",
"Kaogongji, Tiangong kaiwu texts and scans",
"Link out; do not scrape",
"partial 2026-09-28",
"https://ctext.org/faq/ens",
"Fetched page was anti-scraping notice."
],
[
"SRC091",
"CBETA (Buddhist canon)",
"text-library",
"F1.8;F1.9",
"AS-CHN;AS-SAS",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Buddhist texts on image-making and ritual objects",
"Not checked",
"unverified",
"",
""
],
[
"SRC092",
"Palace Museum Beijing digital collection",
"museum-open-access",
"F1.8",
"AS-CHN",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"no",
"Qing court objects",
"Not checked; assume link out",
"unverified",
"",
""
],
[
"SRC093",
"Indian Culture portal (Ministry of Culture)",
"aggregator",
"F1.9",
"AS-SAS;AS-HIM",
"Web portal/collection (see verification_url or site)",
"free (site says free 'but this policy may change in future')",
"Per content owner's licence; any use implying endorsement or for promotion/commercialisation is prohibited",
"unverified",
"no",
"Indian museum objects, manuscripts, rare books, archives",
"Treat as link out",
"yes 2026-09-28",
"https://www.indianculture.gov.in/terms-and-conditions",
""
],
[
"SRC094",
"Digital Library of India (scans on Internet Archive)",
"text-library",
"F1.9",
"AS-SAS",
"Web portal/collection (see verification_url or site)",
"free",
"per-item; copyright status often unclear",
"unverified",
"per-item",
"Indian-printed scholarship, Shastra translations",
"Many scans are in copyright in India",
"unverified",
"",
"Acharya's Manasara volumes found as in.ernet.dli.2015.* items."
],
[
"SRC095",
"GRETIL / SARIT (Sanskrit e-texts)",
"text-library",
"F1.9",
"AS-SAS",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Sanskrit originals of Shilpa/Vastu texts",
"Not checked",
"unverified",
"",
""
],
[
"SRC096",
"South Asia Open Archives (JSTOR)",
"text-library",
"F1.9",
"AS-SAS",
"Web portal/collection (see verification_url or site)",
"free (not re-verified)",
"unverified",
"unverified",
"per-item",
"South Asian periodicals, reports",
"Not checked",
"unverified",
"",
""
],
[
"SRC097",
"Qatar Digital Library",
"manuscript-library",
"F1.10;F1.13;F1.9a",
"WA-ARB;WA-IRN;WA-MES",
"Web portal/collection (see verification_url or site)",
"free",
"Public Domain, Creative Commons, or OGL (Crown copyright) per item; COMMERCIAL use needs prior informed consent",
"unverified",
"no",
"Gulf archives (India Office Records), Arabic science manuscripts",
"Commercial consent required even for PD items",
"yes 2026-09-28",
"https://www.qdl.qa/en/copyright-ethical-terms-reuse",
""
],
[
"SRC098",
"Archnet (Aga Khan Documentation Center, MIT)",
"image-commons",
"F1.10;F1.9;F1.6",
"WA-ARB;WA-IRN;AF-MAG;AF-SAH;AS-SAS",
"Web portal/collection (see verification_url or site)",
"free",
"Image terms not found; MIT Libraries' own content CC BY-NC",
"unverified",
"no",
"Islamic architecture images, drawings, Aga Khan Award files",
"Link out until per-item terms verified",
"partial 2026-09-28",
"https://libraries.mit.edu/akdc/archnet/archnet-guide-faq/",
""
],
[
"SRC099",
"Digital Library of the Middle East (DLME)",
"aggregator",
"F1.10;F1.9a",
"GL",
"Web portal/collection (see verification_url or site)",
"unverified",
"per-item",
"unverified",
"per-item",
"Aggregated Middle East collections",
"Not checked",
"unverified",
"",
""
],
[
"SRC100",
"Cuneiform Digital Library Initiative (CDLI)",
"dataset",
"F1.9a",
"WA-MES;WA-IRN;WA-ANA",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Tablet images and transliterations",
"Not checked",
"unverified",
"",
""
],
[
"SRC101",
"Oracc (incl. State Archives of Assyria Online)",
"text-library",
"F1.9a",
"WA-MES",
"Web portal/collection (see verification_url or site)",
"free (not re-verified)",
"unverified",
"unverified",
"per-item",
"Translated Assyrian letters incl. craft and tribute",
"Not checked",
"unverified",
"",
""
],
[
"SRC102",
"Electronic Text Corpus of Sumerian Literature (ETCSL)",
"text-library",
"F1.9a",
"WA-MES",
"Web portal/collection (see verification_url or site)",
"free (not re-verified)",
"unverified",
"unverified",
"per-item",
"Sumerian proverbs and literary texts in translation",
"Not checked",
"unverified",
"",
""
],
[
"SRC103",
"Endangered Archives Programme (British Library)",
"manuscript-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web viewer",
"free",
"Per project/archive; commercial requests referred to archive owners",
"unverified",
"no",
"Digitised archives from Africa, Asia, Americas, Pacific (e.g. Timbuktu-region, Ethiopian, Pacific records)",
"Link out; commercial needs owner permission",
"yes 2026-09-28",
"https://eap.bl.uk/reuse-collections-and-takedown-policy",
""
],
[
"SRC104",
"British Museum Endangered Material Knowledge Programme (EMKP) repository",
"practice-archive",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Figshare repository",
"free",
"CC BY-NC-SA 4.0",
"unverified",
"no",
"Documentation of living craft practices worldwide",
"Non-commercial; community consent context",
"yes 2026-09-28",
"https://www.emkp.org/repository/",
"FAQ: 'can also not be used for commercial purposes'."
],
[
"SRC105",
"Digital Benin",
"aggregator",
"F1.6;F1.24",
"AF-GUI",
"Web portal/collection (see verification_url or site)",
"free",
"Each lending museum's copyright/licence preserved",
"unverified",
"per-item",
"Catalogue of Benin objects dispersed across 130+ institutions; Edo-language terms",
"Per-item; restitution context",
"yes 2026-09-28",
"https://digitalbenin.org/documentation/introduction",
""
],
[
"SRC106",
"African Online Digital Library (AODL, MSU)",
"text-library",
"F1.6",
"AF-SAH;AF-SOU;AF-GUI",
"Web portal/collection (see verification_url or site)",
"free",
"Licence not stated on homepage",
"unverified",
"per-item",
"Oral histories, images, teaching modules (West Africa, South Africa)",
"Link out until terms verified",
"partial 2026-09-28",
"https://aodl.org/",
""
],
[
"SRC107",
"JSTOR Struggles for Freedom: Southern Africa (formerly Aluka)",
"text-library",
"F1.6",
"AF-SOU",
"Web portal/collection (see verification_url or site)",
"paid (institutional licence); free alternative: DISA, AODL",
"Licensed",
"unverified",
"no",
"Liberation-movement documents",
"Not free",
"yes 2026-09-28",
"https://about.jstor.org/products/journals-and-primary-sources/licensed-collections/struggles-for-freedom-southern-africa/",
""
],
[
"SRC108",
"JSTOR Global Plants (Aluka)",
"dataset",
"F1.6",
"GL",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"no",
"Plant type specimens (materials: dyes, fibres)",
"Not checked; likely licensed",
"unverified",
"",
""
],
[
"SRC109",
"Digital Innovation South Africa (DISA)",
"text-library",
"F1.6",
"AF-SOU",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Anti-apartheid periodicals and documents",
"Not checked",
"unverified",
"",
""
],
[
"SRC110",
"Iziko Museums of South Africa",
"museum-open-access",
"F1.6",
"AF-SOU",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Southern African material culture",
"Not checked",
"unverified",
"",
""
],
[
"SRC111",
"SAHRIS (South African Heritage Resources Agency)",
"dataset",
"F1.6",
"AF-SOU",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Heritage site records and permits",
"Not checked",
"unverified",
"",
""
],
[
"SRC112",
"Zamani Project (African heritage 3D)",
"3d",
"F1.6",
"AF-HRN;AF-SWA;AF-SAH;AF-SOU",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Laser scans of Lalibela, Kilwa, Djenné etc.",
"Not checked",
"unverified",
"",
""
],
[
"SRC113",
"INAH Mediateca / Repositorio INAH (Mexico)",
"image-commons",
"F1.7",
"AM-MES;AM-LAT",
"Web portal/collection (see verification_url or site)",
"free (viewing)",
"Terms page redirected to new repository; not retrieved. INAH runs a formal reproduction-authorisation procedure (trámite INAH-01-004)",
"unverified",
"no",
"Mexican archaeology, codices, Fototeca Nacional",
"Link out until verified",
"partial 2026-09-28",
"https://repositorio.inah.gob.mx/",
""
],
[
"SRC114",
"Brasiliana Guita e José Mindlin (USP)",
"text-library",
"F1.7",
"AM-AMZ;AM-LAT",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Brazilian colonial books incl. Staden, Léry editions",
"Not checked",
"unverified",
"",
""
],
[
"SRC115",
"BNDigital (Biblioteca Nacional do Brasil)",
"text-library",
"F1.7",
"AM-AMZ;AM-LAT",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Brazilian manuscripts and iconography",
"Not checked",
"unverified",
"",
""
],
[
"SRC116",
"Open Khipu Repository",
"dataset",
"F1.7;F1.5",
"AM-AND",
"Web portal/collection (see verification_url or site)",
"free",
"No licence stated in README",
"n/a",
"no",
"Cord-level khipu data for recurrences of record-keeping",
"Treat as all rights reserved: cite and link",
"partial 2026-09-28",
"https://github.com/khipulab/open-khipu-repository/blob/master/README.md",
"Zenodo record 5037552 also shows no licence."
],
[
"SRC117",
"Digital Florentine Codex (Getty Research Institute)",
"manuscript-library",
"F1.7",
"AM-MES",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Sahagún's Florentine Codex with Nahuatl and translations",
"Not checked",
"unverified",
"",
""
],
[
"SRC118",
"Reciprocal Research Network",
"community-published",
"F1.7",
"AM-NWC",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"no",
"Northwest Coast belongings with community input",
"Community protocols; link out",
"unverified",
"",
""
],
[
"SRC119",
"SlaveVoyages",
"dataset",
"F1.13;F1.6;F1.7;F1.23",
"AF-GUI;AF-CEN;AM-CAR;AM-LAT;AM-EWD",
"Web portal/collection (see verification_url or site)",
"free",
"Site content CC BY-NC 3.0 US",
"Historical data from documents = public domain; imputed data and Estimates = CC BY-NC 3.0 US",
"per-item",
"Voyages, people, routes of the Atlantic and intra-American slave trades",
"Human-flow sensitivity; imputed data NC",
"yes 2026-09-28",
"https://www.slavevoyages.org/blog/legal/180",
"Show people, not goods (brief rule)."
],
[
"SRC120",
"UNESCO Dive into Intangible Cultural Heritage (data)",
"dataset",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Graph + downloadable data",
"free",
"Images carry own copyright metadata",
"Released 'according to the principles... of open science'; licence not stated on page",
"per-item",
"Inscribed ICH elements (craft practices) with links",
"Licence unclear; images per-item",
"partial 2026-09-28",
"https://ich.unesco.org/fr/acces-libre-aux-donnees-de-dive-01218",
""
],
[
"SRC121",
"UNESCO World Heritage List data",
"dataset",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + downloads",
"unverified",
"unverified",
"unverified",
"per-item",
"Site list with coordinates",
"Not checked",
"unverified",
"",
""
],
[
"SRC122",
"PeriodO",
"gazetteer",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + JSON-LD dumps",
"free",
"n/a",
"Public domain dedication (CC0)",
"yes",
"Scholarly period definitions with region scope (regional ages)",
"",
"yes 2026-09-28",
"https://perio.do/license/",
""
],
[
"SRC123",
"Pleiades",
"gazetteer",
"F1.11;F1.9a;F1.6;F1.10;F1.12a",
"EU-GRR;WA-MES;WA-LEV;WA-ANA;AF-EGY;AF-MAG",
"Web portal/collection (see verification_url or site)",
"free",
"n/a",
"CC BY 3.0 US",
"yes",
"Ancient places with coordinates",
"Mediterranean-centred",
"yes 2026-09-28",
"https://pleiades.stoa.org/downloads",
""
],
[
"SRC124",
"World Historical Gazetteer",
"gazetteer",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API",
"free",
"Per contributed dataset licence",
"Per dataset (documentation itself CC BY-NC 4.0)",
"per-item",
"Historical place names worldwide",
"Check each dataset's licence",
"partial 2026-09-28",
"https://docs.whgazetteer.org/",
""
],
[
"SRC125",
"Getty Vocabularies (AAT, TGN, ULAN)",
"vocabulary",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"LOD/SPARQL + downloads",
"free",
"n/a",
"ODC-By 1.0",
"yes",
"Controlled terms for materials, techniques, object types, places, makers",
"Attribution required",
"yes 2026-09-28",
"https://www.getty.edu/research/tools/vocabularies/lod/index.html",
""
],
[
"SRC126",
"Seshat Global History Databank",
"dataset",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + downloads (sign-in page seen)",
"free (sign-in may be required)",
"n/a",
"CC BY-NC-SA per GitHub datasets README; Equinox release on Zenodo is CC0",
"per-item",
"Polity-level variables incl. technology, writing, money",
"NC for most; CC0 for Equinox only",
"partial 2026-09-28",
"https://github.com/datasets/seshat",
""
],
[
"SRC127",
"Cliopatria (Seshat polity borders)",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"GitHub GeoJSON",
"free",
"n/a",
"CC BY 4.0",
"yes",
"Polity boundaries 3400 BCE-2024 CE for maps",
"Boundaries are scholarly approximations",
"yes 2026-09-28",
"https://raw.githubusercontent.com/Seshat-Global-History-Databank/cliopatria/main/LICENSE.md",
""
],
[
"SRC128",
"Natural Earth",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download",
"free",
"n/a",
"Public domain",
"yes",
"Base map layers",
"Modern boundaries only",
"yes 2026-09-28",
"https://www.naturalearthdata.com/about/terms-of-use/",
""
],
[
"SRC129",
"OpenStreetMap",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download/API; do not rely on OSMF tiles for production",
"free",
"Produced works (rendered maps) may carry any licence",
"ODbL 1.0: attribution required; derivative databases share-alike; collective databases may differ",
"yes",
"Present-day places, sites, workshops, routes",
"Share-alike on derived data; attribution '© OpenStreetMap contributors'",
"yes 2026-09-28",
"https://osmfoundation.org/wiki/Licence/Licence_and_Legal_FAQ",
"Recipients of produced works may request underlying data."
],
[
"SRC130",
"OpenHistoricalMap",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + data",
"free",
"n/a",
"CC0 unless noted",
"yes",
"Historical features by date",
"Coverage patchy",
"yes 2026-09-28",
"https://wiki.openstreetmap.org/wiki/OpenHistoricalMap/FAQ",
""
],
[
"SRC131",
"geoBoundaries",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download",
"free",
"n/a",
"CC BY 4.0 (project outputs; source boundaries may carry own terms)",
"yes",
"Admin boundaries; free alternative to GADM",
"Check source per country",
"yes 2026-09-28",
"https://github.com/wmgeolab/geoBoundaries/blob/main/LICENSE",
""
],
[
"SRC132",
"GADM",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download",
"free-limited (academic/non-commercial only)",
"n/a",
"Non-commercial; redistribution not allowed without permission",
"no",
"Admin boundaries",
"Use geoBoundaries instead",
"yes 2026-09-28",
"https://gadm.org/license.html",
""
],
[
"SRC133",
"David Rumsey Map Collection",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + downloads",
"free",
"CC BY-NC-SA 3.0 (site also allows publisher use without charge; commercial facsimiles need permission)",
"unverified",
"no",
"Historical maps and atlases worldwide",
"NC licence; link out if app charges",
"yes 2026-09-28",
"https://www.davidrumsey.com/about/copyright-and-permissions",
""
],
[
"SRC134",
"Library of Congress Geography and Map Division",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"loc.gov",
"free",
"per-item",
"unverified",
"per-item",
"Historical maps",
"Not checked",
"unverified",
"",
""
],
[
"SRC135",
"Ancient World Mapping Center map files and tiles",
"maps-geodata",
"F1.11;F1.9a;F1.6",
"EU-GRR",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Ancient base maps",
"Not checked",
"unverified",
"",
""
],
[
"SRC136",
"Digital Atlas of the Roman Empire (DARE)",
"maps-geodata",
"F1.11",
"EU-GRR",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Roman roads, places",
"Not checked",
"unverified",
"",
""
],
[
"SRC137",
"GeoNames",
"gazetteer",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download + API (username)",
"unverified",
"n/a",
"unverified",
"per-item",
"Modern place names",
"Not checked",
"unverified",
"",
""
],
[
"SRC138",
"Protomaps basemaps (PMTiles)",
"maps-geodata",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Self-hosted single-file tiles",
"free",
"Tiles mix OSM (ODbL), OSM-derived coastlines (ODbL), Natural Earth (PD), ESA WorldCover landcover (CC BY 4.0), Mapzen icons (MIT)",
"see content",
"yes",
"Self-hostable basemap with no tile-server bills",
"Attribution for OSM required",
"yes 2026-09-28",
"https://github.com/protomaps/basemaps/blob/main/LICENSE_DATA.md",
""
],
[
"SRC139",
"D-PLACE (cultural practices database)",
"dataset",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + downloads",
"unverified",
"n/a",
"unverified",
"per-item",
"Cross-cultural variables (crafts, subsistence, housing)",
"Not checked; colonial ethnography source bias",
"unverified",
"",
""
],
[
"SRC140",
"Glottolog",
"vocabulary",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + downloads",
"unverified",
"n/a",
"unverified",
"per-item",
"Language names/codes for makers' communities",
"Not checked",
"unverified",
"",
""
],
[
"SRC141",
"Nomisma",
"vocabulary",
"F1.11;F1.9a;F1.10",
"GL",
"LOD",
"unverified",
"n/a",
"unverified",
"per-item",
"Coin types, mints, denominations",
"Not checked",
"unverified",
"",
""
],
[
"SRC142",
"Local Contexts Hub (TK/BC Labels and Notices)",
"community-published",
"THEME;F1.26;F1.24",
"GL",
"Hub accounts",
"free-limited (Individual researcher subscription free: 1 user, 0 API keys, 10 Projects/yr, 12 notifications/yr; Collections Care Notices free for institution accounts; paid tiers Small US$1,250, Medium US$5,000, Large US$10,000/yr)",
"Notices and Labels usable within usage guidelines; Labels are applied only by Indigenous communities (community accounts)",
"n/a",
"per-item",
"Notices on Atlas cards; invite communities to add Labels",
"As of 2025 a subscription (free or paid) is required to generate Notices; free tier has no API key",
"yes 2026-09-28",
"https://localcontexts.org/hub-agreements/subscribers/",
"FAQ: 'as of 2025, a subscription is required for their use'. Page updated July 6, 2026."
],
[
"SRC143",
"CARE Principles for Indigenous Data Governance (GIDA)",
"community-published",
"THEME;F1.26",
"GL",
"Downloadable documents and translations",
"free",
"Licence not stated on GIDA page",
"n/a",
"per-item",
"Governance framework the brief requires",
"Framework to follow; cite, do not host",
"partial 2026-09-28",
"https://www.gida-global.org/careprinciples",
"Data Science Journal article (2020) is the citable version (licence not checked)."
],
[
"SRC144",
"Mukurtu CMS",
"tools",
"THEME;F1.26",
"GL",
"Self-hosted open-source CMS",
"unverified",
"n/a",
"unverified",
"per-item",
"Community-controlled publishing with cultural protocols",
"Not checked",
"unverified",
"",
""
],
[
"SRC145",
"Protocols for Native American Archival Materials",
"community-published",
"F1.7;THEME",
"AM-NWC;AM-WST;AM-EWD;AM-ARC",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"n/a",
"per-item",
"Guidance on handling Native American material",
"Not checked",
"unverified",
"",
""
],
[
"SRC146",
"OpenAlex",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"API (key) + snapshots",
"free-limited (free account: US$1 of API usage per day; key required)",
"n/a",
"CC0",
"yes",
"Finding scholarship and OA copies on every Atlas node",
"Paid tiers above free daily budget",
"yes 2026-09-28",
"https://help.openalex.org/access/pricing/",
""
],
[
"SRC147",
"Unpaywall",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"REST API (email parameter) + snapshots",
"free",
"Links to OA copies; each copy has own licence",
"unverified",
"per-item",
"Locating legal free PDFs by DOI",
"Now runs on OpenAlex codebase (2025 rebuild changed OA classifications)",
"partial 2026-09-28",
"https://casrai.org/guides/unpaywall-open-access-status-database-api",
"Secondary guide; official docs not fetched."
],
[
"SRC148",
"CORE",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"API (no registration) + web",
"free-limited (1 batch or 5 single requests per 10 s without registration)",
"Full texts carry own licences",
"unverified",
"per-item",
"Repository full texts (theses, working papers)",
"Faster tiers typically paid; commercial use under T&C",
"yes 2026-09-28",
"https://core.ac.uk/services/api",
""
],
[
"SRC149",
"DOAJ",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Website, API, widgets, Atom feed (free); premium OAI-PMH/dumps",
"free (premium current OAI-PMH, daily dumps and journal CSV paid from 17 Mar 2026; open versions lag ~1 month)",
"Articles carry journal licences",
"unverified",
"per-item",
"Finding OA journals by field",
"Premium only for freshness",
"yes 2026-09-28",
"https://blog.doaj.org/2026/03/03/doajs-new-premium-metadata-services/",
""
],
[
"SRC150",
"JSTOR free register-and-read",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Free personal account",
"free-limited (10 articles every 30 days, online reading)",
"Copyrighted; read only",
"n/a",
"no",
"Access to key scholarship for authors",
"Link/cite only",
"yes 2026-09-28",
"https://support.jstor.org/hc/en-us/articles/115004760028-How-to-Register-Get-Free-Access-to-Content",
"Brief's '100/month' figure is outdated: page says 10 per 30 days."
],
[
"SRC151",
"JSTOR Open Community Collections",
"image-commons",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"JSTOR platform",
"free",
"Per collection; not specified on announcement",
"unverified",
"per-item",
"450+ collections from 135+ libraries/museums (photos, coins, maps)",
"Check each collection's terms",
"partial 2026-09-28",
"https://about.jstor.org/news/add-more-than-450-open-community-collections-to-your-research-mix/",
""
],
[
"SRC152",
"OAPEN / Directory of Open Access Books",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"unverified",
"per-book CC licences",
"unverified",
"per-item",
"Open monographs on craft, art, archaeology",
"Not checked",
"unverified",
"",
""
],
[
"SRC153",
"Zenodo",
"open-literature",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API",
"unverified",
"per-record",
"unverified",
"per-item",
"Datasets and papers (e.g. Seshat Equinox, Khipu)",
"Not checked",
"unverified",
"",
""
],
[
"SRC154",
"SciELO",
"open-literature",
"F1.7;F1.6",
"AM-LAT;AM-AND",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Latin American scholarship",
"Not checked",
"unverified",
"",
""
],
[
"SRC155",
"Persée",
"open-literature",
"F1.11;F1.6;F1.10",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"per-item",
"French journal backfiles (archaeology, Africanist, Orientalist)",
"Not checked",
"unverified",
"",
""
],
[
"SRC156",
"World History Commons",
"open-textbook",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"per-item",
"Teaching modules with primary sources",
"Not checked",
"unverified",
"",
""
],
[
"SRC157",
"Smarthistory",
"open-textbook",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web essays and videos",
"free",
"CC BY-NC-SA 4.0",
"n/a",
"no",
"Short essays/videos per object",
"NC: link out if app charges",
"yes 2026-09-28",
"https://smarthistory.org/faq/",
"Also listed on CC wiki. Individual images may carry other licences."
],
[
"SRC158",
"Khan Academy (art history)",
"open-textbook",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"free",
"CC BY-NC-SA (videos/exercises); ads count as commercial",
"n/a",
"no",
"Video lessons (partly Smarthistory)",
"Mandatory attribution notice before login",
"yes 2026-09-28",
"https://support.khanacademy.org/hc/en-us/articles/202262954-Can-I-use-Khan-Academy-s-videos-name-materials-links-in-my-project",
""
],
[
"SRC159",
"Heilbrunn Timeline of Art History (The Met)",
"open-textbook",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web essays",
"free",
"No reuse licence found; rights page lists photo credits and copyright holders",
"n/a",
"no",
"Authoritative essays and chronologies",
"LINK ONLY; OA images inside can be taken from Met OA directly",
"partial 2026-09-28",
"https://www.metmuseum.org/toah/rights-and-permissions",
""
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
