insert into public.f1_source_routes ("id", "name", "type", "covers_worlds", "covers_sub_regions", "access", "cost", "licence_content", "licence_metadata", "commercial_safe", "what_it_fills", "known_limits", "verified", "verification_url", "notes")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11), public.cw_text(x->12), public.cw_text(x->13), public.cw_text(x->14)
from jsonb_array_elements($cwb$[
[
"SRC160",
"Perseus Digital Library / Scaife Viewer",
"text-library",
"F1.11;F1.9a",
"EU-GRR",
"Web portal/collection (see verification_url or site)",
"free",
"Licence not confirmed (CC wiki lists 'copyright'); many older translations PD",
"unverified",
"per-item",
"Greek and Latin texts with translations (Pliny, Vitruvius, Xenophon)",
"Check each text's licence note",
"partial 2026-09-28",
"https://wiki.creativecommons.org/wiki/Tufts_University_%E2%80%93_Perseus_Digital_Library",
""
],
[
"SRC161",
"Open Greek and Latin",
"text-library",
"F1.11",
"EU-GRR",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Open Greek/Latin texts",
"Not checked",
"unverified",
"",
""
],
[
"SRC162",
"LacusCurtius (Bill Thayer)",
"text-library",
"F1.11",
"EU-GRR",
"Web portal/collection (see verification_url or site)",
"free",
"PD translations transcribed (not re-verified)",
"n/a",
"per-item",
"Vitruvius, Pliny transcriptions",
"Not checked",
"unverified",
"",
""
],
[
"SRC163",
"Biodiversity Heritage Library",
"text-library",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web + API + Flickr",
"free",
"PD items: free incl. commercial; in-copyright items (with permission) CC BY-NC-SA 4.0",
"unverified",
"per-item",
"Natural history of materials: dyes, fibres, shells, woods",
"NC for in-copyright",
"yes 2026-09-28",
"https://about.biodiversitylibrary.org/help/copyright-and-reuse/",
""
],
[
"SRC164",
"Making and Knowing Project: BnF Ms. Fr. 640 edition",
"practice-archive",
"F1.11;F1.28a",
"EU-WCE",
"Web portal/collection (see verification_url or site)",
"free",
"'The Project's data is open access'; specific licence not stated on page",
"unverified",
"per-item",
"Transcription, translation and reconstructions of a 16th c. artisan manuscript",
"Confirm licence at edition640.makingandknowing.org",
"partial 2026-09-28",
"https://www.makingandknowing.org/digital/",
""
],
[
"SRC165",
"Getty Conservation Institute publications",
"practice-archive",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Free PDFs",
"free (not re-verified)",
"per-publication",
"n/a",
"per-item",
"Technical studies of materials and techniques",
"Not checked",
"unverified",
"",
""
],
[
"SRC166",
"CAMEO (MFA Boston materials database)",
"practice-archive",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web wiki",
"unverified",
"unverified",
"unverified",
"per-item",
"Definitions of materials and techniques",
"Not checked",
"unverified",
"",
""
],
[
"SRC167",
"Heritage Crafts Red List (UK)",
"practice-archive",
"F1.11;F1.29",
"EU-BLC",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Endangered crafts in the UK",
"Not checked",
"unverified",
"",
""
],
[
"SRC168",
"Timbuktu manuscripts (Mali Magic on Google Arts & Culture)",
"manuscript-library",
"F1.6;F1.10",
"AF-SAH",
"Web portal/collection (see verification_url or site)",
"free (viewing)",
"unverified",
"unverified",
"no",
"Digitised Timbuktu manuscripts",
"Link out",
"unverified",
"",
""
],
[
"SRC169",
"Freesound",
"audio",
"F1.4;THEME",
"GL",
"Web + API",
"free (API key; not re-verified)",
"Per-sound: CC0, CC BY, CC BY-NC (Sampling+ being retired)",
"unverified",
"per-item",
"Workshop and tool sounds for immersive units",
"Filter to CC0/CC BY",
"yes 2026-09-28",
"https://freesound.org/help/faq/",
""
],
[
"SRC170",
"Musopen",
"audio",
"F1.4",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"per-item",
"PD classical recordings",
"Not checked",
"unverified",
"",
""
],
[
"SRC171",
"British Library Sounds / World and traditional music",
"audio",
"F1.4;F1.29",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"no",
"Field recordings",
"Not checked; assume link out",
"unverified",
"",
""
],
[
"SRC172",
"Smithsonian Folkways",
"audio",
"F1.4;F1.29",
"GL",
"Streaming/purchase",
"paid (downloads); free alternative: Freesound CC0, LoC PD recordings",
"Copyrighted",
"n/a",
"no",
"Ethnographic recordings",
"Not checked",
"unverified",
"",
""
],
[
"SRC173",
"NASA Image and Video Library",
"image-commons",
"F1.22;THEME",
"GL",
"Web + API",
"free",
"Generally not subject to US copyright; no implied endorsement; insignia protected; third-party items marked; NFT use prohibited",
"unverified",
"yes",
"Earth-from-space imagery for the planetary-present unit",
"Check third-party credits",
"yes 2026-09-28",
"https://nasa.gov/nasa-brand-center/images-and-media",
""
],
[
"SRC174",
"LoC National Screening Room",
"film-video",
"F1.4;F1.19",
"AM-EWD",
"Web portal/collection (see verification_url or site)",
"unverified",
"unverified",
"unverified",
"per-item",
"Early films of industry and work",
"Not checked",
"unverified",
"",
""
],
[
"SRC175",
"British Pathé",
"film-video",
"F1.19;F1.19a;F1.21",
"GL",
"YouTube embeds; licences paid",
"paid for reuse; free alternative: Prelinger, LoC PD films",
"Copyrighted",
"n/a",
"no",
"Newsreels",
"Embed/link only (not re-verified)",
"unverified",
"",
""
],
[
"SRC176",
"MorphoSource",
"3d",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web; registration for restricted media",
"free-with-registration (for restricted items)",
"Per-item: CC licences, copyright, or PD",
"unverified",
"per-item",
"3D/CT scans incl. cultural heritage",
"Many NC or restricted",
"partial 2026-09-28",
"https://www.re3data.org/repository/r3d100012224",
""
],
[
"SRC177",
"Open Heritage 3D / CyArk",
"3d",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"unverified",
"unverified",
"unverified",
"per-item",
"Site-scale scans",
"Not checked",
"unverified",
"",
""
],
[
"SRC178",
"Noto fonts",
"fonts",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"GitHub/Google Fonts",
"free",
"SIL Open Font License 1.1",
"n/a",
"yes",
"Scripts for every world (Arabic, Devanagari, CJK, Ethiopic, Vai, Tifinagh, cuneiform, hieroglyphs)",
"OFL: may not sell fonts alone",
"yes 2026-09-28",
"https://github.com/notofonts/noto-fonts/blob/main/LICENSE",
""
],
[
"SRC179",
"Google Fonts library (OFL/Apache)",
"fonts",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web",
"free",
"OFL or Apache per family (not re-verified)",
"n/a",
"yes",
"UI and display type",
"Check each family",
"unverified",
"",
""
],
[
"SRC180",
"Amiri / Scheherazade New (Arabic)",
"fonts",
"F1.10",
"GL",
"Download",
"free",
"OFL (not re-verified)",
"n/a",
"yes",
"Naskh typography for Arabic quotations",
"",
"unverified",
"",
""
],
[
"SRC181",
"Gentium / Charis SIL",
"fonts",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Download",
"free",
"OFL (not re-verified)",
"n/a",
"yes",
"Extended Latin/Greek for transliteration",
"",
"unverified",
"",
""
],
[
"SRC182",
"Junicode",
"fonts",
"F1.11",
"GL",
"Download",
"free",
"OFL (not re-verified)",
"n/a",
"yes",
"Medievalist characters",
"",
"unverified",
"",
""
],
[
"SRC183",
"IIIF (Image/Presentation APIs)",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Open standard",
"free",
"Specifications openly published (licence not re-verified)",
"n/a",
"yes",
"Deep-zoom and comparison of museum images without hosting copies",
"",
"unverified",
"",
""
],
[
"SRC184",
"Mirador",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Open-source IIIF viewer",
"free",
"Apache 2.0 (not re-verified)",
"n/a",
"yes",
"Side-by-side IIIF comparison (copying/transfer unit)",
"",
"unverified",
"",
""
],
[
"SRC185",
"OpenSeadragon",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Open-source deep-zoom viewer",
"free",
"BSD-3-Clause (not re-verified)",
"n/a",
"yes",
"Zoomable images in cards",
"",
"unverified",
"",
""
],
[
"SRC186",
"Universal Viewer",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Open-source IIIF viewer",
"free",
"MIT (not re-verified)",
"n/a",
"yes",
"IIIF viewing incl. manuscripts",
"",
"unverified",
"",
""
],
[
"SRC187",
"QGIS",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Desktop GIS",
"free",
"GPL (not re-verified)",
"n/a",
"yes",
"Making static and tiled maps",
"",
"unverified",
"",
""
],
[
"SRC188",
"MapLibre GL JS",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Open-source web map library",
"free",
"BSD-3-Clause (not re-verified)",
"n/a",
"yes",
"Interactive maps from Protomaps/OSM/Cliopatria",
"",
"unverified",
"https://github.com/maplibre/maplibre-gl-js",
""
],
[
"SRC189",
"D3.js / Observable Plot",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"JS library",
"free",
"ISC (not re-verified)",
"n/a",
"yes",
"Custom timelines and networks",
"",
"unverified",
"",
""
],
[
"SRC190",
"Datawrapper (free plan)",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Hosted charts/maps",
"free (unlimited views)",
"You keep copyright over charts, 'publish them freely in academic or commercial contexts'; must retain 'Created with Datawrapper' attribution",
"n/a",
"yes",
"Charts and locator maps without coding",
"Third-party hosting; attribution required on free plan",
"yes 2026-09-28",
"https://www.datawrapper.de/pricing",
""
],
[
"SRC191",
"Blender",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Desktop 3D",
"free",
"GPL (not re-verified)",
"n/a",
"yes",
"3D reconstruction, rendering, cleaning scans",
"Outputs are yours",
"unverified",
"",
""
],
[
"SRC192",
"Meshroom (AliceVision)",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Desktop photogrammetry",
"free",
"MPL-2.0 (LICENSE-MPL2 file in repo; not read)",
"n/a",
"yes",
"Making own 3D scans of objects/replicas",
"Needs CUDA GPU for best results (not re-verified)",
"partial 2026-09-28",
"https://github.com/alicevision/meshroom/blob/develop/LICENSE-MPL2.md",
""
],
[
"SRC193",
"model-viewer / three.js",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web 3D display",
"free",
"Apache 2.0 / MIT (not re-verified)",
"n/a",
"yes",
"Showing glTF models in the app",
"",
"unverified",
"",
""
],
[
"SRC194",
"Inkscape",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Vector drawing",
"free",
"GPL (not re-verified)",
"n/a",
"yes",
"Diagrams of techniques, maps clean-up",
"",
"unverified",
"",
""
],
[
"SRC195",
"TimelineJS / StoryMapJS (Knight Lab)",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Hosted/self-hosted JS",
"free",
"MPL-2.0 (not re-verified)",
"n/a",
"yes",
"Narrative timelines and map stories",
"",
"unverified",
"",
""
],
[
"SRC196",
"Omeka S",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Self-hosted collections CMS",
"free",
"GPL (not re-verified)",
"n/a",
"yes",
"Exhibit prototyping with IIIF",
"",
"unverified",
"",
""
],
[
"SRC197",
"Zotero",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Reference manager",
"free (300 MB sync free; not re-verified)",
"AGPL (not re-verified)",
"n/a",
"yes",
"Shared bibliography for the canon",
"",
"unverified",
"",
""
],
[
"SRC198",
"Recogito (Pelagios)",
"tools",
"F1.6;F1.7;F1.8;F1.9;F1.9a;F1.10;F1.11;F1.12;F1.12a;F1.13",
"GL",
"Web annotation",
"unverified",
"unverified",
"n/a",
"yes",
"Geo-annotating primary texts (Periplus, Ibn Battuta)",
"",
"unverified",
"",
""
]
]$cwb$::jsonb) x
on conflict ("id") do nothing;
