insert into public.documents ("path", "title", "kind", "module", "format", "artifact_url", "docs_id", "tab_name", "rev", "content", "pdf_path", "sha256")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11)
from jsonb_array_elements($cwb$[
[
"docs/02-program/glossary/index.md",
"Glossary — the program's compendium",
"document",
"program",
"md",
"https://claude.ai/artifact/8HprReEvNxePChS1Yb1zg2",
"3b095c62-6d8b-45c4-b069-0d279f24acdb",
"Glossary — the program's compendium",
"3",
[
"# Glossary — the program's compendium\n\n2026-09-28 · @Mohammad AlFalasi\n\n## How the glossary works\n\nEvery term the program uses on purpose is here once, in plain words, with the unit where a learner first meets it, the terms it connects to, and — for the briefer lane — one line on how to use it with a designer; version 1 holds the program's core vocabulary and F1's, about ninety terms, and grows with each module through the factory.\n\n**Rules for entries**\n\n1. A term enters the glossary when a unit introduces it; it is never used in unit copy before its unit.\n2. One term per idea; synonyms are listed as \"also called\", never used interchangeably.\n3. Meanings are one or two sentences, written for someone who has not studied design.\n4. \"Met in\" is the first unit; later uses are found through the Atlas and the unit register, not listed here.\n5. \"Say it to a designer\" appears where a briefer would use the idea in a meeting or a brief.\n6. In the app, every term is a link wherever it appears; \"Related\" terms are links too, which is what makes this a compendium rather than a list.\n\n## The program and the method\n\n| Term | Meaning | Met in | Related | Say it to a designer |\n",
"|---|---|---|---|---|\n| Artifact | The one thing every learner builds through the program: their Concept DNA and what attaches to it | O1.3 | Concept DNA, sources record | — |\n| Lane | The way a learner applies each unit: the maker lane produces; the briefer lane writes briefs and judges work | O1.3 | Apply step, route | — |\n| Depth | How far into a module a learner goes: Orientation (the idea), Practice (the usable core), Mastery (the full studio and defence) | O1.3 | Route, slice | — |\n| Route | A default path through the depths for a kind of learner: Maker, Briefer, Founder, Student | O1.3 | Lane, persona | — |\n| Opening move | How a unit begins, chosen for what its knowledge needs: lab, object, story, problem, prediction, argument, artifact, partner, data or making first | Every unit | Unit | — |\n| Apply step | The part of a unit where the learner uses the idea on their own world | Every unit | Lane | — |\n| Thread | A concern that recurs across the program and must progress, not repeat: planetary weight, handover, attribution, accessibility, writing, AI collaboration | F1 (attribution) | Checkpoint | — |\n",
"| Partner voice | One of seven AI roles that question the learner's work without grading it: Mirror, Stranger, Client, Fabricator, CFO, Historian, Planet | O1.4 | Historian, Stranger test | — |\n| Seed world | A ready-made fictional world a learner can use when they have no project of their own | O1.3 | Exemplar world | — |\n| Concept DNA | The versioned set of rules from which anyone can build a world correctly: premise, rules, grammars, anti-DNA, tests, brief, history | O1.3; M2 | Premise, grammar, Stranger test | \"Here are the rules; show me what you would build from them.\" |\n| Premise | A world's proposition, stance, central contradiction, human scenario and non-goals | M1.9 | Perimeter, stance | \"What is this world for, and what will it never do?\" |\n| Perimeter | What a world enables, protects, resists, rejects and transforms | F5.1 | Non-goal | \"Tell me what this protects and what it refuses.\" |\n| Non-goal | Something the world deliberately does not try to do | M1.12 | Perimeter | \"Which good ideas are we saying no to?\" |\n| Constant | A rule that never changes, whatever the product or medium | M2.4 | Variable, threshold | \"What must be true of everything we make?\" |\n",
"| Variable | A rule that may flex to suit a product, place or audience | M2.4 | Constant, threshold | \"What can change from one piece to the next?\" |\n| Threshold | How far a variable may move before the world stops being itself | M2.4 | Edge | \"How far can this go before it isn't us?\" |\n| Grammar | A family of rules for one dimension of a world: formal, material, construction, chromatic, spatial, atmospheric, sensory, behavioural, interaction, temporal, narrative or verbal | M2.6 | Concept DNA | \"Which grammars carry this brand, and which are open?\" |\n| Anti-DNA | What the world is incapable of being | M2.5 | Non-goal | \"What would make this unmistakably wrong?\" |\n| The four tests | Belongs, edge, failure, seductive-but-off: the four verdicts any piece can get against a world's rules | M2.2 | Test set | \"Is this on-brand, on the edge, off, or tempting but off?\" |\n| Seductive-but-off | A piece that is attractive and even excellent but breaks the world's rules | M2.2 | The four tests | \"I love it, but which rule does it break?\" |\n",
"| Stranger test | Giving the rules to someone who has never met you (a person or the AI Stranger) and scoring how far their result drifts | M2.15 | Drift, contributor brief | \"Could a stranger build this from the brief alone?\" |\n| Drift | How far a stranger's result moves from the world's rules; the measure of a weak rule | M2.15 | Stranger test | — |\n| Contributor brief | The Concept DNA rewritten as instructions for someone else to build from | M2.19 | Brief | — |\n| Anchor | The piece that establishes a world most fully; the one everything else refers to | M3.3 | Hero, family | \"Which piece carries the world if we can only make one?\" |\n| Hero, core, entry, experimental, supporting | The other roles a piece can play in a collection | M3.3 | Anchor, collection | \"Which role is this piece playing?\" |\n| Carrier | Where a world meets people: a shop, a site, a feed, a package, a person | M3.8 | Touchpoint | \"Where will people actually meet this?\" |\n| Adjacent translation | The same world expressed in a second medium, as a test of its rules | M4.3 | Drift | — |\n\n## History and culture\n\n| Term | Meaning | Met in | Related | Say it to a designer |\n|---|---|---|---|---|\n",
"| Reading an object | Treating a made thing as a document of its material, the labour behind it, the trade that moved it and what it meant | F1.1 | Autopsy, object biography | \"What does this object tell us about who made it and why?\" |\n| Autopsy | F1's lab for reading an object layer by layer: material, labour, trade, meaning, and at Practice, technique | F1.1, F1.25 | Reading an object | — |\n| Canon | The set of works and makers a field treats as essential; always a choice made by someone | F1.3 | Counter-history | \"Whose canon are we drawing on here?\" |\n| Periodisation | Dividing time into named periods; the names carry assumptions about where history happened | F1.3 | Calendar, canon | — |\n| Counter-history | A history told from what the dominant account leaves out | F1.3 | Canon, obscured labour | — |\n| Design history and design studies | Two ways the field studies itself: the history of made things, and the study of designing as an activity | F1.3 | — | — |\n| Recurrence | Something invented or developed independently in several places and times, such as writing, cities, metallurgy, weaving and printing | F1.5 | Stimulus diffusion | — |\n",
"| Stimulus diffusion | Borrowing the idea of something without borrowing its form; one reading of how writing reached Egypt | F1.5 | Recurrence | — |\n| World of making | One of F1's regional chapters, read through a device (metallurgy, fibre, the workshop, cotton, routes, the guild, navigation) rather than a list | F1.6 | Network | — |\n| Network | A route system that moved objects, materials and skills: Silk Roads, Indian Ocean, trans-Saharan, Mediterranean, Atlantic, Pacific | F1.10, F1.13 | Route, copy chain | — |\n| Copying and transfer | How forms, techniques and goods were imitated across places, from porcelain to chintz; the engine of exchange and the origin of licensing questions | F1.14 | Adaptation, licence | \"Is this a transfer we'd credit, or a copy we'd have to license?\" |\n| Exhibition as taxonomy | How world's fairs and catalogues sorted the world's making into categories, often by extracting it | F1.15 | Appropriation | — |\n| Commissioning regime | The system by which a brief is issued and paid for: patron, guild, merchant, industry, agency, platform | F1.17 | Brief | \"Which regime are we in, and who really holds the brief?\" |\n",
"| Guild | An association of makers that set rules for training, quality and trade | F1.11, F1.17 | Commissioning regime | — |\n| Waqf | An Islamic charitable endowment that funded buildings and institutions, and so commissioned making | F1.10, F1.17 | Commissioning regime | — |\n| Karkhana | A Mughal court workshop producing goods for the ruler | F1.9, F1.17 | Commissioning regime | — |\n| Obscured labour | The work of makers, technicians and communities whose names do not appear on the object | F1.23 | Credit map | \"Who made this that we are not naming?\" |\n| Credit map | F1's lab for pulling an object apart into everyone who contributed to it | F1.23 | Attribution line | — |\n| Object biography | The life of a thing from making through use, trade, ownership and display; also called the social life of things | F1.22a | Provenance | — |\n| Provenance | The documented chain of an object's owners and holders | F1.24 | Restitution | \"Where has this object been, and how did it get here?\" |\n| Restitution | Returning objects to the communities or nations they were taken from | F1.24 | Provenance | — |\n",
"| Operational sequence | A technique read as an ordered chain of gestures, tools, materials and knowledge; also called chaîne opératoire | F1.25 | Technique, reconstruction | — |\n| Reconstruction | Remaking a historical technique from a text or object to learn what the record does not say | F1.28a | Operational sequence | \"How do we know it was made that way?\" |\n| Vernacular intelligence | Knowledge carried in local practice, oral history, folktale and local ways of naming | F1.29 | Living practice | — |\n| Living practice | A making tradition still carried by people today; recorded in the Atlas as a Practice | F1.6–F1.12 | Intangible heritage | \"Is this tradition still practised, and by whom?\" |\n| Intangible heritage | Practices, skills and knowledge recognised as heritage, as distinct from objects; UNESCO keeps lists nominated by states | F1.3, F1.6 | Living practice | — |\n| Counterfactual history | A disciplined \"what if\": one changed fact, with consequences traced from sources | F1.30a | Scenario | — |\n| Pluralism and decolonisation | Adding more regions to an existing story (pluralism) is different from letting other frames set the story (decolonisation) | F1.3 | Canon | — |\n\n",
"## Rights, credit and protocol\n\n| Term | Meaning | Met in | Related | Say it to a designer |\n|---|---|---|---|---|\n| Reference | Pointing to a source openly as an influence | F1.2 | Spectrum | \"What are we referencing, and do we say so?\" |\n| Quotation | Reusing a recognisable part of a source, credited | F1.2 | Spectrum | \"Are we quoting this, and is it credited?\" |\n| Adaptation | Changing a source to fit a new use while keeping its identity | F1.2 | Spectrum | — |\n| Translation | Carrying a source into another medium, culture or language | F1.2 | Adjacent translation | — |\n| Appropriation | Taking from a culture without its consent, credit or benefit, especially where that culture has been harmed | F1.2 | Harm, consultation | \"Would the source community recognise this as theirs, and would they agree?\" |\n| Spectrum plane | F1's two-axis sort: reference to appropriation on one axis, harm to the source community on the other | F1.2 | Appropriation | — |\n| Attribution line | A short credit naming makers, sources and communities, generated from the sources record | F1.1 | Credit map | \"Put the attribution line in the deck.\" |\n",
"| Consultation | Asking a source community before using what is theirs, and recording what was agreed, credited and given back | F1.26 | CARE | \"Who did we ask, and what did we agree?\" |\n| CARE principles | Collective benefit, Authority to control, Responsibility, Ethics: principles for handling Indigenous data and heritage | F1.26 | Local Contexts | — |\n| Local Contexts Notice | A placeholder label saying a record may carry community protocols, used until a community issues its own Label | F1.26 | Label | — |\n| Traditional Knowledge Label | A label issued by a community stating its permissions, attribution and protocols for a record | F1.26 | Notice | — |\n| Sensitivity flag | The world set's marker for sacred, ancestral, funerary or restricted material, excluded by default | F1.12, F1.26 | CARE | — |\n| Public domain | Free of copyright; usable by anyone | F1.3 | CC0 | \"Is this public domain where we'll publish?\" |\n| CC0 | A dedication placing a work in the public domain as far as law allows | F1.3 | Public domain | — |\n| CC BY and NC | Creative Commons licences requiring credit (BY), and forbidding commercial use (NC) | F1.3 | Licence | \"Does this licence allow commercial use?\" |\n",
"| Rights statement | One of twelve standard statements (RightsStatements.org) used by heritage institutions when a Creative Commons licence cannot apply | F1.3 | Licence | — |\n| Informed consent | Agreement given knowing the purpose, risks and uses, with the right to refuse and withdraw | F1.29 | Narrator review | — |\n| Narrator review | Letting the person recorded check, correct, restrict or withdraw what they said before it is shared | F1.29 | Informed consent | — |\n\n## The Atlas and its data\n\n| Term | Meaning | Met in | Related |\n|---|---|---|---|\n| Atlas | F1's graph of the history of making, with eleven views onto it; the place the module happens in | F1.1 | View, ring |\n| Node | Anything in the Atlas: an object, person, community, place, material, technique, movement, event, institution, text, route, idea or practice | F1.1 | Relation |\n| Relation | A sourced link between two nodes, such as made by, copied from, traded along, commissioned by, influenced by | F1.13 | Claim |\n| Claim | A statement the Atlas makes, with its source and confidence | F1.5 | Confidence |\n",
"| Confidence | How sure a claim is: documented, probable, contested, interpretive; contested claims show both readings | F1.5 | Claim |\n| Date range | Every date shown as earliest and latest, never as a single point unless it is one | F1.5 | Uncertainty |\n| Ring | Where a node's data comes from: Ring 1 is curated by the program; Ring 2 is linked context from open knowledge bases; Ring 3 is the open graph beyond, unreviewed | F1.3 | Coverage |\n| View | A way of seeing the Atlas: map, globe, timeline, occurrences, connections, movements, inventions, compare, story, lineage, calendars | F1.1 | Lens |\n| Lens | A filter across every view: labour and credit, material and extraction, gender, ritual and belief, commissioning, copying, provenance, body and access | F1.3 | View |\n| Coverage | How many licensed objects and practices the Atlas holds per world; where it is thin, the gap is shown and taught | F1.3 | Bias of the record |\n| Lineage | The learner's own layer of the Atlas, starting with their first object in F1.1 | F1.1 | Sources record |\n",
"| Sources record (SRC) | The learner's record of every source their world draws on, with rights, protocol and consultation; grows with depth | F1.1 | Attribution line |\n"
],
"docs/02-program/glossary/index.pdf",
"ef91d4223f9d4ea25bcb968af71ec7d34267548b4a70e078022718f5940f5d3e"
]
]$cwb$::jsonb) x
on conflict ("path") do nothing;
