insert into public.documents ("path", "title", "kind", "module", "format", "artifact_url", "docs_id", "tab_name", "rev", "content", "pdf_path", "sha256")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11)
from jsonb_array_elements($cwb$[
[
"modules/F1-histories-of-making/README.md",
"F1 Histories of making",
"readme",
"F1",
"md",
"",
"",
"",
"",
[
"# F1 Histories of making\n\nThe first Foundations module. It teaches a global history of making as a web of objects, makers, places, routes and institutions. Its threshold concept is that design history is a web with obscured strands, not a line. F1 has 35 units at structure v3.6. Gate G1 passed on 28 September 2026. Phase 4 is under way, and spec batch 1 (eight units) was written on 29 September 2026.\n\n## What is here\n\n| Folder | Contents |\n|---|---|\n| `docs/` | The module's documents, in order, as Markdown and PDF (listed below) |\n| `specs/` | Unit specs on template v3, one Markdown file per unit; these are the authoring sources for the batch-1 doc |\n| `grouping-pages/` | Five grouping pages from round 2: the Indian Ocean, the Indus Valley civilisation, the waqf, Arts and Crafts, the Middle Horizon. The first three (Mingei, Nok, Igun Eronmwon) are inside the Groundwork document |\n| `atlas/` | The Atlas data and its jobs: the canon register (4,228 nodes), the world-set, claims and practices registers, 198 zero-cost source routes, 130 primary texts, the harvesters, validation, coverage and the licence switch. See `atlas/README.md` |\n",
"| `briefs/` | The briefs research agents worked to: canon schema and codes, grouping pages, unit specs |\n| `research/` | Studies behind decisions: licensing routes, object-type density, how civilisations and movements are treated, the round-2 blind map, the AP-250 coverage check, licence verification notes |\n| `review-logs/` | Fact-check logs for the canon, including the lint fixes of 29 September |\n| `design/mockups/project/` | The mockups (version 4): nine artboards and the canvas file. They need the Design runtime to render, so open them from the live mockups link below |\n| `exports/` | The canon register as a workbook, for reading without code |\n| `build/` | The scripts that built the canon and registers, kept as a record of method. They ran once in a scratch workspace, and their input and output paths point there |\n\n## Documents, in the order they were made\n\n| # | Document | Files | Live |\n|---|---|---|---|\n| 01 | F1 Pass 2, v1 | [md](docs/01-pass-2-v1/index.md) · [pdf](docs/01-pass-2-v1/index.pdf) | [open](https://claude.ai/artifact/3rnb6jRGHAYc2wq2TkyEeD) |\n",
"| 02 | F1 Pass 2, v2: experience design and the Atlas | [md](docs/02-pass-2-v2/index.md) · [pdf](docs/02-pass-2-v2/index.pdf) | [open](https://claude.ai/artifact/33S9DSwRyK8eVJZjccwf2q) |\n| 03 | F1 Module File (unit list, research log, coverage, pipeline, protocols) | [md](docs/03-module-file/index.md) · [pdf](docs/03-module-file/index.pdf) | [open](https://claude.ai/artifact/BboHsN1C9o5jVJjhLeseJp) |\n| 04 | F1 Deep Dives 1: Recurrences, Africa, and what a node carries | [md](docs/04-deep-dives-1/index.md) · [pdf](docs/04-deep-dives-1/index.pdf) | [open](https://claude.ai/artifact/Y4aKv8a3JcoKa5me1Tj9EC) |\n| 05 | F1 Deep Dives 2: seven worlds, the networks, and two new chapters | [md](docs/05-deep-dives-2/index.md) · [pdf](docs/05-deep-dives-2/index.pdf) | [open](https://claude.ai/artifact/VvUG1iSWSLmWBreRtDbERT) |\n| 06 | F1 Atlas Logic: nodes, views and groupings | [md](docs/06-atlas-logic/index.md) · [pdf](docs/06-atlas-logic/index.pdf) | [open](https://claude.ai/artifact/TRvMpQ4BZknMfHd8YPfKo4) |\n",
"| 07 | F1 Groundwork: provenance, registers, pre-read and grouping pages | [md](docs/07-groundwork/index.md) · [pdf](docs/07-groundwork/index.pdf) | [open](https://claude.ai/artifact/ETkAadxwBNo2CJYq8ceMbg) |\n| 08 | F1 Scope v2: everything, at zero cost | [md](docs/08-scope-v2/index.md) · [pdf](docs/08-scope-v2/index.pdf) | [open](https://claude.ai/artifact/WJhZUYYh646mvLL3f9uZpB) |\n| 09 | F1 Round 2: gaps, free routes, template v3 and the road to G3 | [md](docs/09-round-2/01-round-2.md) · [pdf](docs/09-round-2/01-round-2.pdf); grouping pages tab [md](docs/09-round-2/02-grouping-pages.md) · [pdf](docs/09-round-2/02-grouping-pages.pdf) | [open](https://claude.ai/artifact/Frnn3wb2anESAtoJburFSu) |\n| 10 | F1 Unit Specs, batch 1: overview plus F1.1–F1.4, F1.14, F1.15, F1.16, F1.18 | [folder](docs/10-unit-specs-batch-1/) | [open](https://claude.ai/artifact/RNWmnhgLuzjbQAGXEj8KnV) |\n| — | F1 Mockups (version 4) | [source](design/mockups/project/) | [open](https://claude.ai/artifact/VJPkDAa6sPPtSxAbTYkfFT) |\n\n## Where F1 stands\n\n- **Done:** G1; all nine world chapters and the networks unit deep-dived; Atlas logic; groundwork; scope v2; round 2; spec batch 1.\n- **Next:**\n",
"  - spec batch 2 (F1.19, F1.19a, F1.19b, F1.20–F1.22a, F1.23, F1.24), which must carry the steppe with a case;\n  - spec batch 3;\n  - the five other partner-voice packs;\n  - the first harvest run;\n  - G2 (Atlas logic and mockups) and G3 (specs and data fact-checked).\n"
],
"",
"f999ec042e0f722ccf31ca5bbf2aea2f20a7fe795b980cecc7a45e75812d2f96"
],
[
"modules/F1-histories-of-making/atlas/DATA_LICENCES.md",
"Licences of the data we draw on",
"readme",
"F1",
"md",
"",
"",
"",
"",
[
"# Licences of the data we draw on\n\nWhat we may do with each source. Checked 28 September 2026 unless noted; the harvest re-checks record-level licences monthly. The full registry, with the page each licence was read from, is `data/sources/sources_zero_cost.csv`.\n\n| Source | Licence | What we do |\n|---|---|---|\n| Cleveland Museum of Art Open Access | CC0 per record (`share_license_status`) | Host records marked CC0 |\n| The Met Open Access | Public domain per record (`isPublicDomain`); the search filter is unreliable | Host only records whose own flag is true |\n| Art Institute of Chicago | Data CC0; `description` field CC BY 4.0; images public domain per record | Host; credit AIC when quoting descriptions |\n| Smithsonian Open Access | CC0 where marked | Host records marked CC0 |\n| Wikidata | CC0 | Use ids and facts |\n| PeriodO | CC0 | Use period definitions |\n| Getty vocabularies (AAT, TGN, ULAN) | ODC-By | Use with credit |\n| Pleiades; geoBoundaries | CC BY | Use with credit |\n| Natural Earth | Public domain | Use |\n| UNESCO intangible heritage data (graph_en.json) | No licence stated | Keep facts only (names, years, list, states) and link to UNESCO |\n",
"| Wikimedia Commons | Per file | Host only CC0, public domain, CC BY or CC BY-SA files, with credit |\n| British Museum, V&A, Gallica, Bodleian, EMKP, Smarthistory | Non-commercial | Link only, unless a holder grants free educational use (open build only) |\n| Te Papa, Auckland Museum (taonga Māori and Pacific material) | Restricted by the holders' own rules despite open markings | Link only |\n\nLocal Contexts Notices are applied by hand under a free researcher account; Labels are applied by communities themselves.\n"
],
"",
"ab726ecd0311f464b926bdd7f3c97a47544c433d2ce61ed08bb13c05d474f55a"
],
[
"modules/F1-histories-of-making/atlas/README.md",
"F1 Atlas data",
"readme",
"F1",
"md",
"",
"",
"",
"",
[
"# F1 Atlas data\n\nOpen data for **F1 Histories of making**, the first module of a design-education program. F1 teaches a global history of making as a web of objects, makers, places, routes and institutions. This repository holds the data its Atlas is built from, and the scheduled jobs that keep that data honest.\n\nEverything here is produced at zero cost from free and open sources. Nothing is hosted whose licence does not allow it; everything else is linked.\n\n## What is here\n\n| Folder | Contents |\n|---|---|\n| `data/canon/` | The canon register: 4,228 nodes in 24 kinds. It covers civilisation names, archaeological cultures, polities, dynasties, belief traditions, movements, styles, schools, maker communities, institutions, exhibitions, networks, techniques, materials, object types, living practices, \"first known\" claims, communities (under their own names), people, places, events and period definitions. One schema for all (see `tools/codes.py`) |\n| `data/register/` | The world-set register v0 (64 objects with licence and 1970 provenance test), claims (110), practices (12), the provenance pass |\n",
"| `data/sources/` | 198 zero-cost source routes with licence and a commercial-safe flag; 130 primary texts on making with public-domain status |\n| `data/harvested/`, `data/matches/` | Written by the harvest jobs: register re-checks, UNESCO facts, Wikidata id proposals, open-object candidates |\n| `harvest/` | The harvesters (standard-library Python) and their offline tests |\n| `tools/` | Validation, coverage report, the licence switch |\n| `reports/` | Coverage by sub-region and period, validation output, UNESCO matches |\n\n## Rules the data follows\n\n- **Identifiers are never typed.** Wikidata, Getty and PeriodO ids come from the harvest as proposals, and a person accepts each one (`data/matches/wikidata_accepted.csv`).\n- **Listings and licences come from the source.** UNESCO status is taken from UNESCO's own data, and licences are checked record by record, every month and again each 2 January.\n- **Licence per record.** An old date or an anonymous maker proves nothing. Only records the holder marks CC0 or public domain, or that carry a national open licence or CC BY/BY-SA, count as open.\n",
"- **The 1970 test.** An archaeological object is an exemplar only if it left its country of origin before 17 November 1970, was excavated with a record, or was legally exported. Otherwise it is taught as a case.\n- **Sensitivity.** Human remains, sacred or secret material, and anything a descendant community asks not to show are never shown. Other grave goods are shown with their origin and a content note. People are never described as goods.\n- **Civilisation is a label.** A civilisation name is a search label that opens onto the groupings beneath it. It is never ranked, and every card says what the name leaves out.\n\n## The licence switch\n\n`tools/licence_class.py` puts every asset in one of six classes: PD-CC0, NATIONAL-OPEN, ATTRIBUTION, OWN, PERMISSION-NC and LINK-ONLY. One dataset makes two builds. The **open build** may host items a holder has permitted for free education. The **commercial build** drops them automatically and uses the fallback recorded for each. F1 is free today, and the day it charges nothing is rewritten.\n\n## Running it\n\nRun these from this folder (`modules/F1-histories-of-making/atlas`).\n\n```bash\n",
"python tools/validate_canon.py          # errors block a change; warnings are for review\npython tools/coverage.py                # reports/coverage.md\npython harvest/harvest.py data/register/world_set_v0.csv --out data/harvested/register_check.json\npython harvest/ich.py                   # UNESCO facts and proposed matches\npython harvest/wikidata_match.py --limit 100\npython harvest/candidates.py --tiers R1 --limit 20\n```\n\nPython 3.9+ and nothing else. The harvest workflow (`.github/workflows/harvest.yml` at the repository root) runs monthly and on 2 January. It opens a pull request with its results and never writes to `main` directly.\n\n## Being a good guest\n\nThe harvesters send a descriptive User-Agent and stay under each museum's rate limits: 20 requests a minute to APIs and 6 a minute to the Met's web pages. If a holder asks us to slow down or stop, we do.\n\n## Licence\n\nSee the repository's root README (decision Q43). Source data keeps its own licences, listed in `DATA_LICENCES.md`.\n\nFact-check logs, verification notes and grouping pages that used to sit beside this data now live one level up, in the module's `review-logs/`, `research/` and `grouping-pages/` folders.\n"
],
"",
"fca1155d406a138bd4a9fde7b99fe3323ac149bbeb15362fec94860bbf0e6d5e"
],
[
"modules/F1-histories-of-making/atlas/data/register/README.md",
"F1 world-set register v0 and harvester",
"readme",
"F1",
"md",
"",
"",
"",
"",
[
"# F1 world-set register v0 and harvester\n\nBuilt 2026-09-28 from the verified tables in F1 Deep Dives 1 and 2 and a provenance pass on the flagged records.\n\n| File | What it is |\n|---|---|\n| world_set_v0.csv / .json | 77 records: 64 objects plus places, documents, assets and a dataset. One row per record; `units` lists every chapter that uses it |\n| claims_v0.csv / .json | 110 claims from the eleven deep dives, each with unit, confidence and source (IDs from CL-101) |\n| practices_v0.csv | 12 living practices (PR-001 to PR-018) |\n| prov_pass.json | The provenance pass: verbatim provenance, the 1970 test result, its basis, the gap, the action |\n| harvest.py | Harvester for Cleveland, the Met and the Art Institute of Chicago. Standard library only |\n| test_harvest.py, fixtures/ | 13 offline tests on real responses saved 2026-09-28 |\n| build_register.py, build_claims.py | How v0 was built from the documents (rerun only to rebuild v0) |\n\nRun the tests: `python3 test_harvest.py`\nHarvest (needs open internet): `python3 harvest.py world_set_v0.csv --out harvested.json`\nOutput lists every record whose licence or 1970-test result differs from the register, for a person to review.\n\n",
"Status values: exemplar · case (fails the test; taught as a case) · excluded · to-license · to-source · rights-blocked.\nTest values: pass · pass-caveat · enquiry · fail · colonial-gap · n/a (not archaeological).\n\nNotes\n- The Met's open API has no provenance field; harvest.py reads it from the object page's server-rendered payload. If the Met changes its page, `met_provenance` returns None and the record is flagged, never silently passed.\n- Cleveland's `q=` search is fuzzy; harvest.py keeps only an exact accession match.\n- Rate limits are per host (Met web pages 6 a minute, APIs 20 a minute). Be gentler if a museum asks.\n"
],
"",
"abbd676f2ef5029ed7f078dac647accb5cae50ca2c6db43cda0dd9d58a2a4bb1"
],
[
"modules/F1-histories-of-making/atlas/reports/coverage.md",
"Coverage report",
"readme",
"F1",
"md",
"",
"",
"",
"",
[
"# Coverage report\n\nBands: B01 before 8000 BCE; B02 8000-4000 BCE; B03 4000-2000 BCE; B04 2000-1000 BCE; B05 1000 BCE-1 CE; B06 1-500; B07 500-1000; B08 1000-1400; B09 1400-1700; B10 1700-1900; B11 1900-now\n\n## Canon nodes per cell\n\n| Sub-region | B01 | B02 | B03 | B04 | B05 | B06 | B07 | B08 | B09 | B10 | B11 |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n| AF-EGY Egypt | 4 | 10 | 67 | 86 | 92 | 91 | 97 | 101 | 88 | 89 | 94 |\n| AF-NUB Nubia and Sudan | 1 | 3 | 16 | 21 | 21 | 21 | 19 | 20 | 19 | 19 | 23 |\n| AF-MAG Maghrib | 9 | 7 | 7 | 9 | 24 | 21 | 36 | 47 | 40 | 33 | 41 |\n| AF-SAH Sahel and Western Sudan | 5 | 11 | 12 | 15 | 24 | 26 | 32 | 55 | 69 | 57 | 72 |\n| AF-GUI Guinea Coast | 3 | 7 | 12 | 19 | 21 | 22 | 23 | 45 | 83 | 100 | 123 |\n| AF-CEN Central Africa | 8 | 7 | 9 | 14 | 18 | 18 | 21 | 29 | 48 | 57 | 63 |\n| AF-HRN Ethiopia and the Horn | 11 | 7 | 15 | 16 | 24 | 28 | 30 | 35 | 43 | 46 | 45 |\n| AF-SWA Swahili coast and East African interior | 20 | 14 | 18 | 20 | 24 | 25 | 37 | 44 | 54 | 56 | 62 |\n| AF-SOU Southern Africa | 29 | 20 | 23 | 25 | 28 | 28 | 30 | 42 | 48 | 55 | 51 |\n",
"| AF-MAD Madagascar and Indian Ocean islands | **0** | **0** | 4 | 6 | 6 | 6 | 12 | 15 | 21 | 28 | 22 |\n| AM-ARC Arctic | 3 | 5 | 9 | 9 | 11 | 10 | 12 | 21 | 22 | 22 | 28 |\n| AM-NWC Northwest Coast | 3 | 3 | 3 | 4 | 6 | 5 | 5 | 10 | 15 | 30 | 29 |\n| AM-WST North American West | 8 | 8 | 10 | 13 | 13 | 15 | 26 | 37 | 45 | 62 | 91 |\n| AM-EWD Eastern Woodlands | 2 | 10 | 16 | 18 | 24 | 21 | 25 | 26 | 44 | 106 | 162 |\n| AM-MES Mesoamerica | 5 | 13 | 14 | 31 | 50 | 47 | 65 | 66 | 71 | 39 | 41 |\n| AM-CAM Central America | 1 | 3 | 4 | 6 | 9 | 17 | 23 | 16 | 23 | 14 | 15 |\n| AM-CAR Caribbean | 2 | 2 | 5 | 5 | 8 | 6 | 10 | 13 | 38 | 40 | 40 |\n| AM-AND Andes and Pacific coast | 6 | 20 | 42 | 49 | 60 | 61 | 83 | 74 | 103 | 77 | 71 |\n| AM-AMZ Amazonia and lowland South America | 3 | 10 | 10 | 10 | 15 | 22 | 27 | 27 | 37 | 25 | 25 |\n| AM-LAT Colonial and modern Latin America | · | 1 | 4 | 4 | 8 | 8 | 10 | 18 | 76 | 85 | 95 |\n| AS-CHN China | 10 | 30 | 54 | 75 | 118 | 120 | 154 | 183 | 185 | 187 | 203 |\n| AS-KOR Korea | 1 | 4 | 7 | 14 | 28 | 30 | 41 | 44 | 55 | 51 | 53 |\n| AS-JPN Japan | 12 | 18 | 24 | 26 | 35 | 38 | 61 | 68 | 112 | 118 | 127 |\n",
"| AS-SAS South Asia | 4 | 16 | 49 | 61 | 90 | 93 | 114 | 138 | 181 | 198 | 222 |\n| AS-HIM Himalaya and Tibet | **0** | 1 | 6 | 7 | 7 | 12 | 26 | 29 | 38 | 43 | 37 |\n| AS-MSE Mainland Southeast Asia | 2 | 8 | 15 | 20 | 39 | 52 | 59 | 64 | 66 | 62 | 55 |\n| AS-ISE Island Southeast Asia | 6 | 12 | 19 | 20 | 30 | 36 | 49 | 51 | 75 | 81 | 74 |\n| AS-CEN Central Asia and the steppe | 3 | 4 | 19 | 28 | 61 | 57 | 75 | 83 | 80 | 77 | 88 |\n| AS-NTH North Asia and Siberia | 11 | 14 | 17 | 21 | 31 | 22 | 27 | 28 | 35 | 39 | 37 |\n| WA-MES Mesopotamia | 6 | 19 | 67 | 63 | 72 | 55 | 81 | 83 | 71 | 75 | 83 |\n| WA-IRN Iran | 2 | 10 | 38 | 34 | 61 | 50 | 72 | 98 | 98 | 89 | 84 |\n| WA-LEV Levant | 19 | 27 | 38 | 55 | 71 | 66 | 62 | 67 | 61 | 58 | 67 |\n| WA-ARB Arabia and the Gulf | 1 | 6 | 25 | 25 | 33 | 32 | 40 | 42 | 41 | 41 | 51 |\n| WA-ANA Anatolia | 11 | 23 | 29 | 45 | 56 | 52 | 54 | 76 | 87 | 76 | 70 |\n| WA-CAU Caucasus | 9 | 12 | 18 | 19 | 26 | 22 | 23 | 32 | 32 | 33 | 35 |\n| EU-GRR Greek and Roman Mediterranean | 1 | 6 | 22 | 53 | 101 | 74 | 58 | 64 | 68 | 70 | 56 |\n| EU-BYZ Byzantium and the Balkans | 3 | 16 | 13 | 13 | 18 | 24 | 37 | 40 | 40 | 30 | 31 |\n",
"| EU-WCE Western and Central Europe | 33 | 33 | 47 | 53 | 76 | 74 | 89 | 117 | 167 | 229 | 267 |\n| EU-BLC Britain, Ireland and the Low Countries | 5 | 9 | 20 | 19 | 33 | 36 | 49 | 64 | 88 | 181 | 145 |\n| EU-IBE Iberia | 11 | 5 | 9 | 11 | 23 | 16 | 31 | 44 | 54 | 43 | 32 |\n| EU-EER Eastern Europe and Russia | 6 | 13 | 22 | 19 | 22 | 18 | 25 | 41 | 47 | 53 | 68 |\n| EU-SCA Scandinavia, the Baltic and Sapmi | 8 | 17 | 19 | 18 | 18 | 22 | 32 | 43 | 35 | 38 | 44 |\n| OC-AUS Australia | 30 | 39 | 41 | 41 | 43 | 43 | 43 | 43 | 43 | 55 | 83 |\n| OC-MEL Melanesia | 4 | 7 | 10 | 18 | 23 | 15 | 16 | 16 | 26 | 34 | 43 |\n| OC-MIC Micronesia | · | · | 2 | 4 | 7 | 7 | 9 | 17 | 16 | 14 | 17 |\n| OC-POL Polynesia | 3 | 6 | 10 | 17 | 26 | 19 | 19 | 44 | 42 | 65 | 69 |\n\nGaps (0): 3. Thin (1-2): 13. '·' = no people there yet.\n\n## Verified open objects per cell\n\nNo harvest yet (data/harvested/objects.json missing).\n"
],
"",
"284ad4d5a5f187f7f81563975581479ea0392bcfd7684fcc9fcebc7e6434ddd7"
],
[
"modules/F1-histories-of-making/atlas/reports/validation.txt",
"validation.txt",
"readme",
"F1",
"txt",
"",
"",
"",
"",
[
"warn  canon_beliefs.csv BEL003: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_beliefs.csv BEL004: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV001: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV003: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV015: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV044: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV068: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV078: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV085: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_civilisations.csv CIV086: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_civilisations.csv CIV088: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN002: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN004: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN012: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN014: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN023: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN029: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN051: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN052: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN061: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_dynasties.csv DYN066: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN075: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_dynasties.csv DYN076: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_makers_institutions.csv MKR015: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_makers_institutions.csv EVT026: banned phrase in making_significance: 'tribal'\nwarn  canon_movements_styles_schools.csv STY003: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY004: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY006: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY014: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_movements_styles_schools.csv STY016: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY019: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY026: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY091: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY096: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_movements_styles_schools.csv STY107: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_people.csv PER072: prose names coerced labour but the human-flow flag is missing\nwarn  canon_people.csv PER128: banned phrase in making_significance: 'primitive'\nwarn  canon_people.csv PER378: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_places.csv PLC186: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_polities.csv POL001: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL003: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL005: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL007: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL019: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL026: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL029: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL040: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL041: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL046: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_polities.csv POL051: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL055: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL068: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL075: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL082: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL089: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL093: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL095: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL096: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL102: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_polities.csv POL116: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL117: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL118: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL121: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL122: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL123: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL124: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL131: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL132: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL133: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_polities.csv POL141: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL148: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL153: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL154: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL160: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL193: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL200: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL209: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL213: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL217: review: leaves_out names coerced labour; decide whether the row needs human-flow\n",
"warn  canon_polities.csv POL228: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_polities.csv POL232: review: leaves_out names coerced labour; decide whether the row needs human-flow\nwarn  canon_techniques.csv TEC042: review: leaves_out names coerced labour; decide whether the row needs human-flow\n4228 rows in 19 files: 0 errors, 82 warnings\n"
],
"",
"8a0d8f91c24d09367629c30b0efcca1eafe3041758152b5ef7f83128117c92b6"
],
[
"modules/F1-histories-of-making/briefs/BRIEF.md",
"Brief for canon-register drafting (F1 \"Histories of making\")",
"brief",
"F1",
"md",
"",
"",
"",
"",
[
"# Brief for canon-register drafting (F1 \"Histories of making\")\n\n## The project\nF1 is the first module of a self-paced design-education web app for designers, brand/marketing people, founders and commissioning clients. It teaches a *global* history of making (objects, techniques, materials, makers, institutions, routes) across the whole timeline, \"as a web, not a line\". Its knowledge system is the **Atlas**: every thing is a *node* with one card; *groupings* (cultures, polities, movements, networks, guilds, civilisations-as-commonly-named, etc.) are nodes whose members are other nodes. Hard rules:\n- **Zero cost.** Only free, open sources. Images only where the licence permits reuse (CC0, public domain, CC BY, CC BY-SA, KOGL Type 1, Japan Government Standard Terms). Anything else is linked out, never hosted.\n- **\"Civilisation\" is never the frame.** It is a searchable label (\"civilisation, as commonly named\") whose card opens onto the precise groupings underneath and says what the name leaves out (neighbours, stateless peoples, enslaved makers, present-day communities). Never ranked, no \"rise and fall\" unless evidence supports it.\n",
"- **Sensitivity (CARE principles).** Sacred, ancestral and funerary material is excluded from display by default unless community-published; material from Indigenous communities carries a Notice. Human beings are never drawn as goods (Atlantic and other slave trades are shown as people, with a content note).\n- **Ages are regional.** \"Bronze Age\" etc. always carry the region they were defined for.\n\nThe user has asked us to expand scope to EVERYTHING: all civilisations, cultures, polities, movements, networks, techniques, materials, object types, practices — not a favourite few. Your job is to draft a COMPLETE, ACCURATE register for your assigned families. Completeness matters, but accuracy matters more: include only entities you are confident exist and are named as you name them. Never invent identifiers (no Wikidata QIDs, no accession numbers, no URLs you are not sure of). Dates are approximate ranges; mark uncertainty.\n\n## Tiers (propose one per row)\n- **R1**: taught inside a unit, gets a full grouping page with an authored 6–9 step walk. Choose where the entity carries a lesson about making that a unit needs (not merely because it is famous).\n",
"- **R2**: card + member grid, no walk. Needs at least five verifiable member objects/nodes from free sources.\n- **R3**: card + link out (Wikidata/PeriodO/collection search). Everything else. Every row gets at least R3.\n\n## World chapters (column `world`)\nF1.6 Africa · F1.7 The Americas · F1.8 East Asia · F1.9 South and Southeast Asia · F1.9a West Asia before Islam · F1.10 The Islamic world (network, 7th c. on) · F1.11 Europe and the Mediterranean · F1.12 Australia and the Pacific · F1.12a The steppe and Central Asia · F1.13 Networks · THEME (belongs to a thematic unit rather than a world). Multiple allowed, separated by `;`.\n\n",
"Thematic units (column `units`, optional, `;`-separated): F1.2 reference-to-appropriation · F1.3 how histories get written · F1.4 film/performance/sound/games · F1.5 recurrences (writing, cities, metallurgy, weaving, printing invented many times) · F1.13 networks · F1.14 copying, transfer, counterfeit · F1.15 ornament; exhibitions · F1.16 ritual and belief · F1.17 who commissions (patrons, guilds, merchants, industry, agencies, platforms) · F1.18 textiles and \"women's work\" · F1.19 industry, the machine, the exhibition · F1.19a war and crisis · F1.20 modernisms, plural · F1.21 consumer society, digital, platform · F1.22 planetary present, extraction · F1.22a use, repair, consumption · F1.23 obscured labour · F1.24 museum, provenance, restitution · F1.26 attribution and consultation · F1.28 primary sources · F1.28a reconstruction · F1.29 vernacular/oral · F1.30 calendars and periodisations.\n\n## Sub-region codes (column `sub_regions`, `;`-separated)\n",
"AF-EGY Egypt · AF-NUB Nubia and Sudan · AF-MAG Maghrib · AF-SAH Sahel and Western Sudan · AF-GUI Guinea Coast · AF-CEN Central Africa · AF-HRN Ethiopia and the Horn · AF-SWA Swahili coast and East African interior · AF-SOU Southern Africa · AF-MAD Madagascar and Indian Ocean islands ·\nAM-ARC Arctic · AM-NWC Northwest Coast · AM-WST North American West (Southwest, Plains, Great Basin, California) · AM-EWD Eastern Woodlands · AM-MES Mesoamerica · AM-CAM Central America (Isthmo-Colombian) · AM-CAR Caribbean · AM-AND Andes and Pacific coast · AM-AMZ Amazonia and lowland South America · AM-LAT Colonial and modern Latin America ·\nAS-CHN China · AS-KOR Korea · AS-JPN Japan · AS-SAS South Asia · AS-HIM Himalaya and Tibet · AS-MSE Mainland Southeast Asia · AS-ISE Island Southeast Asia · AS-CEN Central Asia and the steppe · AS-NTH North Asia and Siberia ·\nWA-MES Mesopotamia · WA-IRN Iran · WA-LEV Levant · WA-ARB Arabia and the Gulf · WA-ANA Anatolia · WA-CAU Caucasus ·\n",
"EU-GRR Greek and Roman Mediterranean · EU-BYZ Byzantium and the Balkans · EU-WCE Western and Central Europe · EU-BLC Britain, Ireland and the Low Countries · EU-IBE Iberia · EU-EER Eastern Europe and Russia · EU-SCA Scandinavia, the Baltic and Sápmi ·\nOC-AUS Australia · OC-MEL Melanesia · OC-MIC Micronesia · OC-POL Polynesia (incl. Aotearoa, Hawaiʻi) · GL Global/many.\n\n## Functions (column `functions`, the Atlas's twelve, `;`-separated)\nshelter · clothing and adornment · food and storage · tools · record and writing · exchange and value · ritual and belief · rule and display · war · play and music · care and access · transport\n\n## CSV schema (exact header, this order)\nid,name,other_names,kind,family,world,sub_regions,start,end,date_note,making_significance,materials_techniques,object_types,functions,defined_by,leaves_out,sensitivity,free_sources,tier,units,confidence,notes\n\n- `id`: your prefix + 3 digits (prefix given in your task).\n- `kind`: one of the grouping kinds or node types named in your task.\n- `family`: Place | Time | People | Ideas | Connections | Things | Composite | Source.\n",
"- `start`,`end`: integer years, negative = BCE (e.g. -2600). Leave `end` empty for ongoing. Approximate is fine; say so in `date_note`.\n- `making_significance`: ONE plain sentence on what it made or why it matters to a history of making. No adjectives like \"stunning\", \"iconic\".\n- `materials_techniques`, `object_types`: short `;`-lists.\n- `defined_by`: who defined/named the grouping (archaeologists, the members themselves, a named scholar, museums, historians, the state…).\n- `leaves_out`: mandatory for civilisation names, polities, movements; optional elsewhere.\n- `sensitivity`: none | sacred | funerary | ancestral | Indigenous-community | human-flow | conflict-looting | living-community (`;`-list).\n- `free_sources`: named zero-cost routes where material can come from (e.g. \"Met Open Access (CC0); Cleveland (CC0); Wikimedia Commons; Europeana; British Museum EMKP (CC); open-access excavation reports; community-published site\"). Only name routes you believe hold relevant material.\n- `confidence`: high | medium | low — your confidence in the row's facts.\n- `notes`: anything a verifier should check.\n\n",
"Write the CSV with Python's `csv` module (QUOTE_MINIMAL) so commas inside fields are safe. UTF-8. Save to the path given in your task. Aim for breadth across ALL sub-regions and ALL periods, deliberately including Africa, the Americas, Oceania, the steppe, Southeast Asia, the Caucasus, Arabia, the Arctic, Madagascar, the Himalaya, Amazonia, the Caribbean — not only the regions museums favour. Also include the 20th–21st century where the family applies.\n\nWhen done, reply with: file path(s), row count per file, count of rows per world, and a short list (≤10) of rows you are least sure of.\n"
],
"",
"aea95a4d49b00ea267308d7bec4dbdc86ec2164011e5b46b8c6ea40590cc2b72"
],
[
"modules/F1-histories-of-making/briefs/BRIEF_ADDENDUM_v2.md",
"Addendum to BRIEF.md — new families (round 2)",
"brief",
"F1",
"md",
"",
"",
"",
"",
[
"# Addendum to BRIEF.md — new families (round 2)\n\nRound 1 built 2,430 canon nodes in 20 kinds (civilisations, cultures, horizons, polities, dynasties, beliefs, movements, styles, schools, maker communities, institutions, exhibitions/events, networks, diasporas, techniques, materials, object types, living practices, first-known claims). Files: /tmp/claude-0/-home-claude/76042139-a9b9-5b20-8cec-5583346d0a7e/scratchpad/f1-scope/canon/canon_*.csv. Read the relevant ones before drafting so you link to (and do not duplicate) what exists; put related canon IDs in `notes` as \"links: CIV012; POL021\".\n\nSame CSV schema, same codes, same rules as BRIEF.md. Lessons from the fact-check of round 1 — apply them:\n- Do not overstate in `making_significance` (\"built\", \"invented\", \"first\", \"produced\") beyond what the evidence supports; say \"credited with\", \"is associated with\", \"earliest known\" where appropriate.\n- If the prose names coerced, enslaved or indentured labour, the `sensitivity` column MUST include human-flow.\n- Never type a UNESCO status, licence or identifier you have not verified; write \"to verify\" instead.\n- Dates are ranges; wrong is worse than approximate.\n\nNew kinds:\n",
"- `person` (prefix PER), family People: named makers, workshop heads, designers, architects of objects, patrons and commissioners, theorists and writers on making, collectors and museum founders, restitution actors, scholars who defined groupings. `start`/`end` = birth/death (or floruit with date_note \"fl.\"). `leaves_out` = who is obscured by crediting this person (assistants, wives, enslaved or anonymous workshop members, the community whose designs they used). Living people: include only those who publicly present themselves as makers or public figures; add \"living\" to sensitivity as `living-community`.\n- `place` (prefix PLC), family Place: sites of making and exchange — workshops, kiln sites, mines and quarries, ports and markets, excavated sites, craft quarters and streets, museums that hold or authored collections, world's-fair grounds. `start`/`end` = period of the activity that matters to F1.\n",
"- `event` (prefix OCC), family Time: occurrences that changed making — laws and bans (sumptuary laws, the Calico Acts, the Navigation Acts, NAGPRA, the UNESCO 1970 Convention, the Indian Arts and Crafts Act), patents, treaties, wars, sieges and lootings (Benin 1897, the Summer Palace 1860, Maqdala 1868), fires and disasters, epidemics, migrations, restitutions and returns, founding of key institutions (if not already in canon), technological turning points already not in the firsts file.\n- `period` (prefix PRD), family Time: period definitions as named by a specific source for a specific region (Heian; Edo; Classic Maya; Old Kingdom; Tang; Abbasid; Archaic Greece; Late Antiquity; Jōmon periods; Bronze/Iron Ages ALWAYS with region). `defined_by` = the scholarly tradition or source that defines it. PeriodO is the eventual gazetteer; do not type PeriodO IDs.\n"
],
"",
"5fe4b730cb560414b87ac8938adfd68f5fa384f92d0be93d92ce2c709d5ceb68"
],
[
"modules/F1-histories-of-making/briefs/GROUPING_PAGE_BRIEF.md",
"Brief: writing a grouping page for the F1 Atlas",
"brief",
"F1",
"md",
"",
"",
"",
"",
[
"# Brief: writing a grouping page for the F1 Atlas\n\nF1 \"Histories of making\" is the first module of a self-paced design-education web app (designers, brand people, founders, commissioning clients). Its Atlas holds nodes (objects, places, people, practices, techniques…) and groupings (cultures, polities, networks, movements, horizons, institutions, civilisation-names…). Every grouping gets a page that tells it as a story. Three pages already exist as the pattern — Mingei (movement), Nok (archaeological culture), the Igun Eronmwon guild (maker community) — in the Claude Docs document \"F1 Groundwork\" (project id 6d02bdf9-1689-4a2b-b1fe-258e11817b83, prose node 65518300-dfe7). Read them with the Claude Docs `read` tool if it is available to you: first `{\"projection\":\"outline\"}`, then `{\"kind\":\"view\",\"parentId\":\"<table id>\"}` for each Card and Walk table under the three \"Grouping page\" headings. If you cannot read the doc, follow the structure below exactly.\n\n## Page structure (markdown)\n1. `## Grouping page: <name>` then one lead sentence (the point, ≤ 25 words).\n",
"2. **Card** — a table: Kind · Defined by (who, when) · Span · Places · Membership confidence · Leaves out · Rights line (what may be shown and from where).\n3. **Walk** — a table of 6–9 steps: # · Step title · What the learner sees and reads (2–3 sentences) · Nodes (canon IDs where they exist, e.g. NET002, PLC114; objects as \"Met 1985.xxx\" only if you verified the record) · Claim and confidence (documented / probable / contested / interpretive).\n4. **Members** — one paragraph counting members by type, naming the key ones.\n5. **Neighbours** — the groupings it defined itself against and parallel groupings elsewhere.\n6. **Afterlives** — revivals, living practice (dated to its source, e.g. \"in 2024…\"), how it is sold or remembered.\n7. **What is argued** — 2–4 bullets, each giving both readings with sources.\n8. **Apply** — the unit that uses it, with a Maker (M) and a Briefer (B) task.\n",
"9. **Candidate open objects** — up to 8 real records you verified, each: holder, accession/ID, date range, licence as the holder states it (CC0 / public domain / CC BY…), the 1970 provenance status if the record states acquisition history, and the record URL. Only commercially reusable licences (CC0, PD, CC BY, CC BY-SA, KOGL Type 1). If none exists, say so and propose the living practice, a drawing of our own, or a link-out instead.\n10. **Sources** — the pages you actually opened, as [title](url).\n\n## Rules (the program's writing standard — apply all)\n",
"1. Start from the object, the place or the person, not the category. 2. First sentence of each step ≤ 16 words. 3. Say who made it even when unnamed (\"casters of the guild\", not \"Benin bronze\"). 4. Dates as ranges with the source's qualifier. 5. Confidence grammar: documented stated plainly; probable = \"probably\"/\"most specialists\"; contested = \"argued\", both readings; interpretive = \"we read it as\". 6. \"Earliest known\", never \"first\". 7. Name violence plainly; perpetrators' terms in quotation marks, attributed. 8. Community's own name first. 9. Never \"primitive\", \"tribal\", \"lost civilisation\", \"exotic\", \"mysterious\", \"discovered\" (for places people knew). 10. Date living practices to their source. 11. Admit what is not known. 12. Each tier true on its own. Also: human beings are never described as goods or cargo (content note where enslaved people appear); sacred, secret and funerary material and human remains are never shown (grave goods only with origin and a content note, never where a descendant community objects); \"civilisation\" is a search label that opens onto groupings beneath it, never ranked, no rise-and-fall unless evidenced. No AI filler (\"rich tapestry\", \"testament to",
"\", \"stands as\"). Plain words, sentences under 25 words.\n\n## Canon\nThe canon register (IDs to cite) is at /tmp/claude-0/-home-claude/76042139-a9b9-5b20-8cec-5583346d0a7e/scratchpad/f1-scope/canon/canon_*.csv. Use grep to find the rows for your grouping and its members; cite their IDs.\n\n## Tools\nUse WebSearch/WebFetch for research (the shell cannot reach websites). Museum APIs: Cleveland (openaccess-api.clevelandart.org), the Met (collectionapi.metmuseum.org — the Met's public-domain search filter returns non-public-domain objects, so check `isPublicDomain` on each record), AIC (api.artic.edu). WebFetch may cache or strip query parameters; if a query returns the wrong thing, you may use the Firecrawl scrape tool with `formats:[\"rawHtml\"]`, but no more than 15 Firecrawl calls in total (they cost the user credits).\n"
],
"",
"18b6370fbc5ac46f289392fa14995fae6df1694e2e57e6497cc6fd8d6ec9bf4c"
],
[
"modules/F1-histories-of-making/briefs/SPEC_BRIEF.md",
"Brief: writing an F1 unit spec (batch 1), template v3, to the F1.17 standard",
"brief",
"F1",
"md",
"",
"",
"",
"",
[
"# Brief: writing an F1 unit spec (batch 1), template v3, to the F1.17 standard\n\n## The program and the module\nA self-paced design-education web app for designers, brand/marketing people, founders and commissioning clients. Two lanes in every unit: **Maker (M)** and **Briefer (B)**. Depths: Orientation (O), Practice (P), Mastery (M). Every learner builds one artifact (the \"Concept DNA\"); units write into its fields: SRC (sources record), GRM.f / GRM.n / GRM.m (grammar: form, narrative, material), CMB (commissioning brief), PLW (planetary weight), LCY (lifecycle), RGT (rights), PRM (premise), DOS (dossier), PER (persona). Partner voices (AI partners with declared agendas): Historian, Mirror, Client, Fabricator, Planet, Stranger. Presentation forms by number: 1 scrollytelling, 2 step-through, 3 object story, 4 explorable, 5 before/after, 7 video, 8 audio, 10 comparison wall, 11 timeline scrub, 12 map, 13 argument card, 14 sequential illustration, 15 prediction prompt. Threads: Attribution and Authority; Planetary Weight; Writing and Argument; Accessibility (level 1 starts in F1).\n\n",
"F1 \"Histories of making\": threshold concept \"design history is a web with obscured strands, not a line\". Its Atlas has nodes and groupings; the canon register (IDs to cite) is at /tmp/claude-0/-home-claude/76042139-a9b9-5b20-8cec-5583346d0a7e/scratchpad/f1-scope/canon/canon_*.csv (4,228 rows: CIV civilisation names, ARC cultures, HOR horizons, POL polities, DYN dynasties, BEL beliefs, MOV/STY/SCH movements, styles, schools, MKR/INS/EVT makers, institutions, exhibitions, NET/ISP/DIA networks, TEC techniques, MAT materials, OBT object types, PRA living practices, INV first-known claims, COM communities, PER people, PLC places, OCC events, PRD periods, GAP round-2 additions). Primary texts: canon/primary_texts.csv (TXT ids). Existing verified objects: /tmp/claude-0/-home-claude/76042139-a9b9-5b20-8cec-5583346d0a7e/scratchpad/register/world_set_v0.csv (WS ids) and claims_v0.csv (CL ids). Grep them.\n\n## The exemplar format (F1.17, already approved as the standard) — a table with these rows, in this order\n",
"Essential question · Opening move (with a claim and counter-claim or the prediction/object that opens it, and one case) · Lab or main interactive · Concept (length in words and what it covers) · Cases (usually three, one object story each) · Apply — maker · Apply — briefer · Partner (the voice, its question, and the test it ends with) · Forms (numbers) · Consumption forms (Five-minute · Session · Reference) · Media · Artifact fields · Threads · Closing contribution (one line in the sources record) · Claims sheet.\n\n## Template v3 additions (write each as its own section after the table)\n1. **Responsibility block.** Which canon groupings, object types, sub-regions and periods this unit must reach (canon IDs), and which the Atlas carries instead. Thematic units must reach at least four of the nine world chapters (F1.6 Africa, F1.7 Americas, F1.8 East Asia, F1.9 South and Southeast Asia, F1.9a West Asia before Islam, F1.10 Islamic world, F1.11 Europe and the Mediterranean, F1.12 Australia and the Pacific, F1.12a steppe and Central Asia) with a case or example — say which.\n",
"2. **Protocol screen.** Never human remains, sacred or secret material, or anything a descendant community asks not to show; other grave goods and altar objects only with origin and a content note; a Notice on every Indigenous community's material; people never described as goods.\n3. **Claims (12–20).** Each: the claim in plain words; confidence (documented / probable / contested — give both readings / interpretive); the source you actually opened (URL); how deep that source goes (full text / abstract / summary). Declare the unit's own framing as an interpretive claim. \"Earliest known\", never \"first\".\n4. **Nodes.** For each case and claim, the canon IDs that carry it; propose new canon rows (name, kind) where a node is missing.\n",
"5. **Candidate open objects (3–6).** Real records you verified at source: holder, accession, date range, licence as the holder states it (only CC0, public domain, CC BY, CC BY-SA, KOGL Type 1 count as open), 1970 provenance status where archaeological (\"n/a\" for decorative or signed modern work), record URL. The Met's search filter returns non-public-domain records: check `isPublicDomain` on each record. If no open object exists, say so and propose a drawing of our own, a living practice or a link out.\n6. **People and credit.** Named makers where the record allows; who the credit leaves out.\n7. **Visual plan (zero cost).** For each form, where its images come from: open record, national licence, attribution licence, our own drawing, map or diagram, or link out. No generated images of historical objects, people or places.\n8. **Success criteria.** Three observable criteria, none taking a side in a live debate.\n9. **Readings and risks.** What the Historian pre-read (pack v2) should check; sensitive steps to hold until a reader clears them.\n",
"10. **Fact-check list.** Every row a checker must confirm at source before G3 (R1/R2 canon rows used, living people, endonyms, UNESCO claims, licences).\n\n## Writing standard (apply to all prose)\nStart from the object, place or person. First sentence of a paragraph ≤ 16 words; sentences under 25 words. Say who made it, even unnamed. Dates as ranges with the source's qualifier. Confidence in the words. Name violence plainly; perpetrators' terms in quotation marks and attributed. Community's own name first. Never \"primitive\", \"tribal\", \"lost civilisation\", \"exotic\", \"mysterious\", \"discovered\" (for places people knew), and no AI filler (\"rich tapestry\", \"testament to\", \"stands as\"). Admit what is not known. Plain words, no adjectives of praise.\n\n## Rules\n- Zero cost: only free sources; images only where the licence allows reuse; everything else linked.\n- Research with WebSearch/WebFetch (the shell cannot reach websites). Museum APIs: Cleveland (openaccess-api.clevelandart.org, add cc0=1), the Met (collectionapi.metmuseum.org), AIC (api.artic.edu). Firecrawl scrape costs the user credits: at most 10 calls.\n",
"- Never invent a URL, accession number or identifier. If you could not verify something, say \"not verified\".\n- Length: the table plus the ten sections, about 2,000–3,000 words.\n\n## Output\nSave the spec as markdown to /tmp/claude-0/-home-claude/76042139-a9b9-5b20-8cec-5583346d0a7e/scratchpad/f1-scope/specs/<unit>.md (e.g. F1.1.md), starting with `## <unit> <title>` then one lead sentence (the unit's point), then **Spec** (the table), then the ten sections as `**1. Responsibility block**` etc. (bold labels, not headings). Create the folder if missing. Do not edit any other file.\n"
],
"",
"3a361286a0b4f8f69b2a6e459306dbe3cd504a0fc477cf59a2437ba3e8cf57c8"
],
[
"modules/F1-histories-of-making/design/mockups/project/A-Phone.dc.html",
"A-Phone.dc.html",
"mockup",
"F1",
"html",
"",
"",
"",
"",
[
"<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>F1.1 One object, three readings — phone</title>\n<script src=\"./support.js\"></script>\n</head>\n<body>\n<x-dc>\n<helmet>\n<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&amp;family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&amp;display=swap\">\n<style>\nbody{margin:0;background:#F3EDE3;font-family:'IBM Plex Sans',system-ui,sans-serif;color:#1E1A15}\na{color:#2F4470}a:hover{color:#1C2B4A}\nbutton,input{font-family:inherit}\n</style>\n</helmet>\n<div style=\"width: 390px; height: 844px; box-sizing: border-box; display: flex; flex-direction: column; background: #F3EDE3; color: #1E1A15; font-family: 'IBM Plex Sans', system-ui, sans-serif;\">\n\n  <header style=\"height: 52px; box-sizing: border-box; padding: 0 12px; display: flex; align-items: center; gap: 8px; background: #FBF8F2; border-bottom: 1px solid #DCD3C4;\">\n    <button type=\"button\" aria-label=\"Back to module\" style=\"width: 44px; height: 44px; border: 0; background: transparent; display: flex; align-items: center; justify-content: center;\">\n",
"      <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#1E1A15\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M15 5l-7 7 7 7\"></path></svg>\n    </button>\n    <span style=\"flex-grow: 1; font-size: 13px; color: #574E42;\">F1.1 · Orientation · 5 of 12 min</span>\n    <span style=\"font-size: 12px; padding: 5px 9px; border: 1px solid #DCD3C4; border-radius: 999px; color: #574E42;\">Record · 0</span>\n  </header>\n\n  <section aria-label=\"Atlas strip\" style=\"padding: 12px 16px 0;\">\n    <div role=\"img\" aria-label=\"Image placeholder: proto-cuneiform tablet\" style=\"height: 176px; border-radius: 8px; background: repeating-linear-gradient(135deg, #D8CDB9 0 10px, #D2C6B0 10px 20px); display: flex; align-items: flex-end; justify-content: space-between; padding: 10px; box-sizing: border-box;\">\n      <span style=\"font-size: 12px; color: #574E42; background: #FBF8F2; padding: 4px 8px; border-radius: 6px;\">[Object image · CC0]</span>\n      <button type=\"button\" style=\"height: 36px; padding: 0 12px; border: 0; border-radius: 8px; background: #1E1A15; color: #FBF8F2; font-size: 13px;\">Open in Atlas</button>\n    </div>\n  </section>\n\n",
"  <main style=\"flex-grow: 1; padding: 16px 16px 0; display: flex; flex-direction: column; gap: 12px; min-height: 0;\">\n    <h1 style=\"margin: 0; font-family: 'Newsreader', Georgia, serif; font-size: 26px; line-height: 1.15; font-weight: 500;\">One object, three readings</h1>\n    <p style=\"margin: 0; font-size: 14px; line-height: 1.5; color: #3A332B;\">Read it before anyone tells you about it. One line each — guesses are the point.</p>\n\n    <div style=\"display: flex; flex-direction: column; gap: 10px;\">\n      <div style=\"display: flex; flex-direction: column; gap: 4px;\">\n        <label for=\"m1\" style=\"font-size: 13px; font-weight: 600;\">1 · What is it made of?</label>\n        <input id=\"m1\" type=\"text\" value=\"stone, carved\" style=\"height: 44px; box-sizing: border-box; padding: 0 12px; border: 1px solid #C9BCA4; border-radius: 8px; background: #FFFFFF; font-size: 15px; color: #1E1A15;\">\n      </div>\n      <div style=\"display: flex; flex-direction: column; gap: 4px;\">\n        <label for=\"m2\" style=\"font-size: 13px; font-weight: 600;\">2 · Who made it?</label>\n",
"        <input id=\"m2\" type=\"text\" value=\"a scribe for a king\" style=\"height: 44px; box-sizing: border-box; padding: 0 12px; border: 1px solid #C9BCA4; border-radius: 8px; background: #FFFFFF; font-size: 15px; color: #1E1A15;\">\n      </div>\n      <div style=\"display: flex; flex-direction: column; gap: 4px;\">\n        <label for=\"m3\" style=\"font-size: 13px; font-weight: 600;\">3 · What was it for?</label>\n        <input id=\"m3\" type=\"text\" placeholder=\"Your reading\" style=\"height: 44px; box-sizing: border-box; padding: 0 12px; border: 1px solid #C9BCA4; border-radius: 8px; background: #FFFFFF; font-size: 15px; color: #1E1A15;\">\n      </div>\n    </div>\n\n    <button type=\"button\" style=\"height: 48px; border: 0; border-radius: 10px; background: #A0431F; color: #FFFFFF; font-size: 15px; font-weight: 500;\">Reveal the record</button>\n    <span style=\"font-size: 12px; color: #6B6154; text-align: center;\">The rest of this unit waits for your desk session.</span>\n  </main>\n\n  <nav aria-label=\"Sections\" style=\"height: 64px; box-sizing: border-box; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); border-top: 1px solid #DCD3C4; background: #FBF8F2;\">\n",
"    <button type=\"button\" aria-current=\"page\" style=\"border: 0; background: transparent; font-size: 12px; font-weight: 600; color: #A0431F; border-top: 2px solid #A0431F;\">Unit</button>\n    <button type=\"button\" style=\"border: 0; background: transparent; font-size: 12px; color: #574E42; border-top: 2px solid transparent;\">Atlas</button>\n    <button type=\"button\" style=\"border: 0; background: transparent; font-size: 12px; color: #574E42; border-top: 2px solid transparent;\">Record</button>\n    <button type=\"button\" style=\"border: 0; background: transparent; font-size: 12px; color: #574E42; border-top: 2px solid transparent;\">Historian</button>\n  </nav>\n</div>\n</x-dc>\n<script type=\"text/x-dc\" data-dc-script data-props='{\"$preview\":{\"width\":390,\"height\":844}}'>\nclass Component extends DCLogic {\n  renderVals() { return {}; }\n}\n</script>\n</body>\n</html>\n"
],
"",
"fc574d460ef0ce4b35d27ef4335caaf81afe757ffed7cb256d82da130202415d"
]
]$cwb$::jsonb) x
on conflict ("path") do nothing;
