insert into public.documents ("path", "title", "kind", "module", "format", "artifact_url", "docs_id", "tab_name", "rev", "content", "pdf_path", "sha256")
select public.cw_text(x->0), public.cw_text(x->1), public.cw_text(x->2), public.cw_text(x->3), public.cw_text(x->4), public.cw_text(x->5), public.cw_text(x->6), public.cw_text(x->7), public.cw_text(x->8), public.cw_text(x->9), public.cw_text(x->10), public.cw_text(x->11)
from jsonb_array_elements($cwb$[
[
"modules/F1-histories-of-making/review-logs/REVIEW_LOG_people.md",
"Review log: people/grouping registers (independent fact-check)",
"review-log",
"F1",
"md",
"",
"",
"",
"",
[
"# Review log: people/grouping registers (independent fact-check)\n\n| id | field | old | new | source URL |\n|---|---|---|---|---|\n| DYN004 | making_significance | The Eighteenth Dynasty introduced large-scale glassmaking, built Karnak and the Amarna city, and filled royal tombs such as Tutankhamun's. | The Eighteenth Dynasty introduced large-scale glassmaking, greatly expanded the Middle Kingdom temple at Karnak, built the Amarna city, and filled royal tombs such as Tutankhamun's. | https://en.wikipedia.org/wiki/Karnak |\n| DYN033 | making_significance | King Lalibela's reign produced the rock-hewn churches of Lalibela. | Tradition credits King Lalibela (r. c. 1181–1221) with the rock-hewn churches of Lalibela, though archaeologists date some of the complex earlier. | https://www.metmuseum.org/toah/hd/lali/hd_lali.htm |\n| DYN082 | start | 1071 | 1072 | https://en.wikipedia.org/wiki/Siege_of_Palermo_(1071%E2%80%931072) |\n| DYN082 | date_note | Norman conquest of Palermo 1071; kingdom from 1130 | Norman siege of Palermo 1071, city taken January 1072; kingdom from 1130 | https://en.wikipedia.org/wiki/Siege_of_Palermo_(1071%E2%80%931072) |\n",
"| POL036 | making_significance | Mali's rulers funded earthen mosques and scholarship at Timbuktu and Djenné and sent gold across the Mediterranean. | Mali's rulers funded earthen mosques and scholarship at Timbuktu, and Sahelian gold under their control reached Mediterranean markets across the Sahara. | https://en.wikipedia.org/wiki/Djenn%C3%A9 |\n| POL036 | notes | Keïta dynasty is a DYN row. Djinguereber attribution to al-Sahili is traditional. | Keïta dynasty is a DYN row. Djinguereber attribution to al-Sahili is traditional. Djenné was at most an intermittent tributary of Mali (Tarikh al-Sudan says never conquered), so its mosque is not credited to Mali. | https://en.wikipedia.org/wiki/Djenn%C3%A9 |\n| POL044 | making_significance | Teotihuacan housed craft workshops in apartment compounds producing obsidian tools, Thin Orange ware, murals and stone masks. | Teotihuacan housed craft workshops in apartment compounds producing obsidian tools, pottery, murals and stone masks, and distributed Thin Orange ware made in southern Puebla. | https://www.cambridge.org/core/services/aop-cambridge-core/content/view/S0956536100000201 |\n",
"| POL151 | sensitivity | none | human-flow | https://en.wikipedia.org/wiki/Belbaltlag |\n| POL073 | sensitivity | living-community | human-flow;living-community | https://en.wikipedia.org/wiki/Quilombo_dos_Palmares |\n| ARC151 | start | -1750 | -1400 | https://sciencedirect.com/science/article/pii/S2352226724000709 |\n| ARC151 | date_note | c. 1750–1100 BCE (Lhasa) | early phase at the type site re-dated to c. 1400–1300 cal BCE by 2024 re-excavation (earlier estimates c. 2000–1500 or 1750–1100 BCE); end approximate (Lhasa) | https://sciencedirect.com/science/article/pii/S2352226724000709 |\n| ARC151 | making_significance | Settlements near Lhasa with burnished black pottery and some metal. | A Neolithic settlement near Lhasa whose potters made polished, incised and stamped round-based wares. | https://sciencedirect.com/science/article/pii/S2352226724000709 |\n| ARC151 | materials_techniques | burnished pottery; copper | burnished pottery; incised and stamped decoration | https://sciencedirect.com/science/article/pii/S2352226724000709 |\n",
"| ARC151 | notes | (empty) | Copper/metal claim removed: not reported in the 2024 re-excavation (Neolithic assemblage); restore only with a source. | https://sciencedirect.com/science/article/pii/S2352226724000709 |\n| ARC196 | making_significance | The earliest known Caribbean islanders, making large blade tools and ground stone. | Among the earliest known settlers of the Greater Antilles, making large flaked-stone blades and, later, ground-stone tools. | https://en.wikipedia.org/wiki/Banwari_Trace (Trinidad, c. 5000 BCE, predates Casimiroid) |\n| NET047 | start | 500 | 1500 | https://researchportalplus.anu.edu.au/en/publications/the-origins-of-the-kula-ring-archaeological-and-maritime-perspect/ |\n| NET047 | date_note | antiquity debated (c.1,000–1,500 years); ongoing | Irwin et al. 2019 place the Ring's emergence in the last centuries before European contact (start year approximate; older estimates up to c. 1,500 years); ongoing | https://researchportalplus.anu.edu.au/en/publications/the-origins-of-the-kula-ring-archaeological-and-maritime-perspect/ |\n",
"| NET047 | notes | Check antiquity estimate. | Antiquity checked against Irwin et al. 2019 (Archaeology in Oceania). | https://researchportalplus.anu.edu.au/en/publications/the-origins-of-the-kula-ring-archaeological-and-maritime-perspect/ |\n| NET035 | sub_regions | AF-GUI;AF-CEN;AF-SOU;AM-CAR;AM-LAT;AM-EWD;EU-BLC;EU-IBE | AF-GUI;AF-CEN;AF-SOU;AF-SWA;AF-MAD;AM-CAR;AM-LAT;AM-EWD;EU-BLC;EU-IBE | https://www.tandfonline.com/doi/abs/10.1080/0144039X.2012.734112 (Southeast Africa/Indian Ocean embarkations) |\n"
],
"",
"ffcd1cf205f7c7010b30fb4fd2da971dc5670895b52b012b8a4a6b42be163763"
],
[
"modules/F1-histories-of-making/review-logs/REVIEW_LOG_round2_communities.md",
"Review log, round 2: communities",
"review-log",
"F1",
"md",
"",
"",
"",
"",
[
"# Review log, round 2: communities\n\nIndependent fact-check of canon/canon_communities.csv (300 rows, kind `community`).\nBackup of the pre-review file: archive/prereview_round2/canon_communities.csv.\nScope (196 rows): all 115 R1/R2 rows (endonym check); all 33 rows with endonym/self-name \"to verify\"; all 9 rows carrying a \"(rejected exonym)\" flag plus a search for missing ones; the 11 flagged rows (COM184 Druze, COM191 Baekjeong, COM194 Buraku, COM133 Taíno, COM154 Uyghur, COM220 Mahra, COM221 Soqotri, COM206 Pashtun, COM249 Guanches, COM059 Konso, COM068 Haya); a random sample of 50 further rows (seed 20260929; ids in work_r2com/sel.json). Tense check (making_significance) and sensitivity-flag check run over all 300 rows.\nEdit script: work_r2com/apply.py.\n\nFormat: id | field | old | new | source URL\n\nCOM003 | notes | Shali date traditional; endonym to verify. | Shali date traditional; endonym Isiwan verified. | https://en.wikipedia.org/wiki/Siwi_people\nCOM012 | name | Ishelhin | Ishelḥiyen | https://en.wikipedia.org/wiki/Shilha_people\n",
"COM012 | other_names | Chleuh (exonym); Shilha-speakers; Soussi | Chleuh (French rendering of the self-name); Shilha-speakers; Soussi | https://en.wikipedia.org/wiki/Shilha_people\nCOM012 | notes | Endonym form to verify; links: Moroccan Jewish communities row. | Endonym išelḥiyen verified (also written Ishelhien); links: Moroccan Jewish communities row. | https://en.wikipedia.org/wiki/Shilha_people\nCOM019 | other_names | Senara; Senambele (endonym to verify) | Siena; Syénambélé (Senambele); Senoufo (French); Senara (one subgroup) | https://en.wikipedia.org/wiki/Senufo_people\nCOM019 | notes | links: PRA027. Endonym to verify. | links: PRA027. The name Senufo is of external origin and subgroups use their own names; no single endonym, so the widely used name is kept (endonym to verify). | https://en.wikipedia.org/wiki/Senufo_people\nCOM058 | other_names | Gey Usu | Gēy Usuach (Gey Usu, \"people of the city\") | https://en.wikipedia.org/wiki/Harari_people\nCOM058 | notes | Endonym to verify. | Endonym verified: Gēy Usuach. | https://en.wikipedia.org/wiki/Harari_people\n",
"COM059 | other_names | Xonsitta (endonym to verify) | Xonsita (self-name); language Afaa Xonso | https://en.wikipedia.org/wiki/Konso_people\nCOM059 | making_significance | Konso communities build walled terraced towns and carve waka memorial figures, some stolen and later returned. | Konso communities build walled terraced towns and carve waka memorial figures, many of which have been stolen for the art market; Ethiopian customs impounded more than 200 from 1996. | https://mg.co.za/article/2010-01-03-a-museum-to-save-an-ethiopian-tribes-soul/\nCOM059 | notes | Waka thefts documented; return cases to verify. | Endonym Xonsita verified (single t). Seized waka are kept at the Konso Museum; individual returns from abroad still to verify. | https://mg.co.za/article/2010-01-03-a-museum-to-save-an-ethiopian-tribes-soul/\nCOM104 | other_names | Cáuigù | Gáuigú (Kiowa Tribe spelling; also Ǥáuigú, Cáuigú) | https://www.kiowatribe.org/department/kiowa-language-department\n",
"COM104 | notes | links: SCH009. Fort Marion imprisonment: human-flow. Endonym 'Cáuigù' to verify. | links: SCH009. Fort Marion imprisonment: human-flow. Endonym Gáuigú verified with the Kiowa Tribe Language Department. | https://www.kiowatribe.org/department/kiowa-language-department\nCOM104 | making_significance | Kiowa artists kept pictographic calendars and ledger drawings, and the Kiowa Six painters worked in Oklahoma in the 1920s. | Kiowa artists kept pictographic calendars and ledger drawings, the Kiowa Six painters worked in Oklahoma in the 1920s, and Kiowa artists continue to paint today. | https://en.wikipedia.org/wiki/Kiowa\nCOM109 | name | Aniyvwiya | Tsalagi | https://en.wikipedia.org/wiki/Cherokee\nCOM109 | other_names | Cherokee; Tsalagi | Cherokee; Aniyvwiya (\"Principal People\"); Anigiduwagi (\"people of Kituwah\") | https://en.wikipedia.org/wiki/Cherokee\nCOM109 | notes | links: POL065. Trail of Tears: human-flow. Endonym forms to verify. | links: POL065. Trail of Tears: human-flow. Tsalagi (ᏣᎳᎩ) is the standard endonym; Aniyvwiya (ᎠᏂᏴᏫᏯ) and Anigiduwagi also used. | https://en.wikipedia.org/wiki/Cherokee\n",
"COM120 | notes | Endonyms to verify. links: CIV028; PRA048. | Endonyms Ben'zaa (Valley, also Bën Za, \"cloud people\") and Binnizá (Isthmus) as listed by native-land.ca and Wikipedia. links: CIV028; PRA048. | https://native-land.ca/listings/territories/didxazon\nCOM137 | notes | links: PRA051; PRA053; CIV022. 'Runakuna' as a self-name to verify. | links: PRA051; PRA053; CIV022. Runa (\"person\"), plural runakuna, verified as the Quechua self-designation. | https://en.wikipedia.org/wiki/Quechua_people\nCOM138 | other_names | Aymara; Jaqi (endonym to verify) | Aymara; Jaqi (\"human beings\", historical self-designation); Colla | https://www.encyclopedia.com/history/latin-america-and-caribbean/mesoamerican-indigenous-peoples/aymara\nCOM163 | notes | 'Sharwa' endonym to verify. | Endonym Sharwa verified. | https://english.indigenousvoice.com/sherpa\nCOM165 | other_names | Lepcha (exonym) | Lepcha (exonym); Mútuncí Róngkup Rumkup; Rongpa (Sikkimese form) | https://en.wikipedia.org/wiki/Lepcha_people\nCOM165 | notes | Endonym to verify. | Endonym Rongkup verified. | https://en.wikipedia.org/wiki/Lepcha_people\nCOM165 | confidence | low | medium | https://en.wikipedia.org/wiki/Lepcha_people\n",
"COM197 | notes | links: SCH027. Koitur endonym to verify. | links: SCH027. Endonym Kōītōr (Koitur, Koi) verified; Gond is the name used by outsiders. | https://en.wikipedia.org/wiki/Gondi_people\nCOM198 | other_names | Hor ko (endonym to verify) | Hor Hopon (\"child of human\"); Hor | https://en.wikipedia.org/wiki/Santal_people\nCOM198 | notes |  | Endonym Hor Hopon verified. | https://en.wikipedia.org/wiki/Santal_people\nCOM202 | other_names | Ki Hynniewtrep | Ki Hynñiewtrep (\"the seven huts\"; collective self-designation of Khasi-Jaintia peoples) | https://en.wikipedia.org/wiki/Khasi_people\nCOM202 | notes | Endonym to verify. | Hynñiewtrep verified; living root bridges are credited to War Khasi and War-Jaintia communities. | https://en.wikipedia.org/wiki/Khasi_people\nCOM255 | name | Xal'mg | Khalmgud | https://en.wikipedia.org/wiki/Kalmyks\nCOM255 | other_names | Kalmyks | Kalmyks; Хальмгуд; Xaľmg (sing./adj.) | https://en.wikipedia.org/wiki/Kalmyks\nCOM255 | notes | Deportation 1943: human-flow. Endonym spelling to verify. | Deportation 28 December 1943: human-flow. Endonym Хальмгуд (Khalmgud) verified. | https://en.wikipedia.org/wiki/Kalmyks\n",
"COM265 | notes | links: CIV093; MOV106. 'Zenadth Kes' usage to verify. | links: CIV093; MOV106. Zenadth Kes is the Torres Strait Islander name for the region, used by Islanders who reject the colonial name. | https://theconversation.com/zenadth-kes-peoples-long-journey-to-self-determination-in-the-torres-strait-199675\nCOM270 | other_names | Ambulas (endonym to verify) | Ambulas (name of their language) | https://en.wikipedia.org/wiki/Ambulas_language\nCOM270 | notes |  | Endonym to verify: Ambulas is the language name, not attested as a self-name for the people. | https://en.wikipedia.org/wiki/Ambulas_language\nCOM280 | name | Ri-Majeļ | Ri-M̧ajeļ | https://en.wikipedia.org/wiki/Marshall_Islands\nCOM280 | other_names | Marshallese | Marshallese; ri-Majol (popular spelling) | https://www.infomarshallislands.com/language/\nCOM280 | notes | links: INV115; PRA203; PLC409. Test displacement: human-flow. Endonym spelling to verify. | links: INV115; PRA203; PLC409. Test displacement: human-flow. M̧ajeļ is the Marshallese name of the islands (standard orthography); ri- = person of. | https://en.wikipedia.org/wiki/Marshall_Islands\n",
"COM291 | notes | links: POL084; POL085; MKR088; PRA199. Endonym to verify. | links: POL084; POL085; MKR088; PRA199. Kakai Tonga (\"Tongan people\") in use, e.g. Waikato thesis title \"Kakai Tonga 'i Okalani\". | https://researchcommons.waikato.ac.nz/entities/publication/95d8ed10-9bdb-4990-ada4-575357c182dc\nCOM297 | name | Enana | ʻEnana | https://en.wikipedia.org/wiki/Marquesas_Islands\nCOM297 | other_names | Marquesans; Enata | Marquesans; ʻEnata (South Marquesan) | https://en.wikipedia.org/wiki/Marquesas_Islands\nCOM192 | other_names | Aynu; Utari (term used by some organisations) | Aynu; Utari (\"friend\"; used by the Hokkaido Utari Association 1961–2009, now the Ainu Association of Hokkaido) | https://en.wikipedia.org/wiki/Ainu_Association_of_Hokkaido\nCOM139 | other_names | Mapuche; Araucanian (exonym) | Mapuche; Araucanian (colonial exonym; considered pejorative by some) | https://en.wikipedia.org/wiki/Mapuche\nCOM093 | other_names | Kwakiutl (exonym, one community's name) | Kwakiutl (from Kwagu'ł, one community at Fort Rupert, formerly applied to all) | https://en.wikipedia.org/wiki/Kwakwaka%CA%BCwakw\nCOM182 | name | Ma'dan | ʿArab al-Ahwār | https://en.wikipedia.org/wiki/Marsh_Arabs\n",
"COM182 | other_names | Marsh Arabs | Marsh Arabs; Ahwaris; Ma'dan (rejected exonym: used disparagingly by desert tribes, often considered derogatory today) | https://en.wikipedia.org/wiki/Marsh_Arabs\nCOM182 | making_significance | Ma'dan build mudhif reed guesthouses and reed boats (mashuf) in the southern Iraqi marshes, which were drained in the 1990s. | Marsh Arab communities build mudhif reed guesthouses and reed boats (mashuf) in the southern Iraqi marshes, which were drained in the 1990s. | https://en.wikipedia.org/wiki/Marsh_Arabs\nCOM182 | notes | Drainage and displacement: human-flow. | Drainage and displacement: human-flow. Name changed from Ma'dan, often considered derogatory. | https://cinmena.org/nations/ma%CA%BBdan-or-marsh-arabs/\nCOM184 | name | Muwahhidun | Muwaḥḥidūn | https://en.wikipedia.org/wiki/Druze\nCOM184 | other_names | Druze | Druze (from ad-Darazī, whom the faith regards as a heretic; widely used, including by the community) | https://en.wikipedia.org/wiki/Druze\n",
"COM184 | making_significance | Druze communities in Lebanon, Syria and Israel keep distinctive dress and build stone village houses and khalwa prayer houses. | Druze communities in Lebanon, Syria, Israel and Jordan keep distinctive religious dress and build stone village houses and khalwa prayer houses. | https://en.wikipedia.org/wiki/Druze\nCOM184 | confidence | low | medium | https://en.wikipedia.org/wiki/Druze\nCOM184 | notes | Endonym 'al-Muwahhidun' (the monotheists); making significance is thin; the brief marked this with a query. | Endonym al-Muwaḥḥidūn (\"the monotheists\") verified; da'wa opened 30 May 1017. Making significance is modest. | https://en.wikipedia.org/wiki/Druze\nCOM191 | other_names |  | Paekchŏng (McCune–Reischauer); a status label imposed by the state, with no self-chosen name | https://en.wikipedia.org/wiki/Baekjeong\nCOM191 | date_note | hereditary outcaste status under Joseon; legally abolished 1894 | Joseon status category formed under Sejong (r. 1418–1450), who grouped outcaste groups under this name; legally abolished 1894 (Kabo Reform); discrimination continued into the 20th c. | https://en.wikipedia.org/wiki/Baekjeong\n",
"COM191 | making_significance | Baekjeong were a hereditary low-status group of butchers, leatherworkers and willow-basket makers in Joseon Korea, and their descendants organised the Hyeongpyeongsa movement in 1923. | People classed as baekjeong, a hereditary outcaste status in Joseon Korea, worked as butchers, tanners and willow-basket makers, and in 1923 they founded the Hyeongpyeongsa in Jinju to end the status and its contemptuous names. | https://en.wikipedia.org/wiki/Baekjeong\nCOM191 | defined_by | the community; ethnographic and museum usage | the Joseon state (legal status category); historians | https://en.wikipedia.org/wiki/Baekjeong\nCOM191 | confidence | low | medium | https://en.wikipedia.org/wiki/Baekjeong\nCOM191 | notes | Historical status group rather than self-named people; verify framing. | Kind note: a hereditary status imposed by the state and enforced by discrimination, not a people or ethnic group; write \"people classed as baekjeong\". | https://en.wikipedia.org/wiki/Baekjeong\n",
"COM194 | other_names | Burakumin (term many find stigmatising) | buraku; hisabetsu buraku (\"discriminated-against communities\"); Burakumin (rejected term: carries strong discriminatory connotations) | https://en.wikipedia.org/wiki/Burakumin\nCOM194 | making_significance | Buraku communities, historically assigned to leather and hide work, include makers of taiko drums and leather goods, and the Buraku Liberation League campaigns against discrimination. | Buraku communities, descended from people assigned to hide, leather and other stigmatised work under Edo-period status rules, include makers of taiko drums and leather goods, and the Buraku Liberation League campaigns against the discrimination that persists. | https://en.wikipedia.org/wiki/Burakumin\nCOM194 | date_note | outcaste status formalised in Edo period; abolished legally 1871 | outcaste status formalised in Edo period; abolished legally by the Liberation Edict of 28 August 1871; discrimination persists | https://en.wikipedia.org/wiki/Burakumin\n",
"COM194 | defined_by | the community | the Edo-period status system (imposed); the Buraku Liberation League and community organisations (self-description) | https://en.wikipedia.org/wiki/Burakumin\nCOM194 | confidence | low | medium | https://en.wikipedia.org/wiki/Burakumin\nCOM194 | notes | Handle with care: status group, not an ethnic people. | Kind note: a status group created by discrimination, not an ethnic group or people; members are ethnically Japanese. Use \"buraku\" or \"hisabetsu buraku\". Handle with care. | https://en.wikipedia.org/wiki/Burakumin\nCOM133 | other_names | Taíno; Boricua | Taíno; Boricua (name for Puerto Ricans generally, from Borikén) | https://en.wikipedia.org/wiki/Boricua\n",
"COM133 | making_significance | Taíno descendants revive making including cemí carving, and descent is debated. | People who identify as Taíno in Puerto Rico, the Dominican Republic, Cuba and the diaspora carve cemís and duhos as part of a heritage resurgence; many see unbroken descent, citing Indigenous ancestry in present Caribbean DNA and survivals in crops, food and vocabulary, while others hold that the Taíno did not survive as a distinct people after the 16th century. | https://www.smithsonianmag.com/blogs/smithsonian-latino-center/2019/10/25/funeral-caribbeans-native-extinction-hypothesis/\nCOM133 | confidence | low | medium | https://www.smithsonianmag.com/blogs/smithsonian-latino-center/2018/10/03/renaissance-native-caribbean-people-taino-ethnogenesis/\nCOM133 | notes | links: CIV030; POL055. Continuity is debated. | links: CIV030; POL055. Continuity is debated: both views stated (Smithsonian NMAI \"Taíno: Native Heritage and Identity in the Caribbean\" takes the continuity view). | https://www.si.edu/exhibitions/taino-native-heritage-and-identity-caribbean-event-exhib-6313\n",
"COM154 | date_note | modern collective ethnonym adopted 1921; Turkic Uyghur states from 8th c. are separate groupings | modern ethnonym adopted at a 1921 Tashkent meeting of Turkic intellectuals from the Tarim Basin and made official in Xinjiang in 1934 (Sheng Shicai); the people and their oasis identities are older; the Uyghur Khaganate (8th–9th c.) is a separate grouping | https://en.wikipedia.org/wiki/Uyghurs\nCOM206 | making_significance | Pashtun communities make embroidered dress and the painted and decorated trucks associated with Pakistan. | Pashtun communities make embroidered dress, and Peshawar and Swat, in the Pashtun north-west, are among the centres of Pakistani truck decoration alongside Karachi, Rawalpindi, Quetta and Lahore. | https://en.wikipedia.org/wiki/Truck_art_in_South_Asia\nCOM206 | confidence | low | medium | https://en.wikipedia.org/wiki/Truck_art_in_South_Asia\nCOM206 | notes | Included with a query in the brief; making claims modest. | Endonym Pax̌tānə (Pashtana, pl.) standard. Truck art is regional and multi-ethnic; not attributed to Pashtuns as a whole. | https://en.wikipedia.org/wiki/Truck_art_in_South_Asia\n",
"COM220 | making_significance | Mahra communities of eastern Yemen and Dhofar build sewn and planked boats, herd camels and frankincense lands, and make silver. | Mahra communities of eastern Yemen and Dhofar live from camel herding and Arabian Sea fishing, harvested and carried frankincense into the 20th c., and include noted navigators of Indian Ocean trade. | https://whenmelodiesgather.supdigital.org/wmg/geography\nCOM220 | materials_techniques | silver;leather;boat building | camel herding;fishing;frankincense harvesting;navigation | https://whenmelodiesgather.supdigital.org/wmg/geography\nCOM220 | object_types | boat;camel gear;jewellery | boat;camel gear;frankincense | https://whenmelodiesgather.supdigital.org/wmg/geography\nCOM220 | confidence | low | medium | https://whenmelodiesgather.supdigital.org/wmg/geography\nCOM220 | notes |  | Earlier claims of sewn boats and silverwork unverified and removed. Also Mahris (al-Mahra tribe), found also on Socotra and in Oman. | https://en.wikipedia.org/wiki/Mehri_people\nCOM221 | confidence | low | medium | https://www.soqotraculturalheritage.org/crafts/\n",
"COM221 | notes |  | Pottery made only by women; weaving by women on a horizontal ground loom; dragon's-blood resin applied to pots after firing (Soqotra Heritage Project). | https://www.soqotraculturalheritage.org/crafts/\nCOM249 | date_note | settlement c. 1st millennium BCE; conquest 1402–1496 | settlement date debated: 1st millennium BCE (older dates, e.g. Cueva de los Guanches) or 1st–4th c. CE (Santana et al., PNAS 2024); Castilian conquest 1402–1496 | https://popular-archaeology.com/article/human-colonization-of-the-canary-islands/\nCOM249 | making_significance | The Indigenous islanders made hand-built pottery, pintaderas stamps and goatskin clothing, and many were enslaved after the conquest. | The Indigenous islanders made hand-built pottery, pintadera stamps and goatskin clothing, and during the Castilian conquest many were killed, enslaved and deported. | https://en.wikipedia.org/wiki/Guanches\nCOM249 | confidence | low | medium | https://en.wikipedia.org/wiki/Guanches\n",
"COM249 | notes | Amazigh-related; mummies in museums; enslavement: human-flow. | Amazigh-related; \"Guanche\" first meant the people of Tenerife and is now used for the whole archipelago; mummies in museums; enslavement: human-flow; Guanche ancestry survives in present Canarians. | https://en.wikipedia.org/wiki/Guanches\nCOM068 | date_note | iron smelting at Kagera dated to early 1st millennium BCE by some studies (contested) | Early Iron Age smelting in Buhaya (Kagera) dated to the mid to later 1st millennium BCE (steel-making c. 2,300–2,000 years ago); precise dates debated | https://en.wikipedia.org/wiki/Iron_metallurgy_in_Africa\nCOM068 | making_significance | Haya smelters reconstructed bloomery furnaces for archaeologist Peter Schmidt in the 1970s, a case of living knowledge meeting archaeology. | Haya elders in Kagera, north-west Tanzania, rebuilt and fired bloomery furnaces for archaeologist Peter Schmidt in the 1970s, a case of living knowledge meeting archaeology, and Haya communities hold this smelting history in oral tradition. | https://archaeologydataservice.ac.uk/archives/view/assemblage/html/4/4schmidt.html\n",
"COM077 | making_significance | Herero women wear and make the long Victorian-derived dress and horned headdress, a response to German colonial rule. | Herero women make and wear long dresses adopted from late-19th-century German missionary fashion, now in bright prints, with the otjikaiva headdress shaped like cattle horns. | https://en.wikipedia.org/wiki/Herero_people\nCOM299 | start | -500 | -700 | https://en.wikipedia.org/wiki/Pontic_Greeks\nCOM190 | making_significance | Koryo-saram, deported to Kazakhstan and Uzbekistan in 1937, adapted Korean food, dress and farming tools to Central Asia. | Koryo-saram, deported to Kazakhstan and Uzbekistan in 1937, adapted Korean food, dress and farming tools to Central Asia, and dishes such as morkovcha are now part of post-Soviet cooking. | https://en.wikipedia.org/wiki/Koryo-saram\nCOM187 | making_significance | Adyghe gold embroidery and silver belt work, carried to Ottoman lands after the 1864 expulsion. | Adyghe women make gold embroidery and smiths make silver belt work, crafts carried to Ottoman lands after the 1864 expulsion. | https://en.wikipedia.org/wiki/Circassians\n",
"COM015 | making_significance | Jewish silversmiths, embroiderers and bookmakers were central to Moroccan jewellery and textile production until emigration. | Jewish silversmiths, embroiderers and bookmakers were central to Moroccan jewellery and textile production until emigration, and a community of about 1,000 remains in Morocco. | https://en.wikipedia.org/wiki/History_of_the_Jews_in_Morocco\nCOM065 | making_significance | Kamba carvers developed a large export carving industry from the early 20th c. | Kamba carvers have run a large export carving industry since the early 20th c. and remain known for woodcarving. | https://en.wikipedia.org/wiki/Kamba_people\nCOM214 | making_significance | Bukharan Jewish dyers and embroiderers were central to ikat and suzani trades in Bukhara. | Bukharan Jewish dyers and embroiderers were central to ikat and suzani trades in Bukhara, and most of the community now lives in Israel and the United States. | https://en.wikipedia.org/wiki/Bukharan_Jews\n",
"COM248 | making_significance | Sephardic communities made illuminated Hebrew manuscripts in Iberia and later ritual silver and textiles across the Ottoman world. | Sephardic communities made illuminated Hebrew manuscripts in Iberia and later ritual silver and textiles across the Ottoman world, and Sephardic communities live today chiefly in Israel, France and the Americas. | https://en.wikipedia.org/wiki/Sephardic_Jews\nCOM284 | making_significance | Yapese voyagers quarried rai stone disks on Palau and brought them home as valuables. | Yapese voyagers quarried rai stone disks on Palau and brought them home as valuables, and rai are still exchanged in marriages, inheritance and other important transactions. | https://en.wikipedia.org/wiki/Rai_stones\n"
],
"",
"9727adecbdd600b21b3f72927c42182b56a538b5df306cb93de7aa2bc9bcbff8"
],
[
"modules/F1-histories-of-making/review-logs/REVIEW_LOG_round2_people.md",
"Review log, round 2: canon_people.csv and blindmap/missing_entities.csv (independent fact-check)",
"review-log",
"F1",
"md",
"",
"",
"",
"",
[
"# Review log, round 2: canon_people.csv and blindmap/missing_entities.csv (independent fact-check)\n\nOriginals backed up to archive/prereview_round2/. Format: id | field | old | new | source URL\n\n| id | field | old | new | source URL |\n|---|---|---|---|---|\n| PER006 | notes | Tomb contents are divided mainly between Cairo and the Met; verify which pieces are in the Met. links: MKR090 | Verified round 2: the Met holds about 29 items from TT1, including the coffin sets of Iyneferti and of Khonsu; Sennedjem's own coffin set and sarcophagus are in Cairo (National Museum of Egyptian Civilization). links: MKR090 | https://en.wikipedia.org/wiki/TT1 ; https://www.metmuseum.org/art/collection/search/551783 |\n| PER027 | start | 1964 | 1981 | https://www.ens-lyon.fr/en/article/research/abdel-kader-haidara-director-timbuktu-library |\n| PER027 | date_note | born c. 1964; living | fl.; took charge of his family library in 1981; birth year not verified; living | https://www.ens-lyon.fr/en/article/research/abdel-kader-haidara-director-timbuktu-library |\n",
"| PER032 | making_significance | The Gbari potter from Kwali made hand-built water pots and then, at the Abuja Pottery Training Centre, glazed stoneware that was shown in London and New York. | The Gbari potter from Kwali made hand-built water pots and then, at the Abuja Pottery Training Centre, glazed stoneware that was shown in London (Berkeley Galleries, 1958–62), Paris and Washington. | https://post.moma.org/pots-mastery-and-the-enduring-legacy-of-ladi-dosei-kwali/ |\n| PER059 | start | 1978 | 2019 | https://en.wikipedia.org/wiki/Nana_Oforiatta_Ayim |\n| PER059 | date_note | born c. 1978; living | fl.; curated Ghana's first Venice Biennale pavilion in 2019; birth year not verified; living | https://en.wikipedia.org/wiki/Nana_Oforiatta_Ayim |\n| PER059 | notes | Verify birth year. | Birth year could not be verified from a reliable source in the round-2 check, so a floruit is given. | https://en.wikipedia.org/wiki/Nana_Oforiatta_Ayim |\n",
"| PER067 | date_note | fl.; 16th century, dates uncertain | fl.; dates disputed: often given as reign c. 1576–1610 (16th century), but the Kano Chronicle makes her a contemporary of Muhammad Dauda (r. 1421–38) | https://en.wikipedia.org/wiki/Queen_Amina |\n| PER068 | date_note | born c. 1945; living | born 1945; living | https://awarewomenartists.com/en/artiste/reinata-sadimba/ |\n| PER068 | notes | Verify birth year. links: STY177 | Birth year verified (AWARE). links: STY177 | https://awarewomenartists.com/en/artiste/reinata-sadimba/ |\n| PER073 | start | 700 | 750 | https://www.artic.edu/artworks/126858/water-lily-vessel |\n| PER073 | end | 780 | 810 | https://www.academia.edu/143756887/A_Royal_Artist_at_Naranjo_Notes_on_a_Late_Classic_Maya_Cylinder_Vessel |\n| PER073 | date_note | fl.; 8th century, approximate | fl.; mid-to-late 8th century (Art Institute of Chicago); his father acceded at Naranjo in 765 and one study puts his birth in the 770s, so activity may run to c. 800 | https://www.artic.edu/artworks/126858/water-lily-vessel ; https://www.academia.edu/143756887/A_Royal_Artist_at_Naranjo_Notes_on_a_Late_Classic_Maya_Cylinder_Vessel |\n",
"| PER073 | notes | Signature readings and dates from epigraphers; verify. links: MKR021 | Verified round 2: the Water-Lily Vessel inscription names him, his royal Naranjo lineage and his parents; his mother was a lady of Yaxha. links: MKR021 | https://www.artic.edu/artworks/126858/water-lily-vessel ; https://www.academia.edu/143756887/A_Royal_Artist_at_Naranjo_Notes_on_a_Late_Classic_Maya_Cylinder_Vessel |\n| PER087 | end | (empty) | 2026 | https://www.elfinanciero.com.mx/entretenimiento/2026/03/05/muere-pedro-friedeberg-referente-del-surrealismo-en-mexico-a-los-90-anos-quien-era/ |\n| PER087 | date_note | born 1936; living | born 11 January 1936 in Florence; died 5 March 2026 | https://www.elfinanciero.com.mx/entretenimiento/2026/03/05/muere-pedro-friedeberg-referente-del-surrealismo-en-mexico-a-los-90-anos-quien-era/ |\n| PER087 | sensitivity | living-community | none | https://www.elfinanciero.com.mx/entretenimiento/2026/03/05/muere-pedro-friedeberg-referente-del-surrealismo-en-mexico-a-los-90-anos-quien-era/ |\n| PER120 | other_names | Qwii.aang | Kwii.aang | https://americanindian.si.edu/exhibitions/infinityofnations/northwest-coast/196110.html |\n",
"| PER120 | date_note | approximate | born c. 1858 (Museum of Anthropology, UBC; some sources give c. 1842); died 1926 | https://collection-online.moa.ubc.ca/search/person?person=799&tab=biography |\n| PER120 | notes | Verify dates. | Dates checked round 2: MOA gives 1858–1926; birth year is disputed. | https://collection-online.moa.ubc.ca/search/person?person=799&tab=biography |\n| PER180 | start | 1966 | 1967 | https://en.wikipedia.org/wiki/Lu_Wenyu |\n| PER180 | date_note | born c. 1966; living | born 1967; living | https://en.wikipedia.org/wiki/Lu_Wenyu |\n| PER180 | notes | Verify birth year. | Birth year 1967 per Wikipedia and Bloomsbury Encyclopedia; some web sources give 1966. | https://en.wikipedia.org/wiki/Lu_Wenyu |\n| PER236 | making_significance | One of the few named women painters at the Mughal court, known from a signed portrait of Shah Tahmasp copied from an earlier image. | One of the few named women painters at the Mughal court, known from an early 17th-century portrait of Shah Tahmasp (V&A) whose inscription names her as its painter. | https://collections.vam.ac.uk/item/O405633/shah-tahmasp-of-iran-painting-sahifa-banu/ |\n",
"| PER264 | making_significance | The Indian textile designer worked with handloom weavers and revived techniques in the Weavers' Service Centres. | The Indian textile designer, trained in weaving at Cranbrook, designed for Bombay Dyeing, helped set up textile design at the National Institute of Design (1966) and researched kalamkari printing at Masulipatnam, bringing disused carved blocks back into use. | https://en.wikipedia.org/wiki/Nelly_Sethna |\n| PER264 | leaves_out | the weavers who made her designs | the weavers and kalamkari printers who made her designs | https://en.wikipedia.org/wiki/Nelly_Sethna |\n| PER264 | notes | Verify details. | Round 2: the earlier claim about Weavers' Service Centres could not be sourced and was replaced. | https://en.wikipedia.org/wiki/Nelly_Sethna |\n| PER303 | name | Mariam al-Ijliya | al-ʿIjliyya bint al-ʿIjliyy | https://en.wikipedia.org/wiki/Mariam_al-Asturlabi |\n| PER303 | other_names | al-Asturlabiyya | Mariam al-Ijliya; Mariam al-Asturlabiyya (modern names) | https://en.wikipedia.org/wiki/Mariam_al-Asturlabi |\n",
"| PER303 | making_significance | Ibn al-Nadim names her as an astrolabe maker at the court of Sayf al-Dawla in Aleppo. | Ibn al-Nadim names her, the daughter of the astrolabe maker al-ʿIjliyy and like him a pupil of Nastulus, as an astrolabe maker employed by Sayf al-Dawla in Aleppo. | https://en.wikipedia.org/wiki/Mariam_al-Asturlabi |\n| PER303 | notes | Known from one source. | Known from one source (Ibn al-Nadim, Fihrist); the first name 'Mariam' is a modern addition not found there. | https://en.wikipedia.org/wiki/Mariam_al-Asturlabi |\n| PER320 | start | 1500 | 1515 | https://en.wikipedia.org/wiki/%C5%9Eahkulu_(painter) |\n| PER320 | date_note | died 1555–56 | fl.; brought to Istanbul 1515; died by 1555–56; birth date unknown | https://en.wikipedia.org/wiki/%C5%9Eahkulu_(painter) |\n| PER320 | making_significance | The Tabriz-born court painter in Istanbul led the saz style of feathery leaves and fantastic creatures used in tiles and textiles. | The Iranian court painter, trained in Tabriz and brought to Istanbul in 1515, led the saz style of feathery leaves and fantastic creatures used in tiles and textiles. | https://en.wikipedia.org/wiki/%C5%9Eahkulu_(painter) |\n",
"| PER331 | making_significance | The British-born painter in Baghdad worked with Jewad Selim and taught architectural drawing. | The British-born painter married the sculptor Jewad Selim, taught drawing to architecture students at Baghdad University in the 1960s and painted the city's vernacular buildings. | https://en.wikipedia.org/wiki/Lorna_Selim |\n| PER339 | making_significance | The Emirati painter is among the first women from the Emirates with an art doctorate, using light and colour drawn from henna and textiles. | The Emirati painter was the first Emirati woman to receive a government scholarship to study art abroad (1977), later took a doctorate in Cairo (2001), and works with colour, light and Emirati settings and folklore. | https://en.wikipedia.org/wiki/Najat_Makki |\n| PER339 | notes | Verify biography. | Biography checked round 2 (Wikipedia). | https://en.wikipedia.org/wiki/Najat_Makki |\n",
"| PER380 | making_significance | The Arretine pottery owner's stamps name workers such as Tigranus and Bargathes, enslaved or freed men who later ran the workshop themselves. | The Arretine pottery's stamps show the workshop passing to men who had worked in it: first Perennius's freedman Marcus Perennius Tigranus, then Marcus Perennius Bargathes. | https://www.academia.edu/8587773/Stamps_on_Italian_Sigillata_and_the_Renaissance_of_Aptera_Crete ; https://www.metmuseum.org/art/collection/search/248324 |\n| PER380 | notes | Verify stamp readings and status of Tigranus and Bargathes. links: POL120 | Round 2: Tigranus is described as a freedman of M. Perennius; Bargathes followed him as owner (Phase 3, c. 25–30 CE per Porten Palange). Earlier enslaved status is likely but not explicitly sourced here. links: POL120 | https://www.academia.edu/8587773/Stamps_on_Italian_Sigillata_and_the_Renaissance_of_Aptera_Crete ; https://www.metmuseum.org/art/collection/search/248324 |\n| PER463 | date_note | born c. 1948; living | born 1948; living | https://www.idref.fr/030828783 |\n| PER463 | notes | Verify birth year. | Birth year verified (IdRef authority record). | https://www.idref.fr/030828783 |\n",
"| PER466 | end | (empty) | 2025 | https://anthropology.berkeley.edu/memoriam-professor-nelson-hh-graburn-1936-2025 |\n| PER466 | date_note | born 1936; living | born 1936; died 2025 | https://anthropology.berkeley.edu/memoriam-professor-nelson-hh-graburn-1936-2025 |\n| PER466 | sensitivity | living-community | none | https://anthropology.berkeley.edu/memoriam-professor-nelson-hh-graburn-1936-2025 |\n| PER476 | start | 1947 | 1999 | https://www.anu.edu.au/events/beyond-speculation-design-in-the-epoch-of-unsettlement-with-tony-fry |\n| PER476 | date_note | born c. 1947; living | fl.; Defuturing published 1999; birth year not verified; living | https://www.anu.edu.au/events/beyond-speculation-design-in-the-epoch-of-unsettlement-with-tony-fry |\n| PER476 | making_significance | The British-born design theorist, working in Australia, argued in Defuturing (1999) that design often destroys futures. | The design theorist, working in Australia, argued in Defuturing (1999) that design often destroys futures. | https://www.anu.edu.au/events/beyond-speculation-design-in-the-epoch-of-unsettlement-with-tony-fry |\n",
"| PER476 | notes | Verify birth year. | Birth year and birthplace could not be verified in the round-2 check; floruit given and \"British-born\" removed. | https://www.anu.edu.au/events/beyond-speculation-design-in-the-epoch-of-unsettlement-with-tony-fry |\n| PER274 | notes | Verify the extent of her role in the Jepara trade. | Round 2: sources confirm she marketed Jepara carving to Semarang, Batavia and the Netherlands and worked with the Oost en West association; the scale of her role beyond that is less documented. | https://www.atlantis-press.com/proceedings/icskse-18/125909580 |\n| PER296 | notes | Verify extent of reconstructions. | Round 2: an early reconstruction of Puabi's headdress by Katharine Woolley is documented (ISAW exhibition). | https://isaw.nyu.edu/exhibitions/aesthetics/checklist/99-early-reconstruction-of-puabi2019s-headdress-by-katharine-woolley/view |\n| PER340 | notes | Verify death year. | Death year 2024 verified. | https://artreview.com/safeya-binzagr-pioneer-of-saudi-art-1940-2024/ |\n\n## Scope and results\n\n",
"- Priority set (canon_people): 124 rows = every R1/R2 row, every medium/low-confidence row and every living-community row (includes all 14 flagged items). Rows with substantive errors: 16 (PER027, PER032, PER059, PER067, PER073, PER087, PER120, PER180, PER236, PER264, PER303, PER331, PER339, PER380, PER466, PER476), about 13%. Notes-only verification updates: PER006, PER068, PER274, PER296, PER340, PER463.\n- Random sample, 50 further people rows (seed 20260929; ids in scratchpad/r2_sample_people.txt): 1 row wrong (PER320 Şahkulu: \"Tabriz-born\" and an invented 1500 start date), 2%.\n- Random sample, 30 missing_entities rows (seed 20260929; ids in scratchpad/r2_sample_missing.txt): 0 errors found; missing_entities.csv not changed.\n- Checked and left unchanged: Leizu (PER159) and Lu Ban (PER160), both framed as legend and consistent with sources; Amina's wall attribution; Safeya Binzagr 1940–2024; Whang-od still living (turned 109 in Feb 2026); Esther Mahlangu, Mary Lee Bendolph and other living people's birth years.\n",
"- Error types: two people listed as living had died (Friedeberg 2026, Graburn 2025); unsourced or wrong birth years for living people (softened to a floruit where they could not be sourced); unsupported biographical claims (Sethna, Makki, Sahifa Banu \"copied\", Kwali \"New York\", Fry \"British-born\", Şahkulu \"Tabriz-born\"); a wrong personal name (al-ʿIjliyya, \"Mariam\" is modern); wrong date range (Aj Maxam); a variant spelling of a Haida name.\n- Not changed, but a verifier may want to look again: PER392 Dürer's complaint to Venice about Marcantonio rests mainly on Vasari's account; PER108 note on Maria Martinez signing other potters' pots is still marked \"verify\".\n"
],
"",
"afb9dd9d71f84d8e237df767c575d8bf38529fc112fe6a1d1a26dfa1614777ad"
]
]$cwb$::jsonb) x
on conflict ("path") do nothing;
